### ISSUE TITLE
question: editing song.played count

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1001]
I'm looking at merging my last.fm and rhythmbox stats into ampache, specifically the play count with a view to looking at count in the search instead of just is/isn't played.

If i set played are there other parts of the database like a time played that might be affected as well?

I have the file names in rhythmbox's database and i have the play time in last.fm's data so i could merge both.

**Comment by Afterster** [comment]
I'm not a rhythmbox neither a lastfm user so I might not be the ideal person for the answer.
On Interface settings, you can enabled `Show # played` which will display a play count calculated dynamically from `object_count` table (each song play add an entry on this table).

**Comment by lachlan-00** [comment]
Object count sounds more up my alley. I'll look at that.

**Comment by lachlan-00** [comment]
Is the played column meant to be a boolean? (0=not and 1=played)

**Comment by Afterster** [comment]
Yes about the played column, it's boolean.

**Comment by lachlan-00** [comment]
Thanks, then that makes object_count the answer. Thanks for helping.

**Comment by lachlan-00** [comment]
if anyone is interested in this i've finished my import script.
https://github.com/lachlan-00/ampache-scripts

I'm going to look at turning ampache into an alternative last.fm in the future.
