### ISSUE TITLE
Regression with commit 5124a5ed4c19fec8f525b248fc6c2e81964e8107

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1004]
I can no longer view artist information since commit 5124a5ed4c19fec8f525b248fc6c2e81964e8107. Reverting to 657ff21e43369cd405e29f4f12d0b3d1fc3f1dea resolves this.

**Comment by stebe** [comment]
This is all I see in the logs.

2015-11-07 10:43:00 [stebe] (session) -> Session created: 792cc5dd83cdec814dadd9317795ef58
2015-11-07 10:43:00 [stebe] (browse) -> Show objects called for type {album}

If I disable AJAX page load the information is displayed.

**Comment by Afterster** [comment]
Yep, missing brace, thanks. Fixed.
