### ISSUE TITLE
Search by "Missing artist" is not working

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#1006]
Hey guys,

When searching whether for an artist that exists or not in the library, it leads to an "Internal server error" when selecting the "missing artist" entry in the global search menu.

I can reproduce it every time.

Once again, thanx for your work !

Last ampache pull today : c68eb17
Nginx : 1.8.0
Php : 5.6.15
MariaDB : 10.0.22

**Comment by DanielMaly** [comment]
This is a bug in mikealmond/MusicBrainz, should be fixed by https://github.com/mikealmond/MusicBrainz/pull/19

**Comment by Afterster** [comment]
Thank you @Jucgshu and @DanielMaly.
I updated MusicBrainz library dependency to latest commit. Please pull latest change and run `composer install`.
