### ISSUE TITLE
Can't add rule based on favorites with smart playlists

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#1007]
Hey guys,

For reference, looks like the option is missing : we cannot add smart playlists based on the fav option. Rating option exists but is cross users, whereas fav is personal.

As always, big up for your work !

**Comment by helmut72** [comment]
any news regarding this feature?

**Comment by wagnered** [comment]
@helmut72,

Since you bumped this to my attention, I decided  to stop my work on Ampache/Laravel and take a look at what was involved in make the changes. I just pushed some changes to the 3.8.5-develop branch .  Now "Favorite Artists" and "Favorite Albums" are included on the search list.

**Comment by Jucgshu** [comment]
Can we bump for more? Joke aside, can you point how to use it? I tried with "fav artist IS true OR 1" with no luck.

Fav songs would be awesome as well.

Keep up the good work @wagnered ;-)

**Comment by wagnered** [comment]
Sorry about that @Jucgshu

Use "contains" and leave text box empty for all favorite artists or
enter part of the artist name for particular artist.

Same way for albums.


There is no easy way to remove the other entries from the list.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Jucgshu** [comment]
No worries mate ;-)

So apparently, the fav artists feature returns artists that are not favs of mine. Actually, I have this old habbit of fav-ing songs (not artists nor albums), so I fav'ed an artist just to test. And it returns 1632 pages where it should return only 7.

**Comment by helmut72** [comment]
Just want to have fave songs as a smart playlist to export my faves from Ampache to have an easy backup.

**Comment by wagnered** [comment]
@Jucgshu  OK, I'll give it a look,  I only had one user on my test installation.  I'll add more and see what happens.

@helmut72  If you would like, I will add another list entry "Favorite Songs." to be searched the same way favorite artist and favorite albums are searched.

**Comment by helmut72** [comment]
Search isn't needed. Faves are the only data I generate in Ampache and I want to have an easy backup file of this data. This is the main purpose.

But I just see that even a normal playlist can't be exported/imported. I think I mixed this up with a feature from Subsonic. I just switch between Ampache and Subsonic to much and can't decide what's better.

**Comment by wagnered** [comment]
@Jucgshu,

I removed the "favorite artists" and "favorite albums" from the list and renamed "favorite songs" to "favorites".  The smart playlists based on favorites will now include only your favorites but still can viewed by the public.

**Comment by Jucgshu** [comment]
Yup, that's working now. Looks like we can close this issue?

Big up for the fix!
