### ISSUE TITLE
Can't search

### ISSUE THREAD

**Issue by NotDrexin** [ampache/ampache#1008]
Running ampache 3.8. I can't browse songs, and unless i search for a song name directly, and there is only like 4 results, it gives an internal server error. I have ~200gb of music, but not sure if that is the cause, because i ran earlier ampache and it worked fine. I tried to get an error log, but after enabling it it still won't make one.
apache2 error log:
Before error log enabled
```
[Wed Nov 11 21:06:09.535730 2015] [:error] [pid 2230] [client 73.149.44.88:50113] PHP Fatal error:  Call to a member function quote() on a non-object in /var/www/ampache/lib/class/dba.class.php on line 131, referer: http://home.acapa.tk:8080/index.php
```
after
```
[Wed Nov 11 21:11:52.931460 2015] [:error] [pid 2251] [client 73.149.44.88:50404] PHP Warning:  error_log(/var/log/ampache/ampache.20151111.log): failed to open stream: Permission denied in /var/www/ampache/lib/log.lib.php on line 51, referer: http://home.acapa.tk:8080/index.php

```

**Comment by Afterster** [comment]
About your first error, could you check with latest develop branch to be sure it is not already fixed?
About your second error, this is because the process running ampache (apache?) doesn't have enough permissions to write on /var/log/ampache/ampache.20151111.log.

**Comment by Afterster** [comment]
After further investigation, similar to another issue fixed on develop branch. Feel free to comment if it is not the case.
