### ISSUE TITLE
Ampache fails to import .m3u playlists into catalog

### ISSUE THREAD

**Issue by jaydoes** [ampache/ampache#101]
Ampache 3.6-alpha6+FUTURE on Ubuntu 13.10 (Saucy).

I have tried Add, Verify, Clean, Update, and even deleted & re-added the same as a new catalog.  "Build Playlists from m3u Files" is selected.

I get many of these in the logs:
...
2014-01-12 06:05:38 [jay-work](read) -> Starting work on CD Rips.m3u inside /mnt/raid/Music/CD Rips
2014-01-12 06:05:38 [jay-work](read) -> /mnt/raid/Music/CD Rips/CD Rips.m3u ignored, non-audio file or 0 bytes
...

And, still, browse.php?action=playlist returns "Not Enough Data".

**Comment by kmchen13** [comment]
This happened to me after moving playlists from a folder to another.
That's because playlists are writen in relative path format. The solution I used were to edit the .m3U whitch is a simple .xml file and change all the paths according to the directory where the playlist belongs
