### ISSUE TITLE
Ampache rename on upload

### ISSUE THREAD

**Issue by thefirstofthe300** [ampache/ampache#1010]
I am not sure if this is already implemented and I am too blind to see it or not.  I just uploaded some music via the upload mechanism and all of the music was dumped in the root folder without any folder structure at all.  Is it possible to rename the files after they are uploaded so they match the rest of the file structure in my library?

Thanks for the great piece of software!

**Comment by Afterster** [comment]
Currently the only possibility is to order uploaded files per user. If you want to match the pattern specified at catalog creation (Artist/Album for example), this is currently not possible.
Upload feature is working but it's a first version, I personally received many feedbacks but it will take some time to get implemented.
I will mark it as improvement.

**Comment by Afterster** [comment]
Done with be816474f64ac047ff5d49a71c82020767c748f3 ;)
