### ISSUE TITLE
Can't search, or view album, artist, tag, etc. content

### ISSUE THREAD

**Issue by goodmorty** [ampache/ampache#1017]
Not getting any errors in my debug just  'Lib\Metadata\Metadata' not found!
All I did was a pull request, backing up my config beforehand and replacing it after

**Comment by Afterster** [comment]
I believe you did a git pull before https://github.com/ampache/ampache/commit/f5733f2f7b3605ac1c218b9806b5f50fe5141dbf
If so, could you do a `composer dumpautoload`? Thanks.

**Comment by goodmorty** [comment]
I could, but I just rm -rf'd ampache and recloned, installed composer and put in my cfg file and its all good
