### ISSUE TITLE
Subsonic not connecting

### ISSUE THREAD

**Issue by goodmorty** [ampache/ampache#1018]
Says it cannot understand the reply. The .htaccess files are in place, everything else works,  the backend is enabled, curl and rewrite are installed/enabled, the xml api returns the correct statement, test.php is green all down, lullaby connects and plays. What else is there?

**Comment by goodmorty** [comment]
Also rewrites are allowed across all

**Comment by goodmorty** [comment]
also progress bars and small web player album art dont seem to load

**Comment by krodelabestiole** [comment]
what client precisely ?
when you say the xml is correct do you mean this one :
http://localhost/ampache/rest/ping.view
```xml
<subsonic-response xmlns="http://subsonic.org/restapi" type="ampache" version="1.11.0" status="failed">
    <error code="10" message="Required parameter is missing."/>
</subsonic-response>```

**Comment by goodmorty** [comment]
That is the message, I see but I have to go to index.php and I use the Subsonic Music Streamer

**Comment by krodelabestiole** [comment]
well subsonic api won't work unless ping.view does, no matters what index.php says.
for it to work you need 3 things (considering your server runs apache, does it?) :
- rewrite mod installed and enabled
- apache configuration must allow configuration override (AllowOverride all) on ampache directory - (for .htaccess rules to be considered) e.g. :
```
<Directory /var/www/ampache>
        AllowOverride All
        Require all granted
</Directory>
```

- ampache/rest/.htaccess file existing containing this rules :
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/play/$1 [PT,L,QSA]
</IfModule>
```


here is a link to the doc, just for easy consultation
https://github.com/ampache/ampache/wiki/API#subsonic-api

which of these elements aren't you sure about ?

**Comment by goodmorty** [comment]
I'm positive about mod rewrite enabled, and that's what my .htaccess says. The default-000.conf (which is enabled) has something very similar to that but my ampache directory is /var/www/html/ampache

**Comment by goodmorty** [comment]
I added the Require all granted to 000-default.conf, made sure it was enabled and restarted apache and ping.view still 404s

**Comment by goodmorty** [comment]
there doesn't seem to be a ping.view file

**Comment by krodelabestiole** [comment]
there is no ping.view file
the idea ot the rewrite rule is to say 
> RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
any url that ends with .view should be treated as index.php?ssaction=[any url beginning]

but it seems rewriting doesn't work on your setup (for one of the reasons i mentioned above).
In 000-default.conf i was not talking about "Require all granted" but "AllowOverride All"

**Comment by goodmorty** [comment]
AllowOverride was in there to start with, and all my .htaccess are pointed at ampache/foo

**Comment by goodmorty** [comment]
solved it, I forgot the leading / in my .htaccess files public address direction
