### ISSUE TITLE
Empty lib/components dir on new install

### ISSUE THREAD

**Issue by cyrosy** [ampache/ampache#1021]
Hi everyone !
I cloned the repo and ran the `composer install` command, and everything went fine.
But my lib/components directory is empty, so no external JS/CSS files are loaded (no jQuery, no Bootstrap, ...)
The install script worked, and created my config file, but now I cannot change anything in the admin - I assume jQuery does the magic there.

I tried to symlink lib/vendor/componenets to lib/components, Ampache was able to find jQuery and  Bootstrap files but there were still many missing files.

Any idea how to fix this ?

**Comment by Afterster** [comment]
Already posted on the group at https://groups.google.com/d/msg/ampache/qtlvfoPvCvg/rhe8HzbdCQAJ. Please don't post twice and be patient :)
