### ISSUE TITLE
Last.fm

### ISSUE THREAD

**Issue by goodmorty** [ampache/ampache#1023]
When I go into the modules page and click "Activate" next to the last.fm plugin it says that it is unable to install the plugin.

**Comment by nioc** [comment]
Hum... can you post some logs or something that can help to understand?
Is it a fresh install or do you upgrade an existing one (in this case did you activate lasftfm plugin previously?)?

**Comment by goodmorty** [comment]
Relatively fresh, 3 upgrades since install, never had it activated
previously. Will post logs soon.

**Comment by goodmorty** [comment]
2015-11-25 16:38:57 [pat] (session) -> Session created: 8efe3722d92ebc82073bbb88992710ff
2015-11-25 16:38:57 [pat] (plugins) -> Error: Plugin Install Failed, Lastfm
2015-11-25 16:38:57 [pat] (Core) -> Registered post form confirmation with SID 1d8b35345adadb00b45ddd8be0087447 and expiration 1448491137 (3600 seconds from now)

**Comment by nioc** [comment]
This is strange... I do not modify this part, so I can not help a lot :disappointed: 
Can you try to query database with the following : `SELECT * FROM ampache.preference where name like '%fm%' order by id desc` ?
The result should be null in your case, but the expected result is as defined in [this post] (https://github.com/ampache/ampache/issues/965#issuecomment-142441300).
And may be, it should be interesting if you can activate a more verbose logs level (debug).

**Comment by goodmorty** [comment]
debug is at 5, i cleared the log and ran the install again and what I got is above. 

the query returned what is pasted below

+----+-----------------+-------+---------------------+-------+--------+----------+
| id | name            | value | description         | level | type   | catagory |
+----+-----------------+-------+---------------------+-------+--------+----------+
| 77 | lastfm_url      |       | Last.FM Submit URL  |    25 | string | internal |
| 76 | lastfm_host     |       | Last.FM Submit Host |    25 | string | internal |
| 75 | lastfm_port     |       | Last.FM Submit Port |    25 | string | internal |
| 74 | lastfm_md5_pass |       | Last.FM Password    |    25 | string | plugins  |
| 73 | lastfm_user     |       | Last.FM Username    |    25 | string | plugins  |

**Comment by nioc** [comment]
I'm not in front of my server so I can not test it, but I suggest, you backup theses line in a SQL file and remove it. Then go on the plugin page and install lastfm, it should works.

**Comment by nioc** [comment]
Is it ok for you @goodmorty ? I know that @Afterster feels scared when there are too many opened issues :smile:

**Comment by goodmorty** [comment]
I'm not all that familiar with mysql so i don't really know how to do that

**Comment by nioc** [comment]
Ok, so log in your server and run :
```bash
mysql -u root -p
```
Type your password in the prompt. Then Type the following command :
```sql
mysql> use ampache;
```
You should have this :
```bash
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
```
Then type the two following commands, commit and exit the mysql prompt:
```sql
mysql> delete from ampache.user_preference where preference in (select id from ampache.preference where name like 'lastfm%') and preference is not null;
Query OK, 5 rows affected (0,00 sec)

mysql> delete from ampache.preference where name like 'lastfm%';
Query OK, 5 rows affected (0,00 sec)

mysql> commit;
Query OK, 0 rows affected (0,00 sec)

mysql> exit
Bye

```

Finally, go in the http://yourserver/admin/modules.php?action=show_plugins to desactivate and reactivate lastfm plugin.

**Comment by goodmorty** [comment]
ok, so i did all that and went in ampache and did the last.fm grant url but it still doesn't seem to scrobble

**Comment by nioc** [comment]
Do you had the following message after you processed the grant button:
"Your Account has been updated : Lastfm" ?
The following SQL returns a value (do not post it) ?
```sql
select * from ampache.user_preference where preference in (select id from ampache.preference where name like 'lastfm_challenge');
```

**Comment by goodmorty** [comment]
no values

**Comment by nioc** [comment]
Can you post the debug log, may be something goes wrong with your configuration. I just did it in my server (delete lines with SQL, desactivate, activate plugin, grant access) and it scrobbles.
Something I forget to ask: do you created an lastfm account and updated the API key and secret? If not, the message says:
"Your Account has **not** been updated : Lastfm"

**Comment by goodmorty** [comment]
updated api key and secret?

**Comment by nioc** [comment]
In the log, you should have this kind of lines when it works:
```bash
grep Last.FM /tmp/ampache.20151207.log 
2015-12-07 19:10:54 [nicolas] (Last.FM) -> getSession Successful 
2015-12-07 19:16:19 [nicolas] (Last.FM) -> Submission Successful 
```
But when you do not set your API key and secret, you had theses:
```bash
grep Last.FM /tmp/ampache.20151207.log 
2015-12-07 19:29:44 [nicolas] (Last.FM) -> No session key, not scrobbling (need to grant Ampache to last.fm) 
2015-12-07 19:29:45 [nicolas] (Last.FM) -> getSession Failed: Did not receive a valid response 
```
You can request an API key and the secret on [last.fm site](http://www.last.fm/api/account/create). Then set the two variables in your `/config/ampache.cfg.php` : `lastfm_api_key` and `lastfm_api_secret`

**Comment by goodmorty** [comment]
I figure it out just before you posted. Thank you very much for all of your help :]
