### ISSUE TITLE
Not able to add dropbox folder to catalog

### ISSUE THREAD

**Issue by ricky641** [ampache/ampache#1027]
Hello,
When I click on Make It Ready, it throws this error

Fatal error: Uncaught exception 'Exception' with message 'The Dropbox SDK uses 64-bit integers, but it looks like we're running on a version of PHP that doesn't support 64-bit integers (PHP_INT_MAX=2147483647). Library: "/Applications/AMPPS/www/ampache/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/RequestUtil.php"' in /Applications/AMPPS/www/ampache/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/RequestUtil.php:22 Stack trace: #0 /Applications/AMPPS/www/ampache/lib/vendor/composer/ClassLoader.php(412): include() #1 /Applications/AMPPS/www/ampache/lib/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Applications/A...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Dropbox\\Request...') #3 /Applications/AMPPS/www/ampache/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/WebAuthBase.php(14): spl_autoload_call('Dropbox\\Request...') #4 /Applications/AMPPS/www/ampache/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/WebAuthNoRedirect.php(56): Dropbox\WebAuthBase->_getAuthorizeUrl(NULL, NULL) #5 /Applicati in /Applications/AMPPS/www/ampache/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/RequestUtil.php on line 22

Please help me. I am running Ampps in Mac Yosemite with PHP Version 5.5.

**Comment by Afterster** [comment]
That's because Dropbox SDK only works on 64-bit system/php. I believe your system or php is running in 32-bit here which makes Dropbox SDK to fail. This is a limitation from https://github.com/dropbox/dropbox-sdk-php
