### ISSUE TITLE
Movie title is not properly cleaned.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1029]
First, my config setting is:
   `metadata_order_video = "getID3,Tmdb,"`

It's getting the title from _parse_general($tags).

Would it be ok to run $filename through formatVideoName such as:
       `$parsed['title'] = $this->formatVideoName(urldecode($this->_pathinfo['filename']));`

**Comment by wagnered** [comment]
Oh yea, it fails to properly clean the title for tv shows too, but the title is not used for tv shows only movie titles.

**Comment by Afterster** [comment]
Mh yes I think this would be consistent. But you should only do this if gather_types contains tvshow or movie I believe.

**Comment by Afterster** [comment]
#1035 merged, thanks.
