### ISSUE TITLE
Add catalog not working (not even dropbox and nor local)

### ISSUE THREAD

**Issue by ricky641** [ampache/ampache#1031]
I have tried all the possible ways to add catalog ..I also tried with dropbox and went through 100 times via troubleshooting steps for adding catalog but nothing seems to work. Not even 1 song gets added to the catalog. Sometimes I get pattern error via dropbox  and sometimes I get Server-Sent events reconnection error whenI try to do via local ..I have tried all the methods possibles ..I have changed permissions and done everything else mentioned in troubleshooting. Here is snapshot of Ampache Config.
I was only able to add songs to catalog when I had run ampache on my localhost but after running on linux based web server,nothing seems to work and songs are same. Please help me.
![screen shot 2015-12-01 at 1 12 34 am](https://cloud.githubusercontent.com/assets/11390377/11482519/578f6dfe-97c9-11e5-9cb7-eb80ca53470c.png)

**Comment by Afterster** [comment]
Could be because your web server configuration doesn't accept Server-Sent Events. You should try to check about that. Otherwise you can try to disable Ajax page loading on interface settings, this will then not use SSE for catalog update.
