### ISSUE TITLE
Can't install using admin password containing special characters

### ISSUE THREAD

**Issue by jagerman** [ampache/ampache#1033]
I tried to install using a randomly-generated password that contains an ampersand, and got an error that my passwords don't match.

It comes down to this line in install.php:

        $password2 = scrub_in($_REQUEST['local_pass2']);

and since the first password, $password, is captured without scrub_in, the & in my password caused a failure.  (I'm sure there are other characters that would cause a similar problem).

I'm pretty sure the scrub_in here is wrong, especially since it isn't being applied to $_REQUEST['local_pass'] for scrub_in, and the only place $password2 is ever used is in a comparison to $password.  $pass1 and $pass2 in register.php also don't go through scrub_in.

Removing the scrub_in call (i.e. just $password2 = $_REQUEST['local_pass2'];) fixes the problem.

**Comment by Afterster** [comment]
Indeed, this is an error I believe. I'm gonna to fix it, thanks.
