### ISSUE TITLE
PHP 7 seems unsupported

### ISSUE THREAD

**Issue by trampi** [ampache/ampache#1034]
Hello together,

ampache does not seem to work with PHP 7. After upgrading my distribution to PHP 7 the following behaviour occured.

When accessing the Login-Page, the following error appears in the apache error log:

    Uncaught Error: Call to undefined method Error::display() in /opt/ampache/templates/show_login_form.inc.php:91\nStack trace:\n#0 /opt/ampache/login.php(27): require()\n#1 {main}\n  thrown in /opt/ampache/templates/show_login_form.inc.php on line 91

The rendering of the login page is aborted just before the "login"-Button.

The problem ist also present on the newest commit on the development-branch.
The streaming / remote API however is unaffected, I can stream the music on my devices.

I am on CentOS 7, using PHP via https://webtatic.com/packages/php70/
The problem is *probably* reproducible with PHP 7 on any distribution.

If you need any further informations do not hesistate to ask.

**Comment by Afterster** [comment]
Indeed. This is because a new class type Error is now defined in php7 and conflict with Ampache Error class. See http://php.net/manual/fr/language.errors.php7.php
I'm gonna to fix it, thank for the report ;)

**Comment by Afterster** [comment]
Should be fixed with 92fcb8467070733bc70e0e0dc6a6edd3bbb2a621. Please confirm.

**Comment by trampi** [comment]
Nice! That was fast!
It seems that your commit fixed the problem.

I have not found any other problems yet, therefore I close this issue.
