### ISSUE TITLE
Tracks ending early with MPD

### ISSUE THREAD

**Issue by fre-ber** [ampache/ampache#1036]
Hi, I have a setup that plays long tracks (several hours each) from Ampache with MPD. MPD and Ampache are running on the same machine. Quite often I get messages like these in the log:

2015-12-05 10:18:58 [admin](play) -> Stream ended at 65466368 (65466368) bytes out of 219477766

Nothing else gives any hints on why it stopped early and when this happens, MPD simply stops playing. Instead of moving to the next track in the playlist it just goes silent until I restart the playlist in Ampache.

I have increased the PHP setting "upload_max_filesize" to 512M and set the Ampache setting "stream_length" to 36000, which is longer than any of ther tracks in the playlist.

I did some more digging and logged the result of "connection_status()" and see that CONNECTION_ABORTED is set when this happens. I suppose that this means that it is MPD that prematurely closes the socket to Ampache. What could make this happen?

Repeatedly running "mpc" after this has happened shows something like this every time, the timers have stopped:
Johnny Clarke SL - 20150807
[playing] #6/26  45:14/152:25 (29%)
volume:100%   repeat: on    random: off   single: off   consume: off

This implies that MPD does get the correct file size from Ampache.

"gapless_mp3_playback" is disabled in mpd.conf.

This problem has started to happen whiting two or three months, possibly related to a package upgrade. I don't know exactly when it started, but before that upgrade it played smoothly for months. I am not sure if this ever happened before my upgrade to Ampache 3.8.0, but it might have.

I would appreciate any ideas on what could have happened with my configurations or installations.

EDIT: It stops at different positions every time. Sometimes a track is played fully and sometimes the same track is cut short.

**Comment by stebe** [comment]
Make sure your session hasn't timed out before file has finished playing. I recall having a similar problem in the past and increasing the session_length to a day solved it for me.

**Comment by fre-ber** [comment]
Hmm, I thought that session_length was just for the log in sessions on the website and that stream_length is the one controlling the playback sessions from MPD. Is this not correct? 

I also thought that these sessions are extended automatically. Hence these log messages:

    2015-12-06 15:17:55 [admin] (session) -> 7963c7f3009d3ece21bc20028a7243ed has been extended to Mon, 07 Dec 2015 01:17:55 +0100 extension length 36000

The 36000 in that line is from the stream_length setting in the Ampache config.I could set this to something ridicilously long for testing pourposes, but I would like more details on this matter especially since the stop doesn't appear to happen on stream_length intervals. If it was the case of a session time out, wouldn't there be something other than "connection_status() != 0" that makes the stream loop exit?

**Comment by fre-ber** [comment]
I tested the stream with single song tracks (As in much shorter, just a few minutes each) and it still randomly stops. Should I really extend session_length? And does that mean that it will still stop when that time is reached? My MPD is supposed to play 24/7. I will try it but I don't think that this is it as it stops at different positions every time - it isn't a fixed length from when the stream starts.

My extended log shows messages like these when it happens, the first line is something I added to get more information:

```
2015-12-14 15:26:24 [admin] (play) -> Stream ended: EOF=0, connection_status=1, transcode=0, bytes_streamed=4820992, stream_size=6112477
2015-12-14 15:26:24 [admin] (play) -> Stream ended at 4820992 (4820992) bytes out of 6112477
```
```
$ date
Mon Dec 14 16:22:38 CET 2015
$ mpc
UB40 - Sing our own song
[playing] #121/330   2:55/4:09 (70%)
volume:100%   repeat: on    random: on    single: off   consume: off
$ date
Mon Dec 14 16:22:42 CET 2015
$ mpc
UB40 - Sing our own song
[playing] #121/330   2:55/4:09 (70%)
volume:100%   repeat: on    random: on    single: off   consume: off
```
I would appreciate any information on this topic.

**Comment by EvilLivesHere** [comment]
I have a similar issue with certain tracks ending early.  My test track is an MP3 that is 4:14 long and will fully play in various music programs.  It shows as the correct length in Ampache and the playlist that Ampache builds shows the file should be 4:14 long.  However, trying to stream via Ampache, it will only play for 3:34.  
After doing some testing, I noticed that the file being sent by Ampache is actually shorter than the original.  I have transcoding disabled.  I used a separate utility to re-encode the file to FLAC and that solved the issue.  I then tried re-encoding my FLAC file back to MP3, but the problem started again at the same 3:34 mark.

I can say that this problem DID occur before the 3.8.1 upgrade, but was relatively rare.  It seems to be a lot more common now that I've upgraded to 3.8.1.

Are the files you are attempting to stream MP3s?  If you convert them to some other format, does the issue go away?  Perhaps this is some kind of MP3 issue with Ampache.

**Comment by fre-ber** [comment]
MPD spews out some gibberish that is difficult to interpret when this happens:
```
Dec 17 00:16 : client: [0] opened from [::1]:47282
Dec 17 00:16 : client: [0] process command list
Dec 17 00:16 : client: process command "status"
Dec 17 00:16 : client: command returned 0
Dec 17 00:16 : client: process command "currentsong"
Dec 17 00:16 : client: command returned 0
Dec 17 00:16 : client: [0] process command list returned 0
Dec 17 00:16 : client: [0] closed
Dec 17 00:16 : client: [1] opened from [::1]:47283
Dec 17 00:16 : client: [1] process command list
Dec 17 00:16 : client: process command "status"
Dec 17 00:16 : client: command returned 0
Dec 17 00:16 : client: process command "currentsong"
Dec 17 00:16 : client: command returned 0
Dec 17 00:16 : client: [1] process command list returned 0
Dec 17 00:16 : client: [1] closed
```
Does this help at all? I can't tell if this is something that is correct or wrong. I just see that after this, nothing else is logged by MPD until I either restart the stream from Ampache or restart MPD. Both actions makes it start to play again.

EvilLivesHere: No, I don't think there is anything wrong with the tracks or the way they have been imported. My problem is more random than that - it is not the same track that makes it stop, it is not always the same location in the tracks. 

It could still be something related to sessions timing out, but I see no correlation between the error and either stream_length or session_length settings. I now have these set high (ten hours) but it still stops before that, sometimes as quickly as half an hour, or even less, after the track started playing.

**Comment by Afterster** [comment]
This looks related to your environment. Nothing to do with session length I believe, looks like MPD is closing the connection prematurely. Either because of a timeout or because it think the file download is completed. I'm not a MPD user and cannot help you here but I believe you should look at MPD side.

**Comment by Phyks** [comment]
@fre-ber Could you have a look at an MPD log with maximum logging level? Same for Ampache? No clue at all?

Could you also check that it is still happening with latest `develop` branch?

If it is the case, could you let me know about the steps you follow (if anything particular is different from default config) so that I try to reproduce? I am using MPD localplay (although not a lot) and have never noticed similar behavior.

**Comment by tomgould** [comment]
Is anyone still having this issue?

I was so made a JS script to auto-skip

http://tom-gould.co.uk/blog/ampache-auto-skip

// ==UserScript==
// @name       Ampache Autoskip
// @namespace  http://tom-gould.co.uk/blog/ampache-auto-skip
// @version    0.1
// @description  Skips the track if Ampache fails to
// @match      http://yourserver.com/*
// @copyright  2012+, Tom Gould
// @require      https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
// @grant GM_addStyle
// ==/UserScript==
var skipAmpache = function () {
    var currentTime = jQuery('div.jp-current-time').html();
    var duration = jQuery('div.jp-duration').html();
    if (undefined == currentTime || undefined == duration) {
      setTimeout(skipAmpache, 3000);
      return;
    }
    var cur = parseFloat(currentTime.replace(':', ''));
    var dur = parseFloat(duration.replace(':', ''));
    var diff = dur - cur;
    if (diff == 1) {
        jplaylist.next();
        setTimeout(skipAmpache, 10000);
        return;
    }
 
    setTimeout(skipAmpache, 1000);
};
 
skipAmpache();

**Comment by lachlan-00** [comment]
usually i've found this was from an ffmpeg error but not always, closing for age. mpd is used very regularly by people and haven't reported something like this for a long time.
