### ISSUE TITLE
Typos in ampache.sql file causes errors for new installs

### ISSUE THREAD

**Issue by NestedLooper** [ampache/ampache#1037]
INSERT INTO `preference` (`id`, `name`, `value`, `description`, `level`, `type`, `catagory`) VALUES
...
...
(141, 'theme_color', 'dark', 'Theme color', 0, 'special', 'interface')**;**
(142, 'disabled_custom_metadata_fields', '', 'Disable custom metadata fields (ctrl / shift click to select multiple)', 100, 'string', 'system')**;**

**The semicolons following both lines 141 and 142 should be commas. The semicolon should be only after inputing 143. This causes the initial install to fail.**

**Comment by Afterster** [comment]
Indeed, thanks.
