### ISSUE TITLE
Questtion about php-cs-fixer.phar

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1039]
@Afterster,
I am running the latest (1.11) with fixers:
`--fixers=indentation,linefeed,trailing_spaces,short_tag,braces,controls_spaces,eof_ending,visibility  . `
and show no errors. Thisd is what I've been using for some time with no problems.

I submitted a PR and found that all the travis builds failed.  I then closed that PR, removed the commit from remote/develop (my fork) and checked the files again, just in case. Again no failures. 

Has the list of fixers changed?

**Comment by hyperactivated** [comment]
fixers were updated to: indentation,linefeed,trailing_spaces,short_tag,braces,controls_spaces,eof_ending,visibility,align_equals,concat_with_spaces,elseif,line_after_namespace,lowercase_constants,lowercase_keywords 

about 2 weeks ago, you can find them in [scripts/tests/codestyle.sh](https://github.com/ampache/ampache/blob/develop/scripts/tests/codestyle.sh)

**Comment by wagnered** [comment]
OK Thanks.
