### ISSUE TITLE
Add web.config to .gitignore for IIS

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1041]
I'm running Ampache on IIS and it works fine.
The only issue I have is that after every git pull I lose my IIS web.config in the root of the Ampache web folder.
Could it be added to the .gitignore?

**Comment by Afterster** [comment]
This shouldn't change anything.
Doing a git pull shouldn't remove your uncommitted local files.

**Comment by Rouzax** [comment]
Hmm, I can't pull right now because I'm already up to date.
```
icrosoft Windows [Version 6.3.9600]
c) 2013 Microsoft Corporation. All rights reserved.

:\inetpub\wwwroot>cd Ampache

:\inetpub\wwwroot\Ampache>git pull
lready up-to-date.

:\inetpub\wwwroot\Ampache>
```

**Comment by Afterster** [comment]
Just added web.config to ignore list as it makes sense, but the file shouldn't have disappear anyway. This is a mistake of your side for sure (bad git commands, ...) :)

**Comment by Rouzax** [comment]
That could be a valid assumption. :smile:
Thanks for the addition.
