### ISSUE TITLE
PHP Fatal error:  Access to undeclared static property: Video::$aliases

### ISSUE THREAD

**Issue by johanlundberg** [ampache/ampache#1042]
I get the following error message when trying to run "php /var/www/ampache/bin/catalog_update.inc".

PHP Fatal error:  Access to undeclared static property: Video::$aliases in /var/www/ampache/modules/catalog/local/local.catalog.php on line 819

Running version 3.8.1-beta2.

Please tell me if I can provide any more information.

**Comment by Afterster** [comment]
Indeed, this is happening on catalog update of video catalogs. Please don't hesitate to report any other issues you could encounter on this beta before it gets released. Thanks!
Fixed.
