### ISSUE TITLE
lib/vendor/ampache/ampacheapi-php/src/AmpacheApi.lib.php still at GPLv2

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1043]
I was stepping through the code and noticed the header on this script.  Maybe you already caught this.

**Comment by Afterster** [comment]
That's right :)
In fact this file is now under a dedicated repository (with his own issue tracker btw :smile:), see https://github.com/ampache/ampacheapi-php

I'm gonna to fix it, thanks!
