### ISSUE TITLE
Subsonic API not working properly

### ISSUE THREAD

**Issue by codewing** [ampache/ampache#1046]
Hey guys, 
I've set up the subsonic api as described in the [wiki](https://github.com/ampache/ampache/wiki/API#subsonic-api) 
The ping page also works like a charm ([here](http://hms.mhn.de:13370/ampache/rest/ping.view))
And when I try to use an android app the connection test says everyting is alright.
I'm also able to view the most played songs and play them.

But whenever I try to access the library it tells me that "a network error occured please check the server address or try later". I've tried 3 different apps (subsonic music streamer, ultra sonic and dsub) and each one tells me the same.

Edit: I've discovered the "Subsonic Remote Catalog" module and activated it because it seems like only the library does not work but sadly it didn't fix anything.

**Comment by Afterster** [comment]
Anything on logs? 
You can also try to give me a temporary access and I will take a look when I get some time.

**Comment by codewing** [comment]
It doesn't create a log when I'm using log level 2 or 5 (the others aren't so discriptive). 
>; 3 == ??
>; 4 == ?? (Profit!)
Logging works btw, tested it in the browser.

I've sent you an email with the credentials :)

**Comment by Afterster** [comment]
Ok I believe it's just coming from a timeout. Could you try to add `set_time_limit(300);` here https://github.com/ampache/ampache/blob/develop/lib/class/subsonic_api.class.php#L335? Thanks.

**Comment by codewing** [comment]
Works like a charm! Thanks a lot! :)

**Comment by Afterster** [comment]
Then this would be a timeout from the client because the server is taking more than 30sec to give an answer...

**Comment by codewing** [comment]
Hmm okay this is weird, after restarting the app the lib works... It's probably working in the background without displaying anything.. 
Well. I think this can be closed but you probably should add the set_time_limit method call. But it's your decision :)
Thanks a lot!
