### ISSUE TITLE
Updating Album art does not update file size

### ISSUE THREAD

**Issue by EvilLivesHere** [ampache/ampache#1052]
This is an issue that I believe has been around for a while, but that I am seeing on 3.8.1 (fcab5e6).  Ampache does not update the size attribute in the 'song' table after it adds album art to the file.  This causes streams to end early, depending on the new size difference of the file.

To reproduce:
* Add a song to your catalog (and obviously choose a type that Ampache is actually configured to add covert art to, such as mp3). note the size in the song table.  The song will play fine.
* Go to that album and add album art to the album.
* Check the size of the file and the size in the song table and see the difference.  If you try to play the song, it will only get partially through the song before stopping.  In the log, you'll see a message about the size of the file sent being the old file size (not the new correct one).

**Comment by Afterster** [comment]
So if I understand you correctly, you have `write_id3_art` enabled right?

**Comment by EvilLivesHere** [comment]
That is correct.  I have write_id3_art = "true" in my cfg file.
As a side note, I also have write_id3 set to true, however I noticed that my files do not get updated when I change their information (like song name or album) until I update the album art for their album.  Only then does it seem to finally write all of the tag information.  I haven't done any testing on that issue yet, so I wasn't going to post a bug report, but I figure it might be useful information to have for this.

**Comment by Afterster** [comment]
Song files are now re-analyzed after writing id3 information. This should fix this issue, please confirm.

**Comment by EvilLivesHere** [comment]
I can confirm that commit 47faff9 fixed this issue for me.  Thanks!
