### ISSUE TITLE
Fails to add collections containing errors in tags

### ISSUE THREAD

**Issue by JK2gUu-Ny9** [ampache/ampache#1053]
on branch development, using mysql 5.6.28:
When adding a collection, a single file with wrong tags can cause an infinite loop.
This causes the collection to never be added, iterating over already added files for all eternity.

```
[user] (read) -> Starting work on 06-horkyze_slize-velke_dlhe_a_s_dvoma_bodkami.flac inside /media/dummycollection/Horkyze_Slize-St._Mary_Huana_Ganja-SK
[user] (Memory) -> 2.25 MB
[user] (vainfo) -> Cleaning vorbis
[user] (Dba) -> Error: ["HY000",1366,"Incorrect string value: '\\x84A\\x84 S ...' for column 'title' at row 1"]
[user] (Dba) -> Error: ["HY000",1366,"Incorrect string value: '\\x84A\\x84 S ...' for column 'title' at row 1"]
[user] (Dba) -> Error: ["HY000",1366,"Incorrect string value: '\\x84A\\x84 S ...' for column 'title' at row 1"]
[user] (Dba) -> Error: ["HY000",1366,"Incorrect string value: '\\x84A\\x84 S ...' for column 'title' at row 1"]
```

I agree that 'title' seems broken, but the expected behavior would be to either:
* skip the file alltogether and log an error
* add the file with an empty title
* strip unknown runes from the title, add with modified title

I can supply the file for bug reproduction, if needed.

**Comment by Afterster** [comment]
Yes this is a bug indeed. Comming from the fact that parsed data can be on another charset than utf8 and the database field is excepting an utf8 string. We should check/convert data on vainfo class.
Your test file would simplify my test yes :)

**Comment by Afterster** [comment]
This was in fact a remaining debug code issue. Removed with 47faff95238acc9c41457e054b41c50fabf67b9b.
