### ISSUE TITLE
Artist Search / Removed Article(s)

### ISSUE THREAD

**Issue by codewing** [ampache/ampache#1055]
Some of the artists lose parts of their name. 
E.g.: 
Die Happy -> Happy
Die Toten Hosen -> Toten Hosen

Seems like you're removing german articles. 
The problem is that "Die" of Die Happy is not an article. :)

I've briefly searched for this in the settings but couldn't find something related to this problem.

**Comment by Afterster** [comment]
Yes indeed this is the excepted behavior. English and French prefixes are also removed. There is sometimes wrong positives and it's mainly on `Die` btw.
There is no option to disable this behavior or configure prefix list for now.
