### ISSUE TITLE
Broken Action buttons

### ISSUE THREAD

**Issue by psjbeisler** [ampache/ampache#1064]
I did a completely new install just to make sure this wasnt my fault first but I'm not sure if anyone else is getting this or not. 

Catalog view
![2015-12-20-212543_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2433907/11922090/4b1582b4-a761-11e5-90b4-a7b0de8146b3.png)

Album view
![2015-12-20-212641_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2433907/11922091/4b1db0c4-a761-11e5-9273-145753a85755.png)

**Comment by Psy-Virus** [comment]
Just a shot into the blue, but if you have a standard browser like FireFox or Chrome and you simply install Ampache as it should be installed.... Do you have an Ad- or script blocker or something in this direction installed on your browser?

As I said its only a shot into the blue but maybe it helps if you disable them and if this fixes it, you should check the blocker-extension settings.

:-)

**Comment by Psy-Virus** [comment]
Just a shot into the blue, but if you have a standard browser like FireFox or Chrome and you simply installed Ampache as it should be installed.... Do you have an Ad- or script blocker or something in this direction installed on your browser? Maybe you have blocked any kind of form..

As I said its only a shot into the blue but maybe it helps if you disable them and if this fixes it, you should check the blocker-extension settings.

And did you check it with another browser?

Or maybe you simply should clear you Browsers cache^^ That fixes mostly 90% of display errors :laughing: 



:-)

**Comment by psjbeisler** [comment]
seems ok now, not sure what happened in the first place. but i added new users to test and it was fine after. I had definitely flushed cache and hard reloaded a few times on diff machines with no chanage previously... idk
