### ISSUE TITLE
Error 500 after updating to new ampache

### ISSUE THREAD

**Issue by ricky641b** [ampache/ampache#1066]
http://juanynelson-applicationcode.rhcloud.com/ampache/

Please check this link..I just updated to new ampache and after that this error came.
please help its urgent

**Comment by Afterster** [comment]
Be sure you have installed and updated composer packages with composer install. Otherwise please provide logs.

**Comment by ricky641b** [comment]
I am getting this when try to run this command

composer install --prefer-source --no-interaction
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/var/lib/openshift/565f26ce89f5cf6fc800011b/php/usr/bin/composer self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/process v3.0.0 -> satisfiable by symfony/process[v3.0.0].
    - symfony/process v3.0.0 requires php >=5.5.9 -> your PHP version does not satisfy that requirement.
  Problem 2
    - kriswallsmith/assetic v1.3.2 requires symfony/process ~2.1|~3.0 -> satisfiable by symfony/process[v3.0.0].
    - kriswallsmith/assetic v1.3.2 requires symfony/process ~2.1|~3.0 -> satisfiable by symfony/process[v3.0.0].
    - symfony/process v3.0.0 requires php >=5.5.9 -> your PHP version does not satisfy that requirement.
    - Installation request for kriswallsmith/assetic v1.3.2 -> satisfiable by kriswallsmith/assetic[v1.3.2].

**Comment by ricky641b** [comment]
Seems like it needs PHP 5.5.9 ...but thats not possible as openshift have only php supported till 5.4 ..so is their any way I can revert to previous version?

**Comment by Afterster** [comment]
Hum this is an inherited dependency issue that I didn't noticed then. It's too early to drop PHP 5.4 support. I will try to resolve it around Christmas and let you know. You will have to revert to 3.8.0 then for now I believe.

**Comment by ricky641b** [comment]
Oh..My app was going to be live on app store..how to revert to 3.8.0 ...I have some 300 albums in ampache..will have to add that again?

**Comment by Afterster** [comment]
If you didn't made a backup before upgrade, then yes. But catalog update should be quick enough as you know. Sorry for that it wasn't excepted and it may annoy several users btw... Feel free to identify the problematic package and suggest a PR if you have some knowledge on it, otherwise I will fix it quickly when I will get some times on a real computer.

**Comment by ricky641b** [comment]
After you will fix then I have to just update the ampache from composer to fix it right?

**Comment by ricky641b** [comment]
Would it be fine If I use 3.8.1 beta 2 ...because I dont think their dropbox support in 3.8.0 ..and my whole collection is stored in dropbox only.

**Comment by Afterster** [comment]
The problem is here since the move to Composer I believe. I don't have time to investigate the issue before Christmas, but I posted a dependency graph attached to my previous comment to help investigation.

**Comment by Afterster** [comment]
Fixed dependencies version with 66a3e7138e527e78140c2cbcd145c059335e16ae.
