### ISSUE TITLE
Log Error when Forwarding Requests to Ampache

### ISSUE THREAD

**Issue by EvilLivesHere** [ampache/ampache#1067]
I had been receiving this error in my logs:

```
[ampache] (PHP) -> [Runtime Error] inet_ntop(): Invalid in_addr value in file F:\ampache\lib\class\user.class.php(1029)
 ```

I am using an IIS server to forward requests to my Ampache server on a different machine.  After looking into the issue, I figured out it was because the HTTP_X_FORWARDED_FOR address was actually sending ip:port instead of just the IP, which seemed to be what Ampache was expecting.  It was also writing a blank ip address blob into my ip_history table for the user.  Is my IIS server just mis-configured to send the port, or is Ampache not correctly dealing with this?

I fixed this issue temporarily by just modifying user.class to parse the IP correctly, but wanted to let you know of the problem in case it was something to fix.

**Comment by Afterster** [comment]
Ok I added parsing with 7d3c2354b4bbc79cf4ae31035c6d049c67dfaeaa, could you confirm this fixed it? Thank you.

**Comment by EvilLivesHere** [comment]
Sorry for the late response.  Yes the issue is fixed now :)
Thanks
