### ISSUE TITLE
Can't sync podcasts

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#1068]
Hey guys,

I'm trying the new exciting podcast feature with no luck : tried with a couple of feeds like this one for example (http://radiofrance-podcast.net/podcast09/rss_13940.xml).

Podcasts folders are created as expected with the right user:group (I think).

But I keep getting this when trying to sync episodes :
```
(ajax.server.php) -> Called for page: {podcast} 
2015-12-21 21:49:06 [ampache] (PHP) -> [Runtime Error] file_get_contents(): Filename cannot be empty in file /ampache/lib/class/podcast.class.php(440) 
2015-12-21 21:49:06 [User] (podcast) -> Cannot access feed
```

***
Using the following :
* Nginx 1.8.0
* php 5.6.16
* MariaDB 10.1.9

**Comment by Afterster** [comment]
Good to know you are testing it :).
I believe it's because `allow_url_fopen` setting is disable on your php.ini. I think I should move this part through Requests to avoid this requirement.

**Comment by Jucgshu** [comment]
Nope, ``allow_url_fopen`` is supposed to be activated in my php.ini.

I tried with both ``on`` and ``1`` values with no luck.

**Comment by Afterster** [comment]
OK I added a log entry, could you try and post the concerned logs here again? Thank you.

**Comment by Jucgshu** [comment]
Thanx for that @Afterster 

Here you go :
```
2015-12-23 07:48:05 [User] (ajax.server.php) -> Called for page: {podcast} 
2015-12-23 07:48:05 [User] (podcast) -> Syncing feed  ... 
2015-12-23 07:48:05 [ampache] (PHP) -> [Runtime Error] file_get_contents(): Filename cannot be empty in file /ampache/lib/class/podcast.class.php(442) 
2015-12-23 07:48:05 [User] (podcast) -> Cannot access feed
```

**Comment by Afterster** [comment]
Ok, looks like feed url is empty...
How do you attempt to subscribe to the podcast, using web interface or Subsonic API?

**Comment by br3wal** [comment]
Web interface only.

Also, one important thing I forgot to mention is that the subscription works well and the episodes list gets populated as intended. Only the status stays "pending" waiting for the sync process to complete.

**Comment by Jucgshu** [comment]
Web interface only.

Also, one important thing I forgot to mention is that the subscription works well and the episodes list gets populated as intended. Only the status stays "pending" waiting for the sync process to complete.

EDIT: wrong github account ;p

**Comment by Jucgshu** [comment]
Little update.

Looks like it's (sort of) working after all.

BUT, we have to manually sync the episodes from the episode list. The main sync function (on top of the podcast page) ends up with an error (see above).

I guess this is still a bug as the "main" sync function does not work, but we can download podcasts episodes anyway.

**Comment by Afterster** [comment]
Indeed, fixed now, thanks :).
Don't hesitate to give feedback about Podcast feature on #30.
