### ISSUE TITLE
"size" parameter of Subsonic's "getCoverArt" method is not supported

### ISSUE THREAD

**Issue by s4astliv** [ampache/ampache#1070]
Subsonic's getCoverArt API method accepts two parameters: id and size.

http://www.subsonic.org/pages/api.jsp#getCoverArt

Whenever size parameter is included in the URL, the art cover is not returned.

OK: https://server/rest/getCoverArt.view?u=user&p=enc:xxx&f=jsonp&v=1.11.0&c=Music&id=200000822
Not OK: https://server/rest/getCoverArt.view?u=user&p=enc:xxx&f=jsonp&v=1.11.0&c=Music&size=30&id=200000822

Apache logs:

OK: 10.0.0.2 - - [22/Dec/2015:19:56:08 +0000] "GET /rest/getCoverArt.view?u=serhiy&p=enc:3330303531393834&f=jsonp&v=1.11.0&c=Music&id=200000822 HTTP/1.1" 200 236204
Not OK: 10.0.0.2 - - [22/Dec/2015:19:56:06 +0000] "GET /rest/getCoverArt.view?u=serhiy&p=enc:3330303531393834&f=jsonp&v=1.11.0&c=Music&size=30&id=200000822 HTTP/1.1" 200 -

**Comment by Afterster** [comment]
This feature requires PHP-GD, are you sure this php module is enabled on your server?

**Comment by s4astliv** [comment]
Thank you for coming back to me. Yes, it is installed.

```
GD Support	enabled
GD Version	bundled (2.1.0 compatible)
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.5.3
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	8
PNG Support	enabled
libPNG Version	1.6.13
WBMP Support	enabled
XPM Support	enabled
libXpm Version	30411
XBM Support	enabled
WebP Support	enabled
```

I enabled ampache debug logs. Here is what I see in regards to art:

```2015-12-23 08:24:56 [serhiy] (Art) -> Local image art /srv/www/ampache/metadata/album/392/default/art-160x160.jpg cannot be read.
2015-12-23 08:25:03 [serhiy] (Art) -> Local image art /srv/www/ampache/metadata/album/392/default/art-30x30.jpg cannot be read.```

Checking the directory shows that there is only original art: art-original.jpg.
