### ISSUE TITLE
3.8.2 Develop unable to add new catalog

### ISSUE THREAD

**Issue by minnesotags** [ampache/ampache#1072]
On a completely new installation, the "add catalog" link hangs before bringing up the frame.

**Comment by Psy-Virus** [comment]
What's in your Ampache Logs? Composer installed and updated?
if nothing and yes:
    what web server do you use?
    Is the php version at least 5.4?
else:
    Please show us your Ampache logs around the time you clicked on the add catalog button. (Please within [markdown code tags](https://guides.github.com/features/mastering-markdown/) or as upload)
    The web server logs around this time could also be helpful.

:-)

**Comment by Psy-Virus** [comment]
Oh ehm #1066 indicates that some composer dependencies may need php 5.5.9. So maybe 5.5.9 would be better instead of 5.4....

**Comment by minnesotags** [comment]
I'll do this tomorrow. I need to go from a working stable to a broken 3.8.2 to duplicate.

 Right now I went back to the stable version and it is working. I'm playing holiday music.

**Comment by Afterster** [comment]
Is this still actual @minnesotags?

**Comment by minnesotags** [comment]
There has been so much activity that I will close this and try with a new build install.
