### ISSUE TITLE
No connectivity via subsonic apps after 3.8.0Dev -> 3.8.1 Update

### ISSUE THREAD

**Issue by calcmandan** [ampache/ampache#1076]
I was running 3.8.0-dev on ubuntu server running apache. Updated to 3.8.1 following the directions. Subsonic was working great prior to update.

I've confirmed that subsonic backend is enabled.

Unforunately, I'm not sure which log files to look at to begin narrowing down why I can't stream via my phone.

When I re-added the server to dsub it gave me a 'conection failure' error.
Subsnoic gave a 'Connection failure. Didn't understand the reply' error.

I left apache untouched during the upgrade process because the instructions didn't entail anything t o do.

I have to warn all of you that, in the time since I built the server and got it operational, doing anything but weekly updates to the system were all I've done in nearly a year. The majority of knowlege I gained while setting the box up are forgotten, so I'm more or less a complete noob.

Any assistance would be greatly appreciated.

**Comment by Afterster** [comment]
What about each steps describe on https://github.com/ampache/ampache/wiki/API#subsonic-api?
You should also check your current /rest/.htaccess and /play/.htaccess with /rest/.htaccess.dist and /play/.htaccess.dist
Then please also provide Apache/Ampache logs.

**Comment by calcmandan** [comment]
The rest and play directories don't have the .htaccess files. Just the index files.

Forgive my ignorance, but I can't seem to locate the ampache log file.

**Comment by calcmandan** [comment]
Hey afterster, i'm the one who asked the same question in irc. would you prefer to work in here or there?

**Comment by calcmandan** [comment]
afterster, thanks fr your help. I just needed to recreate the config file. it's working
