### ISSUE TITLE
Playing files twice fail

### ISSUE THREAD

**Issue by Arsimael** [ampache/ampache#1077]
Hi,

If I play a Song, and some other player sees it in the overview and tries to play it too, it fails.
He can click the song as long as he wants, no sound will be heard and the speakers stay silent. Even after I stopped the song, it seems the song is "locked" for a time. (I can't restart the song).

Same happens with 3rd party players. (Viridian, AMPM, etc)

Greetings
A.I.

**Comment by Afterster** [comment]
The usual here... could you check/provide you Ampache/Apache logs?
Thanks!

**Comment by Arsimael** [comment]
ampache.cfg.php
I don't have a logfile. For some reason ampache/apache2 didn't created one.

**Comment by Afterster** [comment]
Accordoing to your configuration, you didn't enabled debugging. Could you please try to investigate the issue on your side first and then come back here with additional structured information? Thank you!

**Comment by Arsimael** [comment]
Created the logfile. It says:
2015-12-28 11:31:56 [Arsimael] (Stream) -> Unable to play media currently locked by another user

How can I prevent the lock?

**Comment by Afterster** [comment]
Ok thank you. Then this is the excepted behavior if `Lock Songs` setting is enabled on Admin => Server Config => System. You should disable it for all users.

**Comment by Arsimael** [comment]
Perfect! Thanks! Now it's working. 

When is it recommended to activate this function?

**Comment by Afterster** [comment]
Great :).
Not sure why this feature was created at the beginning, it was here before me :smile:.
I believe this was implemented according to someone country law in the old ages. I keep it now as this can be useful depending your server bandwidth or the catalog type behind if not local. But it shouldn't be enabled by default.
