### ISSUE TITLE
Not able to list songs for albums / albums for artists with Mysql 5.7

### ISSUE THREAD

**Issue by JK2gUu-Ny9** [ampache/ampache#1078]
#### Versions:
mysql version: 5.7.10
ampache: Ampache 3.8.2-develop 4b44387

#### Problem:
After installing ampache, everything works as expected. After adding collections, artists and albums get displayed. However the artist view lists no albums/songs, and the album view lists no songs for this album.

In the debug log, the following errors get repeated:
```
(Dba) -> Error: ["42000",1055,"Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ampache.now_playing.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
(Dba) -> Error: ["42000",1055,"Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ampache.song.catalog' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
(Dba) -> Error: ["42000",1055,"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ampache.tag_map.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
(Dba) -> Error: ["42000",1055,"Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ampache.song.catalog' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
```

#### Pretty screenshots:
[Titles missing](https://cloud.githubusercontent.com/assets/8956925/12020196/dd46b1da-ad79-11e5-82db-07e779bc4779.png)
[Albums missing](https://cloud.githubusercontent.com/assets/8956925/12020197/dd4d8c44-ad79-11e5-8ac5-ed580163e72a.png)

**Comment by stebe** [comment]
This is probably related to this https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html
The workaround is to turn the new feature off http://www.mysqlfaqs.net/mysql-client-server-commands/what-is-sql-mode-in-mysql-and-how-can-we-set-it

You can check the current mode with SELECT @@sql_mode; and erase the new restricted mode with SET sql_mode = '';

**Comment by JK2gUu-Ny9** [comment]
`SELECT @@sql_mode;` returns:
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
as you stated.

after making the proposed changes and setting it to `STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`, the problem persists. Sadly, the log entries remain unaffected by the change.

**Comment by Afterster** [comment]
This is because you only did it for the active connection. You should edit `sql-mode` setting on my.ini file and remove `ONLY_FULL_GROUP_BY` from it, then restart mysql server.
That's said, commit d83bf5d1695b4aec707a81bf3f45890d0d5ef7fc should now fix all sql requests to be valid in this mode.
