### ISSUE TITLE
Subsonic API redirecting incorrect from SSL URL

### ISSUE THREAD

**Issue by kwenieroalt** [ampache/ampache#1080]
I have installed the 3.8.1 release and enabled the subsonic API and on http URLs it is working out of the box like it should with the Android Subsonic App. However if I change the URL to a https url then the playback of a song is not working. The rest is working fine.. (like selecting playlists etc.)

What I noticed is that the subsonic stream class rewrites the stream url to:
http://<my host url>:443/ampache/play/index.php?ssid=dd15954125710807212356d7f39c4030&type=song&oid=190&......

Notice the http:// and the :443/

I now hacked subsonic_api.class.php in the stream function to conditionally replace http:// into https:// if there is :443/ in the $url, but somehow  the protocol is not honored. To give you an indication where I fixed it at line 1014:

            if (Subsonic_XML_Data::isSong($fileid)) {
                $url = Song::play_url(Subsonic_XML_Data::getAmpacheId($fileid), $params, 'api', function_exists('curl_version'));
                // Hack to rewrite :443/ urls to https:// instead of http://
                if( strpos($url,":443/") !== false ) {
                        $url = str_replace("http://","https://",$url);
                }
            }

But obviously the play_url method should return https:// since I did my original request was on:
https://<my host url>/ampache/rest/stream.view

**Comment by Afterster** [comment]
I believe you have same issue when using https on web player? Could you check that `Forces Http play regardless of port` (force_http_play) is disabled for all users?

**Comment by kwenieroalt** [comment]
Hey there, 

It took me a while before I found the 'force http play'option in the
interface settings. But it was turned on by default. I was unaware of
the setting. Maybe this setting was enabled in the 3.6 release of the
Debian package. 

It now works fine even in https webplayer. Thanks! 

Greetings,

---
--
Roalt Zijlstra 

On 2015-12-31 10:30, Afterster wrote:

> I believe you have same issue when using https on web player? Could you check that Forces Http play regardless of port (force_http_play) is disabled for all users? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/ampache/ampache/issues/1080#issuecomment-168157245
