### ISSUE TITLE
Websocket not opening?

### ISSUE THREAD

**Issue by khionu** [ampache/ampache#1083]
I'm not able to connect, via the FQDN, or by a direct connection.
```
WebSocket connection to 'ws://REDACTEDIP:8100/' failed: Error during WebSocket handshake: Unexpected response code: 404
```

I followed [this guide](https://github.com/ampache/ampache/wiki/Broadcasts), opened the port before testing the direct connection, made sure the port was bound.... I'm dreadfully confused

[ampache.cfg.php](http://ghost.iamtrue.net/paste/y7bb3)
[nginx conf file](http://ghost.iamtrue.net/paste/o2pbw)

**Comment by Afterster** [comment]
Are you sure php libevent extension is installed and enabled? If not this will not work and you will get this kind of logs
```
2016-01-04 22:05:56 [ampache] (autoload) -> 'libev\EventLoop' not found! 
2016-01-04 22:05:56 [ampache] (autoload) -> 'libev\EventLoop' not found! 
2016-01-04 22:05:56 [ampache] (autoload) -> 'EventBase' not found! 
```

**Comment by khionu** [comment]
It looks like I didn't. How would I restart Ampache after installation?

**Comment by Afterster** [comment]
I don't understand, what do you mean by restart?

**Comment by khionu** [comment]
.... there were some process IDs attached to Ampache PHP files, and I wanted to know if there was a recommend way to soft-restart them?

**Comment by Afterster** [comment]
It's php, not really as far as I know :)

**Comment by khionu** [comment]
Ok, then, guess `kill` it is.

Reason I asked is because, while, yes, PHP is a scripting language, so is JS, and Node has `process.exit()` so I wasn't sure...
