### ISSUE TITLE
Ampache to Icecast tutorial outdated?

### ISSUE THREAD

**Issue by CuritzJT** [ampache/ampache#1086]
I think that the Ampache to icecast tutorial is outdated because of apache2 and icecast2 being the main ones now.
Any way i can still stream to icecast or shout?

**Comment by Afterster** [comment]
Are you talking about https://github.com/ampache/ampache/wiki/Ampache-on-Icecast? It is not outdated but just one way to do it :).

**Comment by ivandrago228** [comment]
Can anyone explain how to set up steam to icecast or shout?
I think manual outdated because 'Ices configuration' look different.
