### ISSUE TITLE
updating tags on flac files

### ISSUE THREAD

**Issue by tk421storm** [ampache/ampache#1087]
hello all!

I would like to use the tag cloud to organize my music library, and view it based on distinct folders I've setup. To do this, I'm writing an application that will make sure the genre tags on my albums are correct. So far I've tested updating genre tags on MP3s, and it successfully changes the "tag" in ampache.

I'm having trouble updating flac files, however. When I change the genre= metadata field (using metaflac on ubuntu) the tag doesn't update in ampache on any catalog function (add, verify, clean).

Any ideas why this might be true?

Thanks!
-Mike

**Comment by Afterster** [comment]
Which version are you using?
Is your tags correctly imported if you remove and recreate the catalog?
What give you demo.browse sample of [getID3](https://github.com/JamesHeinrich/getID3)?

**Comment by tk421storm** [comment]
Hey! Thanks for your response.

Currently I'm running 3.8.2-develop.

When I delete and re-create the catalog, the tag is correctly read.

I'm not sure how you use getID3, however metaflac gives me this result:

METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 16 bytes
  maximum framesize: 13631 bytes
  sample_rate: 44100 Hz
  channels: 2
  bits-per-sample: 16
  total samples: 11485992
  MD5 signature: 708599910502251bc27922e8e1d91a9d
METADATA block #1
  type: 3 (SEEKTABLE)
  is last: false
  length: 486
  seek points: 27
    point 0: sample_number=0, stream_offset=0, frame_samples=4096
    point 1: sample_number=438272, stream_offset=788866, frame_samples=4096
    point 2: sample_number=880640, stream_offset=1786788, frame_samples=4096
    point 3: sample_number=1318912, stream_offset=2774496, frame_samples=4096
    point 4: sample_number=1761280, stream_offset=3813130, frame_samples=4096
    point 5: sample_number=2203648, stream_offset=4895451, frame_samples=4096
    point 6: sample_number=2641920, stream_offset=6040138, frame_samples=4096
    point 7: sample_number=3084288, stream_offset=7179137, frame_samples=4096
    point 8: sample_number=3526656, stream_offset=8328720, frame_samples=4096
    point 9: sample_number=3964928, stream_offset=9535648, frame_samples=4096
    point 10: sample_number=4407296, stream_offset=10844672, frame_samples=4096
    point 11: sample_number=4849664, stream_offset=12159336, frame_samples=4096
    point 12: sample_number=5287936, stream_offset=13475411, frame_samples=4096
    point 13: sample_number=5730304, stream_offset=14771027, frame_samples=4096
    point 14: sample_number=6172672, stream_offset=15869916, frame_samples=4096
    point 15: sample_number=6610944, stream_offset=17003759, frame_samples=4096
    point 16: sample_number=7053312, stream_offset=18179710, frame_samples=4096
    point 17: sample_number=7495680, stream_offset=19392068, frame_samples=4096
    point 18: sample_number=7933952, stream_offset=20693950, frame_samples=4096
    point 19: sample_number=8376320, stream_offset=22032672, frame_samples=4096
    point 20: sample_number=8818688, stream_offset=23379212, frame_samples=4096
    point 21: sample_number=9256960, stream_offset=24714649, frame_samples=4096
    point 22: sample_number=9699328, stream_offset=26035318, frame_samples=4096
    point 23: sample_number=10141696, stream_offset=27309442, frame_samples=4096
    point 24: sample_number=10579968, stream_offset=28586880, frame_samples=4096
    point 25: sample_number=11022336, stream_offset=29786787, frame_samples=4096
    point 26: sample_number=11464704, stream_offset=30804496, frame_samples=4096
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 337
  vendor string: reference libFLAC 1.2.1 20070917
  comments: 11
    comment[0]: album=Nine Types of Light
    comment[1]: ALBUMARTIST=TV on the Radio
    comment[2]: artist=TV on the Radio
    comment[3]: DATE=2011
    comment[4]: title=Second Song
    comment[5]: TRACKNUMBER=01
    comment[6]: replaygain_album_gain=-9.13 dB
    comment[7]: replaygain_album_peak=0.992004
    comment[8]: replaygain_track_gain=-9.37 dB
    comment[9]: replaygain_track_peak=0.991852
    comment[10]: genre=Pop-IndieEuro
METADATA block #3
  type: 1 (PADDING)
  is last: true
  length: 8017

**Comment by Afterster** [comment]
Ok but using GetID3 would be more helpful for issue identification if any :). Could you do that? Or share a test file. Thank you.

**Comment by tk421storm** [comment]
Well, now I'm seeing the same problem on mp3 files.

If I create a catalog, it'll read in the genres as they are currently in the file. If I change the file's genre using a command line tool (id3v2 for mp3s, metaflac for flacs), and run "update catalog", the genre does not update in the database. Only deleting the catalog and re-creating it will show the update.

I'm not sure how to use getID3, isn't that a php function? I'm not familiar with php. Would printing out the results in the ampache gui be the same thing?

**Comment by tk421storm** [comment]
Here are the commands I'm using to update the genre tag via the command line:

id3v2 -g Pop-IndieEuro /path/to/file.mp3

flac is more complicated, I have to remove the "comment" for genre first, then add it back, since otherwise it'll just add another genre, and I only want each file to have one genre.

metaflac --remove-tag=genre /path/to/file.flac
metaflac --remove-tag=GENRE /path/to/file.flac
metaflac --set-tag=genre=Pop-IndieEuro /path/to/file.flac

If there's a better way to update the tags via the command line, maybe I should use that instead? I'm on ubuntu 14.04.

**Comment by wagnered** [comment]
If I may make a suggestion and you are not stuck on using a command-line
tool, you might try Easytag. It  should be in the Ubnuntu
distribution/repository.  If not, it's at
https://launchpad.net/~amigadave/+archive/ubuntu/ppa.

It allows single or batch editing.  For Genre, it has a drop down list
of the common ones and unique values can be manually added.

I used lib/vendor/james-heinrich/getid3/demos/demo.browse.php to see
what a specific flac file contained.  This would be what ampache uses.

I, myself, would never use a command-line tool to operate on more than
one file; way too tedious.

Ernie


On 01/29/2016 07:30 AM, tk421storm wrote:
> Here are the commands I'm using to update the genre tag via the command
> line:
> 
> id3v2 -g Pop-IndieEuro /path/to/file.mp3
> 
> flac is more complicated, I have to remove the "comment" for genre
> first, then add it back, since otherwise it'll just add another genre,
> and I only want each file to have one genre.
> 
> metaflac --remove-tag=genre /path/to/file.flac
> metaflac --remove-tag=GENRE /path/to/file.flac
> metaflac --set-tag=genre=Pop-IndieEuro /path/to/file.flac
> 
> If there's a better way to update the tags via the command line, maybe I
> should use that instead? I'm on ubuntu 14.04.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/1087#issuecomment-176816432>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by tk421storm** [comment]
Unfortunately my system is headless, so I don't think I can use easytag, as it looks gui-based.

For my purposes, a command line tool is perfect. In python, I've written a script that will iterate through all files in my folders, make sure they're tagged correctly, and if not, fix them. That part was easy!

With security settings on my apache, I can't seem to execute those demo scripts.

**Comment by tk421storm** [comment]
Running that script in the command line, i'm able to get this about one of the flac files:

MD5 Data Tags - vorbiscomment	 
Errors and Warnings - (blank)

**Comment by Afterster** [comment]
There was an issue on update from file when data are array (eg. genres). Fixed, thanks!

**Comment by tk421storm** [comment]
yay!!!! thanks so much :)
