### ISSUE TITLE
write_playlists produces hard-to-read filenames

### ISSUE THREAD

**Issue by yam655** [ampache/ampache#1088]
The default playlist name becomes an impossible-to-read mess with the regular expression that is used.

<pre>
6. yam65520151226231913.m3u
</pre>

Since spaces and dashes are universally supported by Linux, Mac OS X, and Windows, they should all be available. (Particularly being that spaces were <em>already</em> added to the file names.)

I'm attaching a change that will produce far better results:

<pre>
6. yam655 - 2015-12-26 23.19.13.m3u
</pre>

Adding the dash and the space as legal definitely helped out the most (and should make things better for the vast majority of folks). Converting the colon (<tt>:</tt>) to a period (<tt>.</tt>) allows the time to be easily legible when dealing with default playlists. (Even the "Foo: bar" case is better with "Foo. bar" than "Foobar" or "Foo- bar".)

My change also got rid of the needless escape of the period within the square brackets. The square brackets implicitly escape the period. (It makes no sense to have a wildcard in an explicit set of characters.) (Also note: the dash (<tt>-</tt>) ceases to have a special meaning when at the beginning or end of a square bracketed set of characters.)

While there is <a href="http://www.mtu.edu/umc/services/web/cms/characters-avoid/">room for improvement</a>, this change produces better results for everyone.

<pre>
diff --git a/bin/write_playlists.inc b/bin/write_playlists.inc
index ccfafd5..de0e3b1 100644
--- a/bin/write_playlists.inc
+++ b/bin/write_playlists.inc
@@ -68,7 +68,8 @@ foreach ($items as $item) {
     $name = $item->get_fullname();
     // We don't know about file system encoding / specificity
     // For now, we only keep simple characters to be sure it will work everywhere
-    $name = preg_replace('/[^a-zA-Z0-9\.]/', '', $name);
+    $name = preg_replace('/[:]/', '.', $name);
+    $name = preg_replace('/[^a-zA-Z0-9. -]/', '', $name);
     $filename = $dirname . DIRECTORY_SEPARATOR . $item->id . '. ' . $name . '.' . $ext;
     $medias = $item->get_medias();
     $pl = new Stream_Playlist(-1);
</pre>

**Comment by Afterster** [comment]
I agree with your changes and thanks for the explanation.
I could commit it myself but it would be better if you could create a pull request directly? Thank you.
