### ISSUE TITLE
[Translation ES] Wrong translations everywhere

### ISSUE THREAD

**Issue by malkavi** [ampache/ampache#1089]
Where can I change translations for spanish? I have changed things in transifex months ago, but they aren't used... 
At this moment the spanish version is unusable.

```
Examples:
msgid "Imports playlists."
msgstr "Borrar lista" (this means delete list)

msgid "- Channel "
msgstr "Salvar cambios" (Save changes) 
...
```

**Comment by Psy-Virus** [comment]
@Afterster? Could you please take a look at the Automation of [translation sync](http://docs.transifex.com/integrations/best-practices/) between Github and Transifex?

Github to transifex works but not vice versa.

We definitely need an automatic way.

Thank you :-)

**Comment by Psy-Virus** [comment]
@malkavi, you're right, the most translations are at least extremely outdated. And we still haven't an automatic sync from Transifex to GitHub. Please hang on. I hope we can discuss this here.

Thanks for your patience :-)

@Afterster? Could you please take a look at the Automation of [translation sync](http://docs.transifex.com/integrations/best-practices/) between Transifex and GitHub?

Github to transifex works but not vice versa.

We definitely need an automatic way.

Thank you :-)

**Comment by Afterster** [comment]
Yes translations are outdated on github repository and correctly fixed on Transifex.
@Psy-Virus automatic integration from Transifed to Git repository requires a server making the link. I tried [this](http://docs.transifex.com/integrations/github/) one year ago and it didn't work well. Feel free to give a try too and to setup a custom Amazon EC2 instance as explained.
For now the synchronization from Transifex to Git is manual. That means I'm waiting for your PR to update the translation :). Thank you.

**Comment by Psy-Virus** [comment]
Hey, sry for late reply...
>  I tried this one year ago and it didn't work well.

Oh sure, there was/is a link within our TF Project, I'm sorry.

I'll take a look into this Amazon thing the next days and if I don't get it to work, I maybe can script something to make it easier to maintenance it manually. There are tons of projects, maybe one of them is easy enough or at least well enough documented. :D

**Comment by Afterster** [comment]
Ok great, thanks as usual @Psy-Virus :)
During this time, maybe it could worth it if you could send a PR to merge all these language improvements? Don't you think it could worth it?

**Comment by Psy-Virus** [comment]
That was my intention but had not time, at time of writing, for it... but in the next hour maybe...

**Comment by Psy-Virus** [comment]
@Afterster, could you create a new project on transifex named ampachetest or only test or something? I do not have the permissions to create it. It would help me to figure out how the cli client for transifex works and I have not to create an own organization only for testing. I think the heaviest problem we have at the moment is simply that we have different directory structures on github and Transifex. It seems that the client cant work with different structures....

:-)

**Comment by Psy-Virus** [comment]
So, the PR is up.

**Comment by Afterster** [comment]
Ok thank you for your work here.
I looked on setting up a test repository but this would make Ampache profile a mess. I would prefer to keep Ampache organization as clean as possible to not misguide new people. You should do your test on a test user/repository on your side if you don't mind, sorry.

**Comment by Afterster** [comment]
Initial issue was that translation wasn't updated from Transifex. Still manual but not the case anymore, closing it.
