### ISSUE TITLE
SubSonic API Issue with Lighttpd

### ISSUE THREAD

**Issue by SadFool** [ampache/ampache#1090]
Hi All,

maybe you can help me.

I've got a Buffalo TeraStation III and am using the lighttpd server running on that for an Ampache 3.7.0 install. The lighttpd server is using php 5.2, therefore I have to stick to Ampache 3.7.0...

So, now I tried to use SubSonic API to access my library with iPhone etc, however:
Using SoundWaves, trying to access the server always results in "There was a problem with your request: Required Parameter is missing.".

So I have now 2 questions:

1. From looking at the wiki, is it possible that the URL rewrite is not complete? It seems that the /play/ directive, as in .htaccess, is not covered on the wiki...
2. Is there anything I could do - in case it's an issue fixed in v3.8.0 and above - to implement those changes without the need of fully upgrading? I cannot upgrade PHP on the TeraStation...

Cheers and thanks,

Marc

**Comment by Afterster** [comment]
1. I don't think so, you would get another error otherwise.
2. See https://github.com/ampache/ampache/commits/develop/lib/class/subsonic_xml_data.class.php and https://github.com/ampache/ampache/commits/develop/lib/class/subsonic_api.class.php history since May 26, 2014 and adapt the changes. But this will be difficult...

I don't think there is is simple solution here sorry.

**Comment by SadFool** [comment]
Thanks for pointing me into the right direction. In case someone has the same issue, here is what I did to get it working with PHP 5.2 and Ampache 3.7.0:

Replace the files with the ones from Ampache 3.8.1:
/rest/index.php
/lib/class/subsonic_api.class.php
/lib/class/subsonic_xml_data.class.php

Furthermore, as I'm using lighttpd, the following functions couldn't be found, as php versions below 5.4 don't know them:
apache_request_header()
http_response_code()

Following instructions on php.net, I just included below code on top of the subsonic_api.class.php:
```php
/* replacement function if not installed on apache */
if( !function_exists('apache_request_headers') ) 
{
	function apache_request_headers() 
	{
		$arh = array();
		$rx_http = '/\AHTTP_/';
		foreach($_SERVER as $key => $val) 
		{
			if( preg_match($rx_http, $key) ) 
			{
				$arh_key = preg_replace($rx_http, '', $key);
				$rx_matches = array();
				// do some nasty string manipulations to restore the original letter case
				// this should work in most cases
				$rx_matches = explode('_', $arh_key);
				if( count($rx_matches) > 0 and strlen($arh_key) > 2 ) 
				{
					foreach($rx_matches as $ak_key => $ak_val) 
					{
						$rx_matches[$ak_key] = ucfirst($ak_val);
					}
					$arh_key = implode('-', $rx_matches);
				}
				$arh[$arh_key] = $val;
			}
		}
		return( $arh );
	}
}

/* lower version of php do not support http_response_code */
if (!function_exists('http_response_code')) 
{
	function http_response_code($code = NULL) 
	{
		if ($code !== NULL) 
		{
			switch ($code) 
			{
				case 100: $text = 'Continue'; break;
				case 101: $text = 'Switching Protocols'; break;
				case 200: $text = 'OK'; break;
				case 201: $text = 'Created'; break;
				case 202: $text = 'Accepted'; break;
				case 203: $text = 'Non-Authoritative Information'; break;
				case 204: $text = 'No Content'; break;
				case 205: $text = 'Reset Content'; break;
				case 206: $text = 'Partial Content'; break;
				case 300: $text = 'Multiple Choices'; break;
				case 301: $text = 'Moved Permanently'; break;
				case 302: $text = 'Moved Temporarily'; break;
				case 303: $text = 'See Other'; break;
				case 304: $text = 'Not Modified'; break;
				case 305: $text = 'Use Proxy'; break;
				case 400: $text = 'Bad Request'; break;
				case 401: $text = 'Unauthorized'; break;
				case 402: $text = 'Payment Required'; break;
				case 403: $text = 'Forbidden'; break;
				case 404: $text = 'Not Found'; break;
				case 405: $text = 'Method Not Allowed'; break;
				case 406: $text = 'Not Acceptable'; break;
				case 407: $text = 'Proxy Authentication Required'; break;
				case 408: $text = 'Request Time-out'; break;
				case 409: $text = 'Conflict'; break;
				case 410: $text = 'Gone'; break;
				case 411: $text = 'Length Required'; break;
				case 412: $text = 'Precondition Failed'; break;
				case 413: $text = 'Request Entity Too Large'; break;
				case 414: $text = 'Request-URI Too Large'; break;
				case 415: $text = 'Unsupported Media Type'; break;
				case 500: $text = 'Internal Server Error'; break;
				case 501: $text = 'Not Implemented'; break;
				case 502: $text = 'Bad Gateway'; break;
				case 503: $text = 'Service Unavailable'; break;
				case 504: $text = 'Gateway Time-out'; break;
				case 505: $text = 'HTTP Version not supported'; break;
				default:
					exit('Unknown http status code "' . htmlentities($code) . '"');
				break;
			}

			$protocol = (isset($_SERVER['SERVER_PROTOCOL']) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.0');
			header($protocol . ' ' . $code . ' ' . $text);
			$GLOBALS['http_response_code'] = $code;
		} else 
		{
			$code = (isset($GLOBALS['http_response_code']) ? $GLOBALS['http_response_code'] : 200);
		}

		return $code;
	}
}
```

And now, my subsonic client (soundwaves on ios) is working perfectly!


Cheers,
Marc
