### ISSUE TITLE
LDAP authentication succeeding, but stuck on login page

### ISSUE THREAD

**Issue by Niols** [ampache/ampache#1091]
Hello,

I am trying to get LDAP authentication working with Ampache.
I have two problems.

#### Problem 1

This one is an Ampache bug I think. I should be able to provide a fix for it once I get a solution for my problem 2.
The [call to `ldap_read`](https://github.com/ampache/ampache/blob/9c3637b879026071fcd0617dc0376615830549de/lib/class/auth.class.php#L349) doesn't provide the [`member` attribute that is used later](https://github.com/ampache/ampache/blob/9c3637b879026071fcd0617dc0376615830549de/lib/class/auth.class.php#L366).
I would gladly rework this function, clean the code, provide a fix for this little problem, and maybe even for the [TODO goals in the comments](https://github.com/ampache/ampache/blob/9c3637b879026071fcd0617dc0376615830549de/lib/class/auth.class.php#L274).

#### Problem 2

This one is probably a problem coming from my instance, and probably an error in my configuration.
Without the `require_group` option, the LDAP authentication function is working. The logs seem not to complain about a failure in the authentication, and I tested the function out of ampache, and it's working.
My LDAP users cannot connect though (I come back on the login page).

Here is a successfull connection of a MySQL user (admin):
```
2016-01-12 11:51:54 [ampache] (session) -> Unable to read session from key t1gba1ut4q8tso2bqds7t7m5c7 no data found
2016-01-12 11:51:54 [ampache] (ldap_auth) -> ldap_search: (&(objectclass=organizationalPerson)(uid=admin))
2016-01-12 11:51:54 [admin] (session) -> Session created: 6h6vdlpoisd3ujsb83n6o2nqo3
2016-01-12 11:51:54 [admin] (autoupdate) -> Checking latest version online...
2016-01-12 11:51:54 [admin] (autoupdate) -> Checking latest version online...
2016-01-12 11:51:56 [admin] (session) -> 6h6vdlpoisd3ujsb83n6o2nqo3 has been extended to Tue, 12 Jan 2016 12:51:56 +0100 extension length 3600
2016-01-12 11:51:56 [admin] (session) -> Session created: 234501d8371f0423b72f2a4e7002ab3f
2016-01-12 11:51:57 [admin] (session) -> 6h6vdlpoisd3ujsb83n6o2nqo3 has been extended to Tue, 12 Jan 2016 12:51:57 +0100 extension length 3600
2016-01-12 11:51:58 [admin] (session) -> 6h6vdlpoisd3ujsb83n6o2nqo3 has been extended to Tue, 12 Jan 2016 12:51:58 +0100 extension length 3600
2016-01-12 11:51:58 [admin] (ajax.server.php) -> Called for page: {index}
2016-01-12 11:51:58 [admin] (session) -> 6h6vdlpoisd3ujsb83n6o2nqo3 has been extended to Tue, 12 Jan 2016 12:51:58 +0100 extension length 3600
2016-01-12 11:51:58 [admin] (ajax.server.php) -> Called for page: {index}
```

and here is an unsuccessfull connection of a LDAP user (niols):
```
2016-01-12 11:52:31 [admin] (session) -> 6h6vdlpoisd3ujsb83n6o2nqo3 has been extended to Tue, 12 Jan 2016 12:52:31 +0100 extension length 3600
2016-01-12 11:52:31 [ampache] (session) -> Unable to read session from key fj2lblv3s207qe3a6iplmh5fb1 no data found
2016-01-12 11:52:54 [ampache] (session) -> Unable to read session from key fj2lblv3s207qe3a6iplmh5fb1 no data found
2016-01-12 11:52:54 [ampache] (ldap_auth) -> ldap_search: (&(objectclass=organizationalPerson)(uid=niols))
2016-01-12 11:52:54 [ampache] (session) -> Session created: hin2r9a2a90qbrarfcuk928ev3
2016-01-12 11:52:54 [ampache] (session) -> Unable to read session from key 5eeleir34mk3dgvf5a84vpt536 no data found
```

I can see the `(session) -> Session created: hin2r9a2a90qbrarfcuk928ev3` message. I guess its meaning is that I am now connected. But I'm not. Or at least I'm redirected to login page again and again.

I can see all the `Unable to read session from key ... no data found` messages. That might be the source of the problem, but I have no idea of what is causing them to appear.

Here are the relevant parts of my config file:
```
; Auth Methods
; This defines which auth methods Auth will attempt to use and in which order.
; If auto_create isn't enabled the user must exist locally.
; DEFAULT: mysql
; VALUES: mysql,ldap,http,pam,external,openid
auth_methods = "ldap,mysql"

;#########################################################
; LDAP login info (optional)                             #
;#########################################################

; LDAP filter string to use (required)
; For OpenLDAP use "uid"
; For Microsoft Active Directory (MAD) use "sAMAccountName"
; DEFAULT: none
ldap_filter = "uid"
;ldap_filter = "(sAMAccountName=%v)"

; LDAP objectclass (required)
; OpanLDAP objectclass = "*"
; MAD objectclass = "organizationalPerson"
; DEFAULT null
ldap_objectclass = "organizationalPerson"

; Initial credentials to bind with for searching (optional)
; DEFAULT: none
;ldap_username = ""
;ldap_password = ""

; Require that the user is in a specific group (optional)
; DEFAULT: none
;ldap_require_group = "cn=B6,ou=groups,dc=niols,dc=fr"

; This is the search dn used to find users (required)
; DEFAULT: none
ldap_search_dn = "ou=people,dc=niols,dc=fr"

; This is the address of your ldap server (required)
; DEFAULT: none
ldap_url = "ldap://localhost/"

; Attributes where additional user information is stored (optional)
; OpenLDAP ldap_name_field = "cn"
; MAD ldap_name_field = "displayname"
; DEFAULT: none
ldap_email_field = "mail"
ldap_name_field  = "cn"
```

I a using nginx (`nginx version: nginx/1.6.2`).

Any help would be greatly appreciated, since I have no idea of how to solve this problem.

I stay available as much as possible.

**Comment by Afterster** [comment]
I cannot help here, I don't have such environment and it is always a pain to test it for me.
Could some LDAP users give a hand? @T-Rock @consolidation @kahlb @Jeffsninja? Thanks!

**Comment by Niols** [comment]
I know LDAP well enough to debug this part, I think.
I still need to know where all these `(session) -> Unable to read session from key ... no data found` come from, what they do mean, etc.
Thanks for your help anyway!

**Comment by Niols** [comment]
Yep, I confirm, the LDAP auth returns correctly a `{"success":true,"type":"ldap","username":"niols"}` array. The problem comes after, in here:

```
2016-01-14 09:22:24 [ampache] (session) -> Session created: tq0au1om9ctpr9thqcfi8pk666
2016-01-14 09:22:24 [ampache] (session) -> Unable to read session from key smu3ubottfm004nptogdg7s5h7 no data found
```

**Comment by Afterster** [comment]
`Session created: tq0au1om9ctpr9thqcfi8pk666` => a new session was created and stored on database
`Unable to read session from key smu3ubottfm004nptogdg7s5h7 no data found` => this session didn't exists.

As you can notice, you don't have the same key for the created session and the one you got an error. I believe the first one is created but not stored correctly on user computer, and the second one is the old one stored on cookie. Investigation required anyway here.

**Comment by Niols** [comment]
OK, so these keys are stored in a cookie I suppose.
I'll do some digging and report when I have more information

**Comment by Niols** [comment]
@Afterster I got it!

The authentication system is working correctly.
The problem is that, when the user try to access the `index.php` page, he is automatically logged out.

This comes from `lib/init.php`:

    /* Create the new user */
    $GLOBALS['user'] = User::get_from_username($_SESSION['userdata']['username']);

    /* If the user ID doesn't exist deny them */
    if (!$GLOBALS['user']->id && !AmpConfig::get('demo_mode')) {
        Auth::logout(session_id());
        exit;
    }

The `User::get_from_username` function is right here:

    /**
     * get_from_username
     * This returns a built user from a username. This is a
     * static function so it doesn't require an instance
     */
    public static function get_from_username($username)
    {
        $sql        = "SELECT `id` FROM `user` WHERE `username` = ?";
        $db_results = Dba::read($sql, array($username));
        $results    = Dba::fetch_assoc($db_results);

        $user = new User($results['id']);

        return $user;
    } // get_from_username

Obviously, the LDAP user is not in the SQL database (I checked), so `$results` doesn't have an index `id`. The logs are agreeing with me on that point:

    2016-01-14 15:27:55 [ampache] (PHP) -> [Warning] Undefined index: id in file /path/to/ampache/l
ib/class/user.class.php(268)

An empty user is returned:

    User: {"id":null,"username":null,"fullname":null,"fullname_public":null,"access":null,"disabled":null,"email":null,"last_seen":null,"create_date":null,"validation":null,"website":null,"state":null,"city":null,"apikey":null,"prefs":[],"playlist":null,"f_name":null,"f_last_seen":null,"f_create_date":null,"link":null,"f_link":null,"f_useage":null,"ip_history":null,"f_avatar":null,"f_avatar_mini":null,"f_avatar_medium":null}

The test `if (!$GLOBALS['user']->id && !AmpConfig::get('demo_mode')) {` in `lib/init.php` fails, and the user is logged out.

I wonder how the other Ampache instances using LDAP can even work. A comment from the people in your first comment would be interesting.

I don't know how it could be fixed though, since I don't really get how the whole machinery is working. I just traced back the call until I found the responsible.

**Comment by T-Rock** [comment]
You need to activate "auto_create", so that the users, who are authenticated by LDAP, are created as a user in the database and then the standard authentication from ampache works.

ampache.cfg.php:
auto_create = "true"

Maybe you also want to change the setting "auto_user" from "guest" to "user".

**Comment by Niols** [comment]
Yes, indeed, I finally figured that out.
But as it is written in the configuration, it does not appear as a required thing, more like a bonus.

Thanks anyway. I'll probably propose a PR in the nexts days to add the support for LDAP servers that doesn't give the members to the `ldap_read` function.

I can now close this.
