### ISSUE TITLE
catalog_update.inc and api keys

### ISSUE THREAD

**Issue by Kallys** [ampache/ampache#1092]
Hi guys !

Ampache is such a powerful tool and I really want to congratulate you for that.

I currently encounter some problems with api keys using the bin/catalog_update.inc script.
For example, tvdb_api_key and tmdb_api_key aren't found when I'm using this script (logs are explicit), whereas everything is fine when I'm using the web interface.

I've watched in concerned plugins files, and it seems that api_key are loaded in the load() function using the $user var. My guess (but I'm not really aware about how ampache works) is that this $user var is empty when I'm running the catalog_update.inc script (otherwise, which user should be used ?).

Moreover, it seems that if I put the api key using the web admin pannel, api key aren't stored in my SQL db nor any file (I guess it's serialize somewhere ?).

Is it a bug or a misconfiguration ?

Thanks !

**Comment by Afterster** [comment]
You're right about user related settings. Those are stored inside database. If you want to make it available by default, you need to change the settings under Admin => Server Config => Plugin and check the box `Apply to All`.

**Comment by Kallys** [comment]
Hum, I've retried but this is not solving my issue.
Perhaps this is a server misconfiguration on my side but checking this box does nothing for me. Does the checkbox should remain checked after saving preferences (not my case) ?

I also tried to manually insert my key in dabatase in 'preference' table (the line was here but empty) but still not working.

2016-01-13 20:48:09 [ampache] (Tvdb) -> No Tvdb api key, metadata plugin skipped 

Thanks for your answer !

PS: I'm on the latest develop build.

**Comment by Frank12B** [comment]
I can see the same error with discocogs metadata plugin while using cli for catalog update:
```
2016-01-23 16:42:19 [ampache] (Discogs) -> No Discogs api key, metadata plugin skipped
2016-01-23 16:42:19 [ampache] (update) -> /media/e8c39db6-00db-45f1-852d-8b5c3d1f15f4/Daten/Musik/Deichki$
2016-01-23 16:42:19 [ampache] (tag-read) -> Reading tags from /media/e8c39db6-00db-45f1-852d-8b5c3d1f15f4$
2016-01-23 16:42:19 [ampache] (vainfo) -> Cleaning id3v1
2016-01-23 16:42:19 [ampache] (vainfo) -> Cleaning id3v2
```

Consumer key and secret are actual and set in webui.

**Comment by lachlan-00** [comment]
I've had a look and it's loading with a null user so will never update.

I'll add a check to load the system user instead when it doesn't have one.
