### ISSUE TITLE
Default Columns and filters. 

### ISSUE THREAD

**Issue by bozo83** [ampache/ampache#1097]
Hey, firstly, what an awesome piece of kit this is. Got this hosted on my webserver with all my files sitting in cloud storage. My own mini Spotify with just the content I want. Truly beautiful. Secondly this is not really an issue just a personal preference that I hoped you might be able to help with?

I've had a quick look through some of the php and I just can't seem to make my preference the default, I imagine it's being called from Javascript?! 

Anyway, here's what I'd like to do, is it possible?

When viewing the list of artists I would like the default filter being set to "infinite scroll" site wide not just for one login. Currently on this laptop it remembers my choice however when I move to another laptop I then have to select it again. Other users also have to select it to change. Is there a way I can make "infinite scroll" the default rather that "pages". 

The other one is default Columns. In artist list, album list and search pages I'd like to have "tags" on for instance but then on an album page I'd like to have tags turned off by default. Again, site wide for all users. Is this something that is possible? 

As I say, I've had a look in a few of the php and I just can't seem to figure it out, I can remove the "tag" output, but the column header remains as does the selectable options. Thanks for your help.

**Comment by Afterster** [comment]
All this `view` options you described are done client side and stored on cookie. That's why it cannot be setup globally.

**Comment by bozo83** [comment]
That's what I thought. No problem. Thanks for getting back to me. I'll close this now.
