### ISSUE TITLE
Web player song list uses absolute positioning and percentage width

### ISSUE THREAD

**Issue by nearwood** [ampache/ampache#1102]
The jp-playslist div:

    <div class="jp-playlist" style="position: absolute;">

uses absolute positioning and the theme css, jplayer.midnight.black.css:467:

    div.jp-playlist {
	    width: 100%;
        ...
    }

Which causes it to take 100% of the window width while being offset to the right by the album art, etc. divs. This causes scroll bars to be permanently displayed, making it more-or-less impossible to use the right-most controls (remove button, playlist scrollbar).

Removing the 'position: absolute' style attribute from the HTML fixes it for me.

Chrome 47.0.2526.111 m
Ampache 3.8.2 develop (commit 42778955550b9edb716ce45dcf078b8de2bff184), but I've been experiencing this since ... 3.7?

**Comment by nearwood** [comment]
![image](https://cloud.githubusercontent.com/assets/1929778/12452328/e4d89280-bf5b-11e5-8c8a-69136f1f9586.png)

**Comment by Afterster** [comment]
Thanks @nearwood and thanks for the associated PR #1103. I got your point, but unfortunately the proposed solution cannot be accepted as it will only work if player is started on new window (=if you're not using ajax loading). Could you try to suggest a fix that handle both case? That would be great, thanks!

**Comment by nearwood** [comment]
Ooh, the ajax loading is fancy now--I forgot I had disabled it a while back. I have submitted a new pull request with additional changes to keep the ajax player intact. Sorry, I am trying to familiarize myself with the codebase.
