### ISSUE TITLE
PHP: AmpacheAPI not found while creating remote catalog over Internet connection

### ISSUE THREAD

**Issue by Frank12B** [ampache/ampache#1105]
Hello,
I was trying to connect two ampache-server instances over the Internet and got the following error in the Web GUI: Server-Sent Events connection error. Re-connection... and nothing ever happens. Both servers are secured with ssl (self signed certificate).

Log outputs:
Nginx-log: (always this one error shows up)
*596 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'AmpacheApi\AmpacheApi' not found in /var/www/ampache/modules/catalog/remote/remote.catalog.php on line 195" while reading upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /server/sse.server.php?worker=catalog&action=add_to_catalog&catalogs=a%3A1%3A%7Bi%3A0%3Bs%3A1%3A%221%22%3B%7D HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "127.0.0.1", referrer: "https://127.0.0.1/index.php"

Ampache-debug lvl 5 log:
2016-01-21 10:55:29 [admin] (session) -> s6o1t1rurpg73j94cpdmvjugh6 has been extended to Thu, 21 Jan 2016 11:55:29 +0100 extension length 3600
2016-01-21 10:55:29 [admin] (autoload) -> 'AmpacheApi\AmpacheApi' not found!
2016-01-21 10:55:29 [admin] (autoload) -> 'AmpacheApi\AmpacheApi' not found!
2016-01-21 10:55:32 [admin] (session) -> s6o1t1rurpg73j94cpdmvjugh6 has been extended to Thu, 21 Jan 2016 11:55:32 +0100 extension length 3600
2016-01-21 10:55:32 [admin] (autoload) -> 'AmpacheApi\AmpacheApi' not found!
2016-01-21 10:55:32 [admin] (autoload) -> 'AmpacheApi\AmpacheApi' not found!

Setup:
Server outside: Debian 7, ngix, php5-fpm, mysql-server 5.5
php -i|grep ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
openssl

Remote Server: Elementary Os (Ubuntu 14.04), nginx, php5-fpm, mysql-server 5.6 
php -i|grep ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
openssl

On both servers ACLs were made according to https://github.com/ampache/ampache/wiki/API-RPC
I used my dyndns as path for the remote catalog.

I would be happy if anyone could help me!

Thanks in advance,

Frank

**Comment by Afterster** [comment]
Looks like the dependency is missing. It was recently moved to an independent repository. Is your composer dependencies up to date? Try to run `composer install` again.

**Comment by Frank12B** [comment]
Seems that everything is up to date:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files

thx for the fast reply!

**Comment by Afterster** [comment]
Looks like there was an issue with latest changes since the move to another git repository.
Could you try again with latest changes and after a new `composer install`? Thanks.

**Comment by Frank12B** [comment]
Remote catalog shows up now and songs can be played. Thank you. 
I noticed that in the development branch additional_genre_delimiters work but not in the master branch.
