### ISSUE TITLE
FLAC files only showing one genre

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#1106]
It appears that Vorbis Comments support multiple genres by having a separate GENRE tag for each genre.  The current DEV build of Ampache looks like it's only displaying the first genre tag and ignoring the ones after it.  I have a multi-genre tagged album, and when I look at it in Ampache in album view, I only see the first genre tag.  The other genre tags are not in the tag cloud either.

**Comment by Afterster** [comment]
I believe this is not on FLAC only but because of bugged update 380003 when initially committed.
Try to remove `UNIQUE_TAG_MAP` constraint on `tag_map` table and recreate it with
```
ALTER IGNORE TABLE `tag_map` ADD UNIQUE INDEX `UNIQUE_TAG_MAP` (`object_id`, `object_type`, `user`, `tag_id`)
```

**Comment by apastuszak** [comment]
How do I do that?

**Comment by Afterster** [comment]
Through SQL directly (using phpmyadmin for instance). Otherwise try to recreate the database just for test purpose.

**Comment by stebe** [comment]
@apastuszak you need to look at the relation view of the tag_map table in phpmyadmin and drop the unique_tag_map index, then in the SQL window replace what is shown with the code posted above to recreate the key.

![screenshot from 2016-01-22 07-28-24](https://cloud.githubusercontent.com/assets/4076671/12510729/097a2f52-c0da-11e5-8f41-fbcf078e606f.png)
![screenshot from 2016-01-22 07-34-22](https://cloud.githubusercontent.com/assets/4076671/12510819/9cc923c6-c0da-11e5-91b1-882ac72fa873.png)

**Comment by Afterster** [comment]
Can this be closed @apastuszak?

**Comment by apastuszak** [comment]
Give me till Monday and I will let you know.  Not home this weekend to 
test.  if you don't hear from me on Monday, you can close it.

**Comment by Niols** [comment]
Hey, @apastuszak, can this be closed now?

**Comment by apastuszak** [comment]
Close it. I never got to test. I don't want to.leave it out there.
