### ISSUE TITLE
VLC Unable to open the MRL

### ISSUE THREAD

**Issue by 4warded** [ampache/ampache#1110]
When I have set up the VLC http settings and everything seems to work fine until I start to play the audio. The message I get is:

VLC is unable to open the MRL 'http://ampache.DOMAIN.net/play/type/song/oid/84/uid/name/SONG_NAME.EXTENSION'

All of my music is stored in /music, so I don't know why it is pointing there.

**Comment by Afterster** [comment]
The url looks this way because of url rewriting.Try to access the provided URL directly with your browser. If working, then try to load it manually on vlc, if not, check /play/.htaccess generated rewrite rules.

**Comment by 4warded** [comment]
If I go to the URL I get a 404 error page, my .htaccess.dist (nginx) looks like this:
![image](https://cloud.githubusercontent.com/assets/16733449/12621165/39d761e2-c517-11e5-877f-ba3b1c673436.png)

**Comment by Afterster** [comment]
If you're using Nginx then you should adapt these url rewrite rules to Nginx.
You can find a sample nginx config for Ampache here (could be not exhaustive, feel free to edit the wiki if not):
https://github.com/ampache/ampache/wiki/Installation#nginx

**Comment by 4warded** [comment]
I have already followed that guide and I am using that config already

**Comment by Afterster** [comment]
It is url rewriting issue otherwise you would not get 404. Check your nginx config for Ampache.

**Comment by 4warded** [comment]
I set it up using the wiki:
https://github.com/ampache/ampache/wiki/Installation#nginx

**Comment by Afterster** [comment]
This wiki chapter was done by contributors. Not sure it will work just with copy/past. Some nginx adaptation specific to your environment could be required here. I will let your issue open a few weeks in case another nginx user would like to give you a short help. Please post the solution here once you find out so that it could benefits others. Good luck!

**Comment by Afterster** [comment]
Nginx rewrite rule issue. Already discussed several time, and even in currently open threads #1062. Closing this as duplicate.
