### ISSUE TITLE
x246 mp4 video does not play in Firefox, Opera

### ISSUE THREAD

**Issue by tcpie** [ampache/ampache#1114]
I have placed an x246 mp4 video file in my catalog. When I try to play this video through the web interface with Firefox 44.0 and press the play button, the play button changes to a pause button, but the video playback screen remains black. After less than 1s, the pause button changes back to a play button again.

The issue with Opera 34.0 is similar, though slightly different. When pressing the play button, a seek bar appears underneath the black display window, and turns blue momentarily. The starting time is listed as 0:00, the ending time as 0:00 as well. Then, like Firefox, the play button changes back to a pause button.

Firefox should support x246, aka h246 (https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox#w_supported-formats). I can play h246 video on other webpages (ex: http://camendesign.com/code/video_for_everybody/test.html)

When I use Chrome, the video plays back perfectly, so that is not the issue.

**Comment by Afterster** [comment]
Could be a configuration issue. Anything on logs?

**Comment by Afterster** [comment]
Any new @tcpie? Is the camendesign video working on firefox the one you're trying on Ampache too (should be to be relevant)?

**Comment by lachlan-00** [comment]
old enough that it's probably out of date now.

Videos aren't greatly supported still though
