### ISSUE TITLE
Upload name prefix to file

### ISSUE THREAD

**Issue by strikerlord** [ampache/ampache#1115]
when a user uploads a song there is a prefix added to the file;
##########_[original filename]
![filename prefix](https://cloud.githubusercontent.com/assets/15890009/12695415/b46dba04-c74d-11e5-8cd1-ede0d9cbe95a.jpg)

is there any way to fix this since this is also showing in ampache?
I tried looking for closed issues and php related prefix settings but to no avail.

**Comment by Afterster** [comment]
Should be handled #1010. Duplicate then :).

**Comment by strikerlord** [comment]
just as a remark, 1010 is about the map structure, this is the filename structure. As long as it's covered im good :).
