### ISSUE TITLE
Fast-Forwarding not working with .flac-files

### ISSUE THREAD

**Issue by zaphbbrox** [ampache/ampache#1116]
I noticed that I'm not able to fast-forward flac files while listening via the Web-Client. It works with other file types. Not a big problem for me, because I barely fast-forward a song but maybe someone else like to do it so I decided to report this.

**Comment by Afterster** [comment]
This is due to Aurora decode or on-the-fly transcoding (depending what you're using). It was discussed several time on other issues and cannot be handled at Ampache side as far as we know.
