### ISSUE TITLE
Podcast file naming issue

### ISSUE THREAD

**Issue by calcmandan** [ampache/ampache#1118]
Excited of the new features, I updated to latest. Per directions I enabled podcasts and rss in ampache.cfg.php. In which, I began subscribing to my favorite podcasts.

They download their lists just fine, and when I select a podcast to sync, it does the download but appends a bunch of extra info into the filename.

So, for isntance, I subscribe to the 60 minutes podcast and the latest file downloaded into the catalog is: 3026-1AQWD_3.MP3?show=60+Minutes&category=News+%26+Politics&callsign=PlayIt&market=national&awCollectionId=831&awEpisodeId=589848

So I attempt to play it but it won't. Shouldn't it be simply 3026-1AQWD_3.MP3? 
or even
3026-1AQWD_3.MP3?show=60+Minutes&category=News+%26+Politics&callsign=PlayIt&market=national&awCollectionId=831&awEpisodeId=589848.mp3?

Not sure what I should do from here. Thanks.

**Comment by calcmandan** [comment]
I started over again by killing the catalog and specifying only %o for filename pattern and no changes. It still appends all the extra stuff after .mp3

**Comment by calcmandan** [comment]
I'd like to confirm that this doesn't effect ALL podcasts. I've added a few more in the ensuing days and, upon sync, it downloads the mp3 fine without appending to the filename.

Three subscriptions, for instance, work fine:
http://extratimeradio.buzzsprout.com/947.rss
http://www.davidbarrkirtley.com/podcast/geeksguideshow.xml
http://feeds.feedburner.com/freakonomicsradio

Here are a few which have problems:
http://www.cbsradionewsfeed.com/rss.php?id=90
http://www.newstalk910.com/podcast/ang2011.xml
http://feeds.feedburner.com/PennSundaySchool/

**Comment by Afterster** [comment]
Indeed, this is an issue due to query string. I will fix it, thanks!
