### ISSUE TITLE
Some songs not playing with new version

### ISSUE THREAD

**Issue by Khymick** [ampache/ampache#1128]
Hi there,

I have installed 3.8.0-devel and 3.8.2-devel on my server and I want to use rhythmbox as client. With 3.8.0-devel, all works fine. With 3.8.2-devel, some songs are not displayed at all by rhythmbox, but playback generally works.

As the client with the ampache plugin is exactly the same, I wonder what did change from version 3.8.0-devel to 3.8.2-devel that makes it impossible to get all songs.

If you need more info. let me know, I will provide it.

**Comment by Afterster** [comment]
So if I understand correctly the songs are available on Ampache web interface but not on external app? Is both application using Ampache API here?
If so please try to found a faulty audio file and send it to me for testing. Could be related to new metadata on API.

**Comment by Khymick** [comment]
Yes, that is correct. Mail sent as PM.

**Comment by Afterster** [comment]
Ok but I didn't get your test file.

**Comment by Khymick** [comment]
Do you have any limitations on attachment size or similar?

Von meinem iPhone gesendet

**Comment by Afterster** [comment]
Ok got it thanks.
Works on my side with all Ampache android players I tested (Just Player, Lullaby 4 Ampache, ...).
Seems related to a rhythmbox-ampache issue.

**Comment by Khymick** [comment]
Hi,

I think that this may be the cause, but unfortunately, I didn't get any feedback from any developer of the plugin. As for now, I think it would help to understand if there were some changes in the API of Ampache, as the plugin works fine with elder version. I didn't find any suspicious changes in change logs. Did I possibly missed something here?

Greets,
Michael

**Comment by Afterster** [comment]
Fixed by yourself. Visitors, see https://github.com/lotan/rhythmbox-ampache/issues/6 for explanation.
