### ISSUE TITLE
How-to: update catalogs for podcasts

### ISSUE THREAD

**Issue by calcmandan** [ampache/ampache#1129]
I've enabled podcasts as of last week. They were all downloaded upon adding them. I read in issue #30 that a cron job has to be added for it to audo-update the catalog for podcasts to download automatically. Fair enough. In the meantime, though, manually updating the catalog isn't fetching fresh podcasts for those already subscribed. Have I missed something?

I followed all the directions on the wiki for enabling the podcasts and someone else mentioned having this problem, but issue #30 is closed.

**Comment by Afterster** [comment]
Fixed with 41a6769c2db301a327fe85daa3e821bded8c1b9b. Thanks.
