### ISSUE TITLE
Version 3.8.2 / Catalog build

### ISSUE THREAD

**Issue by maelange** [ampache/ampache#1130]
Dear devs,

Let me tell you thanks for your work on this project.

It seems to exist a problem on 3.8.2 version, when building a catalog; when i use a completly new installation and database with this version, mbid of artist is fill with musicbrainz_artistid not with musicbrainz_albumartistid . As a consequence, I have a lot of duplicated artists (cause musicbrainz_artistid is a multi values string in case of featuring).

I hope details I give are understandable (I am not fluent in english).

Mael

**Comment by Afterster** [comment]
The code related to this behavior is:

```
        $albumartist_id = null;
        if (!isset($results['albumartist_id'])) {
            if ($albumartist) {
                $albumartist_id = Artist::check($albumartist, $albumartist_mbid);
            }
        } else {
            $albumartist_id = intval($results['albumartist_id']);
        }
        $artist_id = null;
        if (!isset($results['artist_id'])) {
            $artist_id = Artist::check($artist, $artist_mbid);
        } else {
            $artist_id = intval($results['artist_id']);
        }
```

That means album artist is always first and you could have a different artist per song on the same album, which is excepted.
But there is indeed an issue with featuring. Multiple mbid string is not supported as long #347 is not handled. As long it is not supported, I will do a change to only take care about the first mbid on multi artist songs.

**Comment by maelange** [comment]
It is what i have understood. Thank you for preparing to change your code in the aim of keep only the first mbid on featuring track.

Have you an idea of why 
-with 3.8.1, featuring tracks create artists duplicates in database (same artist name, several mbid strings) but only the first one is shown in artist view
- with 3.8.2 featuring tracks create artists duplicates in database (same artist name, several mbid strings)and all of them are listed in artists view
This difference is not a regression?
I had to reinstall 3.8.1 in order to have something useable with my collection (30000 tracks)

Mael

**Comment by Afterster** [comment]
Yes that's because with 3.8.2 Ampache start to trim `feat.` from artist name, and just ignore everything after feat. as long #347 is not handled to add relations. Then you can result to duplicates name with different mbid.
I will close your issue here as it will be handled with #347, but thanks for the report.
