### ISSUE TITLE
FTP plugin

### ISSUE THREAD

**Issue by nasariasl** [ampache/ampache#1135]
hi,
 i need to add catalog file from FTP but till now ampache dont support FTP ! I hope to soon be added ّFTP plugin .

**Comment by arnaudbey** [comment]
hey, maybe you could mount your remote FTP locally ?

**Comment by nasariasl** [comment]
TNX "arnaudbey "  , Do you have ideas for Cpanel web hosting control panels ?

**Comment by nasariasl** [comment]
To reduce the server load and increase the speed of loading pages
Audio and video files must be downloaded and loaded from external auxiliary space such as "FTP".
For example, look at the YouTube website carefully
Website YouTube as a media server to increase the efficiency and speed of loading pages uses from multiple subdomains and multiple auxiliary spaces behind the scenes to load music and video.

**Comment by Afterster** [comment]
Indeed this should be handled php (Ampache) side but. We will not add additional catalogs type to the existing one (remote, local, beets ; subsonic, soundcloud and dropbox are keep as example) which give enough support by themselves already :smile:.
Preferred method is the one described by arnaud but feel free to create and maintain a new /modules/catalog/ftp as your own ampache plugin project.
