### ISSUE TITLE
wave form generate :error -i : make sure you typed name correctly

### ISSUE THREAD

**Issue by nasariasl** [ampache/ampache#1136]
//when open a new song page to generate waveform , Ding error notification sound is heard from the windows server :
![dash-i](https://cloud.githubusercontent.com/assets/17225652/13036791/8ff558e0-d386-11e5-9933-3cee0ca591b2.PNG)
//then in the page The result will show  in black color
![wave-black-blank](https://cloud.githubusercontent.com/assets/17225652/13036802/02b44d14-d387-11e5-9bf6-bb5bcc988c97.PNG)

**Comment by Afterster** [comment]
The error is explicit enough, looks like your transcode settings doesn't match your environment (`transcode_input = "-i %FILE%"` I believe but your ffmpeg/avconv version doesn't know this parameter).
Proper transcode configuration is required for waveform generation feature.
