### ISSUE TITLE
Batch download: URL generated wrongly

### ISSUE THREAD

**Issue by henryford** [ampache/ampache#1137]
Hi,

when using the album-browser, currently the URL is generated wrongly. This is because there is a missing "/" in the code:
`templates/show_album_row.inc.php:            <a rel="nohtml" href="<?php echo AmpConfig::get('web_path') ?>batch.php?action=album&<?php echo $libitem->get_http_album_query_ids('id') ?>">`

when changing it to:
`<a rel="nohtml" href="<?php echo AmpConfig::get('web_path') ?>/batch.php?action=album&<?php echo $libitem->get_http_album_query_ids('id') ?>">`

it works again. Not that good with github - didn't want to make a PR for just a single char ;)

**Comment by Afterster** [comment]
Fixed, thanks ;)
