### ISSUE TITLE
update button in Some of the pages are not displayed

### ISSUE THREAD

**Issue by nasariasl** [ampache/ampache#1138]
![hidden button](https://cloud.githubusercontent.com/assets/17225652/13063629/54aa58ec-d45f-11e5-91c9-c4d6227cdaba.PNG)

**Comment by nasariasl** [comment]
Resolved ! With change web server

**Comment by Afterster** [comment]
That looks related to your web server, timing out before completion. Feel free to reopen the issue if you cannot fix it, and if you can provide accurate information (logs, ...).
