### ISSUE TITLE
Unable to Broadcast 

### ISSUE THREAD

**Issue by poshwosh** [ampache/ampache#1140]
I've spent hours trying to figure this out to no avail. I'm not so knowledgeable in this field you see, but I really do want to get it to work. I understood the broadcast feature works exactly like Grooveshark's broadcast system and I've been looking for an alternative since! So you can imagine how determined I am to get this to work, I'm really desperate for it, haha.  

My problem is when other users try to connect to a broadcast, their player is filled with a blank song. 

This is what I've done so far:

- I'm running ampache on WAMP 2.5 x32 (PHP 5.5) on Windows 7 x64
- I placed php_libevent.dll into php\ext and added it php.ini
- In httpd.conf I enabled proxy_wstunnel_module
- I also enabled mod_proxy.so and mod_proxy_http.so which got me a step further thanks to a [web article](https://confluence.atlassian.com/doc/using-apache-with-virtual-hosts-and-mod_proxy-173685.html)
- I enabled Include conf\extra\httpd-vhosts.conf so I could use vhosts
- In apache\conf\extra\httpd-vhosts.conf I added this:
```
<VirtualHost *>
ProxyPass /ws ws://127.0.0.1:8100 retry=0
ProxyPassReverse /ws ws://127.0.0.1:8100 retry=0
ProxyRequests off
ProxyTimeout 15
</VirtualHost>
```
- In ampache\config\ampache.cfg.php I turned broadcast on and replaced the websocket address with websocket_address = "ws://localhost/ws" as according to the [wiki article](https://github.com/ampache/ampache/wiki/Broadcasts).
- I ran CMD, typed "cd S:\wamp\www\ampache\bin" then "php websocket_run.inc -p 8100 > nul &" ...the original command (php bin/websocket_run.inc -p 8100 > /dev/null &) on the wiki didn't work, I searched up and it's for LINUX only? Then I found out a Windows alternative to /dev/null & which is nul &.

And as I said above, after doing all that, when users attempt to connect, it just sends them a blank song.

http://i.imgur.com/vYEYVYw.png

This is not the case when I change websocket_address = "ws://localhost/ws" to websocket_address = "_http_://localhost/ws" (out of experiment), it adds a play button, but it still doesn't work.

http://i.imgur.com/ijvgnmd.png

Firefox console shows this: Firefox can't establish a connection to the server at ws://2.98.3.xxx:8100/ws/broadcast.

I'm sure I've done wrong somewhere along those lines or forgot something, haha. Or could it be that the broadcast system just isn't fully function on my setup?

Thanks!

**Comment by Afterster** [comment]
Ok I updated the wiki for Windows thanks.
First be sure proxy_wstunnel is enabled and correctly working.

But, if `websocket_address` is configured to *ws://localhost/ws*, you shouldn't have a request to *ws://2.98.3.xxx:8100/ws/broadcast* but to *ws://localhost/ws/broadcast* on your Firefox browser. I don't get it here, are you sure the setting is enabled?

I will give a try later this week on Windows with your environment and let you know about the result.

**Comment by poshwosh** [comment]
> Ok I updated the wiki for Windows thanks.

I'm not so sure about it myself! Like I said, I'm not knowledgeable in this field haha, the command didn't give return me any confirmations of it succeeding, it was just blank, but it made 127.0.0.1:8100 load an empty page as opposed to server cannot be reached, and made 127.0.0.1/ws return 500 opposed to 503, so I'm assuming it worked?

That 2.98.3.xxx must have slipped through when I was fiddling, sorry. I tried both ws://localhost/ws and ws://localhost:8100/ws just then, it returned the same can't establish connection error.

I'm not so sure how to determine if proxy_wstunnel is working. It's definitely enabled, however there's these lines in the apache error log which just tell us the same thing Firefox's console did?
`[Wed Feb 17 08:29:15.664743 2016] [proxy:error] [pid 27268:tid 876] (OS 10061)No connection could be made because the target machine actively refused it.  : AH00957: WS: attempt to connect to 127.0.0.1:8100 (127.0.0.1) failed`

`[Wed Feb 17 08:29:15.664743 2016] [proxy:error] [pid 27268:tid 876] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 0s`

`[Wed Feb 17 08:29:15.664743 2016] [proxy_wstunnel:error] [pid 27268:tid 876] [client 127.0.0.1:62406] AH02452: failed to make connection to backend: 127.0.0.1`

Thank you for your efforts Afterster!

**Comment by poshwosh** [comment]
I'm sorry for the double post, I think I'm getting somewhere.

I updated to apache 4.9.10 which solved the proxy issues. I found out I can only connect to the websocket from localhost, all this time I was connecting from my external IP address. 

```
http_host = ""
websocket_address = "ws://localhost:8100/"

ProxyPass /ws ws://127.0.0.1:8100 retry=0
ProxyPassReverse /ws ws://127.0.0.1:8100 retry=0
ProxyRequests off
ProxyTimeout 15
```

Now there isn't an error, instead the meta details of the song loads, yay!! 
...but the mp3 itself doesn't.
http://i.imgur.com/mAma7Ki.png
When I checked the console, I noticed this out of place:
`http://ampache/play/index.php?ssid=229b645d0d0035787c216b9f8087e8a9&type=song&oid=1&uid=-1&name=Unknown -Orphaned- - GWAVE - Personalizer.mp3`

Shouldn't it be http://localhost/ampache/play/index.p... instead?

**Comment by Afterster** [comment]
Please check your settings with more attention.

Generated links will be wrong if http_host is explicitly forced to empty string, and of course it will only work on localhost if you setup websocket_address with a local ip or hostname.

**Comment by poshwosh** [comment]
Oh, that worked! 

It's now working locally, I spent a few minutes trying to set it to public. I had to change the "localhost" inside websocket_run.inc to my address and also had to port forward.
Also, "websocket_address = "ws://xxx.xxx.xxx:8100/"" worked opposed to "websocket_address = "ws://localhost/ws"" that's on the wiki. Should I add these pieces of information to the wiki?

The broadcast is surprisingly even more stable and reactive than Grooveshark, I'm really liking it. I really wish I could contribute somehow. I mostly only know design and I know you stick to one theme, so I can't help with that. If I can't find any ways to contribute I'll just donate.

**Comment by Afterster** [comment]
Ok good to know thank you for the feedback :).
I believe websocket proxy pass configuration was failing at your end related to the configuration. But anyway this is optional as you noticed, I will make it clear on the wiki.

Any help is appreciated. I think there is a lot of work we can do on the UI. New UI is a "duke nukem forever"-like project... so if you have improvement on current theme/architecture, feel free to suggest a PR.
Also, there isn't a lot of Ampache users using Broadcast feature so feel free to suggest/PR any improvement on this subject too.

Thanks!

**Comment by Afterster** [comment]
I encountered the same issue. In fact the problem is on host used for websocket proxy pass.
Instead of `ProxyPass /ws ws://127.0.0.1:8100 retry=0` you should setup `ProxyPass /ws ws://your.domain:8100 retry=0` because otherwise the ws server will filter the requests.
