### ISSUE TITLE
Preferences view is not responsive

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1142]
Hi,

Below 970px wide, the preferences panel is not responsive and is thus completely unusable (as nothing at all is shown in the panel).

See screenshot:
![capture d ecran 2016-02-17 a 21 18 21](https://cloud.githubusercontent.com/assets/3856586/13123367/18080322-d5bc-11e5-8680-30a14b54a71c.png)

**Comment by Afterster** [comment]
There is several things like that today. Generally, Ampache web interface is not responsive today.
This is indirectly part of #359 loooong discussion :wink:. I will close this thread as it is a duplicate.
