### ISSUE TITLE
batch download music zip file

### ISSUE THREAD

**Issue by matteos1** [ampache/ampache#1143]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: apache2
 * Server operating system: raspberry
 * Client operating system: chrome
 * Client type:
   - [ ] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)

# Description
whe i try to download music album the url is http://192.168.1.110/ampache%20%20%20%20%20%20%20%20%20%20%20%20/batch.php?action=album&id%5B0%5D=920 and not correct like this http://192.168.1.110/ampache/batch.php?action=album&id%5B0%5D=920
where is wrong in config?

# Logs

[Uploading ampache.20160218.txt…]()
[Uploading access.txt…]()

**Comment by Afterster** [comment]
Yes indeed. This was reported few days ago and already fixed in current development branch. Thank you anyway.

**Comment by matteos1** [comment]
and how can i resolve this problem. i must reinstall all the release? where is the link?
