### ISSUE TITLE
tag mp3

### ISSUE THREAD

**Issue by matteos1** [ampache/ampache#1144]
# Environment
 
 * Ampache version: 3.82
 * Web server + version: php
 * Server operating system: raspberry
 * Client operating system: chrome
 * Client type:
   - [ x] Web
   - [x ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings

# Description
one question. when i modify an album or the tag of the title of a song, the modify stay only in ampache or modify the tag of album/song?

# Logs

**Comment by Afterster** [comment]
By default your changes are only effective to Ampache database, except if you enabled `write_id3`.

**Comment by matteos1** [comment]
where is this paramether? there is in cong?

**Comment by wagnered** [comment]
If you mean config file (ampache.cfg.php), yes.

It's on or around line 187. Remove the semicolon and change to "true"

If you want to write album art to file when updated, do the same to
write_id3_art on line 197.

On 02/20/2016 09:55 AM, matteo wrote:
> where is this paramether? there is in cong?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/1144#issuecomment-186658633>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug
