### ISSUE TITLE
Error Webdav

### ISSUE THREAD

**Issue by Catskan** [ampache/ampache#1145]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: 2.4.18
 * Server operating system: Linux Ubuntu (Server)
 * Client operating system: OS X/ iOS
 * Client type:
   - [ x] Web
   - [ x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ x] WebDAV
 * Client application + version: 
 
# Settings
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/138135/ampache.cfg.php.txt)

# Description
I want use WebDav for connect my iPhone (with Infuse) on my ampache server with Webdav (only way to connect this client), but when I go on localhost/ampache/webdav (for test localy), I entered my ampache account and I have this error : 

3.0.5 Sabre\DAV\Exception\NotImplemented There was no handler found for this "GET" method

Thanks you

**Comment by Afterster** [comment]
This is excepted. You cannot browse it directly through your web browser (it's not a web directory index) but using WebDAV protocol. The base address **must include** `/index.php/` btw (eg. http://localhost/ampache/webdav/index.php/).
