### ISSUE TITLE
Error API Subsonic before release 3.8.1

### ISSUE THREAD

**Issue by davicool** [ampache/ampache#1146]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.7
 * Server operating system: Ubuntu 14.04.4 LTS (Uptodate)
 * Client operating system: Android 5.1.1
 * Client type:
   - [ ] Web
   - [ ] Ampache
   - [x] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Subsonic App version 4.4
 
# Settings
Default

# Description
Hello,

since the update to version 3.8.1 and version 3.8.2 as well.
I can not reach my Ampache server API subsonic from my Android devices.
Before EARLIER in old versions (3.8.0) I had no problem.

I test for two android applications that I used previously:
application "DSub" and application "Subsonic" official.

My Ampache server is installed on a "Ubuntu 14.04.4 LTS" to date.
My Ampache instance is a HTTP and HTTPS.
I did a fresh install any Ampache 8.2 on the same server Linux.
The problem is the same.

Not having more tracks to be able to diagnose any of you he Arait an idea?
Thank you in advance.

# Logs

I have no error:
- /var/log/apache2/access.log
- /var/log/apache2/error.log
- /var/log/ampache/ampache.2016xxxx.log

Only a message that appears on the client application when I test the connection:
"Connection failed misunderstood replica. Please check the server address."

**Comment by Afterster** [comment]
You should start from the beginning and ensure/test everything on https://github.com/ampache/ampache/wiki/API#subsonic-api

**Comment by davicool** [comment]
Hello, thank you for the answer.
I have verified all this (and much more before me decided to create this issue).

The only trace I can find is this line in the file /var/log/apache2/access.log is,

Whith subsonic app: 
192.168.1.167 - - [21/Feb/2016:18:11:34 +0100] "POST /rest/ping.view?u=admin&p=enc:00&v=1.2.0&c=android HTTP/1.1" 400 491 "-" "-"
192.168.1.167 - - [21/Feb/2016:18:11:38 +0100] "POST /rest/getRandomSongs.view?u=admin&p=enc:00&v=1.2.0&c=android&size=50 HTTP/1.1" 400 491 "-" "-"

With DSub app:
192.168.1.254 - - [21/Feb/2016:18:16:10 +0100] "POST /rest/ping.view?u=admin&p=enc:00&v=1.2.0&c=DSub HTTP/1.1" 400 491 "-" "DSub"

(Note: enc:"00" is replacemet of my crypted password)

But there's nothing wrong at this stage it seems.
This also shows that access to my instance is correct (confirmed by the HTTP and HTTPS access without errors from Firefox and other browsers).

What blocks me most is the inability to obtain logs (as I said in my post) ...

**Comment by davicool** [comment]
My config as well:
debug = "true"
debug_level = 5
log_path = "/var/log/ampache"
log_filename = "%name.%Y%m%d.log"

**Comment by Afterster** [comment]
400 bad request is definitely wrong.
I believe the url rewriting rules is not working as excepted here. Check /rest/.htaccess file and your server setting about url rewriting.

**Comment by davicool** [comment]
Hello,
Thank you for the track, my /rest/.htaccess file was damaged.
I took the original file (/rest/.htaccess.dist) and have renamed, the connections are working properly now.
If I can make a suggestion: a few traces (error) in the logs can perhaps be useful in this case.
Anyway thank you very much, the ticket can be closed.
