### ISSUE TITLE
Duplicate albums when filtering by catalogs

### ISSUE THREAD

**Issue by poshwosh** [ampache/ampache#1148]
While browsing through the albums page, it would normally group songs together into a single album entry.

http://i.imgur.com/J62VsNF.png

However, when I change the catalog selection in the filter section from "All" to any catalog, suddenly there is an album entry for every single song in the album.

http://i.imgur.com/8QhTdYv.png

I tried clearing some metadata to see if that's part of the issue, but it still persisted. The strange thing, when reverting back to "All", the duplicates still remain, the only way to revert it is to refresh the page.

**Comment by Afterster** [comment]
Indeed, always missed this one... thanks for the report, fixed.
