### ISSUE TITLE
Ampache retrieved podcast filename includes URL query string

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#1149]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.7
 * Server operating system: Ubuntu 14.04
 * Client operating system: n/a
 * Client type:
   - [ ] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: n/a

This is a portion of the XML for a podcast I've subscribed to:
`
<item>
<title>(2/25) 8am Success From Scratch</title>
<itunes:author>KFI_AM_640</itunes:author>
<itunes:subtitle>Success from Stars. HOTN LATE edition</itunes:subtitle>
<itunes:summary>Success from Stars. HOTN LATE edition</itunes:summary>
<itunes:image href="http://img.ccrd.clearchannel.com/media/mlib/616/2016/02/default/handel_lightsaber_meme_0_1456392628.jpg"/>
<imageurl>
http://img.ccrd.clearchannel.com/media/mlib/616/2016/02/default/handel_lightsaber_meme_0_1456392628.jpg
</imageurl>
<enclosure url="http://media.ccomrcdn.com/media/station_content/616/2016/02/mp3/default/_2_25__8am_sfs_hollywood_celeb_0_1456402055.mp3?CPROG=PCAST&MARKET=LOSANGELES-CA&NG_FORMAT=&SITE_ID=616&STATION_ID=KFI-AM&PCAST_AUTHOR=KFI_AM_640&PCAST_CAT=&PCAST_TITLE=Bill_Handel_on_Demand" length="" type="audio/mpeg"/>
<guid>
http://media.ccomrcdn.com/media/station_content/616/2016/02/mp3/default/_2_25__8am_sfs_hollywood_celeb_0_1456402055.mp3
</guid>
<pubDate>Thu, 25 Feb 2016 12:08:18 -0500</pubDate>
<itunes:duration>:40:00</itunes:duration>
<itunes:explicit>No</itunes:explicit>
<description>Success from Stars. HOTN LATE edition</description>
<mediaId>26761572</mediaId>
<podcast_downloadable>1</podcast_downloadable>
<mediaTitle>(2/25) 8am SFS Hollywood Celebrity Tours</mediaTitle>
<mediaType>audio</mediaType>
</item>
`

So what appears to have happened is when Ampache retrieved this item, it took the URL with query string `http://media.ccomrcdn.com/media/station_content/616/2016/02/mp3/default/_2_25__8am_sfs_hollywood_celeb_0_1456402055.mp3?CPROG=PCAST&MARKET=LOSANGELES-CA&NG_FORMAT=&SITE_ID=616&STATION_ID=KFI-AM&PCAST_AUTHOR=KFI_AM_640&PCAST_CAT=&PCAST_TITLE=Bill_Handel_on_Demand` and instead of saving it as `1-_2_25__8am_sfs_hollywood_celeb_0_1456402055.mp3` on my local storage, I ended up with a file called `1-_2_25__8am_sfs_hollywood_celeb_0_1456402055.mp3?CPROG=PCAST&MARKET=LOSANGELES-CA&NG_FORMAT=&SITE_ID=616&STATION_ID=KFI-AM&PCAST_AUTHOR=KFI_AM_640&PCAST_CAT=&PCAST_TITLE=Bill_Handel_on_Demand`

It's unplayable (probably because of all the invalid characters).  There's the `<guid>` tag that has the URL without the query strings.  I don't know how common the `<guid>` tag is, but if that's a standard for the file URL, that might be a better place to parse the file name.  Or, possibly parse out query strings if there are any.

**Comment by Afterster** [comment]
Yes you're right! But this was already reported few weeks ago and fixed in current develop branch. See #1118.

**Comment by dhsc19** [comment]
Ah..ok thanks...will give check out the development version.
