### ISSUE TITLE
Suggestions: Album info & Play All Favorites

### ISSUE THREAD

**Issue by Poshwosh** [ampache/ampache#1150]
I've been using Ampache for a few days now, I'm getting comfy but it's lacking some basic features I used to use, I'd like to propose them.

**Album info:**
A simple text line on the third row in the current playing song that indicates which album the song is part of.
Something like this:
http://i.imgur.com/MG7fmIb.png
I understand some people might not use it, so it can be an option?

**Favorites improvements:**
There is no play all button which completely ruins the whole point of favorites in my opinion.

**Comment by Joelfred** [comment]
+1 I would like seeing the album name as well

**Comment by Afterster** [comment]
Not sure to understand you correctly guys, there is already the album name near currently playing song information. Could you give some details?

**Comment by poshwosh** [comment]
I completely forgot there was a currently playing information, I disabled it a while ago, and I confused the two.

I meant to say the currently playing song on the player.

So it would turn from this:
http://i.imgur.com/7FhNavS.png

Into this:
http://i.imgur.com/LpS9mOV.png

Just a rough example, I didn't really think much about it just gives the basic idea.

**Comment by lachlan-00** [comment]
I did toy with the album name but didn't like how cluttered it made things.

It would require adding more data to the streaming links/webplayer and slow things down a bit more. there's a link to the album now which i think covers this enough to close
