### ISSUE TITLE
itunes m4a naming not supported & metadata not read...

### ISSUE THREAD

**Issue by incompetus** [ampache/ampache#1152]
# Environment
 
 * Ampache version: 3.8.3 Develop - 8b77d6209fd91f06258b17bb9bd015db586f3796
 * Web server + version: Apache 2.4.7
 * Server operating system: Ubuntu 14.0.4
 * Client operating system: Mac
 * Client type:
   - [X] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
Fairly standard setup. Can provide if needed...

# Description
2 'overlapping' issues:

1 - itunes naming conventions not recognised for multi-disc albums. Single disc album convention is:

01 [songname.m4a]

Multi disk is [disc]-[track] [songname.m4a] eg. 2-01 songname.m4a

This means any files from multi disc albums can't be recognised. 

2 - unable to read metadata from lossless m4a files. For whatever reason, it doesn't seem to be able to read embedded metadata from lossless m4a files.This combined with issue 1) results in approx 900 orphaned files on my reasonably small library (~10K songs) - nearly all of which have multi-disk filenames....

# Logs
Can provide if needed...

**Comment by Afterster** [comment]
For 1), just pushed 8a2120ceac1af11d817bd63d772d90e85838c9cd that add *%d* variable to catalog pattern.
For 2), not sure but it looks like a getid3 issue. Could you try directly with [getid3](https://github.com/JamesHeinrich/getID3) demo.browse.php sample?

**Comment by incompetus** [comment]
Hi

Thanks. Attached is a sample from getid3 and the entry from ampache. 
[ledzep.zip](https://github.com/ampache/ampache/files/149842/ledzep.zip)

**Comment by Afterster** [comment]
Thanks. Getid3 return correct information according to your output. Are you sure getID3 is first on `metadata_order` setting?

**Comment by incompetus** [comment]
Looks like it:

getid3_tag_order	id3v2
id3v1
vorbiscomment
quicktime
matroska
ape
asf
avi
mpeg
riff
metadata_order	getID3
filename

**Comment by Afterster** [comment]
Looks ok... could you send me a test file? Thank you.

**Comment by Afterster** [comment]
Related to https://github.com/JamesHeinrich/getID3/issues/66 which was fixed on master. Updated dependency to latest GetID3 commit then with https://github.com/ampache/ampache/commit/ef6caa20d15e94882f73ec7361c952ef34daf2e4
You will have to run `composer install` again. Thanks!

**Comment by incompetus** [comment]
Worked a treat - thanks!
