### ISSUE TITLE
Call to a member function quote() on null in lib/class/dba.class.php:134

### ISSUE THREAD

**Issue by GieltjE** [ampache/ampache#1154]
* Ampache version: GIT develop
 * Web server + version: Apache 2.4.18, **PHP 7.0.3 via fpm-fcgi**, MariaDB 10.1.12
 * Server operating system: Gentoo
 * Client operating system: Any webclient
 
# Settings
Just a plain ampache with nearly stock settings

# Description
Just open the login page

# Logs
Fatal error: Uncaught Error: Call to a member function quote() on null in /var/www/ampache2/lib/class/dba.class.php:134 Stack trace: #0 /var/www/ampache2/lib/class/preference.class.php(448): Dba::escape(-1) #1 /var/www/ampache2/lib/init.php(220): Preference::init() #2 /var/www/ampache2/index.php(23): require_once('/var/www/ampach...') #3 {main} thrown in /var/www/ampache2/lib/class/dba.class.php on line 134

**Comment by Afterster** [comment]
Except the error, everything working?
If not, this happen when the database connection setting is wrong.

**Comment by GieltjE** [comment]
The database settings are correct, nothing is working.

**Comment by Afterster** [comment]
If you get this, connection cannot be establish.Check again.
Anything on Ampache logs like 'connection failed' or similar message?

**Comment by GieltjE** [comment]
There are no other logs and all other scripts can connect succesfully to the database.

**Comment by Afterster** [comment]
Ok.
Well If you enable Ampache logs, you will have additional logs... The provided logs is php error logs only.

**Comment by Afterster** [comment]
I committed a change yesterday to have more appropriate log on this. Please try with latest change and share your logs (**Ampache logs** required here). Thanks.

**Comment by GieltjE** [comment]
I should be able to test that tonight.

**Comment by GieltjE** [comment]
The latest git doesn't output anything, not even in debug mode.

**Comment by Afterster** [comment]
Could you share your Ampache logs anyway just to see what's happening?

**Comment by GieltjE** [comment]
Found the problem, when I define debug (debug = "true") the config file breaks (test.php displays "ERROR" for "Configuration file validity"), commenting that line fixes everything.
