### ISSUE TITLE
Cannot play some files

### ISSUE THREAD

**Issue by ciroiriarte** [ampache/ampache#1159]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: httpd-2.2.15-47.el6_7.3.x86_64
 * Server operating system: CentOS 6
 * Client operating system: Windows 8.1
 * Client type:
   - [x] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/153527/ampache.cfg.php.txt)

# Description
Some MP3 files cannot be played using a browser or even downloaded. This is the error I'm getting on the Chrome console:

![image](https://cloud.githubusercontent.com/assets/1750260/13440493/140f1412-dfd1-11e5-88b1-36eca522e9a2.png)

Other files are playing fine (all of them are MP3 files). In the case of one of the problematic songs, I can copy the underlying MP3 file to a workstation (scp) and play it locally.

# Logs
I'm adding the log entries for the failed playback attempt

[ampache.txt](https://github.com/ampache/ampache/files/153545/ampache.txt)

**Comment by Afterster** [comment]
Wow your filename looks weird, see this log line:
```Media /recorder/2016-02-03/58466/0069027585f46dbb_A611_<REPLACED>_21-15-56_-017E016B-1000292B-0001.mp3 (0069027585f46dbb) does not have a valid filename specified```. PHP cannot read this file and then you got this error. Could you check permission/filename (specifically the <REPLACED> thing :smile:)?

**Comment by ciroiriarte** [comment]
The replaced section is a series of numbers actually (9 digits), I replaced that for log publication.

The file is owned by the web server user. Is it possible to make the log any more verbose about the issue? :D

**Comment by ciroiriarte** [comment]
I can list the file by copying the path and pasting it on a SSH session (it's correct). Also, SELinux is set to permissive.

Also the file doesn't seem corrupted as I can download it using SCP and play it locally.

**Comment by ciroiriarte** [comment]
Forgot to mention, the files that are playing fine have the same filename structure.

**Comment by Afterster** [comment]
We cannot have more logs on that sorry. I believe the issue is server environment side, please create some php test script file and try to access the file directly. I cannot help much when this is related to the environment ;)

**Comment by ciroiriarte** [comment]
Well, with the help of getID3 browser demo found out that one of the subdirectories had wrong permissions :/

Mistery solved
