### ISSUE TITLE
Disabling video features

### ISSUE THREAD

**Issue by ciroiriarte** [ampache/ampache#1160]
Is it possible to disable the video features on 3.8.2?

**Comment by Afterster** [comment]
Yes (Admin => Server Config => Options => Allow video features), please do a search on your settings before creating an issue, or please post to google groups. GitHub issue tracker is mainly for development related subjects like bug/feature request. Thanks! :wink:

**Comment by ciroiriarte** [comment]
Thanks, I'll look for the Google Group
