### ISSUE TITLE
High file count

### ISSUE THREAD

**Issue by ciroiriarte** [ampache/ampache#1161]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: httpd-2.2.15-47.el6_7.3.x86_64
 * Server operating system: CentOS 6
 * Client operating system: Windows 8.1
 * Client type:
   - [X] Web
   - [X] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
Are there any best practices for big deployments?, I'm trying ampache as a user interfase to access Contact Center call recordings, my estimation is of around 80k MP3 audio files generated per day.

Operating system tunning is well known topic for me, but from what I've seen the catalog update process can be an issue

**Comment by Afterster** [comment]
Wow that's big. I know several unstallation with hundred of thousands entries, but I'm sure we reached several millions. In your case few music oriented feature will not be useful for you and could take extra computing. Best practice will be to disable almost everything and see the behavior.
Do you attempt to tag your MP3 audio records? If not, you should use catalog pattern parsing only and also disable GetID3.

**Comment by ciroiriarte** [comment]
The original audio files are created as WAV files, a later process converts the files to MP3 and adds tags after that. A month worth of recordings translates to 2.4M files, the internal user request is to save at least 3 months.

This equals to 7.2M files, once we get to day 1 of month 4, it also means 80k old file deletions per day while we create 80k more at the same time. I'll take a look at the music features that can be disabled.

I'll move this to the Google group. Thanks!

**Comment by Afterster** [comment]
Ok, don't hesitate to give feedback on the result.
