### ISSUE TITLE
Server sent events while managing catalog doesn't work in Chrome based browsers

### ISSUE THREAD

**Issue by thejk** [ampache/ampache#1162]
# Environment
 
 * Ampache version: 3.8.x
 * Web server + version: lighttpd 1.4.33
 * Server operating system: GNU/Linux
 * Client operating system: Any
 * Client type:
   - [x] Web
 
# Description
Select a Chrome based browser, go to ampache, Show Catalogs and select to Add, Update or any of the other actions that displays a progress status via server sent events.
Instead of getting status events a "Server-Sent Events connection error. Re-connection..." message is shown and in the console of chrome you get:
EventSource's response has a charset ("iso-8859-1") that is not UTF-8. Aborting the connection.

**Comment by Afterster** [comment]
Merged!
