### ISSUE TITLE
unable to complete php installer

### ISSUE THREAD

**Issue by indigo00** [ampache/ampache#1166]
# Environment

 
 * Ampache version:  commit 58ede..... (latest as of 5th march 2016)
 * Web server + version: lighttpd +  mariadb
 * Server operating system: arch linux
 * Client operating system: ubuntu 15.10
 * Client type:
   - [ X] Web 
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version:  FF 44
 
# Description
Unable to start installation (test.php shows error on "Database tables").
What I've done in sql:
- added user ampache
- created table ampache
- granted all on ampache.*

If i login to mysql with user ampache, i can select database, and create tables, etc.
**Apparently ampache thinks that if the db is already present, this is not a new installation, and existing data should be preserved. I found no way of disabling this feature/bug... apparently there is a checkbox somewhere to by pass this.
Any clues?

**Comment by Afterster** [comment]
You should use web installer or run /sql/ampache.sql to create tables. For web installer, do not create ampache.cfg.php manually and go to /install.php with your web browser.
