### ISSUE TITLE
Ampache does not generate clean xml

### ISSUE THREAD

**Issue by jschurse** [ampache/ampache#1171]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4
 * Server operating system: Debian Jessie
 * Client operating system: Arch
 * Client type:
   - [x] XML
 * Client application + version:
   - [x] Rhythmbox

# Settings
Ampache + MySQL + Apache with FCGID

# Description
The XML API does not generate clean XML. It does not escape ampersands correctly.
I have meta information for a song where the componist is set to: 'Christian Schüle & Sebastian Lux'. If I query the API for the songs the parser throws an error:

XML Parsing Error: not well-formed
Line Number 157007, Column 30:	<composer>Christian Schüle & Sebastian Lux</composer> 

The ampersand should be escaped, shouldn´t it?

**Comment by Afterster** [comment]
Yes this is right, I just found out this issue two days ago and fixed in last week-end. Currently fixed in develop branch but thank you for the report anyway ;).
