### ISSUE TITLE
low memory

### ISSUE THREAD

**Issue by matteos1** [ampache/ampache#1173]
# Environment
 
 * Ampache version: 
 * Web server + version: 
 * Server operating system: 
 * Client operating system: 
 * Client type:
   - [X ] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
after update apache have a significant level of memory used on raspberry

# Description
after update apache have a significant level of memory used

**Comment by Afterster** [comment]
I'm sorry but this is not a valid issue. I think it is just how Ampache is.
