### ISSUE TITLE
Resize images stops new pages from loading

### ISSUE THREAD

**Issue by Poshwosh** [ampache/ampache#1174]
I have enabled resize_images on the config file and enabled the PHP extension PHP_GD2.
It works great, dumbed down the sizes from 200kb to 10kb, amazing.

However, in pages where the resized art is included, specifically album browse and artist browse, changing pages no longer works.
I click it, and it stays on page 1. Console returns an error to hints its related to PrettyPhoto?
While going to another page and then returning to the previous one, it sends me to page 2, meaning that the pages still work, but the transition toward the page fails.

**Comment by Afterster** [comment]
I don't think this is related to this feature. Could you do more investigation and isolate the behavior? Once that done, please try to provide associated browser/ampache logs.

**Comment by Phyks** [comment]
@poshwosh any news on this?

**Comment by mitchray** [comment]
Closed due to inactivity
