### ISSUE TITLE
Comments in more than 140 caracters

### ISSUE THREAD

**Issue by Aisyk** [ampache/ampache#1175]
Ampache 3.8.2 / Dogmazic

Comments are limited to 140 caracters, some off dogmazic's users wants more space to publish their critics. Maybe with a tiny html editor and a limit of 2000 caracters ?

**Comment by lachlan-00** [comment]
I'm going to up this limit to the 2000 suggested in develop.

I think the character limit is set for visuals in the interface as the column is not limited at all in the database. (text, 65k characters)

**Comment by lachlan-00** [comment]
pushed to develop, add/edit are limited to 2000 there's still room to move and the limit is only set in the html so it's not in the database.
![image](https://user-images.githubusercontent.com/1305249/72868546-06cb5400-3d2e-11ea-8ee7-c08351bafdcc.png)
