### ISSUE TITLE
Illegal unicode characters in database

### ISSUE THREAD

**Issue by jschurse** [ampache/ampache#1177]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4
 * Server operating system: Debian Jessie
 * Client operating system: ArchLinux
 * Client type:
   - [x] XML
 
# Description
I requested the songs via the XML API and got XML parse errors. After some search I found bad unicode characters in the XML. For example:

    <composer>Stray from the Path]]</composer>

Other characters (unicode 0x0) can`t even be posted here
http://i.imgur.com/8S4UGbl.png
http://i.imgur.com/3AXBaKO.png

I was able to fix it by editing the affected fields in the database using phpmyadmin.
Tonight ampache will update the catalog. I don`t know if the problem will return tomorrow.
Did such problems occure in the past?

**Comment by Khymick** [comment]
I could reproduce the same problem with 3.8.3-devel.

**Comment by Afterster** [comment]
Ok, could you provide a test file? So I can fix and test on the same time. Thanks.

**Comment by Khymick** [comment]
File sent to you via mail.

**Comment by Afterster** [comment]
Ok, should be fixed at xml output time now.
But I believe this happen because of getid3 when mbstring is not available.

**Comment by jschurse** [comment]
Hey,

Thanks for your help!

I looked it up and mbstring is available at my setup:

Multibyte Support enabled
Multibyte string engine libmbfl
HTTP input encoding translation disabled
libmbfl version 1.3.2

2016-03-21 8:35 GMT+01:00 Afterster <notifications@github.com>:

**Comment by Khymick** [comment]
I will try it as soon as I have some time - quite stressy days at the moment...

**Comment by jschurse** [comment]
Hey, 
I applied your patch to the xml_data.class.php file and now everything is working perfectly again!
Thank you verry much for your help!

**Comment by Khymick** [comment]
Sorry to ask, but where is the patch? I cannot find it here...
