### ISSUE TITLE
expand error message about art.

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1178]
Would it be possible to include the filename or the album ID that failed in the log?

2016-03-11 12:50:29 [user] (Art) -> Image failed PHP-GD test
2016-03-11 12:50:29 [user] (Art) -> Not inserting image, invalid data passed

**Comment by Phyks** [comment]
@lachlan-00 do you think the PR #1267 would match your requirements?

**Comment by lachlan-00** [comment]
That looks great to me. Having the type and UID in the logs will make this error much easier to examine.
