### ISSUE TITLE
Feature request : PostgreSQL Integration

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#118]
_Issue by **[JGroselle](https://github.com/JGroselle)** from Wednesday Feb 12, 2014 at 14:28 GMT_
_Originally opened as https://github.com/ampache-doped/ampache-doped/issues/138_

----

Hi, 

First of all, thank you so much for this fork ! Good Job !
I want use ampache-doped to listen my music, but I can't bring myself to use the SGBD MySQL. For me, this database engine is not ready for production and install two Database engine on my little server is not optimum.

It would be so great if you add a PosgreSQL connector to ampache-doped.

Thank you in advance.
Have a good day.

**Comment by SUTJael** [comment]
Moved to #488.
