### ISSUE TITLE
Ajax-Bug after changing language ???

### ISSUE THREAD

**Issue by Megabyte66** [ampache/ampache#1182]
# Environment
 
 * Ampache version: 3.6
 * Web server + version: Apache: 2.4.16
 * Server operating system: 
 * Client operating system: 
 * Client type:
   - [ ] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)

# Description
Hi Team. I am still using Ampache 3.6. Everything works well as long as I don't
change to "Language: German". When I switch to german I recognise following
error:

When pressing one of the five buttens top of the side-bar nothing changes. For example
I am in the "Home"-Mode of the sidebar and click on "Admin" nothing happens. When
I now click on any other link in the sidebar (maybe "Newest"), than the click on "Admin"
(done before) shows effect and the sidebar changes to the admin-mode.

This only appears in Laguage: german. So I don't think it's a problem in the config
file (maybe the setting of charset, site_charset = UTF-8, lc_charset = ISO-8859-1).

I checked the po file for german and the config-file. Both are saved as UTF-8 without BOM.

Any clue?

# Logs
[Ampache logs](https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging) and web server access/error logs in attached files. Please also add client application logs if appropriate.

**Comment by Afterster** [comment]
Thanks for the report but unfortunately this is an old issue. A lot of things changed on latest Ampache releases, including page loading. No fix will be provided for 3.6 anymore sorry.
