### ISSUE TITLE
Invalid syntax in update class for MySQL 5.7.4+

### ISSUE THREAD

**Issue by ksarnelli** [ampache/ampache#1187]
# Description

I encountered an issue during Ampache's database update process - the 'Update Now!' button appeared to do nothing and no error was returned.

I tracked it down to the following SQL statement in update::update_380003()

`ALTER IGNORE TABLE ``tag_map`` ADD UNIQUE INDEX ``UNIQUE_TAG_MAP`` (``object_id``, ``object_type``, ``user``, ``tag_id``)`

Support for the `IGNORE` clause in `ALTER TABLE` was dropped in MySQL 5.7.4, so anyone running a current version of MySQL is going to have issues.

**Comment by Afterster** [comment]
Thanks for the report, this was already fixed on current development branch.
