### ISSUE TITLE
Enable transcoding by default

### ISSUE THREAD

**Issue by arielelkin** [ampache/ampache#1191]
Many music collection have many lossless audio files (FLAC, ALAC, WAV, etc.)

Transcoding disabled is not a sane default. It causes problems:

* [FLAC](https://github.com/ampache/ampache/issues?utf8=%E2%9C%93&q=is%3Aissue+flac)
* [M4A](https://github.com/ampache/ampache/issues?utf8=%E2%9C%93&q=is%3Aissue+m4a)

Nowadays most linux distributions come with either `ffmpeg` or `avconv` installed, Ampache should be able to configure itself during installation.

Transcoding should therefore be enabled server-wide by default.

**Comment by Afterster** [comment]
I agree most distrib now have ffmpeg by default, but it's generally not the case on servers.
Moreover transcoding is already enable by default as soon you select the correct transcode application on web setup wizard.
