### ISSUE TITLE
topmenu-music.png is missing from /images directory

### ISSUE THREAD

**Issue by robled** [ampache/ampache#1195]
# Environment
 
 * Ampache version: Ampache 3.8.3-develop
 * Web server + version: Apache 2.4.10
 * Server operating system: Debian 8
 * Client operating system: *
 * Client type:
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
I get a 404 on page load for the 'Artists' icon on the top menu.  I found that topmenu-music.png is missing from the /images directory, and a workaround is to do the following:

`ln -s topmenu-artist.png topmenu-music.png`

**Comment by Psy-Virus** [comment]
Hey @robled,

I did a PR to fix your issue. But to avoid update problems (once the PR is merged), you should redo your workaround before you update.

:-)

**Comment by robled** [comment]
Thanks @Psy-Virus.  I will delete that symlink before the next update.

**Comment by Psy-Virus** [comment]
Well, I did the fix but forgot to press "create PR" XDD
But now it's there. :D
