### ISSUE TITLE
Subsonic backend: issues using search function

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#1198]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.18
 * Server operating system: Fedora 23
 * Client operating system: Android 4.1.1
 * Client type:
   - [ ] Web
   - [ ] Ampache
   - [x] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: DSub 5.1.6
 
# Description
I noticed a few issues when searching the ampache database through the subsonic backend.
At first I thought this was a problem with the app DSub and I posted an issue on its [GitHub Tracker](https://github.com/daneren2005/Subsonic/issues/673) but the developer argued that the problems lie with the REST API used by the subsonic backend.
Here are the issued as I posted them on the DSub tracker:

1. If the for instance an album title am searching for contains an apostrophe (') it will not be found.
In my case the album title is "I'm not there" (a film soundtrack containing tracks by various artists.

2. When searching for example for "Frank Zappa" the search works fine. If I search only for "Zappa" no results are found.

It looks like the value stored in the database has to start with the beginning of the search string.
Both these problems do not occur on the web interface of my ampache installation.

Any help is really appreciated!

Thanks
Arno

**Comment by arno1979** [comment]
Ok, thanks for looking into it!
I am still on 3.8.2 haven't tried the development version yet. I'll try to update my installation and see if it works as you described.

**Comment by Phyks** [comment]
So I guess this one can be safely closed, isn't it? At least, if it is actually coming from Dsub as seems to be indicated by previous tests.

Sorry, and reopen if it is not the case.
