### ISSUE TITLE
Extended Attributes or ID3 Metadata?

### ISSUE THREAD

**Issue by NickWinston123** [ampache/ampache#1200]
Hey I was wondering you could help me answer this question. Does ampache get its artist, album, etc from "extended attributes" ((https://github.com/rg3/youtube-dl/blob/536a55d/youtube_dl/postprocessor/xattrpp.py#L139-L147) or the mp3's ID3 metadtata? 

More info here:
https://github.com/rg3/youtube-dl/issues/9113

**Comment by wagnered** [comment]
I am a contributor to Ampache and believe that I can safely write that
the answer is "from the id3v1-id3v2 standard tags."

The long answer is that according to ID3.org, the extended header is
exactly that: for more information about the tag that it extends,
excluding parsing information. It is not meant to be a new tag.  It is
my opinion that the fact that mp3tag and other mp3 editors use the
extended header in a "non-standard" manner.

Therefore I would not expect any open source media manager to implement
managing extended information, especially in a manner that it was not
intended to be used.

Understand that every tag can have an extended header: To manage them
all, it would take a commercial media center like JRiver mc which would
have the (financial) resources to accomplish this.

On 04/08/2016 07:28 AM, NickWinston123 wrote:
> 
>   Environment
> 
>   * Ampache version:
>   * Web server + version:
>   * Server operating system:
>   * Client operating system:
>   * Client type:
>       o [x ] Web
>       o Ampache
>       o SubSonic
>       o Plex
>       o DAAP
>       o UPnP
>       o WebDAV
>   * Client application + version:
> 
> Hey I was wondering you could help me answer this question. Does ampache
> get its artist, album, etc from "extended attributes"
> ((https://github.com/rg3/youtube-dl/blob/536a55d/youtube_dl/postprocessor/xattrpp.py#L139-L147)
> or the mp3's ID3 metadtata?
> 
> More info here:
> rg3/youtube-dl#9113 <https://github.com/rg3/youtube-dl/issues/9113>
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/1200>
> 

-- 
73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Short answer, no it is not supported today :smile:.

We rely on [GetID3](https://github.com/JamesHeinrich/getID3) for all file metadata stuff. You should give a try with provided getid3 sample, and see if it can parse those metadata. If so, then it could be easily added to Ampache, if it makes sense and is standard enough of course.

**Comment by NickWinston123** [comment]
@wagnered @Afterster Thank you very much for your replies, hopefully youtube-dl will have ID3 support soon.
