### ISSUE TITLE
External auths: various suggestions

### ISSUE THREAD

**Issue by Niols** [ampache/ampache#1206]
Hi,

I'm currently writing a fix for issue #1201, and that reminded me of some ideas I had.

I believe Ampache should support more than just `name`, `email` and `website`. The users can have more infos (cities, avatars, …) and some external authentication backends (e.g. LDAP) can provide them.

https://github.com/ampache/ampache/blob/develop/lib/login.php#L116

Secondly, Ampache could update the user at each connection, so that changes on the external server would have an impact in Ampache (optional, of course).

And finally, the passwords shouldn't (once again, an option?) be stored in the MySQL database. This could be
- for security reasons (delegate the security to a server whose job is security),
- for philosophic reasons (“hello, I'm an Ampache admin, but I don't store your passwords”)
- and because the password updates on the external server or in the MySQL table allow the users to use two different passwords (in particular, removing a user from his group on the LDAP server doesn't prevent him from loging in with his old password)

I'm waiting for ideas, advices, suggestions, … and preparing a PR.

**Comment by Rouzax** [comment]
It would also be nice if an user were able to update their password which would also change the AD password in the backend although I'm not sure that is feasible.

**Comment by Niols** [comment]
This is feasable, but requires much more work. This is also the topic of an opened issue (I'm on my phone, I can't look for it right now).
It alse requires a modification of the user system to know where a user comes from.
And it requires an AD server allowing password modification
-- 
Niols

**Comment by Rouzax** [comment]
Was just a thought, not really necessary. 
Anyways thanks for the fix

**Comment by Niols** [comment]
The issue I was mentionning is #808.

**Comment by Niols** [comment]
About passwords, I've found the config value `auth_password_save` that does exactly what I want:

> Automatic local password updating
>
> Determines whether successful authentication against an external source
> will result in an update to the password stored in the database.
> A locally stored password is needed for API access.

https://github.com/ampache/ampache/blob/develop/config/ampache.cfg.php.dist#L129

However, the fact that we need to store the password for API access can be annoying. This is the topic of issue #990.

I'll try to think about that, but, for now (for this issue), I will forget about that third password stored in the database.

**Comment by Niols** [comment]
OK, the PR #1201 has been merged, adding the two first suggestions.

Two things remain:

- allow the API to use external auth
- allow modification of users on external servers

The first point corresponds ton issue #900. The second to issue #808.

Which means this one can be closed.

**Comment by Niols** [comment]
Note: the first point corresponds to issue #990 and not 900 as mentionned.
