### ISSUE TITLE
Firefox Browser Notification Fedora

### ISSUE THREAD

**Issue by emerham** [ampache/ampache#1207]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.7-1ubuntu4.9
 * Server operating system: Ubuntu 14.04.4
 * Client operating system: Fedora 23, Gnome 3.18.4
 * Client type: Firefrox Web Browser from default repo
   - [X] Web
   - [X] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
Firefox: 45.0.1 using Ampache Web Player (html5)
Chrome: 50.0.2661.75 (64-bit)
Chromium:  48.0.2564.116 Built from source for @@BUILD_TARGET@@ (64-bit)
Vivaldi: 1.0.435.42 () (64-bit)
Epiphany: 3.18.5
Midori: 0.5.11 user Ampache Web Player
Maxthon for Linux:  1.0.5.3 (don't really care about this one)
Opera: 36.0.2130.65 
Otter: Otter 0.9.07-dev
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...) Settings are all stock

# Description
Here the bug/feature description and how to reproduce/integrate it.
When listing to a play list the Browser Notifications do not show when the next song is played, and will sometimes get triggered when manually skipping songs.
### Expected:
Song changes in playlist do to previous song ending notification of next song played
Broswer that work
Chrome/Chromium/Opera/Vivialdi/Epiphany(Gnome web)/Otter

### Recived:
Web player goes to next song, no notification
Brosers that fail:
Firefox/Midori/Maxthon
# Logs

[Ampache logs](https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging) and web server access/error logs in attached files. Please also add client application logs if appropriate.

**Comment by Afterster** [comment]
I'm not sure this is an Ampache issue. Could be related to browser implementation. Is HTML5 notifications working as excepted with these browsers and other websites?

**Comment by emerham** [comment]
After upgrading to Firefox 46, web push notifications are now properly working. It was an issue with Firefox 44 and lower. You can close this.

**Comment by Afterster** [comment]
Ok good to know. Thanks for the feedback.
