### ISSUE TITLE
bug ampache php7 

### ISSUE THREAD

**Issue by Catskan** [ampache/ampache#1209]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: apache2 + php7
 * Server operating system: Ubuntu 16.04 LTS
 * Client operating system: All
 * Client type:
   - [x ] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 

# Description
I setting up a htpc server with the newest Ubuntu 16.04 LTS and I have a blank page on "localhost/ampache/install.php
I installed extension php-gettext ...

# Logs
tail -f /var/log/apache2/error.log
[Sat Apr 23 01:45:55.044829 2016] [:error] [pid 2355] [client 192.168.1.2:52944] PHP Fatal error:  Uncaught Error: Class 'Gettext\\Translator' not found in /var/www/html/ampache-test/ampache/lib/i18n.php:36\nStack trace:\n#0 /var/www/html/ampache-test/ampache/install.php(103): load_gettext()\n#1 {main}\n  thrown in /var/www/html/ampache-test/ampache/lib/i18n.php on line 36

**Comment by Catskan** [comment]
I installed composer and a reboot solve the problem oO.

**Comment by Witos** [comment]
What  Composer? I have the same problem...

**Comment by Witos** [comment]
Never  mind, composer install helped.
