### ISSUE TITLE
please check and approve the Chinese messages.pot

### ISSUE THREAD

**Issue by BoneAsh** [ampache/ampache#1210]
hello, I am a Chinese and I just finished translating chinese messages.pot in transifex.com ,please check and approve it.
I hope chinese will be available in next version.
Finally，I hope your project even better

**Comment by Psy-Virus** [comment]
Hey @BoneAsh,

please take a look at this: 
https://groups.google.com/forum/#!topic/ampache/S-6AMfvhKpQ
and this:
https://www.transifex.com/ampache/teams/40984/discussions/15339/

Thank you!

:-)

**Comment by BoneAsh** [comment]
It's my pleasure to be a reviewer
