### ISSUE TITLE
Subsonic API Backend: Path Field

### ISSUE THREAD

**Issue by daneren2005** [ampache/ampache#1213]
# Environment
 * Ampache version: Ampache 3.8.3-develop (https://github.com/ampache/ampache/commit/66ea7bc403fa31cc353ca01539a15c2bcd5aef74)
 * Web server + version: Nginx
 * Server operating system: Ubuntu 14.04
 * Client operating system: Android
 * Client type:
   - [ ] Web
   - [ ] Ampache
   - [x] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: DSub

# Description
The path field isn't actually the path field, it is just the Artist/Album/Song.  The reason this can create issues is if the artist or album tags have slashes in them, you can end up with weird "paths": `Elton/ John/Road/ To El Dorado/01 - El Dorado.flac`. This was obviously a made up example since I didn't have any artists/albums with slashes in them already.  Is there a reason why Ampache isn't putting the actual file path in that param?  If there is, I can work around this by just building the path manually based off the Artist/Album/Title just for Ampache.  I was just curious about why it was setup like this.

PS I came across this via https://github.com/daneren2005/Subsonic/issues/681, but I am pretty sure there problem has nothing to do with this since I was able to play a song from an artist with slashes in it just fine.

**Comment by Afterster** [comment]
thanks for the report @daneren2005.
Indeed, this was excepted behavior, well at least it was coded this way on Ampache side. Before that Ampache was returning the full file path, which is also wrong. I believe the correct value here should be relative path according to catalog root path (which is what is done by legacy Subsonic server I think so).
Gonna need to be fixed then.

**Comment by daneren2005** [comment]
Yes the path is relative to the root of the music folder in Subsonic.

**Comment by Phyks** [comment]
I did an attempt at implementing it in https://github.com/ampache/ampache/pull/1240. Let me know if it does match with the expected behavior.

**Comment by Phyks** [comment]
I think this can be closed now, no?

**Comment by Afterster** [comment]
Yes it can, thank you both.
