### ISSUE TITLE
username flagged as too long after upgrading to ubuntu 16.04

### ISSUE THREAD

**Issue by ricksorensen** [ampache/ampache#1214]
# Environment
 
 * Ampache version: 66ea7bc403fa31cc353ca01539a15c2bcd5aef74
 * Web server + version: Apache2 2.4.18 (default OS pkg)
                       MySQL: 5.7.12
                       php: 7.0
 * Server operating system: Ubuntu 16.04 (upgraded from 15.10)
 * Client operating system: Windows
 * Client type:
   - [ x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Chrome 
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/239641/ampache.cfg.php.txt)

# Description
With previously working long usernames I now get 'username' too long errors.

I had a working ampache server running on Ubuntu 15.10 with user names like 'rick.sorensen@gmail.com', and then I upgraded to Ubuntu 16.04.  At that point, I had to make some modifications to the Php 7.0 install for php libraries before the login screen showed up.  After the login screen was appearing, on the first login attempt with login 'rick.sorensen@gmail.com' I saw nothing happen (no messages on the screen.)  I then tried to login as 'admin' which worked.  

I then turned on debug and retried- saw the 'username' too long error message.  I did a few experiments (see log file) with creating usernames 40, 30, 20, and 10 characters- and only usernames with length <20 (<16?) worked.  Again- no notification of error on the browser login window.

Note that as admin I could create all these username (long names, long names with spaces, long names with '@', ....) and enter them in the database.  Database queries return the entered usernames. 
Note also that if I enter a long username with an incorrect password I do get an invalid login message.

I suspect this is related to php 7. I tried searching the code but did not find a length check in the code (find . -name '*.php' -exec grep username {}\; | grep 'too long')(I also tried searching for debug and error, and *.inc files, but don't know php very well)

# Logs
[Ampache logs] (annotated by me- with #comments)

[ampache.20160427.log.annotate.txt](https://github.com/ampache/ampache/files/239645/ampache.20160427.log.annotate.txt)

**Comment by ricksorensen** [comment]
Just a testing note- I Switched Ubuntu/apache2 to php5.6, and this problem still occurs.

**Comment by ricksorensen** [comment]
This is looking like an interface issue with MySQL- or at least the 22001 error is indicated as an MySQL error (with 1406).  I don't fully understand why a read of a what looks like a valid user table entry would give this error- but here is my MySQL status of ampache database: (from 'status' command)
```
--------------
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

Connection id:          737
Current database:       ampache
Current user:           ampache@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.12-0ubuntu1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    latin1
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
```
 
and requesting user data (select * from `user`; ) gives
```
select * from `user`;
+----+-------------------------+---------------+-------------------------+---------+--------+-----------------------------------------------------------------+--------+----------+------------+-------------+------------+-------+------+----------------+
| id | username                | fullname      | email                   | website | apikey | password                                                         | access | disabled | last_seen  | create_date | validation | state | city | fullname_public |
+----+-------------------------+---------------+-------------------------+---------+--------+------------------------------------------------------------------+--------+----------+------------+-------------+------------+-------+------+-----------------+
|  1 | admin                   | Administrator |                         | NULL    | NULL   | 405e1cd41699a253992da6a1bcaf127ff5810311bf9e26c630c0469fa307458d |    100 |        0 | 1465150123 |  1458407791 | NULL       | NULL  | NULL |               0 |
|  2 | rick.sorensen@gmail.com | Rick Sorensen | rick.sorensen@gmail.com | NULL    | NULL   | ec73d822e0f1fdcfdacdd2236c1a07e840e989f9729f377cc45b7bb37242cf54 |     25 |        0 | 1461354070 |  1458501507 | NULL       | NULL  | NULL |               0 |
|  3 | rick                    |               | rick.sorensen@gmail.com | NULL    | NULL   | 405e1cd41699a253992da6a1bcaf127ff5810311bf9e26c630c0469fa307458d |     25 |        0 | 1464988625 |  1461559237 | NULL       | NULL  | NULL |               0 |
| 11 | tom                     |               | tsthedork@gmail.com     | NULL    | NULL   | 14d3c29df683e91b8ebdee0ca608d3c8c5a7104a288c27d15047768be7f1cbba |     25 |        0 | 1461987866 |  1461987762 | NULL       | NULL  | NULL |               0 |
| 12 | Ella                    |               | Ella.phillips@gmail.com | NULL    | NULL   | b1cabb16bab449b00c4b549373b1f97b98f2ef0f61f12cd7e38f12f3a84ce75a |     25 |        0 | 1462559226 |  1462506703 | NULL       | NULL  | NULL |               0 |
| 13 | 12345678901234567890    |               | x@y.org                 | NULL    | NULL   | 7c2c4df740f720b0c861920dc27692c4d4b5daa65d6330a593c931d35f8ac737 |      5 |        0 |          0 |  1465150116 | NULL       | NULL  | NULL |               0 |
+----+-------------------------+---------------+-------------------------+---------+--------+------------------------------------------------------------------+--------+----------+------------+-------------+------------+-------+------+-----------------+
6 rows in set (0.01 sec)
```

I haven't found the php/inc files yet that contain elements of  the ampache log error message:
`2016-06-05 13:08:54 [12345678901234567890] (Dba) -> Error: ["22001",1406,"Data too long for column 'username' at row 1"]`

**Comment by ricksorensen** [comment]
See:
[https://mattstauffer.co/blog/how-to-disable-mysql-strict-mode-on-laravel-forge-ubuntu](url)

(I am not proficient at databases- .... so caveat emptor)
It appears that MySQL 5.7 made STRICT_TRANS_TABLE standard for sql_mode for the first time.  I eliminated that setting per the instructions in above link and can now use long usernames.  It is unclear to me what the ramifications of this change is, in particular whether the fact that an error is reported in strict mode is significant.  I still haven't determined which SQL event is triggering the error ....

**Comment by Phyks** [comment]
I think a possible cause of this error is a type overflow (see [this page of the doc](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict)).

Username is a `VARCHAR(128)` which should be ok: https://github.com/ampache/ampache/blob/develop/sql/ampache.sql#L1156.

Still, in session tables, it is a `VARCHAR(16)` which might be the overlow you see (note that I did not dig enough in the code to ensure there was potentially an overflow issue here): https://github.com/ampache/ampache/blob/develop/sql/ampache.sql#L829


It may be also a missing value for a field without default value.


In any case, if you enable strict mode and increase verbosity of MySQL logs, I think you should have something appearing in the logs, that may hint what the issue really is. Could you try it out please?

Thanks

**Comment by ricksorensen** [comment]
I added a debug line to lib/class/session.class.php after the SQL to build a session- 
https://github.com/ampache/ampache/blob/develop/lib/class/session.class.php#L246
Line added when error declared: 
`debug_event('session', 'INSERT INTO error ' . $sql, '1');`

After re-enabling STRICT_TRANS_TABLES in sql_mode, and setting debug level to 5 for ampache the original symptoms recurred, and the new err in ampache log occured:(bold is error point)
2016-06-13 18:49:56 [ampache] (session) -> Unable to read session from key db5iehgvnsjh8ig8l3j7n6vkv3 no data found
2016-06-13 18:50:18 [ampache] (session) -> Unable to read session from key db5iehgvnsjh8ig8l3j7n6vkv3 no data found
2016-06-13 18:50:18 [12345678901234567890] (Dba) -> Error: ["22001",1406,"Data too long for column 'username' at row 1"]
2016-06-13 18:50:18 [12345678901234567890] (Dba) -> Error: ["22001",1406,"Data too long for column 'username' at row 1"]
2016-06-13 18:50:18 [12345678901234567890] (Dba) -> Error: ["22001",1406,"Data too long for column 'username' at row 1"]
2016-06-13 18:50:18 [12345678901234567890] (Dba) -> Error: ["22001",1406,"Data too long for column 'username' at row 1"]
**2016-06-13 18:50:18 [12345678901234567890] (session) -> INSERT INTO error INSERT INTO `session` (`id`,`username`,`ip`,`type`,`agent`,`value`,`expire`,`geo_latitude`,`geo_longitude`, `geo_name`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2016-06-13 18:50:18 [12345678901234567890] (session) -> Session creation failed**
2016-06-13 18:50:18 [ampache] (session) -> Unable to read session from key 9urglu5bqp5ncqjbi90iq87f23 no data found

It looks like it is indeed the username varchar(16) is the various session tables(session, session_remember) that is causing the error, and removing STRICT_TRANS_TABLES mode allows it to work.  It is my understanding that modifying a table field length is a non-trivial exercise- with potentially many side-effects?-

**Comment by ricksorensen** [comment]
Snippet from old mysql general.log (which I had forgotten about ...) .... showing actual SQL sent:
2016-06-08T16:21:39.290073Z  866 Connect	ampache@localhost on  using Socket
2016-06-08T16:21:39.290306Z  866 Query	SET NAMES utf8
2016-06-08T16:21:39.290430Z  866 Query	USE `ampache`
**2016-06-08T16:21:39.290717Z  866 Query	INSERT INTO `session` (`id`,`username`,`ip`,`type`,`agent`,`value`,`expire`,`geo_latitude`,`geo_longitude`, `geo_name`) VALUES ('rb7uq6glrics23q43r6s1icrg0', '12345678901234567890', 'K±', 'mysql', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', ' ', '1465406499', NULL, NULL, NULL)**
2016-06-08T16:21:39.291302Z  866 Quit	
2016-06-08T16:21:39.292570Z  867 Connect	ampache@localhost on  using Socket
2016-06-08T16:21:39.292903Z  867 Query	SET NAMES utf8
2016-06-08T16:21:39.293040Z  867 Query	USE `ampache`
2016-06-08T16:21:39.293323Z  867 Query	UPDATE `session` SET `value` = 'userdata|a:3:{s:7:\"success\";b:1;s:4:\"type\";s:5:\"mysql\";s:8:\"username\";s:20:\"12345678901234567890\";}', `expire` = '1465406499' WHERE `id` = 'rb7uq6glrics23q43r6s1icrg0'
2016-06-08T16:21:39.294378Z  867 Quit	
2016-06-08T16:21:39.378854Z  868 Connect	ampache@localhost on  using Socket
2016-06-08T16:21:39.379066Z  868 Query	SET NAMES utf8
2016-06-08T16:21:39.379147Z  868 Query	USE `ampache`
2016-06-08T16:21:39.379319Z  868 Query	SELECT * FROM `session` WHERE `id` = 'rb7uq6glrics23q43r6s1icrg0' AND `expire` > '1465402899' AND `type` IN('mysql')
2016-06-08T16:21:39.379937Z  868 Query	DELETE FROM `session` WHERE `id` = 'rb7uq6glrics23q43r6s1icrg0'
2016-06-08T16:21:39.380412Z  868 Quit

**Comment by Phyks** [comment]
Yes, I am almost sure it comes from the VARCHAR field.

Could you try increasing the value of the VARCHAR field `username` in `session` table? This should be:
```
ALTER TABLE session MODIFY username VARCHAR(255);
```
in CLI for instance (or you can do it graphically with something like PHPMyAdmin if you are used to it).

Please ensure you have a recent backup if you consider your database important, so that I will not be responsible for any data loss :)

Let me know if this fixes the issue, after having restablished `STRICT_MODE` as it was out of the box.


If it is the case, we can think of a fix. I am not sure to understand why there is a duplicated field to store `username`. As far as I understand, it is only here for caching. If anyone has more infos on this, please let me know so that we can come up with the best fix.

**Comment by Afterster** [comment]
Wow, it should never have been limited to varchar(16) on session table... I don't know who did this without changing all tables but it was here since several years and should be same length than on user table of course. Thanks for founding the issue.

**Comment by Phyks** [comment]
There is also the same thing in `session_remember` table, and a discrepancy between sizes in `user` table and `user_remote` table.

Yw

**Comment by ricksorensen** [comment]
I checked the active database for the session and session_remember data:
session had 2 rows, both with empty username.
session_remember had 0 rows.

I cloned the database (from ampache to ampache_clone), and changed ampache.cfg.php to reflect this.  I also update the field sizes in ampache.sql (? but this probably only affects things at database creation?) and then returned the my.cnf (mysql config) to STRICT_TRANS_TABLE and restarted mysql.

I verified the long usernames still did not work for login.
I then altered the field size in the cloned version of my database:
ALTER TABLE session MODIFY username VARCHAR(128);
(1 Row altered)
ALTER TABLE session_remember MODIFY username VARCHAR(128);
(0 Row altered)
 I didn't find a user_remote table, so I made no other changes.

Retried login and this time the long login names did work.  I wonder if this works largely because these are dynamic tables with each login session?  Anyway, I will leave the (5.7 default) STRICT mode enabled and keep testing, but changing the field sizes seems to solve the login issue.

Thanks for the pointers.
Rick

**Comment by Phyks** [comment]
Good news! So homogeneizing field lengths in `ampache.sql` should solve the issue. Still, I know there is a way in Ampache to update the database properly, applying required updates between versions but I'm not sure about the correct way to implement it.

**Comment by ricksorensen** [comment]
I just tried an experiment using only the mods to ampache.sql, without the direct resetting of the field lengths.... this did not work.  So it looks like databases need to be upgraded directly through SQL if they already exist.  Maybe the ampache.sql mods work when first creating the database?

**Comment by Phyks** [comment]
Yes sure, `ampache.sql` is just used at db creation. So changing `ampache.sql` works for a new installation.

To handle the update properly, one should edit [this file](https://github.com/ampache/ampache/blob/ad270da63210f9870df0358d90d4480819ea7358/lib/class/update.class.php#L3913) as well. However, I am not sure what is the correct way to do it, in particular which version should be set.

Ping @Afterster

**Comment by Afterster** [comment]
update.class.php must be updated indeed. The version number is incremental, just do +1 ;)

**Comment by Phyks** [comment]
^ Should be fixed.
