### ISSUE TITLE
copy database users from one to another db

### ISSUE THREAD

**Issue by Khymick** [ampache/ampache#1218]
Hi there,

this is no real issue (and also not directly connected to ampache), but as I am not that deep into working with databases, I thought I just ask:

I have two different installation of ampache running here, also one "productive" and one "testing" with two different databases. The testing one is always slightly a newer version of the productive one. Is there any way to simply copy the users from the productive to the testing one? I saw that there is a table called "users" in both databases, but I am not sure if there is any way to simply copy the entries.

Beside, I use MySQL as database engine.

Greets

**Comment by Afterster** [comment]
You should be able to copy, export/import your users from one Ampache db to another without issue, just by using regular SQL SELECT and INSERT commands ;).
