### ISSUE TITLE
Columns question

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#1219]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: 
 * Server operating system: ubuntu 12.04
 * Client operating system: 

Hi i work on a radio station (cultural radio) and we want to use Ampache as our library and i want to know if there is a way to add the Column "Composer" (along with Title, Album, Tags, Time, Favs, Action...) because when a song is introduced to the audience we mention also the Composer of that song.

We put The composer information on the ID3 tag and it is recognized by ampache because i can see it on Details of the song.

Thank you in advance for your help.

**Comment by Afterster** [comment]
This is possible but a bit specific for now, you will have to patch on your installation.
No option will be added to Ampache with current UI (already enough a mess).

To patch it, see https://github.com/ampache/ampache/blob/3.8.2/templates/show_songs.inc.php#L36 and https://github.com/ampache/ampache/blob/3.8.2/templates/show_song_row.inc.php#L68.
Print song composer with `scrub_out($libitem->composer)`.
