### ISSUE TITLE
Create Channel error "Unable to fork"

### ISSUE THREAD

**Issue by strikerlord** [ampache/ampache#1223]
# Environment
- Ampache version: Ampache 3.8.3-develop
- Web server + version: IIS 6.2 (build 9200)
- Server operating system: Server 2012 R2
- Client operating system: W8.1
- Client type: 
  - [x] Web
  - [ ] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
- Client application + version: Firefox and Chrome
# Settings

Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)
[ampache.cfg - shareable 220516.zip](https://github.com/ampache/ampache/files/276560/ampache.cfg.-.shareable.220516.zip)
# Description

Once a channel is created it is not possible to start the channel, in the log the error "Unable to fork" comes up after running the script from the site as an admin level user.
# Logs

[ampache.20160519.zip](https://github.com/ampache/ampache/files/272839/ampache.20160519.zip)

**Comment by Afterster** [comment]
Web interface assume you're using linux, maybe the check can be extended to Windows but for now could you try to start your channel manually https://github.com/ampache/ampache/wiki/Channels#start-a-channel?

**Comment by strikerlord** [comment]
Hi Afterster,

I am running the system on Windows Server 2012 R2.

Without changing anything (except for deleting the channel that was created that gave the error " unable to fork") i am now getting errors on DBA that there is an incorrect value on the "is_private" column even though the playlists are public.

added the log again.
[ampache.20160605.zip](https://github.com/ampache/ampache/files/299366/ampache.20160605.zip)

**Comment by Phyks** [comment]
Could you check what the value of `is_private` is in your db?

**Comment by strikerlord** [comment]
It took me a while to get familiar with the MySQL commands and such (in my studies i barely passed the SQL course xD where I got really good grades on the other subjects :))

In the attachment a screenshot of the entire Channel table.
The value for is_private seems to be set to 0.

![desc channelj](https://cloud.githubusercontent.com/assets/15890009/17809832/7b1f344c-6619-11e6-89d9-399648e592b7.jpg)

tested on creating a channel today again, this now gives the error "unable to fork" again instead of the incorrect is_private error, maybe this is something that gets released "over time".... i don't know, hope this was something simple and stupid.
Back to the Fork error now :( .

2016-08-19 14:04:12 [admin] (browse) -> Show objects called for type {channel} 
2016-08-19 14:04:14 [admin] (session) -> agbpiv1b5bpbf14c466c86mfc3 has been extended to Fri, 19 Aug 2016 15:04:14 +0200 extension length 3600 
2016-08-19 14:04:14 [admin] (ajax.server.php) -> Called for page: {browse} 
2016-08-19 14:04:14 [admin] (browse.ajax.php) -> Called for action: {get_filters} 
2016-08-19 14:04:19 [admin] (session) -> agbpiv1b5bpbf14c466c86mfc3 has been extended to Fri, 19 Aug 2016 15:04:19 +0200 extension length 3600 
2016-08-19 14:04:19 [admin] (ajax.server.php) -> Called for page: {index} 
**2016-08-19 14:04:21 [ampache] (PHP) -> [Runtime Error] exec(): Unable to fork [php C:\inetpub\wwwroot\Ampache (project)\Ampache/bin/channel_run.inc -c 3 &gt; /dev/null &amp;] in file C:\inetpub\wwwroot\Ampache (project)\Ampache\lib\class\channel.class.php(302)** 
2016-08-19 14:04:28 [admin] (session) -> agbpiv1b5bpbf14c466c86mfc3 has been extended to Fri, 19 Aug 2016 15:04:28 +0200 extension length 3600 
2016-08-19 14:04:28 [admin] (ajax.server.php) -> Called for page: {index} 
2016-08-19 14:05:02 [ampache] (session) -> Unable to read session from key d1akla6vpqrlrb4hncr0r81sc6 no data found 
2016-08-19 14:05:02 [ampache] (session) -> Session created: mrov7ocb5gv2gclf1vg7e68817

**Comment by Phyks** [comment]
Ok for the `is_private`, let's forget about it for the moment as it is no longer here.

For the "Unable to fork" error, have you tried to start your channel manually? (https://github.com/ampache/ampache/wiki/Channels#start-a-channel)

Do you have a similar error in such a case?

**Comment by strikerlord** [comment]
@Phyks , i have never used a terminal as of yet to set off commands for PHP sites.
In this case am running it on a W2012R2 installation with IIS, the commands are writen for Linux installations, how can i run this command in a console for windows? 
Does CMD suffice and if so, how do i translate the php bin location to the windows location?

**Comment by strikerlord** [comment]
So, here is what i tried:
I started up CMD and navigated to the ampache root folder with cd command.
once CMD was in that folder I started PHP interactive with php -a.
then i run the command as suggested (php bin/channel_run.inc -c 3 > /dev/null &) (channel ID is 3.)

nothing shows up in the Command line screen, no confirmation or anything, and in the Ampache log i don't see any activity.
either I am doing something wrong, or something else is wrong :).

Suggestions?

**Comment by wagnered** [comment]
You don't say what version of php is installed.

    see https://forums.iis.net/t/1161333.aspx?unable+to+fork+the+mystery+

which indicates a problem with php-5.3

Also check out:

    https://forums.iis.net/p/1216283/2084546.aspx

caused by conflicting IIS settings.

Just throwing it out there.O:-)

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by strikerlord** [comment]
@wagnered  , you sir are a genius!
The article (2084546) did indeed create the forking issue.
I changed the anonymous user identity to use the application pool identity for the website and this removed the fork error.

I thank you a lot!
still didn't get the channel running, but those are configuration issues I need to run through :)

**Comment by wagnered** [comment]
Thanks, but not really: Actually I abhor Windows, I just know how to use
search engines.;-)

If the fork problem was solved, you should close this issue and create
another one on the channel problem if necessary.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by strikerlord** [comment]
Closing the issue, and thank you for the better google work then i did :)!
