### ISSUE TITLE
Footer hidden by player

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1224]
Hi,

In `3.8.3-develop` version (I do not have the exact commit version, maybe @Niols has it as it is on his instance), the footer is hidden by the player. See attached picture.

This is the very bottom of the page I can see, footer is behind the webplayer and cannot be seen:

![2016-05-19-170245](https://cloud.githubusercontent.com/assets/3856586/15398355/9a50d588-1de3-11e6-9069-139ad09beebe.png)

Thanks

EDIT: Not sure if it is new and/or intended, but I never noticed it before. As a side note (but part of any longterm UI rework I think), the buttons on the webplayer are quite small and not really visible. I've just discovered the "toggle visibility" button on the webplayer after having created this issue, although I am using Ampache almost daily :)

**Comment by Afterster** [comment]
Indeed, but this is here since more than one year now I think :).
It will not be fixed until a new UI, I'm gonna close this issue then but thanks for reporting this kind of problem.

**Comment by Phyks** [comment]
Ok, np. I just noticed it now, sorry for the noise :)
