### ISSUE TITLE
Channel Not Working (Apache)

### ISSUE THREAD

**Issue by Nassiel** [ampache/ampache#1226]
# Environment
- Ampache version: 3.8.2
- Web server + version: Apache 2.4.6
- Server operating system: Centos 7
- Client operating system: Windows 10
- Client type:
  - [X ] Web
  - [ ] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
- Client application + version: Ampache Web Page
# Settings

ampache config
        websocket_address = "ws://localhost:8100"

VirtualHost config
        ProxyPass /ws ws://127.0.0.1:8100 retry=0
        ProxyPassReverse /ws ws://127.0.0.1:8100 retry=0
        ProxyRequests off
        ProxyTimeout 15
# Description

My configuration of apache virtual host is inferred from the nginx configuration because i didn't found the base .htaccess for the root directory. I didn't modify any of channel or play. 
So after creating a playlist i created two channel with port 8200 and 8201, both when i try to run them with this websocket_run.inc script, it throws the log data. Obviously, channels doesn't work. The socket for 8100 runs perfect but i can't broadcast anything too.

Thanks, any other detail that you need, please feel free to ask anything. Thank you very much in advance.
# Logs

-->php websocket_run.inc -p 8100 > /dev/null & -> RUNS PERFECT
-->Channel 2 config - stream URL http://127.0.0.1:8201/stream.mp3
-->php websocket_run.inc -c 2 > /dev/null & throws:
PHP Fatal error:  Uncaught React\Socket\ConnectionException: Could not bind to tcp://0.0.0.0:8100: Address already in use in /var/www/html/lib/vendor/react/socket/src/Server.php:29
Stack trace:
#0 /var/www/html/lib/vendor/cboden/ratchet/src/Ratchet/App.php(80): React\Socket\Server->listen(8100, '0.0.0.0')
#1 /var/www/html/bin/websocket_run.inc(58): Ratchet\App->__construct('localhost', 8100, '0.0.0.0')
#2 {main}

  thrown in /var/www/html/lib/vendor/react/socket/src/Server.php on line 29

**Comment by Nassiel** [comment]
If i try to explicitly create a socket on port 8200, 
#php websocket_run.inc -p 8200 > /dev/null &
this is the result:
PHP Fatal error:  Uncaught React\Socket\ConnectionException: Could not bind to tcp://127.0.0.1:8843: Address already in use in /var/www/html/lib/vendor/react/socket/src/Server.php:29
Stack trace:
#0 /var/www/html/lib/vendor/cboden/ratchet/src/Ratchet/App.php(93): React\Socket\Server->listen(8843)
#1 /var/www/html/bin/websocket_run.inc(58): Ratchet\App->__construct('localhost', 8200, '0.0.0.0')
#2 {main}
  thrown in /var/www/html/lib/vendor/react/socket/src/Server.php on line 29

**Comment by Afterster** [comment]
Looks like a [Ratchet](https://github.com/ratchetphp/Ratchet) limitation I wasn't aware of: two channels can't be started at the same time for now...
But your first channel should work, anything on Ampache log, verbose output or browser console?
