### ISSUE TITLE
User can't play democratic playlist

### ISSUE THREAD

**Issue by strikerlord** [ampache/ampache#1227]
# Environment
 
 * Ampache version: Ampache 3.8.3-develop
 * Web server + version: IIS 6.2 (build 9200)
 * Server operating system: Server 2012 R2
 * Client operating system: W8.1
 * Client type: 
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Firefox and Chrome
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)
[ampache.cfg - shareable 220516.zip](https://github.com/ampache/ampache/files/276559/ampache.cfg.-.shareable.220516.zip)

# Description
I have created a democratic playlist with the Admin account and this is running fine, i can tune in on the playlist with the playbutton on the democratic playlist page with that account.
Once i log in under a user account i can vote for songs and access the democratic page, but there is no play option vissible as there is under the admin account.

This might just be a goof on my end, but i have been searching and trying out all settings available on the Ampache settings page, and i can't get it working for a normal user account.
It is playable to the level of Catalog manager, lower than that the play option is not showing.

any thoughts on what i am missing?

# Logs
no logs available since the option im looking for isn't showing.

**Comment by strikerlord** [comment]
Right, as said earlier I might made a goof on my end.
after reading the documentation again and again it started to dawn on me that the functionality of the democratic playlist is different from what i interpreted.
" ...many users and a single output source." I didn't read that part right :).

the playlist is democratic while only one source will play this playlist, it is not meant to be multi client like the channels are, my bad!

**Comment by Afterster** [comment]
Indeed this is the goal of this feature ;)
