### ISSUE TITLE
I can't start install: no language available...

### ISSUE THREAD

**Issue by thymon13** [ampache/ampache#1228]
Hi all,

I can't start the ampache installation.
Because I've no languague choice...

[Screen](http://img11.hostingpics.net/pics/311260Ampache.png)

I do not know what to do...

Tanks in advance.

**Comment by Afterster** [comment]
This version is too old and no support will be officially provided for this one, you should use a more recent version (in any case, always test with latest version before posting an issue in case it is already fixed). Thanks.

**Comment by thymon13** [comment]
Too old ??

But I used "apt-get ampache"

Is not the last version ?

**Comment by Psy-Virus** [comment]
Hey @thymon13,

the Ampache package is outdated. You should try to use the latest development version by cloning via git or the latest [main release](https://github.com/ampache/ampache/releases/tag/3.8.2) and install Ampache manually.

:-)
