### ISSUE TITLE
Column's filtering review

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#123]
_Issue by **[SUTJael](https://github.com/SUTJael)** from Friday Mar 21, 2014 at 13:21 GMT_
_Originally opened as https://github.com/ampache-doped/ampache-doped/issues/169_

---

First implementation is fine but there's still few improvements to do before next release:
- No transparency for the menu
- Save parameters to local cookies
- Columns are reset when filtering (example: go to the albums, then filter by name)
- Columns overlay if screen is too small (improve the display/hide algo to limit the table size to the middle panel content)
- Add a new option to reset the column filtering to the default state
- Maybe some others, need to test it more.

**Comment by nearwood** [comment]
I'm having the same problem as anettles. It doesn't remember my column filter settings. Lemme investigate a bit more and clear out my cache and cookies since I just updated to the new ui branch.
