### ISSUE TITLE
Internal server error with xbmc localplay plugin

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1232]
Hi, 

I installed Ampache following the instructions in the wiki (git clone of the develop branch + composer install).

I wanted to have the localplay MPD controller. So I followed the infos in the wiki about it, but I could not load the page `/index.php#admin/modules.php?action=show_localplay`. When looking at the debugger console in my browser, I saw there was a 500 internal server error on the queried page.

It appears this was due to the `xbmc` controller, and I could not figure out what was happening. Simply removing the `xbmc` folder from `modules/localplay` did solve the problem.

Same type of error was happening in `Settings/Options` page as well.

My setup is very standard, Apache and PHP. I could not find any trace of this error either in Apache log nor in Ampache log.

**Comment by Phyks** [comment]
Ok, I found out there was error silencing in xbmc module. Removing the leading `@` to the include, I got:

```
<b>Fatal error</b>:  'continue' not in the 'loop' or 'switch' context in <b>/srv/http/ampache/lib/vendor/krixon/xbmc-php-rpc/rpc/Client.php</b> on line <b>255</b><br />
```

So definitely not Ampache fault, but still of high impact for Ampache.

**Comment by Phyks** [comment]
Reported the error upstream: https://github.com/krixon/xbmc-php-rpc/issues/3. Weird that nobody seemed to be affected by this before.

**Comment by Phyks** [comment]
I shot him an email to see if the repo is actually abandoned or not.

What about forking `krixon/xbmc-php-rpc` in the Ampache org on Github and pulling the fix in it and tracking it from Ampache?

**Comment by Afterster** [comment]
Well any abandoned dependency should be handled this way yes (forking on Ampache orga). But this should be the latest solution of possible, I really would like to avoid as much fork as possible.

**Comment by Phyks** [comment]
Sure, but I could not get any answer from the author on this.

I solved the two opened issues on the xbmc-php-rpc project in my fork: https://github.com/Phyks/xbmc-php-rpc.

Feel free to fork it under Ampache namespace and track it if you want, and this would solve this issue. Please do not track directly the repo under my namespace, as I cannot guarantee its lifetime.

**Comment by Phyks** [comment]
Solved with the merge of https://github.com/Phyks/xbmc-php-rpc/commit/908078900c3761c54e62d96fc07ba65a3ffc21e1! =)

Guess at next composer install/update it will be fixed as Ampache tracks Git branch master.
