### ISSUE TITLE
Server-Sent Events connection error. Re-connection...

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1233]
# Environment
 
 * Ampache version: Latest develop branch commit
 * Web server + version: Apache
 * Server operating system: Linux
 * Client operating system: Linux
 * Client type:
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Chromium or Firefox, latest (out of the box, so not a plugin error)

# Description

When trying to update or add on a catalog, I get a `Server-Sent Events connection error. Re-connection...`. Very similar to https://github.com/ampache/ampache/issues/737 although this one solved itself automagically. Very similar to https://github.com/ampache/ampache/issues/1162 as well, except this PR has been merged and should be fixed.

I am on it, trying to get some ideas about it, or at least manage to get some error in the logs.

**EDIT**:

Seems that the associated error is
```
[Wed Jun 01 14:42:46.644622 2016] [:error] [pid 875] [client 192.168.1.20:34180] PHP Fatal error:  Uncaught Error: Call to undefined function ngettext() in /srv/http/ampache/lib/class/catalog.class.php:599\nStack trace:\n#0 /srv/http/ampache/modules/catalog/local/local.catalog.php(592): Catalog::get_stats('1')\n#1 /srv/http/ampache/lib/class/catalog.class.php(1799): Catalog_local->clean_catalog_proc()\n#2 /srv/http/ampache/lib/class/catalog.class.php(2344): Catalog->clean_catalog()\n#3 /srv/http/ampache/server/sse.server.php(67): Catalog::process_action('full_service', Array, Array)\n#4 {main}\n  thrown in /srv/http/ampache/lib/class/catalog.class.php on line 599, referer: http://AMPACHE
```

**Comment by Phyks** [comment]
This is solved, it was due to the absence of `gettext` PHP extension on my server.

@Afterster It is not listed in requirements in the `README.md`: https://github.com/ampache/ampache#requirements and is not covered by a test case in the preinstallation check. Maybe it would be worth adding such a case? What do you think about it?

**Comment by Afterster** [comment]
Mhh gettext php extension should be optional thanks to https://github.com/oscarotero/Gettext dependency
If translation is working correctly on web ui but not catalog update only, I believe it's only a dependency loading issue on catalog update context.

**Comment by nasariasl** [comment]
yesteday i recived similar error when adding or updating new catalogs
after 60 day from running ampache server without error i recived Server-Sent Events connection error. Re-connection
--------
i able to update artist , videos image but i not able to add or update albums images
i enabled debug mode but in debug i cant see any error and when i want to add album cover i just delete Previous arts and cant add new images
:::
2016-06-01 09:54:11 [My-Music] (session) -> 9aeik13phl0g28tuqdt62kvo16 has been extended to Wed, 01 Jun 2016 10:54:11 +0200 extension length 3600 
2016-06-01 09:54:11 [My-Music] (session) -> Session created: ef137ab13c1c711fc945378e5b2728fd 
2016-06-01 09:54:11 [My-Music] (Art) -> Deleting E:\server\www\avayeman\metadata\album\5010\default\ directory... 
2016-06-01 09:54:11 [My-Music] (Art) -> Inserting image Album Film Musicآلبوم موسیقی فیلم on songs.

**Comment by Phyks** [comment]
@Afterster ok, ty for the hint. I will try to see if I can find a fix for it :)

**Comment by Phyks** [comment]
@Afterster ok, indeed catalog update does not use PHP gettext dependency: https://github.com/ampache/ampache/search?utf8=%E2%9C%93&q=ngettext&type=Code. I will submit a PR to fix it.

Is it expected that in the `gather-messages.sh` script there are unused keywords? https://github.com/ampache/ampache/blob/67a8477dbac9336877596bb4b2d3864f7280d1ce/locale/base/gather-messages.sh#L68

Indeed, `T_gettext` and `T_ngettext` does not return any match on the code. `ngettext` should not be used according to previous comments.

**Comment by Phyks** [comment]
Think we can close it now :)
