### ISSUE TITLE
Artist images not being generated until you viewing it.

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1235]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: nginx/1.8.1
 * Server operating system: CentOS
 * Client operating system: Windows 10
 * Client type:
   - [x] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Chrome 50.0.2661.102

# Description
Just downloaded a fresh copy of Ampache-full and set it up. Added a couple catalogs and got things underway. I noticed that browsing the Artist page shows all missing Artist art. However upon clicking on an artist, it usually automatically loads an image, which is then permanently stored.

Is there any way to pre-generate all of these images? There's over a thousand artists and would take a while to go through and click each one..... Thanks!

**Comment by kuzi-moto** [comment]
Any thoughts on this?

**Comment by Afterster** [comment]
This is the normal behavior.
You should set `deferred_ext_metadata` to false on ampache.cfg.php

**Comment by Phyks** [comment]
Also, there is a "Gather all media art" link in Catalog settings. Did not try it myself, but isn't it supposed to do precisely this?

Closing this, reopen with a proposal for a new behavior that we could discuss if the two above mentionned solutions do not fit.
