### ISSUE TITLE
Problem with Channel/Port

### ISSUE THREAD

**Issue by ivandrago228** [ampache/ampache#1237]
# Environment
- Ampache version: 3.8.2
- Web server + version: 2.4.6
- Server operating system: Ubuntu 14.04
- Client operating system: Ubuntu/Mac
- Client type:
  - [ X ] Web
  - [ ] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
- Client application + version: Ampache Web Page
# Settings

ampache config:
websocket_address = "ws://localhost:8100"

VirtualHost config:
ProxyPass /ws ws://127.0.0.1:8100 retry=0
ProxyPassReverse /ws ws://127.0.0.1:8100 retry=0
ProxyRequests off
ProxyTimeout 15

Channel config:
URL: _MY_IP_
Intreface: 127.0.0.1 

nginx config:
server {
[...]
   location /ws {
      rewrite ^/ws/(.*) /$1 break;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_pass http://127.0.0.1:8100/;
   }
}
# Description

I cant connect from the outside to icecast (127.0.0.1:8100).
On the server running(i can connect to m3u playlist).

If i try connect to "http://_MY_IP_/1/stream.mp3"  error: The requested URL /channel/1/stream.mp3 was not found on this server.
Could you help me?
# Logs

If i try choose in "Interface Channel" my ip address i cant enable channel.
Error from log: unable to connect to tcp://_MY_IP_:8100 (Cannot assign requested address) in file /var/www/html/bin/channel_run.inc(101) )

**Comment by Phyks** [comment]
This does look like you miss a rewrite rule. Could you provide more infos on this issue?

**Comment by mitchray** [comment]
Closed due to inactivity
