### ISSUE TITLE
API is returning empty XML file

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#1242]
# Environment
 
 * Ampache version: 0a0721525b0be7d9448e5cae2114fb2cab95b27a
 * Web server + version: Nginx 1.2.1
 * Server operating system: Debian 7
 * Client operating system: Mac Yosemite
 * Client type:
   - [ ] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Firefox 
 
# Settings
Pretty much standard, I don't think I've changed anything.

# Description
Whenever I try to use the xml.server.php API the returned file is always empty. Ampache logs the problem in it's logs but doesn't write it in the XML file for some reason. 

> 2016-06-06 21:05:25 [ampache] (API) -> Login Attempt, IP:(my ip) Time: 1465272209 User:admin (1) Auth:e42208be8f601d1d15568f534e0683fc2f19f8a7a08e999418fdf7e472828556 
> 2016-06-06 21:05:25 [ampache] (API) -> Login Failed, unable to match passphrase 

If it's relevant the ajax.server.php file returns a file with text in it.

If you'd like access to the server for testing, please let me know!

**Comment by Phyks** [comment]
Same here. Can reproduce.

**Comment by Niols** [comment]
Indeed, here are server logs (debug level: error + warn) when @Phyks reproduced the error:

    2016-06-07 11:38:55 [ampache] (API) -> Login Attempt, IP:(Phyks's IP) Time: 1465292388 User:phyks (9) Auth:e470739d47d8c3b85253a285a3ee1e2b2d95e00b26cbb1c46144471d159e6f7c 
    2016-06-07 11:38:55 [ampache] (API) -> Login Failed, unable to match passphrase

**Comment by Niols** [comment]
Debug level 5 (debug) doesn't really provide more information:

    2016-06-07 11:45:35 [ampache] (API) -> Handshake Attempt, IP:176.183.110.17 User:phyks Version:350001 
    2016-06-07 11:45:35 [ampache] (API) -> Login Attempt, IP:(Phyk's IP) Time: 1465292388 User:phyks (9) Auth:e470739d47d8c3b85253a285a3ee1e2b2d95e00b26cbb1c46144471d159e6f7c 
    2016-06-07 11:45:35 [ampache] (API) -> Login Failed, unable to match passphrase

**Comment by Phyks** [comment]
And note that the XML file is actually *not* empty, although it seems to be.

```
$ % stat information.xml
[…] Size : 3 […]
```

It contains
```
b'\xef\xbb\xbf'
```

**Comment by AshotN** [comment]
> Size : 3

I've had some files be 0 bytes, and some 3 bytes... not sure why.

**Comment by Phyks** [comment]
Actually not. This is happening if you do fail your authentication. But if you authenticate properly, you have the correct XML file.
