### ISSUE TITLE
Prompt user to change secret_key during install.

### ISSUE THREAD

**Issue by BoBeR182** [ampache/ampache#1248]
# Environment
 
 * Ampache version: fbbc3bd51736b99f4d56bfa5e6543f4d3b337197
 * Web server + version: Apache
 * Server operating system: Linux
 * Client operating system: Linux
 * Client type:
   - [ ] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)

# Description
Here the bug/feature description and how to reproduce/integrate it.

Ampache should prompt the user to change the secret_key when asking for database info during the web installer.

# Logs
[Ampache logs](https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging) and web server access/error logs in attached files. Please also add client application logs if appropriate.

**Comment by Phyks** [comment]
:+1: for this.

Maybe there should be an input for the secret_key, prefilled with some random text? Still, I think it should be outside of the database fieldset, and maybe should be grouped together with webpath input which is currently not in the right section as well.

**Comment by AshotN** [comment]
How about we just generate a random secret. From my understanding that'll be more secure than having someone type their password in confusion.

**Comment by Phyks** [comment]
:+1:

Though, it has to be a crypto secure generated secret. Something like `bin2hex(openssl_random_pseudo_bytes(LENGTH));`?

**Comment by Phyks** [comment]
^ Above PR should do the trick. It generates a 32 bytes long secret key.
