### ISSUE TITLE
Ampache web player won't play ogg files

### ISSUE THREAD

**Issue by DarwinAwardWinner** [ampache/ampache#1250]
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: 2.4.18-2ubuntu3
 * Server operating system: Ubuntu 16.04 LTS
 * Client operating system: Mac OS 10.11.5
 * Client type: Web
 * Client application + version: Firefox 47.0
 
# Settings
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/310703/ampache.cfg.php.txt)

# Description
When I try to play any ogg file in the web player, it acts like it's starting to play, and then immediately stop/skips the track, never producing any sound, as if the audio track had zero length. MP3 files play just fine.

# Logs
Full Ampache log: [ampache.20160612.log.txt](https://github.com/ampache/ampache/files/310705/ampache.20160612.log.txt)
Ampache log excerpts: 
[trying-to-play-ogg-log.txt](https://github.com/ampache/ampache/files/310706/trying-to-play-ogg-log.txt) 
[playing-mp3-log.txt](https://github.com/ampache/ampache/files/310707/playing-mp3-log.txt)

Corresponding Apache access.log excerpts:
[trying-to-play-ogg-apache-log.txt](https://github.com/ampache/ampache/files/310709/trying-to-play-ogg-apache-log.txt)
[playing-mp3-apache-log.txt](https://github.com/ampache/ampache/files/310710/playing-mp3-apache-log.txt)

**Comment by DarwinAwardWinner** [comment]
In my streaming preferences, I tried disabling "Authorize Flash Web Player(s)" and enabling "Authorize HTML5 Web Player(s)", which made ogg files start working. Not sure why, since last time I tried the HTML5 player a few months ago it didn't work at all for me.

**Comment by DarwinAwardWinner** [comment]
By the way, I should emphasize that Ampache didn't produce any error messages before. It simply acted like all ogg files were valid audio files with zero length.

**Comment by Phyks** [comment]
I have been using the HTML5 player for a while, and it worked pretty well in my case, except from #1127 which is still to be investigated.

I can confirm the issue with the Flash player though.

As far as I know, Ampache is using [jplayer](http://jplayer.org/) and the Flash version does not support ogg (see bottom of the page).

I guess Ampache is missing transcoding rules in such cases.

**Comment by Afterster** [comment]
Hum OGG shouldn't be tried with Flash player. Maybe HTML5 wasn't enabled?
Normally if both are enabled the player should know automatically if it needs to use Flash or HTML5.

**Comment by DarwinAwardWinner** [comment]
I think the HTML5 player was disabled when I checked the settings later. (I guess I thought you were only supposed to enable one of them?) It would have been nice if it gave some error telling me why they weren't playing.

**Comment by Afterster** [comment]
Mhh normally you should have get this message: `This media is not supported by the player. Is your browser up to date?` just behind the player. But maybe flash backend is mixing the things up.

**Comment by Phyks** [comment]
Ok, I managed to reproduce it. If you only enable Flash webplayer, it works as expected:
![2016-06-14-113107](https://cloud.githubusercontent.com/assets/3856586/16038073/b6496b5c-3223-11e6-92c6-9a5280e7261d.png)


However, if you enable both Flash webplayer and "Use Aurora.JS …", but disable the HTML5 webplayer, you get the waveform and it is trying to play the song, but fails:
![2016-06-14-113136](https://cloud.githubusercontent.com/assets/3856586/16038095/ceaf4586-3223-11e6-8dc0-d97eff975251.png)

**Comment by DarwinAwardWinner** [comment]
Yes, I think that matches my settings when I encountered the problem.

**Comment by Phyks** [comment]
Some extra debugging:

When enabling both Aurora.JS and Flash player, we get these jplaylist options:
```
jplaylist = new jPlayerPlaylist({
            jPlayer: "#jquery_jplayer_1",
            cssSelectorAncestor: "#jp_container_1"
        }, [], {
            playlistOptions: {
                autoPlay: true,
                loopOnPrevious: false,
                shuffleOnLoop: true,
                enableRemoveControls: true,
                displayTime: 'slow',
                addTime: 'fast',
                removeTime: 'fast',
                shuffleTime: 'slow'
            },
            swfPath: "https://music.b-six.rocks/lib/vendor/happyworm/jplayer/dist/jplayer",
            preload: 'none',
            audioFullScreen: true,
            smoothPlayBar: true,
            keyEnabled: true,
            solution: "flash,aurora",
            nativeSupport:true,
            oggSupport: false,
            supplied: "oga",
            volume: jp_volume,
            auroraFormats: 'flac, m4a, mp3, oga, wav',
            size: {
                width: "80px",
                height: "80px",
            }
        });
```

As you can see, file is in `oga` format, enabled players are Flash and aurora.js and aurora supported formats list contains `oga`.

So the webplayer states that this file is supported and (I guess) tries to read it using Aurora.


The supported formats are hardcoded on [this line](https://github.com/ampache/ampache/blob/ad270da63210f9870df0358d90d4480819ea7358/templates/show_html5_player.inc.php#L68). Flac, m4a and mp3 are explicitly supported, provided in the examples of Aurora.JS: https://github.com/audiocogs/aurora.js/.

I did not find more at the moment, but it really looks like an issue with aurora.js. Especially since `vorbis.js` and `ogg.js` in https://github.com/ampache/ampache/tree/ad270da63210f9870df0358d90d4480819ea7358/modules/aurora.js never seem to be loaded by my browser.

**Comment by Phyks** [comment]
Ok, got an idea. Have a look at http://jplayer.org/latest/developer-guide/.

```
* Add the aurora.js JavaScript file to the HTML. The library core adds support for WAV:
<script src="aurora.js"></script>

* Add the Aurora Codec JavaScript files you require to the HTML. For example, add FLAC and OGG support. (OGGs use Vorbis or Opus):
<script src="flac.js"></script>
<script src="ogg.js"></script>
<script src="vorbis.js"></script>
<script src="opus.js"></script>
```

We never include the JS codecs files, hence aurora.JS does not work.

I cannot test it at the moment, will do as soon as I can.

**Comment by Afterster** [comment]
Well Aurora.js support on jPlayer was a PR done by myself :smile:.
So this is not the root of the issue as Aurora.js should be included, see https://github.com/ampache/ampache/blob/ad270da63210f9870df0358d90d4480819ea7358/templates/show_html5_player_headers.inc.php#L52

**Comment by Phyks** [comment]
^^

Sure, it is included, but the codecs are not included, are they? At least, as I understand the statement from jplayer doc, the aurora.js inclusion only handles wav files, and we should add extra includes for codecs, no?

If this is not it, I will try to find what is the root cause of the issue.

**Comment by Phyks** [comment]
I checked and adding the codecs includes does fix the issue. See above PR.
