### ISSUE TITLE
Option to show all tracks of Interpret

### ISSUE THREAD

**Issue by gsantner** [ampache/ampache#1257]
# Environment
- Ampache version: 3.8.3
- Web server + version: Apache  2.4.10
- Server operating system: Debian 8
- Client type:
  - [x] Web
  - [ ] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
# Description

Please provide an option in the web-ui-settings to automatically **show all** tracks of an artist, when an artist is clicked (e.g. when searching for an artist -> Click -> show all tracks).  
Option should allow to select between 
- Show tracks of artist 
- Show albums of artist   _(this is currently happening onclick, keep default)_

**Comment by Phyks** [comment]
Kind of related to https://github.com/ampache/ampache/issues/359. Just posting to centralize links to UI issues in a common place.

**Comment by Afterster** [comment]
There is such thing but manually today (named `Show all`).

**Comment by gsantner** [comment]
I know, thats what I am refering to. That option should allow to go directly to that one.

**Comment by gsantner** [comment]
not planned to implement, right?
