### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1260]
Hi, (@Afterster)

I cannot find the policy for the trailing whitespaces in the dev wiki. Is there one?

I see empty lines in Ampache having indentation, and others which do not have.

Thanks

**Comment by Niols** [comment]
Note: In `php-cs-fixer`, this would correspond to the fixers `trailing_spaces` (for non-empty lines) and `whitespacy_lines` (for empty lines).

`trailing_spaces` is already present in the continuous integration, but `whitespacy_lines` isn't.

**Comment by Phyks** [comment]
Also, same thing happens with `method_argument_space` PHP-CS fixer (where to put spaces around commas), which is not uniform across the files.

I guess there are quite a few such fixers that we could enable to homogeneize the code. Should Ampache respect PSR-1/2 guidelines?

**Comment by Afterster** [comment]
Ampache generally follow PSR-1/2 guidelines except a very few exceptions (that I don't remember right now sorry).
I also thing php-cs-fixer should be the code style reference now. `whitespacy_lines` and `method_argument_space` should be added.

**Comment by Phyks** [comment]
@Afterster before closing this issue, do you think there is an issue similar to https://sonar.spring.io/coding_rules#rule_key=squid%3AS2201|s=createdAt|asc=false in codacy/scrutinizer/any other tool we are using?

Could it be possible to enable it, as it would help avoid errors such as https://github.com/ampache/ampache/issues/1203#issuecomment-228155210.
