### ISSUE TITLE
Add Sitemap

### ISSUE THREAD

**Issue by nasariasl** [ampache/ampache#1265]
# Environment
- Ampache version: 
- Web server + version: 
- Server operating system: 
- Client operating system: 
- Client type:
  - [x] Web
  - [x] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
- Client application + version: 
# Settings
# Description

ampache dont have sitemap yet , pls add sitemap to new version
now google and other search engine uses sitemaps to crawl pages but ampache dont have it and i should manually create site map for my music directory.
Pls , Add sitemap feature in new version .
# Logs

**Comment by Phyks** [comment]
Hmmm, not sure about the right way to include a sitemap. I feel like most of the Ampache instances are private and do not need a sitemap (which could even be considered harmful). Plus Ampache uses AJAX loading a lot to browse through the pages.

What would be the topical use case you have in mind?

**Comment by mitchray** [comment]
Closed due to inactivity (and lack of use case)
