### ISSUE TITLE
Profile picture is not force-resized

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1277]
See attached picture.

![2016-06-21-114140](https://cloud.githubusercontent.com/assets/3856586/16225067/2710f9d2-37a5-11e6-94d3-cfec8a9ad00c.png)

We should force the size of the profile picture, either by resizing it in the backend or in CSS.

**Comment by Niols** [comment]
Probably in the backend **and** in the CSS. I don't think we want to store huge images, the sys admin might want to set a size limit.

**Comment by lachlan-00** [comment]
this is okay now.
