### ISSUE TITLE
Group actions in private message page causes JavaScript error

### ISSUE THREAD

**Issue by s-chia** [ampache/ampache#1282]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache HTTP Server 2.4.6, PHP 5.4.16
 * Server operating system: CentOS 7.2
 * Client type:
   - Web

# Description

In the private messages page (/index.php#browse.php?action=pvmsg), selecting messages and clicking on the option links (delete and mark), causes a JavaScript error to occur.

# Logs

ReferenceError: getSelectionArray is not defined
<anonymous>

**Comment by Phyks** [comment]
The above mentionned PR should fix this issue.

**Comment by s-chia** [comment]
That resolved the issue. Thank you
