### ISSUE TITLE
Clicking on play makes the song "continue" even if it is finished

### ISSUE THREAD

**Issue by Gano16** [ampache/ampache#1285]
# Environment and Settings

For any details for this part, see with @Niols or @Phyks.
# Description

When a song is finished and no other song is in the playlist, clicking on play makes the song "continue" (see times and waveform on screenshot) instead of restarting it from the beginning.

![](https://lutim.phyks.me/0aCcPHxK)

EDIT: always after the song is finished, even if moving at a time "in" the song, no music is played.

**Comment by Phyks** [comment]
Indeed, that is a bug.

What should be the expected behavior? Play the last song in the current playlist or restart from the first song in the current playlist? @Afterster @Niols

**Comment by Niols** [comment]
I would personnaly go for whole current playlist.

I've also seen on an other player an "intelligent" play button, that would try to find the next album, or a similar artist, or a new random, … Even if I don't like such a feature, I thought it was worth mentionning.

**Comment by Phyks** [comment]
Intelligent button would likely be handled by https://github.com/ampache/ampache/issues/879 and bliss :)

**Comment by lachlan-00** [comment]
clicking play in a test now doesn't create anything weird for me, this was probably fixed a longgg time ago
