### ISSUE TITLE
Editing a song infos need two clicks

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1286]
# Environment
- Ampache version: latest develop
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - Web
# Settings

# Description

As noticed by @Kolokial in #1271, we need two clicks to edit songs info in the current UI. The first one does not give any feedback to the user but seems to be loading some things in the background.

Further investigation is needed on this.
# Logs

**Comment by lachlan-00** [comment]
It looks like the image needs to be clicked to load something in the entire table then a second single click works on any row.

I'll try this pull from @AshotN as it links up with tools.js where there links are generated.

**Comment by AshotN** [comment]
I don’t remember exactly what was happening. I haven’t touched the code in years. But I’m here to be of help if within my scope

**Comment by lachlan-00** [comment]
I've pulled your patch into my fork and I'll be looking at it this week. So far it fixes the issue of two single clicks so that's a great start. :)

**Comment by lachlan-00** [comment]
fixed in current core branch
