### ISSUE TITLE
Some PHP errors

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1305]
# Environment

 * Ampache version: develop
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

Some PHP errors I came accross lately. Just noting them to remember to handle it.

- [ ] An illegal offset
```
2016-06-16 22:52:46 [ampache] (PHP) -> [Runtime Error] Illegal offset type in file /srv/http/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(827)
```

- [ ] There is a mix of `PHP_EOL` and hardcoded `\n`/`\r` in the code, not sure if we should keep both of them as is or try to homogeneize it.

# Logs

**Comment by Phyks** [comment]
First point is already discussed in referenced issue above.

Concerning second point, I would need some feedback from @ampache/developers :)

**Comment by Afterster** [comment]
`PHP_EOL` is preferable if we want to be closer to the running platform, I believe the change can be done. Just be careful than sometimes we really want the new line to be `\n\r`.

**Comment by Phyks** [comment]
Ok. Closing, as discussion will go on in above mentionned PR, which I should handle.
