### ISSUE TITLE
Rewrite rules for lighttpd webserver

### ISSUE THREAD

**Issue by meskarune** [ampache/ampache#1314]
I just wanted to share these. Maybe they could be added to the docs.

```
$HTTP["host"] == "example.com" {
    server.document-root = "/srv/http/vhosts/example.com/public/"
    url.rewrite-if-not-file += (
        "^/(.*)\.(css|js|jpg|png|gif)$" => "$0",
        "^/rest/(.+)\.view$" => "/rest/index.php?ssaction=$1",
        "^/rest/fake/(.+)$" => "/play/$1",
        "^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$" => "/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg",
        "^/play/([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$" => "/play/$5?$1=$2&$3=$4",
        "^/play/([^/]+)/([^/]+)(/.*)?$" => "/play/$3?$1=$2",
        "^/play(/[^/]+|[^/]+/|/?)$" => "/play/index.php",
        "^/channel/([0-9]+)/(.*)$" => "/channel/index.php?channel=$1&target=$2"
    )
}
```

These rules work for an ampache that is already installed. Getting through the install required using another webserver. Is it possible to install ampache manually instead of having to go through the install script? Or even having a CLI install script would be really nice.

**Comment by Phyks** [comment]
Sure, this should be put in the wiki if wiki is not up to date and these are needed.

If Ampache is said to support lighthttpd, I think that it should fully support it, including for install steps. Sadly, I am not sure any major contributor is using lighthttpd in production and could maintain this =( We should think about it I think.

**Comment by meskarune** [comment]
I wrote the rewrite rules based off the .htaccess files. If you compare them you can see its very easy to do that.

**Comment by Phyks** [comment]
Do we agree these should go [there](https://github.com/ampache/ampache/wiki/Installation#lighttpd) in the doc?

**Comment by meskarune** [comment]
Yes, they should def replace that because it doesn't work. I ended up writing the rewrite rules when someone in my support chan needed help with their webserver and the official ones weren't working for them. After pasting in my rules ampache worked.

**Comment by confusedlinuxgirl** [comment]
Thank you Meskarune for writing on github on my behalf. And for Phyks helping me on irc. Its my lighttpd server that was having issues installing Ampache. Kept having weird url issues. I ended up having to use nginx to install Ampache, then use Lighttpd post installation which to my shock ended up working just fine. I'd be glad to share logs and screenshots if that would be helpful. Hopefully we can get it fixed as maintaining two servers on one machine is kinda annoying when you will only be using the lighttpd.

**Comment by Phyks** [comment]
[Done](https://github.com/ampache/ampache/wiki/Installation#lighttpd)
