### ISSUE TITLE
Can't create Channel?

### ISSUE THREAD

**Issue by threeeye** [ampache/ampache#1316]
# Environment
- Ampache version: 3.8.2
- Server operating system: Ubuntu Server 16.04

- Client type:
  - Web
# Settings

[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/347969/ampache.cfg.php.txt)

# Description

I'm new to Ampache, I created a playlist and I have my music in it,
![playlist](https://cloud.githubusercontent.com/assets/404815/16587137/2a694b78-4297-11e6-8ea9-f1f0fa1054fd.PNG)
I click "Create Channel"
![channel1](https://cloud.githubusercontent.com/assets/404815/16587664/bc4d93d0-4299-11e6-8ca4-60be3cf170dd.PNG)
I click "Create"
On the left side the "Loading" is spinning, and "Stream Source" is empty and nothing is happening...
![channel2](https://cloud.githubusercontent.com/assets/404815/16587768/31edcfd8-429a-11e6-85d6-1cc9899c2f62.PNG)
Am I doing something wrong?
Am I missing something?
Please help, Thanks

**Comment by Phyks** [comment]
Could you check behavior on latest `develop` branch please? The spinning "loading" issue remembers me of something else which should have been fixed.

**Comment by threeeye** [comment]
> Could you check behavior on latest develop branch please? The spinning "loading" issue remembers me of something else which should have been fixed.

How do I do that?

**Comment by Phyks** [comment]
Hmm, first, do backups of Ampache and db if your instance has any importance to you, as it may break things.

Then, just follow the `upgrading` steps in the wiki, either using the git branch `develop` if you git-cloned it, or [this zip file](https://github.com/ampache/ampache/archive/develop.zip).

**Comment by threeeye** [comment]
I followed the upgrade instructions:
Renamed my Ampache folder to .old
copied the new folder
Copied the ampache.cfg.php from old to new

now, when loading the server (<ip>/ampache), it forwards me to the <ip>/ampache/test.php (which is blank...) and I can't access anything...

**Comment by Phyks** [comment]
This really looks like a PHP error. `test.php` is really dead simple and has almost no reasons to be blank.
