### ISSUE TITLE
Installation is not doable in Lighthttpd

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1318]
# Environment

 * Ampache version:  latest develop
 * Web server + version: lighthttpd
 * Server operating system: Linux

 * Client type:

# Settings

# Description

As mentionned [here](https://github.com/ampache/ampache/issues/1314), installation seems to be not working when done under Lighthttpd.

I am not sure about who in the Ampache team is currently using a setup based on Lighthttpd. Then, should we still support it (and find a way to test it as well as everything else) or not? Note this is also a more general question about features of Ampache and its modularity approach.

# Logs

cc @Afterster

**Comment by meskarune** [comment]
If the ampache install requires **RewriteCond %{REQUEST_FILENAME} !-d** that may be the issue. Lighttpd currently only supports **RewriteCond %{REQUEST_FILENAME} !-f** using **url.rewrite-if-not-file**.

https://redmine.lighttpd.net/projects/1/wiki/Docs_ModRewrite#urlrewrite-repeat-if-not-file

For directories a lua mod_magnet script is required. https://redmine.lighttpd.net/projects/1/wiki/Docs_ModMagnet

They look something like this:

```
function file_exists(path)
  local attr = lighty.stat(path)
  if (attr) then
      return true
  else
      return false
  end
end
function removePrefix(str, prefix)
  return str:sub(1,#prefix+1) == prefix.."/" and str:sub(#prefix+2)
end

-- prefix without the trailing slash
local prefix = '/ampache'

if (not file_exists(lighty.env["physical.path"])) then
    -- file still missing. pass it to the fastcgi backend
    request_uri = removePrefix(lighty.env["uri.path"], prefix)
    if request_uri then
      {{ put rules in here}}
    end
end
```

I am not familiar enough with lua to write the lua rewrite rules for ampache though.

**Comment by confusedlinuxgirl** [comment]
Background info for server with the issues...
Arch Linux - Kernel 4.6.3-1-ARCH
Lighttpd version 1.4.39
php version 7.0.8
Mysql/Mariadb 15.1/10.1.14-Mariadb
----- Would not install on Lighttpd----Install server was -----
Nginx version 1.10.1

---kudos and much assistance received from meskarune----

**Comment by Phyks** [comment]
@confusedlinuxgirl What is the behavior under lighthttpd?

Actually, I have been thinking, rewrite rules are not in use during install procedure. Typical URLs are in the form `http://localhost/ampache/install.php?action=init`. Then, I see no reason why it would work in nginx and not in lighthttpd, provided that your vhost is fine.

**Comment by confusedlinuxgirl** [comment]
A typical problem is example.com/install.php?action=check/?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init?action=init/?action=check/?action=init 

Cannot fathom why it is doing this. This is what I meant when I said the url is doing 'screwy' things.

**Comment by Phyks** [comment]
There should not be any redirection code in `install.php` so this behavior is very weird.

Could you try to setup the most dead simple vhost in Lighthttpd (don't worry about anything Apache specific, just setup a as basic as possible PHP vhost) and try to see if the behavior is the same?

**Comment by confusedlinuxgirl** [comment]
Alrighty. Will do. Happen to be setting up a twin server right now to see if I can replicate the bad behavior.

**Comment by wagnered** [comment]
@meskarune, 

I've been working on the video/movie/TV code for awhile now and I've been using lightty for years with Ampache and never had a problem with installation and basic usage, including playlists: A vhost is not needed.

I've never had to create a URL rewrite rule  but it can't be assumed that mod_rewrite.so is automatically loaded:  It's not in the Fedora distribution. 

> For directories a...

Not sure what you mean by this.  List files? Access files in a certain folder? access a folder outside of Document root?  All can be done by setting lighttpd.conf directives.

Ernie D

**Comment by confusedlinuxgirl** [comment]
I hate to be a bother. I really do. I think we need to close this bug report. I installed on a clean server. Twice. I deleted my ampache.cfg.php and changed to commenting out the rewrite rules and reinstalling. Both times installed without a peep in the logs. W/ rewrite rules and w/o rewrite rules. It didn't seam to make a difference. I think (given I am a newb) I had some sort of f--- up in my php.ini file. Please forgive me for wasting everyones time.

**Comment by meskarune** [comment]
>Not sure what you mean by this. List files? Access files in a certain folder? access a folder outside of Document root? All can be done by setting lighttpd.conf directives.

In ampache's .htaccess files it has **RewriteCond %{REQUEST_FILENAME} !-d** and **RewriteCond %{REQUEST_FILENAME} !-f**

Lighttpd's evquivalent for **RewriteCond %{REQUEST_FILENAME} !-f** is **url.rewrite-if-not-file** but it does not have an equivalent for directories.

I wrote rewrite rules for my friend @confusedlinuxgirl based off the .htaccess files ampache ships with.

**Comment by confusedlinuxgirl** [comment]
The only difference I am noting between having the rewrite rules on or off is speed of execution of the various tasks. Its faster w/ the rewrite rules that @meskarune has written for me. I have no tried it w/ or w/o the rewrite rules that had originally been on the wiki.

**Comment by Phyks** [comment]
Closing as invalid and an error in client configuration, not an Ampache issue.
