### ISSUE TITLE
User Uploads?

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#132]
_Issue by **[Psy-Virus](https://github.com/Psy-Virus)** from Tuesday Apr 15, 2014 at 03:54 GMT_
_Originally opened as https://github.com/ampache-doped/ampache-doped/issues/198_

---

Do you plan an upload function?
It would be a nice gimmick. Realizable as module so you can switch it on and off.
Function can be like; I make a folder on the disk and ampache will write for each user a folder where they can upload their music. With a contingent of so and so much GB Memory.

I hope you see the coolness of this epic idea like I do :-D

Best regards
Psy-Virus

**Comment by ShulkMaster** [comment]
I just install Ampache into the server and I'm looking for some help whit the upload funtion into Ampache, it is not letting me to upload anything above 8mb no matter if I put 1G, 200mb 100MB 9MB into the php.ini it won't let me upload anything bigger. i change php vertion as well an noo changes whatsoever.
I'm using windows 8.1 64 bits whit the wamp server php 5.6.31 and 7.0.23 , apache 2.4.27

**Comment by wagnered** [comment]
@ShulkMaster

  The upload is set by the POST size and is limited by the default value `post_max_size = 8M` in php.ini

**Comment by ShulkMaster** [comment]
Oh! I really  appreciate you  help wagnered now i can upload upto 128mb files to the Ampache instance i have in the wamp server. thanks for the info
