### ISSUE TITLE
Impossible to add podcast. 

### ISSUE THREAD

**Issue by ghost** [ampache/ampache#1321]
# Environment
- Ampache version: 3.8.3 Devel Latest github dev branch.
- Web server + version: Lighttpd 1.4.39
- Server operating system: Arch Linux
- Client operating system: Arch Linux

- Client type:
  - Web
# Settings

Latest Ampache version: cb460be05b06fa095bd642b6efe3aa803449ae89

PHP Settings
Setting     Value
Memory Limit    256M
Maximum Execution Time  30
Override Execution Time     Succeeded
Safe Mode   Off
Open Basedir  
Zlib Support    On
GD Support  On
Iconv Support   On
Gettext Support     On
Current Configuration
Preference  Value
prefix  /srv/http/vhosts/ampache.example.com/public
config_version  34
web_path    http://ampache.example.com
database_hostname  
database_port  
database_name  
database_username  
database_password  
secret_key  
session_length  3600
stream_length   7200
remember_length     604800
session_name  
session_cookielife  0
session_cookiesecure    Off
auth_methods    mysql
access_control  On
require_session     On
require_localnet_session    On
getid3_tag_order    id3v2
id3v1
vorbiscomment
quicktime
matroska
ape
asf
avi
mpeg
riff
metadata_order  getID3
filename
metadata_order_video    filename
getID3
deferred_ext_metadata   1
additional_genre_delimiters     [/]{2}|[/|\||,|;]
catalog_file_pattern    mp3|mpc|m4p|m4a|aac|ogg|oga|wav|aif|aiff|rm|wma|asf|flac|opus|spx|ra|ape|shn|wv
catalog_video_pattern   avi|mpg|mpeg|flv|m4v|mp4|webm|mkv|wmv|ogv|mov|divx|m2ts
catalog_playlist_pattern    m3u|m3u8|pls|asx|xspf
catalog_prefix_pattern  The|An|A|Die|Das|Ein|Eine|Les|Le|La
track_user_ip   On
use_auth    On
default_auth_level  guest
ratings     On
userflags   1
directplay  1
sociable    1
licensing   0
statistical_graphs  1
art_order   musicbrainz
db
tags
folder
lastfm
google
show_similar    1
lastfm_api_key  
lastfm_api_secret  
wanted  1
wanted_types    album,official,single,compilation,remix,promotion
channel     1
live_stream     1
podcast     1
refresh_limit   60
show_footer_statistics  1
debug_level     5
log_path    /var/log/ampache
log_filename    %name.%Y%m%d.log
site_charset    UTF-8
openid_required_pape  
allow_public_registration   Off
cookie_disclaimer   0
registration_display_fields     fullname
website
registration_mandatory_fields   fullname
transcode_m4a   On
transcode_flac  On
transcode_mpc   allowed
transcode_ogg   On
transcode_oga   allowed
transcode_wav   allowed
transcode_wma   allowed
transcode_aif   allowed
transcode_aiff  allowed
transcode_ape   allowed
transcode_shn   allowed
transcode_mp3   On
encode_target   mp3
transcode_player_customize  1
transcode_cmd   /usr/bin/ffmpeg
transcode_input     -i %FILE%
encode_args_mp3     -vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1
encode_args_ogg     -vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1
encode_args_m4a     -vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1
encode_args_wav     -vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1
encode_args_flv     -b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1
encode_args_webm    -q %QUALITY% -f webm -c:v libvpx -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1
encode_args_ts  -q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1
encode_get_image    -ss %TIME% -f image2 -vframes 1 pipe:1
encode_srt  -vf "subtitles='%SRTFILE%'"
encode_ss_frame     -ss %TIME%
encode_ss_duration  -t %DURATION%
common_abbr     divx,xvid,dvdrip,hdtv,lol,axxo,repack,xor,pdtv,real,vtv,caph,2hd,proper,fqm,uncut,topaz,tvt,notv,fpn,fov,orenji,0tv,omicron,dsr,ws,sys,crimson,wat,hiqt,internal,brrip,boheme,vost,vostfr,fastsub,addiction,x264,LOL,720p,1080p,YIFY,evolve,fihtv,first,bokutox,bluray,tvboom,info
load_time_begin     1467944800.0435
version     3.8.3-develop
int_config_version  34
raw_web_path    /
http_host   example.com
local_web_path  http://example.com:80
http_port   80
max_upload_size     1048576
cookie_path     /
cookie_domain   80
cookie_life     0
cookie_secure   Off
download    Off
popular_threshold   10
transcode_bitrate   192
site_title  Ampache :: For the love of Music
lock_songs  Off
force_http_play     On
localplay_controller    mpd
play_type   stream
lang    en_US
playlist_type   m3u
theme_name  reborn
offset_limit    50
localplay_level     100
allow_stream_playback   On
allow_democratic_playback   On
allow_localplay_playback    On
stats_threshold     7
rate_limit  8192
playlist_method     default
transcode   always
show_lyrics     Off
mpd_active  0
httpq_active    Off
shoutcast_active    Off
lastfm_challenge  
lastfm_grant_link  
share   0
ajax_load   0
now_playing_per_user    1
album_sort  default
show_played_times   0
song_page_title     1
subsonic_backend    1
plex_backend    1
webplayer_flash     1
webplayer_html5     1
allow_personal_info_now     1
allow_personal_info_recent  1
allow_personal_info_time    1
allow_personal_info_agent   1
ui_fixed    0
autoupdate  1
autoupdate_lastcheck    1467940768
autoupdate_lastversion  cb460be05b06fa095bd642b6efe3aa803449ae89
autoupdate_lastversion_new  
webplayer_confirmclose  0
webplayer_pausetabs     1
stream_beautiful_url    0
share_expire    7
slideshow_time  0
broadcast_by_default    0
concerts_limit_future   0
concerts_limit_past     0
album_group     0
topmenu     0
demo_clear_sessions     0
show_donate     0
upload_catalog  -1
allow_upload  
upload_subdir   1
upload_user_artist  
upload_script  
upload_allow_edit  
daap_backend    1
daap_pass  
upnp_backend    1
allow_video     1
album_release_type  1
direct_play_limit   0
home_moment_albums  1
home_moment_videos  1
home_recently_played    1
home_now_playing    1
custom_logo  
album_release_type_sort     album,ep,live,single
browser_notify  1
browser_notify_timeout  10
geolocation     0
webplayer_aurora    1
upload_allow_remove     1
custom_login_logo  
custom_favicon  
custom_text_footer  
webdav_backend  1
notify_email    0
theme_color     dark
disabled_custom_metadata_fields  
disabled_custom_metadata_fields_input  
podcast_keep    10
podcast_new_download    1
libitem_contextmenu     1
upload_catalog_pattern  
catalog_check_duplicate  
browse_filter   1
sidebar_light   0
custom_blankalbum  
custom_blankmovie  
libitem_browse_alpha  
stream_control_time_max     -1
stream_control_time_days    30
stream_control_hits_max     -1
stream_control_hits_days    30
stream_control_bandwidth_max    -1
stream_control_bandwidth_days   30
theme_path  /themes/reborn
theme_css_base  Array
ajax_url    http://example.com/server/ajax.server.php
ajax_server     http://example.com/server
# Description

Podcast impossible to add. Does not see catalog. No catalogs are seen in the list. See screenshot. 
# Logs

See this screenshot! https://pb.gehidore.net/qIOa

**Comment by Niols** [comment]
The catalog list is empty because you don't have any catalog of type 'podcast'.
Please try to add a podcast catalog from the admin panel (just like any catalog) and select the 'podcast' type.

- [ ] I tried it. With that, I'm able to add podcasts, to see them, to list their content, but not to read the files. So this requires a bit more digging.

- [ ] The Wiki is terribly empty, we'll need to update that

- [ ] Ampache should provide an error message with a few explanation instead of an empty list.

**Comment by confusedlinuxgirl** [comment]
Confirmed cannot play added podcast after creating a podcast catalog and adding a podcast. Can view list of available podcasts as @Niols said.

**Comment by Niols** [comment]
OK, so:

- There's an option (mentionned in the Wiki) to tell Ampache how many episodes to keep and how many episodes to get when there's an update. This option seems not to have an impact on the episodes that are already here when one adds the podcast

- One can get the podcasts with an "Add to catalog". I guess that, when the number of podcasts goes over the specified option, the "Clean catalog" button is the one that will delete what needs to be deleted

- There's a "sync" action available in the podcast's episodes list that triggers the download of an episode (status changes from "skipped" to "completed"). This button looks only available to the admin user

**Comment by confusedlinuxgirl** [comment]
Still having trouble getting it to stop sitting on pending. https://pb.gehidore.net/WAxF logs. https://pb.gehidore.net/FRQk screenshot Reinstalled gettext via composer install gettext/gettext. Continue to be unable to get it to leave pending.

**Comment by confusedlinuxgirl** [comment]
Issue continues in both Lighttpd and Ngnix.

**Comment by AshotN** [comment]
Am also expericing odd issues with Podcasts, going into the error logs I found

`[ampache] (PHP) -> [Runtime Error] Illegal offset type in isset or empty in file /var/www/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(805)`
`[ampache] (PHP) -> [Runtime Error] Illegal offset type in file /var/www/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(827)`

I'm not sure if this error is because of Ampache or https://github.com/rmccue/Requests

Hopefully someone with a bit more knowledge in the area can figure this out.

**Comment by Phyks** [comment]
I already noticed this PHP error in another issue mentioning php errors. It is on the todo list to handle it. 

If anyone feels good to have a look at the code and eventually come up with a PR, that would be cool :)

Le 9 juillet 2016 00:41:06 UTC+02:00, Ashot Nazaryan <notifications@github.com> a écrit :
>Am also expericing odd issues with Podcasts, going into the error logs
>I found
>
>`[ampache] (PHP) -> [Runtime Error] Illegal offset type in isset or
>empty in file
>/var/www/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(805)`
>`[ampache] (PHP) -> [Runtime Error] Illegal offset type in file
>/var/www/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(827)`
>
>I'm not sure if this error is because of Ampache or
>https://github.com/rmccue/Requests
>
>Hopefully someone with a bit more knowledge in the area can figure this
>out.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ampache/ampache/issues/1321#issuecomment-231489685

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by AshotN** [comment]
But is it an Ampache issue?

**Comment by Phyks** [comment]
At least it seems to impact Ampache. Related issue mentionned above is https://github.com/ampache/ampache/issues/1305.

**Comment by confusedlinuxgirl** [comment]
Thank you for working on this. Keep up the good work. I really need to learn to code so I can help more then present bugs.

**Comment by AshotN** [comment]
@confusedlinuxgirl 
If you want to help without coding, I could use some help testing the new JSON API and making sure nothing is behind omitted.

**Comment by confusedlinuxgirl** [comment]
@AshotN will do my best. Pm me on irc.

**Comment by AshotN** [comment]
What' your username is IRC? Same thing?

**Comment by Phyks** [comment]
@AshotN Coming back on this, do you have any way to reproduce the `illegal offset` php error in a reliable way?
