### ISSUE TITLE
Database is getting hammered since upgrade

### ISSUE THREAD

**Issue by madeye-matt** [ampache/ampache#1322]
# Environment
- Ampache version: 3.8.2
- Web server + version: Apache 2.4.10
- Server operating system: Fedora 20
- Client operating system: Windows 10
- Client type:
  - Web: Chrome  51.0.2704.103  Win 10 (also Firefox Fedora)
# Settings

config_version = 12
web_path = ""
database_hostname = "localhost"
database_name = "ampache_test"
database_username = "ampache"
database_password = "XXXXXXXXXXXXXXXXXX"
session_length = "1800"
stream_length = "7200"
remember_length = "7200"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
auth_methods = "mysql"
catalog_file_pattern = "mp3|mpc|m4p|m4a|mp4|aac|ogg|rm|wma|asf|flac|spx|ra|ape|shn|wv"
catalog_video_pattern = "avi|mpg|flv|m4v"
catalog_prefix_pattern = "The|An|A|Die|Das|Ein|Eine|Les|Le|La"
access_control = "true"
require_session = "true"
require_localnet_session = "true"
downsample_remote = "true"
track_user_ip = "true"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
metadata_order = "getID3,filename"
use_auth = "true"
default_auth_level = "admin"
ratings = "true"
sociable = "true"
art_order = "db,tags,folder,musicbrainz,lastfm,google"
amazon_base_urls = "http://webservices.amazon.com"
max_amazon_results_pages = "1"
debug = "false"
debug_level = "5"
site_charset = "UTF-8"
refresh_limit = "60"
max_bit_rate = "200"
min_bit_rate = "48"
transcode_m4a = "1"
use_rss = "1"
# Description

I have just updated my Ampache server from Ampache 3.6-alpha6+FUTURE to Ampache 3.8 and it is pretty much unusable. 

All operations are taking of the order of 10 times as long as with 3.6.  For example, to simply log in takes 15-20 seconds where it was under a second before.  A music search takes a minute or two where it would take around 1-2 seconds before.  All normal operations are similarly affected. 

While the operation is executing I notice that CPU on mysql goes up to 100% for the duration.   Admittedly it's a sizable collection (~20k songs) but I imagine there are much larger collections.

Interestingly, I am running a Verify now - it's taking ages but it always did before. The CPU is running 25% on httpd and mysql 3-5% and it's about the same as my 3.6 install

The server itself is a quad core machine with 8Gb RAM pretty much dedicated to ampache so it should be able to run it without problem.

I am wondering if maybe some database indexes are missing? Is it worth having a peek at the slow query log?

I have the 2 up side by side and can furnish a test login to anyone who wants to take a look.
# Logs

N/A

**Comment by madeye-matt** [comment]
I enabled the slow query log and there was no useful output suggesting either that the bulk of the queries are prepared statements or that there are a huge number of fast queries being executed.  

Enabling the general query log made it clear it was the latter of the 2.  I tried the following test for both 3.6 and 3.8:
* Log into ampache
* Search for "wolf alice"
* Click on album name to show album contents
* Logout

3.6 executed ~1700 queries for that and took about 10 seconds total.  3.8 executed ~5100 queries and took about 120 seconds total.  I am surprised 3.6 is so fast , bearing in mind it's still executing best part of 2000 queries. I've attached the raw database logs to the ticket.   

Looking at this database traffic I have a feeling I am going to have to revert to 3.6 on the grounds that there isn't going to be an easy way to reduce the number of database queries.  

However if anyone does want to see how slow it is, let me know and I'll pass over a test login.

[maya.log.tar.gz] (https://github.com/ampache/ampache/files/354373/maya.log.tar.gz)

**Comment by madeye-matt** [comment]
**W00T! I've identified the problem.**   

```
MariaDB [ampache_test]> select min(date) from object_count;
+------------+
| min(date)  |
+------------+
| 1080980133 |
+------------+
MariaDB [ampache_test]> select count(*) from object_count where object_type = 'song';
+----------+
| count(*) |
+----------+
|    51200 |
+----------+

```

My Ampache setup has a record of every track that I've played in ampache and it's predecessors since Sat 03 Apr 2004 09:15:33 BST.  That's 12 years worth of music comprising 51,200 track plays. 

In the attached database log, you can clearly see that there are no joins onto the object_count table in the 3.6 log but that there are 428 queries that join onto object_count in the 3.8 log. I am guessing this is a new piece of functionality for 3.8 around number of times tracks have been played?

As I have so many records in object_count I am seeing a performance problem. Those with less records won't see the problem.

To this end I deleted all the records from the object_count table in the test database and performance became acceptable (not lightning quick, but acceptable).  However this is not a long term solution for me as I have other tools that mine this data for random playlists (I am really attached to them).

So:
1) Is there any way to disable the feature that is using the object_count table?
2) How easy would it be to optimise the query such that it would only consider, say, records from the last month? (does mysql support materialised views?)

Any help that can be offered with this gratefully accepted

**Comment by madeye-matt** [comment]
Ok, so I am going for the Ampache issues section longest monologue record here ....

Thanks to this pull request I was able to identify the guilty code:
https://github.com/ampache/ampache/pull/983

So I've commented out lines 1024-1029 of user.class.php and hardcoded the $total to 0 and it seems to work but **is there a better way to disable bandwidth calculations?** 

3.8 is still noticeably slower than 3.6 but I won't complain about it unless my users do - I am hoping they will be wowed by the mobile friendliness of the new interface and not mention the slowness (99% of track plays are localplay selected through the website on mobile devices so it should be a big improvement).

**Comment by Niols** [comment]
Hello,

That's interesting, and that clearly requires digging. I think you indeed identified the problem.
However, I'm not sure that the changes made to `lib/class/user.class.php` in #983 are the cause, but maybe more a symptom.

Did you try reverting this PR instead of commenting out? I can't see why the changes in the PR would've had a negative impact in SQL performances… I'll try to setup a 3.8.6 Ampache with a huge (fake "recently played" list) to see when this things have become that bad.

**Comment by Phyks** [comment]
@madeye-matt Nice catch! Not sure this function can be disabled at the moment, but definitely a config entry in `ampache.cfg.php` could be nice.

I do not know advanced MySQL enough, but I am not sure it can do much better than just a WHERE clause to limit the number of fields treated. To be investigated further.

**Comment by madeye-matt** [comment]
@Niols PR #983 is fine, it's not the problem, it just helped me locate the code  (I expect my problem would be 10x worse without it).  As it stands that query isn't too bad. The question I have to ask is: **why is the user bandwidth being calculated 428 times during 3 simple operations?**

@Phyks I might give it a go, though PHP's not really my forte  - how close to real time does the bandwidth calculation need to be? Would it be possible to calculate it once and hour and store it as a field on the user?

**Comment by Niols** [comment]
428 looks like a huge number. I tried the same protocol:
- Log in
- Search for "white pixel"
- Click on the album "The White Pixel Ape"
- Log out

I get 4 calls as admin (but I have "social" features disabled) and 6 as normal user.
Since this is in a "format" function, this might be related to the number of users of your instance (one for each user? more?).

Anyway, such a important calculation should be:
- Done once for all users
- Cached

I will try to find a way to fullfill these two objectives

**Comment by confusedlinuxgirl** [comment]
So I am also experiencing this, not to the extent but still a very large amount of queries. https://pb.gehidore.net/8zJ5 <--- note highlighted section of page. Ignore my choice of podcasts.... x.x

**Comment by mitchray** [comment]
Closing due to time since last discussion, reopen if there is still an issue with the number of queries in more recent versions
