### ISSUE TITLE
API Timeline Function

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#1325]
The Web API Timeline function seems to have a problem in it

`<b>Fatal error</b>:  Call to a member function format() on a non-object in <b>/var/www/ampache/lib/class/xml_data.class.php</b> on line <b>676</b><br />`

If I comment out line 676
`$shout->format();`

It works

**Comment by AshotN** [comment]
https://github.com/ampache/ampache/pull/1268/commits/04e1b57604f8d528a5e15465c47b2600120a94cb

I think this was the intent originally.

**Comment by Phyks** [comment]
Why do you have `$activity->shout` in XML but `$activity->action` in JSON?

**Comment by Niols** [comment]
Yes, there are two `$shout->text` and one becomes `$activity->action` and the other `$activity->shout`. Why is that so?

**Comment by AshotN** [comment]
That my friends, is what we call. A mistake. Thank you

**Comment by AshotN** [comment]
https://github.com/ampache/ampache/pull/1268/commits/61178322fc4daf3a2cbc89d602c3b2cbad3d5971

**Comment by Afterster** [comment]
Indeed that's an issue. As JSON API pr will not be merged right now, do you thing you can send a separate PR just to fix this? Thank you.

**Comment by AshotN** [comment]
I'm really bad at Git, and I'm not 100% sure how to :(

I'm going to be trying to figure it out though.

**Comment by Niols** [comment]
Should be fixed now
