### ISSUE TITLE
httpoxy

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1337]
# Environment

 * Ampache version: any
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - any

# Settings

# Description

Ampache depends on Guzzle (which is affected by httpoxy) and makes external calls to servers. I think Ampache may be sensitive to httpoxy attacks, and we should investigate it further and eventually bump some versions in composer and/or update the recommended vhosts in the wiki.

https://httpoxy.org
Owncloud already mitigated the issue for instance: https://owncloud.org/blog/owncloud-9-0-4-8-2-7-8-1-9-8-0-14-released/

# Logs

**Comment by cobra2** [comment]
Its the leet issue. (I couldn't help it)

**Comment by Afterster** [comment]
I believe you're right here. Main problem will be cross-dependencies here... We may have to wait for dependencies to update themselves first.

That's indeed is perfect issue for the leet issue :).

**Comment by stebe** [comment]
guzzlehttp/guzzle (5.3.1) has a fix and should be pulled in with a composer update.

https://github.com/guzzle/guzzle/commit/70f1fa53b71c4647bf2762c09068a95f77e12fb8

**Comment by Phyks** [comment]
:+1: for the guzzle fix. We should add corresponding options also in the ampache and nginx config in the wiki I think.

What is the leet issue?

**Comment by Phyks** [comment]
So here is a PR to bump Guzzle version and mitigate it. Ampache also relies on Guzzle 3.\* as a side dependency, but this one is not affected, so this should do it.

I edited the `nginx` template [here](https://github.com/ampache/ampache/wiki/Installation#nginx) to add a mitigation also.

I do not know `lighthttpd` to provide any fix.

Apache already published a fix which was integrated in Debian, so I guess we don't have much to do concerning Apache (we do not provide any specific vhost, and it's the user role to be up to date IMO).

**Comment by confusedlinuxgirl** [comment]
@Phyks I will querie the people with lighttpd servers and investigate a httpoxy fix for lighttpd. Partly since I use lighttpd. Will get back to you shortly.
