### ISSUE TITLE
Artists arts are behind auth but not album arts

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1340]
# Environment
- Ampache version: latest develop
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - Web
# Settings

# Description

It seems that to get artists art, you have to be logged in. However, you do not have to be logged in to get album art, which is surprising.

I would have expected the two to have a similar behavior.
# Logs

**Comment by Afterster** [comment]
The behavior should be similar, but it can depends how the image url is formed. Depending from where you get the art, you could have a temporary session id on the url which provide access to it.

**Comment by Phyks** [comment]
Oops, I messed some things up.

URLs look like (returned by the API) with `object_type` to artist or album:

`https://AMPACHE/image.php?object_id=905&object_type=artist&auth=AUTH`

Now, if I remove the `auth` part, I cannot see any image.

Now, I I open another tab and connect to Ampache,
`AMPACHE/image.php?object_id=905&object_type=artist` will still be blank, but `AMPACHE/image.php?object_id=46&object_type=album` will show something. Album view manages somehow to revive the current opened session, and artist view does not. This was the actual issue.

Also, not that if user is not authorized to view the image, a blank `200` page will be shown, whereas it may be better to return some error code or a redirect, no?

**Comment by Afterster** [comment]
Hum the later is one indeed as there is basically no difference in the code between album art and artist art display as far as I know.

I agree about HTTP error code otherwise.

**Comment by Phyks** [comment]
Ok, so I get the problems.

1. My album art has `$etag` set in `image.php`. Then, the response looks like:
```
Cache-Control: private
Etag: 121
Last-Modified: Mon, 25 Jul 2016 20:37:23 GMT
```
and chromium feels like he is entitled to cache it. Then, when the session expires (or I logout) chromium still serve the image from the cache, which explain why the image is still browsable.

2. Some album arts have weird headers sent, resulting in things like:
```
Content-Disposition: inline; filename="Bob Dylan.com"
Content-Type: image/com
```
which looks like non sense.


All this seems to boil down to [these lines](https://github.com/ampache/ampache/blob/develop/image.php#L143-L151). However, I feel like I don't know enough this code base to get the purpose of all of this, and suggest a valid fix.

Still, I think caching a resource behind an authentication can result in security bugs and leaks.

**Comment by AshotN** [comment]
http://AMPACHE/image.php?object_id=21&object_type=album
http://AMPACHE/image.php?object_id=21&object_type=artist

Both gave me blank page

In the log

`Access denied, checked cookie session: and auth:`

**Comment by Phyks** [comment]
See https://github.com/ampache/ampache/issues/1340#issuecomment-235078765, it is due to caching.

There are some cache headers sent with the album art which are not sent with the artist art. Try to login, go to an album art page, and to an artist art page. You see both. Now, logout and go back to the same page. You should still be able to see the arlbum art, but not the artist art, due to caching.

**Comment by lachlan-00** [comment]
image.php doesn't need a session for art now
