### ISSUE TITLE
Preference db table needs to be improved

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#1347]
As I played with enabling and disabling modules and plugins due to the fix for the translation issue in #1301, I saw that the regarding preference table entries are created and dropped instead of simply change a value like:
active -> [0|1].
At least for translations, it would be better, if the plugin - preference - description entries remain there or if they simply get created, if there's a new plugin or if you manually can install them and create the entries that way via the UI.

The reason is, that I don't have to enable and maybe set up all plugins and modules to get the translatable texts. ^^

:-)

**Comment by Phyks** [comment]
Hmm, I am not sure to understand what are the "preference table entries". You mean that entries in the `preference` table in db are inserted and deleted when plugin is enabled/disabled?

I am not sure to get why it would be better to always have them in the db.

**Comment by lachlan-00** [comment]
I've put in T_ for all the preferences/descriptions for each plugin. That way you don't need to enable the plugin to get the translations.

Once these are translated we might do a DB update to enforce the changes for new languages but it's at least available and not hardcoded into english.
