### ISSUE TITLE
Album duplicate issues & better album manager

### ISSUE THREAD

**Issue by baoc75** [ampache/ampache#1350]
# Environment
- Ampache version: Ampache 3.8.3-develop 
- Web server + version: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23
- Server operating system: Windows NT (Windows 7) 
- Client operating system: Windows 7

# Settings
# Description

I am having a album duplicate issues, it has the same name, only the artist is different. And I find out it's because my folder name, so here is Ampache works:
**Singer A** - Album title - 2011 (Alright so Ampache know the artist of this album is "Singer A")
**Songs in album:** 
1. Song number one - **Singer A** (Well, "Singer A" is same like "Singer A", let's put it into album)
2. Song number two - **Singer A,B** (Hmm, "Singer A,B" is different from "Singer A" in the album, so it mean album are different too, let's create another one!)
3. Song number three - **Singer C** ("Singer C" is different from "Singer A" too, let's create more album)
...

So that makes I have a lot of duplicate album which I had to manually click on single song and then change it's album to move the songs. Do we have option to joined albums with same name to a single album? Or any configuration that can fix the problem?
Plus we should have album manager for admin so we can easily move, copy, delete multiple albums.
Thanks!
# Logs

**Comment by Phyks** [comment]
This looks like a kind of duplicate for https://github.com/ampache/ampache/issues/1179, although the issue to be in a reversed way here.

**Comment by kuzi-moto** [comment]
@baoc75 Wast this still an issue for you? I believe that songs within an album are now properly assigned to the same one. Unless perhaps the "Album Artist" field was not set, then I can see how this happens in that case.

**Comment by mitchray** [comment]
Closed due to inactivity, and kuzi-moto is suggesting it is probably resolved now
