### ISSUE TITLE
Ampache Subsonic backend with MusicBee plugin

### ISSUE THREAD

**Issue by PlaidPhantom** [ampache/ampache#1352]
# Environment
- Ampache version: 3.8.3-develop
- Web server + version: Apache 2.4.7
- Server operating system: Ubuntu 14.04.4
- Client operating system: Windows 10

- Client type:
  - SubSonic
# Description

I'm trying to use [MusicBee](http://getmusicbee.com/) and [this plugin](https://github.com/midwan/MB_SubSonic) to connect to Ampache using the Subsonic API.  I set up the API per the [wiki's](https://github.com/ampache/ampache/wiki/API#subsonic-api) instructions, and I'm able to connect to the API using some other apps I've tried, but the MusicBee plugin will not connect.  I worked with the developer in [this issue](https://github.com/midwan/MB_SubSonic/issues/7), and he suggested that Ampache is using an older authentication method and not the current Subsonic standard. Is this something that could be fixed, or is there something I can do to make this work?
# Logs

For what it's worth, I did a cursory scan of my logs and found a few instances of this line in the logs:

2016-07-28 10:54:44 [ampache](subsonic) -> Missing Subsonic base parameters

**Comment by Phyks** [comment]
Indeed, the implementation of Subsonic API in Ampache is based upon version 1.11.0 (AFAIK). See "Authentication" section in `http://www.subsonic.org/pages/api.jsp`.

Passing password in cleartext in URL is mostly ok as long as you use HTTPS. Of course, implementing the updated authentication should be better.

I note this as an enhancement and will try to find sometime to update it. Actually, there is an ongoing discussion about the Ampache-API design https://github.com/ampache/ampache/issues/1292 that is kind of linked to this issue (concerning which future we want for all these APIs, eventually merge some of them).

If you want to give it a try, subsonic API is served from https://github.com/ampache/ampache/tree/develop/rest. 

Subsonic API is implemented in [this file](https://github.com/ampache/ampache/blob/develop/lib/class/subsonic_api.class.php#L298) (link to the ping view example).

For this very issue, the section to edit is [here](https://github.com/ampache/ampache/blob/develop/rest/index.php#L51-L72), putting a switch on the required version.

**Comment by lachlan-00** [comment]
i've started updating the subsonic api in pull #1965 

Right now it's just supporting token auth with user + apikey but that's a start!
