### ISSUE TITLE
DSub Random doesn't play

### ISSUE THREAD

**Issue by stephen-d-hill** [ampache/ampache#1353]
# Environment

 * Ampache version: v3.8.2
 * Web server + version: Apache v2.4.7
 * Server operating system: Ubntu 14.04
 * Client operating system: DSub on Android

 * Client type:
   - SubSonic - DSub
# Settings

Attempt to play Random gives error - "A problem occurred communicating with the server"

**Comment by Phyks** [comment]
How do you "play random" in dsub? What does it mean ?

Do you have any infos on server side? Does it work if you play normally?

**Comment by stephen-d-hill** [comment]
In Album Lists choose Random; you get a random selection of albums. Then
hit the triangle play button to see the error.
Playing albums works fine.

**Comment by Phyks** [comment]
I'm sorry, I cannot reproduce and will need either extra info or you to check the server logs. Could you try also to reproduce the issue with an updated Ampache on the `develop` branch?

With my install on latest `develop`, I have no problem playing songs with DSub either normally or randomly.

**Comment by stephen-d-hill** [comment]
Found the issue....I had mod_evasive enabled on my apache server. Disabling it fixed it.

**Comment by Phyks** [comment]
Ok, good! Thanks for the input on the resolution. I guess dsub is making a large number of requests, in parallel, for all the albums in the random selection.
