### ISSUE TITLE
Unable to add local catalog using the latest develop branch

### ISSUE THREAD

**Issue by stevejbauer** [ampache/ampache#1356]
# Environment

 * Ampache version:  Latest develop branch
 * Web server + version: apache 2.4.23
 * Server operating system: gentoo
 * Client operating system: Windows 10

 * Client type:
   - Web

After the commit: 088fa00b368f1ee00647fa32fd0a56ad66c1ca06, the input box for the path of a local catalog was changed from a textbox to url.  This prevents a person from adding a normal path as described in the on screen prompts for the local catalog.

**Comment by Phyks** [comment]
Why does it prevent ? There should be no enforcement of a valid URL scheme.

**Comment by stevejbauer** [comment]
Whenever I try to add a catalog in using the normal path syntax, it pops up a little message stating it should be in url form.  When I changed the type to textbox, it then allowed the normal directory syntax work.

**Comment by Phyks** [comment]
Sorry, my bad… I set it to "url" to have a "path" keyboard which is more confortable on smartphones. I was not aware browsers used to validate it against a regex URL, which is terrible in this case.

I kept the URL type for URL fields. I used text type for paths and kept URL type for URL/URI. Let me know if you think it is ok.

Note: This issue will close automatically when PR is merged.

**Comment by stevejbauer** [comment]
As long as the browser is trying to force the path to be a url that should
be fine for setup then.
