### ISSUE TITLE
Missing album art randomly when it's in folder/id3

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1359]
# Environment

 * Ampache version: latest 3.8.3-develop
 * Web server + version: nginx/1.8.1
 * Server operating system: CentOS release 6.8 (Final)
 * Client operating system: Windows 10

 * Client type:
   - Web

# Settings

relevant maybe?
art_order = "db,tags,folder,musicbrainz,lastfm,google"
album_art_store_disk = "false"
album_art_preferred_filename = "cover.jpg"

# Description

After creating a catalog or doing updates there are quite a handful of albums that are missing cover art. However, when you go to the albums page and select cover art, the cover is available either from the folder or from ID3 tag. And when it's from the folder, I've checked to see that the filename is cover.jpg. I can then select the album art and it works fine, but I'm wondering why it wouldn't pick it up in the first place? It's a bit tedious to go through 30-some pages of albums finding all the ones with missing art.

# Logs

Will provide logs as needed.

**Comment by Phyks** [comment]
So some albums miss cover art, although they should be available from tags or folder and then get imported, and you have to manually select the album art.

Could you provide `debug` level logs of a (small) catalog creation (just the minimal number of albums to reproduce it), so that we could see how it goes?

Thanks

**Comment by kuzi-moto** [comment]
I tried to create a catalog containing 1 album, and afterwards it appeared to have the correct album art, when previously it was missing. I'm going to try to setup Ampache from scratch, and create a catalog with a small section of my music to see if I can reproduce.

**Comment by Phyks** [comment]
Ok. Let me know whenever you have some minimal number of steps to reproduce it, this would ease debugging a lot!

**Comment by kuzi-moto** [comment]
Okay, well I tried it again. So I created a brand new ampache install with basic settings. I created a small catalog of about 17 albums, all of which had their album art. I then added another hundred or so and started a catalog add but had to leave so I closed out of the browser (don't know if this has any effect or not). When I re-opened the albums were all there but missing album art. Running "Gather all art" seemed to work with collecting all the art.

Not sure what happened before but it seems to be working now. I'll wipe out my old ampache install/database and try again with the whole thing.

**Comment by kuzi-moto** [comment]
Alright, I re-created one of my previous catalogs with a fresh Ampache install, and it's happened again. Interestingly, none of my albums had cover art even though I had gather art selected. After clicking the option to gather manually, there are still some missing covers that were missing them previously! Looking quickly through the logs, it appears that for some reason they were just skipped as I can see where they were imported into the catalog, but there is no entry for getting art. I can't find an error or anything.

I could post the log file somewhere but it's about 4 MB.

**Comment by Phyks** [comment]
There should be a lot of art debug messages in the log. See [this file](https://github.com/ampache/ampache/blob/develop/lib/class/art.class.php) and the `debug_event` lines.

Maybe the log could be useful. I think you may be able to attach it to this github issue (anonymize first).

**Comment by kuzi-moto** [comment]
Hmm, well I'm not sure I saw any errors in the log but I figured it out. Apparently there was a weird issue with permissions. I set all my music to 775 and did another update and all the albums missing art were fixed. Sorry for the false alarm!

**Comment by Phyks** [comment]
No problem, thanks for the update on this issue :) Let me know if you experience any other issues.
