### ISSUE TITLE
Problem connect with any client

### ISSUE THREAD

**Issue by juarezpedra** [ampache/ampache#1360]
Hi,

I followed the instruction described here https://github.com/ampache/ampache/wiki/API and here https://www.howtoforge.com/how-to-set-up-the-ampache-streaming-music-server-in-ubuntu-12.04-lts, even so ampache refuses to accept connection from client in my ipod and android. I have attached the log file and configuration file.

Thanks!
# Environment
- Ampache version: 3.8.2
- Web server + version: Apache 2.4.18
- Server operating system: Lubuntu 16.04
- Client operating system: iOS 4.2.1
- Client type:
  - Ampache: iAmpache
# Settings

# Description

I want to hear the music stored in my server in my ipod or android phone.
# Logs

**Comment by Phyks** [comment]
Removed the logs as they were not anonymized and I was not sure you were aware of it (typically, database password was in).

Config file does not give much information. Log file shows successful logins to the API:
```
2016-08-05 20:58:51 [-1] (API) -> Login Attempt, IP:YOUR_IP Time: 1470441550 User:YOUR_USER Auth:SOME_TOKEN
```

What error exactly do you have in the clients? Could you describe it more precisely?

**Comment by juarezpedra** [comment]
Hi,
Here is the image of the error:
![img_0003](https://cloud.githubusercontent.com/assets/20867814/18857643/160fcd0a-843c-11e6-8d8a-8c6864607230.PNG)

**Comment by Phyks** [comment]
Hmmm ok, are you sure you put the right URL? Can you browse the specified URL with Safari on your iPod?

I don't know much about iAmpache and never had a chance to try it as I don't have iOS device. Could you check with another client?

**Comment by Afterster** [comment]
Unfortunately this doesn't seems to be related to Ampache server. Probably an issue on client side (misconfiguration?). I would suggest to post your issue to iAmpache developers.

**Comment by manuelglez86** [comment]
Well im not shure whats your configuration but seeing your address "lorca.local", it think that android and ipod didnt find that addres and the reason of that is maybe is not and addres register on you network dns i assume that "lorca.local" is a vhost that you only register on your lubuntu machine.

So the phones try to look for that addres but that addres doesn really exist on your network just on you lubuntu machine.

So i think you need to find ampache using your ip addres acording to you configurarion.

Something like 192.168.1.77/ampache

**Comment by AshotN** [comment]
This issue is really old. If OP or anyone is having a similar problem please create a new issue.
