### ISSUE TITLE
Prevent misleading "not found" log messages about theme.cfg.php

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1361]
# Environment
- Ampache version: latest develop
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - Web
  - Ampache
  - SubSonic
  - Plex
  - DAAP
  - UPnP
  - WebDAV
# Settings

# Description

In the loop in [this function](https://github.com/ampache/ampache/blob/develop/lib/themes.php#L29), we do not filter out `..` and `.`, leading to error messages such as:

```
2016-06-17 09:20:15 [phyks] (theme) -> /srv/http/ampache/themes/../theme.cfg.php not found.
```

in the logs.

They are totally harmless but can be confusing.
# Logs

**Comment by lachlan-00** [comment]
This was fixed a while ago when i merged the core branch.
