### ISSUE TITLE
Not very useful error message in play/index.php

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1362]
# Environment
- Ampache version: latest develop
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - API
# Settings

# Description

[This line](https://github.com/ampache/ampache/blob/develop/play/index.php#L204) is not very useful for debug. In particular:
- `AmpConfig::get('demo_mode')` is `NULL`, giving lines such as

```
2016-08-06 21:29:46 [test] (UI::access_denied) -> Streaming Access Denied:is the value of demo_mode. Current user level is 5 
```

in the log.
- Same thing when access level is not enough. Typically, when a user is a "guest" they cannot stream music through the API. This results in an error such as

```
2016-08-06 21:29:46 [test] (UI::access_denied) -> Streaming Access Denied:is the value of demo_mode. Current user level is 5 
```

Expected user level is not given in the error message. And for a beginner I think it might be misleading and difficult to find the correct setting.
# Logs

**Comment by lachlan-00** [comment]
Pointed to the actual reason in all stream denied errors in 52f67dbec
