### ISSUE TITLE
"Add to existing playlist" is misleading

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1364]
# Environment
- Ampache version: latest develop
- Web server + version:
- Server operating system:
- Client operating system:

- Client type:
  - Web
# Settings

# Description

The playlist icon with a plus sign, to add current item (or temporary playlist) to a playlist has a title which states "Add to existing playlist". This is misleading as there is a sub-button to "create a new playlist". This is valid in English and French translations at least.

I think it should state "Add to playlist" (without mention of playlist existence)?
# Logs

cc @Psy-Virus who may have an opinion on this :)

EDIT: Oops, sorry, wrong hl the first time :/

**Comment by roba91** [comment]
Another problem is this button in the webplayer section. It adds the whole current playlist to a playlist. But as it's placed next to the song control buttons one can also think the button would only add the current playing song.

![musix](https://cloud.githubusercontent.com/assets/4061254/18138108/7ba021ec-6fab-11e6-9cfb-ef4241fff9a9.png)

**Comment by lachlan-00** [comment]
Changed T_('Add to existing playlist') to T_('Add to playlist') in #1957

**Comment by robsdedude** [comment]
This doesn't solve the problem of the un-intuitive action this button takes. I'd expect it to only add the current song. However, I can imagine that there are people that actually expect it to add the whole temporary playlist. There should a) be an option for both actions b) be a intuitive and clear way to do either.

**Comment by lachlan-00** [comment]
I'll change the playlist one to either the current track or rename/replace the icon with a different stylr

**Comment by lachlan-00** [comment]
I think this will fix it. currently in stringsupdate (#1957)

![image](https://user-images.githubusercontent.com/1305249/65735775-f9a1ae00-e11b-11e9-895a-ffe8b7385565.png)

**Comment by robsdedude** [comment]
Yes. I think the added "All" makes clear, what the button does.

**Comment by lachlan-00** [comment]
Great! Hopefully psy will be ready to merge the pull soon

**Comment by mitchray** [comment]
Appears to have been implemented, closing
