### ISSUE TITLE
database update issue 

### ISSUE THREAD

**Issue by jeski** [ampache/ampache#1368]
# Environment
 * Ampache version:  3.8.3 develop
 * Web server + version: apache 2.4.18 mysql 5.7.13
 * Server operating system: ubuntu 16.04
 * Client operating system: ubuntu, windows 10

 * Client type:
   - Web
[ampache.cfg.php.gz](https://github.com/ampache/ampache/files/417050/ampache.cfg.php.gz)

   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

Clean install, goes very well until the database updates are run,  when the install simply reloads the update page.  Debug set to 6 and that info is listed in the uploaded ampache.20160814.log.gz
[ampache.20160814.log.gz](https://github.com/ampache/ampache/files/417053/ampache.20160814.log.gz)

# Logs
nothing listed in the apache error.log and only 200 response codes in the apache access.log

**Comment by jeski** [comment]
FWIW, I pulled from head, re-installed and everything worked well.  The only difference to the develop branch was That I installed php7.0-dev before running the installer. Personally, I doubt that changed anything.  Close this out if like, or let me know if you'd like to pursue it further.

**Comment by Phyks** [comment]
I don't really get what the error was in the first place. Could you describe it further?

Thanks

**Comment by jeski** [comment]
I can't speak to what the exact problem was, I can only mention what I saw.  That was at fresh install everything worked well until it came to the database update page. I couldn't get beyond it, was is if  nothing was happening.  However in the log file this error repeats: 

Database connection.
Error: ["42S22",1054,"Unknown column 'kind' in 'where clause'"]
Database disconnection.

**Comment by Phyks** [comment]
Looks like for some reason [this line](https://github.com/ampache/ampache/blob/f76e7e6228d9b0c44891b8875d4121b3ff40d803/lib/class/update.class.php#L2974) was not executed.

Closing for now as it is both isolated, solved, and not replicable on my instance. Anyone, feel free to reopen if you experience it.
