### ISSUE TITLE
Access Levels (Sharing)

### ISSUE THREAD

**Issue by evil666** [ampache/ampache#1369]
It seems that Access Level for "Sharing" isn't working properly. If you set the access level to Admin and then apply... It does not show up for accounts with Admin Access. The only way it works is if you click the check box to apply to all, however that lets every one now have the opportunity to share. I think this also affects other options as well. Let me know if I am wrong or I am not understanding the concept.

Environment

 * Ampache version: 3.82
 * Web server + version: Apache
 * Server operating system: Ubuntu 14.04
 * Client operating system: All

 * Client type:
   - Web

Description

Enable sharing, click apply. Notice it does not take affect. Then click on apply to all box, notice it works but now for everyone. Individual Access Level only not working.

**Comment by Afterster** [comment]
This is not the purpose of access level. Access level defines which minimum level is required to change the setting, not the targeted population.
