### ISSUE TITLE
Web Player Design Suggestion

### ISSUE THREAD

**Issue by greengeek1** [ampache/ampache#137]
The current web player is wonderful!  So much better than how the old one worked in the popup!

One idea that I really like on some web players is the ability to expand and minimize the player along with expand and minimize the playlist.  I purchased this player for another project, and I really like how it is laid out far as the expanding and collapsing of the playlist and controls.   http://cc.radykal.de/fullwidthaudioplayer/  (located at the bottom of the page) This one is done with soundmanager2 and javascript.

Another example I really like is http://www.streampad.com/ (also located at the bottom of the page)

Could this type of functionality be added to the current ampache doped player?

**Comment by Afterster** [comment]
Done!
Be aware that if you're using flash to decode audio, music will pause when minimizing web player... music keep playing minimized with HTML5 or Aurora.js.
