### ISSUE TITLE
blank xml responce for subsonic api when testing in firefox

### ISSUE THREAD

**Issue by mrpurplenz** [ampache/ampache#1371]
* Client type:
   - SubSonic

# Description

In the wiki https://github.com/ampache/ampache/wiki/API#subsonic-api there is a suggestion to test your wrking system by going to .../rest/ping.view 

In firefox the result is blank. Try Chrome which will actually return the xml as shown in the wiki

I dont think it needs fixing in the code but a note in the wiki like "try different browsers if a blank page is returned" would have saved me an hour

Cheers

**Comment by Phyks** [comment]
Hmmm, here is the result under Firefox:
![2016-08-26-135408](https://cloud.githubusercontent.com/assets/3856586/18004498/9b023a68-6b94-11e6-9c6e-c89f866b7446.png)

Are you sure it is not coming from an extension or something like this?

**Comment by mrpurplenz** [comment]
OK maybe just me and my version firefox 48.0 I've got shockwave, and Java plugins installed so perhaps they're taking control and hiding the "invalid" xml or perhaps theres a setting switch i flipped some time ago which hides invalid xml and I forgot.

I guess just getting a blank page and not getting a 404 should have been enough for me to realise that something is being sent and to investigate further.

For me the correct xml was visible when I view source.

So no problem with ampache and an isolated case of a difficulty when installing.

**Comment by Phyks** [comment]
Maybe your webserver does not send the correct content-type for XML files?

**Comment by mrpurplenz** [comment]
Here are screen shots of the xml in chrome and the page source for the firefox blank page
![subsonic_xml_chrome](https://cloud.githubusercontent.com/assets/2926203/18038725/be4dbec2-6def-11e6-8f8d-e6da623afe27.png)
![subsonic_xml_firefox_source](https://cloud.githubusercontent.com/assets/2926203/18038726/be4f11d2-6def-11e6-8af1-8c8cb3dadc06.png)

**Comment by Phyks** [comment]
So the source view is indeed correct. Firefox is just not treating it as XML for whatever reason. Could you send me the link to your instance in a private message so that I could test it myself?

**Comment by mrpurplenz** [comment]
pm sent. Interestingly I have other instances of firefox on other machines which work as expected.

**Comment by Phyks** [comment]
Weird, it works fine on my computer.

**Comment by mrpurplenz** [comment]
Yeh, so I dont think there's is/was anything wrong on the ampache server side. I just wish I had thought to switch browsers or "view source" when a blank page appeared in my "faulty" browser.  The fact that the server did not report a 404 should have been my clue that the server was at least doing "somthing" I just didnt put 2 and 2 together in the face of a blank page.

**Comment by Phyks** [comment]
Ok, then closing the issue. I think anyone can edit the wiki, feel free to edit the wiki if you think it deserves more infos. Don't hesitate to post a link to new revision here if you want a review :)
