### ISSUE TITLE
User uploads: keep artist and album tags

### ISSUE THREAD

**Issue by robinwils** [ampache/ampache#1377]
# Environment
- Ampache version: develop
- Web server + version: apache 2.4.7
- Server operating system: 14.04.1-Ubuntu
- Client operating system: 14.04.1-Ubuntu
# Settings

Basic settings, just allowed transcoding with libav and user uploads
# Description

When a user uploads files, he needs to choose an album and an artist, and if you don't choose any it will erase those mp3 tags apparently(by default). Is there an option or something to just keep the regular tags if those fields are blank ? Currently, you cannot upload multiple albums/artists at the same time.

**Comment by robinwils** [comment]
I don't know if it erases the actual tags in the saved file, but the songs don't show up with an artist or an album in the song list. 
It would be nice if ampache tried to find an artist and album for every song uploaded, create them if they don't exist (from the tags). From what I've read in the source code it does not do that at the moment, if I am not mistaken.

**Comment by lachlan-00** [comment]
Artist and album are read if you don't set them in the upload page
"Leave the artist and album fields blank to read file tags"
