### ISSUE TITLE
Uncaught Error: Class 'Gettext\Translator' not found

### ISSUE THREAD

**Issue by erwin16** [ampache/ampache#1380]
# Environment

 * Ampache version:  git HEAD
 * Web server + version:  nginx/1.10.0 (Ubuntu)
 * Server operating system:  Ubuntu 16.04 Xenial
 * Client operating system:  OSX  10.11.6

 * Client type:
   - Web     Browser Chrome Version 52.0.2743.116 (64-bit)

# Settings

Not yet installed...  error at the beginning of installation

# Description
Ubuntu / Nginx / MySQL / PHP7 installation
Nginx conf setup ( ampache as virtual host , root :  /var/www/erwin16.live/ampache
cloned ampache from git into /var/www/erwin16.live/ampache
request in web browser :  http://ampache.erwin16.live
resulting in HTTP Error 500
The ampache.erwin16.live page isn’t working
ampache.erwin16.live is currently unable to handle this request.
redirected to http://ampache.erwin16.live//test.php    ( ** note the // in the URL )

# Logs
nginx/error.lig

2016/09/08 15:54:08 [error] 24605#24605: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Gettext\Translator' not found in /var/www/erwin16.live/ampache/lib/i18n.php:36
Stack trace:
#0 /var/www/erwin16.live/ampache/test.php(66): load_gettext()
#1 {main}
  thrown in /var/www/erwin16.live/ampache/lib/i18n.php on line 36" while reading response header from upstream, client: 86.206.154.86, server: ampache.erwin16.live, request: "GET //test.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "ampache.erwin16.live"

**Comment by wagnered** [comment]
Me thinks you haven't installed/updated with Composer as indicated at
https://github.com/ampache/ampache/wiki/Installation. You should be able
to install it from your distribution or from the link on the above
listed page. It must be run from the same folder that composer.json is
located.


73 From AA1AD

Ernie D
Federal Way, WA | CN87ug

**Comment by erwin16** [comment]
OK.. got it !

**Comment by n0mad-samurai** [comment]
Thank you! I installed composer but missed the rest of the procedure. :-(
Works as it should now.
