### ISSUE TITLE
how to add shoutcast stream in catalog

### ISSUE THREAD

**Issue by karthikindia** [ampache/ampache#1381]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: apache2
 * Server operating system: cloud linux
 * Client operating system: ubuntu

 * Client type:
   - Web
   

Need to know how to add shoutcast stream as a catalog
does ampache supports that

**Comment by Phyks** [comment]
Not sure this is feasible, but I do not know enough of this part of Ampache basecode.

@Afterster do you know more about this?

**Comment by Afterster** [comment]
Shoutcast stream can be added as a radio station (you need to enable radio feature). This will allow you to play the stream but shoutcast metadata (current song title...) will not be displayed.
