### ISSUE TITLE
How work visualizer

### ISSUE THREAD

**Issue by dlazzy** [ampache/ampache#1390]
# Environment

 * Ampache version: Latest (at 29 September 2016)
 * Web server + version: Nginx, latest
 * Server operating system: Ubuntu 16.04
# Description

How to activate the visualizer like this : (visualize button show black screen behind player and list)
![screen](https://cloud.githubusercontent.com/assets/1348073/18971171/5c32f460-8694-11e6-9b1c-f2b06dbc2794.jpg)

Thanks you very much for your help.

**Comment by Phyks** [comment]
Where do you take this screenshot from?

**Comment by dlazzy** [comment]
Hello,

I've take this screenshot from [ampache.org](url) website, scroll down you will see it.

**Comment by Phyks** [comment]
I only know about the "visualization" button and have never seen anything similar to your screenshot. Maybe it is a screenshot from an old version.

Maybe @Niols or @Afterster will be more helpful on this.

**Comment by dlazzy** [comment]
I don't know but actually it doesn't work.

**Comment by Afterster** [comment]
This is working but only available if you're using HTML5 streaming (not Flash neither JavaScript). If so, you should see a "Visualizer" icon button near the player to enable the feature like in the screenshot.

**Comment by dlazzy** [comment]
It works thanks !
