### ISSUE TITLE
No song title/artist provided with streaming

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1391]
- Ampache version:
  Installed Ampache version: 98094ad2bd9152f68bfbc88a4f6887959cba6ad2.
- Web server + version:
  Apache Mysql
- Server operating system:
  Debian testing
- Client operating system:
  Vlc

Hi

When I stream from web to  my player I get no artist/title in my player (mainly Vlc). I tried it on Android and Linux. All i get is the long full url of the streamed song.

I tried using beuatiful urls but when I enable it streaming breaks, I cant download or stream songs anymore so I cant use it on my system, if that is the option that I am supposed to use.

**Comment by Phyks** [comment]
@Niols is using a similar setup I think.

**Comment by lachlan-00** [comment]
I am using this setup for my channel streaming and get artist/title from VLC. It takes a few seconds but changes consistently.

I assume you've forced transcoding too? I'm force transcoding everything.
I'm streaming using an mp3 stream, are you using ogg or something else?

 (I can't see anything in my config, user options or log that would dictate stream title though if anyone knows of one?)
