### ISSUE TITLE
Catalog Update with catalog_update.inc -a not importing cover

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1394]
I'm running the latest dev version from git.

Is it correct that when I'm adding a new album with `catalog_update.inc -a` it will not show the cover in Ampache until I run a complete import?
My files are tagged with the cover and the cover also resides in the album directory as folder.jpg.
![image](https://cloud.githubusercontent.com/assets/4103090/19073423/47a448b4-8a3b-11e6-8ef2-b6a9954b2556.png)

**Comment by Psy-Virus** [comment]
Hey @Rouzax,

this is not fully correct. You can add your media with the following command, to also add covers:
`php catalog_update.inc -a -g`

if you run the script without switches, everything except the `-m` switch is executed.

For more information, simply run `php catalog_update.inc --help`.

:-)

**Comment by Rouzax** [comment]
Yeah but the weird thing is it looks like the `-g` option will re-evaluate all albums instead of only doing the new files.

**Comment by Psy-Virus** [comment]
That's right. If a cover exists, it will be skipped. Otherwise it will be extracted from TAG or downloaded from the sources, you have configured.

All functions do it. The `-a` option also looks, what files are there and then process all others.

**Comment by Rouzax** [comment]
Would it not make sense that `-a` would also import the art from the new files?
With `-g` that adds a lot of time to import.

**Comment by pabx06** [comment]
Runing into the issue art from id3v2 not imported. then all covers of al albums were the same.
My first catalogue file import . after fresh install.
![image](https://cloud.githubusercontent.com/assets/4013370/22187128/4e37c7ec-e101-11e6-8223-c54773c63b06.png)

**Comment by lachlan-00** [comment]
lots of changes to art over the years, this should be okay
