### ISSUE TITLE
Change the number of albums on light sidebar page

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1398]
Is there a way to change the default number of 6 albums on the overview page somewhere, when using light sidebar?
![image](https://cloud.githubusercontent.com/assets/4103090/19181587/6e211a32-8c6e-11e6-943e-9344f07047dd.png)

**Comment by Phyks** [comment]
Not sure about this. cc @Niols @Afterster

**Comment by lachlan-00** [comment]
There is now. This has been in develop for a bit but setting your popular threshold will limit the mashup
![image](https://user-images.githubusercontent.com/1305249/65655639-3c9e4b80-e060-11e9-8f80-618185d0e085.png)

![image](https://user-images.githubusercontent.com/1305249/65655650-458f1d00-e060-11e9-81d0-0b5adc3b8c01.png)
