### ISSUE TITLE
Character set problem

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#140]
Hi,
First of all just wow, the new interface looks really nice and works really good.

Issue
I have a Windows 2008 R2 server with IIS 7.5 and PHP 5.4.9 with a MySQL 5.5 backend.
Ampache is the latest develop build.
![image](https://cloud.githubusercontent.com/assets/4103090/2764707/5f922a5c-ca19-11e3-80dd-4de7c6ee0c11.png)

In my ampache.cfg.php I have the following settings:
; Charset of generated HTML pages
; Default of UTF-8 should work for most people
; DEFAULT: UTF-8
site_charset = Windows-1252

; Locale Charset 
; Local charset (mainly for file operations) if different
; from site_charset.
; This is disabled by default, enable only if needed
; (for Windows please set lc_charset to ISO8859-1)
; DEFAULT: ISO8859-1
;lc_charset = "ISO8859-1"

this works well with most files. It understands ë and é etc.
One of my albums is from Justice and the name of the album is ✝ see http://musicbrainz.org/release-group/867d4882-4e8e-3acd-8134-66f19bcca915
In my debug log this is not recognised:
2014-04-22 14:07:58 [ampache](read) -> Starting work on Justice inside D:\FTProot\MP3 
2014-04-22 14:07:58 [ampache](Memory) -> 6 MB 
2014-04-22 14:07:58 [ampache](Memory) -> 6 MB 
2014-04-22 14:07:58 [ampache](Memory) -> 6 MB 
2014-04-22 14:07:58 [ampache](read) -> Starting work on 2007-06-06 - ? inside D:\FTProot\MP3\Justice 
2014-04-22 14:07:58 [ampache](Memory) -> 6 MB 
2014-04-22 14:07:58 [ampache](read) -> D:\FTProot\MP3\Justice\2007-06-06 - ? ignored, non-audio file or 0 bytes 

Windows screenshot:
![image](https://cloud.githubusercontent.com/assets/4103090/2764620/f05ef24c-ca17-11e3-8986-61b0b2206f41.png)

**Comment by iglosiggio** [comment]
Well, this bug is still present on windows (because all the php IO functions use legacy windows calls that support only Windows-* charsets and the filenames of NTFS is internally UTF-16 encoded.).

[This](https://github.com/kenjiuno/php-wfio) extension fixes it by creating a pseudo-protocol `wfio://` wich accepts utf-8 encoded names.

**Comment by Rouzax** [comment]
As a workaround I've enabled "Replace non-ASCII characters" in Musicbrainz Picard, that way the file names will not have special characters while the tags still do.
![image](https://cloud.githubusercontent.com/assets/4103090/19181026/851c516a-8c6a-11e6-950a-96e49062f885.png)
