### ISSUE TITLE
External images seem to be written multiple times

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1401]
# Environment
- Ampache version: Latest git 
- Web server + version: IIS 8.5
- Server operating system: Windows 2012R2
# Settings

```
; Album Art Store on Disk
; This defines if arts should be stored on disk instead of database.
; DEFAULT: false
album_art_store_disk = "true"

; Local Metadata Directory
; This define a local metadata directory with write access where to store
; heavy data if enabled (album arts, ...)
; DEFAULT: none
local_metadata_dir = "C:/inetpub/wwwroot/Ampache/_metadata"
```
# Description

When using external images it seems that Ampache writes and deletes the images several times before doing the next one.
![image](https://cloud.githubusercontent.com/assets/4103090/19270164/e41e5ba2-8fbe-11e6-9dcb-4156dda5cd52.png)

I see in my explorer view in Windows the folder with the images flicker while it is busy with it, so it creates the folder with image than deletes it again and so on. 
The end result is okay.

**Comment by Rouzax** [comment]
It might only appear on a new catalog import, as far as I can see now.

**Comment by lachlan-00** [comment]
I think i may have fixed this a while ago by ignoring existing art images.

The art process used to write for each file regardless of the art existing already. Now the process will check the art exists and ignore duplicate requests to write it.

**Comment by mitchray** [comment]
Closing, reopen if still present in more recent versions
