### ISSUE TITLE
Subsonic API version bump needed

### ISSUE THREAD

**Issue by SenorSmartyPants** [ampache/ampache#1405]
# Environment
- Ampache version: 3.8.3-develop
- Web server + version: lighttpd
- Server operating system: debian
- Client operating system: DSub

- Client type:
  - SubSonic
# Settings

# Description

DSub will not display podcast channel images unless version is at least 1.13.0 . I increased it in /lib/class/subsonic_xml_data.class.php  and then DSub displayed the images correctly.

I do not know if all other features of 1.13.0 API have been implemented in ampache.
# Logs

**Comment by Phyks** [comment]
See [this issue](https://github.com/ampache/ampache/issues/1389) concerning why a version bump is not this easy to achieve. Flagging as enhancement, and still, this issue might help some people.

**Comment by nish81** [comment]
I have a similar issue with the subsonic plugin for MusicBee - it won't authenticate at all, returning an error that the REST API is too old. I changed the constant in /lib/class/subsoni_xml_data.class.php just like you did, and it then authenticated and I can browse my songs, but I only successfully played two songs (out of a test library of 24). Trying to play other songs returns an error. So I suspect there are other missing features from 1.13.0.

I've opened an issue at the MusicBee plugin's site to see if there's any way to make it backwards compatible. In the meantime I just thought I'd add some information about another plugin that seems to require the higher version.

PS this may help the original issue, I have an old version of dSub on my android phone and it connects and plays fine. So if you can downgrade somehow that could solve the matter for you.

**Comment by lachlan-00** [comment]
i've started updating the subsonic api in pull #1965 

Right now it's just supporting token auth with user + apikey but that's a start!
