### ISSUE TITLE
Artist slideshow resolution and results

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1410]
# Environment
- Ampache version: 98094ad
- Web server + version: IIS 8.5 + PHP 7.0.11
- Server operating system:Server 2012 R2

# Description

The Artist slideshow is really low res, how can i change that?
Also the results are not that great 😄 
![image](https://cloud.githubusercontent.com/assets/4103090/19470670/b1e732d2-9520-11e6-94af-05a8dc519b56.png)

**Comment by Phyks** [comment]
Not sure such a setting is available. Artist arts are gathered from Musicbrainz I think. Does the artist art match the one on Musicbrainz? Is there a higher resolution available there?

**Comment by Rouzax** [comment]
I think they are gathered from Flickr?

**Comment by Phyks** [comment]
Why Flickr? Definitely, they should be coming from Musicbrainz AFAIK.

**Comment by Rouzax** [comment]
I do not know, that is where they seem to come from. 
Maybe it is because I enabled the Flickr plugin?

**Comment by Phyks** [comment]
Yes, default is to take pictures from Musicbrainz. Flickr is a separate plugin, and if enabled artists arts will be taken from Flickr instead of Musicbrainz.

**Comment by NatureMuncher** [comment]
Not sure if this is related but didn't want to open another issue since it is similar...

The image art on some albums is very low-resolution, like 64x64. I usually open the Edit/Find Art button and find a 300X300 version which looks much better.

Is it possible for Ampache to set a default minimum resolution for the automatic art gathering?

**Comment by NatureMuncher** [comment]
Would it be possible to update all existing low-resolution album art automatically? I'd guess that this would be difficult unless there was a flag indicating whether the image was added by the user (in which case you would not want to update it) or if it was previously gathered by Ampache.

**Comment by kuzi-moto** [comment]
@NatureMuncher in your `conf/ampache.cfg.php` is an option to set minimum resolution for Ampache to store art into the database. For the various areas around the Ampache interface, the cover art is resized depending on the section of the interface it appears. I agree there are some areas that could do with better quality images. It should be fairly easy to edit, but the function that handles getting the art is kind of stupid, and I think should be changed to make more sense.

**Comment by lachlan-00** [comment]
Last.fm also took away the image API this year but for the moment the minimum res is the best option

**Comment by NatureMuncher** [comment]
Thanks! I updated the following:
```
album_art_min_width = 300
album_art_min_height = 300
```
I also removed _lastfm_ from `art_order`

When I manually retrieve art the grainy thumbnails under 300X300 are gone. Hoping newer automatic retrievals are also 300X300. Don't suppose there's an easy way to remove the grainy ones from the DB automatically?

**Comment by lachlan-00** [comment]
I think you've just given a good idea for bin/catalog_update

Clean art based on resolution. I think that's a great idea.

**Comment by lachlan-00** [comment]
I'll add it today, I think it should be pretty simple but until I do that the only way is manually in the database or manually in the ui

**Comment by lachlan-00** [comment]
bin/clean_art_table.inc is just about to go into develop

pfp -f  bin/clean_art_table.inc will clear your table of art that is either too small or too large depending on your settings.

**Comment by xekon** [comment]
Neat @lachlan-00 now if I can just get ampache to honor my settings in the ampache.cfg.php for the minimum width and height.

```
nano /var/www/ampache/config/ampache.cfg.php
album_art_min_width = 200
album_art_min_height = 200
```

No matter what I do the album art continues to be displayed as 150 x 150 px

**Comment by kuzi-moto** [comment]
The art is stored properly in the database, however certain sections of the interface are hard-coded to display a certain resolution.

**Comment by mitchray** [comment]
Answered so I think its safe to close this

**Comment by murchu27** [comment]
Hey folks, I can't see this `bin/clean_art_table.inc` file @lachlan-00 mentions. This is all that's in my `bin` folder:

```
/var/www/ampache# ls bin
cli  daap_register.bat  installer
```

Has this script been moved?

**Comment by lachlan-00** [comment]
It's all under the cli application now. I'll be writing up more about it in the wiki but there's a little blurb about it here

https://github.com/ampache/ampache/wiki/Ampache-Next-Changes

For you the command is `php ./bin/cli cleanup:art`

**Comment by murchu27** [comment]
That did the trick, thanks! Still having strange problems with some albums not finding art, but seems like that would be a separate issue.

**Comment by lachlan-00** [comment]
> That did the trick, thanks! Still having strange problems with some albums not finding art, but seems like that would be a separate issue.

Art is always an issue.
Spotify and the audiodb are worth using if you haven't set them up (but theaudiodb is paid api access)
