### ISSUE TITLE
New ampache user - PHP Error

### ISSUE THREAD

**Issue by kstickel** [ampache/ampache#1416]
After creating a playlist when I want to edit it by clicking on the playlist  I get this error :
 Fatal error: Call to undefined function _() in /ampache/templates/show_playlist.inc.php on line 79

Here is the snippet from my show_playlist.inc.php file 
77                 <a href="<?php echo AmpConfig::get('web_path');
78       ?>/playlist.php?action=sort_tracks&playlist_id=<?php echo $playlist->id;
79       ?>"><?php echo UI::get_icon('sort',_('Sort Tracks by Artist, Album, Song'));
80       ?>

googling "PHP get_icon" does not return anything that helps me correct the error.

Sorry I do not know any PHP so I have no clue as to what to fix in here.

Thanks
K Stickel

**Comment by Phyks** [comment]
Hi, looks like an already fixed issue, not yet released in stable release. Could you try moving to the `develop` branch please and check whether it is fixed?
