### ISSUE TITLE
No coverArt for Playlists in subsonic XML

### ISSUE THREAD

**Issue by SenorSmartyPants** [ampache/ampache#1418]
# Environment

 * Ampache version: 3.8.3-develop

 * Client type:
   - SubSonic

# Settings

# Description

# Logs

I can easily add this to the XML, but I need to know if ampache generates a coverart image for playlists. Subsonic takes 4 covers of songs in the playlist and merges them into a grid for a cover image.

**Comment by lachlan-00** [comment]
In develop/master Ampache is hardcoded to grab 4 images from items in the playlist.
In core Ampache grabs a single random cover.
It's pretty easy get as many covers as you want from playlist items.

**Comment by lachlan-00** [comment]
This is fixed in develop now for all play/smartlists using the same method as web by selecting a random item from the list.
