### ISSUE TITLE
Subsonic API does not use full artist names

### ISSUE THREAD

**Issue by SenorSmartyPants** [ampache/ampache#1421]
# Environment

 * Ampache version: 3.8.3-develop

 * Client type:
   - SubSonic

# Settings

# Description

# Logs

Subsonic API displays artists without prefix 

Beatles
instead of 
The Beatles

The Beatles should still be displayed in the Bs

**Comment by lachlan-00** [comment]
This is fixed in develop.
i've coalesced the prefix and name in most places while also allowing you to search by
"beatles" or "the beatles"
