### ISSUE TITLE
Convert possibility by media file

### ISSUE THREAD

**Issue by Tetram76** [ampache/ampache#1427]
Hi,

Most of my music files can be converted regarding my settings. But some of them cannot (I can't find the reason).
The immediate effect is to hang external players (such as AIMP3).

Is there a possibility to disallow conversion for one music (media?) file in particular?
If not, is it possible to add this as an option attached by file?

**Comment by Phyks** [comment]
@Afterster I do not know about this, you might have better info.

**Comment by Tetram76** [comment]
outdated
