### ISSUE TITLE
php-fpm hang when using dsub to cast

### ISSUE THREAD

**Issue by eephyne** [ampache/ampache#1430]
# Environment
 * Ampache version:
latest develop commit (a9292f8f6e947e33fc6a1d8cdf7d535dc31b6000 now)
 * Web server + version:
nginx 1.10.2 + php-fpm 7.0.12
 * Server operating system:
Linux Arch 64 bit
 * Client operating system:
Linux Arch 64 bit and Android 6 with Dsub 5.3.1

 * Client type:
   - SubSonic

# Settings

I've modified nothing in my settings except db of course
# Description
I really don't know if this related to php-fpm, ampache or dsub, so I ask here first because its the central point.

Without updating anything (that i remember), one day, casting to chromecast using dsub stopped working.
It happen like that:
I start casting
The first song play nicely
When the second song need to be loaded, it don't work.
If I look to DSub, it show failed to load in loop and skip every song one by one (and freeze also…).
If I look the nginx error log, I can see a LOT of request like that 
```

2016/11/19 12:20:43 [notice] 3667#3667: *37 "^/rest/(.*).view$" matches "/rest/stream.view", client: 192.168.0.254, server: music.**, request: "GET /rest/stream.view?u=eephyne&p=enc:616d7061636865&v=1.2.0&c=DSubCC&id=300202531&format=raw HTTP/1.1", host: "music.**", referrer: "https://www.gstatic.com/eureka/player/player.html?skin"
2016/11/19 12:20:43 [notice] 3667#3667: *37 rewritten data: "/rest/index.php", args: "action=stream&u=eephyne&p=enc:616d7061636865&v=1.2.0&c=DSubCC&id=300202531&format=raw", client: 192.168.0.254, server: music.**, request: "GET /rest/stream.view?u=eephyne&p=enc:616d7061636865&v=1.2.0&c=DSubCC&id=300202531&format=raw HTTP/1.1", host: "music.**, referrer: "https://www.gstatic.com/eureka/player/player.html?skin"
2016/11/19 12:20:43 [info] 3667#3667: *37 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 192.168.0.254, server: music.**, request: "GET /rest/stream.view?u=eephyne&p=enc:616d7061636865&v=1.2.0&c=DSubCC&id=300202531&format=raw HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "music.**", referrer: "https://www.gstatic.com/eureka/player/player.html?skin"
```
And when I look to php-fpm, its still there but do not respond anymore (neither for ampache or any other php app on the server. (the error log file of php-fpm don't say anything useful)

I know there is clearly not enough informations to debug this, but I really don't know where to look first for this one.

**Comment by Phyks** [comment]
Could it be that you do not have enough PHP-FPM or Nginx workers? This setup should work just fine (I am using the same setup).

**Comment by lachlan-00** [comment]
I use this setup as well and will close this due to the massive age.
