### ISSUE TITLE
add_user.inc problem

### ISSUE THREAD

**Issue by jameseck** [ampache/ampache#1434]
* Ampache version: 3.8.2 and master branch
 * Web server + version: nginx 1.10.1 + php 7.0.13
 * Server operating system: alpine
 * Client operating system: n/a

Hi,

I'm currently building a docker image to run Ampache.
In one of the startup scripts, I'm trying to create a user with the add_user.inc script.

Unfortunately, the add_user.inc script does not seem to work.  It gets as far as the require_once line for the init.php and then just exits.  Exit code is 0, no output at all.  Even running the script with no arguments or "-u", the result is the same.

Can anyone help me to debug why this is happening please?

Thanks

J

**Comment by Phyks** [comment]
Could you give it a try with the `develop` branch? `master` branch is quite outdated and there have been quite a number of fixes in the `develop` branch lately.

**Comment by jameseck** [comment]
Hi,
I've just tried this with the develop branch too and I get the same result.

**Comment by jameseck** [comment]
Just to also clarify, the update_db.inc script appears to work fine.  That is sourcing the same init.php file, so still quite confused here.

**Comment by jameseck** [comment]
Hi,
I think this might have resolved itself, so I'm closing this issue.

Thanks for the help.
