### ISSUE TITLE
Include a new JSON API

### ISSUE THREAD

**Issue by 2012lucho** [ampache/ampache#1435]
# Description
I am working on a project that uses Ampache as music content manager and we consider that our work would be simpler if Ampache had an API that allows to return answers in JSON format.

That is why we would like to work on incorporating this functionality.

We are currently modifying a local copy by implementing the JSON API, proposing the following changes:

1. Creation of the JSON_Data class (XML_Data variant located in / lib / class)
2.  Creating the json.server.php file (variant of xml.server.php located on / server)

Thank you and sorry for my poor English.

Regards!

**Comment by Phyks** [comment]
This is partly done in https://github.com/ampache/ampache/pull/1268, which is to be merged.

**Comment by 2012lucho** [comment]
ohh thanks!
