### ISSUE TITLE
Blank page when opening /ampache

### ISSUE THREAD

**Issue by j-lin** [ampache/ampache#1444]
# Environment

 * Ampache version: 
latest git clone

 * Web server + version: 
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

 * PHP version:
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

 * MySQL version:
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

 * Server operating system:
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64)

# Description

The server is pretty new, and all the components were recently installed for the latest stable version. I cloned ampache's latest git repo and set the ampache folder with:
`chown -R www-data:www-data ampache`
`chmod -R 755 ampache`
Then I opened the ampache url <server.address>/ampache and it automatically redirected to ampache/test.php, but the whole page was all blank. 
All the necessary and recommended php modules are enabled.
Did I miss anything? I'm guessing so, because I searched the issues and there's no related issues. Can anyone give me a hand or some guidance of where to look at? I'm fairly new to Linux servers, so forgive me if this is too dumb.

**Comment by wagnered** [comment]
Did you install/run composer as described in the wiki at:
https://github.com/ampache/ampache/wiki/Installation? The release
version already had the necessary vendor modules pre-installed, but the
develop version requires that they be manually installed.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by j-lin** [comment]
It worked. I totally overlooked the composer part in the installation instructions. Sorry for my ignorance... 
I guess it was because I downloaded the release archive and tested it on my local internal server, but used the git head on the remote server instead. Thanks for the tips.
