### ISSUE TITLE
DAAP doesn't working with nginx

### ISSUE THREAD

**Issue by Catskan** [ampache/ampache#1445]
# Environment

 * Ampache version: 3.8
 * Web server + version: nginx 1.0
 * Server operating system: Linux Mint 18
 * Client operating system: Windows

 * Client type:
   - DAAP

# Description

Hi all, 
I'm trying to setting up my ampache to a DAAP Server. My iTunes show me my ampache server but the connection doesn't established ...
The wiki instructions are for apache web server, and I have nginx and I can't adapt the apache virtual host to my nginx virtualhost.

My nginx vhost : 

```
 server {
         listen 3689 default_server;
         listen [::]:3689 default_server;
 
         root /var/www/html/ampache/daap;
         index index.html index.php index.htm index.nginx-debian.html index.php;
 
         server_name catskan.hd.free.fr;
 
         location / {
                 try_files $uri $uri/ =404;
         }
 
         location ~ /\.ht {
                 deny all;
 }
 }

```
and my daap/.htaccess : 
```
location / 
{ 
      if (!-e $request_filename) { 
                  rewrite ^(.+)$ /index.php?action=$1 break; 
     } 
}
```

I am a new nginx user and I have trouble getting there.

Thanks you for your help

**Comment by manuelglez86** [comment]
The daap implmentation is not fully working yet, see #718

**Comment by Phyks** [comment]
Closing as a duplicate. Let us continue the discussion in #718.
