### ISSUE TITLE
LDAP auth configured, but only white page is shown

### ISSUE THREAD

**Issue by brendankearney** [ampache/ampache#1446]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: apache 2.4.23
 * Server operating system: fedora 24
 * Client operating system: fedora 24

 * Client type:
   - Web Firefox 50.0.2

# Settings

ldap_filter = "(uid=%v)"
ldap_objectclass = "*"
ldap_username = "cn=Manager,dc=bpk2,dc=com"
ldap_password = "CENSORED"
ldap_require_group = "cn=wwwAmapcheUsers,ou=domainGroups,ou=Groups,dc=bpk2,dc=com"
ldap_search_dn = "ou=domainUsers,ou=Users,dc=bpk2,dc=com"
ldap_url = "ldap://server1.bpk2.com/"
ldap_email_field = "mail"
ldap_name_field  = "cn"
auto_create = "true"

# Description

configure ldap auth per above, and attempt to log in.  only a blank page shows.  note, the required config value in the below logs was the auto_create directive, which was found and set.  once set, sessions seem to establish, but only a blank page is seen.  i suspect this to be a missing php module for LDAP, but am not sure.

# Logs

12:33:23 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:33:23 [ampache] (ldap_auth) -> Required config value missing 
12:33:23 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:34:47 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:34:47 [ampache] (ldap_auth) -> Required config value missing 
12:34:47 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:36:26 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:36:26 [ampache] (ldap_auth) -> Required config value missing 
12:36:26 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:38:40 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:38:40 [ampache] (ldap_auth) -> Required config value missing 
12:38:40 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:39:01 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:39:01 [ampache] (ldap_auth) -> Required config value missing 
12:39:01 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:39:29 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:39:29 [ampache] (ldap_auth) -> Required config value missing 
12:39:29 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:42:52 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:42:52 [ampache] (ldap_auth) -> Required config value missing 
12:42:52 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:43:11 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:43:11 [ampache] (ldap_auth) -> Required config value missing 
12:43:11 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:43:13 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:43:13 [ampache] (ldap_auth) -> Required config value missing 
12:43:13 [ampache] (Login) -> brendan From 192.168.1.87 attempted to login and failed 
12:46:28 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:47:06 [ampache] (session) -> Unable to read session from key ruqkfn520mbfbu6lsqgsq4nn55 no data found
12:47:27 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:47:34 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:48:18 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:48:24 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:49:48 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:49:56 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:50:01 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:50:51 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:50:56 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:53:08 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found
12:53:14 [ampache] (session) -> Unable to read session from key 08ejsgb01a2vkl1sk53fubn775 no data found

**Comment by Phyks** [comment]
@Niols rewrote the LDAP integration recently. @Niols do you have any idea about this?

**Comment by T-Rock** [comment]
I installed Ampache these days and I had the same behaviour with Debian Jessie. 
But I forgot to install the PHP LDAP module php5-ldap.
After installing the module it worked fine.
Can you check, if the module is installed?

**Comment by brendankearney** [comment]
on fedora, the package is php-ldap, and it was not installed.  installed it and all dependencies, and DING!!! logins work.  nice job.

**Comment by mitchray** [comment]
Seems to be solved, closing
