### ISSUE TITLE
jQuerry errors on scroll

### ISSUE THREAD

**Issue by PBlock96** [ampache/ampache#1448]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.23
 * Server operating system: Manjaro Linux
 * Client operating system: Windows 10 Home

 * Client type:
   - Web: Firefox 50.0.2 and Google Chrome 56.0.2924.21

# Settings

http://pastebin.com/CMWsuLpC

# Description
After switching from any page to the browse albums page to the browse song title page every time you scroll the javascript dev console with fill with jquerry errors like so: http://imgur.com/a/Ds0rL

# Logs

Ampache: http://pastebin.com/0jU2jms7

Apache Error log: http://pastebin.com/j3AWrijj

**Comment by Phyks** [comment]
I cannot reproduce on my instance. Maybe a problem with one of your extensions?

**Comment by PBlock96** [comment]
Possible, system has been replaced. Sorry I can't be of much more help.
