### ISSUE TITLE
500 error after first install

### ISSUE THREAD

**Issue by nicosalto** [ampache/ampache#1449]
Hi,
i got a 500 error when i try to install a clean new ampache onto a freenas jail.
I installed apache, php, mysql and the php plugins.
i copied over the git and processed the installed with composer.
i also activated mod_rewrite. 
All those step went fine.

This is my vhost config:
```
<VirtualHost *:80>
    ServerAdmin something@something.com
    DocumentRoot "/usr/local/www/ampache"
    ServerName ampache
    ServerAlias www.ampache
        <Directory />                        # This should be a full path, though
            Require all granted
            Options Indexes FollowSymLinks Includes ExecCGI                
            AllowOverride all
        </Directory>
</VirtualHost>
```

also i didnt changed any of the htaccess since ampache is the root folder.

Please let me know if you have any idea where my issue is coming from!

**Comment by nicosalto** [comment]
I reinstalled everything again from scratch today, but still not luck. iam still getting that 500 error when i want to access the 500 page.
this is my error log : ( /var/log/httpd-error.log )
> [Wed Dec 14 22:19:35.294054 2016] [mpm_prefork:notice] [pid 94396] AH00163: Apache/2.4.23 (FreeBSD) configured -- resuming normal operations
[Wed Dec 14 22:19:35.294222 2016] [core:notice] [pid 94396] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:22:52.017490 2016] [mpm_prefork:notice] [pid 94396] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 22:22:52.116264 2016] [mpm_prefork:notice] [pid 94495] AH00163: Apache/2.4.23 (FreeBSD) configured -- resuming normal operations
[Wed Dec 14 22:22:52.116437 2016] [core:notice] [pid 94495] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:28:57.897487 2016] [mpm_prefork:notice] [pid 94495] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 22:28:58.003037 2016] [mpm_prefork:notice] [pid 94898] AH00163: Apache/2.4.23 (FreeBSD) PHP/5.6.28 configured -- resuming normal operations
[Wed Dec 14 22:28:58.003085 2016] [core:notice] [pid 94898] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:29:34.230778 2016] [:error] [pid 94899] [client 192.168.1.229:52699] PHP Warning:  phpinfo(): It is not safe to rely on the system's timezone settings. $
[Wed Dec 14 22:34:49.076309 2016] [:error] [pid 94956] [client 192.168.1.229:52760] PHP Fatal error:  Class 'Gettext\\Translator' not found in /usr/local/www/apache24/$
[Wed Dec 14 22:36:33.088710 2016] [:error] [pid 94959] [client 192.168.1.229:52771] PHP Fatal error:  Class 'Gettext\\Translator' not found in /usr/local/www/apache24/$
[Wed Dec 14 22:49:07.629419 2016] [mpm_prefork:notice] [pid 94898] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 22:49:07.745811 2016] [mpm_prefork:notice] [pid 97096] AH00163: Apache/2.4.23 (FreeBSD) PHP/5.6.28 configured -- resuming normal operations
[Wed Dec 14 22:49:07.745870 2016] [core:notice] [pid 97096] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:49:15.614927 2016] [:error] [pid 97097] [client 192.168.1.229:52824] script '/usr/local/www/apache24/data/ampache/in.php' not found or unable to stat
[Wed Dec 14 22:49:18.692483 2016] [:error] [pid 97097] [client 192.168.1.229:52824] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:49:31.178756 2016] [:error] [pid 97098] [client 192.168.1.229:52826] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:49:37.205292 2016] [:error] [pid 97099] [client 192.168.1.229:52827] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:55:20.891383 2016] [mpm_prefork:notice] [pid 97096] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 22:55:21.016890 2016] [mpm_prefork:notice] [pid 97333] AH00163: Apache/2.4.23 (FreeBSD) PHP/5.6.28 configured -- resuming normal operations
[Wed Dec 14 22:55:21.016943 2016] [core:notice] [pid 97333] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:55:25.007137 2016] [:error] [pid 97334] [client 192.168.1.229:52853] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:55:27.418695 2016] [:error] [pid 97335] [client 192.168.1.229:52854] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:57:22.457298 2016] [mpm_prefork:notice] [pid 97333] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 22:57:22.583089 2016] [mpm_prefork:notice] [pid 97394] AH00163: Apache/2.4.23 (FreeBSD) PHP/5.6.28 configured -- resuming normal operations
[Wed Dec 14 22:57:22.583142 2016] [core:notice] [pid 97394] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 22:57:26.680706 2016] [:error] [pid 97395] [client 192.168.1.229:52862] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 22:58:14.714876 2016] [:error] [pid 97396] [client 192.168.1.229:52865] PHP Warning:  phpinfo(): It is not safe to rely on the system's timezone settings. $
[Wed Dec 14 22:58:30.777205 2016] [:error] [pid 97399] [client 192.168.1.229:52867] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 23:02:13.918357 2016] [mpm_prefork:notice] [pid 97394] AH00169: caught SIGTERM, shutting down
[Wed Dec 14 23:02:14.045409 2016] [mpm_prefork:notice] [pid 97609] AH00163: Apache/2.4.23 (FreeBSD) PHP/5.6.28 configured -- resuming normal operations
[Wed Dec 14 23:02:14.045462 2016] [core:notice] [pid 97609] AH00094: Command line: '/usr/local/sbin/httpd -D NOHTTPACCEPT'
[Wed Dec 14 23:02:17.187616 2016] [:error] [pid 97610] [client 192.168.1.229:52924] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$
[Wed Dec 14 23:03:23.371705 2016] [:error] [pid 97612] [client 192.168.1.229:52926] PHP Fatal error:  Call to undefined function utf8_encode() in /usr/local/www/apache$

>

**Comment by wagnered** [comment]
Missing class 'Gettext\Translator' indicates improper installation. Make
sure composer is run INSIDE the document root; the ampache folder.

Enable ampache debug log per
https://github.com/ampache/ampache/wiki/Troubleshooting

What version of Ampache is installed?  Try the develop branch.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
Also, make sure that the php xml extension is loaded. cli command `php
-m` will display all loaded modules.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by nicosalto** [comment]
Thanks a lot for your answer and help wagnered !
You were on the gold, my issue was that the xml package was not installed! I had simpleXml installed, but not xml...
They should put this info on the the installation page!
Thanks again!

**Comment by wagnered** [comment]
Yea, that README probably has not been updated from an earlier version
of Ampache.


If your issue has been resolved, please close it: It can be  reopened
later if the problem re-occurs.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug
