### ISSUE TITLE
Fatal error: Uncaught Error: [] operator not supported for strings in

### ISSUE THREAD

**Issue by pbtrung** [ampache/ampache#1451]
I encountered this error while scanning my media library using php .../catalog_update.inc -a

......./05-AudioTrack 05.mp3
Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:926
Stack trace:
#0 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1088): getid3_mp3->decodeMPEGaudioHeader(1757, Array, false)
#1 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(1757, 2174, false)
#2 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(1757, Array, true)
#3 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(1757)
#4 /var/www/html/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /var/www/html/lib/class/vainfo.class.php(96): getID3->analyze('/media/aub/PEMA...')
#6 /var/www/html/modules/catalog/local/local.catalog.php(674): vainfo->__construct('/media/aub/PEMA...', Array, '', '', '', '%a/%A', '%T - %t')
#7 /var/www in /var/www/html/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 926

Ampache docker: https://github.com/pbtrung/ampache-docker
Ampache 3.8.3-develop, PHP 7, MySQL 5.7, Apache 2.4

Thanks.

**Comment by pbtrung** [comment]
It seems to be because of james-heinrich/getid3.

**Comment by wagnered** [comment]
Let's not jump to conclusions....

Have you tried updating from the web interface?


I ran the command on my collection and did not find a problem.

Is your collection using the utf-8 or the utf-16 character set? Ampache has problems when
 the characterset is mixed: this often happens with id3v2 metadata? Should be utf-8.

Is this an ampache debug log (doesn't look like it) or php error log? if not an ampache debug log,
Try running command with ampache debugging set.

Just throwing the info out there: It looks like php is complaining because Ampache, for some reason
is supplying  a string to the getid3 functions instead of an array, which the function requires.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by pbtrung** [comment]
I can not reproduce the error anymore. Close it for now.
Thanks for your reply.

**Comment by petrucci4prez** [comment]
this problem still exists. I started weeing this after I upgraded to php7.1 from 7.0. I see the following in my http error log when trying to update from the web interface:

`[2017-02-14 20:57:48.619787] [php7:error] [pid 1080] [client 192.168.11.11:59582] [https://portnoy4prez.ddns.net/ampache/index.php] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:464
Stack trace:
#0 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1098): getid3_mp3->decodeMPEGaudioHeader(36859, Array, false)
#1 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(36024, 36859, false)
#2 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(36024, Array, true)
#3 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(36024)
#4 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /usr/share/webapps/ampache/lib/class/vainfo.class.php(94): getID3->analyze('/mnt/data/Music...')
#6 /usr/share/webapps/ampache/lib/class/catalog.class.php(1 in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 464`

Additionally, I see `Server-Sent Events connection error.` on the web interface, and it seems to get caught in an infinite loop of scanning a few songs, throwing the error, and resetting.

Downgrading to php7.0 solves the issue

**Comment by wagnered** [comment]
You don't give any info about what version of Ampache, or system.

If you are running Ampache 3.8.2-release. try installing composer and
running the command:

    composer update james-heinrich/getid3

in the ampache folder.

There was a fix dated [2016-12-14] for this problem.

If you are running a develop version, just run the command.

Otherwise

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by petrucci4prez** [comment]
sorry, ampache 3.8.2-release on Arch with apache 2.4.25

composer did not solve the issue, here is the output:

Package "lib/vendor/james-heinrich/getid3/getid3/getid3.php" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
ComponentInstaller\Installer::postAutoloadDump
Compiling component files

also, what fix on 2016-12-14? I don't see any commits on that date

**Comment by wagnered** [comment]
If you look at issue #92 he indicates commit 7f069ac
<https://github.com/JamesHeinrich/getID3/commit/7f069ac25b3d83e849aeefe4f7da660f358b6b25>
for errors and commit 288293d
<https://github.com/JamesHeinrich/getID3/commit/288293d2a7b95b79e7ef27da957dcdfd89873f62>
which standardizes all the warning calls.

Your composer.lock file is probably not allowing a later version of
getid3. if you look at the version history in changelog.txt in
lib/vendor/james-heinrich/getid3 You will see the latest changes. It
should say "1.9.13: [2016-12-14] James Heinrich".

You will probably have to go to Ampache 3.8.3-develop to get the latest
version of getID3.

If upgrading doesn't help, then you need to create  another getID3 issue
and submit a file that is causing the problem as suggested in issue #92.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug
