### ISSUE TITLE
Ampache Clients Can't Connect

### ISSUE THREAD

**Issue by ramicaza** [ampache/ampache#1453]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.10
 * Server operating system: Raspian
 * Client operating system: Multiple

 * Client type:
   - Ampache
   - SubSonic
# Settings

[ampache.cfg.php.zip](https://github.com/ampache/ampache/files/667945/ampache.cfg.php.zip)

# Description

I've gotten the server installed and running on a raspberry pi and the web client seems to work fine however I can't seem to get any android client to work correctly.  "Just Player" authenticates correctly and says it's connected but doesn't show my music library.  "Power Ampache" and "Music Player" fail to even authenticate.  I've also tried some subsonic clients.  When i feed them the /ampache/server/xml.server.php file they try to connect and then give a "subsonic rest exception".  Thanks in advance.

# Logs

I enabled debug level 5 and there doesn't seem to be any logs being generated when the clients try to log on.

**Comment by Phyks** [comment]
Maybe related to https://github.com/ampache/ampache/issues/1429, https://github.com/ampache/ampache/issues/1405 and https://github.com/ampache/ampache/issues/1389.

Long story short, the Subsonic API implementation in Ampache is based on an older version of the Subsonic API, and some clients may not be compatible. I know for sure that DSub on Android works fine. See the [wiki](https://github.com/ampache/ampache/wiki/API#subsonic-api), you have to set up URL rewriting to use the subsonic API.

**Comment by ramicaza** [comment]
I downloaded DSub as you recommended and still cannot get it to connect.  I've noticed that I get a 404 when I try to visit /rest/ping.view.  I've also checked to make sure my .htaccess file in the rest dir is configured correctly with my full path name.  Here is my .htaccess:
`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/play/$1 [PT,L,QSA]
</IfModule>
`

**Comment by ramicaza** [comment]
I found the issue.  It turns out my .htaccess file was configured correctly however I did not have "Allowoverride All" set in my apache2.conf.  Used this guide to troubleshoot:  https://docs.bolt.cm/3.4/howto/making-sure-htaccess-works
