### ISSUE TITLE
Plex backend shows up in myPlex with "Needs Update" message

### ISSUE THREAD

**Issue by gryphonmyers** [ampache/ampache#1456]
# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache/2.4.6 (CentOS) 
 * Server operating system: CentOS Linux release 7.3.1611 (Core) 
 * Client operating system: macOS Sierra 10.12.2

 * Client type:
   - Plex

# Settings

[Uploading ampache.cfg.php…]()

# Description

After adding ampache plex backend to my myplex account on port 32500, myPlex successfully lists the server but marks it as "Needs Update":

https://www.dropbox.com/s/yjrjotovtfgi7xp/Screenshot%202017-01-01%2012.21.47.png?dl=0
https://www.dropbox.com/s/8m3um9toegdbmsm/Screenshot%202017-01-01%2012.09.52.png?dl=0

Apologies if this is a problem with my configuration, but it seemed likely that Plex may have recently changed their API and ampache has not yet been updated to support it. 

# Logs

[log.txt](https://github.com/ampache/ampache/files/768826/log.txt)

**Comment by Phyks** [comment]
Sorry, I never used the Plex backend. I am not sure we actually have any maintainer left for the Plex backend :/

Any help or PR on this is greatly appreciated ! :)

I tagged it as `bug` as it is a blocking problem as far as I understood.

**Comment by gryphonmyers** [comment]
OK that's sorta what I thought. I'd wager a guess that this broke when Plex
revamped their music libraries. IMO this is useful functionality to
preserve because the Plex clients are better and more frequently updated
than any of the subsonic clients (at least on desktop).

**Comment by gryphonmyers** [comment]
I updated the version the plex api sends to a more recent version, and while it gets rid of the "Needs Update" message and shows the library, unsurprisingly, it now gives all kinds of weird errors when attempting to load items for the dashboard or play songs. Seems like there are indeed some updates needed.

**Comment by gryphonmyers** [comment]
I have tracked the issue (at least AN issue) to Plex trying to stream from a URL resembling:

http://REDACTED/library/parts/140001383/file.mp3?X-Plex-Session-Identifier=i1guqynfdv9luc1ypmympwrk&X-Plex-Product=Plex%20Web&X-Plex-Version=2.13.0&X-Plex-Client-Identifier=719bd22f-f303-44f0-8a60-cb3311b74fb8&X-Plex-Platform=Chrome&X-Plex-Platform-Version=56.0&X-Plex-Device=OSX&X-Plex-Device-Name=Plex%20Web%20%28Chrome%29&X-Plex-Device-Screen-Resolution=679x803%2C1440x900&X-Plex-Token=REDACTED&Accept-Language=en

When I plug that URL into the browser, it 404s. 

https://github.com/ampache/ampache/blob/develop/lib/class/plex_api.class.php#L1100

Looks to be the relevant code but nothing is jumping out at me. 

In Ampache's logs I see a corresponding stream proxy resembling:

http://REDACTED/play/ssid/320ace850ed57cdc3bcb83f92e76010e/type/song/oid/1379/uid/1/player/api/name/REDACTED.mp3

I don't know enough about how Ampache works to understand if this is a config issue on my part, or if something about the Plex class is generating bad stream proxy URLs. Normal playback from the Ampache interface works fine. 

Any thoughts?

**Comment by gryphonmyers** [comment]
When I compare to a correctly functioning stream URL (that I grab out of the Ampache web player), it looks to me like the Plex class is incorrectly parsing params into path rather than query string.

Works:
http://REDACTED/play/index.php?ssid=94476577e7b2d0fbf19310c2c9df1e9d&type=song&oid=2016&uid=1&name=Kow%20Otani%20-%20Final%20Battle.mp3

Does not work:
http://REDACTED/play/ssid/51035d4e492d95dd65249869ab160e39/type/song/oid/391/uid/1/player/api/name/Shackleton%20-%20Music%20for%20the%20Quiet%20Hour-%20Part%201.mp3

I see type/song rather than &type=song, etc etc. Can @Phyks or @Afterster or anyone verify whether this URL pattern is supposed to work?

**Comment by lachlan-00** [comment]
Closing.
Plex is proprietary software now and the backend is going to be removed from the next release of Ampache.
