### ISSUE TITLE
guzzle packages abadoned - use guzzle/guzzle instead

### ISSUE THREAD

**Issue by shoubamzlibap** [ampache/ampache#1457]
# Environment

 * Ampache version: develop, commit 18aeae2ae26762829395bfaefc570d386f556fb8 (04-Jan-2017)

# Issue
When running composer, I get

```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

```

So I guess the dependencies should be updated accordingly.

**Comment by Phyks** [comment]
It is a dependency of a third-party library. See https://github.com/ampache/ampache/issues/957 for more infos. Closing as a duplicate.
