### ISSUE TITLE
End of support for sabre/dav, PHP 5.4

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#1458]
We currently support PHP 5.4, forcing us to stay on the `3.0` branch of `sabre/dav`, whose support will end this month: http://sabre.io/dav/install/.

**Comment by AshotN** [comment]
Support is over for sabre, any news on removing support for PHP 5.4?

**Comment by lachlan-00** [comment]
Closing.
Ampache currently supports 5.6 & 7.3.
sabre/dav is set to 3.*.* current supported verison is 3.2
