### ISSUE TITLE
ID -1  imports weird ratings on tag update?

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1464]
when i do a verify to update tag changes i get a lot of random ratings on tracks. these ratings can't be removed, only altered.

(ie, i can make a 5 rating 4. but when i delete the rating it returns to 5)

I can't find anything in the tags themselves that obvious but there are a lot of -1's.

If i delete these rows they are reimported.

id 	user Ascending 1 	object_type 	object_id 	rating
34793 	-1 	song 	46153 	4
34712 	-1 	song 	961 	4
34713 	-1 	song 	962 	4
34716 	-1 	song 	2823 	5
34717 	-1 	song 	2825 	5
34719 	-1 	song 	2828 	5

**Comment by tdeuling** [comment]
These ratings are global ratings which are extracted from the file itself.

1. Local importer getting Fileinformation https://github.com/ampache/ampache/blob/develop/modules/catalog/local/local.catalog.php#L679
2. Identify rating in new file https://github.com/ampache/ampache/blob/develop/lib/class/vainfo.class.php#L928
3. Writing rating for new file https://github.com/ampache/ampache/blob/develop/modules/catalog/local/local.catalog.php#L752

IMHO this is not a bug and ticket can be closed.

**Comment by lachlan-00** [comment]
What if i can't find a rating tag in my files?

So far i've checked easytag, quodlibet, terminal programs, any my own scripts looking for a rating but they don't exist.

I've deleted the tage and reapplied from musicbrainz picard and they still come back.

**Comment by lachlan-00** [comment]
Using audioshell [http://www.softpointer.com/AudioShell.htm]

I set all tracks to 4 stars then half to unrated.

the 4 stars stayed  4 and the unrated songs reverted to 5.

**Comment by tdeuling** [comment]
I'm using EasyTag for Linux too, and that tool doesn't show me the rating.
But there is a Popularimeter tag (https://en.wikipedia.org/wiki/ID3), which I could modify with the Kid3 ID3-Editor. Afterwards the rating for user -1 is not longer available.
![selection_051](https://cloud.githubusercontent.com/assets/1298841/24303022/cb9b6454-10b4-11e7-9ff0-ee015fac42ef.png)

**Comment by lachlan-00** [comment]
There was no popm tag in my files but if I add one then delete one the ratings disappear.

I'm not sure what it could be but it must be corruption in the individual files.
