### ISSUE TITLE
Compatibility with newer doctrine/cache

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1465]
Hello!

I'm working on packaging ampache for Fedora. I've noted that ampache has a requirement on an explicit verison of doctrine/cache at 1.5.4. Fedora already has 1.6.1, which is the latest upstream release. Is ampache incompatible with the 1.6 series? If so, could we patch it to work with 1.6?

**Comment by Phyks** [comment]
https://github.com/ampache/ampache/pull/1459/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R36

**Comment by bowlofeggs** [comment]
@Phyks Awesome! Since that PR didn't change any code, do you think the stable release of Ampache might work with cache 1.6.1? Or have there been changes on master since the release that make that PR ok?

**Comment by Phyks** [comment]
Normally I should have checked it, and it should be ok. Still, a double check is always useful :)

**Comment by bowlofeggs** [comment]
Thanks for the information!
