### ISSUE TITLE
Can Ampache work with a newer gettext?

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1467]
It seems that gettext's latest version is 4.2.0:

https://packagist.org/packages/gettext/gettext

However, the ```composer.json``` file specifies a dependency on 3.5.*. Is it possible that Ampache is compatible with 4.2.0 without changes, or would it need to be altered to work with a newer gettext?

**Comment by Phyks** [comment]
See https://github.com/ampache/ampache/pull/1459/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R37

**Comment by bowlofeggs** [comment]
On Wed, 2017-01-18 at 02:43 -0800, Lucas Verney wrote:
> See https://github.com/ampache/ampache/pull/1459/files#diff-b5d0ee8c9
> 7c7abd7e3fa29b9a27d1780R37

Great, thanks!
