### ISSUE TITLE
Localplay gets error 404

### ISSUE THREAD

**Issue by paul70078** [ampache/ampache#1475]
# Environment

 * Ampache version: 3.8.3-develop
 * Web server + version: Apache 2.4.10 (Raspbian)
 * Server operating system: Raspbian 8

# Settings

Ampache ist installed in the root directory (via virtual host)

Localplay activated for mpd on localhost:6600
(for more, see config file)

# Description
When trying to use local play with mpd it doesn't work and mpd logs
`curl: curl failed: The requested URL returned error: 404 Not Found`

# Logs

[config+logs.zip](https://github.com/ampache/ampache/files/734043/config.logs.zip)

EDIT: Added install location

**Comment by stebe** [comment]
Is  your Ampache instance is not on the root of the server. MPD may need to be calling http://<IP-OF-SERVER>/ampache/play.... Did you set up your htaccess file correctly in the rest and play sub-folders? Check the web server configuration section in the wiki https://github.com/ampache/ampache/wiki/Installation

**Comment by paul70078** [comment]
ampache is in the root directory and the .htaccess files seem to point to the correct path

**Comment by stebe** [comment]
Your apache access log doesn't show a similar request to mine.
ampache.example.com:443 2001:470:ffff:1::10 - - [27/Jan/2017:05:53:01 -0500] "GET /play/index.php?ssid=c32b83a6ffaafd476589adbdcd76b114&uid=1&demo_id=1 HTTP/1.1" 200 7010289 "-" "Music Player Daemon 0.19.1"


I'm running as a vhost so the htaccess should be similar to mine as Ampache is on the root of the vhost.

[htaccess.txt](https://github.com/ampache/ampache/files/735049/htaccess.txt)

**Comment by paul70078** [comment]
Are you sure to open the right path in your browser? Ampache would be installed under http://localhost/ampache

**Comment by paul70078** [comment]
I see the difference in access log, but i compared the .htaccess files and they are ident.
Webplayer is working fine. Is there a way to check if the .htaccess is working?

**Comment by paul70078** [comment]
Got it up and running!
Had previous problems with `AllowOverride All` in VHost config and looked it up on google
