### ISSUE TITLE
TrackNumber not unique when added over API

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#1479]
# Environment

 * Ampache version: Ampache 3.8.3-develop 
 * Web server + version: NGinx
 * Server operating system: Debian
 * Client operating system: Linux Mint

 * Client type:
   - Web
   - Ampache

# Description

It is not completely clear to me why, but whenever I use the playlist_add_song option in the API some songs end up having the same TrackNumber. This is really problematic for me since the only way to remove songs from a playlist via the API is by using the TrackNumber. Once I load the playlist with the regular web browser, it auto-sorts the tracks and the problem is gone. 

### Some things I noticed not sure if they are relevant

Sometimes I add a song that exists in one playlist to another playlist... it copies the TrackNumber

For example

I have two Playlists, Playlist A and Playlist B

If Track X is in Playlist A with a TrackNumber of 11
I add Track X to Playlist B and the TrackNumber is identical

I took a look, I didn't fully understand the mechanism. If someone is able to reproduce I will see if I can fix it myself

[The Mechanism](https://github.com/ampache/ampache/blob/624a2f0717395443dfdd5a5c4594f8512ae5bd65/lib/class/playlist.class.php#L388 )

**Comment by BLeeEZ** [comment]
I am currently facing this issue too. This is a big problem to manage the server playlists via API.

**Comment by lachlan-00** [comment]
Thanks I haven't seen this issue yet but I'll be working on the API soon

**Comment by lachlan-00** [comment]
fixed in core branch.
