### ISSUE TITLE
catalog_update.inc does not run with php7.1

### ISSUE THREAD

**Issue by ricksorensen** [ampache/ampache#1481]
# Environment

 * Ampache version: 3.8.3-develop/18aeae2ae26762829395bfaefc570d386f556fb8
 * Web server + version:apache2
 * Server operating system:Ubuntu 6.04 LTS
 * Client operating system: Windows 10 (web)  Not Applicable
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapperLinux 
PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )

 * Client type: not applicable
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings
MySql:
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapperLinux 
PHP:
PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
Apache:
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

# Description
[Note: git clone in /home/rick/tool/ampache]
When trying to run the cron.daily/ampache update:
`sudo -u www-data php /home/rick/tools/ampache/bin/catalog_update.inc -a -c`
nothing happens- no standard output, no standard error.  I put echo commands in the catalog_update.inc command, and it looks like the execution does not make it through the:
` require_once $prefix . '/lib/init.php';`
I even tried hard coding the address, and it still does not make it through- with no entries in any log I can find.  If I change the command to:
`sudo -u www-data php7.0 /home/rick/tools/ampache/bin/catalog_update.inc -a -c`
The update works fine, (as it does with php5.6)

Note- I noted the problem on the prior development version of Ampache (>6 months old).  I then uipdated to see if the new version made a difference but it did not.  

Ampache works fine for playing/searching/etc... The database is a mess though- many badly stored/tagged files, with many utf-8 errors, but functionally the Ampache interface works great.

# Logs

**Comment by wagnered** [comment]
You might want to enable ampache debug logging and/or php error logging.

I do know that character set errors in the mp3 tags will cause the file
not to be added to the catalog. You seem to be indicating that php isn't
getting that far.

The debug/error logs might reveal what's going on.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by ricksorensen** [comment]
Thanks for the suggestions- 

Note that when I clean/add/verify from the web interface (admin:show catalogs windows) the requested action takes place correctly.  I have seen this only with the command line execution.

For ampache logging- I had been using debug level 2 which had no information written to ampache log.  I set the level to 5 and saw nothing when using php7.1 with command:
`sudo -u www-data php7.1 /home/rick/tools/ampache/bin/catalog_update.inc -a -c`

 For php5.6 the ampache log showed all the update checks with command:
`sudo -u www-data php5.6 /home/rick/tools/ampache/bin/catalog_update.inc -a -c`

The php logs showed nothing- though I am not proficient in php so the logging may not be set correctly.  The only php log file I found was `php7.0-fpm.log` and `php5.6-fpm.log`.  The only entries were from last reboot of system.
The apache2 logs `access.log` and `error.log` gave no indications of any php issues.

**Comment by wagnered** [comment]
If you look closely at the command line below, you are not using the fpm
module of Apache2.  you are using the PHP cli (command Line Interface)
which on some systems is actually called php-cli.  You need to set the
logging in the global php.ini file, It might be the same one as set in
the php-pfm.conf file, but you need to check.  As I don't use Windows, I
can't help you there.

Sometimes, when PHP detects an error, it reverts to the beginning of the
procedure/file that caused the error and repeats.  If there is no debug
code at that point, there will be nothing in the log. I've seen this
problem when working with the TV and movie code. the php log should
expose the errors.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by ricksorensen** [comment]
Modifying /etc/php/7.1/php.ini to enable logging did not give anymore information.  However, I determined my apache2 config was using php5.6 so I reverted the CLI to 5.6 also.  

I do not yet know why php7.1 was not successful though..

**Comment by ricksorensen** [comment]
Php 7.1 was installed with a set of other updates on my Ubuntu 16.04.  Now looking at the install and all the modules, I discovered that many of the php modules were missing.  After installing the 7.1 php modules to match the 5.6 and 7.0 set, the command line now works.  Still not clear as to why there was no error reported by php- but that is another issue.  This should be closed as not an ampache issue.
