### ISSUE TITLE
Web Client: Cannot "save track order" in playlist

### ISSUE THREAD

**Issue by nis65** [ampache/ampache#1483]
# Environment

 \# git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
 \# git pull
Already up-to-date.
 \# git rev-parse HEAD
18aeae2ae26762829395bfaefc570d386f556fb8

 * Client type: Web

# Description

Playlist support is the most important feature for me in a music application. Usually, I create a playlist in two steps: First, I add tracks more or less arbitrarily. Second, I want to refine the playlist by reordering the tracks (and add/remove one or the other). While I am able to move individual songs with drag&drop, I am not able to save the new track order - it is lost after reloading the playlist. Am I too ignorant to find the "save track order" button or has this been removed? I think that this existed once, as there is an older Issue (#361) describing such a button.

**Comment by mitchray** [comment]
'Save Track Order' is showing on playlists for me on 4.4.1 so I'm going to close this
