### ISSUE TITLE
Preventing Duplicates in Playlists over API

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#1484]
* Client type:
   - API
# Description

Currently using the `playlist_add_song ` API method allows no way of knowing if the song being added is already in the playlist.

If a ` playlist_contains` method were added or if the `playlist_add_song` method didn't allow duplicates that would be better in my opinion.

**Comment by AshotN** [comment]
Was this ever addressed, or should I check if it's still an issue.

**Comment by lachlan-00** [comment]
I put checks in the main code for imports and updates so I'm assuming this is okay over the API as well. I'll double check today
