### ISSUE TITLE
Compatible with noty-2.4.0?

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1485]
Hello!

I'm working on packaging Ampache and all of its dependencies for Fedora. I noticed that Ampache's ```composer.json``` specifies that it depends on ```"needim/noty": "2.3.*"```, but the latest release of noty is 2.4.0. Is Ampache known not to work with 2.4.0?

**Comment by lachlan-00** [comment]
I just tested with 3.1.4 and it looks okay. i'll update to 2.4.1 for now and test that out.
