### ISSUE TITLE
can't connect with AD Windows 2008

### ISSUE THREAD

**Issue by Mokhless** [ampache/ampache#1486]
# Environment

 * Ampache version: 2.4 
 * Server operating system: ubuntu 16.04
 * PHP7.0 

# Settings

;#########################################################
; LDAP login info (optional)                             #
;#########################################################

; LDAP server URL (required)
; DEFAULT: none
ldap_url = "ldap://vod.com/"
;ldap_url = "ldaps://192.168.0.1/"

; LDAP credentials (optional)
; DEFAULT: none
;ldap_username = ""
;ldap_password = ""

; LDAP Base DN for the search (required)
; DEFAULT: none
ldap_search_dn = "ou=ampache,dc=vod,dc=vod,dc=com"

; LDAP objectClass (required)
; DEFAULT: none
;ldap_objectclass = "posixAccount"          ; OpenLDAP
ldap_objectclass = "organizationalPerson"  ; Microsoft Active Directory

; LDAP filter for search (required)
; DEFAULT: none
;ldap_filter = "(uid=%v)"                   ; OpenLDAP
ldap_filter = "(sAMAccountName=%v)"        ; Microsoft Active Directory

; Require that the user is in a specific group (optional)
; DEFAULT: none
;ldap_require_group = "cn=yourgroup,ou=yourorg,dc=yoursubdomain,dc=yourdomain,dc=yourtld"

; LDAP name field
; DEFAULT = "cn"
;ldap_name_field = "cn"
;ldap_name_field = "displayName"

; LDAP email field
; DEFAULT = "mail"
;ldap_email_field = "mail"

; LDAP avatar field
; DEFAULT: none
;ldap_avatar_field = "jpegPhoto"

; LDAP avatar mime type
; DEFAULT: image/jpeg
;ldap_avatar_mime = "image/jpeg"

; LDAP protocol version to use
; DEFAULT: 3
;ldap_protocol_version = 3

; LDAP StartTLS
; DEFAULT: false
ldap_start_tls = "false"

; LDAP member attribute name.
; That's the name of the attribute of the group that will contain
; the usernames.
; DEFAULT: member
;ldap_member_attribute = "ampache"
;ldap_member_attribute = "Users"

# Description

i configure my server AD and try to connect with users created in AD, help me please

# Logs

2017-02-09 09:30:29 [ampache] (session) -> Unable to read session from key 9m8fqe0j168igoh66p7tpjp835 no data found
2017-02-09 09:30:29 [ampache] (ldap_auth) -> ldap_search: (&(objectclass=organizationalPerson)(sAMAccountName=hachicha))
2017-02-09 09:30:29 [ampache] (PHP) -> [Runtime Error] ldap_search(): Search: Operations error in file /var/www/html/ampache/lib/class/auth.class.php(334)
2017-02-09 09:30:29 [ampache] (PHP) -> [Runtime Error] ldap_get_entries() expects parameter 2 to be resource, boolean given in file /var/www/html/ampache/lib/class/auth.class.php(335)
2017-02-09 09:30:29 [ampache] (Login) -> hachicha From 127.0.0.1 attempted to login and failed

**Comment by wagnered** [comment]
From your log, it looks like either the 'ldap_search_dn',  or
ldap_filter string is wrong in your config file. PHP can't produce the
required resource from the data given in the config file.

I'm not familiar with LDAP protocol, but please have patience, The
people who can help, donate their spare time to the Ampache project,
someone knowledgeable should respond in good time.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Mokhless** [comment]
thank you
