### ISSUE TITLE
Giving smart playlists some love

### ISSUE THREAD

**Issue by antlersoft** [ampache/ampache#1487]
This is not really an issue, more an announcement of an ongoing project that should result in one or more pull requests.

I'm finally dropping out of the Apple music ecosystem completely.  One of the features I really liked about my iPods were their smart playlists.  Ampache is a nice open platform with clients for all my devices that also supports smart playlists, but the smart playlists don't have some of the key features I want and are also impossible to use from any client that is not the web client.

I'll describe my use case, which I don't think is that unusual.  I have ~5,000 songs in my collection that are mostly curated, with all but the newest songs having a star rating.  I like to hear a random selection of these songs, skipping any songs with a 1 or 2-start rating and any that I've listened to in the last couple of weeks.  iPods let you do this but off-the-shelf Ampache does not.  I was able to extend Ampache's smart playlist feature pretty simply to support this-- I've added a new rule type Fresh with a minimum number of days since a song was last played by the user-- and it looks like it should be able to be extended further to support some things that you can't do on iPods that I'd like: maybe allow 5 star songs to be played every 3 days and 4 star songs every 7 days, something like that.

Smart playlists had a few more problems that I had to overcome.  First, it seems like you can only play them from the web client.  Other clients I've tried-- Amplayer for Chrome, many different ones for Android, don't support playing from smary playlists.  I'm working an a [new android client to address some other issues with existing clients](http://github.com/antlersoft/patchyamp), but I'd really like to just use any existing client to play my smart playlists.  The obstacle here is that the XML API doesn't include support for smart playlists, even for just playing them.  In [my fork of Ampache](http://github.com/antlersoft/ampache), I've done a quick and dirty workaround, where the XML API returns and plays smart playlists instead of regular playlists-- this needs a better long term solution; I'm leaning towards the XML API returning both regular and smart playlists, modifying the ID field so they can be distinguished in future client requests.

This part is already in, just didn't see it in the UI: [Another problem is that clients tend to not be built to randomize playlists.  To fix this, I want Ampache to do the randomization on the server side.  This has been added as a feature in Ampache searches, but not in smart playlists.  I've addressed this in my fork Ampache by making whether or not a playlist is randomized a rule type rather than a flag external to the rules.  Making it a rule type makes the UI just work for both searches and smart playlists.  I also want to make the Limit count a rule type, expecially since the most recent Web UI becomes unusably slow when used with long playlists.]

One additional problem with smart playlists is that the database upgrade doesn't handle converting smart playlists rules from serialize to JSON format when that change was made...

One concern that might arise from the Fresh rule is that it tends to consume a lot of resource in MySQL.  This isn't a problem for me-- and I imagine not for most people whose Ampache supports only a few users.  If you have a lot of songs and a lot of users, processing the Fresh rule as I've implemented it might be too resource intensive.

**Comment by lachlan-00** [comment]
The official subsonic app for android supports smart playlists in a decent way.

**Comment by lachlan-00** [comment]
I've added a 'My Last Play' type of filter to search in #1544 
Some thoughts on naming/extension would be good.

**Comment by lachlan-00** [comment]
Support for smart playlists is included in the api now as a playlist. You don't have to do anything extra to support them now.

The api will also only return smart playlists that have a limit set.

Heaps of new options in develop so have at it!

**Comment by lachlan-00** [comment]
I'm treating all smart or regular lists as one list. there have also been a lot of updates to make them faster as well as indistinguishable from a regular playlist.

Reopen if you want to do more to lists but the api has come a long way in the last year.
