### ISSUE TITLE
Multiple Disks API Issue

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#1490]
* Client type:
   - API 

# Description

Currently the API `album` doesn't give any way to know what the ID of a the next Disk is.

For example the album by Eminem, Relapse: Refill contains two disks, if query Ampache for the album it returns
```

[
    {
        "album": {
            "id": "42",
            "name": "Relapse: Refill",
            "artist": {
                "id": 0,
                "name": "Various"
            },
            "year": "2009",
            "tracks": "20",
            "disk": "1",
            "tags": {
                "id": 14,
                "count": 1,
                "name": "Hip Hop"
            },
            "preciserating": 0,
            "rating": 0,
            "averagerating": null,
            "mbid": "e4c70158-a426-48f7-b96d-1238cdf3db60"
        }
    }
]
```

It notes that this is the first disk but I'd have to guess what the second disks ID is to be able to query for its songs

**Comment by lachlan-00** [comment]
the api will return a single disk per album when grouping is enabled so this is fixed now.
