### ISSUE TITLE
Missing CDATA on xml_data.class.php

### ISSUE THREAD

**Issue by antropia** [ampache/ampache#1493]
# Environment

 * Ampache version: 3.8.2
 

 * Client type:
   - Ampache

looks like ../lib/class/xml_data.class.php is used for generate xml-api output

line 484 contains:

`"\t<composer>" . $song->composer . "</composer>\n" .`
  

This leads to a xml-parsing error, if there's a composer with a '&' in the composer-name

A CDATA-escaping should fix the bug:

`"\t<composer><![CDATA[" . $song->composer . "]]></composer>\n" .`

**Comment by wagnered** [comment]
@antropia,

The problem appears to be fixed in Ampache 3.8.3-develop.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by antropia** [comment]
you're right, it's fixed.
