### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1500]
Hello!

As I mentioned in a few other issues, I've been working on packaging Ampache for Fedora. It's been a while since the last release of Ampache, and it seems there has been quite a lot of development since then. Would you be willing to make another release soon? In addition to releasing new features/bug fixes, this would also help me as the development branch of Ampache is compatible with newer versions of some of the dependencies which would be nice too.

Thanks for your consideration!

**Comment by wagnered** [comment]
@bowlofeggs ,

Sorry to take so long to respond: Short on developers with spare time. 

I am now working on  releasing 3.8.3.

**Comment by bowlofeggs** [comment]
On Thu, 2017-06-15 at 19:30 -0700, Ernest Wagner wrote:
> Sorry to take so long to respond: Short on developers with spare
> time.

I know the feeling, no complaints from me ☺

> I am now working on releasing 3.8.3.

Awesome, I look forward to it ☺
