### ISSUE TITLE
API question regarding plays

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1501]
Hi,
I've been tossing up how do do this and I'd like some feedback.

Right now if I don't play a song in Ampache I sync them up later using a python script I wrote using my last.fm data. What I'd like to do is stop using last.fm and then write a plugin for for rhythmbox to send data to my ampache server.

I assume that it's possible to write a plugin to get a catalog list and cache it locally; the part I can't see in the docs is this:
-Auth to Ampache with my user
-Song is played in rhythmbox.
-Plugin matches the song with cached Catalog.
-Plugin sends request to Ampache API to add song artist and album to the db
-Log anything that doesn't match with date of the play

The reason I'm using rhythmbox in this question is that I've written a few plugins for that and it would be easy enough. I just don't know how I would get this data into Ampache.

I could use my existing MySQL scripts and work them into a plugin but it's a bit dodgy to rely on db access.

**Comment by a7medo778** [comment]
will this is a good question actually, madsonic subsonic fork has been able to extend subsonic api, adding a few additional funtions to it
if there was a clear way to do it, i know people will add so many cool stuff as well (i forone have 4 calls being done directly to the db and would love if i can call them through the api)

**Comment by lachlan-00** [comment]
I don't mind altering the database just for me but I would like to be able to do more with song/artist/album id

**Comment by a7medo778** [comment]
@Iachlan-00 agreed, if only we learn how to extend subsonic api's
I mean imagine the possibilities of just adding a simple catalag parameter to the calls to restrict the results to a catalog
Or having a time scope for the statistics

**Comment by lachlan-00** [comment]
After taking another look at the rhythmbox plugin for Apache, its probably a better way to do things.

Used more as a data source over trying to recreate player features on top of other software

https://github.com/lotan/rhythmbox-ampache

**Comment by lachlan-00** [comment]
closing, this isn't an important issue to follow up
