### ISSUE TITLE
Graphs not working due to changes with 

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1504]
# Environment

 * Ampache version: cd761ccc3b997ee0e219c81dd6cdf2668e70f734
 * Web server + version: Apache 2.4
 * Server operating system: Debian Stretch
 * Client operating system: Debian Stretch

 * Client type:
   - Web
   - Ampache

# Settings

I don't think the Ampache settings are needed but will post them if needed

# Description

Changes to c-pchart mean that graphs are no longer being drawn and the following error is thrown in Apache error log: 

[Tue Mar 07 17:59:17.815954 2017] [:error] [pid 17854] [client 2001:470:b28c:1:21b5:b12:466a:ee12:54808] PHP Fatal error:  require_once(): Failed opening required '/var/www/ampache/lib/vendor/szymach/c-pchart/src/Classes/pData.php' (include_path='/var/www/ampache/lib/vendor/openid/php-openid:.:/usr/share/php') in /var/www/ampache/lib/class/graph.class.php on line 27, referer: https://ampache.animeshare.com/stats.php?action=show

The Classes folder is no longer there.

# Logs

2017-03-08 06:35:55 [ampache] (PHP) -> [Runtime Error] require_once(/var/www/ampache/lib/vendor/szymach/c-pchart/src/Classes/pData.php): failed to open stream: No such file or directory in file /var/www/ampache/lib/class/graph.class.php(27)

**Comment by wagnered** [comment]
@stebe,

I have a fix. .   I just need to clean it up before doing a pull request.

@afterster, 

 I was using php-7.1 for the fix,  but it should work with 5.4 also.

**Comment by wagnered** [comment]
@stebe,

Try the patch at [https://github.com/ampache/ampache/pull/1507.patch](url)

**Comment by stebe** [comment]
I'm testing the patch and the graphs are showing again. The errors are gone from the logs.  I'm using PHP 7.0.16

**Comment by stebe** [comment]
I'll wait for the patch to merge before closing.

**Comment by lachlan-00** [comment]
Graphs used a non-free library and have been removed from develop.
