### ISSUE TITLE
Sneaky way of importing playlists (Please help)

### ISSUE THREAD

**Issue by M4DM4NZ** [ampache/ampache#151]
Hey Guys :)

I'm storing my music on USB hard drives (that i love to swap around regularly)
so i have scripts in place that auto mount on bootup, then update the catalog. Therefore I'm trying to import the generated M3U file from MPD into an ampache playlist but im having trouble automating it.

I need to use the playlist.php file to import the M3U file via shell script or command-line using the php command.

can anyone suggest how to $php playlist.php "/location/to/m3u/file/" playlist/name

adding the M3U file with the web-interfaces import function works fine manually, I just want a way to automate the process.

Im running 3.6-alpha+FUTURE on xubuntu.

Sorry my PHP skills are minimal at best :/

**Comment by phirestalker** [comment]
@M4DM4NZ I know this is old, but could you tell me how you did the catalog update.inc? mine gives me these errors

`PHP Notice:  Undefined index: SERVER_NAME in /Library/Server/Web/Data/Sites/phirestalker.strangled.net/lib/init.php on line 85
PHP Notice:  Undefined index: SERVER_NAME in /Library/Server/Web/Data/Sites/phirestalker.strangled.net/lib/init.php on line 88
PHP Notice:  Undefined index: SERVER_PORT in /Library/Server/Web/Data/Sites/phirestalker.strangled.net/lib/init.php on line 88
PHP Notice:  Undefined index: SERVER_NAME in /Library/Server/Web/Data/Sites/phirestalker.strangled.net/lib/init.php on line 99`

How do I set those session variables when i am accessing the script from the command-line?
