### ISSUE TITLE
whishlist: Catalog admin api

### ISSUE THREAD

**Issue by ftoledo** [ampache/ampache#1511]
Add api to support to manage the catalog from remote client.
functions like add/remove songs, edits fields, and upload files too.

**Comment by lachlan-00** [comment]
That's a good idea! I'm working on API extension for 4.0.0

**Comment by lachlan-00** [comment]
add/clean actions added to the core branch api today.

**Comment by lachlan-00** [comment]
Develop has catalog_action method
This allows - 'add_to_catalog' and 'clean_catalog'.

I'm not sure i would add much more to this as it should be handled by the server. 
What are your thoughts?

**Comment by lachlan-00** [comment]
for the moment i'm not going to extend the catalog actions beyond kicking them off. i'd rather keep these settings inside the web interface.
