### ISSUE TITLE
Possible bug in source code (CWE-480)

### ISSUE THREAD

**Issue by AppChecker** [ampache/ampache#1514]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bug:

https://github.com/ampache/ampache/blob/cd761ccc3b997ee0e219c81dd6cdf2668e70f734/templates/show_random_albums.inc.php#L45

```
            <a href="<?php $album->link; ?>">
                <?php echo '[' . $album->f_artist . '] ' . $album->f_name; ?>
            </a>
```
$album->link has no effect. Maybe there should be echo.

Possible defect was found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by morrme** [comment]
I would like to help, with some support, if possible.
