### ISSUE TITLE
malformed xml return data for songs action

### ISSUE THREAD

**Issue by phirestalker** [ampache/ampache#1516]
# Environment

 * Installed Ampache version: cd761ccc3b997ee0e219c81dd6cdf2668e70f734.
 * Apache/2.4.25 (Unix)
 * osx 10.12.3 client and server

 * Client type:
   - Web
   - Ampache

# Settings

# Description

this line isn't right. `<total_count>6640</total_count>\n<song id="5075">`

there should be an actual newline instead of the newline special character

**Comment by lachlan-00** [comment]
Closing, just tested and fixed in 4.0.0-develop
![image](https://user-images.githubusercontent.com/1305249/59897541-72fc7700-9430-11e9-8db6-052c9cc75006.png)
