### ISSUE TITLE
How do I make episode artwork to show in ampache?

### ISSUE THREAD

**Issue by matterik** [ampache/ampache#1519]
Hello,

I am trying to get episode artworks to show. The album artwork for the mp3 files show. The episode artworks are in the id3tag v2.4 tag picture.

I have dsm synology operating system, apache2.2 server, php 5.6 and ampache 3.8.2. 

The artwork is showing in itunes and kid3 but not in ampache. But ampache somehow extracted artwork for the albums but there are no artwork for the songs/episodes. How do I make apache put artwork for each song or is that not possible ?

**Comment by wagnered** [comment]
@Matterik,

"Episodes" usually refer to video files, especially to TV shows. 
Podcast producers may refer to their mp3 files as "episodes". mp3 files
can have several APIC (picture) tags, but most users are only concerned
with album/volume covers in mp3 files. At this time, Ampache has no way
of accessing/storing more than one (the first) artwork that it finds.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug
