### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tallesairan** [ampache/ampache#1521]
is there any limit?, I need to put 480,000 and possible?

**Comment by wagnered** [comment]
It should only be limited by disk space, and the size of the playlist
that is automatically created when directly playing songs might be
limited by size of memory.


I believe I remember some contributors to this forum having over 100,000.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by tallesairan** [comment]
Thank you very much I will try in future I can even help in development with a module of type.
