### ISSUE TITLE
Looking audios on subdirectories 

### ISSUE THREAD

**Issue by uribes78** [ampache/ampache#1523]
Hi, I have a question about the Local catalog, I defined a new one but inside the structure of the audios are Year/Month/Day/filename.ogg

The "root" path of the local catalog is "/repo/g24", so an example could be:

/repo/g24/2017/04/21/1034884.ogg

But, when I want ot update the catalog to read all the audios, it is not finding the audios, I guess that happens because is not reading the subdirectories of the root path. I tried to set the "directory path" even setting an absolute path, but is not reading or finding the audios.

How can I configure to force reading the subdirectories? The subdirectories has been created like that because a call center software, I can't control that software. Hope you can help me with this.

By the way, ampache is a good software.
Thanks

# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache 2.4.6
 * Server operating system: Centos 7
 * Client operating system: Fedora 25

**Comment by stebe** [comment]
The folder, sub folders and files need to be readable by the same user or group that the web server runs under. Otherwise you need to add the web server user to the group that owns those files and folders. I believe Centos the webserver user is apache.

In my case the all the catalog folders are drwxr-xr-x and files are -rw-r--r--

**Comment by uribes78** [comment]
@stebe  your right, I didn't check that part. Checking the subdirectories permisions all of them has the owner as "root", so I guess, is necesary to change at least the group permission to apache user to be able to ready the subdirectories, am I right?

**Comment by uribes78** [comment]
I did change the owner, and when I update, I so this on the log:

2017-04-21 20:59:19 [ampache] (PHP) -> [Runtime Error] chdir(): Permission denied (errno 13) in file /var/www/html/modules/catalog/local/local.catalog.php(242) 
2017-04-21 20:59:19 [admin] (read) -> Unable to chdir to /repo/g24/2017 

Do I need to reload the Apache service to be able to read them?

**Comment by uribes78** [comment]
Well, now it's working, @stebe was right, I had to change not only the owner but also permissions, I did

`
# chown -R root:apache 2017
# chmod -R 755 2017
`
then every works fine. Thanks por helping.
