### ISSUE TITLE
Can't access API Data Methods

### ISSUE THREAD

**Issue by freemanpolys** [ampache/ampache#1524]
# Environment

 * Ampache version:  Ampache 3.8.2
 * Web server + version: Apache 2.4.7
 * Server operating system: Ubuntu 14.04.5 LTS
 * Client operating system: Postman on MAC OX

 * Client type:
   - Ampache XML-API

# Settings

config_version = 33
web_path = ""
database_hostname = "localhost"
database_port = ""
database_name = "ampache"
database_username = "ampache"
database_password = "ampache"
secret_key = "abcdefghijklmnoprqstuvwyz0123456"
session_length = 3600
stream_length = 7200
remember_length = 604800
session_name = ampache
session_cookielife = 0
session_cookiesecure = 0
auth_methods = "mysql"
access_control	= "true"
require_session = "true"
require_localnet_session = "true"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
metadata_order = "getID3,filename"
metadata_order_video = "filename,getID3"
deferred_ext_metadata = "true"
additional_genre_delimiters = "[/]{2}|[/|\\\\|\|,|;]"
catalog_file_pattern = "mp3|mpc|m4p|m4a|aac|ogg|oga|wav|aif|aiff|rm|wma|asf|flac|opus|spx|ra|ape|shn|wv"
catalog_video_pattern = "avi|mpg|mpeg|flv|m4v|mp4|webm|mkv|wmv|ogv|mov|divx|m2ts"
catalog_playlist_pattern = "m3u|m3u8|pls|asx|xspf"
catalog_prefix_pattern = "The|An|A|Die|Das|Ein|Eine|Les|Le|La"
Allow Zip Types
use_auth = "true"
default_auth_level = "guest"
ratings = "true"
userflags = "true"
directplay = "true"
sociable = "true"
licensing = "false"
art_order = "db,tags,folder,musicbrainz,lastfm,google"
lastfm_api_key = "d5df942424c71b754e54ce1832505ae2"
lastfm_api_secret = ""
wanted = "true"
wanted_types = "album,official"
channel = "true"
live_stream = "true"
refresh_limit = "60"
show_footer_statistics = "true"
debug_level = 5
log_filename = "%name.%Y%m%d.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
registration_display_fields = "fullname,website"
registration_mandatory_fields = "fullname"
transcode_player_customize = "true"
transcode_input = "-i %FILE%"
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
encode_args_webm = "-q %QUALITY% -f webm -c:v libvpx -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"
encode_srt = "-vf \"subtitles='%SRTFILE%'\""
encode_ss_frame = "-ss %TIME%"
encode_ss_duration = "-t %DURATION%"
common_abbr = "divx,xvid,dvdrip,hdtv,lol,axxo,repack,xor,pdtv,real,vtv,caph,2hd,proper,fqm,uncut,topaz,tvt,notv,fpn,fov,orenji,0tv,omicron,dsr,ws,sys,crimson,wat,hiqt,internal,brrip,boheme,vost,vostfr,fastsub,addiction,x264,LOL,720p,1080p,YIFY,evolve,fihtv,first,bokutox,bluray,tvboom,info"

# Description
I can only access handshake and ping methods from Postman.

REQUEST  : GET http://localhost:4080/server/xml.server.php?action=songs&auth=883136d171a5a683985d9e82758923b2&version=380001
RESPONSE : 
error code="401"
[CDATA[Session expired]

# Logs

**Comment by wagnered** [comment]
@freemanpolys,

Sorry to take so long to respond.  The error code indicates that the server is not getting username and/or passphrase.  Did you get this working?

**Comment by RekarBotany** [comment]
Hello i also have the same problem
i generated the API Key
but when i try 
http://localhost/ampache/server/xml.server.php?action=songs&auth=d3ab5c1dd8db853cc956c64ddbad64c7

the response is

<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<error code="401"><![CDATA[Session Expired]]></error>
</root>

**Comment by a7medo778** [comment]
yeah i keep getting session expired error when i try the XML-API as well

**Comment by wagnered** [comment]
Please upgrade to Ampache 3.8.3 and give it a try.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
@Rekar,

Please include the complete response.

Thanks...

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
@a7medo778,

What was the result of the handshake message? This should create the
session.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by RekarBotany** [comment]
@wagnered 
i get this with handshake
`<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<auth><![CDATA[0604fd4826d4100a65b04b98bc69486e]]></auth>
	<api><![CDATA[380001]]></api>
	<session_expire><![CDATA[2017-06-26T05:36:02-04:00]]></session_expire>
	<update><![CDATA[1969-12-31T19:00:00-05:00]]></update>
	<add><![CDATA[2017-06-19T20:49:22-04:00]]></add>
	<clean><![CDATA[2017-05-20T12:37:23-04:00]]></clean>
	<songs><![CDATA[20504]]></songs>
	<albums><![CDATA[2501]]></albums>
	<artists><![CDATA[601]]></artists>
	<playlists><![CDATA[5]]></playlists>
	<videos><![CDATA[0]]></videos>
	<catalogs><![CDATA[2]]></catalogs>

</root>`


but for other requests i get
`<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<error code="401"><![CDATA[Session Expired]]></error>
</root>
`

**Comment by wagnered** [comment]
@Rekar and @a7medo778

I need more information.

Please see the [Issues
Template](https://github.com/ampache/ampache/wiki/Issues) to find out
what information would be very helpful.

Thanks...


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
#Rekar, 

What is the handshake command that you are sending to Ampache?

**Comment by wagnered** [comment]
I  updated the release and might fix the DAAP API problem. The PR was offered and tested by @markuswernig.

**Comment by a7medo778** [comment]
@wagnered ok i am deploying it right now
just to clarify i should be able to get a response from the following call right
http://SERVERNAME/server/xml.server.php?action=songs&auth=API_KEY

**Comment by wagnered** [comment]
Please carefully read the [XM-API Wiki](https://github.com/ampache/ampache/wiki/XML-API). It explains what you should send in the handshake and receive as a result.  The handshake is necessary for all following requests.

**Comment by a7medo778** [comment]
here is my handshake output
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<auth><![CDATA[d24ea8a87d39e59c50851a76c3b73997]]></auth>
	<api><![CDATA[380001]]></api>
	<session_expire><![CDATA[2017-06-26T23:50:48-04:00]]></session_expire>
	<update><![CDATA[1969-12-31T19:00:00-05:00]]></update>
	<add><![CDATA[2017-06-19T20:49:22-04:00]]></add>
	<clean><![CDATA[2017-05-20T12:37:23-04:00]]></clean>
	<songs><![CDATA[20504]]></songs>
	<albums><![CDATA[2501]]></albums>
	<artists><![CDATA[601]]></artists>
	<playlists><![CDATA[5]]></playlists>
	<videos><![CDATA[0]]></videos>
	<catalogs><![CDATA[2]]></catalogs>

</root>

and here is me calling the song method right after
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<error code="401"><![CDATA[Session Expired]]></error>
</root>

**Comment by wagnered** [comment]
@RekarBotany & @a7medo778 ,

Relax, there seems to be a problem with the code.

**Comment by a7medo778** [comment]
@wagnered
Actually i might have figured it out, you need to pass the other arguments the key that you get from the handshake, but the output is looking weird so i'll do some further testing and report back

**Comment by wagnered** [comment]
I pushed some changes to the development branch that should take care of the problem.   Please install the 3.8.4-develop version ad let me know.
This fix works with the API key. There is still a problem with using the passphrase

**Comment by manuelglez86** [comment]
Hi @a7medo778 

 Im working with the api too and as far as is have used it is working well, and i think you error is this:
you are requesting songs like this as you said;
http://SERVERNAME/server/xml.server.php?action=songs&auth=API_KEY

but the API_KEY is just for Log-In you future request must ahave the auth code you received on the xml after Log-in, so using the handshake output you post before as an example your requests should be:

http://SERVERNAME/server/xml.server.php?action=songs&auth=d24ea8a87d39e59c50851a76c3b73997

hope it helps.

**Comment by a7medo778** [comment]
@manuelglez86 thanks for the answer, i figured that part out but still struggling to pull out the charts information )trending, popular...etc) since it only exist on album level with the api's but available in the gui

**Comment by manuelglez86** [comment]
sorry what do you mean with charts?? if you mean tags you can pull it out by using tag_artist, tag_albums, tag_songs

**Comment by a7medo778** [comment]
@manuelglez86 in the GUI if you go to the information tab you can see stuff like popular items (tracks, artists and albums) or top rated...etc
That information isnt available to pull throught the current api

The obly option close is "stats" method and it only does albums

**Comment by manuelglez86** [comment]
ok got it, so this is not implemented on the xml-api so you couldnt do that.

Sorry.

**Comment by a7medo778** [comment]
@manuelglez86 any tips on how to retrieve it directly from the database? (especially by time period like weekly and monthly)
i can always store it on firebase and get it from there

**Comment by manuelglez86** [comment]
i really dont know about how to retreive it from the database.

And to extend the xml api/ subsonic you can make changes on the php code and if you want later make pull request to share your changes.

**Comment by lachlan-00** [comment]
i've added api trending support in a new issue #2757

the original issue here is closed now.
