### ISSUE TITLE
[Feature Request] Libresonic backend

### ISSUE THREAD

**Issue by m-boyd** [ampache/ampache#1528]
# Environment

 * Ampache 3.8.2
 * QNAP 4.3.3.0136 Web Server
 * Android 7.1.2
 * Client type:
   - Subsonic (Audinaut 0.2.1)

# Description

A Libresonic backend would enable Libresonic clients to connect to Ampache. This is not possible with the Subsonic backend without additional client development.

**Comment by wagnered** [comment]
@m-boyd 
Added as a future enhancement.

**Comment by lachlan-00** [comment]
Closing,
Libresonic is abandoned [https://github.com/Libresonic/libresonic/issues/501]

Airsonic is the next fork which follows the subsonic api. As this fork follows the api we don't need to support additional clients.

I will be updating the subsonic backend to support token auth and at a minimum api version 1.13.
This should help with libre/airsonic connections as well. 
![image](https://user-images.githubusercontent.com/1305249/58681878-ca6b7200-83b1-11e9-95ea-0327018370db.png)
