### ISSUE TITLE
Same album name, different artists

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#153]
Having a small issue with albums with same name. They are mixed up in the library view and when I try to play album by artist1, album by artist2 comes into the playlist as well.

Both artists/albums tags are OK.

Ex :
- Think Tank by Blur
- Think Tank by Pat Martino

Cheers !

**Comment by juanalexei** [comment]
What about taking into account 'is a compilation' and 'album artist' tags?
Album artist should be taken into account for album sorting if present instead of artist tag.

albums with same name and different artists but not compilation tag should be separated.
