### ISSUE TITLE
Track number in title

### ISSUE THREAD

**Issue by smoorf** [ampache/ampache#1531]
## Environment

    Ampache version: 3.8.3
    Web server + version: Apache 2.4.18
    Server operating system: Ubuntu Linux 16.04.2
  

## Description

Hallo 
I found two problems with track numbers:
1. if I create a catalog with this pattern:  %T %t  (without hyphen)
     the track number will be part of the title (Example "02 Lovesong"
2. additional to the track number of my collection I added the CD number. 
     The syntax is:  "1-03 Lovesong.mp3"
     Ampache can't handle this. My workaround is to remove the hyphen in the vainfo.class.php
     The track number is now 103 - and that's ok and running

Michael

**Comment by lachlan-00** [comment]
what if you use other?
I use:
%o%T - %t

**Comment by smoorf** [comment]
Hi 
I tested this three option:
%o%T - %t   -  was OK with "1-02 - lovesong.mp3  -  not ok with "01 - lovesong.mp3"
%T - %t    -  was OK with "01 - lovesong.mp3"
%T %t    -  was not ok with "01 lovesong.mp3"

**Comment by smoorf** [comment]
my workaround for the "1-01 - lovesong.mp3":

vainfo.class.php
`    public static function parse_pattern($filepath, $dir_pattern, $file_pattern)
    {
        $results         = array();
        $slash_type_preg = DIRECTORY_SEPARATOR;
        if ($slash_type_preg == '\\') {
            $slash_type_preg .= DIRECTORY_SEPARATOR;
        }
        // Combine the patterns
        $pattern = preg_quote($dir_pattern) . $slash_type_preg . preg_quote($file_pattern);

        // Remove first left directories from filename to match pattern
        $cntslash = substr_count($pattern, preg_quote(DIRECTORY_SEPARATOR)) + 1;
        $filepart = explode(DIRECTORY_SEPARATOR, $filepath);
        if (count($filepart) > $cntslash) {
            $filepath = implode(DIRECTORY_SEPARATOR, array_slice($filepart, count($filepart) - $cntslash));
        }


        // Prueft auf CD Nummer und entfernt den Bindestrich
        $filepath = str_replace('^1-', '1', $filepath);
        $filepath = str_replace('^2-', '2', $filepath);
        $filepath = str_replace('^3-', '3', $filepath);
        $filepath = str_replace('^4-', '4', $filepath);




        // Pull out the pattern codes into an array
        preg_match_all('/\%\w/', $pattern, $elements);`

**Comment by smoorf** [comment]
I logged out the array field "title" inside "vainfo.class.php" after the reading of the file (debug_event).
To my surprise the title is in the right form. So the problem must be at the point where the array data will written to the database.
Can anyone tell me where this will happend. I can't find it.
@lachlan-00 did you have a look to this problem?

**Comment by smoorf** [comment]
to solve the problem with the track number in the title I add two lines to 'song.class.php':

`       $replaygain_track_peak = isset($results['replaygain_track_peak']) ?    
        $results['replaygain_track_peak'] : null;
        $replaygain_album_gain = isset($results['replaygain_album_gain']) ?     
        $results['replaygain_album_gain'] : null;
        $replaygain_album_peak = isset($results['replaygain_album_peak']) ?   
        $results['replaygain_album_peak'] : null;
        

        //remove track number 
        $title = preg_replace('/^[0-9]{2}/','', $title);
        $title = preg_replace('/^[0-9]+-[0-9]{2}/','', $title);


        $albumartist_id = null;
        if (!isset($results['albumartist_id'])) {
            if ($albumartist) {
                $albumartist_id = Artist::check($albumartist, $albumartist_mbid);`
