### ISSUE TITLE
Reflected XSS in arts.php

### ISSUE THREAD

**Issue by fenceposterror** [ampache/ampache#1532]
I found these issues auditing Ampache, some of which were found with [RIPS](https://www.ripstech.com/). If you'd like the following vulnerabilities posted somewhere else, or in a different manner, please let me know.

# Environment

 * Ampache version: 3.8.3-dev branch

# Description
A reflected cross-site scripting (XSS) vulnerability occurs when user input is embedded unsanitized into the HTML response page of the web application. It allows an attacker to inject arbitrary HTML or JavaScript code into the response page of a tampered request. Usually, this attack is performed by crafting a malicious link that is sent to a victim. When opened, the attacker's JavaScript payload within the link is reflected by the application and executed in the victim's browser in the context of the web application's domain. This enables the attacker to perform phishing attacks or to steal cookies associated with the domain.

## burl
The GET parameter `burl` is received in line 35 of arts.php is vulnerable to XSS.
The input is then passed to `show_confirmation(T_('Art Cleared'), T_('Art information has been removed from the database'), $burl);` and echoed back out unsanitized on line 28 of [show_confirmation.inc.php](https://github.com/ampache/ampache/blob/develop/templates/show_confirmation.inc.php#L28).
It is also echoed unsanitized in line 65 of [show_get_art.inc.php](https://github.com/ampache/ampache/blob/develop/templates/show_get_art.inc.php).
## object_id
The GET parameter `object_id` is received in line 28 of arts.php is vulnerable to XSS.
The input is echoed back out unsanitized on lines 24 and 63 of [show_get_art.inc.php](https://github.com/ampache/ampache/blob/develop/templates/show_get_art.inc.php).

Both `burl` and `object_id` also get returned in links that get created on the page shown. But I couldn't determine the sink.

Looks like this:
`[800x534]
                                [<a href="https://localhost/ampache/arts.php?action=select_art&image=4&object_type=album&object_id="><script>alert(1)</script>&burl=">Select</a>]`

**Comment by vollmerk** [comment]
Arg - so this isn't a super easy fix without losing functionality let me mull this over, but right now I'm in faver of killing functionality
