### ISSUE TITLE
Updating a few search bugs in song search

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1535]
Using latest develop version.

When you use advanced search it searches all users in the query.

For example if i search for 'rating' 'IS' '3 stars'. It will return tracks that any user has rated 3 stars.

I then get a list of random ratings depending on what i've rated. (I get more 5/faves or 1 star than tracks i have actually rated 3.)

Is there a way to prevent this? I like that ratings do persist over users but once i've made my own it should take precedence.

**Comment by vollmerk** [comment]
Yeah wrong number :(

**Comment by lachlan-00** [comment]
Can anyone explain what the type does in search.class.php?
$this->type != "public"

If i cut the user ID out of the type check and just add it on i get the correct ratings.
~~~
        if ($join['rating']) {
            $userid          = $GLOBALS['user']->id;
            $table['rating'] = "LEFT JOIN `rating` ON `rating`.`object_type`='song' AND ";
            if ($this->type != "public") {
                $table['rating'] .= "`rating`.`user`='$userid' AND ";
            }
            $table['rating'] .= "`rating`.`user`='$userid' AND ";
            $table['rating'] .= "`rating`.`object_id`=`song`.`id`";
        }
~~~

I was trying to make a separate "Ratings (My user only)" menu option but i wasn't able to get that working.

**Comment by lachlan-00** [comment]
So from what i understand the default option using ratings is to actually obtain an average across all users.

This is okay if you explain that but not when i want my ratings. i think i'll expand this to album and artist as well.

**Comment by lachlan-00** [comment]
I've updated #1544 to also fix an issue with searching 'Played'
It was terrible at returning the correct results before so i've cut it to a bool type of 'true_false'

**Comment by lachlan-00** [comment]
I have an issue with my pull when changing 'Played'

After a search the rule isn't kept in the list it keeps loading the results and fails to re-add the rule to the search list. :(

**Comment by lachlan-00** [comment]
Pull merged
