### ISSUE TITLE
SQL Injection in artists.php

### ISSUE THREAD

**Issue by fenceposterror** [ampache/ampache#1536]
I found this issue auditing Ampache with [RIPS](https://www.ripstech.com/) and verified it manually. If you'd like the following vulnerability posted somewhere else, or in a different manner, please let me know.

# Environment

 * Ampache version: 3.8.3-dev branch

# Description
A sql injection vulnerability occurs when user input is embedded unsanitized into a SQL query. An attacker can modify the SQL syntax and alter the query's target or result. This can lead to the retrieval of sensitive information from the database or to an attack against the underlying web server by using SQL file operations. An attacker can also elevate privileges if the SQL query is used for authentication. It is recommended to use prepared statements and to run the database user with the least privileges necessary.

The detected injection point in the SQL query occurs within single quotes. Thus, the user input can be sanitized by using the built-in function addslashes() that escapes the data and prevents breaking out of the quotes.

The GET parameter `catalog` is read and directly passed to `get_albums` on line 67 in [artists.php](https://github.com/ampache/ampache/blob/develop/artists.php#L67). In `get_albums` it is concatenated in line 266 of [artist.class.php](https://github.com/ampache/ampache/blob/develop/lib/class/artist.class.php#L266) into part of a sql statement and that string is concatenated into the final sql statement in line 290. This statement is then passed unsanitized to `Dba::read` in line 293.

**Comment by vollmerk** [comment]
Soo total Fix Failure... but it's fixed in https://github.com/ampache/ampache/commit/ee0dd9f9f94838e672dc70b70d5ce0de84c9b1d0 which referenced the wrong issue. 

Thanks for the note.
