### ISSUE TITLE
Wrong artist tags

### ISSUE THREAD

**Issue by NotGabriel** [ampache/ampache#1538]
I have been using Ampache for the last 2 months and I'm very happy with it. 
However I recently had an annoying bug, I added a few albums from the same artist, with one album which a multi-artist album. But Ampache decided that all the albums should have this multi-artist tag, instead of reading id3tag correctly. I also try to edit directly in Ampache the artist, but it do not work. Is there a solution for this issue?

**Comment by lachlan-00** [comment]
Could you show some examples/screens/files? I have had similar things before and this was worked out by editing the tags.

Sometimes the artist/album_artist tags are different enough that they can be split.

**Comment by wagnered** [comment]
As no examples have been offered, I will close this issue.
