### ISSUE TITLE
Develop Err

### ISSUE THREAD

**Issue by yi-ge** [ampache/ampache#1540]
I see it when installing beta.

Fatal error: Uncaught Error: Class 'Gettext\Translator' not found in /Users/wangyi/Project/ampache-develop/lib/i18n.php:36 Stack trace: #0 /Users/wangyi/Project/ampache-develop/test.php(66): load_gettext() #1 {main} thrown in /Users/wangyi/Project/ampache-develop/lib/i18n.php on line 36

**Comment by wagnered** [comment]
@轶哥 ("Yi brother" according to Google Translate):-)

What do you mean by "beta"?  There is only 3.8.2-release and 3.8.3-develop,

Anyway, make sure the gettext library is installed on your system. Also,
you might need the php-gettext module installed and loaded depending on
the ampache version.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
With no further replies this issue will be closed.  Please reopen it again if the problem is still unsolved.

**Comment by Cyllos42** [comment]
I have the same error trying to load ampache for the first time.

` Fatal error: Uncaught Error: Class 'Gettext\Translator' not found in /srv/http/ampache/lib/i18n.php:36 Stack trace: #0 /srv/http/ampache/test.php(66): load_gettext() #1 {main} thrown in /srv/http/ampache/lib/i18n.php on line 36`

I'm running Arch Linux with Lighttpd and php7

**Comment by yi-ge** [comment]
Thank you for your prompt reply.
