### ISSUE TITLE
how to access "information" sections by the api

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1543]
hi guys,
while subsonic api doesn't support it directly, i noticed that in the main interface under "information" section you can access stuff like Recent, Newest, Popular, Top Rated, Favorites
so i was wondering how can i retrieve them via api's ? does ampache XML api support them or which one ?

(btw, any plans to update subsonic api to 1.14 from 1.11 ?)

with regards
ahmad

**Comment by wagnered** [comment]
@a7medo778,

>while subsonic api doesn't support it directly, i noticed that in the main interface under "information" section you can access stuff like Recent, Newest, Popular, Top Rated, Favorites...

The XML API only provides access to the Ampache data. See [https://github.com/ampache/ampache/wiki/XML-API](https://github.com/ampache/ampache/wiki/XML-API)

**Comment by a7medo778** [comment]
@wagnered thanks for the reply m8, i searched the xml api before and couldnt find the methods needed to request that information
can you please guide me to them ?

you can close that bounty thread as well

**Comment by wagnered** [comment]
I think that the types in the 'stats' method might correlate with "Recent, Newest, Popular, Top Rated, Favorites"

**Comment by a7medo778** [comment]
i guys,
i opened this ticket again because after accessing the XML-API, i am still unable to access those information
your right @wagnered about the stats method, but it only returns albums as results 

meaning that i can't retrieve popular tracks, or top rated....etc
is there another way?

i am sure there is because the gui can access that information, and even more, detailed (like popular this week) and madsonic fork added all those functions

**Comment by wagnered** [comment]
What you see on the XML-API wiki is what you get.
I'll mark this as a feature request and look into it, but it might not be until the Ampache-Laravel version is released (tbd).

**Comment by a7medo778** [comment]
@wagnered ok thanks a million m8
if i could do any thing to speed things up let me know, i'll release my app with the core stuff only i guess (though charts are pretty important :( )

**Comment by a7medo778** [comment]
hey @wagnered , whats the latest updates for the laravel version? it seems to be wasteful spending time developing new features to the current ampache

**Comment by wagnered** [comment]
@a7medo778,

Not developing new features, but only fixing bugs and such for example,  Dropbox changed their API so the existing dropbox catalog module (V1) stopped working 9/30/2017 and needs to be modified for V2 of the dropbox API.

As for the laravel version, I have most of the installation procedures and user management completed.

As for joining koel, that would be up to @Afterster as he still owns Ampache.  The idea is to duplicate the feel and likeness of the old Ampache, but the challenge is unraveling the old ampache architecture to convert it to the Laravel framework: There are a lot of details to unwrap in the conversion.

**Comment by a7medo778** [comment]
Well, we have a wealth of features here, but a very limited active devs, and an old framework/code base that we have to migrate out from
Koel is super basic, and trying to add more features overtime, but have a more active dev community

I dont know but i think the best chances of keeping ampache relevant specially at this time is to have an understanding with koel since the framework migration is happening anyway
Dont get me wrong, i am against giving up any feature, and koel sucks in api support, thats why it might be a good idea

Regards
Ahmed

**Comment by a7medo778** [comment]
shameless bump for the thread as i am unable to find anything in the db to pull

**Comment by wagnered** [comment]
@a7medo778 

My apology, but at the time of this discussion (last October), I was probably struggling with getting the Dropbox catalog updated for their new API and was only half paying attention to this issue. :weary:

> shameless bump for the thread as i am unable to find anything in the db to pull

No problem: Do you mean database, or repository, and if repository, which one?  Often times I need things spelled out for me. :weary:

>  might be crazy, but why not contact the peeps of koel 

I'm sorry, but please refresh my deteriorating memory: There is no context given to the name "koel:"  So I'm at a loss to know what this is referring to. :pensive:

**Comment by a7medo778** [comment]
It's ok, forget about koel as I never thought we would make that much progress here

Right now using the regular web ui you can find the popular tracks of tracks of the day, where is that info counted and stored in the DB (so I can create a method to retrieve that info) nd try to spawn a top for the week/month as well

**Comment by wagnered** [comment]
@a7medo778 

There is no one specific table  for that stuff.  I've never had the need to look deeply into that aspect of Ampache. 

I'm guessing that much of the statistics stuff depends on the user_activity and user_flag tables and the stats class(stats.class.php).  The SQL statements are often join two or more tables.

If your server is on Linux/unix you might do a grep for those tables from the Ampache root folder; That should reveal   what logic might be using those tables and the functions in the stats class.  

Sorry I can't be of more help.

**Comment by a7medo778** [comment]
@wagnered understood,so just to clearly get this, right now there is no "charts" information that can be retrive by either the api or the data methods right ?

**Comment by wagnered** [comment]
That is correct.

**Comment by a7medo778** [comment]
hey guys, i am just shamelessly trying to bump this thread up
with all the upgrades and fixe's going on, i think is a very very important this that has been left out

currently, we cannot retrieve any of the charts or trending info that is displayed
i would go as far and request to have a local recommendation engine, but that's for later :P, for now, i would really appreciate if the XML api had something that help us retrieve that info

**Comment by lachlan-00** [comment]
I've been trying to go over all the issues I can put this in pretty easy.

**Comment by lachlan-00** [comment]
API extension is a big focus for me in this next release so the more we do now the more stable the API can be

**Comment by lachlan-00** [comment]
I'll be extending stats to include type instead of just albums now with a default fallback to album in case people have coded against it.

What's really annoying is that type shouldn't be the filter. I should be able to work around that for older API clients. but this will get done today and go into core this afternoon.

**Comment by lachlan-00** [comment]
Updated in my branch and will merge into core soon.
```
     * stats
     * MINIMUM_API_VERSION=380001
     * CHANGED_IN_API_VERSION=400001
     *
     * This get library stats for different object types.
     * When filter is null get some random items instead
     *
     * $input = array(type     = (string) 'song'|'album'|'artist'
     *                filter   = (string) 'newest'|'highest'|'frequent'|'recent'|'flagged'|null
     *                offset   = (integer) //optional
     *                limit    = (integer) //optional
     *                user_id  = (integer) //optional
     *                username = (string) DEPRECIATED 400001
     *
     * @param array $input
```

**Comment by lachlan-00** [comment]
Closing, merged into core and will be in the next official release of ampache api versino 400001
