### ISSUE TITLE
Provide Ampache binary for faster installation

### ISSUE THREAD

**Issue by arielelkin** [ampache/ampache#1545]
Currently, [the Ampache release](https://github.com/ampache/ampache/releases) is a tarball with its source code; installation requires asking Composer to download the dependencies, and [there are quite a few](https://github.com/ampache/ampache/blob/develop/composer.json). 

Full install takes 10 minutes on my machine. 

In order to reduce installation time, would it be possible to also provide a binary that's a compiled executable? 

GitHub's workflow allows for that:
https://github.com/blog/1547-release-your-software

And the binary can also be produced as a final step of CI:
https://travis-ci.org/ampache/ampache

**Comment by wagnered** [comment]
@arielelkin,

An ampache-x.x.x-all.zip is provided with each release.  This zip file contains all dependencies needed to run once it is unzipped to the document root.

PHP is an 'interpreted' language and can be considered a 'dynamic' language in which the code can change while it is being executed.  There is no binary for php as I understand.

**Comment by meandor** [comment]
a dockerfile might be usefull though
