### ISSUE TITLE
Does Ampache support Roku Streaming Protocol (RSP) ?

### ISSUE THREAD

**Issue by drder66** [ampache/ampache#1546]
I'm trying to connect a Roku Soundbridge. The DAAP notes /seem/ to imply that rsp is supported.

service
  type_rsp._tcp/type
  port 3689 /port
/service
/service-group

However the logs show that the Soundbridge gets seen but doesn't get answered:

2017-05-25 08:41:03 [ampache] (daap) -> Request headers: Array
2017-05-25 08:41:03 [ampache] (daap) -> (
2017-05-25 08:41:03 [ampache] (daap) ->     [User-Agent] => Roku SoundBridge/3.0
2017-05-25 08:41:03 [ampache] (daap) ->     [Host] => 192.168.10.2:3689
2017-05-25 08:41:03 [ampache] (daap) ->     [Accept] => */*
2017-05-25 08:41:03 [ampache] (daap) ->     [Pragma] => no-cache
2017-05-25 08:41:03 [ampache] (daap) ->     [accept-encoding] => gzip
2017-05-25 08:41:03 [ampache] (daap) ->     [accept-codecs] => wma,mpeg,wav,mp4a,alac
2017-05-25 08:41:03 [ampache] (daap) ->     [rsp-version] => 0.1
2017-05-25 08:41:03 [ampache] (daap) ->     [transcode-codecs] => wav,mp3
2017-05-25 08:41:03 [ampache] (daap) -> )

www.cxxxxxxxx.linkpc.net:3689 192.168.10.137 - - [25/May/2017:08:41:01 +0100] "GET /rsp/info HTTP/1.0" 404 342 "-" "Roku SoundBridge/3.0"

I don't seem to be able to get DAAP to work properly either - but that's another issue I think

# Environment

 * Ampache version: 3.8.2
 * Web server + version: Apache/2.4.10 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0
 * Server operating system: Debian Jesse (ARM)
 * Client operating system:

 * Client type:
   - DAAP Roku SoundBridge M1001

# Settings

;#<?php exit(); ?>##
;#########################################################
; General Config                                         #
;#########################################################

; This value is used to detect quickly
; if this config file is up to date
; this is compared against a value hard-coded
; into the init script
config_version = 33

;#########################################################
; Path Vars                                              #
;#########################################################

; The public http host of your server.
; If not set, retrieved automatically from client request.
; This setting is required for WebSocket server
; DEFAULT: ""
http_host = "cxxxxxxxxx.linkpc.net"

; The public http port of your server.
; If not set, retrieved automatically from client request.
; DEFAULT:
;http_port = 80

; The public path to your ampache install
; Do not put a trailing / on this path
; For example if your site is located at http://localhost
; than you do not need to enter anything for the web_path
; if it is located at http://localhost/music you need to
; set web_path to /music
; DEFAULT: ""
web_path = "/ampache"

; The local http url of your server.
; If not set, retrieved automatically from server information.
; DEFAULT: ""
;local_web_path = "http://localhost/ampache"

;#########################################################
; Database                                               #
;#########################################################

; Hostname of your database
; For socket authentication, set the path to socket file (e.g. /var/run/mysqld/mysqld.sock)
; DEFAULT: localhost
database_hostname = "localhost"

; Port to use when connecting to your database
; DEFAULT: none
database_port = ""

; Name of your ampache database
; DEFAULT: ampache
database_name = "ampache"

; Username for your ampache database
; DEFAULT: ""
database_username = "ampache"

; Password for your ampache database, this can not be blank
; this is a 'forced' security precaution, the default value
; will not work (except if using socket authentication)
; DEFAULT: ""
database_password = "xxxxxxxxxx"

(rest is same as default install)
# Description

# Logs

**Comment by wagnered** [comment]
@drder66,

> I don't seem to be able to get DAAP to work properly either - but that's another issue I think

Yes, but I doubt if the Ampache API  supports Roku Soundbridge.

If you want to enter an separate issue about DAAP, I'll attempt to look into the matter.
