### ISSUE TITLE
Music scan crashes on specific mp3

### ISSUE THREAD

**Issue by RedKage** [ampache/ampache#1553]
# Environment

 * Ampache version: Ampache 3.8.2
 * Web server + version: nginx 1.11.9
 * Server operating system: Gentoo x86_x64 box
 * Client operating system: Doesn't matter
 * Client type:
   - Web
   - Ampache

# Settings

See [ampache.cfg.zip](https://github.com/ampache/ampache/files/1057262/ampache.cfg.zip) attached.

# Description

Music scan crashes with a specific mp3.
This mp3 has no tag in it.
The scan is interrupted making the rest of the unscanned musics unavailable.

Reproducing the crash:
1. Put 01.mp3 ([01.zip](https://github.com/ampache/ampache/files/1057270/01.zip)) into your music folder
2. Run php catalog_update.inc -a
3. Observe crash

Related Google group discussion: [here](https://groups.google.com/forum/#!topic/ampache/zKU0E2zBLOM).

# Logs
```
----------------------------------------------------------
Starting catalog operations...
        - Adding new media to catalog/s
----------------------------------------------------------
Reading catalog: Musics
- Start adding new media -
           Starting New Media Search
Starting New Media Search on [ Musics ] catalog
Found: None
Reading:
Fatal error: Uncaught Error: [] operator not supported for strings in /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:926
Stack trace:
#0 /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1088): getid3_mp3->decodeMPEGaudioHeader(172629, Array, false)
#1 /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(172629, 173046, false)
#2 /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(172629, Array, true)
#3 /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(172629)
#4 /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /mnt/sdb1/redkage/web/ampache/lib/class/vainfo.class.php(94): getID3->analyze('/home/redkage/m...')
#6 /mnt/sdb1/redkage/web/ampache/ in /mnt/sdb1/redkage/web/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 92
```

**Comment by wagnered** [comment]
@RedKage,

Couldn't duplicate your problem with 01.mp3.

Are you trying to import a zip? Otherwise why would the debug log refer to 01.zip. The log should indicate that it is skipping any non music files.

Please try the latest develop version 2.8.3 which can be found at [https://github.com/ampache/ampache](https://github.com/ampache/ampache).

**Comment by RedKage** [comment]
Can't find the dev version 2.8.3 so I pulled dev at commit e91c786 and it insta crash when I open the home ampache url. I guess you meant the future 3.8.3 perhaps.

```
2017-06-15 14:15:33 [ampache] (autoload) -> 'Gettext\Translator' not found! 
2017-06-15 14:15:33 [ampache] (autoload) -> 'Gettext\Translator' not found! 
2017-06-15 14:15:36 [ampache] (autoload) -> 'Gettext\Translator' not found! 
2017-06-15 14:15:36 [ampache] (autoload) -> 'Gettext\Translator' not found! 
```

**Comment by Phyks** [comment]
Did you run composer? Looks like you are missing Gettext module.

**Comment by wagnered** [comment]
Sorry, a typo. Yes, I meant the latest 3.8.3-develop version and the
commit listed below seems to be the latest.

Also, check the wiki at
https://github.com/ampache/ampache/wiki/Installation to install Ampache
and composer.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by RedKage** [comment]
Ah yeah I see.
I didn't use composer for the stable version. I used the "ampache-x.x.x_all.zip" since I don't have composer. I will see if I can install it, but that's gonna be in a while: it's always quite complicated for me to install things (no root, shared environment, etc.)

**Comment by wagnered** [comment]
FYI: Composer can be downloaded into the root of your ampache
installation and run from there. It's just a php file with the .phar
extension and doesn't need to be installed system wide. You indicate a
"shared environment".  You do have your own home directory, don't you?
Composer stores its logs, etc in ~/.composer.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
ampache-3.8.3_all.zip has been released. You might give it a try first.

**Comment by RedKage** [comment]
It works.
Updated using the all package.
Put the mp3s that were crashing the scan back into my musics folder.
Scan goes okay.

I guess it was the module that was outdated.
