### ISSUE TITLE
[question] catalog access permissions

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1560]
hi guys, 
i am trying to retrieve tracks that belong to a specific catalog via the subsonic api, and since from there i can't filter the catalog (i get results from all catalogs) i was wondering about the following

when assigning a catalog/content manager role, how do I limit which catalog does he have access to?

thanks in advance

**Comment by wagnered** [comment]
@a7medo778 

At this time, Ampache does not have the capability of  assigning rules, only permission levels.

I will mark this as an enhancement for possibly adding to the new Ampache/Laravel version.

Thanks...

**Comment by a7medo778** [comment]
Yes how can i assign permission to a single catalog ?

Regards
Ahmed

**Comment by wagnered** [comment]
@ahmed,

I should have used the word "Access Level" instead of "permissions". It
can't be done in 3.8.*.

But you can try enabling share and set the level to "Catalog Manager". 
Then you create a user catalog for that user which he can then manage. 
I haven't explored this possibility but if each catalog/user has a
different file path, it might work.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by a7medo778** [comment]
thanks ernie for the reply much appreciate it
please bare with me

so i enabled the sharing and set its level to "catalog manager", now i created a new user and assigned that role to it, how can i pick which catalog? (if possible)

**Comment by Ahmed** [comment]
Wat?

**Comment by a7medo778** [comment]
@Ahmed well i am trying eventually to give the "catalog manager" access to a single catalog (or content manager)

**Comment by wagnered** [comment]
I Thought it had something to do with users uploading files and
automatically creating a catalog, But maybe I'm remembering incorrectly.

But I reiterate:  Ampache doesn't have a feature to assign catalogs to a
specific catalog manager.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by a7medo778** [comment]
ok thanks for the reply, i guess i'll try with the XML-API
