### ISSUE TITLE
Documentation: local_web_path is mandatory when using DAAP backend

### ISSUE THREAD

**Issue by markuswernig** [ampache/ampache#1562]
# Description

When setting up ampache (3.8.1) for DAAP access, following the guide at https://github.com/ampache/ampache/wiki/API#daap-api , one still ends up with a non-working environment.

Reason: If `local_web_path` is not set in `config/ampache.cfg.php`, the client code seems to use the `Host` header from the client request to find out where to connect to during `call_user_func(array('daap_api', $method), array_slice($params, $i, count($params) - $i));`.

Usually this will be something like `ampache-server:3689`, so the PHP code tries to call `http://ampache-server:3689/play/ssid/103063ce4dad5aeaeda1cde3a6d8aa6d/type/song/oid/8383/uid/-1/... etc.`
**But:** If one has followed the above guide and configured a distinct virtual host on port 3689, with document root at `SERVER_ROOT/ampache/daap`, this is not a valid path. This path is only valid on the main ampache server `SERVER_ROOT/ampache`. 

So, consequently, the call results in a 404:
<pre>127.0.0.1 - - [25/Jun/2017:17:51:03 +0200] "GET /play/ssid/fbd4eabf35b5f92f4f165f5c3ee23b9f/type/song/oid/61/uid/-1/transcode_to/mp3/player/api/name/SomeArtist%20-%20SomeSong.mp3 HTTP/1.1" 404 85
a.b.c.d - - [25/Jun/2017:17:51:03 +0200] "GET /databases/1/items/61.mp3?session-id=6 HTTP/1.1" 200 85</pre>
*Note:* In this example, `ampache-server` resolved to 127.0.1.1 on the server, so the connecting IP address (of the PHP code on the server) is 127.0.0.1. The player client's address is a.b.c.d. Both requests were seen in the log file of the DAAP virtual host. 

In a working environment there would be one request in the DAAP virtual host's logfile:
<pre>a.b.c.d - - [25/Jun/2017:20:18:39 +0200] "GET /databases/1/items/61.mp3?session-id=6 HTTP/1.1" 200 3393193</pre>
and one in the main ampache server's:
<pre>::1 - - [25/Jun/2017:20:18:39 +0200] "GET /play/ssid/71f175fd153c732b02a2d323090df1a4/type/song/oid/61/uid/-1/transcode_to/mp3/player/api/name/SomeArtist%20-%20SomeSong.mp3 HTTP/1.1" 200 3393193</pre>

The change **required** to get this working was to add the following to `config/ampache.cfg.php`:
<pre>local_web_path = "https://localhost"</pre>
(https because the main server only listens on SSL, and "localhost" only because the default vhost is serving the ampache main content).

I think this should be documented in the guide.

# Logs

**Comment by wagnered** [comment]
@markuswernig,

Thanks, for the info.

FYI:  Anybody can edit the wiki pages. You are welcome to make any
informative changes to the text.

Also, Ampache is now at release 3.8.3 with a lot of fixes and features
added.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by manuelglez86** [comment]
Hi @markuswernig 

giving a feedback to #718 i follow your 2 posts, i downloaded the ampache develop (with your correctios on daap_api.class.php) and i try local_web_path to "https://localhost" and "http://localhost"

and i get in itunes when i try to play a file of the catalog:

"this real time streaming server cant accept more conections at this time", but i got the same error if im not set local_web_path

maybe im missing something?

**Comment by markuswernig** [comment]
Hi @manuelglez86

On 07/05/2017 05:24 AM, manuelglez86 wrote:
> Hi @markuswernig 
> 
> giving a feedback to #718 i follow your 2 posts, i downloaded the ampache develop (with your correctios on daap_api.class.php) and i try local_web_path to "https://localhost" and "http://localhost"
> 

This obviously depends on what you have set as DocumentRoot in your main
apache virtual host.

If your main ampache server can be reached under "http://localhost"
(i.e. if you connect to that URI you get the ampache web interface),
then you must put that into local_web_path.
If your main ampache server is reached at "http://localhost/ampache",
then you must put that into local_web_path.

(If you have a default virtual host running that is serving from eg.
/var/www/localhost, and you have copied the ampache files into
/var/www/localhost/ampache and set up a second virtual host serving from
there as per the documentation, and have not changed the configuration
of the default vhost, then chances are that your ampache virtualhost is
not seeing any requests, but the default virtual host is replying to
anything under http://localhost/ampache, i.e. /var/www/localhost/ampache.
If you have that setup and want to keep it, you need to put
http://localhost/ampache into local_web_path.

BTW. You can easily verify which vhost is getting which requests if you
configure the default vhost and your ampache vhost and the daap vhost to
use three different log files.)

> and i get in itunes when i try to play a file of the catalog:
> 
> "this real time streaming server cant accept more conections at this time", but i got the same error if im not set local_web_path

The client I tested with was rhythmbox, not itunes, so I can't say what
this message really means, and I can't reproduce it. It could well be
another error.

I suggest that you:
- Set up different error and access log files for each of your
virtualhosts and check them for errors during the failed connection
(especially if you see any 40x or 50x HTTP error codes in there)
- Check your apache config if anything is limiting requests
- Capture the traffic with tcpdump or wireshark (the one between client
and server as well as the one between the daap vhost and the ampache
vhost, which goes over the loopback interface presumable) and see what
each vhost is responding.

Best /markus

**Comment by markuswernig** [comment]
@wagnered 
> FYI: Anybody can edit the wiki pages. You are welcome to make any informative changes to the text.

OK, added the info to the [DAAP section](/ampache/ampache/wiki/API#daap-api)

**Comment by wagnered** [comment]
@markuswernig ,

Thank You....

**Comment by manuelglez86** [comment]
hi @markuswernig 

i have done what you said

try http://localhost/programacion
try http//:192.168.0.187/programacion and i get (in both cases) on other virtualhost log  this:

127.0.1.1:3689 192.168.0.172 - - [15/Jul/2017:19:12:50 -0500] "GET http://192.168.0.187:3689/databases/1/items/3698.mp3?session-id=6 HTTP/1.1" 400 0 "-" "iTunes/12.6.1 (Windows; Microsoft Windows 7 x64

i have a virtual linux machine with ampache (192.168.0.187)

An itunes on the windows host (192.168..172)

do i missing somethin maybe??
did you do something else?

**Comment by markuswernig** [comment]
hi @manuelglez86 
I'm not sure I fully understand your setup.

You have put `"local_web_path http://localhost/programacion"` into ampache.cfg.php?
Is that the same virtual host that also hosts the ampache application at "http://192.168.0.187/programacion"? (Please check with a browser from your windows host - do you get the ampache login page?)

From which virtual host is the log entry above? It shows that the request to "http://192.168.0.187:3689/databases/1/items/3698.mp3?session-id=6" results in a 400 error code. This is an error that seems to come from the PHP application code rather than apache. Does your DAAP virtual host really serve that path? What do you get when you copy that URL into your browser on the windows host? Is there a corresponding entry in any of the apache error logs?

Maybe if you could share your apache config (for all involved virtual hosts), .htaccess files and ampache.cfg.php (sanitized), we could check if there's anything there?
