### ISSUE TITLE
[error] 3.8.3 upgrade error (Error: Your config file is out of date!)

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1563]
hi, i upgraded my install to the latest ampache (from 3.8.2 to 3.8.3), I got the ampache update.php page and update the database and everything, but now i keep getting 
"Error: Your config file is out of date! 
Generate and download new config file | Write new config file to disk"
i tried all available options, new config, restored the old, nothing worked I am still getting the same message

ampache looks fully functional though with the exception of the REST api not working
"Not Found

The requested URL /rest/getRandomSongs.view was not found on this server."

so what can i do ?

**Comment by wagnered** [comment]
@a7medo778,

The instructions in the wiki are not quite correct.  The config file for
3.8.3 is version 34, 3.8.2 is 33. meaning config switches have been
added or removed. So copying the old one back in will cause the message 
you get.

The  quick fix would be to back up config/ampache.cfg.php file and
delete the old one. Then copy config/ampache.cfg.php.dist to
config/ampache.cfg.php and transfer your previous changes from the
backed up file to the new config file.

If the second problem still exists, rewrite rules might need to be
enabled in both Ampache and the web server.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by a7medo778** [comment]
Thanks for the answer ernie
Problem 1 was solved, but still facing that api page issue
Where can i find the rewrite file to copy (i have another fully functional 3.8.2 install to copy from)
