### ISSUE TITLE
Error making a catalog

### ISSUE THREAD

**Issue by xDarkkk** [ampache/ampache#1565]
Hello!, sorry if this question is something noobish, well i just wanted to make my own streaming website which i could share with my friends, i used "Softaculous" to install ampache, and when i try to make my own catalog, it says "htdocs/data/songs" is not readable or does not exist", and i also tried "data/songs" but it doesnt work

If you wonder what was my "form" Looks like, Here is the info

**Comment by iiAriGrandeEpix** [comment]
Sorry,i pressed "Enter", but here is the info
Catalog Name: *No need right?*
Catalog Type: Local
Filename Pattern: %T - %t
Folder Pattern: %a/%A
Gather media types: Music

Path: *Here is where i put the "htdocs/data/songs*

**Comment by a7medo778** [comment]
When you chose "local" you should get an additional field to enter the path
Try a diff browser if your not seeing it

Regards
Ahmed

**Comment by iiAriGrandeEpix** [comment]
Yes i do see it, thats with the "Path" thingy i added at my second comment :)

**Comment by wagnered** [comment]
@ iiAriGrandeEpix,

Please see [Wiki](https://github.com/ampache/ampache/wiki) for answers
to many questions. A form for submitting issues can now be found there 
and provides us more information to answer questions. .

The song folder must have that same user/group permissions as that of
the web server. Assuming you're running Apache as web server, it
defaults to username:www, and group:www. If you add yourself to the same
group, log out and then in again, you should not have to use sudo to
access the song folder.

Or, you can give the song folder global R/W permissions which is not a
good idea.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by iiAriGrandeEpix** [comment]
Hello!, im not using any Linux server, or linux computer/vps, im running on a website, just pure, with a FTP and CPanel, and i just wanted to make my own Streaming Website :)

**Comment by wagnered** [comment]
@iiAriGrandeEpix ,

cPanel runs on Linux  and only Linux systems. That is about the only thing I know about cPanel, and my previous message still holds true. 

Use the information at [Ampache Wiki](https://github.com/ampache/ampache/wiki) with the information you get from the cPanel Gurus to set up your streaming website.

If  you were setting it up on your own Linux/Windows system. we could be of more help.  Also, If you fill out the Issues template from the wiki with the information you just gave me, maybe someone who uses cPanel will read it and offer help.

Sorry....

**Comment by iiAriGrandeEpix** [comment]
What i do really meant to clarify this, is how could i stream my music from my web's storage?, like lets say theres a folder name "htdocs", and basically Ampache's files is on "htdocs", and inside htdocs theres a new folder name "music" and there is where i put my songs, but if i try to put on the "Path" this: "htdocs\music", it doesnt work

**Comment by wagnered** [comment]
Ok,
Ampache requires the full path from root "/" to the music folder.  For example: `/var/www/html/music`

The default location of Apache's document root is </var/www/html>, but the system manager can put it anywhere on the system.  For Apache it is defined in /etc/httpd/conf/httpd.conf.

You might want to put the music folder in you home folder and the full path is usually:  `/home/[your username]`.  The  command `pwd` will print the full path to your home folder

**Comment by iiAriGrandeEpix** [comment]
Okay, i think i got your idea, but to again to clarify, im using a website hosting (Like 000webhost), ima try this later :) 👍

**Comment by pravynandas** [comment]
Thanks wagnered. You saved my day !! The full path did the trick !!

**Comment by lachlan-00** [comment]
closing, not an issue
