### ISSUE TITLE
az   z  z

### ISSUE THREAD

**Issue by isanniu** [ampache/ampache#1566]
# Environment

 * Ampache version:
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

# Logs

**Comment by Psy-Virus** [comment]
Yepp, I just thought the same!

Should be closed, I guess
