### ISSUE TITLE
Cannot add ANY Local Cataog Path

### ISSUE THREAD

**Issue by martinamw** [ampache/ampache#1567]
# Environment

 * Ampache version: 3.8.3-develop
 * Web server + version: Apache/2.4.7 (Ubuntu)
 * Server operating system: Ubuntu 14.04 LTS
 * Client operating system: Any

 * Client type:
   - Web
 
# Settings

# Description

Cannot add any local Catalog Path.  Web Client says "Enter a URL", and will not let me enter a local path.  It is not even sending a request to server - seems javascript is validating the path and failing.   It seems to want a windows style path - if I enter C:/ the browser will accept, but obviously not find anything.

Path: /home/me/Backup/music
Above works if I manually edit the database.

# Logs
There is nothing in the logs about this, the browser is not sending the request to the server.  Either javascript or html5 is badly trying to validate the path.

Link to screenshot: [screenshot](http://picpaste.com/pics/Screen_Shot_2017-07-04_at_16.33.37-iP3wPY6H.1499201593.png)

**Comment by Psy-Virus** [comment]
Cant reproduce it on latest develop version. Are you sure, you are running the latest version? Do you have any "ad-blocker/no-script" addons running?

**Comment by martinamw** [comment]
I see the issue now, the HTML for the Path input box is `<input type="url" name="path" value="">`

The input box expects a URL and the browser (latest OSX safari) is not allowing a non-url formatted string to be entered.

I changed the input type in a DOM editor and it accepted the path.  But i'm not sure nobody else seems to be having the same issue.

The specific version i'm using is 3.8.3-develop (178e53a82e6dd75b85aaec367cd1663422175f0d)

**Comment by wagnered** [comment]
@martinamw ,

The code for 3.8.4-develop shows input type = text for the path textbox. I don't know where or when you got the version you are using, but there have been a lot of fixes since 3.8.3-develop has been first published.

**Comment by martinamw** [comment]
Sorry it must have been an old version, it wasn't really updating when I thought it was.

the issue was pointed out before by someone else here: [https://github.com/ampache/ampache/issues/1356](https://github.com/ampache/ampache/issues/1356)

Thanks for you help.
