### ISSUE TITLE
Wish there a Snap / AppImage / Bitnami / Any Self Contained Package for Ampache Easy Install

### ISSUE THREAD

**Issue by qwertyuser1983** [ampache/ampache#1568]
# Environment

 * Ampache version: Latest
 * Web server + version: Ampache
 * Server operating system: Linux Ubuntu 16.04
 * Client operating system: Linux Ubuntu 16.04

 * Client type:
   - Ampache

# Settings

# Description

Wish there a simple all dependence contained installer for Ampache, something like Ampache-Snap. :)

# Logs

**Comment by idelsink** [comment]
If you're interested, I and several other people made a Docker container of Ampache.
<https://github.com/idelsink/ampache-docker>

**Comment by qwertyuser1983** [comment]
@idelsink , I shall try Your shortly. :)

**Comment by lachlan-00** [comment]
Ampache-docker is the solution for this. There won't be any Flatpack/snap/etc versions of Ampache other than this.

https://github.com/ampache/ampache-docker
