### ISSUE TITLE
Is subsonic engine updatable 

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1569]
Hi guys,
So subsonic is on version 6.1 (1.15.0 api) which makes us 4 releases too old

Madsonic fork has been able to keep uptodate so i wonder can ampache binaries be updated as well ? I know subsonic has gone closed sourced but iff the other fork is doing it we should be able to do t as well

On another subject, i am adding some queries directly to the db, any advice on how to extend subsonic api so we standardize it ?

**Comment by lachlan-00** [comment]
i've started updating the subsonic api in pull #1965 

Right now it's just supporting token auth with user + apikey but that's a start!
