### ISSUE TITLE
Update catalog chooses default art again

### ISSUE THREAD

**Issue by daxcurson** [ampache/ampache#1570]
# Environment

 * Ampache version:3.8.3
 * Web server + version:Apache 2.4.25
 * Server operating system:Fedora 24
 * Client operating system:Mac OS X 10.11

 * Client type:
   - Web
   - Ampache

# Settings

# Description

I choose an image of higher resolution among the art options that are displayed, but this selection is replaced by the default every time I update the catalog (via Show catalogs -> update). However, if other albums have art that has specifically been uploaded from a file, they are ignored. How can I prevent the choice I made from being overwritten by the default? Example: if I ask to change the art, for an album, the default image is 34x34. I choose the 300x300 image from the listing but after the update, the art goes back to 34x34.

Thanks!

# Logs

**Comment by wagnered** [comment]
@Agustín @Villafañe,


Did you remember to uncomment:

`;album_art_min_width = 100`

and

';album_art_min_height = 100`

in ampache.cfg.php?


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by daxcurson** [comment]
Hello, Ernest, I didn't know about that option. I'll look for it,,thanks. I'll close as resolved.
