### ISSUE TITLE
Artist Taging

### ISSUE THREAD

**Issue by rohebe** [ampache/ampache#1574]
# Environment

 * Ampache version:3.8.3-all
 * Web server + version:Apash 2.4.25
 * Server operating system: linux cpanel 64.0 (build 30) X86_64
 * Client operating system: Windows 7
 * Client type:
   - Web
   - Ampache

# Settings

# Description
I would like to know if it's someway possibel to handel traks with several artis. For the moment it create a new artistis with the name "ARTIST 1;ARTIST 2" Would be better to have the media listed separatly in ARTIST 1 and ARTIST 2. Maybe it's juste a problem in my MP3 tags.
Tks for your help
# Logs

**Comment by wagnered** [comment]
@Rob,

MP3 tags have both "album artist" and "artist" which is often displayed
as "featured artist".  If the album contains more than one featured
artist, or album artist, The problem you describe can't be avoided with
the current release of Ampache.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by mitchray** [comment]
Duplicate of #2711 

(consolidating multi-artist issues)
