### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined [device.coffee:83]

### ISSUE THREAD

**Issue by idelsink** [ampache/ampache#1576]
# Environment

 * Ampache version: 3.8.3
 * Apache2
 * Alpine Linux 3.6
 * Docker container: <https://hub.docker.com/r/idelsink/ampache/> (idelsink/ampache:latest)

This was run inside a Docker container. This way a reproduction of the affected setup is a simple pull of the container.

* Client type:
   - Web (browser/version)

# Settings
The following settings where used inside the docker container.
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/1179554/ampache.cfg.php.txt)

# Description
After configuration of ampache and adding a catalog (consisting of a few flac files), the streaming fails when setting the transcoding to "**never**".  When enabling transcoding again, everything works fine.

I'm using Chrome to access ampache and the Chrome debug console throws the follwoing message when transcoding in the streamer settings is set to "never":

```text
device.coffee:38 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at AudioDevice.destroy (device.coffee:38)
    at Player.stop (player.coffee:89)
    at a.jPlayer._aurora_resetMedia (jquery.jplayer.min.js:3)
    at a.jPlayer._resetMedia (jquery.jplayer.min.js:3)
    at a.jPlayer.setMedia (jquery.jplayer.min.js:3)
    at HTMLDivElement.<anonymous> (jquery.jplayer.min.js:2)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.a.fn.jPlayer (jquery.jplayer.min.js:2)
    at jPlayerPlaylist.select (jplayer.playlist.min.js:2)
```
When enabling transcoding again, results in a fully functional web player without any problems.

# Reproduction
I'm using a docker container to use Ampache. To reproduce my setup my docker container can be pulled down. This will recreate a new Ampache environment with the setup I tested.

The following docker command can be used to run this container:
```sh
docker run -it --name=ampache --rm -p 80:80 -p 443:443 -p 9001:9001 -p 32400:32400 idelsink/ampache:latest
```
See the docker container at <https://hub.docker.com/r/idelsink/ampache/> .
Use the docker tag `latest` to get a container running the latest release of version 3.8.3.

# Logs

## Ampache
The following log shows the streaming with transcoding enabled and then where it is set to "never".
[ampache.20170730.log.txt](https://github.com/ampache/ampache/files/1185835/ampache.20170730.log.txt)

## Chrome
The following snippet shows the debug output of my web browser used.
```text
device.coffee:38 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at AudioDevice.destroy (device.coffee:38)
    at Player.stop (player.coffee:89)
    at a.jPlayer._aurora_resetMedia (jquery.jplayer.min.js:3)
    at a.jPlayer._resetMedia (jquery.jplayer.min.js:3)
    at a.jPlayer.setMedia (jquery.jplayer.min.js:3)
    at HTMLDivElement.<anonymous> (jquery.jplayer.min.js:2)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.a.fn.jPlayer (jquery.jplayer.min.js:2)
    at jPlayerPlaylist.select (jplayer.playlist.min.js:2)
```

**Comment by wagnered** [comment]
@Ingmar,

We need more information.  The information below suggests what you can
report to us to help solve your problem.

See https://github.com/ampache/ampache/wiki/Issues for a description of
the items below. Also, the wiki describes how to set up a debug log that
might reveal more.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by idelsink** [comment]
@wagnered I've updated the issue with the missing info.

**Comment by wagnered** [comment]
@idelsink ,

I can't duplicate your problem.  Most of my files are flac and they all play without transcoding.

Have you tried a different browser (not chromium)?

Also, try playing one of the flac files directly from you web browser. For example, enter the file path into the address bar as:
    file:///media/Music/Cowboy Bebop - Original Soundtrack 1/01 - Tank!.flac

The browser should automatically create a player and play the file.

**Comment by idelsink** [comment]
Hm I tried it using a different browser (Firefox).
This was functioning as expected. It streamed the flac files just fine.

The browsers I use:
- Google Chrome Version 60.0.3112.78 (Official Build) (64-bit)
- Firefox 54.0 (64-bit)

The only thing I can think of is that Chrome has a new API for the HTML5 audio?

**Comment by idelsink** [comment]
Another small comparison test via enabling/disabling the web players:

## Chrome
```
Streaming->Authorize Flash Web Player(s): Enable
Authorize HTML5 Web Player(s): Disable
```
Result: **Does not play**

```
Streaming->Authorize Flash Web Player(s): Disable
Authorize HTML5 Web Player(s): Enable
```
Result: **Does not play**

## Firefox
```
Streaming->Authorize Flash Web Player(s): Enable
Authorize HTML5 Web Player(s): Disable
```
Result: **Does not play**

```
Streaming->Authorize Flash Web Player(s): Disable
Authorize HTML5 Web Player(s): Enable
```
Result: **Does play**

**Comment by wagnered** [comment]
I'm guessing that chrome uses coffeescript and has a bug in the code.
