### ISSUE TITLE
Export catalog to csv: missing " at the end of each line

### ISSUE THREAD

**Issue by Nicocys** [ampache/ampache#1578]
# Environment

 * Ampache version: 3.8.3
 * Web server + version: Apache 2.4.27
 * Server operating system: ArchLinux
 * Client operating system: ArchLinux

# Description

When exporting the catalog to a csv file using the export function at https://SERVER/ampache/index.php#admin/export.php, the generated csv file lacks the " character at the end of each line (for the file location strings). This leads to LibreOffice interpreting the whole file as a giant line. Easy to fix using a text editor, but it would be nice if the file was good to start with ;)

**Comment by wagnered** [comment]
@Nicocys,

    Thanks,  the fix will be in 3.8.4-debug.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
Fixed with commit 48ae878
