### ISSUE TITLE
issue with the ampache.cfg.php is writable

### ISSUE THREAD

**Issue by Hamza-Almass** [ampache/ampache#1580]
Dear All
please i have an issue with install the ampache on my server which i install on it centos7 
when i download the package ampache from the git hub (https://github.com/ampache/ampache/releases/download/3.8.3/ampache-3.8.3_all.zip)
everything it's work correctly but i face this problem when i install it from GUI 

in the below link my issue 
https://ibb.co/cniqLQ
although i give config permission 777 and also not working and you can see the error in the ampache.cfg.php
i try to fix it one week but i couldn't please can help me for fix this issue

thanks a lot
 

# Environment

 * Ampache version:
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

# Logs

**Comment by vincent456** [comment]
I have the same problem. What was the solution ?
