### ISSUE TITLE
how can i register to Ampache by using API

### ISSUE THREAD

**Issue by Hamza-Almass** [ampache/ampache#1581]
Dear All

i hope all well
please i have an question about how can i register to Ampache by using API
is the ampache have API for register user ?

thank you very much 

# Environment

 * Ampache version:
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

# Logs

**Comment by a7medo778** [comment]
hi,
http://www.subsonic.org/pages/api.jsp#createUser

**Comment by Hamza-Almass** [comment]
thank you my friend , but am using the centos 7 not subsonic , this API only for subsonic?

thank you

**Comment by a7medo778** [comment]
subsonic api is fully supported by ampache, it doesn't matter what OS are
you using as long as you have ampache installed

**Comment by Hamza-Almass** [comment]
so please why i get page **404 not found** when i make request to the following URL : http://myserver/reset/createUser?

thank you

**Comment by a7medo778** [comment]
Are you including all parameters ? U, p, app...etc

Regards
Ahmed

**Comment by Hamza-Almass** [comment]
i include parameters username , password , email ,
is this correct ? what do you mean app...etc?

**Comment by lachlan-00** [comment]
It's not currently accessible from the API, only using a subsonic client like DSUB.

I will look at adding createuser and deleteuser to the API

**Comment by lachlan-00** [comment]
I'll work on this in #1982
