### ISSUE TITLE
Consider adding support for ListenBrainz

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#1582]
Hi guys,

This is hardly a feature request since ListenBrainz is still at early development stage, but it might worth the shot to take a look at it anyway.

__What is it ?__

ListenBrainz is aiming to be an opensource scrobbler and a public store of your listen history. Some kind of FFOS last.fm implementation. More info [here](https://listenbrainz.org/goals).

__Why now?__

Just to match a [recent blog post](https://blog.musicbrainz.org/2017/07/28/listenbrainz-enters-beta-stage/) :

> If you are an author of a music player, we ask that you consider adding support for ListenBrainz in your player

__Additional links__
  * [ListenBrainz website](https://listenbrainz.org/)
  * [Github repo](https://github.com/metabrainz/listenbrainz-server)
  * [API readme](https://github.com/metabrainz/listenbrainz-server/blob/master/API_compatible_README.md)
  * [API documentation](http://listenbrainz.readthedocs.io/en/production/dev/api.html)

**Comment by wagnered** [comment]
@Jucgshu,

Thanks, Marked as an enhancement to possibly be added to the Laravel based version of Ampache.

**Comment by Jucgshu** [comment]
@wagnered,

And thanks to you for working on the next generation of Ampache ;-)

-j

**Comment by lachlan-00** [comment]
it's been added
