### ISSUE TITLE
Problems with Reverse Proxy Configuration

### ISSUE THREAD

**Issue by mbrandis** [ampache/ampache#1589]
# Environment
 * Ampache version: 3.8.3
 * Web server + version: 2.4.25-3+deb9u2 (Ampache + Reverse Proxy)
 * Server operating system: Debian 9.1 (Ampache + Reverse Proxy)
 * Client operating system: Web Browser
 * Client type: Web

# Settings
```
; Path Vars                                              #
; Tried several permutations of turning on/off these variables. web_path was always on.
http_host = "ampache.xxx.yyy"
;http_port = 443
web_path = "/ampache"
;local_web_path = "https://ampache.xxx.yyy/ampache"
```
```
# Apache configuration
<IfModule mod_proxy_http.c>
  <Proxy https://ampache.xxx.yyy/ampache>
    Require all granted
  </Proxy>

  ProxyRequests Off
  SSLProxyEngine on
  SSLProxyVerify none 
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off
  <Location /ampache>
    RequestHeader set Front-End-Https "On"

    ProxyPass https://ampache.xxx.yyy/ampache retry=0 disablereuse=On
    ProxyPassReverse https://ampache.xxx.yyy/ampache
  </Location>
</IfModule>
```

# Description

Opening this issue after discussing in #181 .

Moved an existing and working Ampache configuration to another host and use the previous host now as a reverse proxy. Ampache can be seen from the outside, but all URLs are absolute (e.g. https://ampache.xxx.yyy/ampache instead of /ampache).

Old (working) configuration: Ampache -> DSL Modem -> Internet -> Web Browser
New configuration: Ampache -> Reverse Proxy -> DSL Modem -> Internet -> Web Browser

I already tried my luck with rewriting, but no luck so far. Also after reading #181 Ampache should deliver relative URLs. 

Any help is appreciated. Thank you!

**Comment by wagnered** [comment]
@mbrandis ,

>Ampache can be seen from the outside, but all URLs are absolute

Are you saying that you get the login page but nothing else? Or that when pinging the Ampache server a response is received?

What is DOCROOT of the Ampache web server? Is the web server also Apache?

The Apache configuration indicates that SSL is enabled.  I suggest disabling it while trying to resolve the problem.  This helps remove "unknown variables" that may or may not be causing a problem.

My network is behind a router and uses NAT, so I can't duplicate your setup. So I may have more questions to get a complete understanding of your setup.

**Comment by mbrandis** [comment]
See the screenshot. This is taken from a cellphone. It looks the same from a desktop web browser.

![ampache](https://user-images.githubusercontent.com/4790494/29484260-0ced80c0-84bb-11e7-9f98-2eabcc6ef3cf.png)

DOCROOT is /var/www/html, the Ampache installation is in /usr/local/share/ampache-x.y.z which is linked to /usr/local/share/ampache. Configuration is this:

```
Alias /ampache /usr/local/share/ampache
<Directory /usr/local/share/ampache>
  Options Indexes FollowSymLinks
  AllowOverride all
  Require all granted
</Directory>
```

My setup is also behind a router and uses NAT. The mentioned xxx.yyy is a description for a home network behind a DSL router.

**Comment by wagnered** [comment]
Try setting "ProxyPreserveHost on" as described at [https://poweruphosting.com/blog/apache-reverse-proxy/](https://poweruphosting.com/blog/apache-reverse-proxy/).  As this causes the proxy server to send the original host header to the Ampache server, the relative path might not be required.

>Web server + version: 2.4.25-3+deb9u2 (Ampache + Reverse Proxy)
Server operating system: Debian 9.1 (Ampache + Reverse Proxy)
Client operating system: Web Browser

Is the reverse proxy server on the same hardware(operating system) as the Ampache web server? if so, why isn't ProxyPass using localhost(127.0.0.1) or the 192.168.x.x ip address instead of the external "https://ampache.xxx.yyy/ampache"?

Sorry I can't be of any real help on this issue.

**Comment by mbrandis** [comment]
It works now with the original installation. Sadly, I don't know why exactly since from my point of view nothing changed. Attached is the configuration which now works:

```
# Apache reverse proxy configuration
<IfModule mod_proxy_http.c>
  ProxyPreserveHost On
  SSLProxyEngine on
  SSLProxyVerify none 
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off
  <Location /ampache>
    ProxyPass        https://<INTERNALNAME>/ampache
    ProxyPassReverse https://<INTERNALNAME>/ampache
  </Location>
</IfModule>
```

```
# Snippet from Ampache configuration
;http_host = "NOTSET"
;http_port = 443
web_path = "/ampache"
;local_web_path = "NOTSET"
```

**Comment by rrolla** [comment]
If your ampache redirects to your webserver port eg:

```
https://myampacheurl:8080/login.php
```

Than you need to add to your nginx reverse proxy

```
proxy_set_header X-Forwarded-Port 443;
```
