### ISSUE TITLE
Ampache players

### ISSUE THREAD

**Issue by MasaruKato** [ampache/ampache#1595]
# Environment

Ampache version: 3.8.2
Web server + version: Apache/2.4.10
Server operating system: Debian (ARM)
Client operating system: Linux / Android
# Client type:
Web
Ampache
SubSonic
# Settings

Default

Hi, I would like to know If Ampache stores some kind of data of the players/agents somewhere. And I also would like to know If it's possible to manually delete agents (like Subsonic). Thank you for your time.

**Comment by wagnered** [comment]
@MasaruKato 

Ampache would only keep user agent data for the current session.  That  information would be a task of the web server to log. if the administrator so chooses.  Also, the client Browser probably has a history of the activity if used to play via Ampache/subsonic catalog.  Disabing the subsonic, or other catalog type in Ampache will remove the table from the database, thus removing all data. The only data that is kept is the username/password, url and id of the catalog and possibly an API key, depending on the catalog type.

**Comment by MasaruKato** [comment]
Is the concept of agent different from the one of player? Because I had some issues with Subsonic players before, and I would not like to experience them with Ampache.
