### ISSUE TITLE
Double Last.fm submission

### ISSUE THREAD

**Issue by MasaruKato** [ampache/ampache#1596]
# Environment

Ampache version: 3.8.2
Web server + version: Apache/2.4.10
Server operating system: Debian (ARM)
Client operating system: Linux / Android

# Client type:

Web
Ampache
SubSonic

# Settings

Default

I don't know why, but Ampache scrobbles the same song twice. 

![screenshot_20170827_131216](https://user-images.githubusercontent.com/29920421/29749370-e31420cc-8b29-11e7-8dcb-8e1febb2651c.png)

I tried to reinstall it, but the same issue occurs.

**Comment by stebe** [comment]
Is the Subsonic client configured to scrobble as well as the Ampache account? This will cause the double scrobbling. I usually disable scrobbling on the Subsonic client and let the Ampache account do the scrobbling in my setup.

**Comment by MasaruKato** [comment]
I'm currently using only the Ampache WebUI.

**Comment by wagnered** [comment]
@MasaruKato,

As this seems to no longer be an issue, I'll close it.  If the issue returns, it can be re-opened.
