### ISSUE TITLE
Show ID3-Art-Image per song and not per album/artist

### ISSUE THREAD

**Issue by xanthos84** [ampache/ampache#1600]
Hi everyone,

is it maybe possible to let Ampache gather the art/image from the mp3 files (for every file) instead of gather it for the complete "Album"?

So it finally saves and shows the actual art from the mp3 file instead of the first image ampache found for one album tag...

Background: I dont have traditional "albums" in my collection, instead i use the albums tag for music "labels".. so I got various artists under one album tag. but they all have different images! So I want to see the image from the specific files...

Hope you understand my question.. as english is not my motherlanguage... Thanks!

**Comment by xanthos84** [comment]
what I found so far...

Is it possible to add to the "image" table in sql some kind of "song" object_type? - at the moment only album&artist are inserted there.

And then it should be possible to call the 'song' database row to show on the player/search results?

I am nowhere near a real programmer.. just basic knowledge... so is maybe anyone able to code me that "song" insert sql for i guess the art.class.php? I would donate some money if its needed :)

**Comment by Jucgshu** [comment]
I know this is not the answer you're looking for, but I use Ampache only as a music player (e.g. *not* as a tagging tool).

Instead, I use [beets](http://beets.io/) and I'm reaaaaally happy with it.

In your usecase, you should have a look on beets [singleton mode](http://beets.readthedocs.io/en/stable/guides/tagger.html?highlight=singleton).

**Comment by xanthos84** [comment]
Thanks for your reply... but .. well I also dont use ampache as a tagging tool....

I only talk about SHOWING tags... showing the FILE/ID3/ART per file during playback and on the search results.
But to show images, I figured out that Ampache first needs them to read into the database.
And what I saw it only reads album+artist.
So I need to extend(?) the classes to read the image/art per song and write it to the database.
And then change the player+search results to show the song art/image instead of something else(usual it shows artist,album...)

So if anyone can help and want some donation for it... let me know..

**Comment by xanthos84** [comment]
so far I got it now implemented.. maybe not perfect but at least it works, it gathers image id3 tags per file and writes it to the image table.. and the players and search results are showing the song artwork prefered over the album artwork.

maybe the devs could implement some kind of official implementation for this request,...

**Comment by phynias** [comment]
why not put a pull request in with your changes ?

**Comment by a7medo778** [comment]
yes please, it would be interesting to see the results, i am going to overhaul the api commands as soon as the laravel port is done, so this will be interesting

**Comment by xanthos84** [comment]
because i am in no way a real developer :)
beside that, i made so many little or big changes to my ampache installation,
that I have no idea how I could extract that portion of implementation.
sorry :/

**Comment by Greo83** [comment]
Hi all,
first of all: I'm absolutely brand new to GitHub and PHP development, although I have experiences in other languages. And I would like to add that I really do love ampache, very great tool!

While maintaining my database I ran into the same issue that is discussed here. I tried to understand the coding and solve it by myself, but unfortunately I know arrived a point where I don't know how to proceed. 
I believe the important point is function `gather_art_item` in `catalog.class.php`. It seems that this is the central function to add images, called by several other functions. Is that correct?
When I'm right then this function is called for example after `Song::Insert`, which itself is called from a class called `catalog_worker`. Correct? But where is `catalog_worker` defined? I suppose (hope) that the reason for inserting pictures only per album can be found there.

Appreciate your help, thank you!

**Comment by Greo83** [comment]
Hi again,
meanwhile I was able to change the importing routines so that the image table now also contains images linked to the songs. Field object_type is song and object_id the id of the related song. So from the database point of view it looks fine already.

But what do I need to change to get these images displayed? I already tried changing the `show_now_playing_row.inc.php` to show function `display_art` of the song object instead of the album object. I debugged the code, in general it works and finds the correct database record. But still the album image is shown.
I also found out that the `image.php` is called with the `$_GET` parameter set to the album. I believe I need to change the calling function, but I cannot find out where it is called. Can someone help me with that?

**Comment by Greo83** [comment]
I love it when a development comes together! :-)

Finally it seems to work now. I get the song pictures showed in web player and search results and after some more research even in my mobile app for the Subsonic API. 
I will test it a little more within the next days and then try to upload my changes here.

**Comment by Greo83** [comment]
Okay, I created a pull request now: [https://github.com/ampache/ampache/pull/1845](url)
I hope I did everything correct and you like it.

**Comment by mitchray** [comment]
Fixed by #2620
