### ISSUE TITLE
Ampache won't play songs that are longer than 1 minute

### ISSUE THREAD

**Issue by itaym120** [ampache/ampache#1601]
* Ampache version: v3.8.3
 * Web server + version: iis 6
 * Server operating system:windows server 2008
 * Client operating system: windows 10 + 7

 * Client type:
   - Web
 

# Description

The web server cant play any file that is longer than a minute. No matter the format.

**Comment by lachlan-00** [comment]
I've found this happening in newer browsers.

Any firefox greater than ESR (v52) has stopped working for me. I think this is related to issues in jplayer which hasn't been updated in a few years.

**Comment by Simounet** [comment]
It might be link to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1373618) I filled in. It must be fixed on Firefox 55+.

**Comment by wagnered** [comment]
Well, @itaym120 doesn't reveal what web browser is being used. most likely IE. being a windows 10 system.

I'm using Firefox 55.0.1 on Fedora Linux and have no problem.

**Comment by itaym120** [comment]
@wagnered sorry for the very late comment.
I'm using chrome 60.0.3112.90
But i checked it also on chrome 44 and its the same :(
IE i used to install chrome once

**Comment by wagnered** [comment]
@itaym120,

As I indicated earlier, I cannot duplicate your problem, primarily because I use Linux.

How are you trying to play the songs:  through the browser webplayer  or stream to an app such as WMP?

Also, please enable the debug log in config/ampache.cfg.php to see if it might ampache problem.

Also, you might install Apache to see if it might be a problem with your IIS setup.

**Comment by itaym120** [comment]
Im playing them throw the webplayer. I tried to use it on apache2 on ubuntu server 16.04 and now the chrome 60.0.3112.90 can play files no matter their length but only mp3 and mp4  :/

**Comment by itaym120** [comment]
@wagnered

**Comment by wagnered** [comment]
Hi @itaym120,

The HTML-5 video/audio player  doesn't play all types of music. see:
[https://html5test.com/](https://html5test.com/) to test your various  browsers..

Any other types of files would have to be transcoded.

**Comment by itaym120** [comment]
I'll just transcode my music libary to the right types. And stick to the ubuntu server.
Thanks @wagnered
