### ISSUE TITLE
Need to filter illegal XML chars returned by XML api

### ISSUE THREAD

**Issue by rpridemore** [ampache/ampache#1606]
Working on parsing the XML api data from a scala project.  Traced an exception down to illegal control characters in the comment on an artist, if memory serves.  Regardless of where or how the odd chars got into my database, these need to be filtered from XML responses since there doesn't seem to be a way to configure my XML parser to be lenient.  A reference can be found [here:  https://www.w3.org/TR/xml/#charsets](https://www.w3.org/TR/xml/#charsets)

# Environment

 * Ampache version: 3.8.2
 * Web server + version: apache 2.4.25
 * Server operating system: ubuntu linux
 * Client operating system: ubuntu linux

 * Client type:
   - Web

# Settings
nothing unusual to see here

# Description
Insert chars that are not legal for XML into any table holding music metadata then query for it via the XML api.  Those chars should be stripped from the response.

# Logs
nothing unusual to see here

**Comment by wagnered** [comment]
@rpridemore,

Please give it a try with the latest release 3.8.3.  Many changes have been implemented since v3.8.2

I'm only working on existing bug fixes not features (Your issue doesn't seem to affect Ampache under normal use), I am currently the only developer who has time and most of it is used developing the Ampache/Laravel  version.

If someone wants to create a PR for this issue, they are welcome,

**Comment by a7medo778** [comment]
should we working on api's improvements or just wait for the laravel version then work on it ?

**Comment by wagnered** [comment]
@a7medo778,

Development of the Laravel version is slow as I'm responding to existing 3.8.4-develop issues and the ampache/laravel development. I can't even plan to issue a release date. APIs in the ampache/laravel framework will be the last to be implemented.

I would suggest that current issues that's causing problems with existing features be fixed first and I'm not sure how many issues involve the API: possibly any subsonic, DAAP, UPNP, etc. After that new API features for the existing 3.8.4-develop  API will be developed.

I consider @rpridemore's issue a feature, but if you consider it an important improvement, go ahead.

**Comment by wagnered** [comment]
@a7medo778 
>After that new API features for the existing 3.8.4-develop API will be developed.

I meant 
>After that new API features for the existing 3.8.4-develop API **may** be developed.

**Comment by a7medo778** [comment]
@ernest
Ok so just as i thought, hold new features dev until laravel is out
Keep up the good job m8

Regards
Ahmed

**Comment by manuelglez86** [comment]
Hi @rpridemore as @wagnered said, please try with the latest version of ampache (maybe the develop branch) and if the problem still exist point me to the exact part and i may help you as im working with the XML api too.

Thanks.

**Comment by AshotN** [comment]
There have been many updates. If this is still an issue please open a new issue.
