### ISSUE TITLE
Already played by user?

### ISSUE THREAD

**Issue by xanthos84** [ampache/ampache#1608]
Hi everyone,

is it maybe possible to have the played mark per song per user?
so you can use it in the smart playlist to filter tracks you did not already hear?

if its easy to implement, i would love to see some guides to do that.. because i guess we would need another mysql table which holds user id+song id...

thanks for anyone who thinks this is a great idea and can contribute!

**Comment by xanthos84** [comment]
i have implemtened it into my ampache myself.
the devs could think about bringing this feature into main build as i think its quite usable!
greetings

**Comment by Jucgshu** [comment]
A nice PR could help bringing this nice addition into main build I guess ;-)

**Comment by xanthos84** [comment]
PR = pull request?

well, I am no near a developer - so my code is quite unusable I guess.. it works for my cases.. but now over time it got heavily customized .. so yeah.. i think a real dev should do a good and performant implementation ;)

**Comment by Jucgshu** [comment]
Too bad. Would love to see a feature like this come into main branch ;-)
