### ISSUE TITLE
Unable to delete or hide empty album

### ISSUE THREAD

**Issue by Linuxine** [ampache/ampache#1609]
Hi, this is not really an issue, but I cannot seem to find an answer in the documentation, is there a way to delete an empty album ? I just installed Ampache, and it is really great ! But I have many standalone mp3, and Ampache has assigned them to an album with 1 title. So to avoid that, I have gathered them in a "various artists" album, but now I still see the empty album in the album list, and I have not found a way to hide or delete them ? Thanks a lot for your help !

**Comment by wagnered** [comment]
At this time, there is no way to remove a "childless"(empty) album. It
is my opinion that this should be a integrated into the clean process.
I'll mark this as a feature.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Linuxine** [comment]
Thanks for the answer, would be a nice feature indeed ! :)

**Comment by wagnered** [comment]
@Linuxine 

Took care of this while working on another problem. It' fixed in  latest commit (07bf9fd).
