### ISSUE TITLE
Creation of DB User fails

### ISSUE THREAD

**Issue by Khymick** [ampache/ampache#1618]
# Environment

    Ampache version: Ampache 3.8.3
    Web server + version: apache2 2.4.10-10+deb8u8
    Server operating system: Debian 8
    Client operating system: Different (Lin,Win,MacOS)
    MySQL: mysql-server-5.5                      5.5.54-0+deb8u1

I am trying to create a test instance of actual ampache on my web server. In order to seperate all, I want to create a own database for the test. Therefor, I copied my live db on to another db called "ampache-test". Now I want to create a db user for that copy. I copied my live user on to "ampachetest" and want to grant all options on the new database for that user. But when I do

GRANT ALL PRIVILEGES ON ampache-test.* TO 'ampachetest'@'localhost';

I keep getting the error

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-test.* TO 'ampachetest'@'localhost'' at line 1 

I know that this is not directly attached to ampache, but perhaps someone could crash my head on the mistake I´m making - I am not seeing it :(

**Comment by wagnered** [comment]
@Khymick 

The easiest way to create another ampache schema would be to rename config/ampache.cfg.php.  Thus accessing the the web site will cause the installation start: Just enter a different DB name and username/password.

Anyway, MySQL syntax require forward ticks (\`) around hyphenated schema, tables, etc:
    
    GRANT ALL PRIVILEGES ON `ampache-test`.* TO 'ampachetest'@'localhost';

You should get into the habit of using forward ticks consistently.

**Comment by Khymick** [comment]
Okay, thank you - I got it with the syntax.
What concerns your suggestion to rename ampache.cfg.php: As you said, the installer is then creating a new db for the test installtion. But I want to keep all settings (users, catalogues etc.) I have in my live installation. With your suggestion, I would have to recreate all of that, correct?

**Comment by wagnered** [comment]
@Khymick 

> With your suggestion, I would have to recreate all of that, correct?

Yes you would.

**Comment by Khymick** [comment]
Okay, thanks.
I will try to migrate existing settings then via another way (but a short remark: If the catalogue is quite big, it would be nice if I hadn´t to rebuild it).

**Comment by wagnered** [comment]
Maybe I didn't express myself clearly.  I was just saying it would be
better to do it the way you originally planned.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug
