### ISSUE TITLE
Random Album always finds multiple albums from same artist

### ISSUE THREAD

**Issue by StephenAtty** [ampache/ampache#1624]
# Environment

 * Ampache version: 3.8.4 Develop
 * Web server + version:  Apache/2.4.27
 * Server operating system: Ubuntu 14.0.4
 * Client operating system:

 * Client type:
   - Web

# Settings

[ampache.cfg.txt](https://github.com/ampache/ampache/files/1399663/ampache.cfg.txt)

# Description

Random Album always returns multiple albums from one artist - I'd expect it to return random albums from multiple artists.

# Logs

**Comment by wagnered** [comment]
@StephenAtty 

I'm running 3.8.5-develop, Random->Album selects exactly one album and displays all files from that album.
I have a small test catalog with 6 albums of different artists including the Beatles White album which has two disks.  Out of 6 random albums selected only two were the Beatles: Both disk 1 and 2 were selected only once.

I'm not well informed on statistics, but that seems a low hit rate on the same artist when two-thirds of the catalog is one artist.

If you haven't yet upgraded, I suggest that you do so.

**Comment by StephenAtty** [comment]
It looks like its fixed in 3.8.5-release which came out earlier today.

Now just got to work out the problem with Chome using the webplayer via a HTTPS proxy server.....
