### ISSUE TITLE
HTML5 Desktop Nofication Sounds

### ISSUE THREAD

**Issue by xordspar0** [ampache/ampache#1626]
# Environment

 * Ampache version: Lastest develop branch

 * Client type: Web
 * Browser: Firefox
 * Client OS: Mac

# Description

The HTML5 desktop notifications make a sound, which is kind of annoying. It seems like Chrome doesn't make a sound by default, but neither Firefox nor Chrome have configurable notification sound settings. The notifications API, however, offers an option for silent notifications: [`Notification.silent`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/silent).

I propose that either:

 1. notifications be completely silent, or
 2. a configuration option is added in Ampache to make them either noisy or silent.

It looks like this would be a simple change to the function `NotifyBrowser` in `templates/show_html5_player_headers.inc.php`. I would be happy to submit a patch for this.

**Comment by wagnered** [comment]
@xordspar0 

One question:  if the web page is right-clicked and "page-info is selected, the permissions tab allpws blocking notifications from that URL.  Do you know if that also blocks sounds?

You are welcome to submit a Pull Request (PR) per your #2 proposal.

Please remember to run `php php-cs-fixer fix` before pushing the changes to your repo 
There may be a problem with your current version of php-fixer. If it doesn't run, please download the latest version of [php-cs-fixer.phar](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.7.1/php-cs-fixer.phar) from the friendsofphp swbsite.

**Comment by xordspar0** [comment]
Note that this is on a Mac. I'm not sure if this is the same on every platform.

**Comment by xordspar0** [comment]
Alright, I'll work on PR. Thanks for the tip!
