### ISSUE TITLE
musicbrainz settings

### ISSUE THREAD

**Issue by se7enten** [ampache/ampache#1627]
I've enabled the plugin but I can't find the settings.  I've read that you need to integrate the API key but I can't find any documentation or settings, it just seems everybody has musicbrainz.org integration working some how.  What am I missing?

**Comment by wagnered** [comment]
@se7enten 

It is my understanding that credentials/API key are only needed if one is adding to the Musicbrainz database.  This is not the case for the Ampache Musicbrainz plugin.  This plugin only gathers existing data therefore should not need credentials.

But for Ampache to access Musicbrainz, it must be enabled in ampache.cfg.php:
`metadata_order = "getID3,filename, musicbrainz`
`art_order = "db,tags,folder,musicbrainz,lastfm,google"`

**Comment by wagnered** [comment]
@se7enten 

Has this issue been solved?  IF not it can be re-opened.
