### ISSUE TITLE
when http_host is not set it is not being set to what the user puts in browser

### ISSUE THREAD

**Issue by phynias** [ampache/ampache#1629]
# Environment

 * Ampache version: 3.8.3
 * Web server + version: nginx 1.12.2
 * Server operating system: freebsd
 * Client operating system: windows

 * Client type:
   - Web

# Settings

# Description

just wondering why in init.php it is setting the http_host to $_SERVER['SERVER_NAME'] instead of $_SERVER['HTTP_HOST']. in the config it says if http_host is not set than it gets the url from what the user entered in the browser. the way it is now does not do that. SERVER_NAME is gotten from whatever the web server is set to. 

lib/init.php

line: 83
```
if (empty($results['http_host'])) {
    $results['http_host'] = $_SERVER['SERVER_NAME'];
}

```
# Logs

**Comment by wagnered** [comment]
@phynias 

Sorry to take so long to get back to you

I came late to the Ampache development team, so I'm not quite sure.  But it seems that `$_SERVER['HTTP_HOST']` is not always set, but `$_SERVER['SERVER_NAME']` is, either by php or by the  web client. 

If `$_SERVER['SERVER_NAME']` is not set, the web browser will set it according to [the php documentation](http://php.net/manual/en/reserved.variables.server.php) Of course this can be spoofed. But Ampache is not meant for highly classified operations 😃  The php documentation explains how spoofing of this property can be prevented.
