### ISSUE TITLE
Feature - Spacebar to pause music playing

### ISSUE THREAD

**Issue by sylvainar** [ampache/ampache#1631]
It could be nice if the spacebar could pause music playing. I'm a heavy keyboard user and I'd like to pause the music with a quick keyboard action if someone is talking to me in the openspace, that's why I think that this feature could be useful.

**Comment by a7medo778** [comment]
That sounds like a very good feature, but i think we should hold out on new features until the migration to laravel is finished

Regards
Ahmed

**Comment by wagnered** [comment]
Closig just to get all the enhancement issues out of the way.

**Comment by GrigoriyPeters** [comment]
I assume migration to Laravel is compleTe.
Could you please tell if this feature is possible now?
Maybe it can even be enabled via config somewhere.

**Comment by lachlan-00** [comment]
p is the keyboard shortcut and media keys and MPRIS notifications are supported too.

Laravel was abandoned for continuing the pure php version.

**Comment by GrigoriyPeters** [comment]
> p is the keyboard shortcut and media keys and MPRIS notifications are supported too.
> 
> Laravel was abandoned for continuing the pure php version.

Cool! Is it possible to remap `p` to `spacebar`?

**Comment by lachlan-00** [comment]
right now you would ned to do it manually in the JS here (space is 32 i think)

![Image](https://github.com/user-attachments/assets/c9c74920-fe50-4173-81cd-f87491eb2236)

when i have more time options are easy to set in the player template here which i can do as database preferences

![Image](https://github.com/user-attachments/assets/6c3f2be1-9cb1-45ce-be24-2eab5351bf31)
