### ISSUE TITLE
Subsonic API - Browsing of library possible, playing not

### ISSUE THREAD

**Issue by simpledisaster** [ampache/ampache#1639]
# Environment

 * Ampache version: 3.8.3
 * Web server + version: Apache 2.4.29
 * Server operating system: Dietpi
 * Client operating system: iOS

 * Client type:
   - SubSonic

# Description

I set up Ampache successfully on an Apache Server. Everything works, but playing songs with a Subsonic API Client on iOS (such as AVSub or Substreamer) is dysfunctional and only shows a "loading". Browsing of the library is absolutely possible and everything is being displayed correctly.
I followed the guide of setting up the Subsonic API meticulously and a connection has been established, however as mentioned playing doesn't work.
When I tried to find a solution for this problem, I stumbled across the following help in the FAQ:

> When using an API (Ampache, Subsonic, UPnP ...) I can browse my library but playback doesn't work whereas it is working using the web interface, how to make it work?
> 
> For most API backend it is recommended to have php cUrl module installed and enabled. Otherwise few clients could failed the playback if they are excepting a specific url format.
> 
> If your server support ipv6, be careful that your webserver (eg. Apache) is listening the same way on ipv4 and ipv6. Be aware that when using cUrl with a default configuration, ipv6 will always be used by default on cUrl operations.

This seems to be the solution to my problem, however I'm completely clueless in applying the required steps. How do I set the settings in curl in order to shut off the default ipv6? Or how do I make sure Apache is listening to ipv4 as well as ipv6.
It's probably not very hard to do, but for noobs hard enough to figure out and I'm sure others would like to know as well.

I'm thankful for any help given!

**Comment by wagnered** [comment]
Changing `Listen 80` to 0.0.0.0:80 in the Apache config file should keep Apache from using ipv6.
for php cUrl type php -m in a cli and curl should be in the list.  I think that will prevent php curl from using ipv6. 

Please enable ampache debug log in ampache.cfg.php when attempting to use dsub.

I'm looking at it with Ultrasonic which should be a version of dsub.

**Comment by simpledisaster** [comment]
Thank you for your quick response, wagnered!

I did everything you said, however without any noticeable effect.
I was unable to change  `Listen 80` to `0.0.0.0:80` as my **apache config** contained the line
 `# Include list of ports to listen on`
`Include ports.conf
`

So in **ports.conf** I changed it up to

```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 0.0.0.0:80

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

The mentioned **/etc/apache2/sites-enabled/000-default.conf** looks like this. I haven't changed anything here.

```
<VirtualHost *:80>
ServerAdmin webmaster@localhost
DocumentRoot /var/www

ErrorLog /error.log
        #CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

Is there anything else we could try or is there something we overlooked?
Again, I appreciate any help and I'm very thankful for any thoughts!

**Comment by wagnered** [comment]
@simpledisaster 

See issue #974.

It refers to release 3.7.0 as working. Could you give it a try? You will probably have to recreate the  database if you do. If 3.7.0 works as indicated in the above issue, maybe I can make some comparisons with the API's.

I am having my own problems with the api.  I tried several dsub clones without success.  I get the message "The requested data was not found."  That is an actual message from the Ampache API. I can't even browse the library.

**Comment by wagnered** [comment]
Never mind about 3.7.0. I think it requires php-5.3 to work properly.  I
tried it with 5.6 and it worked better than with 7.0, but still had
problems.

Have to think of another way to solve the problem.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by simpledisaster** [comment]
I appreciate all the effort!
I haven't tried using Dsub, only substreamer and AVSub (which are constantly being updated) on iOS with above mentioned difficulties.
I can try of course to use the downgraded 3.7.0 version. However, I have been using a fresh install without any upgrades and never used SSL (in contrary to [issue #974 ](https://github.com/ampache/ampache/issues/974)) . Also for the sake of future updates, I thought it would be counter-intuitive to use 3.7.0.

> Never mind about 3.7.0. I think it requires php-5.3 to work properly.  I tried it with 5.6 and it worked better than with 7.0, but still had problems. Have to think of another way to solve the problem. 

Should I still try to set up 3.7.0?

Thank you so much for being on this case and helping, @wagnered !! I'm really unsure why I'm having these issues, as many others seem to be using the Subsonic API successfully with the latest develop. Earlier this year I had set up an Ampache Server using Apache manually, and ran into the same issues. Now I thought using the automated Dietpi config, I would eliminate possible errors and end up with a better build.

**Comment by wagnered** [comment]
If you have the time, try with the currently installed php.  The Fedora repository no longer has php-5.3 so I tried building it but have had problems building it and don't want to waste my or your time.

Right now, I'm trying to understand why I can't even browse the library with the client on Android.
Could you let me see your apache config file to see if that is my problem? Also, what version of PHP are you using?

.

**Comment by wagnered** [comment]
Instead, try 3.8.4-develop instead or wait for 3.8.4 to be released, which shouldn't be too long now. I pushed some changes to the develop branch.

I have it working with Subsonic, DSub. It worked for a while with Ultrasonic but not substreamer. For some reason, Ampache is trying to play the Ultrasonic requested music on localplay, but the mpd player isn't installed. on the server.
 
As for Substreamer, I can't remember if it worked at all before a there is no album/artist fetching and nothing is displayed.

**Comment by wagnered** [comment]
@simpledisaster 

I found the problem with Ultrasonic: I occidentally set it to jukebox mode.  When I disabled that mode, I had to restart Ultrasonic for the change to take effect.

**Comment by wagnered** [comment]
Got SubStreamer working:  Had a typo in the web server URL.

**Comment by simpledisaster** [comment]
Wow, those are fantastic news!! I am out of town now, but I will wait until 3.8.4 gets pushed and then I will keep my fingers crossed. So basically your changes in the new version made everything work? There is no other troubleshooting necessary?
Thank you again for your support!!

**Comment by wagnered** [comment]
@simpledisaster

About troubleshooting, no one ever knows for sure. It was working both
from my local network and through my ddns address.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
3.8.4 had been released.


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by arno1979** [comment]
I just upgraded to 3.8.4 and I cannot access my ampache installation using D'Sub / Subsonic API anymore. I made sure the .htaccess is present in the "play" subfolder as well as in the "rest" subfolder.
Subsonic backend is also enabled in the system settings.
If I switch back to 3.8.3 it works again.

Any idea? The logfiles show nothing suspicious as far as I can tell.

**Comment by wagnered** [comment]
@arno1979 

Ironically, on my setup, I found 3.8.4 works and 3.8.3 doesn't. Could you give some more information according to [the Issues Template](https://github.com/ampache/ampache/wiki/Issues)?

**Comment by wagnered** [comment]
@simpledisaster, @arno1979 

Try using http://x.x.x.x/rest as the DSub  server address with 3.8.4. To me, the Wiki isn't very clear on what to use as the server address but implied  that it required "/rest" to be appended.

**Comment by arno1979** [comment]
@wagnered 
I followed your hint and appended "/rest" to the server address and now it works.
This is definitely a change from 3.8.3 where the addition of "/rest" was never needed...

Thanks!

**Comment by wagnered** [comment]
@arno1979

Thanks for the info, I never used the Subsonic API before,so  I guess I
interpreted the wiki incorrectly:-(. I am now looking into find out what
changed.

regards,

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
@arno1979,

For some reason, when I restarted my Apache server, Dsub started working without the '/rest: appended. So it should now be the same as 3.8.3.

I reverted the changes and pushed another ampache-3.8.4_release.zip up to the releases page.

Sorry for the inconvenience.

**Comment by arno1979** [comment]
@wagnered 
Just checked out the new release and can confirm that the "/rest" appendix is not needed anymore.
Thanks for taking care!

**Comment by wagnered** [comment]
@simpledisaster,

Is this still a problem?  I made some major imporverments to the Subsonic API with the last few commits: Especially with the latest Ultrasonic client.

If this is still a problem, This issue can be re-opened.

**Comment by simpledisaster** [comment]
@wagnered 

So I finally had the opportunity to check the update to 3.8.4.
Locally, everything plays smoothly, but again remotely using a noip service (the connection is fine, I checked that multiple times), I can only connect to Ampache and browse through all categories, however playing is stuck on loading. I even managed to get hold of an Android device to check out Ultrasonic. Same thing is happening. Something is still not quite right yet.

Also, I'm having troubles with my log files. The access.log & error.log are being created, but are completely empty if I "tail" them (directory is writable and accessible by all users and groups).

I really don't know why my case is so hard. Would you have any thoughts, what we could check out or troubleshoot?

Thanks in advance!!

**Comment by wagnered** [comment]
Ultrasonic is not the one to try with ampache-3.8.4-release.  The latest version uses json format to transfer data.  I just fixed the last bug in Ampache's ability to respond with the json format. I will be releasing ampache-3.8.5 soon.

I know everything is ok with the Subsonic API.  last week I was at my brother's place and was able to use Dsub and Subsonic Client to access my music. at home through my oen ddns: musicbyernie.ddns.net:8090

**Comment by wagnered** [comment]
@simpledisaster 

OOPS! My heavy hands accidently pressed the wrong key and accidently sent the message with typos.

The  URL should be http://musicbyernie.ddns.net:8000.  Go ahead and try it.  The music is Creative Commons so no harm done.

I don't know if you subscribed to this issue, but here is the gist of the message I accidently sent then deleted:

>Ultrasonic is not the one to try with ampache-3.8.4-release. The latest version uses json format to transfer data. I just fixed the last bug in Ampache's ability to respond with the json format. I will be releasing ampache-3.8.5 soon.

>I know everything is ok with the Subsonic API. last week I was at my brother's place and was able to use Dsub and Subsonic Client to access my music. at home through my oen ddns\: musicbyernie.ddns.net:8090

You wrote:
>Also, I'm having troubles with my log files. The access.log & error.log are being created, but are completely empty if I "tail" them (directory is writable and accessible by all users and groups).

By "accessible" do you mean "readable"? Folders allow accessibility, files allow readability. 😄 

Anyway, I'm no expert on Apache, but if Apache is creating them when it is started, there shouldn't be a problem.  I did notice that when I manually created them, Apache "refused" to use them.  I had to delete them and restart Apache to have it create the log.

**Comment by wagnered** [comment]
Oops! again  the username/password is guest/guest

**Comment by simpledisaster** [comment]
@wagnered 

Thank you so much for your reply and the opportunity to try out a working Ampache setup :-) I just tried it out and it works beautifully with all clients (Substreamer & AVSub) that I would like to use on my setup. 

I absolutely believe you that the bugs have been fixed and the API is back to working flawlessly. I was able to check it with your setup and it worked with my own within my LAN. I'm just not getting why it doesn't work remotely on my setup, if a connection is actually established and browsing through the library is possible. Where would be the bottleneck in that case? 

"Writable and accessible" was my lack of jargon to describe chmod 777. 😄

Another question: Do these recent changes that you made affect all servers positively? (apache, nginx, lighttpd).

**Comment by wagnered** [comment]
@simpledisaster 

The changes I recently made will not affect any web server.  

Are you isolated from the internet by a router? If so, port forwarding needs to be set on the router.  As you can see, the incoming port is set to 8000. it is forwarded to 80 which my web server watches.  The router firewall ignores anything coming from the internet on port 80. 

It has to be a routing problem either with a router or server rewrite or server document root.

**Comment by wagnered** [comment]
@simpledisaster 

The subsonic API path (/rest/getAlbumList.view....)  is different from the web access (/login.php). With web access, the /index.php (in document root) is accessed behind the scene by the web server.  Not the 
index.php in /rest/getAlbumList.view...) if the document root is not set correctly.  The .htaccess in /rest is supposed to inform  Apache how to rewrite the path, but can't if Apache can't find it or Apache mod-rewrite is not enabled.

I hope I explained the the concept clearly.

**Comment by wagnered** [comment]
@simpledisaster,

@prschopf brought to my attention in issue #1642 that he had to modify the rest/.htaccess file. The changes he made are listed.

If none of my other suggestions help, please try his suggestion and see if it helps your situation? I think  his issue is because of his web server's document root setting and it might be yours.

**Comment by simpledisaster** [comment]
@wagnered

Thank you again for messaging and guiding me through the thought process. I think we might be on to something here. Somehow my remot3.it service is not available right now. I’m guessing the router at home got stuck. I will check back with the setup in 2 weeks and let you know about my results. Thanks!!

**Comment by kirby0025** [comment]
Hi, 

I'm having the same troubles as simpledisaster, and i would like to know if you finally got to fix it somehow.

For about the same time, i can browse easily through my library, but the songs are not playing. 
When I hit play on one that is not in my local cache, the player just get stuck printing 'Loading 0B' (actually "Chargement 0B", as I'm French).
Thanks to tcpdump, I see that it's really requesting the server, a huge number of packets are sending from server to client, but it's like the client doesn't really care, so i'm not sure weither it's a client or server problem.
I also tried with the server from wagnered (thanks for putting this public), and the results is the same.

Things i've tried : 
* Updating from 3.8.3 to 3.8.5
* Re-install DSub
* Try with UltraSonic, same result
* Checked my htaccess in 'rest' and 'play' folder
* Apache is listening only in ipv4
* When i request the API with my browser, file is downloading correctly

FYI : I'm using Ampache 3.8.5, Subsonic API, Apache 2.4.25 and DSub latest version as my client.
Everything works great when browsing and playing from Firefox or Vivaldi.

I can provide more feedback/do some tests if needed.

Thanks

**Comment by simpledisaster** [comment]
@kirby0025 

Hi!
Unfortunately, I'm not home much (hence also why I'm so eager on getting this thing going) and I haven't been able to fix anything yet (I will try further troubleshooting in 10 days). Have you checked out the issues from @prschopf?

**Comment by gerroon** [comment]
3.8.5  does not work for me.

I add the subsonic catalog and use http://192.168.2.116:8080 as the url and enter my creds
2018-02-06 13:11:56 [ampache] (PHP) -> [Runtime Error] opendir(http://192.168.2.116:8080/rest): failed to open dir: not implemented in file /var/www/ampache-3.8.5/lib/class/art.class.php(1310) 
2018-02-06 13:11:56 [xxxxx] (folder_art) -> Error: Unable to open http://192.168.2.116:8080/rest for album art read

I have no albums listed, and it also throws reconnection errors in the interface , not in the logs.

**Comment by wagnered** [comment]
@gerroon 

> I add the subsonic catalog and use http://192.168.2.116:8080 as the url

Do you  really mean subsonic catalog or do you mean you are trying to use the Subsonic API.

Please understand that the Subsonic catalog (remote) and Ampache's Subsonic API are not the same thing. To use the Subsonic API with a subsonic client on IOs or Android, you must create a local catalog on the Ampache server.

The Subsonic catalog is much like Dropbox: the files reside on a remote system.

**Comment by gerroon** [comment]
@wagnered 

I am sorry I posted this under wrong bug :(  

I was trying to post it under a Subsonic remote catalog

**Comment by dubwoc** [comment]
I ran into the same problem after recently upgrading ampache to 3.8.5 from a pretty old version.

After some digging I found that the subsonic Stream proxy url passed to the client looked like the following: 
(subsonic) -> Stream Proxy: https://some_url.ampache.music:80/play/ssid/ba7cc279c2973b9a0091a75738d43092/type/song/oid/32002/uid/2/client/android/noscrobble/1/player/api/name/ALURIA%20-%20Nyc-Original%20Mix-.flac

Notice the :80 afterwards, no idea where that came from but it resulted in errors like the following in the log: OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

In my config I have http_port set to 443 (turns out this has no effect either way, unsure why not). I also have force_ssl on as the ampache container I am running has a Reverse proxy inf ront of it that terminates SSL and without that on I was being redirected to http (where nothing is listening)

I haven't dug into the issue far enough to know why :80 is being added to my stream URL for songs but I did take quick shortcut to get subsonic players back up and running by adding the following to lib/class/subsonic_api.class.php:128

`$url = str_replace(':80', '', $url);
`

If I root cause the actual problem i'll circle back but posting this now to see if it resonates with anyone. *It could very well be that I have something misconfigured but this is what got me back up and running.

**Comment by wagnered** [comment]
@dubwoc ,

Did you inadvertently enable "Forces Http play regardless of port" on the Admin->Server Config->System page?  I think that might be the problem.

**Comment by dubwoc** [comment]
@wagnered Thank you for the suggestion I was not aware of that knob. When I checked via the web interface it showed that options value as disabled. Could it possibly be set some how via the config?

**Comment by wagnered** [comment]
@dubwoc 

>In my config I have http_port set to 443

Actually, if this is left commented  out, Ampache should use the port from the client request.

I don't see anywhere else in the config file or the preferences table of the database that might force http port 80.

The only other thing I see is if you forgot to uncomment the `http_port` switch, Ampache would get the port from  $_SERVER['HTTP_HOST'] which would mean that the proxy would be using 80 instead of 443.

**Comment by wagnered** [comment]
@dubwoc 

Almost forgot:

> Could it possibly be set some how via the config?

Doesn't look like it.

**Comment by wagnered** [comment]
If you are on Linux, try using wireshark to examine the URL that Ampache is actually passing to the proxy.  Maybe the problem is with the proxy.

**Comment by wagnered** [comment]
@dubwoc,

Now that I have had enough sleep, and reading up on reverse proxies, It looks like you actually have an "SSL **forward proxy**": network side **https**-> server-side **https**.  An "SSL **termination** proxy" would have network side **https** ->server side **http**, thus the word 'termination'. It seems like an actual SSL termination proxy would  suffice and may have better results with Ampache.

Anyway, I am attempting to replicate your situation. As  a middle step, I enabled  SSL on my Apache2 server.  Not exactly an SSL forwarding proxy, but it worked with several Android clients set to HTTPS.

I want to replicate your issue to step through code to try to determine where the port 80 is being introduced.

**Comment by wagnered** [comment]
@dubwoc 

I could not set up an SSL forward proxy because the proxy I set up with Apache is on the same server as localhost and of course I could not set up both sides with port 443.

BUT the SSL termination proxy setup worked beautifully.

**Comment by simpledisaster** [comment]
@wagnered Quick feedback: I had some time over Easter to set everything up from the beginning again using Dietpi on a Raspberry 2 (with the Apache webserver). Finally everything works as advertised (LAN or globally) - no extra debugging or configuring was necessary! What an Easter gift! It's purely magical once it works. Thank you again for your patience and guidance!

**Comment by acroyear** [comment]
I am still having this problem.

Ampache 3.8.6, hosted environment w/ cpanel (so there are limits to what I can change in the server config) and this is still a problem for me. The configs look correct. the htaccesses look correct. Pure HTTPS configuration (though http is available)

Problem exists http AND https, and I would prefer https (need this for a PWA).

The server is sending 200 OK with 0 content-length.

What I am finding in adding some logs is that the redirect seems to be working internally, but the redirected target is giving me a 403 Unauthorized.

requested link:
**http://subfiresuite.com/ampache/rest/stream.view?id=300000002**

Internal URL in follow_stream
**http://subfiresuite.com:80/ampache/play/ssid/<guid>/type/song/oid/2/uid/2/client/SubFireBase/noscrobble/1/player/api/name/Marillion%20-%20You-re%20Gone.mp3**

If I were to paste that internal stream url in, I get the failure 403.  I'm wondering if that is happening internally and the error handler doesn't know what to do?  I'm increasingly convinced this is the problem, because when I *break* the internal url (replace http with htxttps), I get the same behavior - a 200 with 0 content.

I also get a 403 failure if I turn off CURL entirely and just return the "fake" URL.

What might be causing the 403? I've gone through the config options on screen and turned on everything I could think of that might affect it.

**UPDATE**: ok, if I log in with my admin account, it all works, unchanged. So something about my 'normal' user is not allowed to stream for some reason. Need to go hunt down the config screens to figure it out, as I really don't want to require users to log in as admins all the time, esp with an exposed password (since ampache doesn't support the token/seed authentication).

**Comment by acroyear** [comment]
Got it.

A new user is a "Guest" until changed.

The admin screen for **Editing Server preferences** says that "url rewriting" is for Admin or User only.

By getting those two to match (upgrade user to User or downgrade the restriction of rewrite to Guest), it started working.

**Comment by darioce** [comment]
I was also facing a similar issue in my subsonic client, that I could see and browse the library but not play.

I finally found the issue in my `/var/www/ampache/config/ampache.cfg.php` file...
I had to change this
`
local_web_path = "http://localhost"
`
instead to
`
local_web_path = ""
`
(It seems that the subsonic client was trying to access the server using the local address, which is not accessible as I am using virtual hosts. Interestingly this was only done when requesting a song and not when accessing album art etc.)

I do not know why I changed this. Did not seem to affect my setup since streaming through the browser and Subsonic clients work fine now.

**Comment by zerodogg** [comment]
I'm having this issue as well. My setup is nginx (running publicly on 443, with port 80 redirecting to https) which proxies requests to an apache-server running on port 80 (in a container) that runs ampache. As has been noted earlier, ampache replies with :80 in the URL but https:// as the scheme (ie. `https://example.org:80/play/ssid/2993b6b548000a80989a20549e7558a5/type/song/oid/191775/uid/1/client/DSub/noscrobble/1/bitrate/193/player/api/name/file.mp3`), thus breaking streaming with ampache logging `(subsonic) -> Stream error: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol `. Changing `local_web_path` to the full *public* url (ie. `local_web_path = "https://example.com"`) fixed it (as did @dubwoc's hack to remove :80). Changing `http_port` did not.

**Comment by pvdputte** [comment]
Similar setup here, nginx with ssl (port 443) on a public IP, handling SSL and proxying to the backend serving apache on a private IP (port 80).
There were actually 2 problems:
- I hadn't understood this before from the discussion but apparently there's streaming going on by the subsonic api script, which of course tries to connect to the DNS name, hence the public IP on the nginx proxy. This didn't work for networking-related/firewall reasons. Solved by adding the fqdn with the private IP to the /etc/hosts file of the ampache host, so it connects directly to itself.
- It used https in the url (as evidenced in the ampache debug log) while ampache on the backend is only accessible on port 80. Solved by setting local_web_path to the "http://fqdn" instead of "https://"

**Comment by brokensbone** [comment]
I was stuck on this one too.

Brand new install, same problem as above (can browse over subsonic api, can't play). Ampache sat behind nginx ssl-terminating proxy.

I did a slight variation on @zerodogg 's suggestion and set local_web_path (which was unset) to  `local_web_path = "http://localhost:PORT"` (in my case 8080) and that sorted it. Magic,

**Comment by xekon** [comment]
> I was stuck on this one too.
> 
> Brand new install, same problem as above (can browse over subsonic api, can't play). Ampache sat behind nginx ssl-terminating proxy.
> 
> I did a slight variation on @zerodogg 's suggestion and set local_web_path (which was unset) to `local_web_path = "http://localhost:PORT"` (in my case 8080) and that sorted it. Magic,

THANK YOU!!!!

I recently switched from nginx to haproxy, with nginx i was handling the https and http /rest seperately. but with this one setting I dont need to do any of that:

`local_web_path = "http://localhost:80"`

**Comment by Canorus** [comment]
changing `local_web_path = "http://localhost/ampache"` to 
`http://mydoma.in` or 
`https://mydoma.in` or 
`http://mydoma.in:80` or 
`http://localhost` or
`http://localhost:80` 
all didn't work (accessing mydoma.in 80 port on browser redirects to 443).
URL rewrite is enabled for User (though I'm admin) and nginx is configured as [here](https://github.com/ampache/ampache/wiki/API#for-nginx-users)

Please let me know what else I can try. thanks.

**Comment by xeruf** [comment]
Just `localhost` worked for me, as did setting the server IP: https://www.reddit.com/r/ampache/comments/gxa1dw/comment/fx7r0cb/?utm_source=share&utm_medium=web2x&context=3

**Comment by TheNomad11** [comment]
> Got it.
> 
> A new user is a "Guest" until changed.
> 
> The admin screen for **Editing Server preferences** says that "url rewriting" is for Admin or User only.
> 
> By getting those two to match (upgrade user to User and downgrade the restriction of rewrite to User), it started working. I couldn't get it to work with "Guest/Guest", but that's ok for my purposes.

Wow thank you I spent many hours looking for the solution. Somewhere I read that URL rewriting has to be turned off. I had two different settings in the admin and the user section, I turmed off both and DSub started playing again. I had the error 

`(Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 403 Forbidden`
