### ISSUE TITLE
Uploads are missing

### ISSUE THREAD

**Issue by Eulafe** [ampache/ampache#1640]
Hello,

I'm trying to upload musics on my server but after the uploading (I click on blue button "Browse", select 2/3 musics) I can't find them !
It's like I uploaded... nothing !

Do you have an issue ? Is it a right problem on the server (Debian 8) ?
What should I check ?

Regards from France !

**Comment by wagnered** [comment]
Hello @Eulafe 

What version of Ampache are you using?

Did you set a catalog to save the uploaded file to?  `Uploads catalog destination` on the Admin/system page.

On the home tab, select uploads in the Information section, the uploaded albums/artists should be seen.

I'm not sure how well the drag & drop feature works, but browsing for the file  to upload will work.

**Comment by Eulafe** [comment]
Hello !

I'm using Ampache 3.8.4-develop. Does this version 'develop' allow me to upload ?
I checked catalog and it's now OK, but can't upload again.

Thank you 4 your help !

**Comment by wagnered** [comment]
@Eulafe,

After the first upload, it is necessary to got to "Admin->Show Catalogs" and "Add" again. The files are uploaded, but it is necessary to do an "Add". before they are seen.

I'm not sure if that is a problem or a feature.  :smile:

If that doesn't work, make sure the uploaded files are on the "Allowed List" and not larger than what is indicated on the upload page.

**Comment by wagnered** [comment]
For some reason, the response I made from my own computer did not show up here, so I will repeat it:

It is necessary to do a catalog->add on the catalog it was uploaded to after uploading second file.

**Comment by wagnered** [comment]
@Eulafe 

Is this still an issue?  If so, It can be reopened and I will check it out further.
