### ISSUE TITLE
Missing aditional instructions to upgrade

### ISSUE THREAD

**Issue by prschopf** [ampache/ampache#1642]
I upgraded my Ampache instalation today and I had to do 2 aditional steps to get it working.

I followed these instructions here: https://github.com/ampache/ampache/wiki/Upgrade

And I had to do these also:

- Changed all folder permissions to 755.
- Changed 2 lines below in file /mydomain.com/ampache/rest/.htaccess to:
    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/play/$1 [PT,L,QSA]

Should be good to update Ampache upgrade page to add this.

**Comment by wagnered** [comment]
@prschopf thanks for the info.

You don't indicate what http server you are using nor the version of ampache that gave you trouble; release or develop.

 For myself, using Apache, nothing needed to be done with the .htaccess file and I am a developer who needs to switch from 3.8.2 to 3.8.5-develop  sometime on an hourly basis to check for issues or when I'm working on the new Ampache/Laravel version. The only thing I need to do is change the document root in the Apache config file and restart the server.

I will monitor this in case someone else has the same issue with the new release.

**Comment by prschopf** [comment]
* Ampache version: upgrading 3.8.2 to 3.8.3 and 3.8.3 to 3.8.4 (all of them are releases)
* Web server + version: Apache 2.2.34
* Server operating system: Linux kernel 2.6.32-673.26.1.lve1.4.20.el6.x86_64

Problem in .htaccess is the root folder. In the updated version downloaded from http://ampache.org, it comes with "/", so, I had to replace it with "/ampache" (where my ampache is).

I use to upgrading Ampache using this help page: https://github.com/ampache/ampache/wiki/Upgrade

Thanks for you reply.

**Comment by wagnered** [comment]
@prschopf 

You commented:
> Changed all folder permissions to 755.

 I don't consider this an Ampache issue.  It is explained in the Apache set-instruction:  All folders need to be owned by the user/group running the Apache server.  This goes for nginx and lighttpd.

Also, In my opinion, The described upgrade instructins only work if there is no change in the database tables between upgrades.  If there is, recovery of the backed up data might or might not fail.

The laravel based version still in it's early stage of development, will use a different approach to upgrading and should have dynamic updating of DB tables and possibly functionality.

Regards....

**Comment by prschopf** [comment]
Its not an Ampache issue but an upgrading instructions page issue. I have reported it here because I dont know where to do it.

I followed these upgrade instructions and Ampache didnt work. So, I think upgrade page needs a fixing.

Instructions to upgrade are very clear. Its written:

mv ampache ampache.old
unzip ampache-X.X.X_all.zip
cp ampache.old/config/ampache.cfg.php ampache/config/

If someone does that, Ampache wont work. It needs these aditional steps which I mentioned.  If you know who is in charge of Ampache pages, please contact him/her and ask for a fixing in this specific page.

Regards,

**Comment by wagnered** [comment]
@prschopf 

This is the correct place to submit your issues and questions. 🆒
 
OK, I think I now understand.  What is in the .htaccess file is determined by what Apache2's Document root is. 

Also I have the ownership of the files that Apache2 accesses set to the owner/group of the Apache2 instance.

I have never had a problem with accessing Ampache. and never had to touch the .htaccess file whether it be an upgrade or a fresh install: although they apply the same package.

Also, Anyone who has a Github account should be able to edit the Ampache wiki pages. But if you do decide to edit a page, make sure that the edits affect everyone and not just your own situation. 😄 

I will download and double check the 4.8.4 package.

Thanks,

Ernie D

**Comment by prschopf** [comment]
Today, I updated Ampache to 3.8.5 and was not necessary to change folder's permission. But I still had to change /mydomain.com/ampache/rest/.htaccess

In original zip archive, this file contains:

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /play/$1 [PT,L,QSA]
</IfModule>

I had to change it to fit in my instalatin to this:

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/play/$1 [PT,L,QSA]
</IfModule>

So, this should be informed here: https://github.com/ampache/ampache/wiki/Upgrade

**Comment by wagnered** [comment]
@prschopf 

Thank you for your concern. Over the last several weeks, several of us have been working with Subsonic API issues which uses the /rest/index path. and none, including me, has had the same issue, or at least no one has brought it up.

In fact, I will bring up this issue with some one who still has the Subsonic API issue around external access to his network and find out if your suggestion helps that person.

Actually I think that you might have this issue because of the setting of  your web server's document root.

**Comment by prschopf** [comment]
I dont have access to my ampache settings. Im using a shared hosting.

**Comment by wagnered** [comment]
Do you mean ampache settings or Apache2 settings?   if you mean Apache2 then /rest/.htaccess most likely does need to be reconfigured. You should have access to your ampache installation via ssh or maybe cPanel.

Also, the "web_path" switch in config/ampache.cfg.php might need to be set correctly.

**Comment by prschopf** [comment]
@wagnered 

Sorry, I meant Apache2 settings.

My Ampache settings are:

web_path        = "/ampache"
session_cookiesecure = 1

Others settings are default or database configuration related.

**Comment by wagnered** [comment]
@prschopf, 

I think your web_path setting might be why you end up having to change rest/.htaccess  I leave my "web_path" switch at the default ('') and have  apache2 document root at ~/workspace/ampache instead of one folder above, which is the default doc root path for apache2.  I'm guessing that your Apache2 doc root path is also one folder above your ampache root folder.

 So there is no need for me to change the default web_patch switch.  Just drop the upgrade in and go. :smile:

**Comment by prschopf** [comment]
@wagnered 

I removed "/ampache" from web_patch and .htaccess and I couldnt access Ampache anymore.

**Comment by wagnered** [comment]
@prschopf 

But you didn't change your web server document root to compensate, did you? 😉  For example on Redhat based systems the default Apache2.4 document root is /var/www/html.  If the path for document root is set to the actual location of ampache: /var/www/html/ampache or even /var/www/ampache, the editing of the ampache.cfg.php or rest/.htaccess would not be necessary. 

Your settings work and don't need to be changed, I'm just explaining why updating of the installation/updating procedure in the wiki is not necessary . 😄 

I referenced this issue from issue  #1639  but he has a slightly different problem.  He is using a hosted server and doesn't have access to the Apache config file, so he has to modify res/.htaccess and probably config/ampache.cfg.php.

Also, the  [Ampache API wiki](https://github.com/ampache/ampache/wiki/API) indicates that:

>Default configuration is for Apache web server, you have to adapt /rest/.htaccess script for your web server if you're not using Apache

Again, the accuracy of that quote depends on the server's document root path.

**Comment by prschopf** [comment]
@wagnered 

I dont have access to Apache2 settings, Im using defaults of my host.

I have my domain hosted there and Ampache is a folder under it, like that:

~/mydomain (where my website is)
~/mydomain/ampache (where ampache is)

So, I had to change these setting to have it working. But if its a problem in my instalation, its solved, dont worry about that.

**Comment by dcrobertson01** [comment]
Hi - glad you posted this. Just upgraded to 3.8.7, and could not log into the server with android clients. Took a look at the /ampache folder/rest directory and there was no .htaccess file, just an .htaccess.dist file. 

Also - might be better to link to the ampache-all.zip file for the download so people don't download the version that needs composer - composer is fine for a development machine, but bit of a pain for an ordinary server set up. I am, for example, running ampache on a Nethserver machine, which is based on CentOS. The default system php is 5.4. I have php 7.1 running for the web server, but the system defaults to 5.4 on the command line.

Which composer does not like. nor does it like being run as root or sudo, and the apache user cannot log onto a shell, so the files need the ownership changed before composer can be run ... and it needs to be run by calling is like php71 /usr/local/bin/composer.phar etc etc ...

Just another layer of hassle for us ordinary users. Developer machines will be set up with the latest bits and pieces - but server machines are not always on the latest. Makes using stuff like composer a bit of a pita, frankly.

Anyway - worked out all the problems and then found I could have downloaded a version with all the dependencies included and would have saved a bit of hassle.

Well, that escalated quickly.

**Comment by wagnered** [comment]
@dcrobertson01   good that you got things squared away.

**BUT** there is still a rather serious DSub bug in 3.8.7 release.  Because you indicate you managed to install 3.8.7-release source, I suggest you install the latest develop version (3.8.8-develop) It has the fix for the DSub problem. I will probably release 3.88 by the end of the month though.

> The default system php is 5.4.

This version was "retired" a  long time ago.  php.net doesn't even list a changelog  for 5.4.  The earliest version listed is 5.6.23.

I run Fedora 27. It has a command called `alternatives`.  With this any number of versions of any command can be set up to be selected using `sudo alternatives --config php` for example.
