### ISSUE TITLE
Using  '$this' in static context

### ISSUE THREAD

**Issue by AppChecker** [ampache/ampache#1648]
Hi!

[method '_checkCompatibility'](https://github.com/ampache/ampache/blob/e22c4e2fcf60a65977f1862c0bf709bec343093f/modules/localplay/mpd/mpd.class.php#L991)
uses '$this' variable:
```
    private static function _checkCompatibility($cmd, $mpd_version)
    {
...
                    $this->_error(...);
...
}
```
this can lead to fatal error (using $this when not in object context ).

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by wagnered** [comment]
Thank you for the information, but this is an open-source and not-for-profit project.

**Comment by AppChecker** [comment]
@wagnered we just check some open sourse projects, if this is really a defect, what's wrong with that?:)

**Comment by wagnered** [comment]
And I thanked you for the information. No need to get defensive.
