### ISSUE TITLE
Php 7.2 support

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#1650]
Hi guys,

Tried to sync on Github today, and composer complained about ```friendsofphp/php-cs-fixer``` not being compatible with ```Php 7.2```.

```    - friendsofphp/php-cs-fixer v2.4.2 requires php ^5.6 || >=7.0 <7.2 -> your PHP version (7.2.0) does not satisfy that requirement.```

As a side comment, can't wait to try the Laravel version. I can see that @wagnered worked really hard on it. Kudos to that!

-j

**Comment by wagnered** [comment]
Hello @Jucgshu,

Please download php-cs-fixer.phar 2.90 from [Sensiolabs](http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar) and let me know if it will accept php 7.2.  If so, I will update the development version to that version.

Thanks.

**Comment by wagnered** [comment]
Never mind, php-cs-fixer ver 2.9.0 supports php 7.2. I've updated composer.json to update php-cs-fixer to that version.  php-cs-fixer can now be updated by running `composer update friendsofphp/php-cs-fixer`.
