### ISSUE TITLE
Ampache with IceS

### ISSUE THREAD

**Issue by MagicD3VIL** [ampache/ampache#1655]
I've recently installed IceS and I'm trying to make it work with Ampache. I followed your Wiki but no matter what I do it won't work. Can you please tell me how to properly set IceS config?

Every time I launch IceS everything works normal and IceS is running properly but Ampache plugin is ignored with this error: `Unknown Stream keyword: Input` so I moved it away from Stream section in the config and got an error saying: `Unknown node: Input`.

**My IceS config:**
https://pastebin.com/hyCuXib8

**My ampache.sh:**
https://pastebin.com/FeeuPKf0

_Every help is much appreciated_

**Comment by wagnered** [comment]
@MagicD3VIL 

What version of iceS? 
What version of Ampache?
What web server and its version?

I've been an Ampache developer for only a short time an am not completely familiar with Ampache funcdtioning, so it may take me awhile to investigate. Maybe someone else who is using iceS will read your request.

The first thing I see in ampache.sh is:
>AMPACHE=https://radio.clanhouse.eu/admin/

The example from the wiki shows "ampache" as the document root of the web server:
>AMPACHE=http://localhost/ampache  # Ampache server url

I guess "admin" could be your document root  depending on your web server and .htaccess settings. Normally it is "/ampache".

I need more information though. 😄 

Thanks,

**Comment by MagicD3VIL** [comment]
Thanks for reply!
IceS version is IceS2 with Lame support
Ampache version is Ampache 3.8.4-release
Apache is newest version with PHP 7.1

About that it's `/admin` is because I renamed root folder of installation to `/admin` + index of Ampache is located at `https://radio.clanhouse.eu/admin/index.php`

**Comment by wagnered** [comment]
OK, thanks for the details.

I'm not at all familiar with icecast/ices but I think I fouind a problem with the wiki.  the guide at [...ices2 HOWTO](http://www.6809.org.uk/media/ices2-howto.shtml) shows the script input function as: 

\<input>
**\<module>playlist\</module>**
    \<param name='type'>script\</param>
    \<param name="program">/etc/ices/get_random.sh\</param>
\</input>

Notice the additional line.

I have installed iceS and iceS runs without any apparent errors, only debug messages. I probably don't have it completely set up correctly because vlc doesn't see the stream.

The Ampache wiki might be for icecast 1.

Please try it with the above change to your xml file and let me know the result.

**Comment by MagicD3VIL** [comment]
Oh god... well, I just noticed that I posted old configuration file...
Although I already had your suggestion in my config so I think that's not the case :/

Right config: https://pastebin.com/tUjXDUvQ

**Comment by wagnered** [comment]
Looking at the iceS docs I see a discrepency between your config file and that described in the docs, the config should start tag <ices>.

\<ices>
	general settings
	stream section
\</ices>

Your config uses the following as a start tag:

\<Playlist>
	general settings
	stream section
\</Playlist>

And the examples that comes with the iceS source files uses </ices></ices>

Can you explain the discrepency? 😣

**Comment by MagicD3VIL** [comment]
My config goes by:
`<ices:Configuration xmlns:ices="http://www.icecast.org/projects/ices">` (same as `<ices>` but must be like this otherwise it would give you error about namespace)

I think they mean other than `Stream` settings must go above stream section (`<Stream>`) and unfortunately there must be `<playlist>` configured otherwise IceS won't start.

When I tried to put `<input>` at the top of the config I got error saying `Unknown Node: Input`

**UPDATE:** I tried to edit my config and it seems it should be working but when I try to play a song in Ampache it still does not communicate with each other. It there any specific configuration that has to be made in Ampache?
New config: https://pastebin.com/HrUSsE0n

**Comment by wagnered** [comment]
I just noticed that your version of ices is:
> IceS version is IceS2 with Lame support.

and the ices web site that:
> source client for broadcasting in MP3 format to an icecast2 server
    ices-0.4.tar.gz


Now I'm really confused.

You also wote:

>ices:Configuration xmlns:ices="http://www.icecast.org/projects/ices"> (same as <ices> but must be like this otherwise it would give you error about namespace)

What would give you an error about namespace?  The ices error log, Ampache? PHP?  None of the examples I've seen have that entry and my ices.error log as I wrote earlier gave no error messages.

I tried that url and it gave me a 404 error.  I recommend that you go to the ices web site and use the example config information described at http://www.icecast.org/ices/ to create your config file.

Meanwhile, I'll try to get the ices/ampache combo working on my system.  😃

**Comment by MagicD3VIL** [comment]
So I reinstalled IceS and I installed Icecast and ditched Shoutcast.

I can connect to server properly now with no probs and IceS is working well too

**BUT**

Plugin still does not care about what I play on Ampache (set to Stream mode) and just spamming console with:
`[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_1.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_2.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_3.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_4.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_5.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_6.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_7.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_8.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_9.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_1.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_2.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_3.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_4.ogg"
[2018-01-06  13:18:46] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_5.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_6.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_7.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_8.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_9.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_1.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_2.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_3.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_4.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_5.ogg"
[2018-01-06  13:18:47] INFO playlist-builtin/playlist_read Currently playing "/tmp/ampcache_6.ogg"`

**Comment by wagnered** [comment]
That error might be just that ices is doing a sloppy shut down.  If the error showed up before the shut-down signal, I might be more concerned.

I've been looking at the bash script that iceS runs and it looks like wget creates an empty file then tries to download it from Ampache, but gets a 404 error. so the empty file name is passed to iceS. That's why the spamming INFO messages

If I take that wget statement and run it from the command line, using the values from the script variables, it will download the complete file. So I'm trying to find out what's going on with that.

**Comment by wagnered** [comment]
OK I got it working.  At least it is according to http://192.168.2.3:8000/admin/stats.xml. ices is connected and the displayed song keeps changing.

> AMPACHE=https://radio.clanhouse.eu/admin/ 

It youir document root is the above, then i think the entry should be: https://radio.clanhouse.eu

My server's document root is at http://localhost/ampache so I changed the url entry to http://localhost in the script.

**Comment by MagicD3VIL** [comment]
I renamed folder name from `admin` to `ampache` just in case so Ampache's location is now `https://radio.clanhouse.eu/ampache`

If I'm correct, script runs a wget command and then adds /play ... behind set URL so it should be `https://radio.clanhouse.eu/ampache/play ...`. I think that I don't see no point in changing URL.

Also when I tried to run `wget https://radio.clanhouse.eu/ampache/play/?uid=-1&random=1&transcode_to=ogg` (the thing that is script doing) I got E404, did you managed to fix that?

**Comment by wagnered** [comment]
It really doesn't matter what the root folder is called.  It matters what the server document root is set to. If it is set to ampache's root folder then the URL for wget would be "https://radio.clanhouse.eu/".
If the server document root is above ampache's root folder the URL for wget would be "https://radio.clanhouse.eu/<folder name>".

The URL https://radio.clanhouse.eu/... implies it is an external URL. Which further implies that you are trying to get  the files from the internet into your local computer to use as a source for your icecast radio broadcast:. Is this correct?  

If that is the case, then it seems that https://radio.clanhouse.eu/ is not configured correctly.
If that isn't correct, then you will have to explain to me in more detail what you are trying to accomplish.

As it works on my intranet with  an address of 192.168.2.3, I don't believe there is any need to change anything.

**Comment by wagnered** [comment]
I just used wget to successfully download a file via my public url musicbyernie.ddns.net (currently 73.42.226.251).  You can try it.  The music is released as Creative Commons so perfectly legal.

**Comment by wagnered** [comment]
BTW I had to use port 8000 because my router blocks port 80 for it''s own web server. so thr URL is:
http://musicbyernie.ddns.net:8000/play/?uid=-1&random=1&transcode_to=ogg

**Comment by MagicD3VIL** [comment]
So I was off for a couple of days for personal reasons but I got back to it and when I saw .htaccess in /play folder I considered reinstalling Ampache completely.

After reinstall, I can get to my stream by `https://radio.clanhouse.eu/ampache/play/?uid=-1&random=1&transcode_to=ogg` so that's fixed and cool

My Ampache.sh is configured `AMPACHE=radio.clanhouse.eu/ampache` but I still get the same "spamming" error. Also when I try to run `wget https://radio.clanhouse.eu/ampache/play/?uid=-1&random=1&transcode_to=ogg` on local machine it connects but gets an Error 400 (Nothing to play) but when I try to open `https://radio.clanhouse.eu/ampache/play/?uid=-1&random=1&transcode_to=ogg` in Chrome on second PC music starts to play :/ 
_By the way I have my Linux network configured to take radio.clanhouse.eu as my local IP so don't try to figure that out_

It really confuses me why `wget` is not able to download the file and gets error 400 but Chrome is able to download and play the file with the same URL. I think that LAME support might be the case since all songs are in .mp3

**Comment by wagnered** [comment]
@MagicD3VIL 

>By the way I have my Linux network configured to take radio.clanhouse.eu as my local IP so don't try to figure that out

And that might be why wget doesn't work.  

I did a web search and found a possible answer at [https://superuser.com](https://superuser.com/questions/421551/difference-between-wget-and-browser-file-downloading).  Sometimes ipv6 gets in the way and the -4, (--inet4-only) switch must be added (`man wget`).

There is another suggestion about adding the `--user-agent` switch to wget to make it a[ear to be chromium(chrome).

Other than that, I believe it is a network problem, not Ampache.

**Comment by MagicD3VIL** [comment]
I tried suggested solution and unfortunately, it didn't help.

Another odd thing is when I play it as Stream in Ampache, it will download a .m3u file but when I open it nothing is actually playing. Since m3u is playlist file connecting you to streaming server and it won't play anything that may be why I get error 404 (Nothing to play) on wget

**Comment by wagnered** [comment]
You wrote:
> "Another odd thing is when I play it as Stream in Ampache, it will download a .m3u file but when I open it nothing is actually playing. Since m3u is playlist file connecting you to streaming server and it won't play anything that may be why I get error 404 (Nothing to play) on wget."

Do you mean that when you try to stream an album from the Ampache web browser, it downloads an empty .m3u file?   What does the Ampache debug log report when you do that? What is giving the 404 error:  wget?  If you are getting an empty playlist, then it might be the transcode configuration in ampache.cfg.php.

  When I try to stream an album, playlist or whatever, my  debug log reports an error and doesn't send a playlist file, but appears to create an m3u file and add information to it. I'm looking to see if it is a setting problem or true error.

**Comment by wagnered** [comment]
Fixed the stream type play with commit [9463779](https://github.com/ampache/ampache/commit/9463779e9cfe63fd3aa7234fb9499adf672e01de) pushed to the develop branch (Ampache-3.8.5-develop).

@MagicD3VIL, Thanks for bringing the streaming problem to my attention....

**Comment by MagicD3VIL** [comment]
So editing stream.php as you did should help solve my problem? :o

**Comment by wagnered** [comment]
It should fix the streaming problem, but not the iceS problem because iceS worked before the commit and continues to work.
