### ISSUE TITLE
Feature Request: XML API need to be compresed..

### ISSUE THREAD

**Issue by matiasdelellis** [ampache/ampache#1656]
# How to Reproduce
1. Intall ampache and append music
2. Just use a client with XML API.

All the XML API answers are sent as plain text with "Transfer-Encoding: chunked".
Using the query "Songs", (for example with Pragha Ampache plugin), with a large collection of 16.000 songs, 64 urls are downloaded of 250 songs each.  Approximately 420 Kb per url, gives us 26.88Mb of downloads..
Compressed files are no more than 52 KB, which would greatly reduce the size of transfers. 52Kb x 64 = 3.32MB

## Environment

 * Ampache version: v3.8.4
 * Web server + version: Apache/2.4.29
 * Server operating system: Fedora
 * Client operating system: Fedora and Debian

## php_info: report:
 * $_SERVER['HTTP_ACCEPT_ENCODING']: gzip, deflate, br

## I am not an expert, the next is a small investigation.. 😞 
The problem seem that you use 'echo' to reponses..
See: https://github.com/ampache/ampache/blob/develop/lib/class/api.class.php#L545

Since not add 'header content-size', the server has no other way to respond than 'Transfer-Encoding: chunked'. And since there is no negotiation of headers (echo directly), send it as plain text.. 😞

**Comment by wagnered** [comment]
@matiasdelellis 

I think I understand the problem, but this is a major change.  I will mark this as an enhancement for the :Next Generation" Ampache/Laravel.  It will fully implement both xml and json file transfer and echo will not be used.

Thanks for the suggestion.

**Comment by a7medo778** [comment]
hey @wagnered whats the current ETA for the laravel upgrade ? and how is it looking ?

**Comment by wagnered** [comment]
@a7medo778 

Sorry to say that an ETA doesn't exist:  Laravel is a continual "seat of the pants" learning process.  To complicate things, I also have to give a lot to time to issues on the existing version as no other developer has the time to get involved. 😢

But I am having fun. 😆
