### ISSUE TITLE
how to delete an empty album?

### ISSUE THREAD

**Issue by andrepradotf** [ampache/ampache#1660]
# Environment

 * Ampache version:
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

# Logs

**Comment by andrepradotf** [comment]
I'm using 3.8.4  Where can I do this? I didn't find. Thaks for reply and help.

**Comment by wagnered** [comment]
@andrepradotf,

On the Admin tab, select Catalogs->Show Catalogs.

On the right side, there is an Action dropdown.  Use it to select "clean" or "update" then "Go".  Do that for each catalog and all empty albums should be removed.

**Comment by lachlan-00** [comment]
Going to invalid id's will produce an error and catalog clean will clean the database as @wagnerd said above.
