### ISSUE TITLE
FR: Smart playlists as channels

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1668]
Hi

Currnetly only the regular playlist can be turned into channels. I think that it can be much nicer if the smart playlist can be run as channels as well since their contents might change on the fly making it more useful with in areas where static playlists are a bit tedious and boring.

thanks

**Comment by mitchray** [comment]
Closing as Channels are being deprecated, however you can now use Smart Playlists in Democratic Play mode 👍
