### ISSUE TITLE
Musicbrainz ID 

### ISSUE THREAD

**Issue by MasaruKato** [ampache/ampache#1669]
# Environment

Ampache version: Ampache 3.8.6-develop 
Web server + version: Apache/2.4.25 (Debian)
Server operating system: Dietpi (ARM)
Client operating system:  Linux Mint

 * Client type:
   - Web

# Description
Hi, I have some problems with the MusicBrainz plugin. I would like to retrieve the MusicBrainz Id for the Artists automatically, but it doesn't work. I've changed the order in the `ampache.cfg.php` file like so 
`metadata_order = "MusicBrainz,getID3,filename"` but it doesn't work anyway.
 
Other than that, whenever I try to use the Headphones plugin (For album of suggested artists, I've tried to insert manually the MusicBrainz ID of some artists in my library and the plugin works correctly. The log reports `2018-02-08 15:30:09 [user] (wanted) -> Using Wanted Process plugin: Headphones
2018-02-08 15:30:09 [user] (Headphones) -> Artist `` doesn't have MusicBrainz Id. Skipped`

**Comment by wagnered** [comment]
@MasaruKato 

Sorry...

Looking at the code, Ampache doesn't grab the MBID, It just uses it to get album information, mostly artwork. The MBID must already be in the album's tag info.

I will mark this as a possible enhancement for the next generation (NG) of ampache based on the Laravel framework.

A utility like **Musicbrainz Picard** for Linux, at this time, is required to populate the tags with the various MusicBrainz id's for Ampache's use.  It seems to be a mass processor as I just matched 5 different artist subdirectories at the same  time.

**Comment by MasaruKato** [comment]
@wagnered 

So there is no way to download an album from the "Similar Artists" section with the Headphones plugin?

**Comment by wagnered** [comment]
@MasaruKato 

I don't know anything abut Headphones except what I see in the Ampache Headphones plugin code:  Same situation.  The headphones plugin expects the artist mbid to already be in the database.
