### ISSUE TITLE
Ampache without vhost

### ISSUE THREAD

**Issue by alpharde** [ampache/ampache#1670]
Hello,
I'm not very well versed in writing URL rewrite configuration for webservers, I'd like to know if there is a configuration for Nginx that isn't dependent of an domain because everytime I try to access Ampache it rewrites the URL to the domain name.

**Comment by wagnered** [comment]
@alpharde 

It sounds like you may be doing redirect instead of rewrite.

DId you check the Nginx blog [Creating NGINX Rewrite Rules](https://www.nginx.com/blog/creating-nginx-rewrite-rules/)? The blog gives some examples.

**Comment by alpharde** [comment]
Holy, got notified about this after the labels were set up.
Already found a way around this long ago.
