### ISSUE TITLE
Subsonic API 404's with 3.8.5 release

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1674]
# Environment

 * Ampache version: 3.8.5
 * Web server + version: httpd-2.4.29-1.fc26.x86_64
 * Server operating system: Fedora 26
 * Client operating system: Android

 * Client type: dDub

# Description

After upgrading from Ampache 3.8.4 to 3.8.5, dSub reports that it cannot communicate with Ampache via the Subsonic API. The logs indicate that dSub is receiving HTTP 404 codes for the Subsonic API.

# Logs

```
<IPADDR> - - [16/Feb/2018:16:14:48 -0500] "POST /rest/getAvatar.view?u=gnexus&p=REDACTED&v=1.2.0&c=DSub&username=gnexus HTTP/1.1" 404 217 "-" "DSub"
<IPADDR> - - [16/Feb/2018:16:14:49 -0500] "POST /rest/getAlbumList.view?u=gnexus&p=REDACTED&v=1.2.0&c=DSub&type=newest&size=20&offset=0 HTTP/1.1" 404 220 "-" "DSub"
<IPADDR> - - [16/Feb/2018:16:15:00 -0500] "POST /rest/getAlbumList.view?u=gnexus&p=REDACTED&v=1.2.0&c=DSub&type=random&size=20&offset=0 HTTP/1.1" 404 220 "-" "DSub"
```

**Comment by bowlofeggs** [comment]
I forgot to mention, I was able to downgrade back to 3.8.4 and things are working again.

**Comment by wagnered** [comment]
@bowlofeggs 

Thanks, although I did most of the Subsonic API fixes in 3.8.5 and have been using it with DSub and 3.8.6-develop, rather often.

I just did a rolling upgrade to  Fedora 27 and all my webservers stopped working with PHP Will look into it after I get my webserver(s) working with PHP again.

**Comment by wagnered** [comment]
@bowlofeggs 

Got my web servers working...

I just tested Ampache-38.4 and Ampache 3.8.5 releases with DSub and I was able to access/play music from DSub with the two releases.  I made no changes to the  Ampache releases or the server address in DSub when switching.

I can't replicate your issue.

Could it be a change in "web_path" in ampache.cfg.php or play/.htaccess, or maybe a change in the web server document root?

**Comment by bowlofeggs** [comment]
Hello @wagnered!

I don't see any differences in ```ampache.cfg.php```:

```
$ diff -u ampache-3.8.4/config/ampache.cfg.php ampache-3.8.5/config/ampache.cfg.php
<no output>
```

However, I seem to not have ```ampache-3.8.5/play/.htaccess``` but instead have ```ampache-3.8.5/play/.htaccess.dist```. Unfortunately, resolving this discrepancy still does not fix it, and also it doesn't have any differences between old and new:

```
$ diff -u ampache-3.8.4/play/.htaccess ampache-3.8.5/play/.htaccess
<no output>
```

I simply see HTTP 404 codes when dSub tries to access the API as reported above.

When I did the upgrade, I followed the [Basic Instructions](https://github.com/ampache/ampache/wiki/Upgrade#basic-instructions), and I used the [tarball that did not have all the deps included](https://github.com/ampache/ampache/archive/3.8.5.tar.gz) and then used ```composer install --prefer-source --no-interaction``` to get the deps.

As far as I can tell in the UI, the Subsonic API is enabled. I guess that's in the database rather than in the config file?

Do you have further suggestions about how I can debug this? Perhaps I should try the larger tarball that has the included deps (or is the way I did it also "supported")?

Sorry for the delayed response, busy week!

**Comment by wagnered** [comment]
@bowlofeggs 
I updated the first topic of the upgrade instructions in the Wiki.

To upgrade an existing release version, it is easier to use the ampache-X.X.X_all.zip and the instructions given in the first item **"Upgrade From Release"**.  Composer doesn't need to be executed on this package and the .htaccess files already exist.

Did you use the same database with 3.8.5? If not, did you enable URL rewrite in Admin->Server Config->Streaming?

Given time I might think of something else, but for now I'm at a "dead end". :smile:

**Comment by bowlofeggs** [comment]
I switched to the 3.8.6_all.zip release and things seem to be working now. Thanks for the tips!
