### ISSUE TITLE
Album / Artist page not change

### ISSUE THREAD

**Issue by wargreen** [ampache/ampache#1676]
# Environment

 * Ampache version: 3.8.6, commit acf252c8df9ab1e387f006b3027174379087970a
 * Web server + version: apache2 2.4.29-1
 * Server operating system: debian SID
 * Client operating system: debian SID, firefox 58.0.1 (64 bits)

 * Client type:
   - Web

# Settings

```
config_version = 34
http_host = "space.lebib.org"
http_port = 8080
web_path = ""
local_web_path = "http://localhost/"
database_hostname = "localhost"
database_port = ""
database_name = "ampache"
database_username = "ampache"
database_password = "*****"
secret_key = "******"
session_length = "3600"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
auth_methods = "mysql"
logout_redirect = "https://lebib.org"
access_control = "true"
require_session = "true"
require_localnet_session = "true"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
metadata_order = "getID3,filename"
metadata_order_video = "filename,getID3"
deferred_ext_metadata = "true"
catalog_file_pattern = "mp3|mpc|m4p|m4a|aac|ogg|oga|wav|aif|aiff|rm|wma|asf|flac|opus|spx|ra|ape|shn|wv"
catalog_video_pattern = "avi|mpg|mpeg|flv|m4v|mp4|webm|mkv|wmv|ogv|mov|divx|m2ts"
catalog_playlist_pattern = "m3u|m3u8|pls|asx|xspf"
catalog_prefix_pattern = "The|An|A|Die|Das|Ein|Eine|Les|Le|La"
allow_zip_download = "true"
Allow Zip Types
allow_zip_types = ""
waveform = "true"
tmp_dir_path = "/tmp/ampache"
generate_video_preview = "false"
use_auth = "true"
default_auth_level = "guest"
ratings = "true"
userflags = "true"
directplay = "true"
sociable = "true"
licensing = "false"
memory_cache = "true"
resize_images = "true"
art_order = "db,tags,folder,musicbrainz,lastfm,google"
lastfm_api_key = "d5df942424c71b754e54ce1832505ae2"
lastfm_api_secret = ""
wanted = "true"
wanted_types = "album,official"
channel = "true"
live_stream = "true"
refresh_limit = "60"
show_footer_statistics = "true"
debug = "true"
debug_level = "3"
log_path = "/var/log/ampache"
log_filename = "%name.%Y%m%d.log"
site_charset = "UTF-8"

allow_public_registration = "false"
cookie_disclaimer = "false"
registration_display_fields = "fullname,website"
registration_mandatory_fields = "fullname"
transcode_m4a = "required"
transcode_flac = "required"
transcode_mpc = "required"
transcode_ogg = "allowed"
transcode_wav = "required"
transcode_avi = "allowed"
transcode_mkv = "allowed"
transcode_mpg = "allowed"
encode_target = "ogg"
encode_video_target = "webm"
transcode_player_customize = "true"
transcode_cmd = "avconv"
transcode_input = "-i %FILE%"
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
encode_args_webm = "-q %QUALITY% -f webm -c:v libvpx -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"
encode_srt = "-vf \"subtitles='%SRTFILE%'\""
encode_ss_frame = "-ss %TIME%"
encode_ss_duration = "-t %DURATION%"

common_abbr = "divx,xvid,dvdrip,hdtv,lol,axxo,repack,xor,pdtv,real,vtv,caph,2hd,proper,fqm,uncut,topaz,tvt,notv,fpn,fov,orenji,0tv,omicron,dsr,ws,sys,crimson,wat,hiqt,internal,brrip,boheme,vost,vostfr,fastsub,addiction,x264,LOL,720p,1080p,YIFY,evolve,fihtv,first,bokutox,bluray,tvboom,info"
```
# Description

Changing of page in the album/artist view do not work.

# Logs

The firefox console :
```
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/server/ajax.server.php?page=browse&action=browse&browse_id=26&key=regex_match&multi_alpha_filter=^G
Numéro de ligne 13, Colonne 187 :
ajax.server.php:13:187
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/#browse.php?action=artist
Numéro de ligne 13, Colonne 187 :
space.lebib.org:8080:13:187
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/server/ajax.server.php?page=browse&action=browse&browse_id=26&key=regex_match&multi_alpha_filter=^G
Numéro de ligne 13, Colonne 187 :
ajax.server.php:13:187
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/#browse.php?action=artist
Numéro de ligne 13, Colonne 187 :
space.lebib.org:8080:13:187
```
Ampache log :
```2018-02-21 22:39:21 [admin] (session) -> 29sisr6dsr46h3es9pnu05uri0 has been extended to Wed, 21 Feb 2018 23:39:21 +0100 extension length 3600 
2018-02-21 22:39:21 [admin] (ajax.server.php) -> Called for page: {browse} 
2018-02-21 22:39:21 [admin] (browse.ajax.php) -> Called for action: {browse} 
2018-02-21 22:39:21 [admin] (Catalog) -> set catalog id:  
2018-02-21 22:39:21 [admin] (browse) -> Show objects called for type {artist} 
2018-02-21 22:39:21 [admin] (Art) -> Error: No mime type found. 
2018-02-21 22:39:21 [admin] (Art) -> Unable to retrieve or generate thumbnail for artist::9388 
2018-02-21 22:39:21 [admin] (Art) -> Error: No mime type found. 
2018-02-21 22:39:21 [admin] (Art) -> Unable to retrieve or generate thumbnail for artist::10688 
2018-02-21 22:39:22 [admin] (Art) -> Error: No mime type found. 
2018-02-21 22:39:22 [admin] (Art) -> Unable to retrieve or generate thumbnail for artist::10347 
2018-02-21 22:39:22 [admin] (Art) -> Error: No mime type found. 
2018-02-21 22:39:22 [admin] (Art) -> Unable to retrieve or generate thumbnail for artist::10411 
```

**Comment by wagnered** [comment]
@wargreen 

I can't duplicate your issue. Those art errors should not be  fatal. The images just will not be displayed.

My datase shows 23 pages of albums and 8 pages of artists and I can browse to every one of them.

Was this commit referred to above an upgrade, and if so, was there a problem before the upgrade?

If this is a fresh install, I'm guessing that the tag info (metadata) might contain bad data.

Could you enable the php log and see if there are any error's or warnings listed in it?

**Comment by wargreen** [comment]
I don't know if it can be related, but in the firefox console i can see :
```Erreur dans les liens source : request failed with status 404
URL de la ressource : http://space.lebib.org:8080/lib/components/jquery/jquery.min.js
URL du lien source : jquery.min.map```
And in the apache log : 
```"GET /lib/components/jquery/jquery.min.map HTTP/1.1" 404 534 "-"```
In the apache error.log i got
```[Wed Feb 28 16:30:30.964403 2018] [authz_core:debug] [pid 24870] mod_authz_core.c(809): [client *****:59554] AH01626: authorization result of Require all granted: granted, referer: http://space.lebib.org:8080/
[Wed Feb 28 16:30:30.964462 2018] [authz_core:debug] [pid 24870] mod_authz_core.c(809): [client *****:59554] AH01626: authorization result of <RequireAny>: granted, referer: http://space.lebib.org:8080/
[Wed Feb 28 16:30:30.964481 2018] [charset_lite:debug] [pid 24870] mod_charset_lite.c(219): [client *****:59554] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://space.lebib.org:8080/
[Wed Feb 28 16:30:31.228271 2018] [deflate:debug] [pid 24870] mod_deflate.c(853): [client ****:59554] AH01384: Zlib: Compressed 372805 to 19658 : URL /server/ajax.server.php, referer: http://space.lebib.org:8080/```

**Comment by wagnered** [comment]
@wargreen 

Sorry about the delay: I finally had time to look more deeply into your issue. 

The error:
> 2018-02-21 22:39:21 [admin] (Art) -> Error: No mime type found. 

might be caused by the PHP-GD module failing to load.

If you go to admin->Other Tools->Ampache Debug,  you should see `GD Support On`.

Also, xecuting `php-cgi -m` or `/usr/sbin/php-fpm -m on a command line will list the loaded modules. The "gd" module should be seen in the list.

**Comment by wargreen** [comment]
Yes, the GD Support is enabled !

**Comment by wagnered** [comment]
@wargreen 

Getting back to the mainproblem "Album/Artist page not change":

I noticed that the Apache access log  revealed:
> "GET /lib/components/jquery/jquery.min.map HTTP/1.1" 404 534 "-"

Sorry I didn't notice it before, but that file isn't even used in 3.8.6-develop.

It looks like 3.8.6-develop was installed **incorrectly**.  Was composer installed and run per the [installation wiki](https://github.com/ampache/ampache/wiki/Installation).

In Firefox, if you select Tools->web Developer->Network then the js tab, you should see jquery.min.js.
If you see a red dot and 404,  the installation wasn't performed correctly. That file is required to ba able to change pages.

**Comment by wargreen** [comment]
Sorry for the time,
I've try to reinstall from git, and i still got 
```
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/server/ajax.server.php?page=browse&action=page&browse_id=1&start=50&browse_uid=1
Numéro de ligne 13, Colonne 183 :
ajax.server.php:13:183
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/index.php#browse.php?action=album
Numéro de ligne 13, Colonne 183 :
index.php:13:183
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://space.lebib.org:8080/lib/components/jquery/jquery.min.js
URL du lien source : jquery.min.map
```
in my firefox's console.

**Comment by wagnered** [comment]
@wargreen 

Please enable debug logging in the ampache.cfg.php file according to the [Ampache wiki](https://github.com/ampache/ampache/wiki/Troubleshooting). The log might show php errors and more detailed information.

If you run the command `php -m` from a command line to see the loaded modules you should see:

xml
xmlreader
xmlwriter
simplexml (optional).

If you don't see at least the first three, then php will have problems parsing xml content.

Also, I suggest you install a [release version:](https://github.com/ampache/ampache/releases/download/3.8.6/ampache-3.8.6_all.zip) It's a matter of just "dropping it in". Not necessary to run composer as you had to do with the develop version you downloaded/cloned.

**Comment by wargreen** [comment]
Same with xml installed.
I see the first page, it seem that the problem happen with the ajax only


```
sudo -u www-data php -m
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
igbinary
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

In the ampache's log :
```
2018-03-10 19:39:58 [wargreen] (session) -> cdsbqtf94jgf0na3pl5bqs7375 has been extended to Sat, 10 Mar 2018 20:39:58 +0100 extension length 3600 
2018-03-10 19:39:58 [wargreen] (ajax.server.php) -> Called for page: {browse} 
2018-03-10 19:39:58 [wargreen] (browse.ajax.php) -> Called for action: {page} 
2018-03-10 19:39:58 [wargreen] (browse) -> Show objects called for type {artist} 
2018-03-10 19:39:58 [wargreen] (Art) -> Error: No mime type found. 
2018-03-10 19:39:58 [wargreen] (Art) -> Unable to retrieve or generate thumbnail for artist::15879 
2018-03-10 19:39:58 [wargreen] (Art) -> Error: No mime type found. 
2018-03-10 19:39:58 [wargreen] (Art) -> Unable to retrieve or generate thumbnail for artist::15215 
2018-03-10 19:39:58 [wargreen] (Art) -> Error: No mime type found. 
2018-03-10 19:39:58 [wargreen] (Art) -> Unable to retrieve or generate thumbnail for artist::15628 
2018-03-10 19:39:58 [wargreen] (Art) -> Error: No mime type found. 
2018-03-10 19:39:58 [wargreen] (Art) -> Unable to retrieve or generate thumbnail for artist::14771 
```

In the firefox's log :
```
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://space.lebib.org:8080/lib/components/jquery/jquery.min.js
URL du lien source : jquery.min.map
[En savoir plus]
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/server/ajax.server.php?page=browse&action=page&browse_id=1&start=50&browse_uid=1
Numéro de ligne 13, Colonne 183 :
ajax.server.php:13:183
Erreur d’analyse XML : mal formé
Emplacement : http://space.lebib.org:8080/index.php#browse.php?action=artist
Numéro de ligne 13, Colonne 183 :
```

**Comment by wagnered** [comment]
@wargreen 

> I see the first page, it seem that the problem happen with the ajax only

Are you implying that by disabling AJAX page loading on the Admin->ServerConfig->Interface tab you can go to "next" page?

Ajax is actually javaScript: Do you have JavaScript disabled in your browser?

Concerning the Ampache debug errors:  I noticed that php-gd isn't loaded.  Ampache uses GD to test and allow only certain image files to be created as thumbnails. Without that module loaded, It gets a NULL value when testing a file, thus the errors.  If I remember correctly, those aren't fatal error, but loading php-gd might prove me wrong. :confounded:

**Comment by wargreen** [comment]
@wagnered 

> Are you implying that by disabling AJAX page loading on the Admin->ServerConfig->Interface tab you can go to "next" page?
Nop, i say that cause all the other links works. But in fact it's also ajaxed, so i'm wrong.
Javascript is activated in my browser, and nothing seem blocked.

I have installed GD (i have forgot to install it for php7.1), and the problem still.

Maybe it can be a misconfiguration  of my web server ?

**Comment by wagnered** [comment]
@wargreen 

> Maybe it can be a misconfiguration of my web server ?

No, because I  "accidentally" was able to reproduce your issue, in part: Only for artists, paging through albums still works correctly.

For reasons I won't mention :anguished:,  I had to use my main backup which produced the systems I described above.  I spent several hours stepping through the code, but Eclipse isn't the best for debugging php.

I did find a "work-around" which was refreshing the browser after selecting the next page.

Also, it produces the same thumbnail errors that you reported above. I'll look into that symptom.

**Comment by wagnered** [comment]
@wargreen 

In addition to the issue of paging, I also had a problem of no details being displayed from any  the Admin->Server Config menu items.

So I removed config/ampache.cfg.php and rebuilt the database, overwriting the old one.  That fixed my second issue, but did not appear to fix the first until I unchecked the "pages" checkbox on the "view" button at the right top of the Albums/Artists lists. then rechecked it.

I don't know if your problem is identical,

**Comment by wagnered** [comment]
@wargreen 

> Maybe it can be a misconfiguration of my web server ?

Well, I discovered that all of a sudden, I managed to replicate your issue in part, but only for Artists. Albums would page ok.

I tried running `php -S 127.0.0.1:8000` to check my backup and found that I was able to go to next page.

I don't know what changed, but something must have changed in my web server settings.

**Comment by wagnered** [comment]
I've discovered on my system, that after selecting next page, a browser refresh will then display it.  Not a good work-around, but i've had a lot of false leads so far.

**Comment by wagnered** [comment]
@wargreen 

I think I was wrong about the ampache log error `No mime type found` not being the main problem. I haven't tracked down the reason, but I noticed that the mime type passed into that function is corrupted.
I disabled the `resize_images` switch in ampache.cfg.php and I was then able to page to next and previous.

Looking at the "mime" column in the image table, I confirmed that the corrupted value was stored in the column.  Now I will attempt to track down the actual problem.

**Comment by wargreen** [comment]
I confirme, disable ```resize_image``` let me able to page previous/next also !

**Comment by wagnered** [comment]
Good to know.
Now finding what's causing the storing of corrupted mime type is a slow process of elimination.

**Comment by wagnered** [comment]
@wargreen 

Could you examine the database's `mime` column in the image table  and report any entries that appear irregular?
Ampache accepts only the following mime types:
image/jpg
image/jpeg
image/png
image/jif
image/bmp

Thanks...

**Comment by wargreen** [comment]
I see some ```image/```, ```image/JPG``` (with caps) and ```image/com``` with Original size.
Hope it's help.

**Comment by wagnered** [comment]
Good.  That's about what I've seen in results from Google searches.

I am now testing out the final changes to the clean-up code.

I'll be pushing the fix to the develop branch ASAP.

**Comment by wargreen** [comment]
With a more in-deph search, i have also a ```image/jpg?c\u003d1050,550\u0026w\u003d1050```, ```image/jpg?itok\u003dzkT_VGjw```, ```image/jpg?resize\u003d800,600\u0026ssl\u003d1```, ```image/png?format\u003d500w```, ```image/jpg?1502175249```....

**Comment by wagnered** [comment]
@wargreen 

Thanks, for your help :smile:   and bringing the issue to my attention.  I'm surprised that nobody noticed this issue earlier.   Again, those are the same as was in my database.  Hopefully, there won't be any new forms of url strings to deal with.

I'll be pushing the changes soon.

**Comment by wagnered** [comment]
Latest commit a67b8036 to fix this issue as been pushed to the develop branch.

**Comment by wargreen** [comment]
Nice, thank you !
Is should i to do something for fix the database ?

**Comment by wagnered** [comment]
That's up to you.  You can manually edit those bad mime column entries to be one of the types I listed above. I only found about a dozen or so bad entries out of about 1000 images.

Then you should be able to enable the `resize_images` switch if you would like.  Although doing this burdens the CPU usage and load time as described in ampache.cfg.php.

Editing the mime column entries would save you the trouble of upgrading Ampache. If you do decide to upgrade Ampache, please remember to follow the [wiki](https://github.com/ampache/ampache/wiki/Upgrade) and backup your database first, The instructions are given in the wiki.

**Comment by wargreen** [comment]
After an upgrade, the problem still and the incorect keys in the database also.
Maybe is it a way to flush all albums arts and re-retrieve it ?

**Comment by wagnered** [comment]
When you upgraded, you probably didn't overwrite the existing database. The image table entries must be removed.

I suggest that you execute the following MySQL command:  TRUNCATE TABLE \`image`; This will remove the image data.

Then in Ampache, execute "Gather Art" from the admin->Show Catalogs action list. 

Otherwise move config/ampache.cfg.php out of that folder and re-initialize ampache, overwriting the database.

**Comment by wargreen** [comment]
Thanks, flush the image table work fine !
This issue seem closed :)
