### ISSUE TITLE
Media does not play automatically in Firefox

### ISSUE THREAD

**Issue by Offerel** [ampache/ampache#1677]
# Environment

 * Ampache version: 3.8.5
 * Web server + version: Nginx 1.10
 * Server operating system: Debian 9
 * Client operating system: Windows
 * Client type:
   - Firefox
   - Ampache

# Settings

# Description

If in Firefox 58 the setting media.autoplay.enabled is set to false, this prevents from autoplay of videos the site is loaded. I dont know if this is a new setting since Firefox 57. I think it's only available from about:config screen and not the normal Firefox settings. However, is this set to false, also when i click on the play button in playlist overview the music does not start to play. Only the Webplayer is opening but waits for a additional click on the play button in the Webplayer. Since the above Firefox setting should prevent only from unwanted media autostart, this is a event which is wanted and so it should be played automatically. I dont know if it is possible to trigger in such case the additional click on the play button or call the event directly. Personally, i like this new Firefox setting, but in case of Ampache it does not work as expected. I didnt see this as a Firefox Bug directly since the user triggers playing manually and it doesnt work as expected only in this Webplayer.

**Comment by nearwood** [comment]
AFAIK, This as as designed. The webplayer opens up in a new window, so the click on the play link on the previous screen does not count against the autoplay setting in Firefox (or Chrome). Disabling autoplay is specifically to prevent new tabs/windows from starting audio that the user did not directly trigger (eg., video ads on a new tab).

**Comment by wagnered** [comment]
@nearwood 

Sorry to take so long to respond, Also, I thought this comment was just an observation  and you weren't really complaining about it.

I believe this is a Windows only issue and thanks for submitting your observation.

With the Linux version of Firefox, only a single click is necessary.  I have never changed media.autoplay.enabled in about:config and it was set to true.

I am running Firefox 58.0.1 on Fedora 26..

@nearwood 

Thanks for bumping this and bringing it to my attention. :smile: 

> AFAIK, This as as designed. The webplayer opens up in a new window,

Again, this may happen only in the Windows version of Firefox,  In the Linux version of Firefox, the web player opens up at the bottom of the same page that the item is selected to play. And it begins playng automatically.

Again, thanks to both of you for submitting your observatons.

**Comment by kuzi-moto** [comment]
Closing this issue for two reasons:

1. `media.autoplay.enabled` has been removed from Firefox as of version 63.
2. Firefox now has more more sophisticated auto-play controls, where you can allow specific sites to auto-play media. More information from this [ghacks.net article](https://www.ghacks.net/2018/09/21/firefox-improved-autoplay-blocking/).
