### ISSUE TITLE
FR: Sorting a Smart Playlist

### ISSUE THREAD

**Issue by Offerel** [ampache/ampache#1678]
I have a wish for sorting the Smart Playlists. I would like to be able to sort the Smart Playlist. The following sorting would be important to me: Sorting by year of release, by album name, within the album by title number and sorting by rating. Sort criteria should used one by one or several criteria together (eg. sort by years, the album and in the album by title number).

**Comment by lachlan-00** [comment]
This should be possible with an option like the random checkbox. i'll ad this as a todo after the next release

**Comment by lachlan-00** [comment]
date added is in there and would definitely be a good option.
I's all fairly easy on the backend side i just need to add it into the ui
