### ISSUE TITLE
Import LastPlayTime for songs from MediaMonkey

### ISSUE THREAD

**Issue by Offerel** [ampache/ampache#1682]
For everyone how wants to import the LastPlayed timestamp for song's from MediaMonkey, i want to share my SQL snippet.

```
select TrackNumber, SongTitle, PlayCounter, strftime('%s',datetime(LastTimePlayed+2415018.5)) as timestamp, 
"INSERT INTO object_count (object_type, object_id, date, user, agent, count_type) VALUES ('song', (select id from song where title = """ || SongTitle || """ and track = " || TrackNumber || ") , " || strftime('%s',datetime(LastTimePlayed+2415018.5)) || ", 1, 'sqlimport', 'stream');"
from songs
where lasttimeplayed > 1
order by lasttimeplayed;
```

This creates in the last column a list of SQL commands, which you can than use, to import the timestamp to the ampache database. In my case, i had to clean up the quotes a little bit, since i used only very simple Sqlite Browser. Be sure that every sing has a unique SongTitle/Tracknumber combination to identify the song correctly. The MediaMonkey database is saved in Sqlite Format in the file mm.db.

Maybe this is useful for someone.

**Comment by lachlan-00** [comment]
This will only put the song in and ampache also uses the album and artist so you can get wonky data.

you could look at exporting into a tsv and use mysql-connection.py from my scripts.
https://github.com/lachlan-00/ampache-scripts

It uses  a pretty basic format that the old last.fm exporter uses.
time, title, artist, album, mbid-title, mbid-artist, mbid-album
~~~
1522809611	Vegas Two Times	Stereophonics	Best of Stereophonics: Decade in the Sun	c0c932cb-8686-4c77-aa68-532d4e1f3ef1	0bfba3d3-6a04-4779-bb0a-df07df5b0558	b6a82fef-20b3-44e6-8f8f-a2595f0ac1fc
~~~

**Comment by kuzi-moto** [comment]
Closing as this is not really an issue.
