### ISSUE TITLE
Deleting catalog doesn't remove all data relating to that catalog

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1686]
* Ampache version: 3.8.*
 * Web server + version: N/A
 * Server operating system: N/A
 * Client operating system: BN/A

# Description

When deleting a catalog, Ampache only removes the songs: albums, images, artists associated with that catalog remain.  Other than "stuffing" the database, no sure what other problems this may cause.

**Comment by a7medo778** [comment]
this is still an issue

**Comment by kuzi-moto** [comment]
If you click "Clean All" on the "Show Catalogs" page, it should remove all the data.

**Comment by a7medo778** [comment]
I just did and it didn't work
Cleared the cache and it didn't work

And even optimized the tables and it didn't work 
(yes I know it's strange)

**Comment by lachlan-00** [comment]
garbage_collection had some old bugs not clearing things from object_count but this is just the artist themselves in the artist table?

I have 18 in mine which to me look mostly like translations/spelling
![image](https://user-images.githubusercontent.com/1305249/60390311-3f4bdc00-9b17-11e9-94c5-5954bd4371c9.png)

Do you think there's any reason why they would be needed? I can't really see a reason for keeping them.

**Comment by a7medo778** [comment]
in my case about 400 " tracks, albums, artists" records remained there
i tried clean up, didnt work
optimized the tables, didnt work

i ended up emptying the tables my self

**Comment by lachlan-00** [comment]
which tables? The only obvious bug i found so far has been in object_count so it would be good to know which specifically.

For music there is a collection run on at least these tables:
song
artist
album
object_count
rating
user_flag
user_activity
image
shout
tag

**Comment by lachlan-00** [comment]
I've had a deeper look @a7medo778 and it seems like all the queries are deleting correctly as far as i can see.

There are 37 garbage_collection functions in Ampache so I'll need some table/row specifics as i think what might be happening is that there is still something attached to those id's.
![image](https://user-images.githubusercontent.com/1305249/60405035-0d0ead00-9bf1-11e9-8e31-8b9e4edf9eab.png)

**Comment by a7medo778** [comment]
i just did a test
albums,artists,songs were the biggest in item count

but this time, a clean operation was able to clear them up

**Comment by lachlan-00** [comment]
That makes me think it needs to these queries more than once depending on the task or the order they run.

Thanks for the tables. I'll look at those garbage_collections and see what can be done.

**Comment by Afterster** [comment]
See #2336
