### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by prschopf** [ampache/ampache#1687]
# Environment

 * Ampache version: 3.8.6
 * Web server + version: Apache
 * Server operating system: Unix
 * Client operating system: Chrome version 64.0.3282.186

 * Client type: web

# Description

There are some missing strings in translation (using transifex). Im sending some screenshots:

Missing strings in preferences/interface: [here](https://s9.postimg.org/afqyt0b73/tela1.jpg)
Missing strings in preferences/options: [here](https://s9.postimg.org/3pahjoqn3/tela2.jpg)
This string is translated but its not showed in preferences/streaming: [here](https://s9.postimg.org/t82twwkjj/tela3.jpg)
Missing strings in admin/server: [here](https://s9.postimg.org/nl6gyz7lr/tela4.jpg)

May someone check that, please?

**Comment by Psy-Virus** [comment]
Are they missing on Transifex or just in Ampache?

**Comment by Psy-Virus** [comment]
And btw. there's an delay between the translations and the updates to Ampache. I mostly run an update once or two times a month. Because mostly there's not much activity on Transifex, even if nearly every two weeks someone is registering for a translation task.

**Comment by prschopf** [comment]
The third one is already in Transifex, translated, but not in Ampache.

The other ones are not in Transifex yet.
