### ISSUE TITLE
With light sidebar showing, some items cannot be played.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1689]
# Environment

 * Ampache version: 3.8.6+
 * Web server + version: N/A
 * Server operating system: N/A
 * Client operating system: N/A

With light sidebar displayed and artist or album is selected, item images display play button when cursor is hovering over them, but clicking on them won't intiate playing of the selected item.

**Comment by lachlan-00** [comment]
Closing, this is fixed in core at least.
