### ISSUE TITLE
How to: Delete a song

### ISSUE THREAD

**Issue by Cypoun** [ampache/ampache#1691]
Hello,
I'm not sure if it's an issue or not.

I just would like to know how can someone (admin or not) delete a song from Ampache ? If I delete it from my ubuntu server (`rm *****`) the file stays in Ampache but can't be read anymore.
So, is there a button someone or a way to create one ?

**Comment by wagnered** [comment]
@Cypoun 

On the admin->Show Catalogs page, set the drop down list to "Clean", Then click "Go". That will check the database and remove the songs that cannot be found in the catalog path.

**Comment by Cypoun** [comment]
Last time I tried it wasn't working, but maybe it was because of my cache. I'll try and tell you if there is actually an issue or just me have trouble to understand how Ampache works !
Anyway, thank you for your fast answer :)

**Comment by kuzi-moto** [comment]
@Cypoun, did you have any more issues with cleaning the catalog? Deleted files should be removed from Ampache properly after a catalog clean as wagnered says.

**Comment by kuzi-moto** [comment]
Closing as no response from requestor in over a year.

**Comment by mbluett88** [comment]
The problem with the "Clean" option is that it would take a lot of time to go through the entire song library checking each song. Simply adding a delete function as part of the song page would be much better. Please put this on your todo list. Thanks. Ampache is by far the best music library player and streaming mechanism. I would like to see more management capability though. I realize the intention was not to make it a management tool, but we really need such a thing.
