### ISSUE TITLE
Missing php-soundcloud dependency

### ISSUE THREAD

**Issue by IAmVinnnn** [ampache/ampache#1695]
I just setup latest ampache on my machine and when click on add catalog, It's throw some errors in the console which is related to missing php-soundcloud dependency.

I have checked composer.json file thiss dependency is not placed in that file also. Can you please fix that issue and let me know what changes I need to do.

Thanks,

**Comment by wagnered** [comment]
Hello @IAmVinnnn 

The main composer.json will include all .json files in modules/catalogs, etc as shown below.

At the bottom of the main composer the lines:
>           "include": [
>				"modules/catalog/*/composer.module.json",
>				"modules/localplay/*/composer.module.json",
>                             "modules/plugins/*/composer.module.json"
>            ]

install the php-soundcloud dependencies.

Perhaps the composer install was interrupted and the .json file in modules/catalog/soundcloud didn't get included.

Btw: php-soundcloud is pre-installed in the the release version (ampache-3.8.6_all.zip).

**Comment by IAmVinnnn** [comment]
Thanks @wagnered for the quick response, Above issue is fixed in ampache-3.8.6_all.zip.
