### ISSUE TITLE
Upload Menu is missing

### ISSUE THREAD

**Issue by IAmVinnnn** [ampache/ampache#1696]
I have setup latest ampache. Installation is fine but upload menu is missing from the sidebar. Please have a look of attached screenshot and let me know if anything is wrong at my side.
![ampache __ for the love of music - home 1](https://user-images.githubusercontent.com/24268675/37867487-6933f29c-2fbf-11e8-89db-32f5a6fd537c.png)

**Comment by wagnered** [comment]
@IAmVinnnn 

In admin (second icon to right on left sidebar) ->Server Config->System, "Allow users to upload media" must be enabled.

**Comment by IAmVinnnn** [comment]
@wagnered Thanks for quick response. I got that option.
