### ISSUE TITLE
Unable to create songs cache at the time of uploading

### ISSUE THREAD

**Issue by aditya-dikonia** [ampache/ampache#1697]
I have used ampache for the backend of my mobile app. Where admin / catalog manager uploaded the songs and mobile users will playing these songs via mobile app and everything is working well. But I am facing a small issue regarding cache not store at the time of songs uploading. 
When I uploaded a fresh song from backend and play it first time on the mobile app the time tracker is not working. But when I am playing that song again time tracker is also working fine. 
Is there any option in the config or need any changes at code end which can fix that issue?

**Comment by wagnered** [comment]
@aditya-dikonia 

> Is there any option in the config or need any changes at code end which can fix that issue?

Sorry to report that there is no option to change that and no plan for "fixing" it. That would mean big changes to Ampache and only serious issues are being attended to.  Most of my time is devoted to developing the next generation Ampache.

Manually uploading a song shouldn't happen that often as all songs should already be in the catalog. The "upload" function primarily exists for users to occasionally upload their favorite songs.

**Comment by kuzi-moto** [comment]
Closing as this is more of an issue on the client-side. The Dsub app handles this by displaying a loading animation on the timeline while the song is caching. When complete, it will show the correct position on the timeline as the song plays.
