### ISSUE TITLE
Plex API server out of date

### ISSUE THREAD

**Issue by miniesta01** [ampache/ampache#1698]
# Environment

 * Ampache version: 3.8.3
 * Web server + version: Yunohost 2.7.10
 * Server operating system: Debian Jessie
 * Client operating system: Mac/Windows/IOS/android...
 * Client type:
   - Plex

# Description

Currently Plex server version inside Ampache is V0.9.9.. However current Plex client need at least server V1.3.0 to work. Is it possible to update Plex server ? Latest Plex server version is V1.12.1.  
Thanks

**Comment by wagnered** [comment]
@miniesta01 

You wrote:
> However current Plex client need at least server V1.3.0 to work.

I'm curious as to where you found this information?

I've done some searching and found that Plex hasn't published a formal API for the Plex server.
There is an "informal" listing of API commands but I don't know if the list is complete or even accurate.

I'll take a look at Ampache's Plex API to see what can be updated, but I don't know how long it will take.   I have been having trouble with the Android app seeing the Plex server I installed.

**Comment by miniesta01** [comment]
@wagnered Thanks for your quick answer. The information is display on web app (mac application and web browser):
![capture d ecran 2018-03-28 a 08 40 51](https://user-images.githubusercontent.com/37772001/38013647-2e3151cc-3266-11e8-8ec1-8795910bd33d.png)
I though is was the same for all Plex client. But I test today for iPhone application and in that case I see the serveur but it's seen offline:
![ima_d74ee85](https://user-images.githubusercontent.com/37772001/38013701-5f227842-3266-11e8-94c8-eaa50bfc6f51.png)
I'll perform more test on that point (with iPhone app) later this week. 
Thanks

**Comment by wagnered** [comment]
@miniesta01 

Thanks, I hadn't got that far, I have been trying to get the Plex android app working with the plex server first.  Just got it working last night.

**Comment by wagnered** [comment]
@miniesta01 

The last step in the Plex wiki states:
> Administrate and publish the server to myPlex with http://localhost:32400/web

Could you explain what that means and how to do it?  The Plex server does it automatically, I think.
But there is nothing on the Plex web site for how to do it manually.

**Comment by miniesta01** [comment]
Hello,
Here the exemple of the plex server installation on mac. 

1. configuration is done under the web browser at the following adress
![capture d ecran 2018-03-29 a 19 51 28](https://user-images.githubusercontent.com/37772001/38106207-931bdc1e-338e-11e8-95f5-8c30559e0a5a.png)

2. Serveur Naming
![capture d ecran 2018-03-29 a 19 51 09](https://user-images.githubusercontent.com/37772001/38106239-a79ac4ac-338e-11e8-9fa8-52f79cb2163b.png)

3. Library configuration
![capture d ecran 2018-03-29 a 20 15 48](https://user-images.githubusercontent.com/37772001/38106259-b2eec97a-338e-11e8-9341-facad8ea4fb3.png)

4. End
![capture d ecran 2018-03-29 a 20 17 52](https://user-images.githubusercontent.com/37772001/38106270-bcf2fbf8-338e-11e8-8836-8d8a9517f58f.png)

Then you access the web app where you can manage player and server. I don't know more about how manually it's done. Did you have a look to Plex API on Github  : [https://github.com/Arcanemagus/plex-api/wiki](url)

If I found anything else, i'll share with you. 

Thanks,

**Comment by miniesta01** [comment]
@wagnered Thanks you for you detail analysis. I understand the complexity of the task. And I understand that it may be not possible as the API became proprietary. So do as you can. I'm very please of the Ampache app anyway. It's a great application! Thank you for that and for your time :)

**Comment by lachlan-00** [comment]
Closing, Plex backend /support is to be removed from Ampache.
