### ISSUE TITLE
Cannot install Ampache - 

### ISSUE THREAD

**Issue by giovi321** [ampache/ampache#1699]
# Environment

 * Ampache version: 3.8.7-develop with database version 380012.
 * Web server + version: apache2
 * Server operating system: Debian 9 64bit
 * Client operating system: Windows 10

 * Client type:
   - Web

# Settings

;#<?php exit(); ?>##
;#########################################################
; General Config                                         #
;#########################################################

; This value is used to detect quickly
; if this config file is up to date
; this is compared against a value hard-coded
; into the init script
config_version = 34

;#########################################################
; Path Vars                                              #
;#########################################################

; The public http host of your server.
; If not set, retrieved automatically from client request.
; This setting is required for WebSocket server
; DEFAULT: ""
http_host = "music.example.com"

; The public http port of your server.
; If not set, retrieved automatically from client request.
; DEFAULT:
http_port = 443

; The public path to your ampache install
; Do not put a trailing / on this path
; For example if your site is located at http://localhost
; than you do not need to enter anything for the web_path
; if it is located at http://localhost/music you need to
; set web_path to /music
; DEFAULT: ""
web_path = "/ampache"

; The local http url of your server.
; If not set, retrieved automatically from server information.
; DEFAULT: ""
;local_web_path = "http://localhost/ampache"

;#########################################################
; Database                                               #
;#########################################################

; Hostname of your database
; For socket authentication, set the path to socket file (e.g. /var/run/mysqld/mysqld.sock)
; DEFAULT: localhost
database_hostname = "192.168.56.102"

; Port to use when connecting to your database
; DEFAULT: none
database_port = "3306"

; Name of your ampache database
; DEFAULT: ampache
database_name = "ampache"

; Username for your ampache database
; DEFAULT: ""
database_username = "ampache"

; Password for your ampache database, this can not be blank
; this is a 'forced' security precaution, the default value
; will not work (except if using socket authentication)
; DEFAULT: ""
database_password = "xxxx"

# Description
Unable to install Ampache as i get db connection error:
SQLSTATE[HY000] [2002]

# Logs
2018-03-28 00:05:08 [ampache] (Dba) -> Connection failed: SQLSTATE[HY000] [2002] No such file or directory
2018-03-28 00:10:47 [ampache] (Dba) -> Connection failed: SQLSTATE[HY000] [2002] No such file or directory
2018-03-28 00:17:47 [ampache] (Dba) -> Connection failed: SQLSTATE[HY000] [2002] No such file or directory

**Comment by wagnered** [comment]
@giovi321 

Please check the following, 1 and 3  might seem obvious, but number two might not:

1. Is the mysql (mariadb) server running?

2. If the mysql server and  Ampache are both on the debian system, the config switch `database_hostname` should be the default "localhost". This provides much higher security. Also, it doesn't require possible changes to the firewall settings.

3. Is the mysql server actually listening on port 3306(default)?

**Comment by giovi321** [comment]
@wagnered: thank you for helping. 

1) server up and running 
2) server is not local, it’s on another virtual machine
3) server runs on the default port

The MySQL server is used also by other applications and they work properly (each application has its own user and runs on a separate vm)

**Comment by giovi321** [comment]
@wagnered
1) I can access the MySQL server through command line from the vm where ampache is running. Phpmyadmin is running on the host machine and it can access the MySQL server. 
2) Apache error logs show nothing both on the host machine (hosting the reverse proxy, see below) and on the vm running ampache
Additional info: I access ampache through a reverse proxy on apache2 on the host machine. 

I will try to explain the setup:
Client —> https://music.mydomain.com —> host machine —> apache2 reverse proxy —> http://192.168.56.105 —> ampache on the vm —> MySQL server installed on another vm at 192.168.56.102:3306

**Comment by giovi321** [comment]
I was able to install ampache using lynx browser from command line on the virtual machine. However, I still cannot access ampache from outside. Is there a way to use ampache with reverse proxy?

**Comment by giovi321** [comment]
@wagnered 
Amazing. Problem solved.
Many many thanks!
