### ISSUE TITLE
timeout streaming - cURL connection timed out after 1000 ms

### ISSUE THREAD

**Issue by tk421storm** [ampache/ampache#1701]
# Environment

 * Ampache version: 3.8.4-release 
 * Web server + version: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g
 * Server operating system: Ubuntu 16.04.4 LTS
 * Client operating system: CentOS, Ubuntu, Windows

 * Client type:
   - Web

# Description

I've recently started to have consistent timeout errors when attempting to stream. The player will never load the file (using either VLC on ubuntu or Winamp on Windows), and skip to the next one. In my syslog, I get the following errors - something about last.fm?

# Logs
From syslog:
[Sat Apr 14 11:16:03.521311 2018] [:error] [pid 20094] [client 192.168.1.1:50889] PHP Fatal error: Uncaught Requests_Exception: cURL error 28: Connection timed out after 10000 milliseconds in /ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php:422\nStack trace:\n#0 /ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array)\n#1 /ampache/lib/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_cURL->request('http://ws.audio...', Array, NULL, Array)\n#2 /ampache/lib/vendor/rmccue/requests/library/Requests.php(231): Requests::request('http://ws.audio...', Array, NULL, 'GET', Array)\n#3 /ampache/lib/class/recommendation.class.php(53): Requests::get('http://ws.audio...', Array, Array)\n#4 /ampache/lib/class/recommendation.class.php(46): Recommendation::query_lastfm('http://ws.audio...')\n#5 /ampache/lib/class/recommendation.class.php(227): Recommendation::get_lastfm_results('artist.getsimi in l/ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 422, referer: [---AMPACHE URL---]

**Comment by wagnered** [comment]
@tk421storm 

Try disabling everthing related to last.fm: Similar artists/songs, scrobbling, etc. 

I suggest you upgrade Ampache to 3.8.6-release following the instructions in the [wiki](https://github.com/ampache/ampache/wiki/Upgrade).

If you upgraded php on the ampache server, make sure curl is loaded: `php -m`

**Comment by tk421storm** [comment]
upgrading to 3.8.6-release fixed it. Thanks!!

**Comment by tk421storm** [comment]
Unfortunately I spoke too soon, I'm still having issues. I've pretty much narrowed it down to last.fm - after selecting a track, it'll pause for 30-45 seconds then start playing. In the log, this message appears right before playback starts:

2018-04-19 16:56:51 (Scrobbler) -> Cannot access https://ws.audioscrobbler.com/2.0/ 
2018-04-19 16:56:51  (Last.FM) -> Error Submit Failed: Did not receive a valid response 

I've turned both last.fm variables in my ampache.cfg file to false, and I've removed both the stored API keys, but somehow it's still scrobbling. Where are the per-user scobbling settings located?

Thanks.

**Comment by wagnered** [comment]
@tk421storm 

Do you have last.fm deactivated in modules->Available Plugins? This should control whether Ampache scrobbles or not.

If you have `show_similar` or `show_concerts` enable, it might try to scrobble, but that should be a bug if the last.FM plugin is not activated.

It doesn't look like there is a per-user setting for scrobbling. Would this be a good thing?

Could you include the complete ampache log set at level 5 while selecting/playing a track?

If you actually do want to scrobble, it is necessary to make sure that the device/app you are scrobbling from is "owned" by your last.FM account.  I had to try several times to get Ampache registered to my last.FM account.

**Comment by tk421storm** [comment]
Disabling the last.fm plugin through modules did fix the problem. Unfortunately re-enabling doesn't return to the previous behavior - now it seems to work as intended without the keys that I removed:

2018-04-20 16:35:16 (Last.FM) -> No session key, not scrobbling (need to grant Ampache to last.fm) 

FWIW, here's the full log around the previous event:

2018-04-19 16:45:21 (stream_playlist) -> Generating a {m3u} object... 
2018-04-19 16:45:22 [ampache] (play) -> Asked for type {song} 
2018-04-19 16:45:22(session) -> 34d3ef32498396ed7cb6614268ff2e6a has been extended to Thu, 19 Apr 2018 23:32:02 -0400 ex
tension length 24400 
2018-04-19 16:45:22 (play) -> Playing file (/torgo/Media/Full Albums/FolkAndAnti-Folk/Guillemots/Through the Windowpane/0
1 - guillemots - little bear.mp3}... 
2018-04-19 16:45:22  (play) -> Media type {mp3} 
2018-04-19 16:45:22 (play) -> Custom play action {} 
2018-04-19 16:45:22 (play) -> Transcode to {} 
2018-04-19 16:45:22 (play) -> Transcode disabled in user settings. 
2018-04-19 16:45:22 (play) -> Starting stream of /torgo/Media/Full Albums/FolkAndAnti-Folk/Guillemots/Through the Windowp
ane/01 - guillemots - little bear.mp3 with size 6942916 
2018-04-19 16:45:22 (play) -> Registering stream stats for {Guillemots - Little Bear}... 
2018-04-19 16:45:22 [(user.class.php) -> Updating stats for {song/55806} {Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36}... 
2018-04-19 16:45:22 (user.class.php) -> save_mediaplay... 
2018-04-19 16:45:29 (Scrobbler) -> Cannot access https://ws.audioscrobbler.com/2.0/ 
2018-04-19 16:45:29 (Last.FM) -> Error Submit Failed: Did not receive a valid response 
2018-04-19 16:45:29(play) -> Stream ended at 18432 (18432) bytes out of 20800112

**Comment by wagnered** [comment]
I'm wondering if it had anything to do with cache.

**Comment by tk421storm** [comment]
So I'm working with this again (I don't mind the loss of scrobbling, there are other methods - but I miss the nice artist descriptions that come up). 

If it's a cache issue, how can I clear the cache and try again?

**Comment by wagnered** [comment]
I was actually referring to browser cache: There is a config switch: `memory_cache = "false"` but that probably isn't the problem.

To get the artist descriptions, set only the `lastfm_api_key` switch in the config file. It's the lastfm secret that causes Ampache to try to scrobble so leave that blank unless you actually want to try lastfm scrobbling again.

**Comment by tk421storm** [comment]
Can confirm that "memory_cache" (was true, now false) does not affect the issue.

Unfortunately it seems like the error is due to the feature I miss, the recommendations/artist bios/etc. (removing lastfm secret has no effect). Is there any other info I can provide to help diagnose this issue?

**Comment by wagnered** [comment]
I guess I forgot to include that to get the artist info, it is necessary to update or recreate the catalog after enabling the `lastfm_api_key`.

**Comment by tk421storm** [comment]
Looking into this morning, it appears I can succesfully access the api link from work (it returns XML data), but from home I get timeouts. Likely that last.fm is blocking my ip address.

I tend to run scheduled updates every night - is there a last.fm command that would be running along with catalog updates that could be seen by them as abusive, if it occured every day?

**Comment by wagnered** [comment]
> Likely that last.fm is blocking my ip address.

I'm really surprised if they did. It seems to me that you would be notified. I haven't done any performance tests, but PHP is rather slow in processing the files. looking at my log, It looks like  it accesses lastfm once about every 3 to 5 seconds. 

So according to the lastfm api terms of service page Ampache doesn't come close to abusing it.

Also, my previous statement:
> I guess I forgot to include that to get the artist info, it is necessary to update or recreate the catalog after enabling the lastfm_api_key.

is not quite correct.  The config switch `deferred_ext_metadata` allows updating artist info when "browsing the library item"  Otherwise it is done when updating.

**Comment by tk421storm** [comment]
Nope, unfortunately I was wrong - I can succesfully contact ws.audioscrobbler.com from my server with wget - or a browser - in fact I get back the xml data that ampache is looking for.

I created a quick curl test php script to ensure it wasn't something wrong with my configuration; when run from the command line it worked, so I'm not sure what's going on.

**Comment by wagnered** [comment]
@tk421storm 

I need to get my thoughts organized. :frowning: 

As I understand, your current problem is getting Artist information, correct?

> when run from the command line it worked, so I'm not sure what's going on.

Was this run on the server or the client operating system?

> 2018-04-19 16:45:29 (Last.FM) -> Error Submit Failed: Did not receive a valid response

Is this the error that is preventing getting the artist bio?  This looks like the XML data is not formatted correctly or there is an illegal character embedded in the text.

**Comment by tk421storm** [comment]
UGH - I think it might've been fail2ban. It was blocking the IP address of ws.audioscrobbler.com. If I unblock it (through whitelisting), I'm able to get the data (recommended artists, artist bios) without a problem - including scrobbling!

This is the second time this month fail2ban had been secretly making my life hell. Thanks for sticking with me through this. This can be closed!
