### ISSUE TITLE
XML-API: handshake with user limited ACL

### ISSUE THREAD

**Issue by jones1008** [ampache/ampache#1707]
# Environment

 * Ampache version: Ampache 3.8.6-release
 * Web server + version: Apache/2.4.25 (Debian)
 * Server operating system: Linux odroid-jessie 4.9.58+
 * Client operating system: Windows 10

# Settings

[http://paste.debian.net/1022884/](http://paste.debian.net/1022884/)

# Description

I tried to create a handshake for the XML-API with a specific user. I followed the XML-API Guide but can't get it to work... I am trying to create the handshake with [this command](https://github.com/ampache/ampache/wiki/XML-API#api-key) explained in the XML-API documentation.
Before that I created a ACL with the following data:

```
name      | start   | end             | lvl | user        | type
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | nick (nick) | API/RPC
DEFAULTv6 | ::      |                 | All | nick (nick) | API/RPC
```
Then I generated an API Key for that user referenced in that ACL and took this to create a simple handshake via a browser with the following address:
`https://<host>/server/xml.server.php?action=handshake&auth=<API_KEY>&version=350001`

But I always get an unauthorized access error like this:
`<TIMESTAMP> [ampache] (Access Denied) -> Unauthorized access attempt to API [<ip address>]`

Is there something that I am missing? or is it just a bug?
The handshake works when I set the user attribute to ALL in both ACL-entries, which is obviously pretty insecure...

**Comment by wagnered** [comment]
@jones1008 

Are you sure you entered the correct API key?  I just tried it with the API key of an ordinary user and with the admin API key and it worked for both.

Is the "unauthorized access error" from the Ampache debug log or returned by the server?

**Comment by jones1008** [comment]
> Are you sure you entered the correct API key? I just tried it with the API key of an ordinary user and with the admin API key and it worked for both.

Yes, I copied the API key from the User settings into the request.
I just tried it with an ordinary user and it didn't work either (changed the ACL before of course)

> Is the "unauthorized access error" from the Ampache debug log or returned by the server?

yes this is from the ampache debug log.
This is returned by the server:
`<error code="403"><![CDATA[Fehler: Nicht autorisierter Zugriff auf 'API - ACL']]></error>`

**Comment by wagnered** [comment]
There might be a problem.  I removed the original default API/RPC ACL for All users and the error was produced.

**Comment by wagnered** [comment]
I fixed the problem and successfully executed the example command for retrieving songs. I am pushing the changes to the develop branch and will build the 3.8,7-release as soon as possible.

**Comment by jones1008** [comment]
Nice! Can you please link the commit(s) with the changes you made?

**Comment by wagnered** [comment]
The link is: https://github.com/ampache/ampache/commit/8ee6a6522f035c5af674c64c586df13532afede9. Is this what you mean?

**Comment by jones1008** [comment]
Exactly! I will test it later on my system...

**Comment by jones1008** [comment]
I tested it and it worked well.
Thanks for solving this issue!
