### ISSUE TITLE
Problem with tag search "does not contain"

### ISSUE THREAD

**Issue by Adiatz** [ampache/ampache#1709]
# Environment

 * Ampache version: Ampache 3.8.6-release
 * Web server + version: Apache 2.4.18
 * Server operating system: Debian Jessie
 * Client operating system: Debian Jessie

#Description 

 * Tested with Firefox / Chrome

# Description

I use tags with my files but I can filter correctly my tag research with the option "does not contain".

As you can see on the screenshot I got two songs with different tags I want to get the result only with piano tag by using "does not contain" violin still the search adds this song in the result.

![issuesearchtag](https://user-images.githubusercontent.com/38939943/39571600-0d8771de-4edd-11e8-8147-d106c75cd0d7.png)

**Comment by wagnered** [comment]
@Adiatz,

The search algorithm uses the basic mysql qualifier "(NOT) LIKE" which was meant for single item not a comma separated string.   I will take a look and if too complex, I will consider it an enhancement for the next Ampache major version.

**Comment by wagnered** [comment]
Sorry, but because of the way that tags are stored, the changes  would be complex. This will be labeled as a possible enhancement.

**Comment by Adiatz** [comment]
Sorry I didn't think about that:) No problem at all.
