### ISSUE TITLE
API problem with some playlist_* actions

### ISSUE THREAD

**Issue by jones1008** [ampache/ampache#1710]
this is a follow up issue from #1707 

I just noticed that the actions "playlist_delete", "playlist_add_song" and "playlist_remove_song" don't work, when you configure your ACL as mentioned in the linked issue above...

When executing this with a normal browser after a successful handshake:
`https://<host>/server/xml.server.php?action=playlist_add_song&filter=<playlistid>&song=<songid>&auth=<API_KEY>`
it gives you a "access denied on this playlist" error even though the playlist this action is used on belongs to the user with the used apikey:
`<error code="401"><![CDATA[Der Zugriff zu dieser Playlist wurde verweigert.]]></error>`

I think [server/xml.server.php](https://github.com/ampache/ampache/blob/develop/server/xml.server.php) needs some more changes about these actions when using the XML-API without the default ACL(s).

**Comment by wagnered** [comment]
>I think server/xml.server.php needs some more changes...

Yes, It looks like the logic was originally designed for username/passphrase but assumes that the user has a valid session and ignores the passphrase. I May consider removing this method as the apikey method is much cleaner and a session should not be required.

**Comment by wagnered** [comment]
I think the api is completely working now.
link: #https://github.com/ampache/ampache/commit/62817cff014d5fa4f2dba3f1ea382afbeb70cb5e

Let me know if any problems remain.

**Comment by jones1008** [comment]
it seems to be working now!
Thanks!
