### ISSUE TITLE
[BUG] removing a catalog wont remove the records from the SQL

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1716]
hi guys,
using the latest dev build,
i found that many of the images were broken, so trying to do a cleanup i removed the catalog altogether, still, on apache, i can see the records present (i waited from 5 hours), i checked the SQL and all the records of the removed catalog are there.

question is: is there a clean up command somewhere to run from ampache ?

**Comment by wagnered** [comment]
@a7medo778 
What type of catalog did you have: local, remote or what? 
Does it remove only the songs but leaves the albums in place?
I just tested deleting a small local catalog and everything was removed from the database. NO trace of it on Ampache's album page.

Does the Ampache debug log reveal anything?

I am going to test a large local catalog. to try to duplicate your issue.

 > question is: is there a clean up command somewhere to run from ampache ?

If you can see only empty albums on the Albums page, the "Clean All" on the Show Catalogs page should remove the empty albums. I did an update on the local catalog cleaning process in commit https://github.com/ampache/ampache/commit/87310cb10ad52e55699bf0b1cfc116e58d42a7e8.

**Comment by a7medo778** [comment]
- local
- yes the tracks are not there but artists and albums still exist


the clean all did the trick 👍, i guess it was missing from the process,
thanks
