### ISSUE TITLE
Access denied to this playlist when tring to add a song using XML API

### ISSUE THREAD

**Issue by robp2175** [ampache/ampache#1720]
Trying to add a song to a playlist using the xml API and I keep getting access denied. I have the latest code. Any help is appreciated

http://serverurl/server/xml.server.php?action=playlist_add_song&auth=authidofadmin&filter=1&song=1

 * Ampache version: Latest (just downloaded today)
 * Web server + version: XAMP PHP 7.2.1
 * Server operating system: Windows 10
 * Client operating system: Windows 10

**Comment by robp2175** [comment]
Apologies, I had downloaded the latest release, but not the latest code.
Cloned the repo then ran composer install. APIs run great now.

**Comment by wagnered** [comment]
@robp2175 

Good to know..
