### ISSUE TITLE
[Question] How do you do Genre in ampache ?

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1722]
hi guys,
i been puzzled by this for some time now until i saw this picture today
[https://user-images.githubusercontent.com/1344115/30549907-4c52fd56-9c96-11e7-9c76-727a970ebef1.png](url)

so i have a fairly large collection, with tracks that belong to several Genre, how do i categorize them in ampache ? doing it via tags only doesnt seem to do the job as even the api's i cannot filter the results by tags.
so, how can i get the Genre button shown in the top toolbar in the pic ?

**Comment by wagnered** [comment]
@a7medo778 

In preferences, select interface and at the bottom is the "top menu" setting.  Then log out and back in again.   For users, it might have to be set system wide in admin/server config/interface.

In English, it is called "Tag Cloud". "Generes" should also be found on the Home/Music menu list.

**Comment by a7medo778** [comment]
so "tag cloud" = "Genres"

because i do have it enabled but can only see "tag cloud" but not Genres

**Comment by a7medo778** [comment]
Though he was using a recent build
https://github.com/ampache/ampache/issues/1603

But maybe the string was renamed

**Comment by wagnered** [comment]
> But maybe the string was renamed

Yes, @Psy-Virus regularly volunteers to work on the translations for Ampache. He uses his best judgement as to what the various translations should be. He also contributes a PR about once a month  So  although the image in #1603 doesn't show the version, it very well could be the latest version of Ampache.

**Comment by a7medo778** [comment]
hey @wagnered 
sorry for re openning the issue again, i noticed in subsonic api there are several calls that lets you specify genre in its parameters like : getSongsByGenre , getGenres, getAlbumList...etc

does it take that from the tags parameter ?

**Comment by wagnered** [comment]
@a7medo778   it depends on Ampache's configuration.  Ampache can get metadata from tags or from lastfm or other external sources that have been enabled.

**Comment by a7medo778** [comment]
In my config its only from metadata, so that “genre” parameter should comes directly from the metadata right ?

**Comment by wagnered** [comment]
metadata is the extra information in a file that describes the contents of the file.
The switch in my config file is:
'metadata_order = "getID3"`
This means that Ampache is only using the getID3 library to get the metadata from the tags in the file.
Lines 193-197 give some idea of what external sources can be add to the line(separated by commas). 

On the modules->plugins page is an extensive list of plugins that can be activated.  Most of them require keys or passwords to actually use.

**Comment by a7medo778** [comment]
Ok sounds good, and assuming i want to actually make that take effect over my current library, do i need to remove it and re add it ? Or just do a “clean all”

**Comment by wagnered** [comment]
You would need to delete and add the catalog again.  I'm not sure an update would do the job but it would take as long as adding a new catalog. And cleaning it only removes songs not attached to an album and removes empty albums.
