### ISSUE TITLE
UI Theme, inaccessible image with CSS.

### ISSUE THREAD

**Issue by davpat** [ampache/ampache#1726]
# Environment
Ampache 3.8.6-release

# Description
UI Theme, inaccessible image with CSS.
I am currently making UI Theme for my private server and I was wondering if it's was possible to add  html ID to the sidebar Image and Top-Menu Image. This would allow themes to modify the icones image.

**Comment by lachlan-00** [comment]
yes, i'm happy to make changes like this. are you still looking for this change?

**Comment by davpat** [comment]
Yup, any upgrade to the UI would be useful, or at least at the accessibility will be useful for me,

**Comment by lachlan-00** [comment]
I've had a look and themes pull icons from the theme/icons folder based on name (icon_home.png, icon_localplay.png)

If the themes folder is missing icons the server looks inside the root /images folder

Is there a reason why you couldn't just make your custom theme by putting the icon files into the theme folder? It is possible to take the images out of the ajax/ui.class process but it doesn't seem like it would be that beneficial.

**Comment by davpat** [comment]
It's been a while since I played with the CSS, so maybe it's was possible to do it that way. 
I'm not sure 100%, but I do remember having alot of trouble where it's would have been fixed by adding an ID tag to sidebar and Top-Menu Image.

I did manage to do a "fix " by using this in my CSS 
```
#topmenu_container div:nth-of-type(1) img {
	background: url(../images/icons/neon-green/topmenu-home.png) no-repeat;
}

or
#sidebar-light li:nth-of-type(1) img {
	  background: url(../images/icons/neon-green/sidemenu-home.png) no-repeat;
	  position: relative;
	  overflow: hidden;
	  width: 32px;
	  height: 32px;
	  padding: 32px 32px 0 0;
	  box-sizing: border-box;
}
```
but if we change some options or add new icons, everything kind of break.

Here an Image the UI just for fun : https://snag.gy/qDlaz3.jpg

**Comment by lachlan-00** [comment]
If you upload your theme somewhere I can probably get it working for you without having to change the code. I think the way the code is configured now it's easier to copy to a new theme folder and do all your work inside the themes.

Format would be something like:
```
/themes/davpat/ ->
                              templates ->
                                                  fonts/
                                                  default.css
                                                  davpat.css
                              images ->
                                              icons/
                                              ratings/
                              theme.cfg.php
```

Doing that you should only really have to edit theme.cfg, davpat.css and the icons you want to change.

**Comment by kuzi-moto** [comment]
Hey @davpat, were you still looking for assistance on this, or can the ticket be closed?

**Comment by davpat** [comment]
you can close it, thanks

Le mar. 25 févr. 2020 à 13:40, Kuzma Fesenko <notifications@github.com> a
écrit :
