### ISSUE TITLE
artist feat. guest information is dropped

### ISSUE THREAD

**Issue by GB609** [ampache/ampache#1728]
# Environment
 * Ampache version: 3.8.2, but also in current master
 * Concerns behaviour of Artist::check in /lib/class/artist.class.php

Assumed process:
A new local catalog has been created and the filesystem is scanned for files.
Directory structure and file pattern:
- (root)/Albumartist/Album/Artist - Title
- %A/%a - %t

Some of the songs have the following format:
Artistname feat. someGuest - songtitle.flac

These files are also tagged according to the file pattern, whichs means the artist tag is "Artistname feat. someGuest".

I expected to have "Artistname feat. someGuest" show up as Artist in any detail view of the song in question. It did not and it took me quite a while to find out why. I managed to trace the problem back to /lib/class/artist.class.php. More precisely to the following line of code:

```
// If Ampache support multiple artists per song one day, we should also handle other artists here
$trimmed = Catalog::trim_featuring($name);
```
During creation/scanning of a new catalog when songs are created from file without an artist_id or musicbrainz artist id (=filename pattern/tags are used) Artist::check is called with the value determined during file scan.
This call to Catalog::trim_featuring is hardcoded. This method just cuts of any part of the artist from the first "feat." group onwards. There is no option and, even worse, no mention of this in any "user" visible part of the application.
Regardless of whether multi-artist is supported in any way or not, this does not work the way the user might expect.

While i understand part of the reasoning, to me this behaviour is a deliberately forced drop of precious information.
I personally understand the consequence of the "artist feat. guest format" which means that grouping under the main artist does not work.

**Comment by wagnered** [comment]
Hello @GB609 
You wrote:
> This method just cuts of any part of the artist from the first "feat." group onwards.

Please give an actual example of an complete folder path including an artist and  featured guest(s).  

That will give me an idea how to structure the file path for examining the code.

Thanks...

**Comment by GB609** [comment]
The path in question is
/media/music/files/Unheilig/Unter Dampf/Unheilig feat. Helene Fischer - So wie du warst.flac

Catalog root is /media/music/files

I do group music files by artist and album, but utilize tags and filenames for more precise information.

**Comment by wagnered** [comment]
@GB609 

OK,  yes, this is by design. 

I will mark your issue as an (possible) enhancement, 

How does a "featured artist" differ from "artist" or "album artist" which are both id3 tags? Ampache stores both, but they're not linked together in the db and artists are displayed as "album artists". 

As I continue to think about a possible enhancement it seems to get more complex. I have to give it more thought.  Because enhancements and PRs are put on hold, this enhancement might need to wait until Ampache/Laravel version is developed.

Sorry...

**Comment by GB609** [comment]
Well, a "featured" artist as per my song file names or how its used as far as i can tell, in most cases, does not own any rights to the "original" song. It's just one recording/performance where they partake.

E.g: "Unheilig - So wie du warst" on and of itself - no other artists.
The version "Unter Dampf/Unheilig feat. Helene Fischer - So wie du warst" is "features" Helene Fischer because she sings a part of the lyrics, so the song does not "originate" from her.
I tend to place such an information into the regular file artist id3 tag as support for multiple artists artist tags is still not spread very widely and does not run properly with most players i have tried (even the implementation/fields used differ). If something's not supported broadly, i tend to "stick to the basics", just so that i don't have to take extra measures for every other implementation/player.
Besides, that way i can easily and quickly differentiate the song in the file system from the "original" without having to look at it with any extra tool.
As far as i'm concerned "Unheilig feat. ..." IS the track artist(s) for that special version which i'd like to see.

So the issue is more or less about 1 or 2 more general requirements:
- When ampache is configured to take song info from filenames before tags, the data that actually is placed into its metadata should adhere to the filename pattern without post-processing that changes actual data (except error handling ofc) (i did see one or two other trim_ functions too, iirc)
- The same should basically apply to tags

I think you're putting a bit too much thought into how this can be enhanced as a feature while its quite simple. Keep metadata as close to original from file/tags as possible, eventually with an option to change that behaviour to a more intelligent processing (or vice versa). Most of the time people tend to develop their own tagging and naming schema which they expect to be reflected by the tools they use. Just my opinion, though.

I also think those infos don't really need to be linked that much.
- Browse artists: If this list can also handle track artists from compilations ("various artists discs") i'd just leave it be. Theres no need to make it more complicated.
- Browsing albums: List Albums by Name and Album artist name
- Browse album contents: List Songs with artist name - the only "link" you need is which album the song is contained in. I don't think there's a need to link the artist/album artist to each other in any further way.

**Comment by mitchray** [comment]
Related to #2711 

(consolidating multi-artist issues)
