### ISSUE TITLE
Error while try to get similar artist in Last FM

### ISSUE THREAD

**Issue by djschorn** [ampache/ampache#1732]
# Environment

 * Ampache version: 3.8.6
 * Web server + version:  Apache/2.4.18 (Ubuntu)
 * Server operating system:  Linux version 4.4.0-127-generic (buildd@lcy01-amd64-020) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #153-Ubuntu SMP Sat May 19 10:58:15 UTC 2018
 * Client operating system: Windows / Firefox

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

; Recommendations
; Set this to true to enable display of similar artists or albums
; while browsing. Requires Last.FM.
; DEFAULT: false
show_similar = "true"

; Concerts
; Set this to true to enable display of artist concerts
; Requires Last.FM.
; DEFAULT: false
;show_concerts = "false"

; Last.FM API Key
; Set this to your Last.FM api key to actually use Last.FM for
; recommendations and metadata.
lastfm_api_key = "af497a1f1d3d9da184acdc4e04670660"

; Last.FM API secret
; Set this to your Last.FM api secret to actually use Last.FM for
; scrobbling.
lastfm_api_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Description

When I try to look up for similar artists => nothing in the web hmi (loading never ending...). See logs for more informations. 

# Logs

2018-06-10 12:13:49 [computer] (Recommendation) -> search url : http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&api_key=af497a1f1d3d9da184acdc4e04670660&artist=Abba&lang=fr 
2018-06-10 12:13:50 [ampache] (PHP) -> [Runtime Error] simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in file /usr/share/ampache-3.8.6/www/lib/class/recommendation.class.php(56) 
2018-06-10 12:13:50 [ampache] (PHP) -> [Runtime Error] simplexml_load_string(): 19B5 in file /usr/share/ampache-3.8.6/www/lib/class/recommendation.class.php(56) 
2018-06-10 12:13:50 [ampache] (PHP) -> [Runtime Error] simplexml_load_string(): ^ in file /usr/share/ampache-3.8.6/www/lib/class/recommendation.class.php(56) 
2018-06-10 12:14:37 [computer] (session) -> 04nmh96rrgonas5i3qsjfairo3 has been extended to Sun, 10 Jun 2018 13:14:37 +0200 extension length 3600

**Comment by djschorn** [comment]
This version does not seem to be realeased,, where can i find it ?

**Comment by wagnered** [comment]
@djschorn 

Sorry, I guess I made a typo on the wiki. Thanks for bringing it to my attention. The page has been edited to point to the correct release.

All releases can be found on the Ampache [release page](https://github.com/ampache/ampache/releases).

The instructions for backing up and upgrading can be found on the Ampache [upgrade  page](https://github.com/ampache/ampache/wiki/Upgrade)

**Comment by djschorn** [comment]
Thanks for your answer. 
So if i understand, i have the last version (3.8.6), is there a way to solve my initial problem ?

Thanks.

**Comment by wagnered** [comment]
I'm sorry again :frowning_face: for adding more confusion. Click to download [ampache-3.8.7_all.zip ](https://github.com/ampache/ampache/releases/download/untagged-8e21b414686f51d4645d/ampache-3.8.7_all.zip)

**Comment by djschorn** [comment]
404 Error on your link, i'm unlucky :(

**Comment by wagnered** [comment]
Forgetfulness and double embarrassment :cry: :cry:.  I edited the release the other day and forgot to re-publish it.

You should be able to see it now. 

Again, my apologies...

**Comment by djschorn** [comment]
I installed the last version and indeeed it works

Thanks for your help and long life to Ampache :-)
