### ISSUE TITLE
DSub not knowing its cached albums after upgrade to 3.8.7

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#1735]
# Environment

 * Ampache version: 3.8.7-release
 * Web server + version: Apache/2.4.33
 * Server operating system: Fedora 27 Kernel: 4.16.13-200.fc27.x86_64
 * Client operating system: Android 7.0

 * Client type:
   - SubSonic (DSub)

# Description

I upgraded from 3.8.6-release to 3.8.7-release as usual.

Checked the web frontend in Chrome and Firefox, all worked fine.

Then pulled up the DSub App on my phone, went to "New albums" and noticed that none of my recently cached albums are recognized as cached anymore. Also when entering the track list view of any cached albums normally the tracks would be shown as being permanently cached with a green icon on the right hand side of each track name.
Also: When entering the track list view of ANY album DSub suddenly shows the artwork from the newest album on EVERY album.

I can easily change back to the 3.8.6 version, restart DSub on the phone and the problem is gone, all my cached albums are recognized as such again. Switching to 3.8.7 again makes the problem appear again.

Let me know if I can be of anymore help.

All the best
Arno

**Comment by wagnered** [comment]
@arno1979 

Could you try the latest develop.  I made some modifications to Ampache's subsonic API  to reduce chance of network timeouts with large catalogs/playlists and failed to create the cache folders correctly.  If I understand your issue correctly, the fix should be in 3.8.8-develop.

Let me know if you still have issues...

**Comment by arno1979** [comment]
@wagnered 
Yeah, I got the latest develop installed after a bit of a hassle (had to manually run `composer update -o` multiple times to install and/or update packages). I am not used to working with composer in the ampache context. But after getting the develop to run it seems to be working fine with DSub again.
Will you publish a new release version soon containing the fix? I would prefer to use a release version but also would like to have the latest bugfixes from the 3.8.7

Thanks!

**Comment by wagnered** [comment]
The bug fixes are accumulative.  3.8.8 contains bug fixes that was added to every previous version of Ampache.  Take a look at docs/CHANGELOG.md to see all the changes that the current develop version contains.

Ampache-3.8.7 was released less than 30 days ago. I'll probably release 3.8.8 at the end of this month.

Congratulations, by learning to install the latest develop branch, you now have all the latest and greatest features and fixes when you want.  :triumph::purple_heart:

**Comment by arno1979** [comment]
@wagnered 
Alright, thanks for the info. :-)

**Comment by arno1979** [comment]
@wagnered 
Thanks for the 3.8.8 release. Just installed it, all works fine!
