### ISSUE TITLE
Docker Image on hub.docker.com/r/ampache/ampache does not auto build

### ISSUE THREAD

**Issue by zerodogg** [ampache/ampache#1741]
The docker image is unmaintained and hasn't been updated in over a year. It also ships its own builtin mysql-instance, and doesn't use the upstream php docker images as a base. I've forked it and started maintaining a replacement container (that can be paired with the `mariadb` image for a database, reducing the cruft and maintenance of the ampache container itself) that I've rebased upon the official PHP container - https://gitlab.com/zerodogg/ampache-docker and https://hub.docker.com/r/zerodogg/ampache-apache/.

I'd like to suggest this be made the new offical image, as it's a much cleaner setup. I'm also willing to maintain it (it can't directly replace the image on dockerhub though, as it's not compatible, so a new repo would be needed to avoid breaking anyone using it already).

This image also fixes many of the issues opened against the current image like ampache/ampache-docker#19 ampache/ampache-docker#20 ampache/ampache-docker#16 (ampache/ampache-docker#15)

**Comment by Jucgshu** [comment]
Awesome! This is great news @zerodogg 

Can't wait to see a ~~~proper~~~ maintained Docker image for Ampache.

-j

**Comment by davpat** [comment]
Sick!

**Comment by juanluisbaptiste** [comment]
@zerodogg Excellent news man, it's great that someone is stepping up to maintain this docker container.

One question, have you thought on moving the repository to github ? it would be easier to collaborate to the project without having to open an account on gitlab for that. I was hoping to create a PR with a docker-compose file and then realized the project is hosted in gitlab :-/

At least a mirror repo in github that you could merge to your gitlab repo (using the github repo as a remote origin of your gitlab repo).

Just my 0.02$

**Comment by lachlan-00** [comment]
@zerodogg github is where ampache will stay. 

If you would like to maintain it i can add you as a developer on the ampache-docker repo? that way it's maintained in the organization.

**Comment by lachlan-00** [comment]
fyi @vollmerk this should be brought into the org. will email you.

**Comment by zerodogg** [comment]
@lachlan-00 I'd be happy to move it to the github org. There's still the issue of it not being compatible with the old docker image, though, so we're going to need a new dockerhub image (and/or just keep the zerodogg one. I'll be leaving that in place either way since there are people using it right now, and keeping requires zero work).

**Comment by lachlan-00** [comment]
The old image hasn't been updated for 2 years and seems to be only used by people trying it then failing to get it working. Not that that is 100% correct but it's just not recent enough to keep.

I would actually prefer to make a break now that we both have time to work on it and direct everyone to the official image keeping your original repo open.

**Comment by Sapphirecode** [comment]
I built a new Image from https://github.com/ampache/ampache-docker
it seems to work just fine, except for the Subsonic api.
To fix that one issue I added this line to the Dockerfile
`RUN for f in rest play channel; do mv /var/www/$f/.htac* /var/www/$f/.htaccess; done;`
Now I have a solid instance of ampache running in Docker.
why doesn't the Image on the docker hub just get updated with the current state of the Git repo then

**Comment by lachlan-00** [comment]
Because I don't have access to the docker hub account.
The hub account needs to update it's hooks for the repo which I can do as an admin in the Ampache repo but I can't find who owns the docker account to update it.

**Comment by lachlan-00** [comment]
Follow the docker repo issue 27 if you want to keep updated on that

**Comment by lachlan-00** [comment]
looks like i can publish packages directly in github though
https://github.com/ampache/ampache-docker/packages

That might be a good stop gap

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache-docker/packages

I'm just building an image targeting develop code now.

**Comment by lachlan-00** [comment]
I've updated the docker builds and we now have packaged images for docker users. I'll update the title of this to reflect that hub images are out of date and we'll see if we can get a hold of someone with access. (https://github.com/ampache/ampache-docker/issues/27)

To run the current Ampache master (stable) branch
```
docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 80:80 docker.pkg.github.com/ampache/ampache-docker/ampache:latest
```
To run the current Ampache develop branch
```
docker run --name=ampache -d -v /path/to/your/music:/media:ro -p 80:80 docker.pkg.github.com/ampache/ampache-docker/ampache:develop
```
It's not not recommended to use the https://hub.docker.com/r/ampache/ampache image as it is out of date and unable to be updated at this time.

**Comment by lachlan-00** [comment]
So it looks like by adding my personal repository to docker hub has reenabled the auto builds in the official channel!

This is finally Fixed!!
![image](https://user-images.githubusercontent.com/1305249/68826517-fec9b500-06e9-11ea-8d22-c217a49abd09.png)
