### ISSUE TITLE
FR: Better metadata handling with local play

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1742]
Hi

I use localplay with Mpd quite a bit, it works fine but one thing is that my Mpd does not get any metadata to display except the file name see Ncmpcpp's display

```
Artist        Track Title                               Album     Time   
─────────────────────────────────────────────────────────────────────────
Dublicator    02    Normalized Perceptions              Normalize -:--   
<empty>             Dublicator%20-%20Spore.mp3          <empty>   -:--   
```

As you see only the current playing song has data but others in the list does not have any data to show.  It would be nice if this metadata is improved a bit.

thanks

**Comment by wagnered** [comment]
I did some research on the Mpd documentation and found this statement:
>When scanning or playing a song, MPD parses its metadata. The following tags are supported: 

And lists all the tags it supports.

And from the Ampache log when sending over the list of songs the following info is added to the playlist:
> 2018-06-22 13:57:35 [admin] (stream_playlist.class.php) -> Adding url {{"properties":["url","title","author","time","info_url","image_url","album","type","codec","track_num"]}}... 

So, It appears that Mpd is ignoring the information when it is placing the information in the play queue and only getting the metadata when it plays the file.

**Comment by gerroon** [comment]
@wagnered 

Thansk for looking into it. As I understand from what you say,  it is Mpd that is disregarding it until it plays.

Do you think it is possible to contruct a proper playlist( like an m3u which Mpd likes) and then submitting that to Mpd would make a diff, instead of sub,mitting each song individually?

**Comment by wagnered** [comment]
@gerroon 

I played around with mpd/mpc but could not get an  mp3u playlist loaded.  I'll mark this as an enhancement, but with no promises.  If you would like to play around with mpc or even Curl to see what it would take to remotely get a playlist loaded, I'd appreciate your efforts.  Right now, my progress on the new version of Ampache is accelerating and I don't want to let up.
