### ISSUE TITLE
Url field is missing

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1746]
I was trying to add a new catalog to my Ampache but I realize that I am missing the url entry field box, so it is not possible to add a new catalog it seems. I tried all types in the dropdown, and all seems to miss it.

Ampache 3.8.8 Debian Testing 
PHP 7.2.4-1+b2 (cli)
Apache/2.4.33
mysql  Ver 15.1 Distrib 10.1.29-MariaDB

**Comment by wagnered** [comment]
@gerroon 
If there is no url/file path, etc inputs at the bottom when you switch to local, or remote catalog type, It means that the javascript files aren't being loaded or javascript is disabled in the browser.

**Comment by gerroon** [comment]
See the image please. I tried with 2 different browsers (Firefox, chrome) 
![_duzensiz_](https://user-images.githubusercontent.com/8519469/42790935-26cc25e6-8933-11e8-8100-e496cd521a09.jpg)

**Comment by wagnered** [comment]
The image looks normal to me.  When Catalog Type shows [select] there will be no inputs for url or local path. "Remote" or "Local" catalog type must be selected.

Catalog Type "local" is the default type and is enabled on installation.  If no catalog types are on the drop down list, perhaps all catalog types might have become disabled in Modules->Catalog Modules, 

I just checked my installation of 3.8.8-release and all works well.

**Comment by gerroon** [comment]
Yes that is what I am saying, selecting any of those wont give me any aditional urls.  See the image

![Uploading Selection_029.jpg…]()

**Comment by wagnered** [comment]
What image?  The above message i received in my email had what seemed like a link, but no image.

I noticed that your system is using php-7.2.  Ampache hasn't been tested with php-7.2 so perhaps there is a problem with that.

Please enable ampache debug logging. Mayb it will reveal something.

**Comment by gerroon** [comment]
Not sure, the image is attached here, if not

https://user-images.githubusercontent.com/8519469/42791682-7930a89e-8937-11e8-82a4-a6cdb7b19d80.jpg

**Comment by wagnered** [comment]
I just installed php-7.2 and tested this issue with no problems.

Just to check: enter about:config into the address bar and press enter.
in the search box look for javascript.enabled and make sure it's set to true.

Script and ad blockers might prevent javascript from running.

**Comment by gerroon** [comment]
@wagnered 
Thanks, I am glad to hear the default install has no issues. I will look into this.

**Comment by wagnered** [comment]
@gerroon 

I apologize for not responding sooner.  I have been very busy as the only active developer.

Has this issue been resolved?

**Comment by gerroon** [comment]
It seems fixed.
