### ISSUE TITLE
Ampache fails with Mysql > 8.0

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#1758]
For the record.
Servers > 8.0 use a different authorization plug-in by default.  PHP hasn't released a module that can  properly respond to this plugin.

It is necessary to get the server to use the native password plugin by adding the following switch to my.cnf:
`default_authentication_plugin=mysql_native_password`.

**Comment by lachlan-00** [comment]
Not sure what has happened but now with the latest mysql you also need to reset the password to allow auth in legacy auth mode.

Tested successfully using mysql 8 from the oracle official repo
```
root@steam:~# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 615
Server version: 8.0.16 MySQL Community Server - GPL

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'PASSWORD;
Query OK, 0 rows affected (0.05 sec)

mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.01 sec)
```
