### ISSUE TITLE
Install AWS Linux Server

### ISSUE THREAD

**Issue by fconejerose** [ampache/ampache#1759]
No working
1) Apache has mod_rewrite enabled
2) Download the installer (tar or git)
3) Its the only server in apache, does not use Virtual server
And Not work:

ec2-18-232-140-48.compute-1.amazonaws.com no puede procesar esta solicitud en este momento.
HTTP ERROR 500

????
someone has installed in a aws linux server?

Thanks a lot

**Comment by wagnered** [comment]
Hello @fconejerose 

Did you follow the installation instructions at the [Ampache Wiki](https://github.com/ampache/ampache/wiki/Installation)? It is necessary to install and run **Composer** if you tried to install the tar file.  That package is the develop version.

I suggest that you download the Ampache-3.8.9_zip file from the [Ampache Release page](https://github.com/ampache/ampache/releases).  This is a release package and is a complete self-contained package. No additional preparation is needed other than the pre-requisites: web server, PHP > 5.6 and < 7.2 and  mysql.

**Comment by wagnered** [comment]
Has this issue been resolved.  I am not familiar with the Amazon AWS.
