### ISSUE TITLE
[develop] Not able to start channel

### ISSUE THREAD

**Issue by Tetram76** [ampache/ampache#176]
Hi,
I'm "playing" with channel but I can't start them.
What I've done:
- build a playlist (with a lot of songs, don't know if it could be a problem)
- create a channel based on this playlist:
  ![image](https://cloud.githubusercontent.com/assets/7486827/2954298/95cba286-da6f-11e3-9e05-4ecd0c468a93.png)
- seeing the status of the channel is "stopped" I try to click on "start" button... but absolutly nothing happens

nothing in the log while I activated it:

``` php
debug = "true"
debug_level = 2
```

Looking at the code, I found that transcode must be enabled, so I activated it:

``` php
transcode_m4a      = required
transcode_flac     = required
transcode_mpc      = required
transcode_mp3      = allowed
transcode_wav      = required
encode_target = mp3
transcode_player_customize = false
transcode_cmd = "avconv -i %FILE%"
encode_args_mp3 = "-vn -b:a %SAMPLE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %SAMPLE%K -c:a libvorbis -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %SAMPLE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %SAMPLE%K -c:a pcm_s16le -f wav pipe:1"
```

even like this, I can't make a channel "started"

and if I run 

``` shell
php bin/channel_run.inc -c 3
```

I got this error

```
Starting Channel...
        - Channel 3
PHP Fatal error:  Call to a member function get_random_items() on a non-object in /var/www/ampache/lib/class/channel.class.php on line 281
Listening on 127.0.0.1:8201
```

Did I miss something ?

**Comment by carlosaraya** [comment]
Hello, I have the  Ampache 3.9.0 version, and I'm having the same problem y cant get a channel started.
