### ISSUE TITLE
some catalog works stops immideatly after closing browser window

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#1766]
# Environment
Ampache version: 3.8.9-release
Web server + version: apache 2.4 / Php 7
Server operating system: Synology DSM 6.2
Client operating system: W10
# Client type:
Web
Ampache
# Settings
large local catalog

# Description
"Veryfy" and "clean" are stopping when the browser window will be closed. i can't discover some suspicious things In the ampache log file, that will explain what happend. just shows the last entry that was worked.
When i let open the window long enough, the catalog work will be successful end.

"add" will work even if i close the browser window.

Maybe its related to the issue that i couldn't get the  catalogs tasks working from the command tool (catalog_update.inc) 

# Logs

**Comment by noyse27** [comment]
i tried to run this as cron - does not work
i tried it to start via command shell (ssh'd into Nas) after 2sec it stopped -no entry in logfile
i used  `php catalog_update.inc -a`

**Comment by wagnered** [comment]
@noyse27 

Sorry to take so long to get back to you on this.
> i tried it to start via command shell (ssh'd into Nas) after 2sec it stopped -no entry in logfile

Are you still having a problem with this? If you are, here are some items to check.

Did you stay ssh'd into the NAS while it ran? If you want to exit the ssh session enter the command with the ampersand (&) at the end:  `php catalog_update.inc -a &`. It will run the command in the background and won't stop if you exit out of the ssh'd session.

Enable `log_errors = On` switch in /etc/php.ini.  The Apache server will need to be restarted. Sometimes there's php error that Ampache can't report.

**Comment by noyse27** [comment]
yupp i stayed ssh'd - when i started the script i had opened the logfile in parallel. and there is no entry that indicate what kind of error the script prevents from beeing executed

Maybe its also  that the synology has a very special enviroment. with th enew dsm its fairly complicated to modify the apache settings. but at the end ampache is running and can be used :)
