### ISSUE TITLE
Did you delete 3.8.9 release ?

### ISSUE THREAD

**Issue by max-k** [ampache/ampache#1768]
Hi,

Did you remove release zip for ampache 3.8.9 or has it never been available ?

Is it still Ampache current stable release ?

My AUR package doesn't work anymore and I don't know if I have to downgrade it.

Thank you very much.

**Comment by wagnered** [comment]
@max-k 

My apology...  I made a change and must have left 3.8.9 in "draft mode".   In draft mode, I'm the only one who can see it. :frowning: 

It is again published and accessible by the public.

Again, Sorry....
