### ISSUE TITLE
External music sharing instead of local music sharing (Raspberry PI)

### ISSUE THREAD

**Issue by electro575** [ampache/ampache#1771]
Hi all,

I'm using ampache server on my raspberry pi on raspbian.

I opened a port to have access to ampache server.

So, in 192.168.X.X it's good, power ampache application arrived to listen music.

But now, if i connect the server with an external adress (srv.domaine.org), power ampache application have the music without picture album.

When i try to listen a music, the application freeze and i must restart it.

What is the option to listen the music by external adress instead of local adress ?

Thanks a lot

**Comment by wagnered** [comment]
@electro575 

> I opened a port to have access to ampache server.

Is this port on the Raspberry PI or the router or both?  The router must have port forwarding from "srv.domaine.org" to the internal address of the Raspberry PI.

> When i try to listen a music, the application freeze and i must restart it.

This has nothing to do with setting any Ampache options. By "application" do you mean the Ampache server on the Raspberry or  Power Ampache?  If it's the Ampache server, then the problem might be not enough memory on the Raspberry.

Maybe someone who has successfully set up Ampache on a Raspberry will offer their suggestions. I changed the title of your issue to attract the attention of Raspberry users.

**Comment by electro575** [comment]
> Is this port on the Raspberry PI or the router or both? The router must have port forwarding from "srv.domaine.org" to the internal address of the Raspberry PI.

I opened the same port for router and raspberry pi.

> By "application" do you mean the Ampache server on the Raspberry or Power Ampache?

Application is android application whose Power Ampache. I don't know if it's a memory raspberry pi problem !

**Comment by wagnered** [comment]
I can't help you with Power Ampache: It is a "3rd party" application.

I suggest you set up the [subsonic API](https://github.com/ampache/ampache/wiki/API#subsonic-api) on the Ampache server and use a subsonic client (DSub, Subsonic, Ultrasonic on Android). The subsonic api is used by many to access their music.  Also, the subsonic clients have many more features than power ampache.

If the Subsonic clients give you a problem, then the problem might be with the Ampache server or the Raspberry.

**Comment by wagnered** [comment]
@electro575 

Has this issue been resolved?
