### ISSUE TITLE
Empty string in translation

### ISSUE THREAD

**Issue by prschopf** [ampache/ampache#1776]
I have found an empty string to translate and its impossible:

![transl](https://user-images.githubusercontent.com/16743256/45425000-80e5c600-b66e-11e8-816c-b65f4442bcb0.jpg)

You may find this empty string in [Transifex](https://www.transifex.com/ampache/ampache/dashboard/)

**Comment by wagnered** [comment]
@Psy-Virus 

What's the status of this issue?

Not trying to hurry you, just want to go through the issues to respond or close them.

**Comment by prschopf** [comment]
Nothing about that?

**Comment by Psy-Virus** [comment]
Sry I was busy in the last weeks and will be for some more.
But I'll take a look into it.
But for now, simply leave it blanc and save it as blanc string, if possible.

:)

**Comment by Psy-Virus** [comment]
Seems like some variable processing in the `gather-messages.sh` file produced this behaviour.
I don't know why and I honestly don't want to dig through it right now. I expect it to be an as NULL declared NOTNULL field in my database or something like that. So the script thinks there's something in the variable even if it's not. Weird stuff. I probably would have to implement something that checks if the var actually has letters and/or numbers in it.

It also could be some weird encoding issue.

Anyway I fixed it and will push a PR with the fix and updated translations in the next hour.

:)

**Comment by Psy-Virus** [comment]
Hmmm, I guess the phrase "Fix for #issue" doesn't close related issues :(

**Comment by prschopf** [comment]
Solved, thanks!
