### ISSUE TITLE
cli operations on dropbox catalog do nothing

### ISSUE THREAD

**Issue by ftoledo** [ampache/ampache#1777]
# Environment

 * Ampache version: 3.8.9-develop
 * Web server + version: Nginx 1.10 
 * Server operating system: Debian Stretch
 * Client operating system: GNU/Linux
 
# Description

I just run catalog_update cli tool on dropbox remote catalog and the script finish inmediately without any info at the debug log.
```
tom:/home/ampache/html# php bin/catalog_update.inc dropbox -a -v -c

----------------------------------------------------------
Iniciando operaciones de catálogo...
	- Añadiendo nuevos medios a catálogo/s
	- Verificando catálogo/s
	- Limpiando catálogo/s
----------------------------------------------------------

tom:/home/ampache/html# echo $?
0
```
None of the above actions do the job. This task work if trigger via web client.

# Expected behavior:

The actions add / clean/ verify / etc.. must be run like another catalog types.

**Comment by wagnered** [comment]
@ftoledo 

If you run `php bin/catalog_update.inc dropbox -h` you see that it is asking for a catalog **name,** not  catalog **type.** 

The `bin/catalog_update.inc dropbox` command is hard-coded to  local catalog types.  It probably was created before the Dropbox catalog module was added.

I'll take a look to see how much work it will take to modify the existing command to include other catalog types. If I can easily do the changes, I'll commit them to the develop branch, but I don't know when the next release will be.

**Comment by wagnered** [comment]
@ftoledo 

I've made the `bin/catalog_update.inc` command much more versatile.  It can process catalogs by catalog name and/or catalog type.

Run `bin/catalog_update.inc -h` to see all the switches.

The changes have been pushed to the develop branch.

**Comment by ftoledo** [comment]
> @ftoledo
> 
> If you run `php bin/catalog_update.inc dropbox -h` you see that it is asking for a catalog **name,** not catalog **type.**
> 
> The `bin/catalog_update.inc dropbox` command is hard-coded to local catalog types. It probably was created before the Dropbox catalog module was added.
> 
> I'll take a look to see how much work it will take to modify the existing command to include other catalog types. If I can easily do the changes, I'll commit them to the develop branch, but I don't know when the next release will be.

Hi @wagnered, thanks for the reply, i use the catalog name "dropbox" not the type.

![captura de pantalla_2018-09-24_10-23-21](https://user-images.githubusercontent.com/95441/45954618-e24d5380-bfe3-11e8-98d1-5586b69a92e4.png)

i will pull and test again! thanks!

**Comment by ftoledo** [comment]
Fixed! it's work with name (-n) or type(-t) now. Thanks!
