### ISSUE TITLE
Invalid configuration settings Error: Config files not found or unreadable for ampache.cfg.php

### ISSUE THREAD

**Issue by chenmingzhang** [ampache/ampache#1779]
# Environment

 * Ampache version: 3.8.9, 3.8.8
 * Web server + version:
 * Server operating system: debian 8
 * Client operating system:

 * Client type:
   - Web
   - Ampache 3.8.9
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

when i download the file and run setup, it keeps on saying 

config/ampache.cfg.php action  download write

config/ampache.cfg.php exists? error

config/ampache.cfg.php configured? error

when i go to config there is only 
ampache.cfg.php.dist  motd.php.dist  registration_agreement.php.dist

and no ampache.cfg.php

even if i click 'download'
it says in red

Invalid configuration settings
Error: Config files not found or unreadable

# Logs

**Comment by wagnered** [comment]
@chenmingzhang 

>when i download the file and run setup, it keeps on saying

>when i go to config there is only

I'm not sure what  you mean by "run setup"? It looks like you are using someone's installer? If you are, you will need to need to consult the creator of the installer.

Is this a new installation?  When you set your browser to the Ampache URL, it should first display a page to set system language. After Ampache puts you through the initialization pages, it will create "ampache.cfg.php" then bring you back to the login page.

Did you install the release version [ampache-3.8.9_all.zip](https://github.com/ampache/ampache/releases/tag/3.8.9) or the  develop version(*.zip or *.gz). The develop versions need to have compose installed and run before setting a web browser to the URl of the installation.

The release version already has the composer packages installed.  See [Requirements](https://github.com/ampache/ampache/blob/develop/README.md#requirements) for the Ampache dependencies.The only other preparation required it to set the document root of your web server.

**Comment by chenmingzhang** [comment]
thanks for the reply, turns out, i will need to put in password  to allow auto generation of config/ampache.cfg.php. i did not put anything in the password box and the error appeared did not indicate this was due to not put in a password. now things are working as a charm.
