### ISSUE TITLE
Direct folder download without renaming and include non music files?

### ISSUE THREAD

**Issue by gambra** [ampache/ampache#1781]
Hey, I'm testing out Ampache for use in a music archive and it's looking nice so far. I just have one question about the file download option. Is it possible that when you download an album it will just download a ZIP file of the entire folder the album is in without renaming it or any of the files? I would also like for the ZIP to include any non music that's in the folder (such as JPG files, PDF's, TXT files etc) as they're part of that album too.  So for example I have an album folder like: 

/home/gambra/music/AlbumFolder
->01.flac
->02.flac
->AlbumInfo.txt
->AlbumCover.jpg

I want the ZIP to be a direct copy of that structure and contents without any renaming or changing of files.

**Comment by wagnered** [comment]
@gambra 

Sorry to take so long to respond...

Not in the current version of Ampache. 

I have marked this as an enhancement to be **considered** for the next generation Ampache.
