### ISSUE TITLE
API for Streaming urls not playing

### ISSUE THREAD

**Issue by rinav** [ampache/ampache#1782]
# Environment

 * Ampache latest:
 * apache:
 * ubuntu 18.04:

 * Client type:
   - Web
   - Ampache

# Settings
The default ones. The only thing I changes is enable the streaming toggle from the admin module

# Description
I am building an Android App, which should play streaming audio from Ampache, preferably adaptive audio stream. The audio files might be of 10-20 minutes long.

I am looking at -> [API-Docs](https://github.com/ampache/ampache/wiki/XML-API) url for pulling audio url
e.g. `/ampache/server/xml.server.php?action=songs&auth=xxx`

I consume the audio urls from the above api and pass on to Exp-Player which should stream the audio. However the returned urls are in .mp3 files and does not look like a streaming url. Moreover it does not play the audio nor does it gets played in VLC. But Ampache is able to play the audio from web if I toggle the dropdown to localPlay

How do I make sure the api exposes proper url and that I can consume it in my app. 
Are there any configs which needs to the added to the config file.

**Comment by wagnered** [comment]
Hello @rinav 

Sorry to say that no Ampache api access provides streaming. A third-party streaming service such as Icecast would be required.

Ampache is capable of streaming with channels, broadcasts and radio (live streams), but not by remote control.

I added the "Enhancement" tag to explore the possibility of adding this feature to the next generation Ampache.
