### ISSUE TITLE
sometimes ampache did not take covers from tag

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#1785]
# Environment

Ampache version: 3.8.9-release
Web server + version: apache 2.4 / Php 7
Server operating system: Synology DSM 6.2
Client operating system: W10
Client type:
Web
Ampache
Settings
large local catalog

 * Client type:
   - Web
   - Ampache
 

# Settings

# Description

sometimes Ampache add Albums but without the covers that are emmbed in the tag. it also will not add them via search for all covers.
Adding covers manually to more than two or three albums is very awkward :( the function update from tags will not read the covers from the tag too. is there a possibility to add covers fast when they are not recognize by Ampache?
# Logs

**Comment by noyse27** [comment]
@wagnered 

it seems that the "search for covers" action from the catalog menu breaks after 5 min . all other actions working till the end.
 is there any possibility to add a coversearch in the tag when i use "update from tag" this would be very helpful. all th eother tools that i have recognize the tag embedded covers correctly :(

**Comment by wagnered** [comment]
> it seems that the "search for covers" action from the catalog menu breaks after 5 min.

In php.ini there are some switches that may be limiting the time. The defaults seem to be:
`max_execution_time = 2440` # which is nearly 5 minutes
`max_input_time = 60`
If  `max_execution_time` is set to 0 it will be unlimited.

**Comment by noyse27** [comment]
i raised all the mentioned configuration entries but it didnt work - after ~ 5 min the cover gathering stops working :(

**Comment by noyse27** [comment]
i wrote a small raw script which i run as script now. it gather only art from albums that have no arts and it works fine and lasts only a few minutes:

this is the logic im using
`$sql = "select id from album where id not in (select object_id from image where object_type = 'album')";
$db_results = Dba::read($sql);
while ($row = Dba::fetch_row($db_results)) {
    //gather cover art for this albums
    $catalog = Catalog::create_from_id(1);
    $catalog->gather_art_item('album',$row['0']);`

i also add this
`<?php
$catalog = Catalog::create_from_id(1);
$catalog->gather_art_item($type, $object_id);
?>`
to the "update from Tags" logic so its very easy to add covers for single item :)

nevertheless thx for your help
