### ISSUE TITLE
Cannot connect using Subsonic client over internet

### ISSUE THREAD

**Issue by umutyazgan** [ampache/ampache#1786]
# Environment

 * Ampache version: 3.8.9-develop
 * Web server + version: Apache 2.4.25-3+deb9u5
 * Server operating system: Raspbian Stretch on Pi Zero
 * Client operating system: Android 7.1.1

 * Client type:
   - SubSonic : Subsonic Music Streamer 4.7

# Settings

https://gist.github.com/umutyazgan/ab9019c9c1f37a904343b94040069cfa

# Description

I cannot connect to my Ampache server running on my Raspbbery Pi Zero from Subsonic Android application over internet. In my home network, it connects with no issues at all. However if I try to connect outside of my home network, using my external IP address, it client cannot connect and gives this error: "A network error occurred. Please check the server address or try again later." I can use the web interface from outside my local network and play songs from there without any issues. I feel like I'm missing something obvious here.

I also tried another client: Power Ampache. It can connect to my server over internet, can browse my music, but cannot play any songs. Tracks do not start playing and the bottom bar shows absurd track lengths like "8375:06".

# Logs

https://gist.github.com/umutyazgan/6424ce444795dd1b67fe79da640b385c

**Comment by wagnered** [comment]
@umutyazgan 

Did you copy .htaccess.dist to .htaccess in the following folders?

- play
- server
- rest

Please follow the [Subsonic API](https://github.com/ampache/ampache/wiki/API#subsonic-api) instructions.

Also read the Apache User section which follows the Subsonic API information: rewrite_module must be enabled.

After making sure that Ampache and Apache is set up correctly, please feel free let us know if there are any more problems.

**Comment by umutyazgan** [comment]
Well, I feel like an idiot right now. After spending a whole saturday on this, it turns out all I need to do was to forward port 80 in router settings. Subsonic seems to be working right now (Power Ampache is still broken though).

Sorry for wasting your time and thanks for the answer.
