### ISSUE TITLE
Get similar tracks not working

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1787]
# Environment

 * Ampache version: Ampache 3.8.9-develop
 * Web server + version: Apache 2.4.34
 * Server operating system: Debian testing
 * Client operating system: Debian testing

 * Client type:
   - Web
   - Ampache

# Settings

Only including portion that enables this.

; Recommendations
; Set this to true to enable display of similar artists or albums
; while browsing. Requires Last.FM.
; DEFAULT: false
show_similar = "true"

# Description

When ampache tries to get a list of similar songs the API call is not correct so no results are returned. The artist needs to be included as per the API instructions at: https://www.last.fm/api/show/track.getSimilar

The current call being made is :  http://ws.audioscrobbler.com/2.0/?method=track.getsimilar&api_key=9f7e4585a9afdcc97f8433f1f0aab978&track=Anything%20To%20Say%20You%27re%20Mine&lang=en

Note that get similar artists is working.

The call is reference in: lib/class/recommendation.class.php, server/index.ajax.php and lib/class/subsonic_api.class.php

# Logs

2018-10-07 11:02:13 [stebe] (Recommendation) -> search url : http://ws.audioscrobbler.com/2.0/?method=track.getsimilar&api_key=9f7e4585a9afdcc97f8433f1f0aab978&track=Anything%20To%20Say%20You%27re%20Mine&lang=en

**Comment by stebe** [comment]
I'm not a coder so cannot make a pull request but I believe I found out the code that needs to be changed. 

In server/index.ajax.php line 97 should be like this:
           $songs   = Recommendation::get_songs_like($media_id, $_REQUEST['media_artist'], 3);

In lib/class/recommendation.class.php 

line 128 should be something like:
  public static function get_songs_like($song_id, $artist_id, $limit = 5, $local_only = true)


lines 135 to 142 should something like: 

       $artist = new Artist($artist_id);
        $song = new Song($song_id);

        if (isset($song->mbid)) {
            $query = 'mbid=' . rawurlencode($song->mbid) . '&artist=' . rawurlencode($artist->name);
        } else {
            $query = 'track=' . rawurlencode($song->title) . '&artist=' . rawurlencode($artist->name);
        }

I'm not sure what needs to be changed in lib/class/subsonic_api.class.php

**Comment by wagnered** [comment]
Thanks,

I'm looking at it now and am coming to a similar conclusion.

**Comment by wagnered** [comment]
@stebe 

What Subsonic client you are using and how do I get to the "similar songs" menu item?

In DSub, I can get the "Similar Artists" menu", but not the "Similar Songs" menu.  But, "Similar Artists" gives me "No Data". which is wrong for the artist who's music I am playing.

**Comment by stebe** [comment]
I haven't tried anything with subsonic, just with the Ampache web interface. I just tried with DSub and I get the same results you are getting.

**Comment by wagnered** [comment]
I guess that your referencing subsonic class, caught me off balance.

I vaguely remember working on this a while back, but I'm not sure what for.

Also, many of my albums have Musicbrainz id's so it took me awhile to find some albums without mbid's for testing.

I pushed the changes to the develop branch.

**Comment by stebe** [comment]
Changes are working. Thanks @wagnered
