### ISSUE TITLE
Cannot authenticate after creating API key

### ISSUE THREAD

**Issue by nearwood** [ampache/ampache#1791]
# Environment

 * Ampache version: Ampache 3.8.9-develop (also Ampache 3.8.6-develop)
 * Web server + version: Apache 2.4.35-1
 * Server operating system: Arch 4.18.14
 * Client operating system: Postman Win7

 * Client type:
   - XML-API

# Settings

`diff --unchanged-line-format= --old-line-format= --new-line-format='%L' /srv/http/ampache/config/ampache.cfg.php.dist /srv/http/ampache/config/ampache.cfg.php`

```
http_port = "80"
web_path = "/ampache"
database_hostname = "localhost"
database_port = ""
database_name = "xxx"
database_username = "xxx"
database_password = "xxx"
secret_key = "xxx"
session_length = "172800"
stream_length = "172800"
remember_length = "2419200"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "1"
access_control = "true"
write_id3 = "false"
write_id3_art = "false"
additional_genre_delimiters = "[/]{2}|[/|\|\|,|;]"
catalog_playlist_pattern = "m3u|pls|asx|xspf"
track_user_ip = "true"
waveform = "false"
waveform_color = "#FF0000"
tmp_dir_path = "/tmp"
generate_video_preview = "true"
use_auth = "true"
sociable = "false"
memory_cache = "true"
album_art_min_width = 128
album_art_max_width = 2048
album_art_min_height = 128
album_art_max_height = 2048
resize_images = "true"
statistical_graphs = "true"
podcast = "true"
debug = "true"
debug_level = "5"
log_path = "/srv/http/logs"
site_charset = "UTF-8"
max_bit_rate = "192"
min_bit_rate = "128"
transcode_m4a = "required"
transcode_flac = "required"
transcode_mpc = "required"
transcode_ogg = "allowed"
transcode_wav = "required"
transcode_mp3 = "allowed"
transcode_avi = "allowed"
transcode_mkv = "allowed"
transcode_mpg = "allowed"
encode_target = "mp3"
encode_video_target = "webm"
transcode_player_customize = "1"
transcode_cmd = "ffmpeg"
encode_args_mp3 = "-vn -b:a %SAMPLE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %SAMPLE%K -c:a libvorbis -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %SAMPLE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %SAMPLE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %SAMPLE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
```

# Description

I believe everything was working fine until I created an API Key for a user. Now I am not able to properly authenticate via the XML API. Each `handshake` attempt results in a HTTP 200 response, but with an empty `auth` tag:

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
    <auth>
        <![CDATA[]]>
    </auth>
    <api>
        <![CDATA[380001]]>
    </api>
    <session_expire>
        <![CDATA[2018-10-20T22:09:05-04:00]]>
    </session_expire>
    <update>
        <![CDATA[2017-03-16T16:43:34-04:00]]>
    </update>
    <add>
        <![CDATA[2017-11-08T11:00:39-05:00]]>
    </add>
    <clean>
        <![CDATA[2017-03-16T16:39:32-04:00]]>
    </clean>
    <songs>
        <![CDATA[8075]]>
    </songs>
    <albums>
        <![CDATA[938]]>
    </albums>
    <artists>
        <![CDATA[601]]>
    </artists>
    <playlists>
        <![CDATA[0]]>
    </playlists>
    <videos>
        <![CDATA[0]]>
    </videos>
    <catalogs>
        <![CDATA[1]]>
    </catalogs>
</root>
```

# Logs

```
2018-10-18 22:10:05 [ampache] (API) -> Handshake Attempt, IP:192.168.1.1 User:xxx Version:350001
2018-10-18 22:10:05 [ampache] (API) -> Login Attempt, IP:192.168.1.1 Time: 1539914988 User:xxx (6) Auth:51e85b7a1734916d79fd73ce6e7e7d11906ccde9d4ff91bbb36afa1b85c478ec
2018-10-18 22:10:05 [ampache] (Dba) -> Error: ["23000",1062,"Duplicate entry 9759c54409c524131bd419b17bde2126' for key 'PRIMARY'"]
2018-10-18 22:10:05 [ampache] (Dba) -> Error: ["23000",1062,"Duplicate entry 9759c54409c524131bd419b17bde2126' for key 'PRIMARY'"]
2018-10-18 22:10:05 [ampache] (Dba) -> Error: ["23000",1062,"Duplicate entry 9759c54409c524131bd419b17bde2126' for key 'PRIMARY'"]
2018-10-18 22:10:05 [ampache] (Dba) -> Error: ["23000",1062,"Duplicate entry 9759c54409c524131bd419b17bde2126' for key 'PRIMARY'"]
2018-10-18 22:10:05 [ampache] (session) -> Session creation failed
2018-10-18 22:10:05 [ampache] (API) -> Login Success, passphrase matched
```

Is there an easy way to remove the API keys other than going through the DB?

**Comment by wagnered** [comment]
Hello @nearwood 
Thank you for bringing this to my attention.
>Is there an easy way to remove the API keys other than going through the DB?

No, not at this time, but the problem is **not** the API key. The problem is that the logic is not handling the session creation correctly. Thus the authorization token is not being created.

I am looking into this and attempting to determine the best fix.

**Comment by nearwood** [comment]
Browsing the tables, I see an entry to the `sessions` table with this id:

| id | user | expire | value | ip | type | agent | geo_latitude | geo_longitude | geo_name |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 9759c54409c524131bd419b17bde2126 | ampdrv | 1540084050 | 1539911103 | 0xc0a80101 | api | okhttp/3.10.0 | NULL | NULL | NULL |

There also are over 17,000 entries in the sessions table, looks like my app has issues.

Anyway, I removed the `apiKey` from the user table row (left the sessions table alone), and I can login as a user again. And some other unrelated issue on my app's side is now (not so) mysteriously working, so today has been a good day! If you need me to try anything else out let me know.

**Comment by nearwood** [comment]
Browsing the tables, I see an entry to the `sessions` table with this id:

| id | user | expire | value | ip | type | agent | geo_latitude | geo_longitude | geo_name |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 9759c54409c524131bd419b17bde2126 | xxx | 1540084050 | 1539911103 | 0xc0a80101 | api | okhttp/3.10.0 | NULL | NULL | NULL |

There also are over 17,000 entries in the sessions table, looks like my app has issues.

Anyway, I removed the `apiKey` from the user table row (left the sessions table alone), and I can login as a user again. And some other unrelated issue on my app's side is now (not so) mysteriously working, so today has been a good day!

As you undoubtedly already know, some combination of creating an `apiKey` session then switching back to user auth caused it to try and create a new session with the user's `apiKey` as the id. If you need me to try anything out let me know.

**Comment by wagnered** [comment]
> Anyway, I removed the apiKey from the user table row (left the sessions table alone), and I can login as a user again.

> As you undoubtedly already know, some combination of creating an apiKey session then switching back to user auth caused it to try and create a new session with the user's apiKey as the id. If you need me to try anything out let me know.

Do you mean login via web interface?  Or do you mean sending handshake with "User / Password"?

I have no problem logging in via the web interface as a non-admin user with an API key.

I was also able to login after doing an API handshake with both user/password and API key.

So I either don't understand your problem or cannot reproduce it.

> There also are over 17,000 entries in the sessions table, looks like my app has issues.

Yes, I know.  Ampache doesn't remove expired sessions. and it seems to create new sessions every time a web page is accessed.  Ampache doesn't manage sessions very well.

**Comment by nearwood** [comment]
> Do you mean login via web interface? Or do you mean sending handshake with "User / Password"?

Sorry -- never had an issue logging in via the web. This is all related to API authentication with user credentials or API key.

> Yes, I know. Ampache doesn't remove expired sessions. and it seems to create new sessions every time a web page is accessed. Ampache doesn't manage sessions very well.

Ah, I though it was my app, since 99% of them say "API" as the type.

> I did find a problem with the API key being used as a session key

Ok, I thought that was intentional, it was just missing a check to see if the session already existed. Thanks for you help on this. I do have a work-around so there's no rush on my end.

**Comment by lachlan-00** [comment]
Just having a read over. Is this an error with the auth key generated by the handshake?

It looks like the handshake is just generating an API key which doesn't seem like that's right.

**Comment by lachlan-00** [comment]
unique auth keys are generated by ampache-develop now so this collision shouldn't be happening.
