### ISSUE TITLE
Enhancement : Store and use "import playlist option" while updating catalog

### ISSUE THREAD

**Issue by djschorn** [ampache/ampache#1799]
# Environment

 * Ampache version:3.9.0
 * Web server + version: all
 * Server operating system: All
 * Client operating system:All

# Description

While creating a catalog, it's possible to set option "import playlist". 
This information is not stored in database so when updating a catlog, new m3u playlists in catalog are not added in Ampache database.
It could be nice to store this value and use it when updating a catalog.

**Comment by wagnered** [comment]
Added enhancement label for possible inclusion in next generation Ampache.

**Comment by lachlan-00** [comment]
Now that i've added checking for playlists and the contents i can add this option into the next version after 4.0.0

**Comment by lachlan-00** [comment]
From cli the -i|--import option does this.
I'll add import as a UI option next week. Import is just an add with playlist import on top

**Comment by lachlan-00** [comment]
a0d8ab4a4 add's import to the list of catalog actions.

So now both the CLI and UI allow you to use import to run add + importplaylists using the import command
