### ISSUE TITLE
Modify wiki ?

### ISSUE THREAD

**Issue by IDerr** [ampache/ampache#1800]
Hi everyone,
Is it normal that everyone can modify the wiki ?

https://github.com/ampache/ampache/wiki/Kodi

Thanks for your work.

**Comment by wagnered** [comment]
@IDerr 

I think it's limited to github members, but yes, any additional information about the use of Ampache is surely welcome. The wiki exists as it is with the help of volunteers.

Of course I get to have last word about what is added to the wiki :smiling_imp:

**Comment by IDerr** [comment]
hehe, It's pretty rare to see repos with this kind of freedom. 
I thought it was an error :)

Thanks for your fast answer :)
