### ISSUE TITLE
Update.php loop after install

### ISSUE THREAD

**Issue by KaaJaryi** [ampache/ampache#1801]
# Environment

 * Ampache version: 3.9.0-release
 * Web server + version:
 * Server operating system: Raspbian 4.14.71
 * Client operating system:

# Description

I try two times, after installation, I'm stuck in a loop on the update.php page. Ampache ask me to make a bunch of upgrade (version 3.8 Build:0005 to 3.8 Build:0012), after done it it tells me there is nothing to upgrade, but when I try to go to the login page, I'm back in the first one, with the same upgrade to make.

**Comment by wagnered** [comment]
@KaaJaryi 

I just downloaded 3.9.0-release and ran through the setup procedures.  I found no problem.

After you do the Ampache Update by clicking on `Update Now!` and click on `[Return to main page]` (http://127.0.0.1/), what exactly happens? Do you start the installation procedures again, or return directly to the "Ampache Update" page again?

If you click on `[Return to main page]` it should automatically display a web page as Ampache user logged in.

Perhaps a php module hasn't been loaded.  see the php module requirements in README.md in the ampache root folder.

**Comment by KaaJaryi** [comment]
After a few tests and reinstallations, I managed to get to the login page. The problem seems to have been the cache -_-" Sorry for the disturbance

**Comment by wagnered** [comment]
No problem. :smile:
