### ISSUE TITLE
Flawed logic in album hyperlink from song list

### ISSUE THREAD

**Issue by muzop** [ampache/ampache#1802]
Flawed logic in hyperlink from search results. This is also the case for artist specific listing of the album. Here's a scenario. Say Luther Vandros has  "Greatest Hits" album and Sting also has one. If I search for Sting, this and his other albums shows up just fine. When I click on the album to get a listing f Sting songs in that album, I get a list of every song by every artist that has an album "Greatest Hits." Did some sleuthing and indeed, you are calling for a single album ID even when the artist is not the same. The database shows that there are indeed different IDs for the same name album from different artists. Perhaps the flaw is in how you are getting the ID for the album post search as they are all getting the ID of the first matching entry in the album table.

mysql> select * from album where name="greatest hits";
+-----+---------------+--------+------+------+------+------------+--------------+--------------+
| id  | name          | prefix | mbid | year | disk | mbid_group | release_type | album_artist |
+-----+---------------+--------+------+------+------+------------+--------------+--------------+
|  37 | Greatest Hits | NULL   | NULL | 1999 |    0 | NULL       | NULL         |          144 |
| 280 | Greatest Hits | NULL   | NULL | 1982 |    1 | NULL       | NULL         |          385 |
| 281 | Greatest Hits | NULL   | NULL | 1976 |    0 | NULL       | NULL         |          385 |
| 394 | Greatest Hits | NULL   | NULL | 2001 |    0 | NULL       | NULL         |          464 |
| 402 | Greatest Hits | The    | NULL | 1988 |    1 | NULL       | NULL         |          466 |
| 775 | Greatest Hits | NULL   | NULL | 2001 |    0 | NULL       | NULL         |          592 |
| 835 | Greatest Hits | NULL   | NULL | 1994 |    0 | NULL       | NULL         |          226 |

**Comment by muzop** [comment]
Why can't the query be adjusted to pull correct album id per entry?

Anyways, I'll look through the code and see why this seems to be an
impossibility.

P.

**Comment by lachlan-00** [comment]
This should be fixed in develop. all the queries have been tested to avoid this happening. repen if you're still getting it in develop
