### ISSUE TITLE
Problems with Ampache-Catalogue and android

### ISSUE THREAD

**Issue by dnpsys1** [ampache/ampache#1803]
Hello, may I be forgiven for opening a new thread here, but my English is unfortunately too bad to find a suitable solution to my problem here. I hope someone here can read what I am writing here, as I am writing this with the help of a translation program. I have 2 problems with Ampache:

1. Unfortunately, my video catalogue does not show annual figures in the file name (for example, there are two videos with the titles Holiday 1990 1.avi and Holiday 1990 2.avi. In the catalogue, however, only Holiday 1 and Holiday 2 are shown.) But if I now have more videos with annual numbers in the title, it becomes very quickly confusing to chaotic. Is there a setting with which I can tell Ampache that he should just display the file name as a title?

2. Ampache runs flawlessly on my PC and I can also access my server from other PCs and play the video with the setting stream (the PC then loads a m3u file and the VLC plays the video). On my Android smartphone I can't play via the web player (which also makes problems on the PC for videos) or via stream. Is there a solution to this?

I would be very grateful for a quick and positive response. And I would ask once again to forgive my possibly bad English.

# Environment

 * Ampache version: 3.9.0
 * Web server + version: xampp 3.2.2
 * Server operating system: Windows 10 Pro x64
 * Client operating system: Android 8.1.0

 * Client type:
   - Web
   

# Settings

# Description

# Logs

**Comment by wagnered** [comment]
Helo @dnpsys1 

1. You might need to rename your files and/or change the folder path to "/Holiday/1990/1, /Holiday/1990/2" for example.

    A. When you create the catalog, it is also necessary to set "Filename Pattern:" and "Folder Pattern:" using the legend ojn the right side of the "Add a Catalog" page.
.
     B. What do you have for `metadata_order_video` in config/ampache.cfg.php?  It should contain "filename" if you want to get the information from the file/folder, or "getID3" if you want to get the information embedded in the file's tags.

    C. If you convert your avi files to mp4 and embed the information in the file's tags, The file pattern/folder pattern would be irrelevant , 

2.  All Browsers (HTML5) play mp4's and only some browsers play ogg or webm.  AVI files must be **transcoded** to one of those to play in the web interface. 

     A. This must be done by setting "Transcoding" in Admin->Server Config->Streaming to "Default" or "Always".

    B. ffmpeg, avconv or other transcoder needs to be set by uncommenting one of them in the `transcode_cmd` switch (Lines 950-952 of config/ampache.cfg.php).

    C. In the transcoding section, starting at line 877 of config/ampache.cfg.php it is necessary to set the files you want/need to transcode, what app you want to transcode it and what format you want the oputput file,

I hope this helps and if you have more questions, please ask.

**Comment by dnpsys1** [comment]
I would like to thank you very much for the quick and very helpful response. I think you can think of the thread as closed. And thank you again.
