### ISSUE TITLE
php7.2 can't access /admin/ pages when using empty web_path

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1805]
* Ampache version: GIT
 * Web server + version: apache php 7.2
 * Server operating system: debian

 * Client type:
   - Web

# Description

I can't access my server when trying to get to /admin/ urls.
I didn't realise this was happening until i redid the whole site trying to work out why this was happening.

These url's fail
https://server/admin/

These work
 https://server/ampache/admin/

I update the web_path in config to reflect the "" or "/ampache" but using https://server/admin fails with a 400 error when opening a new window.

Are there rewrite rules needed for the admin folder?

**Comment by lachlan-00** [comment]
I also tested by symlinking admin using an empty web_path to https://server/test/admin and that works fine.

**Comment by lachlan-00** [comment]
Is there any additional apache conf needed for the document root? it seems to only be an issue for me when i use commands from the index page

What happens is this.
 * Log into site
 * go to any admin page -> blank site page
(/index.php#admin/catalog.php?action=show_catalogs)
![image](https://user-images.githubusercontent.com/1305249/48330636-ff73d980-e698-11e8-948c-716bfe5e7aaf.png)

 * go to admin page with my sym link -> works
(/index.php#test/admin/catalog.php?action=show_catalogs)
![image](https://user-images.githubusercontent.com/1305249/48330647-0bf83200-e699-11e8-8c4b-f1d8606ec38e.png)

This is in the same session/browser windows and using the same url.
If i change the settings to a sub web_path it works every time.

**Comment by wagnered** [comment]
@lachlan-00 
You indicated that the Ampache version is "GIT".  Does this mean that you downloaded the .zip or .gz file and unpacked it in the Apache server document root, then renamed the folder from 'ampache-3.9.0' to 'ampache'. This would put ampache as a sub-folder of Apache's Document Root and  `web_path` would be required to be set.

If you move the entire contents of the ampache folder up to Apache's document root, the config switch `web_path` would not be needed.

BTW: I think that if you decide to use any of the API's, like the Subsonic back end, .htaccess.dist must be copied to .htaccess in the play, rest and channel folders.

**Comment by wagnered** [comment]
@lachlan-00 

So, I can assume that your Apache's Document root is "/opt"? If you set Apache's document root to /opt/ampache, the web_path config switch could be commented out.

For example, I have Apache's Document root set to /home/ernie/workspace/ampache.  I don't need to worry about web_path switch for what ever I want to do.

Maybe if I understood why you are trying to access the admin  page from a URL and not by clicking on the admin icon on the web page, I might understand the problem.

**Comment by lachlan-00** [comment]
Document root is /opt/ampache for both sites.

I can't access the admin pages in the web interface at all unless it's from a suddirectory url

**Comment by wagnered** [comment]
If your document root is /opt/ampache and web_path is "", it should work.  And with the /opt/ampache/ampache installation, web_path="ampache" should work.

Do you have separate virtualhosts for each?  If so, it could be a permissions problem in the Apache config file.

> go to admin page with my sym link -> works

What is the symlink location and what folder is it pointing to?

Could you try http: instead of the secure https?

Also can you access ampache with localhost or it's local network address?

Can you access "/index.php#browse.php?action=album"?  This might indicate that' it's a permissions problem for some reason.  

Otherwise I'm running out of ideas :frowning_face:

**Comment by lachlan-00** [comment]
it must be something with my apache config then i can't see any reason for this happening.

**Comment by lachlan-00** [comment]
It's php7.2! I started using the sury php7.2 for nextcloud and it's broken ampache in the process.

I tested by moving to an old stretch box and it worked again.

**Comment by wagnered** [comment]
That's interesting, I've been using php-7.2.11 for awhile now with no problems.  I actually had to make a few code changes to allow Ampache to work with php >7.2.0.  There was a problem with login, but it might have been a problem in other areas too. This was fix was implemented in Ampache 3.8.9.

**Comment by lachlan-00** [comment]
I'm using the packages from https://deb.sury.org/ for getting 7.2 into stretch.
![image](https://user-images.githubusercontent.com/1305249/48444189-f1c86c00-e7de-11e8-8f16-8ad054061c87.png)

**Comment by lachlan-00** [comment]
Doesn't work with a stretch docker contrainer so it must be the server I'm using.

Closing because I can't repeat it on my server
