### ISSUE TITLE
Advisory - Amapche 3.8.6 - Reflected XSSes

### ISSUE THREAD

**Issue by DanielBishtawi** [ampache/ampache#1806]
Hello,

While testing the Netsparker web application security scanner we identified Reflected XSS vulnerabilities in Amapche. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details. 

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by zingmars** [comment]
@wagnered you might want to look at this https://www.netsparker.com/web-applications-advisories/ns-18-046-reflected-cross-site-scripting-in-ampache/

**Comment by lachlan-00** [comment]
@DanielBishtawi can i email you about this? there are a lot of security issues being resolved currently in the core branch

**Comment by DanielBishtawi** [comment]
@lachlan-00 Sure, email me and I can put you in contact with the Security Researcher who identified these vulnerabilities.

**Comment by lachlan-00** [comment]
This is closed in develop but i will double check in the debian branch to see if any apply to that.
