### ISSUE TITLE
4.0.0 Pre-release shows up as "update available"

### ISSUE THREAD

**Issue by roobre** [ampache/ampache#1816]
# Environment

 * Ampache version: 3.9.0-release

 * Client type:
   - Web

# Description

4.0.0, which is (afaik) a pre-release, shows up in the main page featured as an update. The changelog it points to does not contains any notes about 4.0.0, and the download link is also broken.

Basically the update script should filter out releases tagged as pre-release from the github page.

**Comment by wagnered** [comment]
Many thanks for bringing this to my attention. 

I  forgot about the current version being capable of update checking.


Regards,

**Comment by lachlan-00** [comment]
closing, fixed by wagnerd
