### ISSUE TITLE
Unable to use Beets catalog

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1817]
# Environment

 * Ampache version: 3.8.9-develop
 * Web server + version: Nginx 1.14.1
 * Server operating system: Arch Linux
 * Client operating system: Windows

 * Client type:
   - Web: Firefox Nightly 65

# Settings

Will update with info if needed

# Description

I have seen a couple mentions of the possibility of using a Beets catalog with Ampache, however I can't seem to figure out how to use it. I did notice another open issue regarding beets, but they seem to have at least added the catalog (https://github.com/ampache/ampache/issues/1466).

If I go to the Add Catalog page, there are no options for Beets under Catalog Type, or Media Type.

I have checked, and the Beets module appears to be in the modules directory.

Please let me know what other information I can provide.

# Logs

will update if needed

**Comment by wagnered** [comment]
@kuzi-moto 

> I have checked, and the Beets module appears to be in the modules directory.

Did you remember to activate the Beets catalog on the right side of the modules page? After activating, it will show on the "Add Catalog" page as "Catalog Type"..

**Comment by kuzi-moto** [comment]
> 
> 
> @kuzi-moto
> 
> > I have checked, and the Beets module appears to be in the modules directory.
> 
> Did you remember to activate the Beets catalog on the right side of the modules page? After activating, it will show on the "Add Catalog" page as "Catalog Type"..

Ah, I was looking through configuration settings, but I had forgotten that this page existed. Looks like it's working now!

Looks like there's no mention of the Modules page in the wiki. Is this something worth putting in there? I'd be happy to do it myself when I have some time.

**Comment by wagnered** [comment]
Ahh...  Yes, it seems that people only have time to add wht is absolutely necesasry to get Ampache installed and running.  A good set of help pages explaining the various icons and items on tab pages would be very much appreciated if you have time.

Regards

**Comment by kuzi-moto** [comment]
> Ahh... Yes, it seems that people only have time to add wht is absolutely necesasry to get Ampache installed and running. A good set of help pages explaining the various icons and items on tab pages would be very much appreciated if you have time.
> 
> Regards

Great, I'll see what I can come up with when I have some spare time. Thanks for the help! Closing issue now.
