### ISSUE TITLE
Downloading single tracks doesn't work

### ISSUE THREAD

**Issue by retrodpc** [ampache/ampache#1818]
# Environment

 * Ampache version: 3.9.0
 * Web server + version: nginx 1.14.0
 * Server operating system: Ubuntu 18.04
 * Client operating system: Linux Mint 19, Windows 10

 * Client type:
   - Web

# Description

Pressing the download button links me to https://ampache/stream.php?action=download&song_id=N, which redirects to https://ampache/play/index.php?type=song&oid=N&uid=UID&name=NAME&action=download. This URL times out, but removing action=download lets it download normally (in the logs, using action=download will result in a 500 error)

# Logs

[29/Nov/2018:22:17:50 +0000] "GET /play/index.php?type=song&oid=201&uid=4&name=T-Square%20-%20Omens%20Of%20Love.mp3&action=download HTTP/1.1" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
[29/Nov/2018:22:19:10 +0000] "GET /play/index.php?type=song&oid=201 HTTP/1.1" 400 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"

**Comment by retrodpc** [comment]
Downloading zipped albums, however, does work.

**Comment by wagnered** [comment]
@retrodpc 

Sorry to say, I can't replicate your issue.  I was able to download both single song and whole zipped album on Ampache 3.9.0-release.

Does the problem exist on  both Linux and Windows?
What version of PHP do you have installed? If it's pre 7.0, I will have to install PHP 5.6 to try to replicate the issue.

**Comment by lachlan-00** [comment]
I did find an issue in develop that blocked downloading single files for me.
If you're on stable this should be fixed when 4 moves into stable but this is fixed in develop.
