### ISSUE TITLE
Laravel artisan install failing on Debian

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1819]
# Environment

 * Ampache version: 4.0
 * Web server + version: Apache 2.4
 * Server operating system: Debian 9.0 (testing)
 * Client operating system: Debian 9.0 (testing)

 * Client type:
CLI

# Settings

nothing generated yet

# Description
I was successful in cloning the repo and composer install. I already created the database and user otherwise I would get an username and password error in artisan.

Trying to run sudo -u www-data php artisan ampache:install

First run I get this error:

Application key set successfully.

 Please enter the mysql database name: [ampache]:
 > ampache-l
                                      
  The "force" option does not exist.  
                                      
Second time I run the command I get this error:

 Do you want to overwrite existing .env file? [no]:
 > yes

Please enter the mysql database name: [ampache]:
 > ampache-l

 Please enter the mysql database host: [127.0.0.1]:
 > 

 Please enter the mysql database port: [3306]:
 > 

 Please enter the mysql database user name:  [root]:
 > ampache-l

 Please enter the password associated with this user:
 > 

 Please confirm password: :
 > 

 Database ampache-l exists. Do you want to overwrite? [overwrite]:
  [0] overwrite
  [1] change
  [2] cancel
 > 0

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: DROP DATABASE ampache-l)

  at /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'")
      /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=ampache", "root", "secret", [])
      /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  Please use the argument -v to see more details.

# Logs

No logs yet.

**Comment by wagnered** [comment]
Hello @stebe 
See the [Laravel Directory Structure](https://laravel.com/docs/5.7/structure).

The log should be located at storage/logs/ and should contain something  like the following.

> [2018-11-28 23:15:37] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES).

>  PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=ampache", "root", "secret", [])

Anyway, There seems to be a problem with the logic setting the new password.

The .env file in the root folder has the password.  It can be changed manually to the correct one.  Changing it manually should allow you to continue.

Although there is not much to show, thanks for previewing Ampache/Laravel and helping out...

**Comment by wagnered** [comment]
If you are re-running all migrations, it is necessary to run: You then need to run `php artisan db:seed`. This is executed in the ampache:install artisan command.

Also the role is set after the user is created.  so run `artisan ampache:install` again or manually remove the registered user from the user table. Notice that there is a guest user with the id=0.

> Because I'm using MariaDB 10.1 I needed to make this change:
https://laravel-news.com/laravel-5-4-key-too-long-error
Then I was able to run

Thanks for the "Heads Up".  I was aware of the problem, but I only recently switched some tables to innodb from isam, which allows 1000 character key. 

As I've been exercising the installation command, I've found a few  other minor changes needed and am looking at them now.

Thanks,

**Comment by wagnered** [comment]
I fixed some bugs and maybe improved the user experience with commit https://github.com/ampache/ampache/commit/bedd11f946e042fd14c2181b391ff4746f0a34d0.

**Comment by stebe** [comment]
That fixed a lot of the problems, I can now get through ampache:install and correctly set up the database. The only error I'm not getting is that the application key is not getting generated, so I manually did this with key:generate.

RuntimeException thrown with message "No application encryption key has been specified."

Stacktrace:
#16 RuntimeException in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44
#15 Illuminate\Encryption\EncryptionServiceProvider:Illuminate\Encryption\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1027
#14 tap in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:48
#13 Illuminate\Encryption\EncryptionServiceProvider:key in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:24
#12 Illuminate\Encryption\EncryptionServiceProvider:Illuminate\Encryption\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
#11 Illuminate\Container\Container:build in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:658
#10 Illuminate\Container\Container:resolve in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:609
#9 Illuminate\Container\Container:make in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:733
#8 Illuminate\Foundation\Application:make in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:912
#7 Illuminate\Container\Container:resolveClass in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:840
#6 Illuminate\Container\Container:resolveDependencies in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:807
#5 Illuminate\Container\Container:build in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:658
#4 Illuminate\Container\Container:resolve in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Container/Container.php:609
#3 Illuminate\Container\Container:make in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:733
#2 Illuminate\Foundation\Application:make in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:215
#1 Illuminate\Foundation\Http\Kernel:terminateMiddleware in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:189
#0 Illuminate\Foundation\Http\Kernel:terminate in /var/www/ampache-l/public/index.php:60

**Comment by wagnered** [comment]
Yea, I did notice the problem after I made the commit.  The problem is that it seems to be random.  I run the  install a again and the app key was added.  I'm trying to find the problem now.

**Comment by stebe** [comment]
Now that I can run the web server and register, but I think something isn't loading correctly in composer. Or a module is missing.

![image](https://user-images.githubusercontent.com/4076671/49343713-81be4080-f63c-11e8-9031-3433eee09cbc.png)

**Comment by stebe** [comment]
I'm using Firefox. I see a lot of 404. I've tried both with the web server and the artisan serve with the same results.

![image](https://user-images.githubusercontent.com/4076671/49345935-72012500-f659-11e8-9719-10333e18839d.png)

**Comment by wagnered** [comment]
Didn't realize the missing folders/files  were on the .gitignore list. Changes pushed to laravel branch This time I cloned the repo and checked it out separate from my working repo.

**Comment by stebe** [comment]
I restarted the install from scratch and except for the default string length problem with Maradb during artisan install I'm able to set up Ampache. I'm able to log in and now get all the images and menu items. I'll play around and open separate issues if needed.

**Comment by xoxefdp** [comment]
I got a different variation of this issue, i've also tried to migrate and seed and that works fine but on php artisan ampache:install result in the next stacktrace:

```

 ➜  ampache git:(laravel) git fetch --verbose
Desde https://github.com/ampache/ampache
 = [actualizado]       laravel    -> origin/laravel
 = [actualizado]       develop    -> origin/develop
 = [actualizado]       master     -> origin/master
 = [actualizado]       new-ui     -> origin/new-ui
➜  ampache git:(laravel) php artisan ampache:install -v

 Do you want to overwrite existing .env file? [y|N]:
 > n


   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Dotenv\Dotenv::__construct() must be an instance of Dotenv\Loader, string given, called in /RESOURCES/Ampache/ampache/app/Console/Commands/InstallAmpache.php on line 79

  at /RESOURCES/Ampache/ampache/vendor/vlucas/phpdotenv/src/Dotenv.php:31
    27|      * @param \Dotenv\Loader $loader
    28|      *
    29|      * @return void
    30|      */
  > 31|     public function __construct(Loader $loader)
    32|     {
    33|         $this->loader = $loader;
    34|     }
    35| 

  Exception trace:

  1   Dotenv\Dotenv::__construct("/RESOURCES/Ampache/ampache", ".env")
      /RESOURCES/Ampache/ampache/app/Console/Commands/InstallAmpache.php:79

  2   App\Console\Commands\InstallAmpache::handle()
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  3   call_user_func_array([])
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  4   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  5   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  6   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Container/Container.php:580

  7   Illuminate\Container\Container::call()
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  8   Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /RESOURCES/Ampache/ampache/vendor/symfony/console/Command/Command.php:255

  9   Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  10  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/vendor/symfony/console/Application.php:908

  11  Symfony\Component\Console\Application::doRunCommand(Object(App\Console\Commands\InstallAmpache), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/vendor/symfony/console/Application.php:269

  12  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/vendor/symfony/console/Application.php:145

  13  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  14  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  15  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /RESOURCES/Ampache/ampache/artisan:37
```
