### ISSUE TITLE
Laravel, error in preference/interface/edit

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1821]
# Environment

 * Ampache version: 4.0 #1537 
 * Web server + version: Apache2 2.4
 * Server operating system: Debian 10
 * Client operating system: Debian 10

 * Client type:
   - Web
 
# Settings

# Description

Clicking on admin/server config/interface creates and E_Error
# Logs

ErrorException thrown with message "Invalid argument supplied for foreach() (View: /var/www/ampache-l/resources/views/preferences/edit.blade.php)"

Stacktrace:
#70 ErrorException in /var/www/ampache-l/app/Services/PreferenceService.php:166
#69 ErrorException in /var/www/ampache-l/app/Services/PreferenceService.php:166
#68 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/ampache-l/app/Services/PreferenceService.php:166
#67 App\Services\PreferenceService:create_preference_input in /var/www/ampache-l/storage/framework/views/d21019d7afd488b3162820643edc386204d0f338.php:48
#66 include in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#65 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#64 Illuminate\View\Engines\CompilerEngine:get in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/View.php:142
#63 Illuminate\View\View:getContents in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/View.php:125
#62 Illuminate\View\View:renderContents in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/View.php:90
#61 Illuminate\View\View:render in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Http/Response.php:42
#60 Illuminate\Http\Response:setContent in /var/www/ampache-l/vendor/symfony/http-foundation/Response.php:202
#59 Symfony\Component\HttpFoundation\Response:__construct in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:747
#58 Illuminate\Routing\Router:toResponse in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:719
#57 Illuminate\Routing\Router:prepareResponse in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:679
#56 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#55 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/app/Http/Middleware/LogLastUserActivity.php:42
#54 App\Http\Middleware\LogLastUserActivity:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#53 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#51 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#48 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#45 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#42 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#39 Illuminate\Session\Middleware\StartSession:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#36 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#33 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#30 Illuminate\Pipeline\Pipeline:then in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
#29 Illuminate\Routing\Router:runRouteWithinStack in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:656
#28 Illuminate\Routing\Router:runRoute in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:622
#27 Illuminate\Routing\Router:dispatchToRoute in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Router.php:611
#26 Illuminate\Routing\Router:dispatch in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#25 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#24 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/app/Http/Middleware/SystemConfig.php:28
#23 App\Http\Middleware\SystemConfig:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/app/Http/Middleware/RedirectIfNotInstalled.php:53
#20 App\Http\Middleware\RedirectIfNotInstalled:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/ampache-l/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/ampache-l/public/index.php:55

**Comment by stebe** [comment]
The save isn't happening for me when I toggle an option. I'm not seeing any error in the logs either when I do this. I tried this with Firefox, Chrome and IE 11.

**Comment by wagnered** [comment]
What tells you that the change isn't being saved.  If you make a change on a value or role for a given switch then go to another page and return, do the changes stick? 

There might be one or two, though.  I haven't checked all 100 plus preferences.

**Comment by stebe** [comment]
The settings on these pages, specifically dealing with localplay.

![image](https://user-images.githubusercontent.com/4076671/49512673-b4df1a80-f85c-11e8-87a7-7eab5eb9ff69.png)

**Comment by wagnered** [comment]
OK, thanks for exercising it and helping me find problems.

As soon as I get the Beets problem on current version  and the V4 interface preferences page fixed,, I'll check it out.

**Comment by lachlan-00** [comment]
Closing, I won't be maintaining the laravel branch. If wagnerd comes back and wants to keep working on it he can reopen the reports
