### ISSUE TITLE
[Runtime Error] Illegal string offset 'id' in file edit.server.php(143)

### ISSUE THREAD

**Issue by obel1x** [ampache/ampache#1826]
# Environment

 * Ampache version: 3.9.1
 * Web server + version: Apache2 Server Version: Apache/2.4.33 (Linux/SUSE) OpenSSL/1.1.0i-fips mod_fcgid/2.3.9 PHP Version 7.2.5
Server MPM: worker
Server Built: 2018-10-11 15:10:09.000000000 +0000 
 * Server operating system: Linux/SUSE Leap 15.0 (4.12.14-lp150.12.25-default #1 SMP Thu Nov 1 06:14:23 UTC 2018 (3fcf457) x86_64)
 * Client operating system: Linux/SUSE Leap 15.0

 * Client type:
   - Web

# Description

When editing Objects (like Title of Songs) in Web Frontend, the Error beneath is thrown, while assigning the new Value to an uninitialised result- variable in the way it is done. This is a syntax-related php- program- error beeing mentioned when reporting of  E_STRICT is enabled on your Server (see docs at https://secure.php.net/manual/en/migrating5.errorrep.php).
To be future-proof, assigning arrays should be done as described in https://secure.php.net/manual/en/language.types.array.php

# Logs

...
[ampache] (PHP) -> [Runtime Error] Illegal string offset 'id' in file /.../server/edit.server.php(143)
...

**Comment by lachlan-00** [comment]
merged into core branch
