### ISSUE TITLE
Error in log from Statistics inserting on object_count with use_auth = false;

### ISSUE THREAD

**Issue by NathanaelA** [ampache/ampache#1827]
# Environment

 * Ampache version: 3.9 (Dev)

# Settings
`use_auth = "false"`

# Description
When `use_auth` is set to false, init.php initializes the auth['id'] to be -1.   The object statistics will fail because the `user` column is tagged as a `unsigned` in the `object_count` table.

### Relevant Code:
init.php -> Line 181   `   $auth['id']           = -1;`
stats.class.php -> Line 117 
```
$sql = "INSERT INTO `object_count` (`object_type`,`object_id`,`count_type`,`date`,`user`,....) " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            $db_results = Dba::write($sql, array($type, $oid, $count_type, time(), $user, $agent, $latitude, $longitude, $geoname););
```

### Solutions:
I can give you a PR to fix it one of two ways;
1. we can change the column to be signed; so that -1 works.
2. We can short circuit the insert with a simple `if ($user < 0) return;`   

# Logs

```
2018-12-09 01:58:06 [System] (statistics) -> Unabled to insert statistics:INSERT INTO `object_count` (`object_type`,`object_id`,`
count_type`,`date`,`user`,`agent`, `geo_latitude`, `geo_longitude`, `geo_name`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2018-12-09 01:58:06 [System] (Dba) -> Error: ["22003",1264,"Out of range value for column 'user' at row 1"]
```

**Comment by wagnered** [comment]
@NathanaelA 

Thank you for bringing this to my attention, 

I think there is a more "global" fix:  Depending on the default user's access level, more tables than object_count" are accessible.

I think a much less "expensive" fix would be to change the -1 in init.php:179,181 to 0.   Of course, in case I missed something, this change should be tested as fully as possible as the default user.

Ernie W...

**Comment by wagnered** [comment]
@NathanaelA 
In case you did not receive via email my previous (deleted) comment:  Thanks for bringing this to my attention.

> because the user column is tagged as a unsigned in the object_count table.

Of course I'm running Ampache-3.9.1-develop but the tables haven't been changed in quite a long time.

I looked closer at the object _count table and column 'user' is defined as int(11) not unsigned according to MySQL workbench. That is also what the install script ./sql/ampache.sql indicates.

I just exercised the "Ampache User" and it is indeed inserting -1 into the 'user' column of the object_count table.

So I'm not sure what's going on with your installation, and I cannot duplicate your issue.

**Comment by NathanaelA** [comment]
Interesting; I've been a very long time ampache user; so it is possible that the table failed to be updated from unsigned to allowing signs.   I can manually do it.   Might just reinstall the sql and re-index all the music so that I have fully updated tables.

**Comment by wagnered** [comment]
Just went through the history for sql/ampache.sql and it was changed on 3/1/2016. There was also two other significant changes to the tables since that date.

Ernie D

**Comment by NathanaelA** [comment]
Thanks; wow -- I haven't seen any negative affects, so maybe it was just the one table that failed to change.     I'll just reset my sql; should be the safest course of action.  Thanks!
