### ISSUE TITLE
can't run ampache with php 7.2.5 - connection reset by peer

### ISSUE THREAD

**Issue by lemmy04** [ampache/ampache#1828]
# Environment

 * Ampache version: 3.9.0
 * Web server + version: apache2 2.4.33
 * PHP version: 7.2.5
 * Server operating system: openSUSE Leap 15.0
 * Client operating system: openSUSE Leap 15.0, Firefox 63.0.3

 * Client type:
   - Web: Firefox 63.0.3

# Settings

ampache.cfg is attached:
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/2663372/ampache.cfg.php.txt)

# Description

ampache won't open, "connection reset by peer" in browser, "empty response" when accessing with curl

# Logs
no logs in /var/log/ampache even with debugging enabled.
apache log shows this:
`[Mon Dec 10 14:52:53.984921 2018] [php7:error] [pid 20355] [client fdff:ffc0:8aee:a415:baee:65ff:fe47:1cb0:38018] PHP Recoverable fatal error:  Unknown: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0, referer: http://akari.eregion.home/`

**Comment by wagnered** [comment]
Hello @lemmy04 

I think this might be a selinux problem.  Could you enable php logging and report any error?  Don't forget to restart the Apache serve after enabling. :smile:

**Comment by lemmy04** [comment]
I don't have selinux active - this is an openSUSE box
and even with php logging enabled the log entry above is all I get.

**Comment by wagnered** [comment]
Try setting `session.autostart=Off` and `display_startup_errors = On`, in php.ini.

Make sure that Apache has access to the /temp folder.

I'm suggesting possible solutions I've got from web searches.

The problem is not with Ampache.  I am using PHP-7.2.12 and cannot  replicate your issue.  I vaguely remember that there was a problem with PHP-7.2.5, but I cannot  remember what it was. You might try installing a different version if your distribution has it.

**Comment by lemmy04** [comment]
still the same issue, and no additional detail either.
and there's no higher php72 version available (yet).

**Comment by wagnered** [comment]
OK I will install 7.2.5 to see if I can replicate your issue.

**Comment by lemmy04** [comment]
I have upgraded php to 7.2.13, problem persists but with a different message in the apache error log:

```
[Tue Dec 11 09:01:50.433190 2018] [core:notice] [pid 17720] AH00052: child pid 19966 exit signal Segmentation fault (11)
[Tue Dec 11 09:01:50.434522 2018] [core:notice] [pid 17720] AH00052: child pid 19967 exit signal Segmentation fault (11)
[Tue Dec 11 09:01:50.434791 2018] [core:notice] [pid 17720] AH00052: child pid 19978 exit signal Segmentation fault (11)
[Tue Dec 11 09:01:50.438421 2018] [core:notice] [pid 17720] AH00052: child pid 19980 exit signal Segmentation fault (11)
[Tue Dec 11 09:01:50.438825 2018] [core:notice] [pid 17720] AH00052: child pid 19981 exit signal Segmentation fault (11)
```

other php apps work normally.

**Comment by wagnered** [comment]
Sorry to inform you that I now have php-7.2.5 installed and could not reproduce your issue.
It might involve a folder/file access issue.

PHP-7.13 hasn't been tested yet, so it might be an unrelated problem. I'll install it tomorrow and see what I get.  

The error you get with php-7.2.5 is frustrating because it reports the file as "unknown" so I haven't been able to find a possible cause.

**Comment by obel1x** [comment]
i got opensuse leap 15 / php 7.2.5 too and no probs. maybe i can help - what apache-module do you have for php? i use php-fpm and mod_proxy_fcgi, other ones didn't work well for me.

**Comment by lemmy04** [comment]
ok so i switched to fpm for php, but ampache isn't working that way either, and my other php apps died in the process too, so i'm switching back to "normal", can't have my roundcube broken as well.

**Comment by lemmy04** [comment]
[mozilla.pdf](https://github.com/ampache/ampache/files/2718300/mozilla.pdf) here's a printout of phpinfo() from my machine if that's any help.

**Comment by obel1x** [comment]
ok, so you got prefork mpm for apache and mod_php7 which is the "old style" to setup up the webserver. did you changed your "session save handler" in apache-php.conf to 'user' or do you have some .htaccess doing this? error looks like there is an problem with that setting and doesn't come from ampache.

Maybe copy phpinfo to ampache directory and check if there ist a difference here (e.g "files" is turned off for ampache somehow?):
Registered save handlers: files user
session.save_handler: files
Should be the right values, as your config that you have posted.

If that does not help, i wouldn't know if there is a problem with mod_php and save_handle user-setting and i cannot switch back to that setup.
To avoid complications with php-config in apache: I would definitively go for a newer setup of apache with event-mpm + php-fpm as this is also very much better in configuration, faster, much more scaleable and stable than you prefork + mod_php in general. But it needs to be setup a bit. I could show you how to do it fast, but it will change your setup.

**Comment by lemmy04** [comment]
d'oh. 
the ampache rpm I'm using comes from opensuse, it comes with a file /etc/apache2/conf.d/ampache.conf and that one has a "session save handler user" line in it... changed to "files" and now it works 0.o

gonna submit that fix to opensuse.

**Comment by lemmy04** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1120428

**Comment by lemmy04** [comment]
I'd like to let it open until someone at opensuse has acknowledged the bug report...

**Comment by lachlan-00** [comment]
@lemmy04 looks like suse have resolved the issue as the bug is closed.

**Comment by lemmy04** [comment]
yup, its fine now.
