### ISSUE TITLE
Various incompatibilites with Subsonic API

### ISSUE THREAD

**Issue by darkphoenix** [ampache/ampache#1829]
# Environment

 * Ampache version: HEAD (develop branch)
 * Web server + version: Apache
 * Server operating system: Linux (Synology)
 * Client operating system: Raspbian
 * Client: py-sonic

# Description
Various parts of the Subsonic API appear to be implemented incorrectly. Firstly, there is a bug in lib/class/subsonic_api.class.php - Line 731 should probably be $song   = Subsonic_XML_Data::getAmpacheId($songid); because the way it is right now causes it to fail and getSong.view to not work (only "ok" status, but no song returned). Also, the xml2json function does not work correctly in this case because it converts the single-element XML list to a JSON Array which is in violation of the official implementation and breaks clients. This can be fixed by removing song from the alwaysArray config element, however, I presume this breaks other things. I think there are more issues with the implementation as I have not been able to get it to work at this point - I will update as I find them.

**Comment by darkphoenix** [comment]
Actually, it seems the rest is at least good enough to work. Sadly, modifying the xml2json config like I did breaks single-event searches and things like that - I'm thinking about adding another parameter to Subsonic_Api::apiOutput and apiOutput2 to let the caller decide whether they want single-element arrays or not - deciding this on a method-by-method-basis would probably work. If I get it to work for me, I'll open a PR.

**Comment by darkphoenix** [comment]
Okay, I've got a fork that has this modification in - I'm not entirely sure I got all the methods that only ever return one element and need this special treatment, but I've got the additional parameter and it works for me. I'll open a PR with it, but I would feel much more comfortable with this if somebody who knows the codebase had a look at it, I haven't read all that much of it and it's been a while since I last did any PHP.

**Comment by a7medo778** [comment]
I intended to ask this earlier as i am aiming to migrate my app to the laravel branch. 
How about ampache xml-api, have you tried it? Is it working?

I am pulling everything direct from db but need some api calls to get the transcode and stream feature for example
https://graphql.org looking specially good

**Comment by darkphoenix** [comment]
@a7medo778, this issue is related neither to the XML API nor to the Laravel branch. Please refrain from throwing unrelated questions in here.

**Comment by a7medo778** [comment]
@darkphoenix my bad, replied to the wrong email

**Comment by lachlan-00** [comment]
merged into core!
