### ISSUE TITLE
Unable to set remote database in web installer

### ISSUE THREAD

**Issue by Perflyst** [ampache/ampache#1835]
# Environment

 * Ampache version: git master
 * Web server + version: apache2 (2.4.25-3+deb9u6)
 * Server operating system: Debian 4.9.0-8-amd64
 * Browser: Tested with Firefox and Chromium

# Description

The webinstaller in the second step wants a database. I created an user and a database on a ***remote*** host. Entered details in the webinstaller and it shows

"Error: Unable to make database connection: SQLSTATE[HY000] [1045] Access denied for user 'ampache'@'LOCALIP' (using password: YES)"

It always tries to connect to a local database server (there is none). It is not possible to install ampache via webinstaller while using a remote database.

Pressing "Skip": I get a white page. Error log from webserver is empty.

**Comment by lachlan-00** [comment]
that's the database denying your user from the webserver (hence the local ip)

Are you using mysql/mariadb?

**Comment by lachlan-00** [comment]
Closing. Not an installer issie
