### ISSUE TITLE
Search Load Issue

### ISSUE THREAD

**Issue by vineetdikonia** [ampache/ampache#1839]
# Environment

 * Ampache version: 3.4.1
 * Web server + version: Apache 2.2
 * Server operating system: CentOS 6.5
 * Client operating system: MAC

 * Client type:
   - Web
   - Ampache
   - SubSonic
   - Plex
   - DAAP
   - UPnP
   - WebDAV

# Settings

# Description

We have used Ampache for our music site and mobile app also, And used the Search class for searching the songs by keywords. But the response getting very slow. I tried to look on the queries you guys used for search there are 3 to 4 joins in the query. Is someone here who suggest me to make search faster?
Please suggest your solutions, I really need it.
Thanks
# Logs

**Comment by ftoledo** [comment]
Me too, search is very  slow =( I use with dsub clent and get several network timeouts

**Comment by lachlan-00** [comment]
What kind of searches are slow for you? I don't really have too many search issues so if you can point to something that's bad i can try to make it better.

The joins really only seem to relate to the object you're searching for from what i see in search.class.php. The anywhere search might be the slowest but there's probably a way around that

**Comment by ftoledo** [comment]
HI @lachlan-00 Thanks for reply. I found that search from search box are slow to respond i have 90K songs at 9000 albums aprox..
Somo actions (catalog related) have 504 gateway timeout from nginx . i will try to increment some settings nginx and php-fpm of course, but i want to try to debug more to help to improve it.

Also in last update to 4.0.0-develop i get this issue #1947 

```
190.19.234.64 - - [25/Jun/2019:00:18:36 -0300] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:22:00 -0300] "GET /server/ajax.server.php?page=search&action=search&target=anywhere&search=ni&xoutput=json HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:22:01 -0300] "GET /server/ajax.server.php?page=search&action=search&target=anywhere&search=nin&xoutput=json HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:22:03 -0300] "GET /server/ajax.server.php?page=search&action=search&target=anywhere&search=nino&xoutput=json HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:24:10 -0300] "GET /image.php?object_id=7587&object_type=album&thumb=1&fooid=142504 HTTP/2.0" 200 10908 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:24:11 -0300] "GET /image.php?object_id=5045&object_type=artist&thumb=1&fooid=152165 HTTP/2.0" 200 3265 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:26:14 -0300] "POST /server/ajax.server.php?page=index&action=random_albums HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:37:14 -0300] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/2.0" 504 246 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
190.19.234.64 - - [25/Jun/2019:00:57:25 -0300] "GET /image.php?type=session&image_index=1&cache_bust=2019062503837464325046 HTTP/2.0" 200 41641 "https://music.tom.pressenter.com.ar/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"

```

**Comment by lachlan-00** [comment]
have you got cache enabled in your config file?
```
memory_cache = "true"
```
I'm up to 250k now and get basically instant search and smartlists in the web ui.
With caching it never really goes above 0.3 of a second
![image](https://user-images.githubusercontent.com/1305249/60069434-1b267e80-9756-11e9-905d-8cde6f093268.png)
![image](https://user-images.githubusercontent.com/1305249/60069485-60e34700-9756-11e9-87fe-d076b29062fd.png)

**Comment by ftoledo** [comment]
Yes, i have memory_cache="true" at my config.

Results:
Queries:428 Cache Hits:52 | Load time:2.4960 

Maybe i need to tune the mysql/nginx/php-fpm... i have almost default setting for all.
also i think that will enable slow queries at mysql to identified if the issue come from database..

**Comment by lachlan-00** [comment]
I'm using php-7.3 with fpm as well, it did require a lot of tuning to make it stable to use.

I read this guide and tweaked it a bit after.
https://ma.ttias.be/a-better-way-to-run-php-fpm/

**Comment by kuzi-moto** [comment]
Hey @vineetdikonia, were you able to try the solutions provided by lachlan-00?

**Comment by ftoledo** [comment]
hi all ! 
I update my server to more power hardware and now get good load times
```
Queries: 476 | Cache Hits: 361 | Load Time: 0.7355 
```
So, the issue was solved for me with better hardware.
I still see that have several queries (show 476) that maybe can be pissible optimize too.

thanks!

**Comment by AshotN** [comment]
I'll close this issue since you seem to have resolved it. If you experience a similar issue, feel free to either re-open this, or create a new issue.

**Comment by kuzi-moto** [comment]
@AshotN Technically he wasn't the ticket author, but they haven't responded yet to the ticket after the initial post anyway. @vineetdikonia if you are still having issues you should probably open a new one anyway.
