### ISSUE TITLE
Add object-fit CSS rule to images to prevent distortion

### ISSUE THREAD

**Issue by membranophonist** [ampache/ampache#1841]
You can prevent images from being distorted using the object-fit CSS rule on the `table.tabledata tbody .cel_cover img` selector, like so:

`object-fit: cover;`

# Environment

 * Client type:
   - Web
   - Ampache

# Description

Examples of image display without (top) and with object-fit.
<img width="1046" alt="images-no_object-fit" src="https://user-images.githubusercontent.com/7274867/51060646-6856cf80-15be-11e9-8e37-e9c90b53007f.png">
<img width="1046" alt="images-object-fit_on" src="https://user-images.githubusercontent.com/7274867/51060647-6856cf80-15be-11e9-99c1-e445390851a6.png">

**Comment by lachlan-00** [comment]
does this need to go in the hover as well? i'm testing it out on my side server now.
```
table.tabledata tbody .cel_cover img {
    -webkit-box-shadow: 0 0 10px rgba(0,0,0,0.75);
    -moz-box-shadow: 0 0 10px rgba(0,0,0,0.75);
    box-shadow: 0 0 10px rgba(0,0,0,0.75);
    object-fit: cover;
}
```

**Comment by membranophonist** [comment]
I don't think you need to add it for the hover state.

**Comment by Psy-Virus** [comment]
Usually, pseudo classes overtake the definitions and stuff from the already setup selectors.
You only have to write something in, if you want to change something like:

```css
#selector {
    font-size: 20px;
    background-color: #000;
}

#selector:hover {
    background-color: #fff;
}
```

The `background-color`will be changed from black to white on hovering over the element but the `font-size` will stay the same.

**Comment by lachlan-00** [comment]
I have put this into my fork and it will move from me -> core -> develop soon as i finishe the modernization project,

Thank you for contributing to Ampache!
