### ISSUE TITLE
black screen overlay when start play song

### ISSUE THREAD

**Issue by ftoledo** [ampache/ampache#1843]
My screen goes black few second start playing any song.
I try research who cause it, its ocurs 1 seconds later to star play the song
I use the latest git code.
This issue started after restoring a backup. I review all files permissions and several things but i can detect the origin of this behavior.
![captura de pantalla_2019-01-19_12-23-13](https://user-images.githubusercontent.com/95441/51428760-45dc3c00-1be6-11e9-9e09-5a3f7571d47f.png)

**Comment by ftoledo** [comment]
i found htat is relate to slideshow div in header.php
this content sem to be empty:

```
<div id="aslideshow" style="height: 1200px; display: inline;">
    <div id="aslideshow_container">
           <div id="fslider"></div>
           <div id="fslider_script"></div> 
    </div>
</div>

how to this work?
can disable it?
```

**Comment by lachlan-00** [comment]
Found the fix for it and it's in the current develop branch! Thanks for reporting.
