### ISSUE TITLE
Songs not playing via SubSonic API with lighttpd

### ISSUE THREAD

**Issue by Marmo** [ampache/ampache#1853]
# Environment

- Ampache version: 3.9.1-develop
- Web server + version: lighttpd 1.4.45
- Server operating system: Raspbian 9 (stretch)
- Client operating system: Android 8.1.0

- Client type:
  - SubSonic UltraSonic 2.6.1
  - SubSonic DSub 5.0.3

# Settings
- ampache.cfg.php: default as setup by the installer
- lighttpd: rewrite rules from [wiki/Installation](https://github.com/ampache/ampache/wiki/Installation#lighttpd) and [wiki/API](https://github.com/ampache/ampache/wiki/API#for-others), mod_rewrite enabled, ipv6 not enabled

# Description
Browsing the catalog works in both clients as expected, but streaming/playing or downloading a file does not work. The web server access log shows a 404 response. 
Streaming/playing in PowerAmpache works without problems, so it seems to me, this is a client or SubSonic API specific problem.

My understanding: to rewrite the URL requested by the SubSonic client's 
```
/play/ssid/984f76d993e466015d58614f896ffd8a/type/song/oid/141/uid/2/client/Ultrasonic/noscrobble/1/player/api/name/Bad%20Religion%20-%20Atheist%20Peace.mp3
```
for Ampache every consecutive pair of path elements should be translated into key-value-pairs of a query string:
```
/play/index.php?ssid=984f76d993e466015d58614f896ffd8a&type=song&oid=141&uid=2&client=Ultrasonic&noscrobble=1&player=api&name=Bad%20Religion%20-%20Atheist%20Peace.mp3
```

As far as I understand lighttpd-url-rewriting and the regexes proposed in the [wiki](https://github.com/ampache/ampache/wiki/Installation#lighttpd) this will not happen, because in the lighttpd rewrite rules there is no such mechanism as the "N" option in the Apache rewrite rules (which causes the rules to be applied again until it does not match anymore and thus iterating over all the 16 path elements in the SubSonic URL). (I have to add that I have very little experience configuring lighttpd or apache2)

Finally I stumbled over #709, specifically [this post](https://github.com/ampache/ampache/issues/709#issuecomment-76600206) and added a rewrite rule mentioned there to my lighttpd.conf:
```
url.rewrite-if-not-file += ("^/play/ssid/([^/]+)/type/([^/]+)/oid/([^/]+)/uid/([^/]+)/client/([^/]+)/noscrobble/([^/]+)/player/([^/]+)/name/([^/]+)(/.*)?$" => "/play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&player=$7&name=$8")
```

After reloading the Webserver config streaming/playing/downloading from Ultrasonic and DSub works :)

I guess this is rather a ugly workaround than a solution but for my setup it is sufficient.

Maybe this helps someone, maybe it should be added to the wiki? Or is my understanding of the problem wrong?

# Logs
lighttpd access log:
```
192.168.2.222 192.168.2.222:32500 - [24/Feb/2019:08:12:33 +0100] "GET /play/ssid/984f76d993e466015d58614f896ffd8a/type/song/oid/141/uid/2/client/Ultrasonic/noscrobble/1/player/api/name/Bad%20Religion%20-%20Atheist%20Peace.mp3 HTTP/1.1" 404 345 "-" "okhttp/3.10.0"
```

**Comment by lachlan-00** [comment]
you should be able to edit the wiki page with this and it should go through for approval. (whoever approves that?)

**Comment by Marmo** [comment]
hm  ok .. didn't expect I can edit there. Added to the API page and it seems noone has to approve what I did.
