### ISSUE TITLE
Adding Amperfy as new iOs client

### ISSUE THREAD

**Issue by BLeeEZ** [ampache/ampache#1855]
I have create a new iOs client [Amperfy](https://github.com/BLeeEZ/amperfy). It uses the XML API and is released under GPLv3. I would appreciate to see it listed with the other iOs clients. 

I wrote this new app, because there are currently no other open source apps supporting iOs 12.

**Comment by a7medo778** [comment]
Dude this is awesome, are you using only the subsonic api or the xml as
well?

**Comment by BLeeEZ** [comment]
I am only using the xml api. Subsonic api is currently not supported.

**Comment by lachlan-00** [comment]
impressive!
love to see new clients using the api. hopefully someone with write can put this in the wiki/site.

**Comment by lachlan-00** [comment]
@BLeeEZ changes made.

I love that you're using the ampache api and want to make sure api clients have all the support they need. If you feel like there are calls missing please file another bug report and i will endeavor to help you resolve them.
