### ISSUE TITLE
Piwik plugin needs updating.

### ISSUE THREAD

**Issue by Baggypants** [ampache/ampache#1857]
# Environment

 * Ampache version: Ampache 3.9.0-release

# Description

Piwik has changed to Matomo, references to piwik.php need to be changed to matomo.php  https://matomo.org/faq/new-to-piwik/faq_21984/

**Comment by Baggypants** [comment]
Here is a minimal diff to make it work with matomo.

```
diff --git a/modules/plugins/Piwik/Piwik.plugin.php b/modules/plugins/Piwik/Piwik.plugin.php
index ee2b3a4b..322556db 100644
--- a/modules/plugins/Piwik/Piwik.plugin.php
+++ b/modules/plugins/Piwik/Piwik.plugin.php
@@ -100,16 +100,16 @@ class AmpachePiwik
         echo "_paq.push(['enableLinkTracking']);\n";
         echo "(function() {\n";
         echo "var u='" . scrub_out($this->piwik_url) . "';\n";
-        echo "_paq.push(['setTrackerUrl', u+'piwik.php']);\n";
+        echo "_paq.push(['setTrackerUrl', u+'matomo.php']);\n";
         echo "_paq.push(['setSiteId', " . scrub_out($this->site_id) . "]);\n";
         if ($GLOBALS['user']->id > 0) {
             echo "_paq.push(['setUserId', '" . $GLOBALS['user']->username . "']);\n";
         }
         echo "var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n";
-        echo "g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);\n";
+        echo "g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n";
         echo "})();\n";
         echo "</script>\n";
-        echo "<noscript><p><img src='" . scrub_out($this->piwik_url) . "piwik.php?idsite=" . scrub_out($this->site_id) . "' style='border:0;' alt='' /></p></noscript>\n";
+        echo "<noscript><p><img src='" . scrub_out($this->piwik_url) . "matomo.php?idsite=" . scrub_out($this->site_id) . "&amp;rec=1' style='border:0;' alt='' /></p></noscript>\n";
         echo "<!-- End Piwik Code -->\n";
     }
```

**Comment by meandor** [comment]
why would you even need matomo for the app? it seems like it is bloating the whole thing up (not that it is not bloated already?)

**Comment by lachlan-00** [comment]
is piwik still available? should matamo be separated into a new plugin?

**Comment by Baggypants** [comment]
@lachlan-00 It should probably be a new plugin. Piwik has become Piwik-PRO and the community version has become Matomo. Also people might not have upgraded from Piwik to Matomo. I made the changes for my personal benefit.

@meandor I don't _need_ it, but I run a public ampache for my personal compositions which are no longer on soundcloud and it's helpful for me to see what traffic it generates. Also the whole plugin appears to be 143 lines which adds 10 lines to the footer, and it only does this **if** the plugin is enabled, which it isn't by default. https://github.com/ampache/ampache/blob/develop/modules/plugins/Piwik/Piwik.plugin.php

**Comment by lachlan-00** [comment]
i'll patch a separate plugin using the old version and add it to my pull.
