### ISSUE TITLE
autoplay is stopping transcoded songs

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1858]
ref from https://github.com/jplayer/jPlayer/issues/421

something in play/index.php needs an update to deal with browsers stopping autoplay

The html5 player has issues with transcoding files that stop loading after about 1:20. (if your track is shorter it's obviously okay.)
![image](https://user-images.githubusercontent.com/1305249/54863129-5b114a80-4d90-11e9-8856-a9c6e5c24d51.png)

i can get the track to load fully by skipping towards the end of the track
![image](https://user-images.githubusercontent.com/1305249/54863131-606e9500-4d90-11e9-93ff-4367bd3043ea.png)

in dev tools i get this message
```
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.
```
disabling this will fix it
![image](https://user-images.githubusercontent.com/1305249/54863140-72e8ce80-4d90-11e9-8309-981e462f6c34.png)

**Comment by lachlan-00** [comment]
The only file with audioContext is in the uberviz module. Must be there.
https://github.com/ampache/ampache/blob/develop/modules/UberViz/AudioHandler.js

**Comment by lachlan-00** [comment]
https://github.com/phetsims/vibe/commit/3bf8488a8801605887d34506255cfb862cc07f77

this commit from vibe edited for ampache will fix it

But:
* need to allow autoplay permission on the site.
* it will load without interaction but only when it gets to towards the end of the song.

**Comment by lachlan-00** [comment]
I think i can fix this by putting the player div before playing the files. This way the browser has detected user interaction.

Add this to the bottom of ./templates/header.inc.php 
```
<?php Stream_Playlist::show_web_player() ?>
```
Then add this function to lib/class/stream_playlist.class.php
```
    /**
     * show_web_player
     *
     * Show the created web player for ajax page loading.
     * Browsers block autoplay when you haven't interacted with the page so load it early.
     */
    public function show_web_player()
    {
        if (AmpConfig::get("ajax_load")) {
            require AmpConfig::get('prefix') . UI::find_template('show_web_player_embedded.inc.php');
        }
    }  // show_web_player
```

**Comment by Psy-Virus** [comment]
Well, I tried to reproduce this but didn't have any luck.
I tried it with a transcoded song from FLAC to MP3 and from MP3 to MP3 in FireFox.

Do you have a list of steps to reproduce? Is it Browser dependent?

**Comment by lachlan-00** [comment]
This is in the current Firefox nightly.

Not sure which version of Chrome has this setting but it's not in current Firefox either

**Comment by lachlan-00** [comment]
Steps to reproduce.

* Open Firefox 68+ (nightly)
* Open ampache
* Play a song
* song doesn't start playing unless you press play.
* remove the song but don't close the player
* play a new song
* the song will play without interaction.

The reason I notice this on transcoded songs is that the song isn't loaded completely and the browser blocks the AudioContext before it's complete.

Putting the play div in the window fixes this.

**Comment by lachlan-00** [comment]
Moving on.
