### ISSUE TITLE
add to all bypass's GatherArt settings

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#1865]
# Environment

 * Ampache version: 3.9
 * Web server + version: apache2
 * Server operating system: ubuntu
 * Client operating system: osx

# Settings
; Art Gather Order
; Simply arrange the following in the order you would like
; ampache to search. If you want to disable one of the search
; methods simply leave it out. DB should be left as the first
; method unless you want it to overwrite what's already in the
; database
; POSSIBLE VALUES (builtins): db tags folder lastfm musicbrainz google
; POSSIBLE VALUES (plugins): Amazon,TheAudioDb,Tmdb,Omdb,Flickr
; DEFAULT: db,tags,folder,musicbrainz,lastfm,google
art_order = "tags,folder"

# Description

when i  add the catalog i stop gather art function, but when i click add to all later it seems that it bypass my gatherart settings and go look in external sources leaving me with junk coverarts and broken images

**Comment by lachlan-00** [comment]
The add function doesn't look for art; only new files.

How are you running the command?

**Comment by a7medo778** [comment]
directly from the gui,
before i run it, all the missing art just shows a the default missing
thumb, after running its a bunch of broken images and wrong google searched
images (its an indie catalog)

**Comment by lachlan-00** [comment]
I think what's happening is that the UI is trying to load a picture when there isn't any art automatically. not from the catalogue scan.

I have similar problems with random art filling areas.

**Comment by a7medo778** [comment]
yes that might be it.
because i literally tried everything, even removing all sort of gather art functions, and i am still getting junk google images inserted

**Comment by lachlan-00** [comment]
Let me have a look at the art class and see what i can find. I think we're on the right track.

I'd prefer it to fall back to a blank image myself.

**Comment by lachlan-00** [comment]
hey @a7medo778 i think i've found it.

The last.fm integration is overwriting the art for me which is why it's ignoring your settings.

If you disable lastfm_api_key in your config i'll bet that it works. (you don't have to keep it disabled just have a look and i'll know if i'm right then.)

**Comment by lachlan-00** [comment]
Found it!

This will merge into core soon and we are almost ready to move into develop. this will be fixed for you soon!

https://github.com/lachlan-00/ampache/commit/c1658931e0f56c3fa75434c0fc98babd1688bad4
