### ISSUE TITLE
dsub cannot fetch podcasts

### ISSUE THREAD

**Issue by calcmandan** [ampache/ampache#1870]
# Environment

 * Ampache version: 3.9.0
 * Web server + version: Apache/2.4.10
 * Server operating system: Ubuntu 15.04
 * Client operating system: Android

 * Client type:
   - DSUB

# Settings

; Set this to true to enable podcasts and the
; possibility for admins to subscribe to new podcasts.
podcast = "true"
# Description

Podcasts don't appear in dsub.
I attempted to clear the application cache and reconfigure 
Podcasts appear on web client and work fine
Did a diff between current config and old with no distinct difference

# Logs

Thousands of the following

2019-04-12 11:30:42 [daniel] (autoload) -> 'episode' not found!

followed by

2019-04-12 11:30:42 [ampache] (PHP) -> [Runtime Error] DOMDocument::loadXML(): internal error: Huge input lookup in Entity, line: 2 in file /var/www/ampache/lib/class/subsonic_api.class.php(191)

**Comment by lachlan-00** [comment]
I think this is from an issue i found with large xml strings.
I fixed this in amuzak so i'll put in a pull for ampache if i can find the commit.

**Comment by lachlan-00** [comment]
https://github.com/ampcore/amuzak/commit/67e31559da1a1d2b82f38493e0a9a8b1fefb97a6

![image](https://user-images.githubusercontent.com/1305249/56871673-6416cb00-6a64-11e9-8096-335fdef57f3c.png)

can you test with this? i can send you patches/files if you need help

**Comment by lachlan-00** [comment]
@calcmandan if you want to patch yourself the code is there. The slowness from everyone means I doubt this would actually be merged. I'm working on a fork that already includes this patch and a lot of the open pulls already.

https://github.com/ampcore/amuzak
