### ISSUE TITLE
Friends Timeline plugin needs help. (Do you use it? do you like it?)

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1878]
I don't really see why this plugin even exists. It ruins the main page by pushing all it's content hard in a single column on the left.
![Screenshot_2019-05-08_00-01-28](https://user-images.githubusercontent.com/1305249/57305462-78be2780-7124-11e9-8e8e-0dff12a9461d.png)

it's also not really showing much more than the recently played section
![Screenshot_2019-05-08_00-02-47](https://user-images.githubusercontent.com/1305249/57305639-bde25980-7124-11e9-832a-31cf912db518.png)

If someone wants to play around with this plugin, maybe it could be a bit more useful.

Right now it's not a priority but it would be a good learning experience.

**Comment by kuzi-moto** [comment]
I've never used it, as I'm the only one in my instance. However I could see how some of the other information such as favoriting could be useful. I think if it were to be kept, that the formatting could be changed to make it more compact.

Perhaps strip off the album art, reduce padding between lines, and maybe move each event into just a single line.

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/57660542-7418d800-762a-11e9-878b-ed67b2efcbb3.png)

This is a start. i'm happy with that for now, it's really just a notification you should glance and ignore.
