### ISSUE TITLE
Updates to the Wiki

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1879]
Hello! I've gone through the Wiki and made a series of edits on my own copy, that I wanted to have looked over before pushing here. This is a summary of changes:

* Moved content of Home page to the sidebar
* Added some more items to Features section
* Moved content from about page to home page
* Fixed lots of syntactical errors in markdown formatting.
   * Some of these resulted in improperly displaying content such as lists. Most of these were just simple, such as adding spaces between headings, or trailing whitespace after lines..
   * Changed all code blocks to use three back-ticks instead of spaces, and ensured proper syntax highlighting was used.
   * However, there were a couple instances of content that was essentially invisible because it used angle brackets without properly escaping them.
* Several quick grammar errors in writing, and couple spelling errors.

Found here: https://github.com/kuzi-moto/ampache/wiki

In my next revision, I'd like to more thoroughly parse through each article ensuring proper grammar, making sure that sentences actually make sense, and possibly re-arranging content to make sure it's in the most intuitive location.

Please let me know if there are any questions/comments/concerns around these changes, and if I should ask before making them in the future.

Also, @lachlan-00 if there is a feature missing, or something that you add in the future that you would like an article for, I would be happy to write it for you.

I'm sort of a nut about documentation!

**Comment by lachlan-00** [comment]
Hey. Thanks for taking the time to do this. The wiki is such an important tool for everyone to keep maintained.

There was a lot of old info and just having a read over for coherence is a great start.

One thing I have been mulling over is how to document the API correctly.

I want to work out a way of documenting code.
```
/**
     * record_play
     * MINIMUM_API_VERSION=400001
     *
     * Take a song_id and update the object_count and user_activity table with a play
     * This allows other sources to record play history to ampache
     *
     * $input = array(id     = (int) $object_id
     *                user   = (int) $user_id
     *                client = (string) $agent (optional))
     *
     * @param array $input
     */
    public static function flag($input)
```
Into a clearer template that's a bit easier to follow.

I'll have a read over but don't feel apprehensive about requesting changes for the work you've started.

Once core moves in to develop there is going to be a big update anyway.

**Comment by kuzi-moto** [comment]
Okay great. Should I go ahead and update all the pages then?

Better documentation on the API is definitely a good idea. Perhaps there are other projects with good examples? Also, were you thinking of documenting the code itself, or just the wiki?

**Comment by lachlan-00** [comment]
I would update everything that needs an obvious change but we will need to do another rewrite when core moves into develop and it would need to be complete before releasing as 4.0.0.

When I say document code I mean I'd like to have both code and wiki updated for the api.

The documentation on the subsonic api site seems like a good example.
http://www.subsonic.org/pages/api.jsp

Their structure makes a lot more sense than the way it's done here.
Content doesn't matter so much as I can update all that as we go.

**Something like this?**

## Intro

Main api page

### Auth

link to separate section about auth with examples

### Errors

link to separate section about the error responses you get.

### Version History

Current version and 4.0.0-prerelease history / changelog

### API method documentation

Link to a documentation page for all methods (style TBD) with examples

**Comment by lachlan-00** [comment]
@kuzi-moto I just had a browse of your fork of the wiki. i really love what you've done in a day!

**Comment by kuzi-moto** [comment]
@lachlan-00 Thanks! Just some quick restructuring and editing. There are definitely some other things that could use editing though! I'll go ahead and update the wiki here then. 

How thorough did you want the rewrite to be? Were you thinking about scrapping existing content, and starting from scratch, or just making sure everything is up-to-date and any missing holes are filled?

I do think that is a decent way of documenting the API, and I'm sure once we get it set up it will be easier to see if there's anything that can be done to make it better.

**Comment by kuzi-moto** [comment]
Hmm, looks like I can't push changes to the wiki from my PC, but I can edit individual files in the browser. If you want you can clone mine and merge it here.

**Comment by lachlan-00** [comment]
Closing because your wiki is now the ampache wiki!

Make changes on the individual pages and i'll add you to the docs/acknowledgements to make sure your contribution is acknoledged!
