### ISSUE TITLE
installing issue load_gettext fatal error

### ISSUE THREAD

**Issue by etay-zas** [ampache/ampache#1894]
Hi everybody!

I have my XAMPP up and running for a while, mod_rewrite enabled and overrides allowed for all.
Although, I Couldn't make this great Ampache work on my XAMPP.

here is the error I found on my http://localhost/ampache/install.php:
`Fatal error: Uncaught Error: Class 'Gettext\Translator' not found in C:\xampp\htdocs\ampache\lib\i18n.php:36 Stack trace: #0 C:\xampp\htdocs\ampache\install.php(103): load_gettext() #1 {main} thrown in C:\xampp\htdocs\ampache\lib\i18n.php on line 36`

**this is my set up:**
XAMPP Version 7.3.0
Apache 2.4.37
PHP 7.3.0

Thanks for your kind help,
Etay

**Comment by lachlan-00** [comment]
Getteslxt means you probably haven't run composer install.

You can't unzip Ampache and install without that first.

https://github.com/ampache/ampache/wiki/Installation

**Comment by lachlan-00** [comment]
This should help you get composer if you still need info but that is definitely the issue.

https://www.thecodedeveloper.com/install-composer-windows-xampp/

Closing.

**Comment by etay-zas** [comment]
Worked, thanks!
