### ISSUE TITLE
translating strings that are equal to the source string?

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1896]
@Psy-Virus do you want to only translate strings that don't match the source string?

e.g. English words that are the same:
Deleted (US)
Deleted (UK)

**Comment by Psy-Virus** [comment]
I guess you mean for the English (UK) version?

Then yes. Only if there is a difference between the US and UK string.

For example:
US: Theme color
would be 
UK: Theme colour

If they're the same, we don't need a translation string as the original string is shown by default.

Btw. I plan to update the translations at Thursday, as I'll be AFK on the weekend. Just to let you know, when

**Comment by lachlan-00** [comment]
Thanks for clarification. I assumed that was the process.

I'll also update the wiki to mention not to translate redundant strings
