### ISSUE TITLE
Playlists show up empty on client side (SubSonic API)

### ISSUE THREAD

**Issue by simpledisaster** [ampache/ampache#1897]
# Environment

 * Ampache version: 3.8.6
 * Web server + version: Apache2 (most current)
 * Server operating system: Dietpi (Debian)
 * Client operating system: iOS AVSub (SubSonic API)

 * Client type:
   - SubSonic

# Description

Hello everyone! I'm wondering if there's a known bug that lets Smart Playlists created in Ampache with over 3000 or 1000 songs result in "empty" and not playable playlists on clients using the SubSonic API. These Smart Playlists are usable in the Web-version of Ampache and they have not been created within the App. I haven't been able to try the developer-branch yet. The client (AVSub) is receiving updates on regular basis and has not been abandoned. Otherwise it is not a problem to browse through the library and play songs.

Or this is this due to the fact that it's a Smart Playlist and not a regular Playlist? Would that make a difference (what is the difference between those two actually?) ?

Thanks in advance for any thoughts!

<img width="414" alt="20190521_130459593_iOS" src="https://user-images.githubusercontent.com/22875294/58098419-d8630b00-7bd9-11e9-904a-3124e4dadf6d.png">

**Comment by lachlan-00** [comment]
I haven't used this client (don't own an ios device) but i have issues once the smart list is over about 3000 items. In Dsub it can take 15-20 seconds for my phone to reload a 2700 track playlist.

The likely issue is that the lists are too large before the web server or the app itself time out.
Once they timout out the client fails over to listing the incomplete playlist as empty.

**Comment by simpledisaster** [comment]
Thanks for checking in on my issue, @lachlan-00 !

It seems I have solved the problem by...

1. Creating a smart list (in my case I wanted one with tags for separating genres and putting them into separate smart playlists).

2. Selecting all songs and creating a temporary playlist.

3. Adding that temporary playlist to a regular playlist.

4. (optionally) Deleting the smart playlist created in Step 1 (because I'm not able to select it on client side anyway).

Now, these show up as regular playlists full of content on client side just as intended.

You actually touched a problem that I am having now after solving my initial issue. I can select and play a playlist with 500 songs, which shows up after about 10 seconds of loading, but a playlist with 2000 songs times out after about 25 seconds and doesn't play. Is there any way of increasing the moment of timeout for playlists?

Thanks in advance!

**Comment by lachlan-00** [comment]
I'll be looking at the speed of these things once I get v4 out.
Ampache has a caching feature which I think might be able to fix these issues.

Another option is to make them random with a smaller limit. I set mine to 50 and refresh them to get a new list.

**Comment by simpledisaster** [comment]
> I'll be looking at the speed of these things once I get v4 out.
> Ampache has a caching feature which I think might be able to fix these issues.

That sounds awesome. So I'll hang tight for this!! Thanks so much!!

> Another option is to make them random with a smaller limit. I set mine to 50 and refresh them to get a new list.

It's a good option for the web-version, but here again it's the problem of not being able to access smart playlists on any of my clients (also tried Substreamer now), and that feature seems limited to smart playlists.

Generally speaking, is there another way of sorting Genres / Tags using the Subsonic API?

**Comment by rodrigoesborges** [comment]
Just to note I seem to have a similar problem, though my limit seems rather low. As long as I create a smart playlist with more than, say, 250 songs, I start to have issues with subsonic client

**Comment by simpledisaster** [comment]
Apparently, the limitation of songs in a playlist is based on how much RAM you have on your Ampache Server (device).

**Comment by rodrigoesborges** [comment]
In my case more than 10g on server, can't imagine it as an issue.
On earlier versions, like 3.8.* such lists even without limits, involving several thousand songs, where displayed appropriately

Em 23 de outubro de 2019 11:47:34 BRT, simpledisaster <notifications@github.com> escreveu:
>Apparently, the limitation of songs in a playlist is based on how much
>RAM you have on your Ampache Server (device).
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ampache/ampache/issues/1897#issuecomment-545480063

-- 
Rodrigo Emmanuel Santana Borges Borges
Doutor em Economia internacional - Universidad Complutense de Madrid
Pós-doutorando em Política Social - PPGPS/UFES

**Comment by simpledisaster** [comment]
You are right - 10gb of RAM should be able to handle larger playlists if the way that they are being handled hasn’t changed. But according to your statement that it was working fine on earlier versions implies that it has changed.
Could you provide any logs around the moment when selecting / playing aforementioned playlists?

**Comment by lachlan-00** [comment]
At about 2500+ it's usually a timeout on the subsonic client. But this is partially because of the time it takes to build the list in Ampache.

If I request the XML in Firefox with a high time limit it will work.

The goal in this issue is to reduce the time it takes to build large lists.

**Comment by rodrigoesborges** [comment]
Sorry guys, it was a misconfiguration on my nginx server part. I can retrieve again even unlimited smart playlists

**Comment by kuzi-moto** [comment]
What did you need to change? Is it worth putting in the wiki?

**Comment by lachlan-00** [comment]
I've made smart lists faster by caching the amount of items and length of the list cache in the database. this speeds up things a lot so the issues like this should be reduced.

reopen if you have a problem but i have lists over the 5000 that load okay now in subsonic.
