### ISSUE TITLE
no longer needed (issue fixed myself but dont know how)

### ISSUE THREAD

**Issue by Cutters1982** [ampache/ampache#1908]
*please ignore, issue fixed, but unsure of exact fix)

**Comment by lachlan-00** [comment]
I'll have a look at uploads personally later just to make sure they're all okay 

To make your log directory you need to make an Ampache folder. (The web server doesn't have permission to the log folders automatically)

```
sudo mkdir /var/log/ampache
sudo chown www-data:www-data /var/log/ampache
```

Now that you've made the log directory Ampache can write to that folder.

**Comment by Cutters1982** [comment]
great, thanks for the info regarding logs, at least I know for future reference :) incase I have any issues I can enable debugging again

**Comment by Cutters1982** [comment]
@lachlan-00 I've tried enabling debugging (logging) - but it's not working, doesnt create any .log files at all, any ideas? I have it on debug level 5 at present, shall I try lowering it down to 1 or 2?

Thanks in advance

**Comment by stebe** [comment]
Here are the details on how to enabling logging in Amache.  https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging

**Comment by Cutters1982** [comment]
Thank you, I'm going to give it another try now using that guide, will let u know how I get on :-)

**Comment by Cutters1982** [comment]
Yeah, that guide is as per what I have done, but still no luck.

I created that /var/log/ampache folder and set chmod to allow writing permissions and set www-data:www-data for that folder...

Any ideas please?

**Comment by stebe** [comment]
anything in the Apache server error logs?

**Comment by Cutters1982** [comment]
Just looked and only this shows up:-

[Sat Jun 01 02:55:30.544493 2019] [mpm_prefork:notice] [pid 1140] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sat Jun 01 02:55:30.544569 2019] [core:notice] [pid 1140] AH00094: Command line: '/usr/sbin/apache2'
sh: /home/ampache: Is a directory
[Sat Jun 01 03:07:27.587272 2019] [mpm_prefork:notice] [pid 1138] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sat Jun 01 03:07:27.637588 2019] [core:notice] [pid 1138] AH00094: Command line: '/usr/sbin/apache2'
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
sh: /home/ampache: Is a directory
[Sat Jun 01 14:06:22.325013 2019] [mpm_prefork:notice] [pid 1156] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sat Jun 01 14:06:22.330940 2019] [core:notice] [pid 1156] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 01 14:57:50.753540 2019] [mpm_prefork:notice] [pid 1156] AH00169: caught SIGTERM, shutting down
[Sat Jun 01 15:02:04.027533 2019] [mpm_prefork:notice] [pid 23747] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Jun 01 15:02:04.027767 2019] [core:notice] [pid 23747] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 01 15:10:21.323518 2019] [mpm_prefork:notice] [pid 1025] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Jun 01 15:10:21.330367 2019] [core:notice] [pid 1025] AH00094: Command line: '/usr/sbin/apache2'
