### ISSUE TITLE
Adding genre to folder pattern?

### ISSUE THREAD

**Issue by Cutters1982** [ampache/ampache#1909]
Hey folks

I wanted to know whether there is a code for Genre so you can add it to the folder pattern?

What I want to do is, people upload something, and Ampache automatically puts it in a folder as follows:-

\Genre\Artist\Title\

As it stands I have %a/%A so it can do \Artist\Title\

Hopefully with the right folder pattern, this then means that the mp3s get moved into the Genre folder which then subsequently updates the catalogs of the relevant genre (my aim is to have a catalog for each genre)

From looking, it appears there is no % code for looking at a genre metadata tag?

Hope someone can help with this

Thanks!

**Comment by Cutters1982** [comment]
Alternatively, is there a way of setting it up so that the uploader chooses what catalog the uploaded files go in?

I could then set up a catalog for each genre, and when someone uploads they can just choose from a drop down what catalog the file should go in?

**Comment by kuzi-moto** [comment]
Is there a particular reason you don't tag the music with the genre? There are tons of different genres would be a pain to have a separate catalog for each one, when you can already browse by-catalog.

There are tons of tools to do this automatically. Picard has a GUI, and Beets is a command line tool.

**Comment by Cutters1982** [comment]
Yeah, I do tag the music with the genre, I just wanted to go down the route of having a catalog for each genre :)

**Comment by kuzi-moto** [comment]
You would have to manually create a new catalog per genre anyway, as the catalog creator only creates one catalog at a time. The folder patterns let's the catalog know how to expect layout of music so it can correctly index the music (I believe).

**Comment by Cutters1982** [comment]
yeah, I realise I can only do 1 catalog at a time, was just wondering how I can set up the folder pattern thing so it moves the uploaded files into the relevant genre folder, basically.

**Comment by lachlan-00** [comment]
I do want to extend the item matching as it doesn't fit my library format either but it's a nice-to-have so I won't be working on it for a bit while we work on the next release.

Ideally any tag Ampache reads we should be able to match on.

**Comment by Cutters1982** [comment]
^ yeah, ideally! hope they will extend the functionality of it.

**Comment by lachlan-00** [comment]
I've started work on adding additional tags into the library/db as well in #1964 

Another step in this update will be extending the matching for tags. there are a few other bugs to fix first but it is at least in progress now.

**Comment by lachlan-00** [comment]
@Cutters1982 i've started looking at this and it looks like genre is already in the lists. It's not in sort_files.inc so don't use that yet but it looks like most of the work is done, just not in the UI to tell us
```
function translate_pattern_code($code)
{
    $code_array = array('%A' => 'album',
            '%a' => 'artist',
            '%c' => 'comment',
            '%g' => 'genre',
            '%T' => 'track',
            '%t' => 'title',
            '%y' => 'year',
            '%d' => 'disk',
            '%o' => 'zz_other');
```

**Comment by kuzi-moto** [comment]
How is zz_other used?

**Comment by lachlan-00** [comment]
From what i can tell searching around absolutely nothing.

It seems to only be in the page ui and that array.
![image](https://user-images.githubusercontent.com/1305249/60786523-44093380-a19a-11e9-9dbe-2ad818266176.png)

**Comment by lachlan-00** [comment]
I'll be testing in #1964 but this should be pretty simple seeing as the code is already there.

**Comment by lachlan-00** [comment]
This has been added to develop.

**Comment by Cutters1982** [comment]
Great, thank you lachlan :)
