### ISSUE TITLE
Music file not added to catalog - mysql error "Data truncated for column 'mode'"

### ISSUE THREAD

**Issue by DrMMu** [ampache/ampache#1913]
# Environment

 * Ampache 3.9.0-release
 * Web server + version: Apache/2.4.18 (Ubuntu), PHP 7.0.33-0ubuntu0.16.04.5 (cli) ( NTS )
 * Server operating system: Ubuntu 16.04.6 LTS
 * Client operating system: N/A

# Description / Excerpt from the Log
An mp3 file is not added to the catalog. At debug level 5, the corresponding log entry reads:

    (Dba) -> Error: ["01000",1265,"Data truncated for column 'mode' at row 1"] 

I set debug level 6 to see what has been sent to the database:

    (Query) -> INSERT INTO `song` (`file`, `catalog`, `album`, `artist`, `title`, `bitrate`, `rate`, `mode`, `size`, `time`, `track`, `addition_time`, `year`, `mbid`, `user_upload`, `license`, `composer`, `channels`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ["\/home\/ubuntu\/x.mp3","2","304","729","La Terraza",128000,44100,"unk",67745175,4233,1,1560102651,2013,null,null,null,"",2]

This is a little tough to read, but ampache has sent the string "unk" for the "mode" field, and the database can't swallow that.
I tried with another file. In this case ampache sends 'null', and it works.

I assume that there is something in the file which causes ampache to set the mode to "unk". But what can that be?

Thanks for reading this far. Any comments are appreciated!

Best, Dr. MMu

**Comment by lachlan-00** [comment]
Thanks for digging into your logs. I'll check it out and report back for you

**Comment by lachlan-00** [comment]
Fist up it could be as simple as the encoding/tags are mangled somehow.

Another step is to run something like vbrfix on the file to correct any weirdness.
http://manpages.ubuntu.com/manpages/precise/man1/vbrfix.1.html

Initially to me it looks like a bad file so lets look at that first.

**Comment by DrMMu** [comment]
Thank you some much for directing me to `vbrfix`! I applied `vbrfix` to the suspicious file with `-always -makevbr`, and I could add the file to the catalog.
(`-always` alone was not sufficient).
According to the log (at debug level 6), ampache has now passed "vbr" as the "mode" to the database (instead of "unk").

Fun fact: The suspicious file is CBR! (I validated this using `vbrfix` with `-log`)
Why ampache passed "unk" as the mode for the original (CBR) file, is beyond me, but my original problem is fixed now.

Thanks again and best regards, Dr. MMu

**Comment by lachlan-00** [comment]
I'm putting in a new debug message to warn when this happens. it won't fail but should give you a better idea of why this happened.

debug_event('song.class', 'Error analyzing: ' . $file . ' unknown file bitrate mode: ' . $mode, 2);

Which will log a message like this:
```
2019-06-11 09:29:29 [user] (song.class) -> Error analyzing: /mnt/music/badfile.mp3 unknown file bitrate mode: unknown
```
