### ISSUE TITLE
Special characters in user fullname fields are getting over-escaped

### ISSUE THREAD

**Issue by lavacano201014** [ampache/ampache#1917]
# Environment

 * Ampache version: 3.9.2
 * Web server + version: Apache
 * Server operating system: Ubuntu 18.04

 * Client type:
   - Web

# Description

![Screenshot_20190612_092306](https://user-images.githubusercontent.com/4407155/59368770-cb769a80-8cf3-11e9-93bc-0f394e9bd5b2.png)

That's supposed to be an apostrophe. If I go into account settings to change something else, that becomes `&amp;#039;`, and so on and so on until I finally change it back to a regular old `'` character.

**Comment by lachlan-00** [comment]
I see it, i'll fix that up now and i'll be updating the core branch today.

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/59394948-04cb0b00-8dc5-11e9-84f0-2169e9ab3e5d.png)
Fixed in core Update 13
