### ISSUE TITLE
Dark overlay when using web player.

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1933]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Web server + version: apache 2.4
* Server operating system: Debian Buster
* Client operating system: Windows 10

* Client type:
  * Web
  
## Settings
Specific settings can be added if needed.

## Description
When playing songs with the web player a dark overlay happens on the main window. I'm using Ajax pageload and HTML5 web player. At one time I used to have a flckr slideshow but I disabled the flickr plugin.

![image](https://user-images.githubusercontent.com/4076671/59866432-8ab4fc00-9359-11e9-9066-863578445ba1.png)

**Comment by stebe** [comment]
If I do this in templates/headers_inc.php on line 230 the attempt to display a slideshow is disabled.
        //    var refresh_slideshow_interval=<?php echo AmpConfig::get('slideshow_time'); ?>;
            var refresh_slideshow_interval = 0;

I don't know how to set this configuration as there seems to be no option to do this in the UI or ampache.config.php. Perhaps at one time there was such an option.

**Comment by lachlan-00** [comment]
```
AmpConfig::get('slideshow_time')
```
It's a db option under interface.
![image](https://user-images.githubusercontent.com/1305249/59886652-2fd7df00-9403-11e9-9393-857acbec9a19.png)

It should be checking for the flickr plugin instead of just showing nothing. i'll fix that

**Comment by lachlan-00** [comment]
This button should remove the slideshow
![image](https://user-images.githubusercontent.com/1305249/59886940-94476e00-9404-11e9-903c-720d802573f8.png)

Will be fixed in #1932

**Comment by lachlan-00** [comment]
can you let me know if the latest develop stops this?

It seems like that slideshow is only for the flikr plugin.

**Comment by stebe** [comment]
This is now fixed. Thanks.
