### ISSUE TITLE
White screen updating develop

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1937]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop

## Description

When updating Ampache to 4.0.0-develop using the debug page, I got a white screen. I have already resolved the issue, but wanted to post about it just in case it happens to anyone else.

I ran git pull which said it was up to date, then ran composer, and it said the following:
```shell
  - Updating gettext/languages (2.3.0 => 2.5.0):     The package has modified files:
    M bin/export-plural-rules.php
    Discard changes [y,n,v,d,s,?]? y
```

Afterwards, I ran `composer install --prefer-source --no-interaction` to be safe, though I'm not sure it was required. Not sure how a file was modified, since I never make any changes, but perhaps a one off bug?

**Comment by lachlan-00** [comment]
hey, do you remember what page gave you the white screen?
I've set test and install to error out so this is a different one?

**Comment by lachlan-00** [comment]
actually it's in init. wil be fixed soon.
