### ISSUE TITLE
Error: Unable to make database connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by Wicked0ne** [ampache/ampache#1939]
## Environment

* Ampache version: ampache-3.9.0_all.zip
* Web server + version: nginx/1.10.3
* PHP: PHP 7.0.33-0ubuntu0.16.04.5(using php-fpm)
* Server operating system: Ubuntu 16.04

* Client type:
  * Web

## Description

I clone the repo(master) into my web directory, 
browse to http://domain.com/ampache, 
get redirected to http://domain.com/ampache/install.php, 
choose language, 
see requirements(everything is green except php max upload size), 
click continue, 
see Insert Ampache Database, 
enter fields: 
Desired Database Name, MySQL Hostname, MySQL Administrative Username, MySQL Administrative Password, 
select create database, create tables, 
hit insert database
I then get an error saying: Error: Unable to make database connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

After googling it seems mysql 8+ changed the authentication methods so I edit mysql's config section [mysqld] and add default_authentication_plugin = mysql_native_password, restart mysql then proceed to login to mysql(mysql -uroot -p) and use alter to alter my users password auth plugin to mysql_native_password and change the password.

After changing the mysql password auth stuff I retry the ampache install and I get the same error:  Error: Unable to make database connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

**Comment by lachlan-00** [comment]
There is another MySQL report for this version. I'll have to install the db and take a look as I use mariadb

**Comment by Wicked0ne** [comment]
Thanks, I see to have forgotten the exact mysql version in my original post.
mysql -V                                             
mysql  Ver 8.0.15 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by lachlan-00** [comment]
Seems to be from Sha2 password caching.

In the mean time unless you have a specific reason while I work this out mariadb works correctly.

**Comment by Wicked0ne** [comment]
Yea its something to do with how php connects to the mysql server. I just don't know enough to dig deeper. 

I already have mysql and postgres installed due to various projects. I may see about mariadb, but would like to not install another database lol.

If you need any additional info from me, I'm happy to help.

**Comment by lachlan-00** [comment]
The answer here is probably where I'll start.

https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

**Comment by Wicked0ne** [comment]
From my googling earlier, it seemed like it related to the php mysql extension. https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

**Comment by lachlan-00** [comment]
I've installed mysql 8 from their debian repo and enabled legacy auth during the install.

will test tonight installing ampahe on my pc and see what happens

**Comment by lachlan-00** [comment]
Fixed it.
Even though you set native auth during install you actually have to recreate the user password to allow auth in ampache.

Tested successfully using mysql 8 from the oracle official repo
```
root@steam:~# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 615
Server version: 8.0.16 MySQL Community Server - GPL

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'PASSWORD;
Query OK, 0 rows affected (0.05 sec)

mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.01 sec)
```

This will fix all auth problems. If you have an existing database you can just recreate a new user in mysql and it will connect.

**Comment by lachlan-00** [comment]
I've put a workaround into current develop to force mysql8 to use native password.  (https://github.com/ampache/ampache/commit/485bf2a5a95ec717eed8df986eced3e7652888be)

I've tested with mysql8 and with mariadb successfully creating users and databases.
