### ISSUE TITLE
Seafile plugin removed

### ISSUE THREAD

**Issue by PlaidPhantom** [ampache/ampache#1941]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Web server + version: Apache 2.4.29
* Server operating system: Ubuntu 18.04

## Description

Hi, I noticed that the Seafile catalog plugin I created was removed in the most recent development release.  I understand if the (apparently changed?) core team doesn't want to support it in the main repo, but what would be the best way for me to support/publish such a plugin?  There's not much guidance on this that I've been able to find.

**Comment by lachlan-00** [comment]
restored the plugin.
