### ISSUE TITLE
Use and/or import MPD/beets database database

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#1943]
Ampache takes quite a long time to do a full update.  With over 30,000 tracks a full import takes hours.  I have two other applications that contain a full database of my music,.  One is mpd, which is able to update my music very quickly.  The other is beets, which I use to tag all my music.  It would be nice if ampache was able to either use one of those databases or import them, rather than scan my hard drive.

**Comment by kuzi-moto** [comment]
Ampache supports having a beets database by default. You can enable it by clicking on the power-plug looking icon (should be called modules if you hover over it) and then click on "Catalog Modules". If you click on "Activate" next to beets, then you can create a catalog of that type.

Supposedly it should be working, but for some weird reason it never did for me unfortunately.

**Comment by apastuszak** [comment]
I'll give that a try.  Thanks!
