### ISSUE TITLE
cannot select add to new playlist

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1945]
# Issue Template

## Environment

* Ampache version: 4.0.0 develop
* Web server + version: Apache 2.4.38
* Server operating system: Debian 10 (Buster)
* Client operating system: Windows 10

* Client type:
  * Web
  * Ampache

## Description

When attempting to add a temporary playlist to a real playlist it's impossible to select. The selection disappears as the mouse moves away from the button. Similar to issues #572 and #901.

![image](https://user-images.githubusercontent.com/4076671/60021908-da007280-9660-11e9-8145-2faa7cb59fea.png)

**Comment by lachlan-00** [comment]
Is this in a webkit browser?

Chrome had some weird bugs with the css but i thought i'd stopped that. You hover over the button and it just keeps moving over?

**Comment by lachlan-00** [comment]
Oh sorry, i misread, the playlist list isn't moving. i'll fix that. in #1948
