### ISSUE TITLE
"Authorize Flash Web Player(s)" still in server preferences

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1954]
## Description

I believe that the flash player was removed some time ago after the HTML5 player became standard.

**Comment by lachlan-00** [comment]
I've always stared at this wondering as well. i'll have a look for a reason to keep it or drop it.

**Comment by kuzi-moto** [comment]
I also still see some references to Plex in parts of the code. I'm guessing there are a lot of things like that still around.

**Comment by lachlan-00** [comment]
There's probably two obvious places left to remove plex besides translations. (ampache.sql and lib/preferences.php) it gets removed from the database so it's dead code right now.

There are some references in jplayer regarding a flash backend but i don't know if that's actually usable. It looks like there are 3 player types jplayer can use.
![image](https://user-images.githubusercontent.com/1305249/60390408-6b685c80-9b19-11e9-9bfa-e82a3f94635c.png)

**Comment by lachlan-00** [comment]
Looks the jplayer repo is still using swf as a module so i think we keep it.
![image](https://user-images.githubusercontent.com/1305249/60482975-e1fe8900-9cd6-11e9-8aa7-15035ee218b7.png)
