### ISSUE TITLE
XML API - No owner set when creating a new playlist

### ISSUE THREAD

**Issue by ROYALBEFF** [ampache/ampache#1955]
# Issue Template

## Environment

* Ampache version:  Ampache 3.9.0-release
* Web server + version: Apache/2.4.18
* Server operating system: Ubuntu 16.04.6 LTS
* Client operating system: Fedora 30

* Client type:
  * Ampache

## Settings

I kept the default settings for everything.

## Description

I'm using the Ampache plugin for Rhythmbox. Streaming music works perfectly fine.
I'm trying to implement some new features for the plugin.
When creating a new playlist via the XML API, the newly created playlist has no related user.
This is the response I get:

```{xml}
<root>
<total_count>1</total_count>
<playlist id="160">
  <name>test</name>
  <owner></owner>
  <items>0</items>
  <type>public</type>
</playlist>
</root>
```
The playlist was (more or less) succesfully created but can only be seen by the administrator.

This is the API call that is used for the handshake:
```
[URI]/server/xml.server.php?action=handshake&auth=[AUTH]&timestamp=[TIMESTAMP]&user=[USER]&version=350001
```

Then I tried to create the playlist like this:
```
[URI]/server/xml.server.php?action=playlist_create&name=test&type=public&auth=[AUTH]
```
I already searched the XML API documentation, but there is no owner parameter that could be used to set the owner name manually.

## Logs

Here is the log of the login attempt and the creation of the new playlist. The playlist creation did not appear in the log, but the playlist was again created without an owner.

```
2019-06-29 23:59:16 [ampache] (API) -> Handshake Attempt, IP:[IP] User:[USER] Version:350001 
2019-06-29 23:59:16 [ampache] (API) -> Login Attempt, IP:[IP] Time: [TIMESTAMP] User:[USER] (2) Auth:[AUTH] 
2019-06-29 23:59:16 [ampache] (session) -> Unable to read session from key  no data found 
2019-06-29 23:59:16 [ampache] (session) -> Session created: 66ecf4e1355bc0fa2700b065814c9c89 
2019-06-29 23:59:16 [ampache] (API) -> Login Success, passphrase matched 
```

**Comment by kuzi-moto** [comment]
There have been some improvements to the API in the develop branch. Would you be able to try it out there and see if you're still having the same issue?

**Comment by lachlan-00** [comment]
In current develop i create a playlist and it assigns owner. It's been a few years sine i've used master and won't be changing anything in that branch outside of moving in a new version from develop.
```
https://AMPACHE/server/xml.server.php?action=playlist_create&name=Test private&type=private&auth=AUTHKEY&version=350001
```
This works with private or  public
![image](https://user-images.githubusercontent.com/1305249/60390273-576f2b80-9b16-11e9-8326-66a877e4a5ca.png)

So short answer is i could look at what's happening in master but won't be doing anything outside of confirming your issue.

**Comment by ROYALBEFF** [comment]
Thanks to @lachlan-00 for testing the playlist creation with the development version. I'll try to check out the development version myself as soon as I can.

**Comment by ftoledo** [comment]
I have similar issue with the flag api, the user is set to 0 in the database #1971

**Comment by lachlan-00** [comment]
I've added some more to the api and this should never happen after it merges

**Comment by ftoledo** [comment]
good i will update a test!
thanks!

**Comment by lachlan-00** [comment]
test the update that just merged now! I think the missing users are fixed by searching for the id's correctly in this update.

**Comment by lachlan-00** [comment]
API requests are using the user from the call instead of the GLOBAL from before.
i've left this open but i'm pretty sure it's been fixed for a long time

**Comment by lachlan-00** [comment]
closing fixed, there should not be any more instances of this as it doesn't rely on the globals for the user.
