### ISSUE TITLE
Capitalization in Ampache Web Interface

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1956]
# Description

So, I know that in the grand scheme of things, this is any incredibly minor issue. But as someone with OCD like tendencies, it sticks out like a sore thumb.

What I'm talking about, is the inconsistent capitalization found in Ampache's Web Interface. Here are some of the things I'm talking about:
![Screenshot_20190629-205636](https://user-images.githubusercontent.com/17068090/60391308-15f86500-9ab1-11e9-9ed9-1e8bb5ebd78c.png)
The preferences page is probably the worst offender:
![Screenshot_20190629-210731](https://user-images.githubusercontent.com/17068090/60391365-789e3080-9ab2-11e9-8c23-e58432bb5268.png)
* URL should be capitalized
* Title is capitalized. I'm not sure it needs to be.
* playing is lowercase, but below it's capitalized. Need to pick a standard. Is "now playing" considered a proper noun and should be capitalized?
* Albums is capitalized, but moment isn't. Same case as now playing.
* Sort is randomly capitalized.
* Web player - Web is capitalized, and player is not.
* Lyrics is capitalized.

There are more on that and other preference pages.

And last example on the localplay controllers page:

![Screenshot_20190629-212035](https://user-images.githubusercontent.com/17068090/60391444-09294080-9ab4-11e9-8d37-e7d308213985.png)

* UPnP should be UPnP
* Mpd should be MPD
* Vlc should be VLC
* Xbmc should be XBMC
* Httpq should be httpQ

That's not the only cases, just ones I found quickly... I think that this would be a nice thing to change, as it would make Ampache appear more professional in keeping a consistent style.

As I don't have much programming skill, I thought I would go ahead and find these and change them. Figured I'd ask first before going ahead with it if there would be any problems, like with translations.

**Comment by lachlan-00** [comment]
Be good to do asap as translations need to be updated now that develop is updated. I merged and replaced a lot of strings so I'll try to get this done asap tonight.

**Comment by lachlan-00** [comment]
working in pull #1957

**Comment by kuzi-moto** [comment]
If you want any help I'd be happy to go search through the files to find other things.

**Comment by lachlan-00** [comment]
Put anything you spot in the pull. I did a big search and replace last night and an initial db update as well so a lot might be in there

**Comment by lachlan-00** [comment]
A. Lot. of changes in the pull now.

I don't want to do this again after this pull or nobody will want to translate for us again!

**Comment by lachlan-00** [comment]
Closing as part of strings update. Looking forward to getting it merged. :)
