### ISSUE TITLE
Can't create database user on Windows with Bitnami WAMP

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1958]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Web server + version: Apache 2.4
* Server operating system: Windows 10
* Client operating system: Windows 10

* Client type:
  * Web: Firefox Nightly

## Settings

N/A

## Description

I was doing some testing, and ran into an error while trying to install Ampache on Windows. It seems to run into a problem when trying to create a user for the database: `Error: Unable to create user ampache with permissions to ampache on localhost: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'ampache' WITH GRANT OPTION' at line 1"]`

* MySQL: Ver 8.0.16 for Win64 on x86_64 (MySQL Community Server - GPL)

I dug around, and it created the database, but didn't populate with tables, and didn't create the user. If I do not specify it to create a user, then it proceeds as normal.

I don't know if it matters, but it's the pre-packaged WAMP server by [bitnami](https://bitnami.com/stack/wamp)

**Comment by lachlan-00** [comment]
Could probably be mysql 8 specific. I did have mysql8 installed to check it out but didn't create a user.

Oracle have put in a big change to auth in 8 so it's a bit flakey while distros catch up.
https://github.com/ampache/ampache/issues/1939

if you have it loaded still you can test altering lib/install.lib.php
![image](https://user-images.githubusercontent.com/1305249/60475453-b79ed280-9cba-11e9-80ba-3fbcd181ed6f.png)


```
$sql .= "IDENTIFIED WITH mysql_native_password BY '" . Dba::escape($db_pass) . "' WITH GRANT OPTION";
```

**Comment by lachlan-00** [comment]
Also try this instead. (same file) this falls through to trying with the additional WITH mysql_native_password in the above after trying the normal way.

```
        $sql .= "IDENTIFIED BY '" . Dba::escape($db_pass) . "' WITH GRANT OPTION";
        if (!Dba::write($sql)) {
            //try mysql8 legacy auth on failure
            $sql = str_replace('IDENTIFIED BY ', 'IDENTIFIED WITH mysql_native_password BY ', $sql);
            if (!Dba::write($sql)) {
                AmpError::add('general', sprintf(T_('Error: Unable to create user %1$s with permissions to %2$s on %3$s: %4$s'), $db_user, $database, $db_host, Dba::error()));
            }

            return false;
        }
```

**Comment by kuzi-moto** [comment]
Sweet, I'm not at my computer but I'll give it a go tomorrow.

**Comment by lachlan-00** [comment]
Needs more work. Syntax is different enough that I need to work on this more.

**Comment by lachlan-00** [comment]
Please update to develop and test again. (https://github.com/ampache/ampache/commit/485bf2a5a95ec717eed8df986eced3e7652888be)

I've tested with mysql8 and with mariadb successfully creating users and databases.

**Comment by lachlan-00** [comment]
closing as i put a workaround for myssql8 into the install
