### ISSUE TITLE
Double Slash in localplay MPD

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#1959]
# Issue Template

## Environment

* Ampache version: 4.0.0 dev
* Web server + version: Apache 2.4
* Server operating system: Linux Ubunutu 18.04
* Client operating system:

* Client type:
* MPD

## Description
Localplay MPD doesn't work anymore on my computer.
In logs (MPd, Apache) I found an error 404 for each tracks.
there is two "/" between "player" and "name".
I try the url corrected with mpc and it's work.
I also found this double slash in ampache log uid\/2\/player\/\/name\

**Comment by lachlan-00** [comment]
beautiful_url's/"Enable URL Rewriting" enabled?

I think i know what this is.

**Comment by douglasriper** [comment]
It was disable.
I try with enable and Thérèse no change.
With dsub the url is right. (type/song/oid/74904/uid/2/client/DSub/noscrobble/1/player/api/name/The)
It's just for localplay

**Comment by lachlan-00** [comment]
okay, that's not what i thought but i'll work on this soon to confirm and ideally fix!

**Comment by douglasriper** [comment]
Thanks Lachlan 🙂

**Comment by lachlan-00** [comment]
looking at it now.

This is when sending a track to the localplay server?

**Comment by douglasriper** [comment]
Yes, I see the error a when "add" and then when "play"
“process command "add " ...”

**Comment by lachlan-00** [comment]
Can confirm. Will fix asap

**Comment by lachlan-00** [comment]
Reminder for myself. Stream_playlist

**Comment by lachlan-00** [comment]
it's something in the url generation. It should be including a player type. or not include it at all.

"player//name" should be "player/%PLAYERTYPE%/name" as the name is part of the url for the file name.

Will be able to track this down now just had other things on.

**Comment by lachlan-00** [comment]
@douglasriper sorry so much for spamming you but this will fix you in the short term while i work out why a player isn't there.

Insert @121 in stream_url.class.php
```
$url = str_replace('player//name', 'name', $url);
```

![image](https://user-images.githubusercontent.com/1305249/60782729-2f716f00-a18b-11e9-8762-2f8ebd0158ab.png)
