### ISSUE TITLE
Suggestion: Move "Other Tools" section under Modules to Admin page.

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1960]
## Description

I have always felt that the "Other Tools" are in kind of a weird spot. Doesn't seem like they should be under Modules as I don't think that's what they are. I believe it would make a bit more sense to move it under the Admin page, as it's more of admin tasks type thing.

**Comment by lachlan-00** [comment]
these ones?
![image](https://user-images.githubusercontent.com/1305249/60475097-eddb5280-9cb8-11e9-8478-a1841fc467f6.png)

Maybe this?
* "Ampache Debug" under "Server config"
* "Clear Now Playing" under "user tools"
* "Export catalog" would go under "catalogs"

**Comment by lachlan-00** [comment]
Oh **Modules**!

Duplicates would go into catalogs and mail users would go into user tools

**Comment by lachlan-00** [comment]
The modules section itself could probably just go into preferences as well.

**Comment by kuzi-moto** [comment]
I think that would be a decent idea. Not really a big enough section to have a page for itself.

**Comment by lachlan-00** [comment]
Well this is the time to do it.

I'll take your pull in and work on splitting it all up tonight.

Less areas to look and better grouping is a really positive change

**Comment by kuzi-moto** [comment]
Certainly! I know I've forgotten about the modules page at times wondering where some of the settings were.

**Comment by lachlan-00** [comment]
Merged into stringsupdate pull request. looking a lot cleaner now
