### ISSUE TITLE
Abandoned packages during installation: react/socket-client

### ISSUE THREAD

**Issue by danieldietsch** [ampache/ampache#1966]
## Environment
* Ampache version: git develop 19573a35e
* Web server + version: Apache 2.4.39
* Server operating system: Gentoo 

## Description
Similar to #1848 during install, php composer complains about abandoned packages. 
````
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.
````
The last package, ``react/socket-client`` is new when compared to #1848 .

**Comment by lachlan-00** [comment]
looks like it's a part of react/react right now. 4.2 is also the latest version so i'm not sure how long they'll take to update that.
```
www-data@web:~/music$ composer why react/socket-client
react/http-client  v0.4.17  requires  react/socket-client (^0.5 || ^0.4 || ^0.3)  
react/react        v0.4.2   requires  react/socket-client (0.4.*)  
```

**Comment by lachlan-00** [comment]
react/react and cboden/ratchet are conflicting on react/socket right now.

To move to socket one needs 0.4 and the other 0.5

**Comment by lachlan-00** [comment]
Altering composer.json to remove the specified react/react and updating cboden/rachet will pull in the latest react sources.

Will require testing but it seems okay from an interface perspective initially.
```
www-data@web:~/music$ git diff composer.json
diff --git a/composer.json b/composer.json
index 4207e908..95e7ba26 100644
--- a/composer.json
+++ b/composer.json
@@ -38,8 +38,7 @@
         "mikealmond/musicbrainz": "dev-master",
         "phpmailer/phpmailer": "5.2.*",
         "rmccue/requests": "1.7.*",
-        "react/react": "0.4.*",
-        "cboden/ratchet": "0.3.*",
+        "cboden/ratchet": "0.4.*",
         "symfony/event-dispatcher": "^3.0",
         "symfony/routing": "^3.0",
         "symfony/http-foundation": "^3.0",
```

**Comment by lachlan-00** [comment]
@danieldietsch @areyus i'll be looking at the updating the composer files tonight with these changes.

Will just test on a fresh install to make sure nothing weird happens before i push it.
