### ISSUE TITLE
Update bin/write_playlists.inc to include smartlists and more options

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1967]
The write_playlists script should be extended. it's actually not bad but needs more options and extension to smartlists.

made from comments in #1844

**Comment by lachlan-00** [comment]
Add option to export http urls instead of local file path

**Comment by barcoboy** [comment]
I'd love to see this support smart playlists as well.  Would like to use it to generate a playlist to use with Ices, so that I could use rules to exclude parts of my catalog, such as for examples songs with the Genre "Comedy".

**Comment by lachlan-00** [comment]
I am looking at fixing up the ices implementation recently but haven't got to it.

You use ices from a playlist file? I was looking at using a script to download a random file from a search

**Comment by barcoboy** [comment]
I was going to do that, but then read about scripting.  Problem was I found out that because I am using an Icecast 1 server, I had to use Ices 0.4 with it, and that doesn't support scripting.  I then found Ezstream which does support both Icecast 1 and scripting, and by modifying the example in the Wiki slightly, I have it working with my democratic playlist.

**Comment by barcoboy** [comment]
And speaking of democratic playlists, it would be awesome to be able to use a smart playlist there as a Base Playlist.  :-)

**Comment by lachlan-00** [comment]
Ezstream is what I used to use. That would reload the playlists on change which was awesome.

It does seem stupid that we can't use a search when it's picking a song each load. We should add that

**Comment by lachlan-00** [comment]
I need to add playlist export to the API and allow URLs, filenames and relative paths (eg server file but replace the library part with a share or local source)

I used to do it with ezstream from SQL and bash

**Comment by skeagy** [comment]
Sorry if I’m necro-posting… I use Ampache for listening and playlist creation… really want to export smart playlists so I can use them on my Sonos player. Can save a smart playlist to regular playlist and export, but not export directly. Here’s my +1 to bump this up priority list, and I can help testing if necessary.

**Comment by lachlan-00** [comment]
This is added now in develop
php bin/cli export:playlist ~/playlists/ smartlists

**Comment by lachlan-00** [comment]
You can now also export web urls instead of files as well as smart lists. to get decent search results you need your search user to be your id as well.

this will all be documented but a basic command get export smartlists for user 2 and use web links is:

```
php bin/cli export:playlist ~/playlists/ smartlists --user 2 --web
```
