### ISSUE TITLE
Do not separate multiple discs in albums when browsing by ID3 tags using Subsonic API

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#1969]
Just created a new issue so this doesn't get forgotten.

**Comment by lachlan-00** [comment]
Can you show me what your album is tagged as?

The group section of the query is:
```
GROUP BY `album`.`name`, `album`.`album_artist`,`album`.`mbid`
``
so each disk needs to have those to be grouped. (mbid can be null)
```
SELECT * FROM `album` WHERE `name` = 'Station to Station'
```

**Comment by lachlan-00** [comment]
There are also changes in progress (#1964) to assign disk number correctly for all albums so this should help clients like avsub where disks are being reported as 0.

I just need to make sure when it updates it doesn't recreate each album.

**Comment by apastuszak** [comment]
If you want, I can share the actual music files with you.

**Comment by lachlan-00** [comment]
Just the details page like this is fine or the query results from above.
![image](https://user-images.githubusercontent.com/1305249/60855941-db2cc480-a248-11e9-9c97-f56a23d4c252.png)

**Comment by apastuszak** [comment]
I just check Ampache and it was using a beets catalog.  I just deleted it and added a local catalog.  I'll post results once it's done scanning.  I'm going to guess there's a good change we will be able to close this one.

**Comment by apastuszak** [comment]
Ok. still happening even with a local library.  Can't edit an album untli the whole scan is complete, so I this is going to have to wait at least an hour, possibly till the morning EDT.

**Comment by apastuszak** [comment]
Station to Station has 5 discs to it.
![disc 5](https://user-images.githubusercontent.com/3401054/62002284-2d863600-b0cf-11e9-9d88-29db24e383cf.png)
![disc 1](https://user-images.githubusercontent.com/3401054/62002285-2d863600-b0cf-11e9-8edf-fa74cf422baa.png)
![disc 2](https://user-images.githubusercontent.com/3401054/62002286-2d863600-b0cf-11e9-987e-c38dc9fa9927.png)
![disc 3](https://user-images.githubusercontent.com/3401054/62002287-2d863600-b0cf-11e9-972d-38b3142a02ac.png)
![disc 4](https://user-images.githubusercontent.com/3401054/62002288-2d863600-b0cf-11e9-85b5-201eb092afca.png)

**Comment by lachlan-00** [comment]
With these looking exactly the same, the only issue would be with the ampache subsonic api.
Just double check the station to station query as well from above.
```
SELECT * FROM `album` WHERE `name` = 'Station to Station'
```

I think what i'll do is make getArtists, getArtist and getAlbum use getMusicDirectory. Ampache is sort of reversed in that it uses id3 data and not folders at all.

This change will go into the open pull for subsonic 1.13 https://github.com/ampache/ampache/pull/1965

**Comment by lachlan-00** [comment]
*Just a reminder for myself
In testing these will output the same thing but don't do it the same way.
```
getartist (BAD)
Subsonic_XML_Data::addArtist
$artist->get_albums(null, true);
self::addAlbum($xartist, $album);

getmusicdirectory (GOOD)
Subsonic_XML_Data::addArtistDirectory
$artist->get_albums();
self::addAlbum($xdir, $album, false, false, "child");
```

**Comment by lachlan-00** [comment]
This is the answer. subsonic api code was ignoring the groupings no matter what is set.

This should sort you out.
![image](https://user-images.githubusercontent.com/1305249/62443101-57112280-b79d-11e9-82b5-0ae96305cf81.png)

**Comment by lachlan-00** [comment]
Last thing to fix is id3 search only shows the last disk. That's easy enough to fix.

**Comment by lachlan-00** [comment]
Final fix in the subsonic pull.

I get the same response whether id3 is enabled or not now.
![image](https://user-images.githubusercontent.com/1305249/62619169-75bc1880-b959-11e9-93d7-61712db1a21d.png)

**Comment by apastuszak** [comment]
Patiently waiting for this to be merged into develop.

**Comment by lachlan-00** [comment]
haha, have to have a lol at that.

It's next on my list now that it's done. the objects just need their extra attributes to be fully 1.13 compliant.

**Comment by apastuszak** [comment]
You sir, are a miracle worker.  Thank you for bringing this project back to
life.

**Comment by lachlan-00** [comment]
@apastuszak #1965 will be merging this weekend.
all the mandatory attributes are in as well as the methods for 1.13 so i just need to test against dsub and ultrasonic and fix any remaining disk issues.

**Comment by apastuszak** [comment]
If you have a server you want me to test iOS apps against, let me know.

**Comment by lachlan-00** [comment]
I'l take you up on that when i finish.

**Comment by lachlan-00** [comment]
@apastuszak i have my server ready for you. if you paste an email here i'll send you details and delete the comment.

**Comment by apastuszak** [comment]
apastuszak@gmail.com
