### ISSUE TITLE
catalog_update Doesn't Do Anything - Small Fix

### ISSUE THREAD

**Issue by e-tsik** [ampache/ampache#1970]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop (git from today)
* Web server + version: Apache 2.4, PHP 7.0
* Server operating system: CentOS 7
* Client operating system: CentOS 7

## Settings

Well, not really relevant

## Description

I had an issue where catalog_update.inc didn't quite do anything. After a quick investigation I found out that the the value for $catname is initialized with '' whereas further on it is compared against false to check whether to update all catalogs.

This line fixes it
sed -i "s|$catname = '';|$catname = false;|g" catalog_update.inc

## Logs

----------------------------------------------------------
Starting catalog operations...
	- Doing all catalog operations
----------------------------------------------------------

- Gathering art - 
- Optimizing database tables - 
------------------
\n
(and then exists)

**Comment by lachlan-00** [comment]
Cool, this will go in tomorrow when I can test it out. I did a lot of code changes to follow docstrings and some have been missed.

Diff to remind me
```
diff --git a/bin/catalog_update.inc b/bin/catalog_update.inc
index a2be4f92e..f629cb80a 100644
--- a/bin/catalog_update.inc
+++ b/bin/catalog_update.inc
@@ -36,8 +36,8 @@ $catadd = 0;
 $artadd = 0;
 $plimp = 0;
 $optimizetables = 0;
-$cattype = '';
-$catname = '';
+$cattype = false;
+$catname = false;
 $options = getopt("hn:t:mvcagio");

 if (count($options) == 0) {
```
