### ISSUE TITLE
XML-API: flag action seems that it does not work.

### ISSUE THREAD

**Issue by matiasdelellis** [ampache/ampache#1971]
## Environment

* Ampache version: 4.0.0-develop (Commit: https://github.com/ampache/ampache/commit/7246ddc6da29920baedc69bca065bc35ebb06968 )
* Web server + version: Ngnix
* Server operating system: Debian
* Client operating system: Fedora 31

## Client type:
  * @pragha-music-player over XML-API

## Description

Some time ago I implemented the reproduction of Ampache music on Pragha
Now with the latest API additions, I'm trying to handle the favorites.

API:
 * https://github.com/ampache/ampache/wiki/XML-methods#flag

Call on Pragha:
 * https://host/server/xml.server.php?action=flag&type=song&id=100003&flag=1&auth=TOKEN

Api response:
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<success />
</root>
````
Result:
 * I open the browser, I enter ampache, and I do not see the favorite anywhere. I can add or remove many songs, but I never see it in the browser. :disappointed: 

## Logs

I do not have access to the server to do internal tests.. Please @ftoledo. You can test and append it here?

Thanks.

**Comment by matiasdelellis** [comment]
p.s: I try to get the user's favorites ..

API: stats

Description: (https://github.com/ampache/ampache/wiki/XML-API)
> stats
> 
>    type (Type of album stats to retrieve [newest|highest|frequent|recent|flagged|random])
>    username (Username filter, only if type is recent for now. Optional)

Example: 
 * https://HOSTS/server/xml.server.php?action=stats&type=song&filter=flagged&auth=TOKEN
 * https://HOSTS/server/xml.server.php?action=stats&type=song&filter=flagged&username=matias&auth=TOKEN

Description
 * I I do not pass the username (Which says it is not implemented), The api returns the favorites of all users, and there is no way to filter your own. If it is not 'implemented', it can be a valid answer, but please ... can it be implemented ???? :smile: 
 * As it is an optional parameter, I add it with the hope of fixing it later, but server response the favorite albums of all the users. which is wrong since i query for songs. :disappointed:

**Comment by lachlan-00** [comment]
It flags for me in the website. if you can't get it immediately over the api maybe it's cached?
```
https://ampache.org/server/xml.server.php?action=flag&auth=AUTH&version=350001&type=song&id=94761&flag=1
```

for stats it's not passing the user but the Userflag::get_latest method supports it so lets add it!

**Comment by ftoledo** [comment]
hi @lachlan-00 i m debugging this issue and found that the user_id are empty in the set_flag() function and the database is filled with 0:
So, the Core:get_global() are fail.

Also, the auth token was no verified and the database still update, having a security risk.

```
mysql> select * from user_flag where user=0;
+----+------+-----------+-------------+------------+
| id | user | object_id | object_type | date       |
+----+------+-----------+-------------+------------+
| 24 |    0 |     14832 | song        | 1562900058 |
| 21 |    0 |     15711 | song        | 1562898145 |
| 23 |    0 |     15743 | song        | 1562898467 |
| 55 |    0 |    100003 | song        | 1563200576 |
| 38 |    0 |    107802 | song        | 1562935047 |
+----+------+-----------+-------------+------------+

```

```
    /**                                                                                                                                                                                                         
     * set_flag                                                                                                                                                                                                 
     * This function sets the user flag for the current object.                                                                                                                                                 
     * If no user_id is passed in, we use the currently logged in user.                                                                                                                                         
     */                                                                                                                                                                                                         
    public function set_flag($flagged, $user_id = null)                                                                                                                                                         
    {                                                                                                                                                                                                           
        if ($user_id === null) {                                                                                                                                                                                
            $user_id = Core::get_global('user')->id;  <<<<------                                                                                                                                                          
        }                                                                                                                                                                                                       
        $user_id = (int) ($user_id);                                                                                                                                                                            
        $results = array();                                                                                                                                                                                     
        if ($this->type == 'album' && AmpConfig::get('album_group')) {                                                                                                                                          
            $sql = "SELECT `album`.`name`, `album`.`album_artist`, `album`.`mbid` FROM `album`" .                                                                                                               
                    " WHERE `id` = ?";                                                                                                                                                                          
            $db_results = Dba::read($sql, array($this->id));                                                                                                                                                    
            $results    = Dba::fetch_assoc($db_results);                                                                                                                                                        
        }                                                                                                                                                                                                       
        if (!empty($results)) {                                                                                                                                                                                 
            return self::set_flag_for_group($flagged, $results, $user_id);                                                                                                                                      
        }                                                                                                                                                                                                       
        debug_event('userflag.class', "Setting userflag for $this->type $this->id to $flagged", 4);    
```

**Comment by ftoledo** [comment]
I notice tha the recent list show "Ampache User" as user, maybe this can be related to this issue? The user that was played these songs was @matiasdelellis via the xml api.

![Captura de pantalla_2019-07-16_21-06-06](https://user-images.githubusercontent.com/95441/61337954-cbdfe500-a80d-11e9-985e-566e7ac4bb48.png)

**Comment by lachlan-00** [comment]
Cool, thank you for all the investigating. I'm going to fix these recent bugs up tonight and extend the stats method to allow flagged by user as well.

It must be another bug that 0 equates to any user when highlighting in the UI so i'll have to check that out as well.

**Comment by lachlan-00** [comment]
i've just tested again and i'm getting my user in the database.

I'm going to add more checks and pass the user from the api section instead if possible.

**Comment by lachlan-00** [comment]
I can't recreate your empty errors in the api from the site/firefox but i've added some extra steps in #1978 to hopefully bypass that.

Please test if you can and let me know.

**Comment by lachlan-00** [comment]
this should be fixed now in develop. have a look and let me know!
