### ISSUE TITLE
Feature request: Edit ampache.cfg.php from the browser

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1972]
# Description

Just a thought, it would be neat to be able to change the Ampache configuration file from within the Ampache interface. I can't see any existing issues where this has been brought up before, so I wanted to see if anyone else had thoughts about it, or if maybe there is some reason this isn't a good idea.

**Comment by ftoledo** [comment]
I think it is better that all options can be modified from the web, but while it is not possible, it is a good idea that the file can be edited. This can be useful for people who do not have fast access (via ssh for example) to edit it.

**Comment by kuzi-moto** [comment]
Agreed. Also, I was just thinking, why were there ever two config areas to begin with? Why don't we just have all of the configuration options merged with the "Server Config" section?

**Comment by lachlan-00** [comment]
For me there are 2 areas and they are separated for a reason.
* The config file is used for server wide configuration, cli, installation options, session options and static values that don't change regularly.
* The database preferences are for user settings and preferences that affect ui, player, streaming and config of those options for each user.

I think that the config file options should stay separated from the web interface and if needed individual  options move into the interface if they are better suited to the interface..

**Comment by kuzi-moto** [comment]
Okay, that does make sense to keep the two areas separate then. Though I do think it would be neat to be able to change the file values from the interface. I was just bringing it up to see if there were any reasons to keep it the same!
