### ISSUE TITLE
XML-Api auth not validated as expected

### ISSUE THREAD

**Issue by nicklan** [ampache/ampache#1979]
# Issue Template

## Environment

* Ampache version: 3.9.0-release
* Web server + version: nginx
* Server operating system: Linux
* Client operating system: Linux

* Client type:
  * Ampache XML Api via cUrl

## Settings

relevant settings
```php
session_length = 3600
stream_length = 7200
remember_length = 604800
session_name = ampache
session_cookielife = 0
session_cookiesecure = 0
auth_methods = "mysql"
access_control  = "true"
require_session = "true"
require_localnet_session = "true"

```

## Description

I can do:
`curl -v "https://[server]/server/xml.server.php?action=songs&offset=0"`

from anywhere and it works without any auth

## Notes
So this https://github.com/ampache/ampache/blob/master/server/xml.server.php#L51 calls this https://github.com/ampache/ampache/blob/master/lib/class/session.class.php#L306  which will always be true, so the api always just goes into `Access::check_network`

That function here https://github.com/ampache/ampache/blob/develop/lib/class/access.class.php#L373 appears to always allow access if the IP is in an allowed range and if no auth is passed, if the `user` column is `-1`. 

By default all the ACLs set "user" to "All", but what I would expect that to mean is not "anyone at all can use these things", but rather, all VALID users can use these things.  I think the logic should be refactored to at least require a valid user to be specified.  The docs should also be updated to reflect this non-intuitive, and frankly highly insecure behavior.

**Comment by nicklan** [comment]
Ohh man, this is not easy to work-around either.  It seems the "auth" field is just super broken for the xml api here, because after a successful handshake, if you then use the returned `token` and have set up an ACL for a user for api access, it will always fail, but the code just tries to use that `auth` field as an `apikey` selector on the user database, which is just wrong. so it appears to currently be impossible to have proper access control on the xml api and actually have things work.

**Comment by nicklan** [comment]
Also to be documented.  If you want to create an ACL to allow only a certain user, they need to have a generated API key.  I think the interface, or docs, should mention that.  Also, the handshake method should fail if the user doesn't have an api-key, rather than returning something that will not work for any subsequent calls.

**Comment by matiasdelellis** [comment]
Although not the original report, it seems similar to that found in:
 * https://github.com/ampache/ampache/issues/1971#issuecomment-511425975

The same security bug on 'flag' api..

**Comment by lachlan-00** [comment]
flag is just copied from rating so there's probably a lot more to check

**Comment by nicklan** [comment]
Yeah, I think the fact that there's inconsistent meanings giving to the `auth` token all through the code is causing both security issues and breaking stuff.

**Comment by lachlan-00** [comment]
Thank you for taking the time to check this is depth. it's been really good that everyone is becoming a lot more active here!

It looks like we need to bring it back to the auth/session level before we let the client into the api.

When you handshake it seems to just create an api key value anyway so it probably needs to be looked at from the top down.

**Comment by lachlan-00** [comment]
It looks like the 400001 api should make an effort to correct all these issues and work towards securing auth.

I've been debating in my head how auth should change. maybe move to a token auth like subsonic? it's not a great system to send your actual API key over the internet.

**Comment by lachlan-00** [comment]
First steps:
* Session::create needs to create a session for api users.
* Session::exists needs to actually look for an api session instead of allowing all access.
* I think we should look at requiring a handshake to create api sessions instead of just letting them through.
* The handshake needs to generate an individual token that is a salted hash of the apikey and is verifiable.

**Comment by lachlan-00** [comment]
I've been working in the api branch (#1982) and have enforced session checks as well as generated unique handshake values for auth.

Now i want to extend the api a bit more to provide a few more functions but it's looking pretty complete now.

A final part will also be allowing a secure hash for handshakes so you don't have to send your api key out to the internet.

**Comment by lachlan-00** [comment]
Auth requirements have merged into develop.

Have a look around in this revision and let me know if anything else is missing.

**Comment by lachlan-00** [comment]
Closing as auth is always required for the api in develop and will return session expired when trying to bypass.
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<error code="401"><![CDATA[Session Expired]]></error>
</root>
```
