### ISSUE TITLE
Ampache Enhancement Requests

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#1986]
Open enhancement requests make up a large portion of the open issues here so they will be consolidated into this issue and the wiki.

[https://github.com/ampache/ampache/wiki/Enhancement-Requests](Enhancement Requests)

NEW FEATURES

* Add an audiobook catalog https://github.com/ampache/ampache/issues/1996
* Update bin/write_playlists.inc to include smartlists and more options #1967

**Comment by kuzi-moto** [comment]
I think the link syntax is backwards

**Comment by lachlan-00** [comment]
REFER TO
https://github.com/ampache/ampache/projects/3
