### ISSUE TITLE
Registration allowed/no error messages when creating a new account and email is disabled

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1989]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Client type: Any

## Settings

```INI
allow_public_registration = "true"
;mail_enable = "false"
```

## Description

The issue here is that when enabling user registration, but not configuring the email settings, then someone can still register for an account. On registering they get a message stating they will receive an email with an activation code, but will not get it. Nor will the administrator see an error in the logs stating that someone tried to register an account.

It may be a good idea to instead show an error on the registration page, preventing someone from creating an account, show an error after creating an account, or at least mention that in the log file.

**Comment by lachlan-00** [comment]
i'll put some error checking for these into your pull for the other registration issues
