### ISSUE TITLE
Democratic keep last vote timestamp (for ordering)

### ISSUE THREAD

**Issue by GieltjE** [ampache/ampache#199]
When voting for a song the song should be placed on the bottom of the song section with the same ammount of votes.

So if it is the 4th song with 3 votes and it gets a 4th vote it should be put on the bottom of the list of songs with 4 votes.

This ensures a more "democratic" order, currently the visual list on the site appears to behave this way but the m3u sometimes differs from the displayed order.

**Comment by Afterster** [comment]
Major changes was done since this post, is this still valid on your side @GieltjE?

**Comment by GieltjE** [comment]
I will check it later this week,

**Comment by GieltjE** [comment]
For now the bugs seem to have been fixed, I'll report back when more field testing has been performed and something breaks.
