### ISSUE TITLE
Registration confirmation page says user will get activation code even if not required

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1990]
# Issue Template

## Environment

* Ampache version: 4.0.0-develop
* Client type: Any

## Settings

```INI
allow_public_registration = "true"
user_no_email_confirm = "true"
```

## Description

There are no checks in the confirmation page if `user_no_email_confirm` is set, so the message states the user will get an activation key, even though they can login after this point.

Another easy one, I can do this too.

**Comment by lachlan-00** [comment]
You're assigned!

If you want to put all these three into one pull we can merge together.

**Comment by kuzi-moto** [comment]
Nice, sounds good! I probably could have made one issue, but wasn't planning on running into so many bugs.

**Comment by lachlan-00** [comment]
It's good to keep them separate as they are sort of different and the same so we'll need to make sure they all work as intended.

One thing i've found is that fixing bugs in ampache generally leads to new ones!
