### ISSUE TITLE
 Error  Unable to load required dependencies. Please visit the wiki for installation help

### ISSUE THREAD

**Issue by andri000me** [ampache/ampache#1993]
Fatal error: Uncaught exception 'Exception' with message 'load_gettext()' in E:\xampp 3.2.1\htdocs\Musik\ampache-develop\test.php:62 Stack trace: #0 {main} thrown in E:\xampp 3.2.1\htdocs\Musik\ampache-develop\test.php on line 62

Solution?

**Comment by kuzi-moto** [comment]
Did you follow the steps to install and run [Composer](https://github.com/ampache/ampache/wiki/Installation#composer)?

**Comment by andri000me** [comment]
i using xampp server php 5.6.8

**Comment by kuzi-moto** [comment]
Did you run through the installation instructions in the wiki? I have specific steps to install composer in my windows intall guide [here](https://github.com/ampache/ampache/wiki/Windows-Installation-Guide#composer). That should fix your dependency issues.

**Comment by lachlan-00** [comment]
This error page is meant to direct you to the wiki, please follow the guides and get composer dependencies installed
