### ISSUE TITLE
Feature Request: Change viewport to device-width

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2007]
## Description

I was thinking about a mobile interface for Ampache, and on looking into it, found that header.in.php has `<meta name="viewport" content="width=1024, initial-scale=1.0">`. To support mobile layouts, I think it needs to be changed to `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. I think there will most like need to be a change or two to reborn, because probably screens less than 1024 will look strange.

Just wanted a second option before screwing around with it.

**Comment by lachlan-00** [comment]
you'll probably find that the ui has a minimum width that doesn't play too well with device-width.
Most of the css is still pixel based  so widths&heights are pretty static.

I went to 1024 as it fits most of the pages without being weird

**Comment by kuzi-moto** [comment]
Yeah, I run into that. I was thinking that perhaps there were other CSS values that can be set to preserve the appearance of reborn, but then allow other themes to create more responsive interfaces more easily. Or at least some way for a theme to orrveride the viewport to device-width?

**Comment by kuzi-moto** [comment]
I think setting body to `min-width: 1024px;` should solve any issues after changing viewport.

**Comment by lachlan-00** [comment]
feel free to play around with things. @mattish91 seems to know a lot of this front so maybe you'd have some input?

**Comment by kuzi-moto** [comment]
I have something working. Basically just need to add a class to the body in header.inc.php, so that I can set it to a min width of 1280, and not affect login/registration pages, etc. This way reborn will not change and it makes it easier for other themes to be responsive.

I'll submit a pull request tomorrow probably.
