### ISSUE TITLE
Subsonic "Stream" api returns full track

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2008]
hi guys,
i am running on the latest 4.0.0 build, and i did have this same issue a couple of years back where when i use the "stream.view" api call instead of returning the m3u file, it return the full sized mp3 file
any idaes on how to solve this, i remember it used to be a common issue with a simple fix

**Comment by lachlan-00** [comment]
According to the subsonic API site stream returns binary data on success.

Depending on your settings this will be transcoded into chunks or the full file.

**Comment by a7medo778** [comment]
thanks for the reply @lachlan-00 
as per of my understanding and prior experience, the diffrance between "download" and "stream" is that one sends the full file, while the other sends it in chunks, meaning the original file you download isnt full-sized
i just tested the same api call on my madsonic install and it is indeed a much much smaller m3u file

but just to be safe, what settings are you referring to ?

**Comment by lachlan-00** [comment]
For Ampache it will chunk based on the transcoding settings.

So download is the original file and stream is the play url transcoded based on the settings for that file type.

**Comment by a7medo778** [comment]
Exactly, so the stream file should not be 11mb in size, it should just contain the stream url

**Comment by lachlan-00** [comment]
You'll get the full binary file either way it does it.

I'll have a look at the code after I get the tag updates in but to a subsonic client it will expect the binary MP3/etc and Ampache will send it in one piece or multiple.

There should never be an m3u returned from the stream method.
http://www.subsonic.org/pages/api.jsp#stream

**Comment by lachlan-00** [comment]
I'm closing this one. I think the API is acting correctly
