### ISSUE TITLE
TV/Video Naming Pattern does not match Template

### ISSUE THREAD

**Issue by BlueNalgene** [ampache/ampache#2009]
## Environment

* Ampache version: 3.9.0-release
* Web server + version: apache2 up to date
* Server operating system: Ubuntu
* Client operating system: Win10

* Client type:
  * Web
  * Ampache

## Settings

N/A I think

## Description

The auto filename parsing for TV/Movies appears to be inaccurate.  For example, the following path: ``/media/storage1/Moving_Images/TV/30_Rock/Season_01/01-Pilot.mp4`` should toss info to correct tags using the Kodi scheme described [here](https://github.com/ampache/ampache/wiki/TV-Shows-and-Movies), namely the template ``/Top Folder/show name [year]/[season ]##/##[-episode-Title].ext``, yet this is not the case.  The following tags are created
- title="01-Pilot"
- show=""
- season=""

This means the show does not appear in the "TV Shows" section.  The only way I can reach the file appears to be when it shows up on the random feed of video files on the index page.

Have I done something wrong here?  Is there a more correct way to name the files which would avoid this issue?

## Logs

n/a

**Comment by kuzi-moto** [comment]
I'm not sure why it's not using the correct folder structure, but I think you can manually edit the tags in Ampache. Otherwise, re-tag your video files directly, that way Ampache will get all the correct data from the files themselves.

**Comment by BlueNalgene** [comment]
@kuzi-moto 

Your suggestions led me to the actual answer.  The ampache dialog when adding a new catalog should be updated to reflect this information for video files.  The pattern matching from Kodi can be used from [here](https://kodi.wiki/view/Video_file_tagging#MP4_tag_options)

-B | -podcast | pcst | NUM | Set the podcast flag
-- | -- | -- | -- | --
-c | -comment | ©cmt | STR | Set a general comment
-C | -copyright | cprt | STR | Set the copyright information
-e | -encodedby | ? | STR | Set the name of the person or company who encoded the file
-E | -tool | ? | STR | Set the software used for encoding
-g | -genre | gnre / ©gen | STR | Set the genre name
-G | -grouping | ©grp | STR | Set the grouping name
-H | -hdvideo | hdvd | NUM | Set the HD flag (1/0)
-i | -type | stik | STR | Set the Media Type (tvshow, movie, music, ...)
-I | -contentid | cnID? | NUM | Set the content ID
-j | -genreid | ©gen / gnre? | NUM | Set the genre ID
-l | -longdesc | desc? | STR | Set the long description
-m | -description | desc? | STR | Set the short description
-M | -episode | tves | NUM | Set the episode number
-n | -season | tvsn | NUM | Set the season number
-N | -network | tvnn | STR | Set the TV network
-o | -episodeid | tven | STR | Set the TV episode ID
-O | -category | ©grp? | STR | Set the category
-p | -playlistid | ? | NUM | Set the playlist ID
-P | -picture |   | PTH | Set the picture as a .png, Cover
-S | -show | tvsh | STR | Set the TV show
-X | -rating | rtng | STR | Set the Rating (none, clean, explicit)
-y | -year | ©day | NUM | Set the release date


These can be modified with the percent sign ``%`` in place of the dash ``-``.  So for my example, I can use the following tagging pattern:

Filename pattern: ``%M-%t``
Folder pattern: ``%S/Season_%n``

Suggestion to package maintainers: just toss this into the dialog echo box and add this to the git wiki.

**Comment by lachlan-00** [comment]
hey @BlueNalgene do you want to write up a blurb/page for the wiki? i can put it as a link inside the code when people are editing catalogues so they know there's more information specifically for videos.

**Comment by BlueNalgene** [comment]
I updated the wiki with a more concise and readable version of the text above.  Closing this Issue thread.

**Comment by lachlan-00** [comment]
@BlueNalgene thanks for that. i'll make a reference in the strings update branch now. #1957
