### ISSUE TITLE
An option for a constant replay gain :-)

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#201]
Hey,
it would be nice if you put that to the roadmap^^
By stumbling randomly through the Media library, the songs where at different volumes. It's not really cool if you hear some silent song and in the next moment your speakers try to paint your wall, behind you, in red, with your brain :-))

If I've read the right things, ffmpeg and/or avconv seem to support that on nearly every audio file type... 
According to this, I think that option should also affect that files who are not being transcoded, because Ampache only transcodes that files who are forced and that files who have a higher bit rate than adjusted, isn't it?
I think in most cases that would be mp3's ? And mp3's support the gain change without transcoding. But I don't know if it's possible with ffmpeg or avconv ... but I know that mp3gain can do that job.

Or maybe it's the best alternative to let the Webplayer do that work? I don't know if it is possible...

Hope you enjoy that idea^^

**Comment by Afterster** [comment]
Ok thanks for your explanation. To be honest I never used ReplayGain even if its around since decades, so the algorithm was new to me.
I adapted gain calculation based on http://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification.
Could you take a look on latest commit and tell me if this is ok now? If so you can close the thread, otherwise just comment. Thanks for your patience ;)

**Comment by Psy-Virus** [comment]
All right, thanks for your work!
I'll test it in the next days and let you know, if all's fine :-)

**Comment by Afterster** [comment]
How was your tests @Psy-Virus?

**Comment by Psy-Virus** [comment]
All in all, I'd say that it's working great.

**Comment by Psy-Virus** [comment]
All in all, I'd say, it's working great. I only still have the issue of lagging playback (only with enabled RG) while I navigate through the site. But only on Firefox. On IE it works well.

And I don't think that my browser is lagging, because if I open two tabs within the same window and have a running playback on one tab and navigate on the other, it's not lagging.

It's also not a long lag, maybe 100-200 ms...

**Comment by Afterster** [comment]
Ok great, I'm happy to close this issue after several months. Thanks for your great discussion!

About the lag, this seems to be a firefox issue indeed. There is several issues in Firefox with Audio API and it could be part of it ; I don't believe it's coming from Ampache code right now.

**Comment by Psy-Virus** [comment]
All right, and thank you for your patience and work!
It's an awesome feature. :-)
