### ISSUE TITLE
Catalog disable doesn't do anything, enable does

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2015]
# Issue Template

## Environment

* Ampache version: 4.0.0 develop eb7bb58f33478ad3cb3b9258eddf4a0211a25f54
* Web server + version:  Apache/2.4.38 (Debian)
* Server operating system: Debian GNU/Linux bullseye
* Client operating system: Debian GNU/Linux bullseye

* Client type:
  * Web Firefox

## Settings

; Catalog disable
; This defines if catalog can be disabled without removing database entries
; WARNING: this increase sensibly sql requests and slow down Ampache a lot
; DEFAULT: false
catalog_disable = "true"

## Description

This is another old unreported issue.  When I have catalog_disable set to true. In the show catalogs page, clicking on the disable button for a specific catalog switches the button to green but when I leave and go back to the page, the catalog isn't disabled seems the database isn't updated.  I've been able to manually change the catalog to disabled through phpmyadmin.  But I can enable the catalog from the Ampache UI and the database is updated.
![image](https://user-images.githubusercontent.com/4076671/63135552-5dbd4800-bf9c-11e9-8b95-24575a2c9b8e.png)

## Logs

Not much is logged.

2019-08-15 20:24:14 [stebe] (session.class) -> bqck3hrl37acjvic04r50l7rib has been extended to Fri, 16 Aug 2019 20:24:14 -0400 extension length 86400 
2019-08-15 20:24:14 [stebe] (ajax.server) -> Called for page: {catalog}

**Comment by lachlan-00** [comment]
i've found the issue for this. will ping it in the newest pull as well.
