### ISSUE TITLE
Update PHP-CS-Fixer

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2017]
# Description

I would like to propose updating PHP-CS-Fixer to the latest release, `2.15.1`. The current version within Ampache is `2.12.8 Long Journey`.

The primary reason I'd like to update, is because of a fix first applied in `2.12.9`: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4339. This fix stops putting the PHP closing tag on a new line, after an opening brace. Here is an example:

Before:

```PHP

                <?php if (Mailer::is_mail_enabled()) {
    ?>
                    <div class="loginoptions">
                        <?php if (AmpConfig::get('allow_public_registration')) {
        ?>
                            <a rel="nohtml" class="button" id="registerbutton" href="<?php echo AmpConfig::get('web_path'); ?>/register.php"><?php echo T_('Register'); ?></a>
                        <?php
    } // end if allow_public_registration
                        ?>
                        <a rel=\"nohtml\" class=\"button\" id=\"lostpasswordbutton\" href=\"" . $web_path . "/lostpassword.php\">Lost password</a>
                    </div>
                <?php
} ?>
```

After:

```PHP
                <?php if (Mailer::is_mail_enabled()) { ?>
                    <div class="loginoptions">
                        <?php if (AmpConfig::get('allow_public_registration')) { ?>
                            <a rel="nohtml" class="button" id="registerbutton" href="<?php echo AmpConfig::get('web_path'); ?>/register.php"><?php echo T_('Register'); ?></a>
                        <?php } // end if allow_public_registration
                        ?>
                        <a rel=\"nohtml\" class=\"button\" id=\"lostpasswordbutton\" href=\"" . $web_path . "/lostpassword.php\">Lost password</a>
                    </div>
                <?php } ?>
```

I think this reduces unnecessary white-space and makes code a bit more readable. It doesn't change all the files, but if changed manually than it will stay. I probably wouldn't mind as much if it at least did the right indentation...

**Comment by lachlan-00** [comment]
Updated the binary file and composer json file but doesn't seem to catch this rule.

is there a specific rule this is checking against?

**Comment by lachlan-00** [comment]
this is the .php-cs my server has generated
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('master')
    ->exclude('develop')
    ->exclude('core')
    ->exclude('lib/components')
    ->exclude('lib/vendor')
    ->exclude('modules')
    ->exclude('modules/captcha')
    ->exclude('modules/oauth')
    ->exclude('nbproject')
    ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
    ->in(__DIR__)
    ->in(__DIR__ . '/modules/localplay')
    ->in(__DIR__ . '/modules/catalog')
    ->in(__DIR__ . '/modules/plugins')
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'strict_param' => false,
        'no_trailing_whitespace' => true,
        'blank_line_before_return' => true,
        'full_opening_tag' => true,
        'braces' => ['allow_single_line_closure' => true],
        'single_blank_line_at_eof' => true,
        'visibility_required' => true,
        'binary_operator_spaces' => ['align_equals' => true],
        'concat_space' => ['spacing' => 'one'],
        'elseif' => true,
        'blank_line_after_namespace' => true,
        'lowercase_constants' => true,
        'encoding' => true,
        'no_break_comment' => false,
        'method_argument_space' => false,
     ])
   ->setIndent("    ")
   ->setUsingCache(false)
   ->setFinder($finder)
;

```

**Comment by kuzi-moto** [comment]
It's a default rule. It also doesn't change any of the existing formatting, you still have to change it yourself it seems. But at least it won't change it back like the current version.

**Comment by kuzi-moto** [comment]
From the PR:

> the change will be in all releases and will be the new default behavior (it is not optional/configurable)

**Comment by lachlan-00** [comment]
ah so that means i would need to delete it and start again. i'll test that tomorrow

**Comment by lachlan-00** [comment]
The braces rule affects the curly braces {} and the rule we have for this allows single lines for braces but doesn't affect the closing/opening tags (at least for me) after updating the version to 2.15

https://github.com/ampache/ampache/blob/develop/.php_cs
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.15|fixer:braces

**Comment by lachlan-00** [comment]
while putting dropbox back in tonight i'll look at v2.15.3 as well.

**Comment by lachlan-00** [comment]
composer updated for the newer cs-fixer
