### ISSUE TITLE
smart playlists question

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2021]
hey guys,
1- does smart playlists auto-update itself ? or do i need to trigger something every once in a while?
2- can i retrieve the smart playlist via either the XML or subsonic api ?

**Comment by lachlan-00** [comment]
Every time you query a smart playlist it generates a new search. So you don't have to regenerate them, they change every time you request them.

In subsonic and API they are joined in with playlists.

In the API I have only let it add a smart list if an explicit limit is set.

In subsonic there is no limit but it will probably timeout when the list is bigger than 3000 items.

I'll add more details later today about how they are pulled by api's

**Comment by a7medo778** [comment]
as long as we can retrieve them using subsonic api, its all good, thanks

**Comment by lachlan-00** [comment]
XML
* playlists will list all playslist
* playlist_songs will list the songs for that id

Subsonic
* getPlaylists will get a list of playlists
* getPlaylist will get the single playlist details
