### ISSUE TITLE
group album shows only the first cd

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#2023]
# Issue Template

## Environment

* Ampache version: 4.0.0.2
* Web server + version: apache 2.7
* Server operating system: synology DSM 6.2
* Client operating system: windows 10

* Client type:
  * Web
  

## Description

group album shows only the first cd

![before_group](https://user-images.githubusercontent.com/25564572/63621147-74464d80-c5f3-11e9-9f16-479c6b6e580b.jpg)
![group_1](https://user-images.githubusercontent.com/25564572/63621149-74464d80-c5f3-11e9-8c70-2991083825f4.jpg)
![group_2](https://user-images.githubusercontent.com/25564572/63621150-74464d80-c5f3-11e9-8029-13ae78411cbd.jpg)

i would expect that all titles of the cds were shown. but maybe i misunderstood the functionality

**Comment by lachlan-00** [comment]
This is part of an incomong change with the open subsonic pull. The disk part is meant to be removed

**Comment by lachlan-00** [comment]
#1965 has this fixed and will merge soon. it's a visual error only as ampache used to ignore a lot of grouping settings and still include the disk number.

When you have grouping enabled it should only show 1 item with all the contents.

**Comment by noyse27** [comment]
ah ok :) will check after merge ;)

**Comment by lachlan-00** [comment]
check again and reopen with any issues but this is all in develop now.

API / UI and subsonic now all respect your album_group settings

**Comment by noyse27** [comment]
the behaviour isn't solved. After grouping still shows only the titles of the first cd

**Comment by lachlan-00** [comment]
This is the setup in current develop.

Grouping enabled
![image](https://user-images.githubusercontent.com/1305249/64614285-7db91d80-d41b-11e9-99bf-c3fa4b160bc8.png)

Grouping disabled
![image](https://user-images.githubusercontent.com/1305249/64614303-87db1c00-d41b-11e9-80dc-91a9d459e718.png)

Grouping will combine each disk into a single item. is that not what you're talking about here?

**Comment by noyse27** [comment]
hmm thats curious: this is what i get:
grouping enabled:
![15_44_55](https://user-images.githubusercontent.com/25564572/64619390-4b3efe80-d3e2-11e9-8f69-b6f0608c75c2.png)

grouping disabled
 
![15_48_53](https://user-images.githubusercontent.com/25564572/64619516-7fb2ba80-d3e2-11e9-9f58-82f4ec73827e.png)

whats new is that disc 1/2 isn't shown anymore.

**Comment by lachlan-00** [comment]
What's more odd is that the album count isn't showing up correctly either. The query to identify multi disks might need work.

Can you update from tags for these disks and then screen the album edit page?
![image](https://user-images.githubusercontent.com/1305249/64656233-298d5800-d472-11e9-9cac-052d4ef2d94d.png)

**Comment by lachlan-00** [comment]
Fixed now
Groups and counts work for many different variations. '[Disk x]' will also show up when needed correctly now.

Grouped with correct count
![image](https://user-images.githubusercontent.com/1305249/64756359-f92ce300-d571-11e9-9c89-801968639bc0.png)

Ungrouped with disk numbers and correct count.
![image](https://user-images.githubusercontent.com/1305249/64756386-19f53880-d572-11e9-9635-6c44da081afc.png)

I'm keeping this open in case you see anything else but i think it's covered now. please close when you're happy or raise any more issues here.

**Comment by lachlan-00** [comment]
We got there in the end. Lots of bug fixes this week. :)
