### ISSUE TITLE
Importing multiple m3u8 files doesn't create multiple playlists

### ISSUE THREAD

**Issue by zingmars** [ampache/ampache#2024]
## Environment

* Ampache version: commit bafda752fdc293d97a22c0e4c34b5b46ec3df98b
* Web server + version: Nginx 1.14.0
* Server operating system: Ubuntu 18.04
* Client operating system: Windows 10, Firefox 68.02
* Client type:
  * Web

## Description

When there are no playlists present and I import a playlist, it will show me the "success" dialogue and open the playlist as expected. When I try to import another playlist from a different file, I'll get the success dialogue, but it will open the playlist that I imported before. What's worse, it seems that all the songs in the 2nd m3u8 file were appended to it.

It's probably something stupid, but I can't seem to find the button that allows me to create new playlists and/or import m3u8 files to different playlists. I do remember being able to set them up before though.

## Logs

```
2019-08-24 19:16:03 [admin] (catalog.class) -> Add file (...) to playlist.
- (...) repeat for all files -
2019-08-24 19:16:03 [admin] (catalog.class) -> import_playlist Parsed /tmp/Server - 1.m3u8, found 793 songs
2019-08-24 19:16:03 [admin] (catalog.class) -> import_playlist playlist has 2902 songs
2019-08-24 19:16:03 [admin] (catalog.class) -> import_playlist filtered existing playlist, found 612 new songs
```

**Comment by lachlan-00** [comment]
playlists are the same name?

I put in a check for the server to see whether the name existed as it was importing new playlists each time.

**Comment by lachlan-00** [comment]
If you want to import new ones i think i'll need to add an option to disable that check. but the easiest path is to create unique filenames.

**Comment by zingmars** [comment]
The filenames are unique. When I import a new file it just adds the songs from it to the playlist created when the first file was imported. Oddly enough the "Success" screen shows the different names.

I sorta got around to this by uploading the playlist files to the media folder and using the catalogue script to import them which seems to have worked, but I couldn't figure out the UI at all.

**Comment by lachlan-00** [comment]
oh, now that's interesting. so it's in the ui when using the import.
```
playlist.php?action=show_import_playlist
```
Definitely a bug then!

**Comment by zingmars** [comment]
ffmpeg absolutely refuses to work with me this morning, so screenshots will have to do:

Importing the first file:
![image](https://user-images.githubusercontent.com/917126/63646541-5bd25200-c71d-11e9-83f3-297b3564b32d.png)

Leads to
![image](https://user-images.githubusercontent.com/917126/63646542-61c83300-c71d-11e9-8d72-240cef8c0231.png)

Which opens the playlist view like this:
![image](https://user-images.githubusercontent.com/917126/63646545-6ab90480-c71d-11e9-96e7-c33d49acfd3d.png)

Importing the second file
![image](https://user-images.githubusercontent.com/917126/63646550-76a4c680-c71d-11e9-9fda-6d606e6c5081.png)

Leads to
![image](https://user-images.githubusercontent.com/917126/63646552-7c021100-c71d-11e9-8978-ed8ef91d9acf.png)

Which opens the first playlist. Note that the item count has changed.
![image](https://user-images.githubusercontent.com/917126/63646554-82908880-c71d-11e9-93f0-c553da75c6a5.png)

**Comment by lachlan-00** [comment]
Thanks for these.

If i can get on my laptop tonight i'll push a fix

**Comment by lachlan-00** [comment]
i think this is catching the tracks in the existing playlist and then not actually checking the file names are different.

thanks for your report, fixing now

**Comment by lachlan-00** [comment]
SQL!
