### ISSUE TITLE
Access denied issue

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2025]
Hey guys
I know this is noobish, but I am submitting the app today, I  changed my web server from apache to nginx and having the following problem when trying to scan the catalog

https://ibb.co/9GQNc8J
And the webplayer isn't working as well (api powering the app is working perfectly) any ideas?

**Comment by lachlan-00** [comment]
got a working config? i don't use nginx but it seems like most issues are related to the config file for the site.
https://github.com/ampache/ampache/wiki/Installation
https://github.com/ampache/ampache/issues/1757#issuecomment-497569878

**Comment by lachlan-00** [comment]
@rodrigoesborges that's a separate issue to this. Make a new one and I'll look into it. A few large changes are merging soon

**Comment by a7medo778** [comment]
hey guys, just before closing the issue 
the issue was in the nginx config file as @lachlan-00 commended, had a double config file which was making the issue

thanks for the help
