### ISSUE TITLE
Update avatar doesn't show in account settings

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2030]
# Issue Template

## Environment

* Ampache version: 4.0 develop

* Client type:
  * Web

## Description

When I upload an avatar the what I assume is the avatar display box doesn't show anything. It seems to be highlighted when I go to the API key menu. Avatar shows fine in the currently playing screen and browse users screen.

![image](https://user-images.githubusercontent.com/4076671/63981853-a5f56380-ca8e-11e9-8838-5b78e250a759.png)
![image](https://user-images.githubusercontent.com/4076671/63981821-80685a00-ca8e-11e9-9a25-7ef82ba0d219.png)

**Comment by lachlan-00** [comment]
i actually forgot that was in there. i don't think i removed it but it may have been pulled in a find and replace.

**Comment by lachlan-00** [comment]
This is going into strings update (#1957) now.

there will also be an image check to notify when the image is not inserted instead of just pretending to pass

**Comment by lachlan-00** [comment]
You get an avatar with a delete button now
![image](https://user-images.githubusercontent.com/1305249/66169158-c8c4fa00-e682-11e9-8ce3-4d65e7a6db6e.png)

It might need a layout tweak to put browse above it because it's all on one row but it's there!

The image check will tell you when an avatar upload fails as well.

**Comment by stebe** [comment]
Doesn't work for me. 
![image](https://user-images.githubusercontent.com/4076671/66170348-ec039100-e611-11e9-9df6-0846b9a2d12b.png)

It shows up in browse Users: 
![image](https://user-images.githubusercontent.com/4076671/66170402-1b1a0280-e612-11e9-90a5-d7aa6ce585cc.png)

And when I open that user from browse users:
![image](https://user-images.githubusercontent.com/4076671/66170440-3be25800-e612-11e9-92a9-04286ab6280b.png)

**Comment by lachlan-00** [comment]
do you get it in your show_user page after clicking your username? it's the same image from there

![image](https://user-images.githubusercontent.com/1305249/66170648-5ce59000-e688-11e9-8a0a-7b221f56cbfb.png)

**Comment by lachlan-00** [comment]
oh sorry i just read the bottom part

**Comment by lachlan-00** [comment]
does it change if you add the $client->format() in this screen?

templates/show_edit_user.inc.php
![image](https://user-images.githubusercontent.com/1305249/66170825-29573580-e689-11e9-9994-5e9a94149c54.png)

**Comment by lachlan-00** [comment]
It should also have a generic avatar if it can't find yours
![image](https://user-images.githubusercontent.com/1305249/66170882-6a4f4a00-e689-11e9-9afc-87b4ee9d7905.png)

**Comment by stebe** [comment]
Adding that line didn't change the results. When I'm in the browse users screen and I click on the gear on my username that screen has my avatar.
![image](https://user-images.githubusercontent.com/4076671/66187613-24778f00-e653-11e9-818c-2f02d30cb4f1.png)

**Comment by lachlan-00** [comment]
I must have missed that template.

**Comment by lachlan-00** [comment]
that box is apparently a qr code for the api key

**Comment by lachlan-00** [comment]
got it. with a better display now too
![image](https://user-images.githubusercontent.com/1305249/66200240-f1311080-e6e3-11e9-935f-0ce520d4f27e.png)

**Comment by stebe** [comment]
Working now everywhere. 👍
