### ISSUE TITLE
getting disk # in album name

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2031]
hi guys,
i did a rescan to all my catalog, and now i am getting "disk 1" appended to all album names, and even in the api returned
<img width="385" alt="Screen Shot 2019-08-31 at 8 34 08 PM" src="https://user-images.githubusercontent.com/1003222/64067279-e5f34c80-cc2e-11e9-9df2-d09d1f2d831a.png">
the disk number isnt part of the name its just mentioned there in the album properties 
<img width="679" alt="Screen Shot 2019-08-31 at 8 34 28 PM" src="https://user-images.githubusercontent.com/1003222/64067285-fc99a380-cc2e-11e9-8e71-aa3b5f3329f1.png">
so it shouldnt appear in the name

how can i resolve this ?

**Comment by lachlan-00** [comment]
Grouping or no grouping? I think you must have no grouping. Pretty sure I know what the UI is doing.

Disk 1 was added and all the old checks were for numbers greater than 0.

The API shouldn't be returning a name with disk in it though. Send any calls you made with weird titles.

For the UI I know the answer and will stop that for single disks when I get back from vietnam

**Comment by a7medo778** [comment]
here is a sample api call return using get album list call (all albums are returning it in title) 
https://imgur.com/a/GRC02Q7?desktop=1

**Comment by lachlan-00** [comment]
Ablumlist. No problem. I'm back on the 10th and will fix.

Mean time enabling album group will join disks together and remove that

**Comment by a7medo778** [comment]
great, how can i do that 😅

**Comment by lachlan-00** [comment]
Preferences -> interface -> Album - Group multiple disks

I think that's going to the the future default

**Comment by a7medo778** [comment]
it was disabled,, group per releaae type was enabled and i disabled it
but still getting disk number in album titles

**Comment by lachlan-00** [comment]
group per release type is a different setting.

#2036 will stop this by checking for albums having more than one disk. just have to test the changes.

**Comment by a7medo778** [comment]
@lachlan-00 was this problem addresed already? enabling the disk grouping removed the disk number from the GUI, but still getting disk numbers qhile retrieving albums uaing subsonic api

**Comment by lachlan-00** [comment]
you should only have disk numbers for multiple disk albums everywhere now. i've tested, api, web, subsonic with enable/disable so i'm pretty confident that it's working.

The only other reason would be tags but i think i've gotten most of those cases.

show a screen of web and subsonic that you're getting?

**Comment by a7medo778** [comment]
there you go
https://ibb.co/SX0PZvb

but this is not the latest build, its a week old, so i was asking if any additional changes were made

**Comment by lachlan-00** [comment]
update to the most recent build and let me know. lots of subsonic and api changes just went in.
