### ISSUE TITLE
Email configuration problem.

### ISSUE THREAD

**Issue by trueno-pepe** [ampache/ampache#2032]
Hi:

I have problems using the email function (on the new users registration or sending emails to them after registration) of Ampache.

I have install Ampache 3.9.0, on Windows 7 using xampp. I want to use it with "free" (public) registration as "user" requering email validation, no captcha and no admin notification and nto admin "manually enable".

I want to use a GMAIL SMTP TLS secure server/account on the 587 port.  I have set  the "Allow less secure apps" setting in it.

Although I think all the setting are correct, the system are not sending any email and only a "Email no sent" message is returned (also no debug error are registered in the AMPACHE logs or the APACHE/PHP ones)

Here are the sections of the ampache.cfg.php file I have modify:

Registration: 
```
;#########################################################
; Public Registration settings, defaults to disabled     #
;#########################################################

; This setting will silently create an ampache account
; for anyone who can login using LDAP (or any other login
; extension). The default is to create new users as guests
; see auto_user config option if you would like to change this
; DEFAULT: false
;auto_create = "true"

; This setting will silently update an ampache account's
; informations for anyone who can login using LDAP
; (or any other login extension).
; DEFAULT: false
;external_auto_update = "true"

; This setting turns on/off public registration. It is
; recommended you leave this off, as it will allow anyone to
; sign up for an account on your server.
; REMEMBER: don't forget to set the mail from address further down in the config.
; DEFAULT: false
allow_public_registration = "true"

; Require Captcha Text on Image confirmation
; Turning this on requires the user to correctly
; type in the letters in the image created by Captcha
; Default is off because its very hard to detect if it failed
; to draw, or they failed to enter it.
; DEFAULT: false
;captcha_public_reg = "false"

; This setting turns on/off admin notification of registration.
; DEFAULT: false
admin_notify_reg = "false"

; This setting determines whether the user will be created as a disabled user.
; If this is on, an administrator will need to manually enable the account
; before it's usable.
; DEFAULT: false
admin_enable_required = "false"

; This setting will allow all registrants/ldap/http users
; to be auto-approved as a user. By default, they will be
; added as a guest and must be promoted by the admin.
; POSSIBLE VALUES: guest, user, admin
; DEFAULT: guest
auto_user = "user"

; This will display the user agreement when registering
; For agreement text, edit config/registration_agreement.php
; User will need to accept the agreement before they can register
; DEFAULT: false
;user_agreement = "false"

; This disable email confirmation when registering.
; DEFAULT: false
;user_no_email_confirm = "false"

; This will display the cookie disclaimer (EU Cookie Law)
; DEFAULT: false
cookie_disclaimer = "false"

; The fields that will be shown on Registration page
; If a user wants to register.
; Username and email fields are forced.
; POSSIBLE VALUES: fullname,website,state,city
; DEFAULT: "fullname,website"
registration_display_fields = "fullname"

; The fields that will be mandatory
; This controls which fields are mandatory for registration.
; Username and email fields are forced mandatory.
; POSSIBLE VALUES: fullname,website,state,city
; DEFAULT: fullname
registration_mandatory_fields = "fullname"

Mail:

;#########################################################
;  Mail Settings                                         #
;#########################################################

;Method used to send mail
;POSSIBLE VALUES: smtp sendmail php
;DEFAULT: php
mail_type = "smtp"

;Mail domain.
;DEFAULT: example.com
mail_domain = "gmail.com"

;This will be combined with mail_domain and used as the source address for
;emails generated by Ampache.  For example, setting this to 'me' will set the
;sender to 'me@example.com'.
;DEFAULT: info
mail_user = "user"

;A name to go with the email address.
;DEFAULT: Ampache
mail_name = "User Name"

;How strictly email addresses should be checked.
;easy does a regex match, strict actually performs some SMTP transactions
;to see if we can send to this address.
;POSSIBLE VALUES: strict easy none
; DEFAULT: strict
;mail_check = "none"


;#########################################################
;  sendmail Settings                                     #
;#########################################################

;DEFAULT: /usr/sbin/sendmail
;sendmail_path = "/usr/sbin/sendmai"


;#########################################################
;  SMTP Settings                                         #
;#########################################################

;Mail server (hostname or IP address)
;DEFAULT: localhost
mail_host = "smtp.gmail.com"

; SMTP port
;DEFAULT: 25
mail_port = 587

;Secure SMTP
;POSSIBLE VALUES: ssl tls
;DEFAULT: none
;mail_secure_smtp = tls

;Enable SMTP authentication
;DEFAULT: false
mail_auth = "true"

;SMTP Username
;your mail auth username.
mail_auth_user = "user"

; SMTP Password
; your mail auth password.
mail_auth_pass = "password"
```
Can you help me?

Thanks.

PS. I tryed using another SMTP servers with other security/authentication, also trying to send via "sendmail", and I have the same problem.

**Comment by noyse27** [comment]
seems that 
;mail_secure_smtp = tls

hast to be comment out and you have to choose ssl or tls

**Comment by trueno-pepe** [comment]
Yes. Sorry. I pasted it incorrectly. It s no commented, but is not working at all.

;Secure SMTP
;POSSIBLE VALUES: ssl tls
;DEFAULT: none
mail_secure_smtp = tls

Tnaks.

**Comment by trueno-pepe** [comment]
By the way... I tryed with SSL/465 and also it doesn't work.

**Comment by lachlan-00** [comment]
i'm back, will be testing my server with gmail now and reporting back

**Comment by lachlan-00** [comment]
Works for me with this config.

```

;#########################################################
;  Mail Settings                                         #
;#########################################################

; Enable or disable email server features
; otherwise, you can reset your password 
; and never receive an email with the new one
; Default: false
mail_enable = "true"

; Method used to send mail
; POSSIBLE VALUES: smtp sendmail php
; DEFAULT: php
mail_type = "sendmail"

; Mail domain.
; DEFAULT: example.com
mail_domain = "gmail.com"

; This will be combined with mail_domain and used as the source address for
; emails generated by Ampache.  For example, setting this to 'me' will set the
; sender to 'me@example.com'.
; DEFAULT: info
mail_user = "username"

; How strictly email addresses should be checked.
; easy does a regex match, strict actually performs some SMTP transactions
; to see if we can send to this address.
; POSSIBLE VALUES: strict easy none
; DEFAULT: strict
mail_check = "none"


;#########################################################
;  sendmail Settings                                     #
;#########################################################

;DEFAULT: /usr/sbin/sendmail
;sendmail_path = "/usr/sbin/sendmail"


;#########################################################
;  SMTP Settings                                         #
;#########################################################

; Mail server (hostname or IP address)
; DEFAULT: localhost
mail_host = "smtp.gmail.com"

; SMTP port
; DEFAULT: 25
mail_port = "465"

; Secure SMTP
; POSSIBLE VALUES: ssl tls
; DEFAULT: none
mail_secure_smtp = ssl

; Enable SMTP authentication
; DEFAULT: false
mail_auth = "true"

; SMTP Username
; your mail auth username.
mail_auth_user = "username@gmail.com"

; SMTP Password
; your mail auth password.
mail_auth_pass = "%%PASSWORD%%"
```

**Comment by lachlan-00** [comment]
Definitely works with Gmail so closing this.
Might be good to add as a wiki page if the same settings work for you.

**Comment by klausmcm** [comment]
> Works for me with this config.
> 
> ```
> 
> ;#########################################################
> ;  Mail Settings                                         #
> ;#########################################################
> 
> ; Enable or disable email server features
> ; otherwise, you can reset your password 
> ; and never receive an email with the new one
> ; Default: false
> mail_enable = "true"
> 
> ; Method used to send mail
> ; POSSIBLE VALUES: smtp sendmail php
> ; DEFAULT: php
> mail_type = "sendmail"
> 
> ; Mail domain.
> ; DEFAULT: example.com
> mail_domain = "gmail.com"
> 
> ; This will be combined with mail_domain and used as the source address for
> ; emails generated by Ampache.  For example, setting this to 'me' will set the
> ; sender to 'me@example.com'.
> ; DEFAULT: info
> mail_user = "username"
> 
> ; How strictly email addresses should be checked.
> ; easy does a regex match, strict actually performs some SMTP transactions
> ; to see if we can send to this address.
> ; POSSIBLE VALUES: strict easy none
> ; DEFAULT: strict
> mail_check = "none"
> 
> 
> ;#########################################################
> ;  sendmail Settings                                     #
> ;#########################################################
> 
> ;DEFAULT: /usr/sbin/sendmail
> ;sendmail_path = "/usr/sbin/sendmail"
> 
> 
> ;#########################################################
> ;  SMTP Settings                                         #
> ;#########################################################
> 
> ; Mail server (hostname or IP address)
> ; DEFAULT: localhost
> mail_host = "smtp.gmail.com"
> 
> ; SMTP port
> ; DEFAULT: 25
> mail_port = "465"
> 
> ; Secure SMTP
> ; POSSIBLE VALUES: ssl tls
> ; DEFAULT: none
> mail_secure_smtp = ssl
> 
> ; Enable SMTP authentication
> ; DEFAULT: false
> mail_auth = "true"
> 
> ; SMTP Username
> ; your mail auth username.
> mail_auth_user = "username@gmail.com"
> 
> ; SMTP Password
> ; your mail auth password.
> mail_auth_pass = "%%PASSWORD%%"
> ```

If this works, what is *mail_type* for if you are using smtp settings?

**Comment by lachlan-00** [comment]
mail_type sets how php will try sending the mail.

**Comment by klausmcm** [comment]
Ok, I see there is a *sendmail* program in the debian repository. I'm guessing that will use the smtp settings? What is *smtp* in *mail_type* for then?
