### ISSUE TITLE
registration

### ISSUE THREAD

**Issue by creepin1875** [ampache/ampache#2034]
# Issue Template
where on the login page is there registration i cant seem to figure it out can u help me plz

## Environment

* Ampache version:
* Web server + version:
* Server operating system:
* Client operating system:

* Client type:
  * Web
  * Ampache
  * SubSonic
  * DAAP
  * UPnP
  * WebDAV

**Comment by lachlan-00** [comment]
You need to configure mail and set
mail_enable in you config file to true.

Registration and lost password are hidden unless you enable mail
