### ISSUE TITLE
Status line never changes

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2044]
# Issue Template

## Environment

* Ampache version: 4.0.0 develop
* Web server + version:  Apache/2.4.41 (Debian)  PHP 7.3.8-1
* Server operating system: Debian 10
* Client operating system: Windows 10

* Client type:
  * Web Firefox
  * 

## Description

This is not really important but it bugs me. The status line at the bottom of each page never changes after logging in.
![image](https://user-images.githubusercontent.com/4076671/64864236-ab14ef80-d604-11e9-936e-d3cb98090948.png)

**Comment by kuzi-moto** [comment]
That's... odd... I'm not really sure why that would happen. What version of PHP are you using? I'm not sure if it matters, but might be good to know.

**Comment by stebe** [comment]
I updated the information above. PHP 7.3.8-1

**Comment by stebe** [comment]
I played around a bitt and this only happen when ajax page load is enabled.

**Comment by lachlan-00** [comment]
The footer doesn't technically change when you use Ajax load.
I just worked out how I killed the stars in the webplayer and the div in the footer will need some JS to reload the values.

**Comment by lachlan-00** [comment]
I've moved the footer query to the bottom of the content pages. So now when moving around the page will populate stats correctly.

The changes are in #1957 which is close to merging now.

**Comment by lachlan-00** [comment]
Moved to the bottom of the page being loaded instead of the footer. This updates each load on ajax now.
![image](https://user-images.githubusercontent.com/1305249/66169115-a92dd180-e682-11e9-97da-c09f7ffa4d72.png)

**Comment by stebe** [comment]
Confirmed that this is fixed
