### ISSUE TITLE
Images are not displayed in the search and playback status

### ISSUE THREAD

**Issue by Sevinfolds** [ampache/ampache#2047]
# Issue Template

## Environment

* Ampache version: 3.9.0
* Web server + version: Apache/2.4.38 (Ubuntu) PHP 7.1
* Server operating system: Ubuntu 18.04 LTS
* Client operating system: Windows 10

* Client type:
  * Web
  * Ampache
  * SubSonic
  * DAAP
  * UPnP
  * WebDAV

## Description

Not so long ago I found that my friends do not display pictures in the search and in the status of playing, as well as they can not download the tracks. Began to change settings from the administrator, and now the administrator has the same problems.Who had similar problems, tell me what to do?
![Screenshot_5](https://user-images.githubusercontent.com/45262957/64955025-cf383100-d88f-11e9-8194-887b142073ed.png)
![Screenshot_6](https://user-images.githubusercontent.com/45262957/64955033-d3644e80-d88f-11e9-9776-297a9667bb5c.png)
When you click the download button, this page appears, before the link had a different look
![Screenshot_7](https://user-images.githubusercontent.com/45262957/64955110-073f7400-d890-11e9-8467-65178631009d.png)

**Comment by lachlan-00** [comment]
This issue is because your htaccess files are either not present or your apache config is missing AllowOverride All

Copy these files and remove the .dist part
```
rest/.htaccess.dist
channel/.htaccess.dist
play/.htaccess.dist
```

**Comment by Sevinfolds** [comment]
@lachlan-00 
Thank you very much! Everything worked out, everything works fine now :)

<Directory /var/www/>
	Options FollowSymLinks
	AllowOverride **All**
	Require all granted
</Directory>

**Comment by lachlan-00** [comment]
That's okay, I forget this a lot when making servers and installing manually 

It can be confusing when you see art but not in all places. Downloads also require the rewrite rules from play to function.
