### ISSUE TITLE
add wildcards support to search [request] 

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2055]
hey guys
since @lachlan-00 has been doing an awesome job updating the api, I been having a problem for sometime with subsonic search api (or the xml api). 

in arabic we have some letters that are interchangeable/usesable
for example:  أ = ا or ي = ى
now regulary in rest api calls their would be an option to support wildcards, but i just couldn't make it work here.

**Comment by lachlan-00** [comment]
There is already contains and notcontains. which methods are you searching in?
![image](https://user-images.githubusercontent.com/1305249/65651308-6603ab00-e051-11e9-81dc-3470a9e251ea.png)

In the api i think we need to include an option to set the rule_1_operator. But it's actually defaulting to 0 which means it should work already
![image](https://user-images.githubusercontent.com/1305249/65651654-723c3800-e052-11e9-9c45-544bdc384b7e.png)

You should be able to call search_songs with '_' and '%' without changing anything
![image](https://user-images.githubusercontent.com/1305249/65651598-3f923f80-e052-11e9-8aa7-f861c426fc2f.png)

Same for subsonic apparently
![image](https://user-images.githubusercontent.com/1305249/65651726-b3344c80-e052-11e9-9947-e0f17eb84a2a.png)

In dsub i tested it successfully with '_' and '%'  so this might be an easy issue. ;)

**Comment by lachlan-00** [comment]
What might actually be better is if you replaced characters like that with a '_' to replace a single character in the search

I think MySQL does filter things like o and ö but I forget if that's default behaviour or if it's because they are the same character technically

**Comment by a7medo778** [comment]
@lachlan-00 mate, your a lifesaver :D
been trying this since 2016 and only thought that * works

all good

**Comment by lachlan-00** [comment]
I'm glad i could help!
