### ISSUE TITLE
updateUser api call error

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#2057]
hey guys,
i am having a problem running the updateUser subsonic api call
the call i am using is:
http://web.com/rest/updateUser.view?u=admin&p=adminPassword&v=1.11.0&c=myapp&f=json&username=Username&email=test@test.com

i am getting the following as response:
"
```
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.11.0"><error code="70" message="The requested data was not found."/></subsonic-response>
```
"

**Comment by lachlan-00** [comment]
Good to know. I'm in the process of going over subsonic top to tail looking for issues like these.

Subsonic doesn't really explain what 70 means so I'm going to assume that if this user is valid we have a bug somewhere.

**Comment by lachlan-00** [comment]
Username shouldn't be the whole email though right?

**Comment by a7medo778** [comment]
nope, i assume it shouldn't, because the required parameter is username, email is optional

**Comment by lachlan-00** [comment]
This is my call from dsub when changing email

``` 
"GET /rest/updateUser.view?u=us
er&p=enc:354ehehec52&v=1.2.0&c=DSub&username=generic&ema
il=test%40gmail.com HTTP/1.1" 200 472 "-" "DSub"
```

**Comment by lachlan-00** [comment]
fixed in develop. the user wasn't being instantiated correctly

**Comment by lachlan-00** [comment]
this should be double/triple fixed now.

Have tested all the methods multiple times creating/deleting/updating users.
