### ISSUE TITLE
Install will not create database - unable to connect

### ISSUE THREAD

**Issue by eisengrau** [ampache/ampache#2058]
# Issue Template

## Environment

* Ampache version: 3.9.0
* Web server + version: Server version: Apache/2.4.25 (Debian)
* Server operating system: Debian 9
* Client operating system: Windows 10

* Client type:
  * Web

## Description

hello. this has driving me nuts! I am stuck at the installation step when trying to create the database, I always get the error "Error: Unable to make database connection: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)" no matter if I enter the SQL root password or not
all the checks are green, the apache directory is set up properly, permissions are ok, I have been using the tarball 3.9.0

what am I missing, all files seems to be in order and accessible

![image](https://user-images.githubusercontent.com/42865787/65872398-beec7f80-e380-11e9-992b-52ce53b61455.png)

**Comment by kuzi-moto** [comment]
3.9.0 is pretty out of date at this point, so there aren't much efforts to troubleshoot issues there. I would grab the latest develop and try again, problem might have also already been fixed.

**Comment by lachlan-00** [comment]
MySQL or mariadb?

**Comment by lachlan-00** [comment]
Also on debian did you run
```
mysql_secure_installation
```

**Comment by wagnered** [comment]
I've experienced this issue. If it's MySQL 8, the way the password is processed had been changed and is the default method.  I don't know if php7.*  is  capable of using the new method, but MySQL 8 had a setting to revert to the process used by MySQL 5.* which of course any php version can do.

I don't know if mariadb has copied MySQL but I'm guessing it has in some release of version 10.



-------- Original message --------
Subject: Re: [ampache/ampache] Install will not create database - unable to connect (#2058)

**Comment by lachlan-00** [comment]
I don't think this is sha2 MySQL related but I've got a fix for that I'm testing now

**Comment by lachlan-00** [comment]
Please update to develop and test again. (https://github.com/ampache/ampache/commit/485bf2a5a95ec717eed8df986eced3e7652888be)

Fixes for MySQL during installation as well as splitting the user/database option will give better information about what step failed for you.

**Comment by eisengrau** [comment]
Thanks guys! I'll look into it asap. I would instead try the 4.0 build, as it was recommended.
I am using MariaDB, and I also ran mysql_secure_installation to change the root password as well.

**Comment by eisengrau** [comment]
I have tested the new code. I'm now getting:

> Error: Unable to make database connection: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

It doesn't go further even if I leave the password emtpy (tested by removing the root password completely from the MariaDB instance)

Strange thing that if I enter a different user name than root, it attempts to use that username and password. So I created a new user with admin privileges in MariaDB, and gave in those createntials, and it was able to create the tables, and config, and now it's working, great stuff!

![image](https://user-images.githubusercontent.com/42865787/66162271-5296a800-e62e-11e9-9f70-52f63f286419.png)

**Comment by lachlan-00** [comment]
I'm glad you're in! it might just be specific to your DB.

I've been testing on mysql and mariadb all week so i'll just do it all again this weekend to make sure

**Comment by wagnered** [comment]
For security, any connection other than by socket, root is not granted privileges to any database on MySQL or mariadb.  

Root must explicitly be granted specific privileges. Run MySQL in a CLI and run:

   MySQL> GRANT ALL PRIVILEGES ON ampache.* TO root@localhost

Then to save the change execute:

    mysql> FLUSH PRIVILEGES

For increased security, creating a different superuser was a good idea.

Because ampache is usually running on the same server as MySQL, maybe it should default to connecting by socket.  If I remember correctly, Laravel makes doing this very easy ;'>



-------- Original message --------
Subject: Re: [ampache/ampache] Install will not create database - unable to connect (#2058)

**Comment by lachlan-00** [comment]
closing this one, seems resolved
