### ISSUE TITLE
Translation issues regarding #2062 (WIP)

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#2068]
To be updated...

- If you take a look at the developer notes (red square), you'll see that we have the same string for two different actions.
We have to differentiate the strings in this case.

- Some duplicate strings are not capitalizes the same way (blue squares). Gettext is case sensitive.

![grafik](https://user-images.githubusercontent.com/6222200/66200890-52d08b00-e6a2-11e9-9e69-6e4e22734409.png)

- "The Catalog art search has started"
Is this specific enough?
Would something like "Searching album art for this Catalog" may be better?
- "The License has been deleted."
Do we want the period on the end?

Why do we sometimes have periods and sometimes not?

- "Please check your image is within the minimum %1 and maximum %2 dimensions."
"Please make sure your image is [...]"
- "Destin: 1%s"
"Destination: 1%s"
- "Size comparison failed. Not deleting: 1%s"
One time with and one time w/o "" results in two separate strings.
- "Couldn't get write to create art file: "
Is there an "access" missing?
- "Stream control bandwidth history (days)"
Should probably be "Daily stream control bandwidth history"
- "Stream control maximal bandwidth (month)"
Should probably be "Monthly stream control maximal bandwidth history"

Strings that should be the same:

- "A Username is required" and "Username is required"
- "Failed to write config file" and "Failed writing config file"
- "Unable to connect to the database: " and "Connection to the database failed: "

Strings where we have something like "catalog(s)" should be converted into singular and plural forms. Ofc we would have to implement some logic to count the catalogs that have to be processed then; so we can determine if we have 1 or less/more items to process.

Also I think singular strings should not contain the 1 as number but rather the word "one". This would make it more natural. For example in English/German:
"1 file has been updated" // Would be read like "one file has been updated" what's totally fine in English.
In German on the other hand the number "1" is called "Eins". But if you have one item for example, it would be "Ein Item" in German. But how it is now, we over correct Germans would read it like "Eins Item" What's just wrong ^^. And I think this is how it is in many other languages too. The problem with this is simply that if there is a variable specified, Transifex recognizes it and forbids translations without this specific variable.
I think I changed many of those strings in the past to match a more natural pattern and I guess this has been reverted in this update.(?) I mean, it could also be that I just dreamed about changing the stuff and never did it... 😁

**Comment by lachlan-00** [comment]
I wondered how the hints were showing up in odd places. that explains a lot, i'll work on that now.

Case sensitivity should be changed so i'll keep looking for those

I think the art search is specific because you have to pick gather art and press go
![image](https://user-images.githubusercontent.com/1305249/66203929-eb8bf880-e6ec-11e9-9386-8dfb9ce4fb46.png)

Period is usually at the end of a confirmation message/body but it could probably be removed everywhere. There are about 200.

I'll remove them now and work on hints over the weekend

**Comment by lachlan-00** [comment]
No period in strings. removed the out of case are you sure's.

will work on splitting the hints tomorrow night.

**Comment by lachlan-00** [comment]
@Psy-Virus i'm about to push in translation fixes from edge for this issue.

Changes
* A few hints in the wrong line
* About 6 strings that have been split for context
* completed full stop/period removals
* some hints with different text unified to the same text

I think this should be enough for you to upload a new list to transifex and release the dogs of translation!

**Comment by lachlan-00** [comment]
Merged!

**Comment by lachlan-00** [comment]
these changes are all in develop so closing
