### ISSUE TITLE
Web UI Disappearance of the disconnection link

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#2071]
On the development version I find that the disconnect link at the top right of the username has disappeared.
Ditto for user accounts or administrator.
I tried with several browser in desktop or mobile version.
Ampache is up to date, on Apache 2 hosted on an 18.04 ubuntu

**Comment by kuzi-moto** [comment]
The logout text was replaced with the logout icon on the sidebar.

**Comment by lachlan-00** [comment]
This was taken out for the icons in the sidebar.

sidebar logout
![image](https://user-images.githubusercontent.com/1305249/66443524-c7307300-ea82-11e9-8789-21f139c76c9f.png)

sidebar light logout
![image](https://user-images.githubusercontent.com/1305249/66443503-b8e25700-ea82-11e9-8d11-dc983b04be29.png)

**Comment by douglasriper** [comment]
Oopsie… i don't see that.
Thanks :+1:

**Comment by lachlan-00** [comment]
Don't worry, I made it extra confusing by doing the reverse a few months ago. ;)
