### ISSUE TITLE
Metadata does not get updated

### ISSUE THREAD

**Issue by Rafaeltheraven** [ampache/ampache#2075]
## Description

**Describe the bug**

The metadata in the Ampache DB seems to be "stuck", for the lack of a better word. New files can still be added, but changes in metadata for existing files do not reflect in Ampache. For example, see the following output:

```
ffprobe /var/www/nextcloud/data/rafael/files/Music/Rock/Spiritualized/\[1997\]\ Spiritualized\ -\ Ladies\ and\ Gentlemen\ We\ Are\ Floating\ in\ Space/01\ -\ Ladies\ and\ Gentlemen\ We\ Are\ Floating\ in\ Space.flac 
ffprobe version 3.2.14-1~deb9u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, flac, from '/var/www/nextcloud/data/rafael/files/Music/Rock/Spiritualized/[1997] Spiritualized - Ladies and Gentlemen We Are Floating in Space/01 - Ladies and Gentlemen We Are Floating in Space.flac':
  Metadata:
    GENRE           : Psychedelic Rock
    album_artist    : Spiritualized
    ARTIST          : Spiritualized;Spiritualized
    encoded_by      : Exact Audio Copy   (Secure mode)
    TITLE           : Ladies and Gentlemen We Are Floating in Space (original);Ladies and Gentlemen We Are Floating in Space
    comment         : Track 13
    ALBUM           : Ladies and Gentlemen We Are Floating in Space;Ladies and Gentlemen We Are Floating in Space
    ALBUM ARTIST    : Spiritualized
    DATE            : 1997;1997
    ENCODER         : reference libFLAC 1.1.4 20070213
    ENSEMBLE        : Spiritualized
    TRACKNUM        : 01
    track           : 01
  Duration: 00:03:54.00, start: 0.000000, bitrate: 875 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1000x1000 [SAR 100:100 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)
```

And compare it to what is shown in the Ampache web-interface:

```
Ladies and Gentlemen We Are Floating in Space (original) Details

Rating

        Current rating: not rated yet

Action
    Play Play last Play next Add to temporary playlist Post Shout Share Edit Disable 
Title
    Ladies and Gentlemen We Are Floating in Space (original)
Artist
    Spiritualized
Album Artist
    Spiritualized
Album
    Ladies and Gentlemen We Are Floating in Space (1997)
Genre
    Psychedelic Rock
Year
    1997
Links
    Search on DuckDuckGo ... Search on Last.fm ...
Length
    3:54
Comment
    Track 13
Bitrate
    875-VBR
Filename
    /var/www/nextcloud/data/rafael/files/Music/Rock/Spiritualized/[1997] Spiritualized - Ladies and Gentlemen We Are Floating in Space/01 - Ladies and Gentlemen We Are Floating in Space.flac 24.43 MB
Last Updated
    08/10/2019 16:15
Added
    15/06/2019 16:25
```

Note that it is the same file, but Ampache shows a different (out of date) title and track listing. I have tried both using the web-interface to 'update all' and using `catalog_update.inc`

**To reproduce**
1. Go to catalogues
2. Click on 'update all'
3. Check the track metadata
4. Nothing changed

**Expected behavior**

Track metadata should reflect those on file

**Screenshots**

## Environment

* Ampache version: `e6e463a9979b6c9718b58639fe7864e544e416de.`
* Web server + version: nginx 1.10.3
* Server operating system: Debian Stretch

## Settings

I have pasted my `ampache.cfg.php` here: https://pastebin.com/BR7P8p3A

**Comment by lachlan-00** [comment]
What isn't updated?

**Comment by Rafaeltheraven** [comment]
Small update, this seems to only apply to FLAC files, MP3 updates correctly.

**Comment by Rafaeltheraven** [comment]
> What isn't updated?

Any tag information. In the above example it is the track numbering a track title. In other examples I have seen issues with the comment, the album and various other tags

**Comment by Rafaeltheraven** [comment]
Well I feel very silly now. Because after wrestling with this issue for an hour yesterday, only 30 minutes after posting this issue I've found the problem.

The files that were impacted all had the same issue, they were FLAC files with ID3 tags embedded in them as well as Opus tags. My tagging editor skipped over them, as did my local version of ffprobe. Ampache, however, did not. Neither did the old version of ffprobe on Debian Stretch which can be seen in the output in my original post. Stripping out the ID3 tags has solved it.

This has also solved a different issue which I thought unrelated, it fixed unplayable files to become playable in the web-player. 

Everything works now, it was a tagging issue not an Ampache issue (though maybe something could be implemented to skip ID3 tags in Opus files, not that important), Sorry for wasting your time.

**Comment by lachlan-00** [comment]
One thing is the getid3_tag_order could be changed to put vorbis ahead of id3. Seeing as most files with id3 tags shouldn't have vorbis tags it might alleviate this.
```
vorbiscomment,id3v2,id3v1
```

**Comment by Rafaeltheraven** [comment]
That would probably solve the metadata issue (maybe setting it as the default could be an idea).

More interesting is the issue of the web-player not working with flac files containing both vorbis and ID3 tags, but that is a seperate issue entirely and probably will require more testing, so I'll close this issue for now.
