### ISSUE TITLE
Mediatable ids and classes dissapear after autoreload

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2081]
## Description

**Describe the bug**
Mediatable related attributes/data is removed from the DOM.

It seems to only affect the home page.

**To reproduce**

1. Navigate to home, or do a manual reload with F5.
2. Wait a minute (or whatever value the autoreload is set)

**Expected behavior**
The Mediatable data should remain the same.

**Screenshots**

A partial view of the diff before and after.

![image](https://user-images.githubusercontent.com/17068090/66605827-697d5300-eb76-11e9-8100-53af61516216.png)

## Environment

* Ampache version: Latest develop

**Client type:**

* Web

**Comment by lachlan-00** [comment]
I'm actually considering removing mediatable completely.

There's an old bug here about how it's only loads once and fails. It was also a bug on the original project but it's very dead now.

**Comment by kuzi-moto** [comment]
Makes sense. I think it would be a good idea to remove. We shouldn't keep around outdated dependencies, especially if they have bugs.

**Comment by kuzi-moto** [comment]
Also, I don't think it's necessary anyway, since I think pretty much everything it does can be done with CSS/media queries.

**Comment by lachlan-00** [comment]
Playing with it now in edge. also looking at how we can group albums by type instead of the current way which is hideously broken

**Comment by lachlan-00** [comment]
The mediatable scripts are in the header file and the header isn't reloaded each time the page is loaded.
I think that we might be able to fix this by putting it in the individual pages like i did for the query stats. in #1957

**Comment by lachlan-00** [comment]
scratch that, lets just do it in css.

Closing now that i've removed mediatable from develop
