### ISSUE TITLE
UI Update on add/edit ACLs

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2083]
**Describe what you don't like about Ampache, or what it is missing**
The add ACL and edit ACL are not consistently formatted. Name, Level, User, Type, Address are on different rows. 
 
![image](https://user-images.githubusercontent.com/4076671/66614953-da356700-eb98-11e9-969c-bafab228b82e.png)
![image](https://user-images.githubusercontent.com/4076671/66614966-eae5dd00-eb98-11e9-8966-15ee85088d6e.png)

**Describe how you would like the feature to work**
Just having the rows match on each screen.

**Comment by lachlan-00** [comment]
They are wildly inconsistent.
I'll match them up in a few hours

**Comment by lachlan-00** [comment]
in pull #2086
