### ISSUE TITLE
Remove rel="nohtml" attribute from <a> elements

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2084]
## Description

**Describe the bug**
In 41 cases in Ampache, `<a>` elements have a `rel` attribute with the value `"nohtml"`. This doesn't appear to be a valid keyword and should probably be removed.

I would do it myself, but I'm not sure what should be in there, if anything, so I didn't want to screw with it.

**Example**

in `/templates/sidebar.inc.php` line 68:

```html
<a target="_top" href="<?php echo $web_path; ?>/logout.php" id="sidebar_logout" rel="nohtml">
```

**Comment by lachlan-00** [comment]
Could be something js related we aren't aware of?

**Comment by wagnered** [comment]
I shall add my two cents...

I checked the HTML 4.01 specs and the word "nohtml" must have been removed in an earlier version.

Unless the word "nohtml" is accessed by JavaScript, and I highly doubt it is, the attribute most likely  can be removed from ampache.

The rel attribute only defines the links relationship to the current document : first, last, next, etc.



-------- Original message --------
Subject: [ampache/ampache] Remove rel="nohtml" attribute from <a> elements (#2084)

**Comment by kuzi-moto** [comment]
It could be possible, but searching Google mostly brings up results that have to do with Ampache. As it's not part of the HTML spec itself, it seems like maybe something that became obsolete but never removed from Ampache.

**Comment by wagnered** [comment]
Kuzma,

I studied the js quite thoroughly to understand it and don't remember seeing it in the is code.  With only 41 entries, would it be difficult to remove them and exercise the changes?

Just a suggestion as I hate to see that kind of stuff cluttering up the code. ( ; ' >





-------- Original message --------
Subject: Re: [ampache/ampache] Remove rel="nohtml" attribute from <a> elements (#2084)

**Comment by kuzi-moto** [comment]
Yeah, I'm fine with just removing those and see what happens. I bet it doesn't do anything now anyway, as I can't find any information on what it should do.

**Comment by lachlan-00** [comment]
There's no better way to find out what it affects by removing it completely and seeing what happens

**Comment by lachlan-00** [comment]
testing in edge now.

**Comment by lachlan-00** [comment]
Interesting bug with the logout process is back when testing this.

This was that error i was getting with the logout buttons in stringsupdate. The site doesn't reload to the login page size and fails to complete loading the logo.
![image](https://user-images.githubusercontent.com/1305249/66727510-10b5ff00-ee83-11e9-9282-7370c1709c3d.png)

**Comment by lachlan-00** [comment]
it actually breaks function in a lot of places when removed.

Downloads break, logout and that's just from a few minutes browsing.

**Comment by kuzi-moto** [comment]
Odd... Maybe it can be replaced with one of the other keywords so that there HTML validates properly?

**Comment by lachlan-00** [comment]
I tried noreferrer from w3school list <https://www.w3schools.com/TAGS/att_a_rel.asp> but it breaks as well unless it's nohtml

**Comment by lachlan-00** [comment]
I'll do some more tests with it later but I've reverted edge back to develop.

It clearly does something but I'm not sure what.

**Comment by stebe** [comment]
I wonder if this will help?  https://github.com/mobz/nohtml

**Comment by kuzi-moto** [comment]
This is the only menion of "nohtml" I can find in JS in Ampache in `lib/javascript/dynamicpage.js` on line #76:

```JS
        if (typeof link !== "undefined" && link !== "" && link.indexOf("javascript:") !== 0 && link !== "#" && typeof link !== "undefined" && typeof $(this).attr("onclick") === "undefined" && $(this).attr("rel") !== "nohtml" && $(this).attr("target") !== "_blank") {
```

But all it's doing is checking to see if it's the value of the rel attribute.

**Comment by lachlan-00** [comment]
That seems to line up with the errors I get.

A download or logout are meant to just be links and that code is saying when nohtml isn't found do something ajax'y

Seems like it's a way of telling Ampache to follow links directly.

**Comment by lachlan-00** [comment]
so it seems like at least in the context of dynamicpage.js nohtml is needed.

Should we use a valid attribute instead of nohtml to avoid confusion?

Something like:
external
nofollow
noreferrer
noopener

**Comment by kuzi-moto** [comment]
> Should we use a valid attribute instead of nohtml to avoid confusion?

I think that would be a good idea. Seems like maybe "next" might make more sense though?

**Comment by kuzi-moto** [comment]
Got the fix! Realized that using the `rel` attribute is just silly, when we can simply add **nohtml** as a `class` instead! Submitting a pull to edge.

**Comment by lachlan-00** [comment]
That works for me. It just needs to identify links that need to be ignored so a class does the job. I'll close when I've pushed to develop

**Comment by lachlan-00** [comment]
No issues in testing. really happy with doing things this way and it's merged.

**Comment by kuzi-moto** [comment]
Awesome! Yeah I think it's the cleanest way to accomplish this.
