### ISSUE TITLE
[Discussion] Considering updating DOCTYPE to HTML5/XHTML5

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2087]
While doing some work with Ampache, it would appear that the DOCTYPE is set to XHTML 1.0 Transitional, which is equivalent to HTML 4.01 Transitional and has been superseded in 2018.

I think it would be beneficial to update the doctype to HTML5. It appears there are some cases where we are already using some HTML5 features, and there are lots of other APIs that would be useful, drag and drop, local storage, Server Sent Events, audio/video tag, etc.

The main motivation behind this was because I was validating the HTML output of Ampache, and found quite a few errors. Either way I'd like to fix these errors, but before putting in the effort wanted to see about updating to the HTML5 doctype.

**Comment by lachlan-00** [comment]
Whats positive is that i think this fixes a chrome issue i've been having in the webplayer.

**Comment by kuzi-moto** [comment]
Nice! I think that browsers do a good job of figuring out incorrect markup, bit better that we make sure everything is correct. I think it's been working out great so far - which mostly means there were no discernable changes - which is also good.

**Comment by AshotN** [comment]
Any reason why the DOCTYPE wouldn't be updated? HTML5 isn't new and telling the browser that the page is HTML4 can cause unexpected issues.

**Comment by kuzi-moto** [comment]
> Any reason why the DOCTYPE wouldn't be updated?

I couldn't see any.

> HTML5 isn't new and telling the browser that the page is HTML4 can cause unexpected issues.

Also agree. Lachlan did update the docype a week or two ago in Develop, so it should be working now.

**Comment by lachlan-00** [comment]
No issues have come from the change so let's consider moving to html5 doctype closed
