### ISSUE TITLE
Media does not have a valid filename - filename from mount in Linux?

### ISSUE THREAD

**Issue by rodrigoesborges** [ampache/ampache#2093]
## Description

**Describe the bug**
Trying to play any file gives: Media does not have a valid filename - filename in log and does not play.
Example:
(play/index) -> Media /media/4tb/Musik/Haydn/0000 - ºSinfonias 48(Maria Theresia),49(La Passione)/8 - Haydn. Hogwood - No. 49 in F minor IV. Finale- Presto.mp3 (No. 49 in F minor IV. Finale: Presto) does not have a valid filename specified 

/media/4tb is a NFS mount

**To reproduce**
1. Go to playlist
2. Select Local play, web player or stream
3. Click on any playlist and ask to play

**Expected behavior**

music starts to be played as ordered
**Screenshots**

## Environment

* Ampache version: develop (2019-10-15 checked out)
* Web server + version: Nginx 1.17..3
* Server operating system: openSUSE Tumbleweed / Factory
* Client operating system: openSUSE Tumbleweed / Factory

**Client type:**

* Web
* Amarok
* WebDAV

**Comment by lachlan-00** [comment]
I'll need to look up "does not have a valid filename specified".

I use full UTF text in my filenames and haven't found an issue yet so it should hopefully be simple

**Comment by rodrigoesborges** [comment]
Sorry, the problem was on my side. Some funky issues when trying to use nfs4 with a (propietary) NAS . Nothing to do with ampache.

**Comment by lachlan-00** [comment]
That was simple!
