### ISSUE TITLE
[Feature Request] MusicBee plugin to sync the library

### ISSUE THREAD

**Issue by MightyMalcolm** [ampache/ampache#2104]
Hello everybody,

as I was asked to [in this discussion](https://groups.google.com/d/topic/ampache/In-TGBnTpDY/discussion), I am posting this issue. So I'd kindly ask if you could tell me whether [this MusicBee plugin](https://github.com/ampache/ampache/issues/1352) works with Ampache and helps me sync my local files to Ampache (and vice versa).

Thanks in advance,
Malcolm

**Comment by lachlan-00** [comment]
I'll try it out and see what works/doesn't

**Comment by lachlan-00** [comment]
it seems to work okay but it doesn't integrate them into the main library.
![image](https://user-images.githubusercontent.com/1305249/67257216-433ca900-f4ce-11e9-8f1d-b3446fc31dfa.png)

It splits catalogs into individual folders correctly
![image](https://user-images.githubusercontent.com/1305249/67257245-58193c80-f4ce-11e9-89b3-378c54ba360c.png)

it doesn't seem to load playlists correctly
![image](https://user-images.githubusercontent.com/1305249/67257354-e7beeb00-f4ce-11e9-8d8d-10a5d6ad0f0c.png)

It seems a bit flaky loading files
![image](https://user-images.githubusercontent.com/1305249/67257377-03c28c80-f4cf-11e9-8c50-b30bf2b313a2.png)
![image](https://user-images.githubusercontent.com/1305249/67257403-2359b500-f4cf-11e9-8314-2b1ef1e62b29.png)

and it doesn't seem to load the track when i click play now?

These could all be related to my library size but it's not really that well integrated into the musicbee setup.

**Comment by MightyMalcolm** [comment]
Thanks @lachlan-00 for your efforts. I've also been trying to get the plugin running during the last few days, but it didn't even connect to my Ampache server. It did okay-ish with a local Subsonic server, but that's, of course, not what I need.

Just out of curiousity: what did you do to make the plugin talk to your Ampache?

**Comment by lachlan-00** [comment]
Used my API key as the password and I am running the develop branch.

Ampache supports both styles of auth for subsonic (token / password) but using the API key will cover both ways

**Comment by MightyMalcolm** [comment]
Thanks!

**Comment by MightyMalcolm** [comment]
Well, I'm afraid I have to ask again, since I am not able to establish a connection to my Ampache properly.

- My Ampache version is **3.9.0** (freshly installed).
- My server sits at `music.my-server.net`.
- I'm running **Apache** on **Ubuntu 18.04**.

I'm pretty sure I did everything in [this tutorial](https://github.com/ampache/ampache/wiki/API#subsonic-api) (though, tbh, I did not understand all of it -> not an expert here) and I even got to the point that when I navigate to `https://music.my-server.net/rest/ping.view`, I am receiving the message

```
<subsonic-response status="ok" version="1.11.0">
<error code="10" message="Required parameter is missing."/>
</subsonic-response>
```

That should be fine, right? So, I then configured my MusicBee as follows
![musicbee_config](https://user-images.githubusercontent.com/3305275/67431781-46768880-f5e5-11e9-8743-4051f65b9396.jpg)
... which seems to be working ...
![ping_ok](https://user-images.githubusercontent.com/3305275/67431831-61e19380-f5e5-11e9-8f2e-073d38604872.jpg)
... but when I click on the Subsonic icon, Musicbee tells me that ...
![error](https://user-images.githubusercontent.com/3305275/67431888-7f166200-f5e5-11e9-801b-6cdd535a76d9.jpg)

Any idea how to fix that? I'm terribly sorry but I'm slightly in over my head with all this webhosting business and the tutorials don't seem to be written for newbies such as me.

On a side note, I was able to generate a token for my user via the web interface, but then the plugin told me that token-based authentication was not supported.

Cheers
Malcolm

**Comment by kuzi-moto** [comment]
> My Ampache version is 3.9.0 (freshly installed).

I would recommend using the latest 4.0.0-develop version. 3.9.0 is quite out of date at this point, and the subsonic code has been updated a lot since.

> I'm pretty sure I did everything in this tutorial (though, tbh, I did not understand all of it -> not an expert here) 

Just curious, what could use further explanation? I wouldn't mind updating so it's accessible to more people.

**Comment by lachlan-00** [comment]
thanks for taking time to play with things.

**Comment by kuzi-moto** [comment]
@MightyMalcolm I appreciate you taking the time to list out areas in the wiki that can be improved. Ampache is definitely a bit more involved to set up than the average application, and does appear the wiki needs more clarification, especially for more novice users.

Sorry it couldn't work out for you in the end.
