### ISSUE TITLE
Error when trying to retrieve podcasts from Ultrasonic

### ISSUE THREAD

**Issue by rodrigoesborges** [ampache/ampache#2107]
## Description

**Describe the bug**
When trying to access smart playlist or podcasts from Subsonic client, I get a network error at the client, and some logs with permission denied

**To reproduce**
1. Set up subsonic to the server with LDAP enabled (only way auth it's working)
2. Click on 'Playlists'
3. Select a Smart Playlist

**Expected behavior**

Before last changes, I was able to retrieve and reproduce smart playlists, I was able also to retrieve podcasts lists , even though I couldn't actually access any subscribed podcast from subsonic app

**Screenshots**

## Environment

* Ampache version: 4.0.0 develop
* Web server + version: nginx 1.17.3
* Server operating system: Linux
* Client operating system: Android

**Client type:**

* SubSonic

## Settings

Relevant part
```
; This turns the caching mechanisms on or off, due to a large number of
memory_cache = "true"
; Set this to true to enable podcasts and the
; possibility for admins to subscribe to new podcasts.
podcast = "true"
```

## Logs

Podcast list error:

```
2019/10/23 10:40:35 [crit] 16015#16015: *3159 open() "/var/lib/nginx/fastcgi//1/06/0000000061" failed (13: Permission denied) while reading upstream, client: X.X.X.X server: myampachedomain.tld request: "GET /rest/getPodcasts.view?includeEpisodes=false&u=rodrigo&c=Ultrasonic&f=json&v=1.13.0&p=enc:51376655593665595863 HTTP/1.1", upstream: "fastcgi://127.0.0.1:PORT", host: "myampachedomain.tld:PORT" 
```

Smart Playlist retrieve error:
```
2019/10/23 10:41:03 [crit] 16015#16015: *3162 open() "/var/lib/nginx/fastcgi//2/06/0000000062" failed (13: Permission denied) while reading upstream, client: X.X.X.X, server: myampachedomain.tld, request: "GET /rest/getPlaylist.view?id=400000005&u=rodrigo&c=Ultrasonic&f=json&v=1.13.0&p=enc:51376655593665595863 HTTP/1.1", upstream: "fastcgi://127.0.0.1:PORT", host: "myampachedomain.tld:PORT"
```
On the regular log, I see, though:
```2019-10-23 13:47:59 [ampache] (access.class) -> check_network rpc: ip matched ACL X.X.X.X 
2019-10-23 13:47:59 [rodrigo] (subsonic_xml_data.class) -> API success in function getplaylist-1.13.0 
2019-10-23 13:48:15 [ampache] (access.class) -> check_network rpc: ip matched ACL X.X.X.X
2019-10-23 13:48:15 [rodrigo] (subsonic_xml_data.class) -> API success in function getpodcasts-1.13.0 
```

**Comment by lachlan-00** [comment]
Looks like it's an nginx permission error from this part of the message.
```
open() "/var/lib/nginx/fastcgi//2/06/0000000062" failed (13: Permission denied)
```

Not sure of any changes Ampache-side that would cause this

**Comment by rodrigoesborges** [comment]
Absolutely right about smart playlists, sorry about that. Fixed that and now I'm back again to a problem only when, after having retrieved the list of subscribed podcasts, when trying to access any, I get "network error" and, with debug level 6, among many things, I see:

```
SELECT * FROM `podcast_episode` WHERE `id`='267' null
[Warning] Undefined index: callback in file /XXX/ampache/lib/class/subsonic_api.class.php(173) 
```

**Comment by lachlan-00** [comment]
Now that seems like an error i can look for.

I don't get it with my podcasts but that null means there may be either something missing from your table/podcast or an error in the query.

**Comment by rodrigoesborges** [comment]
Ok

When I do the same query (id 267, for example) directly to the corresponding mysql table , I get one row with the episode details, as expected

**Comment by wagnered** [comment]
Does ultrasonic give any errors?

The $input['callback'] index needs to be tested:
`$callback = isset($input['callback']) ? $input['callback'] : '';`
if my memory serves me correctly.  
And I'm not sure but it might also solve your problem.  ; ' >
A callback exists only if the client requests the JSONP format.

**Comment by wagnered** [comment]
Does ultrasonic give any errors?

The $input['callback'] index needs to be tested:
`$callback = isset($input['callback']) ? $input['callback'] : '';`
if my memory serves me correctly.  
And I'm not sure but it might also solve your problem.  ; ' >
A callback exists only if the client requests the JSONP format.

**Comment by lachlan-00** [comment]
Just checked ultrasonic and I can confirm this.
Doesn't happen on dsub so I'll check out why

**Comment by rodrigoesborges** [comment]
Let me see If I can understand where/how to test your suggestion, @wagnered

**Comment by lachlan-00** [comment]
definitely json related. although it's only with podcasts and not playlist for me using ultrasonic
ultrasonic is calling for json over jsonp so the callback check doesn't look to have any effect.

The json returned is valid so i'm not sure why it's starting to error.

**Comment by wagnered** [comment]
@lachlan,

Are you sure Ultrasonic is using jsonp for podcasts?  Ultrasonic went using in version 2.0.0.  The Ultrasonic crew gave me a lot of help working out bugs: see issue #1651.

JSONP is only for "out of of origin" requests. I don't think that is necessary.  Also, the callback function must be specified by the client, or default to a given name agreed to by the client and third party server. This may be the default name "callback".

See the [integration test resources]( @lachlan,

Are you sure Ultrasonic is using jsonp for podcasts?  Ultrasonic went. Json in version 2.0.0.  The Ultrasonic crew gave me a lot of help working out bugs: see issue #1651.

JSONP is only for "out of origin" requests. I don't think that is necessary.  Also, the callback function must be specified by the client, or default to a given name agreed to by the client and third party server. This may be the default name "callback".
 
Do you have a tool like wireshark to see what the ultrasonic client is actually sending?  I used wireshark quite often when debugging the REST api.  It could be a bug with Ultrasonic, as the `apioutput()`function is called by all methods and only fails with `getpodcasts()`.

See [integration test resources]( https://github.com/ultrasonic/ultrasonic/blob/master/subsonic-api/src/integrationTest/resources/get_podcasts_ok.json) for getpodcasts return results. 

At any rate $input['callback'] should be checked with `isset` and set to '' if it's not.

**Comment by lachlan-00** [comment]
my access.log has ultrsonic only requesting format=json.

I'll double check against that test resource because ther error only happens when fetchepisodes is true

**Comment by lachlan-00** [comment]
here's the first difference
![image](https://user-images.githubusercontent.com/1305249/67725948-e4c47d00-fa2f-11e9-9a27-d3af5fa4a58f.png)

**Comment by lachlan-00** [comment]
I've also gone back almost a month in the subsonic classes and still get the error. will test on a full copy of the earlier branches.

**Comment by lachlan-00** [comment]
I've found the error and will be merging it tonight when i can squash all my mini commits and test fully.

The alwaysarray code was being ignored when nested types had a subarray. (channels have arrays of episodes)
![image](https://user-images.githubusercontent.com/1305249/67734004-a341cb00-fa4b-11e9-9a4d-a49ba86e80ad.png)

**Comment by rodrigoesborges** [comment]
Great! Eager to test it

**Comment by lachlan-00** [comment]
tested using ultrasonic and checked for extra instances of nested arrays. (none from the examples in the ultrasonic repo) merging with other recent fixes now.

**Comment by rodrigoesborges** [comment]
I can confirm that the podcasts episodes are being retrieved now! I've stumbled on another problem it seems. With url rewriting enabled (in options -> streaming) songs are not being downloaded, it seems there is an %20 / space added at the end "%20.%2mp3" which seems to be responsible for a not found error.
As a workaroun, disabling url rewriting everything works! Thanks a lot!

**Comment by lachlan-00** [comment]
you'll need to make a new issue. downloads aren't broken with/without rewriting for me so i'll need some more info.

**Comment by rodrigoesborges** [comment]
Since 2 or 3 weeks the problem started to happen again (playlists retrieval works fine, podcast retrieval fails and returns a network error message in Ultrasonic).
These are Level 6 debug logged messages when trying to retrieve podcasts:

`2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT * FROM `podcast_episode` WHERE `id`='3809' [] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT COUNT(`id`) AS `nb_img` FROM `image` WHERE `object_type` = ? AND `object_id` = ? AND `kind` = ? ["podcast","53","default"] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT `id`, `date` FROM `user_flag` WHERE `user` = ? AND `object_id` = ? AND `object_type` = ? ["1",3809,"podcast_episode"] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT * FROM `podcast_episode` WHERE `id`='3810' [] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT COUNT(`id`) AS `nb_img` FROM `image` WHERE `object_type` = ? AND `object_id` = ? AND `kind` = ? ["podcast","53","default"] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT `id`, `date` FROM `user_flag` WHERE `user` = ? AND `object_id` = ? AND `object_type` = ? ["1",3810,"podcast_episode"] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT * FROM `podcast_episode` WHERE `id`='3811' [] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT COUNT(`id`) AS `nb_img` FROM `image` WHERE `object_type` = ? AND `object_id` = ? AND `kind` = ? ["podcast","53","default"] 
2020-05-24T03:31:09+00:00 [admini] (dba.class) -> SELECT `id`, `date` FROM `user_flag` WHERE `user` = ? AND `object_id` = ? AND `object_type` = ? ["1",3811,"podcast_episode"] 
2020-05-24T03:31:09+00:00 [ampache] (log.lib) -> [Warning] Undefined index: callback in file /srv/www/ampache/lib/class/subsonic_api.class.php(199) 

`

**Comment by lachlan-00** [comment]
I can see that in ultrasonic but not dsub. Will look tomorrow

**Comment by lachlan-00** [comment]
Probably json related as dsub uses xml

**Comment by lachlan-00** [comment]
Actually i don't get any error @rodrigoesborges (i didn't put in the server name correctly so ultrasonic wasn't working)

If you get an error i need the call that you're making to the web server it will be something like this one when i refresh episodes.
```
/rest/getPodcasts.view?includeEpisodes=false&id=600000010&u=user&c=Ultrasonic&f=json&v=1.13.0&p=enc:password
```

**Comment by rodrigoesborges** [comment]
I think this would be the call? By the way thanks a lot again @lachlan-00 !

`"GET /rest/getCoverArt.view?id=200011938&size=256&u=rodrigo&c=Ultrasonic&f=json&v=1.7.0&p=enc:3539646162333836363438346433356561333066333630623163343330313730 HTTP/1.1" 200 0 "-" "okhttp/3.10.0"
`

**Comment by rodrigoesborges** [comment]
I think this would be the call? By the way thanks a lot again @lachlan-00 !

`/rest/getCoverArt.view?id=200011938&size=256&u=user&c=Ultrasonic&f=json&v=1.7.0&p=enc:hashedpassword HTTP/1.1" 200 0 "-" "okhttp/3.10.0`

**Comment by lachlan-00** [comment]
if you paste that into your browser do you get a response?
![image](https://user-images.githubusercontent.com/1305249/82775781-15687a00-9e8c-11ea-9c14-e91d68985262.png)

I tested my response outside ultrasonic in a validator and it's okay

**Comment by rodrigoesborges** [comment]
Ok I'm very dumb/noob, so I don't know how to paste that into the browser. How would it be?
I searched and found a way of copying a request as curl and then pasting it on cli:
` curl 'https://midia.borges.net.br:9093/rest/getPodcasts.view?includeEpisodes=false&u=rodrigo&c=Ultrasonic&f=json&v=1.13.0&p=enc:passowrd' -X GET -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Origin: https://midia.borges.net.br:9093' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: pt-BR,pt;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.129 Safari/537.36' -H 'Accept: application/xml, text/xml, */*; q=0.01' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: sidebar_state=expanded; ampache_remember=rodrigo%3A6a92b5901a80bbf824e5fa991ddf36e9%3A5dbfba8bd11907350d64ae52aa288cd152581127816f772bddde7d9a1ee1b9c5; ampache=34c3079397dba8a10b2fbcfdd96a24e4' -H 'Connection: keep-alive' -H 'Content-Length: 0' --compressed -o Ranswerfrompodcastrequest.json
`
I gess the json created has got not much of personal info besides my "preferences" for podcasts, maybe I should post it?

I pasted it on a validator and it resulted as valid. The only thing I noticed is that episodes seemed to be retrieved, even though the request includes "includeEpisodes=false". Might that be the related to the error?

**Comment by lachlan-00** [comment]
okay, so generating valid json is good.
episodes are getting included in xml as well so i'll stop that. it's true by default but should respect the call.

I don't think it's the cause of the error though. are you on the latest develop? 4.0.0 is really old if you're still there.

**Comment by rodrigoesborges** [comment]
Hi @lachlan-00 sorry for the late delay. I am on latest develop. After trying dsub, I stared sticking to it, since overall it seems more stable, no bugs on access, and faster. 

I have just tried again to access podcasts from Ultrasonic, now I get a message on android about not being authorized, on the access.log I get http 200, on ampache debug log I see like

```
2020-06-24T13:21:18+00:00 [ampache] (dba.class) -> SELECT `id` FROM `user` WHERE `username` = ? OR `fullname` = ? ["rodrigo","rodrigo"] 
2020-06-24T13:21:18+00:00 [ampache] (log.lib) -> [Warning] Trying to get property 'username' of non-object in file /srv/www/ampache/lib/log.lib.php(159) 
2020-06-24T13:21:18+00:00 [ampache] (dba.class) -> SELECT * FROM `user` WHERE `id`='1' [] 
2020-06-24T13:21:18+00:00 [rodrigo] (dba.class) -> SELECT `preference`.`name`, `user_preference`.`value`, `syspref`.`value` AS `system_value` FROM `preference` LEFT JOIN `user_preference` `syspref` ON `syspref`.`preference`=`preference`.`id` AND `syspref`.`user`='-1' AND `preference`.`catagory`='system' LEFT JOIN `user_preference` ON `user_preference`.`preference`=`preference`.`id` AND `user_preference`.`user` = ? AND `preference`.`catagory`!='system' [1] 
2020-06-24T13:21:18+00:00 [ampache] (log.lib) -> [Warning] Undefined index: id in file /srv/www/ampache/lib/class/subsonic_api.class.php(2050) 
2020-06-24T13:21:18+00:00 [rodrigo] (subsonic_xml_data.class) -> API fail in function getpodcasts-1.13.0 
2020-06-24T13:21:18+00:00 [ampache] (log.lib) -> [Warning] Undefined index: callback in file /srv/www/ampache/lib/class/subsonic_api.class.php(199) 

```
