### ISSUE TITLE
Is templates/show_dynamic.inc.php used?

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2109]
## Description

Looking through the code, I'm pretty sure that `templates/show_dynamic.inc.php` is never used in any other part of the code and is impossible to access. Can it be deleted, or should it be re-added somewhere?

**Comment by lachlan-00** [comment]
it was put in here in this commit 4979ca79f67ae1328c14b186617b8cca5ce5e364
I can't say i've found anything about it so it's probably very safe to delete.

**Comment by kuzi-moto** [comment]
Great! Wonder why it was never used.

**Comment by lachlan-00** [comment]
it looks like it was something to do with searching that was implemented in a different way a few times over the years.
I'll remove it and looks for issues in the open pull. Things on edge are stable again so feel free to keep digging.

**Comment by lachlan-00** [comment]
just checked the history too and it's not referred to beyond style/layout fixes so totally dead i think

**Comment by kuzi-moto** [comment]
Perfect! I think this is safe to close.
