### ISSUE TITLE
Subsonic api method `getnewestpodcasts` ignores count parameter

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2112]
@lachlan, I was looking at the subsonic API methods and noticed that `getnewestpodcasts` is incomplete.  It looks like @afterster got too busy or sidetracked to finish it.

The $count variable needs to be passed to `Catalog::get_newest_podcast($count=null)`.  I don't think that the $catalog parameter needs to be passed. Maybe I am missing something, but shouldn't all catalogs be checked?

**Comment by lachlan-00** [comment]
The subsonic API website says count is not required and defaults to 20.

I think we've set it to the db settings for episodes to fetch?

I'll need to have a look to confirm but I'm pretty sure that's why Ampache isn't requesting a count.

For the Catalog I would think it's looking for a podcast Catalog and loading it. I'm not sure if there are allowances for more than one podcast Catalog so another thing to check

**Comment by lachlan-00** [comment]
After checking i can see what needs to happen.

all Catalogs are checked (will only query for podcast catalogs)
Count is never given but will be included again possibly through the fetch limit number.

**Comment by lachlan-00** [comment]
dsub goes for 10 by default and i've set it to use the fetch config as well as a fallback

will test later tonight when i'm home

**Comment by wagnered** [comment]
But then it doesn't conform to the subsonic api specs. The description of subsonic_api::getnewestpodcasts that was written by @afterster, "* Takes the optional count in parameters", explicitly states his intent.

All I got is this dinky Samsung phone.  I'd love to help you if I could.  It looks simple: just pass the. alue of count down to `Catalog::get_newest_podcast_id()`, and add it to the sql statement with the LIMIT keyword.

As for creating multiple podcast catalogs, I believe ampache allows it, as long as they reside at different locations.  I don't know why that would make a difference.

-------- Original message --------
Subject: Re: [ampache/ampache] Subsonic api method `getnewestpodcasts` ignores count parameter (#2112)

**Comment by lachlan-00** [comment]
The limit passed is respected by 8c5f64b falling back to the ampache config value
```
$count = $input['count'] ?: AmpConfig::get('podcast_new_download');
```

It was commented out originally because it was never used. now it's used and the limit is added

**Comment by wagnered** [comment]
OK now I understand.  I didn't realize you just added a new commit.


I like it.  It adds a little versatility, but why not just hardcode it to 20? I'm not sure what advantages it gains other than more admin control.



-------- Original message --------
Subject: Re: [ampache/ampache] Subsonic api method `getnewestpodcasts` ignores count parameter (#2112)

**Comment by lachlan-00** [comment]
That's really the only advantage.

But it would only happen for clients that don't set a limit as well.
