### ISSUE TITLE
New Install Missing Bootstrap

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2119]
## Description

**Describe the bug**
I just git cloned the develop branch onto my server and am trying to install and but the error I'm getting is 
`2019/10/29 22:09:40 [error] 29050#29050: *12 open() "/var/www/html/ampache.hego.co/lib/components/bootstrap/css/bootstrap.min.css" failed (2: No such file or directory)
`

## Environment

* Ampache version: Develop Branch
* Web server + version: nginx/1.14.0 (Ubuntu)
* Server operating system: Ubuntu
* Client operating system: Ubuntu

**Comment by AshotN** [comment]
I'm an idiot, I hadn't ran the Composer install command.

**Comment by lachlan-00** [comment]
haha, it gets me every time!
