### ISSUE TITLE
Unifying XML and JSON API

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2121]
Current implementation of the XML API in JSON involves a duplication of the entire XML API code base, while this was great for backwards compatibility, it's a lot of extra code that increases the chance of inconsistency between the data formats. 

I have created a branch with such proposed changes, not all of my proposed changes are done yet, they would be breaking but if that's asking for too much we can add bridges to resolve that. 

The start
https://github.com/AshotN/ampache/commit/46ca830f11cee578aaae4187824c56e376d324f1

**Comment by lachlan-00** [comment]
i'm out for the night but another thing to look at is just using an apioutput method like subsonic_api then use xml2json when the format is json it might save all the duplication by converting the xml string to json instead.

**Comment by AshotN** [comment]
I'll try to look into the xml2json converter, I just don't like relying on converters in case there is ever a time we hit a limitation of the converter. If we were to rely on a converter we could always expect the client to just use the converter themselves. But ya we should explore the possibilities.

**Comment by AshotN** [comment]
Ya my Git skills have grown a little over the last few years but they still garbage, so my fork is behind the master. 

I'm trying to find reasons for and against XML2JSON converters, the only thing I keep seeing is that XML when translated to JSON has some weird syntax. This site has some examples
https://www.xml.com/pub/a/2006/05/31/converting-between-xml-and-json.html 

Mainly the issues I see is that XML attributes get converted in a weird way. So we should decide how we want to deal with JSON, manually or with a converter. I'll wait for us to make a final decision before continuing any work unifying the API.

**Comment by lachlan-00** [comment]
I agree that a single way needs to happen but that leans me towards xml2json because it exists in subsonic already.

That's a really good resource as i wasn't really aware of the json structure before this week.

tonight i want to "finish" adding some final methods into the api and then i think that's a good time to focus on what should change.

**Comment by AshotN** [comment]
I'll try to compare the Subsonic JSON/XML and see what it's using. XML just in it's nature is not Javascript, and JSON works with Javascript perfectly. @attribute for example has to be accessed with bracket notation instead of dot, and it's just something I had never even seen before. Also sometimes things in XML that make sense don't make sense in JSON. For example having a href attribute just doesn't make sense in JSON. 

Let me know how we should proceed, I'm kinda bored with my work related projects and I've wanted to help cleanup Ampache for a while.

**Comment by wagnered** [comment]
By "manual" I assume you mean a separate class such as Subsonic_json_data class? Actually, subsonic_api should be renamed "subsonic_xml_api and duplicated with "subsonic_json_API" and rest/index.php should determine which class should be called.  Yes, it's more code, but I think it will run faster, but only performance testing will confirm.  Plus it should be easier to modify when the subsonic API changes.

Just my two cents worth. ; ' >



-------- Original message --------
Subject: Re: [ampache/ampache] Unifying XML and JSON API (#2121)

**Comment by lachlan-00** [comment]
The subsonic api will not be changing outside of bugfixing now that it's updated for 1.13.0 so it's probably the best place to start as well.

**Comment by AshotN** [comment]
I’m just focusing on the Ampache API itself. I think it be better to do the JSON manually. I think it’s worth the extra work to have control of the JSON formatting.

**Comment by AshotN** [comment]
Should we shelve this JSON discussion until 4.0 is released?

**Comment by lachlan-00** [comment]
I think so, but mostly so we can get 4 released and work on it from a stable perspective.

**Comment by AshotN** [comment]
@lachlan-00 after 4.0 is out on Monday, can we begin getting JSON into mainline. Writing a client would be easier with a standardized API that I don't have to implement as I go.

**Comment by lachlan-00** [comment]
haha, yes! i think it would be a good thing to focus on next.

**Comment by AshotN** [comment]
So how's this looking

**Comment by lachlan-00** [comment]
Good actually.
I need to merge recent 4.1.0 changes back into the JSON branch but i have been using that api.class on my personal server and the JSON changes haven't affected my XML usage.

I think what i'll do is double check the XML processes after updating the branch and then if that works we just need to get json_data up to the same version.

**Comment by lachlan-00** [comment]
Ideally we should be able to merge this pretty quickly as long as XML isn't affected and move the the JSON development into edge

**Comment by lachlan-00** [comment]
It's in!

I'm starting the documentation with examples for XML and json in the org site but i'll have to do a lot more to get it usable compared to the wiki.
http://ampache.org/api.html

On the plus side it's made me put a lot more effort into the org site and i really like the header changes.
