### ISSUE TITLE
Dropbox catalog missing from latest commit.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2122]
I was advised by Dropbox that github found my apikey in someone's public repository.  It was hardcoded into the catalog_dropbox class.  So I tried checking the catalog_dropbox class to see if I might have done this myself when I helped with the PR to add the feature.  I was surprised that the catalog is missing from the latest commit.  Was it removed on purpose?

**Comment by kuzi-moto** [comment]
Yes, it was removed as part of pull #1931 when develop was updated to version 4. From the changelog:

* Remove plex, seafile, dropbox, googleplus plugins

Although I believe seafile was then later added back in.

**Comment by wagnered** [comment]
Why??  Was it discussed?  People use Dropbox to share files on a temporary or long term basis. The catalog worked quite well in ampache's earlier version.





-------- Original message --------
Subject: Re: [ampache/ampache] Dropbox catalog missing from latest commit. (#2122)

**Comment by kuzi-moto** [comment]
Hmm, I don't really remember much discussion nor why it was removed. @lachlan-00 should be around soon to shed some light on this.

**Comment by lachlan-00** [comment]
This was a holdover from when I forked at the start of the year where anything proprietary-related was taken out.

I kept it out to actually see if there was any interest in these plugins.

seafile was restored and I can put Dropbox back but it hasn't actually been mentioned until now.

**Comment by wagnered** [comment]
It's been almost a year since the latest release 3.9.0.  Most users only update with the release version. So they wouldn't be aware of the change. And I think most users don't care about using Ampache for financial gains. 

Are you sure that the code for the Catalog_dropbox is classified as proprietory?  The person who did the PR indicated he mostly copied the code from one of the other catalogs.  I don't think we are incorporating a proprietory dropbox API in this code.  I think most proprietory code should be in lib/vendor or lib/components after composer is run.  This is where all truly third-party code should reside.  If proprietory code exists in other locations, then ampache is poorly designed in my opinion.

Also, I think composer can be used via scripts to give the installer the option to include proprietory APIs. Opting out on an API will mean opting out on the feature it supplies of course.

It's been almost a year since last release.  What are you waiting for? ; ' >



-------- Original message --------
Subject: Re: [ampache/ampache] Dropbox catalog missing from latest commit. (#2122)

**Comment by lachlan-00** [comment]
I meant that I removed it because Dropbox is proprietary. I'm happy to put it back as it doesn't really affect much and it works.

The API and api-documentation are my last things to finish before 4. I'll need your help when we get to that!

There are a few methods to create and then I need to work out the arrays for searching/advanced_search and document the last missing parameters

**Comment by kuzi-moto** [comment]
If the Dropbox code works and isn't filled with bugs, I think it makes sense to keep. No need to remove working features from Ampache I would think.

**Comment by wagnered** [comment]
IMHO I don't think we should as builders/debuggers should be deciding what services the user has access to.  As long as we conform to the various agreements, no catalog or plug-in should be removed.  If you want to make Ampache 100% open source with the code then be my guest remove the feature and the proprietory API that provides it.  Or find an alternate API

**Comment by wagnered** [comment]
IMHO I don't think we should as builders/debuggers should be deciding what services the user has access to.  As long as we conform to the various agreements, no catalog or plug-in should be removed.  If you want to make Ampache 100% open source with the code then be my guest remove the feature and the proprietory API that provides it.  Or find an alternate API

**Comment by wagnered** [comment]
IMHO I don't think we should as builders/debuggers should be deciding what services the user has access to.  As long as we conform to the various agreements, no catalog or plug-in should be removed.  If you want to make Ampache 100% open source with the code then be my guest remove the feature and the proprietory API that provides it.  Or find an alternate API

**Comment by wagnered** [comment]
IMHO who are we as designers the ones who determine what service a user can access.  Let him or her decide to pay any fee or not for that service.  I think that all catalogs and plug-ins be re-installed if their code doesn't break any agreements if ampache is commercialized.

If you want to remove features that are provided by proprietory or limited open source license, I suggest looking for an alternate third- party API that can provide the feature.

The buttons and screen on this Samsung are so small I guess I accidently closed tis issue.  Also I still don't see an edit or delete button on this screen so sorry about the accidental duplication

**Comment by lachlan-00** [comment]
don't worry about it. i've changed direction a lot compared to march. it's back in edge will just have to test at home tonight before i put it back (composer.lock and json need updating.)

**Comment by AshotN** [comment]
I think we should split off plugins into separate repositories. There are a lot of plugins right now which I think should be split away from the main Ampache repo. In that case any proprietary stuff can be kept separate from the main project and will help keep the code base cleaner.

**Comment by lachlan-00** [comment]
That would be a future issue as every owner of the organisation is usually mia so core pugins will stay in the main base for a while yet.

but pulling plugins from github would be a pretty sweet feature. being able to load them and get fresh ones without having to update ampache like the autoupdate feature.

**Comment by AshotN** [comment]
Ok so we can put that on hold for a future release, hopefully someone can make you an owner and we can get that done. This repo has way to many files and it's a hassle dealing with that, we should separate core functionality as much as possible so it's easier to work on.

**Comment by wagnered** [comment]
I'm sure @afterster has his own modules installed via composer and are located on github.

Also, the modules can be stored on packagist.org which is the default location it grabs the modules from.  Composer is quite powerful.

-------- Original message --------
Subject: Re: [ampache/ampache] Dropbox catalog missing from latest commit. (#2122)

**Comment by lachlan-00** [comment]
i forgot about that.
we use composer for the php-echonest-api from his gitrepo

**Comment by lachlan-00** [comment]
speaking of; https://github.com/RobLoach/component-installer is depreciated while we're at it

**Comment by lachlan-00** [comment]
dropbox modules are back in develop now.

**Comment by wagnered** [comment]
This could be another discussion..


I don't like having JavaScript files here and there throughout the file structure.  I was always having a hard time locating a particular file when debugging Ampache.  Laravel depends on npm to install files listed in a package.json file in a default folder /node_modules.  Modems and npm need to be installed, but I knew where all the JavaScript files were.

Also the RobLoach/component-installer could be removed in the release version.

Ps:  As for [Laravel](https://laravel.com/docs/6.x), it would make Ampache very powerful with all it's built-in tools: mailer, Json, broadcasting, multiple databases, artisan, a very powerful command line tool which can act as a server.  For me, there was a steep learning curve, but what I built so far might help make learning Laravel easier for others.



-------- Original message --------
Subject: Re: [ampache/ampache] Dropbox catalog missing from latest commit. (#2122)

**Comment by wagnered** [comment]
You should get to the api-documentatiom ASAP as I don't know how much longer I can continue contributing my time.




-------- Original message --------
Subject: Re: [ampache/ampache] Dropbox catalog missing from latest commit. (#2122)

**Comment by lachlan-00** [comment]
That's a good incentive then!
I'm feature complete and have been documenting as I go so it's not a huge job.

**Comment by AshotN** [comment]
I think we should move the API doc off the wiki. It's not really pretty using the wiki.

**Comment by lachlan-00** [comment]
That will have to happen at some point. Markdown doesn't flow well for this type of content

It can go in the website and even in Ampache itself in the admin tab

**Comment by AshotN** [comment]
Well until we decide how the API should move forward in respect to the JSON implementation, you can assign me to issues you need help with. I've been in the open source mood so I'm down to help.

**Comment by lachlan-00** [comment]
closing as discussion has moved on from here and dropbox catalog is in develop
