### ISSUE TITLE
XML API advanced_search on Favorite always returns 0 matches

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2125]
Hi,

Hope you doing well. I'm looking to add an Ampache plugin to my pet project, so I'm messing around the XML API in devel branch.

Hope it's OK to report/ask here.

Example:

The following call
/server/xml.server.php?action=advanced_search&auth=<auth_code>&type=song&rule_1=favorite&rule_1_input=%&rule_1_operator=contain
produces this SQL
SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `user_flag` ON `song`.`id`=`user_flag`.`object_id`  WHERE `song`.`title`  '%' AND `user_flag`.`user` = 0 AND `user_flag`.`object_type` = 'song'

First question is operator missing for song.title. Am I wrong to use contain as operator in the request?
Second is user being 0. This seems to be an issue with all APIs, not only advanced_search. Even on the "Recently Played" page, songs played through the API have user name "Ampache User".

Thank you in advance
Peter

**Comment by lachlan-00** [comment]
I'll have a look tonight. i'm tying to finish this version of the api off this week.

**Comment by lachlan-00** [comment]
@AshotN do you know much about the search rules?

**Comment by lachlan-00** [comment]
I think i can fix the issue with the user being 0. What's probably happening is that the search rules are relying on globals and it needs to be passed from the api call.

**Comment by AshotN** [comment]
Frankly I don’t. But if you like I can take a look at the API and see if I can figure out the problems.

**Comment by lachlan-00** [comment]
Just from looking it looks like the advanced_search api call is using the same format as the search pages. I'm willing to bet that the search.class is relying on the global being filled which won't happen when no one is in the ui.
![image](https://user-images.githubusercontent.com/1305249/68094993-62d1c980-fef1-11e9-9441-6705d01e5742.png)

But feel free to ignore this one @AshotN and i'll fix it tonight. @4phun you have been really helpful with this issue as the advanced search was something i had yet to understand so thank you!

**Comment by 4phun** [comment]
Hi @lachlan-00 

As far as the user id goes, I think you'd win that bet:

```
search.class.php

private function song_to_sql()
{
    $sql_logic_operator = $this->logic_operator;
    $userid             = Core::get_global('user')->id;
```
This probably correct on the UI but not through the API.

Just my 2 cents

**Comment by 4phun** [comment]
@lachlan-00 I'm glad if my question was helpful. In my humble opinion you guys doing great work with Ampache. Appreciate it.

**Comment by AshotN** [comment]
Oddly I don't have advanced_search in my fork of the API. Just noticed that trying to find it

**Comment by lachlan-00** [comment]
your operator should be containS as well. that's why nothing came up but i should default that to LIKE instead

**Comment by lachlan-00** [comment]
wait, i read the wrong line. ignore!

**Comment by lachlan-00** [comment]
found the issue.
```
foreach ($this->rules as $rule) {
```
$this->rules isn't being set.
i've pulled the user back into the construct so i'll do the same for rules

**Comment by lachlan-00** [comment]
This is because your operator is actually meant to be an int (not your fault this stuff wasn't documented well)

```
/server/xml.server.php?action=advanced_search&auth=<auth>&type=song&rule_1=favorite&rule_1_operator=0&rule_1_input=%
```

**Comment by lachlan-00** [comment]
rule_1

rating
favorite
myrating
artistrating
albumrating
played_times
license
rating
myrating
rating
myrating

rule_1_input

text
integer
etc

rule_1_operator

0 = contains
1 = does not contain
2 = starts with
3 = ends with
4 = is
5 = sounds like
6 = does not sound like

@wagnered this was one of the last things i needed to document. i'll be ready to work on releasing v4 after this is on the wiki!

**Comment by 4phun** [comment]
I see it's working in edge branch now. Cool! Thanks a ton!

**Comment by lachlan-00** [comment]
You've really helped me put this method to paper so thanks for your report.

I'll be working on your favourite flag as well but i'm not going to guarantee it for the initial api 4 release.

**Comment by 4phun** [comment]
All cool.

I was thinkin' about some more XML API methods... but I don't want to increase you workload. Would you accept contribution?

**Comment by lachlan-00** [comment]
Always! My focus this run was on extending the API to try and match the abilities of the subsonic backend while filling in the things that were missing.

**Comment by 4phun** [comment]
Sounds great. What do I do? Can I create a new branch from edge, do my thing, and we can discuss via pull request? Or do you have a preferred workflow? Just let me know.

**Comment by kuzi-moto** [comment]
> Can I create a new branch from edge, do my thing, and we can discuss via pull request?

Yep, that's typically the best way to do it.

**Comment by lachlan-00** [comment]
@kuzi-moto is right, my current flow has been to use edge for development first. make/break, then push back into develop. squashing/renameing commits to make the tree a bit better.

Just be aware you may have to do resets/rebases as i will make changes to the commits from there before pushing to develop. i very much treat edge as totally disposable

**Comment by 4phun** [comment]
OK sounds great, that's what I'll do. I'm guessing it'll be a week or two before I'll have anything to show, as I usually do the hobby stuff on the weekends.

**Comment by lachlan-00** [comment]
advanced search is good in develop now
