### ISSUE TITLE
XML API song data to contain Favorite

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2126]
Hi,

I'd like to add this feature request, that song XML data to contain a Favorite boolean flag.

Thank you

**Comment by lachlan-00** [comment]
adding flagged should be simple enough.

This would go into artist, album as well as song.

**Comment by lachlan-00** [comment]
@AshotN the advanced search is the most confusing api call. it would be good if you could have a look at this one too.

**Comment by lachlan-00** [comment]
I think this should actually be part of the format method for song/artist/album

So we could then get the bool/int for it using $song->flag

It would have a few applications outside the api at least as well

**Comment by 4phun** [comment]
Not sure if this means anything in this context, but the web UI's song list
already has this column included.

**Comment by lachlan-00** [comment]
Most of the code requests it on demand but if we put it in at format time it should ideally speed this up.

**Comment by lachlan-00** [comment]
done in edge

1 for yes, 0 for no
```
<flag>1</flag>
```

**Comment by 4phun** [comment]
Cool!
