### ISSUE TITLE
Pull #2137 breaks Ampache

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2139]
### Describe the bug

When viewing Ampache homepage, it just shows sidebar and header. I believe this is due to the latest commit from pull #2137. Specifically, in `lib/class/song_preview.class.php`, line 211 was changed from `public function format($details = true)` to `public function format()`. Reverting this change fixes Ampache. I would open a pull request to fix it, but I don't know why the change was made so maybe something else needs to be fixed.

### To reproduce

1. Go to homepage

### Expected behavior

Show albums of the moment, recently played, etc.

### Screenshots

![image](https://user-images.githubusercontent.com/17068090/68488901-ab4bf880-020b-11ea-8902-84686c5d541a.png)

## Environment

* Ampache version: Latest develop

## Logs

No Ampache logs, Nginx log:

`2019/11/08 09:33:46 [error] 2749835#2749835: *2454 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Song_Preview::format() must be compatible with playable_item::format($details = true) in /srv/www/ampache/lib/class/song_preview.class.php on line 23" while reading response header from upstream, client: 206.55.176.98, server: ampachedomain.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "ampachedomain.com"`

**Comment by NatureMuncher** [comment]
Also cannot play anything. Pressing Play causes a brief `loading...` to appear but the player never appears or begins. Initally I was able to bounce Apache and got it working but now nothing. Guessing it may be related to this. I updated this morning to `63e6d1f8d7f266a403d5945749b2c36fffccf2bb`

**Comment by NatureMuncher** [comment]
> Reverting this change fixes Ampache.

I updated via the GUI and am unfamiliar with git. Is there a `git revert xxxx` command I can run to undo the update?

**Comment by kuzi-moto** [comment]
@NatureMuncher running this command in your Ampache directory should do the trick: `git reset --hard HEAD~1`

**Comment by NatureMuncher** [comment]
Thanks so much! I had to run it twice since the problem still existed:
```
git reset --hard HEAD~1
HEAD is now at ce35c23 scrutinizer (#2136)
git reset --hard HEAD~1
HEAD is now at edc5d40 Update .travis.yml
```

**Comment by kuzi-moto** [comment]
Perfect! I'm sure @lachlan-00 will be taking a look at this later today and will fix it.

**Comment by lachlan-00** [comment]
For preview the details are dead code in format but there must be something pushing to it. Will get that in a few hours today

**Comment by lachlan-00** [comment]
for the moment i'll just revert that and look at the why later.
