### ISSUE TITLE
get_random broken in album.class.php when $with_art = true

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2142]
https://github.com/ampache/ampache/blob/develop/lib/class/album.class.php#L1156

If $with_art = true, it returns 1. 

I looked through code, there is no use of the function where $with_art is set to true. 

If someone is willing to test and see if I'm just doing something wrong.

**Comment by lachlan-00** [comment]
with_art will join the binary images from the art table.

I changed some queries to force with art and don't get any errors.
![image](https://user-images.githubusercontent.com/1305249/68523703-65288f00-0308-11ea-9582-875fa22d20aa.png)

This is the query generated with_art true
```
SELECT DISTINCT `album`.`id` FROM `album` LEFT JOIN `song` ON `song`.`album` = `album`.`id` LEFT JOIN `catalog` ON `catalog`.`id` = `song`.`catalog` LEFT JOIN `image` ON (`image`.`object_type` = 'album' AND `image`.`object_id` = `album`.`id`) WHERE `catalog`.`enabled` = '1' AND `image`.`id` IS NOT NULL  AND `album`.`id` NOT IN (SELECT `object_id` FROM `rating` WHERE `rating`.`object_type` = 'album' AND `rating`.`rating` <=1 AND `rating`.`user` = 2)ORDER BY RAND() LIMIT 5```

**Comment by AshotN** [comment]
I'll have to check it again, I was running into issues with it prior.

**Comment by lachlan-00** [comment]
this one will have changed a lot over the years and should be fixed
