### ISSUE TITLE
[Feature Request] PHP 7 upgrade

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2143]
Is there any reason Ampache does not seem to have a goal of upgrading to PHP 7. Would be nice if we could write new code without having to worry about compatibility with PHP 5.6. Some new features like [null coalescing](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)  would be really useful on making the API cleaner.

**Comment by wagnered** [comment]
Yes, 5.6 is no longer supported, therefore we no longer need to code for it. 7.0 is no longer supported, but the new features should be upwardly compatable.  Even so, Ampache releases should always be tested with the latest php version as those who sell webspace tend to update often.

-------- Original message --------
Subject: [ampache/ampache] [Feature Request] PHP 7 upgrade (#2143)

**Comment by lachlan-00** [comment]
7.2 and 7.3 are the only active supported versions and i code against 7.3 so i don't see why we shouldn't drop the older ones.

**Comment by lachlan-00** [comment]
7.2 introduced changes incompatible with 7.0/1 so lets bump it up to 7.2 and 7.3

**Comment by AshotN** [comment]
I was presuming based on the README 

> PHP 5.6 or greater

What version is officially targeted. Because composer is also set to 5.6, which is why PHPStorm would complained if I used `??`

**Comment by lachlan-00** [comment]
I have just upped it to 7.1 in edge and am testing it now.

**Comment by lachlan-00** [comment]
Php 7.1-7.3 as official supported versions.

No issues using those and will maintain security supported versions
