### ISSUE TITLE
[Feature Request] implement album_songs into album

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2147]
The API right now has `albums` and `album_songs`. Instead of needed two API calls, could we add a boolean flag to `albums` to include songs in the output. I don't think this should require two API calls.

**Comment by lachlan-00** [comment]
A lot of the other calls have include so we could add include=songs to do just that.

**Comment by AshotN** [comment]
I'd implement it, but it's kind of a mess for me to create a pull for develop because my code is mixed with the JSON API in it. On my client I'm making two database calls, which is kind of annoying but I just wanna get a working prototype to show case here quickly.

**Comment by lachlan-00** [comment]
I can get this done sometime quickly tonight/tomorrow. Its a pretty reasonable change to make for artists, albums, etc

**Comment by lachlan-00** [comment]
It actually looks like it's already meant to do it

album and albums both have an include filter so i'll double check why it doesn't return anything extra
```
echo XML_Data::albums($albums, $input['include'], true, $user->id);
```

**Comment by lachlan-00** [comment]
It is looking for an array but not actually making one. sending in a fix now.

Album, albums will return songs with include=songs
