### ISSUE TITLE
API search_songs filter optional

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2153]
https://github.com/ampache/ampache/wiki/XML-methods#search_songs says filter is not optional, but if you don't specify one the server just returns all the songs. Should the server not return an error with the lack of a filter, or the wiki should be changed to filter being optional. 

But searching for all songs does take some time for the server to respond.

**Comment by lachlan-00** [comment]
I think we should force an item like a '%' at the very least.

**Comment by lachlan-00** [comment]
a lot of these older functions don't check for their expected parameters.

I'll do a run for mandatory parameters and fix them up.
```

        if (!self::check_parameter($input, array('filter'))) {
            debug_event('api.class', "'filter' required on stats function call.", 2);
            echo XML_Data::error('401', T_("Missing mandatory parameter") . " 'filter'");

            return false;
        }
```

**Comment by AshotN** [comment]
The wiki for Stats also says filter is not optional, but states that if filter is null it'll get random items. So wouldn't that make Stats filter input optional?

**Comment by lachlan-00** [comment]
It's been modified from the previous version which allowed null but it might be the time to break it and force a type

**Comment by lachlan-00** [comment]
not optional now
