### ISSUE TITLE
config/ampache.cfg.php exists? Error

### ISSUE THREAD

**Issue by marklinmax** [ampache/ampache#2171]
## Description
I got the Ampache source from [here](https://github.com/ampache/ampache/releases/download/3.9.0/ampache-3.9.0_all.zip) and I can reach the installation Step 2 but here I get the **"config/ampache.cfg.php exists?"** error.
I checked the permissions and ampache should be able to write in the config folder, as it already did to write the .htaccess file.

I already searched the internet and this is apparently a common issue, but couldn't found any workaround that solved the problem.

### Screenshots

![Ampache_config_screenshot](https://user-images.githubusercontent.com/27149268/69006614-a684f400-0931-11ea-84d7-3f71efc430b4.png)

## Environment

* Ampache 3.9.0
* Apache 2.4.41
* Ubuntu 19.10

Server is running on localhost

## Logs
I also get those two errors in a red rectangle around the top of the page:
Error writing config file
Error: Config files not found or unreadable

**Comment by lachlan-00** [comment]
Did you try write? This section is to either dowload the file and write it manually or try writing it using the web user

**Comment by marklinmax** [comment]
Same error when clicking on "write" or "download".
"Error: Config files not found or unreadable"

**Comment by lachlan-00** [comment]
Write and recheck?
Download means you have to manually put the config file in the folder

**Comment by marklinmax** [comment]
I also did this, but with no success...
I finally installed it with docker, which worked perfectly. I should have looked for a docker container image first, it would have saved a lot of my time!
Anyway, thank you for your help!

**Comment by lachlan-00** [comment]
I only just recently got the docker image rebuilding. so lucky break there!

**Comment by i21** [comment]
Just for the record:
I had the same issue, i solved by creating a new user with password in my mysql with all privileges.
Windows 10 with xampp.
