### ISSUE TITLE
playlist_generate artist and album

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2193]
Hi,

Once again, thank you for including my suggestion in the API.

Seems like there is a mishap between album id and album name:

/server/xml.server.php?action=playlist_generate&auth=xxx&limit=5&album=47
returns 0 results even though I checked in the database album id 47 does exist

/server/xml.server.php?action=playlist_generate&auth=xxx&limit=5&album=Nero
returns 5 random results from entire collection, filter not in effect

and most interestingly
/server/xml.server.php?action=playlist_generate&auth=xxx&limit=5&album=1984
correctly returns 5 results from the album named 1984

Search is being done on album name instead of album id, which is perfectly fine. Only problem is input validation expects integer for album.

A simple solution:

```
- $album = (int) $input['album'];
- if ((array_key_exists('album', $input)) && ($album > 0)) {
+ if (array_key_exists('album', $input)) {
      // set rule
      $array['rule_' . $rule_count]               = 'album';
-     $array['rule_' . $rule_count . '_input']    = $album;
+     $array['rule_' . $rule_count . '_input']    = $input['album'];
      $array['rule_' . $rule_count . '_operator'] = 0;
      $rule_count++;
  }
```
Same behavior observed for artist.

Thank you

**Comment by lachlan-00** [comment]
you're right, album is a text search. i want it to be album id so i'l fix it up tomorrow.
this is basically the last thing before release!

**Comment by lachlan-00** [comment]
Searching done with the id is corrected to convert to full name and search for exact match.

Will test and confirm before release tonight.

**Comment by lachlan-00** [comment]
Fixed for artist and album. Will not include the rules if it can't verify the object id with the input.

Now to release!

**Comment by 4phun** [comment]
Hi,

Commenting on an already closed issue, I don't want to start a new one without discussing it first.

I'm testing this and everything's fine. However, I have a question: "recent" and "forgotten" modes seems to be playing songs that were already played at least once. This obvious with "recent", but with "forgotten" I think songs that were never played are the most forgotten ones. What do you guys think about this?

**Comment by lachlan-00** [comment]
I think of it in the context of recently played and not recently played.

To me unplayed is separate but it could be added as another mode/flag.

Random mode plus unplayed flag?

**Comment by 4phun** [comment]
That sounds great to me.

**Comment by 4phun** [comment]
Take that back. Let me explain. One sec.

**Comment by 4phun** [comment]
Example my pet project at https://launchpad.net/waver (already incorporated the new Ampache API). This plays tracks automatically, without requiring user to select/create a playlist. The aim is to play randomly, without repetition until all tracks are played, then start over. There are some fine tunes to this process, for example "loved" a.k.a. flagged songs come into rotation more frequently, but you get the point.

So if you start out with fresh collection. All songs never played at that point. Then as you go through the songs, more and more will be played at least once. Then eventually you reach the point where all songs are played at least once. At that point unplayed flag becomes useless.

I know this isn't an ordinary situation from Apmache's point of view, and I could create workarounds in my client to achieve my goal. Just want to keep API calls as low as possible.

**Comment by lachlan-00** [comment]
Let's think about it more in a new issue.
