### ISSUE TITLE
playlist_remove_song always returns 'success'

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2198]
The method doesn't check if the input is valid, so as long as the `has_access` call is true the API returns success.

**Comment by AshotN** [comment]
Matter of fact I can't get the method to even work. `playlist_add_song` works for me, but not `playlist_remove_song`

**Comment by lachlan-00** [comment]
It has the option of song id or number in the list. Will test out

**Comment by lachlan-00** [comment]
Found some issues to fix. Just have to make it warm correctly now

**Comment by lachlan-00** [comment]
the quesry was wrong and the checks needed updates. fixed in develop.

Have a quick look to find anything else as i'm going to have to release this to master tonight

**Comment by lachlan-00** [comment]
fixed in develop. will go into master tonight

**Comment by AshotN** [comment]
I can't get the method to work :( 

matter of fact the XML API is giving me a access denied error. Looking through the code line 82 in `xml.server.php`: `$GLOBALS['user'] = User::get_from_apikey($_REQUEST['auth']);
`
is returning NULL

**Comment by lachlan-00** [comment]
Tested this morning okay. In the API access::check is sending the uid as well so I'll check again

**Comment by lachlan-00** [comment]
tested again okay, but that line is probably causing a lot more issues than just that.

**Comment by lachlan-00** [comment]
I know what that issue is now!
API key isn't what that should be looking for it's a session key

Ampache used to rely on the API being static

**Comment by AshotN** [comment]
Funny enough my JSON version still worked, cause it wasn't kept up with the XML updates. So I never noticed an issue. Till I tried testing the playlist remove song method in XML and got a different error. Life can be cruel

**Comment by lachlan-00** [comment]
I'm not a fan of my daily master releases so far but it's been good to have the renewed focus.

Phpunit and static typing are my big todo

**Comment by AshotN** [comment]
OK after merging your changes with my JSON it works! The React client now has playlist add and remove working.

**Comment by lachlan-00** [comment]
Awesome. That actually explains a lot of things I couldn't before
