### ISSUE TITLE
Blank page on ampache with php error on log

### ISSUE THREAD

**Issue by peterpt** [ampache/ampache#2199]
Dist : linux Debian

webserver : Apache/2.4.25 (Debian)
ampache release : Latest zip file with all dependencies included

After going to https://servername/ampache/

i get a blank page , and after looking into log errors i get :

 PHP Fatal error:  Call to undefined function T() in /opt/ampache/templates/show_test.inc.php on line 28

I am a bit lost here , since this is a php error and it is out of my scope .

**Comment by kuzi-moto** [comment]
Oops, looks like I made a typo. I'll submit a pull to fix that, but if you want to get Ampache working now, you can simply open `/opt/ampache/templates/show_test.inc.php` and change line 28 from this:

```php
<title><?php echo T_("Ampache") . " -- " . T("Debug Page"); ?></title>
```

to this:

```php
<title><?php echo T_("Ampache") . " -- " . T_("Debug Page"); ?></title>
```

Notice, the `T("Debug Page");` is missing an underscore after the "T".

**Comment by peterpt** [comment]
nice detection of the error .
Worked perfectly , thank you
