### ISSUE TITLE
Top tracks

### ISSUE THREAD

**Issue by SUTJael** [ampache/ampache#220]
Would be great to add a top track panel like deezer for each artist (http://www.lastfm.fr/api/show/artist.getTopTracks). We could also think about a global "Top tracks" section based on top tracks per country (http://www.lastfm.fr/charts/tracks/top).

**Comment by LesKent** [comment]
I think such a feature would be great for music discovery. Plex's music UI has this feature and I find it really useful and would love to see this in Ampache.

**Comment by lachlan-00** [comment]
putting this in the ui would be good to do still. i use it in subsonic all the time so will look at it again
