### ISSUE TITLE
Changing playback type doesn't accept all modes

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2203]
### Describe the bug

When changing playback type to Democratic or Localplay update preferences sets playback type to web player. Setting to stream works and web player are the only two options that are set correctly.

### To reproduce

1. Go to 'preferences/streaming or select the drop down on any page'
2. Change playback type Democratic or localplay from the dropdown
3. Click on 'Update Preferences'
4. Playback type will go back to web player.

### Expected behavior

The selected option should be the option wanted.

### Screenshots

![image](https://user-images.githubusercontent.com/4076671/69584147-7630fb80-0faa-11ea-8d07-8c5383005762.png)
![image](https://user-images.githubusercontent.com/4076671/69584194-995bab00-0faa-11ea-8573-b7c5fa0fa877.png)
## Environment

* Ampache version: c9bd23eed31af622c62bb00b56ede311f036ce1d
* Web server + version: Apache 2.4.41, PHP 7.3.10-1+b1
* Server operating system: Debian 11
* Client operating system: Debian 11

### Client type

* Web (Firefox)
* Ampache

## Logs

Nothing specific in the log.

**Comment by lachlan-00** [comment]
from the preferences page only and not the top right list?

**Comment by stebe** [comment]
In preferences and in server config/streaming. Top list is working.

**Comment by lachlan-00** [comment]
okay, that's good. must be either in the JS/template for loading or the preferences class. the first thing to check is that the DB is saving the item but not reloading the preference.

If you can't do that i'll be able to after work today.

**Comment by lachlan-00** [comment]
it's a visual problem. the selection is saved but there seems to be an error loading the list.

**Comment by stebe** [comment]
You are faster than me. I can confirm that the database is updated.  Also the top right list changes correctly.

**Comment by lachlan-00** [comment]
I've got the list display fixed. the lib/preferences.php was double selecting and falling back to webplayer.

I see that preferences.php does some odd things with the action/post but i'm just working on that now.

**Comment by lachlan-00** [comment]
okay this is in develop. The method which preferences are loaded has a lot of overlap and doesn't like being loaded twice but this particular error is now fixed.

**Comment by lachlan-00** [comment]
merged in 4.0.3
