### ISSUE TITLE
Ampache 4.0.2 Symlink to 'phpunit' i.e /lib/vendor/php-tmdb/api/examples/phpunit is broken

### ISSUE THREAD

**Issue by prbt2016** [ampache/ampache#2205]
Hello,

When i extracted ampache-4.0.2_all.zip, I found that symlink to 'phpunit' i.e '/lib/vendor/php-tmdb/api/examples/phpunit' is broken. It points to /lib/vendor/php-tmdb/api/build/coverage. But there is no folder 'coverage' in /lib/vendor/php-tmdb/api/build/.

Could you please fix this?.

**Comment by lachlan-00** [comment]
This package pulls from

**Comment by lachlan-00** [comment]
this is a package pulled by composer, it should probably be raised as an issue on their repo as i just run composer install to make the deployment easier so icanhave a look for broken symlinks next time i build

**Comment by lachlan-00** [comment]
still part of 4.0.3 but will look at including it manually

**Comment by prbt2016** [comment]
In next version 4.0.4? . Does the symlink break any crucial functionality?.

**Comment by lachlan-00** [comment]
Nope, it won't affect any ampache operation. It doesn't run any tests on vendor packages to function

**Comment by lachlan-00** [comment]
I'm making a new release today and i'll start searching for broken links when packaging

**Comment by lachlan-00** [comment]
in my release process i remove all dead symlinks now.
it would be good if the packagers upstream either corrected it or removed it but it's not needed for us.
