### ISSUE TITLE
PHP Version support

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2206]
### Describe the bug

I have php 5.4.16 when i try to install v4.0.2 the check of Version of PHP says that is correct but I read on the changelog that the PHP required now is 7.1+, I supposed that the check page is wrong right?

## Environment

* Ampache version: 4.0.2
* Web server + version: apache + php 5.4.16
* Server operating system: CentOS 7.7
* Client operating system:

**Comment by kuzi-moto** [comment]
That is not incorrect. Ampache now requires PHP 7.1.

I don't remember specific reasons, but 5.6 has been unsupported for almost a year at this point.

**Comment by kuzi-moto** [comment]
I think you're right. The check page should be looking for 7.1.

**Comment by lachlan-00** [comment]
I've raised that in develop now
