### ISSUE TITLE
Api playlists not checking public vs private correctly

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2208]
### Describe the bug

Im testing the API the Method "playlists" returns a list of the smart playlists instead of the list of the "normal" playlists (like in previouse versions of ampache)

Thanks
## Environment

* Ampache version: 4.0.2
* Web server + version: apache + php 7.3
* Server operating system: centos 7.7
* Client operating system:

**Comment by lachlan-00** [comment]
It should be returning both?

**Comment by manuelglez86** [comment]
No, it should show Normal Playlists only

**Comment by lachlan-00** [comment]
I've joined them into playlists as there was no way to retrieve them before and this follows how playlists are served to subsonic.

The smartlist have a prefix when added from the api so they can be excluded by the client but we could also put a flag on there for normal lists only

**Comment by manuelglez86** [comment]
But the issue is that Normal playlists doesnt show at all on the API, the xml file just show smart playlists

and also I can exclude smart playlist when i used the methos playlists?

**Comment by manuelglez86** [comment]
Ohh I found the bug, the Playlists Method only shows public Playlists.

It should also show my own private Playlists, if Im a normal User.

And all playlists (private and public) if Im an administrator

**Comment by lachlan-00** [comment]
Ah, that's good. I'll check how the lists are shown in has_access. They must not get the user correctly to show who owns it

**Comment by lachlan-00** [comment]
Fixed in develop. I think subsonic does the same thing so I'll test that before merging to master.

Lots of little fixes to go in

**Comment by lachlan-00** [comment]
merged as part of 4.0.3.

**Comment by manuelglez86** [comment]
thank you i will continue testing the API
