### ISSUE TITLE
Question about Year

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2209]
### Describe the bug

I have some compilations which tracks are from diferent years (This aren´t albums, are songs that I grouped in the form of an album), The songs have the same album name, the same album artist (Various Artists in this case) but now it appears that Year affects the creation of albums in Ampache.

So ampache splits the same album into several albums based on the Year of each song file as you can see on the attached file
![photo](https://user-images.githubusercontent.com/19354668/69759874-b0280c00-1128-11ea-9ddf-3949f3e6bf58.png)

This is a normal behavior now?

## Environment

* Ampache version: 4.0.2
* Web server + version: apache + php 7.3
* Server operating system: Centos 7.7
* Client operating system:

### Client type

* Web
* Ampache

**Comment by lachlan-00** [comment]
When grouped the album's year is used to separate rereleased albums with the same name.
So when a new edition of an old album comes out it's treated as a different release.

Grouping is done by name, release type, album artist, album mbid and year.

**Comment by lachlan-00** [comment]
If you set a custom mbid for the album that should group them too

**Comment by manuelglez86** [comment]
If theres no way to desactivate the year grouping, it will be easier for me to eliminate the year in songs that I put on a custom album as I can do that in bulk

**Comment by lachlan-00** [comment]
The year of the album is considered part of the release/album so that's probably the best way.
There isn't a song field for year data at least in the way you've grouped them.

**Comment by manuelglez86** [comment]
Yes I undestand your point, I´ll just edit the year tags of some compilations that we have in order to get it grouped, its not a big deal.

Thanks.

**Comment by lachlan-00** [comment]
It's good to talk these things out. you've made some really good insights this week.
