### ISSUE TITLE
Subsonic API - wrong username or password

### ISSUE THREAD

**Issue by brokenphone** [ampache/ampache#2210]
## Description
Trying to access the Subsonic API from an Android app results in the error 'wrong username or password'.

### Describe the bug
Since updating to 4.0.2 from 3.9.0 I am unable to access my catalog from Android apps using the Subsonic API (I have not tested with any other clients). Upon entering the same username and password as my admin user, I get the response 'wrong username or password'. The credentials are correct and I can use them to access the WebUI. Tested on Ultrasonic and DSub.

I have also tried adding another user but the result is the same.

## Environment

* Ampache version: 4.0.2
* Web server + version: apache2.4
* Server operating system: Arch ARM
* Client operating system: Android
* Passed all install.php checks: Yes

### Client type

* SubSonic

## Settings
All settings are default and directions in the API wiki page have been checked. 'Use Subsonic backend' is set to 'Yes'.

Please let me know if there is anything else I can provide and I will be happy to do so.

**Comment by brokenphone** [comment]
Right after posting and double checking everything, I realise I needed to `Enable support for LDAP users` in the app settings.

Please trash this issue and sorry for the inconvenience.

**Comment by lachlan-00** [comment]
Glad you found it

I had to choose how best to support the recent (1.13+) subsonic API and using your API key as a password will work correctly on newer clients.

This is because of how differently subsonic and Ampache handle passwords.

**Comment by mzeedijk** [comment]
> I had to choose how best to support the recent (1.13+) subsonic API and using your API key as a password will work correctly on newer clients.

Can you please add this to the Subsonic API page on the wiki: https://github.com/ampache/ampache/wiki/API
Now it says: " Only username and plaintext or hex-encoded password can be used with Ampache's Subsonic API. MD5 hash values for authentication tokens are not supported."
Should be something like: "Using your API key as a password will work correctly on newer clients that uses the v1.13+ Subsonic API. This is because of the use of a different hashing algorithm between the Ampache server and Subsonic API clients."

**Comment by lachlan-00** [comment]
that actually needs to be on it's own page, i didn't even know it was there.
I'll do that soon. good catch

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/wiki/subsonic

**Comment by Gitoffomalawn** [comment]
I had this same issue with the docker install. Managed to find a solution: https://github.com/ampache/ampache/issues/3509#issuecomment-2817352088
