### ISSUE TITLE
 4.0.2 Song Editor: not possible to Add New... Artist or Album.

### ISSUE THREAD

**Issue by Rhythm-of-Time** [ampache/ampache#2212]
## Description
In  4.0.2 Song Editor it is not possible to Add New... Artist or Album.
### Describe the bug

If there are songs with missing artist and album information / Orphaned tracks, it is not possible to create a new artist and assign the track to the artist.
### To reproduce

1. Go to 'Home / Songs'
2. Click on 'Edit Song'
3. Scroll down to 'Artist'
4. Select New Artist... from the dropdown list
5. Nothing happens - no new artist is generated
6. Same for New Album...

### Expected behavior

A new artist / album should be generated after inputting the name.
## Environment

* Ampache version: 4.02
* Web server + version: 1und1 shared host
* Server operating system: Debian GNU Linux
* Client operating system: Windows 7

### Client type

* Web
* Ampache

**Comment by manuelglez86** [comment]
Yes that right, its happening to me too, the option is there but when you selected it you cant type anything.

**Comment by lachlan-00** [comment]
Go to #2140 and we'll sort this out soon.
