### ISSUE TITLE
Delete track from playlist broken in commit dda93f34

### ISSUE THREAD

**Issue by erezschatz** [ampache/ampache#2213]
# Issue Template

## Description

The change in commit dda93f34:
```Index: lib/class/playlist.class.php
@@ -515,7 +515,7 @@
      */
     public function delete_track($object_id)
     {
-        $sql = "DELETE FROM `playlist_data` WHERE `playlist_data`.`playlist` = ? AND `playlist_data`.`id` = ? LIMIT 1";
+        $sql = "DELETE FROM `playlist_data` WHERE `playlist_data`.`playlist` = ? AND `playlist_data`.`object_id` = ? LIMIT 1";
```

But, the actual call from the web client is: 
`http://.../server/ajax.server.php?page=playlist&action=delete_track&playlist_id=1&track_id=19` where track_id refers to the id of the track in the playlist (the actual id of the song was 40 in this example).
At the moment, there is a discrepancy between what the client sends and what the server performs.

**To reproduce**

**Expected behavior**

**Screenshots**

## Environment

* Ampache version: Ampache 4.1.0-develop
* Web server + version: 
* Server operating system:
* Client operating system:

**Client type:**

* Web

**Comment by lachlan-00** [comment]
playlist_data.id is the id of the playlist, track is the track id

**Comment by lachlan-00** [comment]
delete_track is the object id of the track

delete_track_number is the track number in the playlist

**Comment by lachlan-00** [comment]
first problem i see is that the track numbers aren't lining up to the id or the order in the list.....

**Comment by lachlan-00** [comment]
got it, the api needed a new method to perform it's function. using the id for track again
