### ISSUE TITLE
Album Group Multiple Disk Bug

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2214]
### Describe the bug

I don´t know exactly what is for the option Album Group Multiple Disks but if is enabled the albums show correctly like this:
![group enabled](https://user-images.githubusercontent.com/19354668/69818899-63454380-11c3-11ea-8ef4-345509206774.png)

and when i disabled this option the albums looks like this (The total track count is 1 in all albums)

![group disabled](https://user-images.githubusercontent.com/19354668/69818895-604a5300-11c3-11ea-9a67-ad5a2b13e944.png)

## Environment

* Ampache version: 4.0.3
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache

**Comment by lachlan-00** [comment]
Looks like a tag issue.

Send me the album and artist rows for those and i'll look at how they're grouped.

**Comment by lachlan-00** [comment]
made some chenges that should fix this now in develop. will continue testing

**Comment by manuelglez86** [comment]
Now that i migrating all the albums to 4 (im using today develop), I realize that the problem happens when the album artist is diferent from the artistis of the songs like Albums of Various Artists or when the artist of the album has other singers with him on the songs like this:

![Albums_1](https://user-images.githubusercontent.com/19354668/70254455-b6327400-174a-11ea-9546-4f48303760ad.png)


![album_02](https://user-images.githubusercontent.com/19354668/70254479-bfbbdc00-174a-11ea-91d7-15bd28e6bf6d.jpg)

**Comment by kuzi-moto** [comment]
Is the album artist tag the same value on all tracks?

**Comment by manuelglez86** [comment]
Yes, it is. As you can see all the tracks are grouped in one album, is just the total track count on album view that is wrong, but if Album Group Multiple Disks is enabled again the total tracks changes to the rigth amount.

**Comment by lachlan-00** [comment]
So lets write this out with pages from the ui

Is the artist page incorrect for albums?
artists.php?action=show&artist=675

But then you go to an album and it's okay?
albums.php?action=show&album=51823

Or is it on a different page? the counts are done from sql so i'll need to work out which query is incorrect

**Comment by lachlan-00** [comment]
ahh, i see you said with group disabled

can you tell me the above for grouping enabled and disabled?

**Comment by lachlan-00** [comment]
i can see an issue with it disabled on the artist page. will check it out.
artists.php?action=show&artist=15962

**Comment by lachlan-00** [comment]
Fixed, will need to test on mysql8
![image](https://user-images.githubusercontent.com/1305249/70280422-1d602f00-1804-11ea-8c7e-22f4154f84c5.png)

![image](https://user-images.githubusercontent.com/1305249/70280453-31a42c00-1804-11ea-9314-8ea69505ca19.png)

**Comment by lachlan-00** [comment]
works on mysql8 with full group so this should be good now.

**Comment by manuelglez86** [comment]
Yes, I can confirm that. Thanks
