### ISSUE TITLE
Playlist permission bug

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2217]
### Describe the bug

If a playlist is public a non administrator user can edit and delete it. The ownership is not respected neither on the web nor the API.

### Expected behavior

Only administrators should has access to edit or delete playlists that are not owned by them

## Environment

* Ampache version: 4.0.3
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache
* API

**Comment by manuelglez86** [comment]
And also in playlist tracks on the web the button Delete does nothing

**Comment by manuelglez86** [comment]
I found something else that I think is related to this permission issue:

when using "playlist_edit" on a playlist that you dont have access on the API it retunrns success code = 1...... but the changes arent made

and on the web interface you you can clic on the Edit icon and the window appears but doennt show anything.

The buttons Delete and edit doesn´t supose to appear if you are not the owner.

**Comment by lachlan-00** [comment]
working on this to try and resolve them all.

**Comment by lachlan-00** [comment]
that's resolved in develop now.

**Comment by lachlan-00** [comment]
ui and api report correctly in develop. will be working on more issues before master.
