### ISSUE TITLE
Number of tracks/songs column

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#2219]
## Description

Various Arstist albums who have the tag "VA" as album artist shows only 1 track in track/song column

**EDIT**
After further research it seems like a total mess up and not only VA's.
Normal albums with 10 tracks shows 6, with 2 tracks shows 1 etc

![gg](https://user-images.githubusercontent.com/26334546/69865134-18056080-12a9-11ea-847b-a615fc3eda60.PNG)

## Environment

* Ampache version: 4.0.3
* Web server + version:
* Server operating system:
* Client operating system:

**Comment by lachlan-00** [comment]
It is and it's currently fixed i'm just working on some other things before i update it agian

**Comment by PsyZeus** [comment]
big thanks buddy :) also big thanks to anyone involved in this free project.
keep rocking, we love you

**Comment by PsyZeus** [comment]
big thanks buddy :) also big thanks to anyone involved in this awesome free project.
keep rocking, we love you

**Comment by lachlan-00** [comment]
I made a lot of mistakes trying to fix all this up but i'm spending the day on things at home to make sure it's working correctly

**Comment by PsyZeus** [comment]
Thanks :)
For the moment i went back to 3.0.9 until this will be fixed in the future.
I only have one issue now that i got back to 3.0.9
While i didn't changed anything in the process except the folder renaming to .old and back somehow now the album column shows as normally the album name but next to it it shows also "[Disc 1]"
I searched through interface option and everywhere but i didn't found an option to disable the disc number value.
Can i fix that somehow? Why it happened anyway lol
Thanks for any input!

**Comment by lachlan-00** [comment]
This is because multi single disk albums were updated to show 1 instead of 0.

**Comment by PsyZeus** [comment]
So is this option somewhere in the config so i can change it?
Sorry for the noob question.
How it came it changed since i didn't change anything? All i did was i switched from 4.0.4 to 3.0.9 folder.

**Comment by PsyZeus** [comment]
Crap...i'm an idiot.
I didn't hold the database from 3.0.9
I overwrite it with that from 4.0.3
Now am i stuck with showing everywhere the [Disk 1] value? or can i fix it somehow?
I'm running 3.0.9
New added albums don't show the value but can i fix the entire database?

**Comment by PsyZeus** [comment]
Crap...i'm an idiot.
I didn't hold the database from 3.0.9
I overwrite it with that from 4.0.3 when i upgraded to 4.0.4
Now am i stuck with showing everywhere the [Disk 1] value? or can i fix it somehow?
I'm running 3.0.9

EDIT
New added albums don't show the value but can i fix the entire database?

**Comment by PsyZeus** [comment]
Thanks for the info but why did you do that? I mean what's the point?
It doesn't look good to eyes and its confusing when fast reading the album titles. Also maybe  useless?(the way it was i think was perfect)
Will be that way from now on for the next ampache releases?

**Comment by lachlan-00** [comment]
In v4 the single disk albums don't show that text. it's only when the disk count is higher than 1.
When grouped it also will only show a single item without disk count.
![image](https://user-images.githubusercontent.com/1305249/70001401-f3f79700-15a8-11ea-90c8-87787dc40997.png)

The reason is that no album has a release disk of 0.
Because 3.9.0 doesn't handle the grouping or multiple disks well when you've rolled back it has shown it everywhere.

4.0.4 has all the fixes in that make it stable enough for use now.

When group multiple disks is enabled the albums are grouped by:
* prefix
* name
* album_artist
* release_type
* mbid
* year

**Comment by PsyZeus** [comment]
Big big big thanks for the explanation m8 :D 

I manage to fix the database finally back to normal by simple updating the library.(for a moment i thought that i have to insert everything from the beginning=PITA Lol )

Well, i tried 4.0.4 but i had still the issue mentioned in this thread(tracks count) so that's why i went back to 3.9.0
But now that i'm giving it a second though i think that if i had done an update of the library while on 4.0.4 the issue(tracks count) from 4.0.3 could have been fixed?! I wonder... hahaha

**Comment by lachlan-00** [comment]
It will be to do with the SQL queries but not a db problem.

This I think is simple now. We just need to see why they are not reported.

Do the albums show with the correct amount of tracks when you open them?

**Comment by lachlan-00** [comment]
When group multiple disc is enabled it groups by

Name, albumartist, releasetype, year, albummbid so the other thing to check is that your tracks all have the same tags

**Comment by PsyZeus** [comment]
> 
> 
> It will be to do with the SQL queries but not a db problem.
> 
> This I think is simple now. We just need to see why they are not reported.
> 
> Do the albums show with the correct amount of tracks when you open them?

Yes on album page (/#albums.php?action=show&album=) all tracks are there and "Item Count : " reports the correct amount, only the column(tracks) its a mess. That happens in whatever page with all the albums, /browse.php?action=album, /stats.php?action=newest etc

> 
> 
> When group multiple disc is enabled it groups by
> 
> Name, albumartist, releasetype, year, albummbid so the other thing to check is that your tracks all have the same tags

Yeah i check all the tags before i import anything new and fix them if any mistakes. Albums with more than 1cd have only 1 more tag, the "disk number" tag.

**Comment by lachlan-00** [comment]
okay good start. can you send me an album row and some song rows from the db for one that's affected?

I'll be looking at this again today.

**Comment by lachlan-00** [comment]
can you put this debug into the album class and show me the sql you get?
![image](https://user-images.githubusercontent.com/1305249/70102253-473e1800-1683-11ea-946d-67e7b6e270e4.png)

Song count is created in this function.

**Comment by PsyZeus** [comment]
I would be more than glad to help but i'm a noob and i don't know how to do all that.
If you are willing to guide me through a step by step commands then i can help for sure :) 
If it's so much effort, i hope someone else will jump in here and continue helping.
I'm on debian 10 and 10.3.18-MariaDB

**Comment by lachlan-00** [comment]
Same as me. These commands should do it.

In the MySQL server you can usually access it like this
```
mysql -u root -p ampachedatabasename
```
Then in the cli you can run some selects
```
SELECT * FROM `album` WHERE `name` = 'album name';
```
The id of that album is then used in the song table
```
SELECT * FROM `song` WHERE `album` = 123456;
```
This will just help me find something similar in my own lists to compare

**Comment by PsyZeus** [comment]
There you go m8!

![aaa](https://user-images.githubusercontent.com/26334546/70136344-7c9f3180-1694-11ea-89ce-6a0175d083e3.jpg)

**Comment by PsyZeus** [comment]
For the matter i'm on 3.0.9

**Comment by PsyZeus** [comment]
FWIW i'm on 3.0.9 now

**Comment by lachlan-00** [comment]
You can stick on 3 for now. The database structure isnt that different just the disc 0/1

What's the album row look like?

**Comment by PsyZeus** [comment]
![b](https://user-images.githubusercontent.com/26334546/70143734-0e169f80-16a5-11ea-9a97-9b6c69d73d86.PNG)

**Comment by lachlan-00** [comment]
I think this is fixed in develop
I have an album with 24 individual artists reporting as 24
![image](https://user-images.githubusercontent.com/1305249/70295731-c5412100-1833-11ea-88da-778f760b82f1.png)

If you can't recreate put replace your album.class.php with this file and show me the logs.
[album.class.php.txt](https://github.com/ampache/ampache/files/3930404/album.class.php.txt)

**Comment by PsyZeus** [comment]
Sorry for the late response but i didn't had time to test it. :(
Yeaaa that did the trick, everything seems to be ok now! So far so good..
Thanks buddy :D

**Comment by lachlan-00** [comment]
Sweet!
