### ISSUE TITLE
Private playlist of other users not shown for Admin (API)

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2220]
### Describe the bug

As I can see on the code here:
[https://github.com/ampache/ampache/blob/bdd64ba70e668ea00ef3cb6545f8d46536e530e2/lib/class/api.class.php#L299](url)

and here

[https://github.com/ampache/ampache/blob/bdd64ba70e668ea00ef3cb6545f8d46536e530e2/lib/class/api.class.php#L302](url)

the api only counts public playlists and your own playlist even if you are an Admin user (Maybe an IF there to check the access level and count all playlists) 

And the playlist Method only shows also the public and your own private playlists, the private playlists of another users are not shown for administrators.

Thanks.

## Environment

* Ampache version: develop
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* API

**Comment by lachlan-00** [comment]
Thanks I'll finish all these open things off tomorrow and update the master release

**Comment by lachlan-00** [comment]
fixed in develop. coming in once i've fully tested today

**Comment by lachlan-00** [comment]
released fixes in 4.0.4
