### ISSUE TITLE
Issues with play count

### ISSUE THREAD

**Issue by mariof1** [ampache/ampache#2222]
### To reproduce

Set a song to repeat
Only first play counts as played in all stats including SQL
Any thereafter plays are simply ignored.

### Expected behavior

All repeats should add up to a total play count
## Environment

* Ampache version: master/develop
* Web server + version: Apache 2.4
* Server operating system: Centos 7

### Client type

* Web
* SubSonic

**Comment by lachlan-00** [comment]
There's a time limit set. Length + 20. The 3rd repeat will record. 20 might be too high but it can avoid repeats where you play stop and play again quickly

**Comment by mariof1** [comment]
There's something wrong with that. So I listened to a song a few times yesterday and it counted only the first time it played. Then today morning I opened Dsub and played the song one more time and it did not show anything in last played nor did not increase its play count. However if I switched to another song and went back to the first track it counted ok but again only for the first time

**Comment by mariof1** [comment]
This is what I'm seeing in the logs each time the song starts over
`(subsonic_xml_data.class) -> API fail in function saveplayqueue-1.13.0`

**Comment by lachlan-00** [comment]
i'm going to set the last_played to just the song length -5 to alleviate this but your issue with things not recording i can't recreate.

the playqueue error isn't related to this.

**Comment by lachlan-00** [comment]
There is a good config option for subsonic called "subsonic_stream_scrobble". if you disable this setting all cache/downloads are recorded as a download.
```
; Subsonic clients all seem to ignore the download method
; This setting will not scrobble actions from stream actions.
; (This means you can sync playlists without overloading your server)
; Make sure you enable scrobbling in your client to keep recording stats!
; DEFAULT: "true"
;subsonic_stream_scrobble = "false"
```
Then as long as you have last.fm support enabled in dsub all the stats are submitted by dsub to ampache instead of when they are downloaded by the client.

These are the lines you want to look for in your log
```
2019-12-02 10:11:56 [user] (useractivity.class) -> Inserting details for Burn Your Gods - Raggedy Angry - How I Learned to Love Our Robot Overlords. 
2019-12-02 10:11:56 [user] (subsonic_api.class) -> scrobble: 52224 for user using DSub 1575245516 
```

**Comment by mariof1** [comment]
Yes I know this settings, this was actually raised by me ;). I already have this set to false.
The subsonic class log I posted earlier appears only when a song is played more than once in a row.
Anyway I updated Ampache to the latest build and the issue remains.
It does not really matter if I use web player or Dsub if a playlist is set to repeat only first play records any stats. I have checked object_count and there is no records of anything that was repeated. I literally just played a song like 10 times and only the first record shows in DB and in application.

**Comment by lachlan-00** [comment]
Hmm, I'll do the same in both and see what I can get

**Comment by lachlan-00** [comment]
I see another one in is_already_inserted. Just testing that now.

Do you get "Object already_inserted" in the logs?

**Comment by mariof1** [comment]
Yes, I am getting that too

```
2019-12-02 10:39:09 [user.name] (user.class) -> Updating stats for {song/13190} {Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko}...
2019-12-02 10:39:09 [user.name] (user.class) -> save_mediaplay...
2019-12-02 10:39:09 [user.name] (lastfm.plugin) -> Submission Successful
2019-12-02 10:39:09 [user.name] (stats.class) -> Object already_inserted {13190} 1
2019-12-02 10:39:09 [user.name] (stats.class) -> Statistics insertion ignored due to graceful delay.
2019-12-02 10:39:09 [user.name] (stats.class) -> Object already_inserted {4173} 1
2019-12-02 10:39:09 [user.name] (stats.class) -> Statistics insertion ignored due to graceful delay.
2019-12-02 10:39:09 [user.name] (stats.class) -> Object already_inserted {5126} 1
2019-12-02 10:39:09 [user.name] (stats.class) -> Statistics insertion ignored due to graceful delay.
2019-12-02 10:39:14 [user.name] (play/index) -> Stream ended at 8965427 (8965427) bytes out of 8965427
```

**Comment by lachlan-00** [comment]
Okay I've set it to time -5 in develop as well now for that

**Comment by mariof1** [comment]
Sorry for the delay on this. I did test it with every develop release from you and I have never got it right.

**Comment by lachlan-00** [comment]
I've just tested with a 40second song on repeat.
Once it records the song it will not recorded again until at least 35 seconds after that time (40-5) so if you restart/repeat early it doesn't record.
By the time the song has repeated again it's been long enough to record the stats.

Seems okay?

**Comment by mariof1** [comment]
I don't really see any improvements. Latest commit applied, I added only one song (1 min long) to the list, set to repeat. Came back after 20 minutes and only the first play was recorded.

**Comment by lachlan-00** [comment]
I'll check again and set up a process to test

**Comment by lachlan-00** [comment]
this might be dsub specific. the website catches everything okay but dsub doesn't send anything again.

I'll try ultrasonic

**Comment by mariof1** [comment]
All my recent tests were done using web player only

**Comment by lachlan-00** [comment]
no idea why my player worked the other day, it's happening now for me in all.

**Comment by lachlan-00** [comment]
in webplayer it looks like it never reloads the file and doesn't ask to do aything
![image](https://user-images.githubusercontent.com/1305249/70480522-a7bdd100-1b2b-11ea-9d8c-db6a3b970591.png)

**Comment by mariof1** [comment]
Funny enough it works fine when I play it via a stream player for instance in VLC

**Comment by lachlan-00** [comment]
I think that must call the full url again.

I can see that the only thing running when you repeat in subsonic is saveplayqueue
![image](https://user-images.githubusercontent.com/1305249/70481168-7d6d1300-1b2d-11ea-9c80-acf8d9925bfe.png)

It does have the current and position so i might be able to fix it using that.

I think we can fix this with ajax and saveplayqueue but will need to experiment.

**Comment by lachlan-00** [comment]
workaround for subsonic is in. save using the saveplayqueue method but only when repeating a track.

**Comment by lachlan-00** [comment]
fix in webui now as well.

**Comment by mariof1** [comment]
How did you test it? I am still having the same issue....

**Comment by lachlan-00** [comment]
in develop all i have to do is is start a song and press repeat.

In web it will catch all in subsonic it might miss the first repeat depending on when it recorded. (scrobble at the end and then it will try on the repeat at the start.)

**Comment by mariof1** [comment]
This is so strange...ok so I waited a bit and in Dsub it recorded the first play at the end of the song and then there was a gap for a few minutes and started recording again and then it stopped updating stats. The song was 2:44 long.

![image](https://user-images.githubusercontent.com/32400371/70524148-7a2d5380-1b3c-11ea-81ff-b62dac51b316.png)

However in Web player there was no records on repeated songs

**Comment by lachlan-00** [comment]
are you using ajax loading in web? I haven't checked this without ajax page loading

**Comment by mariof1** [comment]
Yes Ajax load is enabled.
I have tried to disable it but I could not play anything and the log was stuck on the below entry
`(stream_playlist.class) -> Generating a {web_player} object...`

**Comment by lachlan-00** [comment]
i've fixed the repeats in web, subsonic and api now. (a while ago)
