### ISSUE TITLE
[4.1.0.0-Delop] now playing isn't shown anymore

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#2223]
# Issue Template

## Description

**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

## Environment

* Ampache version: 4 develop
* Web server + version: apache 2
* Server operating system: dsm 6.2
* Client operating system:

**Client type:**

* Ampache

## Logs

Hi 
Seems that "now playing" (gerade gespielt) isn't shown in the navigation anymore
i only updated to the newest develop.
![20191130090256](https://user-images.githubusercontent.com/25564572/69902393-8b809e00-138d-11ea-9dac-2c4a773aca7b.png)

**Comment by lachlan-00** [comment]
What was the page before? I don't remember it

**Comment by lachlan-00** [comment]
I loaded up 3.9.0 and i can't see it when playing a song either.

**Comment by noyse27** [comment]
found an old screenshot from 3.9. it was  not under information but playlists
![47364832-85c07f80-d6da-11e8-937b-eab6eedf569b](https://user-images.githubusercontent.com/25564572/69934402-1c609200-14d2-11ea-935d-1f68943b87df.jpg)

**Comment by lachlan-00** [comment]
Cool, I can find out what that was easy now

**Comment by lachlan-00** [comment]
The link for this is just back to the main page.
```
echo AmpConfig::get('web_path') ?>/index.php
```

Seems a bit redundant when the icon in the top right will do the same

**Comment by noyse27** [comment]
ahh okay thx now i understood ;) can  be closed
