### ISSUE TITLE
Playlists bugs on the API

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2225]
### Describe the bug

On this playlists methods: 

playlist_remove_song
playlist_delete
playlist_add_song

No administrative users cant use this methods on his own playlists.

-----
playlist_edit - If a no administrator tries to use this method on a playlists of another user the xml resulting says that the canges have been done, when it shoud say "error access denied..." (The changes are not really made, its just the xml wrong)

----
playlist_create - The resulting xml file just have the total count of created playlist, The ID of the resulting playlist is missing, The ID helps to keep track of the new created playlist on the API.

Thanks

## Environment

* Ampache version:4.0.4
* Web server + version:
* Server operating system:
* Client operating system:

**Comment by lachlan-00** [comment]
that's a good find, i didn't think about the id of the list.

That will save having to search for the playlist by name right after creating it.

**Comment by manuelglez86** [comment]
Well that wasnt my idea, it was present on previous versions, and my API client crash trying to find the ID jejeje, so i inspected the resulting xml and notice that the ID wasnt there

**Comment by lachlan-00** [comment]
hmm, i've not taken any attributes out but i'll put it back in.

**Comment by lachlan-00** [comment]
what is the api client you use. i need something besides power ampache and python scripts to test in

**Comment by manuelglez86** [comment]
Its a custom made client for windows, we use it to make playlists and uses VLC player plug-in to play the strems.

I can send you the installer if you want, it uses various API Methods, and i added the new advanced_search for composer, i will expand the adv_searsch in the future

It was fully functional with ampache v3.8.4, but now Im modified it to make it compatible with v4 (Im still testing so maybe have some crashes)

**Comment by BLeeEZ** [comment]
I also encounter this problem: 

playlist_remove_song
playlist_add_song
-> No administrative users cant use this methods on their own playlists.
"Error 401: Access denied to this playlist"

### Environment
- Ampache version: 4.0.4
- Client: iOS Amperfy

**Comment by manuelglez86** [comment]
Regarding to the ID of the recently created playlist with the "playlist_create" th ID is not shown due to this part of the code:

https://github.com/ampache/ampache/blob/7c09e9405191a597352f5719cb98fa065dbb6924/lib/class/xml_data.class.php#L684

As the new created playlist is empty.

**Comment by manuelglez86** [comment]
I made a pull request for the playlist_create #2228

**Comment by lachlan-00** [comment]
Awesome. If you want to share privately you can email me an installer. You can get my email from security.md

I've merged your change and will be working on these issues now

**Comment by lachlan-00** [comment]
I've created a script to test this and I've made a few changes. Create will return an existing id when you try to create a duplicate.

I've tested this all out as an admin and now I'll test with a regular user

**Comment by lachlan-00** [comment]
found the bug. it was OR and not AND in the access checks.

**Comment by manuelglez86** [comment]
I've seen you the API client installer, I'm going to test the changes you made in develop

Thank you.

**Comment by manuelglez86** [comment]
**playlist_remove_song, playlist_delete, playlist_add_song, playlist_creat**e are working correctly now

**playlist_edit** the problem is here:

https://github.com/ampache/ampache/blob/a416b7ebd50b2c27e27b8d652d6dd22b76de9795/lib/class/api.class.php#L1058

This causes a false positive because all the playlists a no admin user can see are public, eliminating this condition gives the "Access denied" Result:

>         !$playlist->type == 'public'

**Comment by lachlan-00** [comment]
No problem, I'll extend my script to test edit as well and fix that up

**Comment by manuelglez86** [comment]
I have send you the Windows API client, you can test from there too

**Comment by lachlan-00** [comment]
Cheers. Looking forward to having more API things to test with

**Comment by lachlan-00** [comment]
Okay, can see that the changes are reporting changed for edit but not completed. also see that name/type are both mandatory when they probably shouldn't be.

**Comment by lachlan-00** [comment]
Fixed in develop.
I will test your client at work today and see what else I can find

**Comment by manuelglez86** [comment]
Upss I pull playlist_edit a while ago, Is my fault that name andt type are mandatory, I think you are right, they shouldnt be.

**Comment by lachlan-00** [comment]
i've made the change in develop now to make them not mandatory

**Comment by manuelglez86** [comment]
I can confirm that playlist_edit is working now.
I think this issue can be close

Thanks.
