### ISSUE TITLE
Documentation error in Ampache wiki

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2226]
In Ampache's XML API wiki , the answer of the api to the Handshake Request is:

`<root>
   <auth>AUTHENTICATION TOKEN</auth>
    <version>APIVERSION</version>
    <update>Last Update ISO 8601 Date</update>
    <add>Last Add ISO 8601 Date</add>
    <clean>Last Clean ISO 8601 Date</clean>
    <songs>Total # of Songs</songs>
    <artists>Total # of Artists</artists>
    <albums>Total # of Albums</albums>
    <tags>Total # of Tags</tags>
    <videos>Total # of Videos</videos>
</root>
`

but the real field it is not version, but api

  `  <version>APIVERSION</version> `
 is incorrect, the correct one is
  `  <api>APIVERSION</api>`

**Comment by lachlan-00** [comment]
Must have been a very old version that did that. i've updated the wiki
