### ISSUE TITLE
Misspelt HTTP_REFERER in /tempates/show_login_form.inc line 81

### ISSUE THREAD

**Issue by Rhythm-of-Time** [ampache/ampache#2229]
## Description
Misspelt HTTP_REFERER PHP varable name in /tempates/show_login_form.inc line 81
### Describe the bug

No idea what effect this may have, but as this is spelt differently in /lib/class/user.class.php and /lib/ui.lib.php I presume it is a typo and not intentional.
## Environment

* Ampache version:
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by lachlan-00** [comment]
Fixed. it's the only one i can see
It will always be null / empty so it won't do anything valuable.
might fix some issues with which page to return to.
