### ISSUE TITLE
flip_state to disable / enable song is not toggling icon by AJAX

### ISSUE THREAD

**Issue by Rhythm-of-Time** [ampache/ampache#2230]
## Description
A disabled song seemingly can't be activated again. The icon remains icon_disable.png.
### Describe the bug

In Songs view or Song Details, clicking on "Disable" disables the song. Clicking again does enable it, but does not change the icon back. After a page reload, the correct state is displayed.
## Environment

* Ampache version: 4.04-release
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by lachlan-00** [comment]
I see that, the song is enabled but the icon doesn't update.

**Comment by lachlan-00** [comment]
Thanks for finding this! fixed in develop

**Comment by stebe** [comment]
I think this fix broke the fix in #2015 as I can no longer disable a catalog.

**Comment by lachlan-00** [comment]
That's odd, I fixed this in the template file so it shouldn't affect that.

Can also still toggle in catalogs on my server too

**Comment by stebe** [comment]
My bad, Seems Firefox being weird. Works fine in Chrome. Sometimes addins I have in Firefox do this, Should have checked with another browser before commenting.
