### ISSUE TITLE
Tags just say "Array"

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2231]
### Describe the bug

Now when I create a new catalog or when verify an existing one, all the tags of the catalog are "Array".

Im using today's develop.

Thanks.

![albums003](https://user-images.githubusercontent.com/19354668/70259021-f5fd5980-1752-11ea-97ff-20dccd95fe07.png)

## Environment

* Ampache version: develop
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache

**Comment by lachlan-00** [comment]
Fixed in develop now.
There is some incorrect code somewhere i need to find that's casting an array as a string without checking for the array.
