### ISSUE TITLE
[Feature Request] API access for Ampache database settings

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2233]
I looked through the XML methods and I can't find a way to access user settings or global settings. Can we get that into the XML API so I can make a port for the JSON API.

**Comment by lachlan-00** [comment]
just whatever is in the preference class?

**Comment by AshotN** [comment]
Whatever would be needed to replicate all the functionality that is in Reborn.

**Comment by lachlan-00** [comment]
just need to add the ability to edit values and we're good. you'll have access to system and per user settings and then the ability to change those values

**Comment by kuzi-moto** [comment]
Nice! This will be a huge step for 3rd part clients.

**Comment by lachlan-00** [comment]
this can all be done now. woo!
