### ISSUE TITLE
[Feature Request] API access to user profile

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2234]
The API let's you create a new user and set it's `Full Name` for example. But there doesn't seem to be a way to access Full name, Email, website.

![image](https://user-images.githubusercontent.com/1350342/70294946-24c01200-17dd-11ea-9faf-dd4748861730.png)

**Comment by lachlan-00** [comment]
It should be in user but it doesn't have everything
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
<user id="2">
	<username><![CDATA[user]]></username>
	<create_date>1108290000</create_date>
	<last_seen>1575502014</last_seen>
	<website><![CDATA[]]></website>
	<state><![CDATA[]]></state>
	<city><![CDATA[]]></city>
</user>
</root>
```

**Comment by lachlan-00** [comment]
as your own user or an admin i've added more details to the user method

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
<user id="5">
	<username><![CDATA[user]]></username>
	<auth><![CDATA[APIKEY]]></auth>
	<email><![CDATA[user@gmail.com]]></email>
	<access><![CDATA[25]]></access>
	<fullname_public><![CDATA[0]]></fullname_public>
	<validation><![CDATA[]]></validation>
	<disabled><![CDATA[0]]></disabled>
	<create_date><![CDATA[1466571291]]></create_date>
	<last_seen><![CDATA[1575262742]]></last_seen>
	<link><![CDATA[https://music.org.au/stats.php?action=show_user&user_id=5]]></link>
	<website><![CDATA[]]></website>
	<state><![CDATA[]]></state>
	<city><![CDATA[]]></city>
	<fullname><![CDATA[username]]></fullname>
</user>
</root>
```

**Comment by AshotN** [comment]
Does the API allow all those fields to be updated as well?

**Comment by lachlan-00** [comment]
whatever isn't in user_edit i can add

**Comment by lachlan-00** [comment]
Looking again there is a bit more todo in update user

allow admin to reset api key
no fullname_public listed or editable

**Comment by lachlan-00** [comment]
these missing things have been added to user_update in a9e2198c8

they can also reset their streamtoken
