### ISSUE TITLE
Configure channel for streaming

### ISSUE THREAD

**Issue by luisbalboa** [ampache/ampache#2237]

**Comment by luisbalboa** [comment]
Hi I followed this toturial ( https://youtu.be/G3YOh-hgF6w ) and I can already create the streaming link but it is not working on the player: https://live.licensic.com/channel/3/stream.mp3


Printshoots (Ampache + Wordpress): 
https://paste.pics/7GCPT
https://paste.pics/7GCRQ 
Player (front page): https://live.licensic.com/player/

Someone can help me?

Thanks

Thank you

**Comment by lachlan-00** [comment]
Did you start the channel? It runs as a background process and you can start it from the channels page

**Comment by luisbalboa** [comment]
Hi, yes I started Channel as you can see from the ready screen you left behind: https://paste.pics/7GCPT

These are the streaming links that Ampache generated:
http://127.0.0.1:8200/stream.mp3
https://live.licensic.com/channel/3/stream.mp3

The problem seems to me to be some permission on the server or some PHP module (CPanel) that must be activated because the channel PLAYER inside Ampache doesn't work ... I don't know why.
How can I send you the accesses of my Ampache and Cpanel, do you have email?

My email: works.luisbalboa@gmail.com 

Please send me a email to replay you with accesses.

Thank you for help

**Comment by luisbalboa** [comment]
When I click PLAY this JavaScript message appears: https://paste.pics/7GI8R

**Comment by lachlan-00** [comment]
It says the state is stopped so it's not running.

**Comment by luisbalboa** [comment]
Yes i understand but when I click here the channel does not start:
https://paste.pics/7GIBP

In VLC Player also gives ERROR: https://paste.pics/7GIAR

Your Ampache acess: 
https://live.licensic.com/login.php
user: lachlan
pass: Lachlan#Helpme:)

Can you access please? 
Thank you

**Comment by lachlan-00** [comment]
it's still stopped. you can run from the cli using the channel_run file

```
php -f bin/channel_run.inc -- -c 3 -v
```

**Comment by lachlan-00** [comment]
you can also use the black terminal button
![image](https://user-images.githubusercontent.com/1305249/70409194-a55d6780-1a96-11ea-82a3-ce3d1cec848c.png)

**Comment by lachlan-00** [comment]
here is a wiki page i just made showing how to make a systemd service to auto restart on failure.
https://github.com/ampache/ampache/wiki/channel-systemd

**Comment by luisbalboa** [comment]
> it's still stopped. you can run from the cli using the channel_run file
> 
> ```
> php -f bin/channel_run.inc -- -c 3 -v
> ```

Hello where do I have to do this?
I have to put this code in the file:
/home/licensic/live.licensic.com/bin/channel_run.inc
???
Is this a command to use on the terminal? If yes I do not have the terminal on CPanel installed :( but if necessary I can ask my hosting support ...

**Comment by luisbalboa** [comment]
> you can also use the black terminal button
> ![image](https://user-images.githubusercontent.com/1305249/70409194-a55d6780-1a96-11ea-82a3-ce3d1cec848c.png)

Did you see my print screen? https://paste.pics/7GIBP
I click this BLACK TERMINAL button and straming does not start :(

I need Ampache to work through the buttons and user-friendly interface:) for non-programmer users ...

**Comment by lachlan-00** [comment]
i'm not sure how cpanel works but you may be restricted from running channels. it requires opening ports on the server which you may not be allowed to do.

**Comment by luisbalboa** [comment]
I will then ask for TERMINAL access to my hosting service in order to work ...

**Comment by wagnered** [comment]
@luisbalboa,

The command must be run from a command line. You might be able to use SSH run the command. See the cpanel documentation at https://documentation.cpanel.net/display/76Docs/Terminal+in+WHM.  This can be very dangerous if you are not familiar with commands.

What company is providing your host?  We need much more information a out the system.  When you opened the issue, you should have seen some text requesting important information that could help us solve the problem.  What version of ampache is Installed?  In your first comment would wrote "ampache + WordPress". What does that mean? What system is the client?  What is the local computer you use to log into the host.

@lachlan-00 when I see something like a random text on the display of https://paste.pics/7GI8R, it usually indicated an incorrectly parsed HTML encoded text. 

But you do bring up a good point.  @luisbalboa might need to ask the host provider to open the port, although 8200 should be open by default, unless some other apparently is using it.  There are web sites that can test for open ports: https://www.portcheckers.com.





-------- Original message --------
Subject: Re: [ampache/ampache] Configure channel for streaming (#2237)

**Comment by luisbalboa** [comment]
Hello I already managed to install SSH on my CPanel. In this video shows how to create the key to access:
https://youtu.be/Ci6WixP3YaE

Here is the access data for my CPanel:
http://www.licensic.com/cpanel
Username: licensic
Password: 81!NR*zZ30Vhou

I don't have much knowledge of SSH can you help make LIVE STREAM work on Ampache?

Thanks

**Comment by wagnered** [comment]
Port 8200 appears to be closed.  @lachlan-00 is correct, channels will not work until port 8200 or other port is open.  8700 seems to be unused.  If your host provider will open that port,  you could create a channel with that port number. 

But you might have more than one problem.  The word "javaScript;" should not be displayed anywhere on the screen.

We need to know what version of ampache you have installed on the server, what is the client system, Windows, Linux or Apple? What browser you are using? When you first created the issue, there should have been information requested.  That information is important to know.null

**Comment by luisbalboa** [comment]
Hello, my server support reported:

Will put the cPanel username and password for access, with SSH port is **58100**
user: licensic
pass: 81!NR*zZ30Vhou

Ampache Version:  4.0.4-release
https://live.licensic.com/login.php
user: lachlan
pass: Lachlan#Helpme:)

Please see if you can login and set up Channel correctly to work 100%

**Comment by wagnered** [comment]
Until you get the administrator to open port 8700, channels will not work.

null

**Comment by luisbalboa** [comment]
I already got in: https://paste.pics/7GQGA
Please check with the following command line:
ssh -p 58100 licensic@licensic.com

I will then ask my support to open port 8700

Thanks

**Comment by luisbalboa** [comment]
Hello, I will have to change servers because my hosting support said:
Hello, I will have to change servers because my hosting support said:
You are on a shared server with dozens of sites / clients so we cannot make all the changes you want for security reasons.

If you want to make custom configurations on the server machine and firewall, you should choose a dedicated hosting solution, for example a cloud server.

**Comment by luisbalboa** [comment]
I will then change the server to put SSH access with port 8700

I'll talk to you back here later.

Thank you

**Comment by wagnered** [comment]
I can SSH to licensic.com that is not the same as accessing a Channel.  There is no need to change the port for SSH.  The port for ampache channels (8700) needs to be opened and a different port is needed for each channel you create.

Also, I created a log file at /home/licensic/live.licensic.com/debug.  The log reports that some settings for transcoding your files to mp3 need to be set in config/ampache.cfg.php. It is necessary that you learn some Linux commands to set up Ampache.

I am working on a Samsung android phone and it is very slow going.   I just don't have time.  

Set up is one problem but I still think there is multiple problems.



-------- Original message --------
Subject: Re: [ampache/ampache] Configure channel for streaming (#2237)

**Comment by luisbalboa** [comment]
OK! I'm really going to switch to a VPS server Linux Operation System ( and so we can configure Ampache the best way because this is a project that interests me to evolve:

**Performance data**
- CPU: two cores
- 4 GB RAM (guaranteed)
- 300 GB disk space (SSD-boosted)

**Networking**
- UNLIMITED traffic !
- 100 Mbit/s port
- No restrictions, no throttling
- DDoS protection (details)

**Operating system**
- Linux (Cent OS 7)

**Administration panel**
- cPanel/WHM

**Server service page:**
https://contabo.com/?show=configurator&vserver_id=253

I'll start with the most basic plan and then upgrade as needed ... do you think it's good to start Ampache with Channel Streaming?

Thanks

**Comment by wagnered** [comment]
I think you should first get familiar with the web player and make sure all your music can be played.  If only some files play, then probably transcoding needs to be enabled from the admin tab.

If some music files don't play such as flac, vorbis. m4a, etc it is necessary to edit config/ampache.cfg.php to enable them to be transcoded.  When all your music files can be played on the web player, it's ready for channels.  Only mp3 files can be streamed through channels. This also can be set in ampache.cfg.php.



-------- Original message --------
Subject: Re: [ampache/ampache] Configure channel for streaming (#2237)

**Comment by luisbalboa** [comment]
Yes this will take a bit of work but enjoying Ampache customization and open source spirit.

For Live Streaming I think MP3 will be enough! As soon as the new server is ready I give news! Thank you

**Comment by a7medo778** [comment]
would be cool if we could see an upgrade to the channels (radio) features
currently, it's missing the ability to switch the play metadata while playing to display the current track info

if implemented correctly alot of icecast folks would migrate here i guess

**Comment by lachlan-00** [comment]
I've started playing with channels this week.

The biggest issue I'm trying to work on is that they just eventually stop working. I've replaced my icecast streams with channels and put the channels in as "radio stations" as well to help with testing.

We'll see what I can find but I think serious users should keep using icecast. Icecast has excellent performance and stability compared to channels right now.

**Comment by lachlan-00** [comment]
your server doesn't have ffmpeg and is probably missing config so i can start a channel but it will never play anything as it can't transcode the output.

I suggest you change all these passwords and not post them up here. Channels require a lot of configurations and understanding of the server.

**Comment by luisbalboa** [comment]
Hello @lachlan-00 

1 - I have already changed the license server password licensic.com how can I inform you the new one, can you give me your email?

2 - This is already a dedicated IP VPS server as suggested to change! If you still can't do Channel Start I can ask this ffmpeg that speaks to the support of the new server.

3 - If it is possible to create a shoutcast or icecast even better because I want to use this PLAYER that uses this functionality: http://heroradioplayer.lambertgroupproductions.com/standard-version-black-controllers/
This PLAYER is great because the information I want like image, song name, artist name and history with latest played songs :)

Can you help me make this PLAYER work with Ampache in any way? I just need the Icecast, Shoutcast or Straming Channel link to make it work ...

**Comment by luisbalboa** [comment]
I already installed PLAYER on my server:
https://live.licensic.com/player/

Streaming Demo: http://s10.voscast.com:9942/;

Now all Shoutcast/Icecast needs to work on Ampache

**Comment by luisbalboa** [comment]
I have already asked my server support to see if it is possible to install or enable this function **ffmpeg**
I´m waitting...

**Comment by luisbalboa** [comment]
Hello,

Regarding **ffmpeg** I had the following answer: https://paste.pics/7HO6M

Please note that we do not place any restrictions from our side. We provided you with root access to your VPS 300 (207.180.192.90) and leave any further settings and configurations in your capable hands. This does also apply for the installation of FFmpeg. More help can be found in the **following tutorial**:

https://medium.com/@ShinobiSystems/how-to-install-ffmpeg-on-centos-7017f7647caf

@lachlan-00 can you help me install **ffmpeg**? Please send me your email or some way of informing you of access to the new server because as you recommended I changed the password.

Thank you

**Comment by luisbalboa** [comment]
Send email to me and I will reply you with the new server password:
works.luisbalboa@gmail.com

**Comment by luisbalboa** [comment]
Hello, I was able to install FFmpeg: https://paste.pics/7HTQ0

Then I executed this command that @lachlan-00  suggested:

`php -f bin/channel_run.inc -- -c 3 -v `

Channel 3 was able to **START** but **NO MUSIC** listen: https://paste.pics/7HTTR

What I have to do now can someone help me?

Thanks

**Comment by wagnered** [comment]
Open another tab on the web browser and point it to https //live.licensic.com/channel/3/stream.mp3.  Remember it's a stream going out to the internet.  It's not meant to be heard on the web player.

Also, the stream must be set to public to be heard from the internet.  I went to that URL and got a blank page.  I think that is because a private stream is created by default.null

**Comment by luisbalboa** [comment]
Hi @wagnered  I created a user for you:
https://live.licensic.com/login.php
user: wagnered
pass: wagnered

The problem is that Channel gives START but PLAYER on Ampache doesn't respond: https://paste.pics/7HTTR

What more is left to do for streaming to work?

**Comment by wagnered** [comment]
That picture shows me that you did not open up another tab and go to https://live.licensic.com/channel/3/stream.mp3.  I can see the url in the address bar.  If you did and the stream worked, you would see nothing but an audio player in the middle of the browser window. 

Also, if you created the channel with public access, anybody can listen to it without logging in.


null

**Comment by luisbalboa** [comment]
Hi, I can't Streaming (Icecast / Shoutcast) with Ampache :( Do you know any good solutions that work on my CPanel server with MySQL database and PHP?

**Comment by luisbalboa** [comment]
Hello, does this Ampache Channel Streaming really work or is it a lie?

I really liked the general panel for user music management but if it's just a Player I don't care :(

Can anyone really help me on this or am I wrong here?

**Comment by lachlan-00** [comment]
Personally i use icecast but i'm working on the channels now.
They work, but require a bit of knowledge to configure.
![image](https://user-images.githubusercontent.com/1305249/70846730-dc24ea80-1ea7-11ea-9014-cd766919c0f2.png)

We all don't have a lot of time for support but will try to make the process easier.

**Comment by luisbalboa** [comment]
Hello @lachlan-00 , 

Icecast if you can do it in Ampache for me is perfect! I have created a new STREAMUSIC.LIVE domain and I will install Ampache there too, please send me an email to give you access and help me set up icecast:

works.luisbalboa@gmail.com

I pay you the service but please help me!

Thank you

**Comment by luisbalboa** [comment]
Hello, 

For communication reasons I changed the URL of my Ampache to:
https://streamusic.live/admin/

the accesses (user + pass) remain the same!

I'm waiting for you to help me make music streaming ...

Thank you

**Comment by luisbalboa** [comment]
I verify that shoutcast is disabled no Ampache Debug Log: https://paste.pics/7IVC7

How to activate?

https://streamusic.live/admin/
user: admin
pass: admin

Thanks

**Comment by luisbalboa** [comment]
I tried to run Channel 1 but it still does not work as it does not give START:  https://paste.pics/7IVOC

**Comment by luisbalboa** [comment]
Hello, have you managed to get Channels working? 
Why does Amapache have this feature if it doesn't work?

Can someone explain to me what is left to configure? I then want to create an Icecast or Shoutcast link to be inserted into this PLAYER: https://streamusic.live/player/

Administrator Access:
https://streamusic.live//admin/login.php
user: admin
pass: admin

Thanks

**Comment by luisbalboa** [comment]
https://paste.pics/7LDE8
NO CHANNEL SOUND? WHY?

**Comment by luisbalboa** [comment]
Hello, do you have any news about Streaming Channel? Ampache has this feature and does not work :(

**Comment by Afterster** [comment]
This requires some permissions to run a separate php process as explained. Closing for now.
