### ISSUE TITLE
[Feature Request] Upload Options

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2239]
## Describe what you don't like about Ampache, or what it is missing
I like what you have done on the uploads secction, now when a file is uploaded its ID3tag is read in order to obtain its info.

But what hapend if you want to upload a WAV file, it doesnt have ID3 info, I think it should be usefull to have an option like in previouse versions:

![uploads](https://user-images.githubusercontent.com/19354668/70459977-efd0eb00-1a7a-11ea-85c0-a69c09be4997.png)

There you can select and existing album and artist to asociate with or to create a new album/artist for the uploaded files. 

Thanks

**Comment by lachlan-00** [comment]
that's true actually.

**Comment by a7medo778** [comment]
while on the subject
what do you guys think about having a permmision level to allow users to only manage thier uploads instead of full catalog's

**Comment by manuelglez86** [comment]
The user levels on Ampache allows that

**Comment by manuelglez86** [comment]
User and content manager levels can upload, modify, eliminate its own uploaded files but not the the files uploaded by other user nor the files on the catalog.

**Comment by a7medo778** [comment]
oh really, i never knew that, let me test it out

Thanks

**Comment by lachlan-00** [comment]
there are a lot of options in uploads for permissions already. nothing on the api though.

I'll look at how to retore artist/album in a simpler way.

**Comment by Rhythm-of-Time** [comment]
It would also be helpful to have the option to add tags to the uploaded songs. The workflow in our use case is exactly like this - we import wav or aiff and fill all the needed info later. The catalog import is a handy batch function, but it relies on mp3 tags. So we end up with all Orphaned (no artist) files... 

Once the function to Add New... Artist / Album is fixed (#2140), it would be great to be able (already in Upload or later in Songs view) to select multiple existing files for editing, like assigning them the same album, artist and/or tags.

Regarding the upload function itself: Maybe it is possible to implement something like Plupload for circumventing upload_max_filesize / post_max_size limits on servers where these can't be changed usually (like on shared hosts)?

**Comment by wagnered** [comment]
@Rhythm-of-Time Plupload looks good but it is dual licensed.

The [blueimp jQuery-file-uploader](https://github.com/blueimp/jQuery-File-Upload/blob/master/README.md) if configured correctly, should be comparable to Plupload and it is MIT licensed.

Otherwise, I agree with you about adding/editing the most important tags during uploads



null

**Comment by Rhythm-of-Time** [comment]
The  [blueimp jQuery-file-uploader] is neatly designed and even may contain an image editor. This would be handy for adding album art. But again, the image editor uses Doka which is not open source. Which license models generally allow free use in Ampache, apart from MIT? 

In [blueimp jQuery-file-uploader] at least there is an option to automatically resize images. But I wonder where in Ampache one can manually add new album art... I would expect this to be in the Edit Album (or Upload) dialog. Is there a way to do it already?

**Comment by kuzi-moto** [comment]
Yes, Ampache already allows for editing album art. Just go to an album's page and hover over the cover art and a cog icon will appear, which will show the album edit page.

**Comment by manuelglez86** [comment]
Yes, you can manually change/add an album art. open and album and on the image theres a button (I dont remeber the name in english of that image) where you can upload the album art

**Comment by wagnered** [comment]
Well there are many open source licenses. See https://opensource.org/licenses/alphabetical.  Ampache itself is licensed under gnu AGPL-3 which is specifically designed for network software.  The problem with most licenses is that they may allow simultaneous OEM commercial licenses. The MIT license seems to be in direct opposition to commercial licensing.  The maker of the charting package Ampache uses changed their open source license to AGPL -3 for that reason.

@lachlan-00 might be aware of Doka: one of his missions is to remove or 'quarantine' non-free modules.

There are at least several open source image editors:  Caman.js seems to have no license at all.  

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by Rhythm-of-Time** [comment]
Thank you! Finally I discovered the "button". That little cog icon only appears on hovering... None of my albums has artwork, because all of the files were imported as .wav.

For the new user (like me) this is not really obvious. The "cover art" - in my case a disc with a question mark - sits at the far right of my large desktop screen. I was desperately looking for something in the  list on the left...

**Comment by lachlan-00** [comment]
My preference will always be to prefer fully free software licences. There is info in the wiki about how I've moved out non-free or unsure libs into a sub composer file. (Which reminds me I need to update that one too for php7.4)

I'll do some play with the uploads this week.

**Comment by lachlan-00** [comment]
hey @Rhythm-of-Time  for art, make sure you set a preferred filename
![image](https://user-images.githubusercontent.com/1305249/70874295-469b6f00-1ffd-11ea-934b-cd1545936a35.png)

then you can run the gather from the cli.
```
php -f bin/catalog_update.inc -- -n music -cag
```
The cag stads for Clean, Add, Gather.
music is the name of the catalog i'm searching.

**Comment by lachlan-00** [comment]
uploads are now able to select an artist/album again
![image](https://user-images.githubusercontent.com/1305249/70874410-bb6ea900-1ffd-11ea-91fe-ed6d5ec7a3e3.png)

**Comment by manuelglez86** [comment]
Thank you for that. I´ve begin to test and Artist is not save just the album. 

When I enable delete from disk on the cfg the owner of the album should have permission to delete the entire album created by him at once (that option doesnt appear now).

For "user" level the option of manually enter the artist and album is not present.

Thanks again

**Comment by manuelglez86** [comment]
As I can understand form the code when a user created an album from the upload secction, this user should be considered as the owner of the album,

**Comment by lachlan-00** [comment]
I'll see what else needs the owner. I put it back with just checking the access level. Delete should check the user folder or access level.
I'll be at my desk all day today

**Comment by lachlan-00** [comment]
it was actually just not creating the new artist because is was calling check as readonly which would always return null.

I'll check deleting now

**Comment by manuelglez86** [comment]
I can confirm that all is working now

Thank you

**Comment by Rhythm-of-Time** [comment]
Cant't get the Uploads to work...

Dropping a file or brwosing results in the filename being displayed beside the circle, which quite rapidly fills. The "Loading..." div remains a while, and then the filename turns red. In the debugger I see this:

Object { type: "fileuploadfail", timeStamp: 1576619897422, jQuery22408272608873777505: true, … }data:Object { disabled: false, replaceFileInput: true, singleFileUploads: true, … }

The jquery.fileupload.js function  _onFail: function(jqXHR, textStatus, errorThrown, options) returns "Internal Server Error", so do I have something misconfigured?

Makes me wonder that I cannot choose the Target Folder (or should I called it the User Folder) - only the logged in username admin is visible, a hand pointer appears on hovering, but nothing happens if I click on it.

The HTML of this element is `<a class="jstree-anchor  jstree-disabled" href="#" tabindex="-1" id="/_anchor"> Is this a missing plugin maybe?

**Comment by lachlan-00** [comment]
Users get assigned as an owner when they're created. I'll see why that's blocking you today.

**Comment by Rhythm-of-Time** [comment]
Think I have messed up one catalog. Is there a way to edit these (especially the path)?

**Comment by lachlan-00** [comment]
Ahh, i see where it is, i didn't put in an access level check there, going in now.

**Comment by lachlan-00** [comment]
you can edit all the catalog settings for your catalogs in:
admin/catalog.php?action=show_catalogs

**Comment by Rhythm-of-Time** [comment]
Thank you, not it works! 

I did not find the place to edit the path for catalogs, though.

Users get assigned as an owner of _what_ when they are created? They get assigned as an owner of their respective user folders, you mean? The admin folder inside my /music folder only got created after the first upload. Let me try to upload with another user to see if there is a new folder...

I have more than one user, but only the admin user is shown - far on the right. As this is a menu related to the Target Folder, shouldn't it be better located right next to it?

**Comment by Rhythm-of-Time** [comment]
Logged in a a simple user, a folder gets created, but again the upload fails with the message
> Album owner doesn't match the current user.

**Comment by lachlan-00** [comment]
I'll lower the access check to user / 25

**Comment by lachlan-00** [comment]
Up in dev now.

If you're registered and it's allowed uploads should go through. to delete you need to be a catalog admin or owner of the upload artist.

**Comment by Rhythm-of-Time** [comment]
Upload as a user works now, thank you!
How can the user distinguish his own content in songs view?

And how do admins / catalog managers distinguish user content and delete single songs or albums?

**Comment by lachlan-00** [comment]
You can search according to Catalog and in the UI you can delete from the song/album/artist pages

I'm working on a Catalog filter now that will allow you to keep an upload area to a single user.

It might be a good idea to add a "my uploads" in the user page to list songs that the user has uploaded.

It would probably be 
Get files in
/mnt/uploads where folder is username

There isn't very specific ownership of files once they're in

**Comment by Rhythm-of-Time** [comment]
Maybe I do not understand well how the folder structure and catalog handling should be. Generally, each catalog is meant to be a folder structure itself, right? I think it is a very good idea to separate the user content. 

If I setup a catalog pointing to a folder  /music where all existing music is located in album subfolders, all of this music will be imported, and on first upload of a user the folder /music/username will be created. Let's see what happens if we have a username that is exactly an existing folder name for an album.

**Comment by wagnered** [comment]
@lachlan-00

Maybe there is something I don't understand about what you are attempting to do but...

Are you aware that a user's uploads are displayed under the Information dropdown list when uploads are enabled?  If I remember correctly, they can be played from that list.

The anchor could probably be moved up to the Music dropdown list and renamed as you suggest.

> There isn't very specific ownership of files once they're in

There is a column in the song, artist, and album table called "user_upload"  which associates the song with the user when it is uploaded.  Of course Ampache doesn't have roles and permissions, so making them private might be involved.

Is an upload folder outside the catalog path necessary?  Can a folder outside the catalog path easily be updated or cleaned? Maybe. I don't remember if Ampache is using relative paths...



-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by lachlan-00** [comment]
You need to make an upload Catalog. It's different from your regular music catalog

**Comment by wagnered** [comment]
@Rhyth-of-time,

You bring up an interesting point. But what is the chance that an album title will be one word and identical to the user who is uploading the file?  Very small. I think it would be a "We will fix it when it happens" situation.  

Having an upload folder outside the catalog path would be good,  if it doesn't require considerable modification of Ampache and also not be open to unforseen problems.

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by manuelglez86** [comment]
Thats what i decided to create a catalog only for uploads, it is also good because i only give writte permisions on the server to the upload folder so the users/ admins can delete the uploads and not the albums by accident.

**Comment by lachlan-00** [comment]
As it sits now the duplicate name would probably be different due to matching on name, release type, year, mbid, etc

Might be a good idea to put in an upload release type for this though

**Comment by wagnered** [comment]
Could you please elaborate? Your response begs the question: What can an "upload" catalog accomplish that a "regular music" catalog can't?

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by wagnered** [comment]
@manuelglez86,

Thanks for the explanation. Is this some kind of "work around" to solve a problem?  Am i getting the wbole picture yet? I didn't realize that Ampache gives the user the ability to delete an upload.

I'm still not sure I understand why a separate "upload" catalog is necessary.  If Ampache's upload-delete capability  functions correctly, there should be no worry that an uploader could delete someone else's file in the "regular music" catalog.

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by manuelglez86** [comment]
Is not a workaround, is just my way to keep things in order and dont mix things.

You can activate the option to delete the files from disk on the cfg file. This gives you the ability to delete the uploads (every user can delete its own uploads) and administrators can delete every archive from ampache.

**Comment by lachlan-00** [comment]
I have always made a music catalog which is the local server and an upload Catalog for all uploads.
In the settings you pick which Catalog to use so that's the easiest way to keep it separate

**Comment by lachlan-00** [comment]
It's very easy to identify users when you separate and then force the folder to be per user
```
root@server:~# ls /mnt/files-music/upload/
generic  glen  user
```

**Comment by wagnered** [comment]
Thanks @manuelglez89 and everyone else for refreshing my memory.  Now it all makes sense.  ; ' >

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Upload Options (#2239)

**Comment by lachlan-00** [comment]
this is back so this is closed now.

Upload choices for all!
