### ISSUE TITLE
help wanted, channel socket server dies after a day

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2242]
Ampache channels are stream_socket_server commands
```
$server = stream_socket_server($server_uri, $errno, $errorMessage);
```

I've been testing it out and the issue seems to be that after a day the socket server dies and never recovers. This seems to be the only issue really holding channels back.

Just wondering if anyone has any ideas to help resolve this issue before i dive into searching about this.

**Comment by stebe** [comment]
Could this help? https://www.php.net/manual/en/function.stream-set-timeout.php

**Comment by lachlan-00** [comment]
Good place to start

**Comment by lachlan-00** [comment]
I'll put some debug in to check if I'm timing out
```
When the stream times out, the 'timed_out' key of the array returned by stream_get_meta_data() is set to TRUE, 
```

**Comment by Rhythm-of-Time** [comment]
If the testing server were on a DSL with dynamic ip, every 24h there would be an interruption and a new ip assigned. Just a thought because you said "after a day"...

**Comment by lachlan-00** [comment]
The script needs to handle dropouts and restart the socket server but right now it assumes that it always open.

It would be good for people to have the script log how and when it restarts/dies

**Comment by Rhythm-of-Time** [comment]
What may be the reason that I can't start the channel? I think that transcoding is set up correctly, and I am using only mp3 files. Start time is displayed as 1970-01-01T01:00:00+01:00 (having never run).

When I click on Start Channel, the Loading div appears for some seconds, nothing else happens. Or at least, it is not indicated. The logs grow rapidly now, with repeating calls every second:

2019-12-16 03:06:26 [admin] (ajax.server) -> Called for page: {index} 
2019-12-16 03:06:26 [ampache] (session.class) -> Existing session found 
2019-12-16 03:06:27 [admin] (session.class) -> e320e6e850318ba05a940e3f4f5909ac has been extended to Mon, 16 Dec 2019 04:06:27 +0100 extension length 3600 
2019-12-16 03:06:27 [admin] (ajax.server) -> Called for page: {index} 
2019-12-16 03:06:27 [ampache] (session.class) -> Existing session found 

Where do these debug events come from?

**Comment by lachlan-00** [comment]
run from the cli first to test that it runs.

-c 8 is my channel id and -v is for verbose
```
php -f bin/channel_run.inc -- -c 8 -v
```

**Comment by Rhythm-of-Time** [comment]
<b>Parse error</b>:  syntax error, unexpected T_NEW in <b>/bin/channel_run.inc</b> on line <b>300</b><br />

**Comment by lachlan-00** [comment]
that's probably why your channel isn't running. is this master?

**Comment by Rhythm-of-Time** [comment]
No, it is develop. Should I try master instead?

**Comment by lachlan-00** [comment]
I'm going to keep working on channels this week and should hopefully have things running a bit smoother in a few days. I'm at home the next few days so that will give me time to investigate.

**Comment by Rhythm-of-Time** [comment]
ok, I'll leave you with it for a while... Good luck!

**Comment by luisbalboa** [comment]
> I'm going to keep working on channels this week and should hopefully have things running a bit smoother in a few days. I'm at home the next few days so that will give me time to investigate.

Ok, I also want to know how to make the channel work, please let me know!

Thanks

**Comment by lachlan-00** [comment]
> > I'm going to keep working on channels this week and should hopefully have things running a bit smoother in a few days. I'm at home the next few days so that will give me time to investigate.
> 
> Ok, I also want to know how to make the channel work, please let me know!
> 
> Thanks

https://github.com/ampache/ampache/wiki/Channels

The wiki and it's sub pages should give you enough info. The limitations are not issues with playing or starting but with maintaining continuous play over days and identifying when the channel has failed.

I've put example systemd files up for a service and a timer to restart the service at 1123 each night.

Channels will run for a day continuously without issue but then the socket seems to time out and die

**Comment by luisbalboa** [comment]
Hi, I join your channels, but it doesn't work:
https://music.com.au/channel/5/stream.mp3
https://music.com.au/channel/6/stream.mp3
https://music.com.au/channel/7/stream.mp3

**Comment by lachlan-00** [comment]
There is no demo right now, they are just examples.

**Comment by luisbalboa** [comment]
> There is no demo right now, they are just examples.

Ok 👍🏻
When do you think it will be possible to create a working Icescast or Shoutcast link on my server? Before that, Channel START needs to be resolved, am I correct?

I need this resolved no later than the end of this year 2019, I appreciate your help.

Thanks

**Comment by lachlan-00** [comment]
If you run icecast you can add a link as a radio station. Icecast supports more listeners than channels as well

**Comment by luisbalboa** [comment]
Yes I understand but I don't want to use an external service for Channel. I want everything to be done inside Ampache: MUSIC CHANNEL + ICECAST RADIO with its link to put in an external PLAYER like this:
https://streamusic.live/player/

It's possible?

**Comment by lachlan-00** [comment]
okay i've been playing with channels and i think the issue is with the stream_socket_server

https://www.php.net/manual/en/function.stream-socket-server.php
![image](https://user-images.githubusercontent.com/1305249/111053639-259c2500-84b1-11eb-9986-940b5ecf4946.png)

Every time my backlog gets to 5 the server stops. i'm not sure how/why it's getting a backlog but it's not processing after it gets locked. and the magic number is 5 so the channel script need s to clear this backlog somehow.

**Comment by lachlan-00** [comment]
more digging, the stream clients never actually end once streaming.
![image](https://user-images.githubusercontent.com/1305249/111547830-7e2b3500-87c5-11eb-893f-1b73c8acab9e.png)

**Comment by mitchray** [comment]
Sayonara Channels
