### ISSUE TITLE
XML-API "playlist_create" does not give back handle to the new Playlist

### ISSUE THREAD

**Issue by DjTuxeedo** [ampache/ampache#2243]
## Description
XML-API "playlist_create" does not give back handle to the new Playlist

### Describe the bug
xml-api returns: 

`<?xml version="1.0" encoding="UTF-8" ?>
<root>
<total_count>1</total_count>
</root>`

but no Information on the newly created playlist. Furthermore: An empty Playlist will not be reported when requesting all Playlists (action=playlists) thus not leaving any chance to reference the newly created Playlist

### To reproduce

Open browser and insert url (change server name and auth):

https://serverName/ampache/server/xml.server.php?action=playlist_create&auth=athentificationgoeshere&name=python-test&type=private

### Expected behavior
create playlist and return xml file with new playlist_id included

## Environment
* Ampache version: 4.0.4
* Web server + version: Apache2
* Server operating system: Ubuntu
* Client operating system: Ubuntu

### Client type
* Web

**Comment by manuelglez86** [comment]
This is already fix on v 4.1.0

**Comment by lachlan-00** [comment]
sure is! This was just a cross issue from the python3-ampache repo.
