### ISSUE TITLE
Unable to get past "Ampache Update" on FreeBSD

### ISSUE THREAD

**Issue by UiharuKazari2008** [ampache/ampache#2245]
Fresh install on FreeBSD, completed configuration wizard, Write Config, Shows "Ampache Update" and "update" even though its at the latest master. Tired on developer and still nothing. Don't know how to disable the "update" so I can just move on

Never got to set a password or anything 

<img width="1189" alt="Screen Shot 2019-12-19 at 17 55 19" src="https://user-images.githubusercontent.com/15165770/71216544-c25d1c00-2288-11ea-81a8-89ab0bdc8f65.png">

**Comment by lachlan-00** [comment]
After install this does the database updates.
Is there no button to apply the updates?

**Comment by UiharuKazari2008** [comment]
I checked and very little has been added. I noticed the it did not grant access to its own database so I gave it everything on that schema. I re-ran the install.php and got it to ask for a admin account. Filled that out and it created the user in the table but it won't let me login and I still get the same page. Only button I have is Update and when you click that it just reloads the page

Trying to find the option on mysql so I can enable the general log.

**Comment by UiharuKazari2008** [comment]
I have deleted the config, database, and user and tried again and now it "works" but it will not let me into the admin interface

**Comment by lachlan-00** [comment]
Seems like it's PHP / SQL. If you go to test.php are there any warnings?

**Comment by UiharuKazari2008** [comment]
none, I set use_auth="true" and I can get in but I want people to be able to "just use the site" and not have to login but I would still need a way to have a admin login

**Comment by lachlan-00** [comment]
Ahh, auth is required for password access. But I'm going to look at allowing a demo style access with admin as well.

**Comment by UiharuKazari2008** [comment]
ah ok I thought I was going crazy for a moment
