### ISSUE TITLE
Playlist blocks album/artist details

### ISSUE THREAD

**Issue by StephenAtty** [ampache/ampache#2250]
### Describe the bug

When you have a playlist open it now lies over the main part of the page, blocking access to things like the artist/album information
### To reproduce

1. Go to 'Random'
2. Click on 'Songs'
3. Playlist appears on right hand side
4. Click on Artist link on Recently Played.
5. Artist details appear behind the playlist

### Expected behavior

Artist details should not appear behind playlist.

### Screenshots
![Annotation 2019-12-21 165317](https://user-images.githubusercontent.com/251449/71310985-a08fa080-2412-11ea-8230-5a8fb3faa131.png)

![Annotation 2019-12-21 165343](https://user-images.githubusercontent.com/251449/71310984-9ff70a00-2412-11ea-977a-011768373575.png)
## Environment

* Ampache version:  Ampache 4.0.4-release
* Web server + version:  Apache/2.4.41 
* Server operating system:  Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-157-generic x86_64)
* Client operating system: Windows 10.   Firefox 71.0 and  Chrome 79.0.3945.88

### Client type

* Web

**Comment by lachlan-00** [comment]
The playlist is now behind the player.

artist info is still covered but you can also now hide the playlist using the minimise icon
![image](https://user-images.githubusercontent.com/1305249/99354118-88115a00-28f1-11eb-9a6e-d3358b679c26.png)

**Comment by mitchray** [comment]
Seems like it can be closed 👍
