### ISSUE TITLE
Wrong SQL syntax

### ISSUE THREAD

**Issue by skriker** [ampache/ampache#2254]
From log:

```2019-12-24 23:58:02 [xxx] (dba.class) -> Error_query SQL: SELECT DISTINCT(`album`) as `id`, MAX(`song`.`addition_time`) AS `real_atime` FROM `song` AND `catalog` = '7' GROUP BY `song`.`album` ORDER BY `real_atime` DESC LIMIT 500
2019-12-24 23:58:02 [xxx] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND `catalog` = '7' GROUP BY `song`.`album` ORDER BY `real_atime` DESC LIMIT 500' at line 1"]```

## Description

This error message appears in the log anytime I try to reload the data from Ampache via Subsonic api `(ios app: play:Sub)`

### To reproduce

Reload data from Ampache via Subsonic API.

### Expected behavior
No Errors

* Ampache version: 4.0.4-release
* Web server + version: Nginx
* Server operating system: Ubuntu 18.04
* Client operating system: iOS

### Client type

* SubSonic

**Comment by lachlan-00** [comment]
I see it here. Should be where
```
FROM song AND catalog = '7'
```

**Comment by skriker** [comment]
Yes:)

I am tracking some strange problems with Subsonic API. This is just what I have noticed along the way.

**Comment by lachlan-00** [comment]
Keep it up. That's exactly what we need to be on top of. I'll be looking at a new release as soon as possible as there have been a lot of bugfixes

**Comment by skriker** [comment]
The whole issue with Subsonic API is actually caused by this SQL problem.

I have "fixed" the problem with this hack:

`if ($allow_group_disks && $type == 'album') {
                $sql .= "LEFT JOIN `album` ON `album`.`id` = `" . $base_type . "`.`album` ";
            }
            else {
                $sql .= " WHERE 1=1 ";
            }`

The bug is related to AmpConfig::get('album_group') setting and it appears when grouping is disabled.

**Comment by lachlan-00** [comment]
Thank you. i'm back at my desk today so i will fix it soon.

**Comment by lachlan-00** [comment]
i've put a fix up now with a little bit of cleanup to the variable names/code.
I also found a situation in the random class that would do the same thing but you should be good for this now.

**Comment by lachlan-00** [comment]
This is long since fixed
