### ISSUE TITLE
Cannot edit smart playlist

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2257]
### Describe the bug

I cannot edit a smart playlist or search songs. Search albums, artists and playlists are not affected.  Not sure if it is my configuration or a general error. Tried with Firefox, Chrome and Edge.
### To reproduce

1. Go to 'Smart Playlists'
2. Click on 'any existing smart playlist'
3. Scroll down to 'rules'
4. No existing rules are show and add rule button doesn't do anything.

### Expected behavior

Should see existing rules and have the ability to delete and add more.

### Screenshots

![image](https://user-images.githubusercontent.com/4076671/71642140-eea76e00-2c74-11ea-9405-8eb3cdd66e2e.png)
![image](https://user-images.githubusercontent.com/4076671/71642208-d5eb8800-2c75-11ea-9b25-2794edc75e63.png)
![image](https://user-images.githubusercontent.com/4076671/71642215-eac81b80-2c75-11ea-89e0-4d12c0581133.png)

## Environment

* Ampache version: aec0ceb1e95d9010aed3494b096023493d6987c4
* Web server + version:  Apache 2.4.41
* Server operating system: Debian 11
* Client operating system: Windows 10

### Client type

* Web - Firefox, Chrome or Edge
* Ampache

## Logs

2020-01-01 09:15:40 [ampache] (session.class) -> Existing session found
2020-01-01 09:15:40 [stebe] (session.class) -> suli4be5cifk8snll229753lhj has been extended to Thu, 02 Jan 2020 09:15:40 -0500 extension length 86400
2020-01-01 09:15:42 [stebe] (browse.class) -> Show objects called for type {playlist_media}
2020-01-01 09:15:45 [ampache] (session.class) -> Existing session found
2020-01-01 09:15:45 [stebe] (session.class) -> suli4be5cifk8snll229753lhj has been extended to Thu, 02 Jan 2020 09:15:45 -0500 extension length 86400
2020-01-01 09:15:45 [ampache] (session.class) -> Existing session found
2020-01-01 09:15:45 [stebe] (session.class) -> suli4be5cifk8snll229753lhj has been extended to Thu, 02 Jan 2020 09:15:45 -0500 extension length 86400
2020-01-01 09:15:45 [ampache] (session.class) -> Existing session found
2020-01-01 09:15:46 [stebe] (session.class) -> suli4be5cifk8snll229753lhj has been extended to Thu, 02 Jan 2020 09:15:46 -0500 extension length 86400
2020-01-01 09:15:46 [stebe] (ajax.server) -> Called for page: {browse}
2020-01-01 09:15:46 [stebe] (browse.ajax) -> Called for action: {get_filters}
2020-01-01 09:15:46 [ampache] (session.class) -> Existing session found
2020-01-01 09:15:46 [stebe] (session.class) -> suli4be5cifk8snll229753lhj has been extended to Thu, 02 Jan 2020 09:15:46 -0500 extension length 86400
2020-01-01 09:15:46 [stebe] (ajax.server) -> Called for page: {stats}

Apache2 logs:
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:40 -0500] "GET /smartplaylist.php?action=show_playlist&playlist_id=33 HTTP/1.1" 200 22628 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /lib/javascript/search-data.php?type=song HTTP/1.1" 200 5104 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /lib/javascript/search.js HTTP/1.1" 200 2946 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /images/icon_download.png HTTP/1.1" 304 547 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=26578&object_type=album&thumb=3&fooid=438968 HTTP/1.1" 200 3890 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=32898&object_type=album&thumb=3&fooid=437702 HTTP/1.1" 200 3678 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=31811&object_type=album&thumb=3&fooid=406494 HTTP/1.1" 200 3246 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=33783&object_type=album&thumb=3&fooid=406521 HTTP/1.1" 200 9783 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /util.php HTTP/1.1" 200 530 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=37203&object_type=album&thumb=3&fooid=438767 HTTP/1.1" 200 3313 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=36631&object_type=album&thumb=3&fooid=433790 HTTP/1.1" 200 2862 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=37265&object_type=album&thumb=3&fooid=440208 HTTP/1.1" 200 3277 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=33155&object_type=album&thumb=3&fooid=433262 HTTP/1.1" 200 2419 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=36238&object_type=artist&thumb=3&fooid=344149 HTTP/1.1" 200 3806 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "POST /server/ajax.server.php?page=browse&action=get_filters&browse_id=3465 HTTP/1.1" 200 826 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=33915&object_type=album&thumb=3&fooid=439193 HTTP/1.1" 200 2526 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36460&object_type=album&thumb=3&fooid=435042 HTTP/1.1" 200 2547 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=30009&object_type=album&thumb=3&fooid=438656 HTTP/1.1" 200 2658 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36052&object_type=album&thumb=3&fooid=432647 HTTP/1.1" 200 3318 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:45 -0500] "GET /image.php?object_id=30363&object_type=album&thumb=3&fooid=433554 HTTP/1.1" 200 2182 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36262&object_type=album&thumb=3&fooid=412330 HTTP/1.1" 200 2543 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=27667&object_type=album&thumb=3&fooid=440915 HTTP/1.1" 200 3279 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=34441&object_type=album&thumb=3&fooid=434078 HTTP/1.1" 200 4432 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=34154&object_type=album&thumb=3&fooid=433354 HTTP/1.1" 200 2878 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=29546&object_type=album&thumb=3&fooid=412067 HTTP/1.1" 200 2783 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=40015&object_type=album&thumb=3&fooid=439564 HTTP/1.1" 200 3123 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36342&object_type=album&thumb=3&fooid=433356 HTTP/1.1" 200 1979 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36043&object_type=album&thumb=3&fooid=433267 HTTP/1.1" 200 2916 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=36063&object_type=album&thumb=3&fooid=434137 HTTP/1.1" 200 3125 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=29947&object_type=album&thumb=3&fooid=432536 HTTP/1.1" 200 3411 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=39803&object_type=album&thumb=3&fooid=436989 HTTP/1.1" 200 2783 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=37759&object_type=album&thumb=3&fooid=439205 HTTP/1.1" 200 3139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=33649&object_type=album&thumb=3&fooid=433143 HTTP/1.1" 200 3304 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=35567&object_type=album&thumb=3&fooid=433830 HTTP/1.1" 200 3600 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=37772&object_type=album&thumb=3&fooid=440832 HTTP/1.1" 200 3227 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /image.php?object_id=34076&object_type=album&thumb=3&fooid=412683 HTTP/1.1" 200 2951 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [01/Jan/2020:09:15:46 -0500] "GET /server/ajax.server.php?page=stats&action=geolocation&latitude=45.3304&longitude=-75.6633 HTTP/1.1" 200 668 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"

**Comment by lachlan-00** [comment]
can confirm

**Comment by lachlan-00** [comment]
sorry, i actually don't get that.
i found an issue with editing in the edit window but not with the rules yet.

Fixing a bug now where setting public/private is always public
![image](https://user-images.githubusercontent.com/1305249/71647441-bf5f3280-2d42-11ea-9297-363c99e0ae8a.png)

I see it tries to load the filters using get_filters but i haven't been able to not see or add them yet.

**Comment by lachlan-00** [comment]
This stuff loads over javascript so has noscript blocked it or something similar?

**Comment by stebe** [comment]
I'm not using any script blockers on the browsers I tested. I even tried IE11 which doesn't have any protection.

![image](https://user-images.githubusercontent.com/4076671/71665711-e2cab300-2d2b-11ea-95fc-ddd7420f7b89.png)

**Comment by stebe** [comment]
Could it be because my network is ipv6?

**Comment by lachlan-00** [comment]
looks broken in IE11 for me. but okay in all others.

I don't have an ip6 network but if things like the webplayer load it seems like it shouldn't be your lan.

**Comment by stebe** [comment]
I want to eliminate my own server install as this used to work before. I'll do a test clean install this weekend.

**Comment by stebe** [comment]
I did a clean install and the rules are available and I can select. I then linked the new install to my existing database and the rules options are not there again. So something in the database is probably corrupt.  

What I'd like to do is continue with a new database but copy the catalogs and stats from the old database.  What tables would I need to transfer from the old to the new?

**Comment by stebe** [comment]
Still working on my old install I was able to get the rules to display but in a strange way. I would first click on search/songs (no rules option would display) I would then click on the album tab and back to the songs tab (rules options will display) click on a smart playlist (existing rules and option display). This will then work for the whole session. If I log out and log in again, the rules would not display again.

**Comment by lachlan-00** [comment]
I think I should do a write up on migrating song data to a new database. I've had to do it before but I think I should do this for my test server to give others the option.

I'm going to sit at my desk tonight and go over your cast to see if I can work out what's happening.

**Comment by lachlan-00** [comment]
In the mean time while i test this out these should be the only tables you need to keep. (AFAIK)
This should keep all the song/user info and ideally not affect your users. You also don't have to takke all of them like playlists but these are all song-related tables that require the id's to remain the same.

I think you can not migrate preferences and it should be okay. i'm going to work on testing this when i get 4.1.0 out.

```
album
artist
catalog
catalog_local
image
object_count
playlist
playlist_data
rating
share
song
user
user_activity
video
```

**Comment by stebe** [comment]
This is related the #2328 so I'll close this one.
