### ISSUE TITLE
PHP Fatal Error ListenBrainz.plugin.php

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#2258]
### Describe the bug

In the Apache logs I have an error on the ListenBrainz module.
See the error in the logs.
To work around the problem I have disabled the module
the error results in the impossibility of broadcasting music
## Environment

* Ampache version: 4 dev ( up-to-date )
* Web server + version: Apache 
* Server operating system: Ubuntu 18.04
* Client operating system: web, UltraSonic

## Logs
[Thu Jan 02 18:12:54.228029 2020] [php7:error] [pid 26225] [client ip**********] PHP Fatal error:  Uncaught Error: Call to undefined function is_empty() in /usr/local/bin/ampache/modules/plugins/ListenBrainz/ListenBrainz.plugin.php:139\nStack trace:\n#0 /usr/local/bin/ampache/lib/class/user.class.php(930): Ampachelistenbrainz->save_mediaplay(Object(Song))\n#1 /usr/local/bin/ampache/lib/class/user.class.php(911): User::save_mediaplay(Object(User), Object(Song))\n#2 /usr/local/bin/ampache/play/index.php(675): User->update_stats('song', '233790', 'okhttp/3.10.0', Array)\n#3 {main}\n  thrown in /usr/local/bin/ampache/modules/plugins/ListenBrainz/ListenBrainz.plugin.php on line 139

**Comment by lachlan-00** [comment]
you know when you're talking in your head and you write what you say?

Fixed in develop now

**Comment by douglasriper** [comment]
I know :)
thx
