### ISSUE TITLE
can't play the song whose url was got by api

### ISSUE THREAD

**Issue by anndyd** [ampache/ampache#2260]
## Description
can't play the song whose url was got by api.

### Describe the bug
I got the song url with API under admin account, but when I try to play the song with this url via Html 5 Audio object, the Audio object can't reach the song.

### To reproduce

1. I get the song's url by XML API, the url likes the following:
    http://yuankua.info:18080/ampache/play/index.php?ssid=8a567b…&type=song&oid=140&uid=1&player=api&name=Yuankua%20-%20-.mp3

2. I try to play the song via HTML 5 Audio Object with this url in my web app

3. If I logged on the Ampache server within same browser session, the song can be played well
    If I run my web app and without logging on Ampache server in the browser, the song cannot be reached

4. I added call handshake API before playing the song. The handshake API return the valid value, but the song still cannot be reached.

5. When I set the use_auth = "false" in the  config/ampache.cfg.php, the song can play.

### Expected behavior
The song should can play.

## Environment

* Ampache version: 4.0.4-release
* Web server + version:  Apache/2.4.6 (CentOS) 
* Server operating system: centos 7
* Client operating system: Windows 10, Chrome, Firefox

### Client type

* Web

## Settings

in  config/ampache.cfg.php:
can't play when use_auth = "true", default_auth_level = "admin"

## Logs

Chrome return error: "session expired"

Firefox return error: 
HTTP load failed with status 403. Load of media resource http://yuankua.info:18080/ampache/play/index.php?ssid=8a567b…&type=song&oid=140&uid=1&player=api&name=Yuankua%20-%20-.mp3 failed.
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable

**Comment by lachlan-00** [comment]
Session expired means that the session doesn't exist in the database. Handshake generates a session id that you use for all other calls.

I'll post an example

**Comment by anndyd** [comment]
@lachlan-00 Thanks!
Exactly. 
But I don't how to use the session id returned from handshake when I play the son with the url.

BTW, I'm using Angular 8 to write web app.
Please put the example or link here when you post the example.
Thank you again!

**Comment by lachlan-00** [comment]
You can use the play url or you can use the stream/download actions.

So send the handshake using your details and you get an auth key
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<auth><![CDATA[eeb9f1b6056246a7d563f479f518bb34]]></auth>
	<api><![CDATA[400002]]></api>
	<session_expire><![CDATA[2019-12-05T10:25:59+10:00]]></session_expire>
	<update><![CDATA[2019-11-26T16:35:05+10:00]]></update>
	<add><![CDATA[2019-12-05T05:35:58+10:00]]></add>
	<clean><![CDATA[2019-12-05T05:35:33+10:00]]></clean>
	<songs><![CDATA[269459]]></songs>
	<albums><![CDATA[25779]]></albums>
	<artists><![CDATA[11069]]></artists>
	<playlists><![CDATA[21]]></playlists>
	<videos><![CDATA[0]]></videos>
	<catalogs><![CDATA[4]]></catalogs>
</root>
```

Then you use that auth key in all future interactions.
(only send your hashed password for the handshake.)

Song/playlist methods will return a play url that includes the session id. the ssid is the auth key from your handshake.
```
<url><![CDATA[https://music.com.au/play/index.php?ssid=eeb9f1b6056246a7d563f479f518bb34&type=song&oid=164215&uid=2&player=api&name=Hellyeah%20-%20-.mp3]]></url>
```
Stream / download will send you the raw stream of a file.
```
https://music.com.au/server/xml.server.php?action=stream&id=164215&type=song&auth=eeb9f1b6056246a7d563f479f518bb34
```

**Comment by anndyd** [comment]
@lachlan-00 , Thank you very much!
It works!
Many thanks for your help!
I'll close this issue.
