### ISSUE TITLE
Album Art now showing in v4.0.4 on webpage

### ISSUE THREAD

**Issue by stephen-d-hill** [ampache/ampache#2261]
## Description

**Describe the bug**
No artwork is displayed in the webpage

**To reproduce**
Open Music->Albums
Even if I click on the cog, for an album artwork to edit/find art, and select an image, when I go back to the album page it is still not shown.

**Expected behavior**
See some artwork in webpage.
Note that with my other client, DSub, artwork is shown.

## Environment

* Ampache version: 4.0.4
* Web server + version: Apache v2.4.41-1+ubuntu16.04.1+deb.sury.org+5 + PHP v7.2.26-1+ubuntu16.04.1+deb.sury.org+1
* Server operating system: Ubuntu 16.04
* Client operating system: Ubuntu 19.10 Firefox

**Client type:**
* Web

## Settings
Vanilla 

## Log
Gather Art log
[ampache.20200106.log](https://github.com/ampache/ampache/files/4027723/ampache.20200106.log)

**Comment by stephen-d-hill** [comment]
Fixed the problem, although not sure what was happening. I found the following in /var/log/apache2/error.log:

`Wed Jan 08 12:49:44.026105 2020] [proxy_fcgi:error] [pid 29032:tid 140425671235328] [client 10.8.0.6:49678] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Art::get_db() in /usr/local/ampache-3.9.0/image.php:88\nStack trace:\n#0 {main}\n  thrown in /usr/local/ampache-3.9.0/image.php on line 88\n', referer: https://hill.ownip.net/ampache/index.php`

which has the wrong path to ampache in it. I deleted this old version, and then the artwork appeared!

**Comment by AshotN** [comment]
@stephen-d-hill please close your issue if it is resolved.
