### ISSUE TITLE
[Feature Request] Example return data for API documentation

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2266]
Would be nice if the API doc had some examples of returned data. Ideally in both XML and JSON. 

This can probably be done by anyone as long as long as they have permission to edit the documentation.

**Comment by kuzi-moto** [comment]
Agree, probably would be good to have. Wiki is publicly editable, so literally anyone could do it.

**Comment by lachlan-00** [comment]
I've already been making them.

http://github.com/lachlan-00/python3-ampache
I have to work on the theme but it's going into the .org site here
http://ampache.org/api.html

**Comment by mitchray** [comment]
I think this can be closed now 👍
