### ISSUE TITLE
Enable issues on ampache-xbmc-plugin

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2267]
In the new https://github.com/ampache/ampache-xbmc-plugin repository it is not possible to post any issue.

**Comment by lachlan-00** [comment]
Done!
What an odd default

**Comment by lachlan-00** [comment]
does the maintainer not give you those permissions? i'll bump you up to admin then

**Comment by lusum** [comment]
Ok, now i have all permissions and issues is present, thanks!
