### ISSUE TITLE
art retrieval using lastfm method always gets the small 34x34 art

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#2268]
When art is retrieved using the lastfm method the audioscrobbler API gives back a list of different art resolutions. The first one seems to always be a 34x34 pixel art which is the one retrieved by ampache, leading to bad resolution art.
If setting album_art_min_width/height is set then one can filter the smaller images, but since the album_art_max_width/height is not set, I would expect that by default it takes the art with the largest resolution.

Here is an example of the audioscrobbler API reply:
https://ws.audioscrobbler.com/2.0/?method=album.getInfo&artist=Led+Zeppelin&album=Remasters&api_key=d5df942424c71b754e54ce1832505ae2

**Comment by lachlan-00** [comment]
so it's getting the first one in the list? I thought art was removed by last.fm so that's good to see it's still in there
![image](https://user-images.githubusercontent.com/1305249/72763151-21b69f00-3c2e-11ea-9e52-9f6ab2d18aeb.png)

**Comment by lachlan-00** [comment]
I think the art check must just pull in the first image result which is the smallest

**Comment by cquike** [comment]
Yes, I think your are right, otherwise you could potentially fill the DB with ridiculously large images. However the current situation is far from ideal, since in the default configuration, for art not found in musicbrainz, ampache will resort to the small lastfm covers.
I think that the default setting for album_art_min_* should then be set to some reasonable value (maybe 100? 200?). And maybe also the default for album_art_max_* should be set (maybe 1000?) to avoid populating the database with extremely large images.

**Comment by lachlan-00** [comment]
i think it's reasonable to set a min of 200 for last.fm but then we should be able to iterate through the results and ignore things that are set in config as well.

**Comment by lachlan-00** [comment]
we should probably reverse that if it's an array of results and check against the config.
I think it's easy enough to fix though. it would explain why i was not getting last.fm results because i set my min to 200x200
