### ISSUE TITLE
Variable types in JSON API 

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2272]
The JSON API currently returns some a lot of numbers as string. Which is kind of annoying for the end user. 

We should go through functions in `json_data.class.php` and make sure variables are properly casted. Unless there is a way to make SQL return the variable with it's proper data type.

**Comment by Rhythm-of-Time** [comment]
Just reading the following on problematic ways of type implementation with JSON 
[](https://tech.signavio.com/2017/json-type-information) 

The bottomline of the article says: "sooner or later, you’ll wish you had a single definition of your data model and JSON serialisation format".

GraphQL seems to be way to achieve this without having to touch the server too much. This sounds very promising: https://www.howtographql.com/. 

It would solve more then type casting issues, could also reduce traffic overhead and improve performance of the client a lot. Like React, it was developed by Facebook, but also works with other languages.

**Comment by AshotN** [comment]
I was considering GraphQL. But as I’ve never used it I didn’t want to push to hard for it. 

But ya perhaps it’s worth looking into. 

As far as the variables, we can cast them in PHP. I was just hoping there may be a better way with SQL.

**Comment by Rhythm-of-Time** [comment]
If you know which type the data should have then you can deserialize (typecast) them accordingly in your app.
 
SQL can tell you the data type of a table's column, but then you run into the problems the topmost linked article above deals with. This is pretty much the same with PHP: Somehow you will need to write the data type into JSON. This makes JSON more verbose, introduces additional nesting and makes it slower to parse.  

Setting up a map to fetch just the needed data with defined types seems a more elegant solution to me. I'll have a closer look at GraphQL and see how far I get with it.

**Comment by AshotN** [comment]
The API should definitely return the proper type. Casting shouldn't cause a performance concern.

**Comment by lachlan-00** [comment]
casting in the classes should be done anyway. i did a bit on static typing at the end of last year but will be looking at enforcing that some time this year.

it fixes a lot of bugs we have within the classes by forcing us to use the correct types. and while it's optional in php now it makes the code better so we should work on that.

**Comment by Rhythm-of-Time** [comment]
I did not mean to say something against type casting. It was rather about including type information in JSON and transferring it with as few requests as possible. Nevermind.

**Comment by lachlan-00** [comment]
I don't know enough about json to be the owner of it but I'm always happy for extra quality

**Comment by Rhythm-of-Time** [comment]
I am already happy if you bring some of the missing endpoints into the API... 

Choice of XMLHttpRequest / Axios / Fetch and more advanced concepts like HTTP/2 and/or GraphQL for the client could be discussed later.

**Comment by lachlan-00** [comment]
For this specific issue i'll look at the responses today.

ID will stay as a string but i'll convert all the ints to ints outside of that

**Comment by lachlan-00** [comment]
i think i've caught most of these so repoen if you see any more.
