### ISSUE TITLE
Ampache Google Group needs update

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2273]
The [Google Group](https://groups.google.com/forum/#!forum/ampache) has a outdated message.

I don't know if anyone besides @Afterster has permissions on it. Frankly I just noticed that Ampache has a Google Group, and just learned that Google Groups are still a thing.

**Comment by wagnered** [comment]
I would like to suggest switching to groups.io.  Back in 1/18 i explored the group's potential and created a group at https://groups.io/g/ampache(home page). The group settings and pertinent email adresses are on the home page.

The group allows uploading of files, creation of database tables, chat, messaging, topics that can be fine tuned.  Moderated/unmoderated topics, wiki, and many more features.

The one drawback I see is that in the free version, members must be invited by email.  So if anyone is interested, please send an email contact to wagnered@comcast.net. @lachlan-00 of course I'll bestow ownership on you. (; ' >

BTW: subscribers can post without being members.




-------- Original message --------
Subject: [ampache/ampache] Ampache Google Group needs update (#2273)

**Comment by kuzi-moto** [comment]
Yeah, I wanted to be able to reorganize the Google group for some time. Never got permission though.

**Comment by AshotN** [comment]
We can have as many communication channels as people want, but we should make sure there’s at least one Ampache organization member active in each. 

I can make a Telegram chat for example.

**Comment by lachlan-00** [comment]
I've been using twitter and just this week mastodon, but really only with a promotional view to the project and to notify of things happening.
https://fosstodon.org/@ampache
https://mobile.twitter.com/ampache

I'm also really only a github person as far as being social is concerned so i'm happy with whatever you all want to do. For me I would rather monitor my git notifications than talk in issues.

**Comment by AshotN** [comment]
I think the idea is to better interact with Ampache users. Easier support and communication. I’ll try to make a Telegram group.

**Comment by AshotN** [comment]
t.me/ampache

If you could add that to the README @lachlan-00 or I can do it if you prefer.

**Comment by lachlan-00** [comment]
added to the readme. i'll post about the group on social as well

**Comment by AshotN** [comment]
I also took control of the Ampache subreddit. /r/Ampache

If anyone needs to be flaired or wants to join. Please add to README if you like.

**Comment by lachlan-00** [comment]
added to readme, i'll have to sign up for reddit too. it's probably a good interactive space comparing to the lists style google groups.

**Comment by lachlan-00** [comment]
https://www.reddit.com/user/lachlan-00/ (i guess that username should have been obvious)

**Comment by AshotN** [comment]
You are a mod and have been given a flair. 

So who has privileges over the Google Group?

**Comment by lachlan-00** [comment]
Probably @Afterster

**Comment by Afterster** [comment]
Yes I have. @lachlan-00 I added you as a group manager.
I will try to get back on the projet btw, at least as an occasional developer not as the main maintainer :).

**Comment by kuzi-moto** [comment]
Cool to have you around @Afterster!

**Comment by lachlan-00** [comment]
Closing as we have active members with access to the group
