### ISSUE TITLE
Not installing c-pchart seems to affects web play

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2278]
It's because  without the c-pchart package installed, the graph class cannot find them in it's construct function and require_once() fails.

I'm writing this on the assumption that any changes should affect the user experience for the better or have as little negative effect as possible.

From the wiki:

> It has been decided to produce a separate composer file to allow users the option of installing the package while not affecting the default install.

I don't think this change minimally affects the user experience for the better.

The purpose of the zipped drop-in package was for those who do not have access to composer such as on hosted systems. The host php might not support the composer.phar that was included in the zipped package.  The previous developers assumption was that running composer with the zip package should never be necessary.

The opportunity to install  packages for commercial use should be presented during initial configuration and/or on the admin page.  At this time the user should be advised that a license must be purchased to use the package commercially. 

Also, it is not good practice running composer outside of the root, depending on its purpose: see [Composer Schema](https://getcomposer.org/doc/04-schema.md#root-package).

**Comment by lachlan-00** [comment]
I think it's not the webplayer but the streaming plugins. I did a grep on the code and these plugins are the only things calling new Graph.
```
modules/plugins/StreamTime/StreamTime.plugin.php:        $graph         = new
 Graph();
modules/plugins/StreamHits/StreamHits.plugin.php:        $graph         = new
 Graph();
modules/plugins/StreamBandwidth/StreamBandwidth.plugin.php:        $graph
     = new Graph();
```
I do want to combine them back into a single composer file under a dev/non-free install option as well I just haven't looked up how to do that.

But there shouldn't be anything calling graphs unless we enable the config option so that's a bug.

**Comment by wagnered** [comment]
From php.net:

 > The include statement includes and evaluates the specified file.

 There are also other files (graph.php for one) that instantiate the Graph class, but none of them have the require_once that includes graph.class.php.   But every file that instantiates the Graph class must be accounted for and prevented if  szymach/c-pchart isn't installed.  Does the `statistical_graphs` switch do this?  Ideally, the `statistical_graphs` switch should have no effect if pcharts is not installed,  but that depends on just what the switch does.

I think that by "evaluates" php.net means that any `require_once()` inside the required file is evaluated.  That's why the fatal error.  I couldn't locate the file with the statement that requires graph.class.php. maybe you'll have better luck. 

I don't think it's necessary to add szymach/c-pchart back into the root composer.json.  Remember, composer is a php binary and if set chmod +x, it can be run as a cli command:   `composer require 'szymach/c-pchart'` could be run in the initial configuration (install) stage giving the user the option of installing it for commercial purposes. This option should also be offered on the admin page.  A popup overlay giving the warning and maybe even a pointer to the [pChart 2.0 licensing page](http://www.pchart.net/license) could be added. 

I don't think this would be adding very much labor to accomplish.  It would also minimally affect the user experience.

**Comment by lachlan-00** [comment]
```
composer require 'szymach/c-pchart'
```
That is actually the way we should do it. 100% we then allow anyone to customise the install from a base level.

When i reverted back to c-pchart it was assuming that the config was checked in all cases but i'll need to get back into netbeans and try to break it.

**Comment by lachlan-00** [comment]
so looking again i still see noe part of the code calling this class.

i've added more fails based on the directory and config option as well.
```
!AmpConfig::get('statistical_graphs') || !is_dir(AmpConfig::get('prefix') . '/lib/vendor/szymach/c-pchart/src/Chart/')
```

I had statistical graphs enabled and the library not installed and it hasn't caused any issues.

i still think it's the plugins and have added catches in the code for them to return true before loading the graph class

**Comment by lachlan-00** [comment]
i'll document the removal of the non-free composer in the wiki and how to enable the extra requirement from the config as charts are disabled by default.

**Comment by wagnered** [comment]
In the ampache google group, Stephan Sandmann submitted a comment titled "Ampache 4.10 not playing any Songs in Webplayer".

He included a logged php runtime error:

> 2020-01-20 21:36:26 [ampache] (log.lib) -> [Runtime Error] require_once(/usr/share/ampache/www/lib/vendor/szymach/c-pchart/src/Chart/Data.php): failed to open stream: No such file or directory in file /usr/share/ampache/www/lib/class/graph.class.php(27)

Because he didn't have the problem when he ran composer on lib/composer.json, although he had a different problem, I assumed that this revealed the cause of his actual issue. At any rate, any runtime error should be corrected.


> i still think it's the plugins and have added catches in the code for them to return true before loading the graph class

Yes, the plugins are calling the graph class and the catches are necessary. But which file is graph.class.php being `required_once` from or somehow included?  It has to be included somehow before the plugins can create the class.  If I had the capability of running ampache in the Eclipse PDT IDE,  a conditional breakpoint should reveal it.

**Comment by lachlan-00** [comment]
I've put a catch in graph.class that will catch that first error if the class is called.

But i haven't been able to see a way to make these errors happen. 
No weird new Graph()'s or szymach/c-pchart's floating around that i've seen

**Comment by wagnered** [comment]
Or replace pchart.  I think that both your way and my suggested method  for including pchart are hacks and if possible, pchart should be replaced.

There are completely open source(as far as I could tell) graphics packages:  chart.js, Google charts, chartist.js, phplot and probably others that might fulfill the needs of Ampache.

@lachlan, don't try to do it all.  You might assign someone to look into using a javascript package to replace pchart. There are some good javascript programmers on the team: Let one of them have at it.

The graphics package has been an integral part of Ampache; It should continue to be so. If it means redesign of the logic, so be it.  

The following is an(other) editorial by me.  I'm not pointing a finger at any particular team member, because everyone is letting it happen and even encouraging the behavior.

 Stop planting more trees(enhancements) and take care of the forest(the entire Ampache package) and adhere to the Ampache philosopy.

@afterster, when he decided to adapt Ampache to Laravel, a much more efficient framework, he wisely put a halt to any enhancement pull requests and ignored any enhancement requests.  He only worked on bug fixes and user issues.   He put the health of Ampache over appeasing anyone's wishes.

I'm not finding fault, as there is quite a learning curve in development.  But because a lot of changes were made going from 3.9.0 to 4.0.0, now would be a good time to build a suite of phpunit test scripts to test the changes and not wait for a user to run into them.  PhpUnit testing isn't all that difficult and everyone who can script should be volunteering for this.  And you members who aren't strong on php or Ampache, install an IDE such as Eclipse.  This will help you strengthen your understanding of php and the inner workings of Ampache.

If caring whether a skip to play ratio or any other enhancement is more important than the overall wellness of Ampache, it will, in the overall, suffer and I see that happening now.

End of soapbox oration.  ( ; ' >

**Comment by lachlan-00** [comment]
It will need to be replaced but it still works so I'm not stressing on making a change for the sake of total freedom over working code.

New people are working on new things so I haven't had to put a lot of time into those. 4.1.1 has benifited from test scripting and documented examples for the api which is where I've mostly been.

https://github.com/ampache/python3-ampache

My next steps are demo and test environment with testing on top. Also I think it's time to put the static typing on again and complete that task.

What got me excited about working in Ampache was solving problems I wanted to change so I'm happy for anyone to work on those things because it might do the same for them. :)

**Comment by mitchray** [comment]
Closing as it appears to be resolved https://github.com/ampache/ampache/issues/1515#issuecomment-584086879
