### ISSUE TITLE
[Feature Request] Favorite field on API

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2279]
The API doesn't tell you if a song is a favorite, the only way I see to check is by using an advanced_search. Which isn't efficient.

**Comment by lachlan-00** [comment]
Should have a flag property in the XML. That's missing from json data?

**Comment by AshotN** [comment]
It's missing in `album_songs` `songs` and even `song`.

Perhaps the `flag` was added to XML and we forgot about JSON parity.

**Comment by AshotN** [comment]
Once the API has all the desired features added. We should take a feature freeze and make sure the two APIs have parity.

**Comment by lachlan-00** [comment]
once i script a test env we should be able to just compare the dumps from each format.
