### ISSUE TITLE
Cannot unset favorite flag with API

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2281]
The API returns a success message, but will not unset the flag. I checked that it is receiving the correct parameter. Not sure if related to #1971

**Comment by lachlan-00** [comment]
possibly, the user needs to be instantiated before the request so it's possible that the user is null when making the change. i know what to look for in this.

**Comment by lachlan-00** [comment]
I think it might be the type. api is sneding an string/int instead of a boolean.
make_bool should fix this. just putting it in edge now for testing
```
$flag      = make_bool((int) $input['flag']);
```

**Comment by AshotN** [comment]
Why cast to int and then to bool?

Isn't the required input already a bool?

**Comment by lachlan-00** [comment]
It should actually remain a string. Otherwise that's a type error for make_bool.

**Comment by wagnered** [comment]
Quick question.  With only php > 7.0 being supported, is make_bool (sub for `boolval`) really necessary?  If `make_bool` is accessed a large number of times, perhaps  converting to `boolval()` might be worth the effort speed wise.  Just a thought.



-------- Original message --------
Subject: Re: [ampache/ampache] Cannot unset favorite flag with API (#2281)

**Comment by lachlan-00** [comment]
> Quick question.  With only php > 7.0 being supported, is make_bool (sub for `boolval`) really necessary?  If `make_bool` is accessed a large number of times, perhaps  converting to `boolval()` might be worth the effort speed wise.  Just a thought.

I'm not sure if it's casting anything other than stings (true, false) and 0,1 so that's probably even easier

**Comment by lachlan-00** [comment]
Looks like strings are only cast to false if empty so it might not be possible to remove completely but I'll check.

Going to work on validation for this tonight

**Comment by wagnered** [comment]
PHP assume the parameter value is scalar: Is allowing $string  = "true" or "false" good practice with php?  Even simple typecasting any string other than "0" or "" will be cast to true: (bool)("false") = true.

The arameter of make_bool($string) is set to "true" or "false" because of the config switches.

So as long as the config file remains in it's current format, make_bool() needs to remain.

You might consider changing the config file to a php array in which the `true` and `false` constants can be used instead of strings.  This is the way most modern frameworks handle the config switches.



-------- Original message --------
Subject: Re: [ampache/ampache] Cannot unset favorite flag with API (#2281)

**Comment by lachlan-00** [comment]
I'd be happy with 0 / 1 which would be in line with mariadb/MySQL booleans. That would make it consistent between config and database.

I can work on that in migrate_config to replace strings and then we'll have a standard Boolean type everywhere.

**Comment by wagnered** [comment]
"migrate_config"  sounds like something new.  It's a good stop-gap approach.  As native functions are always more efficient, I think that eventually, Ampache should  have the  config file format changed to a php array.  A json file would be nice, but it isn't meant to contain comments. ( ; ' >



-------- Original message --------
Subject: Re: [ampache/ampache] Cannot unset favorite flag with API (#2281)

**Comment by lachlan-00** [comment]
Migrate config is a function called when the version updates. I'll examine how it works and whether it can easily change true to 1, etc.

It's a good way of moving the config along at least and making it a bit better.

**Comment by lachlan-00** [comment]
I'm just about done building the test scripts for the api,

I've noticed there are a lot of "success" responses that aren't actually making the changes. (enable/disable, flag, etc).
another issue that annoys me is the total_count isn't giving you the limited count of what the file is actually sending in some calls.

once all the methods have valid responses in https://github.com/ampache/python3-ampache/tree/master/docs i'll be able to close a lot of these issues off.

THEN i'll move it onto the master branch to get a patch release out, Then we move onto the extension of the api..

**Comment by lachlan-00** [comment]
Check_parameter was killing 0's that's fixed now though!

**Comment by lachlan-00** [comment]
develop has this fixed for sure. i'm finalising my test files now and will be making a prerelease 4.1.1 tomorrow for the other api fxes

**Comment by AshotN** [comment]
I tested and it works, but only if I pass 0/1. True/False does not work. If this is desired, can we make the API at least throw an error about an expected input.

**Comment by lachlan-00** [comment]
yes, I think keeping with 0/1 sql boolens but i'll look into converting those as well
