### ISSUE TITLE
[Feature Request] Import playlist is not present in v4

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#2282]
## Describe what you don't like about Ampache, or what it is missing
In previous version on the playlist menu was the option "Import" (below smart playlists), this was usefull because you have the function to backup playlists but now you can't import back again them.

The page was : http://yourserver/ampache/index.php#playlist.php?action=show_import_playlist

This was removed on purpose?

**Comment by kuzi-moto** [comment]
I believed it was just moved under Preferences.

**Comment by manuelglez86** [comment]
Yes, youre rigth sorry. Closing the issue
