### ISSUE TITLE
[Feature Request] Xml Api function songs: parameter filter optional

### ISSUE THREAD

**Issue by BLeeEZ** [ampache/ampache#2285]
## Feature Request
The parameter "filter" of the xml api  function "songs" should be changed from mandatory to optional. 

## Coherency
The xml api functions "artists", "albums" and "playlists" also have this parameter marked as optional.

## Background
In my iOS App [Amperfy](https://github.com/BLeeEZ/amperfy) I first sync the library down to the device to have offline support. The function "get_indexes" does not provide enough information for the offline library especially the song url Is missing. These informations could be gathered via a call to the function "song" for each song in "get_indexes", but this would result in a large overhead and time consumption.

## Why now?
Due to the change in the commit https://github.com/ampache/ampache/commit/cee0024f88a93e177acbd605bd54c3c7782989c5 it is checked if the parameter is provided.

**Comment by lachlan-00** [comment]
I agree that all the %object%s methods should be optional for filter.

I think we'll have to patch that in a point release before 4.2.0

**Comment by lachlan-00** [comment]
Okay so once I've gotten my test lab up properly I'll look at a test script for verification so we can put out a decent API version before patching it into master.

There are a few open bugs from ashot that I need to verify first. (No point releasing if something else doesn't work)

**Comment by lachlan-00** [comment]
closing this as it's set in develop and i'll be release a 4.1.1. preview tomorrow for the master branch
