### ISSUE TITLE
Unable to delete items from temp Playlist

### ISSUE THREAD

**Issue by StephenAtty** [ampache/ampache#2286]
### Describe the bug
Unable to delete items from a random song playlist

### To reproduc

1. Create a random song playlist
2. Click on the delete icon
3. Item does not delete
4. Error : PHP Fatal error:  Uncaught Error: Call to undefined method Tmp_Playlist::delete_track_number() in /webstuff/ampache/server/ajax.server.php:114 

## Environment

* Ampache version: Ampache 4.1.0-release
* Web server + version: : Apache/2.4.41 
* Server operating system: Ubuntu 18
* Client operating system: Chrome/Firefox on Windows 10

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

## Logs

`
[01-Feb-2020 11:23:01 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method Tmp_Playlist::delete_track_number() in /webstuff/ampache/server/ajax.server.php:114
Stack trace:
#0 {main}
  thrown in /webstuff/ampache/server/ajax.server.php on line 114
`

**Comment by lachlan-00** [comment]
I'll check it out. Thanks for reporting

**Comment by lachlan-00** [comment]
found it and reverted the change.

**Comment by lachlan-00** [comment]
fixed in develop; reverted the change that caused it.
