### ISSUE TITLE
Changes in API don't allow the fetch of all tags

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2290]
I'm the mantainer of the ampache kodi plugin. With the old api the filter set to None field in tag_albums, tag_songs and tag_artists it was possible to fetch all tags.

Now, with this patch:

https://github.com/ampache/ampache/commit/cee0024f88a93e177acbd605bd54c3c7782989c5 

it is no more possible. 

It would be possible to restore this feature?

**Comment by lachlan-00** [comment]
Yes, i'll be releasing a patch version of the api soon. it was a mistake by me.

**Comment by lachlan-00** [comment]
added back in for develop
