### ISSUE TITLE
[Feature Request] make date format configurable in catalog view

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#2292]
## Describe what you don't like about Ampache, or what it is missing
![Snag_1928cdb](https://user-images.githubusercontent.com/25564572/73953644-fd7ee180-4900-11ea-96b8-e3f294b3bbb9.png)
the date format is always in english - i would like to prefer if i could configure how the date is shown as shown above. 
## Describe how you would like the feature to work**
may there is an option in the config dialogue

**Comment by lachlan-00** [comment]
That's a good idea/question. I always thought it was defined by PHP config but never actually looked into it

**Comment by noyse27** [comment]
e.g it's in the catalog.class.php:539 format() 
below already changed to "german" format

```
public function format()
    {
        $this->f_name = $this->name;
        $this->link   = AmpConfig::get('web_path') . '/admin/catalog.php?action=show_customize_catalog&catalog_id=' . $this->id;
        $this->f_link = '<a href="' . $this->link . '" title="' . scrub_out($this->name) . '">' .
            scrub_out($this->f_name) . '</a>';
        $this->f_update = $this->last_update
            ? date('d.m.Y H:i', (int) $this->last_update)
            : T_('Never');
        $this->f_add = $this->last_add
            ? date('d.m.Y H:i', (int) $this->last_add)
            : T_('Never');
        $this->f_clean = $this->last_clean
            ? date('d.m.Y H:i', (int) $this->last_clean)
            : T_('Never');
    } 
```

**Comment by lachlan-00** [comment]
That's good. I would like it myself to use yyyy.mm.dd formats

Probably a config option like date_format would be simple enough

**Comment by noyse27** [comment]
i would prefer an option in the ampache backend so every user can change it for himself.

**Comment by lachlan-00** [comment]
That would be fine as a cosmetic only option and would be just as easy

**Comment by noyse27** [comment]
i found "Custom datetime" in ui . :) But no hint how to configure. Could you help pls?

**Comment by lachlan-00** [comment]
I haven't set it up yet. Just put the preference in.

**Comment by noyse27** [comment]
No problem 👍

**Comment by lachlan-00** [comment]
Actually about to merge this with the typing branch. I just want to add a function to fallback when the string isn't date() compatible but this will make Ampache a lot nicer for everyone.

**Comment by lachlan-00** [comment]
done in #2343

you can set your datetime to anything you want from the php date function. (including c and r)
https://www.php.net/manual/en/function.date.php

it's a good idea to include at least day month year (Y-m-d) in your string as i pull those out on some strings/urls that don't need the extra hours, min seconds, etc Those also have punctuation cut so put in whatever you want.

I set all the default to US date (which drives me insane as a euro-australian) but the setting is simple enough. 

Really glad you had this idea @noyse27 it was simple but makes things a lot easier to read.

**Comment by noyse27** [comment]
@lachlan-00 works well thx very much :)
![2020_04_15_08 24 04_polze_j_](https://user-images.githubusercontent.com/25564572/79304877-9712d280-7ef2-11ea-9232-e46acfad1366.png)

**Comment by lachlan-00** [comment]
had to revert from a lot of other issues i found

**Comment by lachlan-00** [comment]
okay i've put it back in. our types are still not perfect enough for enough so i've disabled it and put the changes back in
