### ISSUE TITLE
XML API catalog_action doesn't work

### ISSUE THREAD

**Issue by anndyd** [ampache/ampache#2296]
## Description
XML API catalog_action doesn't work, all tasks: 'add_to_catalog', 'clean_catalog'
### Describe the bug
I need to use API to refresh catalog's songs after uploading the song files.
I call the API followed the doc: https://github.com/ampache/ampache/wiki/XML-methods
catalog_action
https://<ampache_host>/ampache/server/xml.server.php?version=400001&auth=72dfac690dbb147ef593654d6f58ade8&action=catalog_action&task=clean_catalog&catalog=75

### To reproduce

1. call API handshake to get auth key
2. use got auth key to call catalog_action API, likes the following:
https://<ampache_host>/ampache/server/xml.server.php?version=400001&auth=72dfac690dbb147ef593654d6f58ade8&action=catalog_action&task=clean_catalog&catalog=75
3. nothing happens after calling, only has some logs in the service side, see the Logs

### Expected behavior
refresh song list of the catalog, remove deleted songs.

### Screenshots
N/A

## Environment

* Ampache version:  Ampache 4.0.4-release
* Web server + version: Apache/2.4.6 (CentOS)
* Server operating system: centos 7
* Client operating system: Windows 10, Chrome

### Client type

* Web

## Settings
The auth key is Admin's, has admin permission

## Logs

2020-02-11 08:29:00 [ampache] (access.class) -> check_network rpc: ip matched ACL 192.168.2.110
2020-02-11 08:29:00 [ampache] (xml.server) -> API session [d3324dcf095ce3d3474e06b4a5f7dcb7]
2020-02-11 08:29:00 [admin] (session.class) -> d3324dcf095ce3d3474e06b4a5f7dcb7 has been extended to Tue, 11 Feb 2020 09:29:00 +0000 extension length 3600

**Comment by AshotN** [comment]
Related to #2276.

**Comment by lachlan-00** [comment]
i'm up to these now. (working on it now too.) almost ready for a 4.1.1-prerelease

**Comment by lachlan-00** [comment]
actions definitely run so i'll check the "last_x" issue now.

**Comment by lachlan-00** [comment]
scratch that it's not getting to the code, will fix soon

**Comment by AshotN** [comment]
Cool, I don't know if you want to close this issue as a duplicate.

**Comment by lachlan-00** [comment]
found the error, the catalog class was looking for a request array that doesn't exist.

**Comment by anndyd** [comment]
@lachlan-00 , @AshotN ,
Many thanks!

**Comment by lachlan-00** [comment]
that's okay! There is a lot of code in here that relies on being logged into the interface which can be annoying to find.
