### ISSUE TITLE
Database cannot be replicated in MariaDB galera cluster

### ISSUE THREAD

**Issue by JohnCasey** [ampache/ampache#2301]
# Issue Template

## Description

**Describe the bug**
When installing the database the tables are hardcoded to useing ENGINE=MyISAM. This prevents the tables from being replicated in a multi-master galera cluster as only InnoDB tables support this.

**To reproduce**
1. Setup galera cluster
2. Install ampache on database
3. Schema is replicated between cluster nodes
4. all content of tables is only available on node where insert/update commands are executed

**Expected behavior**
Replicated Database should work

## Environment

* Ampache version: 4.1.1
* Web server + version: Apache 2.4.38-3+deb10u3
* Server operating system: Debian 10.2

**Comment by wagnered** [comment]
Hello @johnCasey,

Because Ampache was first presented to the world in 2001 and the galera cluster in 2007, I think this should be a **feature request** not a bug report. ( ; ' >

 You wrote: 

> This prevents the tables from being replicated in a multi-master galera cluster as only InnoDB tables support this. 

Also:

 > all content of tables is only available on node where insert/update commands are executed. 

Thats because myisam tables don't support transactions. There was no need for Ampache to support transactions in the original design. 

This implies that the problem is that the galera cluster only supports the innodb engine because it depends on a transaction on a node to trigger the replication.

 In my opinion, because Ampache was created before framework-based design became the standard, converting Ampache to a transaction based system, would be a major task.

**Comment by lachlan-00** [comment]
In my throwaway server i've converted all the tables to innodb except for tmp_browse

The structure of that table doesn't like the conversion.
![image](https://user-images.githubusercontent.com/1305249/74887317-5a30d080-53c6-11ea-8a6e-f89e1e37c56d.png)

duplicate primary keys i think
![image](https://user-images.githubusercontent.com/1305249/74887345-66b52900-53c6-11ea-8768-534d80181884.png)

it looks like the server itself is working correctly as far as logging in and browsing around.

I have no idea how that's going to affect the server but i'm working on testing at the moment in the classes

**Comment by lachlan-00** [comment]
At your own risk you can test by dropping the dual primary and altering each table.
```
ALTER TABLE `tmp_browse`
  DROP PRIMARY KEY,
   ADD PRIMARY KEY(
     `id`);
ALTER TABLE ampache.tmp_browse ENGINE=InnoDB;
```

**Comment by stebe** [comment]
I've been using InnoDB for a while now without issue, including tmp_browse. I've forgotten how I was able to do this.

![image](https://user-images.githubusercontent.com/4076671/74894709-c1ff0100-535d-11ea-956f-ab1309e729b9.png)
![image](https://user-images.githubusercontent.com/4076671/74894769-eeb31880-535d-11ea-8dfb-687bae0d7bdd.png)

**Comment by lachlan-00** [comment]
Thats good!
I was able to set it right back as well.
```
ALTER TABLE `tmp_browse` DROP PRIMARY KEY, ADD PRIMARY KEY( `id`, `sid`);
```

**Comment by wagnered** [comment]
@johnCasey,

It is experimental but the Mariadb docs indicate that starting a node with:

`--wsrep-replicate-myisam[={0|1}]`

will allow the use of myiasm tables to initiate replication.  The switch can also be added to my.cnf.  See [Galera System Variables](https://mariadb.com/kb/en/galera-cluster-system-variables).

Again, no promises.  Ampache needed to be designed  or redesigned with Galera in mind to assure proper operation.

**Comment by lachlan-00** [comment]
> It is experimental but the Mariadb docs indicate that starting a node with:
> 
> `--wsrep-replicate-myisam[={0|1}]`
> 
> will allow the use of myiasm tables to initiate replication. The switch can also be added to my.cnf. See [Galera System Variables](https://mariadb.com/kb/en/galera-cluster-system-variables).
> 
> Again, no promises. Ampache needed to be designed or redesigned with Galera in mind to assure proper operation.

That's a good find. from my searching @stebe isam has faster processing due to locking so if you're using a cluster too it might be better to revert to that?

**Comment by PaulWalkerUK** [comment]
Another benefit to changing to InnoDB is the support of foreign keys allowing for referential integrity 👍

**Comment by mitchray** [comment]
v5 now defaults to InnoDB so I'm assuming this is no longer an issue? Please reopen if I'm mistaken
