### ISSUE TITLE
[BUG] Gather All Art not finding artwork that is definitely there. New Ampache User.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2303]
## Description
Fresh install of latest Dev build of ampache, added a catalog of 951 albums, every single one has a perfectly square image but about 60 of the albums wont add the image no matter how many times I click "Gather All Art" in the admin panel.

### Describe the bug
about 2-4 albums are missing artwork per page in my library, this is a new install with a thoroughly checked library.

I perform a few checks on my library to make sure its conforming to my parameters, one checks the image exists, another checks that the images are square:

**to summarize my directory structure is:**

/audio/artist/Year - Album/01 - The First Song.mp3
/audio/artist/Year - Album/02 - The Second Song.mp3

**and every album folder has a cover.jpg, 1000x1000 pixels and less than 999 kilobytes**

below are all the checks I perform on my library:
first goto audio directory:
`cd /media/audio`

find any files other than mp3 and jpg named anything other than artist.jpg or cover.jpg:
`find . -type f \( ! -name "*.mp3" ! -name "artist.jpg" ! -name "cover.jpg" \)`

find directories missing cover.jpg:
`find . -mindepth 2 -maxdepth 6 -type d '!' -exec test -e "{}/cover.jpg" ';' -print`

find non conforming mp3s or directorys:
`find -type f -name "*.mp3" | grep -vP "^\./[a-zA-Z0-9 ]+/[0-9]{4} - [a-zA-Z0-9 \[\]\(\)',&–=#]+/([0-9]{2}|[0-9]+_[0-9]{2}) - [a-zA-Z0-9 \[\]\(\)\!'.,&–=#+]+\.mp3" | head -10`

Find non square cover.jpg images:
`find . -mindepth 2 -maxdepth 6 -type d -exec identify -format '%[fx:(h == w)] %d/%f\n' "{}/cover.jpg" ';' | sed -n '/^0 / s///p'`

find cover images larger than 999kilobytes:
`find -type f -size +999k -name "*.jpg"`

Find images that are larger than 1000px:
`exiftool -q -r -ext jpg -if '$ImageHeight > 1000' -p '$Directory/$FileName' .`
`exiftool -q -r -ext jpg -if '$ImageWidth > 1000' -p '$Directory/$FileName' .`

### To reproduce

1. Install a new instance of Ampache.
2. Add a catalog of around 1,000 albums.
3. Once Ampache is finished adding the catalog click through the pages of the library
4. See that many images are missing
5. Click Gather All Art from admin panel again.
6. See that the images are still missing...

### Expected behavior
Add all the images *OR* tell me why an image was not added, or what errors were encountered while trying to add an image.

## Environment

* Ampache version: 4.2.0-develop
* Web server + version: nginx latest
* Server operating system: Ubuntu 18.04.4
* Client operating system: Ubuntu 18.04.4 (Firefox latest)

## Settings

After install and initial setup of Ampache I set the following in ampache.cfg.php:
```
http_port = 443
album_art_preferred_filename = "cover.jpg"
art_order = "folder"
```

and in php.ini:
```
memory_limit = 1024M
```

I really appreciate any help figuring out why the missing images are not being added even though the images are absolutely there, I have triple checked!

UPDATE:

If I click into one of the albums that is missing artwork then I can click the little gear:
![image](https://user-images.githubusercontent.com/106644/74938245-7ae72f00-53a2-11ea-8fb7-14f2e3ef6165.png)

Once I click that gear it will then show the local image, and I can click select:
![image](https://user-images.githubusercontent.com/106644/74938309-9e11de80-53a2-11ea-88c9-1e77c084557d.png)

That fixes it, but I have to do that for every album that does not work with the "Gather All Art" function. This is obviously not idea and a real pain to have to double check every single time you add albums.

**Comment by kuzi-moto** [comment]
Cover art always seems to be a weird issue with Ampache. Best bet would be to enable debugging and check the Ampache logs. Nginx logs might also be useful.

**Comment by xekon** [comment]
I enabled both the ampache debug log and monitored it and nginx, the reason for the missing artworks appears to be that the scan terminates before completing, and I get a popup in ampache when it happens:
![image](https://user-images.githubusercontent.com/106644/74939762-4759d400-53a5-11ea-9a4f-a8de826080f5.png)

the ampache log zooms by adding art, until the above popup in ampache in the web browser talking about **"Server-Sent Events connection error. Re-connection..."**

the log just stops when that happens without any new info:
```

2020-02-20 13:51:12 [admin] (catalog.class) -> Gathering art for artist/110... 
2020-02-20 13:51:12 [admin] (art.class) -> Searching using:["folder"] 
2020-02-20 13:51:12 [admin] (art.class) -> Method used: gather_folder 
2020-02-20 13:51:12 [admin] (art.class) -> gather_folder: Results: [] 
2020-02-20 13:51:12 [admin] (catalog.class) -> Gathering art for album/1820... 
2020-02-20 13:51:12 [admin] (art.class) -> Searching using:["folder"] 
2020-02-20 13:51:12 [admin] (art.class) -> Method used: gather_folder 
2020-02-20 13:51:12 [admin] (art.class) -> gather_folder: Opening /media/audio/Steve Miller Band/1969 - Sailor and checking for Album Art 
2020-02-20 13:51:12 [admin] (art.class) -> gather_folder: Found preferred image file: cover.jpg 
2020-02-20 13:51:12 [admin] (art.class) -> gather_folder: Results: {"6b10acce2f99638ae387314d35b13b61":{"file":"\/media\/audio\/Steve Miller Band\/1969 - Sailor\/cover.jpg","mime":"image\/jpeg","title":"Folder"}} 
2020-02-20 13:51:19 [ampache] (session.class) -> Existing session found 
2020-02-20 13:51:19 [admin] (session.class) -> 7kil4evcniu1ououi2e39cjkfs has been extended to Thu, 20 Feb 2020 14:51:19 +0000 extension length 3600 
2020-02-20 13:51:19 [admin] (ajax.server) -> Called for page: {index} 
2020-02-20 13:52:19 [ampache] (session.class) -> Existing session found 
2020-02-20 13:52:19 [admin] (session.class) -> 7kil4evcniu1ououi2e39cjkfs has been extended to Thu, 20 Feb 2020 14:52:19 +0000 extension length 3600

```

There appears to be no clue in Nginx:
```

10.7.13.7 - - [20/Feb/2020:13:49:19 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 1844 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:50:02 +0000] "POST /server/ajax.server.php?page=index&action=sidebar&button=admin HTTP/1.0" 200 8475 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:50:04 +0000] "GET /admin/catalog.php?action=show_catalogs HTTP/1.0" 200 72389 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:50:04 +0000] "POST /server/ajax.server.php?page=browse&action=get_filters&browse_id=80 HTTP/1.0" 200 207 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:50:11 +0000] "GET /admin/catalog.php?action=gather_media_art HTTP/1.0" 200 64650 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:50:19 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 1844 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:51:11 +0000] "GET /server/sse.server.php?worker=catalog&action=gather_media_art&catalogs=%5B%5D HTTP/1.0" 499 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:51:19 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 1844 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:52:19 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 1844 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
10.7.13.7 - - [20/Feb/2020:13:53:19 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 1844 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"

```

**Comment by xekon** [comment]
UPDATE:  in ampache.cfg.php i changed this:

`art_order = "folder"`

to

`art_order = "db,folder"`

and it was then able to complete and now all albums have art. I did not plan to have it that way just incase I change or update some album art, I would like it to pull in the new art automatically whenever I do a "Gather All Art" atleast if the image had changed....

for now this works though, and im happy the rest of the albums now show the cover art.

**Comment by AshotN** [comment]
Ampache's handling of album art is kind of confusing. I'm hoping once the API is cleaned up and we start getting more advanced things into the new UI, we can make these features easier to use and more intuitive.

**Comment by lachlan-00** [comment]
it's definitely a goal to allow more single item updates instead of saying "Update 400 thousand art files!!!!" when you want to update a new album

**Comment by xekon** [comment]
I still have this problem when I do a gather art from the web interface after a clean install, its like it can only handle so many at a time before it breaks, BUT if I do gather art from the command line then it finishes complete. This is no longer an issue for me personally since I am now just using the command line.

`sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -a -g`
