### ISSUE TITLE
[BUG] Artist Image showing up as a Star, is local Image for artists possible?

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2304]
## Description
Fresh install of ampache, none of the artist images that I have locally are loaded. When I click into the albums one at a time the picture changes from a grayscale disc with a question mark to a grayscale Star image (screenshot below)

my directory structure is:

/audio/genre/artist/artist.jpg
/audio/genre/artist/Year - Album/cover.jpg
/audio/genre/artist/Year - Album/01 - The First Song.mp3
/audio/genre/artist/Year - Album/02 - The Second Song.mp3

### Describe the bug
the local artist.jpg image is not used.

### To reproduce

1. have a artist.jpg image in your directory structure per artist
2. add a catalog
3. none of the artist.jpg images are used.

### Expected behavior
If I have a local artist.jpg file it should be used instead of trying to scrape one from last.fm

### Screenshots
![image](https://user-images.githubusercontent.com/106644/74998482-ae12d800-540d-11ea-9c81-817b52ccb308.png)

## Environment

* Ampache version: 4.2.0-develop
* Web server + version: nginx latest
* Server operating system: Ubuntu 18.04.4
* Client operating system: Ubuntu 18.04.4 (Firefox latest)

**Comment by kuzi-moto** [comment]
I don't believe this is possible at the moment. A good idea as a new feature though!

**Comment by lachlan-00** [comment]
stars are the default last.fm image.
they changed the api a bit so i'm not sure what's different now.

i did write a very bad script to search for folder images in my library but there needs to be a local way for artists.
https://github.com/lachlan-00/ampache-scripts/blob/master/get_images_for_ampache.py

**Comment by lachlan-00** [comment]
i did that script using folder.jpg but i could change that to artist/ artist name and see what we can do in the gather local process.

**Comment by xekon** [comment]
Sounds Awesome! Will be happy to test if you whip anything up.

**Comment by lachlan-00** [comment]
the api has update_art which does the normal gather for individual items but we should allow sending the file path / binary string to the server in the method as well.

**Comment by xekon** [comment]
ah I see, so for albums it must already allow sending the file path / binary string? but for artist art it does not yet?

**Comment by JamesRA3** [comment]
Happening in 4.1.1 also. (remember, this is only about **artist pics** not album art - I only mention this because when I brought this up in the ampache forum, a responder thought I was referring to album art. My album art is fine.)

This is what I found in my log when I click on **artists** from the Home menu - no **artist pics** show up, only an icon with a question mark:
2020-03-18 17:29:55 [ampache] (log.lib) -> [Runtime Error] count(): Parameter must be an array or an object that implements Countable in file /var/www/html/ampache/lib/class/stats.class.php(367)
2020-03-18 17:29:55 [admin] (ampconfig.class) -> Requested a ratings filter of: 1.
2020-03-18 17:29:55 [admin] (browse.class) -> Show objects called for type {artist}
2020-03-18 17:29:55 [admin] (ampconfig.class) -> Requested a ratings filter of: 1.
2020-03-18 17:29:55 [admin] (browse.class) -> Show objects called for type {artist}
2020-03-18 17:29:55 [ampache] (log.lib) -> [Runtime Error] count(): Parameter must be an array or an object that implements Countable in file /var/www/html/ampache/lib/class/stats.class.php(367)
2020-03-18 17:29:55 [admin] (ampconfig.class) -> Requested a ratings filter of: 1.
2020-03-18 17:29:56 [admin] (browse.class) -> Show objects called for type {artist}
2020-03-18 17:29:58 [ampache] (session.class) -> Existing session found

This is what I found in my log file when I click on U2 **artist icon** (which is only a pic of a question mark):
2020-03-18 17:33:19 [admin] (ajax.server) -> Called for page: {index}
2020-03-18 17:33:19 [admin] (recommendation.class) -> search url : http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&api_key=d5df942424c71b754e54ce1832505ae2&artist=U2&lang=en
2020-03-18 17:33:20 [ampache] (log.lib) -> [Runtime Error] Illegal offset type in isset or empty in file /var/www/html/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(722)
2020-03-18 17:33:20 [ampache] (log.lib) -> [Runtime Error] Illegal offset type in file /var/www/html/ampache/lib/vendor/rmccue/requests/library/Requests/IRI.php(742)
2020-03-18 17:33:20 [admin] (art.class) -> Deleting /media/metadata/artist/64/default/ directory...
2020-03-18 17:33:20 [admin] (art.class) -> Deleting /media/metadata/artist/64/default/ directory...

The U2 artist icon changes to a star - exactly like what xekon's screenshot shows.. 

So I followed the URL shown in the log:
**http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&api_key=d5df942424c71b754e54ce1832505ae2&artist=U2&lang=en**

The URL showed HTML code on the page.

So I followed the URL on that page to what should be an artist pic:
**https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png**

Guess what it showed ---- An icon of a star!

To conclude, it may be audioscrobbler at fault or something changed on lastfm that doesn't let audioscrobbler get to the right files or location. Not sure if ampache needs to fix/change anything.

Hope this info helps, because we gotta have artist pics.

**Comment by xekon** [comment]
@JamesRA3 that is correct it is our current situation @lachlan-00 said its because of changes in the last.fm API. My proposed solution was to allow local artist images such as artist.jpg in your local file directory as an alternative solution. I actually prefer local images anyway because then I can pick exactly which ones I wish to use.

**Comment by lachlan-00** [comment]
i was doing something similar manually with a shell script (would look for a folder in the artist folder by depth)
https://github.com/lachlan-00/ampache-scripts/blob/master/get_images_for_ampache.py

There will be a way to script this using the api in the near future.
I could extend update_art to allow "update from file"

**Comment by xekon** [comment]
Looking forward to that being part of the api :)

**Comment by f1rstperson** [comment]
Is there still interest in this feature? I have some experience in php and from what i can gather, the only place artst images are retrieved is in `Recommendation::get_artist_info`. And lastfm seems to be the only hardcoded method to get the images (and all other info). I would suggest adding a new config option `artist_image_preferred_filename` to prefer local files, similar to `album_art_preferred_filename`. If it is set to anything, then `get_artist_info` could just first look at the filename given and only query lastfm if the file is not there.

If I did not miss anything and there are no objections (and I find some time), I could create a PR for that.

**Comment by xekon** [comment]
I actually saw indication that this was recently implemented https://github.com/ampache/ampache/compare/b6da7a49e293bcbc821c951f6189443c26358c4e...cacd6bda1fced4b4270317e1e0eb379dc592f6ab

I h ave not yet tested it myself but probably will today.

**Comment by lachlan-00** [comment]
I have just put in that code for one workaround.

Have a folder full of images by artist name?

Put that in and gather_folder will look for artist images!

Gather folder previously only looked for albums so that was my step one.

I do think adding an artist filename will work as well I just don't have an artist.jpg in every album folder

**Comment by lachlan-00** [comment]
The limitation of regular gather folder right now is it looks in the folder where the media file is.

I don't know many people who would put artist art there due to duplication but if you think it would work I can also do a check for that

**Comment by lachlan-00** [comment]
Oh and the file doesn't have to be a jpg like when you use folder.jpg it will match the name and the extension isn't important.

**Comment by xekon** [comment]
@lachlan-00 if the only way to make it work is to have an artist.jpg in every album then that is what I would do. I agree duplication is not great and my ideal layout would be:

/audio/genre/artist/artist.jpg
/audio/genre/artist/Year - Album1/folder.jpg
/audio/genre/artist/Year - Album1/01 - The First Song.mp3
/audio/genre/artist/Year - Album1/02 - The Second Song.mp3
/audio/genre/artist/Year - Album2/folder.jpg
/audio/genre/artist/Year - Album2/01 - The First Song.mp3
/audio/genre/artist/Year - Album2/02 - The Second Song.mp3

however if it takes putting artist.jpg into every album I would absolutely do it if it makes things easier.

I know in many systems you can look up one level by using ..
such as:
`artist_image = ..\artist.jpg`

which would look up one level for the artist image. To me this would be ideal, it would avoid duplication atleast for my directory structure. I am assuming most people use a folder for a particular artist and then store the albums for that artist below that, but maybe everyone does not do that, I am not sure.

**Comment by lachlan-00** [comment]
that's true, i didn't think of just going up a folder which is how most libraries are done. 

i'll add in search back from the media folder for preferred filename and then if you have enabled an artist filename for that as well.

for the art dump folder this is the log. (my nextcloud has all this art from a media gatherer that only works on windows!)
```
2020-06-18T08:52:44+10:00 [user] (art.class) -> Method used: gather_folder 
2020-06-18T08:52:44+10:00 [user] (art.class) -> gather_folder: Opening /mnt/data/user/files/windows/pictures/covers/Artists and checking for artist Art 
2020-06-18T08:52:44+10:00 [user] (art.class) -> gather_folder: Found preferred image file: Effigy.jpg
```

**Comment by xekon** [comment]
> that's true, i didn't think of just going up a folder which is how most libraries are done.
> 
> i'll add in search back from the media folder for preferred filename and then if you have enabled an artist filename for that as well.
> 

@lachlan-00 I can see all the commits you put out daily so I know your busy with this and that, just thought I would check in to see if there was any progress on adding the preferred filename and looking for it up one level from the media folder?

**Comment by lachlan-00** [comment]
i did start it and insert the config into my own database but then got sidetracked on a different issue.

i'll need to do another database update for a few other options as well though so it will be soon.

**Comment by lachlan-00** [comment]
@xekon 
```
2020-07-03T10:20:52+10:00 [user] (art.class) -> gather_folder: Opening /mnt/music/AC_DC and checking for artist art
2020-07-03T10:20:52+10:00 [user] (art.class) -> gather_folder: Found preferred image file: artist.jpg
```

**Comment by lachlan-00** [comment]
merged

**Comment by xekon** [comment]
I did the update from the web interface like i normally do when it sees changes.

I could not find **artist_art_preferred_filename** in my ampache.cfg.php

I then noticed this:

**config_version = 40**

so I am assuming when I pull the update the config file does not get updated and I should periodically compare this file and add the missing stuff?

**Comment by stebe** [comment]
You can generate a configure from the admin/debug page. It will keep your current settings and generate the new defaults.

**Comment by lachlan-00** [comment]
It should actually tell you config is out of date when you log in. Have to check that out

In Ampache debug you can click write new config to update.

**Comment by xekon** [comment]
Thanks, very excited to try this feature, i noticed my music would no longer play after updating.

I just generated a new config and the setting is there now but  the music still will not play.

I am trying a verify, clean, update, gather to see if that helps.

**Comment by kuzi-moto** [comment]
Same here, this will be a great feature to have. I'm not entirely excited to search for new art for all my Artists however...

**Comment by xekon** [comment]
> Same here, this will be a great feature to have. I'm not entirely excited to search for new art for all my Artists however...

lol, well i actually prefer it because then I can use high quality art that I prefer, which is exactly how I did my albums. I will however agree that it takes a good amount of time gathering high quality art, but it feels great once you get it done and have it all in place.

**Comment by xekon** [comment]
Okay so my Dsub still plays but my web client no longer plays since updating. I may just try doing a git pull.

**Comment by xekon** [comment]
not sure if it helps but the home page is now blank, maybe that is related, normally stuff used to show here like popular songs and now playing, etc:

![image](https://user-images.githubusercontent.com/106644/86501926-6a809100-bd52-11ea-8194-8fb90d0b5ba3.png)

**Comment by xekon** [comment]
So I did a little more research:

git checkout develop

I then rolled the commits back one at a time:

```
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 236601871 really bring the crazy prnts down.
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at fde7a8fca add the value to VALUES too
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 4d2e255da reduce log cruft in catalog add actions
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at ed035480b make song inserts the update time as well.
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 3607942a4 Update ui.class.php
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at b817aeedd give all the sidebar->music pages browse ability
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 4f0482c8e Update show_update_item_group.inc.php
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at d82090a2b update multidisk albums from the album page
```

Each time I rolled the commits back, I would refresh the page, once I got to HEAD is now at 4f0482c8e the home page was showing up again but music still would not play, then i did it once more, and once I got to HEAD is now at d82090a2b update multidisk albums from the album page I was then able to play music in the browser again.

**Comment by lachlan-00** [comment]
fixed those errors
i renamed a command that was still using the old name

**Comment by xekon** [comment]
hmm what is the easiest way to clear the database of art? I attempted a gather all:

```
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> gather_art found 3items missing art 
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> Gathering art for artist/254... 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Searching using:["folder"] 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Method used: gather_folder 
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> Gathering art for artist/208... 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Searching using:["folder"] 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Method used: gather_folder 
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> Gathering art for artist/239... 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Searching using:["folder"] 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Method used: gather_folder 
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> Gathering art for artist/238... 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Searching using:["folder"] 
2020-07-04T06:43:42+00:00 [user] (art.class) -> Method used: gather_folder 
2020-07-04T06:43:42+00:00 [user] (catalog.class) -> Gathering art for artist/237...
```

it does not seem to update any of the artist images (still just the blank star image), but I am wondering if its because it will only look for the artist image if the album image is not already in the db? if thats the case how can i clear the art from my db so that it scans in from files again.... or maybe thats not really the problem and something else is?

**Comment by lachlan-00** [comment]
you could also put folder above db in the gather art order and it should update it from a gather over the top of the database art

**Comment by xekon** [comment]
I tried that as well... it seems the artist art is not being scanned in, going to try and add some debug comments to the new section of code to see if i can figure out why.

**Comment by xekon** [comment]
I tried that as well... it seems the artist art is not being scanned in, going to try and add some debug comments to the new section of code to see if i can figure out why.

does artist_art_folder need to be defined in order for artist_art_preferred_filename to be searched for? Looking at the code that is what it seems like, my artist art is always up one level from the album, but i am going to try and un-comment this and see what happens.

**Comment by xekon** [comment]
I now have pictures for all my artist art and no longer looking at the blank image of the cd album with question mark. I am VERY HAPPY about this. Thank you so much for implementing it @lachlan-00

**Comment by lachlan-00** [comment]
oh, that's not meant to be required. i can see that so i'll check that now.

**Comment by lachlan-00** [comment]
fixed that, there was a check when the art folder was the only option i didn't remove.

**Comment by xekon** [comment]
Everything seems to be working great, going to close this now, thank you @lachlan-00

**Comment by lachlan-00** [comment]
Great that this one is done. This will tide us over while we find a better API to use :)
