### ISSUE TITLE
Tracks are showing the Rating set by Other users if they have not yet set a rating, leading to confusion of all users.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2310]
## Description
Tracks are showing the Rating set by Other users if I have not yet set a rating, leading to confusion of all users.

### Describe the bug
I am new to using Ampache, I have recently set it up and there are 5 users now using my server. One thing that I noticed is that tracks that I have not even listened to yet have ratings. I then noticed they were all tracks listened to by the other users. 3 out of the 5 people also complained to me that some songs have ratings that they did not set, so it seems I am not alone in thinking this is an odd way to handle ratings.

Ideally the ratings shown should only be the ratings that a given user has set themselves.

I will note however that I would love to see what other users rated the song on mouseover or something, but that can be a feature request in a separate issue report.

### To reproduce

1. Configure 2 users for your Ampache.
2. have user 1 click into an album that does not yet have any ratings.
3. have user 2 click into the same album and seting some ratings.
4. have user 1 refresh the page and see that rating they did not set are now showing.

### Expected behavior
the default view of ratings should only show ratings that the user has set themselves.
optionally on mouseover it could display the ratings of other users.

**Comment by wagnered** [comment]
@Hello xekon,

Also according to the official demo, there is a "My rating" in the search  list for songs, albums and artists  Don't these do what you would like?

null

**Comment by xekon** [comment]
the problem comes in when your listening to an album, out of hunderds of albums, and that album displays a rating, and your unsure if that is a rating you set... or if its a rating set by somebody else.

This is particularly bad if your actively listening to music and trying to set ratings for songs that you have not yet set a rating, because with the current implementation it would appear as if you had set a rating even though you had not yet set any ratings.

For example, some of my users are being exposed to a Lot of this music for the first time, there are thousands of songs. How are they supposed to remember if it was a rating they set, or a rating set by somebody else. These rating for example as I was listening to music, none of them were set by me:

![image](https://user-images.githubusercontent.com/106644/75096177-e15e7f80-5551-11ea-8f86-66d0051c8fbd.png)

**Comment by xekon** [comment]
@wagnered I did find the feature your talking about, and it looks very useful, but I honestly did not even know it existed yet. Many new users, myself included are going to play music by going the album or artist library, or possibly even the Tag cloud so they can restrict it to a particular genre.

Being restricted to selecting music through only the "My Ratings" search feature to avoid a ratings display bug or irregularity if you prefer, does not seem ideal to me...

**Comment by wagnered** [comment]
>  Being restricted to selecting music through only the "My Ratings" search feature to avoid a ratings display bug or irregularity if you prefer, does not seem ideal to me...

I suggest posing the question to lachlan-00 as a feature request and discuss the details with him.  He is in a better situation to decide if and how it might be accomplished.

**Comment by xekon** [comment]
@lachlan-00 what do you think about it?

**Comment by lachlan-00** [comment]
I like the average rating feature as it gives me an idea of what other people like but i can see why it would confuse. it's one of those "always been there" features and is aimed towards large groups of users. I tend to click a different rating then back to make sure my ratings are set which is kind of stupid.

In most ui areas Ampache:

* checks for rating by you
* if no rating, then get the average rating across all users.

I could think of two ways to do it:

* different colour stars for average ratings / text to signify average
* option to disable average ratings in the UI.

In a long term view Ampache is meant to be multi-user so I wouldn't remove average ratings completely but I agree that it's confusing without context.

**Comment by xekon** [comment]
My Ampache server is also multi user and the user ratings per song are exactly the reason I switched from Airsonic to Ampache. Having the ratings is awesome. I just really hope some context can be added.

My server currently has 5 users while I am testing, but I plan to open it up to more friends and family after I have tested and used it a bit.

**Comment by AshotN** [comment]
> I like the average rating feature as it gives me an idea of what other people like but i can see why it would confuse. it's one of those "always been there" features and is aimed towards large groups of users. I tend to click a different rating then back to make sure my ratings are set which is kind of stupid.
> 
> In most ui areas Ampache:
> 
>     * checks for rating by you
> 
>     * if no rating, then get the average rating across all users.
> 
> 
> I could think of two ways to do it:
> 
>     * different colour stars for average ratings / text to signify average
> 
>     * option to disable average ratings in the UI.
> 
> 
> In a long term view Ampache is meant to be multi-user so I wouldn't remove average ratings completely but I agree that it's confusing without context.

Funny I never knew about this, one more consideration I need to make while working on the new client then. 

I don't think using colors to differentiate is a good idea, it's an accessibility nightmare.


I would opt for a smaller text under the rating to just say something like "Avg. Rating : 3.4" or something similar.

**Comment by lachlan-00** [comment]
that's true, i didn't think about accessibility.
separating them would be better then.

**Comment by xekon** [comment]
YAY! This seems to have been fixed today, thank you! <3

**Comment by lachlan-00** [comment]
I've taken out the fallthough to averages in the object ratings.

I agree that it's confusing and don't feel that it adds benefit to include. it also reduces another random sql query that is really just going to slow things down. alternatives just provide a great benefit to include compared to just letting your ratings show.

Averages are still in the API and search which is where i think they are actually valuable

Not closing as i'm not 100% that this won't totally change.

**Comment by stebe** [comment]
Perhaps when viewing the object details that have ratings such as song, album or artist show both user and average rating on separate lines.
![image](https://user-images.githubusercontent.com/4076671/79850644-3a039a80-8392-11ea-8790-ae80270c86b0.png)

**Comment by lachlan-00** [comment]
> Perhaps when viewing the object details that have ratings such as song, album or artist show both user and average rating on separate lines.
> ![image](https://user-images.githubusercontent.com/4076671/79850644-3a039a80-8392-11ea-8790-ae80270c86b0.png)

That's a good area for it. Possibly also on artist and album pages for the object.

I like that and it makes sense when you still down you want information and details

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/79943714-f94c7400-84ac-11ea-9bca-5e360b24fc65.png)
In the details section and found a logic check for a file that hasn't existed in god knows how long.adding in the artist/album page i'm still debating a nice way of doing that

**Comment by AshotN** [comment]
Can put the average rating in parentheses next to the rating. Like `****(4.3)`

**Comment by lachlan-00** [comment]
In the artist/album header that might be a good way to do it. 
* * * * * (avg. 4.1)

Visually a second star line doesn't work on those header pages but if it looks okay that would cover all 3.

**Comment by lachlan-00** [comment]
the code sets an explicit div which makes it flow on to a second row but it looks fine and is consistent across the 3 areas
![image](https://user-images.githubusercontent.com/1305249/80052369-e2198f00-855d-11ea-967a-7a4adb92b496.png)

![image](https://user-images.githubusercontent.com/1305249/80052479-1ab96880-855e-11ea-872e-1e4e2c58d8c5.png)

**Comment by AshotN** [comment]
Probably look nicer if it doesnt show the average if there are no ratings.

**Comment by lachlan-00** [comment]
That's a much better idea

**Comment by lachlan-00** [comment]
Or at least if you have rated it. Give me the average

**Comment by lachlan-00** [comment]
okay, i'm happy that the average is out of the physical stars and that the average is shown when more than one rating is added.
