### ISSUE TITLE
Calling XML API fails as Unauthorized even after successful handshake

### ISSUE THREAD

**Issue by openhs** [ampache/ampache#2311]
## Description

When calling an XML RPC API (e.g. artists) server returns 'Not authorized' error even after successful handshake and correct permissions in ACL.

### Describe the bug

`User::get_from_apikey` is calling `User` constructor with _string_ user name which is then converted to _int_, which results to 0.  It is then assigned to its `$id` instance variable.  When `Access::check_network()` then calls `$user->id` it gets the 0 value.  Such user does not exists so `check_network` returns `false`.

Here is how it is happening.  This is after handshake, when the 'artists' API is called.  Please pay attention to '<-----' markings in the code snippets.

In xml.server (from line 64):
```
if ((Core::get_request('action') == 'handshake') && isset($_REQUEST['timestamp'])) {
    $username = Core::get_request('user');
} else {
    $apikey = Core::get_request('auth'); <----- successfully gets apikey
}

if (!Access::check_network('init-api', $username, 5, null, $apikey)) { <----- check_network returns false
    debug_event('Access Denied', 'Unauthorized access attempt to API [' . Core::get_server('REMOTE_ADDR') . ']', 3); <----- we get here
```

In access.class, function check_network:
```
        switch ($type) {
            case 'init-api':
                if ($user) {
                    $user = User::get_from_username($user);
                    $user = $user->id;
                } elseif ($apikey) {
                    $user = User::get_from_apikey($apikey);
                    $user = $user->id; <------ this is 0 (int)
```

In user.class, function get_from_apikey:
```
            // check for legacy unencrypted apikey
            $sql        = "SELECT `id` FROM `user` WHERE `apikey` = ?";
            $db_results = Dba::read($sql, array($apikey));
            $results    = Dba::fetch_assoc($db_results);

            if ($results['id']) { <----- condition is false
                return new User($results['id']);
            }
            // check for api sessions
            $sql        = "SELECT `username` FROM `session` WHERE `id` = ? AND `expire` > ? AND type = 'api'";
            $db_results = Dba::read($sql, array($apikey, time()));
            $results    = Dba::fetch_assoc($db_results);

            if ($results['username']) { <----- this is user name (string)
                return new User($results['username']); <----- constructor is called with string value
            }
```

In user.class constructor:
```
    public function __construct($user_id = 0)
    {
        if (!$user_id) {
            return false;
        }

        $this->id = (int) ($user_id); <----- result of string to int is 0
```

## Environment

* Ampache version: 4.1.1
* Web server + version: Apache 2.4
* Server operating system: Linux
* Client operating system: Linux

### Client type

* Ampache

## Settings

Settings regarding metadata and encoding were omitted
```
config_version = 40
web_path = ""
database_hostname = "..."
database_port = "..."
database_name = "..."
database_username = "..."
database_password = "..."
secret_key = "..."
session_length = 3600
stream_length = 7200
remember_length = 604800
session_name = ampache
session_cookielife = 0
session_cookiesecure = 0
auth_methods = "mysql"
access_control = "true"
require_session = "true"
require_localnet_session = "true"
use_auth = "true"
default_auth_level = "guest"
ratings = "true"
userflags = "true"
directplay = "true"
sociable = "true"
licensing = "false"
refresh_limit = "60"
show_footer_statistics = "true"
debug = "true"
debug_level = 5
log_path = "."
log_filename = "%name.%Y%m%d.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
registration_display_fields = "fullname,website"
registration_mandatory_fields = "fullname"
```

**Comment by lachlan-00** [comment]
When you handshake are you using the returned session after that?

Handshake is where you use the APIkey/password and the server returns a session that you use everywhere else.

**Comment by openhs** [comment]
Yes, the URL I am calling looks like this:

http://\<server\>/server/xml.server.php?action=artists&auth=e619ee8e9e990c5fab7ea3e538f4278c&limit=1&offset=0

It works with Ampache 3.x.  I have not changed the client code, only upgraded Ampache to 4.1.1.

**Comment by lachlan-00** [comment]
one change between 3->4 is that you can't just use your api key throughout the api.

you have to handshake
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<auth><![CDATA[eeb9f1b6056246a7d563f479f518bb34]]></auth>
	<api><![CDATA[400004]]></api>
	<session_expire><![CDATA[2019-12-05T10:25:59+10:00]]></session_expire>
	<update><![CDATA[2019-11-26T16:35:05+10:00]]></update>
	<add><![CDATA[2019-12-05T05:35:58+10:00]]></add>
	<clean><![CDATA[2019-12-05T05:35:33+10:00]]></clean>
	<songs><![CDATA[269459]]></songs>
	<albums><![CDATA[25779]]></albums>
	<artists><![CDATA[11069]]></artists>
	<playlists><![CDATA[21]]></playlists>
	<videos><![CDATA[0]]></videos>
	<catalogs><![CDATA[4]]></catalogs>
</root>
```

then use the session key in all future actions.
```
http://ampache.local/server/xml.server.php?action=tags&auth=eeb9f1b6056246a7d563f479f518bb34&filter=Rock
```

if you're doing that then it could be an ACL error.

**Comment by AshotN** [comment]
If you continue to have a hard-time with the API, I recommend you look at the code in the React-Interface branch to see how I'm interacting with the API. 

You can also hop onto Telegram for help.

**Comment by openhs** [comment]
I am using password for authentication (not API key).  I do handshake and then use returned session key for subsequent API calls like this:

`http://<server>/server/xml.server.php?action=artists&auth=e619ee8e9e990c5fab7ea3e538f4278c&limit=1&offset=0`

So the codepath that I described in the bug report -- where string `username` is passed to `User` class and there it is converted to int and assigned to `$id` -- is correct?  Why would you convert string to int?  I do not understand.  Result of such operation is always 0 and later that 0 is used in SQL select to find ACL entry which always fails (unless there is an entry for 'All' users (id = -1)).

**Comment by AshotN** [comment]
I am using username/password authentication in the React-Interface branch as well. 

Here is the Authentication code I use. https://github.com/ampache/ampache/blob/react-client/client/logic/Auth.ts#L22

Here is the code for getting the artists. https://github.com/ampache/ampache/blob/react-client/client/logic/Artist.ts#L39

I am using the JSON API, but you can just change `json.server.php` to `xml.server.php`

**Comment by openhs** [comment]
@AshotN, thanks for hints to your API usage.  I did look at it earlier and I think my usage of the API is the same.  The fact that you are using JSON API makes the difference and it seems it is the reason why it is working for you.  In `json.server.php` the `Access::check_network` method is called with **username**.  In `xml.server.php` the same method is called with **session key**.  Rest of the story what happens is in my first message.

Additionaly, the critical part of the code in `xml.server.php` of Ampache 3.x is the same as `json.server.php` in _develop_.  Therefore Ampache 3.x is working and JSON is working too.

Please see code snippets below.  Again, important parts are marked with '<-----'.

`json.server.php` v. 4.x:
```
$username =
    ($_REQUEST['action'] == 'handshake' || $_REQUEST['action'] == 'ping')
    ? $_REQUEST['user']
    : Session::username($_REQUEST['auth']);  <---- username is requested

if (!Access::check_network('init-api', $username, 5)) {  <----- username is passed
```

`xml.server.php` v. 4.x:
```
if ((Core::get_request('action') == 'handshake') && isset($_REQUEST['timestamp'])) {
    $username = Core::get_request('user');
} else {
    $apikey = Core::get_request('auth');  <----- session key is requested
}

if (!Access::check_network('init-api', $username, 5, null, $apikey)) {  <----- session key is passed, $username is null
```

`xml.server.php` v. 3.x -- note it is same as `json.server.php` v. 4.x:

```
$username =
    ($_REQUEST['action'] == 'handshake' || $_REQUEST['action'] == 'ping')
    ? $_REQUEST['user']
    : Session::username($_REQUEST['auth']);

if (!Access::check_network('init-api', $username, 5)) {
```

**Comment by AshotN** [comment]
@lachlan-00 might be able to give us some insight.

**Comment by wagnered** [comment]
The auth may be present, but has it been calculated correctly according to the wiki?  If not, the result is the user "guest".

If I remember correctly, id= 0 is given to an unregistered guest to force minimal permissions.

**Comment by openhs** [comment]
I do not think the way how the auth supposed to be calculated has changed since Ampache 3.x.  It works for 3.x so it is correct.

Also, in the debug session presented in the bug description, the value of `$results['username']` is real, existing user, not 'guest'.  I am talking about this part in user.class:
```
            if ($results['username']) { <----- this is user name (string)
                return new User($results['username']); <----- constructor is called with string value
            }
```

**Comment by wagnered** [comment]
I was going to address the user constructor, but got sidetracked.  The constructor expects an id number, but the username is being passed in.   Doesn't compute in my mind.

Looks like there is a step missing to get the user id to be passed into the user constructor

I'm not able at this time to put in a fix.  It'll have to wait for @lachlan-00 or someone else to do a PR to fix it.

**Comment by lachlan-00** [comment]
i need to sit down and fix a few open things asap but what i find interesting about this is as long as you handshake it should be working.

can you add your session table after the handshake?
```
SELECT * FROM `session`
```

and just confirm that the auth returned in your handshake matches a row in the table after auth.

**Comment by openhs** [comment]
Below are logs and SELECT results in chronological order.  Included are logs also from my client.  I have added a few additional logs into Ampache.  They start with ####.  Do not mind them except maybe '####xml' which shows `$apikey` value (see at the end the place where I put it).

Client:
```
INFO vfs.cc:105 [VFSFile]: <0x7f4e30046e70> open (mode r) http://localhost:8081/server/xml.server.php?action=handshake&auth=b1870d1f551563d47220cbc27c43c210f09a61a3a797746cb2ae2a13caa459b3&timestamp=1582824106&version=350001&user=test
```

Ampache:
```
2020-02-27 11:21:46 [ampache] (####xml) -> apikey:
2020-02-27 11:21:46 [ampache] (access.class) -> check_network rpc: ip matched ACL 10.0.2.2
2020-02-27 11:21:46 [ampache] (api.class) -> Handshake Attempt, IP:10.0.2.2 User:test Version:350001
2020-02-27 11:21:46 [ampache] (api.class) -> Login Attempt, IP:10.0.2.2 Time: 1582824106 User:test (2) Auth:b1870d1f551563d47220cbc27c43c210f09a61a3a797746cb2ae2a13caa459b3
2020-02-27 11:21:46 [ampache] (access.class) -> check_network rpc: ip matched ACL 10.0.2.2
2020-02-27 11:21:46 [ampache] (session.class) -> Unable to read session from key  no data found
2020-02-27 11:21:46 [ampache] (session.class) -> Session created: 894f5d314a639910bf106230a924dfd3
2020-02-27 11:21:46 [ampache] (api.class) -> Login Success, passphrase matched
```

Handshake finishes at this point.

SELECT * FROM \`session\` (copy&paste from Adminer)
```
ccbebe14d3c96bc234858babdc821e05	test	1582826814	1582823214	10.0.2.2	api	Audacious/3.11-devel neon/0.30.2	NULL	NULL	NULL
72927bf8001d8b061e90d620488b5efc	test	1582827279	1582823679	10.0.2.2	api	Audacious/3.11-devel neon/0.30.2	NULL	NULL	NULL
894f5d314a639910bf106230a924dfd3	test	1582827706	1582824106	10.0.2.2	api	Audacious/3.11-devel neon/0.30.2	NULL	NULL	NULL
```

Now attempt to get artists.

Client:
```
INFO vfs.cc:105 [VFSFile]: <0x7f4e30044590> open (mode r) http://localhost:8081/server/xml.server.php?action=artists&auth=894f5d314a639910bf106230a924dfd3&limit=1&offset=0
```

Ampache:
```
2020-02-27 11:23:39 [ampache] (####xml) -> apikey: 894f5d314a639910bf106230a924dfd3
2020-02-27 11:23:39 [ampache] (####user) -> results[username]: test
2020-02-27 11:23:39 [ampache] (####access) -> user: 0
2020-02-27 11:23:39 [ampache] (access.class) -> check_network rpc: ip not found in ACL 10.0.2.2
2020-02-27 11:23:39 [ampache] (Access Denied) -> Unauthorized access attempt to API [10.0.2.2]
```

And the '####xml' log is here:
```
if ((Core::get_request('action') == 'handshake') && isset($_REQUEST['timestamp'])) {
    $username = Core::get_request('user');
} else {
    $apikey = Core::get_request('auth');
}
debug_event('####xml', 'apikey: ' . $apikey, 3);
```

**Comment by openhs** [comment]
And SELECTS from user and access_list tables for completeness:

user:
```
1 | admin | Administrator |   | NULL | NULL | 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 | 100 | 0 | 1582662953 | 1582657253 | NULL | NULL | NULL | 0
2 | test |   | test@test.test | NULL | NULL | 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 | 25 | 0 | 1582659449 | 1582657414 | NULL | NULL | NULL | 0
```

access_list:
```
1 | DEFAULTv4 | 00000000 | FFFFFFFF | 75 | interface | 1 | 0
2 | DEFAULTv4 | 00000000 | FFFFFFFF | 75 | stream | 1 | 0
3 | DEFAULTv4 | 00000000 | FFFFFFFF | 75 | rpc | 1 | 0
14 | Anon Web | 00000000 | FFFFFFFF | 5 | interface | -1 | 0
9 | Test | 00000000 | FFFFFFFF | 25 | stream | 2 | 0
7 | Test | 00000000 | FFFFFFFF | 25 | rpc | 2 | 0
```

**Comment by lachlan-00** [comment]
check_network rpc: ip not found in ACL 10.0.2.2

do you have the acl's set up?
![image](https://user-images.githubusercontent.com/1305249/75490295-a6e85d00-59ff-11ea-9a2c-278c36c9af15.png)

disabling acl's will also bypass this check
```
access_control = "false"
```

**Comment by lachlan-00** [comment]
if that works we need to stop allowing handshakes with a better error message

**Comment by openhs** [comment]
Yes I do have ACL set up.  See my previous [comment](https://github.com/ampache/ampache/issues/2311#issuecomment-592100986) where I listed content of `access_list` table.  The reason for `check_network rpc: ip not found in ACL 10.0.2.2` is that in the corresponding SELECT the user id is 0 and the reason why it is 0 is explained in the first comment.

> disabling acl's will also bypass this check

With `access_control = "false"` the XML API can not be used at all.  It is a sort of security check implemented in Ampache.

**Comment by lachlan-00** [comment]
added the correct username in f183680b5042712194a1cdd14c69ee4122b2648b

**Comment by openhs** [comment]
> added the correct username in f183680

It works now.  Thanks!

**Comment by AshotN** [comment]
Glad this was resolved. This problem is part of the larger problem that the API is really messy and there are inconsistencies between XML and JSON.

All the same thanks for spotting this!
