### ISSUE TITLE
Users with independent content access

### ISSUE THREAD

**Issue by luisbalboa** [ampache/ampache#2313]
Hello, how can I create users with independent access to **Catalogs, Playlists and Streaming Channels**?

Is it possible to create a diferent users with the **Catalog Manager** permission level but that only they can access and see their content within a single installed Ampache?

Thank You

**Comment by kuzi-moto** [comment]
I believe what you're looking for doesn't exist currently. I think Lachlan was doing some work in limiting access to music for different users but I'm not sure how far along that is.

**Comment by luisbalboa** [comment]
Hello @lachlan-00 is possible, how do it?

**Comment by lachlan-00** [comment]
You can make private playlists. And authenticated channels.

Catalogs I am working on in a different code branch where you put the id in the Catalog to allow access. When that merges you can split a Catalog for each user

**Comment by luisbalboa** [comment]
OK! let me know when it is possible to perform 👍🏻

**Comment by luisbalboa** [comment]
Hello @lachlan-00 when will you finish this feature? Just update the Ampache or will it be necessary to install a plugin?

**Comment by AshotN** [comment]
I wouldn’t count the days. There is a lot to be done. We will ping you once your issue can be satisfied.

**Comment by lachlan-00** [comment]
it will just be an update, with a config item, it's currently in this branch

https://github.com/ampache/ampache/tree/catalog_filter

I don't like how some of it works but with all the work we're doing it's a this year todo

**Comment by luisbalboa** [comment]
Hello @lachlan-00 
I already updated this version catalog_filter
I creat a user: user1 pass: user1 (Catalog Manager)
https://streamusic.live/index.php

But now I can't create new music catalogs, look:
<img width="1440" alt="Screenshot 2020-03-24 at 14 32 14" src="https://user-images.githubusercontent.com/3830023/77430991-5684d500-6ddc-11ea-9a5c-425ce0682e96.png">

<img width="396" alt="Screenshot 2020-03-24 at 14 54 42" src="https://user-images.githubusercontent.com/3830023/77433246-7073e700-6ddf-11ea-9105-4783e45c7efd.png">

MUSIC PATH: var/www/html/music/user1
MUSIC URL: http://streamusic.live/music/user1/

ERROR: Failed to create the catalog, check the debug logs
[ampache.20200324.log.zip](https://github.com/ampache/ampache/files/4375604/ampache.20200324.log.zip)

See my CONFIG file please:
[ampache.cfg.php.zip](https://github.com/ampache/ampache/files/4375621/ampache.cfg.php.zip)

What do I need to do?
Thanks

**Comment by luisbalboa** [comment]
I think it may be something in the config because in the update the config is not configured, we have to do it manually and therefore some new things may not be working ... that's what I think :)

**Comment by wagnered** [comment]
@luisbalboa, 

The problem **doesn't** look like it is yours.  It looks like an SQL query problem.

Sorry, I am not able, at this time, to look at the problem.  

**To the developers:**

IMHO when a user wants to create his own catalog, the "user_filter" textbox should default to the currently logged in user.  I assume that because there is a "user_filter" anybody can create a catalog for anyone. (This could be problematic)  Unless I don't understand this feature, the user_filter textbox should be labeled "catalog owner" or "assign catalog to" for increased ease-of-use.  Filters are usually for gathering data, not storing them, which the user is actually attempting to do.

**Comment by luisbalboa** [comment]
Hello, when I change the previous Ampache files without the catalog_filter, I import the songs again into a new catalog and the SQL database is the same ...

**Comment by wagnered** [comment]
Can you log in as admin and create a catalog?  I looked at your config file and it looks ok to me.  

Not having admin privileges, I cannot look at the system preferences page. I'm not sure but I don' t think the parameters page has changed at all.

**Comment by luisbalboa** [comment]
hello, I already put user1 as admin
Please check why I can't create new catalogs with this new version catalog_filter

Thanks!

**Comment by wagnered** [comment]
Did you try to make a catalog with catalog_filter set to "false"?  If not, could you set `catalog-filter="false"` in the config file then go to or refresh the catalog page?  The "user_filter" textbox should no longer be seen and you should be able to to create a "system" catalog.  That is the way it should work.

If you can create a system catalog, the problem **is** probably a bug.  I can't see anything obviously wrong on the Ampache debug list.

**Comment by luisbalboa** [comment]
I already put catalog_filter = "false" and the problem remains because I can't import music or create catalogs:
<img width="822" alt="Screenshot 2020-03-24 at 18 28 35" src="https://user-images.githubusercontent.com/3830023/77457880-9b6d3380-6dfd-11ea-9e85-f2efcbffa78c.png">

@lachlan-00 you can help?

Thanks

**Comment by wagnered** [comment]
With `catalog_filter="false"` the catagalog_user_filter textbox should not be seen on the catalog creation page.  @lachlan-00 will have to take another look at the logic to solve your problem.

**Comment by luisbalboa** [comment]
Hello @lachlan-00,  but that option **Catalog User Filter** continues to appear and as you know I want to use it:
<img width="1400" alt="Screenshot 2020-03-24 at 19 15 31" src="https://user-images.githubusercontent.com/3830023/77462262-2f41fe00-6e04-11ea-9ae0-5b36decbc566.png">

I updated this new version and it was supposed to work: https://github.com/ampache/ampache/tree/catalog_filter

Please look the log: http://streamusic.live/ampache-log/ampache.20200324.log

Please enter a user: user2 pass: user2

**Catalog path:** /var/www/html/music

Please check! Thanks

**Comment by luisbalboa** [comment]
@lachlan-00 this version:
https://github.com/ampache/ampache/tree/catalog_filter

Is 100% resolved to work?
Can you help?

**Comment by wagnered** [comment]
@lachlan,

I think  I understand what you are trying to do. `filter_users` must be a comma separated list of user id's or a table column of type `set`.  I don't think the "catalog user filter" textbox is necessary, unless the intent is to allow the admin to create catalogs for specific users.  Of course, if that's the case, the sql statement would have to be written differently if the current user has admin privileges.

The `filter_users` variable could be cached the first time the relevant function is entered.

**Comment by lachlan-00** [comment]
catalog_filter isn't complete, it works as far as filtering the users but i want to make the artist and album search a bit faster aswell as fix all the sql changes.

**Comment by luisbalboa** [comment]
I don't have to see your content, and you shouldn't see my content ... as simple as that
it's possible?

**Comment by kuzi-moto** [comment]
> I don't have to see your content, and you shouldn't see my content ... as simple as that
> it's possible?

The main issue is that Ampache was not originally designed to have music-based permissions. It really isn't as easy as filtering by your content vs. someone else's because no one "owns" the music. Unfortunately there is a bit of work involved in adding that functionality.

**Comment by luisbalboa** [comment]
yes true, we have to see that the first version of Ampache was in 2001 a long way from the new social era that we live on the internet today... many software from that time today is already outdated and no longer used.

I have an interesting project in mind but I really need CATALOG USERS to be or can be totally independent in a single Ampache installation and a single server.

**Comment by Afterster** [comment]
Duplicate with #1378 and #1494

**Comment by luisbalboa** [comment]
It could be resolved if the Streaming Channels worked in several directories and paths of the server! 

**Example:**
/html/ampache1 ( user1) 
/html/ampache2 (user2) 
/html/ampache3 (user3) 

the problem is that Channels only work on web root path:
 /html

In my case the URL root path is:
https://streamusic.live/

Is possible Channel works in multiple instalations at the same time?

Example:
https://streamusic.live/ampache1 (user1)
https://streamusic.live/ampache2 (user2)
https://streamusic.live/ampache3 (user3)

How best way to install to have multiple Ampache accounts on the server at the same time and all of their Music Channels work for them?

Thanks

**Comment by mitchray** [comment]
I think this can be closed now that [Catalog Filters](https://github.com/ampache/ampache/wiki/catalog-filters) are in, reopen if still relevant
