### ISSUE TITLE
XML API playlist type and owner

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2314]
### Describe the bug

Unable to retrieve all playlists through XML API v400001

### To reproduce

I have two users. Created regular playlists and smartlists with both user. Some of them are private, some public.

Using "get_indexes" with "type=playlist": Returns all regular playlists, but only public smartlists.
Using "playlists": Returns only public regular playlists and only public smartlists.

### Expected behavior

Both methods should return "type = public" or "owner = current user", for both regular playlists and smartlists.

## Environment

* Ampache version: 4.1.1
* Web server + version: Apache2
* Server operating system: Raspbian GNU/Linux 9 Linux 4.19.66-v7+
* Client operating system: Android, Ubuntu 18.04.4 LTS

I know 4.1.1 is fairly old by now, but:
1. My client, Amproid, aims to support API v400001 and up
2. PHP 7.1 isn't available for Raspbian 9

### Client type

* Amproid
Probably affects others too

**Comment by AshotN** [comment]
Just to clarify, the API is not returning a private playlist owned by a different user? 

Or it's not returning the private playlists of the user making the API request?

**Comment by 4phun** [comment]
Hi,

1. Not returning the private playlists of the user making the API request: "playlists" method for both regular playlists and smartlists, "get_indexes" method for smartlists.

2. Returning playlists that are private owned by another user (returning too much): "get_indexes" method for regular playlists. This might be intentional though, but there is inconsistency as far as regular playlists and smartlists are treated by "get_indexes".

**Comment by 4phun** [comment]
I finally had some time to update my pi to "Raspbian GNU/Linux 10 (buster)" and Ampache to 4.1.1. Happy to report that this issue does not exist anymore. I'm closing it now. Thank you.
