### ISSUE TITLE
[Feature Request] Playlist song order edit

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2316]
I couldn't find anything in the API that would allow the order of the songs in a playlist to be changed. So I can try to implement it in the new React interface, this is blocking #2312

**Comment by lachlan-00** [comment]
sorting or individual tracks or both?

**Comment by AshotN** [comment]
Sorting can be done client side, I mean the order of songs.

So 

A, B, C

can be edited into

B, C, A

**Comment by xekon** [comment]
yes the current interface allows this:

![Peek 2020-02-23 22-34](https://user-images.githubusercontent.com/106644/75132743-fd1a7080-568c-11ea-84fe-99c4dba1c4ad.gif)

which is moving the position of a single track, but it would be REALLY cool if you could select multiple tracks and change their position as well as in my clementine example:

![Peek 2020-02-22 08-51](https://user-images.githubusercontent.com/106644/75097302-0527c280-555e-11ea-8872-21edbb481c67.gif)

**Comment by lachlan-00** [comment]
I'll get this into the next release.

**Comment by xekon** [comment]
That is pretty exciting, let me know if you want any feedback on anything.

**Comment by lachlan-00** [comment]
I think the way on the api is to let you input an array of id's into playlist_edit which will then let you reset the order of the original items or even just replace the items completely

@AshotN would you be happy if i did it this way?

* get playlist_songs
* Rearrange the order of the ids
* put it back in with playlist_edit

**Comment by AshotN** [comment]
I think the best way would be an key array of song IDs => new position

```
10=>3
324=>4
```

To avoid sending more data than needed.

**Comment by lachlan-00** [comment]
sounds good.

**Comment by lachlan-00** [comment]
going to try and finish this today or monday. but then i just need to document everything and update the examples.

**Comment by lachlan-00** [comment]
okay almost done here.

send array of items and tracks
```
%URLCRUFT%&items=30123&items=30124&tracks=3&tracks=4
```

playlist then sets the song id to the track number provided (new function set_by_track_number)

you can also do it in a single arraystring
```
%URLCRUFT%&items=30123,30124&tracks=3,4
```

**Comment by lachlan-00** [comment]
0d54c940f starting here but not testing tonight.

BED TIME

**Comment by lachlan-00** [comment]
playlist edit works now, i didn't realise the keys were combining on dupes so now it will allow all tracks to be updated with comma separated links

```
https://music.com.au/server/json.server.php?action=playlist_edit&auth=1234&filter=2089&tracks=1,2&items=1435,1436
```

**Comment by xekon** [comment]
Awesome! Can't wait to see something making use of it :)

**Comment by lachlan-00** [comment]
@xekon  @memen45 just wrote a json app before we've actually got it out of develop (https://github.com/memen45/SubMusic) so people are keen for more api work. :)

**Comment by AshotN** [comment]
I'll try this out in the React interface and see how it goes.
