### ISSUE TITLE
Albums of the moment will show the same album twice if it has multiple disks

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2321]
#  Description

### Describe the bug

If you have some albums with multiple disks, the album could show as many times as there are disks for the **Albums of the Moment** section. This applies even when **Album - Group multiple disks** is `enabled`.

### To reproduce

1. Go to https://site/index.php
2. Potentially see issue in **Albums of the Moment** section

### Expected behavior

I believe that any album should show once in that section if group disks is on.

### Screenshots

![image](https://user-images.githubusercontent.com/17068090/75591072-6b23b680-5a44-11ea-961a-bded760f7567.png)

## Environment

* Ampache version: Latest develop
* Web server + version: Any
* Server operating system: Any
* Client operating system: Any

### Client type

* Web

**Comment by lachlan-00** [comment]
it should, i'll need to double check the sql

**Comment by lachlan-00** [comment]
this should actually be fixed a while ago. will double check though

**Comment by lachlan-00** [comment]
i un-fixed this for the oracle checks, it will require a little change to close this one.

**Comment by lachlan-00** [comment]
maybe this is the best in the end, default to disk one with grouping and we get all the disks anyway.
6db8d22ff

**Comment by lachlan-00** [comment]
set random to only find disk 1 and then get the rest of the album if multi disk
