### ISSUE TITLE
[Feature Request] Hide playlists / smart lists in API

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2322]
It would be great to have the ability to hide playlists and smart playlists, so they wouldn't be included in API data.

Example:
I want a smart playlist with 10 random songs from the '80s by 5 specific artists.
To my best knowledge, the only way to do this to create one unlimited smart list with "Any rules" having 5 rules "Artist is Band1", "Artist is Band2" etc etc. Then create another smart playlist with "All rules" having "Smart Playlist is <playlist_above>" and "Year >= 1980" and "Year <= 1989".
Now. I have no interest in playing the first list ever, it's just there to be the base of the second list. In the client, it's just polluting the list of playlists.

Thank you

**Comment by lachlan-00** [comment]
add a hidden tag maybe?

**Comment by 4phun** [comment]
Sounds great to me

**Comment by 4phun** [comment]
...continued

I don't see a way to add tags to smart lists currently, am I missing something?

Whether it's a tag or a checkbox - the main point would be for the playlist not to show up in get_indexes (type="playlist") and other API calls, or for the XML to indicate the fact that this playlist is hidden.

**Comment by lachlan-00** [comment]
You can also combine searches into groups of rules. It's not very clear with the API I can probably document them.

You example above isn't that complicated but that or / and joins make it hard to do without a second list

**Comment by 4phun** [comment]
Yes, it's the combination of logical operators and the need for parentheses that makes it impossible (to my best knowledge) to do it in one smart list. Obviously this is just one example, there can be many scenarios when a "base list" and a "final list" is needed.

In my humble opinion, this all good and well. Logic of smartlist creation is neat and clean, and with the "Smart Playlist is ..." filter, virtually everything is possible. It's just that those "base lists" that aren't meant to be played ever are polluting the list of playlists.

**Comment by wagnered** [comment]
This might be made easier using stored procedures.

null

**Comment by 4phun** [comment]
You mean MySQL stored procs :question: :confused:

**Comment by wagnered** [comment]
Yes...

-------- Original message --------
Subject: Re: [ampache/ampache] [Feature Request] Hide playlists / smart lists in API (#2322)

**Comment by 4phun** [comment]
Decided to handle this in the client. It's going to be an option like "Ignore playlists whose name starts with something" I'll figure it out. Thank you

**Comment by lachlan-00** [comment]
I would end with _hidden so you can match smart and regular lista

**Comment by 4phun** [comment]
Not sure I understand what you mean by matching them. In good old Linux fashion I made it "starting with ." but I'm willing to change it (not released yet) if there's a good reason to do so.

**Comment by lachlan-00** [comment]
after writing it i don't have a reason to change it that would be worth the effort.
