### ISSUE TITLE
[Feature Request]XML API, Add catalog_id to get songs response

### ISSUE THREAD

**Issue by anndyd** [ampache/ampache#2325]
## Describe what you don't like about Ampache, or what it is missing
Now: XML API: getSongs response does not contain catalog id.

## Describe how you would like the feature to work**
After deleting a/some song(s) by XML API, it needs to refresh the song list. Now, only catalog_action Api can clean/update, but this Api need catalog id.
For convenience, please add catalog id to songs response.
Thanks!

**Comment by lachlan-00** [comment]
as a wider aside the catalog should actually be expanded a bit more for artist/album as i need a faster way to filter.

**Comment by lachlan-00** [comment]
i'll do some more work in here
https://github.com/ampache/ampache/tree/catalog_filter

**Comment by lachlan-00** [comment]
added to json and xml api!

in the future i'd also like to return an array for artists/albums that cross over multiple catalogs
