### ISSUE TITLE
Ampache doesn't count plays if playing without authentication

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#2327]
### Describe the bug
After commit 2296e588461f22ef4d58288596727a961797274c when you play a song in the interface as a guest (when **use_auth** is `false`) then it doesn't count it as being played, additionally it doesn't update the **Recently Played** section. This was working prior to the referenced commit.

### To reproduce

1. Set **use_auth** to `false` in **ampache.cfg.php**
2. Navigate to Ampache
3. Play any track
4. Playcount/Recently Played is not updated

### Expected behavior
Song playcount should increase by 1, and should show up in the Recently Played

## Environment

* Ampache version: latest develop

### Client type

* Web

## Settings

```use_auth = "false"```

**Comment by lachlan-00** [comment]
I disabled that to stop channels overloading the system but that's actually something that shouldn't stop this.

**Comment by lachlan-00** [comment]
Instead of blocking -1 I'll check useauth instead

**Comment by kuzi-moto** [comment]
Thanks for looking at it! It's not urgent or anything, but would be nice to have back!

**Comment by lachlan-00** [comment]
i have to look at play/index.php

i thought it was okay but this url is ignored still
```
/play/index.php?type=song&oid=2652&uid=-1&name=Apocalyptica%20-%20Heat.mp3
```

**Comment by lachlan-00** [comment]
@kuzi-moto i've set this up now in develop to record as user 0 when not using auth.
![image](https://user-images.githubusercontent.com/1305249/79839242-91882180-83f7-11ea-87fd-b2086e29c973.png)

This relys on use_auth being false or is otherwise treated as normal. (IE when auth enabled give ampache an id > 0)

have a look and see if anything else is missing.

**Comment by kuzi-moto** [comment]
Awesome, thanks for checking into it!

**Comment by stebe** [comment]
Forgot to add, that the user is admin, user 1.

**Comment by lachlan-00** [comment]
the line that fires that is
```
if (AmpConfig::get('use_auth') && $user < 1) {
    debug_event('stats.class', 'Invalid user given ' . $user, 3);
```

it must be sending a null user because the log line is supposed to give the user as well.

**Comment by lachlan-00** [comment]
it also looks like that's the ip problem. 
Incorrect integer value: '' for column ampache.ip_history.user

**Comment by lachlan-00** [comment]
i've found a lot of things that don't catch the plays so this should be okay now.

**Comment by lachlan-00** [comment]
set random to only find disk 1 and then get the rest of the album if multi disk

**Comment by lachlan-00** [comment]
lol, wrong comment.

This one is okay now though too
the plays don't require a user now
