### ISSUE TITLE
Song dropdown doesn't show up when metadata_field contains names with double quotes (") in them.

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2328]
### Describe the bug

There used to be a search option to find songs that have not been played. I think this has been removed. Therefore the #played should allow searching for 0 as a count so I can find songs that I haven't played yet.

### To reproduce

1. Go to search or random search
2. No song rule dropdown shows up
3. Click on a different search tab and rule dropdown is displayed 
4. Go back to song rule and previous tab rule dropdown is shown

### Expected behavior

Rule dropdown for songs should be displayed.
### Screenshots

![image](https://user-images.githubusercontent.com/4076671/75931480-136dbc80-5e43-11ea-871e-1d4bd1d78a9c.png)

## Environment

* Ampache version: 7dd23ece0b76d2f8f9be3d863dffe40911b29ace
* Web server + version: Apache/2.4.41 (Debian)
* Server operating system: Debian 11
* Client operating system: Debian 11

### Client type

* Web
* Ampache

## Logs

2020-03-04 18:13:30 [stebe] (browse.class) -> Show objects called for type {song} 
2020-03-04 18:13:30 [ampache] (session.class) -> Existing session found 
2020-03-04 18:13:30 [stebe] (session.class) -> r1eor4b4egdgncmd2qf4j7oj8h has been extended to Thu, 05 Mar 2020 18:13:30 -0500 extension length 86400 
2020-03-04 18:13:30 [ampache] (session.class) -> Existing session found 
2020-03-04 18:13:30 [stebe] (session.class) -> r1eor4b4egdgncmd2qf4j7oj8h has been extended to Thu, 05 Mar 2020 18:13:30 -0500 extension length 86400 
2020-03-04 18:13:30 [stebe] (ajax.server) -> Called for page: {browse} 
2020-03-04 18:13:30 [stebe] (browse.ajax) -> Called for action: {get_filters} 
2020-03-04 18:13:30 [stebe] (query.class) -> set catalog id: 0

**Comment by lachlan-00** [comment]
there is isplayed and is played by me but i wonder if it removes the zero in a variable check.

will look

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/75933622-2aa1be00-5ec6-11ea-8b99-21dee56d7231.png)
you can search true/false for all these

**Comment by stebe** [comment]
Strange, my list isn't the same.  What db table does this come from?

**Comment by lachlan-00** [comment]
Searches are part of search.class you may be missing them because of the ui setting for show_played times
```
        if (AmpConfig::get('show_played_times')) {
            $this->played_times();
        }
```

**Comment by lachlan-00** [comment]
i also realised that the 0 searches won't work because the # played searches the object count table.

There will never be 0 object counts but i think we can rearrange it based on the value of 0 to get around that.

**Comment by lachlan-00** [comment]
> 
> 
> Searches are part of search.class you may be missing them because of the ui setting for show_played times
> 
> ```
>         if (AmpConfig::get('show_played_times')) {
>             $this->played_times();
>         }
> ```

These are always recorded so they should not be filtered.

**Comment by stebe** [comment]
I had assumed the the song list was shortened and the "played" option doesn't exist.  Which I why I opened this issue to search on 0 times played.  Now after seeing your dropdown list for songs search isn't the same as mine. I did some debugging. I created a new instance and slowly copied each table from my working instance to the new instance.  As soon as I copied the metadata_field table the song search list was not show up.  Seems like something in this table is preventing showing the dropdown list for songs. When I switch to album and then back to songs tab the dropdown remains the album dropdown list.  When I empty the metadata_field table the song dropdown worked again.  So it seems something in the table is preventing the list from showing up.

**Comment by lachlan-00** [comment]
i'v taken out the played times filter, seems like the html gets screwed up with those custom fields so i'll look at why they aren't filtered literally

**Comment by lachlan-00** [comment]
I think this is in templates/show_rules.php

```
<script src="<?php echo AmpConfig::get('web_path'); ?>/lib/javascript/search-data.php?type=<?php echo (string) filter_input(INPUT_GET, 'type', FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES) ? scrub_out((string) filter_input(INPUT_GET, 'type', FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES)) : 'song'; ?>"></script>
```

should probably not be FILTER_FLAG_NO_ENCODE_QUOTES

**Comment by lachlan-00** [comment]
does FILTER_SANITIZE_URL work for you? i'll test it when i get back from work

**Comment by lachlan-00** [comment]
found it. lib/javascript/search-data.php

**Comment by stebe** [comment]
As usual you are working hard while I'm sleeping in Canada
