### ISSUE TITLE
[Feature Request] show "love" button also when userflag is false

### ISSUE THREAD

**Issue by noyse27** [ampache/ampache#2329]
# Issue Template

## Description
i do not want the Highlight section. So i deactivate it through setting userflag = false. Unfortunately now the love button in the html player is also deactivate so i cant mark a song as loved for last.fm anymore.

It would be cool when the button is shown if last.fm or another scrobbler is activated even if userflag is set to false.

The highlight Section:
![20200313215018](https://user-images.githubusercontent.com/25564572/76659146-ec676700-6575-11ea-96d7-65e73d9392f5.png)

The love button:
![20200313215358](https://user-images.githubusercontent.com/25564572/76659230-25074080-6576-11ea-8e35-c1a83f74755b.png)

as a workaround i hardcoded that the highlight section will not be shown when i am logged in ;)

* Ampache version: 4.1.
* Web server + version: apache 2.4
* Server operating system: dsm 6.0
* Client operating system: w10

**Client type:**

* Web

**Comment by lachlan-00** [comment]
Why would you disable them and want them?

**Comment by noyse27** [comment]
the highlight section for me is waste of place. if there is any other option  to disable them with no setting userflag to false - pls tell me :) 
The love button i use to mark songs as loved on last.fm when using ampache.  my desktop audio program uses the loved markers for generating playlists.

**Comment by AshotN** [comment]
I don’t think Ampache can accommodate to an infinite number of styling preferences. If you managed to get the change you want I’d say the issue is resolved.

**Comment by lachlan-00** [comment]
Can you screen the highlight section?

I can get trying to hide things not used but userflag covers a lot of interface/server ability so you should keep it on

**Comment by noyse27** [comment]
@lachlan-00 
![20200315182222](https://user-images.githubusercontent.com/25564572/76706734-29ed0100-66ea-11ea-84a4-2a3555ac296e.png)

may it would help to check if the favorites are from the myself or other users. It makes no sense for me that my own favorites are also displayed there. After all there are the favorites sections in the site menu.
Since I am the only active user with me, this solution would be ok for me. If that makes sense for you too.

that is what i have changed:

modules/plugins/CatalogFavorites/CatalogFavorites.plugin.php

LINE 108

```
public function display_home()
    {
        if (AmpConfig::get('userflags') && Core::get_global('user')->id != 2) {
```
thats why i know that user->id ==2 is me ;)

**Comment by lachlan-00** [comment]
you know that's actually  just a plugin that you can disable.
![image](https://user-images.githubusercontent.com/1305249/76713065-d4583900-6769-11ea-9216-a82cbe49e26e.png)

**Comment by noyse27** [comment]
What plug in do you mean? User flag or the highlight area? I just gone through the settings and didn't found a configuration for this. User flag has been set direct in the config file. But this is not a option for me, because it remove the love button in the player.

**Comment by lachlan-00** [comment]
catalog favorites is the plugin that shows the highlighted favourites on the homepage

**Comment by lachlan-00** [comment]
i'll look up the translation on transifex now.

**Comment by lachlan-00** [comment]
Katalog-Favoriten auf der Startseite

**Comment by noyse27** [comment]
Perfect could you please show me where I can find the setting in a screenshot?After this I will close this issue Am 16.03.2020 06:55 schrieb lachlan <notifications@github.com>:
catalog favorites is the plugin that shows the highlighted favourites on the homepage

**Comment by noyse27** [comment]
thx i found it 👍

**Comment by lachlan-00** [comment]
For reference for others the link is 

admin/modules.php?action=show_plugins
