### ISSUE TITLE
non-existent resources 4.1.1

### ISSUE THREAD

**Issue by yusaiku** [ampache/ampache#2330]
The following requests are returning 404/410 responses. Either fix the broken links, or remove the references to the non-existent resources.

https://.../lib/components/jQuery-File-Upload/js/jquery.fileupload.js
https://.../lib/components/jQuery-File-Upload/js/jquery.iframe-transport.js
https://.../modules/jquery-mediaTable/jquery.mediaTable.css
https://.../modules/jquery-mediaTable/jquery.mediaTable.js

**Comment by lachlan-00** [comment]
file upload is in a different folder but mediatable has been removed

**Comment by yusaiku** [comment]
Yes but the files not exsist. ampache programcode say error. fix it?

**Comment by wagnered** [comment]
@yusaiku,

If the lib/components folder does not exist, you are probably trying to run the develop version without proper installation. This version requires the installation of composer. see the [installation wiki](https://github.com/ampache/ampache/wiki/Installation). 

The zip package of the [release](https://github.com/ampache/ampache/releases) version should contain the complete product and is meant to be "drop-in" for users who can't or don't want to install composer.

**Comment by yusaiku** [comment]
I have installed the master version 4.1.1 and in this version there is the folder lib/components.

But there are no folders there:

/jQuery-File-Upload/js/jquery.fileupload.js

and in the folder modules there are none:

/jquery-mediaTable/jquery.mediaTable.css

etc.

As a request for a page test I get this as an error because these things are not available.

I think you have probably deleted them but in the ampache config it is still in the ampache so that you get this as an error when you do a page test the .js or .css miss

**Comment by wagnered** [comment]
@yusaiku,

You wrote:

> I think you have probably deleted them but in the ampache config it is still in the ampache so that you get this as an error when you do a page test the .js or .css miss

What page test are you referring to?  I haven't worked on Ampache since V3.9.0 but the only "page test" I remember is the one during set-up.  Generally, missing .css or .js files are not fatal.  They just affect the appearance and operation of buttons, etc.  Perhaps commands were added to the set-up test page to check for key .css and .js files.

Could you try the 4.1.1 develop branch?  Perhaps a problem began when the 4.1.1 develop branch was merged with the master branch.

Regards....null

**Comment by yusaiku** [comment]
i check my site with gtmetrix.com

**Comment by yusaiku** [comment]
Oh Thanks i have the error found. i have a old header.inc.php ;)  Thank you very much
