### ISSUE TITLE
Amazon API5 changes from xml to json

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2333]
### Describe the bug

Not really a bug, but I got this notification that Amazon is changing their API to version 5.  Does this affect Ampache working with Amazon for images at all?

Hello associate,

As of March 9, 2020, we started the shutdown of Amazon’s Product Advertising API version 4.0 (PA API 4). Your applications calling PA API 4 to retrieve Amazon product information will experience service disruption. To avoid this service disruption, please upgrade to Product Advertising API version 5.0 (PA API 5) as soon as possible, if you have not already done so.

We remain committed to helping our associates with technology and tools. As customers’ needs continue to evolve, we will be releasing new features to PA API 5 in the coming months

https://webservices.amazon.com/paapi5/documentation/?ref_=pe_3519780_486656220
https://webservices.amazon.com/paapi5/documentation/migration-guide.html?ref_=pe_3519780_486656220

**Comment by lachlan-00** [comment]
I haven't set up Amazon before what do i need to set up an account for testing?

**Comment by lachlan-00** [comment]
The first thing i see is that they're moving to json over xml so it's probably going to stop working until that's sorted.

**Comment by lachlan-00** [comment]
modules/infotools/AmazonSearchEngine.class.php is what needs to be updated to handle these changes.

**Comment by stebe** [comment]
Originally I had signed up for a product advertising account through Amazon AWS but I'm checking now and their policy has changed and it's no longer free or associated with AWS and I'll have to migrate over to their new structure. So I think I'll not use their API in the future.  I'm not even sure I need to register to get Amazon art.
