### ISSUE TITLE
Please stop coding ... 

### ISSUE THREAD

**Issue by MarieSoukaina** [ampache/ampache#2340]
Hello, 
can't install ampache because of an error in the installation with dropbox php sdk.
Your wiki isn't up to date, because you seemed to have dropped this features in your dev, but I can't continue the installayion.

Please, if you can't code something that work, don't do it.
I don't want to waste my time anymore :)

**Comment by lachlan-00** [comment]
This is fixed in develop and I will patch the composer file in master.

We don't control Dropbox which deleted the repo after 4.1.1 released.

Please do not make comments like this towards people who do this for free and fun.

**Comment by kuzi-moto** [comment]
This problem has to do with a repository that was deleted, outside of our control. To bypass the error simple do this `composer remove dropbox/dropbox-sdk`.

Code would never be committed to Ampache knowing that it wasn't working. With that said, mistakes can happen and the Ampache team makes sure to take care of issues as quickly as possible.

**Comment by AshotN** [comment]
To add a note, it's called the dev branch because it's not stable. Don't install it if you don't want to deal with issues.
