### ISSUE TITLE
SSL Error opening https://ampache.org

### ISSUE THREAD

**Issue by derhagen** [ampache/ampache#2341]
Opening https://ampache.org results in the following error:

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for ampache.org. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by lachlan-00** [comment]
we don't use the https site in any links, volmerk has to update the dns and he hasn't done so in the last year that i've asked.

There isn't any need for https in the site as well but i would like it to happen at some stage.

**Comment by AshotN** [comment]
@lachlan-00 what is this a duplicate of? 

I am getting the same SSL error, and frankly I don't think we should close this issue. Even though our website has nothing that would benefit from SSL, it's become a standard at this point to have SSL. It's also a negative on SEO to not have SSL setup.

**Comment by lachlan-00** [comment]
The Ampache website has a repo and has an open issue for this
