### ISSUE TITLE
Server does a poor job scaling down images

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2344]
I have meticulously collected pristine cover art for my albums, most are 1000px square and about 950kb. Currently the covers are reduced to 150 x 150 and approximately 8kb. I would like to change this to 200 x 200 and increase the quality of the image... when I reduce most of my images in GIMP to 200 x 200 it usually results in a file around 80kb when exported at 100% quality.... so I see no reason to drop it to 8kb....

My understanding is that the first step would be to create a new theme based on the existing one and make adjustments.

Inspecting the element in Firefox shows:

https://amp.example.com:7070/image.php?object_id=4841&object_type=album&thumb=11&fooid=16485

I noticed I can modify the "thumb=" value and it shows me other sizes, for instance changing that to thumb=14 gives me an image that is 200x200 px in size, so i am assuming its possible, however the file size is still really low like 9kb and the mosquito noise as a result of the massive compression looks pretty bad.

Before taking possibly days diving into the code and trying to figure out how to make these changes I wanted to see if anybody else has already done so? If so I could just use whatever theme/changes they have already made...

I did notice one of the demo sites has 200x200 px, but the file size is still really low for album covers: https://play.dogmazic.net

**Comment by kuzi-moto** [comment]
I don't remember the details off the top of my head, but the function that reads thumb=10 value has a few other values to change the quality.

I think it needs to be reweitten however, because it doesn't make a lot of sense, and there are only a few resolutions to choose from. I ran into this issue while looking into making a better mobile interface. Default options are not good enough.

**Comment by Meinux** [comment]
Hi there, 

i have had the same issue. 
 I solved it by changing in my ampache-config.
Album Art minimum width and hight does the job for me.

Meinolf

**Comment by xekon** [comment]
Ah, I found that setting in the config file, I changed and saved it then rebooted, but the art is still 150. I am thinking maybe I needed to do this on a fresh install before scanning a catalog in. Maybe I can figure out how to wipe all the cover art from the DB, then I could do a new gather art.

**Comment by Meinux** [comment]
It will not change automatically. 
Only new imported albums are affected. 
I am currently working on my database to change the hole album arts to the better solution oneby one.

**Comment by stebe** [comment]
If you take out the db line from the art_order config option it will rescan over existing art.

; Art Gather Order
; Simply arrange the following in the order you would like
; Ampache to search. If you want to disable one of the search
; methods simply leave it out. **DB should be left as the first
; method unless you want it to overwrite what's already in the
; database**
art_order = "db,tags,folder,musicbrainz,lastfm,TheAudioDb,Amazon,google"
to
art_order = "tags,folder,musicbrainz,lastfm,TheAudioDb,Amazon,google"

**Comment by xekon** [comment]
Did not work, I set it to folder only and have tried gather art several times, the images are still 150px.
I will connect with the database manually later and see if I can drop all the exiting album art.

art_order = "folder"

**Comment by xekon** [comment]
I just found something by searching and browsing the issues tracker: https://github.com/ampache/ampache/issues/1410#issuecomment-553684208

```
cd /var/www/ampache
php -f bin/clean_art_table.inc
```

This also did not work, It seems to me that my settings in the config are not being honored:

album_art_min_width = 200
album_art_min_height = 200

**Comment by xekon** [comment]
As nice as it would have been to simply set:

```
nano /var/www/ampache/config/ampache.cfg.php
album_art_min_width = 200
album_art_min_height = 200
```

and be done, it seems thats not really going to work. I will go back to trying to make a modified theme from the rebork dark theme, that uses the larger images.

**Comment by lachlan-00** [comment]
the theme resizes the images dynamically. But you want the default size to be larger?
custom css can do that but it probably won't work out easily.

The images are resized no matter what the source size is which i think is not what you want to do

**Comment by AshotN** [comment]
I think the issue is that `image.php` is doing a poor job of down-scaling the image. Reborn isn't doing the re-sizing, the server is.

**Comment by AshotN** [comment]
Ampache is using this to generate a thumbnail, https://www.php.net/manual/en/function.imagepng.php

The default compression is level 6, from 1-9. That might be the reason the down-sized image is so blurry,

**Comment by AshotN** [comment]
Ok, I think the issue is with the thumbnail generation. I'll try to tackle this issue in a way that doesn't significantly increase file sizes but maintains quality.

**Comment by AshotN** [comment]
It seems that https://www.php.net/manual/en/book.image.php may be the issue. I think the only solution would be to use something like ImageMagick, but that's a separate dependency to add to Ampache.

**Comment by mitchray** [comment]
I believe this would be solved with pull #2720

**Comment by xekon** [comment]
Thanks, once I get a little free time I will try implementing that pull request.

When I am browsing albums or artists  would be nice to see a larger image, the 150x150 px is small.

Ideally it would only use 150x150 px if on a tiny screen like mobile. If I am on a desktop I would prefer larger images.

**Comment by xekon** [comment]
I have been happy with this change :) Going to link to how I increase the physical size of the images and close this issue: https://github.com/ampache/ampache/issues/2779#issuecomment-817302382
