### ISSUE TITLE
Using an empty Smartlist in an "any rule" Smartlist empties it.

### ISSUE THREAD

**Issue by Silaor** [ampache/ampache#2345]
### Describe the bug

I'm just starting with ampache, and I'm building Smartlists on a fresh docker install.

I want to make a Smartlist regrouping several others : Some 5 stars songs, some 4 stars, and some unrated but played songs I have to rate.

I used a Smartlist with "any" rules, each rule being "Smartlist is ..."

If the unrated Smartlist is empty, then the "any" smartlist is empty too.

### To reproduce

1.  Make an empty  smart playlist List1
     I used another an empty rating (not 1* and not 2* and not 3* and not 4* and not 5*) and played more than 5 times playlist
2. Use another, non-empty smart playlist List2
3. Make a Smart Playlist List3 with:
     Match "any" rules 
     "Smart playlist" "is" List1
     "Smart playlist" "is" List2

### Expected behavior

List3 contains all of List2 songs but is empty.
If I tweak List1 to not be empty (like lower play count to 1) then List3 is correctly puplated with songs from both List1 and List2.

## Environment

* Ampache version: docker version df741a76dbc7449ae2e2b8d6d5c651f4c4201e87 (Tried updating but it didn't work - got a screen flashing fast that it downloaded and ran a command but version didn't change in the "Ampache Debug" view)

**Comment by lachlan-00** [comment]
i'll be doing a big test/fix on searching/lists soon for this. i use them pretty extensively but it's very convoluted.

**Comment by lachlan-00** [comment]
Hey this should be fixed now. i've tested it with an intentionally empty list and it's okay

**Comment by Silaor** [comment]
Just tested it, seems to work for me too. Thanks !

**Comment by lachlan-00** [comment]
Exactly what I like to hear. If you have any more search issues let me know in a new issue. :)
