### ISSUE TITLE
Extracted (album) artwork extremely blocky/pixely

### ISSUE THREAD

**Issue by GottemHams** [ampache/ampache#2346]
## Description
For an unknown percentage of songs it seems that ampache is unable to properly extract the album artwork from the ID3 tags, which somehow ends up extremely blocky. However, the original image that's embedded in the file is of proper quality.

### Screenshots
![Artwork comparison](https://user-images.githubusercontent.com/20195269/78697446-199eff00-7901-11ea-9dd0-a36cc2bbc486.png)

## Environment
* Ampache version: 4.2.0-develop commit 27109b53f68267a02a21497c9bede5acbd4c45b8
* Web server + version: nginx 1.10.3
* PHP SAPI/version: PHP 7.4.4 (fpm-fcgi) (built: Mar 20 2020 14:24:19)
* Server operating system: Openmediavault 4 (Debian Stretch based mediacenter distro)

## Settings
I think the PHP modules I'm using might be relevant, but everything recommended by the debug page (`test.php`) should be active:
```
$ php-fpm7.4 -m
[PHP Modules]
bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by kuzi-moto** [comment]
It could be that you have your art gathering priority set in a way that it's not checking the tags first.

**Comment by GottemHams** [comment]
Actually, it is:
`art_order = "tags,db,folder,musicbrainz,lastfm,google"`

I also made sure it wasn't using old art so I removed the catalog entirely and readded it, with the same result. I'm not using disk storage for artwork (yet).

**Comment by AshotN** [comment]
Potentially a duplicate of #2344

**Comment by GottemHams** [comment]
That one didn't come up in my searches before posting this issue, but it does sound similar so I'll keep an eye on that one too.

**Comment by mitchray** [comment]
I haven't seen this be an issue since outputting the images @2x #2720 so I think we can finally lay this to rest
