### ISSUE TITLE
Regression from pull #2348

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2356]
https://github.com/ampache/ampache/blob/917abefcec48f8778a641d605a9f6a17ca703b78/lib/class/xml_data.class.php#L658

`$playlist_data` is never used. I think we forgot to remove it after https://github.com/ampache/ampache/pull/2348

But we did remove it when we are calling the function. For example
`echo XML_Data::songs($songs, $user->id);`

So we messed up in the sense that the `$user_id` field is not being set, and instead we've been setting `$playlist_data` to the user ID.

**Comment by lachlan-00** [comment]
i'm about to pull the string out of include calls so i'll do that now as well

**Comment by AshotN** [comment]
I'm more ashamed that this slipped by. 

We really do need unit tests.

**Comment by lachlan-00** [comment]
that's a this year goal for sure.

**Comment by lachlan-00** [comment]
i haven't really found any decent documentation about writing them yet either. it's not easy to pick up in the middle of this codebase

**Comment by AshotN** [comment]
Only test I've ever written in PHP was using Laravel. I'll look into what we can use, and see if I can write up an example.

But for the API we don't really need to write it in PHP do we? We can do it in any language as long as we have a server to test with.
