### ISSUE TITLE
Shares No Longer Working

### ISSUE THREAD

**Issue by Ford4D** [ampache/ampache#2367]
Before it was working, but now I get this error on all my shares, new or old, no matter how high I set the expiration dates or play counts:
"You have been redirected to this page because you do not have access to this function

If you believe this is an error please contact an Ampache administrator

This event has been logged"

These produce nothing in the error log. I've tried several different versions of PHP on my server from 5 all the way up to 7.4, but nothing fixes the issue. I even updated Ampache to the latest version. Nothing. Can't figure out why this is happening out of the blue. I had barely used it since it was working.

Again, doesn't even work with new shares created from scratch. Tested on several browsers and devices. Please help.

Any help would be appreciated. Thank you.

**Comment by Ford4D** [comment]
More extensive testing has shown that only SOME of the playlists share links don't work. I was able today to create both a share link that worked and a share link that didn't work for the same playlist

**Comment by lachlan-00** [comment]
are the links that work different?

i haven't been able to break shares so it would be good to see logs accessing the share and during creation

**Comment by Ford4D** [comment]
So I've discovered that it only happens when certain secret codes are set. 

A given secret code that doesn't work will return this error no matter how many times I try to make a new share with the same code.

I guess there's something about certain characters or combinations of characters that makes them not work. It's usually longer ones that fail. I'm not sure if hyphens affect it.

**Comment by lachlan-00** [comment]
That's great to know. I should be able to find that!

**Comment by lachlan-00** [comment]
The secret code is only alphanumeric (0-9+a-z)

Do you have a bad link I can check?

**Comment by lachlan-00** [comment]
okay there is another share issue that probably fixes this for you too

**Comment by lachlan-00** [comment]
should be fine now.
