### ISSUE TITLE
Subsonic API returns lyrics of wrong song

### ISSUE THREAD

**Issue by jleipsig** [ampache/ampache#2374]
## Description
When retrieving song lyrics with Subsonic API, the lyrics of another song are returned. You always get the lyrics of the same song, no matter what request you send to the API.

In 'getlyrics' of Subsonic_Api, a query is built with 'rule operator' set to index 5. This turns out to be the operator 'not equal'. Changing it to index 4 ('equal') solves the problem.

A patch for version 4.1.1  is attached
[Change_operator_for_query_in_getlyrics_from_'not_equal'_to_'equal'.patch.gz](https://github.com/ampache/ampache/files/4581187/Change_operator_for_query_in_getlyrics_from_.not_equal._to_.equal.patch.gz)

## Environment

* Ampache version: 4.1.1
* Web server + version: Apache 2.4.38-3+deb10u3
* Server operating system: Debian Buster
* Client operating system: Android

### Client type

* SubSonic

## Logs

apache.log
```
192.168.1.10 - user [04/May/2020:23:54:38 +0200] "GET /ampache/rest/getLyrics.view?u=user&p=enc:key&v=1.2.0&c=DSub&artist=Some+Artist&title=Some+Title HTTP/1.1" 200 2350 "-" "DSub"
```
ampache.log
```
2020-05-04 23:54:38 [ampache] (access.class) -> check_network rpc: ip matched ACL 192.168.1.10
2020-05-04 23:54:38 [user] (subsonic_xml_data.class) -> API success in function getlyrics-1.13.0
```

**Comment by lachlan-00** [comment]
what a great find! glad to see that you were able to parse the rules/operator parts of the code.

**Comment by lachlan-00** [comment]
merged your pull

**Comment by lachlan-00** [comment]
@jleipsig could you tell me how you found the difference in operator and how we could show that information better?

i really struggled as a newbie to the code and i want to make it easier forothers.

**Comment by wagnered** [comment]
@lachlan-00 wrote:

> @jleipsig could you tell me how you found the difference in operator and how we could show that information better?

I'm not sure he is 'watching' this comment, so I took it upon myself to investigate since I have nothing better to do :smile:

I believe that the index of the operators are set in `Search::set_basetypes()`.  Although the order of operators do not agree with @jleipsig's comment, he might have used the 'trial and error' method.

Hardcoding the operator index in `Subsonic_Api::get_lyrics()` is problematic.  What if someone decides to edit set_basetypes and change the order of populating`basetypes['numeric']`?

I suggest that after initializing `Search` that the index for 'equal' be found using `array_search` on `Subsonic_Api->basetypes`.  Actually a 'getter' function to return `basetypes` should be added to class Search.  With a getter function, the return type only has to be defined once and not typecast in every function accessing `Search->basetypes`.

**Comment by jleipsig** [comment]
Sorry for my late reaction and thanks for stepping in @wagnered . Indeed I stumbled with some trial and error upon the `Search::parse_rules` function. Still didn't get it at first, and later assumed that Artist and Title were text `basetypes`, and changed the index to 4 ('equal') which worked! Later, when trying to understand why it worked, I followed `Search::name_to_basetype` through to `Search::songtypes` to confirm that 'artist' and 'title' were of `basetype` 'text'.

The hardcoded index is indeed problematic and I think the suggestion of @wagnered makes it less vulnerable and improves readability.

After this improvement, it's still hard to read how the query data gets parsed inside de `Search` class. Some extra commenting could help. For example the line `$this->basetypes[$this->name_to_basetype($value)][$data['rule_' . $ruleID . '_operator']]['name']` in `Search::parse_rules` is not exactly an easy read.

The names of variables and functions in `Search` are not always very helpful when trying to wrap your mind around the thing. The array `Search::basetypes` defines comparison operators. The array `Search::types` contains field definitions. Renaming them could make it easier to understand.
The function `Search::songtypes` populates field definitions for song searches, so maybe it would be helpful to name the action (like 'populate' or 'define') in the function name.

**Comment by wagnered** [comment]
@jleipsig,

My apology, it's  been a very long time since I've done any serious work on ampache:  I should have been thinking  'text' not 'numeric' .  


To be more precise, an `array_search` should be done on `Subsonic_Api->basetypes['text]` for 'equal'.

>  Some extra commenting could help.

The problem is that "coders just wanna code".   "Ba humbug" on documentation. Although @lachlan-00 is doing an admirable job  with the wiki and user manual.

You are welcome to contribute. I think you could manage this improvement.  I suggest not changing the names of existing arrays unless you have a good IDE that will show you all references to those arrays so none are overlooked.

I'd like to see a logic flow diagram of each feature.  The problem I think is that anonymous functions (closures) would make this very difficult or complicated.

**Comment by jleipsig** [comment]
I did some renaming like proposed earlier. The renamed variables `types` and `basetypes` are public, which makes it a bit tricky. The only references I found were in lib/javascript/search-data.php. The variable names are not changed in the generated javascript, so this leaves it somewhat inconsistent. 
Also cleaned up some duplicate code and used named keys instead of numeric keys in `Search::rules`, to make it easier to read. There are no big logic changes in the code.

Like discussed a function `get_operator_index_by_name` is added - nothing fancy, just an array loop that was already used in the class. It's private for now, but could be made public static for `Subsonic_Api` etc.

I did some testing from the web interface, smartlists and api, but not very extensive.

See the attached patch file [searchclass-renaming.patch.gz](https://github.com/ampache/ampache/files/4596121/searchclass-renaming.patch.gz) or you can see the changes in the [searchclass_renaming branch on jleipsig/ampache](https://github.com/jleipsig/ampache/tree/searchclass_renaming).

Don't feel obliged to use anything of it. It was a nice exercise to understand the Search logic a bit better.

**Comment by jleipsig** [comment]
The initialization of the rules array was moved, which alters the logic, so i restored that (updated patch attached [searchclass-renaming.patch.gz](https://github.com/ampache/ampache/files/4599133/searchclass-renaming.patch.gz)).
Also I realized that using named indexes in rules will require a database upgrade for existing smartlists. So maybe this is too drastic, and should be reversed.
After renaming the public arrays `types` and `basetypes` it could be a good moment to make them private and write a getter.

If you want me to continue, please let me know @lachlan-00 or @wagnered.

**Comment by wagnered** [comment]
> If you want me to continue, please let me know @lachlan-00 or @wagnered.

I will defer that decision to @lachlan-00 as I am not able to set up a test environment.

A major PR such as you suggest probably would require a means of tracking down all dependencies of any changes made.  If you haven't done so already, I suggest setting up an Integrated Development Environment or IDE such as [PHPstorm](https://www.jetbrains.com/phpstorm), [netbeans](https://netbeans.org/), [Aptana Studio](https://www.aptana.com/) or [Eclipse](https://www.eclipse.org/downloads/packages/). The last three are open source.  I am familiar with Eclipse which has a bit of a learning curve.

Also if you haven't already done so, please get familar with the [Ampache coding standards](https://github.com/ampache/ampache/wiki/Coding-Standards).

>  Like discussed a function `get_operator_index_by_name` is added - ... 

PHP was based on the array and has very powerful commands built around manipulating them.  For example, I believe my suggestion of `array_search()` could do exactly what your function will do as it will return the index of an item.  I suggest that before spending time writing a function to manipulate an array, check [php.net](https://www.php.net/manual/en/language.types.array.php) for an array function that might do what you want.  If I remember correctly there are over 60 built-in array functions.

>  Also I realized that using named indexes in rules will require a database upgrade for existing smartlists. So maybe this is too drastic, and should be reversed.

Will it really? 

Welcome to the Ampache contributer club :smile:

**Comment by lachlan-00** [comment]
@jleipsig  I really like these ideas and making it more human readable rules but i would be concerned that we change things breaking the API.

UI and subsonic are pretty simple to update but it would affect every api program if we changed operators on them so it would need to support int and string operators at least for the moment.

If you think you can support both (int/string) easily i'm more than happy to merge it. even just the renaming of functions is actually a lot clearer just from applying your patch it made a lot more sense in my head.

You should keep going make your own pull as i never like to merge other peoples work under my own name in the repo. i don't care even if it's a few lines i want everyone to be recognised for their work.

Understanding Ampache search is almost like passing an exam. one of my first pulls that @wagnered merged was for search and I still had to fix it up later when i knew more of what i was doing. :/

**Comment by daetsch** [comment]
Many thanks for that! Applied Change_operator_for_query_in_getlyrics_from_'not_equal'to'equal'.patch.gz and Lyrics in DSub now works correctly.
