### ISSUE TITLE
Allow Podcasts to use Proxy configuration in Ampache.cfg.php

### ISSUE THREAD

**Issue by jwhips** [ampache/ampache#2379]
First - apologies as I don't know if this is expected behavior or a bug...

The Podcasts subscribe uses a direct connection and does not utilize the Ampache.cfg.php .  I'm using a very basic squid outbound proxy on port 3128.  I'm blocking all other traffic.  The proxy works for catalog updates , album updates, etc.

For example: In subscribing to http://podcasts.joerogan.net/feed - it will fail (access denied) and I can see my firewall blocking 64.207.186.195:80 .  If I whitelist this connection, subscription is successful, albeit, it will not pull down album art or episodes.

Can we get podcasts to respect the proxy configuration?

If you'd like more on my setup, I'd be happy to share. Thanks for the awesome product!

**Comment by wagnered** [comment]
Hello @jwhips

I investigated the specs of a podcast feed xml file and learned that it requires an 'image' section if it is to offer any art. if you look at http://podcasts.joerogan.net/feed, you will see that it doesn't contain the required section.  Ampache does check for the image section and if it is not found, silently finishes the podcast creation.

**Comment by jwhips** [comment]
Thanks for the response.  

I think you may have misunderstood.  I'm using the part of the ampache config  (see below example) with success.  Meaning ampache can communicate with last.fm, musicbrainz, etc without an issue through the proxy (outbound).
When using / adding Podcasts, Ampache does not use these settings and fails.
--
#########################################################
; Proxy Settings (optional)                              #
;#########################################################

; If Ampache is behind an http proxy, specify the hostname or IP address
; port, proxy username, and proxy password here.
; DEFAULT: not in use
;proxy_host = "192.168.0.1"
;proxy_port = "8080"
;proxy_user = ""
;proxy_pass = ""

---

If I can provide anymore information , please let me know. thank you!

**Comment by wagnered** [comment]
>  If I whitelist this connection, subscription is successful, albeit, it will not pull down album art or episodes.

Ok...  I answered only the album art problem which is valid.  I will look into the episodes problem, but it might require the effort of @lachlan-00 if I can't find anything obvious.

**Comment by wagnered** [comment]
> If I whitelist this connection, subscription is successful, albeit, it will not pull down album art or episodes.

In your example, the url for the episodes is the same as the feed url so there should be no problem downloading episodes upon podcast  creation.  There could be podcasts in which the episodes and art are located at a different url. You would have to examine the xml feed file and whitelist the url for those episodes and and art.

On the admin tab there is a preference for the number of new podcast episodes to download.  The default is 0  and the ampache logic indicates 0 means none will be downloaded. 

Can you select an episode and stream it?

**Comment by wagnered** [comment]
See the [Ampache podcast wiki](https://github.com/ampache/ampache/wiki/Podcasts) to set up Ampache to subscribe to and download podcasts.

**Comment by jwhips** [comment]
> > If I whitelist this connection, subscription is successful, albeit, it will not pull down album art or episodes.
> 
> In your example, the url for the episodes is the same as the feed url so there should be no problem downloading episodes upon podcast creation. There could be podcasts in which the episodes and art are located at a different url. You would have to examine the xml feed file and whitelist the url for those episodes and and art.
> 
> On the admin tab there is a preference for the number of new podcast episodes to download. The default is 0 and the ampache logic indicates 0 means none will be downloaded.
> 
> Can you select an episode and stream it?

I'm really trying not to be rude.  I burnt a lot of time confirming where the problem is.

Everything else works in Ampache as expected via the proxy settings.  **The podcasts do not.**  I can see the podcasts network request(s) not using the proxy and being blocked at my firewall.  

I can post screenshots with details of everything that I am seeing if that helps?

**Comment by kuzi-moto** [comment]
I think I understand what the issue is. All outbound traffic should go through your local squid proxy, which ampache is configured to do but for whatever reason Podcasts are ignoring, and instead trying to reach out directly to the internet. Which causes errors since your proxy will deny access.

Unless you whitelist the subscription URL which allows you to pull the feed, but not episodes or images since presumably they are being hosted from another address.

Likely @lachlan-00 will have to look into this, to see why Podcasts do not respect the Ampache proxy config.

**Comment by wagnered** [comment]
Thanks @kuzi-moto

He wasn't clear to me if podcasts could be down loaded if the system was configured without port forwarding/proxy.  Also to confound the issue, the podcast feed he gave as an example did not have an image url.

But you are correct.  The art class fetches the image directly using the mikealmond/musicbrainz package.

The episode download logic uses php's `file_put_contents()` with `fopen()`.

**Comment by lachlan-00** [comment]
Seems like this function can set proxy options but we haven't here for some reason.
https://www.php.net/manual/en/function.file-get-contents.php

I haven't got a lot of time this week but will be looking at getting to a few issues ASAP

**Comment by jwhips** [comment]
> Thanks @kuzi-moto
> 
> He wasn't clear to me if podcasts could be down loaded if the system was configured without port forwarding/proxy. Also to confound the issue, the podcast feed he gave as an example did not have an image url.
> 
> But you are correct. The art class fetches the image directly using the mikealmond/musicbrainz package.
> 
> The episode download logic uses php's `file_put_contents()` with `fopen()`.

I should have been more clear on my request.  I was trying to include evidence showing that that proxy does work; but podcasts and RSS do not.

**Comment by jwhips** [comment]
> Seems like this function can set proxy options but we haven't here for some reason.
> https://www.php.net/manual/en/function.file-get-contents.php
> 
> I haven't got a lot of time this week but will be looking at getting to a few issues ASAP

Thank you!
Do you guys do a bounty on requests / fixes?  The podcasts and podcast (time / bookmark) syncing is the two things I really would benefit from.

I'm grateful for Ampache!
Cheers,

**Comment by kuzi-moto** [comment]
> 
> 
> > Seems like this function can set proxy options but we haven't here for some reason.
> > https://www.php.net/manual/en/function.file-get-contents.php
> > I haven't got a lot of time this week but will be looking at getting to a few issues ASAP
> 
> Thank you!
> Do you guys do a bounty on requests / fixes? The podcasts and podcast (time / bookmark) syncing is the two things I really would benefit from.
> 
> I'm grateful for Ampache!
> Cheers,

If you wanted to provide a bounty to get it fixed more quickly you could do that, but otherwise there isn't any.

**Comment by lachlan-00** [comment]
> 
> 
> > Seems like this function can set proxy options but we haven't here for some reason.
> > https://www.php.net/manual/en/function.file-get-contents.php
> > I haven't got a lot of time this week but will be looking at getting to a few issues ASAP
> 
> Thank you!
> Do you guys do a bounty on requests / fixes? The podcasts and podcast (time / bookmark) syncing is the two things I really would benefit from.
> 
> I'm grateful for Ampache!
> Cheers,

I don't like to worry about money as part of my work here. Donations from the site go to the demo site and hosting but if you can just help with testing and keep asking questions that's all i need.

Contributing is actually much more helpful and i'm going to start looking at this now.

It's helpful that you have a success for me as well so i can look up what those functions are doing to use the proxy.

**Comment by lachlan-00** [comment]
it should actually be as simple as adding Core::requests_options() to the request.
![image](https://user-images.githubusercontent.com/1305249/82865648-8e3e0380-9f6a-11ea-80c1-b3d1a3e04387.png)

Add the Core::requests_options() will check the config for your proxy and will add it to the array.
![image](https://user-images.githubusercontent.com/1305249/82865681-aca3ff00-9f6a-11ea-99fb-16fc2ad441df.png)

**Comment by lachlan-00** [comment]
i forgot the include path bool
```
file_get_contents($this->feed, false, stream_context_create(Core::requests_options()));
```

**Comment by lachlan-00** [comment]
@jwhips i've put this in develop now, i forgot to merge back from edge but it works without a proxy so test it out with yours

**Comment by lachlan-00** [comment]
this should be okay but leaving open for confirmation for now

**Comment by jwhips** [comment]
Proxy is working as expected ! thank you!

Only took me a few months, but I have finally updated my Ampache and can verify that the podcast feed respects the proxy configuration in the ampache configuration file.

cheers,
