### ISSUE TITLE
Smart playlist: n-number of last added/ newest songs

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2385]
## Describe what you don't like about Ampache, or what it is missing
What I would like to have is a playlist which contains n (for instance 200) number of last added songs, based on the date added. This would require the date added to be constant, the way it is in iTunes where metadata changes or even moving the files doesn't change the date added information, unlike many music players such as Quod Libet, Strawberry, Elisa and possibly others. 

This might already be possible but I wasn't able to figure this out from the demo and documentation. It atleast didn't seem like I could make a smart playlist with n-number of last added songs, I could only set a date. 

I found a related issue/ function: https://github.com/ampache/ampache/issues/1229

With the current functions this function might be hacked together, using a smart rule added after date and limiting the playlist to a number of songs. However it seems the number you can choose is either 25, 50, 100, 500 or unlimited. Is it possible to customize these values to say 250?

**Comment by lachlan-00** [comment]
so like this but by number?
![image](https://user-images.githubusercontent.com/1305249/82167038-c5267080-98fd-11ea-9f25-e177d95460e2.png)

i can probably do a rule of some kind for this pretty easy.

Added is already there and doesn't change
![image](https://user-images.githubusercontent.com/1305249/82167120-20586300-98fe-11ea-955e-3d2b158ce9cb.png)

I think i can add this as something like this?
![image](https://user-images.githubusercontent.com/1305249/82167317-b8eee300-98fe-11ea-9c0e-f8c13176cc7d.png)

**Comment by lachlan-00** [comment]
ive also added 250 as an inbetween of 100 to 500, that is a pretty big jump

**Comment by sandersantema** [comment]
Exactly this, fantastic! For this to work reliably however what is "most recent" can't be based upon simple modification times I believe. I for instance sync my music between a mac mini (because I still am dependent on iTunes for some stuff) and my main linux machine. When I edit metadata in some way or another Quod Libet (music player) sees these edited files as new files. While itunes keeps the added-date of files in its iTunes.xml file, so even if I for instance edit metadata on my linux machine and tell iTunes to update this metadata the added date stays the same while the added date in Quod Libet is practically useless with a synced library.

**Comment by lachlan-00** [comment]
not sure which rule it's going to be part of yet (this was just editing the html in firefox)
it's different enough from the base rules that i'll need to work out how to make sure the sql works.

but whatever the rule ends up being it would be searching based on either.
* Added to the database (addition_time)
* Last time the file has changed (update_time)

As long as you keep the file in the same place the song table never changes the addition_time. if you move the file outside Ampache it will remove the old one and re-add it with a new addition_time.

**Comment by lachlan-00** [comment]
I think i'm going to put this in a separate rule called "most recent" then we can order by

add, update, id and probably more things. going to play on that today

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/82392525-6a208500-9a87-11ea-85d2-acc650cb9771.png)
going into develop now, it seems simple enough but may break other searches? i've tested with single and different rules so it seems okay for testing

**Comment by lachlan-00** [comment]
actually i'm working on it a bit more the rule recent  overwrites itself when you use two

**Comment by lachlan-00** [comment]
okay, fixed now. incoming!
![image](https://user-images.githubusercontent.com/1305249/82397291-77437100-9a93-11ea-9ac8-62bbf6bbd952.png)

**Comment by sandersantema** [comment]
This is all very very nice! Thanks for implementing this so quickly :)

**Comment by lachlan-00** [comment]
There are little things I can add that make the search so much better that I can't resist.

Smart lists and search are really good Ampache features
