### ISSUE TITLE
Installation on Windows with IIS7.5

### ISSUE THREAD

**Issue by he99** [ampache/ampache#2386]
I have managed to install Ampache on Windows with IIS7.5 and put together a wiki page with the steps needed (see https://github.com/he99/ampache/wiki/Windows-installation-on-IIS7.5). I've especially detailed the steps required to make URL rewriting work with IIS, so Subsonic clients can access the server correctly.

Maybe others will find this helpful, so I'm posting this here.

If you like, free to merge this into the official Wiki.

Thanks and keep up the good work!

**Comment by kuzi-moto** [comment]
Thanks for this! Just a note - the wiki should be writeable by anyone. Feel free to add it yourself!

**Comment by wagnered** [comment]
@he99 wrote:

> Streaming Radio stations only seem to work with mp3 streams (m3u playlists don't work)

I found only one reference to "radio station" in the wiki and that is in the discussion on channels:

> You can cheat around some of the channel limitations by adding it as a radio station.

So, if a radio station is an extension of a channel, the wiki explicitly states that only mp3 and ogg files can be streamed.  I understand that M3u files are intended to *point* to streams, not provide them. So I don't think you have a problem in that regard.

It would be nice if the wiki discussed a comparison among 
channels, radio stations and broadcasting.  What are the channel limitations that the wiki refers to?(rhetorical)

@kuzi-moto, could you clarify the differences among the three?

@he99  I too thank you.

**Comment by he99** [comment]
@wagnerd, sorry, I seem to have missed the already reported issue #1313 - it describes a feature request for having "m3u" playlists for radio stations...

@kuzi-moto, thanks I'll try to put it in the wiki here (after it is a bit more polished).

**Comment by wagnered** [comment]
I'm very impressed with your writeup so far.   I would like to see it without the work-arounds, though. :smile:

> ...rename config\ampache.cfg.php.dist to config\ampache.cfg.php and edit it.

I would like to suggest that the .dist file be  copied instead of renamed. That's what Ampache actually does.  

This suggests that the IIS process does not have write access to the ampache/config folder.

> Catalog indexing seems to not work from within ampache (requires scheduled task?). As a workaround, run the following commands from a shell:
> 
> cd C:\inetpub\wwwroot\ampache\bin php catalog_update.inc

That's interesting because catalog_update.inc accesses php files on the Ampache  folder path same as running the catalog update from the web interface does.  Does the Ampache debug log reveal any problems when running the update from the web interface?

**Comment by AshotN** [comment]
Any reason you are running an outdated version of IIS?

**Comment by he99** [comment]
@AshotN: This is due to my Acer AC100 system running Windows Storage Server 2008R2 Essentials - IIS7.5 is what comes with Server 2008R2...

**Comment by he99** [comment]
@wagnered: I checked again today and tried to take a look into the catalog_update issue. Actually I was not able to reproduce, seems like I simply did not wait long enough for it to finish - so yes, everything is working (yeah!).

I've updated the wiki page accordingly and added a few more details about the media folder security settings (allow the IUSR account to read the media folders). Feel free to review - if that's ok, then I will add it here.

**Comment by lachlan-00** [comment]
> @wagnerd, sorry, I seem to have missed the already reported issue #1313 - it describes a feature request for having "m3u" playlists for radio stations...

it's part of the API roadmap to support playlist import as streaming sources. (i missed that issue but i've added it to my project) I also cheat the way wagnerd said above by making my channels "radio stations" which works okay for now.

this will all get better at some point when we can actually just do it. :)

**Comment by mitchray** [comment]
I have cloned the page into the [Ampache wiki](https://github.com/ampache/ampache/wiki/Windows-installation-on-IIS7.5-(from-he99)), so closing this out 👍
