### ISSUE TITLE
docker - Problem: Problem to add catalog

### ISSUE THREAD

**Issue by henning65** [ampache/ampache#2387]
Describe the bug
Im running ampache as docker (ampache/ampache latest) on Synology DSM
The docker is running and I'm able to connect the Web-Interface.
I do fail to add any catalog: I try to add folders within the folder which is connected via docker - set up but fail. 
As I'm new to ampache I'm a little lost. 

Yours

**Comment by kuzi-moto** [comment]
Hey @henning65, care to share your docker-compose.yml file, and perhaps the Ampache logs?

**Comment by PaulWalkerUK** [comment]
I'm new to Ampache as well and it sounds like I have a similar setup to you - running the `ampache/ampache:latest` image on a Synology NAS and accessing media from a shared folder on that same NAS and I also ran into problems at first. I literally just got it working a few hours ago - there might be a better way of doing it - your mileage may vary!! :smile:

I think there's basically 3 things I had to do:
1. Make sure the `users` group on the NAS has at least read permissions on the music directory
2. When starting the container, use a volume to mount the music directory to `/media`
3. Inside the container, add the `users` group to the `www-data` user in the container

Let me know if you want more detail, I can write it up step-by-step if that might help (like I say, I'm no expert, but it seems to work!)

**Comment by kuzi-moto** [comment]
Hey @PaulWalkerUK, there is actually a pull request in the docker repository that should be addressing this issue, which will include some better documentation.

**Comment by henning65** [comment]
@PaulWalkerUK: Thanks for your advice! Could you please explain what I should do in step 3 - I actually don't understand "_to the www-data user in the container_"

@kuzi-moto: I don't know how to generate a docker-compose.yml file. Please find enclosed the csv file of the protocol. If you please advice where to find the ampache log file? I will share them as well.

Yours

[ampache.pdf](https://github.com/ampache/ampache/files/4875267/ampache.pdf)

**Comment by kuzi-moto** [comment]
@henning65, I would advise against making changes inside the container itself. If the container is destroyed (such as when updating the image) the data is lost, and you will have to redo the changes each time. I am working on fixing some issues with permissions.

I assumed you were using `docker compose`. Just share the run command, and what directory you were using within Ampache to add the catalog.

**Comment by PaulWalkerUK** [comment]
Firstly, kuzi-moto is absolutely right - this isn't the proper way to go about this at all. I just did it as a quick and dirty way to make it work (this was my first look at Ampache and wanted to get a quick start to see if it was something I was interested in spending more time on).

1. From the DSM, go into the Docker app and find the running container.
2. Click on the running container then press the Details button
3. Click on the Terminal tab, then press the Create button. This will create a new session called "bash" - click on that
4. If you enter the command `id www-data`, it will show you which groups that user is currently a member of - you should see that the user currently only has group `33(www-data)`
5. Enter the command `usermod -a -G users www-data`
6. If you enter the command `id www-data` again, you should now see that it has `33(www-data),100(users)` 

I suspect the 'proper' fix might be to include something like that command in step 5 in the dockerfile itself, but haven't got around to looking at it yet. If kuzi-moto is already doing some work in this area, I might wait and see if that sorts it

**Comment by henning65** [comment]
@PaulWalkerUK: I followed your steps - the terminal now shows: uid=33 (www-data) gid=33 (www-data) groups=33 (www-data),100 (users)
still I was unable to generate a catalog. I got the same message: " the directory could not be read. Does it exist?"

During docker-compose I define - regulary - PGID and PUID on my NAS to ensure, that the Usergroup / User has access to the volume with the relevant data. I use the same setting for other dockers like calibre as well without problems. The DSM-Usergroup / User have different PGID / PUID than 33 / 100. Might this be the reason for my problems?

@kuzi-moto: I fully agree with your advice not to make changes inside the container. As you may have guessed: I'm not very familiar with programming - so: point taken.
At the moment I simply would like to get a first impression, if ampache could become the new "home" for my music files. For now that's my first priority.
You wrote: "_Just share the run command, and what directory you were using within Ampache to add the catalog_."
I'm not sure I understand your suggestion. I did sent you a pdf-file with the protocol: "ampache.pdf". 
Since yesterday I changed the docker-setting for the volume. It's now directly pointing at the first-level folder "kodi" (setting within Docker: kodi = /media). Still I was unable to add subfolders from kodi to the catalogue.

Yours

**Comment by PaulWalkerUK** [comment]
> The DSM-Usergroup / User have different PGID / PUID than 33 / 100. Might this be the reason for my problems?

It might be. Ampache runs as the user `www-data` (User ID=33). By default, this user is a member of group `www-data` (Group ID=33). One way or another, that user needs to get read-permission on whatever you're mounting to `/media`. Between the container and the NAS, users and groups will be different - what matters is the numbers, not the names. The way I went about it, on the NAS I gave the Users group read-permissions on that share (Control Panel --> Shared Folder, select share, Edit --> Permissions, select Local Groups from the drop down and tick the box for Users to get Read-Only). The NAS's Users group has GID=100. It just so happens that it's the same inside the container. So then, adding the `www-data` user to the the Users group gave that user read-permission on that share.

If you can find out Group ID of any group that has read-permission on whatever you're mounting into the container, you could [create a group in the container with that same GID ](https://linuxize.com/post/how-to-create-groups-in-linux/), then add that group to the `www-data` user. It doesn't matter what the _owner_ of the directory is in the NAS - it's about what groups have access (the NAS uses ACL's, so it's a bit more flexible than the traditional user/group owners)

**Comment by PaulWalkerUK** [comment]
Just been doing some more of my own testing and I've just thought of one other thing I don't remember being mentioned explicitly... When adding the catalog, I assume you're setting Catalog Type to `local` and then Path to `/media`?

**Comment by PaulWalkerUK** [comment]
Ahh, I may have forgotten one other step - after doing `usermod` to add the group to the `www-data` user, you need to restart the container 🙂

**Comment by henning65** [comment]
@PaulWalkerUK:
First of all: thanks for all your effort to help!

@PaulWalkerUK 
@kuzi-moto 
concerning USER / GROUPS: I followed this description [https://hub.docker.com/r/technosoft2000/calibre-web ](url) (see "For Synology NAS users") to clarify the id of my NAS USERs / Groups. Within the docker-setup I then use PGID and PUID as variables to rule out access problems for docker-USERs to the NAS-folders. Actually I thought all dockers would somehow acknowledge these settings but maybe I'm wrong?!? IF the ampache docker would acknowledge the setting my problem to define a catalogue would be wired....?
Within the Terminal I used "getent group" to get a list of all group / GroupIDs of the docker. 
Within ampache-docker: The docker does't list my Group (The Setting PGID).
Within calibre-docker: The docker does list my Synology NAS Group (The Setting PGID).
(it is listed like: "users:x:100:abc ....... abc:x:<PGID-number>:)

[to make my post a bit easier to read: 
for PGID: 65432; 
for PUID: 1234;
for newgroup: docker]

I used the terminal to change the ampache-docker: 
1. I added a new group with a group ID similar to a Group ID on my NAS with access to the folder using <groupadd -g 65432 docker>
2. I added the USER www-data to the new group using <usermod -a -G docker www-data>
3. I verified that the new group exists and that the new group includes the USER www-data. (bash: <getent group>)

I restarted the container.
Unfortunately, this didn't solve the problem. I still can't define catalogues..... 
I still believe the problem is related to my USER / GROUP settings. If I compare the calibre-docker and the ampache-docker:
The calibre-docker (<getent group>):
    www-data:x:33:
    users:x:100:abc
    abc:x:65432
The bash-command <id abc> delivers: uid=1234(abc) gid=65432(abc) groups=65432 (abc), 29(audio), 30(dip),44(video),100(users),103(xrdp)

The ampache-docker (<getent group>):
     www-data:x:33
     users:x:100:www-data
     docker::x:65432:www-data
The bash-command <id www-data> delivers: uid=33(www-data) gid=33(www-data) groups=33(www-data,100(user),65432(docker)

I do have the impression, that it's the primary group of the USER www-data which is 33 and (maybe) the primary uid, which are causing problems?!?

Yours

**Comment by PaulWalkerUK** [comment]
1. How are you setting the fields when adding the catalog? (Maybe a screenshot of that page) - let's just double check you're trying to do the same as I did

2. From inside the container, what do the following commands return?
`ls -l /`
`ls -l /media`

**Comment by henning65** [comment]
@PaulWalkerUK: thanks for your support!

please find enclosed 3 screen shots: 
1 -> ls -l /
2 -> ls -l /media
3 -> catalog

[ls -l.pdf](https://github.com/ampache/ampache/files/4908290/ls.-l.pdf)
[ls -l :media.pdf](https://github.com/ampache/ampache/files/4908291/ls.-l.media.pdf)
[catalog.pdf](https://github.com/ampache/ampache/files/4908292/catalog.pdf)

Yours

**Comment by PaulWalkerUK** [comment]
One thing I notice is that, like me, you have your music folder mounted to `/media` - but when setting up the catalog, you're spcifying the path (the last field) as `Music`. When I set mine up, I specified it as `/media` (since that's what the directory is within the container). I'm not sure about the directory structure - I think you have an extra directory to me, so maybe you'll need to specify `/media/Music`

I'm still a little unsure about your permissions... your `/media/Music` directory has `drwx------` owned by UID `1032` and group `users`. I think this means only UID `1032` can access it (and since it's displaying the UID and not a name, then there must not be a user in the container with that UID). 

For comparison, I've attached a couple of screenshots of my setup.
* On my NAS, my files are are in `/tmp/ampache/music`
* I've made the `/tmp` share readable by the `users` group in the NAS
![permissions-nas](https://user-images.githubusercontent.com/5160018/87246583-44d84380-c446-11ea-81e3-fa9c86fcec52.PNG)

* When starting the container, I used a volume to mount `/tmp/ampache/music` to `/media`
![volume](https://user-images.githubusercontent.com/5160018/87246588-47d33400-c446-11ea-8e32-6613a6b6d988.PNG)

* Within the container, I ran `usermod` as described above to add the `www-data` user to the `users` group
![container-permissions](https://user-images.githubusercontent.com/5160018/87246585-4570da00-c446-11ea-8953-b5430df95194.PNG)

* When adding the catalog in Ampache, I added it as a Local catalog and set the path to `/media`
![catalog](https://user-images.githubusercontent.com/5160018/87246587-473a9d80-c446-11ea-846c-320d8a14baa2.PNG)

**Comment by henning65** [comment]
@PaulWalkerUK: Thanks for all your help, but for now I think its time to stop massing around with the container. I still believe it's an access problem due to the fact that the variables PGID and PUID are not used by ampache. 
Actually I don't want to grant access www-data (uid=33 gid=33) access to my NAS. I know too little to make such a setting bulletproof. I strongly believe it's a mistake within the docker, that's not possible to define a different user via docker-settings (see above: https://github.com/ampache/ampache/issues/2387#issuecomment-654694912). 
Still one simple question remains: As your settings include only read access: Are you able to safe ratings to a song? (Are song-ratings stored in the song-file-metadata? Or simply in an ampache database?)

@kuzi-moto: I would like to suggest that the docker setup is changed. It would be helpful to include a USER (like) "abc". And it would be helpful if it would be possible to define the UID and GID of the USER "abc" by docker-variables. Please find enclosed a linke to another docker with such a setup: https://github.com/ampache/ampache/issues/2387#issuecomment-654694912

Yours

**Comment by kuzi-moto** [comment]
@henning65 thanks for the link! I have been working on getting this working for the Ampache Docker image, as well as some other various improvements. When I create the pull request, I'll link it to this issue.

**Comment by PaulWalkerUK** [comment]
> Are you able to safe ratings to a song? (Are song-ratings stored in the song-file-metadata? Or simply in an ampache database?)

I haven't done much testing in this area, but it looks like it gets saved OK, so I assume it must be in the database (which makes me wonder if that allows different users to have their own ratings - that'd be quite nice 🙂 )

**Comment by henning65** [comment]
@kuzi-moto: any progress?

**Comment by lachlan-00** [comment]
The pull @kuzi-moto made has been merged. i've made a few new builds from in in develop and nosql.

I'll be updating master again when 4.2.2 is out

**Comment by henning65** [comment]
@kuzi-moto: Dear kuzi-moto
concerning the problem to "add catalog": The new build has solved this problem? (it was tested to work) or might have solved (problem addressed but not tested so far) the problem?
Would you like me to give feedback? 

OR
the problem "add catalog" is still on the "to-do" list?

Thanks for clarification.

Yours

**Comment by kuzi-moto** [comment]
Hi @henning65,

The last update should have added support to set the user and group ID that the Ampache container runs with. Theoretically you should be able to set this to your user's user/group id which would eliminate the permissions issues, unfortunately I did not have a lot of time recently to actually test it out. I _think_ you can set the `GID` and `UID` environment variables.

**Comment by henning65** [comment]
@kuzi-moto : could you please specify the name of the variables you used to define GID and UID? I tried PGID and PUID - but failed.... still not able to add catalog

**Comment by kuzi-moto** [comment]
@henning65 I think the variable names should be just `GID` and `UID`. I'm hoping to have some time in the next few days to take a look at this more.

**Comment by kuzi-moto** [comment]
@henning65, did you have some time to take a look at this? I'd be happy to provide an example if that helps.

**Comment by mitchray** [comment]
Closing due to time since last reply, re-open if still relevant for version 6+
