### ISSUE TITLE
ldap_require_group does not work

### ISSUE THREAD

**Issue by mneiger** [ampache/ampache#2388]
## Description
The ldap_require_group does not work with openldap because teh code checks for the user dn in the memberuid instead of the username

Setup ldap authentication with openldap
once it working, add searching for member ship in a group

##Steps to correct the behavior:
replace in lib/class/ldap.class.php / line 288

```
                if (! p`reg_grep("/^$username\$/", $group_infos[$member_attribute])) {
                    throw new LDAPException("`$username` is not member of the group `$group_dn`");
                }

```

## Environment

* Ampache version: 4.1.1-release
* Web server + version: nginx 1.14.2
* Server operating system: debian buster
Linux yohanan 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux
* Client operating system: linux mint 19.3 Firefox

### Client type

* Web Firefox 76

## Settings

ldap_url = "ldap://localhost/"
ldap_search_dn = "ou=People,dc=xxx,dc=org"
ldap_objectclass = "posixAccount"          ; OpenLDAP
ldap_filter = "(uid=%v)"                   ; OpenLDAP
ldap_require_group = "cn=ampache,ou=Groups,dc=xxx,dc=org"
ldap_name_field = "cn"
ldap_member_attribute = "memberuid"

### Non working log

> 2020-05-18 22:20:55 [ampache] (ldap.class) -> binding with username `cn=az test,ou=People,dc=xxx,dc=org` 
> 2020-05-18 22:20:55 [ampache] (ldap.class) -> reading attributes ["memberuid"] in `cn=ampache,ou=Groups,dc=xxx,dc=org` 
> 2020-05-18 22:20:55 [ampache] (ldap.class) -> Exception: `cn=az test,ou=People,dc=xxx,dc=org` is not member of the group `cn=ampache,ou=Groups,dc=xxx,dc=org` 
> 2020-05-18 22:20:55 [ampache] (ldap.class) -> Error during authentication: `cn=az test,ou=People,dc=xxx,dc=org` is not member of the group `cn=ampache,ou=Groups,dc=xxx,dc=org` 
> 2020-05-18 22:20:55 [ampache] (ldap.class) -> Return value of authentication: {"success":false,"error":"`cn=az test,ou=People,dc=xxx,dc=org` is not member of the group `cn=ampache,ou=Groups,dc=xxx,dc=org`"} 
> 2020-05-18 22:20:55 [ampache] (login.class) -> atest From 192.168.78.152 attempted to login and failed 

### Log with patched code :

> 2020-05-18 22:44:40 [ampache] (ldap.class) -> binding with username `` 
> 2020-05-18 22:44:40 [ampache] (ldap.class) -> search: (&(objectclass=inetOrgPerson)(uid=atest)) 
> 2020-05-18 22:44:40 [ampache] (ldap.class) -> searching in `ou=People,dc=xxx,dc=org` for `(&(objectclass=inetOrgPerson)(uid=atest))` 
> 2020-05-18 22:44:40 [ampache] (ldap.class) -> binding with username `cn=az test,ou=People,dc=xxx,dc=org` 
> 2020-05-18 22:44:40 [ampache] (ldap.class) -> reading attributes ["memberuid"] in `cn=ampache,ou=Groups,dc=xxx,dc=org` 
> 2020-05-18 22:44:40 [ampache] (ldap.class) -> Return value of authentication: {"success":true,"type":"ldap","username":"atest","name":"az test","email":null} 
> 2020-05-18 22:44:40 [atest] (session.class) -> Session created: hd0d33a7m508f7ih9e7dh0j38g 
> <!-- To enable logging, visit https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging
>

**Comment by lachlan-00** [comment]
Good to know. My LDAP testing is just done by user so I'll check this out asap

**Comment by lachlan-00** [comment]
what's your ldap_member_attribute?

```
; LDAP member attribute name.
; That's the name of the attribute of the group that will contain
; the usernames.
; DEFAULT: member
;ldap_member_attribute = "member"
;ldap_member_attribute = "memberuid"
```

**Comment by mneiger** [comment]
Although ldap (slapcat) reports "memberUid" this triggers an error, and "memberuid" all lowercase just works.
ldap_member_attribute = "memberuid"
I did not check further on this.
