### ISSUE TITLE
[Suggestion] Promote cohen3 instead of coherence

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2390]
Coherence was abandoned awhile back.  One of the maintainers salvaged it but declined to maintain the project.

The [Cohen3](https://github.com/opacam/Cohen3) dlna/upnp server is the python 3 version of coherence.  Opcam implied that it is a drop-in replacement for coherence.

I was going to just edit the wiki with a reference to the cohen3 github project, but decided that maybe a volunteer should give cohen3 a test first.

**Comment by wagnered** [comment]
The only utility (so far) is the plug-in with all the plug-ins from coherence refactored for Python 3.

**Comment by wagnered** [comment]
If someone is really ambitious and familiar with Python 3, the source for the utilities: marabeau, cadre, inspector and mediarender might be found on the  [internet archive waybackmachine] (https://web.archive.org/) .  Do a search for "coherence-project".  

Reminder that the original utilities were written in Python 2.

**Comment by mitchray** [comment]
Updated the[ Coherence page](https://github.com/ampache/ampache/wiki/Coherence-(abandoned)) with an abandoned notice, suggesting Cohen3 as an alternative

If someone wants to test it please edit the wiki with your findings
