### ISSUE TITLE
Subsonic API schema not correct

### ISSUE THREAD

**Issue by loki666** [ampache/ampache#2394]
## Description
The Subsonic XSD (http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.11.0.xsd) requires Playlist to have a "created" element, but Ampache doesn't expose it

### To reproduce

1. Enable subsonic API
2. Fetch Playlist using subsonic REST endpoint

### Expected behavior
Playlist XML contains a "created" element

## Environment

* Ampache version: 4.1.1

### Client type

* SubSonic

**Comment by lachlan-00** [comment]
it's in there but not showing up in the xml
```
$xplaylist->addAttribute('created', date("c", (int) $playlist->date));
```

**Comment by lachlan-00** [comment]
it doesn't happen to be a smart list?

**Comment by loki666** [comment]
here is the response I have

`{
    "subsonic-response": {
        "status": "ok",
        "version": "1.13.0",
        "playlists": {
            "playlist": [
                {
                    "id": 400000014,
                    "name": "Album 1*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000013,
                    "name": "Album 2*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000012,
                    "name": "Album 3*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000011,
                    "name": "Album 4*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000010,
                    "name": "Album 5*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000009,
                    "name": "Artist 1*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000008,
                    "name": "Artist 2*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000007,
                    "name": "Artist 3*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000006,
                    "name": "Artist 4*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000005,
                    "name": "Artist 5*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000019,
                    "name": "Song 1*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000018,
                    "name": "Song 2*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000017,
                    "name": "Song 3*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000016,
                    "name": "Song 4*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                },
                {
                    "id": 400000015,
                    "name": "Song 5*",
                    "owner": "System",
                    "public": true,
                    "changed": "2020-06-04T12:35:55+00:00"
                }
            ]
        }
    }
}`

**Comment by loki666** [comment]
also the getPlaylist is also responding with an incorrect json
`{
    "subsonic-response": {
        "status": "ok",
        "version": "1.13.0",
        "playlist": [
            {
                "id": 400000014,
                "name": "Album 1*",
                "owner": "System",
                "public": true,
                "changed": "2020-06-04T12:35:43+00:00"
            }
        ]
    }
}`

the playlist should be an object, not an array

**Comment by lachlan-00** [comment]
I use the .org subsonic site a fair bit but it only provides XML example files. Do you know where the json is documented?

**Comment by lachlan-00** [comment]
that id is definitely a smart list. I added the extra fields into develop yesterday

comparing my response to the source files ultrasonic uses i see the playlist come in as an object

response on the left:
https://github.com/ultrasonic/ultrasonic/blob/develop/core/subsonic-api/src/integrationTest/resources/get_playlist_ok.json

my server on the right
/rest/getPlaylist.view?u=user&p=enc:password&v=1.2.0&c=DSub&id=400000149&f=json

![image](https://user-images.githubusercontent.com/1305249/83838405-6e61c900-a73c-11ea-8a20-3469c9b4990c.png)

**Comment by lachlan-00** [comment]
because smart lists are generated each time they're used i've set the time to just be the current time() when grabbing the items

**Comment by lachlan-00** [comment]
it could also possibly be something weird if the playlist is empty.

I just made an empty list and that seems consistent with what you get?
```
{
    "subsonic-response": {
        "status": "ok",
        "version": "1.13.0",
        "playlist": [
            {
                "id": 400000156,
                "name": "user - 2020/06/05 03:03PM",
                "owner": "user",
                "public": true,
                "created": "2020-06-05T15:03:15+10:00",
                "changed": "2020-06-05T15:03:15+10:00",
                "songCount": 0,
                "duration": 0
            }
        ]
    }
}
```

**Comment by lachlan-00** [comment]
Pending fix incoming for develop. taken the always array off of playlist

**Comment by lachlan-00** [comment]
smartlists have a created date (which is the current time as it's a search) but in future i might actually put the date created in the database. for now each time the search is run it's technically a new version so i'm happy with that.

i've also fixed up the array/objects around empty lists and made sure they line up with the standards/playlists from ultrasonics repo
