### ISSUE TITLE
4.2.0 TODO

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2396]
**TODO**
#2388 (need to test more with ldap)
#2411 (check in python-ampache documentation)

**PENDING**
#2379 (fix pending test)

**FIXED**
#2355 (look for more)
Subsonic smartlist, don't get items when songs not needed, use last_count (maybe put a count in playlists as well to make them similar)
#2316 (done in playlist_edit)
#1955 (Pending confirmation but i think it's fixed)
#2394 (empty playlists aren't shown correctly)
#2327 (fix pending test)
#2321 (fix pending test)

**PYTHON Methods DONE**

~~podcast_episode_delete: delete an existing podcast_episode~~
~~podcast_create: create a podcast~~
~~podcast_edit: edit an existing podcast~~
~~podcast_delete: delete an existing podcast~~
~~update_podcast: sync and download new episodes~~
~~catalog_file: clean, add, verify using the file path (good for scripting)~~

**Skipping this update**
#2377 (partially does it correctly, but partially not)
#2288 
#2382 (rearrange this depending on how to handle threading/fpm)

**Comment by lachlan-00** [comment]
Share from dsub failed to create correctly.
/rest/createShare.view?u=u
ser&p=enc:PASSWORD&v=1.2.0&c=DSub&id=300876014&id=300
876016&id=300876015

**Comment by lachlan-00** [comment]
API work now before releasing

**Comment by lachlan-00** [comment]
python methods need to be added and then updated in the build-docs.py to be used for documentation.

**Comment by lachlan-00** [comment]
just made a consistency change for user objects that only included username.

in xml there is a <user> object and the same for json but it was applied only at top level.
so like tags i've made them subobjects of a user

ie
```
"user": {
        "id": "4",
        "username": "generic",
}
```

and
```
<user id="4">
	<username><![CDATA[generic]]></username>
</user>
```

**Comment by AshotN** [comment]
If that API chante is a breaking change. It should be saved for a major change. Like Ampache v5

**Comment by lachlan-00** [comment]
closing now, no more changes while i test out this release
