### ISSUE TITLE
[Feature Request] Volume Leveling

### ISSUE THREAD

**Issue by mike49099** [ampache/ampache#2397]
I am new here so if I didn't find an existing issue, I apologize ahead of time.
As is the case with albums, from one to the next can go from 'can hardly hear it' to 'quickly turn the volume down.
I have about a 22,000 track library (for which I own a disk for all but about 20 tracks). I would like to add a tag at the album level to adjust the volume @ a percentage. For instance 70 to 130 would indicate 70% to 130% volume correction at play.
All of my files are mp3 @ 320.
They are ripped at a workstation to a Nextcloud synced directory which is then shared with Ampache on an Ubuntu 18.04LTS box.
Not sure how this would affect other library file types.
Thanks for your indulgence, Mike

**Comment by stebe** [comment]
Replaygain is what you need and is supported by most players.  Replaygain will have all the songs play at close to the same volume. Nice thing about replaygain is that it doesn't modify the song but adds tags that tell the player to adjust the volume.  I use loudgain to add the replaygain to all my tracks https://github.com/Moonbase59/loudgain/

**Comment by mike49099** [comment]
Wow, that was quick. Using built in player for PCs and Subsonic for
android. (Used to use Power Ampache but can't seem to find it any more)
Thank you very much.
Mike

**Comment by lachlan-00** [comment]
replaygain will work with subsonic clients like dsub no problem.

There are tools that will scan the file and record the replaygain details in the tags for you. if you use windows foobar2000 can do it. http://www.bobulous.org.uk/misc/Replay-Gain.html

it actually looks like power ampache has been taken off the play store! that was one of my faves

**Comment by lachlan-00** [comment]
I forgot to mention that it also works in the webplayer.
![image](https://user-images.githubusercontent.com/1305249/84115963-47740180-aa72-11ea-8ed7-8ab6b664190b.png)
