### ISSUE TITLE
Getting  false errors on install

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2399]
I'm getting Configuration file readability, and validity errors,  along with the database errors, neither of which exists yet.  

Maybe the. Bug has been exposed because this is an absolutely fresh install.
I'm installing it on Android 9 pie with 64 gb storage.  Because it's not rooted, I am limited as to what I can do with it.

**Comment by kuzi-moto** [comment]
What's your process for installing? I can try to follow and see if I can get it to work.

**Comment by wagnered** [comment]
After cloning the Ampache repository, cd'ing into it and running composer, I set my browser to the web page . Ampache immediately returns test.php.

Actually, on a new install, the logic should be checking for ampache.cfg.php.dist.  It was checking for the actual config file, which doesn't get created 'til after the install process is finished.

So I changed ampache.cfg.php to ampache.cfg.php.dist in test.php  and now have problems creating the database. 😭.

**Comment by kuzi-moto** [comment]
Are you using Termux, and how are you installing Apache/PHP?

I haven't installed from scratch for a few development versions, but haven't noticed any of these issues.

**Comment by lachlan-00** [comment]
the only install change I've done this version was removing checks in test for the old PHP function.
I'm starting testing this week but I'll see if anything broke

**Comment by wagnered** [comment]
Yes, I'm running termux but only to install and run a distribution from Andronix. They are built to run in a chrooted environment. I'm running Ubuntu 19. something.

I gave up trying to get Apache running: I think one of the modules requires actual root privileges. I'm running lighttpd with no problem so far. Likewise with php.

Mariadb is running, and I can access it from the CLI. Even though I gave root the right to access remotely, with Ampache, I get "Access denied'.  I ' m sure it's just a configuration problem

**Comment by wagnered** [comment]
Ok, I didn't actually say I fixed it, I guess it was a "work-around" so I could move on. 😊

Back in 2014, afterster added that line when he moved Ampache from being 'doped' to what it is now.

After I made that change, Ampache behaved properly, first showing the language page as it normally does.

Now I guess I gotta find out how to use xdebug without an IDE.

**Comment by kuzi-moto** [comment]
Seems like [this project](https://github.com/vim-vdebug/vdebug) may be promising if you're familiar with VIM.

**Comment by wagnered** [comment]
Ok, I didn't actually say I fixed it, I guess it was a "work-around" so I could move on. 😊

Back in 2014, afterster added that line when he moved Ampache from being 'doped' to what it is now.

After I made that change, Ampache behaved properly, first showing the language page as it normally does.

Now I guess I gotta find out how to use xdebug without an IDE.

**Comment by wagnered** [comment]
Thanks, looking good, I just installed vim and libpython3.7 was also installed.

Thanks again for the tip.

**Comment by wagnered** [comment]
As someone who lived through the '60s would say: " This is unreal".  I completely removed the Ampache clone, recloned it and this time I had no problem with the install.

@kuzi-moto  I have Vdebug installed and am now learning to use it.

Closing for good this time.

**Comment by lachlan-00** [comment]
i've started testing and i see what you mean, those errors shouldn't be there for test.php they come up usually from missing someting like composer or just running the test itself first

i've put some warning as the test.php might be the first page you get to so it needs a bit more direction.

**Comment by lachlan-00** [comment]
What I find interesting is that the install process will only start if everything is okay.

When you get stuck on test and fix things it doesn't really do what it should. 

I agree and will do more for this.

**Comment by wagnered** [comment]
I've been trying to set up a debug environment and also fight a lot of bugs on this android probably caused by not so perfect apps  I've installed.

Anyway, the problem only appears during the first try, I have to reclone every time I want to experience it.  At the same time,  the vim package might not have been compiled with windows, so vdbug might not work.  But I'm having a lot of fun.

**Comment by lachlan-00** [comment]
i've added a redirect to install.php on missing config file.

there is already a test immediately after you select language so this actually works a lot better now
