### ISSUE TITLE
[Feature Request] - Please read Vorbis ratings tags

### ISSUE THREAD

**Issue by LittleGreyDuck** [ampache/ampache#2400]
Just updated to 4.1.1 and uploaded some freshly-ripped CDs to the library, and after import I'm still seeing something I hoped would be fixed by now: My OGG files display every tagged metadata (artwork, etc) _except_ the ratings. I manage my metadata (including ratings) on my local PC and save the tags to the files so they're "portable" (all metadata self-contained). Then all Ampache has to do is read the tags and I can do smart-playlist stuff like "Rock songs 4-stars or higher" and so on.

 MP3s purchased online that I tagged are, of course, showing their correct ratings. All I need is for OGG files to do the same.

 Thanks!

**Comment by lachlan-00** [comment]
have you put vorbiscomment first in the id3 list?
![image](https://user-images.githubusercontent.com/1305249/83982141-6174ed80-a967-11ea-99b1-4cb06be328c2.png)

**Comment by LittleGreyDuck** [comment]
I tried that, ran a catalog update, and my Ogg files still don't show the rating data in Ampache.

Note that all other Vorbis tags came through just fine: Dates, titles, album art, etc. Just not the ratings. Seeing as how Vorbis files don't have ID3 tags, I can't imagine that changing the tag search order was going to make much difference there anyway.

**Comment by lachlan-00** [comment]
vorbis files can have id3 tags attached to them sometimes which isn't meant to happen but there are programs that do it.

if you haven't got ratings associated with an email as well they might not be included either. instead going to the -1 / system user

email me an example file and i'll have a look.
lachlan ( at ) ampache ( dot )dev

**Comment by lachlan-00** [comment]
I see what's happening. file ratings get imported as user -1 (no one / system)

in develop you can now set a config user that will import ratings as that user
![image](https://user-images.githubusercontent.com/1305249/85248737-17c2f180-b495-11ea-972a-77131da427da.png)

To get this setting. update develop and then generate a new config file with these new options
![image](https://user-images.githubusercontent.com/1305249/85248782-31fccf80-b495-11ea-8ee3-ca353332f632.png)

and you can then set your desired ID in the config file.

**Comment by LittleGreyDuck** [comment]
I updated to Develop, wrote the new config, and uncommented the
rating_file_tag_user and set it to 1 (my user ID). Then ran
'catalog_update.inc -a -c'. The Ogg files' ratings still aren't present.

**Comment by lachlan-00** [comment]
i edited the config and picked a user that doesn't exist so i could find it.
![image](https://user-images.githubusercontent.com/1305249/85803421-7a183c80-b78a-11ea-8581-f611418bc4c0.png)

ran a catalog add
```
php -f /var/www/music/bin/catalog_update.inc -- -a
```

and the file is inserted into the database
![image](https://user-images.githubusercontent.com/1305249/85803495-9caa5580-b78a-11ea-9d19-e5e95a112031.png)


Then i deleted the rating of that file then updated the album from tags
![image](https://user-images.githubusercontent.com/1305249/85803591-de3b0080-b78a-11ea-8477-3343df6c8a1f.png)

The rating is back (notice the incremental row update.)
![image](https://user-images.githubusercontent.com/1305249/85803613-eabf5900-b78a-11ea-81a0-1b318595b49c.png)

So it works fine for ogg files now.

**Comment by lachlan-00** [comment]
you can also run a -v / verify which will update all files from tags.
```
php -f /var/www/music/bin/catalog_update.inc -- -v
```

**Comment by LittleGreyDuck** [comment]
Huzzah, that seems to have worked. I'll rip some new CDs (I need to replace
some Oggs created with a TRULY PREHISTORIC version of the codec) and run
the normal import to be sure, but Robert Plant's "Fate of Nations" album
looks good after that catalog update w/ verify:

[image: image.png]

Thanks!

**Comment by lachlan-00** [comment]
Definitely had to make some changes for that. I don't know if vorbis support emails for ratings but if it does we can also add that to identify users like with id3.

Glad it got sorted and now Ampache is a little better
