### ISSUE TITLE
How to disable trending page.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2402]
This is the 1'st. I've checked out Ampache in about 1.5 years.  I thought there was a setting or switch that enabled going directly to their respective libraries when the albums or artists buttons were pressed.  I checked both the interface settings and the config file.  I don't  care at all about statics:  I just wanna listen to my music.  Is my memory failing me? 😊

**Comment by wagnered** [comment]
IMHO if "Trending" was added to the "Information" drop-down on the left menu, the  page wouldn't be needed.

**Comment by lachlan-00** [comment]
This actually prompted me to do what i intended to do moving those items to mashup.

Back when i started a fork i was working on making the sidebar consistent with the intention of using a header on each title bar like the search function. (music header, search header, playlists, etc)

so now the index and browse pages (not all of them just the ones that made sense) are put into a browse header.
![image](https://user-images.githubusercontent.com/1305249/84238657-c0408f80-ab3e-11ea-94af-fb51965a8d4a.png)

**Comment by lachlan-00** [comment]
I've rearranged the main sidebar a bit to focus on the 'Browse' aspect of that main section. the mashup is now back to just the light sidebar.
