### ISSUE TITLE
Top rated list is different depending on what you viewed previously

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2403]
### Describe the bug

When viewing top rated songs, I noticed that the list wasn't consistent.  So I'm not sure what is the true top rated list of songs.
### To reproduce

1. Go to the main page, click on Top Rated on the sidebar and view the list
2. Click on one of the other options under the information submenu
3. Click on Top Rated again. 
4. May need to repeat steps 1 to 3 selecting different options. Sometimes the list isn't the same.

### Expected behavior

Same list every time.

### Screenshots

![Peek 2020-06-10 12-38](https://user-images.githubusercontent.com/4076671/84294614-6d9fad00-ab17-11ea-8542-bcbffed632db.gif)

## Environment

* Ampache version: 5d82ead35192a10260e1be91efff3a97218eb170
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache

**Comment by lachlan-00** [comment]
that's interesting, i think the order is set to random because of other areas but this area doesn't need that. it's also interesting that just reloading the page doesn't recall the query.

it's done in get_highest so i will add an ability to not randomise the list.
(probably sort by rating, playcount, id)
```
Rating::get_highest_sql('song');
```

**Comment by lachlan-00** [comment]
does it do it for albums?

**Comment by lachlan-00** [comment]
so the select is
```
AVG(`rating`) AS `rating`, COUNT(`object_id`) AS `count`
```
and the order is
```
ORDER BY `rating`, `count` DESC
```

which doesn't seem like it would change.... investigating

**Comment by lachlan-00** [comment]
added extra sorting in commit 0e68812 based on the order that the rating was added.

That way the list will only change when a different song is rated 5*

**Comment by stebe** [comment]
I didn't notice it on albums but albums are not rated as often as songs.   The fix now shows consistent sort.

**Comment by lachlan-00** [comment]
all good, it's actually specific to song browsing so fixed!
