### ISSUE TITLE
JSON API inconsistencies

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#2411]
Looking at the JSON API documentation at http://ampache.org/api-json.htm, I find the following aspects somewhat odd. I haven't checked the actual implementation, only the documentation.

1. The representation of the tags is different in `song` responses compared to `album` and `artist` responses. For a song, the tags may be shown e.g. as 
```
        "tags": [
            "Rock",
            "Gothic Metal",
            "Heavy Metal",
            "Symphonic Rock",
            "Symphonic Metal"
        ]
```
and for an album as 
```
        "tags": "{\n    \"id\": 4,\n    \"count\": 1,\n    \"name\": \"Electronic\"\n}",
```

Meanwhile, the XML API represents the tags using the same format in all cases:
```
    <tag id="20" count="1" ><![CDATA[Metal]]></tag>
    <tag id="37" count="1" ><![CDATA[Hard Rock]]></tag>
```

I think that neither of the formats documented for the JSON API are good, because the first one is missing some data available on the XML API, and the second one is a singular object instead of an array.

2. In the XML API, all data responses have the node `total_count` at the top, but no such nodes are documented in the JSON API. If the node is useful for the XML clients, then wouldn't it be useful for the JSON clients, too?

**Comment by paulijar** [comment]
The reason I'm interested on this is because I'm in the process of adding JSON support to the Ampache compatible API provided by the [ownCloud/Nextcloud Music](https://github.com/owncloud/music) application. I think that from the point-of-view of development and maintenance, it would be preferable that the JSON and XML APIs would be as similar as possible, of course taking into account the capabilities of the format. For the Subsonic API, we have such an architecture, that all the responses are first defined using an internal format, and then converted to either XML or JSON. The conversion happens using generic rules, so there is basically 1-to-1 mapping between various structures in XML and JSON. I would like to use similar architecture also on the Ampache API, but it will be difficult if there are many subtle differences in the content provided via these two APIs.

**Comment by lachlan-00** [comment]
@paulijar you're correct in that the json and xml should be 1to1.

Technically the JSON api isn't stable so we need to do some matching in this before 4.2.0

I've been making a  few xml changes to fix some bugs so we'll need to do a comparison between the examples as part of this.

**Comment by lachlan-00** [comment]
@AshotN do you want to put those in or keep the counts like we have before?

**Comment by paulijar** [comment]
Okay, if the JSON API is not yet frozen, then another thing you might want to consider is the use of singular or plural forms in the key names. Currently, the JSON API has e.g. the plural key `tags` where the XML API has multiple `tag` elements. Of course it makes sense to use plural when there are potentially multiple values, but on the other hand, sticking with the singular form used in the XML API would make sharing the implementation between the APIs easier.

In the Subsonic, they have decided to use the key names in singular form even when the value is an array. This can be seen e.g. from
http://demo.subsonic.org/rest/getAlbumList.view?u=guest4&c=test&v=1.16&s=123&t=fcf41657f02f88137a1bcf068a32c0a3&f=json&type=recent

The corresponding XML API result is
http://demo.subsonic.org/rest/getAlbumList.view?u=guest4&c=test&v=1.16&s=123&t=fcf41657f02f88137a1bcf068a32c0a3&f=xml&type=recent

**Comment by AshotN** [comment]
I omitted the total count on purpose. Didn't make sense to include redundant information since the client can get the count pretty easily.

As far as naming parity goes, I agree they should be the same. But since the JSON API is newer, I think we can use the opportunity to change things for the better.

**Comment by wagnered** [comment]
@lachlan-00 will the XML api be going away?  If not, there needs to be parity between the two. If so then , in my mind the version would need to be bumped up because of non-compatability issues.  I suggest bringing parity between the two, deprecating the XML api and give a milepost for it's removal. BTW is there a means of alerting at either installation or at other times other times, such as messaging? Oh yes maybe the way that Admin is alerted to new versions (commits) .

**Comment by AshotN** [comment]
I personally think the XML API ought to be deprecated, but not removed for a long time. A lot of applications still use the XML API and removing it would break them. But I personally find XML much harder to work with than JSON and a waste of development effort to maintain. If we froze it and focused on the JSON API I think we can save a lot of duplicated effort.

**Comment by paulijar** [comment]
@AshotN 
Well, if you design the APIs intelligently, then supporting both XML and JSON at the same time isn't that much of a burden, as you can implement a generic format conversion. Then it's more like a one-time investment than a continuous strain on effort. But if you have many differences in the two APIs, then it is going to require double maintenance effort.

I believe that some clients will want to rather use XML than JSON, and are not thrilled to move over even in the long run. It may be just a personal preference, or the client application may be already using XML extensively on other things, providing them synergy benefits when using XML also in the Ampache API.

I personally quite didn't understand the purpose of the `total_count`, either, but if there is some reason for it to exist in the XML, then that reason probably applies to the JSON as well. And if there is no reason, then it should be removed from the XML, too. One benefit I can think of, is that it may be handy for a human reader when manually testing the API. Another one could be some rare edge case, where you want to know the number of the results without parsing the whole thing.

**Comment by AshotN** [comment]
Ideally the API would be extensible and allow as many formats as possible, but currently it's a bit extra code that is just not the priority to simplify currently. 

`total_count` doesn't belong in JSON but I don't think needs to be removed from XML, just in case some apps are using it we don't want to break backwards compatibility. 

If we ever do a whole API refactor, with a major version change, perhaps we can justify some large changes to the XML API.

**Comment by lachlan-00** [comment]
For total_count, xml children can be counted the same way as Json arrays so i don't really know what it's use is. It's been around since the beginning of the api as far as i know. it's redundant for both api's so might actually be better removed instead of added in.

Might be good to warn in documentation that it's depreciated and to use the actual XML child count instead as it's not really providing valuable info.

I don't have a desire to drop either version for a single API though. XML still works so i don't want to limit anyone to a particular process when they both work. it's not a huge amount of more work and i feel like it has made me a lot better at managing the API by having to understand how both work.

**Comment by lachlan-00** [comment]
@paulijar the docs themselves i need to rewrite again now that i'm getting close to finishing up.

The visual issues in the examples i'll be fixing up if they exists but may have been from me copy/pasting from different sources as well. if it's in the code i'll find it as right now i have a script that runs through each method that i need to rewrite for the new methods this version.

**Comment by lachlan-00** [comment]
@AshotN the tag string doesn't seem to work as well as the song code.

Songs come up with an array but only by name
![image](https://user-images.githubusercontent.com/1305249/85978014-1ce9e880-ba21-11ea-99f4-16664864b4af.png)

while Album/artist are just strings that don't seem to be treated correctly as in the original comment
![image](https://user-images.githubusercontent.com/1305249/85978058-2e32f500-ba21-11ea-81f4-ca35f75b5693.png)

**Comment by lachlan-00** [comment]
found another odd one, genre is included in song but not anywhere else where tags is used with id, name

I'm just pushing a change to make all tags report as an array as well as simplify the code made to support genre by rename tags_string to tags_array.

I think i'll make total_count and genre depreciated data for the next release.

**Comment by lachlan-00** [comment]
Here's a current example

of song
```
[
    {
        "id": "802560",
        "title": "Baker Street",
        "name": "Baker Street",
        "artist": {
            "id": "254",
            "name": "Foo Fighters"
        },
        "album": {
            "id": "71644",
            "name": "My Hero"
        },
        "tags": [
            {
                "id": "22",
                "name": "Pop"
            },
            {
                "id": "6",
                "name": "Rock"
            },
            {
                "id": "33",
                "name": "Alternative Rock"
            }
        ],
        "filename": "\/mnt\/music\/Foo Fighters\/(1998) My Hero (single) [CDCL 796]\/102 - Baker Street.mp3",
        "track": 2,
        "playlisttrack": 1,
        "time": 339,
        "year": "1998",
        "bitrate": "320000",
        "rate": "44100",
        "mode": "cbr",
        "mime": "audio\/mpeg",
        "url": "https:\/\/music.\/play\/index.php?ssid=&type=song&oid=802560&uid=2&player=api&name=Foo%20Fighters%20-%20Baker%20Street.mp3",
        "size": "13650833",
        "mbid": "57497521-16ac-4870-8fe0-4f486652d8ef",
        "album_mbid": null,
        "artist_mbid": null,
        "albumartist_mbid": null,
        "art": "https:\/\/music.\/image.php?object_id=71644&object_type=album&auth=&name=art.jpg",
        "flag": 1,
        "preciserating": 5,
        "rating": 5,
        "averagerating": 0,
        "playcount": 1,
        "composer": "Gerry Rafferty",
        "channels": null,
        "comment": "",
        "license": null,
        "publisher": "Capitol Records",
        "language": "eng",
        "replaygain_album_gain": "0.000000",
        "replaygain_album_peak": "0.000000",
        "replaygain_track_gain": "-7.200000",
        "replaygain_track_peak": "1.000000",
        "genre": [
            {
                "name": "Pop"
            },
            {
                "name": "Rock"
            },
            {
                "name": "Alternative Rock"
            }
        ]
    }
]
```

and an album
```
[
    {
        "id": "57887",
        "name": "(It (Is) It) Critical Band",
        "artist": {
            "id": "9205",
            "name": "90 Day Men \/ GoGoGoAirheart"
        },
        "year": 2000,
        "tracks": 8,
        "disk": 1,
        "tags": [
            {
                "id": "674",
                "name": "Math Rock"
            },
            {
                "id": "1415",
                "name": "Post Rock"
            }
        ],
        "art": "https:\/\/music.\/image.php?object_id=57887&object_type=album&auth=",
        "flag": 0,
        "preciserating": 0,
        "rating": 0,
        "averagerating": 0,
        "mbid": "d6fc36cc-9351-4b53-b7db-7f5b30804800"
    }
]
```

and an artist
```
[
    {
        "id": "58",
        "name": "Ratatat",
        "tags": [
            {
                "id": "4",
                "name": "Electronic"
            },
            {
                "id": "6",
                "name": "Rock"
            },
            {
                "id": "16",
                "name": "Alternative"
            },
            {
                "id": "36",
                "name": "Indie Rock"
            },
            {
                "id": "55",
                "name": "Electro"
            },
            {
                "id": "77",
                "name": "Experimental"
            }
        ],
        "albums": 2,
        "songs": 25,
        "art": "https:\/\/music.\/image.php?object_id=58&object_type=artist&auth=",
        "flag": 0,
        "preciserating": 0,
        "rating": 0,
        "averagerating": 0,
        "mbid": "f467181e-d5e0-4285-b47e-e853dcc89ee7",
        "summary": "Ratatat, from Brooklyn, New York, United States. ",
        "yearformed": 0,
        "placeformed": ""
    }
}
```

**Comment by lachlan-00** [comment]
Okay, I'm going to continue this tomorrow based on a few rules 

* ID is a string for all objects.
* Everything that has an ID should include this in the response.
* All other integers are cast to int
* Same thing for doubles
* Null values are to be cast as empty strings or zero
* Total count is depreciated but not to be removed until API 5.
* Genre in songs is depreciated and will be removed in API 5.
* Python3-ampache will produce example files for all methods exactly as received to help identify methods that don't enforce these rules.

Now that I've got a new nvme and reinstalled debian I can start pushing on this a bit more. I'll also set debugging up to test how data is cast so I don't need to read them all.

**Comment by lachlan-00** [comment]
I'm out at a datacentre today but will be documenting the api and will flesh out the rules above into standard information about what to expect

https://github.com/ampache/ampache/wiki/API-Standards

**Comment by AshotN** [comment]
I don't think null should be cast to 0 or "" 

Null is a different thing, and it's important to have the distinction between null and 0.

**Comment by lachlan-00** [comment]
wouldn't it be better to provide the the correct type to clients? I was thinking that by defining required value types we can provide a clear certainty about what the api will give you.

in php they all equate to each other as well so they will cast as empty strings or 0
![image](https://user-images.githubusercontent.com/1305249/86196201-116bfe00-bb96-11ea-8478-1bfcfc45c1f2.png)

**Comment by AshotN** [comment]
I think it depends on the variable.

If it's something like user email address, if it doesn't exist, the API should report null not "".

**Comment by lachlan-00** [comment]
would clients pick up an email as "null" though?
i'm not sure if it would do that but i'll check it out

**Comment by lachlan-00** [comment]
I thought it might affect xml but simplexml will just create the object and you can cast it to a string anyway.
so then rule change.

Object id is forced to string but null doesn't need to be cast

**Comment by memen45** [comment]
>     * Total count is depreciated but not to be removed until API 5.

The way I understood the total_count attribute is that it shows the total number of results, even when the 'limit' and 'offset' parameters are used. It is not redundant, since checking for the size() of an array in json would result in some number <= limit, instead of the total number of (search)results that are available.

**Comment by lachlan-00** [comment]
Total count gets sliced by the limit so it will be <= limit if higher

**Comment by memen45** [comment]
Ah, okay, sorry, in that case I agree it is redundant. Weird though that it is not possible to see the number of results without actually retrieving all the results, especially for search results where you can't know the number of results in advance.

**Comment by paulijar** [comment]
> The way I understood the total_count attribute is that it shows the total number of results, even when the 'limit' and 'offset' parameters are used.

I also suspected that it could work like this when I first saw that there is such an element. But then I checked the Ampache implementation, and realized that this is not the case. But indeed, reporting the total number of results instead of the limited number (by `offset`+`limit`) would be much more sensible, and that way, the element wouldn't be totally worthless.

**Comment by lachlan-00** [comment]
it would be good to have something to indicate that you need to pull the extra results using the offset.

**Comment by lachlan-00** [comment]
I've been thinking about this and i think we include something like <total_results>

this would allow you to ++ your returned item count and give you the offset to start next with?

**Comment by lachlan-00** [comment]
I've started splitting the spec for 4.2.0 api out into it's own documentation
https://github.com/ampache/ampache/wiki/Ampache-API-4-2-0

i've also split the API into it's own section in the sidebar.
![image](https://user-images.githubusercontent.com/1305249/89595573-30963380-d898-11ea-8a17-95c55e1ce5b3.png)

Done some initial cleanup and fixed some errors. really liking this style instead of live updating the develop section.

this also means old versions can be removed from the sidebar without being removed from the wiki for historical purposes.

**Comment by lachlan-00** [comment]
future versions will include these spec files and examples in the docs folder

**Comment by kuzi-moto** [comment]
What about the API documentation on the ampache.org site?

**Comment by lachlan-00** [comment]
I'm going to do a rewrite of the whole site now that this release is out.

There are a few static site generators that I'm looking at to do this and for now I'm going to redirect org back to the wiki

**Comment by kuzi-moto** [comment]
Ah, good plan. Just to throw in my 2 cents in I like using Hugo, and there are some nice documentation themes available. A single executable and super fast.

**Comment by lachlan-00** [comment]
hugo and gatsby are my current frontrunners. Fosstodon has some really quick responses

**Comment by lachlan-00** [comment]
gatsby was the winner for being the easiest to convert from with  wiki.

check out what took a few hours today
http://ampache.org/api/

**Comment by kuzi-moto** [comment]
Nice! That turned out really good.

**Comment by lachlan-00** [comment]
just need to see why the contents table isn't showing up after building and i'll move the rest over/ start advertising it

table shows up in develop but disappears after building the site.

**Comment by lachlan-00** [comment]
Really solid progress regarding API:
Site
API docs
Examples
Python lib
Test servers
Repeatability
Rules
Standards

Should be set for the life of 5 now.
