### ISSUE TITLE
[Feature Request] Some search enhancements

### ISSUE THREAD

**Issue by jleipsig** [ampache/ampache#2414]
I would like to add some features to search to make it even more powerful.

- Search in lyrics. Other fields from song_data (comment, label) are also searchable.
- Search with regular expressions in text fields. MYSQL supports it, and it gives a lot of extra possibilities.
- Search for non-existent metadata. When searching for an empty string in a metadata field with operator 'is', there are never results because empty values are not stored. You could use this to search for songs that don't have the given metadata field at all.

![search_enhancement](https://user-images.githubusercontent.com/14284810/84602059-053d2c80-ae85-11ea-8ce9-bd1cba1f0946.png)

This search translates to SQL:
`SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `song_data` ON `song`.`id`=`song_data`.`song_id` WHERE `song_data`.`lyrics` REGEXP 'colo[u]?r' AND NOT EXISTS (SELECT NULL FROM `metadata` WHERE `metadata`.`object_id` = `song`.`id` AND `metadata`.`field` = 28)
`

**Comment by lachlan-00** [comment]
one thing i see here is dupe names of the operators. (this isn't from you the metadata operators are a merger of text and numeric which both have the same names)

should look at changing that on probably the numeric side
![image](https://user-images.githubusercontent.com/1305249/84618719-56e1c780-af16-11ea-937c-05e98403b757.png)

**Comment by lachlan-00** [comment]
okay fixed that
