### ISSUE TITLE
Searches on metadata fields with 'any rule' are slow

### ISSUE THREAD

**Issue by jleipsig** [ampache/ampache#2420]
## Description
When i perform a search on more than one metadata field, it takes a very long time before the search results are shown. More than 10 minutes on my (old) 'server'.

### To reproduce
Create a search on page search.php?type=song. Select match 'any rules'. Create two rules with metadata.

### Expected behavior
It would be nice if the results are shown within a few seconds.

### Screenshots

![metadata_search_any](https://user-images.githubusercontent.com/14284810/84836852-e8485b00-b036-11ea-871e-9d48420d5521.png)

## Environment

* Ampache version: develop (cacd6bda lachlan-00 <lachlan.00@gmail.com> on 6/16/20 at 6:55 AM)
* Web server + version: Apache 2.4.38-3+deb10u3
* Server operating system: Debian GNU/Linux 10 (buster)
* Client operating system: Debian GNU/Linux 10 (buster)

### Client type

* Web

**Comment by lachlan-00** [comment]
your query change is about 100% faster than before
