### ISSUE TITLE
songs with negative or big track numbers are not imported 

### ISSUE THREAD

**Issue by jleipsig** [ampache/ampache#2429]
## Description
When adding a song with a negative or big (>65535) track number, the insert fails
When updating songs, big numbers are (sometimes) truncated to 5 digits.

### To reproduce
Give the file a big (>65535) or negative tracknr, e.g. with kid3-cli:
kid3-cli /home/me/music/test2.mp3
kid3-cli> set 'Track Number' 975287
kid3-cli> save
kid3-cli> get
File: MPEG 1 Layer 3 170 kbps 44100 Hz Stereo 6:35
  Name: test2.mp3
Tag 2: ID3v2.3.0
  Title         Test 2
  Artist        Test
  Date          2020
  Track Number 975287

Do import/update in ampache

kid3-cli /home/me/music/test2.mp3
kid3-cli> set 'Track Number' -10
kid3-cli> get
File: MPEG 1 Layer 3 170 kbps 44100 Hz Stereo 6:35
  Name: test2.mp3
Tag 2: ID3v2.3.0
  Title         Test 2
  Artist        Test
  Date          2020
  Track Number -10

Do import/update in ampache

### Expected behavior

I would expect the track to be added.
Because the import fail is 'silent', it's hard to find out what tracks are not imported because of errors.

## Environment
* Ampache version: develop (580b1417 Manuel <psy-virus@users.noreply.github.com> on 6/20/20 at 12:55 PM)
* Web server + version: nginx/1.17.9
* Server operating system: Debian GNU/Linux 10 (buster)
* Client operating system: Debian GNU/Linux 10 (buster)
* Database: MariaDB 10.2.31

### Client type

* Web
* Ampache

## Logs
2020-06-20T16:57:12+02:00 [admin] (dba.class) -> Error_query SQL: INSERT INTO `song` (`catalog`, `file`, `album`, `artist`, `title`, `bitrate`, `rate`, `mode`, `size`, `time`, `track`, `ad
dition_time`, `year`, `mbid`, `user_upload`, `license`, `composer`, `channels`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-06-20T16:57:12+02:00 [admin] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'track' at row 1"] 
2020-06-20T16:57:12+02:00 [admin] (song.class) -> Unable to insert /home/me/music/test2.mp3

**Comment by lachlan-00** [comment]
okay, i'm going to convert this to a db update to allow unsigned ints which will reduce the total size of available positive values but will cover more valid albums than such a large number

**Comment by lachlan-00** [comment]
okay, dbupdate in truncating < 32k into 0 and check_track used from the pull to check high/low values

**Comment by lachlan-00** [comment]
This is checked before insert now. you are also allowed to have negative track numbers
