### ISSUE TITLE
[Feature Request] Access to the "license" field thru the API

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#2431]
Currently as far as I know the Ampache API does not include any way to access the "license" information of the tracks. 

This would be very useful for public servers such as Dogmazic's one, which is dedicated to free-licensed music, if this information could be accessible programmatically through the API. It would allow to develop third-party tools that could make, say, a selection of tracks that you download with it, then redistributable as-is (since indicating licensing information is required by most free/open licenses when talking about redistribution). 

Such a feature could allow people to use such tools to make partial or complete backups of the whole Ampache-powered Dogmazic archive that they could quietly store, and later republish, without breaking licenses' terms.

**Comment by lachlan-00** [comment]
Thank you for bringing this issue up.

seems like you would benifit from
* licence attributes in the objects
* ability to search by licence (probably available in advanced_search?) but maybe extend playlist_generate as well
* bulk download links

I don't think I have much licence information in my files. did you have to manually create and assign or did it fill from tags?

I think the licence generation could probably be expanded a little bit too as Ampache should pre fill this information for common free licences

**Comment by shangril** [comment]
The licensing information on our public server absolutely didn't came from tags. 

We had about 50 000 tracks in our old archive, for which we had the licensing information stored in a database, and Afterster achieved to import these data through a script. Then, in the next years, people uploaded more tracks in the new archive through the Ampache interface, and each time they indicated the licensing information manually when uploading new files. Hope this helps.

**Comment by lachlan-00** [comment]
That does because the first track I tried to import with licensing failed with a SQL error and that's probably been the case for years.

I'll be updating Ampache to allow a url or license name to match with existing names in the database. Probably the same for labels as well.

I'll start on these this week.

**Comment by lachlan-00** [comment]
okay, now if there are license tags in your files they will search for name / url to identify. If no license is found it will create a new one by name even if it's a url. (i had tags with just the CCBY url and no name.)

I've also added the license attribute to song output and new api methods API::licenses API::license to allow searching by licenses.

**Comment by lachlan-00** [comment]
this is closed as the license is available from the api now. when enabled, you can also use the license methods to get a list of songs under that field.

(probably should have closed this ages ago but let me know if you want to do more with this in a new issue)

**Comment by wagnered** [comment]
> Currently as far as I know the Ampache API does not include any way to access the "license" information of the tracks.

Of course, there is no formal spec declaring the license.  The [cc wiki](https://wiki.creativecommons.org/wiki/Web_Integration)  describes a restful API that will help the user choose an appropriate CC license  and supply the needed text to display  when the licensed track is viewed.  I am going to do a PR to implement it. Just having a url to a license selected is not adequate copyright  protection.
