### ISSUE TITLE
API Requests should not redirect to /update

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2433]
Whenever I merge a new version of Ampache, I have to go through the web interface and "Update Now". I think the API should still resolve normally to not break applications. 

![image](https://user-images.githubusercontent.com/1350342/85808799-7a421900-b745-11ea-987f-541a51b84ead.png)

**Comment by lachlan-00** [comment]
that's something i never thought of, i'll intentionally lower my version to see why this happens

**Comment by lachlan-00** [comment]
updates from the api is an intended function at some point too.

**Comment by lachlan-00** [comment]
probably in the init
```
require_once '../lib/init.php';
```

**Comment by lachlan-00** [comment]
set ignore database update in https://github.com/ampache/ampache/commit/a1e5e5856d96a6bbe84c720587dbc85f7db45190
