### ISSUE TITLE
Searching for track in Subsonic Android client 

### ISSUE THREAD

**Issue by ramiws** [ampache/ampache#2434]
Hi, I like ampache and been using it daily. Thank you!

When I tried to use the text search for a track, the app quick list few results that matched the string then I clicked on the track I wanted. It says contacting server and then gives me a huge list of tracks, while I was expecting only the track that I selected

Is very easy to reproduce..

**Comment by lachlan-00** [comment]
is this an official android subsonic client? or something like dsub?

**Comment by ramiws** [comment]
https://play.google.com/store/apps/details?id=net.sourceforge.subsonic.androidapp&hl=en
Subsonic Music Streamer

Yes it is one of the official apps

**Comment by lachlan-00** [comment]
Ok, just grabbed it to check

so, 
* magnifier at the top
* search for song
* scroll down to individual track
* click song.

This is what i get:
* Click artist -> go to artist page
* Click album -> go to album page
* Click song -> go to album page

**Comment by ramiws** [comment]
Ok I guess I know what is happening in my case.
So I have all my songs with "Unknown (Orphaned)" as album and artist :/ 
But I do not care about having correct album and artist. I have used to youtubedl script to pull all my soundcloud songs.
The search is working as I can click on the song found by the search, but I cannot play it as I get the list of all songs as they are all flagged with "Unknown (Orphaned)"

Any workarounds?

**Comment by kuzi-moto** [comment]
Ampache really works best when music is properly tagged. That being said, software like [Mp3tag](https://www.mp3tag.de/en/) or [TagScanner](https://www.xdlab.ru/en/) can allow you to auto-fill the tags based on the file name, or mass edit track information.

I assume you have used youtube-dl to generate a file with the track title as the filename at a bare minimum, so you could have the software fill the Title field from filename, then just assign something generic for Artist, and Album fields such as "Various Artists", and "SoundCloud" respectively.

**Comment by lachlan-00** [comment]
you don't have to tag if you use the naming patterns.
![image](https://user-images.githubusercontent.com/1305249/86853554-08c97980-c0fa-11ea-9bf5-a28d0b5b49d8.png)

but remembr that unless it matches ALL fields it won't identify them

so in my example i'm using a catalog number in square brackets. if i ignore that my files will not name correctly.

**Comment by mitchray** [comment]
Seems like this can be closed
