### ISSUE TITLE
Last FM API changes make it unusable for artist art

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2436]
https://www.reddit.com/r/lastfm/comments/bjwcqh/api_announcement_lastfm_support_community/ explains it

The Last FM API heavily throttles it seems, which is probably why my gather_art keeps returning a stupid white star. 

We should consider finding a better source for images, or understand the last fm limitations better to not have such a negative impact on Ampache usability.

**Comment by AshotN** [comment]
After furthur research, it seems they just stopped providing artist artwork. It just returns "https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png" for everything

**Comment by wagnered** [comment]
How does Google and Musicbrainz do with finding artist art?

If more sources are required, both lastFM and Spotify provides artist images through their api, but both require app registration and api key, which Ampache already provides for lastFM.

**Comment by lachlan-00** [comment]
musicbrainz gives a source url which we search, currently only what's filtered in art.class
![image](https://user-images.githubusercontent.com/1305249/85971531-bb218280-ba10-11ea-8dcc-8c0c59b9f03e.png)

**Comment by wagnered** [comment]
It seems to me that grabbing the art should be the job of the plug in.

Last.FM can do it with a call to Artist.getInfo which gives the URL to three different sized images.

So can Musicbrainz but I'm not sure the current composer package or plugin is capllable.

**Comment by wagnered** [comment]
Ampache has most of the means for grabbing artist images already built in: The default type has been hardcoded to 'default' which apparently means cover art.  Maybe last.FM didn't have the capability when art.class was designed.  I'll look into adding it

**Comment by lachlan-00** [comment]
i haven't actually checked whether coverart from the files are used, i've always had a separate folder.jpg as well as the art in the files

**Comment by paulijar** [comment]
> Last.FM can do it with a call to Artist.getInfo which gives the URL to three different sized images.

I think that the whole point of this issue is that this method of getting artist image from Last.FM no longer works. It used to work, but nowadays all those URLs return just a placeholder image. This is an intentional change by Last.FM. I guess that they kept those URL links there to not break the API, although they no longer want to provide artist art for any external applications.

**Comment by wagnered** [comment]
Yes, my apologies.  I just thought this fact would be documented on their website and I couldn't find anything confirming the fact that it no longer works so I assumed it still does.

Anyway, I'm looking into configuring Ampache to use Musicbrainz for artist images: Currently fighting to understand the logic flow.

**Comment by lachlan-00** [comment]
last.fm won't get artist art anymore so this is closed. we have spotify now!
