### ISSUE TITLE
Oracle MYSQL testing on browse pages

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2442]
This commit broke all of my browse page results, returning 'no songs found' etc. for Songs, Albums, Artists, Radio Stations and Podcast browse pages.
I initially thought it may be related to the actions I took to work around a previous issue #2320 by disabling only_full_group_by mode in my MySQL config file, but restoring this and restarting MySQL did not restore the browse page results.
Reverting back to commit dc1f04b returned expected results.

lachlan-00 replied 23 hours ago

i did break one query part which i've reverted this morning.
image
![image](https://user-images.githubusercontent.com/1305249/86661724-5927d500-c02f-11ea-91af-e30dfd75ef0b.png)

you get it on /browse.php?action=[song|artist|etc] links? i'm able to browse with grouping on/off this morning.

rsinfotech replied 6 hours ago

Yes, it's the /browse.php?action= pages that this happens on.
That commit fixes all browse.php pages with grouping off and everything except the albums page with grouping on?
Great work by the way to all involved...

**Comment by lachlan-00** [comment]
@rsinfotech

I can think of a few ways this might break for you with albums but i have set full grouping and not been able to break it from latest develop.

I have found one more query error which i'm looking at now to do with albums
```
2020-07-07T09:03:10+10:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1055,"'music.album.id' isn't in GROUP BY"]
2020-07-07T09:03:10+10:00 [ampache] (dba.class) -> Error_query SQL: SELECT DISTINCT(`album`.`id`) FROM `album` LEFT JOIN `artist` ON `artist`.`id`=`album`.`album_artist` WHERE (`album`.`name` = 'Century Collapsing'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) = 'Century Collapsing') AND (`artist`.`name` = 'Effigy' OR LTRIM(CONCAT(COALESCE(`artist`.`prefix`, ''), ' ', `artist`.`name`)) = 'Effigy') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year`,`album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year`
```

**Comment by lachlan-00** [comment]
okay, i've been through the entire interface clicking on everything and have actually left full group on my server now to see if any more come up.

**Comment by rsinfotech** [comment]
Brilliant work @lachlan-00, thanks for all the help.
Commit a8b49df54 is still the same for me with grouping on, only the albums page returns no results, everything else is fine.
The ampache log reports: 
`(dba.class) -> Error_query MSG: ["42000",1055,"Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.album.disk' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]`

**Comment by lachlan-00** [comment]
the "Error_query SQL" line will let me track that down. i'll also do some testing/browseing looking for the album.disk queries

**Comment by lachlan-00** [comment]
i think it may in Artist::get_albums so i'll check now
![image](https://user-images.githubusercontent.com/1305249/86857230-6c0ada00-c101-11ea-9e8d-982cb3a6fcb4.png)

**Comment by lachlan-00** [comment]
actually i think it's still in the browse query. this works in mariadb but doesn't work in MySQL?

with grouping the disk part shouldn't actually be on there anyway either.

```
SELECT MIN(`album`.`id`) AS `id`
FROM `album`
LEFT JOIN `song` ON `song`.`album`=`album`.`id`
LEFT JOIN `catalog` ON `catalog`.`id`=`song`.`catalog`
WHERE 1=1 AND `catalog`.`enabled` = '1'
GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`mbid`, `album`.`year`
ORDER BY `album`.`name` ASC, `album`.`disk` ASC LIMIT 0, 45
```

**Comment by lachlan-00** [comment]
okay, i've taken that out of the browse in ef9959c19 because it's actually not required.

@rsinfotech would you be able to give me the mysql sql_mode for your server as well?
```
SELECT @@sql_mode;
```

in mariadb without full group mine is
```
STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

**Comment by rsinfotech** [comment]
With everything working and grouping off it's
`STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`
Adding `ONLY_FULL_GROUP_BY` to the default modes breaks the albums page.

**Comment by lachlan-00** [comment]
i'm going to try this out on windows with this as all my servers are mariadb/debian
https://ampps.com/download

**Comment by lachlan-00** [comment]
can confirm it's still happening with oracle specifically so i'll dig from my desktop

**Comment by lachlan-00** [comment]
hey @kuzi-moto you used xammp and things before right? did you have to do anything weird with the logging or is it just me? I couldn't get query errors in the debug but it was very clearly having errors

I'm going to move back to my laptop with oracle but it was very hard trying to configure logging on windows.

**Comment by kuzi-moto** [comment]
Hmm, I don't remember having many issues, but I don't think I messed with logging much. I really only looked at it enough to write the Windows guide.

**Comment by lachlan-00** [comment]
Thats okay, i found a lot of issues.

Oracle MySQL was also writing each album/artist/tvshow as id 0!

**Comment by lachlan-00** [comment]
@rsinfotech can you give me this sql query?

```
SELECT DISTINCT `id` FROM `album`;
```

**Comment by rsinfotech** [comment]
@lachlan-00 running that query returns 6555 results which matches the number of albums in my catalogue.

Also noticed this morning that when attempting to add new albums in my usual way using the catalog_update.inc script from the command line, that only the new artist was showing in the stats.php?action=newest page and not the new album?

No errors were being reported in the ampache logs and the catalog_update.inc script was completing as expected.

I had to revert back to commit fe5718c05 before both the album and the artist were being listed again on the newest page.

**Comment by rsinfotech** [comment]
Commit 2fbd4622e solves the adding of new albums issue mentioned above.

**Comment by lachlan-00** [comment]
i'm going to do another windows install on develop and try these all again.

**Comment by lachlan-00** [comment]
okay, i've install another Ampps on windows and gone through the gauntlet.

can't generate any errors with SQL now.

**Comment by rsinfotech** [comment]
I can confirm that commit f7190f53b seems to have addressed the MySQL errors that I was getting with only_full_group_by mode enabled in my.cnf.

All browse pages are now returning the expected results with only_full_group_by mode enabled (which it is by default).

Incidentally, I'm running Fedora31 with Apache version 2.4.43 and MySQL version 8.0.20.

**Comment by rsinfotech** [comment]
Don't know if this is related to the changes made for the MySQL issues but commit f7190f53b introduced another issue where the adding of tags when adding new albums was failing with the log message:

`(dba.class) -> Error_query MSG: ["23000",1048,"Column 'object_id' cannot be null"]`

Had to roll back to commit 7d79778ee to get my tags working again when adding new albums.

**Comment by lachlan-00** [comment]
Great to see we're nearly there!

can you give me the error sql as well so i can do a find?

**Comment by lachlan-00** [comment]
don't worry i found it manully. looking now

**Comment by lachlan-00** [comment]
fixed with 090a0855c

**Comment by lachlan-00** [comment]
There's a different bug. It's adding the tags to the database but not updating visually or in the api

**Comment by lachlan-00** [comment]
okay, fixed that too.

**Comment by rsinfotech** [comment]
Brilliant work @lachlan-00 , thanks for all of your help with these issues and for such a speedy response.

The latest commit fixes the tag issue for me and all previous SQL issues seem to have been addressed and are now working with only_full_group_by mode enabled.

**Comment by lachlan-00** [comment]
Nice! Oracle seems to be pushing changes that mariadb will follow so we need to keep pace with both.

I'm about to gear up into test mode for this release now so will do the same thing again when I hit that.

I've saved a query for my server to turn grouping on in mariadb as well as an oracle server with MySQL on my desktop so I think I should be able to catch these more often (if they come up)

It's also made the queries better in the process and making Ampache better is why I'm here.

**Comment by rsinfotech** [comment]
Stumbled across another only_full_group_by error while viewing the admin page for browse users - users.php

I have track_user_ip = "true" set in ampache.cfg.php and the 'Last IP' column was showing 'Not Enough Data' for all users, even if currently logged on.

Clicking on 'Not Enough Data' takes you to the IP History page for that user, which lists 2 empty rows with Date and IP Address:

![image](https://user-images.githubusercontent.com/3216809/88465126-61e62b00-ceb8-11ea-9e25-431c2319049e.png)

The following error message is returned multiple times in the ampache log file: 

`(dba.class) -> Error_query MSG: ["42000",1055,"Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ampache.ip_history.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]`

No rush at all for a fix for this, just thought I should keep reporting any more of these I come across here, hope it helps.

**Comment by lachlan-00** [comment]
good find, my oracle test doesn't have the options on for everything so i'll do that now

**Comment by rsinfotech** [comment]
Just noticed another only_full_group_by error in the logs.

This time triggered by clicking the 'Top Rated' link and viewing stats.php?action=highest

`(dba.class) -> Error_query MSG: ["42000",1055,"Expression #4 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.rating.object_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]`

Incidentally, the results are a mix of 5* rated and non rated songs and no album or artist results found?

**Comment by lachlan-00** [comment]
should be a browse of songs, artists, albums filtered by rating,

i don't get it with my server and grouping on so can you send me the query error as well?

**Comment by lachlan-00** [comment]
@rsinfotech i think it's the get_highest_sql query which is the only one i can find with 4 order bys

album is the only one with 4 order bys so i think it must be that one.
```
SELECT MIN(`rating`.`object_id`) as `id`, AVG(`rating`) AS `rating`, COUNT(`object_id`) AS `count`, MAX(`rating`.`id`) AS `order` 
FROM `rating` 
LEFT JOIN `album` on `rating`.`object_id` = `album`.`id` and `rating`.`object_type` = 'album' 
WHERE `object_type` = 'album' AND 
       (SELECT COUNT(`song_dis`.`id`) FROM `song` AS `song_dis` LEFT JOIN `catalog` AS `catalog_dis` ON `catalog_dis`.`id` = `song_dis`.`catalog` WHERE `song_dis`.`album`=`object_id` AND `catalog_dis`.`enabled` = '1' GROUP BY `song_dis`.`album`) > 0 
GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`mbid`, `album`.`year` 
ORDER BY `rating` DESC, `count` DESC, `order` DESC, `rating`.`object_id` DESC;
```

I can't break this page so if you can let me know asap i want to put out a bugfix release today

**Comment by rsinfotech** [comment]
Is this what you need @lachlan-00? I get this by putting the log level up to 5:

```(dba.class) -> Error_query SQL: SELECT MIN(`rating`.`object_id`) as `id`, AVG(`rating`) AS `rating`, COUNT(`object_id`) AS `count`, MAX(`rating`.`id`) AS `order` FROM `rating` LEFT JOIN `album` on `rating`.`object_id` = `album`.`id` and `rating`.`object_type` = 'album' WHERE `object_type` = 'album' GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`mbid`, `album`.`year` ORDER BY `rating` DESC, `count` DESC, `order` DESC, `rating`.`object_id` DESC LIMIT 0, 50```

**Comment by lachlan-00** [comment]
I still don't get it on mariadb with full group.

I'll try MySQL again and see what I can find

**Comment by rsinfotech** [comment]
Hi @lachlan-00 

I've noticed that another only_full_group_by error has started appearing in the logs but I'm not sure which commit introduced it?

Seems to be triggered when using the quick search box in the top bar.

Typing an artist name and selecting one of the results from the dropdown gives the following errors multiple times in the logs:
```
(dba.class) -> Error_query MSG: ["42000",1055,"Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.album.disk' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]

(dba.class) -> Error_query SQL: SELECT MIN(`album`.`id`) AS `id` FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5
```
The results returned seem to be correct, so not a major issue.

Hope it's ok to keep posting about these here? If you'd rather I'd open new issues, just let me know.

Thanks as always

**Comment by lachlan-00** [comment]
in here is okay, I finally worked out how to force my mariadb server to keep grouping on so i should find ones that break before they get into the repo.

i'll fix this today hopefully

**Comment by lachlan-00** [comment]
it's related to e03af811c but i couldn't force a break even with grouping on which is odd.

I'll update the search class when i get back from work, this will probably fix it but i haven't tested
![image](https://user-images.githubusercontent.com/1305249/103835729-c0a00980-50d2-11eb-9543-5e0d82fe19b4.png)

**Comment by rsinfotech** [comment]
Another thing I've just noticed with this error is that the drop down results from the quick search box in the top bar only shows Artist and Song matches, Album matches seem to have disappeared?

**Comment by lachlan-00** [comment]
i've put the fix in 694998f71, i don't know what the difference between oracle and mariadb is now because i'm not getting any errors with full grouping

can you run
```
SELECT @@sql_mode;
```

for me on mariadb it's
```
IGNORE_SPACE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

**Comment by rsinfotech** [comment]
Running SELECT @@sql_mode;
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
```
I'm still getting the same errors after commit 694998f71

**Comment by lachlan-00** [comment]
what's the query coming in as now?

**Comment by rsinfotech** [comment]
Errors in logs are:
```
(dba.class) -> Error_query MSG: ["42000",1055,"Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.album.disk' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]

(dba.class) -> Error_query SQL: SELECT MIN(`album`.`id`) AS `id`, MAX(`album`.`disk`) AS `disk` FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5
```

**Comment by lachlan-00** [comment]
This is a really odd one. Maybe it's because I name the column?

If you take out the

as `disk`

Part from that query does it work?

**Comment by rsinfotech** [comment]
Running this query in PHPMyAdmin returns the following: (I think I've removed the right bit?)
```
SELECT MIN(`album`.`id`) AS `id`, MAX(`album`.`disk`) FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5

#1055 - Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.album.disk' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by lachlan-00** [comment]
You did. I need to install MySQL again because this doesn't make sense when I'm running the same SQL mode

**Comment by usox** [comment]
What about...

```sql
 SELECT MIN(`album`.`id`) AS `id`, MAX(`album`.`disk`) FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year`,`album`.`disk` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5
```
?

**Comment by lachlan-00** [comment]
> What about...
> 
> ```sql
>  SELECT MIN(`album`.`id`) AS `id`, MAX(`album`.`disk`) FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year`,`album`.`disk` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5
> ```
> ?

It would probably work but I want to avoid grouping by disk to join albums into one id

**Comment by rsinfotech** [comment]
Ok, that query produces no errors and returns the following results:
```
 SELECT MIN(`album`.`id`) AS `id`, MAX(`album`.`disk`) FROM `album`  WHERE (`album`.`name` LIKE 'ac%'  OR LTRIM(CONCAT(COALESCE(`album`.`prefix`, ''), ' ', `album`.`name`)) LIKE 'ac%') GROUP BY `album`.`prefix`,`album`.`name`,`album`.`album_artist`,`album`.`mbid`,`album`.`year`,`album`.`disk` ORDER BY `album`.`name`, `album`.`disk`  LIMIT 5
```

id | MAX(`album`.`disk`)
-- | --
12867 | 1
12866 | 2
10960 | 1
9588 | 1
11341 | 1

**Comment by lachlan-00** [comment]
I think I know what I need to change. This doesn't take into account split disks like other areas. Will fix up when I get to a pc

**Comment by lachlan-00** [comment]
okay, 185d29fad splits this up correctly.

you only want disk sorting when you aren't grouping and i added the group by for ungrouped lists.

**Comment by rsinfotech** [comment]
Yep, more sterling work, this commit solves the problem, no errors in the logs and the dropdown quick search results are back to normal.

**Comment by rsinfotech** [comment]
Hi @lachlan-00 

Another only_full_group_by error has cropped up for me, I think since commit a3054310a7f49aa7f3d145cad269b62b9046011b?

It occurs when accessing the stats.php?action=recent page, Artists, Songs and Playlists all list correctly but the Albums section shows no results and the following errors are reported in the ampache log:

```
(Ampache\Module\System\Dba) -> Error_query SQL: SELECT MIN(`object_id`) as `id`, MAX(`date`) AS `date` FROM `object_count` LEFT JOIN `album` on `album`.`id` = `object_count`.`object_id` AND `object_count`.`object_type` = 'album' WHERE `object_type` = 'album' GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`release_status`, `album`.`mbid`, `album`.`year` ORDER BY MAX(`date`) DESC, `object_count`.`object_id`  LIMIT 0, 50
(Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1055,"Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.object_count.object_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
```

**Comment by lachlan-00** [comment]
put the id back in with 2d22102c1
