### ISSUE TITLE
Writing to ampache.cfg.php ?

### ISSUE THREAD

**Issue by PaulWalkerUK** [ampache/ampache#2448]
During the setup, one of the checks is whether it can write to `ampache.cfg.php`. Does it only need to do this during the initial setup, or does it need to be able to write to that file all the time (e.g. changing any settings through the UI)?

**Comment by kuzi-moto** [comment]
No, the only time it needs write access is during initial setup, or when there is a new version to the config file (which is pretty rare), but even in that case there is an option to download it, and save it manually.

**Comment by PaulWalkerUK** [comment]
That's great, thanks 👍
