### ISSUE TITLE
Addition for API clients list

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2454]
Hi,

The Wiki has a page on compatible client applications and I would like to add one to the list!

The SubMusic client app is available for download in the [Garmin Connect IQ app store](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794). The source code is open and published on [GitHub](https://github.com/memen45/SubMusic). The app allows you to browse your Ampache playlists and select the ones to be synced and played offline. It supports the Ampache JSON API, which will be present in version 4.2.0. Also the Subsonic API is supported, so it is compatible with older versions of Ampache as well.

Hope you can add it to the wiki!

Best regards,

**Comment by lachlan-00** [comment]
you should be able to add to the wiki yourself but i'll put it in now.

**Comment by lachlan-00** [comment]
our first json api app!
![image](https://user-images.githubusercontent.com/1305249/87733015-ce568f80-c811-11ea-94be-38e044daafcc.png)

**Comment by memen45** [comment]
Thanks a lot! Did not know it could be edited by anyone.
