### ISSUE TITLE
Inconsistency between "Recent played" in the web interface and the RSS feed

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#2455]
## Description

 The front page shows a "Recent played" list which contains the tracks recently played by the user and users who want to share their recently played information (setting 91 in preference table). If RSS is enable in the global configuration an RSS icon appears nearby.
 If the user doesn't want to share the recently played information, the RSS feed (which is not authenticated) doesn't contain the tracks from the user, even if the RSS link was retrieved from an icon heading the list of user played tracks. This is quite confusing for the user, who would expect the RSS feed to contain exactly the content of the recently played list.

### To reproduce

1. Have a ampache server configured with at least two users (i.e. user1, user2) 
2. Configure user1 not to "Share Recently Played information" while user2 does share.
3. Play some tracks with both users.
4. As user1, in the main ampache page will appear a list of recently played tracks which contains both the tracks played by user1 and user2. Close to the "Recently Played" list tittle an RSS icon appears with a RSS link.
5. Add the RSS to a RSS viewer
6. The RSS viewer shows the tracks only from user2, while the link was obtained while logged as user1.

### Expected behavior

 I am not sure what the expected behaviour should be. On one side I would expect the RSS feed to contain the list of tracks played by user1. But that's obviously in conflict with the user1 setting "Share Recently Played information" to false, since the RSS feed is not authenticated.

Possible options that I see:

1. For those users the RSS feed should be authenticated.
2. For the users create a feed which includes a random token in the URL specific to that user. That avoids having an authenticated but anyone who has the link can access the user information.
3. Do not show the RSS feed for those users.
4. Explain close to the icon that the feed contains only tracks from users who want to share their recently played tracks.
5. Do nothing and leave the users baffled :)
 
## Environment

* Ampache version: 4.1.1
* Web server + version: Apache 2.4.38
* Server operating system: Debian 10
* Client operating system: Any

### Client type

* Web
* Akregator RSS client

## Settings

 use_rss = "true"

**Comment by lachlan-00** [comment]
the index and rss both use Song::get_recently_played() without a user and that will grab everyone. So what you see in the RSS should match the ui.

But what i do see is that it looks like the web-ui will take into account permissions and will only allow site admins to view the info or people who match the current user.
```
$is_allowed        = Access::check('interface', '100') || Core::get_global('user')->id == $row_user->id;
```

Seems like the Ampache_RSS class doesn't do a lot of this at all. it also looks pretty malformed in the raw data so will need to work on this.

**Comment by lachlan-00** [comment]
so there look like two ways we can go.

Only allow public data in the rss feeds, including your own user (pref 91 = 1 in the above)
do the same for ui recently played and rely on using allow_personal_info_recent (on by default)

OR

generate links per user to fill in that empty user id (which is simple) but have them remain unauthenticated (rss.php?user=2&etc) due to the rss feeds in general being public lists similar to now_playing.php (now_playing.php?user_id=2)

I'm not sure which would be better, either would work pretty easily.

**Comment by mitchray** [comment]
Seems to have been addressed by that PR 👍
