### ISSUE TITLE
every second [ampache] (index) -> no session, calling session_start() 

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2456]
I recently switched from using nginx as my reverse proxy to HAproxy. Other than that I believe the only thing I changed was this:

`local_web_path = "http://localhost:80"`

I have tried with and without the above setting and the log gets hammered with that message regardless. I added the above setting because it makes dsub work while behind the haproxy.

The really weird part is that both the web player and dsub appear to work, so I am not even sure why the log is getting hammered with that. For now I am just going to try and turn debug off, but if anyone wants any more information let me know and I will be happy to provide it.

### Describe the bug

As you can see it just spams the log, it appears to be once per second.

```
2020-07-18T01:48:40+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:41+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:42+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:43+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:44+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:45+00:00 [ampache] (index) -> no session, calling session_start() 
2020-07-18T01:48:46+00:00 [ampache] (index) -> no session, calling session_start() 
```

### To reproduce

this is with:
```
debug = "true"
debug_level = "5"


cd /var/log/ampache/
ls
tail -f -n 100 /var/log/ampache/ampache.20200718.log
```

## Environment

* Ampache version: latest develop from github, updated pretty much daily :)
* Web server + version: nginx on the ampache container, and Haproxy is the reverse proxy that serves it to the ampache container.
* Server operating system: Ubuntu 20.04
* Client operating system: Ubuntu 20.04, Android 6.0, Windows 8.1

### Client type

* Web
* SubSonic Dsub

**Comment by xekon** [comment]
Instead of turning off debug I was able to just reduce the log level:

debug_level = "3"

that was enough to stop the log from getting hammered.

**Comment by lachlan-00** [comment]
it's a level 4 but i've taken it out.

I think this is people pulling the index file so you might be getting hit a lot.

do you have any ACL's set up? it might be able to give you access logs for the ip's instead
```
2020-07-21T12:36:08+10:00 [ampache] (access.class) -> check_network interface: ip matched ACL 192.168.1.9
```

**Comment by xekon** [comment]
OH I KNOW exactly what it is now that you say that. HAproxy has health check feature, that defaults to checking site health every second, and one of the things I just did was switch from using nginx to HAproxy.

Thank you!
