### ISSUE TITLE
Editing song data on Android doesn't retain changes.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2457]
This might be an artifact of Android.

I include the word 'retain'  because stepping through the code, I see the new data is being written to the db and can verify by examining the table with phpmyadmin.  But after continuing, the data reverts to the original, unless I cancel the dialog before continuing the debugger.

I tried with Opera with the same results.

Also the Android web browsers don't have  the debug console.

Could someone confirm or deny that this happens on a desktop browser?

Thanks...

**Comment by wagnered** [comment]
Same problem the album edit dialog.

**Comment by kuzi-moto** [comment]
Firefox for Android had the developer tools add-on, but it's quite hard to use. Firefox Nightly for Android allows remote debugging on PC if you had one.

**Comment by wagnered** [comment]
@kuzi-moto thaks for the info.  Are you implying that the problem does not exist on the desktop? 

Also, it would be nice if someone has a touch screen and would test the dialogs with that.

There is no problem selecting any of the non-JS buttons or drop-downs on the interface.

**Comment by wagnered** [comment]
This is a test  because I seemed to require pressing on the comment button twice for the comment to be inserted. I just enabled the touch sound to make sure it wasn't me.

**Comment by wagnered** [comment]
I noticed that if I set a breakpoint to examine the data, the changes are (usually) retained.

**Comment by wagnered** [comment]
Interesting...  I added some more code and the proble seemed to have disappeared.  Must have been some kind of race condition.
