### ISSUE TITLE
Overriding ampache.cfg.php ?

### ISSUE THREAD

**Issue by PaulWalkerUK** [ampache/ampache#2458]
## Describe what you don't like about Ampache, or what it is missing
I'm looking at running this in Docker, but having the `ampache.cfg.php` managed (and version controlled) outside of the container. To do this securely (and reusably), I need a way to keep things like the database connection parameters out of the file and only provide them at runtime.

## Describe how you would like the feature to work
Docker generally seems to recommend two ways for doing this:
1. Using environment variables. For example, as part of the `docker run` you could include `-e database_hostname='db_host' -e database_port='3306' -e database_user='ampache' -e database_password='monkey'` (or any combination, depending what the user wanted to have in/out of the file). I see this could work such that the file is used as-is, but if any environment variables have been set with the same name, then that takes priority (once the mechanism has been created, it could potentially be used to override _any_ setting in the file?)

2. Using docker secrets. Docker secrets allow you to store sensitive data securely in Docker on the host, then, at runtime, that data is passed into the container, appearing as a file. This could be implemented similar to how Linux programs often handle configuration files. In that world, it's not uncommon for there to be a main config file, but then something like a `conf.d` directory where you can put multiple config files that get applied in order - later settings taking priority. This would allow the main file to have everything, but then use Docker secrets to create one/multiple of these config files with the connection details.

Ideally, both could be implemented. I would see the order of precedence being: amache.cfg.php overridden by conf.d files overridden by environment variables

Since these could be considered more edge-case scenarios, the installer probably doesn't need to worry much about them - that could stick to the main config file.

**Comment by PaulWalkerUK** [comment]
I've found a way around this - happy to close this now

**Comment by AshotN** [comment]
Perhaps you can add a wiki page regarding what you did in case it helps others

**Comment by kuzi-moto** [comment]
Yeah, or even it could be included in the Docker image.

**Comment by PaulWalkerUK** [comment]
I just created my own Docker image and replaced the file with my own version during the build. Nothing fancy and not ideal, but it does what I need for now. There was one of two other things I wanted to experiment with that differ from the official Docker image as well - nothing useful enough/polished enough to publicise yet, but I will contribute/offer ideas if and when I have anything I think others might benefit from
