### ISSUE TITLE
ampache.log having date in the filename interferes with fail2ban

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2459]
ampache.log having date in the filename interferes with fail2ban

it would be better if the currently active log file were just named:

/var/log/ampache/ampache.log

then just use logrotate or something. The reason being is I wanted to setup fail2ban to monitor this log

https://github.com/ampache/ampache/issues/470

An alternative to removing the date from the currently active log could be to have:
`ampache-auth.log`
for auth related log info, but I would actually really prefer it if the active log were simply named ampache.log, this also makes it easier for me to `tail -f /var/log/ampache/ampache.log`

I have found the relevant file:
`/var/www/ampache/lib/log.lib.php`

change:
`        $log_filename = "%name.%Y%m%d.log";`
to
`        $log_filename = "ampache.log";`

and change:
`    $log_filename = str_replace("%d", date('d'), $log_filename);`
to:
```
    $log_filename = str_replace("%d", date('d'), $log_filename);
    $log_filename = "ampache.log";
```

**Comment by xekon** [comment]
after doing the above changes, here is my fail2ban config, I tested it and its working.

`nano /etc/fail2ban/filter.d/ampache.conf`
```
[Definition]
failregex = .* From <HOST> attempted to login and failed
ignoreregex =
```

`nano /etc/fail2ban/jail.local`
```
[DEFAULT]
maxretry = 1
bantime = -1

[ampache]
enabled = true
port = http,https
filter = ampache
logpath = /var/log/ampache/ampache.log
maxretry = 1
bantime = -1
action = iptables-allports
```

**Comment by lachlan-00** [comment]
i set my own log to just amapche-servername.log in the config file i don't really know what the reasoning behind it is.

the setting is just in the config
![image](https://user-images.githubusercontent.com/1305249/87999565-92d40200-cb3e-11ea-9256-3a93460c98b1.png)

i'm happy to change the default as that's what i always on on my servers but it is also just changeable in the config

**Comment by xekon** [comment]
Thanks! I did not realize I could change the format in the config, I will do that now incase the changes I made in that other file get overwritten.

**Comment by lachlan-00** [comment]
in that old issue the debug message has also changed from the original.

```
2020-07-21T10:44:35+10:00 [ampache] (login.class) -> ljljk From 192.168.1.9 attempted to login and failed
```

if you want to write an example file we can include it in the repo under docs/examples/apache-fail2ban-auth.conf

include any comments and i'll also put it in the wiki

**Comment by lachlan-00** [comment]
you've prompted me to update the wiki a bit more as well as direct to the config page from the installation guide

the basic configuration page needs an update as well so i'll work on that now.
https://github.com/ampache/ampache/wiki/Basic

**Comment by xekon** [comment]
sorry did not mean to ignore your nudge, I should have just told you that I was to busy to take on any projects. I do however love Ampache and will contribute more when time permits.

**Comment by lachlan-00** [comment]
time is something we all need. but just add to here when you feel like it. it's a nice to have
