### ISSUE TITLE
Smart playlist tag filter issue

### ISSUE THREAD

**Issue by mariof1** [ampache/ampache#2461]
Since the few latest development builds I can no longer properly filter tracks that include negate rules.
I used to have some smart playlist that would remove songs with tags I don't want and keep only those that contains specific tags.
For instance if a song contains multiple tags [Rock, Pop] and the filter is set like below
Tag contains Pop and Tag does not contain Rock, the song should not be listed but it is now.

![image](https://user-images.githubusercontent.com/32400371/88085101-4cea5e80-cb7d-11ea-8033-8700635957d3.png)

**Comment by lachlan-00** [comment]
i did change the logic to check individual tags so that must have broken the does not. i thought i'd checked all combos but obviously not

**Comment by lachlan-00** [comment]
I know what to change in the logic. Will be fixing in about 2 hours when I'm free

**Comment by lachlan-00** [comment]
fixed that logic but i want to make sure tags are also searchable from Any text as well so i'll work on that now

**Comment by lachlan-00** [comment]
okay @mariof1 there is a lot more tag ability in search now. the is and is not are also fixed

**Comment by mariof1** [comment]
Perfect, thanks @lachlan-00. I can confirm this works now as expected.

**Comment by lachlan-00** [comment]
Thank you for bringing this up. the tag search is wayyyy more powerful now
