### ISSUE TITLE
Web client top bar search function dropdown has stopped working 

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2464]
The latest commit 555f4de19 seems to have broken the nice little java dropdown of suggestions from working in the web client.

The search functions all still work as expected but no dropdown with thumbnails displayed as you type.

Reverting to commit 2a707dd4b gets it working again.

**Comment by lachlan-00** [comment]
i see that, will be from ajax.server. will fix now

**Comment by lachlan-00** [comment]
found it, a missing brace

**Comment by lachlan-00** [comment]
it's back :)
![image](https://user-images.githubusercontent.com/1305249/88357201-d1232880-cdad-11ea-9304-8b36ea9f9dc8.png)

**Comment by rsinfotech** [comment]
Superb! That's fixed it.

Thanks again for such a speedy response @lachlan-00
