### ISSUE TITLE
MP3's being reported as 'Unsupported Format' in web player

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2467]
This mornings commit 37b77e610 seems to have caused a problem with the web player.

Mp3's are no longer playing using the web player interface with the player reporting 'Unsupported Format' where the waveform is usually displayed.

The ampache log reports:

`(log.lib) -> [Runtime Error] Invalid argument supplied for foreach() in file /var/www/html/ampache/lib/class/webplayer.class.php(173)`

Reverting to yesterdays commit 32598d151 gets everything working again.

**Comment by lachlan-00** [comment]
that damn obvious code change that's broken. I know what to revert

**Comment by lachlan-00** [comment]
Got ITM that's the 3rd time I've done that while closing scrutinized issues. Really sorry

**Comment by rsinfotech** [comment]
Fabulous work, that's fixed it! :)

Commit 1c69c2e7d closes this issue.

No need to apologise @lachlan-00, I, and I would presume every other user here really do appreciate all of your hard work and absolute dedication to making ampache as great as it truly is, and each and every commit only serves to makes it better!
