### ISSUE TITLE
latest dev updates break web player.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2469]
my web player would no longer play, once I backed out to 1c69c2e7d it worked again. I backed out 1 commit at a time and did a hard reload on the page, it was not until 1c69c2e7d that the player worked again.

```
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 7c6f255a2 be a bit longer when repeating
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 91684c574 more issue updates
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 803c5b065 Update stream_playlist.class.php
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 1c69c2e7d Update show_web_player.inc.php
root@amp:/var/www/ampache#
```

**Comment by lachlan-00** [comment]
stream_playlist is really annoying me, again i keep breaking it following issues up, the code is not documented well enough while i keep updating things.

sorry for breaking it for so long i hate doing that!
