### ISSUE TITLE
Ampache cron failing to complete after latest commit

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2472]
Something seems to be preventing the cron process from completing fully in the latest commit.

After pulling the latest commit 0e77cb9a7, I noticed that the usual 'started cron process' messages in the ampache log were no longer completing and not reporting that the cron process had finished.

The log was only reporting the following:

`[ampache] (cron) -> started cron process`
`[ampache] (catalog.class) -> Database cleanup started`
`[ampache] (catalog.class) -> Database cleanup ended`

Instead of the usual:

`[ampache] (cron) -> started cron process`
`[ampache] (catalog.class) -> Database cleanup started` 
`[ampache] (catalog.class) -> Database cleanup ended` 
`[ampache] (compute_cache) -> started cache process` 
`[ampache] (compute_cache) -> Completed cache process` 
`[ampache] (cron) -> finished cron process`

Reverting back to commit ef3ac8324 gets the cron process completing fully again every 15 minutes.

**Comment by lachlan-00** [comment]
got it and reverted. no changes now only removals translations and bug fixes until 4.2.0
