### ISSUE TITLE
Bitly V3 API will be phased out by September 14, 2020

### ISSUE THREAD

**Issue by ibmibmibm** [ampache/ampache#2476]
### Describe the bug
Bitly V3 API is used in `modules/plugins/Bitly/Bitly.plugin.php` file, but it's going to be unusable at 2020/09/14.
https://support.bitly.com/hc/en-us/articles/360004395631-Migrating-from-v3-to-v4-of-the-Bitly-API
https://dev.bitly.com/v4_documentation.html

**Comment by lachlan-00** [comment]
thank you for informing me. at least we have a month but i'll get onto it right away so it can go out with 4.2.0
