### ISSUE TITLE
Random playlist generator with "unplayed by me" criterion results in empty list

### ISSUE THREAD

**Issue by MeFri** [ampache/ampache#2477]
### Describe the bug
Advanced playlist generation using only the "played by be" = false criterion results in an empty playlist.

### To reproduce

1. Go to ./random.php?action=advanced&type=song
2. Select "Played by me" and set it to false and desired item count
3. Get empty playlist

### Expected behavior
Generated playlist containing unplayed songs from library

## Environment
* Ampache version: develop

### Client type
* Web

**Comment by lachlan-00** [comment]
definitely not right, i get 1 when i know the answer is about 1000 times that

**Comment by lachlan-00** [comment]
FIXED!

i don't know why i did that one this way but just did the joins/where the same way as album/artist
