### ISSUE TITLE
[Feature Request] list of Android players that work

### ISSUE THREAD

**Issue by AndKe** [ampache/ampache#2479]
Subsonic player: works, dead slow with bigger playlists.
Audinaut, Music stash, and Ultrasonic: unable to log in.

**Comment by kuzi-moto** [comment]
I think all Subsonic clients should work. Are you using the API key as a password?

**Comment by AndKe** [comment]
No, I am just using username+password.
Also, another thing I miss/discovered, is that most does not handle the number of starts/rating system that Ampache is using.

**Comment by lachlan-00** [comment]
all subsonic clients work. subsonic has about 3 different auth methods depending on what they support so use user+pass or user+apikey if that fails.

You'll find 4.2.0 faster with smart lists after a few changes there too.

**Comment by SimonHova** [comment]
You never listed DSub, I've used it without complaint.

**Comment by kuzi-moto** [comment]
The list of [API Clients](https://github.com/ampache/ampache/wiki/client-api) contains all (known) native clients. No need to list out Subsonic clients, as any of them will work.

**Comment by lachlan-00** [comment]
> You never listed DSub, I've used it without complaint.

For me DSub has been probably the best Ampache client for the last 5 years. That's why i've put so much effort into raising the quality of Ampache's API.

**Comment by AndKe** [comment]
The reason I did not try Dsub right away was: 
![Screenshot_20200808-225008_Google Play Store](https://user-images.githubusercontent.com/1468842/89719666-fd07f600-d9ca-11ea-83f3-b2c0009818b1.jpg)

Yes, it works.

@kuzi-moto As for "Power Ampache" in the list, please check the link, it points to a webpage with a different apk (it seems to me)

**Comment by wagnered** [comment]
@AndKe 

F-Droid is based in the UK and   according to them:

>  F-Droid is a robot with a passion for Free and Open Source (FOSS) software on the Android platform.

They are more open about proprietory add ons, they don't track your downloads, as the play store does.  The docs contain a list of anti-features that is checked against when an app applies to be added which Google doesn't do.

F-Droid isn't well known and I stumbled on it awhile back searching for a Linux distro  I couldn't find in the play store.

**Comment by AndKe** [comment]
thanks. :)
