### ISSUE TITLE
Update is done, but he message doesn't go away

### ISSUE THREAD

**Issue by JeromeX** [ampache/ampache#2480]
It says, Update available, Update done, but the message doesn't go away itself.

![grafik](https://user-images.githubusercontent.com/15369779/89207423-fb00fa00-d5ba-11ea-8dcf-a2042f5ee160.png)
![grafik](https://user-images.githubusercontent.com/15369779/89207704-76fb4200-d5bb-11ea-8bb6-24aeef86253a.png)

**Comment by JeromeX** [comment]
In Debug-Tab, it says: Update available, but nothing is really updated
![grafik](https://user-images.githubusercontent.com/15369779/89207909-c93c6300-d5bb-11ea-8646-14a0559a8519.png)

**Comment by lachlan-00** [comment]
that means you have a file conflict somewhere. The web ui can only do a pull when there are no modifications in the folder.

in the cli if you run git pull it will tell you the files,

you can also do a reset as well.
``` git reset lib ``` will reset the whole folder

so while testing the last commit i put it on my server and while it's an error the UI isn't actually aware of these
![image](https://user-images.githubusercontent.com/1305249/89234840-40abda00-d630-11ea-977a-147aab1c8d31.png)

**Comment by lachlan-00** [comment]
sorry, checkout instead of reset
git checkout lib

**Comment by AshotN** [comment]
Would it be reasonable to add a message explaining what's going wrong. Perhaps we can make an FAQ regarding common failure points.

**Comment by lachlan-00** [comment]
we do have the wiki
https://github.com/ampache/ampache/wiki/Troubleshooting
https://github.com/ampache/ampache/wiki/FAQ

But it is something that i only know the answer for because i've experienced this for years. 

You raise a good point though so i think we should probably do a redirection or an error when the change doesn't correct itself
