### ISSUE TITLE
API key can only be reset by administrator but the icon to reset appears in the user settings

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#2484]
## Description
 
 According to the API documentation (https://github.com/ampache/ampache/wiki/Ampache-API) only the administrator can generate (or reset) the API key. However, when a normal user is logged in and goes to the Account preferences, a reset icon appears near to the API Key label (see screenshot). However clicking on it leads to an empty page, presumably because the user doesn't have the permission to do it.

### To reproduce

1. As a normal user go to Preferences - > Account.
2. Click on the icon right to "API Key" which is labeled as "Generate a new API key"
3. An empty page is shown.

### Expected behavior
 
 I see two possible solutions:
 1. The "Generate a new API key" is not shown when the user is logged in.
 2. The user is allowed to change the API key. I am not sure why this is not allowed. A user is actually allowed to change the password, so why not the API key? Which is the rationale behind?

### Screenshots

![api_key_reset](https://user-images.githubusercontent.com/17937361/89518190-da16ef80-d7da-11ea-8138-ff1dd8909e5f.png)

## Environment

* Ampache version: 4.1.2
* Web server + version: apache
* Server operating system: Raspbian
* Client operating system: Firefox on Debian 10

**Comment by lachlan-00** [comment]
I saw that today. (Too late for changes on 4.2.0)

What I think we should do is make it a permission so it only shows up if you assign permission to that level.

Ie allow content managers to reset API key and then only show to users content manager+ and admins

**Comment by cquike** [comment]
I see that  in the latest version 5.6.0 this is not an issue anymore, so I will close the it.
