### ISSUE TITLE
Clicking on the QR code of the API key shows a worrying browser message

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#2485]
## Description
 The QR code shown in the Preferences -> Account tab can be clicked from Firefox but it shows a pop up window warning about login in with a the API key to a website that doesn't need auth. On top of that is says "This may be an attempt to trick you". Which sounds scary... 

### To reproduce

1. Log in as normal user.
2. Go to Preferences -> Account
3. Click on the QR code of the API key.
### Screenshots

![api_key_qr](https://user-images.githubusercontent.com/17937361/89519432-a6d56000-d7dc-11ea-892b-5c68e6a019c6.png)

## Environment

* Ampache version: 4.1.1
* Web server + version: apache
* Server operating system: Raspbian
* Client operating system: Firefox 68.9.0esr on Debian 10

**Comment by lachlan-00** [comment]
There is some background to that link, but why/how the QR code generates that way I'm not sure.

I think it's one of those things that's been around for a while but isn't something that's fully understood or documented (by me at least)

**Comment by lachlan-00** [comment]
I've reset the QR code to just be a string of your api key
