### ISSUE TITLE
Smart playlist improvements

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2491]
## Description
I had created a smart playlist that played unrated tracks. I hacked it together by selecting tracks that weren't rated five stars, OR four stars, OR three stars, etc. However, I see that it's not working any more.

### To reproduce

1. Create smart playlist
2. Match: all rules
3. Create 5 Rules: all should match My Rating and does not equal and the criteria is 5, 4, 3, 2 and 1.
4. Create another three rules, matching My Rating (Artist) and criteria is 1, 2, 3.

### Expected behavior

Should list 15 tracks (limit set in playlist type), instead pulls 0 tracks.

### Screenshots

![image](https://user-images.githubusercontent.com/879342/89723876-0e043780-d9ca-11ea-917f-a95ab98a8e2a.png)

**Comment by lachlan-00** [comment]
The issue i see with the rules is that you're looking for unrated music? (eg myrating is not 1/2/3/4/5)

First thing i'll do is add 0 (Unrated) to search lists.
![image](https://user-images.githubusercontent.com/1305249/89725249-d7253480-da50-11ea-8700-32179bc9c512.png)

But i do see that the way this is build should still return something. so i'll work on how that query builds as well to make sure this works without 0

**Comment by lachlan-00** [comment]
Oh and the workaround for this is to use the rule

My Rating -> is less than -> 1

**Comment by SimonHova** [comment]
Changing it to 0 now works for the songs, but it doesn't work for the artists or the albums. Neither does setting them to less than 1. So, I cannot search for artists or albums that are unrated. Screenshot below shows the criteria I'm trying to set.
![image](https://user-images.githubusercontent.com/879342/89916433-93077080-dbc5-11ea-84bf-29d3a84ef4e3.png)

Also, if I have your ear, can you change the language of the dropbox from 0 to **unrated**? That would be more user friendly.

Finally, I can now set the length of a smart playlist by number of items, can we add or change it duration? This was a favorite feature of mine from MediaMonkey, it allows me to have an hour's worth of music for example, or create nested smart playlists (which I'm playing with now; it's awesome!) that can play more higher rated music and less lower rated.
![image](https://user-images.githubusercontent.com/879342/89916735-f98c8e80-dbc5-11ea-961c-1335577ffb71.png)

**Comment by lachlan-00** [comment]
i see that too, those queries need some work so i'll fix them up.

i had to change the numeric searches to only numbers due to the way the items are generated but i'll see whether i can work out a way to resotre 1 star, 2star etc

**Comment by lachlan-00** [comment]
combined alrating, albumrating and artistrating to avoid issues where they're not doing the right thing

**Comment by lachlan-00** [comment]
i found an easy way to get 1 star, etc back into numeric ratings. as long as i do it in order it matches the number so that's okay now too
![image](https://user-images.githubusercontent.com/1305249/89957841-d0c6d080-dc7b-11ea-80b7-229187124910.png)

**Comment by lachlan-00** [comment]
length of time is something i need to add in and want the same thing just haven't gotten to it yet.

I limit to 50 for my smart lists to achieve this but its obviously not as good as saying "1 hour"

**Comment by SimonHova** [comment]
> i found an easy way to get 1 star, etc back into numeric ratings. as long as i do it in order it matches the number so that's okay now too
> ![image](https://user-images.githubusercontent.com/1305249/89957841-d0c6d080-dc7b-11ea-80b7-229187124910.png)

Then my suggestion, and forgive me if it's not possible in PHP, is to make the code look like:
```<select id="rule_2_input" name="rule_2_input">
  <option value="0">Unrated</option>
  <option value="1">1 Star</option>
  <option value="2">2 Stars</option>
  <option value="3">3 Stars</option>
  <option value="4">4 Stars</option>
  <option value="5">5 Stars</option>
</select>

This will make it easier to see what a 0 star rating means.

**Comment by SimonHova** [comment]
Going through all my old tickets, this was closed forever ago. I will add an issue to make a new length option for smart playlists which was a suggestion made in this issue.
