### ISSUE TITLE
Album Art from tags?

### ISSUE THREAD

**Issue by PaulWalkerUK** [ampache/ampache#2492]
Ampache doesn't seem to be recognising any of the embedded album art from the tags. Are there any obvious things that could be preventing this? I haven't changed any settings in the config file, they're just default. From the log file, I can see it refers to getting the art from the tags, but there's no messages to indicate a problem.

Any thoughts? (I haven't updated to 4.2 yet, still on 4.1 at the moment)

**Comment by wagnered** [comment]
Does the `art_order` switch in the config file contain the `tags` option?

The images will be imported, but they are, if I remember correctly, assumed to be album art.

I am working on improving the importing and writing of images to id3v2.3 tags. 

Ampache will be able to import and write, one each, cover and artist, image to id3 tags.

**Comment by PaulWalkerUK** [comment]
My config file has:

```
art_order = "db,tags,folder,musicbrainz,lastfm,google"
```

I've found that when I click on that "Edit/Find Art" button, the images that are displayed _do_ include those from the tags, so it is able to read them. If I click "Select" on one of them, in the log I see: 

```2020-08-09 20:16:58 [admin] (art.class) -> Not inserting image for album 2519, invalid data passed```

The same happens if I pick an image from one of the other sources, e.g. LastFM, so it's not so much an issue with images from tags, just images in general

**Comment by PaulWalkerUK** [comment]
Ah, I think I've found my issue... Looks like I was missing the PHP GD module, so it was dropping through the [`test_image`](https://github.com/ampache/ampache/blob/d0e4f9332267af766f5e14288cfd68250368ef20/lib/class/art.class.php#L211) function, returning `false` every time.

Thanks for your help @wagnered 👍
