### ISSUE TITLE
Smart playlists don't update

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#2495]
Hello!
As tittle says smart playlists don't update after the update to 4.2.0.
New albums are only shown to /#browse.php?action=album and /#stats.php?action=newest
When searching by catalog to /#random.php?action=advanced&type=song new tracks are not shown nor the smart playlists(/#smartplaylist.php?action=show_playlist&playlist_id=XX) that looks into the catalog is updated.

* Ampache version: 4.2.0

**Comment by PsyZeus** [comment]
FWIW i'm that guy with the numeric catalog names again! :D 
https://github.com/ampache/ampache/issues/2437

**Comment by lachlan-00** [comment]
so catalog is "something" searches?

**Comment by PsyZeus** [comment]
hi @lachlan-00 

when catalog is "something" advanced search & smart playlists works great
when catalog is "1234  something" advanced search and smart playlist is stucked to last count from the fix for 4.1.1
when catalog is "1234" search and smart playlist returns 0 results 

hope that helps a bit.

**Comment by lachlan-00** [comment]
oh so your catalog "123 catalog" is screwing up again?

I think i'm with you now.

**Comment by lachlan-00** [comment]
can you post some picture of the rules in each search and i'll recreate them?

**Comment by PsyZeus** [comment]
Sure buddy!
Thing is that you made everything to work on the fix for 4.1.1...even the catalogs with only numeric characters like the 2016 below.
And yes i saw on your last post that the fix broke the numeric searches and i think i get why that happened but why does this happen on "123 catalog"

![1](https://user-images.githubusercontent.com/26334546/90176735-184f7880-ddb2-11ea-89e5-2743949dcf8c.PNG)
![2](https://user-images.githubusercontent.com/26334546/90176741-1b4a6900-ddb2-11ea-96f3-c781a7a6f907.PNG)
![3](https://user-images.githubusercontent.com/26334546/90176745-1d142c80-ddb2-11ea-9fd8-2cc3c67cf173.PNG)

**Comment by lachlan-00** [comment]
does your server have the catalog id's coming in correctly?
![image](https://user-images.githubusercontent.com/1305249/90200508-65b40000-de1b-11ea-8e42-a2aa75c9a1e5.png)

my list gets the id's correctly for all catalogs
![image](https://user-images.githubusercontent.com/1305249/90200560-97c56200-de1b-11ea-9c22-11cc9a4e8aa4.png)

**Comment by PsyZeus** [comment]
Yes..everything looks like as they should be except the numeric folders that i got 
<option value="2020">2020</option>

I noticed that if i create a new catalog everything works. That's why your recreation worked!
e.g i created a folder "2021 aaa" put some files in, created a smart list, added/removed files from folder, updated the folder and boom..the advanced search worked fine and smart list updated itself as it should do.

**Comment by PsyZeus** [comment]
Yes..everything looks like as they should be except the numeric folders that i got

option value="2020">2020</option

I noticed that if i create a new catalog everything works. That's why your recreation worked!
e.g i created a folder "2021 aaa" put some files in, created a smart list, added/removed files from folder, updated the folder and boom..the advanced search worked fine and smart list updated itself every time as it should do.

**Comment by lachlan-00** [comment]
ohhh, i think it might have saved the smart list as 2021 in the database? so creating a new list with new rules will fix it too

**Comment by PsyZeus** [comment]
Well, not sure what the problem was because all the id's was correct and still are the same but everything is back wonderfully after i updated to 4.2.1 and deleting all smart playlists and make them again!!

Actually almost everything is perfect since the numeric folders are still not searchable because they break other numeric searches as you mentioned, but i hope you can find a fix in the future!
e.g. "option value="2020">2020</option" should be "option value="catalog_id">2020</option" for the catalog to work.

Anyway i was wondering(since it's obvious that i don't know what i'm talking about!! lol) if somehow it's easy and possible, to tell me if i can change a line pr 2(really no more,since i don't know what i'm doing) to make the search work for numeric folders like you did for 4.1.1 fix?!

Your work(and everyone's from the past) is awesome anyway dude :D and many many thanks for all the help.
Ampache is facking awesome for us music lovers!!!

**Comment by lachlan-00** [comment]
I actually think its fixed but we have to work out why yours aren't up to scratch. I'll comment here during the week about fixing it up but I think I'll have to chat with you

**Comment by PsyZeus** [comment]
FWIW the non searchable numeric folders are the "2020" style folders and not the "2020 something"
I know i sound like an idiot but i want to be sure we are on the same boat :D 
Well either way, a new fix is some really awesome news for everyone!!
Also thank you sooo much for helping me to sort that out.
Sure dude just tell me where

**Comment by PsyZeus** [comment]
Ohhh... i'm so sorry i mislead you on that one..truth is, since i didn't read something about it on 4.2.1 release notes i thought i would have the same outcome but i just took a look at it from curiosity because you said you thought it was fixed and voila!! 4.2.1 reports the correct id of the folder here
"option value="26">2016</option"
but nonetheless search still doesn't work.

**Comment by lachlan-00** [comment]
in lib/class search uncomment the debug_event lines and it will give me some SQL to work with.

there are 3 in there but they all start like this
```
debug_event('search.sql'
```

**Comment by PsyZeus** [comment]
hi @lachlan-00 
i found all of them and uncomment them but i don't get anything about sql in the log :/

**Comment by lachlan-00** [comment]
I just finished up a big update on search, update and let me know.

adding 0 to ratings had added an extra issue to the checks and there were a heap of joins that overrode rules when you started to get deep.

**Comment by PsyZeus** [comment]
Hello @lachlan-00 !!
Don't know if that helps but you never know.
I was playing around with it today and i found out that when i create a smart playlist not through ampache but through webmin by simply creating a new line on table "search" numeric folders works fine as smart playlist.
Yes "/random.php?action=advanced&type=song" still doens't work for numeric catalogs but since smart playlist works fine i can shuffle it and be done with it lol

Some more info in case you want to recreate
create a folder "2021" to disk
add the folder "2021" to ampache
get the folder id e.g "catalog_id=111"
create a new line to table "search" and add the rule "[["catalog","equal","111",null]]"
add some music to "2021" folder
add the new music to DB from "/#admin/catalog.php?action=show_catalogs"
check smart playlist
add some more music
check again the smart playlist
it works...

If you create the smart playlist through ampache, for some reason results turns to "0" when pressing the save button.

**Comment by lachlan-00** [comment]
That gives me more to work on. I'm going to be bugfixing for 4.2.2 this week so I'll see what I can fix for this too

**Comment by lachlan-00** [comment]
oh i see that the full numeric names still get caught

**Comment by lachlan-00** [comment]
got it
![image](https://user-images.githubusercontent.com/1305249/91672649-03753200-eb73-11ea-8068-f6f319f6379c.png)

**Comment by PsyZeus** [comment]
You are awesome dude!
Lets hope that the fix wont brake something :D

**Comment by lachlan-00** [comment]
I tested against bitrate, stars and other numeric types. I think it's okay this time
