### ISSUE TITLE
Commit dfed241 crashes web interface

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2499]
### Describe the bug
After updating to the latest version in the dev channel, I now see an error on my installation.

`Fatal error: Uncaught Error: Class 'IntlDateFormatter' not found in /opt/ampache/lib/general.lib.php:531 Stack trace: #0 /opt/ampache/lib/class/user.class.php(1129): get_datetime(1597240816) #1 /opt/ampache/lib/init.php(237): User->format(false) #2 /opt/ampache/index.php(23): require_once('/opt/ampache/li...') #3 {main} thrown in /opt/ampache/lib/general.lib.php on line 531`

Looks like it's related to the datetime update that was updated in ca9122d. I thought it was a dependency issue, but composer hasn't changed.

## Environment
* Ampache version: latest dev
* Web server + version: nginx
* Server operating system: Debian 10
* Client operating system: Win10

**Comment by SimonHova** [comment]
Fixed it. It was a dependency problem affecting me on Debian. The answer on [SO](https://stackoverflow.com/a/50673001/514085) helped. Does composer need to be updated?

**Comment by lachlan-00** [comment]
you're right, i don't see intl included in the readme so i need to add that

**Comment by lachlan-00** [comment]
added to composer requirements, and put it right at the top on the changelog and readme in c3ab0b2b5

Thanks for pointing this one out i run off such an old setup that i tend to miss these things.

**Comment by wagnered** [comment]
Too fast! I wanted to suggest that 
> "ext-json": "*",
 "ext-xml": "*",

be moved up to the platform array.  That way they will be displayed when `composer show  --platform` is executed.

**Comment by wagnered** [comment]
Nevermind.  They already were in theplatform array. Though they remain in the required section

**Comment by lachlan-00** [comment]
ide's don't seem to read the platform part so they've been added in for things like phpstorm who treat it as a composer error.
