### ISSUE TITLE
Ampache Develop now requires php-intl module/dll to be enabled

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2501]
## Description
Latest updates caused my ampache to come up as a blank white page.

### Describe the bug
I am on develop branch, I always grab the latest updates when they appear on the home page. There was an update within the last couple days that listed a lot of things, I woke up this morning and ampache loaded to blank white page. I was able to resolve it by rolling it back

```
root@amp:~# cd /var/www/ampache
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 31eb6a7bf Update search.class.php
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at c5b7d5c6f **IMPORTANT** you need to reset your custom_datetime
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at c6da01ae4 Recently played RSS feeds fixed for users who don't share played info (#2486)
root@amp:/var/www/ampache#
```

at this point  (c6da01ae4) I was able to load the page, and there was a database update available which I did, everything seems to work, I will wait a few days before trying to update  again.

**Comment by lachlan-00** [comment]
Sounds like you're missing php-intl.

it's in develop now to allow translation automatically based on the server locale. I'll pin this issue with info from the readme.

**IMPORTANT** instead of using date() we are now using IntlDateFormatter and your locale to identify formats.

* This means that 'custom_datetime' based on the date() format is incorrect and will look weird.
  * Look here for the code to change your 'custom_datetime' string [(http://userguide.icu-project.org/formatparse/datetime)]
* This also means that Ampache now requires php-intl module/dll to be enabled.

**Comment by PaulWalkerUK** [comment]
I appreciate it was probably unintentional, but I would argue that adding a new dependency is a "breaking change" and should therefore be done as a major version release (v 5) release. 

Now it _has_ been introduced, I believe the Semantic Versioning way to deal with this would be to revert the change (thus restoring the original dependencies) and make a new (v4) release - see 
[What do I do if I accidentally release a backwards incompatible change as a minor version?](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version)

**Comment by lachlan-00** [comment]
4.2.1-release is the current version and doesn't have the intl requirements.

I can always revert develop but 4.3.0 and the develop repo is more of a generic ampache-+1 value and doesn't get an actual release version until much closer to release time.

I intend to bugfix master parallel with develop as there are a lot of removals and changes pegged to happen.

This will leave the 4.2.x release tree for at least the rest of the year. Develop is most likely to release as 5 but it's going to probably take me 6 months to even get close.

**Comment by noyse27** [comment]
unfortunately it seems that this makes ampache never work at this point  on synology anymore because i cannot found any possibility to get this extension enabled on their php 7 :(

**Comment by lachlan-00** [comment]
> unfortunately it seems that this makes ampache never work at this point on synology anymore because i cannot found any possibility to get this extension enabled on their php 7 :(

It's a base module so I don't see why it would be excluded from Synologys releases? But it's not the end of the world to go back.

We could even be lazy and cast each locale manually. It's just that intl is used for localisation which is not something we should hack manually if possible.

**Comment by noyse27** [comment]
> It's a base module so I don't see why it would be excluded from Synologys releases? But it's not the end of the world to go > > back.
ooops
looked at the wrong place. found it.set it. worked :)

**Comment by lachlan-00** [comment]
Ha, I'm glad it was an easy find.

I've seen intl not enabled a lot for things especially on windows where locales are not really used to the same degree as linux but the DLLs are there.

**Comment by PaulWalkerUK** [comment]
> 4.2.1-release is the current version and doesn't have the intl requirements.
> 
> I can always revert develop but 4.3.0 and the develop repo is more of a generic ampache-+1 value and doesn't get an actual release version until much closer to release time.
> 
> I intend to bugfix master parallel with develop as there are a lot of removals and changes pegged to happen.
> 
> This will leave the 4.2.x release tree for at least the rest of the year. Develop is most likely to release as 5 but it's going to probably take me 6 months to even get close.

Ahh OK, apologies, perhaps I misunderstood. It was the comment on the [4.2.1 release page](https://github.com/ampache/ampache/releases/tag/4.2.1) that suggested there's a new dependency being added for 4.3. Following SemVer, I was thinking a new dependency would be a major release (i.e. 5). I don't see any reason to revert it from the `develop` branch - version numbers only really come into play with an actual "release" 🙂

**Comment by noyse27** [comment]
BTW:
After updating to th eINTL Thing it seems that the date display is goin' crazy ;)
the format that i had to used earlier wont work and if i letit empty it wont work either:
![2020_08_14_14 34 25_polze_j_](https://user-images.githubusercontent.com/25564572/90249779-59d83600-de3b-11ea-81af-4b177942965e.png)
![2020_08_14_14 34 59_polze_j_](https://user-images.githubusercontent.com/25564572/90249782-5ba1f980-de3b-11ea-995c-7ad36176f089.png)

**Comment by lachlan-00** [comment]
What I like about having discussions like this is it raises questions about why I do things the way we do.

TBH the versioning in develop might not be relevant and can be confusing or even detrimental. You have to use git to update so it should actually not matter what the string is.

We should probably be just moving develop versioning from X.x.x-develop to 'develop'

That way we can just have a straight semantic release for master and develop stays as is.

**Comment by lachlan-00** [comment]
> BTW:
> After updating to th eINTL Thing it seems that the date display is goin' crazy ;)
> the format that i had to used earlier wont work and if i letit empty it wont work either:
> ![2020_08_14_14 34 25_polze_j_](https://user-images.githubusercontent.com/25564572/90249779-59d83600-de3b-11ea-81af-4b177942965e.png)
> ![2020_08_14_14 34 59_polze_j_](https://user-images.githubusercontent.com/25564572/90249782-5ba1f980-de3b-11ea-995c-7ad36176f089.png)

@noyse27 the intl module uses different codes
http://userguide.icu-project.org/formatparse/datetime

**Comment by noyse27** [comment]
ok now its working too :)

**Comment by xekon** [comment]
> Sounds like you're missing php-intl.
> 

installing php-intl fixed it, thank you.

**Comment by rsinfotech** [comment]
As php-intl is a base module, could it be added to the install checks and then be reported on in the 'Ampache Debug' admin page along with Zlib, GD, Iconv etc. under PHP Settings?

![image](https://user-images.githubusercontent.com/3216809/90275623-7f286c80-de5a-11ea-8a8b-5dd353998341.png)

Look at those beautiful custom dates it enables!

**Comment by wagnered** [comment]
With the extension listed in composer.json,  when composer is run on initial install, it will advise the administrator that the extension is required.

I think the test page was added before the ability to check for PHP extensions was added to composer: I also think that the test page is no longer necessary.

We appreciate that all of you, who run the develop branch, give us considerable help,  but running a non-release version is not "typical". I want to remind all of you that you@lachlan-00 includes any significant changes in docs/CHANGELOG.md at the time of the commit and  It is your responsibility to read that document when installing  any new commit.

Again, we do appreciate all the help you give us.

**Comment by PaulWalkerUK** [comment]
Fully agree @wagnered - I intend to only be using "proper" releases for my PRD environment 🙂

**Comment by lachlan-00** [comment]
The intl module is in test.php but I think I'll add the test into init so it will redirect to test.php when missing.

That will make it clear to the user a module is missing and not show up as a blank screen

**Comment by lachlan-00** [comment]
Okay, no more random +1 version strings.

The develop branch is now "Ampache develop" / develop.

The redirect to test.php should help for people who upgrade over the top and don't catch the requirement change.

I always like to redirect errors instead of a blank screen where possible so this should cover pretty much everyone upgrading from master/develop without intl enabled.

**Comment by SimonHova** [comment]
I hate to hijack a discussion thread, but can I make a suggestion regarding the develop branch and how it's displayed? Currently, the footer simply displays **Ampache develop**, but I have no idea what commit I'm on when I'm on the develop build. Can you append the Github commit version to the footer for installations running develop?

I ask because I must be on a slightly older (by two hours) commit, but I cannot find an easy way to verify what commit I'm on from the web interface, and I'm unsure if a newer commit will solve my issue.

**Comment by wagnered** [comment]
On the admin tab, select "Ampache Debug" and you will see the installed version,  the latest version and a possible update available,

**Comment by SimonHova** [comment]
Thank you for that; I was able to force an update and gave me a better idea of the version number that I'm on; though it hasn't solved my issue, I now have better information to give in my issue.

**Comment by lachlan-00** [comment]
Closing this as intl is a requirement and 5.0.0 is slated for September. No need to keep open
