### ISSUE TITLE
Search Artist only returns one result when it should return many

### ISSUE THREAD

**Issue by drder66** [ampache/ampache#2503]
Search for an artist where you know there are many tracks in the database
Only one result is returned. 
This is because the search SQL includes a GROUP BY artist.id. e.g. for artist 'hurford' the search is:

2020-08-14 22:13:16 (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` WHERE (`artist`.`name` LIKE '%hurford%'  OR LTRIM(CONCAT(COALESCE(`artist`.`prefix`, ''), ' ', `artist`.`name`)) LIKE '%hurford%') GROUP BY `artist`.`id`

If I remove the GROUP BY term in Search::Run, then I get the expected result, a list of all tracks associated with artist 'hurford'. This is because GROUP does an association on the DB search and compresses everything into one row returned. 

However GROUP BY is obviously there for a reason. Can I ask what for?

Reason for asking: I'm working to fill in the missing upnp search function and calling Search::Run is not providing the expected results. I'm not wanting to touch the Search function, noting the warning "Search-related voodoo.  Beware tentacles"

**Comment by lachlan-00** [comment]
I see a bug in album search for album->artist from my phone but song->artist and artist->name search return everything I expect.

Group by artist id joins the text search to an object.

Eg
ID = "prefix", "name"
Artist 1 = "", "big dog"
Artist 2 = "the", "big dog"

The grouping is there for MySQL full_group_by which isn't on by default in mariaDB but requires the queries to group and order all columns used in a select.

It would be good to dig into this a bit more as I can't see why you don't get the right results.

Can you post a ```select * from artist where name like '%hurford%'```

**Comment by PaulWalkerUK** [comment]
Looking at that SQL, I'm inclined to agree with @drder66 - I think the `GROUP BY` is wrong here. For what it's worth, I've tried the query on my MariaDB 10 database and I got the same results - taking off the `GROUP BY` worked as expected (there's no aggregation going on here so no grouping required).

Incidentally, the `DISTINCT` clause isn't needed either - `song.id` is a primary key (so guaranteed to be unique) - and the join to the `artist` table is joining on _its_ primary key (a song can only have one artist), so again will only be returning 0 or 1 rows, therefore `song.id` will be unique in the final result set.

The logic in the first part of the `WHERE` clause is also duplicated in the second part (the second part builds up `prefix` and `name`, then trims off the leading space in case `prefix` was `null` which leaves just the `name` - same as was checked in the first part)

I believe this statement will work fine:

```sql
SELECT song.id
FROM   song 
LEFT JOIN artist 
ON     song.artist=artist.id 
WHERE  LTRIM(CONCAT(COALESCE(artist.prefix, ''), ' ', artist.name)) LIKE '%hurford%';
```

**Comment by lachlan-00** [comment]
That actually is the current query i get in develop?
```
SELECT DISTINCT(`song`.`id`)
FROM `song`
LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` 
WHERE (`artist`.`name` LIKE '%big%'  OR LTRIM(CONCAT(COALESCE(`artist`.`prefix`, ''), ' ', `artist`.`name`)) LIKE '%big%')
```

**Comment by drder66** [comment]
Ok, so evidently there are significant changes in the behaviour of search between 4.1.1. and 4.2.1 
I now get multiple matches for my 'hurford' search (I still have much to do though)
I should have checked out ToT before raising this. Apologies.

**Comment by lachlan-00** [comment]
I'm glad it's fixed. I made the search class simpler and fixed a lot of little issues but I feel like it's going to need a lot more love.
