### ISSUE TITLE
Subsonic wrong song stream URL

### ISSUE THREAD

**Issue by mihapiha** [ampache/ampache#2508]
## Description
Subsonic client cannot play any music.

### Describe the bug
In logs we can see that there is malformed url for accessing song

```
2020-08-15T21:01:14+00:00 [miha] (subsonic_api.class) -> Stream proxy: https://myhost.com/play/ssid/93d4e79a2a05b33caabac1c92f0f62d6/type/song/oid/654/uid/1/client/substreamer/content_length/required/player/api/name/awesomesong.mp3
```

I "fixed" my issue with "disabling" the function call in stream_url.class.php line 122

```
/**
     * format
     * This format the string url according to settings.
     * @param string $url
     * @return string
     */
    public static function format($url)
    {
        return $url; //my "fix"
        if (AmpConfig::get('stream_beautiful_url')) {
            $url = str_replace('index.php?&', '', $url);
            $url = str_replace('index.php?', '', $url);
            $url = str_replace('&', '/', $url);
            $url = str_replace('=', '/', $url);
        }

        return $url;
    }
```

## Environment

* Ampache version: 4.2.0
* Web server + version: nginx
* Server operating system: GNU/Linux
* Client operating system: Android

### Client type

* SubSonic

## Settings

I haven't seen setting named "stream_beautiful_url" that to me seems to get checked here

**Comment by lachlan-00** [comment]
What malformed about it? There are the rewrite rules and translate the URLs to this style.

The rewrite option is in system -> streaming

Enable URL Rewriting

**Comment by lachlan-00** [comment]
Looks the same here
```
play/ssid/mysessionid/type/song/oid/775644/uid/2/client/DSub/bitrate/320/cache/1/player/api/name/In%20Flames%20-%20Clayman.mp3
```

**Comment by mihapiha** [comment]
yeah, but then it doesn't work for me. It returns 404. Where can I disable this rewritting in ampache.cfg.php? Url of this type has to be rewritten again by the webserver right?

```
2020-08-15T21:01:14+00:00 [miha] (subsonic_api.class) -> Stream proxy: https://myhost.com/play/ssid/93d4e79a2a05b33caabac1c92f0f62d6/type/song/oid/654/uid/1/client/substreamer/content_length/required/player/api/name/Laibach%20-%20Eat%20Liver-.mp3 
2020-08-15T21:01:14+00:00 [miha] (subsonic_api.class) -> Stream error: The requested URL returned error: 404 Not Found
```

**Comment by lachlan-00** [comment]
You can disable it here. If the url 404s it means the rewrite rules aren't working.
![Screenshot_20200816-200831_Firefox Beta](https://user-images.githubusercontent.com/1305249/90331983-4aecb180-dffc-11ea-86ad-7fca520edac6.jpg)

**Comment by mihapiha** [comment]
ok that did the trick :)

**Comment by lachlan-00** [comment]
That's good. 

If you use Apache web server rename the htaccess.dist files. If you use nginx there are rules in the wiki (but I don't use nginx)

You can also ignore rewriting completely because it doesn't really matter that much and enjoy Ampache!
