### ISSUE TITLE
Purpose of "Statistics Day Threshold" in relation to "Newest Albums"?

### ISSUE THREAD

**Issue by PaulWalkerUK** [ampache/ampache#2511]
What's the purpose of the "Statistics Day Threshold" please in relation to "Newest Albums"?

When I click on "Albums" from main menu, it shows three sections: Trending, Newest and Popular. I've noticed that the "Newest" section doesn't actually show the very newest - it excludes (by default) the 7 newest ones. If I'm reading the code right, this is driven by the "Statistics Day Threshold" parameter (default = 7), being added to the SQL statement as an `offset` in the `LIMIT` clause.

The way I read the [wiki](https://github.com/ampache/ampache/wiki/Basic#interface), I was thinking this parameter would be used for things like to identify the most popular, but only in the last `x` days. That makes sense to me - as the wiki says, over a long period of time, a new album would never make the list without filtering. However, I'm not understanding the intention of it in _this_ context? It doesn't seem to be working as 'days', rather just hiding the `x` newest. Is it supposed to be working like this? Am I just missing something?

**Comment by lachlan-00** [comment]
that's totally a bug in day threshold.

My understanding is the same as yours " identify the most popular, but only in the last x days."

**Comment by lachlan-00** [comment]
Fixing the incorrect threshold. it was setting an offset instead of being ignored for newest

The wiki definitions are the way it should be applied so i'll do another check of these definitions to make sure it's applied everywhere.
Popular Threshold  = count / limit of items to display.
Stats threshold = get the most popular over the last x days

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if still relevant
