### ISSUE TITLE
Undisclosed vulnerability

### ISSUE THREAD

**Issue by usox** [ampache/ampache#2512]
Hi

@lachlan-00 I've send you an email two days ago regarding an urgent security issue. I just want to make sure, it doesn't get lost.

**Comment by lachlan-00** [comment]
got it. thanks for following up, i don't check the .dev email regularly

**Comment by usox** [comment]
Fixed with 4.2.2

**Comment by lachlan-00** [comment]
i'll be publishing in 2 weeks

**Comment by AshotN** [comment]
Out of curiosity, how severe was the vulnerability.

**Comment by usox** [comment]
Hi @AshotN 

@lachlan-00 will publish it within the next days. Until then, let's say I strongly recommend to update to the latest version :)

**Comment by lachlan-00** [comment]
it was the same as the last one in severity really, it's just this time we were actually ready to assign and resolve this one.

**Comment by lachlan-00** [comment]
Publishing now
