### ISSUE TITLE
Permanent change of db collation

### ISSUE THREAD

**Issue by mariof1** [ampache/ampache#2513]
I need to change the DB collation to utf8mb4_unicode_520_ci in order to properly sort/search the polish accent letters such as 'Ł'. In the past I was able to do it manually in mysql but I think the change reverts itself back to utf8_unicode_ci after some time; I think with every Ampache update (not sure?) 
![image](https://user-images.githubusercontent.com/32400371/90482290-e9773080-e12a-11ea-9490-745fc4b4fda2.png)
On daily basis I use the standard en-GB keyboard and if I search songs that contains 'Ł' I would simply type 'L' however this trick only works when collation is set to utf8mb4_unicode_520_ci.

**Comment by wagnered** [comment]
Not every update, just those that affect any of the tables.

Considering the fact that Ampache has been fine tuning it's search capability, I think it would be nice to be able to select the collation from a drop-down list on the admin page.  An adequate selection to meet the needs of all the installed locales.  Or maybe better, check the system locale and assign the appropriate collation to tables during install/update. Or both.

**Comment by lachlan-00** [comment]
Locale is picked before the database is created on install so that could work.

I think we should allow the collation at the very minimum to be selected.

For your specific issue does utf8mb4_unicode_ci cover your need?

I'm not sure what the 520 means though but I always assumed unicode was unicode

**Comment by wagnered** [comment]
I'm trying to look that up now. 

I'm also curious to know if utf8mb4_polish_ci would also work for him.

**Comment by wagnered** [comment]
I found it in Mysql development:

[10.3.1 Collation Naming Conventions](https://dev.mysql.com/doc/refman/5.7/en/charset-collation-names.html) 

And it has a reference to the meaning of the suffixes.

**Comment by lachlan-00** [comment]
cool, i thought that might have meant something else so that's good.

@mariof1 i'll give you the option to do this before the next database update ;)

**Comment by mariof1** [comment]
> For your specific issue does utf8mb4_unicode_ci cover your need?

@lachlan-00 utf8(mb4)_unicode_ci won't work for me. I didn't want to use country specific collations as I have German, French, Polish titles with their original names. With utf8mb4_unicode_ci some accented letters can be searched using their equivalent letters

utf8mb4_unicode_ci - polish letters

a = ą OK
c = ć OK
e = ę OK
l = ł NOT OK
n = ń OK
o = ó OK
s = ś OK
z = ż OK

utf8mb4_unicode_ci - french letters
words such as côté can easily be searched as 'cote' altough I am not sure what is the equivalent to sing 'œ' or 'æ'

utf8mb4_unicode_ci - german letters
s = ß OK
o= ö OK
a = ä OK 

So the collation utf8mb4_unicode_ci would work, but it is not suitable as I have a few Polish artists/songs that begins with 'Ł' so unless I have a polish keyboard I will not be able to search by their first letters

**Comment by lachlan-00** [comment]
Sure thing. Thanks for laying it out like that.

I'd like to make sure any artist is covered so let's make this possible with collation selection.

**Comment by lachlan-00** [comment]
I just found the issue, I'm going to allow this to be overridden with a config setting

```
* Run Dba::reset_db_charset() after upgrade in case people are playing
  hot potato with their charsets.
```
![image](https://user-images.githubusercontent.com/1305249/90600785-84126500-e23a-11ea-9eb5-1c2faaea97f8.png)

**Comment by lachlan-00** [comment]
@mariof1 the changes are in develop but i'll test on my own database before i update the config version to force an update.

This is actually a pretty good change to include and i know that it's probably been an annoying one to manage!

**Comment by mariof1** [comment]
Awesome, thanks for your quick work on this

**Comment by lachlan-00** [comment]
Works well from existing database, i've converted my DB over to utf8mb4

one issue left, the table engine myisam doesn't seem to like using the 4byte characters in the keys which is sort of the point of converting the db over.
```
2020-08-20T06:53:37+10:00 [user] (dba.class) -> Unable to update the charset of name.varchar(255) to utf8mb4
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query SQL: ALTER TABLE `artist` MODIFY `name` varchar(255) CHARACTER SET utf8mb4
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query MSG: ["42000",1071,"Specified key was too long; max key length is 1000 bytes"]
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query SQL: ALTER TABLE `artist` MODIFY `name` varchar(255) CHARACTER SET utf8mb4
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query MSG: ["42000",1071,"Specified key was too long; max key length is 1000 bytes"]
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query SQL: ALTER TABLE `artist` MODIFY `name` varchar(255) CHARACTER SET utf8mb4
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query MSG: ["42000",1071,"Specified key was too long; max key length is 1000 bytes"]
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query SQL: ALTER TABLE `artist` MODIFY `name` varchar(255) CHARACTER SET utf8mb4
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Error_query MSG: ["42000",1071,"Specified key was too long; max key length is 1000 bytes"]
2020-08-20T06:53:38+10:00 [user] (dba.class) -> Unable to update the charset of name.varchar(255) to utf8mb4
```

**Comment by lachlan-00** [comment]
change is in develop now @mariof1.

If you want to wait for master it'll be a while before you can force a change from Ampache (marked for ampache 5.0.0 now) but i am taking out the auto reset in the next release (4.2.2) so it doesn't affect you any more either way.

**Comment by mariof1** [comment]
Hi @lachlan-00,

I have tested your latest change and it did not work for me. I have updated config file with utf8mb4_unicode_520_ci and then run
`php /var/ampache/bin/update_db.inc -x`
I can see the database and tables collation were nicely updated but the actual columns were not
Some accented letters are still sorted at the end of alphabet however they should come up next to their equivalent letters

![image](https://user-images.githubusercontent.com/32400371/90864251-3c99ef00-e388-11ea-847d-6c221e6e91dc.png)
![image](https://user-images.githubusercontent.com/32400371/90864273-4885b100-e388-11ea-803e-4c4d020e3ab5.png)

**Comment by lachlan-00** [comment]
does the data need to be verified / updated from tags to correct the column values?

**Comment by mariof1** [comment]
I will test it now

**Comment by mariof1** [comment]
Updating data from tags did not help.
I have manually updated few columns which helped
```
ALTER TABLE song MODIFY title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE artist MODIFY name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE album MODIFY name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
```
Now I can search accented letters just fine and all is sorted as it should
![image](https://user-images.githubusercontent.com/32400371/90866570-03637e00-e38c-11ea-99b4-dbed33d5d7ab.png)

**Comment by lachlan-00** [comment]
in 36cc1aed4 i've set it to CONVERT instead of default. this should change the collation and charset in existing tables

**Comment by mariof1** [comment]
I have just pulled the latest commit and run `php /var/ampache/bin/update_db.inc -x`.
All columns were updated with `utf8mb4_general_ci` despite my ampache.cfg.php says `utf8mb4_unicode_520_ci`

![image](https://user-images.githubusercontent.com/32400371/91274676-f8875f80-e776-11ea-8d97-df07fc532ac3.png)

**Comment by stebe** [comment]
I tried too but I'm getting these errors in the logs.

```
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 

```

**Comment by lachlan-00** [comment]
> I tried too but I'm getting these errors in the logs.
> 
> ```
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> ```

what db server is that?

**Comment by lachlan-00** [comment]
> I have just pulled the latest commit and run `php /var/ampache/bin/update_db.inc -x`.
> All columns were updated with `utf8mb4_general_ci` despite my ampache.cfg.php says `utf8mb4_unicode_520_ci`

I'm going to do another query to select all the columns to alter manually it doesn't seem to process the convert the right way

**Comment by lachlan-00** [comment]
on the plus side once it's done once you won't need to do it again

**Comment by wagnered** [comment]
@lachlan-00  the engine change needs to be done before the character set/ collation change.  A two step procedure.

**Comment by lachlan-00** [comment]
i just picked it up then too

**Comment by lachlan-00** [comment]
So i've pasted essentially a whole manual query for the columns into DBA and it doesn't update the collation.

paste it into phpmyadmin and it works....

**Comment by lachlan-00** [comment]
okay, i've done individually column changes in 7945c26c0 as well as split the engine change to stop that error.

It apparently will work once and then subsequent changes failed so that's probably close. i'm just doing one more test now

**Comment by lachlan-00** [comment]
k, **now** it's converted everything.

**Comment by wagnered** [comment]
'SHOW TABLE produces formatted output in each row.

I suggest that the query:
```
    SELECT DISTINCT TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'ampache';
```
Use the resulting array for the alter table query.  It'll be a lot cleaner.

**Comment by wagnered** [comment]
I'm probably wrong about the formatted output.  That might be MySQL doing that.

**Comment by mariof1** [comment]
@lachlan-00 Perfect your latest fix did the trick for me.

**Comment by lachlan-00** [comment]
Good!
Now that you've convertedeverything the function will not run again unless you convert again manually.

**Comment by stebe** [comment]
> > I tried too but I'm getting these errors in the logs.
> > ```
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `access_list` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query SQL: ALTER TABLE `album` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ENGINE=InnoDB 
> > 2020-08-26T04:27:45-04:00 [ampache] (dba.class) -> Error_query MSG: ["42000",1064,"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ENGINE=InnoDB' at line 1"] 
> > ```
> 
> what db server is that?

Sorry about the late response but just for the record: mariadb --version
 mariadb  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

I just ran the script and it works great for me too.

**Comment by wagnered** [comment]
It might be "running great", but has anyone tried adding files after the change?

I have a file I had no problem importing before the attempted change now I get the following:

>  05 Lua Soberana.mp3 has non-UTF-8 characters and can not be indexed, converted filename: 

And as can be seen, it evidently couldn't convert the file and it wasn' added to the catalog.

I'm fairly sure the character set is iso 8859-1 for the title which shouldn't matter because there are no accented characters.

Just wonder if I'm alone in this?

**Comment by lachlan-00** [comment]
I'll do another add on my test server and check.

**Comment by lachlan-00** [comment]
I actually get more files using utf8mb charsets compared to regular utf8.
![image](https://user-images.githubusercontent.com/1305249/91679282-34616100-eb8b-11ea-98d2-0d328b42c4a4.png)

So this change actually helps out with weirdly named files. :)

**Comment by lachlan-00** [comment]
this is all good, hasn't been an issue and the default collation will end up changing with 5
