### ISSUE TITLE
develop 3d48e9d breaks 0 ratings in smart playlists

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2515]
## Description
The changelog for commit [5ffbac7](https://github.com/ampache/ampache/commit/d9fdd7b6b7a9a20d659f0757f00bd62ec5a4e0db) said that the logic of 0 ratings was changed, but now it seems to be broken.

### Describe the bug
Any smart playlist with a zero rating for artist, album or song returns zero results. See screenshot below.
![image](https://user-images.githubusercontent.com/879342/90858394-1ce8d380-e354-11ea-9077-6df08d0df5a9.png)

**Comment by lachlan-00** [comment]
i'll check, i spent all day on this so far!

**Comment by lachlan-00** [comment]
i see it i used in_array which is matching on equals
