### ISSUE TITLE
Ampache Debug not reporting correct value.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2516]
`Ajax loading` is disabled on the interface list, but Ampache Debug shows that it is enabled.  Might be reading preferences of the admin user and not system.

**Comment by lachlan-00** [comment]
it runs a get all
![image](https://user-images.githubusercontent.com/1305249/91108212-b7317a00-e6ba-11ea-9e29-bff66182307b.png)

which is just a grab of global
![image](https://user-images.githubusercontent.com/1305249/91108191-a123b980-e6ba-11ea-8f89-8478e40ce359.png)

Doesn't seem like that should be different from the active admin user but i'll do some comparison

**Comment by wagnered** [comment]
Well, admin typically has a user ID of 1 system is -1 so I'm not so sure they would or should be the same.  

Also, I toggled the "ajax load" setting in the user preference tab and the Ampache Debug page toggled in sync.

And that begs the question: How does self::$_global get loaded.

**Comment by lachlan-00** [comment]
it's actually not a global but an array in the ampconfig class
![image](https://user-images.githubusercontent.com/1305249/91116499-da1a5900-e6cf-11ea-8bd5-ced72c02a9f1.png)

it looks like it loads from preference using either the session or database preferences. might be the session isn't updated but loaded?
![image](https://user-images.githubusercontent.com/1305249/91116630-1cdc3100-e6d0-11ea-9a5f-510fecd69f14.png)

**Comment by wagnered** [comment]
Everything I know is wrong about preferences. ☹️. -1 isn't system user, it's the low level *Ampache user".  Although at database update time it gets the same values as the preference table gets. Also the update function can update the default value and the user preference at the same time, so maybe  -1  could be considered a system user. 

I'm tired thinking, so I'm going to quit for the night.

**Comment by mitchray** [comment]
Closing stale issue, reopen if still relevant
