### ISSUE TITLE
Disabling custom metadata fields fails

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2517]
The array that arrives at the `update_preferences` function in lib/preferences.php isn't being handled  correctly.

**Comment by lachlan-00** [comment]
do you mean here where the value is cast to string?

```
foreach ($results as $data) {
        // Get the Value from POST/GET var called $data
        $name            = (string) $data['name'];
        $apply_to_all    = 'check_' . $data['name'];
        $new_level       = 'level_' . $data['name'];
        $pref_id         = $data['id'];
        $value           = (string) scrub_in($_REQUEST[$name]);

```

**Comment by lachlan-00** [comment]
93eb3ec98 stops casting to string

**Comment by wagnered** [comment]
What am I missing?  I still see the `(string)` in front of ` $data['name']`.  I'll take another look, but the array needs to be imploded to turn it into a string.  `(string)` is not a miracle cure. 😄

**Comment by lachlan-00** [comment]
took it out here to allow arrays
```
$value        = scrub_in($_REQUEST[$name]);
```

**Comment by wagnered** [comment]
Hold on!!!  I need to look at that again.  In `Preference::update` the value **is** imploded.  I was super tired, maybe I misunderstood or misread the error.

**Comment by wagnered** [comment]
Yes, that did it. 

I am going to move that list from the song edit dialog to show_song_row.inc.php.  I don't see any point to allow them to be edited.

**Comment by mitchray** [comment]
Closing issue as it appears to be resolved? Reopen if not
