### ISSUE TITLE
Radio Station codec must be specified in lowercase

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2518]
I have spent many hours trying to get the radio stations feature working, and could not get it working in either version 4.2.1 or the latest development version cloned from github.  The first time I tried to add a new radio station, I did not specify anything in the codec dialog, and when clicking the "Add" button, I got the message "Codec is required (e.g. MP3, OGG...)", so from then on in all my tests, I was specifying codecs in UPPERCASE as the error message indicated.  But whenever I would try to play a station in the Web Player, nothing would happen.  It wasn't until I tried for fun changing the codec in one of my tests stations to lowercase, and then everything started working.  Changing the rest of my test stations to lowercase (both ogg and mp3) and they started working too.  It's not technically a bug, so I did not submit this as such, but could you please add a quick patch to convert to lowercase text entered into the codec input field, and/or change the error message to say that codecs must be entered in lowercase?  Hopefully it will prevent others from having the same issue that I did.

**Comment by kuzi-moto** [comment]
Thanks for the find! Is is interesting that it requires lower-case, but it should definitely be designed so it doesn't matter either way.

**Comment by lachlan-00** [comment]
i always wondered why some of my stations would fail... great digging!

**Comment by lachlan-00** [comment]
i'm just fixing the captcha up but will fix this up today

**Comment by barcoboy** [comment]
Thanks.  It was a total last resort trial before I wrote something here wondering what the heck I was doing wrong!

**Comment by lachlan-00** [comment]
just pushed up b833b55d9 to fix this. update/edit of radios will input the lowercase string.

**Comment by barcoboy** [comment]
Works great, thanks!

**Comment by lachlan-00** [comment]
thank you for finding something i bet hundreds of people (including me) never even realised.

**Comment by barcoboy** [comment]
Happy to help out.  Ampache is a great product, so I'm glad to contribute to it even if ever so slightly.  :-)
