### ISSUE TITLE
Runtime Error when running catalog_update.inc script using -u switch

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2519]
Don't often run the script using this switch but when I did this morning, I noticed the ampache log filling up with the following error message a couple of times per second:

`[ampache] (log.lib) -> [Runtime Error] Recommendation::get_artists_like(): Node no longer exists in file /var/www/html/ampache/lib/class/recommendation.class.php(274)`

Don't know if this is affecting the actual results of the script as the artist info and similar artist info seems to be updating correctly?

**Comment by lachlan-00** [comment]
Looks like a bug. I can sort that out tomorrow

**Comment by lachlan-00** [comment]
I tried a direct link and it looks like Lastfm has killed my API key so it's actually an unhandled error

```
Invalid API key - You must be granted a valid key by last.fm
```

**Comment by lachlan-00** [comment]
And another error that needs to be checked for.

```
code="6">The artist you supplied could not be found
```

**Comment by lachlan-00** [comment]
K this isn't going to stop the other artists but it's definitely not handling empty results so will need to fix

**Comment by lachlan-00** [comment]
fixed now.
