### ISSUE TITLE
Change all usage of utf8 to utf8mb4

### ISSUE THREAD

**Issue by poizan42** [ampache/ampache#2520]
The so-called utf8 in MySQL (now renamed to utf8mb3 with utf8 an alias) is not real UTF-8 and only supports a subset of Unicode. It only exists today because of backwards compatibility. It has also been officially deprecated in MySQL 8.0: https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

Some more information on the situation here: https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by lachlan-00** [comment]
it's not something that can be switched out easily but the next release will allow you to select mb4 charsets and upgrade the database.

for ampache 5 i'll look at changing the default

**Comment by palto42** [comment]
After upgrading to release 4.2.2, I have changed the charset in the Ampache configuration file `ampache.cfg.php` to utf8mb4 and then clicked the "set database charset" on the admin debug page.
Was this the correct way to change to the charset and how can I check that it's correctly applied?  I didn't get any response from the admin page, I think it timed out after a while.

**Comment by lachlan-00** [comment]
it takes a loonnnngggg time to convert. the best way to do it is from the cli so you can tell when it's finished (and won't time out)
![image](https://user-images.githubusercontent.com/1305249/92981780-b84a1000-f4de-11ea-9ef6-4a429c9ecd6d.png)

just run without the -x first to verify that your config is ready and then -x to fire it off.
even on a new install i think it took almost 10 mins to convert

**Comment by palto42** [comment]
@lachlan-00 Thanks!
Successfully tested with comment field using some random 3 and 4 Byte UTF8 chars: ൫𝃆

**Comment by lachlan-00** [comment]
I will put a choice in at install time to let people set things but that's a while away yet. Glad to see the changes are working the right way

**Comment by lachlan-00** [comment]
my plan for this now is to do the sql extract from my database while adding the option at install to choose

**Comment by phirestalker** [comment]
Sorry, I am unclear where to set this in the configuration.

**Comment by lachlan-00** [comment]
> Sorry, I am unclear where to set this in the configuration.

in your config
![image](https://user-images.githubusercontent.com/1305249/127805727-81e42173-9a28-4d4a-a62c-0f6a7765a779.png)


then in develop you run `php bin/cli run:updateDb`
![image](https://user-images.githubusercontent.com/1305249/127805798-438ed185-4ed3-48c7-9b9d-ce990f9ecaad.png)

in stable the command is `php bin/update_db.inc`

add -x if you want to convert

**Comment by lachlan-00** [comment]
default is changed now
