### ISSUE TITLE
API doc: Descriptions of the `auth` parameters have got mixed up between `ping` and `goodbye` actions

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#2523]
The API doc states that `ping` can be used to destroy the session and `goodbye` to extend it :).

![image](https://user-images.githubusercontent.com/8565946/92312793-ffab3a80-efcc-11ea-9cfd-12009c55e3f1.png)

**Comment by lachlan-00** [comment]
Lol! Thank you for notifying me. The API was available from about 5 different sources so it looks like I'll be cleaning up olld errors for a while yet!

**Comment by lachlan-00** [comment]
updated!
