### ISSUE TITLE
Failed to Create User on registration page but the user successfully created at the back

### ISSUE THREAD

**Issue by Vino-git** [ampache/ampache#2524]
Hello Team,

I have download the master version of this repo and enabled the public user registration. Everything is working fine but the registration page shows "Failed to Create user" even though the user created in the MYSQL DB successfully. Below is my config file of user registration.

;#########################################################
; Public Registration settings, defaults to disabled     #
;#########################################################

; This setting will silently create an Ampache account
; for anyone who can login using LDAP (or any other login
; extension). The default is to create new users as guests
; see auto_user config option if you would like to change this
; DEFAULT: "false"
;auto_create = "false"

; This setting will silently update an Ampache account's
; information for anyone who can login using LDAP
; (or any other login extension).
; DEFAULT: "false"
;external_auto_update = "false"

; This setting turns on/off public registration. It is
; recommended you leave this off, as it will allow anyone to
; sign up for an account on your server.
; REMEMBER: don't forget to set the mail from address further down in the config.
; DEFAULT: "false"
allow_public_registration = "true"

; Require Captcha Text on Image confirmation
; Turning this on requires the user to correctly
; type in the letters in the image created by Captcha
; Default is off because its very hard to detect if it failed
; to draw, or they failed to enter it.
; DEFAULT: "false"
;captcha_public_reg = "false"

; This setting turns on/off admin notification of registration.
; DEFAULT: "false"
;admin_notify_reg = "false"

; This setting determines whether the user will be created as a disabled user.
; If this is on, an administrator will need to manually enable the account
; before it's usable.
; DEFAULT: "false"
;admin_enable_required = "false"

; This setting will allow all registrants/ldap/http users
; to be auto-approved as a user. By default, they will be
; added as a guest and must be promoted by the admin.
; POSSIBLE VALUES: guest, user, admin
; DEFAULT: guest
auto_user = "user"

; This will display the user agreement when registering
; For agreement text, edit config/registration_agreement.php
; User will need to accept the agreement before they can register
; DEFAULT: "false"
;user_agreement = "false"

; This disable email confirmation when registering.
; DEFAULT: "false"
;user_no_email_confirm = "true"

; This will display the cookie disclaimer (EU Cookie Law)
; DEFAULT: "false"
cookie_disclaimer = "true"

; The fields that will be shown on Registration page
; If a user wants to register.
; Username and email fields are forced.
; POSSIBLE VALUES: fullname,website,state,city
; DEFAULT: fullname,website
registration_display_fields = "website"

; The fields that will be mandatory
; This controls which fields are mandatory for registration.
; Username and email fields are forced mandatory.
; POSSIBLE VALUES: fullname,website,state,city
; DEFAULT: fullname
registration_mandatory_fields = ""

;########################################################

**Comment by lachlan-00** [comment]
I see the issue, i should add this to a master update asap.

**Comment by lachlan-00** [comment]
you can edit register.php to bypass this
![image](https://user-images.githubusercontent.com/1305249/92419072-9b47d100-f1ae-11ea-8083-1281527e1aa6.png)

**Comment by Vino-git** [comment]
Wow... That's great! Thank you @lachlan-00 .

I did the change and it works.
