### ISSUE TITLE
DSub fails to update playlists  

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#2526]
## Description

After the update to 4.2.0 from 4.1.1 DSub is unable to update the playlists. 

### Describe the bug
 In DSub, select playlists in the menu, then refresh it, by swiping down. This brings a "No data" message. At least it looks like DSub is keeping the old playlists it already knows about, but new ones created since the update do not show up.

## Environment

* Ampache version: 4.2.0 updated from 4.1.1
* Web server + version: apache 
* Server operating system: Raspbian
* Client operating system: Android 8.1.0

### Client type

* SubSonic : DSub 5.0.3

**Comment by cquike** [comment]
I think I know more or less what is happening. After the last upgrade to 4.2.0 a new column "last_duration" was added to the "search" table. The default value for that column is NULL. For some reason, one of the playlists have the value NULL in last_duration. I speculate that this happens for the playlists that I have not visualized yet in the ampache UI since the upgrade. 

For some reason, which I don't know, also the last_count value for this particular playlist is also NULL.
It turns out that when both columns are NULL the XML response looks like this:
2020-09-07T21:47:40+02:00 [user1] (subsonic.class) ->     <playlist id="400000006" name="All random" owner="user1" public="true" created="2020-09-07T21:47:40+02:00" changed="2020-09-07T21:47:40+02:00" songCount="" duration=""/>. As you see  songCount="" duration="". Comparing to ampache 4.1.1 those fields are not present if the columns where NULL. 

According to the subsonic API songCount and  duration are mandatory, so I guess 4.2.0 has "fixed" that by adding them always, also if they are originally undefined. It looks like DSub has problems receiving the "" as a response where an integer is expected. Whether this is intentional or not I don't know. I have tried with UltraSonic app and it seems to be happy.

**Comment by cquike** [comment]
As a workaround for others having the same problem: simply browsing the playlist in the ampache UI is enough to fill the song count and duration in the database. This would need to be done for all the playlists, to be on the safe side.

**Comment by lachlan-00** [comment]
might be in this area. i put zeros in the above part but not for the else part.
![image](https://user-images.githubusercontent.com/1305249/92420137-0ac0bf00-f1b5-11ea-8684-37b3ba21638a.png)

**Comment by lachlan-00** [comment]
i'll put a cast to int in the search class to get around this

**Comment by lachlan-00** [comment]
the casting should get around this andi'll do a DB update later to change this to a 0 by default along with a few other nulls that should be ints
