### ISSUE TITLE
[Feature Request] Add MBID to advanced search API

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2528]
## Describe what you don't like about Ampache, or what it is missing
I'm trying to write a program in Python that syncs the ratings between Ampache and Musicbrainz; I can sync from Ampache to MB, but I cannot sync back because the API currently doesn't allow me to search for objects by MBID.

**Comment by lachlan-00** [comment]
that's easy enough, should be able to add that in to songs, artists and albums methods too

**Comment by lachlan-00** [comment]
doe musicbrainz have unique MBID across all objects? or is it only unique per type?

**Comment by SimonHova** [comment]
To the best of my knowledge, the MBID is not guaranteed unique between
types, every time I've had to input it, I'd had to input the type of object
I'm searching for, be it a recording, artist or release group.

**Comment by lachlan-00** [comment]
okay, that's easy then, i didn't think it was unique. it will be easy to fit into search/advanced search as a rule type but will also be able to go in other places

**Comment by lachlan-00** [comment]
in develop advanced search can use these rules.
'mbid' can be used for song, album, artist
'mbid_album', 'mbid_artist' for song searches

**Comment by ibmibmibm** [comment]
Althrough `mbid` is not guaranteed unique between types, Musicbrainz provided a url for unknown `mbid` query: `https://musicbrainz.org/mbid/{unknown_mbid}`

**Comment by lachlan-00** [comment]
mbid is in advanced search, will double check docs to make sure it's in there for api people as well.
