### ISSUE TITLE
limit=none kills XML query

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2529]
### Describe the bug

While logged in as Administrator, XML call

`/server/xml.server.php?action=get_indexes&auth=xxx&type=playlist&limit=none`

returns

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
<total_count>0</total_count>
</root>
```

Removing `&limit=none` returns the correct list of playlists.

Same behavior experienced with `action=artists`. More than likely others are also affected.

This breaks clients that have "limit=none" added to their XML calls to disable default limit.

## Environment

* Ampache version: 4.2.2, 4.2.0
* Web server + version: Apache2
* Server operating system: Raspbian Linux
* Client operating system: Android 9, Ubuntu Linux

### Client type

* Web (tested XML calls in browser)
* Ampache
* Waver

**Comment by lachlan-00** [comment]
Found a lot of bugs today this is probably another. It should probably get cast to 0

**Comment by 4phun** [comment]
This is one of SQL's less straightforward syntax cases: LIMIT 0,10 returns 10 records, but LIMIT 0 returns zero records. Given the usage of "limit=none", I think it should translate to "no LIMIT clause at all".

**Comment by lachlan-00** [comment]
in get_indexes it should actually be removed if none so the browse shouldn't change the sql
![image](https://user-images.githubusercontent.com/1305249/92831884-4b6d4200-f41a-11ea-81fc-c3670bf5c9de.png)

**Comment by lachlan-00** [comment]
can see it's instantly failing though.

**Comment by lachlan-00** [comment]
found it
![image](https://user-images.githubusercontent.com/1305249/92841213-62656180-f425-11ea-8673-7d9b2970c1ba.png)

**Comment by lachlan-00** [comment]
fixed for json and xml
