### ISSUE TITLE
XML playlists have count instead of track id

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#2530]
### Describe the bug

While logged in as Administrator, execute the XML call

`/server/xml.server.php?action=get_indexes&auth=xxx&type=playlist`

returns

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
<total_count>61</total_count>
<playlist id="20">
	<name><![CDATA['70s Hard Rock]]></name>
		<playlisttrack>1</playlisttrack>
		<playlisttrack>2</playlisttrack>
		<playlisttrack>3</playlisttrack>
		<playlisttrack>4</playlisttrack>
		<playlisttrack>5</playlisttrack>
		<playlisttrack>6</playlisttrack>
		<playlisttrack>7</playlisttrack>
		<playlisttrack>8</playlisttrack>
```
and so on and so forth.

Whereas it should contain the track id inside `<playlisttrack>`, as it used to before. Unfortunately I'm not sure which version brought the issue.

## Environment

* Ampache version: 4.2.2, 4.2.0
* Web server + version: Apache2
* Server operating system: Raspbian Linux
* Client operating system: Android 9, Ubuntu Linux

### Client type

* Web (tested XML calls in browser)
* Ampache
* Waver

**Comment by lachlan-00** [comment]
like that?
```
<playlisttrack id=songid>1</playlisttrack>
```

i've been back through the python releases and i can't see where it changes but i think it needs the id

**Comment by lachlan-00** [comment]
i've fixed this up now.

i've added an 'include' option for json and also kept it on by default for xml.
BUT i make them both require include for Ampache 5.0.0
![image](https://user-images.githubusercontent.com/1305249/92687296-9afe3000-f37e-11ea-9872-293a75e76ff3.png)

when 5 comes out you'll need to add include=1 for xml calls. (for now its enabled if the format is xml)

here's an example of the output in xml
```
<total_count>1</total_count>
<playlist id="2002">
	<name><![CDATA[dewaardradio]]></name>
		<playlisttrack id="144382">1</playlisttrack>
		<playlisttrack id="144383">2</playlisttrack>
		<playlisttrack id="144385">3</playlisttrack>
		<playlisttrack id="144393">4</playlisttrack>
		<playlisttrack id="144391">5</playlisttrack>
		<playlisttrack id="144395">6</playlisttrack>
		<playlisttrack id="144386">7</playlisttrack>
		<playlisttrack id="144384">8</playlisttrack>
		<playlisttrack id="144389">9</playlisttrack>
</playlist>
</root>
```

**Comment by 4phun** [comment]
Hi!

This is great idea! Wholeheartedly agree, include songs only if they are explicitly requested. I have no objection making this required now in XML too.

To answer your first question, it used to be:
```
<playlisttrack>144382</playlisttrack>
<playlisttrack>144383</playlisttrack>
<playlisttrack>144385</playlisttrack>
<playlisttrack>144393</playlisttrack>
```
In other words, the problem is not that the id disappeared, but that it was replaced with count.

Thank you

**Comment by lachlan-00** [comment]
Ahh, that makes more sense. I looked through trying to see a difference but didn't compare numbers.

I'll keep the option in develop but change just before master.

I'm trying to make sure when something has an id we send it as an id the same way.

**Comment by 4phun** [comment]
Sounds great, thank you!

**Comment by lachlan-00** [comment]
I was going to reverse the id and track count back but it probably needs to stay this way to stay in line with json and the code rules. this is how it will go in develop and 5.0.0 when released
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
<total_count>1</total_count>
<playlist id="2002">
	<name><![CDATA[radio]]></name>
		<playlisttrack id="35009">1</playlisttrack>
		<playlisttrack id="35019">2</playlisttrack>
		<playlisttrack id="35020">3</playlisttrack>
		<playlisttrack id="35022">4</playlisttrack>
		<playlisttrack id="35037">5</playlisttrack>
		<playlisttrack id="35047">6</playlisttrack>
		<playlisttrack id="35048">7</playlisttrack>
		<playlisttrack id="35060">8</playlisttrack>
		<playlisttrack id="35063">9</playlisttrack>
		<playlisttrack id="35067">10</playlisttrack>
</playlist>
</root>
```

**Comment by 4phun** [comment]
Sounds good to me, I agree it's more consistent this way.

To be honest, I think the most important improvement from this issue is that "action=get_indexes&type=playlist" should speed up a lot when "include=0". Because smartlists are not needed to be executed when list of tracks is not needed.
