### ISSUE TITLE
Cooldown longer than 255 minutes

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2531]
Trying to setup a democratic playlist, and have discovered that if I put in a cooldown time longer than 255 minutes, the playlist isn't updated/created, and no error message or notification is generated.  Can this be extended?  I'd like to use my entire catalog as a playlist, and not hear the same song played for several days.

**Comment by lachlan-00** [comment]
it's a tinyint so at the moment it's outside the table range
![image](https://user-images.githubusercontent.com/1305249/92659609-0c68bf00-f33c-11ea-9c4f-e156e2351bd8.png)

will need a dbupdate, i'm not really sure why it needs to be so small so that's not an issue

**Comment by lachlan-00** [comment]
a lot of things still don't cause errors when outside the range of the database so also a sort of bug in that it should tell you it's out of range.

**Comment by lachlan-00** [comment]
would 2 million days cover you? ;)

**Comment by barcoboy** [comment]
Hahaha yeah I think so.  :-D

**Comment by lachlan-00** [comment]
have at it!

also try putting in something under 0 or over 3000000000 it should fail

**Comment by barcoboy** [comment]
The maximum value the form will let me enter in is six digits or 999999 minutes, and it accepts that.  A negative number is not accepted. but I am not seeing the "There Was a Problem" message that I see per the source code should appear.

**Comment by lachlan-00** [comment]
okay, 999999 is almost 2 years. i'll see if i can break it myself now. i was just working on the api

**Comment by lachlan-00** [comment]
k, fixed it, i forgot the break so it continued back to the setting page.

so it was warning you, you could just never see it. ;)

**Comment by barcoboy** [comment]
Working now, thanks!
