### ISSUE TITLE
Release 4.2.2 MD5SUM mismatch for downloaded ampache-4.2.2_all.zip

### ISSUE THREAD

**Issue by palto42** [ampache/ampache#2532]
### Describe the bug
MD5SUM of new release 4.2.2 doesn't match with value on release page

### To reproduce

  1. Download [ampache-4.2.2_all.zip](https://github.com/ampache/ampache/releases/download/4.2.2/ampache-4.2.2_all.zip) from [Release 4.2.2](https://github.com/ampache/ampache/releases/tag/4.2.2) page.
  2. Run `md5sum ampache-4.2.2_all.zip`provides result `b0d00cb74d81f56b572ac0dbf10b85e9`
  3. Value published on Release page is `d5c37a0889f8e4a79d11458a89a8bc19`

Tried two times on different systemd (Ubuntu 20.04.1 and Solus) with same result.

**Comment by lachlan-00** [comment]
No good! I did edit the original draft a few times and possibly did not update.

I keep the upload originals so I will check that out asap to compare

**Comment by lachlan-00** [comment]
confirmin the upload md5 is original but my doc is wrong
![image](https://user-images.githubusercontent.com/1305249/92818036-941cff00-f40a-11ea-85b8-1d09f647d8cd.png)

**Comment by palto42** [comment]
Thanks for your quick response and fix - and for this great software :+1:
