### ISSUE TITLE
[Feature Request] update_art should return the new art path

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2535]
The API currently allows for requesting for artist art to be updated, but does not provide the new art unless we pull the artist information all over again. Seems somewhat wasteful, would be nice to have the option to include the art in the response.

**Comment by lachlan-00** [comment]
do you mean the art url or the binary art?

**Comment by AshotN** [comment]
The URL.

**Comment by lachlan-00** [comment]
i'll extend the message method to include objects like that on the return as well

**Comment by lachlan-00** [comment]
happy with something like this? i'm adding an array on the end of message to add extra data
```
{
    "success": "successfully update art"
    "art": "https://etcetcetc"
}
```

**Comment by lachlan-00** [comment]
done.
```
{
    "success": "Gathered new art for: 1893 (artist)",
    "art": "https:\/\/music.com.au\/image.php?object_id=1893&object_type=artist&auth=5g45yt34wg34e6152bc7"
}
```

```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<success code="1"><![CDATA[Gathered new art for: 1893 (artist)]]></success>
	<art><![CDATA[https://music.com.au/image.php?object_id=1893&object_type=artist&auth=5g45yt34wg34e6152bc7]]></art>
</root>
```

```
