### ISSUE TITLE
Find Duplicates missing items

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2537]
Trying to use the "Find Duplicates" on my catalog of around 6300 Christmas songs, and it doesn't seem to be finding all of them, whether I choose just "Title" or "Title and Artist".

According to the following query in my database:

select title, count(title) from song 
group by title
having count(title) > 1;

tells me that I have 168 songs with the title "Silent Night", but this title does not appear at all in the Find Duplicates Title only results.

Running the following query:

select title,artist,count(*) as NumDuplicates from song
group by title,artist
having NumDuplicates > 1;

returns 442 rows of results, while the Artist and Title search in Find Duplicates only returns 39 rows.

Two other minor issues with the page:

1) The first row of the results is always appearing as disabled, showing the green checkmark icon to enable it, even though I have no disabled songs in my catalog.  It appears to be cosmetic only, as if I click the checkmark icon, the song gets disabled and the checkmark remains, but a second click re-enables the song and the red circle with a line through it appears.

2) There are no radio buttons pre-selected when the page is first loaded or reloaded with the results, even though the default search appears to be Title and the "Find Duplicates" button can be pressed.

**Comment by lachlan-00** [comment]
that page is really badly in need of work.

**Comment by mitchray** [comment]
Closing as 'Find Duplicates' was removed in 5.0.0, use 'Possible Duplicate' in searches instead (advanced search)
