### ISSUE TITLE
API check for plugin values

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2540]
Hey @4phun would amproid benifits by being able to read plugin or preference data?

I was thinking about making an API method for accessing data where we could read preferences and I think amproid would benefit from something like a 'favourite playlist' pref.

This way it could stick to the 'music asap' process and also allows API clients to have a quick shuffle choice based on the user preferences.

**Comment by 4phun** [comment]
Hi,
It would be good, but there should be favorite playlist and favorite album. Maybe even favorite smartlist. 2 or 3 favorite items. I could have them on the home page, so user wouldn't have to descend into browse/playlists to find them.
Thank you

**Comment by lachlan-00** [comment]
that's actually an even better way of doing it
i should be able to make a plugin for that

**Comment by lachlan-00** [comment]
new plugin in 56b2a6de1
![image](https://user-images.githubusercontent.com/1305249/93416612-6b54a800-f8e9-11ea-8e18-b9edc35cefee.png)

![image](https://user-images.githubusercontent.com/1305249/93416625-73ace300-f8e9-11ea-9984-24d68eecb50c.png)

I will expand on this to allow comma separated items but this gives me the preferences to pull in from the API!

**Comment by lachlan-00** [comment]
okay, user_preferences is in. thanks for the discussion.
![image](https://user-images.githubusercontent.com/1305249/93427613-74517380-f901-11ea-830b-651488d7b83d.png)
![image](https://user-images.githubusercontent.com/1305249/93427641-816e6280-f901-11ea-97be-de38f49061f4.png)

**Comment by 4phun** [comment]
Cool! Just two questions: what is XML method to call, and from which version will this be available?

**Comment by lachlan-00** [comment]
user_preferences in develop now but will be out for 5.0.0

**Comment by AshotN** [comment]
Will user_preferences allow for custom preferences to be saved.

I want to be able to save settings regarding the React Client onto the server.

**Comment by lachlan-00** [comment]
I'm adding in system_preferences soon, we should allow custom prefs from there that a user can set
