### ISSUE TITLE
DSub client does not download and does not play songs

### ISSUE THREAD

**Issue by gbrea** [ampache/ampache#2542]
## Description
The subsonic Dsub client for android does not download songs.

### Describe the bug

I have Ampache 4.2.2 installed. Both the web client and the Android power ampache client work correctly, but if I try to use a Subsonic client (I tried with Dsub and with the official Subsonic client) download the covers, read the favorites, the latest additions, it does everything correctly until it is time to download the songs, which stops there, neither downloading nor, logically, reproducing anything.
I have tested from several Android devices, with different versions of the operating system and with different versions of the Dsub client.
I have also tried with a subsonic server and with it the clients do download and play the songs.
Looking at the logs, it seems that the communication is correct, it reaches a point where you can see how it tries to download but does not download, however, if you take the URL that appears in the logs and put it in a browser, it downloads the song without any problem.

Looking online, and also in this same forum, I have not found a valid answer for my problem, but I have several indications of how to try to know what is happening.

If I type in the browser https://mydomain.com/rest or https://mydomain.com/rest/ping.view I get:
`<subsonic-response status="failed" version="1.13.0">
<error code="10" message="Missing Subsonic base parameters"/>
</subsonic-response>`

My server runs on Ubuntu 18.04, with PHP7.2, Apache2, and with the rewrite, gd, etc modules enabled.
The virtual server configuration is, for port 80, to redirect to https:
```<VirtualHost *:80>

        ServerAdmin admin@domain.com
        ServerName domain.com
        ServerAlias www.domain.com
        DocumentRoot /var/www/html/ampache

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Directory /var/www/html/ampache/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        </Directory>

RewriteEngine on
RewriteCond %{SERVER_NAME} =www.domain.com [OR]
RewriteCond %{SERVER_NAME} =domain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```
And for port 443:
```<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerAdmin admin@domain.com
        ServerName domain.com
        ServerAlias www.domain.com
        DocumentRoot /var/www/html/ampache

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Directory /var/www/html/ampache/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        </Directory>

SSLCertificateFile /etc/letsencrypt/live/domain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```
As you can see, I have the Ampache server installed in the path /var/www/html/ampache.

In the /var/www/html/ampache/rest directories,
/var/www/html/ampache/play and /var/www/html/ampache/channel I have the .htaccess files with the following content:
/rest:
```<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /play/$1 [PT,L,QSA]
</IfModule>
```
/play:
```<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>
```
/channel:
```<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^([0-9]+)/(.*)$ /channel/index.php?channel=$1&target=$2 [PT,L,QSA]
</IfModule>
```
With this configuration, as I have indicated before, the server works, the Dsub client connects, it does everything except download the songs.

This is the log that is created when from Dsub you try to play a song from an album:
[logAmpache.log](https://github.com/ampache/ampache/files/5249745/logAmpache.log)

And the funny thing is this, if you copy and paste in a browser any of the download links that appear in the log, the song is downloaded without any problem:
```
2020-09-19T13:10:40+02:00 [myuser] (subsonic_api.class) -> Stream proxy: https://domain.com:443/play/index.php?ssid=1b70aa0b09a48b7285feb6e3fc0c2e78&type=song&oid=10258&uid=2&client=DSub&bitrate=256&player=api&name=S-s%20-%20O%20grileiro.mp3
```
In the Ampache configuration the use of the Subsonic backend is enabled.

Something that I can't identify was the moment it started to fail, since I had been using Dsub with Ampache for quite some time. I am not aware that it was neither an update of the Ampache nor of the Dsub.

I also put the apache logs when I try to play a song from Dsub, both from the local network and from the mobile network.
```
46.222.27.13 - myuser [19/Sep/2020:13:49:44 +0200] "GET /rest/stream.view?u=myuser&p=enc:416272332d7433206f6821&v=1.2.0&c=DSub&id=300006829&maxBitRate=128 HTTP/1.1" 200 833 "-" "DSub"
```
```
192.168.1.2 - myuser [19/Sep/2020:13:53:01 +0200] "GET /rest/scrobble.view?u=myuser&p=enc:416272332d7433206f6821&v=1.2.0&c=DSub&id=300006843&submission=false HTTP/1.1" 200 3690 "-" "DSub"
```

## Environment

* Ampache version: 4.2.2
* Web server + version: 
* Server operating system: Ubuntu 18.04
* Client operating system: Android (various versions)

### Client type

* SubSonic

**Comment by lachlan-00** [comment]
Apache should have no issues with downloading. It looks like you're all configured correctly. Is php-curl enabled?

**Comment by lachlan-00** [comment]
Apache should have no issues with downloading. It looks like you're all configured correctly. Is php-curl enabled? Can you see any errors in test.php?

The log looks like all the links are okay too.

**Comment by gbrea** [comment]
Hi. Thanks for your answer. Yes, php-curl is installed and enabled on the server.

**Comment by lachlan-00** [comment]
so if you paste the dsub link like in your example above into a browser it works?
```
/rest/stream.view?u=myuser&p=enc:416272332d7433206f6821&v=1.2.0&c=DSub&id=300006829&maxBitRate=128
```

**Comment by gbrea** [comment]
If I paste ```https://mydomain.com//rest/stream.view?u=myuser&p=enc:416272332d7433206f6821&v=1.2.0&c=DSub&id=300006829&maxBitRate=128``` in a browser I get the following:

```
UNKNOWN 400 Bad Request Server: Date: Mon, 21 Sep 2020 23:59:14 GMT Cache-Control: no-cache,no-store,max-age=0 Prama: no-cache X-Frame-Options: DENY Expires: 0 X-Content-Type-Options: nosniff X-XSS-Protection: 1; mode=block Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' Content-Language: en Content-Type: text/html Connection: close
400 Bad Request
Invalid Request 
```

The log in apache doing this is:
```192.168.1.130 - - [22/Sep/2020:00:05:55 +0200] "GET /rest/stream.view?u=myuser&p=enc:416272332d7433206f6821&v=1.2.0&c=DSub&id=300006829&maxBitRate=128 HTTP/1.1" 200 1259 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```
And the log in ampache doing this is:
```
2020-09-22T00:11:19+02:00 [ampache] (access.class) -> check_network rpc: ip matched ACL 192.168.1.130 
2020-09-22T00:11:19+02:00 [myuser] (session.class) -> Session created: 9b1e56a28098ba3ce788c888e0bdbd53 
2020-09-22T00:11:19+02:00 [myuser] (subsonic_api.class) -> Stream proxy: https://mydomain.com:443/play/index.php?ssid=9b1e56a28098ba3ce788c888e0bdbd53&type=song&oid=6829&uid=2&client=DSub&bitrate=128&player=api&name=O%20jarabanzo%20negro%20-%20Chavita.mp3 
```

**Comment by aksm** [comment]
Same issue here except on NGINX. I reverted to 4.2.1, and DSUB works fine, but as soon as I upgrade streams no longer work.

**Comment by Snamhdaen** [comment]
Can confirm. DSub connects (and browses the database w/o problems) but is unable to download/play music. I tested with 4.2.4, 4.2.1 and develop, same issue everywhere, even on 4.2.1. Webplayer works fine, running on NGINX + NGINX reverse proxy. For completeness sake: I tested a second Android-SubsonicAPI-App (Audinaut). Here even connecting was not possible. I'd very much like to make DSub work with Ampache since apart from that I'm liking Ampache very much.

**Comment by lachlan-00** [comment]
in nginx it will be your rewrite rules, there will usually be something incomplete in the translated url and NGINX is very particular with rewrites

I don't have the best knowledge of nginx but there are a few examples, check out these issues (probably #2060)
https://github.com/ampache/ampache/labels/nginx

In apache there isn't anything that's usually needed outside enabling rewrite and copying the rules. those urls look correct to me so i'm not sure it's more than a config issue. Apache/Dsub are my daily drivers so the issues usually aren't there.

**Comment by Morgan-6Freedom** [comment]
Using Ampache 4.2.5-release.
Installed with the docker image.
My DSub on android is able to connect to server.

When I try a song it says "Downloading - 0 B"

**Comment by lachlan-00** [comment]
> Using Ampache 4.2.5-release.
> Installed with the docker image.
> My DSub on android is able to connect to server.
> 
> When I try to play a song it says "Downloading - 0 B"

Nginx requires the rule config to translate the subsonic urls into ampache ones. not downloading means it didn't rewrite

Dsub request
```
/rest/stream.view?u=user&p=enc:1320781230471290834729047&v=1.2.0&c=DSub&id=300048803&maxBitRate=320
```

ampache develop rewrite result
```
/play/ssid/gw456w5gw3463gw46w34j46/type/song/oid/48806/uid/2/client/DSub/bitrate/320/cache/1/player/api/name/Opeth%20-%20Death%20Whispered%20a%20Lullaby.mp3
```

I don't use nginx due to how it handles rewriting but you can work out which rule is the missing one by which part isn't translated or which value is missing

These are generally the mandatory items needed in a play url
* **ssid** = session_id
* **type** = object_type
* **oid** = object_id
* **uid** = user_id
* **client** = client_string
* **player** = api (for subsonic)
* **name** = stream_name

**Comment by Morgan-6Freedom** [comment]
I don't think I use nginx because I installed Ampache from the docker image

**Comment by kuzi-moto** [comment]
Are you running it through a reverse proxy at all?

**Comment by Morgan-6Freedom** [comment]
@kuzi-moto I don't have a reverse proxy.

**Comment by Morgan-6Freedom** [comment]
Fix it by changing local_web_path:localhost like [here](https://github.com/ampache/ampache/issues/2395#issuecomment-638748440).

Why is it not this value by default ?

**Comment by lachlan-00** [comment]
> Fixed it by changing local_web_path:localhost like [here](https://github.com/ampache/ampache/issues/2395#issuecomment-638748440).
> 
> Why is it not this value by default ?

It's not required in the majority of cases

**Comment by mitchray** [comment]
Can be closed now I think, solution is to set ```local_web_path = "localhost"``` [as documented ](https://github.com/ampache/ampache/wiki/subsonic#set-the-local_web_path)
