### ISSUE TITLE
[Feature Request] "My Last Skip" as a search rule 

### ISSUE THREAD

**Issue by erdmax** [ampache/ampache#2544]
I would like to have the option to choose "My Last Skip" as a search/ smart playlist rule that works the same way as the "My Last Play" rule that already exists.

My use case is combining "My Last Play" and "My Last Skip" to ensure that I can restart playing the same playlist on another device or a later point in time without hearing the Songs I've recently listened to again for the predefined time span (e.g. the last day). 

Thanks,
Max

**Comment by jaddel** [comment]
+1 from me! 

Could someone make some comments on how data points (search variables) are managed in ampache and how to create them?

**Comment by lachlan-00** [comment]
> 
> 
> +1 from me!
> 
> Could someone make some comments on how data points (search variables) are managed in ampache and how to create them?

it's the same setup as advanced search in the api http://ampache.org/api/api-advanced-search

When you run a search it requires a set of prefab rules made using a minimum of three fields
* name (e.g. 'title')
* operator (e.g. 0)
* input (e.g. 'Prodigy')

Last skip isn't too difficult to add, i'll be able to basically merge it with last_play so that's easy. I really like the search ampache provides so i'll add pretty much any rule that works if requested

**Comment by jaddel** [comment]
> I really like the search ampache provides so i'll add pretty much any rule that works if requested

Thats really cool! 

Could you add the ones below as well? 

```
playPercentage[e.g. 0.75] * lastPlayed[in days]

playPercentage[e.g. 0.75] * lastSkipped[in days]

playPercentage = playCount/(playCount + skipCount)
```

**Comment by lachlan-00** [comment]
so a ratio over a time period?

**Comment by jaddel** [comment]
yes, and `playPercentage [e.g. 0.75]` and `lastPlayed/Skipped [in days]` would then be the users input variables.

Q: How often do the smart playlists update, each time a reference point from the database changes?

**Comment by lachlan-00** [comment]
each time you load them so every time you search or open the list it recalculates.

if you use the cron file the play counts are updated when that runs.

**Comment by jaddel** [comment]
Cron file? 

Would it be possible to update them every time a database reference point changes?

**Comment by lachlan-00** [comment]
the cron is actually for the interface mostly, if you aren't using that searches are performed live each time.

**Comment by mitchray** [comment]
Closing as it appears My Last Skip and Ratio have been added 👍
