### ISSUE TITLE
Audio files upload?

### ISSUE THREAD

**Issue by TBJSBigJohn** [ampache/ampache#2545]
To whom it may concern,

   I found Ampache (4.2.2-release) in the CPanel of our web host and decided to give it a try since it looks like something that could fit our need. If I understand it right, we could install it and it would allow us to let people log in and hear the audio that we provide. We installed it, giving it a sub domain at our website. It seems to install fairly easy and looks very nice. However, I am running into the problem for the last several days of trying to get the audio / catalogs figured out. I can not find in your documentation about where to upload the music on your software. I've uploaded some audio using FTP to our server to the specific folders Listed in the "Show Catalogs" section. The catalogs show up and are listed, but unfortunately it doesn't find the mp3's. I've tested with WAV audio files too. No luck!. 

    So my questions to you or anyone who can solve this are:

1) Is it possible to do what I am wanting / trying to do using audio files stored on the server at our web host?

2) Is there a specific folder / directory written in the program that these audio files need to be placed it?

3) IF there is not a specific folder / directory written in the program, the where (or how) do I manually put in the directory for the music to be seen?

4) If not mp3 or WAV files, then what audio is accepted that will be seen on this software?

5) Where can I find a detailed explanation for the steps to properly do this if no one wants to help?

FYI: if I can get this to work like I'm thinking, this will be a BIG help. Thank you in advance!

    Thank you for your time,

            John Horton

**Comment by kuzi-moto** [comment]
Hi John! Thanks for your interest in Ampache, I hope I can shed some light on your questions:

> 1. Is it possible to do what I am wanting / trying to do using audio files stored on the server at our web host?

Yes! This really is the central feature of Ampache.

> 2. Is there a specific folder / directory written in the program that these audio files need to be placed it?

No. On a clean install of Ampache, typically there are no catalogs. On creating a catalog, you specify the full path to your music directory. If there was a catalog already set up as a result of installing Ampache from your web host, then music would have to go in whatever directory they specified.

> 3. IF there is not a specific folder / directory written in the program, the where (or how) do I manually put in the directory for the music to be seen?

As mentioned in the previous response, it's filled in when initially creating a catalog.

> 4. If not mp3 or WAV files, then what audio is accepted that will be seen on this software?

I believe that most (all?) audio formats should work. At the very least mp3, wav, flac, etc.

> 5. Where can I find a detailed explanation for the steps to properly do this if no one wants to help?

The best documentation is currently in the [wiki](https://github.com/ampache/ampache/wiki).

Please let me know if anything needs clarification, or you have any additional questions and I'll be happy to assist.

**Comment by lachlan-00** [comment]
There are two ways you can create an upload catalog. either inside your existing music library or in a separate catalog.
For my server i have created a separate local catalog called upload
![image](https://user-images.githubusercontent.com/1305249/93704993-d823a880-fb5c-11ea-9b6c-50ba9e685d2d.png)

in server config -> system there is an upload setting
![image](https://user-images.githubusercontent.com/1305249/93705010-f4bfe080-fb5c-11ea-9ff7-d9366605c273.png)

You must allow user uploads and set your destination catalog for music to be uploaded.

In the upload page i have locked my server to a folder per user and you can see the server supported files list.
You can choose an artist / album manually or read from tags
![image](https://user-images.githubusercontent.com/1305249/93705043-46686b00-fb5d-11ea-9ce5-4a3da9876bb8.png)

**Comment by TBJSBigJohn** [comment]
I want to thank you both for helping me. I removed the program and made a fresh install. I am making progress with the settings suggested, but now I'm a bit more confused as to what is supposed to happen after I upload the audio file. When the audio file is uploaded (as you can see in the picture below), the name of the file turns red and then a green check mark appears. I click on that check mark and the file goes away. However, I'm still not able to see it in any of the catalogs. Also, I do not see them listed in the upload folder when I log on using FTP. At this point, I'm not sure if or where the files are being uploaded to. 

![image](https://user-images.githubusercontent.com/71574580/93723588-669c2800-fb65-11ea-9814-9171a5bc69f7.png)

**Comment by kuzi-moto** [comment]
Hmm, I've only ever uploaded files directly to the catalog path on the local filesystem and not through the interface. Have you tried creating a standard catalog to see if it is able to find files that way?

**Comment by lachlan-00** [comment]
red means it's had an error while uploading, probably permissions so you should check the log

here's a successful upload
![image](https://user-images.githubusercontent.com/1305249/93724468-b07b2180-fbea-11ea-8572-037d9923fce3.png)

**Comment by wagnered** [comment]
@TBJSBigJohn wrote:

> . I've uploaded some audio using FTP to our server to the specific folders Listed in the "Show Catalogs" section. The catalogs show up and are listed, but unfortunately it doesn't find the mp3's.

I assume they are local catalogs.  On the right side of the "Show Catalogs* section, there is a drop-down list with "add" as the default. Did you try adding the files with that?

If yes,  please enable debugging in config/ampache.cfg.php.  Hopefully it will reveal the problem.

I'd add some screenshots, but my development platform broke after trying out the new branch(source-changes).

**Comment by TBJSBigJohn** [comment]
Yes, these are "local" catalogs and "add" is set as the default. Again, I am trying to set this up on our web host server. 

I have created the folders that is recommended in the Github Wiki ("/var/log/ampache") and it still hasn't created a log as of yet. I have set read/write permissions on the folders I have created, including the "upload" folder and I can't figure this out. As you may be already able to tell, I'm not much of a code writer / programmer. I know enough to get be into trouble (obvious), so please understand when I say I appreciate your help on this.
 


![image](https://user-images.githubusercontent.com/71574580/93726296-dd8feb80-fb7a-11ea-90f0-7cc6b83d1885.png)

**Comment by kuzi-moto** [comment]
The `log_path` needs to be uncommented in addition to the `debug_level`.

**Comment by TBJSBigJohn** [comment]
Well the good news is that the log is working now. It told me "(upload.class) -> No catalog target upload configured." Although I am pretty sure I did make the catalog and set it in the server settings to send uploads to the "upload" folder / directory. 

All I did was remove the ";" before the log path, so if that is what you were referring to by "Uncommented", then I think you were right, although I was thinking "//" for some reason when you said that.

Bad news is that now there is a message at the top that says: "Warning: Unable to write to log (var/log/ampache/Log20200921.log) Please check your log_path variable in ampache.cfg.php"

AND.... now I think it has problems because my catalog won't display and my options (admin, log out, preferences, local play, and home) won't change. I've logged off and refreshed several times to see if it was in my browser cache. I used both, Mozilla and Chrome.

**Comment by wagnered** [comment]
Being on a hosted system, you probably don't have permission to write to /var/log.  I suggest you try setting the log path to your Ampache root  folder temporarily just to solve this problem.

I would like to suggest reading a Linux primer on line if you haven't already done so.  You might have to change permissions on folders/ users, etc.

Can you ssh into the server? Do you have access to the sudo command ? This elevates you to superuser or a different user.

**Comment by TBJSBigJohn** [comment]
Thank you for your help, but I have decided to just remove it. I've talked with my web hosting company (inmotion hosting) and they informed me that it would / should work. I really could use something like this program, but if it has this much problems, I ain't got the time to spend on this. I've spent a week trying to figure this out. It is working enough to let me have the log file, but there seems to be something else going on that is above my pay grade and I don't have that much time to mess with it. It's not the patience, it's the effort to make it work to do something I need that in most cases would be simpler. Don't get me wrong, I really do like this and would love to use it. I've spent too much time on it researching and trying to figure it out before finally asking for help. 

If there is a new version that comes out that doesn't require to be a programmer to use, then I'll be back. Thank you all and I hope God blesses you all!

**Comment by AshotN** [comment]
It's not about programming, it seems your issue is permissions. This is just a general OS setting, for security reasons. If you really want it to work without a care in the world, `chmod 777 -R /var/www/ampache `. Don't run that command if you care about your server security, but if you just want to make it work for testing purposes. 

Sorry if we couldn't help you through this, but it's not an Ampache issue it seems, and this is a support ticket. If you join our Telegram group chat, maybe is someone is available and able, they will help solve your issue.

I am going to close this issue, if you need further help, you can always reopen it.
