### ISSUE TITLE
Add gestures for mobile website

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2546]
The mobile website should have gestures to make he site feel more native. An [experimental change](https://github.com/ampache/ampache/pull/2549) has already been implemented, and I am unsure if this is clean enough. 

Another questions is if gestures should be enabled on desktop, there is an argument that laptops and tablets would benefit from gestures. I think a user preference would be ideal.

**Comment by mitchray** [comment]
Closing due to React client going on hiatus: https://github.com/ampache/ampache/issues/2360#issuecomment-1342288895
