### ISSUE TITLE
Transition all styles to CSS modules

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2547]
The React client originally used separate Stylus files for styling, but that's getting visibility messy and I want to avoid any future headaches. As such I am in the process of changing it all to CSS modules, still using Stylus. This does at some annoying limitations that hopefully won't hinder future developers. But overall is a needed and positive change. 

Some people argue styled components are superior, but I think having to know React styled components adds an extra hurdle for developers. For now CSS modules is the solution, but I am naturally open to discussion.

**Comment by mitchray** [comment]
Closing due to React client going on hiatus: https://github.com/ampache/ampache/issues/2360#issuecomment-1342288895
