### ISSUE TITLE
Unable to install on Raspbian (Raspi OS) due to unmet dependencies / held packages

### ISSUE THREAD

**Issue by leopheard** [ampache/ampache#2548]
I'm trying to install Ampache on Raspbian but am having the following issues - you mentioned on Twitter that Oracle isn't the best method - what could you recommend please? (I'm basically trying to download my Google Music database onto a NAS (as they're moving to a really bad new service) and use Ampache for streaming as the Android app seems very similar to the GMusic layout):

    pi@pihole:~ $ sudo apt-get install ampache
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     ampache : Depends: ampache-common (>= 3.6-rzb2704+dfsg-3) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

When I try and install the above mentioned application:

    The following packages have unmet dependencies:
     ampache-common : Depends: libphp-phpmailer (< 5.2.14+dfsg.0~) but 6.0.6-0.1 is to be installed
                      Depends: php-getid3 (< 1.9.12+dfsg.0~) but 1.9.17+dfsg-1 is to be installed
                      Depends: php-gettext (< 1.0.11.0~) but 1.0.12-0.1 is to be installed
    E: Unable to correct problems, you have held broken packages.

The strange thing is, the versions it wants to install are already installed? Or is this telling me the above three apps are all too new? Any advice would be appreciated.

    pi@pihole:~ $ sudo apt-get install php-gettext
    php-gettext is already the newest version (1.0.12-0.1).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    pi@pihole:~ $ sudo apt-get install php-getid3
    php-getid3 is already the newest version (1.9.17+dfsg-1).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Outputs: 

    $ cat /etc/apt/sources.list
    deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi 
    # Uncomment line below then 'apt-get update' to enable 'apt-get source'
    # deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi  

    $ cat /etc/apt/sources.list.d/raspi.list
    deb http://archive.raspberrypi.org/debian/ buster main 
    # Uncomment line below then 'apt-get update' to enable 'apt-get source'
    # deb-src http://archive.raspberrypi.org/debian/ buster main  

    $ ls /etc/apt/sources.list.d/
    raspi.list

**Comment by AshotN** [comment]
I wouldn't install from a package manager, Debian has dropped Ampache from their repo's due to no one maintaining the package. You should just pull from this Git repo.

**Comment by lachlan-00** [comment]
Definitely don't use those packages. Debian was about 4 years behinds us after the last package update

**Comment by lachlan-00** [comment]
For a pi (which will be Ampache specific?)

Install Apache and then install Ampache into /var/www/html/ which is the default directory.

Follow the wiki and clone master from git. I think I should write up a gist or something that will give the steps to do this on Raspbian

**Comment by leopheard** [comment]
@lachlan-00 That would be appreciated. I have installed it via the following as per the wiki, but I'm not sure where to go after here:
```
cd /var/tmp
wget https://github.com/ampache/ampache/archive/master.tar.gz
tar -xvzf master.tar.gz
mv master /var/www/html/ampache
```
If I go to https://localhost/ampache it provides a strange pihole page, I'm assuming because there's already a webserver in one of the /var/www/html folders for the pihole service running. I have apache installed properly it seems as the holding page comes up when I type the IP of the Raspberry Pi. Any help would be appreciated, as the guide on here assumes a certain level of knowledge of Apache/Ampache already

**Comment by kuzi-moto** [comment]
> Any help would be appreciated, as the guide on here assumes a certain level of knowledge of Apache/Ampache already

It shouldn't require much knowledge really. It's a bit more involved than a standard executable program, but it's mostly copying files to a directory.

Sounds like you are already running pi-hole on there, which is using its own webserver (lightppd) to serve the web interface. This is going to complicate your setup a bit.

The easiest thing would be to change the lightppd port to something other than 80 (instructions here)[https://jdsworld.com/tech-support/pi-hole-dns-change-default-web-port/]. Then, Ampache should work using the URL you tried before.

**Comment by leopheard** [comment]
Thanks, I might give that a try or failing that might use a spare RPi2 I have incase it screws up my network as the Pihole is obviously critical to that

**Comment by leopheard** [comment]
@kuzi-moto Thanks, I might give that a try or failing that might use a spare RPi2 I have incase it screws up my network as the Pihole is obviously critical to that

**Comment by lachlan-00** [comment]
https://www.howtoforge.com/how-to-install-the-ampache-music-streaming-server-on-ubuntu-2004/

I just found this recently, raspbian is just repackaged arm, debian so this might help make things clearer.

**Comment by leopheard** [comment]
> The easiest thing would be to change the lightppd port to something other than 80 [instructions here](https://jdsworld.com/tech-support/pi-hole-dns-change-default-web-port/). Then, Ampache should work using the URL you tried before.

So I tried the above as suggested, but it just moved the default Apache page to the new port and the pi-hole is still there at the normal local IP address?

```
Either way, if I go to http://192.168.1.101/ampache/install.php it tells me: 
Error
The following error has occurred, you will be automatically redirected in 10 seconds.
Error Messages:
Unable to connect to the database, check your Ampache config
```

And then after a few seconds it goes to http://192.168.1.101/ampache/login.php where I can't login to it. It sounds like there's a different issue?

**Comment by kuzi-moto** [comment]
> And then after a few seconds it goes to http://192.168.1.101/ampache/login.php where I can't login to it. It sounds like there's a different issue?

Seems like Ampache thinks that a configuration file already exists, and is trying to use it to connect to the database. Does a configuration file exist at `config/ampache.cfg.php`? If so you could probably delete it and try again.

**Comment by leopheard** [comment]
> Seems like Ampache thinks that a configuration file already exists, and is trying to use it to connect to the database. Does a configuration file exist at `config/ampache.cfg.php`? If so you could probably delete it and try again.

So I started again and the Ampache fresh install webpage comes up under the above link. In the testing page, it says 
`"ampache.cfg.php" is writable. This tests whether PHP can write to config. This is not strictly necessary, but will help streamline the installation process.`

So under /var/www/html/ampache/config there are 3 files:
```
.htaccess
ampache.cfg.php.dist
registration_agreement.php.dist
```
I have copied the middle one into just ampache.cfg.php and it goes back to this original error of unable to connect to the DB.

**Comment by leopheard** [comment]
Ah, just worked out what it was. I did sudo chmod 777 /var/www/html/ampache to that folder to fix the permissions issue.

But on the create DB/user, etc page it also has permission issues:
`Unable to connect to the database: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)`

**Comment by leopheard** [comment]
This can be closed
