### ISSUE TITLE
Subsonic Api Song Id Format

### ISSUE THREAD

**Issue by WisdomCode** [ampache/ampache#2553]
## Description

**Describe the bug**
I was trying to use the [sublime music player](https://gitlab.com/sublime-music/sublime-music) for linux, which in turn is using the subsonic API. There were many errors, primarily because of some wrong variable types. It was solved by converting the incoming ids to strings (from int). This should not be necessary because the subsonic standard sends a string in that case.
The issue on the sublime side can be found here:
https://gitlab.com/sublime-music/sublime-music/-/issues/265

**To reproduce**
1. Create Flatpak from latest master (or use the latest version from the releases tab, but not the old flatpak, which does not support the newer subsonic supported by ampache)
2. Open it, connect to your ampache instance (4.2.2 in my case)
3. open an album by clicking on it, the more songs in it, the likelier the error
4. the command line will spit out an error, the program will not show any songs and simply load spin to infinity.

**Expected behavior**
Songs should appear

## Environment

* Ampache version: 4.2.2
* Client operating system: Sublime-linux, latest master, flatpak

**Client type:**

* SubSonic

**Comment by lachlan-00** [comment]
what's the call you're getting an int in?

I just did a quick find on 'id' and they're all cast as string with ```(string)``` from what i can see.

**Comment by lachlan-00** [comment]
oh and is this in xml or json?

**Comment by lachlan-00** [comment]
json
![image](https://user-images.githubusercontent.com/1305249/94205119-e92a3c00-ff05-11ea-92a7-a39f9e629cf5.png)

**Comment by lachlan-00** [comment]
here it is with JSON_NUMERIC_CHECK
```
json_encode(self::xml2json($xml, $conf), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_NUMERIC_CHECK);
```

**Comment by WisdomCode** [comment]
I can try to track it down, but this seems to be already a working example for the int
The id is given back as an integer (in this example 300952623 for the song and 200087784), but those should be strings. 
from a quick look into its code and this issue https://gitlab.com/sublime-music/sublime-music/-/issues/112 it can be safe to say that we are talking about a json request.

**Comment by WisdomCode** [comment]
The details are stated here
http://subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.13.0.xsd
the ids are string always, except of the directories

**Comment by lachlan-00** [comment]
the json numeric change fixes it, is 1.15 the minimum version though? installing in debian i had to just alter the version string to get access

**Comment by lachlan-00** [comment]
ah, i see it's 1.8.0 plus so i'll check why it's rejecting me on my server and then this is done

**Comment by WisdomCode** [comment]
Sorry but I don't get what you are referring to
If you are trying to install the flatpak, keep in mind that the old one in the releases is relatively aged and will not work, you have to build it from the source
however, the current source already contains a fix for this problem, however, as this is a standardization problem it seems reasonable to solve this on the server side as well. If you want to build a non-working version, revert the changes in this merge:
https://gitlab.com/sublime-music/sublime-music/-/merge_requests/52
dont worry, its just 6 lines. If this proves problematic and you need the flatpak I could build it for you.

**Comment by lachlan-00** [comment]
okay, the package i was using from debian was really old and i see that the bug was fixed for version in v0.11.1.

I can use sublime-music on develop now with no issue and will be updating ampache to 4.2.3 next week to allow this.

I'll also be updating git if you use the master git branch

**Comment by WisdomCode** [comment]
Perfect, thank you for your quick reaction!

**Comment by lachlan-00** [comment]
i've never used it before but sublime music is pretty slick

**Comment by sumnerevans** [comment]
@lachlan-00 @WisdomCode (maintainer of Sublime Music here) wow, thanks for jumping on this so quickly! Please let me know if there's anything else I can do to assist.

**Comment by lachlan-00** [comment]
If you find any more issues just let me know in another issue.
Love the app!
