### ISSUE TITLE
Commit 6ed2d3 can't auto-update

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2556]
### Describe the bug
Because composer.lock changed so much, git won't automatically overwrite the file, so it has to be deleted manually before installation.

### To reproduce
I upgraded from commit 66f06d and whenever I pushed the Update button, the screen would flash, then would remain exactly as before. 

Manually running git update pointed the finger at composer.lock. I deleted it, and the pull worked perfectly. Composer also updated two files.

**Comment by lachlan-00** [comment]
The lock file gets updated sometimes. You should use composer install instead of composer update to avoid this

**Comment by lachlan-00** [comment]
just keep using composer update as i'll run an install towards release time to ensure packages are all working.
