### ISSUE TITLE
Reaction for missing Cover Art Subsonic API

### ISSUE THREAD

**Issue by WisdomCode** [ampache/ampache#2557]
# Issue Template

## Description

**Describe the bug**
When requesting an Album Cover via the subsonic API from sublime for albums that don't have one, the returned message is a 200, but an empty answer. This confuses the client, which expects there to be an error (like 404). Otherwise, this results in errors and infintie spinning. Also, although not sure, I think its responsible for a shifiting of the data, but thats not exactly the point here.

**To reproduce**
1. Request: https://DOMAIN/rest/getCoverArt.view?id=al-200001653&size=300&u=USER&p=PASSWORD&c=Sublime+Music&f=json&v=1.13.0

**Expected behavior**
Get an error/default image

## Environment

* Ampache version: 4.2.2
* Client operating system: Sublime music latest master

**Client type:**

* SubSonic 1.13.

**Comment by sumnerevans** [comment]
I tried this in Airsonic, and that implementation returns a JSON object when the album cover art is not found. Here's an example:

```
{
   "subsonic-response" : {
      "status" : "failed",
      "version" : "1.15.0",
      "error" : {
         "code" : 0,
         "message" : "For input string: \"123123123123\""
      }
   }
}
```

**Comment by wagnered** [comment]
Actually, according to the [Subsonic api](http://subsonic.org/pages/api.jsp) docs, the data not found error should be 70, error 0 is a generic error.

@WisdomCode, 100, 200 400 etc are http server codes, not application error codes .  There might be an error, but sublime is not returning the correct error code.

**Comment by sumnerevans** [comment]
@wagnered (maintainer of Sublime Music here). I agree, this should return an error JSON with error code 70. However, what @WisdomCode and I seem to be observing is that no data is returned by Ampache in this case (not even error JSON).

**Comment by wagnered** [comment]
Well that sort of confounds the issue.   @WisdomCode indicated an empty response with xml. Does that mean no error response?  

In my mind, both Ampache and Sublime have an xml problem.  The json side seems to be working correctly, because of an actual error being reported back to the client.  Your xml logic shouldn't just blindly forward all responses, but check for wierd responses from upstream And let the client know about the problem.  That is what the json logic appears to do.

@lachlan-00 has been working on both the json and xml api, but I'm not sure if the work is for the Ampache  or the Subsonic api.

**Comment by lachlan-00** [comment]
is this from getCoverArt requests?

What it should be doing (at least in my opinion) is returning the blank art pngs we have instead.

I'll check this out and see what my server responds with. The Ampache subsonic api converts xml to json so it's possibly an error in that conversion.

**Comment by lachlan-00** [comment]
off my phone and i see it's with getcoverart, i'll check out what we can do but i like falling back to something

**Comment by lachlan-00** [comment]
return an error now in 901a8a3aa

```
{ "subsonic-response": { "status": "failed", "version": "1.13.0", "error": { "code": "70", "message": "Media not found." } } }
```

**Comment by sumnerevans** [comment]
@lachlan-00 thanks for looking into this!

> In my mind, both Ampache and Sublime have an xml problem.

@wagnered Sublime Music doesn't use the XML API, so I don't think that it's on my side.

Let me know if you need any more help getting this across the line.

**Comment by wagnered** [comment]
Ok, my bad.    I was thinking Airsonic is a client.

**Comment by lachlan-00** [comment]
There are probably more places that need error messages. I think our implementation is pretty slim on errors.

Ill do some more testing today but now there are two new 70 errors.

* Object type not found
* Media exists but art not found

The process should fail on any object without art now.

**Comment by lachlan-00** [comment]
> @lachlan-00 thanks for looking into this!
> 
> > In my mind, both Ampache and Sublime have an xml problem.
> 
> @wagnered Sublime Music doesn't use the XML API, so I don't think that it's on my side.
> 
> Let me know if you need any more help getting this across the line.

For the xml part. Ampache does everytjing in subsonic using xml then converts it to json. This is where most of the content/response issues will come from.

Besides ultrasonic its good to have another json client to test with.

**Comment by lachlan-00** [comment]
there is an issue where errors are not being printed using xml but print okay in json.
(no idea why because the methods that work/don't work in xml aren't doing anything differently)

But that doesn't affect this, i don't really think anything should be stopping this closing now as errors will occur now in json when not found

**Comment by WisdomCode** [comment]
Thanks again for resolving all of this so quickly!
I will test it 4.2.3 as soon as its out. and elaborate whether it resolves the issue on the client.

**Comment by mitchray** [comment]
@WisdomCode Was this resolved for you?

**Comment by WisdomCode** [comment]
Sorry for not replying. I didn't use the Client due to this error:

**Comment by mitchray** [comment]
Excellent!
