### ISSUE TITLE
Managing Album database

### ISSUE THREAD

**Issue by SweetthD3ViL** [ampache/ampache#2561]
Hello all,

New user there and very impressed so far, I have managed to import all my database, however, I realised a couple of albums were missed tags, I amended the tags using kid3. 

I tried to update the catalogue but that did not pick up the tags changes, I tried to use the "Update existing files in:" inserting the file path but I am getting the following error: "ERROR: This subdirectory is not inside an existing Catalogue. The update can not be processed." And yes I am certain of the file path.

Is there a way to force an update for a specific album, or to remove it and then rescan the library that will pick it up?

**Comment by lachlan-00** [comment]
there are a few ways

update from tags in the album/artist pages
![image](https://user-images.githubusercontent.com/1305249/94972619-0934ad80-054d-11eb-99f0-6d270e15fa12.png)

or run a verify on the catalog using the cli
```
php /var/www/html/bin/catalog_update.inc -v
```

**Comment by lachlan-00** [comment]
i've tested again in that page and it works with the full path
![image](https://user-images.githubusercontent.com/1305249/100303188-b2e16980-2fe7-11eb-8957-fd0bdd5bdfa2.png)
