### ISSUE TITLE
Show_get_art cancel button broken.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2567]
The message:
>  The requested resource /http://127.0.0.1:4000/albums.php?action=show&album=3 was not found on this server.

The leading forward slash(/) appears to originate from commit faef956145ebea75225c04d25736fb8dab115736.

At this point, `AmpConfig::get('web_path')` should be empty, but it's not: it **is** commented out in my config file.  `cancelurl` ends up being: `http://127.0.0.1:4000/http://127.0.0.1:4000/albums.php?action=show&album=3`

Seems that if `AmpConfig::get('web_path')` was empty, there'd be a problem

I wonder if it's php 7.4 causing it.  I've noticed a few code changes required.

Just thought I'd get this on record for posterity's sale.

**Comment by wagnered** [comment]
I replaced the forward slash with the question mark.  The cancel button seems to be working, but the url looks weird in the address bar and I'm not sure why it's working.  I'll have to check it out with php7.3.

**Comment by lachlan-00** [comment]
the cancel button in the search page?
![image](https://user-images.githubusercontent.com/1305249/95062867-e539bd80-0740-11eb-9a7a-df2f92484d03.png)

**Comment by wagnered** [comment]
yes.

 I have to fix my php7.3 installation before I can test my fix with it.

Also, at the location which creates the cancel button,  I want to find out why AmpConfig::get('web_path') is not empty when it's commented out in my config file.  This implies that `AmpConfig::get('web_path') == '')` can never be true.
```
<?php $cancelurl = ((string) AmpConfig::get('web_path') == '') ? $burl : (Am  pConfig::get('web_path') . '/' . $burl); ?  >
```

**Comment by lachlan-00** [comment]
it's cast to string so a null will become ''

i don't see why it would want a question mark though? the web_path is for a subfolder so it isn't adding an argument on the end of the url. it's just adding the original url to the webpath if it's cancelled.

**Comment by wagnered** [comment]
> it's cast to string so a null will become ''

I understand that, but, I'm curious,  under what circumstances could AmpConfig::get('web_path'). be null?  even with it commented out in my config file, it's not. so the concantenation of the two with '/' becomes an ill formed URL. My guess is that window.location.href tried to parse it but evidently can't.  The '?' makes the url, plus query string (burl) well formed.  Evidently window.location knows how to parse it.  Check the [URI generic syntax guide RFC 2396](https://www.ietf.org/rfc/rfc2396.txt) at ietf.org.

**Comment by wagnered** [comment]
It's still not working quite right.  After cancelling the dialog the address bar shows `http://127.0.0.1:4000/?http://127.0.0.1:4000/albums.php?action=show&album=3` and displays the login landing page with "Albums of the Moment" displayed. So although the URL is well formed, it's not doing what I (incorrectly) expected.  I'll take a look at it to see how the $cancelurl statement can be reworked.

**Comment by wagnered** [comment]
> the web_path is for a subfolder so it isn't adding an argument on the end of the url. it's just adding the original url to the webpath if it's cancelled.

First, I don't understand what you are trying to accomplish: subfolder?

Second, there is a following `function getCurrentPage(url)` which I'm sure is superceding the one that was created to accomplish what you described. 

I'm going to try commenting out the second getCurrentPage function and see what happens.

**Comment by wagnered** [comment]
> the web_path is for a subfolder so it isn't adding an argument on the end of the url. it's just adding the original url to the webpath if it's cancelled.

First, I don't understand what you are trying to accomplish: subfolder?  It looks like $burl is full path to redisplay show_album,inc.php.  it just needs to be assigned to `location.href`, or better yet, `location.replace` because the history for the get_art dialog doesn't need to be saved.

Second, there is a following `function getCurrentPage(url)` which I'm sure is superceding the one that was created to accomplish what you described. 

I'm going to try commenting out the second getCurrentPage function and see what happens

Didn't work.

I discovered that `web_path` is set in init.lib.php using $_SERVER and/or $_GET strings so it being empty would be a rare and unusual occurrence.

This is fun.

**Comment by rsinfotech** [comment]
I've noticed a few strange behaviours in the web interface since this commit. fb91cf48c

It seems that when listening to tracks via the web player, clicking on the links to artist/album/song etc. in the web player pops up the leave page warning and if ok'd, kills the web player and currently playing track. This didn't happen previously, the pages requested were displayed without losing the currently playing tracks.

Also, I seem to be getting redirected to various random pages when clicking the cancel art search button or sometimes just not responding at all?

One last anomaly I've noticed is that after adding new album or artist art, the URL displayed in the address bar is sometimes huge, it seems to be appended with a long random string of characters. The pages selected are correct but the long string remains in the address bar. The only way to get rid of it is to manually delete the string so that it is just referring to the #index.php again?

Reverting to the earlier commit 4af46ce8e seems to return the expected behaviour of everything.

**Comment by wagnered** [comment]
@rsinfotech  I'll take a closer look, but on an earlier examination, it didn't look like the player used that altered code.

Thanks

**Comment by wagnered** [comment]
> One last anomaly I've noticed is that after adding new album or artist art, the URL displayed in the address bar is sometimes huge, it seems to be appended with a long random string of characters. 

I believe that's a base64 encoded URL.  It's attached as a query so it should be ignored by further calls.  As that URL carries no data, it is not necessary that it is encoded. Granted that it shouldn't be in the displayed URL string.

> It seems that when listening to tracks via the web player, clicking on the links to artist/album/song etc. in the web player pops up the leave page warning and if ok'd, kills the web player and currently playing track.

How does one display those links in the player?  I checked out 4af46ce8eab19d5a809d6ec4171f8f1542ac8d4d and see only the player's playlist and cover art.

**Comment by rsinfotech** [comment]
Hi @wagnered, I think this is the HTML5 webplayer and any of the text relating to the artist/album/track/lyrics etc. on the left are links that take you to the relevant page:

![image](https://user-images.githubusercontent.com/3216809/96003259-f619bb80-0e31-11eb-9fb6-b57b7fe1de37.png)

These all used to work in the background and leave the webplayer playing along happily. They all now seem to trigger the leave page popup dialogue and if you click on leave page, the webplayer and currently playing track are killed:

![image](https://user-images.githubusercontent.com/3216809/96003711-6f191300-0e32-11eb-9a9b-9afed5be33db.png)

Hope this helps? Let me know if you need any further info. Thanks.

**Comment by wagnered** [comment]
Yes, indirectly.  You gave no settings so I decided to switch from Chrome to Firefox for Android and I saw what your image displays.

Strange because JavaScript was supposedly enabled in Chrome.  All the Android browser apps leave much to be desired.

Thanks

**Comment by wagnered** [comment]
In case you don't get notices of PRs the patch can be found at:

Patch Links:
https://github.com/ampache/ampache/pull/2581.patch
https://github.com/ampache/ampache/pull/2581.diff

I'd appreciate it if you could give it a try.

**Comment by lachlan-00** [comment]
@wagnered i tested before and after your pull this morning and you've fixed that up now. 👍

**Comment by rsinfotech** [comment]
Perfect! Links in webplayer now working again as expected.

Great work as always @wagnered and @lachlan-00, much appreciated.

**Comment by lachlan-00** [comment]
This is resolved now too, i do need to put the changelog in to say that art isn't auto started but that's fine
