### ISSUE TITLE
Creating an online audiobook platform

### ISSUE THREAD

**Issue by galikpali** [ampache/ampache#2572]
Hi!

My goal is to create a web-based platform where users can listen to audiobooks.
The idea would be that this online platform would communicate with a self-hosted Ampache via REST API.

The following requirements must be met for this online platform:
- authorized audio plays for audiobooks
- non-authorized preview plays for audiobooks
- disallow file downloads (basically the files can only be downloaded in chunks from the server)
- logging of that how much time a client listened to an audio file (in second precision)
- speed rate 2x, 4x

I'm totally new to Ampache and I was wondering that can I implement these functionalities as a plugin or any other way to Ampache?

**Comment by lachlan-00** [comment]
the only thing you can't really do is configure previews and the playback speed. (at least from the web side.)

limiting length might be possible with ffmpeg commands? bbut i'm not sure off the top of my head.

One of the todo features is to create a catalog for audiobooks based on the podcast views that would make the chapters a lot easier to manage/view compared to the music pages.

**Comment by mitchray** [comment]
Closing stale issue
