### ISSUE TITLE
is there a need for mbid in artist art search?

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2576]
hey @wagnered when you did the spotify search does it require a mbid somewhere in the gather or can i remove that requirement from the art page?
![image](https://user-images.githubusercontent.com/1305249/95799258-7c9da280-0d37-11eb-8ff0-3340791eb0fa.png)

**Comment by wagnered** [comment]
No but If you look at `gather_musicbrainz($limit, $data)`, you'll see that it does.  It enables a manual look up of the mbid on the mb website and entered to do a manual search instead of using Picard.

**Comment by wagnered** [comment]
But...  It could be hidden if MB isn't in the `art order` list.

**Comment by wagnered** [comment]
Oh, just looked closer at the image, you are referring to the artist MBIDs.  Yes, that can be removed.  Only album MBIDs are accepted and required  in the gather_musicbrainz logic.

**Comment by stebe** [comment]
If there isn't any MBID then searching Musicbrainz could be skipped and at least show art from other sources rather than making it a required field. In my config I have the following,

  `db,tags,folder,musicbrainz,TheAudioDb,Discogs,lastfm,spotify`

If I put new art in the song tags or folder or want to put in a direct url and have Musicbrainz enabled I'll not be able to retrieve the new art if there is no MBID.

**Comment by wagnered** [comment]
First, it's not obvious, but this issue is about artist art and I've yet to find any database that provides artist images other than Spotify. If you know of any let me know.

> If I put new art in the song tags or folder or want to put in a direct url and have Musicbrainz enabled I'll not be able to retrieve the new art if there is no MBID.

You're right.  It's a bug. For the record, could you add a new [bug] issue.

Thanks,

**Comment by wagnered** [comment]
Also the release group mbid should be removed from the cover art search.

**Comment by stebe** [comment]
I just created a new issue #2578 specific for album art.

**Comment by wagnered** [comment]
And the question about the release group mbid begs the question: Only the album mbid is used for anything in ampache, why are the others being stored? Are they necessary for anything?

If they really aren't used I'd prefer to not import them than filter them out of the Artist or Album formatting procedures before passing the data to show_get_art dialog.

**Comment by lachlan-00** [comment]
> And the question about the release group mbid begs the question: Only the album mbid is used for anything in ampache, why are the others being stored? Are they necessary for anything?

MBID's are used to allow separation of duplicate strings. So if you have two artists with the same name but different MBID we know they aren't the same artist.

Definitely shouldn't remove them from the database but good to know the restriction can come off

**Comment by wagnered** [comment]
> So if you have two artists with the same name but different MBID we know they aren't the same artist.

Question: What if one or both do not have an MBID?  How is that handled?

I was thinking that Spotify, the only database providing artist info, IDs all artists, perhaps Spotify IDs could be used in lieu of MBIDs.

**Comment by lachlan-00** [comment]
> > So if you have two artists with the same name but different MBID we know they aren't the same artist.
> 
> Question: What if one or both do not have an MBID? How is that handled?

if you have no MBID there isn't any way to detect different artists when there is no extra field.

The Artist::check code will also do different things for a mismatch like this:
Artist1 - mbid-10190-0202-etc
Artist1 - 

the second artist has no mbid but artist::check will then assume that your artist is the first row. if we added another tag like spotify into the mix then that would add another identifier for us to check against. I've been using discogs for genre identification and they also have id's for artists/releases

> 
> I was thinking that Spotify, the only database providing artist info, IDs all artists, perhaps Spotify IDs could be used in lieu of MBIDs.

It would always be good to have an identifier like spotify or musicbrainz. MBID is the 'standard' probably due to picard being integrated into a lot of taggers.

**Comment by wagnered** [comment]
My bad.  I forgot about discogs. But the Spotify IDs could be gathered when gathering artist art.  

Getting back to the topic. 

Ok, I'll just prevent them from being displayed on the show_get_art dialog.

**Comment by lachlan-00** [comment]
all done in a recent pull by you so resolved
