### ISSUE TITLE
Remove defunct LyricWiki plugin

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2577]
Hi Devs,

Just noticed that the LyricWiki plugin seems to have stopped working and is reporting the following runtime errors in the logs when trying to view the lyrics for any song:

`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`
`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string(): &lt;!doctype html&gt; in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`
`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string():  ^ in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`
`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string(): Entity: line 1: parser error : Extra content at the end of the document in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`
`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string(): &lt;!doctype html&gt; in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`
`[ampache] (log.lib) -> [Runtime Error] simplexml_load_string():  ^ in file /var/www/html/ampache/modules/plugins/LyricWiki/LyricWiki.plugin.php(87)`

The response on the Song Lyrics page just shows 'No lyrics found'

**Comment by stebe** [comment]
Does LyricWiki still exists.  I tried url on line 85 of the plugin `$uri     = 'http://lyrics.wikia.com/api.php?action=lyrics&artist=' . url  `or http://lyrics.wikia.com, I get the redirect below.

https://community.fandom.com/wiki/Community_Central:Not_a_valid_community?from=lyrics.wikia.com

**Comment by stebe** [comment]
Found this in Wikipedia:

> Edit lock and closure
> 
> On April 2, 2019, LyricWiki was closed to editing by Fandom for repeated violations of the site's terms of service. The reasoning for this was that Fandom did not approve of images and lyrics that are "overly" sexual and/or shock people, aiming to be a "family friendly site".[23] The site was later shut down completely on September 21, 2020, now redirected into community.fandom.com and data dump is not generated.[24]

**Comment by rsinfotech** [comment]
Ok, thanks @stebe for looking into this, I just remembered it working not long ago but upon trying it again today, getting the No lyrics found message and the errors in the log.

So I suppose this is now a defunct plugin? I'll disable it from the plugin management page and close this issue.

It's a shame as it was quite a nice feature but 3rd party websites closing down is beyond the scope of anyone here.

Thanks again @stebe for your rapid response.

**Comment by stebe** [comment]
The chartlyrics plugin still works.

**Comment by rsinfotech** [comment]
Fantastic! I disabled the LyricWiki plugin, enabled the ChartLyric plugin and lyrics are back and errors are gone.

Many thanks.

**Comment by lachlan-00** [comment]
i'll remove the plugin so we stop pinging a dead site

**Comment by stebe** [comment]
Wonder if we should find a replacement such as Musixmatch? https://developer.musixmatch.com/

**Comment by lachlan-00** [comment]
it would be good to try and replace it instead of just dropping it
