### ISSUE TITLE
Cannot retrieve album art without MBID

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2578]
### Describe the bug

If I want to update art for an albummbut the album doesn't have an MBID, the get art button will not work and I'm prompted to enter the MBID.  For example if I updated art in an album folder or song tags.

### To reproduce

1. Go to any album
2. Click on the gear on the album cover
3. If no MBID is displayed clicking on get art prompts for MBID

### Expected behavior

A search for album art performed from all other sources if no MBID is available.

### Screenshots

![image](https://user-images.githubusercontent.com/4076671/95875618-33058580-0d40-11eb-984f-d87f66866f0a.png)

## Environment

* Ampache version: f74e6ef48aec752780bd9803b800d50c010db911

### Client type

* Web
* Ampache

## Settings

; Art Gather Order
; Simply arrange the following in the order you would like
; Ampache to search. If you want to disable one of the search
; methods simply leave it out. DB should be left as the first
; method unless you want it to overwrite what's already in the
; database
; POSSIBLE VALUES (builtins): db tags folder lastfm musicbrainz google
; POSSIBLE VALUES (plugins): Amazon,TheAudioDb,Tmdb,Omdb,Flickr
; DEFAULT: db,tags,folder,spotify,musicbrainz,lastfm,google
art_order = "db,tags,folder,musicbrainz,TheAudioDb,Discogs,lastfm,spotify"

**Comment by lachlan-00** [comment]
fixed by @wagnered
