### ISSUE TITLE
[Feature Request] Changing login screen background

### ISSUE THREAD

**Issue by agopo** [ampache/ampache#2582]
## Describe what you don't like about Ampache, or what it is missing
I'd like to be able to change the login screen background without having to tamper with the main theme.

## Describe how you would like the feature to work**
Login as admin -> Settings -> User Interface -> User defined URL Loginpage Background (Enter URL or path/to/file.png here)
Logout
Have new background on Loginpage

**Comment by lachlan-00** [comment]
that is a prretty good idea, just needs a database preference and the ability to insert it into the images table probably

**Comment by theTendo** [comment]
I've done some work related to this in commit [dad74f1](https://github.com/theTendo/ampache/commit/dad74f17efc677fce025fc7b391c78dec2ece712):

![commit_dad74f1_1](https://user-images.githubusercontent.com/2078392/102138482-b0db2f80-3e5c-11eb-916f-f1796d0cd311.png)

![commit_dad74f1_2](https://user-images.githubusercontent.com/2078392/102138500-bafd2e00-3e5c-11eb-9ee3-434a0335891e.jpg)

I do have some doubts regarding the preference's id attribute. If the update is applied via `update.class.php` this preference setting is assigned id 172, but apparently this id is already used by "Database preference table", so I don't know if there could be an overlap problem with that.

I haven't done any kind of test apart from the fact that the background is shown correctly, so any testing suggestion is welcomed.

**Comment by lachlan-00** [comment]
You couldn't have picked a nicer background for it!

If you make a pull I can clean it up and put it in tomorrow

**Comment by theTendo** [comment]
PR created :)

**Comment by lachlan-00** [comment]
Cool, I'll do it first up tomorrow.

**Comment by agopo** [comment]
Hey,
I honestly didn't expect this to be implemented so quickly (if at all). Thanks a lot for your work, I'm looking forward to it!
Cheersagopo

    Am Dienstag, 15. Dezember 2020, 09:32:05 MEZ hat lachlan <notifications@github.com> Folgendes geschrieben:  
 
 


Cool, I'll do it first up tomorrow.

**Comment by lachlan-00** [comment]
okay, it looks good, i didn't really change anything just took things out not needed.

this preference will be a system pref as when you go to the login page you don't have a user set.
Things like translations get handled out of regular changes and it doesn't need to be inserted for users to change.

I'll be merging in a few minutes after all the travis checks go through.

**Comment by lachlan-00** [comment]
9546c80a7 now has a custom login background setting!

this actually made me realise there are preferences a user can make which aren't actually usable and will have no effect when set.

you can set a login page logo as a user but you'll never see that because you have no user when logging on.

Thanks for making the change and giving me more to work on. :)

**Comment by theTendo** [comment]
This is the first FOSS project I contribute to and thanks to your guidance I already have two accepted pull requests :)

You are the best lachlan! Thanks for all the work that goes into Ampache!

**Comment by lachlan-00** [comment]
@agopo i'll close this as suggested, it's a nice extra and actually makes the login page branding and other options available without a big effort.

I'll remove the system prefs from users separately.

@theTendo i'm glad to help. Free software isn't a one person job and i will always remember when i made my first contributions. I hope you have the time to make more (not just to Ampache!)
