### ISSUE TITLE
Fatal Error while install

### ISSUE THREAD

**Issue by 13sec** [ampache/ampache#2584]
Fatal error: Call to undefined function T_() in /public_html/music/lib/init-tiny.php on line 27

received this while attempting install fresh instance PHP version: 7.3.6

**Comment by lachlan-00** [comment]
sound like you haven't installed the composer requirements

**Comment by 13sec** [comment]
I was under the understanding that if you download ampache-x.x.x_all.zip if you couldn't use composer? Line 27 appears to deal with PHP so now I am a bit more confused.

**Comment by kuzi-moto** [comment]
Do you have all the required PHP extensions?

**Comment by wagnered** [comment]
@13sec we really need a big more info: what web server are you using?

Two things I infer:
1. PHP7.3 may be installed, but isn't active. If you execute `php  -v` from a command line interface,  it will verify the version.  Depending on the installed web browser, both `php-fpm` and `php-cgi` should also be checked.  Debian based systems(Ubuntu) have the `update-alternatives` command and RH based systems have `alternatives` command.

2. File i18n.php  hasn't been loaded when line 27 is executed thus the "Call to undefined function T_()" error.

**Comment by usox** [comment]
I second @wagnered. It looks like the used php version (by the webserver) is below the minimal required version - so the php version check in init-tiny fails.
But this check tries to translate its error message using `T_` which is not initialized in this early time of request processing. I think, we simply should remove the translation in this line.

**Comment by wagnered** [comment]
I don't see a problem of requiring lib/i18n.php before the php version test. I18n.php doesn't require preloaded files,  Is there a problem I don't see?  To be consistent with previous versions and  the spirit of being an international product, I consider this a bug.  (Sorry@

**Comment by lachlan-00** [comment]
translations are a first class citizen for Ampache. (Even though transifex thinks Australian English doesn't exist.)

So the issue to me looks like the PHP version isn't passing the test and the translation isn't loading the response?

This is at such an early error that we should probably untranslate that string though.

**Comment by usox** [comment]
> I don't see a problem of requiring lib/i18n.php before the php version test. I18n.php doesn't require preloaded files, Is there a problem I don't see?

Sure, i18n.php could be included before the method call happens, but just including the file does not enable translations. The translation init happens somewhat later during initialization - so either including the file or untranslating this line have the same outcome.

**Comment by wagnered** [comment]
@usox thanks for taking the time to explain it to me.

**Comment by usox** [comment]
> @usox thanks for taking the time to explain it to me.

You're welcome.

@lachlan-00 fixed this issue with aba6ab8213c3130dd62787a1932f8d7455a3c57e in develop.

**Comment by lachlan-00** [comment]
yeah this error won't happen in develop, i might do another point release next month with a few other little fixes but now we're moving onto the source-changes branch
