### ISSUE TITLE
Ampache API podcasts filter parameter required

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2586]
According to http://ampache.org/api/api-json-methods#podcasts, the filter parameter is listed as required(OPTIONAL: NO). Should this parameter be optional?

**Comment by lachlan-00** [comment]
yes, it should be, i must have made a copy of the podcast table when i wrote it.

good find, i need to fix up all these docs.

**Comment by lachlan-00** [comment]
updated on the api page and soon to be develop page. thanks for reading the docs. :)

**Comment by memen45** [comment]
Thanks for the quick response and lots of thanks for making those docs. They are a huge improvement compared to some time ago!

**Comment by lachlan-00** [comment]
It's very important to me that people can read and understand the docs so let me know if there's something else you find,

I've also made the first merge in develop of API 5 so i'm trying to really flesh out what is and isn't returned from responses and provide examples for all possibilities.
