### ISSUE TITLE
API action=playlist_songs is returning entire catalog

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2590]
It appears that a recent change in the code is causing an API call to action=playlist_songs to return the entire catalog, not just the songs in the playlist or songs that match the smart playlist conditions.  I have a cron job that runs every night to re-generate lists of songs from two smart playlists and one regular playlist, and the resulting three text files all this morning contained every song in my catalog.  Here is the call I am doing to generate the files:

wget "http://my.ampache.server.url/server/json.server.php?action=playlist_songs&auth=$AUTH&filter=smart_20&limit=none"

**Comment by lachlan-00** [comment]
lol, that is a massive problem. just tested myself

the code for getting items hasn't changed but it's almost like it's calling the wrong method
![image](https://user-images.githubusercontent.com/1305249/97094981-611e8a00-169d-11eb-92a9-46ad85da9162.png)

**Comment by lachlan-00** [comment]
2020-10-25T08:39:58+10:00 [user] (Lib\ApiMethods\PlaylistSongsMethod) -> User 2 loading playlist: 2069
2020-10-25T08:39:58+10:00 [ampache] (log.lib) -> [Runtime Error] Invalid argument supplied for foreach() in file /var/www/music/lib/class/search.class.php(1736)

**Comment by lachlan-00** [comment]
it's running a search instead of the playlist

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/97095046-fd489100-169d-11eb-94c6-ba71bfeec350.png)

found it it was assigning searches as playlists

**Comment by lachlan-00** [comment]
now i just need bad searches  error imstead of grabbing everything

**Comment by lachlan-00** [comment]
it was actually all because i cast the playlist id to an int (a find/replace that i missed)
casting strings to 0 gives a search a free catch all so it was returning everything with no filters

fixed with errors in a8cc36c77

**Comment by barcoboy** [comment]
Sweet, works now.  Thanks so much for the quick fix!

**Comment by lachlan-00** [comment]
> Sweet, works now.  Thanks so much for the quick fix!

You made ampache better! I'll be making some extra fixes based on this in other areas too.
