### ISSUE TITLE
Install guide for Raspberry Pi?

### ISSUE THREAD

**Issue by leopheard** [ampache/ampache#2592]
Hi all,

Does anyone know of an actual installation guide for the Raspberry Pi please?

I'm stuck at the web installation page, I have no idea re: the mysql passwords, can't get it to connect to the database, [1698] Access denied for user 'root'@'localhost', etc.

I have followed this video but he doesn't seem to have the same issues I do: [Youtube link](https://youtu.be/_yS_aoSKEGE)

**Comment by kuzi-moto** [comment]
Hey @leopheard, have you already installed a MySQL server and run `mysql_secure_installation`?

**Comment by leopheard** [comment]
@kuzi-moto Yes, done that, created a database and user, etc. It's just the webserver side that fails on every step. Can I create an Apache server and work from that?

**Comment by KaeTuuN** [comment]
Looks like, this is your Problem: https://github.com/ampache/ampache/wiki/mysql-faq

**Comment by leopheard** [comment]
Sorted it, I think it was an issues problems. I updated the Wiki to help others in the future
