### ISSUE TITLE
API access to login to Android app?

### ISSUE THREAD

**Issue by leopheard** [ampache/ampache#2593]
Hi all,

I'm trying to enable the ACL / APIs in order to get any of the approved Android apps working correctly.

I'm trying to log in to the app using - same as the details I can log in via the website successfully:
http://192.168.1.1/ampache
admin
password

I have looked at the guide here: [](https://github.com/ampache/ampache/wiki/API) and made sure the `access_control=true` is set as such in /var/www/html/ampache/config/ampache.cfg.php

I can't see anywhere I can generate an API code to login?

**Comment by lachlan-00** [comment]
You can do it in the account page if you're an admin 

![20201029_190242.jpg](https://user-images.githubusercontent.com/1305249/97547291-58211600-1a19-11eb-9b0a-f81af07dd957.jpg)

an admin can also do it from the user pages as well

![20201029_190637.jpg](https://user-images.githubusercontent.com/1305249/97547730-e4cbd400-1a19-11eb-9878-e6939f0f5214.jpg)

**Comment by lachlan-00** [comment]
most of the apps should be set up for password auth anyway so unless you're using subsonic it should strictly be needed

**Comment by eddyizm** [comment]
I've also have not been able to connect to a mobile app given that there are so many options, I feel like there's many "roll your own" types. That being said I noticed several clients require **https** - I also noticed an option in the ampache settings to force serving music over http protocol. How does this work? Is it worth setting up an SSL cert on the server?

**Comment by AshotN** [comment]
Since this issue is getting old I will go ahead and close it, if you need further help please re-open it.
