### ISSUE TITLE
Apperent bugs in class StatsMethod

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#2596]
I was looking at Ampache's implementation of the action `stats` as reference for my own implementation in ownCloud Music. Reading the code, I'm pretty sure I found a bug here:
https://github.com/ampache/ampache/blob/86f298e3393239a144f803419ead51e1cffe66f5/lib/class/ApiMethods/StatsMethod.php#L89

You would probably want to have the pointed line of code and the next line swapped. Because now, you set both `$type` and `$input['filter']` to value `'album'`. Then, you have `switch ($input['filter'])` which will go to its `default` block as `album` is not an expected value for the `filter`.

On the other hand, if I understood correctly, the statement https://github.com/ampache/ampache/blob/86f298e3393239a144f803419ead51e1cffe66f5/lib/class/ApiMethods/StatsMethod.php#L69 already prevents calling the function using the API v3.8 convention of not passing a `filter`. So if you actually want to keep the backwards compatibility with 3.8, then the `type` should be the only mandatory parameter.

**Comment by lachlan-00** [comment]
Thanks for reminding me, there was a workaround for the old way the stats method used to work.

I'll fix that code up to how i want it for 5 and update the docs.

**Comment by lachlan-00** [comment]
In f2a3586db i've removed filter from the parameter check and also removed the fallback to the old method.

if it was going to remain as-is it would have been exactly as you mentioned in the last line, filter would have been blocked breaking things anyway.
