### ISSUE TITLE
Trouble setting up mobile client

### ISSUE THREAD

**Issue by eddyizm** [ampache/ampache#2603]
# Description
A

### Describe the bug
When i hit my rest url, the page does not come up. (using myip and custom port. pulls up find in my browser on all devices)
http://myIP:port/rest/ping.view

Not Found

The requested URL was not found on this server.

### To reproduce

I am following the guide lines and seem to have enabled subsonic in the backend 

System settings - 
Use Subsonic backend ON
Access control is on

DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Web Interface |  
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Stream Access |  
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | API/RPC |  
php curl is installed
php*.*-curl is already the newest version 

My rest .htaccess
```
rest$ cat .htaccess
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /play/$1 [PT,L,QSA]
</IfModule>
```
XML-API

I don't see where XML-API is configured so perhaps that is it ? I'm really open to using any app at this point and not specifically a subsonic one. I just want it up and running before I get picky. I may try to roll my own soon enough using Dart/Flutter.

## Environment

* Ampache version: not sure where to grab this from?
* Web server + version: Apache/2.4.41
* Server operating system: Ubuntu 20.04.1 LTS
* Client operating system: Android 9

### Client type

* SubSonic

## Settings

will add relevant lines of config instead of posting the whole thing as I am afraid of posting sensitive settings. 

Just need help on where to look to finish the set up.

**Comment by lachlan-00** [comment]
possibly missing the .htaccess files

```
cp ./rest/.htaccess.dist ./rest/.htaccess
cp ./play/.htaccess.dist ./play/.htaccess
cp ./channel/.htaccess.dist ./channel/.htaccess
```

**Comment by eddyizm** [comment]
@lachlan-00 I posted my rest .htaccess file in the OP. 
The play one is also there : 
```
/var/www/html/ampache/play$ ls -a
.  ..  .htaccess  index.php
```

as is the channel one.
```
/var/www/html/channel$ ls -a
.  ..  favicon.ico  .htaccess  images  index.php  style.css
```
 Where else could I look? I am streaming fine from other devices via the web, even outside my home network. Could it be apache set up? Any clues appreciated.

**Comment by lachlan-00** [comment]
Using Apache for subsonic doesn't need any more than the htaccess files moved, the ping urls will need the full details sent. i don't think you can just pass ping without at least the user+pass or token+salt

you'll also need php-curl for streaming

a regular ping will look something like this
```
https://music/rest/ping.view?u=user&c=Sublime+Music&f=json&v=1.8.0&s=kOuustP&t=a4b7865f865f856f856f86bfdebcf9
```

**Comment by eddyizm** [comment]
it's obviously the htaccess files it seems but need to find where my "AllowOverride" has failed me. php curl is installed. 

@kuzi-moto  suggested the docs that read: 

> Once these prerequisites matched, the best test is to open http://your/ampache/location:port/rest/ping.view, e.g. if your ampache location is /ampache on standard port 80 open http://localhost/ampache/rest/ping.view with your browser and see the output. You should get the following XML response:
```
<subsonic-response version="1.10.1" status="failed">
    <error code="10" message="Required parameter is missing."/>
</subsonic-response>
```
by just hitting the url. which I am not getting. Looks like someone on reddit last year had the same issue so I'm reaching out for help with the apache set up. Hopefully will close this ticket soon :-)

**Comment by eddyizm** [comment]
after some more research, it looks like I didn't have the current path of my install. I probably moved it around when I was installing the app. 
```
<Directory /var/www/html/ampache/>
```
I guess this didn't work
```
<Directory /var/www/>
```
Thanks to a reddit thread it helped me figure out where to look. Hope this helps someone else !
