### ISSUE TITLE
add_user.inc creates user but outputs "User creation failed"

### ISSUE THREAD

**Issue by gramakri** [ampache/ampache#2605]
## Description
I am trying to package ampache for Cloudron. When I use the CLI tool to create the admin user, it says "User creation failed" even though it did create the user.

### Describe the bug
User created but error message and exit value says it failed.

### To reproduce

1. /usr/bin/php /app/code/bin/install/add_user.inc -u admin -l 100 -p changeme -e admin@cloudron.local -n "Ampache Admin"
2. It outputs "User creation failed"

Running it again says "Created Admin user admin with password changeme"

## Environment

* Ampache version: latest version and on develop
* Web server + version: Apache
* Server operating system: Cloudron (this is just a Docker based platform)

**Comment by gramakri** [comment]
I debugged this a bit. [User::create](https://github.com/ampache/ampache/blob/develop/lib/class/user.class.php#L1091) returns the last inserted id. The [add_user code](https://github.com/ampache/ampache/blob/develop/bin/install/add_user.inc#L56) is comparing this to be `< 1` which seems wrong. It should be `>= 1`, I think.

**Comment by lachlan-00** [comment]
should be < 0. there was another area that has this i'll make it the same

**Comment by gramakri** [comment]
@lachlan-00 Do you mean `< 0` means failed?

**Comment by gramakri** [comment]
I found similar code in https://github.com/ampache/ampache/blob/develop/lib/login.php#L123. Made a PR, thanks!

**Comment by lachlan-00** [comment]
lol, you're quick, i just did all the ::creates the same way in 2a3e8fa7e

If you can find anything else let me know and i would prefer that i merged your request instead of doing it myself.

**Comment by gramakri** [comment]
@lachlan-00 Ha ha, no problem, I closed my PR already since it reported there was a conflict. Thanks for the quick fix, I will get back to making the cloudron package work.

**Comment by lachlan-00** [comment]
thank you for finding the issue so quick, if you find anything else i'll make sure not to close it out so you can become a contributor.

**Comment by gramakri** [comment]
@lachlan-00 Can confirm your fix works.

**Comment by lachlan-00** [comment]
putting this into master now, will possibly need to do a minor release for some of these fixes
