### ISSUE TITLE
Files are added twice via cron

### ISSUE THREAD

**Issue by KaeTuuN** [ampache/ampache#2608]
### Describe the bug
I have a daily cron job, that adds new files to Ampache every night. The Problem is, that all Files get double added.
Variation a) Single List, each file is doubled: 1,1,2,2,3,3,4,4,...
Variation b) Two List with same Files: Disc 1 - 1,2,3,4,... ; Disc 1 - 1,2,3,4,...
See Screenshots
The strange thing is, that I can't reproduce this behavior via the Website. When I do an "Update Catalog" here everything seems to works fine.
In Database the songs are also doubled and are added straight in a row:
ID - Song
01 - Song A
02 - Song A
03 - Song B
04 - Song B
...

### To reproduce
Set up Cronjob under /etc/cron.d/ampache
`20 23 * * * www-data php -f /var/www/ampache/bin/catalog_update.inc -- -n Musik -cvag > /dev/null 2>&1`
Rights: `rw-r--r-- root:root`

### Expected behavior
Files should not be added twice.

### Screenshots
https://cloud.wellmann.wtf/index.php/s/3zt49mb8LxbSGm4

## Environment

* Ampache version: 4.2.3
* Web server + version: Apache 2.4.46
* Server operating system: Ubuntu 20.04 LTS HWE

### Client type
* Web
* Ampache
* SubSonic
* WebDAV

## Settings
https://cloud.wellmann.wtf/index.php/s/3zt49mb8LxbSGm4

**Comment by lachlan-00** [comment]
can you print some sql of the dupes?

also take out the v from cagv and test again first.

if you have cron_cache enabled as well turn it off to test as well
![image](https://user-images.githubusercontent.com/1305249/98062571-0e618100-1e9a-11eb-9e62-2387c4bdc3a4.png)

**Comment by KaeTuuN** [comment]
> can you print some sql of the dupes?
Sorry, had to delete the whole catalog and re-add. I will create a second instance and reproduce the bug.

> also take out the v from cagv and test again first.
Already tried that, does not help.

> if you have cron_cache enabled as well turn it off to test as well
It's not enabled

**Comment by lachlan-00** [comment]
okay, getting the dupes from the song table at least and then the album to compare them, there is probably an error when inserting the data into the database

**Comment by KaeTuuN** [comment]
I manually compared some DB Entries yesterday and they where completely identical. The only difference was their ID.

**Comment by lachlan-00** [comment]
then it's probably an error in the insert process somewhere

**Comment by KaeTuuN** [comment]
Upgraded to 4.2.4 and hven't seen the error in a while now... -> Closed
