### ISSUE TITLE
Searching by artist no longer works.

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#2611]
## Description
Searching by artist no longer works.
It seems that only the album search is working.

### Describe the bug
In the different search menus Ampache no longer returns results when I search for an artist.
Same from players using the subsonic API.

There is a Mysql error message in the Ampache logs.
This may have happened after the Ubuntu upgrade.
The server went from 18.04 to 20.04 and I imagine a MySQL upgrade.

index.php#mashup.php?action=artist Works

## Environment

* Ampache version: Develop ( 1b146cdcc3acca7b161fed13369f1962297a0f45 )
* Web server + version: Apache 
* Server operating system: Ubbuntu 20.04
* Client operating system: Web, Subsonics client
* Mysql  Ver 8.0.22-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

## Logs
AMPACHE LOGS :
2020-11-08T14:46:11+01:00 [ampachula] (dba.class) -> Error_query SQL: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` WHERE (`artist`.`name` LIKE '%massive%'  OR LTRIM(CONCAT(COALESCE(`artist`.`prefix`, ''), ' ', `artist`.`name`)) LIKE '%massive%') ORDER BY `song`.`file` 
2020-11-08T14:46:11+01:00 [ampachula] (dba.class) -> Error_query MSG: ["HY000",3065,"Expression #1 of ORDER BY clause is not in SELECT list, references column 'ampache.song.file' which is not in SELECT list; this is incompatible with DISTINCT"]

**Comment by rsinfotech** [comment]
This sounds similar to the issue I've experienced since the latest commit:

[https://github.com/ampache/ampache/commit/6f410b5ca343b7dd739d6b1784ab27aa88c87105#commitcomment-43944280](url)

Reverting to the previous commit dbcf04371 will temporarily resolve this until the devs get time to look at it.

**Comment by lachlan-00** [comment]
2a190b758 it's a full_group_by issue which apparently isn't kept after reboot for mariadb so i missed it

**Comment by rsinfotech** [comment]
Yep, that solves it for me, thanks again @lachlan-00

**Comment by douglasriper** [comment]
> [2a190b7](https://github.com/ampache/ampache/commit/2a190b7580ebabde14c3e7347d80a9267617a55b) it's a full_group_by issue which apparently isn't kept after reboot for mariadb so i missed it

thank you, the "full group by" corrects the dysfunction on the search.
