### ISSUE TITLE
Wrong theme in the "add to playlist" menu

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#2613]
### Describe the bug

When using the "Reborn/Light" theme as the main theme, the "Dark" theme is using in the menu "add to playlist".
Same behavior with Chromium and Firefox
### Expected behavior

Have the same theme as the main one
### Screenshots

I will add a screenshot if necessary and if I manage to convince the github interface to let me do it.

## Environment

* Ampache version: develop 
* Web server + version: Apache 2.4.41
* Server operating system: Ubuntu 20.04
* Client operating system: Manjaro Linux

### Client type
* Ampache (Chromium, Firefox)

**Comment by lachlan-00** [comment]
In the player menu or on a row in the song/album/artist lists?

**Comment by lachlan-00** [comment]
ahh in the row
![image](https://user-images.githubusercontent.com/1305249/98607091-35093700-2334-11eb-8839-06c117b113b4.png)

**Comment by lachlan-00** [comment]
fixed them and a few others in 5d21c3765. Thank you for finding this!
![image](https://user-images.githubusercontent.com/1305249/98620387-f8980400-2350-11eb-965c-c0db2cb218fa.png)
