### ISSUE TITLE
Can't use 'podcast' as Catalog Type

### ISSUE THREAD

**Issue by KaeTuuN** [ampache/ampache#2629]
**Describe the bug**
Try to create a new catalog -> select Catalog Type -> Podcast is not visible

Under 'lib/class/catalog.class.php'/ -> 'public static function create($data)' you can see:
`        if (!in_array($gather_types, array('music', 'clip', 'tvshow', 'movie', 'personal_video', 'podcast'))) {
            return 0;
        }`

**Expected behavior**
'Podcast' should be visible.

_Optional Easy Enhancement: Add Audiobook (German Singular: Hörbuch ; Plural: Hörbücher)_

**Environment**
- Ampache version: 4.2.4 (german language)
- Web server + version: Apache 2.4.46
- Server operating system: Ubuntu 20.04 LTS HWE

**Client type**
- Web

**Settings**
https://cloud.wellmann.wtf/index.php/s/3zt49mb8LxbSGm4

**Comment by lachlan-00** [comment]
podcasts aren't enabled by default
![image](https://user-images.githubusercontent.com/1305249/99876259-57a72400-2c41-11eb-95f5-bb734238d96b.png)

**Comment by KaeTuuN** [comment]
Thank you!

What my suggestion about Audiobooks?

**Comment by lachlan-00** [comment]
you'll have to expand on that one. add it as a catalog type? that's a todo.

**Comment by KaeTuuN** [comment]
Ok, thanks again! :smiley:
