### ISSUE TITLE
Home page is taking longer than it used to

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2630]
I've noticed that the home page is taking a lot longer to load than it used to. Seems to have happened in the last 5 to 10 days.

![image](https://user-images.githubusercontent.com/4076671/99905365-6112a980-2c9e-11eb-9e5b-554dd5a81b64.png)

If I disable show recently played then the page load time is much quicker. 

![image](https://user-images.githubusercontent.com/4076671/99905404-93240b80-2c9e-11eb-86d6-55f42110d84e.png)

I tried disabling various options, Albums of the moment, now playing, show similar but these didn't have any affect on page load time.

**Comment by stebe** [comment]
After a few reset hard I narrowed it down to this commit that started the slowdown.  e455ada7c281221abc2907f1c673de8c827975d4

**Comment by lachlan-00** [comment]
ohh that's a good find, i would have thought the simplification would speed that up, i'll check that query out

**Comment by lachlan-00** [comment]
does hardcoding the pref name fix it? 505ca5d0b

there won't be any user that requires a lookup.

**Comment by lachlan-00** [comment]
it gets me subsecond for users and under 2 for admins i think the online update check is too long as well

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/99933734-a242b080-2da7-11eb-9e7b-19e6cb8ca73b.png)
now i've forced the update check time out a lot more, there is no need for us to check for updates every time you log on and forcefully

**Comment by stebe** [comment]
Yup back to normal times for me.
