### ISSUE TITLE
ListenBrainz plugin broken

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2636]
Can't have been too long ago, my last scrobble was only two days ago, and I have been updating nearly every day (in the develop branch).

Every time it's called, it keeps answering **Last song played within 1 seconds, not recording stats**. Maybe it's got to do with lib/class/stats.class.php? My coding ability is limited, but it looks like that files has had a lot of activity lately.

**Comment by lachlan-00** [comment]
i've found that, it's the diff check in the plugin. I swapped the play insertion into the correct spot so now to stop the double checks we need to just accept that save_mediaplay plugins just run.

removed the check in c50e6f000 so it will just send. thanks for pointing it out as i don't use those plugins.

**Comment by lachlan-00** [comment]
sorry, i was in a different branch, this is fixed in develop now with 4666f29bb
