### ISSUE TITLE
Can't get Personal Favorites plugin working

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2638]
As an administrator, I've activated the Personal Favorites plugin on the Manage Plugins page, added one of my playlists and turned "Personal Favorites on the homepage" to "On" (checking both checkboxes to "Apply for all"), but all I am seeing on the homepage is the header "Favorite Lists".  What am I missing?

**Comment by lachlan-00** [comment]
I need to do the plugin in a better way but you also need to set a list of items to display
![Screenshot_20201205-085114_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/101223168-2154b480-36d7-11eb-8870-bdbd1315c80b.jpg)

I do need to stop the header showing if no lists are set
![Screenshot_20201205-085133_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/101223211-3df0ec80-36d7-11eb-87d7-f457de250fd9.jpg)

I want to make the list a multi line selectable list but I haven't worked that part out yet.

I've started working on documenting the plugins and the plugin creation process but it's still only early stages

**Comment by barcoboy** [comment]
Ah, didn't realize you needed to use the playlist IDs.  Now it's working.

As usual, many thanks.

**Comment by lachlan-00** [comment]
Part of my Christmas break will involve documenting plugins in a smarter way and explaining how things work.

Right now you sort of need to just know which isn't helpful

**Comment by lachlan-00** [comment]
now this is much clearer and also backcompatible with existing user values
![image](https://user-images.githubusercontent.com/1305249/101301278-0a9f9080-3884-11eb-8613-81d7d340e774.png)

**Comment by barcoboy** [comment]
Looks good, thanks!
