### ISSUE TITLE
Lost access to web interface

### ISSUE THREAD

**Issue by eddyizm** [ampache/ampache#2640]
## Description
Unable to login to website, as detailed in link below. I can still access my library via a mobile app (Ultrasonic ATM).

### Describe the bug
So I had the server up and running successfully for a few weeks now. At this point, I was trying to secure the server, you can see where this is going. I was changing some headers at first, breaking functionality, then removing it back to make sure the site loaded with full functionality. 

After messing with Apache, I moved on to the DB and decided I would go back and fix some obvious security mistakes. Which then blew up web access. 
https://www.reddit.com/r/ampache/comments/k6f6ae/hosed_my_maria_db_install/

I posted to reddit which helped me get back to the login screen, with no errors of any sort, apache log/console log/ ? 

At this point, I am not sure where to even look. 

Now that I write this. the one thing I forgot to mention that may have caused this, I decided I should update ampache to the latest so went into the directory and did a git pull.  

```
git status                          │
On branch develop                                                                     │
Your branch is behind 'origin/develop' by 140 commits, and can be fast-forwarded.     │
  (use "git pull" to update your local branch)          
```
it seems like everything has been touched, i had a massive list of modified files that needed to be committed/staged before pulling in. 
`Changes not staged for commit: `

next, my git pull failed: 
```
   9b9fbc28e..0f46ca52e  develop        -> origin/develop                             │
   632a49963..85b019139  catalog_filter -> origin/catalog_filter                      │
   468dd71e1..6b3c7bb86  master         -> origin/master                              │
 * [new tag]             4.2.5          -> 4.2.5                                      │
Updating a8cc36c77..0f46ca52e                                                         │
error: Your local changes to the following files would be overwritten by merge:
```
I was under the impression that a git pull was supposed to be the way to update so not sure what is being overwritten as I've only made the config/changes to the app. 

## Environment

* Ampache version: how do i access this? 
* Web server + version: apache 2.4
* Server operating system: ubuntu 20.04
* Client operating system: windows 10

### Client type

* Web

## Settings

don't think i need to post settings. 

## Logs

i don't have ampache logs going at the moment but that was my next step. please let me know what to post.

**Comment by kuzi-moto** [comment]
At this point I would make a backup of your ampache.cfg.php file and wipe your Ampache directory then re-clone. This should get you to the install page. Skip the "creating database" step and fill in the connection details from your backup config file.

If things are still not working it should help narrow the potential issue.

**Comment by lachlan-00** [comment]
Reset your folder using git
```
git reset --hard origin/develop
```

Do another pull and composer install to make sure the packages are up to date

**Comment by eddyizm** [comment]
Thanks @kuzi-moto  ! @lachlan-00  I'll give that a try this weekend.

**Comment by eddyizm** [comment]
looks like it is pretty hosed so i'm wiping it out and starting over. thanks for your help!
