### ISSUE TITLE
jquery-file-upload has incorrect case

### ISSUE THREAD

**Issue by gturri** [ampache/ampache#2642]
### Describe the bug
In the developer tools on my browser I see those error logs:

    GET https://<mydomain>/ampache/lib/vendor/blueimp/jquery-file-upload/js/jquery.iframe-transport.js [HTTP/1.1 403 Forbidden 3ms]
    GET https://<mydomain>/ampache/lib/vendor/blueimp/jquery-file-upload/js/jquery.fileupload.js [HTTP/1.1 403 Forbidden 3ms]

That's because the requested url is all lower case (`jquery-file-upload`) whereas on my filesystem the directory name is `jQuery-File-Upload`. (renaming this directory on my filesystem removes those errors).

### To reproduce
I'm going to https://<mydomain>/ampache2/index.php and I open the developer tools of my browser

### Expected behavior
I don't see those error logs

## Environment

* Ampache version: 4b94be611c9dbe1ce146edde9d2ed7a851d4dc75 (Wed Dec 2 08:40:42 2020 +1000)
* Web server + version: apache
* Server operating system: Ubuntu 20.04
* Client operating system: Ubuntu 20.04

### Client type
* Web

## Settings
I don't think this part is relevant. But don't hesitate to let me know if you believe it is.

## Logs
I don't think this part is relevant. But don't hesitate to let me know if you believe it is.

**Comment by lachlan-00** [comment]
that's weird, i'm all lower case on my server for all my installs
```
www-data@web:~/music$ ls lib/vendor/blueimp
jquery-file-upload
```

I also removed the folder and reinstalled into a lower case folder without changing anything
```
rm -rf lib/vendor/blueimp
composer install
```

**Comment by gturri** [comment]
hmm.... that may be because I have an old installation (several years old now, though I updated it lately) and that I'm only noticing those errors now... 
If it's not reproducible (and since it doesn't seem to have a lot of visible impacts, besides those error logs in the dev tool console) I'll close this issue then.
Sorry for the noise.

**Comment by lachlan-00** [comment]
it's always good to verify these things!
