### ISSUE TITLE
Abandoned composer dependency

### ISSUE THREAD

**Issue by KaeTuuN** [ampache/ampache#2644]
### Describe the bug

1. Download 4.2.5.zip
2. unzip && cd ampache
3. sudo -u www-data composer install --prefer-source --no-interaction
4. Output: _Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead._

**Comment by lachlan-00** [comment]
dupe of #2500 it's part of jplayer which needs to be updated
