### ISSUE TITLE
How to obtain user_id for record_play action

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2646]
According to http://ampache.org/api/api-json-methods#record_play a user_id (integer) is a required parameter to record a play. However, how can the user_id be obtained? From the client side I only have a username and none of the methods seem to return a user_id. For version 5 the action 'users' could return the required information, however, this is not yet available.

Additional related question: the scrobble action appears to do exactly the same as record_play, though by search strings instead of ids. For this action the user_id parameter is not included, which would indicate that the user_id is not necessary for record_play either. Should the user_id be an optional parameter or even removed from the parameter list?

Thanks in advance!

**Comment by lachlan-00** [comment]
You are right about it not being needed so i'm making user optional.
If you don't supply a user then just fall back to your own account.

I'm also making it so only admins will have the ability to record for other users. 

> However, how can the user_id be obtained?

In api4 you can get an id from the 'user' method using their username.

And their ID is returned for user object
https://raw.githubusercontent.com/ampache/python3-ampache/4.2.2-1/docs/json-responses/user.json


The reason i split these up was to provide an _internal_ scrobble and an _external_ scrobble method for 2 situations.

The scrobble method is for sending data from external databases and programs that don't use ampache for streaming.
* Hey Ampache, here's the "song title", "album title" and "artist name" if you have this can you record it?

Record_play is for internal plugins/processes/scripts where you can identify the song id first
* Hey Ampache, record song 1283 for this user

Most of the time, record play will be used in situations where data has been lost or in imports/updates which isn't very often but i still think it's needed.

Subsonic and api clients will all record plays without needing these two methods as plays are always recorded when you stream from Ampache.

**Comment by lachlan-00** [comment]
ccff80f9f has these changes and it will go into api5

**Comment by lachlan-00** [comment]
I forgot you implemented the 4.2 api into submusic as well!

I think i'll backport the optional user into 4.2 as well (4.2.6)

**Comment by lachlan-00** [comment]
i'm going to do a 4.3 release so this will be going in there.

**Comment by lachlan-00** [comment]
forgot to close this but it's in 4.3.0 now.

Thanks for opening this one!
