### ISSUE TITLE
Play option not always showing for artists or albums in search and browse artist or albums lists.

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2651]
### Describe the bug

While browsing artists/albums or searching for artists/albums, sometimes there is and sometimes there isn't the option to directly play the album, add to temp playlist or add to playlist. I'm logged in as an admin so I don't think it is a security issue. 
### To reproduce

1. Go to artists on the sidebar
2. Scroll through the results
3. Sometimes the play is there, sometimes it isn't.

### Expected behavior

The option to play the album should be available

### Screenshots

Screencast.

![Screencast from 2020-12-16 08:23:28 AM](https://user-images.githubusercontent.com/4076671/102361537-5687bf00-3f81-11eb-8021-68114e729305.gif)

## Environment

* Ampache version: 5a3fdda11411120b28da2a875402467fdbcb6d67

### Client type

* Web Firefox

## Logs

Nothing in the logs.

**Comment by stebe** [comment]
Looking more into it.  Even on the album page there there is no play option.
![image](https://user-images.githubusercontent.com/4076671/102410043-ff540f80-3fbd-11eb-8f1a-e941ba12729c.png)

But on this album there is.  
![image](https://user-images.githubusercontent.com/4076671/102410127-18f55700-3fbe-11eb-9dc5-7b262365c3b8.png)

**Comment by lachlan-00** [comment]
multi disk album?

**Comment by stebe** [comment]
These examples were all single disk

**Comment by stebe** [comment]
I tried as another user and this isn't an issue.  Trying to track down the difference between the two users.

**Comment by stebe** [comment]
So what I did was rename the user account and created another one.  Seems to be limited to this one user. Might be a combination of settings or something else.  Until I can reproduce with this new account I'll close for now.
