### ISSUE TITLE
Error Class 'video' not found not found running CLI 

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#2656]
Running CLI program for catalog update on Ampache CLI, version develop results in the below output....

##tty output

Start verifying media related to Catalog entries
Error Class 'video' not found
(thrown in /var/www/ampache/src/Module/Catalog/Catalog_local.php:626)

Stack Trace:

  0) Ampache\Module\Catalog\Catalog_local->_verify_chunk()
     at /var/www/ampache/src/Module/Catalog/Catalog_local.php:594
  1) Ampache\Module\Catalog\Catalog_local->verify_catalog_proc()
     at /var/www/ampache/src/Module/Catalog/Update/UpdateCatalog.php:102
  2) Ampache\Module\Catalog\Update\UpdateCatalog->update()
     at /var/www/ampache/src/Module/Cli/UpdateCatalogCommand.php:67
  3) Ampache\Module\Cli\UpdateCatalogCommand->execute()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:366
  4) Ahc\Cli\Application->doAction()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:280
  5) Ahc\Cli\Application->handle()
     at /var/www/ampache/bin/cli:71

Above is the results of running the command /var/www/ampache/bin# ./cli run:updateCatalog
This is all running under Apache version 2.4.38 on raspberry p4 manually installed using install.php
Also Catalog verify in web app  loops with server sid e error  reconnecting.. 

Thanks
James

**Comment by usox** [comment]
Hi @jamesc2151 

I presume you're using the current pre-release version an not the develop branch - so thanks for testing :smile: 
I fixed the problem in the related branch, I was not able to test it atm though.

**Comment by jamesc2151** [comment]
Yep using that version..I did however that same night load up the Dev
branch and it did the same thing but I probably grabbed it before you fixed
it. So I'll grab a fresh copy and load it up and see what it does.  Let me
know if there is anything else I can do to help.

Jc

**Comment by jamesc2151** [comment]
Hummm

Ampache version: 53443df491cb62e63e2e3de97c8098d557029510

command  ./cli run:updateCatalog returns ......
+++++++++++++++++++++++++++++++++++++
 Reading Catalog: "MyMusic"
Start verifying media related to Catalog entries
------------------
0
10000
20000
30000
0
10000
20000
30000
+++++++++++++++++

Not sure what that means but there was not an update that I could tell..

Jc
