### ISSUE TITLE
Errors in several Korean translations

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#2659]
Hey there Korean translators,

There are several errors in the Korean translations. Mostly they have happened because of missing variables / format specific arguments.
I'd love to see them fixed so we can be sure they work properly.

Please check the following link to see which strings are not translated correctly.

https://www.transifex.com/ampache/ampache/translate/#ko_KR/messagespot/183025770?q=check%3Aerror

![grafik](https://user-images.githubusercontent.com/6222200/103027395-0945b780-4556-11eb-924a-9f89cbf609fc.png)

Please feel free to ask if there's a question.

Discussion forum on Transifex: https://www.transifex.com/ampache/teams/40984/discussions/19962/

Greetings

Psy :)

**Comment by AshotN** [comment]
The link gives me a 403 error

**Comment by Psy-Virus** [comment]
Interesting, I don't get a 403 on any of these. Even with different browsers. Maybe you were not logged in?
But anyways, with my PR I deleted the wrong translations so they're not showing up anymore on the first link.

I thought it's better to have an translation update rather than waiting for the translators fixing them. So they appear untranslated now...

**Comment by lachlan-00** [comment]
> ns so they're not showing up anymore on the first link.
> 
> I thought it's better to have an translation update rathe

it could be that @AshotN  and i are not on the korean team?
![image](https://user-images.githubusercontent.com/1305249/103504781-2bb7c900-4ea4-11eb-9530-3d99ef4313c7.png)

**Comment by Psy-Virus** [comment]
> it could be that @AshotN and i are not on the korean team?

Yes, that's it probably :D

Ofc as I manage all teams, I have access to all content... 😁 

I guess that was the original intention, why I spoke to the Korean Translators in the first place ^^
