### ISSUE TITLE
Artist Alphabet browsing not updating 

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#2663]
Ampache version: 53443df491cb62e63e2e3de97c8098d557029510.

Recreate error...

Select artist.... View... Check Alphabet.....    Select any letter....... No update...... Working icon does show some sort up action but no screen update to selected letter..

**Comment by lachlan-00** [comment]
Will check, might be slow or an error somewhere. Definitely did work before

**Comment by jamesc2151** [comment]
working now in Ampache version: ff4b371a97c3f787cc9897fa9fe11ae3ac4075db.
