### ISSUE TITLE
Alphabet browsing

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#2665]
Would it be possable to add ABCD....(0123456789) to Alphabet browsing.. I have artists whos names begin with numbers.  IE 10ccs 38 special and the like...

Thanks
James

**Comment by jamesc2151** [comment]
Also what's the latest thoughts about a global folder for artists image pulls using the pattern using the artist name.JPG or Artist.png
I can't get this to work.. at all.

**Comment by lachlan-00** [comment]
> Also what's the latest thoughts about a global folder for artists image pulls using the pattern using the artist name.JPG or Artist.png
> I can't get this to work.. at all. 

You can pull into the database using artist name but it might be a bit confusing to set up?

**Comment by mitchray** [comment]
Closing due to time since last reply, reopen if still relevant
