### ISSUE TITLE
Minimum targeted browsers?

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2666]
Do we have any specified minimum required browser versions that we intend to support. A lot of web technologies don't support old browsers, and while a lot of poly-fills exist, it increases the bundle size for everybody and sometimes is a pain.

**Comment by usox** [comment]
Version 5 could be used to make a cut...

**Comment by AshotN** [comment]
That was my thought as well.

**Comment by lachlan-00** [comment]
If we can keep a major release to every 12ish months I would think something like 2/3years back?

I really only use Firefox so I'm definitely not an expert of browser support.

**Comment by AshotN** [comment]
As long as we don't intend to support IE for example, that'll help speed things up.

But it be nice if we decided something like >1% of usage, or certain browser version.

**Comment by wagnered** [comment]
I found a [reference](https://en.m.wikipedia.org/wiki/HTML5test) to a   browser HTML5 test suite and in the article, were references to other tests sites for tests such as Cascading Style Sheets, ECMAScript, Scalable Vector Graphics, or the Document Object Model.

From the results ampache.org could have a recommended browser.

As microsoft moved to the. Edge browser, which now uses  the blink engine,  we can pretty much ignore the IE series.  My rational is that  a user would want the best (read 'latest') browser to experience Ampache.

**Comment by AshotN** [comment]
The reason I want us to have a minimum supported browser list is so we test with those browsers. Even modern Chrome and Firefox sometimes render things differently, once you start adding in older version of all the browsers. You can get some ridiculous inconsistencies.

**Comment by usox** [comment]
Our policy at work is to support browsers 3 years back. Most of the people use modern browsers - companies with strict software policies and long evaluation cycles are the major issue here. But I guess, these are not our main targetgroup :)

**Comment by lachlan-00** [comment]
Trident/ie and non-blink edge are out of what we should care about for sure

**Comment by AshotN** [comment]
I’m good with a 3 year cycle. If we can decide on what specific versions that entails for Chrome/blink and Firefox/gecko(not many browser engines left these days sadly). I can close the issue and figure out how to test that.

**Comment by mitchray** [comment]
Closing as it looks like a consensus was reached 👍
