### ISSUE TITLE
Documentation for catalog_update.inc What exactly does "-u Update artist information" do?

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2674]
I needed to do a Catalog Update and there's really no good feedback from the admin interface if things are still continuing to work or if the process broke and stopped. So I started searching for a way to do it via command line and found one:

https://github.com/ampache/ampache/wiki/CLI

however that page is a bit outdated, so i checked the help:

`sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -h`

Based on the help info I decided to run this to update my catalog:

`sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -c -v -a -g -m -o`

However I noticed an option I am very curious about:

-u      Update artist information and fetch similar artists from last.fm Make sure lastfm_api_key is set in your configuration file

But before using that option I want to understand what it does exactly? does it update file id3 tags? if so what tags are changed? does it only update entries in the ampache database? Also when it fetches similar artists, how is that data used in the ampache web interface?

## Environment

* Ampache version: git develop latest
* Web server + version: Nginx latest
* Server operating system: Ubuntu 20.04
* Client operating system: Ubuntu 20.04

**Comment by lachlan-00** [comment]
There is data fetched from last FM when you open an artist page. This is usually a description and a list of similar artists. It's database only and isn't stored in files.

The u option will get a list of artists that haven't been updated for over 6 months (I think) and run the recommendation functions.

I don't think it does any more than that but not 100% it's not something you would really need to run regularly on an old install
