### ISSUE TITLE
Add localization to React UI

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#2677]
@Psy-Virus does great work in making sure Ampache is usable in other languages besides English. So the React interface should also be able to support different languages.

Am currently thinking of using https://github.com/i18next/react-i18next

**Comment by lachlan-00** [comment]
Would need a separate transifex repo so that should probably hasten splitting up the react repo

**Comment by AshotN** [comment]
I just don't know how transifex works. I've also never done localization, but it's definitely something that needs to be done!

**Comment by lachlan-00** [comment]
you need to think of a cool name @AshotN so we can make a new repo. ;)

**Comment by AshotN** [comment]
True, we should maybe have a makeshift vote. Can write out some options. Maybe Phoenix, similar to Reborn.

**Comment by lachlan-00** [comment]
reddit, telegram ,etc will be good starts

**Comment by mitchray** [comment]
Closing due to React client going on hiatus: https://github.com/ampache/ampache/issues/2360#issuecomment-1342288895
