### ISSUE TITLE
No Ampache-API connection possible with Power Ampache

### ISSUE THREAD

**Issue by exaveal** [ampache/ampache#2682]
### Describe the bug
I've set up a clean ampache server (v.4.2.4) on a clean raspbian os 64bit installation according to this how-to on my local network:
https://www.digitalocean.com/community/tutorials/how-to-install-the-ampache-music-streaming-server-on-ubuntu-18-04 

- Web GUI is working
- Subsonic API is not working correctly
  > native Linux Client "Sublime Music" not working: Invalid authentication attempt to Subsonic API for user ampache
  > Android Client "Ultrasonic" only working with option "Force plain password authentication", so not usable in a productice environment
- Ampache API is not working correctly
  > Android Client "Power Ampache" not working: Something went wrong. Please try again
  > Android Client "Amdroid" login possible, but music playback not possible

### Expected behavior
- Ampache API working with Power Ampache
- Subsonic API working with Sublime Music

## Environment

* Ampache version: 4.2.4
* Web server + version: Apache latest
* Server operating system: Raspberry OS 64bit on Raspberry 4
* Client operating system: Manjaro Linux

- mod_rewrite acitvated
- .htaccess files adjustet
- SubSonic Backend in Ampache activated
- URL Rewriting in Ampache acitvated

**Comment by lachlan-00** [comment]
if we split this into parts lets look. the subsonic has had token auth support for all 4.x.x versions

for subsonic and sublime, token authentication requires an api key from the user this has to be generated manually
![image](https://user-images.githubusercontent.com/1305249/103964093-522c7b80-51a6-11eb-8381-bfb060b48053.png)

using that as my password connects with token auth on sublime and all other subsonic clients.
![image](https://user-images.githubusercontent.com/1305249/103964008-1e515600-51a6-11eb-99cd-43963e581c60.png)

for the ampache api auth for older clients should be done with passwords but encrypted apikeys are also checked
pinging the api server should return a response.
```
server.com/server/json.server.php?action=ping
```

check those first and then we'll move on.

**Comment by mitchray** [comment]
Ampache [5.2.0](https://github.com/ampache/ampache/releases/tag/5.2.0) now has support for legacy versions of the API (3 & 4) so old apps like Power Ampache should work, once the legacy APIs are enabled
