### ISSUE TITLE
SongRepository::getByAlbum() needs an integer 

### ISSUE THREAD

**Issue by arnaudbey** [ampache/ampache#2698]
### Describe the bug

2021-01-14T21:41:30+00:00 [arnaud] (/var/www/html/ampache/src/Repository/SongRepository.php:38) -> Argument 1 passed to Ampache\Repository\SongRepository::getByAlbum() must be of the type int, string given, called in /var/www/html/ampache/src/Module/Album/Deletion/AlbumDeleter.php on line 71

### To reproduce

Trying to remove an album through my browser
on **Ampache version: 5.0.0-pre-release3**

casting $album->id as an int with intval($album->id) twice in this method seems to be enough but it's certainly not the cleanest way to fix that :)

**Comment by usox** [comment]
Hi and thanks for testing the preview.

I'll have a look later today. Maybe I'll have to replace the usage of the id-property of the "old" model files by a getId method which performs the cast of the value within the model.

**Comment by lachlan-00** [comment]
@arnaudbey i'm really happy to see people taking up the preview. this is going to be replacing develop in the near future so this is really appreciated!

**Comment by usox** [comment]
The issues should be fixed within the source-changes branch but I would recommend to wait for the next preview version.

**Comment by arnaudbey** [comment]
Thanks guys !
