### ISSUE TITLE
Unable to connect to the database: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by leopheard** [ampache/ampache#2702]
Hi all,

I'm trying to get my Raspbian installation back up and running but I am getting the following error when I'm going to [the install page](http://localhostIP/ampache/install.php)

`Unable to connect to the database: SQLSTATE[HY000] [2002] No such file or directory
`
Not sure the exact version of Ampache I'm using, it's a recent one and I used:
`wget https://github.com/ampache/ampache/archive/master.tar.gz` to download it

Obviously it's looking for a folder, but obviously it's very hard to fix something when it gives you nothing to go on.

Edit: So running `mysql -u root -p` it gives the following
```
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```
I tried to install the latest version of Ampache and it seems that mysql has been replaced with mariadb for Rasbpian?? Is that is what's causing this issue?

Edit2: 
So I reinstalled somewhat:
```
sudo apt install mariadb-server php-mysql -y
sudo service apache2 restart
sudo mysql_secure_installation
```
But now I get `Unable to connect to the database: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'`

Also, on the page: http://localhostIP/ampache/install.php?action=check at the very bottom it says 'error' under "ampache.cfg.php" is writable. Is this related? I copied the file /var/www/html/ampache/config/ampache.cfg.php.dist to the same but took off the .dist extension. This broke the local install page entirely. How do I fix this, I'm assuming I need that config file for things to work properly.

**Comment by wagnered** [comment]
> Unable to connect to the database: SQLSTATE[HY00 0] [2002] No such file or directory

Is that the full message? Does it state what file or directory?

  `socket=/var/run/mysqld/mysqld.sock` needs to be added to my.cnf or mysql.cnf depending on the distribution.  Then restart the mysql server.  Note that the distribution might create a link from /var/run/  -> /run. 

This should fix the access via mysql: root by default can connect only through the socket.

**Comment by lachlan-00** [comment]
debian/raspbian use /run now for the sock

![image](https://user-images.githubusercontent.com/1305249/104968229-05139980-5a31-11eb-9d90-062a490d5940.png)

**Comment by usox** [comment]
As the OP is using ampache in more recent tickets (#2705), I consider this problem as solved.
