### ISSUE TITLE
Alignment of columns for multiple discs

### ISSUE THREAD

**Issue by reinerh** [ampache/ampache#2703]
### Describe the bug
When viewing an album page for an album with multiple discs, then the columns (artist, album, year) are not aligned, which does not look so nice.

### To reproduce

1. Go to an album page with multiple discs.
2. Notice that the columns are not aligned.

### Expected behavior

Columns are aligned (same X position, same width).

### Screenshots

![ampache](https://user-images.githubusercontent.com/3106950/105107821-3041cb80-5ab9-11eb-935f-578113b33f8f.png)

## Environment

* Ampache version: 4.2.6

**Comment by lachlan-00** [comment]
I think tilte,artist, album are the issues in this page. sizes for the rest seem static

**Comment by lachlan-00** [comment]
i'll see what i can do with %'s.

the rule is in the default css
```
.cel_song, .cel_album, .cel_artist, .cel_year {
	max-width: 550px;
	white-space: normal !important;
	text-overflow: ellipsis;
	overflow: hidden;
}
```

**Comment by lachlan-00** [comment]
looks much better now in 2a77e5b76

thanks for pointing these out. it's something you tend to ignore over time

**Comment by mitchray** [comment]
@lachlan-00 This unfortunately breaks other items as they share the same classes, check out these now:

/index.php#mashup.php?action=album
/index.php#mashup.php?action=artist

**Comment by lachlan-00** [comment]
> 
> 
> @lachlan-00 This unfortunately breaks other items as they share the same classes, check out these now:
> 
> /index.php#mashup.php?action=album
> /index.php#mashup.php?action=artist

i'll change the mashup as well

**Comment by lachlan-00** [comment]
ac1faeda5 has the mashup columns separated from regular browses and i've centred them in a new class so they don't affect each other
![image](https://user-images.githubusercontent.com/1305249/105123778-6bc5af80-5b24-11eb-9220-3579bac8bb8c.png)
