### ISSUE TITLE
Controls on discs of multi-disc albums affect whole album

### ISSUE THREAD

**Issue by reinerh** [ampache/ampache#2704]
### Describe the bug
On multi-disc albums each disc has its own controls (playing, queueing etc.).
But the controls have the same effect as the global album controls at the top.

### To reproduce

1. Go to a multi-disc album.
2. Click on the play button next to the second disc.
3. The whole album (starting with disc 1) is now being played.

### Expected behavior

When clicking the play button next to the second disc, I expect that only the second disc is added to the playlist and being played.

## Environment

* Ampache version: 4.2.6

**Comment by lachlan-00** [comment]
can see that, it's including all the disks in the section when it should be one disk. i'll check out the template


```
https://music.com.au/server/ajax.server.php?action=basket&type=album&id%5B0%5D=43454&id%5B1%5D=43455&id%5B2%5D=43456&id%5B3%5D=43453', 'play_full_43454'
```

**Comment by lachlan-00** [comment]
put it in 21bfa00ef

that's much less confusing
