### ISSUE TITLE
Artwork is either missing or very pixelated after import

### ISSUE THREAD

**Issue by leopheard** [ampache/ampache#2705]
Hi all,

I'm using 4.2.3 and have linked my music catalogue. Unfortunately, a lot of the artwork has downloaded but is very pixelated as it has chosen the smallest one it seems. Others are just the default image but I can manually edit the picture and it has a variety of sizes for the correct artwork ready for me to hit 'select'.

So my question is, how can I make it choose the higher resolution when it finds artwork and actually select the artwork it already knows is there? I downloaded the vast majority of my music from Google Play Music before it became defunct, so I think the vast majority of it has metadata on it.

Any help please?

**Comment by cquike** [comment]
In the configuration file config/ampache.cfg.php you can specify which should be the minimum size for the artwork:
```
album_art_min_width = "200"
album_art_min_height = "200"
```
I am not sure whether after you change that the existing downloaded artwork which don't comply with that will be redownloaded or maybe you need to retrieve artwork again.

**Comment by lachlan-00** [comment]
you can clean the art table when you set a minimum size
```
php bin/clean_art_table.inc
```

![image](https://user-images.githubusercontent.com/1305249/105164047-5d958480-5b60-11eb-9b3c-485258fa2a11.png)

**Comment by leopheard** [comment]
Thanks for the input both! So, the minimum size did help yes, but unfortunately it hasn't solved the missing artwork. It's strange as when I go to edit the picture, it knows it's there, just doesn't select it, as per this example: 
[Artwork e.g.](https://ibb.co/4VR4Nn5)

**Comment by mitchray** [comment]
Closing as I believe this is resolved now in v5+
