### ISSUE TITLE
Latest commit cuts off album art

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2707]
The latest develop commit 3cb9a197a cuts the bottom off all album art in any of the browse pages or information stats pages in grid view:

![image](https://user-images.githubusercontent.com/3216809/105245672-157b5f80-5b6a-11eb-80a5-d572fe9c6051.png)

Reverting to commit 4799add96 resolves the issue.

**Comment by lachlan-00** [comment]
on mashup?
```
/mashup.php?action=album
```

the css has changed can you ctrl+f5 that page first?

**Comment by lachlan-00** [comment]
the heart icon is meant to be centred too so i think it's because i've split the css class out and it hasn't refreshed

**Comment by rsinfotech** [comment]
Yes, apologies, that was it, refreshing the css cache cured the issue.

**Comment by lachlan-00** [comment]
don't worry about it, when you update in the browser it can be not obvious that things like that have cahnged

**Comment by rsinfotech** [comment]
Just a note on this, you asked if this happened on the mashup pages, I was under the impression that these had been removed?

Both the sidebar browse links and the browse links across the top of the pages return the basic album/artist listings for me and have done for a while now. I no longer get the mashup pages with trending etc. which is a shame as I found them really useful.

Am I missing something simple again here?

Thanks...

**Comment by lachlan-00** [comment]
> Just a note on this, you asked if this happened on the mashup pages, I was under the impression that these had been removed?
> 
> Both the sidebar browse links and the browse links across the top of the pages return the basic album/artist listings for me and have done for a while now. I no longer get the mashup pages with trending etc. which is a shame as I found them really useful.
> 
> Am I missing something simple again here?
> 
> Thanks...

Moved back to the simple sidebar now but I do want to put them in a different place on the main sidebar.

**Comment by rsinfotech** [comment]
Thanks, I rarely use the simple sidebar so missed that.

Yep, would be nice on the main interface somewhere, it's a nice feature.

**Comment by lachlan-00** [comment]
Yeah, I really like the way they present so I do want to put them back in the main area
