### ISSUE TITLE
Database errors after latest database update

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2708]
Noticed the following database errors being reported after pulling the latest commit that updated the database:

```
(Dba) -> Error_query MSG: ["42S22",1054,"Unknown column 'addition_time' in 'group statement'"] 
(Dba) -> Error_query SQL: SELECT `playlist`.`id` as `id`, MAX(`playlist`.`last_update`) AS `real_atime` FROM `playlist` GROUP BY `playlist`.`id`, `addition_time` ORDER BY `real_atime` DESC  LIMIT 0, 50
```
This is triggered when visiting the 'Newest' link - stats.php?action=newest and results in the newest artists being repeated multiple times and no playlists being returned.

**Comment by lachlan-00** [comment]
i know where that is, the column is renamed a_time so i'll need to fix that.

must be a difference between mysql and mariadb as addition_time is found with mariadb

**Comment by lachlan-00** [comment]
it's part of commit 93b50518c

**Comment by lachlan-00** [comment]
the playlist code should have no grouping by time, this should stop with 70cc75f85

**Comment by rsinfotech** [comment]
Confirmed, database errors no longer reported and newest page back to displaying artist results correctly.

Many thanks.
