### ISSUE TITLE
[Feature Request] Add the possibility to configure what year is shown in album view, original, release or both 

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2712]
## Describe what you don't like about Ampache, or what it is missing
I like to sort my albums of an artist by year, to see when exactly an album originally got released.
At the moment ampache only has the ability to show/sort albums by release year in artist view.

## Describe how you would like the feature to work**
An option in the interface setting with on dropdownfield would be nice where one can decide what year to show in artist view.
originalyear, releaseyear or both.
Without this option the reference to emergence of so much masterpieces gets a bit lost regarding all those remasters bringing new life into those masterpieces of music.

**Comment by lachlan-00** [comment]
That's a setting I would really like to add. It's actually why I put original year into the database

A per user "use Original Year" setting would be enough then just edit the queries based on that.

**Comment by SePHTaN** [comment]
Hi
i'm very pleased about not being the only one that likes to have his Music sorted in a samewhat "original" way.
I am using Ampache at least since 2012, and have been waiting for this possibility since then.

Getting deeper and deeper in Server Setups, expanding the Possibilitys of my Homeserver from Year to Year, incl.
some smaller programming Tasks , i HTML, PHP and PYTHON, i decided to ask for this feature.
If there is anything i am able to help to get this feature comming to ampache soon, than iam wiling and read for.

Greets 
Stephan 
P.S.: You are doing a great work with ampache especially the last year was amazing with all the updates the complete ampache team made.

**Comment by lachlan-00** [comment]
Right now the original year is used with callbacks to year in search and the 'decades' option in subsonic.

But it's just been one of those selfish todo options but haven't been able to spend the time on.

Now that I know other people want it it's not really a huge job to undertake. Just a new user preference and option in the browse code.

It's really helped me that so many more people are here to help. 2020 was by far the biggest year for people and activity I've seen in the project.

I think people are really happy just to see us working so hard and that it's a project that will always be free and open to anyone.

**Comment by SePHTaN** [comment]
> I think people are really happy just to see us working so hard and that it's a project that will always be free and open to anyone.

For me i can say that this is definitely an fact, and i am very pleased to hear that ampache will always be free and open(source).
I was slightly disappointed in Jan/Feb 2020 when i recognized that my project i was working on at that time went almost useless because the most important part of it went closed source : Snips.ai.

A question i do have regarding my feature request.
By reading the issues and pull-requests in the last days, you are relatively near to releasing Ampache 5.0.
I don't think that you will be adding this feature to the "old" ampache version, and i can totally understand this especially when i try to comprehend how much work it is to maintain two different versions of an project like ampache.
So here to the question:
Is the Ampache 5.0 prerelease already usable as daily driver/ production system ?
If not, any statement possible how long that you expect v5 will need to be usable.

Greets 
Stephan

**Comment by lachlan-00** [comment]
5 is what I'm using as my daily now but it's not completely stable yet. It will probably be merging into develop in a month depending on what is broken and how hard I can test it beforehand. I also need to heavily document the changes before we force it on everyone.

Before it merges into develop I should also do a 4.3 release to merge some of the changes. 5 is going for a hard support limit of PHP 7.4/8 so there will still be some 7.3 people for a year or 2.

**Comment by usox** [comment]
Hey @SePHTaN 
Like @lachlan-00 said, it's somewhat stable - it mostly depends on your use case. If you simply play media from your local catalog and don't mind minor issues to happen now and then, it should be stable enough.

**Comment by SePHTaN** [comment]
>5 is what I'm using as my daily now but it's not completely stable yet.

Good to hear, pushes me to get ready for an test install.

> 5 is going for a hard support limit of PHP 7.4/8 so there will still be some 7.3 people for a year or 2.

Regarding the PHP Version i have no concern for me. My server is actually configured so i can support apache2 with PHP Versions from 5.6 up to 8.0.
So i might take some time an my next free weekend and setup a secondary database for ampache and also a secondary virtualhost with php8.0-fpm.

**Comment by usox** [comment]
Jus fyi: Made my first steps in here, works for me atm. Now I'm searching for a way to add a user config value to the ui... :)

**Comment by lachlan-00** [comment]
update_400019 was where i put of the moment in to the interface

then you just need a true/false case (cause i'm assuming this if on/off)
![image](https://user-images.githubusercontent.com/1305249/112411605-eb603c80-8d68-11eb-9edf-7d4764c94bed.png)

**Comment by SePHTaN** [comment]
Nice to hear.
When looking into this, take a look at #2850 should be in the same classname.php
I just discovered this one some days ago, but had been busy first with that dying power adapter and next with degraded raid5 array caused by the power failure.

**Comment by lachlan-00** [comment]
i've put this in with 8af6141be

It needs more added to the visuals so you can differentiate between them (something like how multi disks are shown?)
![image](https://user-images.githubusercontent.com/1305249/123930587-3eced000-d9d3-11eb-84fd-39fe157549a6.png)

or maybe in the actual year column?
![image](https://user-images.githubusercontent.com/1305249/123931114-ad139280-d9d3-11eb-965a-82efb39b2021.png)

But this will filter/browse/api respond by original year and fall back to year now

**Comment by lachlan-00** [comment]
i think i'm happy with this in 88160265f

the album page always displays the release year (as it did before)
![image](https://user-images.githubusercontent.com/1305249/124073677-ab0a0c00-da85-11eb-8a5d-9e2a187691f2.png)

keeping it consistent with the album row
![image](https://user-images.githubusercontent.com/1305249/124073764-d42a9c80-da85-11eb-95cc-9140cb0c5bf0.png)

**Comment by lachlan-00** [comment]
okay, i've made the album formatted title use the original year the same way in 9347ee326
![image](https://user-images.githubusercontent.com/1305249/125216168-a7397d80-e300-11eb-8693-3be8468842ea.png)

I think this covers all areas where it would be required and shows everything in a consistent way.
