### ISSUE TITLE
Asking for update

### ISSUE THREAD

**Issue by Dreadlocke12** [ampache/ampache#2714]
Even after the update to 4.2.6 in the admin interface it requests to install the update 4.2.4. Every update i installed got the addition .release.

**Comment by lachlan-00** [comment]
Can you do a force update check first? The server used to only look for the last release and then fall back to the last version. 4.2.6 will loop through releases until it finds the latest.

admin/system.php?action=show_debug

![Screenshot_20210126-091617_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/105778072-51258780-5fb7-11eb-9083-bc78bf83fa37.jpg)

**Comment by Dreadlocke12** [comment]
Even i do a force check there is no difference. I installed already version 4.2.6 and it says the youngest available version is 4.2.4. I restarted the server already but no change. 
 
 
  Am Di., Jän. 26, 2021 at 0:18 schrieb lachlan<notifications@github.com>:   


Can you do a force update check first? The server used to only look for the last release and then fall back to the last version. 4.2.6 will loop through releases until it finds the latest.

admin/system.php?action=show_debug

**Comment by lachlan-00** [comment]
if you use git you can force a branch,
![image](https://user-images.githubusercontent.com/1305249/105813789-18f46800-5ffc-11eb-8c5c-9ec4335b2ecb.png)

if you're using zip releases, this shouldn't be a problem with the current stable.
replace your autoupdate file with the latest version.
https://github.com/ampache/ampache/blob/acb1f7eb5f56732afbbf500be0cc785f1d259a58/lib/class/autoupdate.class.php

**Comment by Dreadlocke12** [comment]
I will test that and let you know if it works 
 
  Am Di., Jän. 26, 2021 at 8:32 schrieb lachlan<notifications@github.com>:   


if you use git you can force a branch,


if you're using zip releases, this shouldn't be a problem with the current stable.
replace your autoupdate file with the latest version.
https://github.com/ampache/ampache/blob/acb1f7eb5f56732afbbf500be0cc785f1d259a58/lib/class/autoupdate.class.php

**Comment by Dreadlocke12** [comment]
That solved the issue: 
![Bildschirmfoto von 2021-01-26 20-24-11](https://user-images.githubusercontent.com/56894437/105894493-9f1ca880-6014-11eb-804e-15aecef08e83.png)
