### ISSUE TITLE
Upload Target Folder Menu Issue

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2721]
# Issue Template

## Description

**Describe the bug**
When using the upload page upload.php, right clicking on a folder in the target folder section reveals a dropdown menu of folder options, New, Rename, Delete etc.

This menu is displayed below all of the other folders and any other text entry areas on the page meaning that none of the menu options are selectable with a mouse click.

I have found that using the arrow keys and enter key when the menu is visible does produce the expected behaviour but the menu items are difficult to see if they fall behind other page objects.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'upload.php'
2. Right click on any user folder in the target folder section
3. Notice that the folder options menu is partially hidden behind other folders and page objects
4. Attempt to select any of the menu items using the cursor and only foreground objects are selectable
5. Using the arrow keys and enter key to navigate the dropdown menu will produce the expected behaviour but this is difficult because of the menu being partially obscured by other page objects

**Expected behavior**
The dropdown menu should be displayed above all other page objects so that the menu items are selectable using the cursor

**Screenshots**
![image](https://user-images.githubusercontent.com/3216809/106491454-ca891280-64ae-11eb-975c-1e29ac5f27e3.png)

## Environment

* Ampache version: Ampache develop
* Web server + version: Apache 2.4.46, MySQL 8.0.22, PHP 7.4.14-1
* Server operating system: Fedora 33
* Client operating system: Ubuntu 18.04.5 LTS

**Client type:**

* Web

## Settings

Related settings under Admin menu (preferences.php?action=admin&tab=system)

Upload
Allow user uploads | On
Allow users to edit uploaded songs | On
Allow users to remove uploaded songs | On
Create a subdirectory per user | On
Destination catalogue | ampachemusic
Post-upload script (current directory = upload target directory) | Blank
Rename uploaded file according to catalogue pattern | On

## Logs

Nothing reported in the error logs

**Comment by mitchray** [comment]
Probably just a z-index issue, I'll take a look soon

**Comment by lachlan-00** [comment]
Thanks for posting this, i didn't even know that existed!

**Comment by lachlan-00** [comment]
the css is vakata from jstree, don't have a rule for it but probably put it in default
```
.vakata-context,
.vakata-context ul
```

**Comment by lachlan-00** [comment]
i've put it in 8fc271f34
