### ISSUE TITLE
ogg radio streams unsupported by jplayer?

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2728]
i didn't realise this until testing but there are ogg streams that don't play in the stream/webplayer.

e.g. http://ubuntu.hbr1.com:19800/tronic.ogg

![image](https://user-images.githubusercontent.com/1305249/106844853-61dfa700-66f5-11eb-970f-a9ffb562cc8f.png)

I always assumed jplayer support ogg stream

the unsupported is part of the show_html5_player.inc.php file

**Comment by xekon** [comment]
@lachlan-00 how do you find radio streams that actually work? A few of my local radio stations have streams that I can play through a few websites in firefox browser but when I inspect those pages I do not find a working stream.

Do you have any resources/bookmarks for Free Radio streams?

**Comment by lachlan-00** [comment]
i listen to a few mp3 streams but don't have ogg streams that work
![image](https://user-images.githubusercontent.com/1305249/107312389-08ec8600-6adc-11eb-9c13-0c64a4c405d7.png)

**Comment by SePHTaN** [comment]
@lachlan-00 
i am not sure but doesn't ampache also transcodes http stream if set in ampache.cfg.php : 
```
transcode_ogg  = "required"
transcode_player_webplayer_ogg = "required"
encode_player_webplayer_target = mp3
```
haven't tested it though, but i think i will try this now
tested and working :)

**Comment by SePHTaN** [comment]
@xekon 
some findings for stream urls:
[RadioBob ](https://www.radiobob.de/radiobob/empfang/livestream)
[rrradio.de 150+ Webradios + Streamaddresses (mostly German)](https://rrradio.de/radiosender/)

**Comment by rsinfotech** [comment]
@xekon this is useful for UK stations:

http://radiofeeds.co.uk/

**Comment by lachlan-00** [comment]
I'm not sure when it's gotten better but i think one of my recent changes has made transcoding/streaming work for me using ogg/m4a streams!

**Comment by lachlan-00** [comment]
> @lachlan-00
> i am not sure but doesn't ampache also transcodes http stream if set in ampache.cfg.php :
> 
> ```
> transcode_ogg  = "required"
> transcode_player_webplayer_ogg = "required"
> encode_player_webplayer_target = mp3
> ```
> 
> haven't tested it though, but i think i will try this now
> tested and working :)

does seem to be that it's just ogg transcoding. not sure why i've never sat down and resolved this

**Comment by lachlan-00** [comment]
> @lachlan-00
> i am not sure but doesn't ampache also transcodes http stream if set in ampache.cfg.php :
> 
> ```
> transcode_ogg  = "required"
> transcode_player_webplayer_ogg = "required"
> encode_player_webplayer_target = mp3
> ```
> 
> haven't tested it though, but i think i will try this now
> tested and working :)

does seem to be that it's just ogg transcoding. not sure why i've never sat down and resolved this
