### ISSUE TITLE
Only album_artists are shown

### ISSUE THREAD

**Issue by reinerh** [ampache/ampache#2733]
### Describe the bug

I just upgraded to 4.3.0 and noticed that suddenly the artists page is quite empty (only 3 are listed).
I think it's related to the album_artist change mentioned in the changelog, because for most albums I don't have an album_artist tag set (as usually it's the same as the artist).
I would suggest to display all artists, not only the ones found in album_artist.

### To reproduce

1. Go to '/index.php#browse.php?action=album_artist'
2. Only known album_artists are shown, not all artists.

### Expected behavior

All artists are shown.

## Environment

* Ampache version: 4.3.0
* 
### Client type

* Web

**Comment by manuelglez86** [comment]
I´m not testing 4.3 right now, but something similar happend to me when I was developing my API interface.

Not all Akbum files has the ALBUM ARTIST tag filled it is usually present when there are duets on some songs of the albums.

@lachlan-00 did you use only album artist? My solution in that time was to use the "Artist" tag when "Album Artist" isn´t present.

**Comment by SePHTaN** [comment]
> 
> 
> Not all Akbum files has the ALBUM ARTIST tag filled it is usually present when there are duets on some songs of the albums.

If you tag your albums with all the information provided by solid Providers like Musicbrainz, with for example Musicbrainz-Picard, then there is always Artist, Artists, Album-Artist aso. filled.
Not having them in your music files leads me to the assumption that you don't tag your music properly.

I do almost only use Musicbrainz Picard for tagging of my music. Rare cases are only for albums which aren't in the database of Musicbrainz.

**Comment by reinerh** [comment]
>  Not having them in your music files leads me to the assumption that you don't tag your music properly.

I tag them mostly manually and don't use Musicbrainz/Picard, because I don't like how they litter the tags with metadata I don't care about (also they are sometimes differently capitalized etc., so I would have to re-tag manually anyway).
I don't see a need to duplicate the artist information into an album_artist tag.

**Comment by SePHTaN** [comment]
> 
> I don't see a need to duplicate the artist information into an album_artist tag.

The only way to group songs together to an album, in case of an sampler or a liveconcert recording with guest artists is the album-artist.
What Kodi recommends : 
[Kodi Media Center- Music Tagging](url=https://kodi.wiki/view/Music_tagging#Tagging)

Ampache needs Information to sort your Music, group it to Albums, gather the art... . If you don't want to provide this information to Ampache through the tags then you can't bother ampache for doing something wrong (from your view).

Proper Tags are essential for a good representation of your music through any software. It doesn't matter if the software is kodi, plex, mediamonkey, squeezbox or any other. They all depend on the quality of the (tagged) data you provide.

**Comment by reinerh** [comment]
> Ampache needs Information to sort your Music, group it to Albums, gather the art... . If you don't want to provide this information to Ampache through the tags then you can't bother ampache for doing something wrong (from your view).
> 
> Proper Tags are essential for a good representation of your music through any software. It doesn't matter if the software is kodi, plex, mediamonkey, squeezbox or any other. They all depend on the quality of the (tagged) data you provide.

I understand that tags are important. But artist is in many (most?) cases the same as album_artist, so I think artist would be a good fallback if there is no album_artist set.
If Ampache really requires certain tags like album_artist to function properly, please document this somewhere.

**Comment by manuelglez86** [comment]
Software like Itunes only fill the album artist tag when converting CDs if theres guest on the tracks, if only the main artist appears then Itunes didn´t fill the album artist tag.

Even some buyed songs doesnt have the album_artist tag filled, so I think it will be a better practice to use Artist if Album_artist is not present.

**Comment by manuelglez86** [comment]
If we complicate things for our final user, they maybe will look for other software solution.

**Comment by SePHTaN** [comment]
> If Ampache really requires certain tags like album_artist to function properly, please document this somewhere.

I go with you in this aspect.
In the wiki there should be a comprehensive explanation what requirements should be fulfilled regarding the tagging of music files to get the best experiance from ampache.

> If we complicate things for our final user, they maybe will look for other software solution.
I can think of solutions to completely make it unnecessary to have tags in your music files.
Fingerprinting would be such a possibility, the audio industry would greatly appreciate,
if audio software like streaming servers or mediacenter software like kodi do upload fingerprints to identify the songs they maintain ...

I also won't call it complication. Tools like Musicbrainz-Picard are extremly easy to use.
The setup of an apache2 server in a secure manner is much more complicated and without one you aren't able to run ampache.

**Comment by xekon** [comment]
> > Not having them in your music files leads me to the assumption that you don't tag your music properly.
> 
> I tag them mostly manually and don't use Musicbrainz/Picard, because I don't like how they litter the tags with metadata I don't care about (also they are sometimes differently capitalized etc., so I would have to re-tag manually anyway).
> I don't see a need to duplicate the artist information into an album_artist tag.

I Also do my own Tagging, for the exact same reason reinerh! If musicbrainz gave me more control over how my files are tagged I *might* use it but even the I can tag my files much faster manually with my scripts.
Lachlan recently did some more work with the album_artist tag, it resolved my issue here: https://github.com/ampache/ampache/issues/2667

I use a bash script that tags my files according to my file structure, My suggestion is any files that don't have album_artist present you should set album_artist to be equal to artist.

I also suspect however that it would be better to fall back on using artist when album_artist is not present which is what @lachlan-00 probably meant to do, but I am only speculating.

**Comment by lachlan-00** [comment]
I'm going to do an update to auto fill them. They're sort of expected even though they're not commonly filled.

I'll make an update where album artist is generated and stored by grouping and count in the SQL

**Comment by lachlan-00** [comment]
update is in develop (10f362c2b) now

If you have albums without an album artist it will do two things after all catalog ADD actions

* Find all albums that are missing an album artist
  * Run sql to check if these albums have **1** artist
  * If not 1 artist run SQL to sort by which artist has the most tracks **OR** the first track if the artists all have 1 track
* Update the album with the chosen artist.

So what this means is if you run an ADD and then there is still something not right at the end of that run it will try to fill the null ones.  This isn't perfect as you should always have tags for this, but now we'll be making things a bit better by at least forcing something in there.

**Comment by mitchray** [comment]
Closing as there is a built-in workaround now
