### ISSUE TITLE
After Update from 4.2.6-release to 4.3.0 Page is solid white.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2734]
### Describe the bug
I did a clean install of Ampache 4.2.6-release Stable a couple days ago, today I click on the update for 4.3.0
After doing this it just returned a white page.

### To reproduce

1. have 4.2.6-release installed or install like this:
```
git clone -b master https://github.com/ampache/ampache/
git checkout 3e79051a730ad5329bbe5a19eff082cf050d0fa3
```
2. Click on Update for 4.3.0
3. The page will turn to solid white, and just sit there.
4. After a couple minutes you will suspect it broke, no amount of refreshing will change anything, page stays white.

### Expected behavior
I think I have seen this happen one other time but it was quite a while ago, and lachlan fixed it fast.

### Screenshots
Ampache 4.2.6-release:
![2021-02-05_14-43](https://user-images.githubusercontent.com/106644/107097026-df241e00-67c0-11eb-98bc-73aae347742d.png)

chrome after clicking to update to 4.3.0:
![2021-02-05_14-52](https://user-images.githubusercontent.com/106644/107097494-ea2b7e00-67c1-11eb-9261-4b68508a2c65.png)

## Environment

* Ampache version: 4.2.6 -> 4.3.0
* Web server + version: Nginx Latest (1.18.0-0ubuntu1)
* Server operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.44-2-pve x86_64)
* Client operating system: Ubuntu 20.04 with KDE/Plasma, Firefox 84.0.2 (64-bit)

### Client type

* Web

## Settings
`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+"`
```
+http_host = "ampache.REDACTED.com"
+http_port = "443"
+web_path = ""
+local_web_path = "http://localhost:80"
+database_hostname = "/run/mysqld/mysqld.sock"
+database_port = ""
+database_name = "ampache"
+database_username = "www-data"
+database_password = ""
+secret_key = "REDACTED"
+getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
+licensing = "false"
+artist_art_preferred_filename = "artist.jpg"
+album_art_min_width = 190
+album_art_min_height = 190
+art_order = "db,folder"
+wanted = "false"
+podcast = "true"
+debug = "true"
+log_path = "/var/log/ampache"
+log_filename = "%name.log"
+site_charset = "UTF-8"
+allow_public_registration = "false"
+cookie_disclaimer = "false"
```

## Logs

This Log covers me logging into Ampache 4.2.6-release and then clicking on the update for 4.3.0, no new info is added to the log when i visit the page, refresh the page, clearing cache does not help, using chrome instead of Firefox also does not help but gives an error code 500 instead of a blank white page.

```
2021-02-05T14:49:52-08:00 [jake] (session.class) -> i6svohalllkeabjeum2joca0n1 has been extended to Fri, 05 Feb 2021 15:49:52 -0800 extension length 3600 
2021-02-05T14:49:52-08:00 [jake] (ajax.server) -> Called for page: {index} 
2021-02-05T14:49:52-08:00 [jake] (session.class) -> Writing to i6svohalllkeabjeum2joca0n1 with expiration 1612568992 
2021-02-05T14:49:53-08:00 [jake] (autoupdate.class) -> Checking latest version online... 
2021-02-05T14:49:53-08:00 [jake] (session.class) -> Writing to i6svohalllkeabjeum2joca0n1 with expiration 1612568993
```

## Notes

I have already rolled my VM back to 4.2.6, Once a fix is in place for this I can try it again, for now I will stick with 4.2.6 until @lachlan-00 says it should be fixed.

**Comment by xekon** [comment]
@lachlan-00 The only thing I did differently from my previous ampache develop install was to use a unix socket instead of a tcp host: "/run/mysqld/mysqld.sock"

I have no idea if this could have caused it, but I can test using localhost instead of the socket if you think it could be the issue. The install went just fine using the unix socket, but possibly the upgrade is having issues with it?

If that would help I could do that test later this evening, just let me know.

**Comment by SePHTaN** [comment]
> using chrome instead of Firefox also does not help but gives an error code 500 instead of a blank white page.

Error 500 tends to be a server misconfiguration (mostly folder/file permissions).

My configuration for ampache for example is apache2 with php7.3-fpm for 4.26/4.30 and apache2 with php7.4-fpm.
So i have actually 5 virtualhosts, each running under php-fpm with an individual user for each host to isolate the hosts against each other.
I have also seen this issue with former versions of ampache. Always, in my cases, these have been folder/file permissions.
To bee honest i unzipped the releasefile and copied it over forgetting i am working as root.
After chown all files with user:group of the corresponding php-fpm virtualhost everything was fine again.

**Comment by xekon** [comment]
> > using chrome instead of Firefox also does not help but gives an error code 500 instead of a blank white page.
> 
> Error 500 tends to be a server misconfiguration (mostly folder/file permissions).
> 
> My configuration for ampache for example is apache2 with php7.3-fpm for 4.26/4.30 and apache2 with php7.4-fpm for 5.00.
> So i have actually 5 virtualhosts, each running under php-fpm with an individual user for each host to isolate the hosts against each other.
> I have also seen this issue with former versions of ampache. Always, in my cases, these have been folder/file permissions.
> To be honest i unzipped the releasefile and copied it over forgetting i am working as root.
> After chown all files with user:group of the corresponding php-fpm virtualhost everything was fine again.

Yeah hopefully thats all it was, I have read that a couple other people have upgraded without issue, so probably.

**Comment by lachlan-00** [comment]
Going to be documenting a process for staying on 4 and changing to 5/preview

Generally I've been up and back on all the branches for years and it's usually not an issue with Ampache.

We'll see who else has issues it's only been a few days so maybe others will find something to add to this issue
