### ISSUE TITLE
browse.php grid/list view options checkbox

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2736]
# Issue Template

## Description

**Describe the bug**
Just a tiny issue here but one which is confusing when viewing any of the browse.php pages.

When selecting the view options for the page, I've noticed that the grid view option checkbox seems to work in reverse?

With the grid checkbox ticked, I get the list view for the page and when unticked I get the grid view?

This seems to be working in reverse to me, I would expect the opposite behaviour.

**To reproduce**
1. Go to any browse.php page (songs, album, artists, live_stream or podcast)
2. Click on 'View' to bring up the page viewing options
3. Tick the 'Grid View' checkbox and 'List View' is actually displayed
4. Untick the 'Grid View' checkbox and 'Grid View' is displayed

**Expected behavior**
This seems to be working in reverse to my logic, when ticked I would expect to see the grid view and when unticked I would expect to see the list view.

**Screenshots**
Podcast page with 'Grid View' checkbox ticked - Actually giving the list view:
![image](https://user-images.githubusercontent.com/3216809/107116633-92961c80-686c-11eb-9179-403fb713f05c.png)

Podcast page with 'Grid View' checkbox not ticked - Actually giving the grid view:
![image](https://user-images.githubusercontent.com/3216809/107116697-ec96e200-686c-11eb-8991-e4e1898d4251.png)

## Environment

* Ampache version: Ampache develop
* Web server + version: Apache 2.4.46, MySQL 8.0.22, PHP 7.4.14
* Server operating system: Fedora 33
* Client operating system: Ubuntu 18.04.5 LTS

**Client type:**

* Web

**Comment by usox** [comment]
Fixed in source-changes.

**Comment by lachlan-00** [comment]
put in develop as well. this won't be the last backwards logic in the web ui we find
