### ISSUE TITLE
generate_config generates ampache.cfg.php.pls which is empty

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2737]
### Describe the bug

Generate config should generate and download the generated ampache.cfg.php instead of an empty ampache.cfg.php.pls (Playlist?)

### To reproduce

1. Go to 'Admin Menu/Ampache Debug'
2. Click on 'Generate Config'
3. ampache.cfg.php.pls opens in your editor of choice which is empty

### Expected behavior

Download of ampache.cfg.php correctly named and not empty

## Environment

* Ampache version: 4.30 and develop (prerelease6)
* Web server + version: Apache 2.4.38 PHP7.3-fpm/PHP7.4-fpm
* Server operating system: Debian10
* Client operating system: Win10

### Client type

* Web

**Comment by usox** [comment]
I'll have a look...

**Comment by usox** [comment]
Ok, I cannot confirm it on 4.3, source-changes and edge. @lachlan-00 Any ideas?

**Comment by lachlan-00** [comment]
i've generated and written on master, develop and source-changes right now.

I've seen bad generations before it's possible that your current config file has some kind of error that is failing to parse/complete

**Comment by wagnered** [comment]
I vaguely remember reading about a similar problem with the .pls extension but with a client file upload.  Seems to me it was an apache setting: maybe an .htaccess configuration but it might have been an Apache config problem or php.

I just tried it and was surprised that it was a standard browser download to the system defined download folder.  It did have the config content though but had the " .txt" extension.  My server is php running with the -S switch.

I assumed the word "generate" would mean that php via Curl, would download it to the config folder and report success or not.

I think I see why I'm getting the  txt extension: $Browser->downloadHeaders() has "text/plain" as the MIME type.  Does that mean that the file extension is lost/ignored and my browser(s) are appending the .txt extension?

**Comment by SePHTaN** [comment]
I poste my Server Setup, would be helpful to know what would be needed.
What i included in the attachment is: 
 ampache.cfg.php
 /etc/php/74/fpm/pool.d/ampache.cfg
 /etc/apache2/sites-available/ampache.conf
When something else is needed just tell me here.
[mysettings.zip](https://github.com/ampache/ampache/files/5943819/mysettings.zip)

**Comment by usox** [comment]
Really funny. I just tried to generate the config file with firefox and chromium - used text-mimetype and the php-mimetype in the second try. The result did not change, the file got downloaded as `ampache.cfg.php`. Maybe this is somehow related to used the browser/OS and/or maybe the webserver configuration.

**Comment by SePHTaN** [comment]
Yeah my first idea was application that is assigned for a specific MIME type in the browser.
But after looking into my browser settings i have neither for text nor php MIME type assignments.
May also have to do with system wide MIME type assignments.

But setting the MIME type "application/x-httpd-php" in GenerateConfigAction.php did the trick for with both Firefox and Chrome.
I am no specialist for mimetype questions, but maybe specifying the mimetype that matches the file overrides any browser or OS settings.

**Comment by SePHTaN** [comment]
Done a little digging : 
[IANA media-types](https://www.iana.org/assignments/media-types/index.html)
[IANA media-type octet-stream](https://www.iana.org/assignments/media-types/application/octet-stream)
According to the second link "octet-stream" would be appropriate for binary streams.

[Apache Configuration htaccess](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Apache_Configuration_htaccess)
According to the link above the file extension can be defined for a given mimetype per .htaccess file.

Don't know how this would also match for other webservers like nginx.

What i do know is that some version of joomla put a lot of mimetype definitions for mod_expires into .htaccess.

**Comment by wagnered** [comment]
interesting, apache.org suggests using `SetHandler application/x-httpd-php` even though the type is not registered. 

also, according to [apache.org](https://httpd.apache.org/docs/2.4/mod/core.html#sethandler) when   using a proxy socket the directive ends with a URL `  SetHandler "proxy:unix:/var/run/app_%{env:MATCH_sub}.sock|fcgi://localhost:8080"`. Your apache.conf doesn't have the full URL.

@SePHTaN  you are welcome to edit the wiki. Any github member can.

**Comment by SePHTaN** [comment]
@wagnered What you are writing is right if we are talking about mod_proxy.
My setup is with php-fpm using [mod_proxy_fcgi](https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html) The part: "Proxy via Handler"
So all request are passed via reverse proxy to the apache2 virtualhost. Each virtualhost has a dedicated user for php-fpm.
I use this setup since around 2010/12 after the virtualhost with apache  got hacked by somebody trying to install some mail-server i believe for sending spam mails. My fortune was i don't have mail on that server ;)

I have a little script that automates me the whole process of adding needed user and group, generating the config for the php-fpm pool, as for apache2 virtualhost, enables the site and restarts php-fpm.
All i have to do is copy over what i want to host, and of course configure/install that part.

As wiki lacks the setup for php-fpm i was thinking already to put a step by step explanation there, with the script as little goodie for the lazy ones.

**Comment by mitchray** [comment]
Closing as this references version 4.x, re-open if this still affects version 6+
