### ISSUE TITLE
API playlists action generates 500 Internal Server Error

### ISSUE THREAD

**Issue by barcoboy** [ampache/ampache#2741]
After authenticating successfully to the API, I'm trying to use it to get a list of all playlists on my server, but am receiving a 500 Internal Server Error from Apache.  Tailing the error_log file reveals the following:

PHP Fatal error:  Uncaught Error: Class 'Lib\\ApiMethods\\AmpConfig' not found in /var/www/ampache/lib/class/ApiMethods/PlaylistsMethod.php:64\nStack trace:\n#0 /var/www/ampache/server/json.server.php(85): Lib\\ApiMethods\\PlaylistsMethod::playlists()\n#1 {main}\n  thrown in /var/www/ampache/lib/class/ApiMethods/PlaylistsMethod.php on line 64

API called with the following URL:

http://FQDN.OF.SERVER/server/json.server.php?action=playlists&auth=$AUTH

If I change the action to "albums", it works fine and returns a list of all albums on my server.

**Comment by lachlan-00** [comment]
i see it's missing ampconfig 023fba5e0 puts that in

**Comment by lachlan-00** [comment]
that also explains why i was having issues with the kodi plugin and not getting anything.

fixed a few more issues in 601533e6c as well, let me know if you find anything else.

**Comment by barcoboy** [comment]
Thanks, that fixed it.

I can also confirm the KODI plugin is fixed.  I had noticed the plugin wasn't returning any of my playlists, but thought it was the plugin itself at fault, so I didn't mention it... guess I should have.  :-)

**Comment by lachlan-00** [comment]
Been a bit lax on develop lately whole working on the other branches. Thanks for reporting because this cleaned up a lot of easy fixes.
