### ISSUE TITLE
Catalogue statistics corrupted after latest commit

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2745]
# Issue Template

## Description

**Describe the bug**
After upgrading to the latest commit 8be6258ff the catalogue statistics and entries seem to be corrupted on both stats.php?action=show and #admin/catalog.php?action=show_catalogs pages.

Reverting to the previous commit 29933ea28 resolves the issue.

**To reproduce**
Steps to reproduce the behaviour:
1. Upgrade to latest commit 8be6258ff
2. View Catalogue Statistics page stats.php?action=show
3. Or view Admin Show Catalogues page #admin/catalog.php?action=show_catalogs
4. See catalogue errors and no Last Verify, Last Add or Last Cleaned dates being reported

**Expected behavior**
Catalogue statistics to be displayed as before commit 8be6258ff

**Screenshots**
Catalogue statistics before update to commit 8be6258ff
![image](https://user-images.githubusercontent.com/3216809/107513903-d0fb4680-6ba0-11eb-9300-fdada9386c75.png)
Catalogue statistics after update to commit 8be6258ff
![image](https://user-images.githubusercontent.com/3216809/107515303-c0e46680-6ba2-11eb-8387-06a469c6aba0.png)

## Environment

* Ampache version: Ampache develop
* Web server + version: Apache 2.4.46, MySQL 8.0.22, PHP 7.4.15
* Server operating system: Fedora 33
* Client operating system: Fedora 33

**Client type:**

* Web

## Logs

No errors reported in logs

**Comment by usox** [comment]
I can't switch to develop ATM so I can't test it. Cannot confirm this four source-changes/edge.

**Comment by usox** [comment]
Confirmed for 4.3, the cause is f698dbb34d9c23146ed4d5e0eb5a9cde14f8b8bb

**Comment by rsinfotech** [comment]
Thanks @usox, I have manually copied the line you modified in lib/class/catalog.class.php and can confirm that this solves the issue in the develop branch also.

Keep up the great work! Much appreciated...
