### ISSUE TITLE
Branch layouts (to be documented)

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2748]
Just taking this out of the pull into an issue. The process is about to change for how the branches are maintained.

The main development repos are going to be
* master: version = 'x.x.x-develop' (this will be where the version is decided based on what is committed from develop)
* develop: version = 'develop'
* edge: version = 'edge'

maintenance branches per major version.
* release4: version = 'x.x.x-release'
* release5 (on 5.0.0 release)
* releaseX created each major release

All future releases are tagged from the releaseX repos allowing a merge from master when the release is complete and people can stay on that release branches while a release is prepared on master.

Bug fixes for the branches will occur in the release branches and will have point releases tagged from that branch. eg 4.3.1, 4.3.2.

This will allow develop and master to continue on the next milestone without creating a large branch divergence that i've managed to create

_Originally posted by @lachlan-00 in https://github.com/ampache/ampache/issues/2722#issuecomment-773767962_

**Comment by lachlan-00** [comment]
going in here 
https://github.com/ampache/ampache/wiki/Branch-Layout

**Comment by lachlan-00** [comment]
happy with that draft now

**Comment by usox** [comment]
Looking good.

**Comment by lachlan-00** [comment]
It's been really good to put all this down and have a bit of direction again

**Comment by usox** [comment]
Really looking forward to get it all going.

**Comment by SePHTaN** [comment]
Will ampache also rename master to main?
[The new Git default branch name](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/)

**Comment by lachlan-00** [comment]
> Will ampache also rename master to main?
> [The new Git default branch name](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/)

neither really cover what the master branch is anymore
