### ISSUE TITLE
[Feature Request]  API - Add support for podcasts streams - so that kodi plugin can work with them.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2750]
I made a feature request to support podcast streams: https://github.com/ampache/ampache-xbmc-plugin/issues/11

Lusum was checking if it was possible and determined it was not because the API does not currently support it.

**Comment by lachlan-00** [comment]
240f01192 has it i develop, this issue can stay open for 4.4.0

**Comment by lachlan-00** [comment]
this is in 4.4 api now.
