### ISSUE TITLE
Replace concatenated function names by better solutions

### ISSUE THREAD

**Issue by usox** [ampache/ampache#2754]
In several places, concatenated strings are used to call certain (static) methods by `call_user_fund`. This is an anti pattern, because these calls are not traceable for IDEs what causes developers not beaing able to recognize the usage of these methods.
We'd like to collect and replace those code fragments by a better and cleaner solution

- [x] `Ampache\Repository\Model\Search` : $type_to_sql (like `artist_to_sql`)
- [ ] `Ampache\Module\Playback\Stream_Playlist`: create_$type (like `create_download`)

**Comment by lachlan-00** [comment]
There are a few calls like that which are weird and annoying.

Update_x_from_tags

It would be good to remove all of them for switches

**Comment by usox** [comment]
I believe, in most cases we can use better patterns for this. Let's use the ticket to collect all the affected code sites first and we'll see how to handle them.

**Comment by usox** [comment]
> Update_x_from_tags

I actually already replaced that one.

**Comment by usox** [comment]
And done
