### ISSUE TITLE
Group multiple disks 'off' causes album to not display

### ISSUE THREAD

**Issue by jonals** [ampache/ampache#2755]
## Description
Multi-disk album tracks display fine when Group multiple disks is set to 'on'. When set to 'off' the individual album disks do not display the album tracks, and there is an error logged:

....public/templates/show_album.inc.php:52) -> Call to a member function getAlbumSuite() on null

Set the Group multiple disks to 'on' again and the album tracks display again.

This is using ampache-5.0.0-pre-release8. Multiple disks works ok on ampache 4.2.5.

**Comment by usox** [comment]
Hi @jonals 

Thanks for reporting this, it should now be fixed in the pre-release branch.
