### ISSUE TITLE
database table for podcast_episodes is missing bitrate, rate and mode for hte podcast files

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2756]
There are some missing columns which would be good to add into podcast_epsidoes table to make them like up a bit better with songs:

* "bitrate" (bytes per second)
* "rate" (frequency, hz)
* "mode" (cbr, abr, ...)

**Comment by usox** [comment]
@lachlan-00 I'd like to defer this until 5.1 "ampache podcast party update". Any vetos?

**Comment by lachlan-00** [comment]
> @lachlan-00 I'd like to defer this until 5.1 "ampache podcast party update". Any vetos?

Not from me. It's an enhancement so it can wait

**Comment by usox** [comment]
And done. Will be available after merging my podcast branch into edge

![podcast_episode_bitrate](https://user-images.githubusercontent.com/5184763/115451009-eafa7a80-a21c-11eb-9539-583f51247b8a.png)

**Comment by lachlan-00** [comment]
set in 6
