### ISSUE TITLE
No, it is not a plugin's bug, the server doesn't send podcast total number

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2758]
No, it is not a plugin's bug, the server doesn't send podcast total number

_Originally posted by @lusum in https://github.com/ampache/ampache-xbmc-plugin/issues/11#issuecomment-780406447_

**Comment by xekon** [comment]
Awesome, looking forward to this one.

**Comment by lachlan-00** [comment]
Just have to add all the counts to ping and handshake probably tomorrow now but it's not huge as the counts are there now, just need to be added to the methods

**Comment by lachlan-00** [comment]
added in a4355cc56

**Comment by xekon** [comment]
Awesome! Thank you!

**Comment by xekon** [comment]
Just Tested, works great.

**Comment by lachlan-00** [comment]
@xekon i've (i think) finished api 4.4.0 can you please have a test on kodi for me?

I've done a lot of work in the master branch today and think we're basically done.

**Comment by xekon** [comment]
Yes, will test now, will report back within an hour.

**Comment by xekon** [comment]
Ampache Master: c680136db9ebfea3013029d93a37f8cfb09462ea

ampache-xbmc-plugin 7f0a484102c3cb9499f6ff446eff28d55869bb9c: https://github.com/ampache/ampache-xbmc-plugin/tree/2.0  

Browsing and playing from both Smart Playlists and Podcasts is working without issue on my systems.

Anything else in particular that I should check on?

**Comment by lachlan-00** [comment]
no, just as long as it's looking okay to you that's all
i want to start testing now and get this out in the next week so just let me know in a new issue if you see anything odd

**Comment by xekon** [comment]
sure thing!
