### ISSUE TITLE
API: playlists, podcasts and videos need to be added to rate method

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2759]
playlists, podcasts and videos are missing
They will also need rating made available in responses

**Comment by lachlan-00** [comment]
Don't forget podcast_episode too

**Comment by usox** [comment]
Thank god I haven't transformed the rate method in edge yet.

**Comment by lachlan-00** [comment]
Gotta check flag as well...

**Comment by lachlan-00** [comment]
changes in 4.4.0-develop and source-changes
