### ISSUE TITLE
Ampache xml api returns every smart playlist on action playlists and every filter

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2760]
### Describe the bug

Ampache xml api returns every smart playlist on action playlists and every filter.
The bug is present in 4.3.0 -4.4.0 (demo server ) and 5.0

### To reproduce

Create some public smart playlists

Call:
http://.../ampache/server/xml.server.php?action=playlists&auth=...&limit=5000&filter=nv
( filter is nv but could be any kind of text )

### Expected behavior

Only the playlists matching the filter should show up

## Environment

* Ampache version: 4.3- 4.4 ( demo server ) - 5.0
* Web server + version:
* Server operating system:
* Client operating system: every client

**Comment by lachlan-00** [comment]
I just did a filter of zzzzzzzzzzzzzzzzzzzzzx and still got some smartlists so def not filtered

**Comment by lachlan-00** [comment]
there's an error i need to look up
```
[demo] (Core) -> 'smart_playlist' not found!
```

**Comment by lachlan-00** [comment]
demo is consistently returning 3 lists. my sites aren't anymore

this is the query generated, the limit isn't part of the query so this is weird
```
2021-02-18T17:07:48+10:00 [user] (Playlist) -> get_playlists query: SELECT `id` FROM `playlist` WHERE `name` LIKE  '%aagggggggggggggggggggg%'  ORDER BY `name` 
2021-02-18T17:07:48+10:00 [user] (Playlist) -> get_smartlists SELECT CONCAT('smart_', `id`) AS id FROM `search` WHERE `name` LIKE  '%aagggggggggggggggggggg%'  ORDER BY `name`
```

**Comment by lachlan-00** [comment]
FOUND IT! there's an OR in there that's not taken care of
```
SELECT CONCAT('smart_', `id`) AS id FROM `search` WHERE `user` = ? OR `type` = 'public' AND `name` LIKE  '%nfghfhv%'  ORDER BY `name`
```

**Comment by lachlan-00** [comment]
fbd26a7c8 and 6f8196b0d have these fixed up now
