### ISSUE TITLE
[Feature Request] Make Customizable login background fit browser window

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2761]
## Describe what you don't like about Ampache, or what it is missing
I really like the cusomizable background feature, but it has one downside.
If the picture one can supply doesn't match the resolution of your monitor it's cropped or repeated.

## Describe how you would like the feature to work**
I would like if the picture only has to have the correct aspect ratio and then be shown fullscreen.
Maybe also customizable wether to match screensize or not;

## How i suggest this can be achived
```
@@ -545,6 +545,10 @@ public static function show_query_stats()

    public static function show_custom_style()
    {
        if (AmpConfig::get('custom_login_background')) {
            if (AmpConfig::get('login_background_fullscreen')) {
                echo "<style> body { background-image: url('" . AmpConfig::get('custom_login_background') . "') !important; background-repeat: no-repeat; background-attachment: fixed; background-size: cover; }</style>";
            } else {
                echo "<style> body { background-image: url('" . AmpConfig::get('custom_login_background') . "') !important;  }</style>";
            }

        if (AmpConfig::get('custom_login_logo')) {
            echo "<style>#loginPage #headerlogo, #registerPage #headerlogo { background-image: url('" . AmpConfig::get('custom_login_logo') . "') !important; }</style>";
        }

```
The config option to switch this feature on/off isn't really needed, but would give the ability to use tiled patterns.
I am currently using this modification on my [server ](https://newampache.sandmann.dd-dns.de/) cause the animated gif with an turntableplayer has only 600x340px.

Stephan

**Comment by mitchray** [comment]
My opinion would be to just have all backgrounds full screen cover by default as that seems to be the expectation nowadays

```
background-position: center;
background-size: cover;
```

Then the situation would become if someone _needed_ it to be tiled they can always override it manually as you did or with something like the Stylish CSS extension

**Comment by lachlan-00** [comment]
i'm happy with cover, just added it to my page.

will center affect anything if we use cover?

**Comment by mitchray** [comment]
Center will trim all edges of the image equally as needed, opposed to always showing the top-left and revealing towards bottom -right

Of course it all depends on the image being used, but generally speaking the region of interest is going to be around the center

**Comment by SePHTaN** [comment]
> My opinion would be to just have all backgrounds full screen cover by default as that seems to be the expectation nowadays

Your solution is definitely the better way, already changed it in my installation :)

**Comment by usox** [comment]
Added in source-changes. I did not add a config option as from my POV the old behavior is not optimal. If someone want to have the old behavior back, we still can discuss adding a config option.
