### ISSUE TITLE
Wma track tag ignored on import

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2764]
@lusum can confirm

Tested with https://archive.org/details/Synthetic_-_Colorsmoke_EP-20k217-2007

Tracks show up as 0
![Screenshot_20210219-205327_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/108495627-c190a180-72f4-11eb-9365-23553068aedc.jpg)

**Comment by wagnered** [comment]
By "import" do you mean into an Ampache catalog? or "from an Ampache catalog into kodi via a plugin? or both? In #2762 I alluded to the fact that getID3 does not handle wma/wmv files.  Only the ms .asf extension is accepted.  But the comment for `getid3_tag_order` implies that if it's not listed, it will be added anyway.  I did not confirm that but the empirical evidence supports the assumption.

**Comment by lusum** [comment]
I confirm the bug

**Comment by lusum** [comment]
> By "import" do you mean into an Ampache catalog? or "from an Ampache catalog into kodi via a plugin? or both? In #2762 I alluded to the fact that getID3 does not handle wma/wmv files. Only the ms .asf extension is accepted. But the comment for `getid3_tag_order` implies that if it's not listed, it will be added anyway. I did not confirm that but the empirical evidence supports the assumption.

Import means added in an Ampache catalog.

**Comment by lachlan-00** [comment]
fixed with 15263dccd

**Comment by wagnered** [comment]
boy, i sure was wrong on this one.  I evidently searched through the wrong getID3 module. oh, well hurray for teamwork.
