### ISSUE TITLE
Gathering art from media files broken?

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#2765]
## Description

Since one of latest updates I can't seem to add new artwork for **some** albums.
I just have tested this with a new catalog which only contains 12 albums. From these 12 albums 11 have artwork contained in the mp3 files themselves. Since I like to add the cover images to every single mp3 file I have set
```
art_order = "db,tags"
```
in my Ampache config file. No limits to the image dimensions are given. This used to work without a hitch in the past, but if I trigger a catalog update (no difference between using the command line or the web interface) now I only get entries in the image table of the database for 6 album (should be 11).
It seems to me that ampache maybe has problems with reading some kind of image or image type? 

The log file shows entries like this:

```
2021-02-19T17:40:36+01:00 [ampache] (catalog.class) -> Gathering art for album/17456... 
2021-02-19T17:40:36+01:00 [ampache] (art.class) -> Searching using:["db","tags"] 
2021-02-19T17:40:36+01:00 [ampache] (art.class) -> Method used: gather_db 
2021-02-19T17:40:36+01:00 [ampache] (art.class) -> Method used: gather_tags
```

But these do not result in images being added, they don't show errors of any kind either.

### Expected behavior
Images should be taken from the mp3 files and added to the image table of the database.

## Environment

* Ampache version: 4.3.0
* Web server + version: Apache 2.4.46
* Server operating system: Fedora 33
* PHP 7.4.15 (with imagick module activated)

### Client type

* Web
* Ampache
* SubSonic

## Settings

```
max_upload_size = 1048576
album_art_min_width = none
album_art_max_width = none
album_art_min_height = none
album_art_max_height = none
resize_images = "false"
art_order = "db,tags"
```

Any help would be greatly appreciated!

**Comment by xekon** [comment]
I seemed to have the same problem: https://github.com/ampache/ampache/issues/2303

I do not have the issue if I update via command line:

`sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -a -g`

You could give that a try and see if your results are any different.

**Comment by arno1979** [comment]
Thanks for the reply! I read your issue before posting mine though.
I always use the command line to update my catalogs and it makes no difference in my case.

**Comment by arno1979** [comment]
I kept digging a little and I maybe found the source of the problem thought I can't exactly figure out WHY the problem occurs:

1.  Instead of gathering artworks from the mp3 files themselves I tried using the "folder" method: I placed a file called "folder.jpg" in the album directory, changed the "art_order" configuration and this seems to work. I did this to rule out the possibility of something being wrong with the image files (or image data). So no problem there.
2. Then I looked at the `gather_media_tags` function in the `Art` class. On line 1794 two strings are compared that have something to do with a "picturetypeid". And as these two strings don't seem to match in most of my cases the artwork is not gathered from the media files.
I lack the knowledge of exactly what these strings are, why they are compared and why the don't seem to match (anymore) but maybe someone else has more insight.

**Comment by wagnered** [comment]
`[Id3.org](https://id3.org/id3v2.3.0#Attached_picture)  designates picture type IDs (total 21) as  numeric strings that indicates that a picture is a cover, artist, composer, etc. so Ampache logic dictates that an artist image only replaces another artist image.  Likewise with a cover image.  Ampache currently has the capability of displaying only those 2 type of images (artist: 8, cover: 3).

if I rember correctly, if there are more than one picture of a type, the first one that fits the config specs will be imported.  if it is manually imported on the album page, then all images will be displayed for choosing the best one

Most tagging (gui) apps allow embedding of 1 picture of type 3(cover).  Easytag allows multiple pictures as defined in the id3v2.3 informal standards but limits the entries to a drop-down list.  "A bright colored fish" is $11(hex) on the id list.

**Comment by arno1979** [comment]
Thanks for the explanation @wagnered.
But as far as I can tell from my search for the reason of the gathering of images from tagged mp3 files not working anymore the comparison in its current form prevents new images from being added from media files:
 I noticed this because in the past it was already difficult to replace images already present in the database with new ones. For this to work I had to manually delete entries matching the given `object_id` from the `images` table. Then I could run the catalog update and new images would be gathered.
This has ceased from working with the 4.3.0 release. When I delete entries from the `image` table and run the catalog update no new entries are being added. Nothing happens.

**Comment by wagnered** [comment]
>  it was never relevant until the 4.3.0 release which introduced the if comparison mentioned above.

Yes, and Ampache generally ignored artist images in file tags until Spotify was added to the list as an "off-the-rack" replacement for last.FM which stopped providing artist images some-time back.  I added the "picturetypeid" as an intermediate step to display other types of images.

**Comment by lachlan-00** [comment]
i've taken that check out for 4.4.0 it's still part of 5 though which is where the change will get documented.
This was due to me copy/pasting and having such diverged branches which we're working to avoid
