### ISSUE TITLE
advanced_search / search.php error

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2769]
As reported by @mitchray 

Run a search
```
/server/json.server.php?action=advanced_search&auth=auth&type=artist&rule_1=artist&rule_1_operator=2&rule_1_input=Prodigy
```

Get the kitchen sink in responses dure to this error
```
2021-02-20T15:02:38+10:00 [ampache] (log.lib) -> [Runtime Error] Invalid argument supplied for foreach() in file /var/www/ampache/lib/class/search.class.php(1548) 
2021-02-20T15:02:38+10:00 [user] (Search) -> SQL get_items: SELECT DISTINCT(`artist`.`id`), `artist`.`name` FROM `artist`  ORDER BY `artist`.`name` 
```

**Comment by lachlan-00** [comment]
Ahh, i see, this is actually just a bad request. there is no artist rule called artist. you want title
```
&type=artist
&rule_1=title
&rule_1_operator=2
&rule_1_input=Prodigy
```

rule_1=artist is only valid for song,album searches

**Comment by lachlan-00** [comment]
@mitchray  i've put a semi fix in 0f6181417 to stop searching on bad rules.

When you put in incorrect rules just return an empty array instead. this says to me i need to split those rules up into types instead of one big table.

**Comment by lachlan-00** [comment]
@usox this is added in 8f2885217

**Comment by mitchray** [comment]
Ah OK, thanks for clarifying

**Comment by lachlan-00** [comment]
it took me a while to realise so it needs expansion/better docs for 5

**Comment by mitchray** [comment]
My mistake was thinking it was 1-to-1 to the smart playlist search, with the 'type' being the desired return objects

**Comment by lachlan-00** [comment]
The types for each rule are listed here which is how I twigged.
 http://ampache.org/api/api-advanced-search

Do you think it would be better to split the first table up instead of relying on looking up based on the 'valid item's column

**Comment by mitchray** [comment]
Yeah I think that would make it easier to follow
