### ISSUE TITLE
[Feature Request] OAuth2

### ISSUE THREAD

**Issue by Dirk23** [ampache/ampache#2770]
Hi,

we are developing [Amperfy Musik](https://apps.apple.com/app/amperfy-music/id1530145038#?platform=iphone), a iOS App, for Amapche. We would like to integrate the App into the HomePod. To get this done, Ampache needs to support OAuth2. 
Here is a Techtalk Video by Apple, describing how it will work: https://developer.apple.com/videos/play/tech-talks/10854. The app creates a configuration. Then the app writes the configuration to the HomePod. In the configuration it says that if Siri recognizes the app as a target, the requests should be sent to the configured URL (video 8:30, example at 9:30). For this to run securely, Ampache must support OAuth2 so that access is protected.

Is it possible to have OAuth2 Support in Amapche?

Thanks in advance.

Dirk und Maximillian

**Comment by izyspania** [comment]
any news on this?

**Comment by Dirk23** [comment]
No. It is unfortunately more complicated than first thought.
