### ISSUE TITLE
Ampache with php-8.* uninstallable and other problems.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2773]
'Tons' of problems.  Tried fresh install of 4.2.5 release source. Had to upgrade the Spotify package to ^4.0. before composer was happy. Then  couldn't get past `session_set_save_handler` in Session::_auto_init().  Arrays are no longer callable.  The parameters for `session_set_save_handler` must be objects, or user defined/anonymous functions.  This is according to the [PHP-8.\*.\* migration notes](https://www.php.net/manual/en/migration80.php).  @usox , Should the 8.0 migration be done on Ampache "^4.0.0"?  If so, I'll leave it to you as I'm sure you can do it much more efficiently.

I don't understand how @BoBeR182 (#2762) got it running at all unless he somehow did a "rolling upgrade".

**Comment by wagnered** [comment]
Got the first problem solved: created a session handler class and modified `session_set_save_handler` to use it per the php.net documentation.

Second problem:  during the install, `split_sql($query)` is not functioning correctly with php-8.0.  I reverted to php-7.4 and there was no problem installing, except thar it did not present me with the list of required updates as earlier versions did. I was on master4 so that might have been a recent feature addition.

BTW gotta take the time to add both php versions to the update_alternatives db.  it's getting tedious switching back and forth.

**Comment by usox** [comment]
@usox , Should the 8.0 migration be done on Ampache "^4.0.0"? If so, I'll leave it to you as I'm sure you can do it much more efficiently.

I think no, not even with 5. Full support of php8 will take quite some time and shouldn't be a showstopper for a 5 release. I'd say, we should consider 5.1 to be the php8-supporting release. Starting with 5.1, we will have full unittest coverage for all apis - this will make the migration much easier for us to accomplish.
I already made some changes in source-changes regarding the php8-compatibility, though. This includes the session-save-handler change you mentioned.

**Comment by wagnered** [comment]
Ok, if that's the case, Shouldn't the version be checked using composer.json or Ampache's test logic to stop install or execution if php-8 is encountered?

**Comment by lachlan-00** [comment]
I've put 7.4 || 8 in docs so will need to update that.

The check is just less than check for a minimum version so it would need to enforce a high check as well.

**Comment by usox** [comment]
> Ok, if that's the case, Shouldn't the version be checked using composer.json or Ampache's test logic to stop install or execution if php-8 is encountered?

As we currently don't have any automated checks/tests which require 8.0, it shouldn't be a problem to make the following changes to the php-requirements in composer.json:
- 4.x: ^7.1
- source-changes: ^7.4
- edge: ^7.4||^8.0

**Comment by wagnered** [comment]
Couldn't finish the insert database step because of fatal error: Learned that PHP-8.0 error mode for pdo data objects has changed from "silent" to "exception". So the problem was never noticed before.  Added logic to read thru the license part of ampache.sql with `fgets` function then resumed with `fread` on the same file pointer.

I think php8.0 will be uncovering a lot of questionable coding.

**Comment by GieltjE** [comment]
Composer doesn't even want to run with a clean develop git branch (gentoo php 8):

```
sudo -u apache composer install --prefer-source --no-interaction
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - jwilsson/spotify-web-api-php is locked to version 3.6.2 and an update of this package was not requested.
    - jwilsson/spotify-web-api-php 3.6.2 requires php ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 2
    - oomphinc/composer-installers-extender is locked to version v1.1.2 and an update of this package was not requested.
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - robloach/component-installer is locked to version 0.2.3 and an update of this package was not requested.
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 4
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 5
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - happyworm/jplayer 2.9.2 requires robloach/component-installer * -> satisfiable by robloach/component-installer[0.2.3].
    - happyworm/jplayer is locked to version 2.9.2 and an update of this package was not requested.
```

**Comment by wagnered** [comment]
@GieltjE , I've already accounted for those issues in my testing:

Ampache v4.*.* Requires composer 1.* and you are running composer v2.*.

And the spotify package requires upgrading to ^4.0.

But that still won't get any version of Ampache running with php-8.0.  There are too many backward **incompatible** issues.  And many are going to be database access issues.  I recommend that you install php-7.4 if you can.

**Comment by wagnered** [comment]
in Repository.php   `getRecords($table, $field = array(), $value = null)` an array of item[0]=>null is passed in `$statement = Dba::read($sql, is_array($value) ? $value : array($value));` but `$this->assembleQuery($table, $field)`  doesn't correctly prepare the statement (no tokens are added.)
 
So  I changed the Dba::read statement to:
  `$statement = Dba::read($sql, !is_null($value) ? array($value) : null);`

I'm thinking that the silent fail(default error mode) of pre php-8 versions, might be affecting search results.

**Comment by usox** [comment]
I took care of the composer installation issues in edge now.

I'd say, tons of problems will pop up in future. Many issues (warnings/notices) are currently suppressed/ignored but some of them became errors in php8. These errors now start to show up in the error logs (like access to non-existing array-keys `Undefined array key "latitude" in file /www/src/Repository/Model/Song.php(2089)` and such).
It will be really hard to fix all those issues by clicking around in the software, because no one will cover all those edge cases hidden in the complexity of ampache.

From my pov, the best/only way is a complete rewrite which includes automated tests which is a decent investment in the future of the software - instead of manually searching for issues which will take quite some time and  has little outcome.

Fyi: Most of the json/xml api is safe in edge - about 80% - are already covered by those tests and don't have any issues with php8.

**Comment by wagnered** [comment]
Well that might be good to know: I can get back to my pet project.  But doesn't the fact that end of life for php-7.4 being Nov 2021 enter into the equation?

**Comment by usox** [comment]
> But doesn't the fact that end of life for php-7.4 being Nov 2021 enter into the equation?

That in fact is a problem - so we definitely have to hurry up. About 10% are covered atm so the first step is done. Maybe we have to develop some strategies to split up some hard-to-refactor parts from the rest - dunno, this definitely has to be discussed.
I'll finish the api work within the next days and will start with the subsonic api...

**Comment by BoBeR182** [comment]
I had ampache installed from the Arch repo, and just updated my PHP7.4 to PHP8

**Comment by ibmibmibm** [comment]
An error pop up while updating my database after rebased to current develop branch. After some debuging, seems that `PDOStatement` cannot implicit converted to `boolean` now.

```diff
diff -rup a/lib/class/update.class.php b/lib/class/update.class.php
--- a/lib/class/update.class.php        2021-02-27 19:07:00.294628111 +0800
+++ b/lib/class/update.class.php        2021-02-27 19:22:19.550946510 +0800
@@ -1416,7 +1416,7 @@ class Update
         $retval = true;

         $sql = "ALTER TABLE `podcast_episode` MODIFY COLUMN `time` int(11) unsigned DEFAULT 0 NOT NULL; ";
-        $retval &= Dba::write($sql);
+        $retval &= (bool)Dba::write($sql);

         return $retval;
     }
```

**Comment by nearwood** [comment]
> An error pop up while updating my database after rebased to current develop branch. After some debuging, seems that `PDOStatement` cannot implicit converted to `boolean` now.
> 
> ```diff
> diff -rup a/lib/class/update.class.php b/lib/class/update.class.php
> --- a/lib/class/update.class.php        2021-02-27 19:07:00.294628111 +0800
> +++ b/lib/class/update.class.php        2021-02-27 19:22:19.550946510 +0800
> @@ -1416,7 +1416,7 @@ class Update
>          $retval = true;
> 
>          $sql = "ALTER TABLE `podcast_episode` MODIFY COLUMN `time` int(11) unsigned DEFAULT 0 NOT NULL; ";
> -        $retval &= Dba::write($sql);
> +        $retval &= (bool)Dba::write($sql);
> 
>          return $retval;
>      }
> ```

I have this same issue with `4.4.1-release`. Attempted to set `PDO::ATTR_ERRMODE => PDO::ERRMODE_SILENT` on PDO init, but that doesn't seem to work. From the comments above, it looks like edge is closer to resolving PHP8 issues?

**Comment by nearwood** [comment]
@ibmibmibm I have the same issue. It appears to be all the implicit casts in the update file. Did you work around it?

**Comment by martadinata666** [comment]
Just add some deps issue on composer with php8, in mean time php 7.4 still fine.
```
> [linux/amd64 9/9] RUN composer install --prefer-dist --no-dev --no-interaction && composer clear-cache:
#15 0.583 Verifying lock file contents can be installed on current platform.
#15 0.630 Your lock file does not contain a compatible set of packages. Please run composer update.
#15 0.631 
#15 0.631   Problem 1
#15 0.631     - jwilsson/spotify-web-api-php is locked to version 3.6.2 and an update of this package was not requested.
#15 0.631     - jwilsson/spotify-web-api-php 3.6.2 requires php ^7.0 -> your php version (8.0.10) does not satisfy that requirement.
#15 0.631   Problem 2
#15 0.631     - narrowspark/http-emitter is locked to version 1.0.0 and an update of this package was not requested.
#15 0.631     - narrowspark/http-emitter 1.0.0 requires php ^7.2 -> your php version (8.0.10) does not satisfy that requirement.
#15 0.631 

```

[http-emitter changelog](https://github.com/narrowspark/http-emitter/blob/main/CHANGELOG.md) min 2.0.0
[spotify-web-api-php changelog](https://github.com/jwilsson/spotify-web-api-php/blob/main/CHANGELOG.md) min 4.0.0

**Comment by lachlan-00** [comment]
fully supporting and running on php 8 now and the composer lock is not forcibly set with the branch (only on releases)
