### ISSUE TITLE
[Question/Enhancement] Winamp Client Plugin possible?

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#278]
I'm using the Winamp Media Player since ages; and now since I'm running Ampache and see how fast it is in search operations and so on, I was asking myself if there is a client plugin for Winamp to search Ampache libraries and play selected Songs etc. etc.

So I've searched on Google but really got no answer... I mean Ampache is one of the oldest streaming applications and Winamp is one of the most used Media Players... And there is no plugin?

So my Question: Does anyone, of this awesome Community, have any knowledge about a working plugin for the last Version of Winamp or the experience and motivation to create one?

**Comment by Afterster** [comment]
@Psy-Virus there was some improvement on UPnP backend few weeks ago, maybe it fixed your Winamp issue?

**Comment by Psy-Virus** [comment]
If I really have to follow only these instructions:

+    You must enable UPnP Backend in System settings.
+    You must also enable Use beautiful stream url in Streaming settings.
+    PHP Socket mod must be enabled
+    You should broadcast the server periodically calling http://localhost/ampache/upnp/?btnSend=Send+SSDP+broadcast or php bin/broadcast.inc with a cron (every 1-2 minutes recommended).

then no. It's still the same behaviour like before. Winamp can see local Winamp and the Winamp on the virtual machine but not Ampache.
But you said, you got it working with Winamp, UPnP and Ampache.

Is it still working on your side? If yes, pls tell me, what you've done that it does work :-D
I have no Firewalls activated, the UPnP Broadcast says "all's fine" And PHP Sockets Support is enabled. In Ampache the settings are also okay....
(?.?)

**Comment by Afterster** [comment]
This looks ok for me. I do the exact same thing but call the broadcast through the web page every seconds (http://localhost/ampache/upnp/?btnSendAuto=Send+SSDP+broadcast+every+second).
Then Ampache show up in Winamp as you can see in the screenshot bellow.
![winamp_ampache_upnp](https://cloud.githubusercontent.com/assets/2251352/5886959/826271fe-a3b7-11e4-8f27-e2e4935c04a2.png)

**Comment by Psy-Virus** [comment]
Okay, I've installed a fresh Ampache on the same machine but different path. Also other rights from Apache. It is working. I gave the same rights to the standard installation and reset the config for it (file and database) and it's not working. The FS rights are also the same... I don't get it.

It's definitely no Ampache issue, but what could it be?

The server also is displayed on upnp inspector on a virtual machine but no options for what is possible, only that it's there and a few details about it.
That's strange.
I bet it's something extremely simple.

**Comment by Afterster** [comment]
Mhh ok, good to know it should be a configuration issue on your side :)
I'm not aware about such issue, maybe you can copy/past both your working and not-working apache configuration? What looks like the final local Ampache url in both case?

**Comment by Psy-Virus** [comment]
Well, it was the local_web_path...
After commenting it, it's working.

As I said, it was something simple. Hours of checking configs and so on... :-D

And the best of all is, Winamp or the upnp plugin dies by loading the database...
Woohooo, all discussion and work for nothing :-D

I hope Winamp will sometime be further developed, so there may be more interest for a native Ampache client-plugin.

But thx anyway @Afterster!

**Comment by Afterster** [comment]
Hehe ok. That was not for nothing, at least Ampache now has a native UPnP backend in PHP only ;)

**Comment by Psy-Virus** [comment]
Yes sry, I meant the discussion and work for that config mistake I made :-D
The UPnP backend is awesome^^
