### ISSUE TITLE
[Feature Request] API - Add 'album artist' as valid item for advanced search

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#2780]
Currently no way to search by album artist via advanced search, only artists in general

![Screen Shot 2021-03-01 at 8 41 59 am](https://user-images.githubusercontent.com/5735900/109434651-6e43ef00-7a6a-11eb-909a-2defe9e9df8e.png)

'Artists' action has 'album_artist' flag but doesn't support regex etc like advanced search does

**Comment by lachlan-00** [comment]
it's probably better to make it a search type rather than adding it to the methods as a parameter

**Comment by lachlan-00** [comment]
done
