### ISSUE TITLE
[Feature Request] API - add 'release type' to album

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#2781]
Wondering if the release type can be added to 'album', and if that information is obtainable somehow so we can output in that specific order if needed

![Screen Shot 2021-03-01 at 8 32 31 am](https://user-images.githubusercontent.com/5735900/109435204-6df92300-7a6d-11eb-9a91-3a62722be401.png)

Currently unable to group albums from API by release like below

![Screen Shot 2021-03-01 at 8 34 58 am](https://user-images.githubusercontent.com/5735900/109435199-6afe3280-7a6d-11eb-829b-9bba2c5f77ab.png)

Album
```
"id": "",
"name": "",
"artist": {},
"time": 0,
"year": 0,
"tracks": [],
"songcount": 0,
"disk": 0,
"genre": [],
"art": "",
"flag": 0,
"preciserating": 0.0,
"rating": 0.0,
"averagerating": 0.0,
"mbid": ""
"releasetype": "ep"
```

Release types (perhaps not tied to anything specifically, so it could be used in multiple places like search results)
```
"releasetypes": ["album", "ep", "single", "live", "compilation"]
```

**Comment by mitchray** [comment]
Closing as I found a workaround

**Comment by wagnered** [comment]
@mitchray , I've been working on writing the MusicBrainz data to files.  "Release type" should be imported from mp3s.  I noticed there's a problem grabbing it from the `_cleanup_vorbiscomment($tags)` function for flac and Vorbis files.

So it's really a bug fix that is needed and I have made the necessary changes: it will be included in my current PR.

**Comment by mitchray** [comment]
I wonder if we are talking about different things, you're mentioning file tags but I am/was trying to get a config setting via the API
