### ISSUE TITLE
Addressing continuing design issues of source-changes.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2785]
Now that the "Source-changes, bugs and errors" issue has been closed, how and where would design changes be suggested, questioned, or offered?  For example RequestParser cannot handle xml passed directly from an XmlHttpRequest?  There is nothing in the wiki about these things.  Is it ok to continue using the $_REQUEST global directly, for example?  RequestParser does handle the $_REQUEST global, but I don't understand how execution avoids the INPUT_POST and INPUT_GET checks.  They filter out tags.

 I think this issue was closed prematurely. IMHO Source-changes hasn't been adequately alpha/ beta tested.  I think design (not bug) issues remain and should be encouraged to be discussed, perhaps with reference to the develop branch now. Maybe a new issue referencing #2574 could be created, Or possibly the Ampache develop group would be appropriate, but which seems to be largely avoided by the team.

**Comment by lachlan-00** [comment]
We can continue here. There is a lot more to get done before moving into master and that issue was more about bugs than design. There are also still things that need documentation and further fleshing out.

My reason for the merge is the major divergence between develop, master and source-changes has just gotten too large to follow. The develop branch was never going into master due to the breaking changes for 4.x and source-changes incorporated all the changes in develop already.

For me day to day, this branch is ready and we need more eyes and opinions on the code.

**Comment by usox** [comment]
Hi @wagnered 

Took me some time to compose a reply here, especially as I took it as a fundamental criticism of my approach.

> Now that the "Source-changes, bugs and errors" issue has been closed, how and where would design changes be suggested, questioned, or offered? For example RequestParser cannot handle xml passed directly from an XmlHttpRequest? There is nothing in the wiki about these things. Is it ok to continue using the $_REQUEST global directly, for example? RequestParser does handle the $_REQUEST global, but I don't understand how execution avoids the INPUT_POST and INPUT_GET checks. They filter out tags.

Well depends.
First of all: This `RequestParser` is/was just some sort of temporary solution for 1-2 code locations which parsed the input the way the RequestParser does now - I needed it to make those locations testable. As I found out later, it was only used to parse some integer values, I already dropped it in edge and replaced it by simple `int` casts.

If you're writing new classes for gui actions (like those actions within the `Ampache\Module\Application`-namespace), I recommend to access the request data by the methods the PSR-7 ServerRequestInterface provides (`getQueryParams` for GET-data, `getParsedBody` for POST-data; other methods exists to access cookie data, uploaded files, ...). This way, you'll be able to write testable code - accesing superglobals (REQUEST, POST, GET, ...) is not recommended - hard to test and I expect them to be deprecated/removed in future php versions.
PSR-7 is _the_ standard for request/response message processing in php (https://www.php-fig.org/).

All other location which don't directly perform gui-input handling/gui rendering are mostly untouched. Using superglobals like REQUEST may be ok - these files will be refactored sooner or later.

> I think this issue was closed prematurely. IMHO Source-changes hasn't been adequately alpha/ beta tested. I think design (not bug) issues remain and should be encouraged to be discussed, perhaps with reference to the develop branch now. Maybe a new issue referencing #2574 could be created, Or possibly the Ampache develop group would be appropriate, but which seems to be largely avoided by the team.

Regarding the single issue, I don't agree with you. The issue became way too big and messy - I'd appreciate single issues for every issue we find.
Those `design issues` you're referring to exist and will exist until we start to make fundamental changes. The things I've done in source-changes are the first step to disentangle some code pieces and add an abstraction between input parsing/rendering and the logic/data layer of the software - no more, no less.

The first real "design"-change will be the introduction of an orm. But before this could be achieved, the `business-logic` must be separated from rendering/data-juggling and that's what I've started in source-changes and now continuing in edge.
Another big design change (and a wish of mine) would be the extraction of the media info parsing (id3 and such) into a separate library which we require by composer. But this should be discussed elsewhere (like you said). 

Regarding the current state of develop and alpha/beta-testing, well: make a suggestion how this should could be accomplished. From my pov, it does not make sense to start a planned test as long as @lachlan-00 hasn't finished building the things he wants to add to 5.0 (which is quite a list... https://github.com/ampache/ampache/milestone/11).
It could be worthwhile to create a simple test-plan with manual tasks (expected result and actual result) which should be performed by us/me.

**Comment by wagnered** [comment]
@usox No, it wasn't intent as a criticism. Just a direct question in my attempt to ***understand conceptually***.  As for discussions, I only recently became aware of the "discussion" tab when I logged into my own github Ampache fork. The notice was in big letters after login.  That would probably be the 'forum' to discuss design/layout/testing issues.

>  This RequestParser is/was just some sort of temporary solution....

Didn't realize that at the time.  Will follow up on your suggestion about PSR-7 library.

I am amazed and grateful for how much i've been learning, conceptually, from your work: where you've taken it and your vision for Ampache's destination.  The challenge is that at my age, I don't know if time will allow me the opportunity to gain enough knowledge  to make the suggestions you request.  🙂

Thanks for taking the time to comment.

**Comment by usox** [comment]
> > This RequestParser is/was just some sort of temporary solution....
> 
> Didn't realize that at the time. Will follow up on your suggestion about PSR-7 library.

Just fyi @wagnered: https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php

The interface contains some doc related to getQueryParams/getParsedBody. In our default usage scenarios, `getParsedBody` returns an array indexed by the parameter name in the body.
`getQueryParams` returns an array containing all the data from the query string, also indexed by the paremeter name.

e.g. POST or GET to `http://some-ampache-instance/podcast.php?action=show&podcast_id=42` would result in `getQueryString` returning the following array:
```php
[
  'action' => 'show',
  'podcast_id' => 42
]
```

**Comment by lachlan-00** [comment]
In pluginEnum there is a list constant
![image](https://user-images.githubusercontent.com/1305249/112251856-b93ad600-8ca7-11eb-8c3d-488ea2ad2cf4.png)

does that mean when people are making their own plugins that they will not be allowed to use them without updating the constant?

**Comment by usox** [comment]
At the moment? Yes - but don't consider it as a mid/long term solution. My plan is to make plugins really `pluggable`, meaning: building a system which registers available plugins (e.g. after running composer) in a certain manner. This would allow to separate all the plugin code from the ampache core (maybe move it into a complete own repository) and allows users to require external plugins by just adding them as a composer requirement (or maybe drop the code to a certain location).

**Comment by lachlan-00** [comment]
## strict return on false LastFmQuery.php:61

simplexml_load_string may be false so this fails for last.fm running updateCatalog. assuming it's empty/not valid somehow but it does load in a browser okay
```
TypeError Return value of Ampache\Module\LastFm\LastFmQuery::queryLastFm() must be an instance of SimpleXMLElement, bool returned
(thrown in /var/www/music/src/Module/LastFm/LastFmQuery.php:61)

**Comment by wagnered** [comment]
In  `Catalog::process_action($action, $catalogs, $options = null)` I set config values 'mid-stream' with `AmpConfig::set($name, $value, $clobber = false)` to update file tags(2922-2925). But 'getSongId3TagWriter::write($song)`  uses the `ConfigContainer` class to check the `write_id3*` settings.

Seems to me that the `AmpConfig::set` function should update the `ConfigContainer->configuration` property the same as the `AmpConfig::set_by_array` function does. 

I hope the above issue is clear.  The "bottom line" is that the metadata can't be written to the files because ``ConfigContainer->configuration` can't be directly updated.

Unless I'm missing something ;'>

**Comment by usox** [comment]
> I hope the above issue is clear. The "bottom line" is that the metadata can't be written to the files because ``ConfigContainer->configuration` can't be directly updated.
> 
> Unless I'm missing something ;'>

I'll check.

**Comment by lachlan-00** [comment]
question regarding static types
![image](https://user-images.githubusercontent.com/1305249/114125200-4c773b00-9939-11eb-9ede-cc53771ed78f.png)

there are a few parameters like mbid which can be null which means this isn't always a string.

Do you cast before the function or do you allow multiple types in the function?

I assume it's better to cast to string but then if you allow empty strings should we filter them back to null?

**Comment by usox** [comment]
In this case, the string cast was added because I wasn't able to determine the behavior of the system at that point. Normally, all scalar types may be nullable - as long as it makes sense. As repositories should not contain (too many) logic, the data should be "readied" before giving it to the repo.

When the time comes and we have an ORM, there will be typed setter-methods for every field which accept the data according to the field in the database. So if the the mbid fields are string|null in the db, the method will accept ?string.

**Comment by lachlan-00** [comment]
i went with cast strings in 7db60aac7 feel free to change back if you don't agree/like that

**Comment by wagnered** [comment]
I had been working in my feature branch for awhile before php threw the following error:


>  16:11+00:00 [admin] (/var/www/ampache/public/templates/header.inc.php:515) -> Call to a member function get_items() on null

Thinking the session had timed out, I logged out then back in but that also failed. The culprit is `$count_temp_playlist = count(Core::get_global('user')->playlist->get_items());`.  I have no playlists so the playlist property is `null`.    Don't know why this didn't show earlier.  Possibly the browser cache prevented it, but I don't remember clearing it.

**Comment by lachlan-00** [comment]
cli might not be pulling api keys from config correctly.

keys are all coming in as `0` when using metadata plugins
```
https://api.discogs.com/database/search?type=artist&title=&per_page=10&key=0&secret=0
http://www.theaudiodb.com/api/v1/json/0/search.php?s=G%C3%A4rden%20Sound
```

**Comment by lachlan-00** [comment]
definitely unable to read config at the moment in cli
![image](https://user-images.githubusercontent.com/1305249/114351463-01b22900-9bae-11eb-9e45-f7e36437837e.png)

**Comment by lachlan-00** [comment]
i think the preference cache is actually the issue here.
6a82e1ca4 set individual settings. this would explain why it's going so wild

**Comment by usox** [comment]
> i think the preference cache is actually the issue here.
> [6a82e1c](https://github.com/ampache/ampache/commit/6a82e1ca453ab7ef668945a29443f598885a9baf) set individual settings. this would explain why it's going so wild

Hm well, doesn't happen here...maybe an error in the config file?

**Comment by usox** [comment]
> In `Catalog::process_action($action, $catalogs, $options = null)` I set config values 'mid-stream' with `AmpConfig::set($name, $value, $clobber = false)` to update file tags(2922-2925). But 'getSongId3TagWriter::write($song)` uses the`ConfigContainer`class to check the`write_id3*` settings.
> 
> Seems to me that the `AmpConfig::set` function should update the `ConfigContainer->configuration` property the same as the `AmpConfig::set_by_array` function does.
> 
> I hope the above issue is clear. The "bottom line" is that the metadata can't be written to the files because ``ConfigContainer->configuration` can't be directly updated.
> 
> Unless I'm missing something ;'>

@wagnered No, you're quite right. The goal is/was to keep the config readonly to avoid errors which come from temporary config changes or workarounds (using the config to transport parameters from one place to another). Line 2944 contains one of those errors (writing the value for `write_id3` twice instead of `write_id3` and `write_id3_art`).

I'd recommend to pass the config-setting-value as parameter to `Art:;insert` instead - so you don't need to change the config setting anymore.
Regarding `write_id3` I'd say we simply drop the condition in SongId3TagWriter which checks if writing is enabled and add this condition at every location which currently invokes the write-method.

This should solve the problem and gets rid of the AmpConfig::set calls. If you want, I can do that for you.

**Comment by lachlan-00** [comment]
@usox the urls generated by the song_row.xhtml template are in a weird order for the delete button
```
<a id="delete_song_991683" href="delete/song.php?action=https://music.com.au&amp;song_id=991683">
```

the `delete/song.php?action=` and site url are backwards

**Comment by usox** [comment]
@lachlan-00 got it, thanks.

**Comment by lachlan-00** [comment]
One UI::show left in the code

`2021-06-16T13:14:58+10:00 [ampache] (log.lib) -> [Error] Non-static method Ampache\Module\Util\Ui::show() should not be called statically in file /var/www/music/public/templates/show_tagcloud.inc.php(38)`

**Comment by usox** [comment]
Covered

**Comment by lachlan-00** [comment]
looks like the `random.php?action=advanced&type=song` page is having issues with andvanced or get_advanced cases causing the page to not load after trying to queue songs

I've gone back to feb commits to see if it was me recently but it looks like a repository/template/ajax loading issue.

**Comment by usox** [comment]
Works now as expected

**Comment by lachlan-00** [comment]
After the last 6(+) months of working on this branch I don't have any reason to keep this open.

The code is 100% better now and it's been easy to add function, trace issues and fix things quickly

It's also enabled me to fix things I couldn't before. 5 is out sep1 and this branch is the better branch now
