### ISSUE TITLE
Ampache 4.4.0 has no option to 'Create admin account' while installation

### ISSUE THREAD

**Issue by prbt2016** [ampache/ampache#2787]
Hello,

I was in the process of manual installation of Ampache 4.4.0 on Centos Linux with PHP 7.1, MYSQL 5.5, Apache 2.2.34.

However, in this version there is no option of 'Create Admin account'.

After 'Generate Configuration File' step page is redirected directly to the http://domain.com/login.php page.
What could be causing this issue?.

Could you please replicate and fix this?

**Comment by lachlan-00** [comment]
you're right,

I do an install when testing but this is new

**Comment by lachlan-00** [comment]
sql file fails to install fixing now

**Comment by prbt2016** [comment]
Thanks for looking into the issue . Let me know when you push the fix.

**Comment by lachlan-00** [comment]
f53937b

**Comment by lachlan-00** [comment]
updating docker now

**Comment by lachlan-00** [comment]
zip is updated, docker will be done soon and the tag is updated in git.

if you don't want to get the zip again you can just update the sql/ampache.sql file manually.
https://raw.githubusercontent.com/ampache/ampache/release4/sql/ampache.sql

**Comment by prbt2016** [comment]
Thanks a lot for the very quick support and fix. I'll re-download the package.

**Comment by lachlan-00** [comment]
i now have another test to add to my process so thanks for getting on and reporting
