### ISSUE TITLE
Ampache.com

### ISSUE THREAD

**Issue by RyanCopley** [ampache/ampache#2790]
Would you like ampache.com? I bought it many years ago and have no use for it currently.

**Comment by lachlan-00** [comment]
looks like a .com is cheaper than the .dev i'm paying for and it would give me ability to https the main site if we moved it there.

I've been waiting for dns changes on the .org for years now to enable https

**Comment by vollmerk** [comment]
Ohh you should have just told me I can make whatever changes uou need to
.org.... haha sorry if I missed a request.

**Comment by RyanCopley** [comment]
1) Are you interested in the .com (for free, but I would appreciate some readme appreciation)
2) Who has the authority to make these changes 
3) Is there a platform where we can communicate privately? I would prefer Discord if possible. `Tesla Owner#1337` is my name there.

**Comment by vollmerk** [comment]
I am happy to take over payment but its lachlan@dewaard.email project 100%
my only involvement is to make sure it can be passed to whoever wants to
maintain it. It almost got abandoned a few years ago and it was luck I
still had enough control to reassign it if you will.

Anyway I can delegate dns management of .org wherever and will happily take
over paying for
Com with the same arrangement ie management is in lachlans hands and I only
keep enough permissions to hand it off if lachlan every gets tired of it.

That work for everyone? If you want to own it outright lachlan I'm
fine with that as well. Just promise you won't dissappear off the earth
like the last person ;)

Maybe we get it in multiple folks name so they don't get lost?

**Comment by lachlan-00** [comment]
I don't want to have ownership of .com if i don't have to as it's not required for me to run the project.

Ownership is something i think should stay with @vollmerk and the org domain but i can always pay for it if you have invoices sent to me or put me as a contact as a backup.

@RyanCopley we can put acknowledgement on the site and readme/acknowledgement docs no problem. I prefer that people are recognized for every contribution to the project.

if you want to take this off the issues page email me (address above) and the 3 of us can discuss.

@vollmerk the dns needs updating to https on the org site which i think is the only issue for the org site.
```
The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request at https://support.github.com/contact?repo_id=18809933&page_build_id=235126213
```

**Comment by vollmerk** [comment]
@ A
185.199.111.153
3600 delete
@ A
185.199.110.153
3600 delete
@ A
185.199.108.153
3600 delete
@ A
185.199.109.153
3600 delete
www CNAME
ampache.github.io
3600 delete
- Just updated the DNS, let me know if that doesn't work.

**Comment by lachlan-00** [comment]
@RyanCopley you can email me about this. i don't have discord or anything else like that, i'll forward on to Karl

**Comment by lachlan-00** [comment]
@vollmerk looks like it's changing now, will wait and check again tomorrow.
![image](https://user-images.githubusercontent.com/1305249/110286160-2e63a580-8030-11eb-950d-7ed24693c156.png)
