### ISSUE TITLE
update_playlist action doesn't seem to update

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2791]
@usox i think the smart / playlist code has been confused

public/templates/show_search.inc.php is listing `/** @var Playlist $playlist */` instead of a search `/** @var Search $playlist */`

I'm trying to add limit and random to the rules page but can't get it to save.
it looks to me like it's not actually changing the rules in UpdatePlaylistAction.php nothing changes when i press 'save changes'

**Comment by usox** [comment]
Thanks and fixed.
