### ISSUE TITLE
Lightbox for viewing artist images, covers not showing only image itself

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2792]
### Describe the bug

When viewing artist pictures, covers ... in fullresolution by clicking on them there should be an "lightbox" with navigation buttons, at least one for closing.
At least releases from 4.2.2 onwards just show the picture.
No functionality is broken just optical issue.

### To reproduce

Click on any Picture wether artist or cover.
![prettyphoto_images_notexists](https://user-images.githubusercontent.com/10261043/109994793-f269d100-7d0d-11eb-8c33-8b24d1847bc0.jpg)

### Screenshots

![prettyphoto_images_exists](https://user-images.githubusercontent.com/10261043/109996029-1e398680-7d0f-11eb-973a-57667c11240d.jpg)

## Environment

* Ampache version: 4.4.0
* Web server + version: NGINX 1.14 + PHP7.4-FPM
* Server operating system: Debian
* Client operating system: Win10

### Client type

* Web

## Logs

`2021/03/04 16:45:57 [error] 22918#22918: *1269 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/sprite.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/compo$
2021/03/04 16:45:57 [error] 22919#22919: *1276 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/sprite_y.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/com$
2021/03/04 16:45:57 [error] 22918#22918: *1274 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/sprite_x.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/com$
2021/03/04 16:45:57 [error] 22918#22918: *1277 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/loader.gif" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/compo$
2021/03/04 16:45:57 [error] 22918#22918: *1269 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/sprite.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/compo$
2021/03/04 16:45:58 [error] 22918#22918: *1269 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/light_rounded/btnNext.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /li$
2021/03/04 17:01:07 [error] 22919#22919: *1514 open() "/usr/share/ampache/www/lib/components/prettyphoto/images/prettyPhoto/default/sprite.png" failed (2: No such file or directory), client: 192.168.1.30, server: ampache.sandmann.dd-dns.de, request: "GET /lib/compo$`

## Solution
As one can see from the logs the folder images from component prettyphoto is missing from release.

**Comment by lachlan-00** [comment]
not sure why they weren't included in the release zip... will have to do a 4.4.1 next week to resolve this.

**Comment by SePHTaN** [comment]
I mark this as solved and close this issue
