### ISSUE TITLE
[BUG] Album arts are cut off on height.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2795]
## Description

I updated to latest git pull, and found the album height is cut off while browsing:

![2021-03-04_15-00](https://user-images.githubusercontent.com/106644/110042269-6306f280-7cfa-11eb-9545-033b5aea7c04.png)

### To reproduce

```
cd /var/www/ampache
git reset --hard origin/release4
git pull
```

To fix roll the changes back, I refreshed the page each time.
```
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at f53937b00 4.4.0-2 (#2788)
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at 5c2a84068 Merge pull request #2778 from ampache/master
root@amp:/var/www/ampache# git reset --hard HEAD~1
HEAD is now at ac669603e 4.3.0<------- Last working commit before album art broken.
```

### Expected behavior
album art not chopped off.

## Environment

* Ampache version: Ampache 4.4.0-release
* Web server + version: Nginx Latest
* Server operating system: Ubuntu 20.04
* Client operating system: Ubuntu 20.04

### Client type

* Web

## Settings

`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+"`

```
+config_version = 46
+http_host = "ampache.REDACTED.com"
+http_port = "443"
+web_path = ""
+local_web_path = "http://localhost:80"
+database_hostname = "/run/mysqld/mysqld.sock"
+database_port = ""
+database_name = "ampache"
+database_username = "www-data"
+database_password = ""
+database_charset = "utf8mb4"
+database_collation = "utf8mb4_unicode_ci"
+secret_key = "REDACTED"
+session_length = "3600"
+stream_length = "7200"
+remember_length = "604800"
+session_name = "ampache"
+session_cookielife = "0"
+session_cookiesecure = "0"
+getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
+additional_genre_delimiters = "[/]{2}|[/|\\|\|,|;]"
+licensing = "false"
+simple_user_mode = "true"
+artist_art_preferred_filename = "artist.jpg"
+album_art_min_width = "190"
+album_art_min_height = "190"
+art_order = "db,folder"
+wanted = "false"
+channel = "false"
+live_stream = "false"
+podcast = "true"
+debug = "true"
+debug_level = "5"
+log_filename = "%name.log"
+site_charset = "UTF-8"
+allow_public_registration = "false"
+cookie_disclaimer = "false"
+transcode_mp3 = "allowed"
```

## Logs

No relevant logs.

**Comment by SePHTaN** [comment]
Hi Xekon,

i wanted to do a bug report on this issue myself today.
But i believe its just an Browser issue with caching the old default.css file from the 4.3.0 version.
It might also be Nginx caching that file. 
Anyway after updating to 4.4.0 the issue dissappeared completely after either restarting my Browser or after restarting my nginx server.
Not able to say who exactly produced it but i can say its not ampache who is responsible.

**Comment by xekon** [comment]
Thank you! I just rebooted my Ampache and completely cleared my browsers cache, works fine now. Maybe there was a css change that would have benefited from cache busting, regardless im fine now, thanks.

**Comment by SePHTaN** [comment]
Indeed there was a change from class="mash_cover" to class="grid_cover" for the layout showing the covers.
Without the correct css file the class "grid_cover" was indefined what caused that look.
