### ISSUE TITLE
[Feature Request] Configurable value for number of "Recently Played" items on the home page

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2798]
## Describe what you don't like about Ampache, or what it is missing

Configurable value for number of "Recently Played" items on the home page: https://ampache.example.com/#index.php

## Describe how you would like the feature to work**

Currently the home page is showing 10 items for Recently Played, I would like to increase this to 20 items, but a configurable value that could be adjusted would be great!

EDIT: I tried figuring it out and got as far as this file: /var/www/ampache/templates/show_recently_played.inc.php but I dont see how it decides to return 10 items.

**Comment by lachlan-00** [comment]
it's the popular_threshold
![image](https://user-images.githubusercontent.com/1305249/110065837-d3c21380-7dbb-11eb-8e53-ba221880a78f.png)

**Comment by xekon** [comment]
Thank You! I was looking for Recently Played so I didn't even notice that, I thought it might be some kind of metric used to determine whats popular. I just set it to 20 and it looks great, thanks.
