### ISSUE TITLE
Add support for arbitrary information, text.

### ISSUE THREAD

**Issue by Xenakis** [ampache/ampache#280]
User may want to add arbitrary information about the album/artist/etc.

Source text file may include artist info, i.e., bio; and may contain album info, i.e., credits; perhaps more.

Text file should also be added to DB for search.

**Comment by Afterster** [comment]
I will move this issue to 3.8.1 so 3.8.0 will not have any improvement and we can focus on test and bug fix for a release. Let me know if it is a problem for you ;)

**Comment by Razrael** [comment]
For me it is no problem, currently I have almost no time to work on it anyway...

**Comment by Afterster** [comment]
Razrael work was merged few weeks ago. I'm going to close this then.
