### ISSUE TITLE
Browse Ampache screen reduce album cover size

### ISSUE THREAD

**Issue by bembudo** [ampache/ampache#2801]
### To reproduce

I just have to go to albums on my left pane to reproduce, cant seem to correct this, hope this is something real easy i am missing

## Environment

* Ampache version:4.4.0
* Web server + version:
* Server operating system:
* Client operating system: Ubuntu

### Client type

* Web
* Ampache

**Comment by bembudo** [comment]
![Screenshot from 2021-03-05 10-46-47](https://user-images.githubusercontent.com/74638754/110140441-18d94c00-7da2-11eb-81cf-bde547d55927.png)

**Comment by xekon** [comment]
clear your browser cache.

**Comment by bembudo** [comment]
OMG thank you, i feel like such an idiot. i knew it was something so simple

thank you once again

**Comment by lachlan-00** [comment]
ctrl + f5 will force a reload of the CSS as well
