### ISSUE TITLE
[Feature Request] Old API support

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2802]
## Describe what you don't like about Ampache, or what it is missing

Most of the ampache clients ( i think all ), mostly on android rely on onlder api versions and now are broken and not working, so it is possible to use ampache server only with subsonic clients, but this requires setting up subsonic module.

## Describe how you would like the feature to work**

It should be possible to create on a user basis, the possibility to enable a minimal old API, that supports only music/authentication and only read only, so most of the old clients will be compatible again, without mantaining a full featured api.

**Comment by AshotN** [comment]
Would running an older version of Ampache not be easier?

**Comment by lusum** [comment]
I thought, that, having no one android native client  working, it would be a good solution.

**Comment by lusum** [comment]
Bad idea, old apps are not maintained and not compatible with modern versions of operating systems
