### ISSUE TITLE
Login issues since ampache 5 upgrade

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2811]
## Description

Since the major change to amapche 5 on the develop branch, I'm having some strange user login issues but I've also made some changes to how ampache is hosted on my server so I'm not sure if this is a bug or just a configuration issue that I've caused?

I used to run ampache in a subfolder of my main domain but with the document root change requirements in amapche 5, I set up a new subdomain with a /var/www/html/ampache/public document root to run ampache from.

Since the upgrade and these changes, every normal login attempt via the web interface is redirected back to the login.php page.

The only way I'm able to bypass this and actually log in is by visiting the lost password page first, not fill anything in but just click on the submit button which takes me back to login.php. Then enter username and password and click login button which takes me back to the lost password page a second time. Again, I just click submit with no email address which takes me to the login.php for a third time, and from there, by just clicking on the login button without filling any username or password I'm in!! 

Once actually logged in, everything in the web UI seems to work just fine which makes me think the server config must be fundamentally ok? I can stream and use the web player all without issue. Also, after changing my subsonic clients to point to the new subdomain, they are all working fine,

I think there could be a cookie issue? Using the browser dev tools, some of the cookies sent seem to be dated 1970 and I think these are being rejected by the browser? (see screenshots) The ampache log is reporting 'unable to read session keys' errors when this occurs but no errors are reported in httpd, php or mysql logs. 

When successfully logged in, the ampache logs are reporting all user actions correctly, with the user name in square brackets as expected, but actions carried out by ampache are just showing empty square brackets. (see logs) Even automated tasks like cron and adding of albums just show [ ] as the user but are all working fine.

As mentioned, I've made some major changes to how ampache is hosted on my server, so this might be the result of bad configuration but any ideas here would be appreciated.

**Screenshots**
Browser dev tools cookie console warnings:
![image](https://user-images.githubusercontent.com/3216809/110224112-c2b6f680-7ed0-11eb-910c-c08e0deb40b1.png)

Browser dev tools cookie storage:
![image](https://user-images.githubusercontent.com/3216809/110224076-74095c80-7ed0-11eb-998c-529a48ae28fb.png)

Browser dev tools cookie request headers:
![image](https://user-images.githubusercontent.com/3216809/110224341-900dfd80-7ed2-11eb-80ba-0f70facaf06e.png)

## Environment

* Ampache version: Ampache develop (latest commit)
* Web server + version: Apache 2.4.46, MySQL 8.0.23, PHP 7.4.15
* Server operating system: Fedora 33
* Client operating system: Fedora 33

**Client type:**

* Web - Firefox 86.0 (64-bit) & Chromium 87.0.4280.66 (64-bit)

## Logs
ampache log when accessing login.php: (Notice no ampache user listed as usual in the square brackets)
```
2021-03-06T22:50:13+00:00 [] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Login\DefaultAction" for action "default"
2021-03-06T22:50:13+00:00 [] (Ampache\Module\System\Session) -> Unable to read session from key kdb606crn0ck30819433n39nfg no data found
2021-03-06T22:50:13+00:00 [] (Ampache\Module\System\Session) -> Writing to kdb606crn0ck30819433n39nfg with expiration 1615074613
```
The same errors are repeated multiple times with different strings
No errors are reported in httpd, php or mysql logs

**Comment by usox** [comment]
Hi

Thanks for the report. It indeed looks like some sort of a cookie problem. The cookies dated to 1970 indicate a logout happens - those `_user` and `_lang` cookies get deleted once a user logs out. This is done by setting a date in the past so I'd say, somewhere happens an implicit logout.
You're saying, ampache was in a subfolder prior to the upgrade. So my first question is: Do you still have the path configured somewhere in the ampache config? `web_path` e.g.?
That rejected session cookie in fact is a bit odd...

**Comment by rsinfotech** [comment]
Yes, initially I kept the subfolder arrangement and just set up an Alias directive to redirect requests from the old URL/ampache document root to the new public root directory. But this resulted in the behaviour described above, so, presumung it was a configuration problem, I set up a whole new virtualhost with ampache as a subdomain, added a DNS entry and removed the old ``web_path`` entry which allowed me to set the document root to /var/www/html/ampache/public as per the instructions but the strange log in behaviour remained.

I'm pretty sure that I've changed all the settings needed in the ampache config to match the new server configuration, I've tried many changes here and can easily break the site but the way I've got it, everything resolves correctly, entering the new subdomain address in the address bar resolves to the ampache login.php page which is where the fun starts.

My current config settings in the Path Vars section are:
```
;#########################################################
; Path Vars                                                                                               #
;#########################################################

; The public http host of your server.
; If not set, retrieved automatically from client request.
; This setting is required for WebSocket server
; DEFAULT: none
; http_host = "ampache.rsinfotech.co.uk"

; The public http port of your server.
; If not set, retrieved automatically from client request.
; DEFAULT: none
; http_port = "80"

; The public path to your Ampache install
; Do not put a trailing / on this path
; For example if your site is located at http://localhost
; than you do not need to enter anything for the web_path
; if it is located at http://localhost/music you need to
; set web_path to /music
; DEFAULT: none
web_path = ""

; The local http url of your server.
; This is used to access the server from within the
; same host where ampache is running.
; For example, if the ampache server is not
; directly accessed via the public domain but via a reverse
; proxy, local_web_path would need to be changed
; to a localhost URL.
; If not set, retrieved automatically from server information.
; DEFAULT: none
; local_web_path = "http://localhost/ampache"
```
The ``web_path`` entry is the only one not commented out and used to contain ``web_path = "/ampache"`` before my changes but this obviously failed to resolve and resulted in page not found errors.

This is an odd one? As I say, once I do manage to log in, everything is working perfectly and all I had to do with my subsonic clients was to update to the new server address and they work flawlessly so the API side of things must be fine too?

Also worth mentioning here is that this is an SSL only virtualhost listening on port 443 but again, everything here seems fine, the server certificate is valid and no errors are recorded in the server logs when this occurs?

**Comment by SePHTaN** [comment]
Hi rsinfotech,

could it be that the session storage isn't reachable for apache2 after your setup change ?

i changed my setup to nginx some weeks ago, but before i also used apache.
my setup is with php7.4-fpm with a pattern (scripted) i use for all my webinstallations
my path layout is as following:
```
/var/www/ampache/public_html   # the document_root
                /conf          # php7.4-fpm socket
                /logs          # dir for logs
                /ltmp          # temp dir
```
```
the corresponding php7.4-fpm ampache.conf
php_admin_value[open_basedir] = /var/www/ampache/public_html/:/var/www/ampache/logs/:/var/www/ampache/tmp/:/var/www/ampache/sessions/:/mnt/Musik:/tmp/
php_admin_value[doc_root] = /var/www/ampache/public_html/public
php_admin_value[upload_tmp_dir] = /var/www/ampache/tmp/
php_admin_value[session.save_path] = "/var/www/ampache/session"
```
at least with my current installed  version of ampache 5.0.0 prerelease (707c32af5aed4961719a1c989d41132ba70f9bdc)
this setup was working flawlessly

**Comment by SePHTaN** [comment]
update on this from my side:
just did a clean install:
`git clone -b develop https://github.com/ampache/ampache.git`

my setup is with nginx 1.14-2 using the exactly same php7.4-fpm setup i used with apache2 mentioned above
no login issues
nothing in firefox webdeveloper regarding Cookie PHPSESSID:
but i have this error (from webplayer?)
```
3:29:00.311 Uncaught TypeError: atoms[name] is undefined
    atom m4a.coffee:4
    M4ADemuxer m4a.coffee:98
    [19]< aurora.js:2703
    s aurora.js:3
    s aurora.js:3
    [18]< aurora.js:1940
    s aurora.js:3
    s aurora.js:3
    [3]< aurora.js:250
    s aurora.js:3
    s aurora.js:3
    [1]< aurora.js:6
    s aurora.js:3
    e aurora.js:3
    <anonymous> aurora.js:3
    <anonymous> aurora.js:3
    <anonymous> aurora.js:3
```
so i assume there something with your webspace setup

**Comment by rsinfotech** [comment]
Hi @SePHTaN,

I am running PHP-fpm but don't have any of these entries in my ``php-fpm.conf`` file and have never edited these? There is one other conf file in the php-fpm.d directory called ``www.conf``, but again it doesn't contain any of the entries you suggest?

I will create another called ampache.conf with the entries you suggest and let you know the result.

Thanks for your suggestions...

My install method has never changed, I run ``sudo -u apache git pull https://github.com/ampache/ampache.git develop`` from the command line in the ampache root directory.

**Comment by rsinfotech** [comment]
Ok, after adding an ampache.conf file with the lines you suggested and modified to suit my environment in the php-fpm.d directory and restarting the server, there is no change to my issue and still no errors reported in the httpd, php or mysql logs.

Just the same error lines in the ampache log:
```
2021-03-07T13:28:29+00:00 [] (Ampache\Module\System\Session) -> Unable to read session from key ejd5fkoge32cft04eafl5f4opc no data found
2021-03-07T13:28:29+00:00 [] (Ampache\Module\System\Session) -> Unable to read session from key g2qqtu9oatai3ie7bou5bg235v no data found
2021-03-07T13:28:29+00:00 [] (Ampache\Repository\Model\User) -> Login from IP address: 82.69.16.228
2021-03-07T13:28:30+00:00 [] (Ampache\Module\System\Session) -> Unable to read session from key m9v7c74e0mqgm742tfsrbk29kv no data found
```
I will keep playing with things here and thanks for your help...

**Comment by stebe** [comment]
I'm using php7.4-fpm as well and this hasn't been an issue for me and I don't have anything special in my php configuration.  I'm using Apache2 for my web server with nginx reverse proxy.  I do have a local web path defined in my configuration. My document root is /var/www/ampache/public

```
;#########################################################
; Path Vars                                              #
;#########################################################

; The public http host of your server.
; If not set, retrieved automatically from client request.
; This setting is required for WebSocket server
; DEFAULT: none
;http_host = "localhost"

; The public http port of your server.
; If not set, retrieved automatically from client request.
; DEFAULT: none
;http_port = 80

; The public path to your Ampache install
; Do not put a trailing / on this path
; For example if your site is located at http://localhost
; than you do not need to enter anything for the web_path
; if it is located at http://localhost/music you need to
; set web_path to /music
; DEFAULT: none
web_path = ""

; The local http url of your server.
; This is used to access the server from within the
; same host where ampache is running.
; For example, if the ampache server is not
; directly accessed via the public domain but via a reverse
; proxy, local_web_path would need to be changed
; to a localhost URL.
; If not set, retrieved automatically from server information.
; DEFAULT: none
local_web_path = "https://ampache.animeshare.com"
```

My web server configuration:

```
<VirtualHost *:8080>
#  DocumentRoot /var/www/ampache/
  DocumentRoot /var/www/ampache/public
  ServerName  ampache.animeshare.com
  ServerAdmin webmaster@animeshare.net
  Protocols h2 http/1.1

  <Directory /var/www/ampache/>
          DirectoryIndex index.php
          Options -Indexes +FollowSymLinks +MultiViews
          AllowOverride All
          Require all granted
  </Directory>

<IfModule mod_rewrite.c>
    RewriteEngine On
</IfModule>

</VirtualHost>

```

**Comment by SePHTaN** [comment]
@stebe @rsinfotech 
i do believe both of you haven't properly setup your server
looking at stebe's <Virtualhost> Directive i didn't see any socket for php-fpm so i don't belief yout virtualhost is using php-fpm its instead using mod-php.

Inside your virtualhost directive you should have something like this:
```
        <Directory /var/www/ampache/public_html/public/>
                Options Indexes FollowSymLinks
                AllowOverride all
                Require all granted
                <FilesMatch "\.(php)$">
                        SetHandler "proxy:unix:/var/www/ampache/conf/ampache-fpm74.sock|fcgi://newampache/"
                        ProxyErrorOverride on
                </FilesMatch>
        </Directory>
```

I going to extend the wiki where lachlan's server setup is missing and post there my setup.
Maybe the better place than clutterung this issue full with server configuration.

**Comment by stebe** [comment]
I have that in my conf-available/php7.4-fpm.conf file so its site-wide. I just verified by stopping the php7.4-fpm service and then I get a 503 error in ampache.

```
# Redirect to local php-fpm if mod_php is not available
<IfModule !mod_php7.c>
<IfModule proxy_fcgi_module>
    # Enable http authorization headers
    <IfModule setenvif_module>
    SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
    </IfModule>

    <FilesMatch ".+\.ph(ar|p|tml)$">
        SetHandler "proxy:unix:/run/php/php7.4-fpm.sock|fcgi://localhost"
    </FilesMatch>
    <FilesMatch ".+\.phps$">
        # Deny access to raw php sources by default
        # To re-enable it's recommended to enable access to the files
        # only in specific virtual host or directory
        Require all denied
    </FilesMatch>
    # Deny access to files without filename (e.g. '.php')
    <FilesMatch "^\.ph(ar|p|ps|tml)$">
        Require all denied
    </FilesMatch>
</IfModule>
</IfModule>
```

**Comment by SePHTaN** [comment]
👍 
 looks pretty similar to mine some additional location matches to deny or restrict filehandling
arises the question why i didn't have any issues regarding login or session/cookie handling

**Comment by rsinfotech** [comment]
Hi all, I've now spent hours trying to diagnose this and have still got no further...

Some of my settings are different from the ones you suggest @SePHTaN and @stebe, php-fpm is definitely running as if I stop the php-fpm service, I then get a 503 error like stebe explains above.

I think all of this must be correct as once I do manage to log in, everything works perfectly with no errors? It's just this initial issue of being constantly redirected to the log in page unless I go through the routine described above which eventually logs me in.

I'll keep trying things here and let you know if I find anything, thanks again for all of your help.

**Comment by SePHTaN** [comment]
I belief it's a problem with cookie handling. All you wrote can be reduced to : unable to read / not found
I am currently looking into possible configuration "mistakes" that maybe came to effect when you changed your webpath.

Have you checked your cookie related settings in the php.ini of your used php version?
With Debian you find it here /etc/php/phpversion eg 7.4/fpm/php.ini
What i also would suggest, give your former working setup regarding paths a try.


The lines from above:
```
php_admin_value[open_basedir] = /var/www/ampache/public_html/:/var/www/ampache/logs/:/var/www/ampache/tmp/:/var/www/ampache/sessions/:/mnt/Musik:/tmp/
php_admin_value[doc_root] = /var/www/ampache/public_html/public
php_admin_value[upload_tmp_dir] = /var/www/ampache/tmp
php_admin_value[session.save_path] = "/var/www/ampache/session"
```
are overrides for php.ini variables you can make in the PHP-FPM conf for an vhost. 
It gives you the ability to have different php.ini settings for different websites.

My server got hacked some years ago. Afterwards i had some help from an friend, who is a small webhoster, to have a more secure setup. So every website i host has its own php-fpm process with different users for each to seperate them from another.
This limits the damage an successful attackers can generate in the beginning to one site.

**Comment by rsinfotech** [comment]
I think you're right @SePHTaN, this is a cookie issue specific to my ampache setup as all other sites on my server are working correctly and so is ampache once I manage to get in.

The phpsession cookie is being deleted by the browser because it is dated 01/01/1970 so I'm stuck in a loop of requesting a cookie and it being deleted, which is why I have the repeated ``Unable to read session from key`` errors in the ampache logs.
```
"PHPSESSID":
	"expires": "1970-01-01T00:00:01.000Z",
	"path": "/",
	"secure": true,
	"value": "deleted"
```
I don't know where this date for the phpsession cookie comes from? Is it set by ampache?

**Comment by SePHTaN** [comment]
The Unix epoch is the time 00:00:00 UTC on 1 January 1970
Thats just the beginning of the unix time, so if you delete an cookie is somewhat the same as setting it expired at the beginning of the unix epoch.
I was digging around a little bit and found this : 
[Firefox rejecting cookies from the past](https://stackoverflow.com/questions/65038173/cannot-remove-a-cookie-firefox-rejecting-cookies-from-the-past)
So a leads me to the possibility that some path changes without clearing your browser cache might be the reason that the handling for the cookie fails.
Next you should set `session.cookie_samesite = "Strict"` in your php.ini
That was one thing firefox complained about, its an feature for security:
```
As of PHP 7.3 the "SameSite" attribute can be set for the session ID cookie.   
This attribute is a way to mitigate CSRF (Cross Site Request Forgery) attacks.
The difference between Lax and Strict is the accessibility of the cookie in requests originating from another  
registrable domain employing the HTTP GET method. Cookies using Lax will be accessible in a GET request  
originated from another registrable domain, whereas cookies using Strict will not. 
```

**Comment by usox** [comment]
> The Unix epoch is the time 00:00:00 UTC on 1 January 1970
> Thats just the beginning of the unix time, so if you delete an cookie is somewhat the same as setting it expired at the beginning of the unix epoch.

As I said earlier. Setting the expiration date to `0` or `-1` is the way to mark cookies as deleted - this happens intentionally at logout.
Imho this should not be related to browser cache. If so, there shouldn't be a problem when using the private/incognito mode. I'm still looking into this.

**Comment by rsinfotech** [comment]
Yes @usox, you are right, using private/incognito mode makes no difference to my issue.

I have found an easier way of logging in though, just messier for my log files...

If I select the 'Remember Me' checkbox before attempting the login, I get a string of bounces between the login.php and the site root folder but then get a message from Firefox as shown below. Clicking on the 'Try Again' button takes me straight in?? And then I am enjoying music again. :-)

I've not changed anything to disable or reject cookies as the message suggests, so really don't understand what's happening here?

Apache access logs of the bounces:
```
[09/Mar/2021:20:58:16 +0000] "POST /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:17 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:17 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:17 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:18 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:18 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:18 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:18 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:19 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:19 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:19 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:20 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:20 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:20 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:21 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:21 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:21 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:21 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:22 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:22 +0000] "GET / HTTP/1.1" 302 102222
[09/Mar/2021:20:58:23 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:24 +0000] "GET /login.php HTTP/1.1" 302 -
[09/Mar/2021:20:58:24 +0000] "GET / HTTP/1.1" 200 114719
```
Firefox error message:

![image](https://user-images.githubusercontent.com/3216809/110539274-eff7e480-811c-11eb-9dd8-ff7065e566c2.png)

**Comment by stebe** [comment]
Those redirects.  Just thinking out loud. Could you have a .htaccess file causing this, something in your sites-available (letsencrypt can create a rewrite rule for example) or a web redirect defined in the DNS? Also most Apache configurations usually have a different file for ssl and non-ssl. Did you update both of them with the new document root?

```
ls -l /etc/apache2/sites-available/ampache*

-rw-r--r-- 1 root root  929 Mar  7 20:32 /etc/apache2/sites-available/ampache.conf
-rw-r--r-- 1 root root 2010 Aug 31  2020 /etc/apache2/sites-available/ampache-le-ssl.conf

```

**Comment by usox** [comment]
@rsinfotech Can you tell me the values of the following config keys from ampache.conf?
`remember_length`, `use_auth` and `auth_methods`

**Comment by rsinfotech** [comment]
Hi all, still looking into this at my end and been unable to find any config problems yet?

@usox, certainly, they are:
``remember_length = "604800"``,  ``use_auth = "true"`` and ``auth_methods = "mysql"``

Thanks...

**Comment by usox** [comment]
Mh. Well, I was not able to reproduce this yet. Could it be related to http and https? Maybe redirection between https, http and back? This could explain, why the session cookies is not readable...

**Comment by rsinfotech** [comment]
Thanks for looking into this again @usox, I've still got the issue but it is obviously a server config error somewhere on my side so I'll close this issue for now.

I've tried lots of config changes including serving it from just http but still not found the root cause, I can still log in and enjoy music and the subsonic clients work flawlessly so it's more of an annoyance than anything.

I'll keep looking into it and post back here if I ever find the culprit, but thanks again for your time and keep up the great work!!

**Comment by rsinfotech** [comment]
Hi all, after many, many hours of trying multiple changes to my server config in an attempt to locate the cause of this redirection issue, I've eventually found the cause and it turned out not to be a server config issue after all.

There was a duplicated static function in src/Module/System/Session.php that was causing problems with my configured PHP session.save_handler. I presume that the call session_set_save_handler was trying to change the default handler location from 'files' to 'user' to store and read session data from the database instead of the files location, but this was failing.

After deleting the following duplicated code, the errors about being unable to read the session keys are gone from the ampache logs and logging in now works beautifully again:
```            
527            static function (): bool {
528                return true;
529            },
```
I've edited the file and submitted a pull request to fix this: #2921 

The strange thing here is that no one else was experiencing this issue, which made me believe it was a server config problem not an ampache problem?

**Comment by usox** [comment]
Hi @rsinfotech 

First of all: thank you for your further investigation, your proposed fix won't work out, though. The behavior of this methods has not changed since ampache 4.
https://github.com/ampache/ampache/blob/48056022711376444f4859c2a6e93273093c24b7/lib/class/session.class.php#L451
By changing the parameter count, you change the parameter order and the way the session handling works. This may work out for you atm, but it's not a solution :cry: 

But maybe this will lead to the real problem. This could somehow be related to the old self-maintained autoloading mechanism in ampache 4. The `_auto_init` method gets called when the file was included during the autoloading process, so _maybe_ the method now is called too late/too early now. Gotta checks this...

**Comment by rsinfotech** [comment]
Thanks for your explanation @usox 

I thought I'd just found a block of duplicated code here that was causing my problem but it's obviously a bit more involved than that.

I think I understand what you're saying here, that this could be down to some sort of race condition instead?

I found this by noticing that the output from phpinfo.php showed that the session.save_handler was reporting a local value of 'user' and a master value of 'files'.

With those 3 lines deleted from Session.php, both local and master values of phpinfo.php now show a session.save_handler of 'files', all key/session errors have gone from the ampache logs and users can log in again without any of the redirection issues mentioned above.

And here was I, thinking this would earn me my first ever contributor status  :wink: Oh well, maybe next time...

Thanks for reopening this and looking into it further.

**Comment by usox** [comment]
@rsinfotech I just made a small change to setup the session_save_handler earlier within the request processing. Before I commit it to the repo, I'd like to perform some tests. Maybe you can test it, too?

If you're familiar with this kind of patchfiles: Just download it to your ampache src and run `git apply session_init.txt`. Git status should report 4 changed files. Maybe this fixes your problem...

[session_init.txt](https://github.com/ampache/ampache/files/6495168/session_init.txt)

**Comment by rsinfotech** [comment]
Ok, I think I've done this correctly? Applied the patch, git status reports:
```
modified:   composer.lock
modified:   src/Config/Init/InitializationHandlerAuth.php
modified:   src/Config/Init/InitializationHandlerConfig.php
modified:   src/Module/System/Session.php
modified:   src/Module/System/SessionInterface.php
```
In this state, everything works perfectly still on my system.

I notice the 3 lines I deleted from Session.php are still missing and if I add them back, the errors return again.

**Comment by usox** [comment]
> Ok, I think I've done this correctly? Applied the patch, git status reports:
>
> I notice the 3 lines I deleted from Session.php are still missing and if I add them back, the errors return again.

Thanks, you did it right. Ok, back to work...we will sort this out.

**Comment by usox** [comment]
@rsinfotech If I may bother you again. This kind of remote debugging is hard... :laughing: 

[session_init_2nd.txt](https://github.com/ampache/ampache/files/6495759/session_init_2nd.txt)

**Comment by rsinfotech** [comment]
So this time, the new patch wouldn't apply, it reported errors.

After reverting the first patch, the 2nd applied OK and git status reports the same modified files as above.

Everything still working perfectly with the 3 lines deleted, errors return if added back.

**Comment by usox** [comment]
Ok thanks... sic

**Comment by lachlan-00** [comment]
I've fixed A LOT of issues around cookies and sessions

Going to move this on 5.1.0 as a toTEST as 5.0.0 is on the way now

**Comment by lachlan-00** [comment]
> So this time, the new patch wouldn't apply, it reported errors.
> 
> After reverting the first patch, the 2nd applied OK and git status reports the same modified files as above.
> 
> Everything still working perfectly with the 3 lines deleted, errors return if added back.

Hey @rsinfotech can i get an update on this one? if i need to create an ldap server i can look more into this but do you get any issues with this currently?

**Comment by rsinfotech** [comment]
Hi @lachlan-00, yes, this issue still gives me problems but I have a workaround that lets me log in so I've just lived with it ever since.

I'm sure it must be some configuration error on my server but I've been unable to find it despite lots of time spent looking in to it. I actually closed this once but it was reopened by @usox for further investigation.

My workaround is to click the 'lost password' link first before entering a username and password, I then just click the submit button without entering any email address and get redirected back to the log in page where I then enter my user details and click login. 

This pings me back to the lost password page, I click the submit button again without entering an email address which takes me back to the log in page where I can then click login without entering any user details again and then get access to the site as expected.

Very strange behaviour I know and I've spent lots of time looking into both the ampache configuration and my server configuration for a possible cause for this without success.

**Comment by rsinfotech** [comment]
Hi @lachlan-00, this issue seems to have gone since the recent develop branch merged to patch7?

Logging in is working as expected again now and has been since the upgrade so I'll close this issue as it's only ever affected my setup anyway?

patch7 is brilliant by the way, love the changes and the upgrade went faultlessly after following your guidance in the [wiki](https://github.com/ampache/ampache/wiki/ampache7-for-admins)

Very impressed with ampache and grateful for all the hard work and effort everyone puts in to such a great project!
