### ISSUE TITLE
Add new files from: in Show Catalogues stops working in develop

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2814]
### Describe the bug
When i add albums to my ctalog i normally use the `add new files from` in show_catalogues.
With ampache 4.40 this is working like a charm.
In develop this feature isn't at least since 5.0.0-prerelease

### To reproduce

1. Go to 'show catalogues'
2. enter file path in 'add new files from'
3. Press button 'update'
4. See nothing happens

### Expected behavior
The album from the entered file path should be added as in working 4.40
Updating through 'Update all' does work.

## Environment

* Ampache version: develop ba35dd141c20021f85539ce0708e8f46a19ee193
* Web server + version: nginx 1.14-2 + php7.4-fpm
* Server operating system: Debian10
* Client operating system: Win10

### Client type

* Web

**Comment by lachlan-00** [comment]
looks like it's running from the log file but not visually showing a notification/popup that it used to

**Comment by lachlan-00** [comment]
@SePHTaN can you explain how you use this path feature? I kind of think it's not need anymore.

is there a reason you just don't run an add action?

**Comment by usox** [comment]
@SePHTaN Thanks, should be fixed in develop :)

**Comment by SePHTaN** [comment]
Just testet it, definitely working again 🥇 
As you been working in the last years really in my neighborhood i tend to spend you an Urpils (or more ?) if you are near.
So i close this one.

**Comment by usox** [comment]
@SePHTaN well, beer is _always_ appreciated :)
