### ISSUE TITLE
Last FM grant not working

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2816]
### Describe the bug

last.fm API grant is not working. clicking on the link does go to last.fm and after accepting the permissions returns to Ampache. At this point the token isn't saved. Temporarily switching to the 4.4x branch and the last.fm grant function works.

### To reproduce

1. Go to 'User Preferences'
2. Click on 'Plugins'
3. Click on 'last.fm Grant plug icon'
3. Accept the permission on last.fm
4. No error, no logs. It just doesn't work.

### Expected behavior

token gets accepted and things like scrobbles work.

## Environment

* Ampache version: 8cfa07e93f7776b73970ad9f133e41a3110a78ae

### Client type

* Ampache

**Comment by usox** [comment]
I guess it's time to reactivate my last.fm account ^^

**Comment by usox** [comment]
I applied a patch but was not yet able to complete the api auth due to missing api key/secret. But I'd say, it _should_ solve your problem.

**Comment by usox** [comment]
Ok, i created a lastfm account, set up a new ampache instance on an external server and performed the api grant - it's working with the current develop branch, so I'm going to close this issue
