### ISSUE TITLE
REST API .htaccess rewrites incorrect path

### ISSUE THREAD

**Issue by BlueNalgene** [ampache/ampache#2818]
### Describe the bug
REST API path rewriting does not include ``ampache`` sub.  This means when I attempt to access ``http://localhost/ampache/rest/ping.view``, the rewriting module attempts to direct me to ``http://localhost/rest/index.php?ssaction=ping`` rather than the correct ``http://localhost/ampache/rest/index.php?ssaction=ping``

## Environment

* Ampache version: 4.4.0-release
* Web server + version: Apache/2.4.18 (Ubuntu)
* Server operating system: Ubuntu 16.04 xenial
* PHP version: PHP 7.4.13 (cli)
* Client operating system: Ubuntu 18.04 bionic

### Client type

Tested using Chromium, Firefox, Lynx, and WGET for good measure.  All failed.

## Settings

Relevant settings

- ``/etc/apache2/apache2.conf``: 
```
blah blah blah
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

<Directory /var/www/html/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
blah blah blah
```
- ``/etc/apache2/sites-available/000-default.conf``(this is on for logging reasons):
```
blah blah blah
RewriteEngine On
LogLevel alert rewrite:trace6
blah blah blah
```
- ``/var/www/html/ampache/rest/.htaccess``:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /play/$1 [PT,L,QSA]
</IfModule>
```
- ``/var/www/html/ampache/config/ampache.cfg.php``:
```
blah blah blah
web_path = "/ampache"
blah blah blah
access_control = "true"
```

### ACL Settings

DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Web Interface |  
-- | -- | -- | -- | -- | -- | --
DEFAULTv4 | 0.0.0.0 | 255.255.255.255 | All | All | Stream Access |  
DEFAULTv6 | :: | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | All | All | Web Interface |  
DEFAULTv6 | :: | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | All | All | Stream Access |  
Amarok | 192.168.11.0 | 192.168.11.255 | Read/Write | All | API/RPC |  
PowerAmpache | 0.0.0.0 | 255.255.255.255 | All | All | API/RPC

## Logs

``tail /var/log/apache2/error.log``:
```
[Thu Mar 11 15:28:42.899073 2021] [rewrite:trace4] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] RewriteCond: input='/var/www/html/ampache/rest/ping.view' pattern='!-d' => matched
[Thu Mar 11 15:28:42.899088 2021] [rewrite:trace4] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] RewriteCond: input='/var/www/html/ampache/rest/ping.view' pattern='!-s' => matched
[Thu Mar 11 15:28:42.899116 2021] [rewrite:trace2] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] rewrite 'ping.view' -> '/rest/index.php?ssaction=ping'
[Thu Mar 11 15:28:42.899127 2021] [rewrite:trace3] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] split uri=/rest/index.php?ssaction=ping -> uri=/rest/index.php, args=ssaction=ping
[Thu Mar 11 15:28:42.899139 2021] [rewrite:trace2] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] forcing '/rest/index.php' to get passed through to next API URI-to-filename handler
[Thu Mar 11 15:28:42.899151 2021] [rewrite:trace2] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] trying to replace context docroot /var/www/html with context prefix 
[Thu Mar 11 15:28:42.899161 2021] [rewrite:trace1] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9c9e0a0/initial] [perdir /var/www/html/ampache/rest/] internal redirect with /rest/index.php [INTERNAL REDIRECT]
[Thu Mar 11 15:28:42.899202 2021] [rewrite:trace2] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9ca4938/initial/redir#1] init rewrite engine with requested uri /rest/index.php
[Thu Mar 11 15:28:42.899214 2021] [rewrite:trace1] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9ca4938/initial/redir#1] pass through /rest/index.php
[Thu Mar 11 15:28:42.899278 2021] [rewrite:trace1] [pid 29748] mod_rewrite.c(476): [client 192.168.11.104:38892] 192.168.11.104 - - [192.168.11.140/sid#7f59f9cfc028][rid#7f59f9ca4938/initial/redir#1] [perdir /var/www/html/] pass through /var/www/html/rest
```

**Comment by SePHTaN** [comment]
I would suggest to change your Apache configuration as following:
```
        DocumentRoot /var/www/html/ampache
        <Directory /var/www/html/ampache>
                Options Indexes FollowSymLinks
                AllowOverride all
                Require all granted
                <FilesMatch "\.(php)$">
                        SetHandler "proxy:unix://var/www/html/ampache/conf/ampache-fpm73.sock|fcgi://ampache/"
                        ProxyErrorOverride on
                </FilesMatch>
        </Directory>
```
The FilesMatch directive is optional and only applicable if you also use PHP-FPM with the socketfile located in 
 `/var/www/html/ampache/conf`
 Your web_path also would then be `web_path = ""`
 With Apache2.xx configured that way ampache 4.4.0 including /rest/ping.view should work as expected.
 At least my installation works without any issues.

**Comment by BlueNalgene** [comment]
Thanks for the quick response @SePHTaN.  I had to enable the proxy using ``a2enmod proxy_http``, otherwise restarting apache2 gave me an error for ``ProxyErrorOverride``.

I added your snippet to my apache2.conf, and I changed my ampache.cfg.php to the empty ``web_path``.  I have php-fpm installed, but I do not have the socketfile you mention.

With these changes, I now get a 500 Internal Server Error on any path outside of the localhost root which displays the default apache landing page.

**Comment by BlueNalgene** [comment]
It looks like this was a RTFM problem.  From the [Subsonic page on the wiki](https://github.com/ampache/ampache/wiki/subsonic):

> Note: Default configuration assumes your Ampache installation resides at the root of your webserver. If you are serving it from a subfolder (say /ampache/), you should:
> 
> Set ``web_path`` in your config.
> ```
> web_path = "/ampache"
> ;local_web_path = ""
> ```
> Edit the ``.htaccess`` file accordingly, e.g. replacing ``/play/`` by ``/ampache/play``.

So now my ``rest/.htaccess`` looks like:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/play/$1 [PT,L,QSA]
</IfModule>
```

While I still can't access my Ampache from the Subsonic API, I am getting the correct response to ``ping.view``, which was the subject of this Issue.  Closing.
