### ISSUE TITLE
stats.php?action=show reporting individual catalogue sizes as time

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2825]
# Issue Template

## Description
Noticed that the statistics page is reporting individual catalogue sizes in days and hours instead of bytes.

**To reproduce**
Visit stats.php?action=show

**Expected behavior**
Individual catalogue sizes should be reported as MB, GB, TB etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/3216809/111082342-a7b33a80-84ff-11eb-8074-74c443b19358.png)

## Environment

* Ampache version: Ampache develop (latest commit)
* Web server + version: Apache 2.4.46, MySQL 8.0.23, PHP 7.4.15
* Server operating system: Fedora 33
* Client operating system: Ubuntu 18.04.5 LTS

**Client type:**

* Web

**Comment by lachlan-00** [comment]
looks like this is a converted template @usox `stats.xhtml`

i'm not totally familiar with these templates yet but it looks like it's just as simple as this?
![image](https://user-images.githubusercontent.com/1305249/111087918-2d6ece80-8570-11eb-9670-656ba186c7af.png)

**Comment by usox** [comment]
@lachlan-00 It actually is that simple.

**Comment by lachlan-00** [comment]
You have no idea how amazing that is to read after years of the hybrid templates

**Comment by rsinfotech** [comment]
Perfect! Latest commit closes this issue.

Thanks.
