### ISSUE TITLE
Upstream/edge branch doesn't display cover art.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#2826]
I created the catalog on the 'develop' branch to check something out on my feature branch.  The develop branch displayed the cover art correctly.

I then switched over to the upstream/edge branch and with the same catalog the cover art did not display.

Seems to me that something that obvious would be caught before being pushed upstream.

**Comment by usox** [comment]
Well, just run `composer install` after a branch switch and you're all good.

**Comment by wagnered** [comment]
Ok, thought I did, but probably got distracted.  Happens to me frequently.😟.

**Comment by usox** [comment]
It's all good :smile:
