### ISSUE TITLE
Empty Video list on develop

### ISSUE THREAD

**Issue by rodrigoesborges** [ampache/ampache#2834]
## Description
Clicking videos or movies results in empty pane, even though the total number of them is displayed.
### To reproduce

1. Go to Home
2. Click on Movies or Videos
4. See empty pane, no movies list populated

## Environment

* Ampache version: develop
* Web server + version: nginx + php-fpm 7.4
* Server operating system: Debian buster

### Client type

* Web

## Logs
Not sure if only this part is relevant::
```
SELECT `video`.`id` FROM `video` WHERE 1=1 ORDER BY `video`.`title` ASC []

Class 'video' not found

```

**Comment by usox** [comment]
Hi @rodrigoesborges 

Should be fixed in develop by now :)
