### ISSUE TITLE
Develop branch API 5 JSON - stats method with recent filter not using offset

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2841]
I noticed using the stats method with offset parameter does not seem to work with a filter of 'recent'.

I use the stats call for a number of album views and the same call works perfect for 'newest' and 'frequent' filters but I get the same results returned from the 'recent' filter no matter what the offset value is.

eg: My generic stats API call works fine for some filters with offset but not the 'recent' filter:

`$call = '?action=stats&type=album&limit=24&filter=' . $filter . '&offset=' . $offset;`

**Comment by lachlan-00** [comment]
you are very right, it's just getting the same thing
![image](https://user-images.githubusercontent.com/1305249/111921163-c6589900-8ade-11eb-9448-03da3184827f.png)

**Comment by lachlan-00** [comment]
i've extended the get_recently_played in master (c8df4592b) and will put that into develop as well today

**Comment by Andrew-McGee** [comment]
Nice one - thank you!

**Comment by lachlan-00** [comment]
in 18ef6225c too, that should cover you

**Comment by mitchray** [comment]
Closing as it seems to be addressed
