### ISSUE TITLE
Can't find the "Create Channel" setting

### ISSUE THREAD

**Issue by addrian1** [ampache/ampache#2842]
Hi everybody

I decided to try this solution for my project on ESP32. I saw a tutorial on how to set up http streaming. I installed ampache on my server, but the button I needed, which was in the channel creation guide, I did not find in my installation.
Maybe someone knows what the problem is?

![image](https://user-images.githubusercontent.com/18485323/111910036-5ad3e480-8a68-11eb-8ea1-faf60be709ea.png)

https://youtu.be/G3YOh-hgF6w?t=122

ampache version: 4.4.0
ubuntu 20.04

**Comment by usox** [comment]
Hi @addrian1 

Did you enable channels in the config?
```
; Channels
; Set this to true to enable channels and the
; possibility for users to create channels from playlists
; DEFAULT: "false"
channel = "true"
```

**Comment by lachlan-00** [comment]
The guide might be very out of date, channels have been disabled by default for a while due to their complicated nature.

**Comment by usox** [comment]
@addrian1 any news here?

**Comment by usox** [comment]
I don't expect a response in here.
