### ISSUE TITLE
Develop branch API 5 JSON - album method always returns 0 for time element

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2844]
Appears that the 'time' element returned by method 'album' is always 0.

I use this call:
`$call = '?action=album&filter=' . $uid;`

Previous code that works in API 4 and returned time as integer in seconds:
`$albm_results['time']`

Now with updated format for API 5 but the result returned is always 0:
`$albm_results['album'][0]['time']`

**Comment by usox** [comment]
Yep, is related to the new album-grouping feature. If enabled (dunno, maybe default) the duration was calculated before the list of albums actually got loaded - the result was always 0. Should be fixed with 32110e03d217ea738e3548f6fa63a931a28e0d08

**Comment by Andrew-McGee** [comment]
@usox You want me to close this one? I'm happy with it.

**Comment by usox** [comment]
If you're happy, we're happy, too :laughing:
