### ISSUE TITLE
Develop branch API 5 JSON - album method returns 'diskcount' not 'disk'

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2845]
Documentation says 'disk' not 'diskcount' (but diskcount would be more consistent).
https://raw.githubusercontent.com/ampache/python3-ampache/master/docs/json-responses/album.json

Here's a var_dump of what I get back from this call (note the 0 time reported in other issue):

array(1) { ["album"]=> array(1) 
	{ [0]=> array(16) 
		{ 
		["id"]=> string(3) "753" 
		["name"]=> string(26) "Chillout Lounge 4 (Disc 1)" 
		["artist"]=> array(2) 
			{ ["id"]=> string(3) "121" 
			["name"]=> string(15) "Various Artists" } 
		["time"]=> int(0) 
		["year"]=> int(2010) 
		["tracks"]=> array(0) 
			{ } 
		["songcount"]=> int(10) 
		["diskcount"]=> int(1) 
		["type"]=> NULL 
		["genre"]=> array(1) 
			{ 
			[0]=> array(2) 
				{ 
				["id"]=> string(2) "12" 
				["name"]=> string(10) "Electronic" } } 
		["art"]=> string(118) "https://edited_this_url/image.php?object_id=753&object_type=album&auth=28decb05ca1f8ac540459eafa683d2f9" 
		["flag"]=> int(0) 
		["preciserating"]=> NULL 
		["rating"]=> NULL 
		["averagerating"]=> NULL 
		["mbid"]=> NULL } } }

**Comment by usox** [comment]
This was renamed intentionally within b0b95ea7ae7b0357c682a2368d633414793d802b. I guess, it did not find it's way back to the documentation yet :)

**Comment by usox** [comment]
https://github.com/ampache/python3-ampache/pull/7

**Comment by lachlan-00** [comment]
@usox. the current develop will also need to un-objectify the data as well.

I've reverted the example in the repo but the updated calls you've put for album need to send just the json string.
https://github.com/ampache/ampache/discussions/2840#discussioncomment-510980

if you're not available today i'll finish off tomorrow. (end of my day here)

**Comment by usox** [comment]
@lachlan-00 as the bug is gone, the doc needs still to be updated, right?

**Comment by lachlan-00** [comment]
site needs an update, will do that now and close this

**Comment by lachlan-00** [comment]
updated, will do another run on the return docs as part of my template work.
