### ISSUE TITLE
[Bug] Regex don't working in smart playlists and tags/genres

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2851]
### Describe the bug

Smart playlist do not work with regex and tags, regex work with other kind of type of data like title.

### To reproduce

1.Create a smart playlist
2.Choose tags
3. Choose match regular expression
4. Write rock|metal as regular expression
5.Click search

### Expected behavior

The list should return songs with a tags containing rock or metal tag
The list returns random songs

## Environment

* Ampache version: 4.4.0 and 5
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by lusum** [comment]
I don't know, now it works

**Comment by lachlan-00** [comment]
it's not just the certain cases or a coincidence?
