### ISSUE TITLE
Update can't be finished

### ISSUE THREAD

**Issue by Dreadlocke12** [ampache/ampache#2857]
I tried to update from ampache version 4.3.0 to 4.4.1: After moving the update as well as the config file this appears: 
![Bildschirmfoto von 2021-03-28 21-26-23](https://user-images.githubusercontent.com/56894437/112765320-f9ce8280-900c-11eb-9833-afd65c309390.png)
I try to press update now but nothing happens. It is hosted on an Ubuntu Server 20.04.2 LTS. The PHP Version is 7.4.3.

**Comment by lachlan-00** [comment]
can you check the log for a sql error? it could be that the update failed partway through and there is a duplicate column in the database

**Comment by Dreadlocke12** [comment]
It seems the table playlist is damaged. I don't know how to fix it yet but thats why the update has stopped. I will try to fix that first and see if the update goes through without problem. Thanks for the hint and fast answer.

**Comment by dfduarte78** [comment]
I am stuck in 4.3.0 too.
I was in 4.2.4 and downloaded 4.4.2, got stuck in the update page where nothing happened.
Tried updating to 4.2.5, to 4.2.6, to 4.3.0, all OK!
4.4.0 or 4.4.2 shows me the update page where nothing happens :/
`This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is 4.4.2-release with database version 400013`

I'm on ubuntu 20.04 with apache2, var/log/mysql/error.log is empty
mysqlcheck on ampache DB is all OKs
I changed the owner of ampache folder to www-data during all updates and followed the other upgrade procedures...

What else i'm missing?
tks

**Comment by lachlan-00** [comment]
It's possible the 400014 update didn't complete.

You can manually run the SQL to update and it will continue from there. I'll paste the SQL to run here in a sec

**Comment by lachlan-00** [comment]
```
# UPDATE 400014
ALTER TABLE `playlist` ADD COLUMN `last_duration` int(11) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `album` ADD COLUMN `time` smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `artist` ADD COLUMN `time` smallint(5) unsigned NOT NULL DEFAULT '0';
# set the database version
UPDATE update_info SET value='400014' WHERE `key`='db_version'
```

**Comment by dfduarte78** [comment]
Hi there!
I don't have a **playlist** table, there is playlist_data, tmp_playlist and tmp_playlist_data.
I see the column time on both album and artist table.
My db_version is 400013.

**Comment by lachlan-00** [comment]
> Hi there!
> I don't have a **playlist** table, there is playlist_data, tmp_playlist and tmp_playlist_data.
> I see the column time on both album and artist table.
> My db_version is 400013.

you have way more problems than a missing update then. You're missing tables required for any sort of function. (possible more than )

I made a sql file from 4.3.0 with the default tables which won't overwrite any existing ones. From mysql the command is usually something like
```
mysql -u root -p ampachedatabase < ampache-create-table-defaults.sql
```

[ampache-create-table-defaults.zip](https://github.com/ampache/ampache/files/6543344/ampache-create-table-defaults.zip)

**Comment by dfduarte78** [comment]
Wow, almost there, but i get an error, i think it is on line 70
```
--
-- Dumping data for table `access_list`
--

`access_list` (`id`, `name`, `start`, `end`, `level`, `type`, `user`, `enabled`) VALUES
(1, 'DEFAULTv4', 0x00000000, 0xffffffff, 75, 'interface', -1, 1),
(2, 'DEFAULTv4', 0x00000000, 0xffffffff, 75, 'stream', -1, 1),
(3, 'DEFAULTv4', 0x00000000, 0xffffffff, 75, 'rpc', -1, 1),
(4, 'DEFAULTv6', 0x00000000000000000000000000000000, 0xffffffffffffffff, 75, 'interface', -1, 1),
(5, 'DEFAULTv6', 0x00000000000000000000000000000000, 0xffffffffffffffff, 75, 'stream', -1, 1),
(6, 'DEFAULTv6', 0x00000000000000000000000000000000, 0xffffffffffffffff, 75, 'rpc', -1, 1);

-- --------------------------------------------------------

```

**Comment by lachlan-00** [comment]
you can delete the insert if that fails. there isn't an easy way for me to know what's missing for you but if you at the very least keep all the create statements it should be okay
