### ISSUE TITLE
Docs Examples showing Error json

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2858]
## Description
Error examples for podcast methods (JSON) in documentation

### Describe the bug
Open the docs, scroll to podcasts methods, click on 'example'. The new page shows a json object with an error instead of an example of a correct response.

### Expected behavior
Example should show correct responses (error responses might be useful as well, but should not be the only example)

### Screenshots
E.g.: podcast_episode method:

```
{
    "error": {
        "errorCode": "4704",
        "errorAction": "podcast_episode",
        "errorType": "filter",
        "errorMessage": "Not Found: 6394"
    }
}
```

Not sure if it should be classified as bug, but it seems that these examples are auto generated, so probably some mistake is in that code.

**Comment by lachlan-00** [comment]
They are all generated and uploaded in one go so I might have missed it.

(150 files an upload so it's easy when it's not automated.) I'll fix when I wake up tomorrow

**Comment by lachlan-00** [comment]
As an aside it's really great to see so many people using this stuff.

**Comment by lachlan-00** [comment]
I've been trying to transfer to a reproducible server/database so this ight be a good issue to keep open while I do that

**Comment by memen45** [comment]
Thanks for responding so quickly!

Would it be possible to have the examples inline with the docs page as collapsible code blocks? That would make it easier to read as well.

**Comment by lachlan-00** [comment]
it's possible but maybe not in the current template, i need to work out why the doc menu isn't showing up too as it can get massive.

just going to make the same calls in my builder and work on the docs now

**Comment by lachlan-00** [comment]
Fixed up the errors in valid docs. There were a few more errors I didn't notice as well in develop so it was productive.

I've been working on my "template" server and i'll do a precommit script to look for obvious errors in the docs to make it a bit simpler.
