### ISSUE TITLE
Small artist art thumbnail on artist view with LastFM enabled

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#2859]
### Describe the bug
While looking into a way to increase the size of the artist art in Artist view in the web client, I found that the code seems to allow for this, but only if the LastFM API key is commented out in config (maybe empty string too...didn't test).   I can see in public/templates/show_artist.inc.php that it's only resizing the thumb if the LastFM API key cannot be fetched.  I'm unsure if this is a bug, or intended by design.  I'd prefer to not have to choose between nice and large artist thumbnails and LastFM!

![image](https://user-images.githubusercontent.com/8648894/113223733-dba89280-9257-11eb-9b86-e5623ff6e013.png)

### To reproduce

1. In ampache.config.php, uncomment `lastfm_api_key`
2. Open to an artist in the web client. The thumbnail appears to be the default size of 128x128

![image](https://user-images.githubusercontent.com/8648894/113224132-b7998100-9258-11eb-97f8-d0bd3cf4177f.png)

### Expected behavior
With the lastfm api key commented out, the thumb is larger and matches the album art size in album view

![image](https://user-images.githubusercontent.com/8648894/113224051-8c169680-9258-11eb-8f9a-49c0adf44987.png)

## Environment

* Ampache version: 5.0.0
* Web server + version: Apache 2.4.46
* Server operating system: Fedora 33
* Client operating system: Android and Fedora 33 Workstation

### Client type

* Web client

**Comment by lachlan-00** [comment]
It's meant to load a biography if it exists but I was going to look at hiding/moving that around a bit to keep the size the same.

**Comment by JoeDat** [comment]
Does last.fm still work for metadata?  It's been a while since I've seen biographies.  I don't scrobble, so can't validate that.   I have a registered api key and my server is registered as an application, but I've been seeing last.fm errors in my logs for months.

**Comment by usox** [comment]
Last.fm scrobbling does work - at least in develop, haven't tried it in the current released versions

**Comment by JoeDat** [comment]
Ok, thanks!  Now that I understand the intent, this becomes a Feature Request to allow large album art with LastFM enabled. Since it's already on the radar, I'll close this out as a non-issue.

**Comment by lachlan-00** [comment]
There's something i've noticed that empty non-null values are making the system believe that there is a bio when it's actually empty.

i had the fix ready but haven't tested enough. after that the page will then load the larger art when no bio is found

**Comment by JoeDat** [comment]
And so I understand, you did say that you were looking for a way to have both the bio and larger at coexist?  I'll play around with it on my end, see if I can get it to work.  My PHP skills are terrible, but can give it a shot!!

Worth reopening this as a Feature Request instead?

**Comment by lachlan-00** [comment]
e31c57dc3 and 057423630 should make this a little better.

no summary, larger image
![image](https://user-images.githubusercontent.com/1305249/113815071-f332ce80-97b5-11eb-87ec-20f9a7fbfd07.png)

summary, smaller thumb
![image](https://user-images.githubusercontent.com/1305249/113815186-1bbac880-97b6-11eb-96e5-77a9b7140743.png)

**Comment by JoeDat** [comment]
Nice, I dig it.  Thanks!

**Comment by lachlan-00** [comment]
if you want to do more/check other things out the show_podcast template puts the description outside the image div.
![image](https://user-images.githubusercontent.com/1305249/113951849-c0411700-9857-11eb-88e8-98b796323210.png)

It's all in 4.4.2 code now so if you think of anything else we can do it in a new issue.

**Comment by JoeDat** [comment]
I was trying to think of a way to have both this large art, while also having the bio.  This does it nicely.   I never thought to use Ampache for podcasts.  But, this inspired me to switch over to it.  I really like the way it looks.  Also, modifying the artist view to this adds a degree of uniformity.

**Comment by lachlan-00** [comment]
It does, but some artists Har pages of text. I know I limited it somewhere but can't remember where.

If it fits though we're still haven't finished 4.4.2
