### ISSUE TITLE
Subsonic clients can not stream music from Ampache 4.4.1

### ISSUE THREAD

**Issue by MyFilippo94** [ampache/ampache#2867]
## Description
Freshly installed and configured Ampache 4.4.1 in docker container is unable to stream music to Subsonic clients. 

### Describe the bug
Tested on DSub (Android) and Sublime Music (Linux). The client seems able to properly retrive all metadata and lists, but when attempting to play the music, or download the file, it doesn't.

### To reproduce

1. Open Subsonic client
2. Select any music, can be by playlist, by author, by album, by random...
3. Attempt to reproduce, or to cache
4. Listen to high quality silence, experience ultrafast 0kbps download speeds

### Expected behavior
Music starts to play, file gets downloaded

### Screenshots
This is a screenshot of latest DSub client on Android, notice the "Downloading - 0 B" message in gray.
[Link to image](https://drive.google.com/uc?id=1hUUtOFHUxWpMS-qojGiPFr4xLCMwF1nC) 

## Environment

* Ampache version: 4.4.1-release
* Server operating system: Ubuntu 20.04.2 LTS
* Client operating system: Android 11/Garuda Linux

### Client type
* SubSonic

**Comment by Bingenberger** [comment]
I struggled with similar problems. With two changes I got everythin up and running:

- In /etc/apache2/sites-available/ampache.conf I added _ServerAlias localhost_ below the entry _ServerName_
- In /var/www/html/ampache/config/ampache.cfg.php I set _local_web_path = "localhost"_

**Comment by MyFilippo94** [comment]
> local_web_path = "localhost"
That did the trick. It seems like a very stupid thing now, I am not sure how I managed to miss it.
Thank you a lot!
