### ISSUE TITLE
Develop - Artist song_count not incrementing after add/clean

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2871]
## Description
After adding an album the song_count for an artist on the album is not incremented even though the artist matches an existing artist.

### To reproduce

1. Add an album via the catalog add function on the web UI.
2. Check the DB to see if the song_count field of artist table has been incremented.

### Expected behavior
The song_count should be incremented.

### Screenshots
Here you can see that 2 songs exist in the db for a particular artist but the song_count is incorrect.

Song table showing artist id = 2200 you can see 2 titles
![Overview](https://i.postimg.cc/g0hjGHZB/song-table.png)

Now the artist table for id 2200 only shows song_count of 1.
![Overview](https://i.postimg.cc/wjCx4RG5/artist-table.png)

## Environment

Installed Ampache version (develop): 3565ede5c726e61b5b39101030d432b6d3d57293.

**Comment by Andrew-McGee** [comment]
I updated and ran an add from the GUI but didn't seem to change. Should I expect to see the existing artist song_count go up as in my screenshot?

Let me investigate more.

**Comment by usox** [comment]
Yepp, the song_count should change - at least, it did at my side. Strange...

**Comment by Andrew-McGee** [comment]
Just to be clear - it should increment for all artists right? Not just the ones I am adding.

**Comment by Andrew-McGee** [comment]
This is now working for me.  To confirm: the song_count updated for artists that were on a new album when I ran the add process and that album was added into the catalog. It did not update for all the existing artists.

When I ran a verify the other artists with incorrect song_count were all updated correctly.

Thank you.
