### ISSUE TITLE
Runtime Error on catalog clean when files got deleted

### ISSUE THREAD

**Issue by SePHTaN** [ampache/ampache#2879]
### Describe the bug

When you delete medias from your storage and run an clean or update catalog afterwards the logs gets filled with annoying runtime errors due to not checking wether a file does exist in Core::get_filesize()

### To reproduce

1. Delete some medias from your storage
2. Click on 'Clean all' in Show Catalogs
3. run 'cat yourlogfile | grep '[Runtime Error]'

### Expected behavior

Ampache should drop avoidable errors.

Fix for that Error is a simple file_exists check already part of my last pullrequest #2864 

## Environment

* Ampache version: develop
* Web server + version: nginx 1.14-2
* Server operating system: Debian 10
* Client operating system: Win10

### Client type

* Web

## Logs

`2021-04-11T14:55:24+02:00 [ampache] (log.lib) -> [Runtime Error] filesize(): stat failed for /mnt/testmusic/Musical/2007 Hairspray Soundtrack/05 Nikki Blonsky - I Can Hear the Bells.mp3 in file /var/www/ampache/public_html/src/Module/System/Core.php(378)
`

**Comment by lachlan-00** [comment]
would a return 0 instead of false work a bit better in #2864?

**Comment by usox** [comment]
Ah kay, @SePHTaN fixed this within f8f2d0d1c0054dd87e4a8d518199c5dae213d566
