### ISSUE TITLE
[Feature Request] Add Genres link to the Music Section.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2882]
## Describe what you don't like about Ampache, or what it is missing

Add a "Genres" link to music section, more than half of my users have asked how to browse genres, I explain the link is "Tag Cloud" for that, which they would have obviously never guessed.

## Describe how you would like the feature to work**

I would like there to be a Genres link in the music section, currently I just do this after every ampache update to add the link:

```
	# Browse album_artist instead of artist (otherwise top NAV bar is missing):
sed -i 's/\?action=artist/\?action=album_artist/' /var/www/ampache/templates/sidebar_home.inc.php

	# Add Genre Link to music section if missing:
grep -q 'Genres' /var/www/ampache/templates/sidebar_home.inc.php && echo 'genre link already exists' || sed -i '/_artist"><?php echo $t_artists; ?><\/a><\/li>/a <li id="sb_home_browse_music_tags"><a href="<?php echo $web_path; ?>\/browse.php?action=tag">Genres<\/a><\/li>' /var/www/ampache/templates/sidebar_home.inc.php
```

**Comment by lachlan-00** [comment]
Genre is in the browse section in develop but won't be changing in the 4.x ui.
![image](https://user-images.githubusercontent.com/1305249/114815349-5dbcbd80-9df9-11eb-9256-9d245c0a3821.png)

**Comment by lachlan-00** [comment]
I also want to change the genre page to get rid of that cloud page all together. My genre list is over 500 and it's unusable.

I'm going to make it like the search page and use it only for genres.

**Comment by xekon** [comment]
My Genre List is actually quite clean, but only because I set the genre tags myself according to file structure, this is for 2,287 albums:

![2021-04-15_00-39](https://user-images.githubusercontent.com/106644/114832279-2ad7e280-9d83-11eb-9617-00de2a4092d2.png)

**Comment by SePHTaN** [comment]
Might be a good feature for some people to allow merging of genres depending on personal reassignment.
Lets say for example you have albums tagged as 'Alt. Rock'. 
When reassigning an Album from "Alt. Rock" to "Alternative Rock" ampache could ask wether all Albums tagged as Alt. Rock should be reassigned to Alternative Rock.
Other possibility could be giving tables which tell ampache which genres should be grouped into a new genre.

On the other hand, this needs to be carefully considered. Besides compilations, i personally do have lots of albums where you could not assign the same genre to all songs cause they simply aren't from the same genre.
Could be though a possibility to reduce the number of almost identical genres displayed by ampache.

**Comment by xekon** [comment]
> On the other hand, this needs to be carefully considered. Besides compilations, i personally do have lots of albums where you could not assign the same genre to all songs cause they simply aren't from the same genre.

I have some albums like this as well, I just pick the genre that fits best overall, but with your idea I could assign multiple genres to an album and let it sort it out such as an album that has all these genres:

Alt. Rock
Punk Rock
Transdelic Rock
Phsycho Rock
Pop Rock

based on my preferences this albums song would instead become both or one of these genres, depending on which genres it started with:

Alternative Rock
Pop Rock

being able to consolidate genres would be a really neat feature. I would probably make it one of the catalog update features so that there is Not a performance impact during normal operation.

**Comment by xekon** [comment]
Thanks, 5.0 has the genre link! perfect.
