### ISSUE TITLE
playlist share

### ISSUE THREAD

**Issue by bfd69** [ampache/ampache#2887]
Hello
dont know if its the right place for requesting this, i love ampache and found the share functionality awesome !
i'm currently using version 4.4.1 and i'd love to have the share functionality for play lists, it seams that its actually only available for albums !
other things that would be great in share :
- make qrcode accessible even after share is created
- make longer passwords 50 chars would be a minimum
- make the download part work when you share, it is not prompted if you want to make download available when creating shares ! but when list your shares there is a column for download availability

please continue the good work on shares !
thanks a lot

**Comment by lachlan-00** [comment]
you can definitely share playlists as long as it's enabled in options a share option shows up.
![image](https://user-images.githubusercontent.com/1305249/115181950-66283780-a11c-11eb-9f16-1e13ca9b12ea.png)

Once that is on you need user level access to make shares. If you can share albums there is no extra step for playlists.

If you want smartplaylists they are not able to be shared right now

the advanced share lets you set download/stream
![image](https://user-images.githubusercontent.com/1305249/115182303-172ed200-a11d-11eb-8401-3942f5f68263.png)

the character limit in secret is 20 in the database

**Comment by bfd69** [comment]
thanks a lot for the reply
but wait wow, i already set "allow share" but when i open a play list i dont have "share", its only available on album !
and when i go in "advanced share" i dont have the option "Allow Download" 
is it part of the prerelease ?

**Comment by lachlan-00** [comment]
I didn't check whether download was hidden based on config but I'll have to double check

There is def not a recent change to downloads/shares so it might be good to dig down and work out if there's a bug because 4.4.2 will be soon as well.

When I'm free tomorrow I'll post some links to check that you can follow with a playlist. (On my phone now)

**Comment by bfd69** [comment]
ok, thanks again,
i will wait for tomrorow then.
please can you also check why "share" is absent on playlist
there is also a bug where share icon is never shown (just text) while the icon file is present on images folder, but i dont mind, the most important is the share link on playlist.
if you need my conf files just ask, 
thanks a lot

**Comment by lachlan-00** [comment]
First up get a playlist ID and try going directly to the link page
![image](https://user-images.githubusercontent.com/1305249/115360875-62231500-a203-11eb-827e-cd72538c317f.png)

then with the id go to the advanced share page
`/share.php?action=show_create&type=playlist&id=2002`

which should show up for you
![image](https://user-images.githubusercontent.com/1305249/115361061-8e3e9600-a203-11eb-8bd3-13de142d3683.png)

**Comment by lachlan-00** [comment]
if you don't see the share icon for that could be a misconfigured webserver. Images are fetched using url rewriting
![image](https://user-images.githubusercontent.com/1305249/115361169-a7dfdd80-a203-11eb-8cb0-783d71df8636.png)

**Comment by bfd69** [comment]
Hello
i tried /share.php?action=show_create&type=playlist&id=11
and it showed me the the share form as you said
![image](https://user-images.githubusercontent.com/66788605/115366021-35500d00-a1c5-11eb-997c-92f0a7766c1f.png)
i'm checking the rewrite part...

**Comment by bfd69** [comment]
meanwhile the share icon is the only one not showed, already checked, rights and i could open it with any image viewer

**Comment by bfd69** [comment]
ampache is hosted directly in apaches htdocs, how can i check the url rewriting ?
i didnt set web_path in conf file.
no more ideas :(

**Comment by bfd69** [comment]
hello
did you find something ? will this be corrected in 4.4.2 ?

Best regards

**Comment by bfd69** [comment]
firstly i updated to 4.4.2 but icon still dont show, i copied icon_share.png to icon_test.png na d in firefox i tried in inspect mode to change icon_share.png to icon_test.png then it showed up ! it was just for test purpose, where is locate the url rewrite part ?

secondly, i inspected the template show_playlist.inc.php in my folder and in the git 

and there is no sign of share functionality, i found all other entries that shows up when you edit (save track order...delete) but no "share playlist", although i'm not sure if its the right file to look in but something seems missing.

if you could look and help me that would be awesome.
thanks for your help  lachlan-00

**Comment by wagnered** [comment]
> possibly he was referring to:

![Edited_20210507_121434](https://user-images.githubusercontent.com/6115438/117498936-56d42700-af2f-11eb-8198-23589fc9bb62.jpg)

All dynaic settings can be found under the "admin/system onfig" item.
"Allow Share can be found on the adinoptions" tab.

**Comment by lachlan-00** [comment]
think we good here
