### ISSUE TITLE
Unauthorized error connecting to subsonic API while podcasts disabled

### ISSUE THREAD

**Issue by bill-bateman** [ampache/ampache#2902]
## Description
Unauthorized error connecting to subsonic API while podcasts disabled - maybe should be a Data Not Found error instead.

### Describe the bug
I was trying to connect my subsonic client to ampache, but it wouldn't connect, saying I wasn't authorized. I checked, double-checked, triple-checked the ACL, finally figured out that it was only giving me an error because podcasts weren't enabled (I looked at which request was failing and checked the source). After I edited `config/amapche.cfg/php` to have the line `podcast = "true"` I was able to connect Jamstash to the subsonic API without errors.

To be clear, I could actually play music the whole time, but I didn't realize, because Jamstash was showing me the unauthorized error so I thought something was wrong.

### To reproduce

Default install, tried to connect Jamstash to Ampache.

### Expected behavior
I suppose the error shouldn't be unauthorized. I'm assuming it's because of this function (https://github.com/ampache/ampache/blob/develop/src/Module/Api/Subsonic_Api.php#L2231). If `podcast` is not set then it will give an unauthorized error.

Maybe it could give error code 70: `The requested data was not found.` So `SSERROR_DATA_NOTFOUND` instead of `SSERROR_UNAUTHORIZED`.

## Environment

* Ampache version: 4.4.1-release
* Web server + version: Apache/2.4.41
* Server operating system: Ubuntu 20.04
* Client operating system: Windows 10

### Client type

* SubSonic: Jamstash 4.7.1

**Comment by lachlan-00** [comment]
i've made this change in 1a20a1ccc

i think that will help other apps as well
