### ISSUE TITLE
[Feature Request] Radio Cover Art

### ISSUE THREAD

**Issue by The-Exterminator** [ampache/ampache#2917]
Can one put picture on the radio station. ??
Right now there is just a standard "picture not found"

**Comment by lachlan-00** [comment]
You sure can

**Comment by lachlan-00** [comment]
![Screenshot_20210512-205543_Firefox Nightly.jpg](https://user-images.githubusercontent.com/1305249/117964125-97cf9f80-b364-11eb-971b-065570485877.jpg)
Same as cover art for albums. Just click the gear and pick your photo/picture

**Comment by The-Exterminator** [comment]
I get only this when i click on the gear :
![billede](https://user-images.githubusercontent.com/6666710/118012062-f68b1e00-b350-11eb-9c2c-26774ec0c885.png)

**Comment by lachlan-00** [comment]
It's on the radio page not in the list 

```
radio.php?action=show&radio=10
```
