### ISSUE TITLE
Now playing not working with iSub

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2918]
### Describe the bug

When clicking Playing item on iSub menu instead to return the now playing playlist the app returns:

> Error : There was an error loading the now playing list.
> 
> Error 2: This is not XML data

The call the app is doing to the server:

/ampache/rest/getNowPlaying.view?v=1.0.0&c=iSub&u=myuser&p=mypass

The server returns:

>HTTP/1.0 500 Internal Server Error

 ( on tcpdump )

or, using the browser

>XML Parsing Error: no root element found
>Location: /ampache/rest/getNowPlaying.view?v=1.0.0&c=iSub&u=myuser&p=mypass
>Line Number 1, Column 1:

### To reproduce

As above

### Expected behavior

As above

## Environment

* Ampache version: 4.4.2
* Web server + version: apache
* Server operating system:
* Client operating system: iSub 4.0.2 build 413 ( ipad )

### Client type

* SubSonic

**Comment by mitchray** [comment]
Was this previously working but now broken? Double check the .htaccess files are present

```
cp ./rest/.htaccess.dist ./rest/.htaccess
cp ./play/.htaccess.dist ./play/.htaccess
cp ./channel/.htaccess.dist ./channel/.htaccess
```

Also make sure you have ```web_path = "/ampache"``` in your config, based off that URL

**Comment by lachlan-00** [comment]
It's a bug when pulling the song. If you aren't playing there is no error.

```
H01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Object of class Ampache\\Repository\\Model\\Song could not be converted to string in /var/www/music/src/Module/System/Dba.php:85\nStack trace:\n#0 /var/www/music/src/Module/System/Dba.php(85): PDOStatement->execute()\n#1 /var/www/music/src/Module/System/Dba.php(61): Ampache\\Module\\System\\Dba::_query()\n#2 /var/www/music/src/Module/System/Dba.php(122): Ampache\\Module\\System\\Dba::query()\n#3 /var/www/music/src/Module/Api/Subsonic_Xml_Data.php(725): Ampache\\Module\\System\\Dba::read()\n#4 /var/www/music/src/Module/Api/Subsonic_Xml_Data.php(708): Ampache\\Module\\Api\\Subsonic_Xml_Data::getSongData()\n#5 /var/www/music/src/Module/Api/Subsonic_Xml_Data.php(1201): Ampache\\Module\\Api\\Subsonic_Xml_Data::addSong()\n#6 /var/www/music/src/Module/Api/Subsonic_Api.php(878): Ampache\\Module\\Api\\Subsonic_Xml_Data::addNowPlaying()\n#7 [internal function]: Ampache\\Module\\Api\\Subsonic_Api::getnowplaying()\n#8 /var/www/music/src/Module/Api/SubsonicApiApplication.php(204): call_user_func()...'
```

**Comment by usox** [comment]
Covered by cd954e2d2d401fa1c4598d16ed0f5807ab3aae52 in develop

**Comment by lusum** [comment]
I have applied the develop patch to 4.4.2 and it works. Only one additional problem, checking the answer i notice this field:

> minutesAgo="1619742703.001"

It seems wrong, maybe, the time is to fix?

**Comment by lachlan-00** [comment]
> I have applied the develop patch to 4.4.2 and it works. Only one additional problem, checking the answer i notice this field:
> 
> > minutesAgo="1619742703.001"
> 
> It seems wrong, maybe, the time is to fix?

that's definitely wrong. i'll fix that up now

**Comment by lachlan-00** [comment]
fixing now with 37040d615
The play action was replacing now-playing for every segment loaded with the current time. you'd never get to 1 minute ago as the segments would replace itself.

I'll put into master now too

**Comment by lusum** [comment]
Solved
