### ISSUE TITLE
[Feature Request] summary, smaller thumb

### ISSUE THREAD

**Issue by The-Exterminator** [ampache/ampache#2919]
Hello, how Can i set this up ???

summary, smaller thumb

 ![image](https://user-images.githubusercontent.com/1305249/113815186-1bbac880-97b6-11eb-96e5-77a9b7140743.png)

**Comment by lachlan-00** [comment]
Do you mean cache a summary for the artist?

**Comment by The-Exterminator** [comment]
> Do you mean cache a summary for the artist?
> (The art is smaller when the summary is found)

Yes, i mean the summary.

**Comment by lachlan-00** [comment]
Currently this is from last FM. You need an api key and it's pulled on load.

We are working on other places to pull summaries from but currently only last fm

**Comment by The-Exterminator** [comment]
> Currently this is from last FM. You need an api key and it's pulled on load.
> 
> 
> 
> We are working on other places to pull summaries from but currently only last fm

My API key is om the config file fra last.fm and Spotify, But the summary is not on the artist

**Comment by The-Exterminator** [comment]
Have tried everything now and can not make it work, but Can see it also does not work
anymore on Airsonic Advanced 11, (Edge Release 11.0.0-SNAPSHOT.20210504201650)
maybe Last.fm has done something about in their api. ???

**Comment by wagnered** [comment]
There is no default language.  If the summary isn't in your language, or the langage code isn't understood, a summary will not be returned. 

Try this url directly in your browser's adress bar substituting your own api key:
"http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Cher&api_key=[your_lastfm_api]&lang=en"
It returns a summary on the develop branch, Except with the Korean language.

The other possibility could be that the api_key is incorrect.  if it isn't, an empty text is returned. That is not an exception, so the event isn't logged.

**Comment by The-Exterminator** [comment]
> 
> 
> There is no default language. If the summary isn't in your language, or the langage code isn't understood, a summary will not be returned.
> 
Thanks, is not work with danish :(
but can one do, so if the language is not supported, then it takes English ???

**Comment by wagnered** [comment]
I added the 'enhancement' tag.  The possibility will be explored.  One problem I see is that a catalog with many songs/artsts will be very slow to finish importing.  It probably will be available only for Ampache 5.*.
