### ISSUE TITLE
Unable to get dependencies - Composer Error Exception

### ISSUE THREAD

**Issue by bashynx** [ampache/ampache#2928]
## Description

Hi, I tried installing ampache, but I run into the wall with composer:

Running command "composer install" doesn't work for me, I can't get dependencies
```
@BashysVPS:/var/www/bashynx/ampache $ composer install --prefer-source --no-interaction
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/GitDownloader.php:253
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/SvnDownloader.php:132
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file


  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

my composer version:
```
@BashysVPS:/var/www/bashynx/ampache $ composer --version
Composer version 1.2.2 2016-11-03 17:43:15
```

my php version (FYI, in installation guide you say 7.1 minimum, but it didnt work unless I downloaded 7.4)
```
@BashysVPS:/var/www/bashynx/ampache $ php --version
PHP 7.4.18 (cli) (built: May  3 2021 12:02:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.18, Copyright (c), by Zend Technologies
```

my linux version:
```
@BashysVPS:/var/www/bashynx/ampache $ uname -a
Linux BashysVPS 5.10.37 #1-vpsAdminOS SMP Tue May 18 15:26:02 UTC 2021 x86_64 GNU/Linux

@BashysVPS:/var/www/bashynx/ampache $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

I wanted to get the zip file from the guide, "ampache-x.x.x_all.zip" but I cant see it linked anywhere.

**Comment by usox** [comment]
Hi @bashynx 

First of all: Please find the ready-to-use zip-packages at the release page: https://github.com/ampache/ampache/releases

The composer error looks weird but tbh I'm using composer 2 for quite some time now - maybe it's related to the legacy composer 1?

Regarding your php version: I assume you've checked out the develop branch? Develop represents the upcoming major release which requires php 7.4 to run. The current stable branch (ampache 4.x) uses 7.1.

**Comment by bashynx** [comment]
> First of all: Please find the ready-to-use zip-packages at the release page: https://github.com/ampache/ampache/releases
 Thank you for your reply, I can see it now

> The composer error looks weird but tbh I'm using composer 2 for quite some time now - maybe it's related to the legacy composer 1?
The instalation guide specifically says to use composer 1, so perhaps that's the problem. I didn't try it,

> Regarding your php version: I assume you've checked out the develop branch? Develop represents the upcoming major release which requires php 7.4 to run. The current stable branch (ampache 4.x) uses 7.1.
That will be it, I didn't rpecify branch, and it defaulted to develop.

Now I checked out the master branch, and got composer 2, but I still get the error:
```
./composer.phar update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires blueimp/jquery-file-upload 10.2.0, it is satisfiable by blueimp/jquery-file-upload[v10.2.0] from composer repo (https://repo.packagist.org) but blueimp/jQuery-File-Upload[9.18.0] from package repo (defining 1 package) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - oomphinc/composer-installers-extender[v1.1, ..., v1.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires oomphinc/composer-installers-extender ^1.1 -> satisfiable by oomphinc/composer-installers-extender[v1.1, v1.1.1, v1.1.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

Do I need to use composer? Because with quick check I don't see a difference between what is in the zip and what I got from master.

**Comment by wagnered** [comment]
The difference between the zipped file and the master branch is that for the zip package, composer was run and the resulting vendor package was already included in  the zip file

Running `composer self-update --1` will revert composer to 1.10.22 and should run fine in the master branch.

**Comment by bashynx** [comment]
> Running `composer self-update --1` will revert composer to 1.10.22 and should run fine in the master branch.

Thank you! Seems that that worked.

So I finally got the composer part over with, hopefully the rest will be easy. Thank you all for help <3
