### ISSUE TITLE
[XML API Bug] "artist_albums" method contains no "songcount" information

### ISSUE THREAD

**Issue by BLeeEZ** [ampache/ampache#2932]
### Describe the bug
A request to the xml api function "artist_albums" returns the following information.

```
...
<album id="48">
    <name><![CDATA['74 Jailbreak]]></name>
    <artist id="58"><![CDATA[AC/DC]]></artist>
    <time>1456</time>
    <year>1984</year>
    <tracks/>
    <songcount/>
    <diskcount>1</diskcount>
    <type/>
    <art><![CDATA[ EMOVED_BY_MYSELF]]></art>
    <flag>0</flag>
    <preciserating/>
    <rating/>
    <averagerating/>
    <mbid><![CDATA[]]></mbid>
  </album>
...
```

As you can see the "songcount" is included in the response but is empty instead of "5".
The content of "songcount" is always empty independent from the requested artist id.
This bug occurs since the update to the latest develop docker image.

## Environment

Ampache via docker on develop tag -> Ampache git commit c4562d92a089bdc5b2d68fa550c3b4a72a8d20c4

**Comment by lachlan-00** [comment]
I think it's probably the grouped join in the album repository. it needs to take out null values instead of assuming they all exist like album::check
```
$sqlw = "WHERE " . $name_sql . "`song`.`album` IN (SELECT `id` FROM `album` WHERE `album`.`release_type` $release_type AND `album`.`release_status` $release_status AND " . "`album`.`mbid` $mbid AND `album`.`album_artist` $artist AND `album`.`year` = " . (string)$this->year . ") ";
```

But i'm going to add a song_count column to the album table to skip having to format for this.

**Comment by lachlan-00** [comment]
song_count is now in the database and counted on construct so it will always be there.
ca30aaf71  and  5a9bb0159 have the database updates and the api, grouping and count changes

The api will now also respect album_group preferences when showing the album total with a new count total

**Comment by BLeeEZ** [comment]
I have tested the latest develop branch and the issue is fixed. Thank you.
