### ISSUE TITLE
[Feature Request] Search by album and add to playlist should maintain grouping

### ISSUE THREAD

**Issue by robot3498712** [ampache/ampache#2933]
## Describe what you don't like about Ampache, or what it is missing

Following use case:
I typically want to listen to **albums**, i.e. **first track to last track**. So I use _Search > Album > Rules_. Results are displayed and grouped by album as expected.
Now I want to **output this list to a playlist**, so I can play it via dSub: _Add Search Result_.
This queues all the tracks, but unfortunately in what appears to be random sort order (or by track number (of the entire set), whatever). In a nutshell, it won't play the albums as described above.

## Describe how you would like the feature to work**

Could _Add Search Result_ stick to the order output by search, or be configured doing so on demand?
This would be here: 1) By Album 2) By Track

I tried to work around this problem but didn't find a solution yet. If such exists, please tell me.

Ampache 4.4.2-release

**Comment by robot3498712** [comment]
Found an issue here:
**Add to playlist** is bugged.

_Search > Album > Add Search Result > Save to playlist_

It adds the exact item count, but the tracks are all wrong when inspecting playlist contents.
Items added by song_id, which was album_id via search result.

**Comment by lachlan-00** [comment]
i'm in search, so i'l check it out now

**Comment by robot3498712** [comment]
Thanks lachlan-00.
Ampache 4.4.3-release - confirmed not fixed

> add to playlist from the temp list
Yes, my reports aren't very precise. The temp list is populated incorrectly, then creating a playlist based on that may be as well, but the temp list creation is the main issue ("Items added by song_id, which was album_id via search result.").

I appreciate you looking into it. Please know that it isn't super-high priority (for me), since I meanwhile started using the python api, which is the workaround I was hoping for.

**Comment by lachlan-00** [comment]
we're doing a lof of indexing and caching in things so it would be good to look at

**Comment by lachlan-00** [comment]
i just need to check how tmp_playlist is read and it's probably very simple.

as part of this issue i should also look more at tmp_playlist for caching searches.

**Comment by lachlan-00** [comment]
I think this has been resolved. can you tell me if these are the same steps you used?

* Go to `search.php?type=album`
* Search for albums
* get results and click "Add to Temporary Playlist"
* in the rightbar click add to new playlist
![image](https://user-images.githubusercontent.com/1305249/125230377-01940780-e31c-11eb-9e14-350df59e9608.png)
* go to `browse.php?action=playlist`
* Playlist matches temp playlist
![image](https://user-images.githubusercontent.com/1305249/125230478-2ee0b580-e31c-11eb-925e-0939546ecf2c.png)

**Comment by robot3498712** [comment]
Delightful news, lachlan-00.

I believe the steps match. I recorded a short video as well so you can double-check: https://streamable.com/5i8ytt

Thanks for your efforts.

**Comment by lachlan-00** [comment]
definitely fixed in develop but need backfixes to 4

**Comment by lachlan-00** [comment]
for master it's fixed in 5622b8ce6 but won't be released for a while while i work on 5

**Comment by robot3498712** [comment]
Brilliant, thanks a lot. I applied the patch and confirm this fixes it.
