### ISSUE TITLE
The next song always jump back to the first song in the list in Subsonic clients when Ampache server used in Jukebox/Localplay mode.

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#2934]
### Describe the bug

I am using Ultrasonic with Ampache in Subsonic API. It works fine in general but there is an issue with localplay and jukebox mode (the client controls it)

I can load bunch of songs in jukebox (which is localplay in Ampache) mode in Ultrasonic or Dsub. I can play the songs in localplay mode from the clients, but everytime I pres next, it goes back to the first song which you can see in the Ampache logs below too.

I can however move to the next song alright if I just use the local Mpd controller like Ncmpcpp. So this must be something todo with the Subsonic Api rather than the actual Mpd controller or the Subsonic clients.

It would be super nice if this functionality is supported properly since it makes it easy to control it from a mobile device as well. it seems like it is almost almost there.

### To reproduce

1. Download Dsub or Ultrasonic
2. Add you Ampache as a server
3. add bunch of songs
4. Select jukebox mode in Ultrasonic or casting in Dsub
5. press next to try to load the next song.

### Expected behavior
it should play the playlist properly.

## Environment

* Ampache version: 4.4.2
* Web server + version: Apache2 2.4.46
* Server operating system: Debian Linux
* Client operating system: Android

### Client type

* SubSonic

## Logs
```
2021-06-03T00:21:03-05:00 [USER] (Stats) -> Repeated the same Song too quickly (168/559s), not recording stats for {392999} 
2021-06-03T00:21:08-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0 
2021-06-03T00:21:08-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0 
2021-06-03T00:21:13-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0 
2021-06-03T00:21:13-05:00 [USER] (Localplay) -> Error: Unable to skip to next song, check mpd controller 
2021-06-03T00:21:14-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0 
2021-06-03T00:21:19-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0 
2021-06-03T00:21:24-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.

```

**Comment by gerroon** [comment]
I tried the same setup but with Vlc localplay this time, still hitting an API thing

`2021-06-03T12:59:15-05:00 [USER] (Subsonic_XML_Data) -> API fail in function jukeboxcontrol-1.13.0`

**Comment by lachlan-00** [comment]
It's definitely in need of work. So much so that I started just using Bluetooth instead.

I think there are problems with the position/track choice but not something I've investigated fully.

**Comment by gerroon** [comment]
Are there any plans to make this for in 5.x series?

**Comment by lachlan-00** [comment]
yeah i think it's a good thing to fix sooner than later. Now that i've added playqueue and track status data i should be able to work this out.

I think previously it was falling back to track one because it was unable to determine what 'next' actually was and went back to the start.

**Comment by lachlan-00** [comment]
@gerroon its actually really obvious...
![image](https://user-images.githubusercontent.com/1305249/149875908-87db7e23-2c0c-4e83-a8bf-1cba717843ac.png)

I can get that part fixed and it will hopefully pick up the correct track

**Comment by lachlan-00** [comment]
added the mpd index with adc2d2e79 i need to re-set up an mpd server as i gave my old stuff away. will look again soon but this change might solve all the issues with index reporting

**Comment by gerroon** [comment]
Hi,

Is this fixed? I just tried 5.3.1 and it still does not work properly, at least in Ultrasonic.

**Comment by gerroon** [comment]
It plays the first few seconds and it rewinds back to the begnning of the song.

**Comment by lachlan-00** [comment]
i've played it a few times in dsub but haven't played enough to test it thoroughly.

i'm working on subsonic pretty much exclusively outside of bugs now so we can look at why this is happening

**Comment by gerroon** [comment]
I tested it with Dsub and Ultrasonic, they both seem to have this issue against 5.3.1. I am just reporting for confirmation purposes. Let me know if you want me to test these features later.

**Comment by lachlan-00** [comment]
i bought new speakers and a new pi for moode so i can test this a lot easier now.

the one thing that i don't get is how the playlist is restored/compared between mpd when picking up the jukebox mode. like do you have to clear the current mpd list to use jukebox mode with subsonic?

**Comment by gerroon** [comment]
When I use the jukebox mode with Ultrasonic, it uploads whatever is in the current Ultrasonic playlist as a new list and overrides the existing playlist in MPD.

**Comment by lusum** [comment]
pull request refert to the wrong thread, ignore it

**Comment by lusum** [comment]
> When I use the jukebox mode with Ultrasonic, it uploads whatever is in the current Ultrasonic playlist as a new list and overrides the existing playlist in MPD.

It seems the default behaviour of localplay, i see the same behaviour working with xbmc

**Comment by lusum** [comment]
I have tested with ultrasonic and jukebox mode and xbmc localplay. One example. Adding an url to ampache correctly takes the form http://serveraddr/play/.... , instead subsonic jukebox mode generates an url like: http://localhost/play.
So , i have the same behavior described in this issue. The problem lies in the add function in jukebox mode. ( ps: forcing the url to be correct in the add function, i have found other problems. So, it is not so simple to solve )

**Comment by lusum** [comment]
Changing this line :

https://github.com/ampache/ampache/blob/73d07d2878fd6a4156a002e3dc378a4590dd09f3/src/Module/Api/Subsonic_Api.php#L2080

to:

**Comment by lusum** [comment]
Fixed with https://github.com/ampache/ampache/pull/3794
