### ISSUE TITLE
[Bug] Multiple subsonic api issues in 5.0-develop api

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2936]
### Describe the bug

Testing ampache 5.0 develop with ultrasonic and doing a tcpdump of the answers i have found some bugs. The testing were done with 4.4.3 and 5.0-develop to check the right answer along with the wrong one. The catalogs are quite equivalent ( same albums, different rating ).

I describe every bug one by one and i attach the files with the correct 4.4 answer and the incorrect 5.0-develop

First one:

The images content type sometimes is sent as:

> Content-Type: text/html; charset=UTF-8

[images4.txt](https://github.com/ampache/ampache/files/6616580/images4.txt)
[images5.txt](https://github.com/ampache/ampache/files/6616581/images5.txt)

Doing other tests: the problem appears when the album has no image

Second: getAlbumList.view?type=frequent ignores size parameter and apply junk at start of the answer

[frequent5.txt](https://github.com/ampache/ampache/files/6616608/frequent5.txt)

Third:  highest seems to send two different answers to the same request
From ohers testings, the call seems ok, maybe other bugs mess up the client.

[highest5.txt](https://github.com/ampache/ampache/files/6616614/highest5.txt)

Forth: starred keeps sending the same albums over and over again
also send some more fields like this
                "created": "2020-10-26T22:59:45+01:00",
               "userRating": "5",
                "averageRating": "5",
different from 4.4, i don't know if they are the problem or they are compatible with subsonic

[starred5.txt](https://github.com/ampache/ampache/files/6616649/starred5.txt)

The following file is the correct one for highest-starred 4.4 answers

[highest-starred4.txt](https://github.com/ampache/ampache/files/6616651/highest-starred4.txt)

Fifth: starred doesn't show starred albums but some random one and ( i suspect  ) it sends an error when no album is present instead an empty list

This one additional bug seems to be present in 4.4.3 : the outuput for starred albums in web interface and in subsonic api is different.

demoserver command 

https://demo.ampache.dev/rest/getAlbumList.view?type=starred&size=20&offset=0&u=demo&c=Ultrasoninic&f=json&v=1.13.0&p=demodemo

## Environment

* Ampache version: 5.0-develop
* Web server + version: apache 2.4
* Server operating system:  linux
* Client operating system: android

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by lachlan-00** [comment]
Second: getAlbumList.view?type=frequent ignores size parameter and apply junk at start of the answer
Limit set with 14c39553b
I don't see the junk on my calls though.

**Comment by lachlan-00** [comment]
Third: highest seems to send two different answers to the same request
I think 7752dcbf0 and 2176462dc might cover that one. the count was counting each disk as a rating which wasn't correct. it's grouped and ordered correctly

**Comment by lachlan-00** [comment]
Forth: starred keeps sending the same albums over and over again
fixed with aa2310804 offset wasn't sent

**Comment by lachlan-00** [comment]
Forth part 2:
* fields have been added to that were missing from the schema http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.13.0.xsd (see `<xs:complexType name="Child">`)

sublime music is pretty strict with the api so it's required a bit of change and they haven't been going back to 4

Fifth: starred doesn't show starred albums but some random one and ( i suspect ) it sends an error when no album is present instead an empty list
* starred gets the stars for your user with ad1a08979
* the errors have been added, we'll need to do more testing, should this be per user or server-wide?

**Comment by lachlan-00** [comment]
Fifth part 2
901be681a puts grouping like the third issue. I fixed up develop.ampache.dev subsonic so you can test against that one now too

the test url worked correctly against the albums i loved/unloved
`https://develop.ampache.dev/rest/getAlbumList.view?type=starred&size=20&offset=0&u=demo&c=Ultrasoninic&f=json&v=1.13.0&p=demodemo`

**Comment by lachlan-00** [comment]
First: The images content type sometimes is sent as html text

* art should probably be a 404 or something similar.
![image](https://user-images.githubusercontent.com/1305249/121298716-ad21f480-c937-11eb-98ec-17bddb27842b.png)

put http 400 and 404 responses in 6438a3288

**Comment by lusum** [comment]
Testing done

First: The images content type sometimes is sent as html text

404 is the wrong answer, it crashes ultrasonic, the correct one, i have found testing 4.4 is:

in 4.4 we have { "subsonic-response": { "status": "failed", "version": "1.13.0", "error": { "code": 70, "message": "Media not found." } } }

Maybe the app was requesting json and ampache give xml? The answer is correct, but the format is wrong?



Fifth:

empty starred list

correct answer:

{
    "subsonic-response": {
        "status": "ok",
        "version": "1.13.0",
        "albumList": {}
    }
}

wrong  develop answer:

{
    "subsonic-response": {
        "status": "failed",
        "version": "1.13.0",
        "error": {
            "code": 70,
            "message": "The requested data was not found: starred"
        }
    }

New bug:

Offset not work in 4.4 and starred, as not worked in 5.0-develop

**Comment by lachlan-00** [comment]
* reverted image, the format works for json
* the empty albums will return an empty list instead of error be709f3d2

for the offset issue which calls are these? there were a few i added and seems to all be working from testing

**Comment by lachlan-00** [comment]
the images are having an issue with xml returning html in the response
![image](https://user-images.githubusercontent.com/1305249/121474535-8d5a0180-ca07-11eb-83a0-3d0841118074.png)

**Comment by lachlan-00** [comment]
yay! art error fixed it's like it doesn't have a format set so i'm putting the header in before the error.
![image](https://user-images.githubusercontent.com/1305249/121477108-c5167880-ca0a-11eb-8a00-d95af10c0058.png)

this was a slippery one to get

**Comment by lusum** [comment]
Ok, now develop version works like a charm. Ultrasonic has no crashes or wrong results.

>for the offset issue which calls are these? there were a few i added and seems to all be working from testing

Version 4.4.3

>http://demo.ampache.dev/rest/getAlbumList.view?type=starred&size=20&offset=0&u=demo&c=Ultrasonic&f=json&v=1.13.0&p=demodemo

If you change the offset to 1 or 10 or whatever number, you have always the same results. 

eg: 

>http://demo.ampache.dev/rest/getAlbumList.view?type=starred&size=20&offset=10&u=demo&c=Ultrasonic&f=json&v=1.13.0&p=demodemo

**Comment by lachlan-00** [comment]
found that highest was giving different orders because it wasn't ordered well enough.
set in aa5d91b1c

I found that the disk ratings/flags were being counted so i've added distinct counts for the user instead of the objects in 34cc9b007

I think we're pretty close now!

**Comment by lusum** [comment]
Another bug, different cell phone and same ultrasonic version/server version


Version 4.4

>GET /ampache/rest/getMusicFolders.view?u=ampache&c=Ultrasonic&f=json&v=1.13.0&p=enc:616D7061636865 HTTP/1.1
>Host:
>Connection: Keep-Alive

> Accept-Encoding: gzip
> User-Agent: okhttp/3.12.13
> 
> HTTP/1.1 200 OK
> Date: Wed, 30 Jun 2021 12:00:54 GMT
> Server: Apache/2.4.41 (Ubuntu)
> Access-Control-Allow-Origin: *
> Content-Length: 278
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json; charset=UTF-8
> 
> {
>     "subsonic-response": {
>         "status": "ok",
>         "version": "1.13.0",
>         "musicFolders": {
>             "musicFolder": [
>                 {
>                     "id": "17",
>                     "name": "-..."
>                 }
>             ]
>         }
>     }
> }
> 


Version 5-devel

> GET /ampache-dev/rest/getMusicFolders.view?u=ampache&c=Ultrasonic&f=json&v=1.13.0&p=enc:616D7061636865 HTTP/1.1
> Host: 
> Connection: Keep-Alive
> Accept-Encoding: gzip
> User-Agent: okhttp/3.12.13
> 
> HTTP/1.1 200 OK
> Date: Wed, 30 Jun 2021 11:56:30 GMT
> Server: Apache/2.4.41 (Ubuntu)
> Access-Control-Allow-Origin: *
> Content-Length: 475
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json; charset=UTF-8
> 
> {
>     "subsonic-response": {
>         "status": "failed",
>         "version": "1.13.0",
>         "error": {
>             "code": 10,
>             "message": "Required parameter is missing."
>         }
>     }
> }{
>     "subsonic-response": {
>         "status": "ok",
>         "version": "1.13.0",
>         "musicFolders": {
>             "musicFolder": [
>                 {
>                     "id": "11",
>                     "name": "..."
>                 }
>             ]
>         }
>     }
> }

Same request, different answers, the 5.0-develop seems wrong cause we have two  subsonic-response

**Comment by lachlan-00** [comment]
fixed that with 365718bd7 the username isn't a parameter of this call, just u

**Comment by lusum** [comment]
the last remaining bug is in 4.4.3 (obsolete )  but not in 5.0.0, so i close the issue
