### ISSUE TITLE
Using Ampache demo server in Ultrasonic?

### ISSUE THREAD

**Issue by tzugen** [ampache/ampache#2938]
Hi!

I am one of the developers of Ultrasonic ( https://github.com/ultrasonic/ultrasonic )
an Android client for Subsonic compatible servers.

Would it be ok for you if I add the demo server as a preconfigured server into our app,
so that new users have some content to check out the app, even if they don't have a server yet?

**Comment by lachlan-00** [comment]
sure, i'll make you a ultrasonic_demo user account for both demo and develop servers

**Comment by lachlan-00** [comment]
@tzugen i'm not sure if you can keep that demo pass encrypted in the source (i don't care, but you might as the security level will just be user level) if you email me lachlan [at] ampache [dot] dev i'll send you the account details

**Comment by lachlan-00** [comment]
Account sent. Passwords will not change unless requested by an ultrasonic team member.
