### ISSUE TITLE
Switching from branch master to develop causes 403 forbidden, switching back to master works properly.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2940]
### Describe the bug
I was interested in trying the new feature pushed to develop: https://github.com/ampache/ampache/pull/2911 which closes https://github.com/ampache/ampache/issues/2797

So I decided to switch from master to develop to try it out but got a 403 forbidden message from nginx.

### To reproduce

```
cd /var/www/ampache
git pull
git checkout develop
git pull
```
And now try hitting your ampache index, 403 forbidden, if I switch back to master then it goes back to working:

```
cd /var/www/ampache
git checkout master
```

### Expected behavior

I did not expect the 403 error, I thought it would just work.

### Screenshots

![2021-06-09_13-34](https://user-images.githubusercontent.com/106644/121425667-8491fe80-c927-11eb-9155-773f1c79ae86.png)

## Environment

* Ampache version: git master branch:   "Ampache 4.4.3-release"
* Web server + version: nginx latest
* Server operating system: Ubuntu 20.04.2
* Client operating system: Ubuntu 20.04.4 (Firefox latest)

### Client type

* Web

## Settings

`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+" | grep -v "host" | grep -v "secret" | cut -c 2-`

```
++ /var/www/ampache/config/ampache.cfg.php      2021-06-09 20:16:24.206648453 +0000
config_version = 46
config_version = 49
http_port = "443"
web_path = ""
database_port = ""
database_name = "ampache"
database_username = "www-data"
database_password = ""
; Usually "utf8" or "utf8mb4". If you set "utf8mb4" as your charset
; Ampache will change the storage engine on all tables to InnoDB
; to support the extra character bytes needed in table KEYs
; DEFAULT: "utf8"
database_charset = "utf8mb4"
; DEFAULT: "utf8_unicode_ci"
database_collation = "utf8mb4_unicode_ci"
session_length = "3600"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
; This determines if we write the changes to files (as id3 tags) when modifying metadata, or only keep them in Ampache (the default).
; DEFAULT: "false"
;write_id3 = "true"

; This determines if we write the changes to files (as id3 tags) when modifying album art, or only keep them in Ampache (the default)
; as id3 metadata when updated.
; DEFAULT: "false"
;write_id3_art = "true"

metadata_order = "getID3,filename"
; This setting takes a regex pattern.
additional_genre_delimiters = "[/]{2}|[/|\\|\|,|;]"
licensing = "false"
simple_user_mode = "true"
artist_art_preferred_filename = "artist.jpg"
album_art_min_width = "190"
album_art_min_height = "190"
art_order = "db,folder"
wanted = "false"
channel = "false"
live_stream = "false"
podcast = "true"
;subsonic_stream_scrobble = "true"
debug = "true"
debug_level = "5"
log_filename = "%name.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
transcode_mp3 = "allowed"
```

## Logs

no new lines appear in the ampache.log while hitting the home page.

nginx error log shows this, not yet sure what it means: 

`2021/06/09 20:38:02 [notice] 3355#3355: using inherited sockets from "7;8;"`

nginx-ampache.log shows this when I hit the homepage:

```
2021/06/09 20:44:56 [error] 231#231: *30 FastCGI sent in stderr: "Unable to open primary script: /var/www/ampache/index.php (No such file or directory)" while reading response header from upstream, client: 10.7.0.1, server: ampache.example.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "ampache.example.com"
10.7.0.1 - - [09/Jun/2021:20:44:56 +0000] "GET /index.php HTTP/1.1" 404 56 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

At first glance I would think its a webserver issue with nginx, however switching back to master the problem goes away so I am not really sure, will have to investigate farther.

**Comment by mitchray** [comment]
If you're coming from v4 you need to [update the web server document root](https://github.com/ampache/ampache/wiki/Ampache-Next-Changes#you-will-need-to-update-the-web-server-document-root)

**Comment by lachlan-00** [comment]
there is an index.html that points to the wiki but i might add in a php one as well for these cases

**Comment by lachlan-00** [comment]
k, the index.php is back (even though it's just a html file) this should help for anyone with the same index setup

**Comment by xekon** [comment]
Sweet, got the switch to 5.0 done today :)
