### ISSUE TITLE
[Feature Request]: Sort smart playlist rules alphabetically

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2946]
## Describe what you don't like about Ampache, or what it is missing

This is just a little nitpick but I think it would be better if the rules for creating a smart playlist would be alphabetically sorted, which would make them easier to find. And I assume a little more polish can never do wrong :)

## Describe how you would like the feature to work**
Alphabetically sort this list.
![image](https://user-images.githubusercontent.com/21057514/122044236-90286e00-cddc-11eb-9674-0f172130ddbd.png)

**Comment by lachlan-00** [comment]
lol, you've opened a good can or worms @sandersantema 

@Psy-Virus @usox @wagnered @AshotN @mitchray @kuzi-moto time for a point of contention!

I'm going to start locking in on 5 and this is probably an important distinction to make. I've always tried to sort search rules by importance based on the object type and the things that would be most common.

Would an alpha sorted list make more sense? As someone who wrote the order of the lists it's not really something i should decide.

There are also probably other areas where this would need to happen as well.

**Comment by kuzi-moto** [comment]
Hmm, I'm partial to alpha sort since otherwise the sort order seems to be a bit subjective.

**Comment by mitchray** [comment]
I think there is value in keeping similar things together, like all the rating items. So perhaps [optgroups](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) would help to make sense of the order

Its getting late here so I'll continue that train of thought tomorrow

**Comment by kuzi-moto** [comment]
Maybe we can include a config option? Allow users the option of sorting alpha, or by their importance.

**Comment by sandersantema** [comment]
I assume the purpose of any kind of sorting of a dropdown list of options is to enable the user to find an option quicker. In order for the method of sorting to be effective the user should therefore be familiar with this particular method of sorting. 

We can assume a user to be familiar with a method of sorting or in general a UI element based on:
1. Exposure: the user has seen the element before, for instance the way we all recognize buttons, textboxes etc.
2. Subjectivity: an element is subjective such as alphabetic sorting itself, there's no doubt about it.

Sorting on importance, object type or categories are all not subjective and in this case I think we can assume the user has no familiarity with them either. Although users might have seen a dropdown list for smart-playlist criteria before I think we can safely assume this ordering won't be the same as it is in Ampache. 

Obviously the user could gain familiarity with these methods of sorting after using Ampache for a while but before the user gains familiarity this defeats the purpose of sorting in the first place: enabling the user to find items in a list quicker. This assuming the user even gets familiar with a list of items, which I think might be far fetched for something like creating a smart playlist which most users don't do that often.

Some concrete examples of problems with the sorting methods:
-  importance: in my case the most important items are `Genre` and `Recently Added` both of which are pretty low down the list, I assume other users would have similar differences in importance.
- object type/ categories: it is often ambiguous to what type or category an item should belong, for instance the `MusicBrainz ID (Album)` item could be grouped with other album items or with other MusicBrainz items.

Although the other sorting methods might be nicer alphabetic sorting is the only method which doesn't suffer of the above. 

Another advantage of alphabetic list sorting is that it takes less time in development, no need to think about how a list of items should be sorted.

**Comment by usox** [comment]
From my POV, it's all about the users expectations. I'd expect a dropdown to be sorted alphabetically, so I could actually search within the dropdown by typing the first letter of the search term and see all the results grouped at once. ATM, the list jumps up and down (e.g. search for `my ...` by typing `m`).

Maybe in future, the GUI could have a more `wizard`-like approach, so the user could be provided with extra info for every item.

> Maybe we can include a config option? Allow users the option of sorting alpha, or by their importance.

I would agree if this issue would affect many users and make it difficult to use the software, but this looks like a very special issue for a small amount of users to me. IMO we should not add config options for every aspect of the UI just to please everyones taste.

**Comment by wagnered** [comment]
I don't usually participate in issues like this one, as it is highly subjective and, having grown up in the "Sixties" I just wanna hear music.

On this, though, I fully agree with @usox.  I have been deciding how to express myself when I noticed his comment.  Saved me the trouble ; ' >.

> IMO we should not add config options for every aspect of the UI just to please everyones taste.

The increasing number of options just increases new user confusion as user documentation continues to not exist.  The wiki is not adequate for explaining Ampache's over-all usage.  Although being "old school" I might be. handicapped in this area of comprehension ; ' >

**Comment by mitchray** [comment]
I put together a demo for my grouped category suggestion: https://codepen.io/mitchray/full/WNpLPWE

**Comment by lachlan-00** [comment]
> I put together a demo for my grouped category suggestion: https://codepen.io/mitchray/full/WNpLPWE

that would actually be a good way of grouping things over a straight alpha list.

**Comment by sandersantema** [comment]
> I put together a demo for my grouped category suggestion: https://codepen.io/mitchray/full/WNpLPWE

This does actually seem pretty nice! And now that I think of it has the advantage of also making it possible to find an item which you don't know the exact naming of. I implicitly assumed the user would always know what item they would be searching for in my previous argument but that is obviously quite often not the case. It is however exactly what categories solve. Items divided in categories where both categories and items are alphabetically sorted might be the winner :+1:

**Comment by lachlan-00** [comment]
was looking at this today, to make the optgroup just needs to go into  `public/lib/javascript/search.js` where the rules are created

![image](https://user-images.githubusercontent.com/1305249/130736721-05689284-d5dd-4c01-aac4-bb49d91464e5.png)

haven't looked much further but it's at least fairly simple just have to work out the JS for it and probably extend search class types into groups.

**Comment by lachlan-00** [comment]
probably add a category/header/group value in the type definition here

![image](https://user-images.githubusercontent.com/1305249/130737849-f3a9e29f-5eb7-412a-9e3f-1c0aef6eded3.png)

**Comment by mitchray** [comment]
Closing this as the items are now grouped nicely
