### ISSUE TITLE
[API] .m4a file conversion to .mp3 at download

### ISSUE THREAD

**Issue by BLeeEZ** [ampache/ampache#2948]
## Description
".m4a" song files can be played without problem via the Ampache Web GUI.
The download link in the Web GUI provides a link to the download API: https://<MY-SERVER-URL>/stream.php?action=download&song_id=17178
Via this link the file can be download with correct file ending and correct file size.

In [Amperfy](https://github.com/BLeeEZ/amperfy), I use the url entry of the "songs" API function to stream and download songs. The provided URL via "songs" looks like this: https://<MY-SERVER-URL>/play/index.php?ssid=<MY-SSID>&type=song&oid=17178&uid=2&player=api&name=Example%20-%20Change%20The%20Way%20You%20Kiss%20Me.m4a"

The downloaded/streamed file of this URL is a mp3 file! It has the same name but with .mp3 as file ending. The size is also dramatically smaller as well as the audio quality.
File sizes:
- mp3: 759 KiB
- m4a: 6,4 MiB

## Environment
This behavior occurs on servers running API version 4.4.1 and on the latest developer branch.

**Comment by BLeeEZ** [comment]
I wasn't aware of this feature, thank you for your help.
With disabled transcoding everything works as intended.

**Comment by lachlan-00** [comment]
you can also add a format parameter to the api call to force the original format too
`https:///stream.php?action=download&song_id=1717&format=raw`
