### ISSUE TITLE
"catalog_update.inc -g" throws a uncaught exception for timeout

### ISSUE THREAD

**Issue by VVelox** [ampache/ampache#2950]
### Describe the bug

```
[root@vulpes]0|/home/vulpes/www/vampache>sudo -u vulpes php bin/catalog_update.inc -g

----------------------------------------------------------
Starting Catalog operations...
        - Gathering new media art
----------------------------------------------------------

PHP Fatal error:  Uncaught Requests_Exception: cURL error 28: Operation timed out after 10001 milliseconds with 28519 out of 106267 bytes received in /home/vulpes/www/vampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php:443
Stack trace:
#0 /home/vulpes/www/vampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php(179): Requests_Transport_cURL->process_response('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Array)
#1 /home/vulpes/www/vampache/lib/vendor/rmccue/requests/library/Requests.php(381): Requests_Transport_cURL->request('http://ec1.imag...', Array, NULL, Array)
#2 /home/vulpes/www/vampache/lib/vendor/rmccue/requests/library/Requests.php(233): Requests::request('http://ec1.imag...', Array, NULL, 'GET', Array)
#3 /home/vulpes/www/vampache/lib/class/art.class.php(1444): Requests::get('http://ec1.imag...', Array, Array)
#4 /home/vulpes/www/vampache/lib/class/art.class.php(1242): Art->gather_musicbrainz(5, Array)
#5 /home/vulpes/www/vampache/lib/class/catalog.class.php(1445): Art->gat in /home/vulpes/www/vampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 443
Reading Catalog: 'Music'
- Start searching new media art -
Adam Freeland
Angelspit
Blood Death Ivory
Larva Pupa Tank Coffin
Nurse Grenade
Nurse Grenade
Krankhaus
Criminal Intents / Morning Star
Dope Stars Inc.
Neuromance
Make a Star
Dope Stars Inc.
Gigahearts
Neuromance
Dope Stars Inc.#                                                                                                                                                                              [root@vulpes]255|/home/vulpes/www/vampache>
```

### To reproduce

```
php catalog_update.inc -g
```
### Expected behavior

It fetches the coverart.

## Environment

* Ampache version: 4.3.0
* Web server + version: Apache 2.4.48
* Server operating system: FreeBSD

```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDFlib
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by VVelox** [comment]
Testing and usually it does not happen on the first round of fetching. Usually goes for awhile and then dies from a query timing out. Likely should sleep for a random few seconds and then retry.

**Comment by VVelox** [comment]
Spotify has the same issue.

```
Uncaught SpotifyWebAPI\SpotifyWebAPIException: Gateway timeout. in /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/Request.php:56
Stack trace:
#0 /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/Request.php(270): SpotifyWebAPI\Request->parseBody(Object(stdClass), 504)
#1 /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/Request.php(137): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(86): SpotifyWebAPI\Request->api('GET', '/v1/albums/00b5...', Array, Array)
#3 /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(591): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/albums/00b5...', Array)
#4 /home/vulpes/www/vampache/lib/class/art.class.php(1380): SpotifyWebAPI\SpotifyWebAPI->getAlbum('00b50dy5chR9j2h...')
#5 /home/vulpes/www/vampache/lib/class/art.class.php(1242): Art->gather_spotify(5, Array)
#6  in /home/vulpes/www/vampache/lib/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 56
```

**Comment by wagnered** [comment]
>  Testing and usually it does not happen on the first round of fetching. Usually goes for awhile and then dies from a query timing out. Likely should sleep for a random few seconds and then retry.

What about updating from the web UI?  Same problem?

The only time I've seen that error was when my network was down.

> cURL error 28: Operation timed out after 10001 milliseconds  with 28519 out of 106267 bytes received...

10 seconds is a long time to transfer 106 kb.  From my POV, it looks like a gateway/network type problem.

**Comment by VVelox** [comment]
It works most of the time. The issue is random time outs from the the remote end.

**Comment by VVelox** [comment]
Also definitely not a network issue. This system it is sitting on is live and everything else is working perfectly and smokeping shows it as all good.

All the slow down and time outs are on the what it is pulling from.

Similarly this if you watch the logs with beets, you will see similar at times. When that happens it backs off.

**Comment by VVelox** [comment]
Similarly this should definitely be a caught error, back off and then retried, and then move on to the next one.

**Comment by VVelox** [comment]
But yeah, fetching them works fine from the web.

Just for some reason the CLI is slow and throws random time outs.

**Comment by wagnered** [comment]
Actually, the CLI uses the same classes as the web interface.  Perhaps @usox or @lachlan-00  are familiar with the differences that might cause your problem.

I'm not yet fully convinced that it's not network problems.  A network tool such as Wireshark would let you see the communications details during  the exchange.

> This should definitely be a caught error, back off and then retried, and then move on to the next one.

1.  The php libraries that use `curl` for the transport must have the logic to catch the error.
2.  It's not a 'popular' issue: Yours is the first for either of the above errors.
3.   I'm not sure that a fix would be backported to V4.*

**Comment by VVelox** [comment]
1: Beets does this exact same thing a hell of a lot if you watch it. It is why it has backoff logic built in.

2: Very much not a network issue. Otherwise smokeping would show it as well as any of the any of the other deamons operating on it would show issues. For example TTRSS fetches remote stuff nice and fast. No. Pure and simple it is not a network issue. 

3: Watching the network shows the exact same thing. Occasional random timeouts fetching it. This is throttling happening on the far end.

**Comment by VVelox** [comment]
Also if you don't mind me pointing out you are missing the big difference between web v. CLI like this.

The web interface when you request cover art for album is doing it on a making only a few requests. The CLI is making many requests in a row. This means is by no means uncommon to see the remote start to throttle via some method.

Go point youtube-dl at a large number of items and you will see something similar.

And like I've said repeatedly. Watch beets if you tell it to go and fetch lots of info. You'll see the exact same thing.

**Comment by wagnered** [comment]
> The web interface when you request cover art for album is doing it on a making only a few requests.

If you look at the code for `catalog_update.inc -g` it can be seen that the same classes for `gather art` are if called from the web "show  catalog" page dropdown list item "gather art".

So I'll let @usox and/or @lachlan-00  take it from here.

**Comment by VVelox** [comment]
Ohh. That. Yeah. That will error as well and won't complete.

Though you were talking about telling it to fetch a single item.

**Comment by usox** [comment]
Fyi: The Requests-library (used to download external resources) has been replaced in the current development-version. The new loading mechanism is not very sophisticated but it catches every exception which happens during the data retrieval and creates a log entry.
Maybe this could/should be enhanced in future to retry failed requests or something alike.
