### ISSUE TITLE
Adding 'The' to Album Name in Web UI adds it to name field in DB not to prefix field

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2951]
## Description
Was trying to clean up some album names using the edit function in the UI and noticed if I add 'The' to the name in the edit form it adds it to the actual name in the database and not the prefix field. This can wind up with albums having double 'The' in front of them - as happened to some of mine.

### Describe the bug
Edit album via the UI to add a prefix to the album name. There is no input field in the form for prefix so assume this should be split from the name when processing the update.

### To reproduce

1. Click the cog icon next to an album to edit.
2. Edit the album name in the form and remove 'The' and save.

a. If 'The' was saved as a prefix the album name will not be changed and still display 'The'.
b. If 'The' was part of the name field it will be removed.

1. Click the cog icon next to an album to edit.
2. Edit the album name in the form and add 'The' and save.

a. If 'The' was already saved as a prefix the album name is changed and display 'The The'.

### Expected behavior
Prefixes should be detected and split from the string when editing and saving the album name. Prefixes should be saved in the prefix field.

\* The tricky part to this is detecting when you remove a prefix just be deleting it from the album name in the form.

## Environment

* Ampache version: develop a64d1072eb35fb230e2df9563366ac887438f8ac

**Comment by wagnered** [comment]
@Andrew-McGee  I am aware of the issue and have implemented a fix in the current work I am doing.  It should be merged into develop relatively soon.

Thanks for making the issue public:  It's one that was migrated from the V4.* development. I'm surprised that it was not previously caught.

**Comment by Andrew-McGee** [comment]
Great, thanks for this @wagnered. Are you also looking at the artist names? I get different results when I call album or stats (no prefix returned) than when I call artist (prefix returned). 
Eg. API calls:
$stats_results['album']['artist']['name'] = 'Tiger Lillies'
$artist_results['name'] = 'The Tiger Lillies'

I can put this in another issue if you aren't looking at it.

**Comment by wagnered** [comment]
Please make a separate issue:  I wasn't looking at it and I am not very familiar with the API but there are others who are.

**Comment by mitchray** [comment]
For the API query, v6 has the prefix and basename as separate fields

https://github.com/ampache/ampache/commit/7c45cd41894c95b1f7d6246b2e4b02f98aac5f2b#diff-2bfab3db5cc1baf4c6d3ff6b19901926e3bdf4411ec685dac973e5fcff1c723bR91-R92

**Comment by mitchray** [comment]
OK to close? Reopen if not
