### ISSUE TITLE
Some API calls do not return artist prefix ('The')

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2952]
## Description
When I get the artist name returned from the stats, album or albums API calls there is no prefix ('The') returned.

When I call artist or artists I get prefix ('The') returned.

### Describe the bug

I get different results when I call album or stats (no prefix returned) than when I call artist (prefix returned).
Eg. API calls:

`?action=stats&type=album&filter='tiger':`

`$stats_results['album']['artist']['name'] = 'Tiger Lillies'`

`?action=artists&filter='tiger':`

`$artists_results['artist']['name'] = 'The Tiger Lillies'`

## Environment

* Ampache version:  develop a64d1072eb35fb230e2df9563366ac887438f8ac

**Comment by lachlan-00** [comment]
i'll fix this up tonight.

**Comment by lachlan-00** [comment]
full name on album artist in 8f2503900

**Comment by Andrew-McGee** [comment]
Nice one mate - love your work.

**Comment by lachlan-00** [comment]
always happy to help
