### ISSUE TITLE
[Improvement]: `Cleans Catalogs from orphaned entries` explanation of `--cleanup` in `bin/cli run:updateCatalog` is ambiguous

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2953]
### Describe what you don't like about Ampache, or what it is missing
If a entry in the catalog is missing tags for instance an artist or album they're listed as `Unknown (Orphaned)`. It's not completely clear whether the `--cleanup` option would remove these files.

### Describe how you would like the feature to work**
I suggest a somewhat more explicit explanation such as: 
`Removes entries from Catalogs which don't have corresponding files` 

I think `Removes` is also more explicit than `Clean` but it's also fine to keep using `Clean`.

**Comment by lachlan-00** [comment]
i'm going to do a run through the cli strings next week and clean these up.

it will need to refernce what the action is (e.g Clean will remove missing or unreadable files from the database)

**Comment by lachlan-00** [comment]
reworded the strings in 3d90cd1db

@Psy-Virus i'm starting to close in on change/feature freeze for 5, can you do a sync with transifex? there are a few new DB prefrerences and general changes as well.

**Comment by mitchray** [comment]
Closing as this looks to have been addressed
