### ISSUE TITLE
[Feature Request]: Report files ampache was unable to import from playlist

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2954]
## Describe what you don't like about Ampache, or what it is missing
When importing a playlist i.e. a `m3u` file from disk ampache reports the amount of tracks it succeeded in adding to the playlist in relation to all the tracks listed in the file. It would be nice to see which files ampache failed to import. 

## Describe how you would like the feature to work**
Extend the import message with a list of files which ampache failed to import.

**Comment by lachlan-00** [comment]
589ede6c5 puts in debug for skipped files.

each file is called
`debug_event(self::class, "import_playlist checking: {{$file}}", 5);`

then skipped files are printed
`debug_event(self::class, "import_playlist skipped: {{$file}}", 5);`

**Comment by sandersantema** [comment]
Very nice but wouldn't this be nice to have in the gui too? There's space enough on the page when importing and ampache already reports the amount of files it successfully imported, this doesn't necessarily seem like something you'd want to look into your debug logs for. Just printing a simple list of paths should be enough, or even simpler: a button to copy all failed imports which would be shown after completion.

**Comment by lachlan-00** [comment]
like the update from tags screen?

that could probably work too

**Comment by sandersantema** [comment]
I think this would be the right place:
![image](https://user-images.githubusercontent.com/21057514/123423254-98905e00-d5bf-11eb-9750-6417e074a02b.png)

**Comment by lachlan-00** [comment]
bam!
![image](https://user-images.githubusercontent.com/1305249/128442944-22cbffe5-325c-4864-8981-fb1b1f82d838.png)

**Comment by lachlan-00** [comment]
with 346b3b801 this is now in. on import we'll keep a list of tracks / files then print out the status on completion

![image](https://user-images.githubusercontent.com/1305249/128443480-7897cd46-27ad-42a3-bc69-854fca8dd864.png)

**Comment by sandersantema** [comment]
Looks very good! Is it possible to sort that list by clicking on the `Track`, `File` and `Status` headers? That'd be nice. If a path is very long does it get truncated?

Is it possible to report the same information when using the ampache cli?

**Comment by lachlan-00** [comment]
The list is echoed html so might be a lot harder to sort/edit but I'll check.

I'll add a really long string to check but if it truncated anything that's just CSS to fix.

In cli I can add detail as well. I need to make it a bit more responsive as well instead of printing it all out at the end of each step

**Comment by lachlan-00** [comment]
detail in for cli imports

```
www-data@web:~/music$ bin/cli run:updateCatalog music -i
Reading Catalogue: "music"
Start adding new media
Starting New Media Search
Starting New Media Search on "[ music ]" Catalogue
Found: None
Reading:
0
/mnt/music/wav.m3u
1: Success:	/mnt/music/Giuseppe Ottaviani/(2020) Slow Emotion 4 [BH9990]/101 - Slow Emotion 4 Extended Mix.wav
2: Success:	/mnt/music/Everything In Colour/(2020) Patreon Only 2020_05_15 [none]/101 - Droner.wav
3: Success:	/mnt/music/Everything In Colour/(2020) Patreon Only 2020_10_19 [none]/101 - Leaving With You.wav
3: Failure:	/mnt/music/INTENTIONAL MISTAKE/101 - Leaving With You.wav
4: Success:	/mnt/music/Switchkicker/(2020) Patreon Only 2020_12_15 [none]/101 - Burn (Instrumental Master).wav
5: Success:	/mnt/music/Switchkicker/(2021) Patreon Only 2021_07_06 [none]/1-01 - New Machine (Instrumental 2021).wav
Total Time: [00:09] Total Media: [0] Media Per Second: [N/A]

```

**Comment by lachlan-00** [comment]
oh, forgot to take out the track number from fails. removing that now

**Comment by mitchray** [comment]
Closing as this looks to have been resolved
