### ISSUE TITLE
[Feature Request]: Don't prepend filetype to name of imported playlist

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2955]
## Describe what you don't like about Ampache, or what it is missing

When importing a playlist ampache prepends the filetype to the name of the playlist i.e. when importing `250.m3u` the name of the playlist becomes `m3u - 250`. This seems unnecessary given that I don't think a user would ever care about the filetype of the imported playlist after import and a user would never want two playlist with the same name only differing in original filetype.

## Describe how you would like the feature to work
Don't prepend the filetype of the imported playlist to the name of the playlist.

**Comment by lachlan-00** [comment]
yeah it seems silly when it's the name of the list that matters. set in 4a8c019a5
