### ISSUE TITLE
noted bugs in 5.0  

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#2959]
Was looking the 5.0 dev section I used before but been outa town for awhile.. I believe the version I'm running is 
5.08  prerelease 8 for sure..

Noted when browsing by artist 2 things.

The alphabet will not shift selection of view to current selected letter..... The other (Viewing artists) which I thought strange is if your toggle grid view  to ON the result is just the top 1/4 of the image shows..   IF you fixed it already super.. If not sorry for adding to your todo list..

Also I do fresh installs as well under apache with php 7.4 and noted I always have to edit the config file and set  use_auth = "true" in the newly generated config file so I can gain access to configure the server settings

JC

**Comment by mitchray** [comment]
The two artist issues don't appear to be affecting the latest develop version in my testing so that's good

**Comment by tomchiverton** [comment]
All fixed by the time I installed 5.1, can be closed ?

**Comment by jamesc2151** [comment]
yepper closer up seems to be on my install
