### ISSUE TITLE
Smart Playlist Tags/Genres not working anymore.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2961]
### Describe the bug
I just noticed my smart playlist that previously worked is no longer working, I have a smart playlist I rated 3+ and Tags is Classic Rock, this smart playlist was working at one point, but now it just shows all music that I have rated 3+ regardless of genre.

The screenshots below shows what I mean, its not just that one song, its all songs, as I scroll the list I am seeing all the songs I rated 3+ regardless of genre. (Techno, Classic Rock, Metal, etc.....)

### Screenshots

![2021-06-25_22-29](https://user-images.githubusercontent.com/106644/123503015-19be1400-d605-11eb-849c-f4696c775303.png)

![2021-06-25_22-32](https://user-images.githubusercontent.com/106644/123503043-3d815a00-d605-11eb-8905-1b7191db6424.png)

## Environment

* Ampache version: git master branch:   "Ampache 4.4.3-release"
* Web server + version: nginx latest
* Server operating system: Ubuntu 20.04.2
* Client operating system: Ubuntu 20.04.4 (Firefox latest)

### Client type

* Web

## Settings

`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+" | grep -v "host" | grep -v "secret" | cut -c 2-`

```
++ /var/www/ampache/config/ampache.cfg.php      2021-06-09 20:16:24.206648453 +0000
config_version = 46
config_version = 49
http_port = "443"
web_path = ""
database_port = ""
database_name = "ampache"
database_username = "www-data"
database_password = ""
; Usually "utf8" or "utf8mb4". If you set "utf8mb4" as your charset
; Ampache will change the storage engine on all tables to InnoDB
; to support the extra character bytes needed in table KEYs
; DEFAULT: "utf8"
database_charset = "utf8mb4"
; DEFAULT: "utf8_unicode_ci"
database_collation = "utf8mb4_unicode_ci"
session_length = "3600"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
; This determines if we write the changes to files (as id3 tags) when modifying metadata, or only keep them in Ampache (the default).
; DEFAULT: "false"
;write_id3 = "true"

; This determines if we write the changes to files (as id3 tags) when modifying album art, or only keep them in Ampache (the default)
; as id3 metadata when updated.
; DEFAULT: "false"
;write_id3_art = "true"

metadata_order = "getID3,filename"
; This setting takes a regex pattern.
additional_genre_delimiters = "[/]{2}|[/|\\|\|,|;]"
licensing = "false"
simple_user_mode = "true"
artist_art_preferred_filename = "artist.jpg"
album_art_min_width = "190"
album_art_min_height = "190"
art_order = "db,folder"
wanted = "false"
channel = "false"
live_stream = "false"
podcast = "true"
;subsonic_stream_scrobble = "true"
debug = "true"
debug_level = "5"
log_filename = "%name.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
transcode_mp3 = "allowed"
```

**Comment by xekon** [comment]
Update on this, if you change it from:

Tags    is                 Classic Rock
to
Tags    contains      Classic Rock

Then it works properly, the thing is, this used to work, and that is exactly the spelling of the tag.

**Comment by lachlan-00** [comment]
simplified with 610b4c423 seems to be okay for all searches except not sounds like which i don't think exists?

**Comment by xekon** [comment]
I just tested both "is" and "contains" and with your latest commit, both are now working. "sounds like" is not something I have ever used, interesting way to filter for sure, lol.
