### ISSUE TITLE
Similar Artists Issues

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2962]
When viewing the Similar Artists tab on any Artist page (artists.php?action=show&artist=), the page heading is duplicated and the columns of the results table are misaligned due to a missing column header which I think is for the  '# Played' column (the one after the 'Time' column):

![image](https://user-images.githubusercontent.com/3216809/123539832-8c2d1200-d733-11eb-8ebd-c467a42dd68b.png)

**Comment by lachlan-00** [comment]
actually just a plain old dupe line 5744547b9

**Comment by rsinfotech** [comment]
Great stuff, duplicated page heading now removed but issue with missing #played column header causing column title alignment issues is still present...

**Comment by rsinfotech** [comment]
Just noticed, this has been fixed in 392adde

Much appreciated.
