### ISSUE TITLE
Modal pop-ups missing artists on most pages

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2963]
The little modal pop-ups that appear when hovering over an album art image should show the artist in square brackets and the album title on all pages - [Artist Name] Album Title

This is working correctly on the index.php page but most other pages show empty square brackets for Artist and just the Album Title:

![ss01](https://user-images.githubusercontent.com/3216809/123540577-a1a43b00-d737-11eb-8b4c-5e2d95290344.png)

This seems to be happening on any of the browse.php pages, stats.php pages and mashup.php pages when hovering over album art images.

**Comment by lachlan-00** [comment]
this would proabably be albums specifically. will check tomorrow but i think it's because album doesn't have the same attributes compared to other items.

**Comment by lachlan-00** [comment]
a66c67174 adds that, let me know if there are other pages

**Comment by rsinfotech** [comment]
Perfect! All pages now show the Artist and Album names in the popup boxes.

Great work @lachlan-00, much appreciated.

**Comment by rsinfotech** [comment]
There is just one more place that I've found this to be happening, it's when you view an actual Album page (albums.php?action=show&album=)

It occurs when hovering over the main Album art image at the top right:
![Screenshot from 2021-06-29 13-01-03](https://user-images.githubusercontent.com/3216809/123794907-4b6ffd00-d8db-11eb-88a0-f00e6a08c1aa.png)

And on the title of the enlarged prettyPhoto popup if you click on the Album art:
![Screenshot from 2021-06-29 13-04-15](https://user-images.githubusercontent.com/3216809/123795071-82461300-d8db-11eb-925c-0fd5447a29be.png)

But I think that's everything...

**Comment by lachlan-00** [comment]
album pages and also random albums fixed with e4f942d4d

**Comment by rsinfotech** [comment]
Brilliant, this also fixes all of the search links to google, last.fm, musicbrainz etc. as these were all missing out the artist too.
