### ISSUE TITLE
'Update from Tags' giving SQL Error Messages

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2964]
When using the 'Update from Tags' command for an album in the web client, the following SQL error messages are reported in the ampache logs:

```
(Ampache\Module\System\Dba) -> Error_query SQL: UPDATE `object_count` SET `object_id` = ? WHERE `object_type` = ? AND `object_id` = ? AND `date` IN (SELECT `date` FROM `object_count` WHERE `object_type` = 'song' AND `object_id` IN (SELECT `id` FROM `song` WHERE `song`.`album` = ?));
(Ampache\Module\System\Dba) -> Error_query MSG: ["HY000",1093,"You can't specify target table 'object_count' for update in FROM clause"]
```
The tag update seems to be working correctly and the web client reports that all tags have been updated.

**Comment by lachlan-00** [comment]
tags are updated but this is for the #played count will need to investigate why mysql doesn't like that

**Comment by lachlan-00** [comment]
bb4327411 puts in a better migration check by looking for dates first then updating.

You're going to have incorrect play count data though so i'll look at fixing that next

**Comment by lachlan-00** [comment]
i'm not going to be able to fix this until next week but just so i can remember this is my query for finding missing id's.

Luckily song never really gets deleted so we can repair based on that

```
# missing artist & album (I'm missing 26)
SELECT * FROM object_count WHERE object_type = 'song' AND count_type = 'stream' AND `date` NOT IN (select date from object_count WHERE count_type = 'stream' and (object_type = 'album' OR object_type = 'artist'))
ORDER BY date DESC;

# missing artist (I'm missing 87)
SELECT * FROM object_count WHERE object_type = 'song'  AND count_type = 'stream' AND `date` NOT IN (select date from object_count WHERE count_type = 'stream' and object_type = 'artist')
ORDER BY date DESC;

# missing album (I'm missing 18307!!!!!!!)
SELECT * FROM object_count WHERE  count_type = 'stream' AND `date` NOT IN (select date from object_count WHERE count_type = 'stream' and object_type = 'album')
ORDER BY date DESC;
```

**Comment by lachlan-00** [comment]
actually i just fixed it with ac35e6db there's a smallish limit (100) so if you have lots of missing rows like i did take the limit out.
![image](https://user-images.githubusercontent.com/1305249/124096726-3394a680-da9e-11eb-8e95-e4bd418a74f5.png)

**Comment by lachlan-00** [comment]
should cover migrating and repairing any issues from these errors now.

**Comment by rsinfotech** [comment]
Brilliant work as always @lachlan-00, the SQL errors are now gone when using the update from tags link in the web client.

I get lots of results when running those queries manually in mysql:

- missing artist & album (I'm missing 2487)
- missing artist (I'm missing 2609)
- missing album (I'm missing 28499!!!!!!!)

I take it that if I temporarily remove the limit from Catalog.php and run an update, these missing artists and album counts will be reduced?

**Comment by lachlan-00** [comment]
They will all go. (It took me 2 goes through) but I think for you take that limit off and run.

It wasn't long to complete, just do updatecatalog -c

**Comment by lachlan-00** [comment]
The reason I put the limit on is 20k results is very large. It not something that would happen often after we have this fix so maybe I put it in the Cron without a limit too?

**Comment by rsinfotech** [comment]
Ok, after removing the limit and running an updatecatalog - c, the first two queries return zero results but the last one for missing album now returns a much reduced 910 results. I ran the clean a couple more times just to make sure.

This has fixed my original issue so should I now close this?

**Comment by lachlan-00** [comment]
it has,

the errors you get were fixed by changing the query and the result of that screwing up was fixed but those limited queries. i'm running a mysql locally on my desktop to test out for these things now too.
