### ISSUE TITLE
Album Favorites Not Showing Up

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#2966]
### Describe the bug
Noticed yesterday that the favorite albums are not showing up both in my front end and in the web GUI.

Favorite albums are still flagged - you can check the individual album. They just no longer show up in results from the stats API call.

### To reproduce

Go to the web GUI. Click on favorites menu item. Results for albums will be 0.

## Environment

* Ampache version: develop a66c67174d5dc01cb1e2c34dd33a2a15262cc0e3

**Comment by mitchray** [comment]
Mine are still working, are there any pending database updates in the regular Ampache interface?

```
/server/json.server.php?action=stats&type=artist&filter=flagged
/server/json.server.php?action=stats&type=album&filter=flagged
/server/json.server.php?action=stats&type=song&filter=flagged
```

**Comment by lachlan-00** [comment]
there's not a cli/api way to do this, i'll update system_update to check the database too

**Comment by lachlan-00** [comment]
4ff84da2e checks the database now too

**Comment by Andrew-McGee** [comment]
I'm getting these msg's in the ampache log:


2021-06-30T23:11:31+10:00 [andy] (Ampache\Module\System\Dba) -> Error_query SQL: SELECT MIN(`user_flag`.`object_id`) as `id`, COUNT(DISTINCT(`user_flag`.`user`)) AS `count`, 'album' as `type`, MAX(`user_flag`.`user`) as `user` FROM `user_flag` LEFT JOIN `album` on `user_flag`.`object_id` = `album`.`id` WHERE `user_flag`.`object_type` = 'album' AND `user_flag`.`user` = '2' GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`release_status`, `album`.`mbid`, `album`.`year`, `album`.`original_year` ORDER BY `count` DESC, `user_flag`.`date` DESC LIMIT 24
2021-06-30T23:11:31+10:00 [andy] (Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1055,"Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampdb.user_flag.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]

**Comment by Andrew-McGee** [comment]
> Mine are still working, are there any pending database updates in the regular Ampache interface?
> 

No, I'm up to date (build 009 I think was the last one).

**Comment by mitchray** [comment]
Have you updated MySQL recently? If so then the error ```this is incompatible with sql_mode=only_full_group_by"]``` suggests it is being more strict on the SQL queries whereas it used to let them slide (which would mean the queries themselves need adjusting)

https://www.percona.com/blog/2019/05/13/solve-query-failures-regarding-only_full_group_by-sql-mode/

But if thats not it then I'm not sure

**Comment by lachlan-00** [comment]
mysql does full grouping slightly differently than mariadb which is annoying AF, can fix that error

**Comment by lachlan-00** [comment]
installing mysql8 locally to run through things now

**Comment by lachlan-00** [comment]
ee07a0fc9 fixes this. Mysql and mariadb differ in one way which is annoying.

in mariadb you can treat `SELECT table.column AS column` as either the full column name or the AS name.
in mysql you can only group by the AS name which is something that really catches me up logically some times.

**Comment by Andrew-McGee** [comment]
Thanks @lachlan-00. I had no idea the SQL syntax differed like this. I was always under the impression that mariadb was 'drop in' compatible with mySQL but it shows that they are slowly diverging over time.

It's always been something on my todo list to switch over to mariadb on my server.  

I will test this update and report back.

**Comment by Andrew-McGee** [comment]
This issue is solved. Thank you team!

**Comment by lachlan-00** [comment]
i've got another mysql box on again so i can keep an eye on them, there was only one other possible which i've updated as well.
