### ISSUE TITLE
Ampache develop Information "Top Rated" , Rating column empty

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2967]
## Description

This might just be a works in progress item, I do not know, but I noticed the Rating column was empty, and I am assuming it should be showing the average rating for all users?

### Screenshots

![2021-06-29_23-14](https://user-images.githubusercontent.com/106644/123911434-a54ee200-d930-11eb-860e-08a0f917fdae.png)

## Environment

* Ampache version: git   "Ampache develop"
* Web server + version: nginx latest
* Server operating system: Ubuntu 20.04.2
* Client operating system: Ubuntu 20.04.4 (Firefox latest)

### Client type

* Web

## Settings

`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+" | grep -v "host" | grep -v "secret" | cut -c 2-`

```
++ /var/www/ampache/config/ampache.cfg.php      2021-06-30 05:35:57.900991750 +0000
http_port = "443"
web_path = ""
database_port = ""
database_name = "ampache"
database_username = "www-data"
database_password = ""
database_charset = "utf8mb4"
database_collation = "utf8mb4_unicode_ci"
session_length = "3600"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
metadata_order = "getID3,filename"
additional_genre_delimiters = "[/]{2}|[/|\|\|,|;]"
licensing = "false"
simple_user_mode = "true"
artist_art_preferred_filename = "artist.jpg"
album_art_min_width = "190"
album_art_min_height = "190"
art_order = "db,folder"
wanted = "false"
channel = "false"
live_stream = "false"
podcast = "true"
debug = "true"
debug_level = "5"
log_filename = "%name.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
transcode_mp3 = "allowed"
```

**Comment by rsinfotech** [comment]
I think this is related to a missing column title header for '#played' throwing the alignment of subsequent column headers as mentioned in #2962

Your song ratings are there, but under the column heading 'Action' instead of 'Rating' which I think should be the column for '#Played'?

**Comment by lachlan-00** [comment]
should be these
![image](https://user-images.githubusercontent.com/1305249/124040968-5183ec00-da49-11eb-8979-1eb02e1ef5ea.png)


It's also odd that the counts are missing can you inspect the empty column and get it's name? it might be something hidden that's hidden in the table header but not in the rows
![image](https://user-images.githubusercontent.com/1305249/124041256-dff86d80-da49-11eb-9ad8-e5264bbbf3d5.png)

**Comment by xekon** [comment]
I rolled my container back the day I posted this issue (bgack to 4.4.3) I then switched and updated to 5.0 again, and now I can no longer reproduce this issue.

**Comment by lachlan-00** [comment]
> I rolled my container back the day I posted this issue (back to 4.4.3) I then switched and updated to 5.0 again, and now I can no longer reproduce this issue.

i did fix up the template logic for songs a bit on friday so that's probably it
