### ISSUE TITLE
DACP Protocol support

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#297]
Now that DAAP protocol is implemented, we should also support DACP protocol with pairing. This would give the ability to browse Ampache transparently from an Apple TV.

Protocol documentation:
http://dacp.jsharkey.org/

**Comment by rubenhak** [comment]
I'm very interested in this enhancement. Is this already supported?

**Comment by Afterster** [comment]
Missing time for such new features. Architecture review (eg. on streams) is also recommended before starting to do this.

**Comment by mitchray** [comment]
Going to close due to time since last discussion and low interest, maybe someone who is interested in this can help implement
