### ISSUE TITLE
translation sync with transifex process

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#2970]
@Psy-Virus is this the process? just want to document it in TRANSLATIONS.md and on the wiki

generate the translations and update the pot and the txt
```
cd locale/base/
bash ./locale/base/gather-messages.sh -gu
```
![image](https://user-images.githubusercontent.com/1305249/125233444-e62bfb00-e321-11eb-91dd-0f577e861cac.png)

Then there are 2(?) choices
* do we merge to the github repo and let transifex read
* or do you `tx push` to transifex instead

then later you do a tx pull and merge into develop

**Comment by lachlan-00** [comment]
Okay @Psy-Virus I'm done with code for 5.0.0 now. I'll give translators until September to translate the changes.

I think that's enough time for use to give to people.

Can you confirm this process and/or do a sync so we can kick it off?

**Comment by lachlan-00** [comment]
@Afterster do you have admin on transited if Manuel isn't available?

**Comment by Psy-Virus** [comment]
> generate the translations and update the pot and the txt
> 
> ```
> cd locale/base/
> bash ./locale/base/gather-messages.sh -gu
> ```
> 
> ![image](https://user-images.githubusercontent.com/1305249/125233444-e62bfb00-e321-11eb-91dd-0f577e861cac.png)
> 
> Then there are 2(?) choices
> 
>     * do we merge to the github repo and let transifex read
> 
>     * or do you `tx push` to transifex instead
> 
> 
> then later you do a tx pull and merge into develop


Right now, Ampache has to be fully set up to update all strings as we have to pull strings from the database too (that's what translatable-database-strings.txt is for), except we parse all the sql files for strings to translate.
But yes, basically it's:
+ fully setup / update Ampache
+ tx pull -f
+ ./gather-messages.sh -au 
    + so it's parsing the php files and database, updates the translation files, cleans everything up and merges the database strings to the messages.pot
+ upload the changed files to github and let Transifex download the messages.pot
+ now translators can translate the changes and the process repeats

I'll update translations now. Sorry for being quiet for so long.

**Comment by lachlan-00** [comment]
i'll flesh that out a bit further in the docs

Just getting into release mode, i want to do another sync before september (Aug 30/31 )and then release on the 1st of Sep

**Comment by lachlan-00** [comment]
Oh i've also been working on a test template for ampache which would help keep these things consistent by working on the same site database.

At the very least having an sql file to use that is the same and maintained would make it easier to check for issues

**Comment by lachlan-00** [comment]
here's my doc server (wihtout media) but it will be good to run the same database for these situations

**Comment by lachlan-00** [comment]
https://github.com/lachlan-00/ampache-test

**Comment by Afterster** [comment]
@lachlan-00 I just added you as an additional maintainer on transifex.

**Comment by lachlan-00** [comment]
Okay that's all good, en_AU won't be supported for 5.0.0 (thanks for adding).

@Psy-Virus  if you could do one more sync this weekend before september we'll be ready to rock

**Comment by Psy-Virus** [comment]
@lachlan-00, will be done later this Monday 👍

**Comment by lachlan-00** [comment]
great!, i've done the branches and things today so you've got plenty of time
