### ISSUE TITLE
New dashboard feature podcast issue

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#2972]
Hi devs, absolutely love the new dashboard feature in develop, I know the mashup pages are not liked by all but I find they give a really useful overview of the music in your collection.

The new podcast episode mashup page is particularly brilliant, before this I had no easy way to find the latest downloads without going through each series one by one. So a big thumbs up from me here. :+1:

Anyway, I found just a little tiny issue with the links. The text links on the podcast mashup page work perfectly, clicking on the Title takes you to the podcast episode, clicking on the Name of the podcast series takes you to the series as expected.

But the link used when clicking on the podcast image is ``#albums.php?action=show&podcast=19`` which results in a "You have requested an Album that does not exist." message in the browser and an ``(Ampache\Module\Application\Album\ShowAction) -> Requested an album that does not exist`` line in the error log.

I think this link just needs updating to ``#podcast.php?action=show&podcast=19`` for everything to be just perfect?

**Comment by lachlan-00** [comment]
good find, set with dd927a218

**Comment by lachlan-00** [comment]
i spent a while trying to work it all out but i think they're important pages so they deserve their own space too
