### ISSUE TITLE
Escaping 

### ISSUE THREAD

**Issue by osiktech** [ampache/ampache#2973]
Hi @lachlan-00,

seems like a mistake happened here.

https://github.com/ampache/ampache/commit/815695851b7c25fef41ab9caa8761b65e4cbf479

shouldn't it be

```
Dba::write("REPLACE INTO `update_info` SET `key`= '" . $table . "', `value`='" . $value . "';");
```

instead of 

```
Dba::write("REPLACE INTO `update_info` SET `key`= '" . $table . "', `value`=" . $value . ";");
```

in __[src/Repository/Model/Catalog.php](https://github.com/ampache/ampache/blob/develop/src/Repository/Model/Catalog.php#L646)__?

Best

**Comment by lachlan-00** [comment]
For set_count? All the values in update_info are ints but I'll check to make sure.

**Comment by lachlan-00** [comment]
the whole table is int values so i'm enforcing that now with 84da175ff by casting and using parameter arrays to remove the ambiguity
