### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by itrushton** [ampache/ampache#2974]
## Description
Unable to complete install on Windows 10

### Describe the bug

I have followed the windows install instructions twice, once using the latest version of Bitnami WAMP (v8.x) and used both the develop and master branches - both with the same problem.  I have now removed and reinstalled using WAMP v7.4.x.   Everything goes well until running composer.  I fixed the missing intl extension but i still have several problems, and when trying to access the web page, i get the error page "Error You may have reached this page because Ampache was unable to load the required dependencies"

When running the composer from powershell CLI, I get the following errors:

PS C:\Bitnami\wampstack-7.4.21-0\apache2\htdocs> composer install --prefer-source --no-interaction
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - oomphinc/composer-installers-extender is locked to version v1.1.2 and an update of this package was not requested.
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
  Problem 2
    - robloach/component-installer is locked to version 0.2.3 and an update of this package was not requested.
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
  Problem 3
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
  Problem 4
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - happyworm/jplayer 2.9.2 requires robloach/component-installer * -> satisfiable by robloach/component-installer[0.2.3].
    - happyworm/jplayer is locked to version 2.9.2 and an update of this package was not requested.

## Environment

* Ampache version: current master branch (as of 22/7/2021)
* Web server + version: Bitnami WAMP 7.4.21.0
* Server operating system: Windows 10 Professional 
* Client operating system: n/a

**Comment by wagnered** [comment]
Hello @itrushton, Composer is the wrong version for the master branch.

Run `composer self-update --1`  then run `composer update`

Or download [ampache-4.4.3_all.zip](https://github.com/ampache/ampache/releases/download/4.4.3/ampache-4.4.3_all.zip). This file was created especially for Windows users: the dependencies should have already been installed (lib/vendor).

**Comment by itrushton** [comment]
@wagnered thanks for the info.  i tried the first method and it worked, but when i tried to add a catalogue I just got a blank screen.  So i have now installed the zip you kindly provided, which makes it work.  I am assuming i don't need to rerun composer after copying those files to htdocs?  if so, should a perform the composer --rollback and it detailed when i performed thae last step?

**Comment by wagnered** [comment]
> I am assuming i don't need to rerun composer after copying those files to htdocs?

Correct as I very poorly explained: The correct version of composer is run before the zip of the folder structure is created.

**Comment by tomchiverton** [comment]
This can be closed then ?
