### ISSUE TITLE
HTOA files listing together under "Orphaned-Orphaned" album name

### ISSUE THREAD

**Issue by itrushton** [ampache/ampache#2977]
### Describe the bug

I have installed version 4.43-release of Ampache, and have a very large collection of personal FLAC rips to add.  When i have ripped these discs, I have ripped complete with the HTOA files, however when adding the albums to the catalogue, Ampache is seeing these as unidentified and putting them all into an album called "Orphaned - Orphaned".  I cannot find a way to make Ampache ignore these files and stop this ocurring
### To reproduce

Add a catalogue, and specify a folder containing a Flas folder containing an HTOA file (for example 00. Bananarama - (HTOA).flac)
Allow Ampache to process album folder, will display a separate album labelled "orphaned-Orphaned" containing said HTOA file(s)

### Expected behavior
File ignored, or given the option to ignore in settings.  or shown in the album folder?

### Screenshots

![image](https://user-images.githubusercontent.com/9013765/126799995-35e78ada-35f0-4c65-88f7-0c7bf9676bfb.png)

## Environment

* Ampache version: 4.4.3-release
* Web server + version: bitnami 7.4.x
* Server operating system: Windows 10
* Client operating system: Windows 10

**Comment by wagnered** [comment]
Currently, Ampache uses the file extension to determine which sub-library to use.  If you don't intend to create new CDs the files with "(HTOA)" in the filename can be deleted, or the file extention can be changed to something that is not in the config switch `catalog_file_pattern` (config/ampache.cfg.php).

**Comment by lachlan-00** [comment]
Most of the checks expect filenames and we only really do an extension check and don't do a negative/exclusion check
![image](https://user-images.githubusercontent.com/1305249/126935397-18a4f511-f232-4c8b-b809-8dec13a32f20.png)

something like catalog_file_skip_pattern would allow people to set their own skip regex as well

**Comment by lachlan-00** [comment]
I need to fix this before 5 so adding the Milestone

**Comment by lachlan-00** [comment]
Will be fixing this next week. You might have to remove from the database manually but I should be able to add a clean check as well

**Comment by lachlan-00** [comment]
@itrushton is there a standard of the naming for these files? i'm about to put it in but i think i'll make it an opt-in change in the config file.

**Comment by lachlan-00** [comment]
added catalog_ignore_pattern with c71631b00

**Comment by itrushton** [comment]
The files can be any file name but always end in .htoa or .HTOA or .Htoa 


Sent from Yahoo Mail for iPhone


On Monday, August 16, 2021, 6:04 am, lachlan ***@***.***> wrote:




@itrushton is there a standard of the naming for these files? i'm about to put it in but i think i'll make it an opt-in change in the config file.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lachlan-00** [comment]
okay if it's a file extension it's interesting that .htoa extensions are being picked up as audio files as they aren't included in the catalog pattern

you can match excluded extensions and pattern anywhere in the files like this now.

```
catalog_ignore_pattern = "\(HTOA\)|\.htoa$"
```
This will match any file that has `(HTOA)` in the filename OR match files ending in `.htoa` (case insensitive)

catalog_ignore_pattern also matches for videos and playlists so you need to be pretty specific when you use it.

is there anything that wouldn't cover the original issue now besides deleting the files from the table?

**Comment by itrushton** [comment]
So sorry - I gave you the wrong info - should have checked first (teach me to answer in the middle of something else!).  The filename does always stay as .flac (in my case), but it appends (HTOA) or (htoa) or (Htoa) onto the end of the artist of the next track, see below:
00. Luther Vandross & Janet Jackson - (HTOA).flac
01. Luther Vandross & Janet Jackson - The best things in life are free.flac
you're new fix will pick that up though, so i will test it out.  And sorry again for the red herring!
    On Monday, 16 August 2021, 23:36:20 BST, lachlan ***@***.***> wrote:  
 
 


okay if it's a file extension it's interesting that .htoa extensions are being picked up as audio files as they aren't included in the catalog pattern

you can match excluded extensions and pattern anywhere in the files like this now.
catalog_ignore_pattern = "\(HTOA\)|\.htoa$"

This will match any file that has (HTOA) in the filename OR match files ending in .htoa (case insensitive)

catalog_ignore_pattern also matches for videos and playlists so you need to be pretty specific when you use it.

is there anything that wouldn't cover the original issue now besides deleting the files from the table?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lachlan-00** [comment]
That's even easier then because the config file example will cover that.
You could be more specific to include the " - " and the "." for the extension if you wanted

So if the files are all like this `$TITLE - (HTOA).$EXTENSION` this will cover it
```
catalog_ignore_pattern = " - \(HTOA\)\."
```

**Comment by lachlan-00** [comment]
To delete the files in the db i would just do it from mysqsl but 82ac359fc includes the delete regex when enabled so that should now cover everything
```
DELETE FROM `song` WHERE `file` LIKE '% - (HTOA).%;'
```
