### ISSUE TITLE
Radio station website

### ISSUE THREAD

**Issue by pisoj** [ampache/ampache#2978]
In the Radio Stations section link the radio station website and replace the stream link with the radio station website link in the station list.
![Screenshot_20210724-112548~2](https://user-images.githubusercontent.com/87895700/126864234-e389724c-2f4b-4689-bcc1-cf28c04ecc85.jpg)
![Screenshot_20210724-112458~2](https://user-images.githubusercontent.com/87895700/126864235-4e44ff6f-8b04-4b67-9fab-89d992b85c40.jpg)

**Comment by lachlan-00** [comment]
actually that would be a better option as there is already a play button on the row

**Comment by lachlan-00** [comment]
i've set this now as well as added the homepages to podcasts to be in line with this in 681f5d455
