### ISSUE TITLE
[Bug] Ampache really slow to show playlists ( normal or smart )

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2980]
### Describe the bug

Using a client or the web interface, i noted that ampache is really slow to show the playlist list, like i click on smart playlists and, even if i have a very little number, it takes forever.

So, i started to debug mysql and i use show processlist to see what sql command causes this behaviour.

The slow command is:

>SELECT sum(`song`.`size`) as size FROM `song` LEFT JOIN `object_count` ON `song`.`id`=`object_count`

that takes forever.

The command seems located in :

> src/Repository/Model/User.php
>   public function format($details = true)

That explains:

    /**
     * format
     * This function sets up the extra variables we need when we are displaying a
     * user for an admin, these should not be normally called when creating a
     * user object
     * @param boolean $details
     */

  /* Calculate their total Bandwidth Usage */

  >  $sql        = "SELECT sum(`song`.`size`) as size FROM `song` LEFT JOIN `object_count` ON `song`.`id`=`object_count`.`object_id` WHERE `object_count`.`user`=" . $this->id . " AND `object_count`.`object_type`='song'";

but i cannot imagine why 
a)we need to calculate the bandwidth usage every time we need to show a list of playlists
and 
b)why, if this command is so time consuming, it is not calculated and stored when the catalog is changed and not every time we read the catalog.

## Environment

* Ampache version: 5.0 develop
* Web server + version:
* Server operating system:
* Client operating system: every client

**Comment by lachlan-00** [comment]
are you mariadb or mysql? mysql can be slower if the query is built a certain way

There's a bandwith usage plugin as well as calculated usage per-user in the admin page, i don't know why it's done on load and not play but we'll have a look and see if we can speed it up.

**Comment by lachlan-00** [comment]
I might actually make that a user table column, really useless to calculate that every load of a user

**Comment by lachlan-00** [comment]
7d036b261 should sort this out. it also makes the totals better because it never actually counted videos or podcasts if enabled

**Comment by lusum** [comment]
Mysql, btw. Now some queries are really faster, smart playlist more faster, but i have found another issue:

When i click smart playlist on web interface and examining the mysql commands ( show processlist; ) i have found that for every playlist i have:

>SELECT * FROM `playlist` WHERE `id`= 'id' 

and 

>Sending to client 

I have checked the playlist by id and i have found that the playlist table doesn't contain any smart playlist and the ids do not match any smary playlist. So, why search for playlist table when smart playlist only are involved?

**Comment by lachlan-00** [comment]
possibly in get_info `public function get_info($object_id, $table_name = '')`

I see a 
```
$sql        = "SELECT * FROM `$table` WHERE `id`= ?";
```

**Comment by lachlan-00** [comment]
it might be getting the list of playlist names for searching? is that on the pages where you load the list with rules on the page?

**Comment by lachlan-00** [comment]
reminder for me. get the id arrays here (and probably in other places)
![image](https://user-images.githubusercontent.com/1305249/127426650-b7eeef93-75ac-4c2f-b783-97ce2f7288b7.png)

**Comment by lusum** [comment]
>it might be getting the list of playlist names for searching? is that on the pages where you load the list with rules on the page?

the slow command is:

>http://x.x.x.x/ampache/index.php#browse.php?action=smartplaylist

but this command: 

>http://x.x.x.x/ampache/index.php#browse.php?action=playlist

is a lot faster

I will try to enable mysql logs to see what queries are slowing the first one

**Comment by lusum** [comment]
Ok, mysql log activate. We have the same queries with playlist and smartplaylist, the longest are fetching data from each playlist. It is like with playlist command ampache fetchs the data of every playlist two time, with smartplaylist ampache fetch the data of every playlist ( even the not smart ) two times for every smartplalist present. ( the logs become really long in this case )

**Comment by lachlan-00** [comment]
I've found a lot of formats and constructs on these pages. Going to dig into this over the weekend. I've made a lot of progress

**Comment by lusum** [comment]
Really fast, now, great work!, bug closed!
