### ISSUE TITLE
 [Bug] Italian translation breaks modify album script

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#2982]
### Describe the bug

In web  interface, admin user, if you use modify album with italian translation activated, the showEditDialog doesn't show up. The problem is caused by a string ( 'Edita l'album' ) with an apostrophe not escaped that broke the function. If we use 
`'Edita l\' album'` instead ( escaped ) the function works again.

an example of offending line
`<a id="edit_album_12981" onclick="showEditDialog('album_row', '12981', 'edit_album_12981', 'Edita l'album', '')">
<img src="http://x.x.x.x/ampache/themes/reborn/images/icons/icon_edit.png" alt="Modifica" title="Modifica">                Modifica album            </a>`

#Screenshot

![error](https://user-images.githubusercontent.com/541595/128018708-2c71db60-8775-467c-a9ac-e65ffcffa481.png)

## Environment

* Ampache version: 5.0 develop
* Web server + version: every server
* Server operating system:every os
* Client operating system: web client

### Client type

* Web
 * Ampache

**Comment by lachlan-00** [comment]
i've put addslashes into 4983fccab for every editdialog template so this should cover it

**Comment by lusum** [comment]
Now it works, thanks!
