### ISSUE TITLE
Radio stations API access

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#2987]
How can the radio stations feature be implemented through the API? I am looking for a method to 
- retrieve the list of radio stations, 
- get the details of a single radio station and 
- get a stream url (HLS?) for that station. 

Do I miss something in the docs regarding these radio stations? I found some mentions of a "live_stream" attribute, but it isn't clear how these relate to radio stations and how to retrieve info and the streams themselves. Is this a new feature that is under development?

Thanks for your help in advance!

**Comment by lachlan-00** [comment]
todo in https://github.com/ampache/ampache/projects/6

live_stream is the name of the database table but i'll call the methods radio
![image](https://user-images.githubusercontent.com/1305249/129115402-d8948a92-4b02-42d9-9587-dbae83cbfe9b.png)

columns are
id - 3
name - Triple M Brisbane (TuneIn)
site_url - https://www.triplem.com.au/brisbane
url - https://ic4ti.scahw.com.au/4mmm_128
genre - 0
catalog - 2 
codec - m4a

**Comment by memen45** [comment]
Thanks, looking forward to it. Is it correct that it is already included in the `get_indexes` action with type `live_stream`?

**Comment by lachlan-00** [comment]
yes live_stream is valid for indexes

BUT

it actually looks like it's missing from json :/
![image](https://user-images.githubusercontent.com/1305249/131934377-d6036525-5c75-49be-a148-dfc817695cf3.png)

**Comment by lachlan-00** [comment]
looks like 5.0.1 will be coming in a few weeks to fix that with f9445d969

**Comment by lachlan-00** [comment]
i'll add the missing stream create,edit and delete functions this week

**Comment by lachlan-00** [comment]
Create edit and delete now added with 6de44e4d7

I'll make sure it all works with my test scripts but now you can edit, create and delete away

(requires access 50 - content manager at a minimum to create these stations)
