### ISSUE TITLE
[BUG]: Can't select a catalog when subscribing to a podcast and therefore can't subscribe.

### ISSUE THREAD

**Issue by sandersantema** [ampache/ampache#2988]
### Describe the bug

There simply seems to be no options in the dropdown list for catalogs:
![image](https://user-images.githubusercontent.com/21057514/129052857-6c8a1579-29ba-4623-bc23-33c4cf27b2ce.png)

Trying to subscribe without a catalog selected fails:
![image](https://user-images.githubusercontent.com/21057514/129053080-5d48c554-1af8-4bfe-aec0-d74ea8eb80de.png)

### To reproduce

Try to select a catalog when subscribing to a new podcast

## Environment

* Ampache version: Latest develop

### Client type

* Web

Other clients might be affected but I wouldn't know since I don't know of a client with capabilities to subscribe to a podcast.

## Settings

I've enabled podcasts in my settings file, other than that I've not changed much other than the required settings and added some api keys.

**Comment by lachlan-00** [comment]
you have to create a podcast catalog first too, music and podcast catalogs are separated
![image](https://user-images.githubusercontent.com/1305249/129114536-9d17107f-3aeb-4b29-9dac-9f90f5485193.png)

**Comment by sandersantema** [comment]
That's it! Missed that. Thanks :)

**Comment by lachlan-00** [comment]
I'll make a string to notify that a podcast Catalog is missing for that page too

**Comment by lachlan-00** [comment]
540e98806 informs you and isn't able to add (because the value is null)

![image](https://user-images.githubusercontent.com/1305249/129301492-f9ff520b-5016-4a68-bcdf-f68644ce482f.png)
