### ISSUE TITLE
song image fall back to Album art

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#2991]
Latest Ampache version: 
1d4cb7c187108987b7322c6eb616e6a0de42be00

if config is set to show_song_art = "true"  and no art is available .. would it be hard to make code default back to album art instead of showing missing image....... Too me a few minutes to realize I had turn it on and thought my art was broken or something.. LOL

**Comment by lachlan-00** [comment]
that's probably a good idea. or at the very least import something into song when nothing is there

**Comment by lachlan-00** [comment]
6bc54dcf9 and 54e6fcd47 add checks that song art actually exists before continuing which falls back to album

I think this covers the areas where song art is used now

**Comment by lachlan-00** [comment]
If you find any more let me know but i've done these 2 commits based on whether song_art is used so should be good
