### ISSUE TITLE
[Feature Request]: Catalog Permissions / extension of the catalog_filter

### ISSUE THREAD

**Issue by miniskipper** [ampache/ampache#2993]
Hi there,

I would like to be able to restrict access to certain catalogs to different users so I set catalog_filter = "true" using the develop branch.
I have a catalog with music, my children should not listen to. Only me and my wife should see them.
On the other side, we don't want to be presented childrens audiobooks and music when listening to random music. 

The current implementation of the catalog_filter feature is a good start, but I had some headache there:
- access is possible for ONE or ALL users - I want to be able to permit acces to 2 users
- as soon as the now playing widget shows an album users without permission are able to listen to it, the catalog_filter only restricts what is returned by the search function
- the subsonic api does (at least for some actions) not mind the filter at all and the app shows all albums (tested with DSub)

I made some progress by putting access restrictions into a new table, simply mapping user_id and catalog_id.
I changed the queries that utilized the filter_user column of the catalog to look for an entry in this new table.
Then I changed some of the subsonic-features (_albumList with types frequent, recent, starred, alphabeticalByName, alphabeticalByArtist and byGenre did not filter at all)

With those simple changes I can now restrict my 2 childrens accounts (using the DSub app on 2 old phones) to only list "their" albums.
The 2 accounts of me and my wife do not get disturbed by childrens songs when playing random music.

I did only change the bare minimum to make it work for our usecase with focus on the subsonic app. Before putting more effort into this feature I would like to know if there is a demand for this at all?
If yes: There would be a lot more work to do and I might need some guidance here and there. Maybe access could even be restricted on a per-album or per-song basis (I think about explicit lyrics or covers)?

**Comment by lachlan-00** [comment]
> as soon as the now playing widget shows an album users without permission are able to listen to it, the catalog_filter only restricts what is returned by the search function

Ahh, that's a good one, there will be a few places like that, i'll actually put a check in the play function to stop that. if we stop it at the play section it will stop playing and i'll look at keeping the now_playing private on top of that.


Catalog filter has been such a hugely requested feature i would expect demand for it.

Things that might make is easier:

* a column in song/artist/album tables called say 'restricted' (like disabled) allowing you as an admin to restrict access to single items 
* creating groups for users or relying on the user access level for filtering. (eg. catalog accessible by Admin users only and the kids are regulars)
* if user permission was used it could work better to extend the catalog_filter option into 2 options (true/user + access) then we could split the access model into 2 types

I kept it pretty simple as the biggest issue you'll find will be speed, so as long as it kept browsing at a decent speed there's no reason to not extend this further.

**Comment by lachlan-00** [comment]
i'll fix the playing restricted files part now but the further extension won't make it to 5.0.0

**Comment by lachlan-00** [comment]
I've put some restrictions in when using catalog_filter in acb192482

* don't add to now_playing if you can't see the catalog
* don't stream if you have an id you shouldn't have

This should stop anyone playing podcasts, songs, and videos that are restricted by catalog. just going to work on restricting a bit further

**Comment by troycarpenter** [comment]
I am very interested in this as the usecase is similar to mine.  I have some catalogs that I do not want younger children to have access to.  As a first test on this, I have tried limiting a catalog to my user.  However, the problem I found is that, if an artist is in two different catalogs, one the user can access and another the user cannot access, the artist page shows ALL the albums from both catalogs.  The difference is that when the album that is in the restricted catalog is selected, it shows zero tracks.  I reality, I don't want the user to even know that album exists even if they cannot access the tracks (could be important if album art for those albums isn't age appropriate either).

I like the fact that albums for an artist that span catalogs are all shown in one place.  Historically, other Subsonic type servers will show a separate entry for the same artist if that artist appears in multiple catalogs.  This is vary obvious with the "Various Artists" entry where all albums from all catalogs that have a Various Artist folder are shown.  That's nice if the "All" Categories or Folders is selected. 

However, it would be nice if the catalog filter applied all the way down to the album level.  That is, if I select a catalog, I would only want to see albums from that artist that are in the category selected and all other albums are excluded.

Is that what you are trying to achieve in this feature request?

**Comment by lachlan-00** [comment]
There will be ways to map this, the catalog id is on songs/artists and albums so it will be not setting this in some pages.

first one i see is src/Repository/AlbumRepository.php getByArtist which will only check if the catalog is disabled.

There will probably be a lot of work to resolve this but really if you see things on a page that shouldn't be there i can ID it pretty quickly from the url and resolve it

**Comment by troycarpenter** [comment]
So what is the long term plan?  The filtering based on the currently selected catalog is nice to avoid unwanted albums without resorting to fancy search criteria.  

BUT, I have the single music server, but not everyone who has access should have access to everything.  Not only should they not have access, I don't even want them knowing the hidden content is even there.  Right now I can't achieve that with the current "permissions" system.

**Comment by lachlan-00** [comment]
catalog_filter is supposed to filter everything for users that don't have access to that catalog.

This feature is only semi-recent and the issue is that most of the Ampache code is built around being completely open to all users so it still has parts that need work.

So what you'll probably find is that there are still things that don't reference the catalog filter when set/searching/etc.

End goal is totally private and unable to be found at all. Right now the direct links are still accessible if a user can guess them so there's a bit to go.

**Comment by troycarpenter** [comment]
So the question would be this: Do you consider the feature far enough along for me to write bugs on some of the things I've found?

Also, there are two different issues that are tied to catalog filtering.

1. When an artist spans multiple catalogs, all that artist's albums are listed on the artist page.  The albums shown should depend on the catalog browse filter selected.

2. Catalog restrictions need to be applied at a user level and pushed down to all the code that shows content to the current user.  The only catalogs they should see are the ones to which they have access, and any asset in a non-authorized catalog should not be shown.

The above needs to apply to the Subsoinc API as well.

**Comment by troycarpenter** [comment]
I am currently working on the database changes to support this feature.  I will have a new table that contains the access level and its name (and add a DEFAULT entry with id of 1), another new table that contains the tuple of (access_name, catalog_id, and enabled (true or false) ).  Finally, a new attribute to the user profile "catalog_access" which will be the ID from first table.

Once the new tables are in place, I can start working on GUI screens to create the new levels and assign catalogs to the levels, and then the user screen to allow a profile to be assigned.  By default, the user gets the DEFAULT profile (ID=0).

Where do I find the code that upgrades the database on startup so I can write the upgrade routines as well?

**Comment by troycarpenter** [comment]
I have started a discussion thread for this feature here: #3244

**Comment by troycarpenter** [comment]
For those not following my monolog discussion at #3244, here's a quick summary of what I've got working on my private branch.  Once I get GUI control of the feature, I'll submit and open for bugs:

Here's what works right now. Given a set of Catalog IDs, content not in that set is not shown. Going down the menu on the left side of the Ampache GUI:

Browse: all content type (album, songs, artists, etc) is filtered
Dashboards: Trending/Newest/Popular for albums/artists are filtered
Playlists: I have not verified playlist functionality yet. Clearly a playlist with content from allowed catalogs will work, but what about a playlist that has songs from a restricted catalog.
Search: Only random search works properly
Information: All info seems to be filtered appropriately.

Also, the catalog restrictions are not controllable via the GUI yet. Right now my testing is done with data already in the database tables.

TODO:
Filter the search results for Songs/Albums/Artists
Filter global search (the one at the top)
Create some playlists and be sure songs are filtered appropriately
Create GUIs to control the feature.

**Comment by troycarpenter** [comment]
https://github.com/ampache/ampache/wiki/catalog-filters

**Comment by mitchray** [comment]
I think this can be closed now 👍
