### ISSUE TITLE
Podcast date-time format in the API

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#2994]
Looking at https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/podcast_episodes.xml and other podcast-related sample responses, it seems that they all use American style date-time format e.g. "7/31/21, 3:00 AM". This isn't quite great since in many cases it may be ambiguous if the timestamp in question
a) uses the MM/DD/YY convention or DD/MM/YY convention
b) is in local time (where) or UTC time.

In the handshake response https://github.com/ampache/python3-ampache/blob/master/docs/xml-responses/handshake.xml the software is already using ISO-formatted timestamps which is the only sensible alternative in any API. Couldn't this same convention be applied on the podcast methods, too? That would surely make the life of the client developers easier.

**Comment by lachlan-00** [comment]
it's using f_pubdate which is formatted to the locale / custom_datetime
![image](https://user-images.githubusercontent.com/1305249/130154892-3591cd04-07e9-4d50-9c56-fdd883251df0.png)

Subsonic uses the iso date `date("c", (int)$episode->pubdate)` which is proabbly what should be used for the date

**Comment by lachlan-00** [comment]
i've made that change in 3f0e63f5d

**Comment by lachlan-00** [comment]
I think i'll do it for the other sync and build, etc dates as well there's no reason to pretty them up

**Comment by lachlan-00** [comment]
AND before i close this off i'll make all API dates that aren't epoch ints convert as well

**Comment by lachlan-00** [comment]
d5ae2badc converts some other dates, I'll document this in the site/docs pages now too.

new (newly documented) rule
* Ampache dates (catalogs, times, etc etc) are all epoch ints and not formatted strings
* podcasts dates are all using ISO 8601 date date in subsonic and api

**Comment by lachlan-00** [comment]
updated in the standards docs and examples are all updated.

![image](https://user-images.githubusercontent.com/1305249/130164728-a99df69c-7659-48a1-a03a-001ba4feb2c3.png)

i'll do another run on dates but so far i think i've got them all covered

**Comment by paulijar** [comment]
Great, thanks! This "living on the other side of the globe" thing works almost like magic: I report something as last thing in the evening, and when I wake up in the morning it's fixed 😄.

**Comment by lachlan-00** [comment]
It does feel like being a digital Santa sometimes.
