### ISSUE TITLE
Getting 404 error in installation on submission of step 3 | ampache 5.0.0

### ISSUE THREAD

**Issue by GaneshKandu** [ampache/ampache#3006]
Hi,

I am trying to install Ampache5.0.0 but i am getting 404 error in installation on submission of step 3,
form redirects to login.php instead of public/login.php

i am installing on sub-directory of webroot.

**Comment by lachlan-00** [comment]
public needs to be the web root now and not the root project dir

https://github.com/ampache/ampache/wiki/Ampache-next-Changes

**Comment by InspectorSparky** [comment]
If it helps, I run ampache on a different port which may be a favorable configuration for some. Here is my ampache.conf for apache2. Don't forget to enable it by running the following commands after the conf file is saved in the sites-available folder.
sudo a2ensite ampache.conf
then
sudo service apache2 reload OR sudo service apache2 restart

<VirtualHost *:4040>
    ServerName 127.0.0.1
    DocumentRoot /var/www/ampache/public

    <Directory /var/www/ampache/public>
        AllowOverride All
        Require all granted
    </Directory>

    RewriteEngine on
    CustomLog /var/log/apache2/ampache.access.log common
    ErrorLog  /var/log/apache2/ampache.error.log

</VirtualHost>
