### ISSUE TITLE
Time vs filelength attributes in song vs episode

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#3008]
The following two endpoints have different ways of describing the duration of an audio file:

[`playlist_songs`](https://ampache.org/api/api-json-methods#playlist_songs) returns an array of song objects, each has the element 'time' which is an integer with the second count of the audio file.
[`podcast_episodes`](https://ampache.org/api/api-json-methods#podcast_episodes) returns an array of episode objects, each has the element 'filelength' which is a string with the format 'hh:mm:ss'. 

Why are these different and would it be possible to use the same way of defining duration of the underlying audio file?

**Comment by memen45** [comment]
Hi,

Any thoughts on this? Would be great if the same format can be used, as it simplifies implementation of songs vs episodes!

Best regards,

**Comment by lachlan-00** [comment]
time is in the podcast episode table so i'll just add that in.

**Comment by lachlan-00** [comment]
108c73a7f adds in the time. is there any other property you're thinking of that's missing there?
