### ISSUE TITLE
[Feature Request] Ampache docker debug log to stdout 

### ISSUE THREAD

**Issue by phirestalker** [ampache/ampache#3012]
## Describe what you don't like about Ampache, or what it is missing
For the docker image, enabling the debug log writes it to a file in the container.

## Describe how you would like the feature to work**
I would like the debug logs to show up when I run docker logs on the container. I know I can just mount a volume to the logs directory to access the logs outside of the container, but I have many services running and it is hard to remember which ones need to have a log file checked as well.

**Comment by cvinhaes** [comment]
I second this request.

**Comment by phirestalker** [comment]
No longer use Ampache due to it ignoring files.

**Comment by cvinhaes** [comment]
@phirestalker , could you please elaborate "ignoring files"?

**Comment by lachlan-00** [comment]
seems like it can just have a symbolic link to the /dev/stdout path?

https://docs.docker.com/config/containers/logging/

**Comment by cvinhaes** [comment]
Yes, found this workaround documented for Nginx and tested with Ampache, but with no success. Get an error from Ampache not being able to write to the file. Maybe permission issues, I need to spend more time on that. Thanks for the response.

**Comment by lachlan-00** [comment]
I think that will be the webserver not being able to write to that path.
![image](https://user-images.githubusercontent.com/1305249/196592621-6512dea4-10bd-4f44-a063-889a5084cc69.png)

so the log file is written to by www-data and stdout is owned by root.

I'm sure there are other ways around that without making www-data a member of root but i haven't checked yet
