### ISSUE TITLE
Help - Nginx reverse proxy for ampache

### ISSUE THREAD

**Issue by ebiscaia** [ampache/ampache#3013]
Hi guys,

I would like a bit of help to finish setting up Ampache. The final bit is to configure nginx as a reverse proxy for it.
Here is my config:
      `upstream ampache {
         server 192.168.1.245:8080;
        }

   server {
         listen 80;
         server_name ampache.eddienetworks.ddnsfree.com *.ampache.eddienetworks.ddnsfree.com;
         rewrite ^(.*) https://$host$1 permanent;
   }

  server {

        server_name ampache.eddienetworks.ddnsfree.com *.ampache.eddienetworks.ddnsfree.com;
       location / {
               proxy_pass http://ampache;
               proxy_set_header Host $host;
        }
    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/eddienetworks.ddnsfree.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/eddienetworks.ddnsfree.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
   }
   `

   And here is my vhost config (using Apache2)
   `<VirtualHost *:8080>
     DocumentRoot "/var/www/ampache/public"
     ServerName ampache.eddienetworks.ddnsfree.com
     ServerAlias *.ampache.eddienetworks.ddnsfree.com

     <Directory "/var/www/ampache/public">
         Options MultiViews FollowSymlinks
         AllowOverride All
         Order allow,deny
         Allow from all
    </Directory>

    TransferLog /var/log/apache2/access.log
    ErrorLog /var/log/apache2/error.log

   </VirtualHost>`

Final result is a page messed up, so any input would be appreciated.

Thanks,

Eduardo

**Comment by stebe** [comment]
This is my ngnix setting for ampache. Maybe you can get something out of this. My apache server is on localhost.


```

server {
    server_name ampache.animeshare.com;

    client_max_body_size 15G;
    listen 443 ssl ;
    listen [::]:443 ssl ;

location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_send_timeout 1200;
	proxy_read_timeout 1200;
    }
}


server {

    if ($host = ampache.animeshare.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name ampache.animeshare.com;
    return 404; # managed by Certbot
}

```

**Comment by stebe** [comment]
This is my apache config

```
<VirtualHost *:8080>
  DocumentRoot /var/www/ampache/public
  ServerName  ampache.animeshare.com
  ServerAdmin webmaster@animeshare.net
  Protocols h2 http/1.1
  <Directory /var/www/ampache/>
          DirectoryIndex index.php
          Options -Indexes +FollowSymLinks +MultiViews
          AllowOverride All
          Require all granted
  </Directory>

<IfModule mod_rewrite.c>
    RewriteEngine On
</IfModule>

</VirtualHost>


```

**Comment by ebiscaia** [comment]
Hey mate,

Just to let you know I applied your settings and everything went fine.

Thanks again

**Comment by mitchray** [comment]
Closing as it looks to have been resolved 👍
