### ISSUE TITLE
fixes to subsonic/lucene advanced search

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#3016]
Subsonic has a search feature to match exact string using quotes in the search string

This has been added in 99dac9fcd and 04976f48d

It will be released with the next stable update which should be next month at the latest.

keeping this issue open and tagging until release

**Comment by lachlan-00** [comment]
ghenry22@gmail.com

**Comment by lusum** [comment]
Has been already added? Bug to close?

**Comment by lachlan-00** [comment]
yes, this was done a while ago
