### ISSUE TITLE
Multi-disk albums are inconsistantly being displayed redundantly.

### ISSUE THREAD

**Issue by InspectorSparky** [ampache/ampache#3018]
## Description
Server:
Ampache 5.0.0-release (no modifications, nearly out-of-the-box configuration)
PHP 7.4.21
Debian 11 (fresh install)

### Describe the bug
This issue is specific to multi-disk albums where the album should show up as a single album in the main listing but contain all associated disks within. So far I have had inconsistent results with using this feature. When the album name, album artist, year and genre are set the same and the disk numbers are set to the actual disk numbers, some albums will show up as a single album in the main listing and others as an individual listing for each disk in the set. I have reset and re-entered all the info trying to correct this without any success. When it shows more than once it does seem to know that it is a multi-disk collection because the "Post Shout" and "Edit" icons are not present for each duplicate album. I haven't tested all scenarios but this seems to happen when displaying albums by genre. It also displays the same total song count next to each duplicate album listed, the number being the overall total of all songs in all disks involved. These duplicate album listings are 100% redundant and any links are identical for each.

Here is a album that shows up 3x when it should be only listed once for a 3 disk set. 
![image](https://user-images.githubusercontent.com/90430718/132785419-6da3bb14-bffd-4e69-adcd-facdf1b10945.png)

**Comment by lusum** [comment]
It doesn't seems related to multi disk management, in this case ampache sees the albums like three different albums with the same name and the same artist.
Probably in the tags is present a field that make the single disk unique, like a musicbrainz album_id.

**Comment by lachlan-00** [comment]
Default album group is done in sql grouping by
```
GROUP BY `prefix`, `name`, `album_artist`, `release_type`, `release_status`, `mbid`, `year`, `original_year`
```

one of those columns will not be the same and will be causing the split

**Comment by lusum** [comment]
Tested with mock files with the same name, year and album artist, ampache recognize the three albums.

**Comment by lusum** [comment]
I think that we can close this issue, the problem seems not related to multi disk management, but, maybe, to another issue in the tags.

**Comment by mitchray** [comment]
> I think that we can close this issue, the problem seems not related to multi disk management, but, maybe, to another issue in the tags.

Closing, reopen if still relevant 👍
