### ISSUE TITLE
record_play required 'user' parameter

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#3021]
https://github.com/ampache/ampache/blob/a93fe6a4bff4b003c98f3da7016183d03dc7e57c/src/Module/Api/Method/RecordPlayMethod.php#L58

Seems contradicting the [docs](https://ampache.org/api/api-json-methods#record_play), as the docs say 'user' parameter is optional?

**Comment by lachlan-00** [comment]
it's meant to be, another simple thing i missed.

5.1 will be a week or two away while i work on merging but it's in 78f3c2303 now

**Comment by memen45** [comment]
Haha don't worry and thanks for fixing, this is one of the few repositories that are so clear that code and docs can be easily found and matched! 

You removed id from the check as well?

**Comment by lachlan-00** [comment]
whoops, id is mandatory, put it back with 6af5e65a9
