### ISSUE TITLE
[Feature Request] API: Allow using `stats` also with playlists and podcasts

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3022]
According to the API specification, the action [stats](https://ampache.org/api/api-xml-methods#stats) may be used on types 'song', 'album', and 'artist'. As I see it, it would make lot of sense to support also types 'playlist', 'podcast', and 'podcast_episode' (and maybe some some?). For example, it is possible to flag all of these entity types, but there doesn't seem to be any method to obtain the flagged items.

I'm not certain if all of the `filter` values would be applicable with these added types. However, at least filters 'newest', 'flagged', and 'random' would make sense.

PS: I have actually already implemented this for the podcasts on the API provided by Nextcloud Music as a non-standard API extension. I'm not expecting anyone to use it as long as it's not in the API specification, but on the other hand, in my case it required just one line code change.

**Comment by lachlan-00** [comment]
stats is a very convoluted class but i'll look at these now

**Comment by lachlan-00** [comment]
i'm about half way through all the options but this should be in develop in the next day or so.

playlists haven't been recorded in object count before today but this should help with the dashboards and other areas

**Comment by lachlan-00** [comment]
initial work is now in badc10f21

They seem to work all correctly but i need to actually use and play more podcasts to verify everything

**Comment by lachlan-00** [comment]
done with 5.1
