### ISSUE TITLE
Track size 0 in the database when adding

### ISSUE THREAD

**Issue by douglasriper** [ampache/ampache#3027]
### Describe the bug
Hi,
I added music in flac format, when updating the database, the file size field is set to 0.
Ampache has good access to the files since it can read all the rest. And the files aren't corrupted
I don't think this is due to the file, because by moving a file that had no problem in another folder, its size becomes zero in the database.

### To reproduce

Add Music (flac only ?)
php /var/ampache/bin/cli run:updateCatalog -cag

## Environment

* Ampache version: 5.0 dev, up to date
* Web server + version: Apache 2 : 2.4.41
* PHP 7.4
* Server operating system: Ubuntu 20.04 LTD
* Client operating system: N/A

## Logs
I had not activated the logs at the time of the update

**Comment by lachlan-00** [comment]
Are you on develop? I've had to do a lot for php8 so it would be good if you could just do a verify on the album and check the table again.

Right now i can't see any files reported as 0 after the fixes i made today so please check again and let me know

**Comment by douglasriper** [comment]
Hi,
Yes in develop version.
I probably misunderstood the requirements for this version, I thought that PHP8 would be necessary only from 5.1.

I did the AFMDAF update and then the catalog update but it didn't change anything
In the Songs table the Size value is 0.
The other values seem to be correct.

**Comment by douglasriper** [comment]
After the update: Half of the files have a size of 0 in the database and the other half do not

**Comment by lusum** [comment]
It is triggered by enable_custom_metadata  option, as in other bugs

**Comment by lachlan-00** [comment]
with d42459cf6 i was able to clear my 0 files after enabling custom metadata

**Comment by douglasriper** [comment]
It works, thank you.

**Comment by lachlan-00** [comment]
awesome! so glad this one is done
