### ISSUE TITLE
User cannot stay logged in

### ISSUE THREAD

**Issue by ainola** [ampache/ampache#303]
Even with 'Remember Me' checked on login, a user is booted after an hour or two. It would be nice to be able to stay logged in. :)

**Comment by Afterster** [comment]
Ok I will reserve myself some time to work on this again. As you said @ainola I can identify myself only the same both remaining issues and I'm not sure it is really an issue.
1) Don't you have this main page returns after the session lifetime expired? I believe `social` feature is disabled on your side? If so, a fix would be to query the server every xx minutes to keep the session alive.
2) Could be related to 1). For streaming to external app it cannot be fixed I believe, the stream session must have a (shorter) lifetime.

**Comment by ainola** [comment]
Well, it turns out that issue 1 is no longer a problem for me! I happen to be sitting in front of my ampache installation and an album I listened to yesterday is still up. So it lasted a night's worth of suspend.

I'm sure you know what you're doing in regards to point 2. It's probably an internals thing with apache or something.

In any case, I think I would safely call this closed for me. It all works! The latest dev code enables me to stay logged in for as long as I specify (in my case, a month) and now properly keeps any album that I leave open.

**Comment by gnujeremie** [comment]
Same for me, I saw yesterday the issue was gone.
