### ISSUE TITLE
Stream Playlist URL Issue

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3035]
Hi all, not sure when this error started happening but recently Streaming playlists via the web interface stopped working for me, with VLC reporting 'VLC is unable to open the MRL' for every track.

After a little playing around with the m3u playlist that is sent from ampache, I found that the 'subtitle' part of the URL was causing the problem.

The string sent by ampache in the m3u playlist is: 
```#EXTM3U
#EXTINF:426, Black Sabbath - Dirty Women (Remastered)
https://ampache.rsinfotech.co.uk/play/ssid/96f23ca3e617f22dcaa0f4f579aeba3b/type/song/oid/114757/uid/2/subtitle//name/Black%20Sabbath%20-%20Dirty%20Women%20-Remastered-.flac
```

If I edit out the empty 'subtitle' part of the URL, the stream starts working perfectly again:
```#EXTM3U
#EXTINF:426, Black Sabbath - Dirty Women (Remastered)
https://ampache.rsinfotech.co.uk/play/ssid/96f23ca3e617f22dcaa0f4f579aeba3b/type/song/oid/114757/uid/2/name/Black%20Sabbath%20-%20Dirty%20Women%20-Remastered-.flac
```

Many thanks for the continued fantastic work!

**Comment by lachlan-00** [comment]
This will be part of the php8 work I've been doing will fix asap

**Comment by lachlan-00** [comment]
updates with 923bf3bf1 and others today should not put in elements that don't have a value like this

**Comment by lachlan-00** [comment]
ahh, i see where it might be coming in.

38301bcc5 fixes a typo and add extra checks
