### ISSUE TITLE
SQL error prevents the "Albums of the Moment" to be displayed

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3036]
## Description
SQL error prevents the "Albums of the Moment" to be displayed

### Describe the bug

The main page of ampache should show the Albums of the Moment however this section is not being displayed.

Apparently, looking into the logs there seems to be a bad sql query that prevents the Albums of the Moment being displayed: 

2021-10-09T00:34:53+02:00 [admin] (Ampache\Module\System\Dba) -> Error_query SQL: SELECT DISTINCT `album`.`id` FROM `album`  AND `album`.`id` IN (SELECT `object_id` FROM `catalog_map` LEFT JOIN `catalog` ON `catalog_map`.`catalog_id` = `catalog`.`id` WHERE `catalog_map`.`object_type` = 'album' AND `catalog`.`filter_user` IN (0, 1) GROUP BY `catalog_map`.`object_id`) ORDER BY RAND() LIMIT 6

### To reproduce

1. Go to main ampache page
2. No Albums of the Moment are shown
3. The log contains SQL query errors.

## Environment

* Ampache version: 5.0.0
* Web server + version: apache 2.4.48
* Server operating system: Raspbian 11
* Client operating system:  Debian 11

### Client type

* Web

**Comment by lachlan-00** [comment]
and instead of where...

**Comment by cquike** [comment]
It sounds like the logic introduced in 27c5bb541aa0fec5b4e9e576ca9a8f5dd9285b8a is not fully correct under the following configuration: 

1. album_group is false
2. catalog_disable is false 
3. catalog_filter is true

I have sketched a possible solution that I will post as a PR soon.

**Comment by cquike** [comment]
PR #3037 contains a potential fix for this issue.
