### ISSUE TITLE
bin/cli -- run:updateCatalog doesn't have any effect

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3041]
## Description
According to https://github.com/ampache/ampache/wiki/cli-faq,   ./bin/cli run:updateCatalog should be equivalent to ./bin/catalog_update.inc. However this is not completely true, since the ./bin/catalog_update.inc does everything if no options are given, whereas ./bin/cli run:updateCatalog  doesn't do anything in that case.
 
  I think that at least the wiki page should be updated to inform that the default behavior (when no options are given) has changed with respect to the previous command line ./bin/catalog_update.inc.

 Also the usage example is wrong:
```
Usage Examples:
  run:updateCatalog some-catalog local   # Update the local catalog called `some-catalog`
```

The correct  command in the example should be  `"run:updateCatalog -u some-catalog local"`

## Environment

* Ampache version: 5.0.0

**Comment by lachlan-00** [comment]
221e07cb0 sets -cage when nothing is set now

**Comment by tomchiverton** [comment]
Can close this off then ?
