### ISSUE TITLE
translating the database strings

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#3051]
hey @Psy-Virus

i've translated the database strings inside the code so they get picked up by gather-messages.sh
(667f6df08 and 11f764526)

I'm going to expand this to allow updating translations on the fly for the database to avoid having to write extra steps for translation sync.

This should take out the need for translatable-database-strings.txt right?

**Comment by Psy-Virus** [comment]
Sounds good and yes, it should. 😃

**Comment by lachlan-00** [comment]
Sounds good Just wanted to bounce that off you
