### ISSUE TITLE
Search boxes and the option for select a catalog is missing in 5

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#3060]
### Describe the bug

On ampache 5 is no longer posible to filter albums by catalog?

this is a screen shot of previous versions:

![albums view](https://user-images.githubusercontent.com/19354668/138130850-57135b5f-f969-4426-95e1-1b8ebbfd3ea9.png)

also the filter for playlist is missing:

![playlist view](https://user-images.githubusercontent.com/19354668/138131049-29d33d18-67be-4b01-9059-cf4a5f9e60ec.jpg)

Theres a way to bring it back or it was an intented change?

Thanks.

## Environment

* Ampache version: 5
* Web server + version: 
* Server operating system:
* Client operating system:

**Comment by lachlan-00** [comment]
i don't usually have the filters on but did not intend to remove it if i did.

will check out

**Comment by lachlan-00** [comment]
interesting, it's okay here in develop
![image](https://user-images.githubusercontent.com/1305249/138182629-6a5117e7-1c60-48c4-95e0-2774602f1c39.png)

I've also tried the demo sites and they all show the browse for catalogs

It could be an error with translations? could you temporarily try en_US and see if it comes back?
