### ISSUE TITLE
Support for API3, API4 in Ampache 5

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#3062]
Great to see the improved Ampache5 API specification! In order to temporarily maintain support for both Ampache4 and new Ampache5 specifications, I was wondering if it possible to enforce the version of the responses to Ampache4 spec. This would allow users to switch to Ampache5 freely while I can implement all Ampache5 updates.

I noticed the 'version' parameter for the handshake and ping methods, however, do they apply to other methods as well?

**Comment by memen45** [comment]
Okay, thanks for clarification!

**Comment by lachlan-00** [comment]
Work is almost done. i can get data from any api version 3,4,5 using my python scripts. going to merge tomorrow for wider testing.

**Comment by lachlan-00** [comment]
098518e51 is in with multi-api support is ready to try out. looks okay from this end so far
![image](https://user-images.githubusercontent.com/1305249/142342688-3e375842-5164-44bb-b0a9-be8085e25c81.png)

**Comment by lusum** [comment]
Api3 and 4 implemented, the bug could be closed?

**Comment by lachlan-00** [comment]
still have to merge edge but i'm going to change my approach for that.

eventual goal is to not need separate classes but for now this is functional
