### ISSUE TITLE
Podcast episodes dashboard javascript

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3064]
Hi all, just a quick observation, when viewing the Podcast Episodes Dashboard, the javascript playbutton popup for each episode currently queues the whole podcast series in your player of choice.

Shouldn't this queue only the single episode selected?

If you want to queue the whole series, you can click on the podcast art or use the text link to view the entire series and select play all from there.

**Comment by lachlan-00** [comment]
had to do it weirdly a little bit in b45b6af22
