### ISSUE TITLE
links in webplayer javascript only support songs

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3065]
Just spotted another podcast issue, clicking on the javascript link of a podcast title currently playing in the webplayer takes you to a song id instead of the podcast id.

![Screenshot from 2021-10-21 19-48-34](https://user-images.githubusercontent.com/3216809/138341139-2039f158-f4ff-487e-bb14-f7a3773257f8.png)

The javascript link is: ``/song.php?action=show_song&song_id=`` 

and should be something like:  ``/podcast_episode.php?action=show&podcast_episode=``

Also, the transcode command recorded in the ampache log for the wav that I think is used to generate the waveform in the player is: ``(Ampache\Module\Playback\Stream) -> ffmpeg -i '/mnt/ampachemusic/MP3Albums/Cat Stevens - Box Set - CD1 - The City/06 - Cat Stevens - The Tramp.mp3' -vn -b:a 320K -c:a pcm_s16le -f wav pipe:1``

So it looks like the waveform displayed is also that of the song id instead of the podcast id.

**Comment by lachlan-00** [comment]
@rsinfotech the waveform code is actually only built for songs so i'll extend that out too now

5.1 is going to make a great podcast release

**Comment by lachlan-00** [comment]
9da7e645e puts that in now. the waveform class would only transcode songs so the waveforms you'd get would not be the podcast_episodes
