### ISSUE TITLE
Podcast dashboard - Newest and Popular heading links

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3074]
Just found two other podcast linking issues on the podcasts dashboard page:

The Newest section heading link is currently ``/stats.php?action=newest#browse_content_podcast_episode`` and resolves to the newest Albums page not newest podcasts.

And the Popular section heading link is ``/stats.php?action=popular`` and also resolve to the popular Albums page instead of podcasts.

**Comment by lachlan-00** [comment]
the stats page used to be pretty simple but there are a lot of types now and shoving them into one page would be a disaster.

it's not not a big job to work on them but not done yet obviously it should be changed into a group per type like all the other pages in the future
