### ISSUE TITLE
API - Develop - stats call - offset greater than zero not returning results

### ISSUE THREAD

**Issue by Andrew-McGee** [ampache/ampache#3082]
## Description
No results from stats API call if I have an offset other than 0.

I'm using the latest develop (8b25a6b91d675617e6fc18382923a4efd592be33).

### To reproduce
Use the stats call like this and results are returned ok:
?action=stats&type=album&limit=24&filter=recent&offset=0

Use like this and I get nothing back:
?action=stats&type=album&limit=24&filter=recent&offset=24

Also nothing returned if I use a different filter such as frequent or newest.

Any ideas? I haven't changed anything in my player and previously it has worked perfectly.

**Comment by lachlan-00** [comment]
Offset was set correctly before but It's probably something php8-related that I've changed.

I spent too much time making php8 work that I must have missed it.

This cycle I need to work on making a script to pull and verify data is returned correctly from the test database so I don't do that again will fix on Monday.

**Comment by Andrew-McGee** [comment]
Thanks mate. I was thinking something similar to get around to write a script to show me what gets returned from the API call rather than the app just borking. :)

**Comment by lachlan-00** [comment]
I've been using https://github.com/lachlan-00/ampache-test to make the doc files for a bit and I can work on a new script to expect returned id's and data for each call as a 'test'

This repo will end up being the base for things like scripts and data so it's reproducible and become the Ampache test-suite (one day)

**Comment by Andrew-McGee** [comment]
Any chance to take a loot at the stats offset @lachlan-00 ?

**Comment by lachlan-00** [comment]
on it now

**Comment by lachlan-00** [comment]
the offset is applied but only on the initial limit. will fix

**Comment by lachlan-00** [comment]
double offsetting and limiting the data. 7d82ad2f9 stops that as the limits are already done by the query

**Comment by mitchray** [comment]
Can I hijack this for a similar issue, for the advanced search JSON I'm seeing weirdness with the offset and limit, where the total number of results will be ```limit``` minus ```offset```

json.server.php?action=advanced_search&type=artist&offset=16&limit=20&operator=and&rule_1=title&rule_1_operator=8&rule_1_input=^c

Will return only 4 results, but a limit of 22 for example will then show 6

**Comment by lachlan-00** [comment]
> Can I hijack this for a similar issue, for the advanced search JSON I'm seeing weirdness with the offset and limit, where the total number of results will be `limit` minus `offset`
> 
> json.server.php?action=advanced_search&type=artist&offset=16&limit=20&operator=and&rule_1=title&rule_1_operator=8&rule_1_input=^c
> 
> Will return only 4 results, but a limit of 22 for example will then show 6

lol, limit minus offset? thats a good one. will hit tomorrow

**Comment by lachlan-00** [comment]
exactly the same issue, another double offset limit.

596000ede sorts that. the code before was doing the offset/limit pulling the items, then doing it again on the results reducing the list again

**Comment by mitchray** [comment]
Bingo! Working as expected now, thanks

**Comment by lachlan-00** [comment]
5.1.1 today i think

**Comment by lachlan-00** [comment]
now that things have calmed down a bit and the software is pretty stable again i'm going to work on support for old api versions

it's going to be fairly simple to update based on handshakes it's just the internals that are going to take time and v3 is i have no idea how possible to support
