### ISSUE TITLE
Zip download issue and request

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#3084]
I have notiCed that now when download a zip it cames with a m3u, but that file is not well formed, so it plays nothing.

This is the contents of the file:

`EL055-Kaleidoscope Deluxe Edition/2-13 Century (Sultan & Ned Shepard R.mp3EL069-Magikal Journey_ The Hits Collecti/1-01 Flight 643.mp3R.Esp188-Lo esencial de rock en tu idiom/1-01 Persiana Americana.mp3`

(all in a single line)

Also I want to know if its posiible that when you download a zip of a playlist the songs can be grouped in one folder (lets say the name of the playlist),

**Comment by lachlan-00** [comment]
playlist i think can be put in a single folder pretty easily based on the type of download.

whatever making the m3u must be a bit of a disaster

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/140669285-d828f942-f4e1-4a81-a6eb-6b1ba2a8d53c.png)

it doesn't seem to do it in a decent way, i'll rewrite the playlist part this week.

The zip function is just combining files based on path so i'll add an option for creating flat zips when download playlists (auto create folder by playlist name)

**Comment by manuelglez86** [comment]
Thank you for the folder part on the zip, it would be useful to have just one folder with the name of the playlist.

I just pointed out the m3u part because in previous versions it wasnt created or at least I dont remember it, so I thought that it was made by you.

I dont know if the m3u is usefull at all, maybe the m3u can be omited? I leave that decision to you.

**Comment by lachlan-00** [comment]
newline added to m3u and the single folder using playlist name are added now.

**Comment by manuelglez86** [comment]
Awesome!! thanks, I´ll continue testing
