### ISSUE TITLE
Fatal Error when Adding Song w/ Seafile catalog

### ISSUE THREAD

**Issue by PlaidPhantom** [ampache/ampache#3085]
### Describe the bug

I'm trying to run an "Add" against a Seafile Catalog. The process is fine until it runs into the first new file; when it tries to add it it gets the error listed below.

Best I can tell, Ampache does not seem to be loading in the catalog's `$this->sort_pattern` and `$this->rename_pattern` properties.  I've verified that they both have values in the database's catalog table.

FWIW I originally wrote the Seafile catalog module: if I need to implement something that's fine; but this worked before, and if I'm doing anything substantially different than the "local" catalog re: these fields I haven't found it yet.

### To reproduce

1. Create a Seafile Catalog
2. Go to the Catalogs page
3. Start an "Add" action
4. Once the add gets to a new item, see it restart. the error will be logged to Apache's logs.

(I imagine no one else has a Seafile installation; if needed I can set up a test user on mine.)

## Environment

* Ampache version: develop, but also ran into this on 5.1.0 and I _think_ 5.0.0
* Web server + version: Apache 2.4.41
* Server operating system: Ubuntu Server 20.04.3
* Client operating system: N/A (seen on both Manjaro and MacOS 11, fwiw)

### Client type

* Web

## Settings

Let me know what might help...

## Logs

in Apache's error.log:
```
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Ampache\\Module\\Util\\UtilityFactory::createVaInfo() must be of the type string, null given, called in /var/www/ampache/src/Module/Catalog/Catalog_Seafile.php on line 384 and defined in /var/www/ampache/src/Module/Util/UtilityFactory.php:57
Stack trace:
#0 /var/www/ampache/src/Module/Catalog/Catalog_Seafile.php(384): Ampache\\Module\\Util\\UtilityFactory->createVaInfo()
#1 /var/www/ampache/src/Module/Catalog/Catalog_Seafile.php(331): Ampache\\Module\\Catalog\\Catalog_Seafile->download_metadata()\n#2 /var/www/ampache/src/Module/Catalog/Catalog_Seafile.php(281): Ampache\\Module\\Catalog\\Catalog_Seafile->insert_song()
#3 /var/www/ampache/src/Module/Catalog/SeafileAdapter.php(267): Ampache\\Module\\Catalog\\Catalog_Seafile->Ampache\\Module\\Catalog\\{closure}()
#4 /var/www/ampache/src/Module/Catalog/SeafileAdapter.php(265): Ampache\\Module\\Catalog\\SeafileAdapter->for_all_files()
#5 /var/www/ampache/src/Module/Catalog/SeafileAdapter.php(265): Ampache\\Module\\Catalog\\SeafileAdapter->for_all_fi in /var/www/ampache/src/Module/Util/UtilityFactory.php on line 57, referer: https://home.plaidphantom.net/ampache/index.php
```

**Comment by lachlan-00** [comment]
should be easy enough to find, it would be the catalog module that's the issue.

i've never actually set up seafile before so i should make a tester for this. is there anything extra you'd like the catalog to do or be capable of?

**Comment by PlaidPhantom** [comment]
I don't have anything specific to add; all I'm after right now is basic functionality (add/update/clean). Let me know if there's anything I can do to help!

**Comment by lachlan-00** [comment]
no probs, i'm adding a catalog for it today

**Comment by lachlan-00** [comment]
few things i've noticed so far

ssl seems to be forcibly enabled?
```
Could not add song "Vivaldi Double Cello Concerto Mvt 1 - Tina Guo.mp3": cURL error 60: SSL: no alternative certificate subject name matches target host name '192.168.1.12' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
so i set ignore ssl, etc to get past that
![image](https://user-images.githubusercontent.com/1305249/140853544-bc118dc7-187e-40a2-b1ef-5fd26ac71c77.png)

but then it doesn't seem to include my local port for the urls
```
Downloading partial song The Swan - Tina Guo.mp3
2021-11-09T13:49:57+11:00 [admin] (seafile_catalog) -> Could not add song "The Swan - Tina Guo.mp3": Client error: `GET http://192.168.1.12/seafhttp/files/310afb15-50a9-41f2-b0a9-db1de4f132f2/The%20Swan%20-%20Tina%20Guo.mp3` resulted in a `404 Not Found` response:
```

the UI is missing the name for the catalog too by the looks.
![image](https://user-images.githubusercontent.com/1305249/140853625-fc99e8ea-ad50-4e1b-bc93-8f7ae1b1c2c5.png)

will look at the vainfo parts now

**Comment by lachlan-00** [comment]
it's actually not filling in any of the catalog data either. something is very up
![image](https://user-images.githubusercontent.com/1305249/140856248-88ac2c4e-0202-4d22-b25a-61638c6ba831.png)

**Comment by lachlan-00** [comment]
this is what's causing your error as the content isn't getting filled from the DB

**Comment by lachlan-00** [comment]
a2e6cf97c fixes the parameters, might fix some other things

**Comment by PlaidPhantom** [comment]
Ah, awesome. I guess i assumed that was happening automatically somewhere. I'll test it out and let you know.

I'm thinking it'd be good to make "ignore cert failures" an additional option. I can work on a PR for that; might need some guidance on the database migration side, though. Not sure what would be up with the ignored port assignment.

**Comment by PlaidPhantom** [comment]
I can confirm that that does fix my issue! My new albums play perfectly, and all that missing info is showing up for me now.

Thanks for the help!
