### ISSUE TITLE
Album and artist art from folder found but not inserted into the database

### ISSUE THREAD

**Issue by krm3** [ampache/ampache#3086]
### Description of the bug
I have a folder for each album and in each folder there is a file cover.jpg. I configured apache to read album and artist art from folder and to use cover.jpg as filename. The file is found, but not inserted into the database because of invalid data als log file is stating.

Config:
``` 
art_order = "folder"
album_art_preferred_filename = "cover.jpg"
artist_art_preferred_filename = "cover.jpg"
```

Log example:
``` 
2021-11-07T21:57:09+01:00 [] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening /music/The Sunpilots - King Of The Sugarcoated Tongues and checking for album Art
2021-11-07T21:57:09+01:00 [] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Found preferred image file: cover.jpg
2021-11-07T21:57:09+01:00 [] (Ampache\Repository\Model\Art) -> Not inserting image for album 1, invalid data passed
```
It's the same for artist Art.

cover.jpg example file from the log above:
/music/The Sunpilots - King Of The Sugarcoated Tongues/cover.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 75x75, segment length 16, baseline, precision 8, 300x266, components 3

As I know my cover.jpg files are okay, I commented out the following lines in

src/Repository/Model/Art.php

```
336 //        if (!self::test_image($source)) { 
337 //            debug_event(self::class, 'Not inserting image for ' . $this->type . ' ' . $this->uid . ', invalid data passed', 1); 
338 // 
339 //            return false; 
340 //        }
```
Then it works - images are inserted into the database - and images are also shown in web client and subsonic client.

Don't know what definition of not okay matches for my cover.jpg files such that test_image fails.

## Environment
* Ampache version: 5.1.0
* Web server + version: nginx 1.18.0
* Server operating system: Debian 11

**Comment by lachlan-00** [comment]
on `/test.php` do you see the php-gd extension installed?
![image](https://user-images.githubusercontent.com/1305249/140868453-f2d9fedf-3ddd-43b3-a3d2-83fd23f4852b.png)

If you don't have it installed it might be falling through in the logic and thinking it failed. I'm thinking it has because you on't get the failed debug.

It's not mandatory so it should not fail the test if it's not there.

**Comment by krm3** [comment]
Thanks, you are right. It works if I have PHP GD extension installed. But then it should be mandatory.

**Comment by lachlan-00** [comment]
good to know, i'll bypass that check if not installed as it's a bit stupid to make it mandatory and not tell you

**Comment by lachlan-00** [comment]
5ae9c65bb sets a bypass, it looks like that's the only area where it does fail if missing.

you can keep the module uninstalled or keep your comment in the field and it should work either way

**Comment by lachlan-00** [comment]
i've updated the wiki install page and the fix is in so i think this should be good now and this will go into the next release.
