### ISSUE TITLE
Make user names in playlist names optional

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#3097]
Hi,

Currently, when playlists are listed (either in the web UI or through XML API), the creator user's name is appended to the name of each public playlist, if it isn't the current user. I think this can be incommodious and confusing. Also, it can make the screen look crowded on mobile clients when the screen is small in physical size.

Please create an option to turn this off.

Thank you

**Comment by lachlan-00** [comment]
will do

**Comment by 4phun** [comment]
Thank you

**Comment by lachlan-00** [comment]
set now. options -> interface under browse
![image](https://user-images.githubusercontent.com/1305249/143157989-2eb6a6dc-b1e5-424c-8a69-33cf0a6e076e.png)

**Comment by 4phun** [comment]
Cool!

**Comment by lachlan-00** [comment]
@4phun i'm also going to work on a 'hidden' type (public/private/hidden) to hide from outside the gui in areas like the api and subsonic

**Comment by 4phun** [comment]
@lachlan-00 That's a great idea! And then hidden playlists can be used as filters in a public smart playlist? Like selecting the "Playlist" or "Smart Playlist" rule.

**Comment by lachlan-00** [comment]
I've tried a couple of ways yesterday but i didn't really like them

* as a type (public/private/hidden)
* as a separate value (e.g. playlist->is_hidden)

I think it might be better to allow a string match like you set in amproid.
`api_hide_playlist_starts_with = "Hide playlists from subsonic and API requests that start with the following string"`

so then a user can say "hide all the lists that start with 'builder' when i'm in the api" (optional switch to show)

**Comment by lachlan-00** [comment]
i'm going to try that out today and backport to api4 as well if it works okay and i put it in

**Comment by lachlan-00** [comment]
set with 263638a4d (and e3573be73) now a per user option to hide any playlist they don't want to see

**Comment by 4phun** [comment]
Cool! Great stuff man.
