### ISSUE TITLE
I already mentioned the problem once

### ISSUE THREAD

**Issue by Churic63** [ampache/ampache#3104]
## Environment

* Ampache version:
* Web server + version:
* Server operating system:
* Client operating system:

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by mitchray** [comment]
Closing due to no details?

**Comment by Churic63** [comment]
NO DETAILS?  HOW ELSE DO I TELL YOU THAT IT DOES NOT LET ME CREATE A ADMIN ACCOUNT.  ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Churic63** [comment]
For the 5-7 or even more years I have worked with this script, I am now done.  It was a good run.  There are now other options…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by lachlan-00** [comment]
Feel free to add at least some pictures of the process to #3077  as it's a not going to have any log information.

Might have some errors from things that have been reverted in 5.2.0-develop as well depending on your server setup
