### ISSUE TITLE
ampache.com DNS is not setup correctly

### ISSUE THREAD

**Issue by RyanCopley** [ampache/ampache#3106]
### Describe the bug
When I navigate to ampache.com in the browser, I get a github pages error.

### To reproduce

1. Go to 'http://ampache.com/'

### Expected behavior

See ampache homepage

### Screenshots

<img width="751" alt="Screen Shot 2021-12-02 at 4 56 42 PM" src="https://user-images.githubusercontent.com/819591/144521581-efe50fb1-6602-494c-aba7-d6d11f0c546e.png">

**Comment by vollmerk** [comment]
Let me know if this is something I need to correct! :D

**Comment by lachlan-00** [comment]
> Let me know if this is something I need to correct! :D

the repo page is set to ampache.org. should the .com be a cname for .org instead?
![image](https://user-images.githubusercontent.com/1305249/144526470-a65aa4d8-fe71-43ae-8126-10cfb6a51bc5.png)

It seems like that error says "i went to github pages but there isn't a pages site set up for ampache.com"

**Comment by vollmerk** [comment]
Hmm, doesn't look like that'll fix it 


<html>
<body>


Host name | Type | TTL | Data
-- | -- | -- | --
ampache.com | A | 1 hour | 185.199.108.153185.199.109.153185.199.110.153185.199.111.153
www.ampache.com | CNAME | 1 hour | ampache.org.


</body>
</html>

Is the current DNS for ampache.com - note that `www.ampache.com` is already a CNAME and doesn't work. Is there a way to add a second domain to page...  But Google Domains has URL forwarding so I just changed it to that
```
Forward to
http://ampache.org
From
ampache.com
www.ampache.com
Redirect type
Permanent redirect (301)
Path forwarding
Forward path
SSL
On
```

**Comment by vollmerk** [comment]
Give it a bit to propagate and I think this'll be fixed :)

**Comment by RyanCopley** [comment]
I think ampache.com is successfully hitting github, however their load balancer does a lookup of domain name to which GH pages page to link to. I'm not 100% sure how to fix that, but setting up a second gh pages with a redirect to .org would work

**Comment by RyanCopley** [comment]
Ahh cache just busted for me, looks like the redirect is working :)
