### ISSUE TITLE
Pictures of albums are very small

### ISSUE THREAD

**Issue by bacinet02** [ampache/ampache#3110]
## Description
Hello.
I have installed ampache 5.1.1 and added my local collection. This collection has a file "folder.jpg" in each album folder.
But, after many tests, these pictures are ignored. Ampache has created pictures of 34x34 size for each album. The result isn't very nice!

I have 2 questions:
1. How to remove current album art images?
2. How to use my own folder.jpg?

Thanks for your help
:-)

### Screenshots

![album](https://user-images.githubusercontent.com/5860039/144639590-7aa6c8c3-1938-4c86-b385-57b2bfbd0e77.png)

## Environment

* Ampache version: 5.1.1
* Web server + version: apache 2.4.41
* Server operating system: Ubuntu 20.04
* Client operating system: Ubuntu and Android

### Client type

* Web
* Ampache
* SubSonic

## Settings
; Album Art Preferred Filename
; Specify a filename to look for if you always give the same filename
; i.e. "folder.jpg" Ampache currently only supports jpg/gif and png
; Especially useful if you have a front and a back image in a folder
; comment out if Ampache should search for any jpg, gif or png
; DEFAULT: folder.jpg
;album_art_preferred_filename = "folder.jpg"

; Artist Art Preferred Filename
; Specify a filename to look for artist specific art, either in the
; same folder as your files or in the parent folder
; e.g. /mnt/music/Artist/Album/artist.jpg
;      /mnt/music/Artist/artist.jpg
; DEFAULT: folder.jpg
;artist_art_preferred_filename = "folder.jpg"

; Artist Art Dump Folder
; Specify a local folder to search for art using name/title to identify
; i.e. "/var/www/art/" is filled with artist images named by artist
; e.g. "Megadeth.jpg", "Judas Priest.png", "The Smashing Pumpkins.jpg"
; When enabled; gather_folder will check this folder for artist images
; DEFAULT: "false"
;artist_art_folder = "/home/html/ampache/art"

; Album Art Store on Disk
; This defines if arts should be stored on disk instead of database.
; DEFAULT: "false"
;album_art_store_disk = "true"

; Local Metadata Directory
; This define a local metadata directory with write access where to store
; heavy data if enabled (album arts, ...)
; DEFAULT: none
local_metadata_dir = "/home/html/ampache/metadata"

; Maximal upload size
; Specify the maximal allowed upload size for images, in bytes.
; DEFAULT: 1048576
;max_upload_size = 1048576

; Album Art Minimum Width
; Specify the minimum width for arts (in pixel).
; DEFAULT: none
album_art_min_width = 128

; Album Art Maximum Width
; Specify the maximum width for arts (in pixel).
; DEFAULT: none
album_art_max_width = 1024

; Album Art Minimum Height
; Specify the minimum height for arts (in pixel).
; DEFAULT: none
album_art_min_height = 128

; Album Art Maximum Height
; Specify the maximum height for arts (in pixel).
; DEFAULT: none
album_art_max_height = 1024

**Comment by lusum** [comment]
>Ampache has created pictures of 34x34 size for each album. 

Are you sure to not have 34x34 images in your folder or embedded in your files?

>1) How to remove current album art images?

You have to log as admin or add your user as catalog manager. The commands appear on the bottom of the image.

>2) How to use my own folder.jpg?

Same as above

**Comment by bacinet02** [comment]
Hello.
No. All my cover pictures have a good resolution.

And I don't want to change cover by cover. I have too many albums.

Thanks for answers

**Comment by mitchray** [comment]
You can clear the existing art from the database by temporarily setting the minimums to 9999 and running the ```cleanup:art``` command

https://github.com/ampache/ampache/wiki/cli-faq 

Then reset back to your desired minimums and Gather Art from the catalogs settings page

**Comment by bacinet02** [comment]
Ok.
I have reinstalled ampache with a new DB. And now, it seems ok.
Thanks!
