### ISSUE TITLE
Web installer fails to initialise database

### ISSUE THREAD

**Issue by Mysgym** [ampache/ampache#3111]
### Describe the bug
 On step 1 of the installation progress, I get the following error : 
`Unable to create the user "ampache" with permissions to "ampache" on "localhost": ["HY000",1396,"Operation CREATE USER failed for 'ampache'@'localhost'"]`
  Trying again lets me through without an error yet ampache asks for updates and links to the debug page with one error : 
`
Database tables : ERROR
This checks a few key tables to make sure that the Ampache database exists, and the user has access to the database
`

## Environment

* Ampache version: 5.1.1
* Web server + version: Apache2
* Server operating system: raspbian lite

I'm a complete mysql noob and simply followed the install guide from the wiki.

## LOGS
I can't seem to find any logs on the installation process.

Here is the only (hopefully) interesting thing I've managed to find in mysql : 
```
MariaDB [ampache]> SHOW TABLES;
Empty set (0.001 sec)
```

**Comment by lusum** [comment]
Same as #3077

**Comment by Mysgym** [comment]
> Same as #3077

My bad ! Closing this issue and moving to #3077
