### ISSUE TITLE
5.1.1  Update failure.

### ISSUE THREAD

**Issue by AndKe** [ampache/ampache#3118]
## Description

I renamed my /var/www/ampache to ampache_old
unzipped the new one to /var/www/ampache,  set group/owner , installed php7.4-intl and so on.

### Describe the bug
the I see a "Warning The root Ampache folder has changed to ./public"

when I click it, I am at http://192.168.1.20/public/update.php and see:
![2021-12-13 13 20 59 192 168 1 20 7aa79f76310f](https://user-images.githubusercontent.com/1468842/145812434-6700a587-52c6-4b54-b3f5-d385a970ac55.png)

When I click "update now"  the browser fails (404) while trying to request "http://192.168.1.20/update.php?action=update"

- because there is no "/public/" in the path it tries.

How can I fix this ? - is if safe to just run "http://192.168.1.20/public/update.php?action=update"  ?  - that could have a chance.

### To reproduce
upgrade from 4.1.1(or newer?) to 5.1.1   

### Expected behavior
I would expect the update button to point to "public/update.php"

### Screenshots
attached.

## Environment

* Ampache version:  5.1.1
* Web server + version:  apache 2, current release
* Server operating system: Ubuntu 20.04
* Client operating system: n/a

### Client type

n/a

## Settings

nothing special
## Logs

I do not think logs will help much here.

**Comment by AndKe** [comment]
Solution was to add "/public" to DocumentRoot /var/www/ampache/public
you may want to handle this error.

**Comment by lusum** [comment]
You can find all you can need to do here: https://github.com/ampache/ampache/wiki/Ampache-next-Changes
