### ISSUE TITLE
Setup Fails newest release

### ISSUE THREAD

**Issue by jamesc2151** [ampache/ampache#3129]
new release fresh install of ampache-5.2.0_all.zip
Major issue found

USER table and admin user not created during install.

clipping and running manual SQL command "
________________________________________________________________________________________________________________________________________-
CREATE TABLE IF NOT EXISTS `user` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `fullname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `email` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `website` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `apikey` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `password` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `access` tinyint(4) UNSIGNED NOT NULL,  `disabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,  `last_seen` int(11) UNSIGNED NOT NULL DEFAULT 0,  `create_date` int(11) UNSIGNED DEFAULT NULL,  `validation` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `state` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `city` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `fullname_public` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,  `rsstoken` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  PRIMARY KEY (`id`),  UNIQUE KEY `username` (`username`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
___________________________________________________________________________________________________________________________________-
resulted in message #1071 - Specified key was too long; max key length is 767 bytes

******* Changing  **username` varchar(255) to username` varchar(128)** corrected error but gave new one in setup*******

Database select failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ampache.session' doesn't exist

correcting

 CREATE TABLE IF NOT EXISTS `session` (
  `id` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
 
to 
CREATE TABLE IF NOT EXISTS `session` (
  **`id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,**

allowed setup to properly finish

**Comment by mitchray** [comment]
Can you give more details on your environment and steps taken to install, I'm able to successfully clean install on Windows with Wampserver from that zip

**Comment by jamesc2151** [comment]
sure .

Web server running web sites and holds local files.
 NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buste
ID_LIKE=debian
Apache version 2.4.38
PHP 8.0

Don't think it's a PHP error as I clipped the user and session segments
from the SQL file included in the zip and executed it directly to Mysql
command on that server

Second server runs the SQL database shared with osmc Kodi host. No files
storage
NAME="OSMC"
VERSION="November 2020"
VERSION_ID="2020.11-1"
ID=osmc
ID_LIKE=debian
MariaDB/MySQL 10.1
 This same setup has run all the dev versions to 5.08 then I switched back
to using the install and production versions with no problems saved old DB
which shows it at version 50015 which was the last time I ran a dev version
before I renamed it and let setup build a new database.

hope this helps let me know if you want a test of changes with a fresh
run.. I do not use composer to do the installs but I did let composer
update the first time the install crashed which gave me a system that did
the same thing.. Couldn't install a running version till I made the changes
to 128 on the included SQL file. I am by no means an SQL guys but I can
move around in it a bit..

James

**Comment by jamesc2151** [comment]
found two more tables missing same problem   tag and session_remember

**Comment by izyspania** [comment]
you should take a look at: https://github.com/ampache/ampache/issues/3077

**Comment by jamesc2151** [comment]
this is not the user I have the issues with.. They are referring to the Database admin user .   I'm referring to the internal admin user once server  is up and running

**Comment by jamesc2151** [comment]
Adding the following to /etc/mysql/mariadb.conf.d/50-server.cnf file fixed the issue:

[mysqld]
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda

You may close this with above fix
