### ISSUE TITLE
Cache error when caching not enabled

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#3137]
### Describe the bug

I do not have any caching other than memory cache enabled but I am getting the error about catalog cache.
## Environment

* Ampache version: 60e5a6bd3cacf678326ae6a118dfc60f97712382

## Settings

; This helps avoid waiting for transcodes to finish and makes
; files immediately available to the client.

; Path to your cache folder.
; This is where the pre-transcoded files will be stored
; DEFAULT: none
;cache_path = "/tmp"

; Default audio output format
; DEFAULT: none
;cache_target = "mp3"

; Look in your local catalogs for these file extensions and pre-cache to the
; 'cache_path'. This could be helpful to reduce space needed on your
; web server or to make sure that clients get files quickly.
; Execute "php bin/cli run:cacheProcess" to process these files.
; DEFAULT: "false"
;cache_m4a = "true"
;cache_flac = "true"
;cache_mpc = "true"
;cache_ogg = "true"
;cache_oga = "true"
;cache_opus = "true"
;cache_wav = "true"
;cache_wma = "true"
;cache_aif = "true"
;cache_aiff = "true"
;cache_ape = "true"
;cache_shn = "true"
;cache_mp3 = "true"

; REMOTE CATALOGS ONLY
; Enabling cache_remote on remote catalogs will cache every file on the remote server
; DEFAULT: "false"
;cache_remote = "true"

## Logs

2022-01-05T17:48:54-05:00 [admin] (Ampache\Repository\Model\Catalog) -> Check your cache_path and cache_target settings

**Comment by lachlan-00** [comment]
after playing a track maybe? i'll look at ignoring/stopping that

**Comment by lachlan-00** [comment]
yup a play action looks up the cache path.

we don't care about that so stopp telling you all the time with f5ba98d97
