### ISSUE TITLE
Translation strings missing

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#3139]
cant find this string on transifex:

**_Hide smartlists that match playlist names in Subsonic and API clients_**

can you confirm this?

I will leave this open in case I find more

thanks.

**Comment by lachlan-00** [comment]
i didn't add it to the translate list so added with 780a0d1ea.

Have to make sure i not that when adding database options.

I think transifex will sync that automatically but if not @Psy-Virus will when he does another translation sync

**Comment by Psy-Virus** [comment]
maybe we should run ```./gather-messages -a``` on each Merge. That would update the messages.pot and Transifex would pull it automatically some hours later.

Idk what Travis is able to do, but ```gettext``` needs to be installed for this to work

**Comment by lachlan-00** [comment]
I'll set it up with a pre-commit hook i think just found some extra strings in there too
