### ISSUE TITLE
Ampache unable to scrobble to Last.fm, call to member function format() on null is cause

### ISSUE THREAD

**Issue by MochaMage** [ampache/ampache#3140]
# Issue Template

## Description

When using the Subsonic API (In my case, DSub is the client application) and DSub attemps to call the /rest/scrobble endpoint, a 500 status code is seeing in the lighttpd logs. The Ampache logs show the cause is that the format() method is trying to be called on a null object.

**To reproduce**
1. Configure Ampache to scrobble to last.fm
2. Configure DSub to scrobble
3. Set DSub to offline mode, listen to a song, then set back to online mode. DSub will then try to scrobble all cached listens.
4. Scrobbles will fail, ampache logging will show format() being called on null object.

**Expected behavior**

Scrobble calls to return 200 status code

## Environment

* Ampache version: 5.2.0
* Web server + version: Lighttpd 1.4.59
* Server operating system: DietPi 7.9.3
* Client operating system: Android 12

**Client type:**

Subsonic

## Logs

#Lighttpd Log #
[08/Jan/2022:22:13:22 +0000] "GET /ampache/rest/scrobble.view?u=admin&p=enc:70696d75736963&v=1.2.0&c=DSub&id=4086&submission=true&time=1640715618284 HTTP/1.1" 500 0 "-" "DSub"

# Ampache Log #
`2022-01-08 22:13:42: mod_fastcgi.c.487) FastCGI-stderr:PHP message: PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /var/www/ampache/src/Module/Api/Subsonic_Api.php:2076
2022-01-08 22:13:42: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2022-01-08 22:13:42: mod_fastcgi.c.487) FastCGI-stderr:#0 [internal function]: Ampache\Module\Api\Subsonic_Api::scrobble()
2022-01-08 22:13:42: mod_fastcgi.c.487) FastCGI-stderr:#1 /var/www/ampache/src/Module/Api/SubsonicApiApplication.php(208): call_user_func()
2022-01-08 22:13:42: mod_fastcgi.c.487) FastCGI-stderr:#2 /var/www/ampache/public/rest/index.php(35): Ampache\Module\Api\SubsonicApiApplication->run()`

**Comment by lachlan-00** [comment]
i can see something weird, the object you're trying to scrobble has a really low id number (4086)

in ampache's subsonic the id should be much higher
![image](https://user-images.githubusercontent.com/1305249/148712472-faddff36-5006-41bd-8a1a-c054836b3901.png)

is this id number the id of the song in ampache?
e.g. `song.php?action=show_song&song_id=4086`

**Comment by lachlan-00** [comment]
also thank you for making a very clear issue. :+1:

**Comment by lachlan-00** [comment]
while i wait for that it might be calling the scrobble function from another part of the API so i'll just double check i'm not sending the wrong id some other way

**Comment by MochaMage** [comment]
Sorry about the silence, I didn't get a notification about a reply. I'll test out scrobbling once more. My guess from what I remember is that that ID field is indeed for a song because I remember seeing multiple scrobble calls being made by DSub and if I'm right, the number of scrobble calls matched the number of songs it was trying to scrobble. Does the Web UI use a different way of scrobbling? The scrobbles from there are working perfectly fine but not with DSub

**Comment by MochaMage** [comment]
Did a little bit of testing with that song_id that failed, it is not showing up in my UI. So I'm a bit lost as to what DSub is sending back as a song ID. I'm going to compare what DSub sends back as a song ID and what ID the same song has on the web UI.

**Comment by MochaMage** [comment]
ok this may be a void issue because I just performed the following: Installed DSub on another device that never had it and linked it to Ampache. Works perfectly fine and scrobbling is working there. However, going back to my phone, where I originally saw the problem, I get the issue. _However_, this only happens if I try playing a song that was already cached on my phone that happened to be put there from another Subsonic server. So this is a DSub issue because it is trying to use an Airsonic ID with Ampache. I'll close this out now that I know the problem doesn't lie in Ampache.
