### ISSUE TITLE
"Details" text when showing song details can be confused with the song title

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3153]
## Description
 When clicking on a song to show the details, the new page shown has the title of the song following immediately by the word "Details". However that word can easily be confused with the title. Like in this screenshot:
![ampache_details](https://user-images.githubusercontent.com/17937361/152700542-0856de5f-4e27-42a1-b7c8-1e303af2629b.png)

Also, I think that the word "Details" doesn't really convey any information. On top of that, in some languages the word "Details" should be at the start of the sentence (in Spanish for instance should be "Detalles de ....").

### To reproduce

1. Click on any song

## Environment

* Ampache version: 5.2.0

### Client type

* Web

**Comment by lachlan-00** [comment]
it is annoying, i'm going to remove it as it's not adding any detail to the string

**Comment by lachlan-00** [comment]
removed in 032dc8b1d. it's also removed from video and live stream. 5.2.1 will be out soon and this will work its way back to develop

**Comment by cquike** [comment]
Thanks!
