### ISSUE TITLE
How to revert artist art gather?

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#3160]
In older versions of ampache, unfortunately i cant find when exactly, album art was gathered from folder and artist art from google then auto-cropped and saved in the most possible smallest size, which that was awesome in so many ways.

For music's sake!! i can't find something in the config that could make it work that way again.

Any help is much appreciated!

**Comment by mitchray** [comment]
Spotify has replaced Google images as the primary source of album art and artist images

[Create an API key with Spotify](https://developer.spotify.com/dashboard) and add it to your Ampache config file under ```spotify_client_id``` and ```spotify_client_secret```

Also make sure spotify is listed as a source in ```art_order```

**Comment by PsyZeus** [comment]
Thanks @mitchray for the workaround, tho i decided to delete all artist art from db.
From now on i only keep album art, i listen electronic music so i already have 8000+ artists and that lists grows really big by each year.
I try to keep my db size as small as possible no need to have a db of 50GB pictures in a few years Lol
Artists art seemed unnecessary to me in the end as like as having high resolution album arts(covers), so except from deleting all artist art i now add a 500x500 cover instead of the original inside the folders.

All the above is the reason i asked
https://github.com/ampache/ampache/issues/3176
all i hope is, its not too much work to add! :)
