### ISSUE TITLE
Podcast documentation incorrect / missing .inc files

### ISSUE THREAD

**Issue by drder66** [ampache/ampache#3167]
The documentation for podcasts https://github.com/ampache/ampache/wiki/Podcasts mentions some steps in automatic podcast updates, e.g. sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -n podcasts -a -g -i

however in 5.2.1 /var/www/ampache/bin/catalog_update.inc (or any of the previous .inc files) seem to have been removed.

I assume there is some way to do the catalog update from the command line, so it would appear that the documentation might need updating. Either that or the .inc files replacing.

**Comment by lachlan-00** [comment]
you're right it's out of date

Use the cli command instead
```
php /var/www/ampache/bin/cli run:updateCatalog podcasts -a
```

**Comment by drder66** [comment]
Fixed. Thanks!

**Comment by drder66** [comment]
thanks!
