### ISSUE TITLE
Changing artist name from recommendation screen causes DB to hang

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#3174]
## Description
When changing an artist name from the screen that displays the "similar artists" screen, it causes a few queries to run that hang the DB

### Describe the bug
When I changed the artist name in the Ampache web interface, which happened to have "similar artists" underneath, the entire system stopped. I ran show processlist; on mysql, and it shows the same query run over and over again: UPDATE IGNORE `recommendation_item` SET `recommendation_id` = '45028' WHERE `recommendation_id` = '4

**Comment by lachlan-00** [comment]
oh, thank you for finding this one, i didn't notice it at first but it's really annoying

will fix up tomorrow after work

**Comment by lachlan-00** [comment]
it's actually the length of time to run through all the change updates. it took a full minute to update for me. i'm going to work on speeding that up

**Comment by lachlan-00** [comment]
i think this should be ok now. the new release should be much closer to instant as it's not migrating the entire play history for an object and it deletes recommendations instead of migrating which was the slowest part

**Comment by lusum** [comment]
I have tested this bug and it seems fixed
