### ISSUE TITLE
Updating file tags after removing custom metadata field does not remove the field from Ampache

### ISSUE THREAD

**Issue by hell001** [ampache/ampache#3185]
### Describe the bug
Updating file tags after removing custom metadata field does not remove the field from Ampache

### To reproduce

1. Add a custom metadata field in your tagging program 
2. Update file tags in your catalog and observe the new field in the "more metadata" section. 
3. Remove the custom metadata field in your tagging program. 
4. Notice that the custom metadata field is **still present** int he "more metadata" section

### Expected behavior
The custom metadata field should be gone after updating the tags

## Environment

* Ampache version: 5.1.1

**Comment by lachlan-00** [comment]
i'll look now

**Comment by lachlan-00** [comment]
it does look like it only updates.
![image](https://user-images.githubusercontent.com/1305249/156067508-c49c143d-c2b6-4a92-aeac-b0f0b327aeac.png)

**Comment by lachlan-00** [comment]
37b20a2f5 sets a delete when not found on tag update
![image](https://user-images.githubusercontent.com/1305249/156097621-f3a8d8a4-7f17-476e-aa73-357cf2a2f611.png)
