### ISSUE TITLE
Browse by Original Year for albums no longer working

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3186]
Don't know if this is happening to others and don't know when it stopped working but the 'Browse by Original Year for albums' setting seems to have stopped working recently despite being set to 'on' in the Server Config - Interface section.

Albums are being listed randomly and the Release Year (in brackets at the end of the album name) is duplicated in the Year column instead of being the Original Year:

![image](https://user-images.githubusercontent.com/3216809/156026152-04eb7ad0-0c29-433d-97cd-95ddbee50648.png)

I'm on the latest develop commit: c586ecb9d

**Comment by mitchray** [comment]
I'll look into that, might be an issue with recent template updates

**Comment by mitchray** [comment]
Should be fixed with #3187

**Comment by lachlan-00** [comment]
merged

**Comment by rsinfotech** [comment]
Great work @mitchray, all back to normal, thanks for the rapid response and thanks for the super quick merge @lachlan-00
