### ISSUE TITLE
MySQL query errors during cron process

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3189]
Hi all, I'm getting the following database query errors since the latest develop commit (37b20a2f5) during every cron run:
```
(Ampache\Module\System\Dba) -> Error_query SQL: DELETE FROM `recommendation` WHERE `last_update` < ? OR ((`object_type` = 'song' AND `rel` IS NOT NULL AND `object_id` NOT IN (SELECT `id` from `song`)) OR (`object_type` = 'artist' AND `rel` IS NULL AND `object_id` NOT IN (SELECT `id` from `artist`)) OR (`object_type` = 'album' AND `object_id` NOT IN (SELECT `id` from `album`)))
(Ampache\Module\System\Dba) -> Error_query MSG: ["42S22",1054,"Unknown column 'rel' in 'where clause'"]
```
Not causing any problems other than the above errors in the logs, just thought I should report.

**Comment by lachlan-00** [comment]
@rsinfotech does this query work for you? (just checking mysql specifics for artist_mapping and i want to insert missing rows)

```
INSERT INTO `object_count` (object_type, object_id, `date`, `user`, agent, geo_latitude, geo_longitude, geo_name, count_type)
SELECT 'album', `song`.`album`, `object_count`.`date`, `object_count`.`user`, `object_count`.`agent`, `object_count`.`geo_latitude`, `object_count`.`geo_longitude`, `object_count`.`geo_name`, `object_count`.`count_type`
FROM `object_count`
LEFT JOIN `song` ON `object_count`.`object_type` = 'song' AND `object_count`.`count_type` = 'stream' AND `object_count`.`object_id` = `song`.`id`
LEFT JOIN `object_count` AS `album_count` ON `album_count`.`object_type` = 'album' AND `object_count`.`date` = `album_count`.`date` AND `object_count`.`user` = `album_count`.`user` AND `object_count`.`agent` = `album_count`.`agent` AND `object_count`.`count_type` = `album_count`.`count_type`
WHERE `object_count`.`count_type` = 'stream' AND `object_count`.`object_type` = 'song' AND `album_count`.`id` IS NULL;
```

**Comment by rsinfotech** [comment]
Hi @lachlan-00 running that query directly in phpmyadmin resulted in the following message and no errors:
```
258 rows inserted.
Inserted row id: 128721 (Query took 0.8647 seconds.) 
```
So it looks like it does work for me?

**Comment by lachlan-00** [comment]
> Hi @lachlan-00 running that query directly in phpmyadmin resulted in the following message and no errors:
> ```
> 258 rows inserted.
> Inserted row id: 128721 (Query took 0.8647 seconds.) 
> ```
> So it looks like it does work for me?

Awesome. That's exactly what I wanted to hear.
Must just be delete actions that mysql doesn't like selecting from itself. 😀

**Comment by rsinfotech** [comment]
Hi @lachlan-00, I'm seeing a couple of MySQL query errors again since the last big commit for album and artist mapping:
```
(Ampache\Module\System\Dba) -> Error_query SQL: DELETE FROM `album_map` WHERE `album_map`.`album_id` IN (SELECT DISTINCT `album_map`.`album_id` FROM `album_map` LEFT JOIN `artist_map` ON `artist_map`.`object_type` = `album_map`.`object_type` AND `artist_map`.`artist_id` = `album_map`.`object_id` AND `artist_map`.`object_id` = `album_map`.`album_id` WHERE `artist_map`.`artist_id` IS NULL AND `album_map`.`object_type` = 'album');
(Ampache\Module\System\Dba) -> Error_query MSG: ["HY000",1093,"You can't specify target table 'album_map' for update in FROM clause"]
```
```
(Ampache\Module\System\Dba) -> Error_query SQL: DELETE FROM `artist` WHERE `id` IN (SELECT `id` FROM `artist` LEFT JOIN (SELECT DISTINCT `song`.`artist` AS `artist_id` FROM `song` UNION SELECT DISTINCT `album`.`album_artist` AS `artist_id` FROM `album` UNION SELECT DISTINCT `wanted`.`artist` AS `artist_id` FROM `wanted` UNION SELECT DISTINCT `clip`.`artist` AS `artist_id` FROM `clip` UNION SELECT DISTINCT `artist_id` FROM `artist_map`) AS `artist_map` ON `artist_map`.`artist_id` = `artist`.`id` WHERE `artist_map`.`artist_id` IS NULL);
(Ampache\Module\System\Dba) -> Error_query MSG: ["HY000",1093,"You can't specify target table 'artist' for update in FROM clause"]
```
Again, not causing any operational issues and the new tables were created and populated correctly during the update, although the new tables are of the type MyISAM while all the rest of the tables are InnoDB, is this correct?

Loving the update though as it now looks like multiple artists and collaborations on a single album are now both listed separately instead of the second artist being ignored and stripped out. :+1: A major leap forward!

**Comment by rsinfotech** [comment]
Update: These errors have stopped since this mornings update to fc04621ea

Great work, apologies for the noise.

**Comment by lachlan-00** [comment]
found a lot after merging to the demo sites but i think function is all working correctly now.
there is also a lot of repair checking done after catalog updates which should pick up anything missing and insert the missing data.

thanks for reporting these things. sometimes i miss them even while watching logs.
