### ISSUE TITLE
advanced_search offset not working with limit of 0

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#3192]
## Description
When firing off an advanced_search function in the api, if I leave limit set at 0 (the default), then offset will be ignored.

### Describe the bug
I'm trying to perform a search of items in chunks of 5000. In previous versions of the API, I was able to set the offset at multiples of 5000, and it would cap the results automatically. Now, it will return the first 5000 records over and over again unless I set the limit to 5000.

### To reproduce
http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=0&limit=0&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=5000&limit=0&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=10000&limit=0&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
all return the same records

but

http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=0&limit=5000&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=5000&limit=5000&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
http://ampache.xxx:5006/server/xml.server.php?action=advanced_search&auth=xxx&operator=and&type=song&offset=10000&limit=5000&random=0&rule_1=myrating&rule_1_operator=4&rule_1_input=1
works properly.

**Comment by lachlan-00** [comment]
will check in about a day. assuming it will be a bug outside the api and affecting all versions

**Comment by lachlan-00** [comment]
the sql is setting itself correctly i think
```
LIMIT $offset, $limit
```

it's in the search::run() function.

will be investigating again soon

**Comment by lachlan-00** [comment]
still happening. i need to fix this one

**Comment by lachlan-00** [comment]
fixed with 7e5e03cd8 the objects should be spliced and not the search

**Comment by SimonHova** [comment]
I think that this is broken again.

**Comment by lachlan-00** [comment]
i'll have a look tomorrow but i don't think i changed this again recently.

**Comment by lachlan-00** [comment]
wasn't set in api 5 so set with 1b6c16321
