### ISSUE TITLE
[Feature Request] View Songs by Genre

### ISSUE THREAD

**Issue by xeruf** [ampache/ampache#3203]
## Describe what you don't like about Ampache, or what it is missing

When I click on "Genres" and click on a genre box, Ampache shows "Loading" but nothing happens.

## Describe how you would like the feature to work

I would expect it to list all songs of this Genre when clicking on it. I know I can do this in "Smart Playlists", but this would be more convenient and intuitive :)

**Comment by mitchray** [comment]
I'm on v5.2.1 with the same docker image and its working as expected

That screenshot shows that you have **Artists** selected at the top, what happens when you click **Songs** and then select a genre?

**Comment by xeruf** [comment]
it looks exactly the same....

**Comment by mitchray** [comment]
Can you [enable logging](https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging) and see if any errors appear?

**Comment by xeruf** [comment]
now it suddenly works, what the heck...
