### ISSUE TITLE
Update page stuck on: Delete duplicate rows and require unique data on `object_count`

### ISSUE THREAD

**Issue by NatureMuncher** [ampache/ampache#3206]
### Describe the bug
Ampache Update
This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is develop with database version 530008

The following updates need to be performed:

Version: Version: 5.3 Build.: Build:0009
* Delete duplicate rows and require unique data on `object_count`

### To reproduce

1. Log in
2. Click on Update
3. Click Update Now on database maintenance page
4. Returned to same update page.
5. See error in logs

### Expected behavior
The update should process then return to the login screen.

### Screenshots
![Ampache_update_page](https://user-images.githubusercontent.com/1648745/159509029-d72653de-50a5-4d69-bcad-a8818472c75d.png)

## Environment

* Ampache version: `Your current version is develop with database version 530008`
* Web server + version: 
~~~
$ httpd -v
Server version: Apache/2.4.6 (CentOS)
~~~
* Server operating system: CentOS 7
* Client operating system: Fedora 35

### Client type

* Web Google Chrome (beta) Version 100.0.4896.46 (Official Build) beta (64-bit)

## Settings
 Upon request

## Logs
~~~
2022-03-22T14:39:58+00:00 [] (Ampache\Module\System\Dba) -> Error_query SQL: ALTER TABLE `object_count` ADD CONSTRAINT `object_count_unique` UNIQUE KEY (`object_type`,`object_id`,`date`,`user`,`agent`,`geo_latitude`,`geo_longitude`,`geo_name`,`count_type`);    
2022-03-22T14:39:58+00:00 [] (Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1071,"Specified key was too long; max key length is 767 bytes"]                                                                                                                
~~~
## Troubleshooting 
Attempted to use the cli to manually update the database but nothing happens:
~~~
[apache@host bin]$ ./cli admin:updateDatabase -e
The following updates need to be performed:
Version: 5.3 Build:0009
* Delete duplicate rows and require unique data on `object_count`
[apache@host bin]$ ./cli admin:updateDatabase -e
The following updates need to be performed:
Version: 5.3 Build:0009
* Delete duplicate rows and require unique data on `object_count`
[apache@host bin]$  cli run:updateDb -x
This script makes changes to your database based on your config settings
Target charset: utf8mb4
Target collation: utf8mb4_unicode_ci
Table engine: InnoDB
WARNING*** Running in Write Mode. Make sure you've tested first!
[apache@host bin]$
~~~

**Comment by lachlan-00** [comment]
i'm shortening this key and indexes now. the geo stuff isn't needed to be unique so this should only be about 700bytes after the next update

**Comment by lachlan-00** [comment]
update 530009 has been reduced to remove that constraint and a new one has been added in 530012 with f5d374d86

**Comment by NatureMuncher** [comment]
Thanks for taking a look, @lachlan-00. I did try the above steps again but it's still stuck:
First attempt after manually updating the git (`git clone -b develop...`:
~~~
This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is develop with database version 530008

The following updates need to be performed:

Version: Version: 5.3 Build.: Build:0009
* Compact `object_count` columns
Version: Version: 5.3 Build.: Build:0010
* Compact mbid columns back to 36 characters
Version: Version: 5.3 Build.: Build:0011
* Compact some `user` columns
* enum `object_count`.`count_type`
Version: Version: 5.3 Build.: Build:0012
* Index data on object_count
Version: Version: 5.3 Build.: Build:0013
* Compact `cache_object_count`, `cache_object_count_run` columns
Version: Version: 5.3 Build.: Build:0014
**IMPORTANT UPDATE NOTES**
This update may require multiple attempts to delete these duplicates before completing successfully.
* Delete `object_count` duplicates
* Use a smaller unique index on `object_count`
~~~

And after clicking Update, it repeats this:
~~~
This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is develop with database version 530011

The following updates need to be performed:

Version: Version: 5.3 Build.: Build:0012
* Index data on object_count
Version: Version: 5.3 Build.: Build:0013
* Compact `cache_object_count`, `cache_object_count_run` columns
Version: Version: 5.3 Build.: Build:0014
**IMPORTANT UPDATE NOTES**
This update may require multiple attempts to delete these duplicates before completing successfully.
* Delete `object_count` duplicates
* Use a smaller unique index on `object_count`
~~~
I did click the Update button multiple times but nothing changed after that.
Let me know when I can try another update.

**Comment by lachlan-00** [comment]
i've done another update to these DB updates to make sure they all go through are you still on 530008?

**Comment by NatureMuncher** [comment]
No I did a fresh git clone. From the capture above I believe I'm on `database version 530011`

**Comment by lachlan-00** [comment]
that's okay then i've fixed these things from 12 upwards so it should be resolved for you in develop now

**Comment by NatureMuncher** [comment]
that did it! Thank you! 
I was puzzled for a bit as it kept throwing `Error Unable to start playback, check mpd controller` errors, which I [googled and learned](https://github.com/ampache/ampache/issues/328) I had to re-select "Web Player" from the drop-down on the upper-right:
![webplayer](https://user-images.githubusercontent.com/1648745/159832922-2130ffc6-2c3f-4551-875c-7e01cc9f83ea.png)

**Comment by lachlan-00** [comment]
i've fixed up the query now to do it in one go and get all the dupes so this should be good now
