### ISSUE TITLE
MySQL database error when updating to version 530013

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3208]
Hi all, following the latest commit with the database updates, I'm getting the following MySQL errors with the database updates failing to apply past version 530012:
```
(Ampache\Module\System\Update) -> run_update: starting
(Ampache\Module\System\Update) -> run_update: checking versions
(Ampache\Module\System\Update) -> run_update: successfully updated to 530012
(Ampache\Module\System\Dba) -> Error_query SQL: ALTER TABLE `cache_object_count` MODIFY COLUMN `count_type` enum('download','stream','skip') CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL NULL; []
(Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1171,"All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead"]
(Ampache\Module\System\Dba) -> Database connection...
```
![image](https://user-images.githubusercontent.com/3216809/159762206-15f8e8bb-75ab-4326-a104-e13b80c1354d.png)

Temporarily worked around the issue by manually updating the db_version entry in the update_info table to 530014

**Comment by lachlan-00** [comment]
i've fixed these all up, set your version back to 530011 to make sure it all goes through

**Comment by rsinfotech** [comment]
Hi @lachlan-00, this got my updates through to version 530013 but each seemed to still result in the following errors:
```
(Ampache\Module\System\Update) -> run_update: starting
(Ampache\Module\System\Update) -> run_update: checking versions
(Ampache\Module\System\Dba) -> Error_query SQL: ALTER TABLE `object_count` DROP KEY `object_count_unique`; []
(Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1091,"Can't DROP 'object_count_unique'; check that column\/key exists"]
(Ampache\Module\System\Dba) -> Database connection...
(Ampache\Module\System\Update) -> run_update: successfully updated to 530012
(Ampache\Module\System\Update) -> run_update: successfully updated to 530013
(Ampache\Module\System\Dba) -> Error_query SQL: ALTER TABLE `object_count` DROP KEY `object_count_UNIQUE_IDX`; []
(Ampache\Module\System\Dba) -> Error_query MSG: ["42000",1091,"Can't DROP 'object_count_UNIQUE_IDX'; check that column\/key exists"]
(Ampache\Module\System\Dba) -> Database connection...
(Ampache\Module\System\Dba) -> Error_query SQL: CREATE UNIQUE INDEX `object_count_UNIQUE_IDX` USING BTREE ON `object_count` (`object_type`, `object_id`, `date`, `user`, `agent`, `count_type`); []
(Ampache\Module\System\Dba) -> Error_query MSG: ["23000",1062,"Duplicate entry '5216-1621198798-5-Mozilla\/5.0 (Windows NT 5.1; rv:52.0) Gecko\/20' for key 'object_count.object_count_UNIQUE_IDX'"]
```
I've tried applying this last one multiple times as mentioned in the update notes but the errors just seem to repeat.

**Comment by lachlan-00** [comment]
Duplicate entry means your table still has dupes.
I've only put deletes in there three times so give it a few refreshes or I'll paste rate delete query too here when I get home

**Comment by lachlan-00** [comment]
DELETE FROM `object_count` WHERE `id` IN (SELECT `id` FROM (SELECT `id` FROM `object_count` WHERE `id` IN (SELECT MAX(`id`) FROM `object_count` GROUP BY `object_type`, `object_id`, `date`, `user`, `agent`, `count_type` HAVING COUNT(`object_id`) > 1)) AS `count`);


To check you have dupes it only gets the max value which may be the 3rd or 4th (or 17th) duplicate value.

I don't really know a fast way to find these but I may just delete them by date for artist/album and restore them instead

**Comment by lachlan-00** [comment]
On my phone but I'll pick this up later.

Before you delete more can you print out what your dupes actually are? I. Assuming artist and album

```
Select * FROM `object_count` WHERE `date` IN (SELECT `date` FROM (SELECT `date` FROM `object_count` WHERE `id` IN (SELECT MAX(`id`) FROM `object_count` GROUP BY `object_type`, `object_id`, `date`, `user`, `agent`, `count_type` HAVING COUNT(`object_id`) > 1)) AS `count`);
```

**Comment by rsinfotech** [comment]
I've repeated this over 50 times now and I'm still unable to escape from the update page so I'm assuming I must have a ridiculous number of duplicates?

**Comment by rsinfotech** [comment]
Running the query you provided returns: Showing rows 0 - 24 (1536 total, Query took 0.3016 seconds.) 
Most of the object_types listed seem to be artist but there are also some song and album entries.

**Comment by rsinfotech** [comment]
Persistence paid off here @lachlan-00, I noticed that after each repeated update attempt, the number of duplicates reported by your query dropped by around 40 entries so I just continued until I eventually received the following:

![image](https://user-images.githubusercontent.com/3216809/159870317-de6c818b-baed-41af-930b-3c76be6a062d.png)

This must have taken well over 100 attempts to complete, I lost count, but it got there in the end :+1: 

Thanks again for your excellent support, much appreciated.

**Comment by lachlan-00** [comment]
haha, yeah i want to make that a bit easier before going into master
