### ISSUE TITLE
Error Object of class Ampache\Repository\Model\Song could not be converted to string

### ISSUE THREAD

**Issue by rockstar2020** [ampache/ampache#3209]
### Description
Hi there,
I'm new to Ampache and I should admit so far it's been the best Music Server I ever had configured.
Thanks for the great work!
Now here is the issue I'm facing:
I have lots of MP3 and FLAC files that are not part of an album. 
For this reason I'd like to gather song art for each song separately and store them in the database.
The problem is that when I'm using D'Sub to play songs remotely but the album art appearing is the art of the first file in that folder, not the actual song art within the media tag.
To fix this issue I set the "gather_song_art" setting in config file ( /var/www/ampache/config/ampache.cfg.php) to True and then ran the following CLI command:
 
sudo -u www-data php -f /var/www/ampache/bin/cli run:updateCatalog -cag

But after running it I get the following errors:

![image](https://user-images.githubusercontent.com/35903046/159819704-224601f2-75ea-44da-800d-1fc165251e29.png)

[Description of the bug or feature]

### Steps to Reproduce

1. Create a Catalog that points to a folder with several MP3 files that are not from the same artists and albums.
2. Add few more MP3 files to the folder.
3. Run the following CLI command:  sudo -u www-data php -f /var/www/ampache/bin/cli run:updateCatalog -cag

**Expected behavior:** [What you expected to happen]

The expectation is to have the new files added to the catalog and all art images for each songs are diplayed in both web player as well as D'Sub client.

**Actual behavior:** [What actually happened]

The files get added to the catalog but with no artwork.
Also the CLI command throws bunch of errors as copied above.

### Versions

Ampache 5.2.1 running on Ubuntu 20.4

**Comment by lachlan-00** [comment]
seems like it's gathering with the object instead of the id somewhere
![image](https://user-images.githubusercontent.com/1305249/160219597-1c666fb1-9e45-47d8-a881-54eed7f7dda4.png)


Will be able to fix up on monday

**Comment by rockstar2020** [comment]
Thanks for your response @lachlan-00 ,
Can you tell me what I need to change in the code to test it?

Thanks

**Comment by lachlan-00** [comment]
something will be calling that function with a song instead of passing the type and id, should be fast to find

**Comment by rockstar2020** [comment]
> something will be calling that function with a song instead of passing the type and id, should be fast to find

Thanks, 
That's what I guessed. 
In fact I excluded the "song" types from gather_art function which helped to fix the errors but I know it's not enough because still some files don't have their arts loaded as album arts. In fact no song arts for some at all. 

Looking forward to see your findings. 

Cheers

**Comment by lachlan-00** [comment]
found one,
![image](https://user-images.githubusercontent.com/1305249/160340599-5132e4f6-2d96-4ea4-ad9c-19091e3da5ea.png)

**Comment by lachlan-00** [comment]
fixed with 4e0f1c699

**Comment by rockstar2020** [comment]
Thanks a lot @lachlan-00 ,
This fix worked.

Cheers
