### ISSUE TITLE
[Feature Request] Web Player remove played tracks from play queue

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3213]
I would like a setting for the Web Player to remove tracks after they have played (or some settable number after played).

This is useful where tracks can be added to the play queue then the play queue shuffled.  It would prevent already played tracks from being shuffled back into the queue and being heard again.

As an example on a mobile player, look at DSub where there is a "removed played songs" checkbox which removes songs after being played.  There is a corresponding "Keep Played Songs" setting in the playback settings which controls how many played songs to keep when the checkbox is selected.

**Comment by troycarpenter** [comment]
Implementation notes:

The web gui should have two action buttons: 
- a "removed played" button or checkbox: Remove all tracks in the playlist above the current track.  This could be a checkbox that also removes the tracks at the time when checked, and then indicates tracks will be removed as played.
- "remove all" button: Does what it says...removes all songs from the playlist.  Right now I have to reload the page to get this functionality.

It would be nice to be able to specify how many tracks to keep above the current, but a first pass implementation would be to keep the previous track in case the user wants to hear that one again.

Finally, the settings should be persistent so that each time the web player comes up it already has the options set based on the last use.

**Comment by lachlan-00** [comment]
DB option to add that in might work. so the player can be created with that option enabled

The option would probably be looked up in show_html_5_player like with all these ifs and an option can be created in the JS
![image](https://user-images.githubusercontent.com/1305249/167065916-b4f8c47f-4141-48b0-a23d-3aae46d3ef4a.png)

We're not using the original jplayer source now so there's no reason not to extend this

**Comment by troycarpenter** [comment]
I'll have a look at it when I'm done with the catalog access filter feature I'm working on.  Seems higher priority than this one.

**Comment by lachlan-00** [comment]
i'd test is just by adding an option into jplayer.playlist
![image](https://user-images.githubusercontent.com/1305249/167066311-2ed08a50-5a5d-4665-beab-13bedf91f458.png)

then you can set it to call self.remove(index -1) in the play function.

at least that looks like what you'd do

**Comment by troycarpenter** [comment]
I noticed the setting for this in the streaming options and it seems to be working.

I don't know when it was added, though:
![image](https://user-images.githubusercontent.com/8419000/191062355-69185aaf-fe37-4990-a6fe-f3b33be3a413.png)

This is from my production server running the latest Docker develop branch image.  I'm going to close it now.

**Comment by lachlan-00** [comment]
it's in develop but not in a 5.x release.
