### ISSUE TITLE
Disabling catalog doesn't actually disable it

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3215]
## Description
After enabling the ability to disable a catalog (catalog_disable = "true"), I am present the universal "NO" signal in the "show catalog" screen for each catalog.  My assumption is that pressing that will disable the catalog from all searches and lists.

### Describe the bug
When I pressed the disable button on the catalog page, the button turns to a green checkmark that says enable.  If I do a search or show albums or artists, content still shows up.  When I go back into the catalog screen, the red disable button has returned, possibly indicating the catalog was never really disabled.

Secondly, if still on the catalog screen, clicking on the green enable button does nothing (button icon doesn't change).

### Steps to reproduce the behavior:

1. Enable the feature in ampache.cfg.php (uncomment catalog_disable = "true")
2. Go to Admin -> Show Catalogs
3. Pick a catalog to disable
4. Click on the red disable button next to the GO button.
5. Search for content in the disabled catalog
6. See content from the supposed catalog appear

### Expected behavior
I expected content from that catalog to be removed from all search results and all the various album/artist lists.

## Environment

* Ampache version: docker-latest (5.2.1)
* Client operating system: Web interface with Chrome Browser

### Client type

* Web
* Ampache
* SubSonic

## Logs
No ampache logs related to this (I've got level 5 debug on)
No apache2 logs when doing this action

**Comment by lachlan-00** [comment]
i'll see if there's something obvious, it's been a while since i used disable so maybe some kind of crept in error

**Comment by lachlan-00** [comment]
seems like it thought the value was blank.

fixed with c58da58bf and 41be04a21
