### ISSUE TITLE
Web player queue actual track order does not change when manually reordering songs in the play queue

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3218]
## Description
Once songs are in the web player queue, as shown on the lower left of the screen, it should be possible to drag and drop songs from one location to another.  While the visual drag and drop function is there, it doesn't actually change the order of songs in the play queue.

### Describe the bug
When songs are re-ordered via a drag and drop action from one part of the playlist, the player still plays the original song order.  For instance, when a song is dragged from the bottom of the play queue to be after the currently playing song, the song that actually plays next is the one there originally.

### To reproduce
The easiest way to see this is to only use three songs:

1. Add three songs to the play queue
2. With the first song playing, go to the queue in the lower right, grab the last song and move it up to be after the currently playing song.
3. When the first song finishes playing, the song that was in the second slot originally plays, not the one just moved up.
4. The play queue on the right highlights the song that was moved into the second slot as currently playing, but it's not.

In short.  The original song order was A,B,C.  Song C was dragged up to make the order A,C,B.  When song A completes, song B plays as was the original order (the player shows song B's info so it's not confused), but the queue shows song C highlighted as playing. 

### Expected behavior
I expect the new song order in the play queue to be respected, not the original order.

### Screenshots
![image](https://user-images.githubusercontent.com/8419000/164029284-e72dceea-1123-4ca8-a09f-3e70dd4babea.png)
In this image, you can see "Jackson" is playing, but the song "Y'all Come" is highlighted in the queue as playing.

## Environment

* Ampache version: Docker Latest (not develop)
* Server operating system: Linux
* Client operating system: Windows

### Client type

* Web (at least Chrome browser, didn't verify others)

## Settings
There shouldn't be any settings to cause this.

## Logs
No logs printed related to this, other than showing the songs playing in the original order when appropriate.

**Comment by lachlan-00** [comment]
i haven't built the docker images yet but i spent a bit of time fixing this up.
will be fixed on the next release

**Comment by lachlan-00** [comment]
The reason you aren't seeing any logs is the issues are in the javascript.

fixed in 483601cfb dec7be71e b847b75b8 and 02f45d6ab

this cycle i've forked jplayer into the ampache code and merged the extended code into the forked module. this allowed me to sit down and fix up all the player issues that have been a long term issue.

**Comment by troycarpenter** [comment]
I just tested this in 5.3.0 Docker `latest` tagged image.  Reordering the list does now appear to work.  However, not related to this bug, the last commit listed 02f45d6 suggests it will fix shuffling the playlist, but it doesn't work as expected.  Not sure if I need to write a bug on that yet.
