### ISSUE TITLE
playlist_generate with flagged in XML API 5.1.0 & up

### ISSUE THREAD

**Issue by 4phun** [ampache/ampache#3220]
Hi,

`/server/xml.server.php?action=playlist_generate&flag=1&format=index&auth=<AUTH_CODE>`

returns (CAPITAL LETTERS by me):

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <total_count>ALL_SONGS_COUNT</total_count>
  <song id="ID">
    .
    .
    .
  </song>
  LISTS ALL SONGS!!!
</root>

```

I'd expect total_count to be the count of flagged songs, and then list flagged songs only.

I've seen this in versions 5.1.0 and up (not tested 5.3.0 yet).

Not sure if this has to do with what I found in change log: `Merge config 'ratings' and 'userflags' checks into ratings. (drop userflags)` I don't fully understand what this changes entails, can please give a short explanation? Thank you.

Note that 

`server/xml.server.php?action=stats&filter=flagged&type=song&auth=<AUTH_CODE>`

also returns count of all songs in total_count.

**Comment by 4phun** [comment]
Hey I did some additional testing about this, seems like it's already fixed in 5.2.1. Sorry I should have caught it.

**Comment by lachlan-00** [comment]
looking now

**Comment by 4phun** [comment]
Hi,

I never had time to complete testing. Sorry! At one point I thought it
works in 5.2.1 then I thought I was wrong about that... I got a
bit confused 😄

**Comment by lachlan-00** [comment]
so generate loads up the regular addsong items which adds the total for the table.

I might add in an option to allow either or both as well as maybe work on the types of objects that get returned by generate playlist
