### ISSUE TITLE
DSub doesn't load "Recently added"

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#3227]
as per title when i try to load "Recently added" in DSub i get the error "a network error occurred"
in apache error log i see

[php:error] [pid 473100] [client 37736] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/ampachetest/src/Module/Api/Subsonic_Api.php on line 742
[php:error] [pid 473100] [client 7736] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
[

what's there that eats 1gb of ram allowed for php?!

* Ampache version: 5.3.1_all_php8.0
* Web server + version: apache 2.4.52
* Server operating system: debian 11
* Client operating system: android 11

**Comment by lachlan-00** [comment]
Fixed now. Patch release early next week to see if anything else comes up

**Comment by PsyZeus** [comment]
upgraded today to php 8.1 (8.1.5) and ampache 5.3.2_all_php8.1
so far all perfect m8!!! :D 

closing this
