### ISSUE TITLE
Unable to start playback on Web interface if HTTPS only mode is enabled

### ISSUE THREAD

**Issue by Altair31** [ampache/ampache#3231]
# Issue Template

## Description

**Describe the bug**
Playback don't start, no playback UI shown either

**To reproduce**
1. In Firefox, go in Settings > Security > HTTPS only mode: Check always
2. Load ampache home page
3. Select play on any song

**Expected behavior**
Song starts playing

## Environment

* Ampache version: 5.3.1
* Web server + version: Nginx 1.18.0-6.1
* Server operating system: Debian 11
* Client operating system: N/A

**Client type:**

* Web

## Settings

Default configuration (upgraded since 3.9)

## Logs
No console error, no request sent.

## Workaround
Whitelist the website.

**Comment by mitchray** [comment]
Have you also configured an SSL certificate for your server and enabled it for Ampache?

Just enabling always-on HTTPS in Firefox won't be enough (sadly)

**Comment by Altair31** [comment]
Yes, I have a legitimate Let's Encrypt certificate. It's in my nginx configuration.
Ampache is served through php-fpm.
It looks like some paths go through HTTP but I was unfortunately unable to list them.

**Comment by Altair31** [comment]
Sorry, seems to work back.
I tried to rollback modifications on browser side and it works as expected -_-
I don't know what happened by the way.
