### ISSUE TITLE
[Bug] Album_map not updated after deleting a song

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#3246]
### Describe the bug

The album_map table is not update after deleting a song

### To reproduce

1. Choose the only song from an album belonging to an artist ( like a song from a compilation )
2. Delete a song from an album ( the album is not  to delete )
3. Run clean album ( from web interface or cli )
4. The album happears already in the artist interface ( should not )
5. Examining the database the album is wrogly present in album_map associated to the artist

### Expected behavior

The album reference shoul be deleted from album_map table

**Comment by lachlan-00** [comment]
need garbage_colleciton in src/Module/Song/Deletion/SongDeleter.php

**Comment by lusum** [comment]
After latest patches  , bug already present..

**Comment by lusum** [comment]
Ok, found the problem

       Song::garbage_collection();
        $this->albumRepository->collectGarbage();
        Video::garbage_collection();
        Podcast_Episode::garbage_collection();
        Wanted::garbage_collection();
        Artist::garbage_collection();

The problem: album_map is updated on        $this->albumRepository->collectGarbage(); , but this data depends on         Artist::garbage_collection(); that is executed after the album. So a solution should be to place artist before album or... split the garbage function in album and place album_map cleaning after artist or simply place album_map garbage collection in artist::garbage_collection.

**Comment by lusum** [comment]
Btw, another bug debugging clean file

The function 

  private function _clean_chunk($media_type, $chunk, $chunk_size)

in catalog_local.php

return an array $dead, but this array is declared , but never used, so it is always empty. ( and obv. the search return zero )

**Comment by lachlan-00** [comment]
> 



> Ok, found the problem
> 
> CatalogGarbageCollector.php
> 
> ```
>    Song::garbage_collection();
>     $this->albumRepository->collectGarbage();
>     Video::garbage_collection();
>     Podcast_Episode::garbage_collection();
>     Wanted::garbage_collection();
>     Artist::garbage_collection();
> ```
> 
> The problem: album_map is updated on $this->albumRepository->collectGarbage(); , but this data depends on Artist::garbage_collection(); that is executed after the album. So a solution should be to place artist before album or... split the garbage function in album and place album_map cleaning after artist or simply place album_map garbage collection in artist::garbage_collection.

it's after album in other place so i'll just match it

**Comment by lachlan-00** [comment]
set the dead total now with 05e910405

**Comment by lusum** [comment]
Tested both, it works
