### ISSUE TITLE
Long podcast descriptions (>4096) seem to cause episode addition issues.  Should be truncated.

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3248]
## Description
I have one podcast that occasionally has LONG descriptions, greater than the SQL table defined length of 4096.  Every time Ampache encounters one of these long descriptions, the episode is skipped.

### Describe the bug
I *think* somewhere in the code when the description is very long, Ampache becomes confused about the publication date.  Every time there is an overly long description, the episode fails with the message like this:
Episode published before 1651674602 (1651654844), skipped.

By adding some debug statements, I've discovered podcast description lengths like 5735 or 4963.  If I skip the date check, the long descriptions cause MYSQL errors due to the length of the description fiield.

When I truncated the description field to 4090 and skipped the date check, the episode was added without issues.  What I have not investigated yet is whether the long description field is causing problems with the date calculations since on this podcast all the skipped episodes have large descriptions (and I know the date check is important because another podcast updated while I was testing and I ended up with duplicated episodes on that podcast) OR is it just case that the RSS feed is messed up at the source.

### To reproduce
Find a podcast that has description larger than 4096 and see if it will add.  For testing and reproducing, the description can be artificially made longer than 4096 and see what happens.

### Expected behavior
In any case, the description and other fields like title need to be truncated if they are too long.

## Environment

* Ampache version: Docker develop (digest 486fe123d997)
* Server operating system: Linux Docker
* Client operating system: Windows

### Client type

* Web

###Logs
Logs were shown above.  Additional debug logs added by me in the source to determine string lengths.

**Comment by lusum** [comment]
Can you post a link to a podcast that causes this bug? So we can reproduce the bug.

**Comment by troycarpenter** [comment]
This one has long descriptions:
https://www.albertmohler.com/category/the-briefing/feed/

**Comment by lusum** [comment]
Ok, found the problem

> "22001",1406,"Data too long for column 'description' at row 1"

In  INSERT INTO `podcast_episode` (`title`, `guid`, `podcast`, `state`, `source`, `website`, `description`, `author`, `category`, `time`, `pubdate`, `addition_time`, `catalog`) VALUES (?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?, ?, ?)

description field is too much long. I think that a possible solution should be checking the description of the podcast and cut to match description ( enlarge description could cause problems with even longer descriptions )

**Comment by troycarpenter** [comment]
What I did in my testing is when the description length was greater than 4096, I simply truncated it which allowed it to be inserted without error.  I did it just before the INSERT INTO.

HOWEVER, what I think is that the string should be truncated when it is read in from the RSS text.  I didn't investigate where that happens to try it, I was hoping someone else who has worked with it would know where that should be done.

What I don't know is whether the long description somehow messed with date calculations because every time I got a "Episode published before ...skipped" message, it was the case that the description was over 4096 characters.  It's odd that it would happen only on the long descriptions an not with other episodes in the feed.

**Comment by troycarpenter** [comment]
In src/Repository/Model/Podcast.php around line 559:
```
        $dsc_len = strlen($description);
        debug_event(self::class, "Descripton length: $dsc_len", 5);
        if ($dsc_len > 4090) {
            $description = substr($description,0,4090);
            debug_event(self::class, "Truncated.  New descripton length: " . strlen($description), 5);
        }
```
That's what I did at this point, but like I said, I think it should really be truncated when the RSS is read.

**Comment by lachlan-00** [comment]
i'll do it as a dba function and we can add it to more areas like this

**Comment by lachlan-00** [comment]
set with 5d4ec7ae0

**Comment by lachlan-00** [comment]
5.3.3 has the change now
