### ISSUE TITLE
Api4 record_play required 'user' parameter should be optional

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#3252]
### Describe the bug
#3021 seems to have reemerged when making requests on Api4.

### To reproduce
- handshake with version 440000 
- record_play without user parameter set 
- server experiences runtime error as user parameter is undefined

### Expected behavior
- server should not experience runtime error, as user parameter is optional

## Environment

* Ampache version: 5.3.1
* Web server + version: N/A
* Server operating system: N/A
* Client operating system: N/A

### Client type

* Ampache

**Comment by lachlan-00** [comment]
the versions were made from the last v4 release zip so there might still be some left overs.

that's made now in 7ce63a7aa

**Comment by lachlan-00** [comment]
new release next week to fix this up. don't have the time today for it

**Comment by lachlan-00** [comment]
5.3.3 has the change now
