### ISSUE TITLE
MySQL Database Creation Errors

### ISSUE THREAD

**Issue by max2play** [ampache/ampache#3254]
Hi,
there is a bug in the Mysql Database Setup with the ampache.sql script. The error does not show up on the installer-page, but you can see that some database tables are missing after creation:

metadata_field
tag
session
session_remember

These tables cannot be created, as the try to create indexes on fields that are too large. Example with session table field id:
id varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL
Creating an Index like "PRIMARY KEY (id)" results in an SQL error ("Key length too long").

The bug leads to issues like "Cannot Create Admin user" where I also posted this as an answer.

As a workaround you could decrease the varchar size of the keys to 190 or change the collation to "utf8_unicode" and keep a size of 255 (decrease 1 from 256). 
In the session table as it stores values like '0d09f796704d66a5d2a620dcdcddf34' (length of 32 chars) and it should be better to set it to varchar(32). Seems like some of the fields are to big for what they need to store. This should also improve performance.

Is there a way that Ampache developers will fix this? I use Ampache as an option in Max2Play and would like this to be fixed in the ampache.sql Setup file rather than always manipulating the file during install.

Tested with Debain Buster, Maria-DB 10.0 (10.0.28-2), Default Setup. The problem seems to be in all current versions of Ampache.

All the Best
Stefan

**Comment by lachlan-00** [comment]
thanks i'm going to try and fix those today with a new release. id'ing the tables people have issuea with are always a pain

**Comment by lachlan-00** [comment]
i'll be setting them to utf8_unicode and compressing in a different major release so i can force all existing databases to match this change

**Comment by lachlan-00** [comment]
set a compacted user and utf8 with e00dd097e

**Comment by troycarpenter** [comment]
If I will be adding a table that uses the name field, should I go ahead and define it the way you made the changes on Master, or should I define it like the others and let it get changed when you do your big update?

**Comment by lachlan-00** [comment]
existing databases will get updated with new updates.

your changes will def warrant a 5.4 release so i'll do the db updates as part of that release after yours have merged

**Comment by troycarpenter** [comment]
Ok.  But I've been looking into the GUI code to figure out how to add new screens and it's taking a bit longer to understand the framework.  We can move that to the feature discussion thread instead of here, though.

**Comment by lachlan-00** [comment]
5.3.3 is out with an updated sql file

**Comment by max2play** [comment]
Thanks! That was quick :)

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
