### ISSUE TITLE
Streaming performance with Media3

### ISSUE THREAD

**Issue by tzugen** [ampache/ampache#3255]
Hi!

Over at Ultrasonic we are switching to Media3 as the playback interface (its the upcoming version of Exoplayer intwgretated onto android). Nite has found some performance issues, possibly related to Ampache. @lachlan-00 could you have a look? Maybe you have an idea what the problem is...

https://github.com/ultrasonic/ultrasonic/pull/726#issuecomment-1117830856

**Comment by mitchray** [comment]
Was this resolved as a https issue?

https://github.com/ultrasonic/ultrasonic/pull/726#discussion_r867073437

**Comment by lachlan-00** [comment]
@tzugen happy to help where I can. The demo isn't very powerful but has been handling the load from what I can see but can provide anything you need.

I was about to extend the hosting for another 3 years so if it needs some more hardware now is the time.

I'm also working on a subsonic rewrite now with the intention of speeding up slow functions and I'm probably half way through that

**Comment by nitehu** [comment]
> Was this resolved as a https issue?

Yes, thank you, I think it was a false alarm, not an Ampache problem.
Media3 seems to hold a stream open for more time (at least more than just writing everything quickly into a file), and it slows down things a bit, but nothing serious - even my NAS can handle it.
