### ISSUE TITLE
Adding Podcasts to Playlists causes numbering issues.

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3256]
## Description
While testing the new catalog access feature, I noticed that adding podcasts to a playlist causes duplicate "track" numbers.

### To reproduce
Add some songs to a playlist, then add a few podcasts.

Look at the playlist_data table for the playlist in question.  You will see duplicate track numbers.

```
MariaDB [ampache]> select * from playlist_data where playlist=4;
+-----+----------+-----------+-------------+-------+
| id  | playlist | object_id | object_type | track |
+-----+----------+-----------+-------------+-------+
| 477 |        4 |     14512 | song        |     1 |
| 478 |        4 |     21760 | song        |     2 |
+-----+----------+-----------+-------------+-------+
2 rows in set (0.001 sec)

MariaDB [ampache]> select * from playlist_data where playlist=4;
+-----+----------+-----------+-----------------+-------+
| id  | playlist | object_id | object_type     | track |
+-----+----------+-----------+-----------------+-------+
| 477 |        4 |     14512 | song            |     1 |
| 478 |        4 |     21760 | song            |     2 |
| 479 |        4 |      1657 | podcast_episode |     3 |
+-----+----------+-----------+-----------------+-------+
3 rows in set (0.001 sec)

MariaDB [ampache]> select * from playlist_data where playlist=4;
+-----+----------+-----------+-----------------+-------+
| id  | playlist | object_id | object_type     | track |
+-----+----------+-----------+-----------------+-------+
| 477 |        4 |     14512 | song            |     1 |
| 478 |        4 |     21760 | song            |     2 |
| 479 |        4 |      1657 | podcast_episode |     3 |
| 480 |        4 |      1329 | podcast_episode |     3 |
+-----+----------+-----------+-----------------+-------+
4 rows in set (0.001 sec)
```

I originally saw this testing my code for the catalog access feature and thought I had messed up some SQL somewhere (easy to do).  I went to the Docker Develop and saw the behavior there as well. 

### Expected behavior
I expect the track field to increase regardless of the media type.  I'm guessing an increment was missed somewhere when adding podcasts.

## Environment

* Ampache version: Docker DEVELOP
* Client operating system: Windows

**Comment by lachlan-00** [comment]
probably here 
![image](https://user-images.githubusercontent.com/1305249/167321365-6c48a5fe-ee66-44e5-b60f-e437a3b3ae1f.png)

**Comment by troycarpenter** [comment]
I think the problem is actually in add_medias.  I'm not sure some count is incrementing when podcasts are added.  When a podcast is added, the playlist track number doesn't increase (that is, if you add a podcast episode as track #10, then add 5 more podcase episodes, then they are all number 10.  However, if you delete any track, it renumbers them correctly.  I'm looking now.

**Comment by lachlan-00** [comment]
> add_medias

looks like it only gets songs so it's counting from the total of songs
![image](https://user-images.githubusercontent.com/1305249/167326395-27cc2c4f-1eaa-4f57-bcaa-5a8107cc839a.png)

**Comment by troycarpenter** [comment]
Yes, I was about to post that it should be using get_items()

**Comment by troycarpenter** [comment]
Confirmed that using get_items() fixes it.  Are you going to to a quick change in develop for that?

**Comment by lachlan-00** [comment]
2535a845b

**Comment by troycarpenter** [comment]
Fixed in develop branch.
