### ISSUE TITLE
handle correctly .htaccess files

### ISSUE THREAD

**Issue by olaulau** [ampache/ampache#3264]
Hi ;
after an ampache upgrade, using release tarballs, endup with a subsonic (android) error again.
I found that is was just .htaccess that are packaged as .htacces.dist .
If ampache is mainly targeted for apache hosting, those files shouldn't be correctly named.
otherwise, it should be well writetn in install / upgrade guides, or maybe an upgrade assistant could detect apache server and rename the files.
what is the purpose of not naming them .htaccess ?

**Comment by arno1979** [comment]
My best guess: .htaccess files are specific to the apache webserver. As you can run ampache using other webservers (i. e. Nginx) .htaccess files should not be automatically in effect.

**Comment by olaulau** [comment]
is this a problem if .htaccess file exists for other webserver ?

**Comment by manuelglez86** [comment]
when you update, did your previous .htaccess files were deleted?

Remember that when you install for ths first time ampache the .htaccess files are generated according to your server configuration

**Comment by olaulau** [comment]
it seems that .htaccess files are renamed by default on the repo : https://github.com/ampache/ampache/tree/develop/public/rest
are you sure that those files are handled by install script ? I had to rename them many times.
the update process is to backup entire folder, extract new release tarball, and them copy the old config file over : https://github.com/ampache/ampache/wiki/Upgrade

**Comment by manuelglez86** [comment]
The .htacces.dist are not fully configured .htaccess files.

the .htaccess files with the information of you ampache folder are generated at install time.

the .htaccess file should look like this:

`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache531/public/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /ampache531/public/play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /ampache531/public/play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /ampache531/public/play/index.php [L,QSA]
</IfModule>`

**where ampache531 is my own folder of ampache. so your files should have your ampache folder

Yes I have notice that the procedure of update on the wiki doesnt consider the .htaccess files.

@lachlan-00 I think the procedure should mencion the need to copy your .htaccess files, can you confirm this?

**Comment by arno1979** [comment]
@manuelglez86 The upgrade guide at https://github.com/ampache/ampache/wiki/Upgrade does mention the need to re-copy the .htaccess files in the 'channel', 'play' and 'rest' subfolders. It's right at the bottom of the page.

**Comment by manuelglez86** [comment]
oohh yeah sorry, its at the end of the page.

@olaulau

**Comment by olaulau** [comment]
true ... sorry !
