### ISSUE TITLE
Custom metadata question

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#3265]
Hi

I was wondering if it is possible to add any custom metadata fields and I found this image on another post:

[https://user-images.githubusercontent.com/1305249/73237228-a1211100-41e0-11ea-908d-82a4e2013de4.png](url)

I would try to add movement, director and maybe other fields for classical music

How do I do that (if its possible)? I couldnt find where in the cfg nor the web interface.

Thanks

**Comment by lusum** [comment]
; Enable importing custom metadata from files.
; This will need a bit of time during the import. So you may want to disable this
; if you have troubles with huge databases.
; DEFAULT: "false"
;enable_custom_metadata = "true"

look for this line in ampache.cfg.php ( in config directory )
