### ISSUE TITLE
DB backup question

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#3270]
So i just took a look at the upgrade page and saw the new options added to the db backup command.

From a quick search it seems that the "--add-drop-table" it's not necessary because it's a default behavior of the mysqldump.

But what about the "--allow-keywords" ?
i mean all these years i use the simple
mysqldump -u USERNAME -p -h localhost AMPACHEDB > /tmp/ampache.sql

did something changed in db and now i need to add that option?
do i miss something if i don't add it and continue with the simple command?
"--allow-keywords" falls under the debug options as i see so is it really necessary?
please enlighten me!!!

**Comment by lachlan-00** [comment]
no nothing has changed i just found separate wiki pages with the same instructions and combined them.

**Comment by lachlan-00** [comment]
personally i just use the simple dump as well

**Comment by PsyZeus** [comment]
thanks for info dude :D
