### ISSUE TITLE
Runtime error when executing catalogue verify from cli

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3274]
Just noticed I'm getting a repeated runtime error occurring in my logs when running `run:updateCatalog -e` from the command line:
```
[ampache] (log.lib) -> [Runtime Error] Attempt to read property "id" on string in file /var/www/html/ampache/src/Repository/Model/Song.php(1709)
```
Nothing else reported and the verify seems to still complete and update tags ok.

**Comment by lachlan-00** [comment]
There are a lot of user-centric features that require an id so i've put it in with 96f582afe

What this should do is load all the preferences for that user (the system ones) and not cause ID errors like this

**Comment by rsinfotech** [comment]
Yep, that has got rid of the errors, many thanks for the quick response as always.
