### ISSUE TITLE
Connection issues after recent update

### ISSUE THREAD

**Issue by Dreadlocke12** [ampache/ampache#3275]
I am using DSub under Android to access my ampache web server in my local (and so far only in my local network).  The web server is running an apache and i enabled as described the rewrite mod as well after the update to 5.3.3 (and updating the database) i run this in the /public Folder: 

cp ./rest/.htaccess.dist ./rest/.htaccess
cp ./play/.htaccess.dist ./play/.htaccess
cp ./channel/.htaccess.dist ./channel/.htaccess 

But now I can not access my ampache anymore over Dsub which is using the subsonic API.

**Comment by lachlan-00** [comment]
Subsonic connects using /rest and requires working rewrite rules so there's something not right then.

possibly that apache security doesn't allow you to rewrite.

Is is a custom docroot or in /var/www/html?

**Comment by Dreadlocke12** [comment]
Well the Apache and the vhost file of ampache have the "Allowoverride all" enabled. It did work though with the same apache settings u til the update to 5.3.3. 

I do not have a custom docroot enabled.

**Comment by manuelglez86** [comment]
I have a question of the update process , when you did the 

cp ./rest/.htaccess.dist ./rest/.htaccess
cp ./play/.htaccess.dist ./play/.htaccess
cp ./channel/.htaccess.dist ./channel/.htaccess

you copy this (play .htaccess as example:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>
```

but on the install process the file generated looks like this:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache531/public/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /ampache531/public/play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /ampache531/public/play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /ampache531/public/play/index.php [L,QSA]
</IfModule>
```

Could this be the problem for @Dreadlocke12 ? or it doesnt matter anymore?

@Dreadlocke12 maybe the update has dissabled some API versions, Could you check on preferences? Which API version does DSUB uses?

Did you gettein an error on DSUB or in AMPACHE log?

**Comment by Dreadlocke12** [comment]
Well I tried to re add the original .htaccess file if that is what you meant but it was not working so i copied the .htaccess files from the ampache folder from the previous installation and it seems to work now: 

the rest folder .htaccess file looks now like this: 

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /ampache/public/rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /ampache/public/play/$1 [PT,L,QSA]
</IfModule>


the channel folders file like this: 

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^([0-9]+)/(.*)$ /ampache/public/channel/index.php?channel=$1&target=$2 [PT,L,QSA]
</IfModule>

and the play folder file like this: 

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/public/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=a>
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /ampache/public/play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /ampache/public/play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /ampache/public/play/index.php [L,QSA]
</IfModule>


so I assume this line: 
RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /ampache/public/image.php?object_type=$2&object_id=$3&
was causing the issue then

I do not know which API Version DSub is using but this would be the app: 
https://f-droid.org/de/packages/github.daneren2005.dsub/

Anyways I think you can close it now as it is solved.

**Comment by manuelglez86** [comment]
ok. thanks will close it
