### ISSUE TITLE
Adding new Podcast Episodes Sometimes Skips Episodes

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3279]
### Describe the bug
Occasionally, podcast RSS feeds are updated out-of-step with the last update time.  This is due to the RSS feed being updated AFTER the last update time, but including a podcast with a timestamp from before.

### To reproduce
This is not reproducible by normal means because it depends on podcast RSS feed updates and frequency of checking for new podcasts.  However, the flow would look like this:

1. Podcast RSS feed checked (or synced) at 5am (local time). 
2. Podcast RSS feed is updated by the producer at 5:10am to add the latest podcast episode.
3. The newly added podcast episode has a timestamp of 4:40am.
4. The next time Ampache checks the RSS feed, the new episode is skipped since the add time is before the last checked time.

Another example:
A podcaster is covering a music festival and records a concert at 7pm every night Monday through Friday, but waits until noon Saturday to update the RSS feed with all the concerts using the pubDate corresponding to 7pm on each respective day the concert happened.  Ampache, by default, updates the Podcast catalog at 10pm local time.  So the last sync time is Friday at 10pm, when the RSS feed did NOT have the concerts listed.  On Saturday night at 10pm, Ampache will check again.  This time there are 5 new episodes listed, all with a pubDate from earlier in the week.  Ampache will NOT add these new episodes since the pubDate was before the last sync date.

This happens more time that you would expect, and we can argue about the pubDate field not being used to correctly indicate the publication date and not the date on which the even occurred, but I can control what podcasters do with their feeds.  This problem can even get down to the time level where a podcaster may only use a pubDate with the correct date but the time portion is set for midnight.  Either case, the timestamps will cause episodes to be skipped.

### Expected behavior
I would expect the new episode to somehow be checked to see if it already exists in the episode database regardless of publish time.
I have seen log entries that indicate some episodes are skipped as their URLs already exist, so I know the system has some method of detecting duplicates.

## Environment

* Ampache version: DOCKER Develop digest c948be4570b8
This is a server issue, not a client issue

## Logs
This is indicated by the log entry "Episode published before...".  Comes from src/Repository/Model/Podcast.php line 579.

**Comment by troycarpenter** [comment]
Some more info...I have modified the system cron to update the Podcast catalog every hour on the half hour.

I have verified that by changing the lastsync field in the podcast database for this particular podcast to midnight and running a sync, the episode gets added.  This seems to be a timing issue for this particular podcast between the timestamp on the episode vs. when the podcast rss feed is actually made available.

Making the cron job run less frequently could help mitigate the issue, but I don't think there is any way to actually eliminate the race condition based on current code.   I also don't know without deeper analysis how the system knows a podcast is new without relying on the timestamps.

**Comment by troycarpenter** [comment]
Apparently this has been happening on a number of my podcasts.  The best way I can explain it is that the podcast originators are adding content to their podcast AFTER the last time Ampache checks the podcast, BUT are backdated to when the podcast episode first aired.

Right now to avoid missing podcast episodes in the future, I have changed the cronjob (ampache_cron.sh) to update my podcasts at 7am, noon, and 6pm local time.

BUT that does not help for podcast content creators that back-date their pubDate fields.

**Comment by troycarpenter** [comment]
Oh, and I understand why using the pubDate/lastsync comparison is helpful.  I once had a paid subscription podcast where everyday the podcast links changed, even for past episodes in an attempt to prevent the links from being shared to avoid paying the subscription.  Another podcast app I used had a subpar way to detect duplicates and ended up downloading the same episodes every day just because the URL was not the same as before.

**Comment by lusum** [comment]
Can you post the url of a podcast that shows this behaviour?

**Comment by troycarpenter** [comment]
I can't.  But I did describe the race condition that causes it.

**Comment by lachlan-00** [comment]
i saw this when i added the always sunny podcast.
what it should do is add them but not download them.

instead it just never adds the episode at all. i'll change that behaviour to add all episodes but only download recent ones (episodes published in the last month from the date of add)

**Comment by lachlan-00** [comment]
feed for reference if you want to see the behaviour
https://feeds.simplecast.com/eoftDcQK

**Comment by troycarpenter** [comment]
I haven't seen this lately.  Going to close.
