### ISSUE TITLE
random playlist in subsonic client select musics in unavailable catalog of another user

### ISSUE THREAD

**Issue by tigermick** [ampache/ampache#3290]
### Describe the bug
I have an ampache server and I enabled the per user privates catalogs in config file.
I use ultrasonic to play music on ma android smartphone because I can use random playlist.
the problem is random playlist select musics in unavailable catalog for my account.

If I try to create a random playlist in web interface of ampache, it seems to be all work fine and no musics in unavailable catalog is selected.

I'm not sure but I think the problem is about subsonic backend.

### Expected behavior
normaly I think I shouldn't find musics of an unavailable private of another user catalog when I create a random playlist in android ultrasonic app

## Environment

* Ampache version: 5.4.0
* Web server + version: apache 2.4.53
* Server operating system: Debian
* Client operating system: ampache web interface and android ultrasonic app

### Client type

 Web
 Ampache
* SubSonic
 DAAP
 UPnP
 WebDAV

**Comment by troycarpenter** [comment]
This bug should be fixed with the expanded catalog filter feature.  See the discussion of that here: #3244

**Comment by troycarpenter** [comment]
https://github.com/ampache/ampache/wiki/catalog-filters

**Comment by lachlan-00** [comment]
@tigermick this update should convert all your private catalogs over into groups, i've tested it multiple times but let me know if this all works how you expect.

The wiki gives an example of how it would be converted over. If you're waiting for stable 5.5.0 will come out in probably 4ish weeks after i get 5.4.1 out

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
