### ISSUE TITLE
Artist and Album explicit selection during File Upload are ignored. License selection fail.

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#3292]
## Description
Artist and Album explicit selection during File Upload are ignored. License selection fail.

### Describe the bug
When the user has proper permissions or 'owns' an artist, he can explicitly select the targeted artist/album where to add the song being uploaded. But this is now ignored. It used to be handled this way on previous Ampache versions: https://github.com/ampache/ampache/blob/4cb8ea10232b90fe71013ac02f90dbbb241f9db5/lib/class/upload.class.php#L99

Moreover the "license" field doesn't seems to work anymore neither during song upload as the $_POST['license'] contains the license id and the lookup is being made for license name on: https://github.com/ampache/ampache/blob/b27a031c795944a87efddb7ffb4a930791f5e7c4/src/Repository/Model/Song.php#L466
We may want to change the license form select to be populated with values from license name instead of license id now?

### To reproduce

1. Go to Upload section and try to upload a file with explicit artist/album selection, and optionally a license.

### Expected behavior
Replace artist/album and set the song license according to the user explicit selection.

## Environment

* Ampache version: 5.4.0
* Web server + version: Apache2
* Server operating system: Debian

### Client type

* Web

## Settings

File upload is enabled.

**Comment by lachlan-00** [comment]
ID for license with d61194094

**Comment by lachlan-00** [comment]
Selection is respected and new objects are created
![image](https://user-images.githubusercontent.com/1305249/188546115-34bb8a40-74df-4f23-98bb-77b67beb631b.png)

**Comment by lachlan-00** [comment]
OK, new behaviors

Upload a song and create an artist + album
![image](https://user-images.githubusercontent.com/1305249/188555764-65da65af-0e84-4902-9bf8-245c08cdf5e4.png)

* Both new items are created and assigned to the song
* The new artist is the 'albumartist' for the album (same when using an existing artist)
* When updating from tags **do not** overwrite a custom artist / custom album+albumartist

![image](https://user-images.githubusercontent.com/1305249/188556104-5975aadc-9903-4575-9d3c-89d53e05f4e1.png)

As album doesn't have an owner column i can't extend this to albums unless that table is extended this should cover most cases

This will go to the next update 5.5.2

**Comment by Afterster** [comment]
Ok great @lachlan-00. I've been a bit busy these days starting a new business but I'm still giving some support to Dogmazic folks who want to upgrade their version and will give another try/test with 5.5.2 and see if that match their expected behavior.

Thanks for your work.

**Comment by lachlan-00** [comment]
Let me know if there's anything else missing.  5.5.x releases will be all bug fixes from now on until 6

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
