### ISSUE TITLE
Statistics no longer showing

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3304]
Hi all,

Just a quick one, I'm on the latest develop commit and the Statistics page has stopped showing for me?

I get the following error in the ampache logs:

``(/var/www/html/ampache/resources/templates/stats.xhtml:67) -> Ampache\Gui\Catalog\CatalogDetails object  doesn't have method/property named 'getFilterUser' ``

Probably related to the per user catalogue features recently added?

**Comment by lusum** [comment]
For me too, same error, i would have opened this bug now.

**Comment by troycarpenter** [comment]
What is the goal with that method?  It would appear to indicate whether the catalog is specific to a user or if it's public, which means that column probably isn't valid any more with the newer catalog feature.

Also, I think that statistics for non-authorized catalogs should be hidden from the user.  The last thing an admin wants is for users to know what catalogs are available and start asking for access to those catalogs.  The admin denied access for a reason, I would guess.

**Comment by lachlan-00** [comment]
also needed the column header but all merged now
