### ISSUE TITLE
Blank screen - No handler found for action "show"

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3310]
The latest develop commit (2639d66ab) gives me a blank screen and throws the following error in the ampache log:

``(Ampache\Module\Application\ApplicationRunner) -> No handler found for action "show"``

Reverting back to ae422ecee brings everything back

**Comment by troycarpenter** [comment]
I've seen this as well.

**Comment by troycarpenter** [comment]
There are a lot of changes between  commit [ae422ec](https://github.com/ampache/ampache/commit/ae422eceedb00b8ee1de449ae3250ba7502fdd65) and now.  I'm hoping @lachlan-00  will be able to quickly see the problem.

**Comment by lachlan-00** [comment]
reverted, there's a strict type issue with one of hte show's.
