### ISSUE TITLE
[Feature Request] For Podcast dashboard (and possibly others as well), move "Newest" section to top

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3311]
On the Podcast dashboard, my users are most interested in the newest podcasts, not what is trending.  I would like to see the "Newest" section moved to the top, or in the best case, an option that allows the user to set the order.

I see that the other dashboards are arranged in the same sections.  I would NOT expect there to be options for each (albums, artist, playlists) to be configurable, but would not be opposed to it either.

This is found at Home -> Dashboards

**Comment by troycarpenter** [comment]
I have modified public/templates/show_mashup.inc.php and changed the three sections into functions:
~~~
  showNewest()
  showTrending()
  showPopular()
~~~

For actually displaying the sections, I have this logic:
~~~
if ($object_type == 'podcast_episode') {
    showNewest();
    showTrending();
    showPopular();
} else {
    showTrending();
    showPopular();
    showNewest();
}
~~~
It makes sense that the other types can be sorted by trending and popular since it's not as common to add new music content to the library; however, podcasts are usually generated on a schedule (sometimes daily) and it is more interesting to know what the newest episodes are.

We can discuss whether this is a change that makes sense for everyone and should go into a release, or if I just keep it local for myself.

**Comment by lachlan-00** [comment]
i would do it for all of them but lets do this after 5.5
i'm going to work on 6 after that so we can look at 5.5 in september and then 6 after that

**Comment by troycarpenter** [comment]
The more I've thought about this one, the more it makes sense to me that music types (albums, artists, playlists) would keep the trending and popular higher than newest since people would be more interested in those categories for music, whereas for the podcast episodes it makes more sense to me to keep the newest on the top row.

In either case, I'm sure not everyone agrees on the section order, and whether the order presented in the different tabs should be disjointed.  If it's going to be roadmapped to 6.0, then it should be made configurable with the default being the current order.

**Comment by troycarpenter** [comment]
For now I've got my custom order and I'm pushing the custom show_mashup.inc.php into my docker image via docker-compose.

**Comment by lachlan-00** [comment]
set in 6 now
