### ISSUE TITLE
Podcast_episodes response not following API version

### ISSUE THREAD

**Issue by memen45** [ampache/ampache#3317]
### Describe the bug
Version parameter in handshake is not followed on podcast_episodes request (always Ampache5 response). This causes issues with SubMusic app or any other Ampache4 client (see issue memen45/SubMusic#54)

### To reproduce

1. Send handshake API request with parameter `version=440000`
2. Send podcast_episodes API request for any podcast id
3. Receive Ampache5 response schema i.e. `{ "podcast_episodes": [•••] }`

### Expected behavior
3. Receive Ampache4 response schema i.e. `[•••]`

## Environment

* Ampache version: 5.4.1

### Client type

* SubMusic (any other Ampache4 client)

**Comment by lachlan-00** [comment]
looks like a copy/paste of 5.
i'm reducing the response to the example. it looks like it included the object as well so fixing that. might be some more so i'll check for others

https://raw.githubusercontent.com/ampache/python3-ampache/api4/docs/json-responses/podcast_episodes.json
https://raw.githubusercontent.com/ampache/python3-ampache/api4/docs/xml-responses/podcast_episodes.xml

**Comment by lachlan-00** [comment]
at a glance it's weirdly the only one that seems to have been copied form api5.

fixed with f1eee168d and 128c84a39

**Comment by lachlan-00** [comment]
actually, scratch those. i just looked at the last 4.4 release and they're correct but the examples are not. i need to update those instead and i'll verify against the old release first

**Comment by memen45** [comment]
I think Ampache4 used to return just the array of results, whereas Ampache5 returns an object with a single key containing the array of results. 

So only difference is 
Ampache4: `[{•}, {•}, ...]`
Ampache5: `{ "podcast_episodes": [{•}, {•}, ...] }`

I don't know whether the keys inside the array objects (i.e. the podcast episode properties) changed in between versions. Do you think they changed too?

**Comment by lachlan-00** [comment]
that's right the object shouldn't be there in 4. i've updated the docs online and they should be corrected in Ampache develop as well now.

The links above have been updated and you've prompted me to fix up a lot of the missing stuff in the older versions

**Comment by lachlan-00** [comment]
there was also a bug with get_indexes and podcast_episodes so i think this should all be covered now

**Comment by memen45** [comment]
Great to hear it is resolved and thanks for your fast response!
