### ISSUE TITLE
Podcasts search errors

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3318]
Just testing the brilliant new podcast search features and found that the Podcast page #search.php?type=podcast returns correct results but generates a runtime error in the logs:

``(log.lib) -> [Runtime Error] Undefined array key "podcast_episode" in file /var/www/html/ampache/src/Repository/Model/Search.php(3015)
``

And the Podcast Episodes page #search.php?type=podcast_episode generates the same runtime error as above but also an SQL error and fails to return any results:

``(Ampache\Module\System\Dba) -> Error_query SQL: SELECT DISTINCT(`podcast_episode`.`id`), `podcast_episode`.`title` FROM `podcast_episode`  WHERE `podcast_episode`.`title` LIKE ? ORDER BY `podcast_episode`.`pubdate` DESC ["%science%"]
(Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'ampache.podcast_episode.pubdate' which is not in SELECT list; this is incompatible with DISTINCT``

**Comment by lachlan-00** [comment]
those should both be fixed with the last 2 commits.

**Comment by rsinfotech** [comment]
Both fixed :+1: 

Loving the new functionality, thanks for all your hard work and dedication

**Comment by lachlan-00** [comment]
thanks! i want to fit a lot in here as 5.5.x will probably be the last ampache5 release before 6
