### ISSUE TITLE
Default art order changed?

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#3325]
## Description
In the ampache.cfg dist file, the default art order was changed, but the description has not. Not sure which is now correct.

### Describe the bug
From ampache.cfg.php.dist, lines 639-640:
`; DEFAULT: db,tags,folder,spotify,musicbrainz,lastfm,google

art_order = "db,spotify,TheAudioDb,musicbrainz,lastfm,tags,folder"`

**Comment by lachlan-00** [comment]
it has changed but not on purporse,

should be more like `db,tags,folder,spotify,musicbrainz`

**Comment by SimonHova** [comment]
It's fine, I just wanted to point it out so you could update the config file for the next release. Feel free to close the issue. Thanks again.
