### ISSUE TITLE
"Add to Temporary Playlist" adds item in reverse order

### ISSUE THREAD

**Issue by jasminemoeller** [ampache/ampache#3327]
### Describe the bug
Multiple items added to a temporary playlist in one step are added in wrong order. Most of the time order is reversed, but sometimes I've also seen completely random orders (I could not reproduce this reliably though)

### To reproduce

1. Navigate to any album containing more than one song
2. Click on 'Add to Temporary Playlist'
3. Playlist is populated in wrong order.

Same also happens with e.g. Enqueue from a Random search (Probably any kind of operation that creates a temporary playlist in one batch)

### Expected behavior
Playlist should be populated in album resp. search result order - see screenshot

### Screenshots
![wrong temp order](https://user-images.githubusercontent.com/8457716/186927511-da3b3802-8738-439d-8325-99c67a0c5d7e.png)

## Environment

* Ampache version: 5.5.1-release (but could also reproduce with e.g. 5.2.0)
* Web server + version: Apache 2.4.54
* Server operating system: Debian 11
* Client operating system: Windows 11, both chrome and firefox

Note that the backend runs in a docker container which is proxied by an NGINX reverse proxy, however I'm not sure whether this is relevant or not...

### Client type

* Web

I can provide the config and logs as well if you cannot reproduce this on your side - I'm also willing to debug this on my side if given some pointers (preferably if this should happen on the client side, i.e. Java Script)

**Comment by jasminemoeller** [comment]
Okay, I think in src/Repository/Model/Tmp_Playlist.php#get_items the SQL query in the "cookie" code path also needs an ORDER BY `id` like in the "try to guess" branch... Should I create a commit/pull request?

**Comment by lachlan-00** [comment]
i'll update this now. it shouldn't update by id either as that can't be used to determine order accurately even though a lot of the time that will be right.

will fix

**Comment by lachlan-00** [comment]
set with c246fa8ec
