### ISSUE TITLE
Update title tag in page header with Ajax page load

### ISSUE THREAD

**Issue by DJ-SteffEN** [ampache/ampache#3329]
### Describe the bug
The content of the HTML tag <title>...</title> is not updated

### To reproduce
Setting: Server Preferences - Interface - 'Ajax page load' = ON
No matter where you move the title tag is not updated.
The function get_location in the funktion.php is missing information here.

### Expected behavior
The title tag should change accordingly though, I think.
The problem arises from the URL expansion when using Ajax.
If you turn off 'Ajax page load' the function does exactly that.
Can this be fixed, or can someone tell me how to get the usable 'REQUEST_URI' there.

## Environment
* Ampache Version: Ampache-5.4.0_all_php8.0
   (Unfortunately from 5.4.1 to 5.5.1 the video in the web player no longer works)
* Web Server + Version: Apache 2.4.54
* Server OS: Debian 11.0/64 bit
* Database: MariaDB 10.8.3
* PHP: version 8.1.9
* Client operating system: Windows 10 (test with Chrome and Edge)

**Comment by DJ-SteffEN** [comment]
Hello,

I have solved the problem as follows (see additions in 'header.inc.php').
The title tag is already overwritten via Ajax before the page is fully loaded.
I adjusted and extended the function get_location() in the function.php.
This better describes the action of the user (just like the ajax call).

![my-changes-from-header inc php](https://user-images.githubusercontent.com/111641714/188725161-856f8f90-821e-48c8-95dd-c512cb330642.jpg)
[my-get_location-from-function.txt](https://github.com/ampache/ampache/files/9500251/my-get_location-from-function.txt)

with kind regards
DJ SteffE.N.

**Comment by lachlan-00** [comment]
thank you!

I will integrate that tomorrow. do you want to do it as a pull or happy for me to just merge it?

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

you are welcome and do it the way it suits you best.

with kind regards
DJ SteffE.N.

**Comment by lachlan-00** [comment]
little bit of tweaking to make it the same as titles for playback but it's merged now. I just a bit more out and made index pages just the site title

Thanks for your time looking and id'ing this. :)
