### ISSUE TITLE
Issue from Ampache version 5.4.1 - web player does not play videos - see https://ampache.org/demo.html

### ISSUE THREAD

**Issue by DJ-SteffEN** [ampache/ampache#3331]
## Description
Videos can no longer be played, I have tested several formats (That's why I stayed with Ampache 5.4.0).

### Describe the bug
When starting a video in the web player, the preview window rises only wafer-thin, then everything breaks off. Although there is no playback, the system can still be operated.

### To reproduce
I observe the same behavior as seen on https://ampache.org/demo.html (also see my screenshot).

### Expected behavior
Play Video

### Screenshots
![image](https://user-images.githubusercontent.com/111641714/187049526-08bee512-185e-435b-beeb-0994b58a1fd5.png)

## Environment
Debian 11.0/64 bit, Apache/2.4.54, MariaDB 10.8.3, PHP 8.1.9, Ampache-5.4.0_all_php8.0

### Client type
* Web

## Settings
[my-ampache.cfg.php.txt](https://github.com/ampache/ampache/files/9438758/my-ampache.cfg.php.txt)

## Logs
I turned on the web player log but unfortunately found nothing usable in the ampache log.

Kind regards
DJ SteffE.N.

**Comment by lachlan-00** [comment]
i think i know what this is, the formats were explicitly set in jplayer to fix a format bug and there aren't video formats in the list.

![image](https://user-images.githubusercontent.com/1305249/187611404-178335ad-5ca8-4c61-add7-65a72a2f26b5.png)

**Comment by lachlan-00** [comment]
next stable patch will include 4be6dde61
and it's fixed in develop with c956b559a

**Comment by lachlan-00** [comment]
tested, i'm goign to release a 5.5.2 to address this and any other bugs people pick up in a week or 2
