### ISSUE TITLE
PHP error when inserting art

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#3335]
## Description
When inserting art, I can sometimes hang the server.

### Describe the bug
This happens when I put in album and/or artist art, but sporadically. Can't tell if it's a resource issue, but the debug log is not useful and the PHP/HTML service has to be restarted.

## Logs
2022/08/31 12:36:46 [error] 16434#16434: *2949 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function has_access() on string in /opt/ampache/src/Repository/Model/Art.php:1494
Stack trace:
#0 /opt/ampache/public/templates/show_artist_info.inc.php(35): Ampache\Repository\Model\Art::display()
#1 /opt/ampache/src/Application/Api/Ajax/Handler/IndexAjaxHandler.php(153): require_once('...')
#2 /opt/ampache/src/Application/Api/Ajax/AjaxApplication.php(90): Ampache\Application\Api\Ajax\Handler\IndexAjaxHandler->handle()
#3 /opt/ampache/public/server/ajax.server.php(35): Ampache\Application\Api\Ajax\AjaxApplication->run()
#4 {main}
  thrown in /opt/ampache/src/Repository/Model/Art.php on line 1494" while reading response header from upstream, client: xx.xx.xx.xx, server: xx.xx.net, request: "GET /server/ajax.server.php?page=index&action=artist_info&artist=6281 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "xx.xx.net:5006"

**Comment by lachlan-00** [comment]
it's an empty global in the checks, i'm adding pre-checks with ff6f9b5a8
