### ISSUE TITLE
[Bug Report] Album Artist Browse Filter shows artists from other catalogs

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3339]
## Description
I'm going to call this a bug right now because it's unwanted behavior that seems to happen during normal usage.  This is happening after heavy tagging/clean/update/verify actions.  I have not done any code investigation to see if I can find anything.

### Describe the bug
When using the browse per catalog feature from the home screen, artists from other catalogs are showing up in the listing when they should not.

For instance, Artist A is in Catalog 1.  Artist B is in Catalog 2.  When I select "Home ->Browse->Album Artist", then select Catalog 1.  I see Artist A and Artist B, but Artist B should not be listed.

Note that this doesn't necessarily happen on all catalogs.  I've currently got one or two catalogs that only list the artists from that particular catalog.

### To reproduce

Select "Home ->Browse->Album Artist",
Cycle through the catalogs in the filter to see if any artists appear that should not be listed.

### Expected behavior
I expect only the artists that have albums in the current catalog would be listed.

### Screenshots
![image](https://user-images.githubusercontent.com/8419000/188245844-6214860e-3443-4a86-9405-edb1da522c08.png)
In this screenshot, I am showing album_artists for the Classical catalog.  There is only one artist listed that should actually be there (Academy of St Martin in the Fields), but the others all belong exclusively to other catalogs (no crossover with the Classical catalog) and should not be listed.

In the past, the only way I've found to fix this is to move all albums of the "offending" artists outside of the catalog directory and do a clean to remove the artist and albums from the database, then move the albums back into the catalog and do an add to put them back.  Once that's done, the artist will appear in the correct catalog.

The drawback to the workaround is that album/artist art must be redone, and it takes a long time.

## Environment

* Docker Develop version

### Client type

* Web

**Comment by lachlan-00** [comment]
I can see it. It will be in the query/browse class. But shouldn't be hard to find as it's easy to see so easy to fix.

One of the commented debugs in query will tell me the one to fix.

**Comment by lachlan-00** [comment]
there are rows left in catalog_map for artists that shouldn't be there so the queries are working but the data needs to be fixed

**Comment by lachlan-00** [comment]
these queries should be sorted now.

A clean should redo the garbage collection but these are the queries
```
INSERT IGNORE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist_map`.`artist_id` FROM `song` LEFT JOIN `artist_map` ON `song`.`id` = `artist_map`.`object_id` AND `artist_map`.`object_type` = 'song' WHERE `song`.`catalog` > 0 GROUP BY `song`.`catalog`, 'artist', `artist_map`.`artist_id`;
INSERT IGNORE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `album`.`catalog`, 'artist', `artist_map`.`artist_id` FROM `album` LEFT JOIN `artist_map` ON `album`.`id` = `artist_map`.`object_id` AND `artist_map`.`object_type` = 'album' WHERE `album`.`catalog` > 0 AND `artist_map`.`object_type` = 'album' GROUP BY `album`.`catalog`, 'artist', `artist_map`.`artist_id`;
DELETE FROM `catalog_map` USING `catalog_map` LEFT JOIN `artist_map` ON `artist_map`.`artist_id` = `catalog_map`.`object_id` WHERE `catalog_map`.`object_type` = 'artist' AND (`artist_map`.`artist_id` IS NULL);


```

**Comment by troycarpenter** [comment]
So is there a code change that would cause the clean to work now?

Also, after I did those queries, I still saw the album artists in the wrong place.  Here's what I saw:
```
MariaDB [ampache]> INSERT IGNORE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist_map`.`artist_id` FROM `song` LEFT JOIN `artist_map` ON `song`.`id` = `artist_map`.`object_id` AND `artist_map`.`object_type` = 'song' WHERE `song`.`catalog` > 0 GROUP BY `song`.`catalog`, 'artist', `artist_map`.`artist_id`;
Query OK, 0 rows affected, 3327 warnings (0.559 sec)
Records: 3327  Duplicates: 3327  Warnings: 3327

MariaDB [ampache]> INSERT IGNORE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `album`.`catalog`, 'artist', `artist_map`.`artist_id` FROM `album` LEFT JOIN `artist_map` ON `album`.`id` = `artist_map`.`object_id` AND `artist_map`.`object_type` = 'album' WHERE `album`.`catalog` > 0 AND `artist_map`.`object_type` = 'album' GROUP BY `album`.`catalog`, 'artist', `artist_map`.`artist_id`; 
Query OK, 0 rows affected, 620 warnings (0.055 sec)
Records: 620  Duplicates: 620  Warnings: 620

MariaDB [ampache]> DELETE FROM `catalog_map` USING `catalog_map` LEFT JOIN `artist_map` ON `artist_map`.`artist_id` = `catalog_map`.`object_id` WHERE `catalog_map`.`object_type` = 'artist' AND (`artist_map`.`artist_id` IS NULL);
Query OK, 0 rows affected (0.070 sec)
```
Running the queries a second time gave the same results.  Warnings on the INSERTs, then nothing deleted.  Is that what was expected?

**Comment by troycarpenter** [comment]
I'm on the latest Docker image.  I just did a "Clean All" command, but nothing changed with respect to the album_artists.  There wasn't anything added to try to address this situation?

I just tried those DB commands again, but the result was the same.

**Comment by lachlan-00** [comment]
that must mean the artist_maps for those extra artists are wrong somehow which is then being put into catalog_map

I did have a lot of bad rows in the catalog_map before but they're all cleared now

on the artist when you're filtered do you get any albums/data or is the page empty?

**Comment by troycarpenter** [comment]
I've never thought much about the browse filter from an artist page.  In my experience, the artist page always shows all the albums of that artists regardless of what browse filter is set (not to be confused with the catalog filter set for that user, which does work). 

I've only seen the browse filter work with songs, albums and album_artists from the "browse" section on the left menu.  As I said, once I go into an artist, it tends to show me all the the artist's albums, and not limited by the browse filter.  Is that a bug, too?

So what am I looking for in the artist_map and catalog_map table that would cause this, and how do I change it?  If I clear those database tables and do a verify command, would that rebuild them?  As I look at those maps, my guess is that the artist somehow has an entry for a song or album entity,  which may no longer be there physically but is mapped to the catalog in question.

Here's an idea: I noticed that when data changes for an album (and maybe an artist) via a verify or update from tags, that Ampache will create a new entity with the new data and "delete" the original entity ID.  I can't tell if the new entity ids are being recycled.  Is it possible that the new entity ID (album or artist) is reusing an older ID that, while no longer in use, hasn't been cleared from the artist/catalog maps, and therefore the system incorrectly thinks the artist is part of the catalog when it was actually the previous entity that was mapped to that catalog?  Does that question make sense to you?

**Comment by troycarpenter** [comment]
Am I misinterpreting this result:
```
MariaDB [ampache]> select * from album_map where object_id=3609 and object_type='song';                    
+----------+-----------+-------------+
| album_id | object_id | object_type |
+----------+-----------+-------------+
|     5976 |      3609 | song        |
|     5978 |      3609 | song        |
+----------+-----------+-------------+
2 rows in set (0.001 sec)
```
Doesn't that say that the song with ID 3609 is showing up on two different albums?
And when I look up those two albums, neither one is the correct album for that song.  The correct album_id for that song is 6471;

Let me see if I can correct the database entries for the catalog/album/artist maps for this one and see if the artist is removed from the incorrect catalog list.

**Comment by troycarpenter** [comment]
Along those same lines, how to I interpret this:
```
MariaDB [ampache]> select * from album_map where album_id=6471;
+----------+-----------+-------------+
| album_id | object_id | object_type |
+----------+-----------+-------------+
|     6471 |       114 | album       |
|     6471 |       114 | song        |
+----------+-----------+-------------+
2 rows in set (0.001 sec)
```
or better yet:
```
MariaDB [ampache]> select * from album_map where object_id=114;
+----------+-----------+-------------+
| album_id | object_id | object_type |
+----------+-----------+-------------+
|     6471 |       114 | album       |
|     6442 |       114 | song        |
|     6461 |       114 | song        |
|     6466 |       114 | song        |
|     6471 |       114 | song        |
|     6477 |       114 | song        |
+----------+-----------+-------------+
6 rows in set (0.001 sec)
```
My bafflement tells me I don't really understand what the rows represent in the album_map table.

**Comment by troycarpenter** [comment]
I actually think I may have found some catalog_map problems.  For instance, to show me all catalogs that artist_id 540 is a part of:
```
MariaDB [ampache]> select * from catalog_map where object_id=540;
+------------+-----------+-------------+
| catalog_id | object_id | object_type |
+------------+-----------+-------------+
|          4 |       540 | artist      |
|          5 |       540 | artist      |
|          6 |       540 | artist      |
|          7 |       540 | artist      |
|          8 |       540 | artist      |
|         10 |       540 | artist      |
|         11 |       540 | artist      |
|         13 |       540 | artist      |
|         14 |       540 | artist      |
|         22 |       540 | artist      |
|         23 |       540 | artist      |
+------------+-----------+-------------+
11 rows in set (0.000 sec)
```
BUT, what I notice is that there are entries there for catalogs that do NOT exist.  Specifically, catalogs_id 4 and 22 do not exist.  Also, catalog #5 is the one in question for the original bug.  This is a prolific artist that appears in almost all of my catalogs, but this artist does NOT have an album in the Classical catalog, nor does this artist credited on any song track in that catalog.

Removing the row for this artist where catalog_id = 5 did remove the artist from the album_artist list for that catalog.

**Comment by troycarpenter** [comment]
Is there or can there be a CLI command that rebuilds the maps?  It looks like there's a lot of errant data, especially in the catalog_map, were entries should no longer be there.

I'm guessing the easiest way to rebuild the maps would be to look through the album database to find the catalog that each album is in.  Then look at the album artist for that album and create an entry in the catalog map for that album.  It might actually be better to build this data from the songs database instead of the album database since that's where the real information lies.

**Comment by troycarpenter** [comment]
Just thinking through this.  I am not a SQL expert by any means.

For each album in the album_id in the album table, look in the album_map table to find all the album artists for a particular album, then create an entry for each of those album artists in the catalog_map table using the catalog of the album.

First, create a list of all distinct rows from the album database for catalog and artist.
```
SELECT DISTINCT catalog,album_artist from album; 
```
But that only gives "primary" album artists.  Then we need to add into it secondary artists for this album from album_map.  The query now becomes:
```
SELECT DISTINCT album.catalog,album_map.object_id FROM album_map LEFT JOIN album ON album.id=album_map.album_id WHERE album_map.object_type='album' ORDER BY album.catalog,album_map.object_id;
```
Which should give a complete list of <catalog, album_artist> (sorted by catalog_id then artist_id) that needs to be put into catalog_map with an object_type of 'artist'.

I also expect it would be prudent to delete all catalog_id records where object_type='artist' before adding the list.  I've verified the special podcast catalog is not affect by that.

That should "rebuild" the catalog_map for artists.  Something similar should probably be done to rebuild the catalog_map for songs as well.

**Comment by lachlan-00** [comment]
there will be places to simplify this a lot more too as the album_count is in the artist table as well

**Comment by troycarpenter** [comment]
Good deal.  I don't know if this was understood, so forgive me if I'm stating something known, but this is for album_artists only, not any old artist that appears on a track as an artist.  I think that's implied by the data that I see in the artist_map and catalog_map tables.

**Comment by troycarpenter** [comment]
Also, as mentioned above, I found at over 100 rows in the catalog_map table for catalog_ids that no longer exist.  I went ahead and manually deleted them, but I'm wondering if there is something that is supposed to catch those old entries?

**Comment by lachlan-00** [comment]
I'm going to try and break this down a bit more and try to spend a bit of time on it.

For your artists that shouldn't be anywhere it's possible they're mapped for something that shouldn't be there and we'll need to track it down. the previous stuff i did fixed what i can see for me but i'll probably need to do a bit more digging to make it automated for everyone.

**Comment by lachlan-00** [comment]
hey @troycarpenter i'm going to be away for about 2 weeks soon so if you could do something for me i'll look at this again when i get back.

If you could dump your db with probably album, album_map, artist, artist_map, catalog, catalog_map and song that should probably allow me to try and work this out a bit more.

feel free to not do this but if you do jsut give me some examples of who's wrong and i'll see what i can do.

another thing to do is to update_from_tags on the artist/albums that you see and see if the maps are removed.

**Comment by troycarpenter** [comment]
I will see if I can get the database for you.  I have manually corrected most of my catalogs, but there are at least one or two catalogs I have not made the manual corrections.  However, whether or not I get the database, what I find is that for any artist that shows up in the wrong catalog, it is always because there is an entry in the catalog_map table for that artist with the wrong catalog_id.  I know how to fix the situation, what I'm more wondering is how those extra entries got into the database to begin with.

**Comment by troycarpenter** [comment]
Just sent an email with a link to where I posted the database.

**Comment by lachlan-00** [comment]
i also found some issues with migration of data that might create false maps in the database.

**Comment by lachlan-00** [comment]
@troycarpenter i've set that up on a running test server now. so lets go back to the start.

Going back to your initial picture i should be able to filter the catalogs and see the joins/issues.

From there i'll look at which queries are causing this and then probably get you to test some updated files.

I think what's happening is that the maps for artists are not being removed/queried correctly in some part which is creating the extras. but you have a lot of catalogs which is good for testing.

**Comment by lachlan-00** [comment]
@troycarpenter can you pick someone off the top of your head who shouldn't be in the lists for the classical catalog (id 5)

This query runs on the catalog_map and artist_map table and prints out the catalogs that match
```
SELECT `artist`.`name`, `artist`.`id`, `catalog_map`.`catalog_id` FROM `artist`
LEFT JOIN `catalog_map` ON `catalog_map`.`object_id` = `artist`.`id` AND `catalog_map`.`object_type` = 'artist'
WHERE `artist`.`id` IN (SELECT `artist`.`id` FROM `artist`
                        LEFT JOIN `catalog_map` ON `catalog_map`.`object_id` = `artist`.`id` AND `catalog_map`.`object_type` = 'artist'
                        WHERE (`catalog_map`.`catalog_id` = 5) AND  `artist`.`id` IN (SELECT `artist_id` FROM `artist_map` WHERE `artist_map`.`object_type` = 'album')
                        GROUP BY `artist`.`name`, `artist`.`id`, `catalog_map`.`catalog_id`)
ORDER BY `artist`.`name` ASC;
```

Then if i know who's not there now it should be easier to work out where the extra maps are

**Comment by troycarpenter** [comment]
The problem I have is that I think I may have already cleaned up that catalog.  Let me see what I can do from one that may not be cleaned up yet.

**Comment by lachlan-00** [comment]
thanks for taking the time it's been helpful and i think it's down to the `catalog_map` table AND only for artists. the albums and songs are respected.

I'm going to merge the big change today and then work on this. I think we've got the table and now the data to find it

**Comment by lachlan-00** [comment]
I think i've found the case and a fix to the query to delete these, i'll test on my copy of your DB  first

**Comment by lachlan-00** [comment]
ok, i've got one part fixed. i found maps that shouldn't be there and have cleared those ones. 

Now that the incorrect/old maps are deleted i can see that there isn't a differentiation between a catalog_map album_artist or a song artist

So it's valid for your artists to be there because they're an artist in the map but Alison Krauss shouldn't be an album_artist but there is no way to tell
![image](https://user-images.githubusercontent.com/1305249/198174107-ac3989fb-7db8-4c18-a684-e93f91c9ff95.png)

**Comment by lachlan-00** [comment]
OK, this is going to be fixed and i'll make a separate patch for 5.5.

Just have to test and make sure things are all okay after the change

**Comment by troycarpenter** [comment]
I have tested with latest develop version 6.0 DOCKER image and all the errant entries are gone.

**Comment by lachlan-00** [comment]
yeah boi!

that was a lot of thinking for it all to be so simple

**Comment by troycarpenter** [comment]
I'm going to close this since it's working now.
