### ISSUE TITLE
Duration time of songs not displayed

### ISSUE THREAD

**Issue by Xaapyks** [ampache/ampache#335]
Hello,

I know of issues #135  and #150 but I am not sure my issue is related to them.
#150 is marked as resolved whereas I have this issue right now on develop branch.

I use transcoding with avconv to ogg. Switching for mp3 as target codec does not solve it.
I am using the default ogg string of parameters to avconv for libvorbis.

I do see the duration flashing for like 300msec at the start of the song start and then it goes to 00:00. The "current elapsed time" is working correctly.
I see this flashing behavior both with the HTML player and through vlc playlists.

I wanted to try switching from avconv to ffmpeg but I did not find a correct argument list to encode as ogg. If someone has a working one, I can try to see if avconv is the culprit.

**Comment by Afterster** [comment]
All remaining issue are related to how 'client' handle the stream. I don't think Ampache can do more on server side but maybe I'm missing some knowledge. I keep this thread open for discussion anyway.

**Comment by Afterster** [comment]
No additional solution, that's just how things are working when transcoding. Feel free to comment if you have new knowledge to share.
