### ISSUE TITLE
API: No more random artists

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#3350]
Random artists returning no results from 93f2f32935461342119bbc6efb83c394d86599bc, albums and songs are still OK

```/server/json.server.php?action=advanced_search&type=artist&operator=and&random=1&rule_1=anywhere&rule_1_operator=0&rule_1_input=&offset=0&limit=18```

SQL errors in logs: https://github.com/mitchray/ample/issues/36

**Comment by lachlan-00** [comment]
`rule_1=anywhere` isn't a rule for albums/artists. sounds like what used to happen is that it would fall through and just pick randomly from all artists/albums.

Now that i've changed it to explicitly load the rules it's failing.

**Comment by mitchray** [comment]
D'oh!

**Comment by lachlan-00** [comment]
i've fixed it with 355855c22

If you send a search with no rules you will get everything which you can limit like with regular searches

**Comment by lachlan-00** [comment]
I don't really mind treating it more like a browse where you can ADD rules to a search similar to how a browse sets filters
