### ISSUE TITLE
Dashboards Not Showing

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3351]
The latest commit 355855c22 breaks the various dashboards for me.

No results are returned when viewing #mashup.php?action=album, #mashup.php?action=artist, #mashup.php?action=playlist or #mashup.php?action=podcast_episode and the following error is recorded in the logs:

``(/var/www/html/ampache/public/templates/show_mashup_browse_form.inc.php:22) -> Class "Access" not found``

Reverting to commit d63c5d0ab brings everything back.

**Comment by lachlan-00** [comment]
bd7e101f0 puts that in. i'll need to check that it's not missing in other templates

**Comment by rsinfotech** [comment]
I've not noticed it happening elsewhere, I'll let you know if I do...
