### ISSUE TITLE
Api inconsistencies with multi disk albums

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#3355]
### Describe the bug

Testing ampache with amperfy client, an inconsistency regarding api handling of multiple albums is found
see:

https://github.com/BLeeEZ/amperfy/issues/141

for a complete description

The problem is:

Thank you very much.
After reading the provided the XML responses I would say that this is an Ampache error.
As you can see in the response to `album_songs` there are listed in total 16 songs. The first 8 songs are on disk 1 and the last 8 songs on disk 2.
The first 8 songs have album id `14712` and last 8 songs have album id `14713`.
This means ampache treats the disks as different albums. This alone would't result in the current wrong display in Amperfy. The problem is that: The "album" of disk 2 with album id `14713` is not listed in the response to `artist_albums`. This is why disk 2 is not appearing under the artists as you (and I) would expect.

From my point of view this is an bug in ampache which needs to be fixed there. Either disks are not treated as separate albums or the disk 2 "album" needs to appear in the response to `artist_albums`.

I think it is even wired that the disk 2 songs are contained in the response to `album_songs` request for disk 1. We explicitly request the songs for disk 1. At least I expect that when I explicitly request this album id.

_Originally posted by @BLeeEZ in https://github.com/BLeeEZ/amperfy/issues/141#issuecomment-1246774662_

**Comment by mitchray** [comment]
Duplicate of (or at least related to) #2776 I think

**Comment by lachlan-00** [comment]
with album_group on they should all go into one id. with it disabled it should be per disk

with grouping off it should be only that disk. this can be the first thing i work on this week

**Comment by lachlan-00** [comment]
might be time to make a change and group these things into one item.

it's very cobbled together

**Comment by lachlan-00** [comment]
change made now with pull/3374

**Comment by lusum** [comment]
Now is solved
