### ISSUE TITLE
UpdateCatalog Error

### ISSUE THREAD

**Issue by imneckro** [ampache/ampache#3359]
Hello.
I am trying to update catalogs via command line and i get 

```
sudo php /var/www/ampache/bin/cli run:updateCatalog -c -v -a
PHP Fatal error:  Uncaught Ampache\Config\Init\Exception\EnvironmentNotSuitableException: Environment is not suitable - please refer to the installation guide in /var/www/ampache/src/Config/Init/InitializationHandlerEnvironment.php:43
Stack trace:
#0 /var/www/ampache/src/Config/Init/Init.php(58): Ampache\Config\Init\InitializationHandlerEnvironment->init()
#1 /var/www/ampache/src/Config/Init.php(37): Ampache\Config\Init\Init->init()
#2 /var/www/ampache/bin/cli(36): require('...')
#3 {main}
  thrown in /var/www/ampache/src/Config/Init/InitializationHandlerEnvironment.php on line 43
```

It was updating fine until recently.
Anyone got any leads on this?
Also recently updated php to 7.4.
Don't know if this is the issue.
I would appreciate any kind of help.
Many thanks in advance

**Comment by imneckro** [comment]
Anyone?

**Comment by lachlan-00** [comment]
if you changed php versions i would do a composer update first.

the error is that the checks have run and something is up
![image](https://user-images.githubusercontent.com/1305249/197636923-3c62e84f-c932-48ab-8338-1f7739f88766.png)

**Comment by imneckro** [comment]
That was it! Thanks a lot for your time and help mate! I appreciate it.

Tuesday, 25 October 2022 - 00:54 +0300 from ***@***.***  ***@***.***>:

**Comment by lachlan-00** [comment]
sorry for not getting to you quicker. but that's great.

i'm going to add more detail to wiki pages to try and help these types of situations.
