### ISSUE TITLE
Subsonic api runtime error

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3361]
Not used Ultrasonic for a while so only just noticed it triggering this runtime error in the ampache logs when playing tracks:

``(log.lib) -> [Runtime Error] Undefined array key "playqueue_time" in file /var/www/html/ampache/src/Module/Api/Subsonic_Api.php(1684)``

Everything is still working perfectly though so not a major issue

**Comment by lachlan-00** [comment]
my last act before holidays 5ca30120d :)

**Comment by rsinfotech** [comment]
:+1: That error is now gone, brilliant! Thank you.

Enjoy your holidays @lachlan-00, they are certainly well deserved.
