### ISSUE TITLE
Transcoding .flac files works but always uses .mp3 extension

### ISSUE THREAD

**Issue by linucksrox** [ampache/ampache#3365]
### Describe the bug
I configured Ampache to force transcoding of all .flac files to .ogg. When transcoding .flac files using Ultrasonic on my Android phone, it displays that it will convert the files to mp3. Transcoding works, and the files play successfully. However, the files on the 

### To reproduce

1. Configure forced transcoding of .flac to .ogg
2. Using the latest version of Ultrasonic on Android, connect and stream a .flac song.
3. Note that it says it will convert flac to mp3
4. After the file fully downloads, check the file on the file system, noting that the extension is .mp3.
5. Inspect the file header and confirm that it is in the OGG format.

### Expected behavior
File should show that it will be converted to .ogg, and save with .ogg extension.

* Ampache version: 5.5.2
* Web server + version: (docker)
* Server operating system: (docker)
* Client operating system: (docker)

### Client type

* Ultrasonic Android app version 4.0.0 (org.moire.ultrasonic)

## Settings

```
transcode_flac = "required"
transcode_cmd = "ffmpeg"
transcode_input = "-i %FILE%"
encode_target = "ogg"
encode_target_flac = "ogg"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
```
## Logs
API Request looks like this: `https://music.example.com/rest/getAlbum.view?id=200000341&u=eric&c=Ultrasonic&f=json&v=1.13.0&p=enc:4162E`
Partial JSON response shows the wrong suffix set to mp3 instead of ogg:
```
"song": [
                {
                    "id": "300001809",
                    "parent": "200000341",
                    "title": "Betrayal",
                    "isDir": false,
                    "isVideo": false,
                    "type": "music",
                    "albumId": "200000341",
                    "album": "Extol",
                    "artistId": "100000244",
                    "artist": "Extol",
                    "coverArt": "300001809",
                    "duration": 260,
                    "bitRate": 1064,
                    "track": 1,
                    "year": 2013,
                    "genre": "Metal",
                    "size": 34675755,
                    "discNumber": 1,
                    "suffix": "flac",
                    "contentType": "audio/x-flac",
                    "path": "Extol/Extol/01 Betrayal.flac",
                    "transcodedSuffix": "mp3",
                    "transcodedContentType": "audio/mpeg"
                },
...
```

**Comment by lachlan-00** [comment]
i see why here `src/Module/Api/Subsonic_Xml_Data.php` it's falling back to mp3

![image](https://user-images.githubusercontent.com/1305249/194465054-b0a27198-c835-4351-a4cd-a0b1bbc0dc17.png)

**Comment by lachlan-00** [comment]
with b7e9bae68 i've set it to use the same check that's used for the play urls which should ID the format

**Comment by linucksrox** [comment]
Wow, thank you for finding and fixing this so fast! I'm looking forward to the next release and I'll just manually patch for now :)

**Comment by lachlan-00** [comment]
5.2.2 was almost a month ago so an update with some of the fixes would be good.

I'll probably work on a release in the next week

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
