### ISSUE TITLE
Can't scrub through music

### ISSUE THREAD

**Issue by geist325** [ampache/ampache#3367]
Can't scrub through music

Maybe I'm just a n00b, but I've went through all of the settings and didn't see a relevant option. Everything plays just fine, my library is all FLAC files. When playing, if I'd like to click further ahead or behind in a song though, the song just starts over from the beginning.

1. Go to any song
2. Click on play (song starts playing)
3. Click on the scrubber to move the timeline
4, Song restarts

**Expected behavior***
Song jumps to time indicated by click position in scrubber

## Environment

* Ampache version: 5.5.2
* Web server + version: Apache 2.4.41
* Server operating system: Ubuntu 20.04.5 LTS 
* Client operating system: Ubuntu 20.04.5 LTS

**Client type:**
* Web
* Ampache

## Settings

https://pastebin.com/aAB1U0YD

PHP settings are default

## Logs

Ampache log after trying to scrub through a song:
https://pastebin.com/Db56uSsa

**Comment by mitchray** [comment]
Scrubbing currently doesn't work with live transcoding, for now you will have to pre-transcode your files if you wish to seek through 

Check out https://github.com/ampache/ampache/wiki/Transcode-Caching

Also see #3216
