### ISSUE TITLE
Serve ampache as subfolder

### ISSUE THREAD

**Issue by imneckro** [ampache/ampache#3373]
Helllo.

I am serving ampache as a subfolder to mydomain.
So the url is www.example.com/ampache/public
Is it possible to change this url into www.example.com/music ?

Best Regards and thank you in advance.

**Comment by lachlan-00** [comment]
you shouldn't be using the ampache folder as the directory it'll screw things up. It can be in any path you want but the root should be the public folder.

So if your website is /var/www/html and you want it to be in music you make a link to /var/www/ampache/public

e.g. ln -s /var/www/ampache/public /var/www/html/music

**Comment by imneckro** [comment]
@lachlan-00 that's great! Thanks a lot for your kind help mate!

**Comment by lachlan-00** [comment]
no problem.

**Comment by mitchray** [comment]
Closing as it appears to be resolved, reopen if its still relevant
