### ISSUE TITLE
Ampache 6 database version 600010 update error

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3378]
Hi all,

I'm in the process of updating my develop branch to the new ampache 6 format.

I've carried out the database updates via the cli as recommended in the wiki but I'm getting an Error_query SQL message and can't get past the 600010 database update.

All previous updates seem to have completed successfully up until this one.

The ampache logs report the following:

```
[System] (Ampache\Module\System\Update) -> run_update: starting
[System] (Ampache\Module\System\Update) -> run_update: checking versions
[System] (Ampache\Module\System\Update) -> run_update: START 600010
[System] (Ampache\Module\System\Dba) -> Error_query SQL: UPDATE `user_data` SET `key` = 'album_disk' WHERE `key` = 'album'; []
[System] (Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-album_disk' for key 'user_data.unique_data'
[System] (Ampache\Module\System\Dba) -> Error_query SQL: UPDATE `user_data` SET `key` = 'album' WHERE `key` = 'album_group'; []
[System] (Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-album' for key 'user_data.unique_data'
```
In this state, the web UI is showing the database update page and won't progress to the login page:

![image](https://user-images.githubusercontent.com/3216809/199723547-c348d76c-04ee-4aed-b311-e9218e14a8b6.png)

**Comment by lachlan-00** [comment]
update ignore with c03844a4a and a delete for the old one.

**Comment by rsinfotech** [comment]
Brilliant, that commit has allowed me to complete the database updates successfully, now on db version 600015, much appreciated.

I'm now getting some more 'order by' SQL errors reported when viewing albums with multiple discs:

```
(Ampache\Module\System\Dba) -> Error_query SQL: SELECT DISTINCT `id` FROM `album_disk` WHERE `album_id` = ? ORDER BY `disk`; ["23513"]
(Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'ampache.album_disk.disk' which is not in SELECT list; this is incompatible with DISTINCT
```

The album page shows the Actions links and album art but no tracks are listed:

![image](https://user-images.githubusercontent.com/3216809/200033422-a3323656-f549-4a67-8b00-106448f5966a.png)

**Comment by lachlan-00** [comment]
added to the select in 4f54d35da

**Comment by lachlan-00** [comment]
there are 13 obvious distinct queries  that might be an issue so i'll check those out aswell (using regex SELECT DISTINCT .*ORDER BY)

**Comment by rsinfotech** [comment]
Perfect! Now showing all the tracks for each of the discs, thanks for the rapid response :+1: 

I'll keep an eye out for any more of these and report them separately if found

Original issue closed
