### ISSUE TITLE
Cron command stalling on DELETE FROM `catalog_map` query

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3380]
The scheduled ampache_cron.timer seems to be taking for ever to complete since the ampache 6 database changes:

```
2022-11-05T09:15:02+00:00 [System] (cron) -> started cron process
2022-11-05T12:39:16+00:00 [System] (cron) -> finished cron process
```

Looking at the running processes in phpMyAdmin shows the following query is running constantly for 3 hours 24 minutes:

```
[DELETE] FROM `catalog_map` USING `catalog_map` [LEFT] JOIN ([SELECT] DISTINCT `song`.`catalog` AS `catalog_id`, 'song' AS `map_type`, `song`.`id` AS `object_id` FROM `song` WHERE `song`.`catalog` > 0 GROUP BY `song`.`catalog`, `map_type`, `song`.`id`) AS `valid_maps` ON `valid_maps`.`catalog_id` = `catalog_map`.`catalog_id` [AND] `valid_maps`.`object_id` = `catalog_map`.`object_id` [AND] `valid_maps`.`map_type` = `catalog_map`.`object_type` WHERE `catalog_map`.`object_type` = 'song' [AND] `valid_maps`.`object_id` [IS] NULL
```

The ampache_cron.timer is set to run at the default 15 minute intervals and so starts again immediately after a successful completion meaning the above query is running constantly and slowing down or creating deadlock issues for other queries.

These cron jobs used to take a matter of seconds to complete and only occasionally took around a couple of minutes at most.

**Comment by lachlan-00** [comment]
i cut it down from 18 seconds to 3 on my server

```
DELETE FROM `catalog_map` USING `catalog_map`
LEFT JOIN (SELECT `song`.`catalog` AS `catalog_id`, `song`.`id` AS `object_id` FROM `song`)
AS `valid_maps` ON `valid_maps`.`catalog_id` = `catalog_map`.`catalog_id` AND `valid_maps`.`object_id` = `catalog_map`.`object_id`
WHERE `catalog_map`.`object_type` = 'song' AND `valid_maps`.`object_id` IS NULL;
```

**Comment by lachlan-00** [comment]
changed a few things and added indexes which should speed this up.

**Comment by rsinfotech** [comment]
A massive increase in speed now:

```
2022-11-07T06:15:05+00:00 [System] (cron) -> started cron process
2022-11-07T06:16:05+00:00 [System] (cron) -> finished cron process
```
Great work :+1: Issue closed.
