### ISSUE TITLE
WAMP download link in the wiki

### ISSUE THREAD

**Issue by LordFoogThe4rd** [ampache/ampache#3385]
![image](https://user-images.githubusercontent.com/89643664/202972755-4227f2e9-2868-46e5-9bfc-ab7c148745e2.png)

why is it a tracker link?

**Comment by kuzi-moto** [comment]
Ugh, you're right someone has replaced the links.

@lachlan-00 would be a good idea to look though commits to the wiki from the offending user to see if he made any other changes and undo them.

**Comment by lachlan-00** [comment]
it's annoying but the only options for the wiki are public or for a user with push access.

I can set a requirement for an account to be active for a few days to reduce any spam but we didn't notice this for almost 6 months so probably not going to help

**Comment by huangdangwibu** [comment]
i accidentally clicked on it before going back to check. would a modem and pc reboot prevent any damage?

**Comment by lachlan-00** [comment]
i would def clear all your browser cache for it just in case

**Comment by mitchray** [comment]
I analysed the entire wiki and fixed two others on that page, but the good news is the rest of the wiki is clean
