### ISSUE TITLE
Version not updated to 5.5.4 in Ampache 5.4.4

### ISSUE THREAD

**Issue by GaneshKandu** [ampache/ampache#3387]
Hi,

Version not updated to 5.5.4 in Ampache 5.5.4
its 5.5.3 in Ampache 5.5.4

**Comment by PsyZeus** [comment]
also in release branch it's still states it's develop

![Καταγραφή](https://user-images.githubusercontent.com/26334546/203019969-cc952295-a5bf-4f46-a845-8c4fa73d2c57.JPG)

**Comment by lachlan-00** [comment]
is this in the zips? i just saw one of them isn't updated correctly

**Comment by lachlan-00** [comment]
yup, i made a mistake in the build

**Comment by lachlan-00** [comment]
uploading new zips now. my script didn't reset the build folders so i need to update that
