### ISSUE TITLE
issue with special character "&" in folder names

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#3388]
i can't recall when it started excactly(maybe 3-4 releases back) but since it's not fixed yet it's worth a shot!

when you are in 
/#random.php?action=advanced&type=song
or anywhere under search.php
/#search.php?type=*
and choose the catalog rule, folders with the character & shows as below
e.g folder with name
something&something
displayed as
`something&amp;something`

**Comment by lachlan-00** [comment]
i see, in search rules. there'll be a double scrub somewhere

**Comment by lachlan-00** [comment]
set now in patch5 and develop
