### ISSUE TITLE
Statistical Graphs not shown

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#3389]
As per title, images appears as broken

Using latest firefox, disabling adblocks and firefox protection doesn't do anything.

![Καταγραφή](https://user-images.githubusercontent.com/26334546/203028034-56266347-6127-4cce-a90e-dafc2c8ef225.JPG)

**Comment by fufroma** [comment]
I think it was fixed in https://github.com/ampache/ampache/commit/6d18d59752896664a104c4c45180c4cbb4fed161

**Comment by fufroma** [comment]
Duplicate #3379

**Comment by lachlan-00** [comment]
hmm, found some issues with templates in squashed but need to check that logic again

**Comment by mitchray** [comment]
Per https://github.com/ampache/ampache/issues/3379 I think this can be closed now
