### ISSUE TITLE
Docker update breaks database connection

### ISSUE THREAD

**Issue by danbuntu** [ampache/ampache#3391]
## Description

Watchtower has updated my ampache docker contianer to the latest version. When I go to the web page for it it takes me the test.php page and I have errors on the 'Database connection' and 'Database tables'  checks. The only way I can find around this at the moment it to delete and recreate the container.

### To reproduce

Update docker container via watchtower

### Expected behavior
The update to be applied without losing the existing database setup.

## Environment

docker Ampache latest

### Client type
Web

**Comment by lachlan-00** [comment]
hasn't really been a big change to latest does the container log anything you can see?

**Comment by lachlan-00** [comment]
issues with the release zips, building again in about 10 mins

**Comment by mitchray** [comment]
Closing as appears to be resolved, reopen if still relevant
