### ISSUE TITLE
uploads in user dir lack folders

### ISSUE THREAD

**Issue by NatureMuncher** [ampache/ampache#3399]
### Describe the bug
When I upload files, they're not put into subfolders. Instead they all are crammed into my user's folder (since I do have `Create a subdirectory per user` enabled.) 
### To reproduce

1. Upload several MP3s.
2. Try to upload another MP3 that has the same name
3. Notice that all files are dumped directly under the user's folder and no album subfolder is created

### Expected behavior
I might be wrong but I assumed each album would be in a separate folder to prevent identically-named songs from clashing.
From the below file listing it does appear that it appends unix timestamps to the clashing filenames, however I still don't understand why `03 - Smoke And Mirrors.mp3` can't be written.

### Screenshots
File listing:
~~~
root@host:~# ls -lht /mnt/data/media/audio/ampache/ | head -n22
total 398M
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:56 10 - Trouble_1669586196.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:56 12 - Hopeless Opus_1669586196.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 01 - Shots_1669585956.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 02 - Gold_1669585956.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 04 - I'm so Sorry.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 05 - I Bet My Life_1669585955.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 06 - Polaroid_1669585954.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 07 - Friction_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 09 - Dream_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 12 - Hopeless Opus_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.8M Nov 27 15:52 13 - The Fall_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 11 - Summer_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 10 - Trouble_1669585953.mp3
-rw-r--r-- 1 www-data www-data 7.8M Nov 27 15:45 01 - Shots.mp3
-rw-r--r-- 1 www-data www-data 7.2M Nov 27 15:45 04 - I’m So Sorry.mp3
-rw-r--r-- 1 www-data www-data 7.1M Nov 27 15:45 02 - Gold.mp3
-rw-r--r-- 1 www-data www-data 8.4M Nov 27 15:45 03 - Smoke And Mirrors.mp3
-rw-r--r-- 1 www-data www-data 5.9M Nov 27 15:45 05 - I Bet My Life.mp3
-rw-r--r-- 1 www-data www-data 7.7M Nov 27 15:45 06 - Polaroid.mp3
-rw-r--r-- 1 www-data www-data 6.2M Nov 27 15:45 07 - Friction.mp3
-rw-r--r-- 1 www-data www-data 7.0M Nov 27 15:45 08 - It Comes Back To You.mp3
~~~

## Environment

* Ampache version: fac66f2f5b0149a7521cab6ed221a58f53d4755e
* Web server + version: Apache 2.4.52
* Server operating system: Ubuntu 22.02
* Client operating system: Fedora 37
* Client browser: Firefox 106.0.4 (64-bit)

### Client type

* Web

## Settings

upon request

## Logs

~~~
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> Uploading to catalog ID 1                                                                                
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target Directory `/mnt/data/media/audio/ampache                                                          
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target File `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3                                    
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> File uploaded to `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3`.                             
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> Failed adding uploaded file to catalog.                                                                  
~~~

**Comment by lachlan-00** [comment]
uploaded but failed to add to catalog i'll do some digging on that

**Comment by NatureMuncher** [comment]
I'm not sure it was uploaded correctly. As implied but not very well explained, these are two different songs from different albums that happen to have identical names (one's a lullaby version of the other). From the files shown and the timestamps of the error, I do not believe the second MP3 was uploaded.
Logs searching on `Mirr`:
~~~
root@host:~# grep Mirr /var/log/ampache/ampache.20221127.log
2022-11-27T15:45:10-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target File `/mnt/data/media/audio/ampache/03 - Smoke And Mirrors.mp3
2022-11-27T15:45:11-06:00 [ampache] (Ampache\Module\Util\Upload) -> File uploaded to `/mnt/data/media/audio/ampache/03 - Smoke And Mirrors.mp3`.
2022-11-27T15:45:11-06:00 [ampache] (local.catalog) -> Found song file to import: /mnt/data/media/audio/ampache/03 - Smoke And Mirrors.mp3
2022-11-27T15:45:11-06:00 [ampache] (Ampache\Module\Util\VaInfo) -> /(.+?)\/(.+?)\/([0-9]+?)\s\-\s(.+?)\..+$/ matched audio/ampache/03 - Smoke And Mirrors.mp3 on audio/ampache/03 - Smoke And Mirrors.mp3
2022-11-27T15:52:36-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target File `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3
2022-11-27T15:52:36-06:00 [ampache] (Ampache\Module\Util\Upload) -> File uploaded to `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3`.
2022-11-27T15:56:36-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target File `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3
2022-11-27T15:56:36-06:00 [ampache] (Ampache\Module\Util\Upload) -> File uploaded to `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3`.
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> Target File `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3
2022-11-27T16:05:59-06:00 [ampache] (Ampache\Module\Util\Upload) -> File uploaded to `/mnt/data/media/audio/ampache/03 - Smoke and Mirrors.mp3`.
~~~
And the files listed by time:
~~~
root@host:~# ls -lht /mnt/data/media/audio/ampache/|head -n22
total 398M
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:56 10 - Trouble_1669586196.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:56 12 - Hopeless Opus_1669586196.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 01 - Shots_1669585956.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 02 - Gold_1669585956.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 04 - I'm so Sorry.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 05 - I Bet My Life_1669585955.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 06 - Polaroid_1669585954.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 07 - Friction_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 09 - Dream_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 12 - Hopeless Opus_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.8M Nov 27 15:52 13 - The Fall_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.7M Nov 27 15:52 11 - Summer_1669585953.mp3
-rw-r--r-- 1 www-data www-data 9.6M Nov 27 15:52 10 - Trouble_1669585953.mp3
-rw-r--r-- 1 www-data www-data 7.8M Nov 27 15:45 01 - Shots.mp3
-rw-r--r-- 1 www-data www-data 7.2M Nov 27 15:45 04 - I’m So Sorry.mp3
-rw-r--r-- 1 www-data www-data 7.1M Nov 27 15:45 02 - Gold.mp3
-rw-r--r-- 1 www-data www-data 8.4M Nov 27 15:45 03 - Smoke And Mirrors.mp3
-rw-r--r-- 1 www-data www-data 5.9M Nov 27 15:45 05 - I Bet My Life.mp3
-rw-r--r-- 1 www-data www-data 7.7M Nov 27 15:45 06 - Polaroid.mp3
-rw-r--r-- 1 www-data www-data 6.2M Nov 27 15:45 07 - Friction.mp3
-rw-r--r-- 1 www-data www-data 7.0M Nov 27 15:45 08 - It Comes Back To You.mp3
~~~

**Comment by lachlan-00** [comment]
do you have filename and path patterns set too?
![image](https://user-images.githubusercontent.com/1305249/204400944-c204f173-8e2e-49f8-bf08-3df1acc58dee.png)

**Comment by NatureMuncher** [comment]
I do, yes:
![image](https://user-images.githubusercontent.com/1648745/204401577-a202446d-653e-47fc-a9e4-0c326353f958.png)

**Comment by lachlan-00** [comment]
thanks, just want to verify things. i'll start working on this today

**Comment by lachlan-00** [comment]
i see an option that should enable this, just about to test
![image](https://user-images.githubusercontent.com/1305249/204428898-9874e214-9f49-475f-bee7-e0a7690ca45c.png)

**Comment by lachlan-00** [comment]
the error is that the file is uploaded but not added to the catalog and that happens in the catalog_local class
![image](https://user-images.githubusercontent.com/1305249/204429144-7df6abb0-b3de-46b1-b525-e603eb8ec066.png)


There may be some lines with the local catalog process that tell us why it wasn't added.
```
2022-11-27T15:45:11-06:00 [ampache] (local.catalog) , etc,etc
```

I've got some random files to upload now so i'll be testing it out and looking for reasons

**Comment by NatureMuncher** [comment]
I don't understand. If the file was uploaded, why can't I locate it in the filesystem? As far as I can tell there is only one file named `03 - Smoke And Mirrors.mp3` and it's the first one uploaded. Where's the second one?

**Comment by lachlan-00** [comment]
I've made a lot of changes to the process now with b0ee4c03a I think your issue is the code to move/create from this could not create the destination path, failed somehow and then just didn't do anything correctly after that

This should work a lot better now. I've tested by uploading multiple songs in different tag states and they were all created/uploaded

Previously the file path was changed before it was uploaded and then attempted to add the file

Now the process is:

* Upload file to catalog
* Add file to the catalog
* If you have set move on pattern work out if it's valid
* If it's valid create the directories (Valid means no symbols left over from your match patterns)
* Copy the file to the new destination
* Verify new path
* delete original upload and update database to new location

**Comment by mitchray** [comment]
Closing as completed, but re-open if its still an issue
