### ISSUE TITLE
[Feature Request] Repeat/loop whole playlist

### ISSUE THREAD

**Issue by lycurgus** [ampache/ampache#3405]
I'm not sure if this is an existing feature that I can't find, or if it doesn't exist. I searched the issues but didn't find anything that seemed relevant.

I'd like to be able to mark a playlist to repeat in its entirety. That is, the playlist should play through as normal, and then when it gets to the end it should restart from the beginning.

As it stands, the "repeat" button only repeats the song that is currently playing.

**Comment by lachlan-00** [comment]
have you seen the random play option? This shuffles but has a single item

![image](https://user-images.githubusercontent.com/1305249/205765372-6b3c0a79-2af4-48a0-8882-af527f54db8c.png)

I can probably put an option in the webplayer that says "if you get to the end, start again"

**Comment by lycurgus** [comment]
I had seen it but I was looking for a way to preserve the order (for listening to a whole album primarily) so mostly passed it by. Does it do something other than what I'm assuming - which is shuffle the contents of the playlist?

An added option would be appreciated :+1:  I'm not sure if it makes it easier or harder to implement, but for discoverability I've found that other players tend to have three states on their repeat button: Off, Repeat One, and Repeat All. Currently the button just toggles between Off and Repeat One; I feel like it would be sensible to bundle the function into that rather than having a separate checkbox somewhere. (Happy with whatever form the functionality ends up taking, though).

**Comment by lachlan-00** [comment]
oh yeah, i forgot about players doing that.... that might be easiest way to do it

**Comment by lachlan-00** [comment]
here's a button in develop.
![image](https://user-images.githubusercontent.com/1305249/205812358-b860af68-29b1-4208-bb0d-42afed3d00c5.png)

Enable this and you will restart the current playlist after it's finished

**Comment by lycurgus** [comment]
Awesome! I'm not on develop (just a release) but keen to try it when it hits. Thanks for the quick response :)
