### ISSUE TITLE
API bitrate always pulls from Transcode Bitrate

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#3419]
## Description

My live server was sitting on 5.5.1 for a while and just updated to 5.5.6, now the bitrate for any song is pulling from the Transcode Bitrate, even if transcoding is set to Never

Looks like there has been a few bitrate updates recently:

https://github.com/ampache/ampache/commit/fde9f27bf114da4d507fe1d1b67741813d88fb21
https://github.com/ampache/ampache/commit/55db08fabed37b22c34594ccf86e7600f1c5649d
https://github.com/ampache/ampache/commit/451881e668963308560b439044c9692639ce9c97
https://github.com/ampache/ampache/commit/32895226e66b1ff0369a26e826db96f6083c6b01

The song bitrates are still correct in the Ampache UI, only the API is affected

### Screenshots
Ampache settings
![firefox_Z1c1sQpdOf](https://user-images.githubusercontent.com/5735900/208325508-6f8194a0-90a7-4b83-a1fc-1ea9d7f8d45a.png)

API json bitrate
![firefox_aUqfW0xUcW](https://user-images.githubusercontent.com/5735900/208325535-9d1ce829-e13f-47e5-8055-5fb088c34010.png)

Reborn bitrate
![firefox_99PD6ZOe8K](https://user-images.githubusercontent.com/5735900/208325541-52f12357-c919-49e3-8d72-05632788ccb4.png)

## Environment

* Ampache version: 5.5.6

**Comment by lachlan-00** [comment]
it is, i set that to show the output size and bitrate (if transcoding enabled)

that's different to before where it was source. what might be better is a transcode bitrate and size field?

**Comment by mitchray** [comment]
Yeah additional fields would be better I think

**Comment by lachlan-00** [comment]
i'll put it in 6 and put 5 back to the original sources

**Comment by lachlan-00** [comment]
I've put mime and bitrate back to original and added stream_ prefixed values in 6

what's the id for quality format? the bitrate is back correctly but doesn't have the old format.
![image](https://user-images.githubusercontent.com/1305249/208581260-72114a19-ea2f-4c65-959c-73db33543ecd.png)
