### ISSUE TITLE
Catalog update: possible bug matching album artist

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#3426]
## Description
I just noticed by accident that after updating one of the catalogs of my Ampache installation (5.5.6) I had a number of albums appearing under a wrong artist (artist album view in the webinterface). They also turn up under the correct artist if I search for a specific artist using the instant search.
I explored the problem a bit and can narrow it down to a possible matching error: All the albums that are listed under the wrong artist (in my case "Bad Religion", the punk band from California; artist id in my database: 2200) have no value set for the "Album Artist" tag in the mp3 files. When I manually add the correct value by retagging the files using my mp3 tagging software and update the related catalog the albums disappear from the "Bad Religion" and are only found under the correct artist.

**Comment by lachlan-00** [comment]
there is a function when missing album artists to try and generate one from the song artists by calculating who is the major artist. `src/Repository/Model/Album.php`
![image](https://user-images.githubusercontent.com/1305249/209033127-3c02e9c5-88fe-4253-9575-4845a44ed52d.png)

Assuming it's just the single artist could you see what the query returns? (change the id to your fixed album id)

```
SELECT MIN(`artist`) AS `artist`, COUNT(DISTINCT `artist`) AS `artist_count` FROM `song` WHERE `album` = 138663 GROUP BY `album`;
```

This function only adds an album artist if artist_count is 1 result so they may have been given a null/0 artist id?

**Comment by arno1979** [comment]
I wasn't able to confirm your idea because I couldn't recreate the problem after fixing the tags on the albums showing the problem in the first place.
I tried to remove the "Album Artist" tag from one album but that didn't work. The album was correctly identified nonetheless.

More inconsistencies are popping up though. For example: As I am constantly reindexing a number of my catalogs I can see that some albums are sometimes showing up under "Bad Religion", sometimes they show up under the artist "Unknown (orphaned)", the most recent "artist" (if you can call it that) they get filed under is "[unknown]".
This all seems to be having to do with the mapping procedure that is being triggered while the catalogs are being indexed. I also noticed that albums that are not even part of a catalog that was just reindexed moved from one of the "artists" mentioned above to another after the updating was finished. This all seems pretty wild to me and I can't really see a pattern.
The only thing all the albums affected seem to have in common is that they are not properly tagged in regards to the "Album Artist" tag. But this wasn't a problem in the past and I missed the point in ampache's releases where the problem started to occur.

**Comment by lachlan-00** [comment]
a lot of things are relying on the album artist. i think there will be issues without one but i'll make some tester ones to see what the database does now.

**Comment by arno1979** [comment]
I would never suggest to remove the album artist!
I started yesterday to go through my catalogs (the ones I haven't worked on so far) and I can't reproduce the "Bad Religion" phaenomenon anymore. Now albums without an album artists tag present are getting reliably put under "Unknown (orphaned)" which makes it easy to identify and fix them.

**Comment by lachlan-00** [comment]
Just testing, the album artist on this album is no one
![image](https://user-images.githubusercontent.com/1305249/210304858-3955c135-bc22-496a-9146-f89c1dbbb0c4.png)

And the album_artist is filled magically.
![image](https://user-images.githubusercontent.com/1305249/210304904-dc86b5fa-d048-43a7-b87c-8ac7552710a2.png)

Who looks to be the lowest ID artist in the album
![image](https://user-images.githubusercontent.com/1305249/210304990-ffe80b64-3c31-4d27-a090-940a4a46126c.png)

Where as this should just be ignored / null

**Comment by lachlan-00** [comment]
being set here, i'll remove that
![image](https://user-images.githubusercontent.com/1305249/210305284-3c9f7404-9678-43f8-a711-5df9a746a6ca.png)

**Comment by lachlan-00** [comment]
OK, partly there.

Set in develop and patch5 (7d7d1d539) the albums are not imported and updated with a count if there isn't a value and it's respected by not filing in the data in the album

![image](https://user-images.githubusercontent.com/1305249/210311371-f66c1d24-4a1a-415b-aa30-e73e5b750f4e.png)

![image](https://user-images.githubusercontent.com/1305249/210311404-ff9259f5-adea-4f06-8b61-d5f6d4b3ccca.png)

If you use develop you can do an add/clean and it will refresh the data

**Comment by mitchray** [comment]
Seems to be resolved, reopen if not
