### ISSUE TITLE
Shared smart playlist cannot find unrated artists

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#3427]
I'm not yet sure that this is a bug, or just a usage error, but it's reproducible.

I use nested smart playlists to find the albums I like. One of my favorites, called **My Favorites** feeds from a dozen different playlists to find a blend of rated and unrated tracks for me to rate. It's cool, I've been meaning to post it to reddit for some time. It's been good, but I've noticed that it never seems to pull unrated tracks that aggressively, something that I'd chalked up to the vaugaties of randomness.

However, when I created a new user with just a handful of favorite albums, I noticed that their My Favorites field was coming up blank. I tracked down one of the subqueries that should have dozens of tracks, but it only had one random one. Here's where it gets weird. When I recreated the query, it worked _perfectly._ Thinking that the original smart playlist was corrupt somehow, I deleted it and recreated it on my own user name. I went from four pages of results to six. Not bad. But, when I went back to the new user, and now it shows two different tracks rather than the random original one.

To reproduce:
- Create a smart playlist with the following criteria:
1. My Rating equals 0
2. My Rating (artist) equals 0
3. My Rating (album) is greater than or equal to 3
4. Length is less than or equal to 8
- Make sure the list is shared with the public.
- Log in as another user, and create the same smart playlist. Note the results.
- Access the shared list from the same user, and compare the results.

**Comment by lachlan-00** [comment]
OK, i think the issue is this.

* As a user you create a search.
* But when you RUN the search it's being used as the web user logged in.

![image](https://user-images.githubusercontent.com/1305249/210495604-61750f48-f69e-4002-887d-edc3707051b4.png)

Every search has a user but it's not being respected on construct (probably)

![image](https://user-images.githubusercontent.com/1305249/210495737-7386d380-0491-4f71-8ac6-fd3a193344e3.png)

What we should do is use the search owner (Unless you are -1/system then use your user)
![image](https://user-images.githubusercontent.com/1305249/210495916-15355e09-87ce-498e-a1a7-4b91230a0d6b.png)

**Comment by SimonHova** [comment]
Could that change have broken my playlists? Some of them are working but some are not. The only clue that I have is the log file, it shows:

`(/opt/ampache/src/Repository/Model/Search.php:79) -> Ampache\Repository\Model\Search::__construct(): Argument #3 ($user) must be of type ?Ampache\Repository\Model\User, string given, called in /opt/ampache/src/Module/Playlist/Search/SongSearch.php on line 365`

**Comment by lachlan-00** [comment]
copy/paste error 68277beff needs the sub user

**Comment by lachlan-00** [comment]
i don't think it's fully working yet either. it still seems to use the web user sometimes.

**Comment by lachlan-00** [comment]
i've been testing and it seems to be picking up the specific user correctly now in develop.

I do need to do morw work in this for subsearches and verify that all the use_id's are respected but it's looking much better now

https://github.com/ampache/ampache/wiki/ampache6-details#searches-and-smartlists-consider-the-owner-of-the-list-instead-of-the-current-user

**Comment by SimonHova** [comment]
I have thoughts on this; but I have transferred them to a [discussion](https://github.com/ampache/ampache/discussions/3452).
