### ISSUE TITLE
Random play does not work

### ISSUE THREAD

**Issue by SuperFola** [ampache/ampache#3428]
On this image we can see the random play button

![image](https://user-images.githubusercontent.com/1305249/205765372-6b3c0a79-2af4-48a0-8882-af527f54db8c.png)

_Originally posted by @lachlan-00 in https://github.com/ampache/ampache/issues/3405#issuecomment-1338347146_

On my instance it doesn't work (no error in the browser console alas), just generating a "Random by Ampache" in the list of songs ; however "Random all to temporary playlist" does work but needs more steps to work.

As a side note, is "Random all to temp playlist" still needed, since "Random play" would be the same as far as I understand?

**Comment by lachlan-00** [comment]
Random play selects a song and then redirects to the direct song url. I've seen it before where the server wasn't redirecting the urls but not sure why a server hasn't redirected.

What it should do it 302 and redirect 200 to the actual url

![image](https://user-images.githubusercontent.com/1305249/210449514-65955657-c173-4bdc-aa46-91447a46d202.png)

It might be better to just load the media on the random url if it's inconsistent between web servers but it was done to make the url details available to clients.

**Comment by lachlan-00** [comment]
Code gets to here and then redirects to the url. (src/Module/Application/Playback/PlayAction.php)
![image](https://user-images.githubusercontent.com/1305249/210452179-5037521d-ae8f-4e44-87d9-e5f1e0d0dd06.png)

**Comment by lachlan-00** [comment]
maybe the 302 redirection is ignored?

you could try using a 303 or a 301 to tell the browser that the data is on the second url?

```
// play the song instead of going through all the crap
header('Location: ' . $media->play_url(), true, 303);
```

if you're on develop the line is different (line 461)
```
// play the song instead of going through all the crap
header('Location: ' . $media->play_url('', $player, false, $user->id, $user->streamtoken), true, 303);
```

**Comment by SuperFola** [comment]
When I click on Random play in a playlist, this happens (Chrome 108, Ampache 5.5.6, everything is behind nginx proxy manager with SSL)

<img width="564" alt="Capture d’écran 2023-01-04 à 15 16 54" src="https://user-images.githubusercontent.com/10694085/210574522-aaf579f3-c280-45df-b661-1df32b05bffa.png">

<img width="949" alt="Capture d’écran 2023-01-04 à 15 17 03" src="https://user-images.githubusercontent.com/10694085/210574554-8955d3e7-5caf-4be2-a26f-13e9eeb26146.png">

Will try updating the code to see how that works

**Comment by lachlan-00** [comment]
ok so the 200 response say's it's not redirected to the actual media which is why nothing comes out.

This is how democratic play works as well so that's probably broken as well...

can you access the container directly without the proxy? might need to edit the config. i'll just check me test containers to see if it's processing okay locally

**Comment by lachlan-00** [comment]
ohhh, you know what it might be.... the redirect is taking too long for the proxy so it just ends the connection.

for my the redirect takes maybe .8 of a second and it may be cut off before it completes

**Comment by SuperFola** [comment]
I can access the proxy, ampache container and its config as well. I can tune nginx parameter for the ampache host, I will try to tune that maximum response time to something like 1 second!

**Comment by lachlan-00** [comment]
yes that's plenty, unless you're using random play from a very complicated smart list the process is pretty quick (generally less than one second.)

**Comment by lachlan-00** [comment]
try out the latest develop and see if the extra redirect works for your proxy
![image](https://user-images.githubusercontent.com/1305249/210931942-acd38f29-7f40-41a5-9bb8-8daa606b18b2.png)

**Comment by SuperFola** [comment]
Currently testing on (Android) Chrome, the problem appear to be the same. Plus I don't have any "user is currently playing song" on the homepage. Will have a look at the network inspector soon.

**Comment by SuperFola** [comment]
![Capture d’écran 2023-01-06 à 09 13 54](https://user-images.githubusercontent.com/10694085/210958752-06f1b4b3-ef7b-4857-9635-1a17bf63664e.png)

Still the same problem, I'll try to monitor on the proxy side, maybe it doesn't like the redirections

**Comment by SuperFola** [comment]
I recently reinstalled Ampache, using the develop docker version (the latest as I understand it) and it's now working. I haven't changed my web browser configuration, nor my Ampache configuration, just the version I was using.
