### ISSUE TITLE
[Help needed] Catalog error

### ISSUE THREAD

**Issue by CrazyWolf13** [ampache/ampache#3434]
Hello there
I tryiedto upload my first Catalog, but sadly the webserver throws the error 
![image](https://user-images.githubusercontent.com/96661824/210010105-778b94d9-1fa1-4954-bb88-26dfef09fc8f.png)

Now i tried fixing this the whole evening and Googling around, i think it's a permission problem, but i ran all the chmod chgrp chown. 
I normally mounted (self-Mounting from the OS) the hdd to my device.
Device: RaspberryPi 3b+
Os: Raspbian
File Tree:
/media/pi/Seagate/Nas/Music/{genre}/{album}/{music_files}
/media/pi/Seagate/Nas and children are mounted as a NAS.

Thank you for any help / information.
Kind regards.

**Comment by lachlan-00** [comment]
I've had issues before where the web user couldn't see the folders inside the /mnt/ folder before and by mounting as the user on /media it's probably not able to see inside the /media/pi folder/

Pi should be using www-data as the web user? you can su to the www user and check what it can see using 
```
su - www-data -s /bin/bash
```

Then try to cd into /media and /media/pi and ls the folders to see what you can see.

I would mount these folders in fstab as i don't know how the /media folder treats these. if you want automount that's all possible from the fstab file and would allow usb/nfs/etc

**Comment by CrazyWolf13** [comment]
> I've had issues before where the web user couldn't see the folders inside the /mnt/ folder before and by mounting as the user on /media it's probably not able to see inside the /media/pi folder/
> 
> Pi should be using www-data as the web user? you can su to the www user and check what it can see using 
> ```
> su - www-data -s /bin/bash
> ```
> 
> Then try to cd into /media and /media/pi and ls the folders to see what you can see.
> 
> I would mount these folders in fstab as i don't know how the /media folder treats these. if you want automount that's all possible from the fstab file and would allow usb/nfs/etc
> 
> 

Good Morning
Thank you very much for the response.
I already tried giving the user www-data root by adding it to the root group. I also manually set the drive in fstab still nothing. And what is the most confusing: it is not creating any log files even touch turned on in settings. No matter what si try.

**Comment by lachlan-00** [comment]
That's a bad idea for give a webserver root access. The root group probably won't have access to the /media/pi folder either

I would keep things as default for the media folder and move it to mnt using /etc/fstab
Media probably won't keep your permission's  on /media/pi/Seagate after a reboot as it will get recreated.

I would

* use `df -h` to list your devices. it'll be something like /dev/sdb2 (the b2 will change but the /dev/sd part is static)
* then in /etc/fstab you add a line to add the device to mount
```
/dev/sdb2 /mnt/music auto defaults 0 0
```

finally

* make the folder as root `mkdir /mnt/music`
* and take ownership `chown pi:www-data /mnt/music`
* add pi as a www-data member `usermod -a -G www-data pi`
* then mount everything `mount -a`

**Comment by CrazyWolf13** [comment]
> That's a bad idea for give a webserver root access. The root group probably won't have access to the /media/pi folder either
> 
> I would keep things as default for the media folder and move it to mnt using /etc/fstab
> Media probably won't keep your permission's  on /media/pi/Seagate after a reboot as it will get recreated.
> 
> I would
> 
> * use `df -h` to list your devices. it'll be something like /dev/sdb2 (the b2 will change but the /dev/sd part is static)
> * then in /etc/fstab you add a line to add the device to mount
> ```
> /dev/sdb2 /mnt/music auto defaults 0 0
> ```
> 
> finally
> 
> * make the folder as root `mkdir /mnt/music`
> * and take ownership `chown pi:www-data /mnt/music`
> * add pi as a www-data member `usermod -a -G www-data pi`
> * then mount everything `mount -a`
> 

Thank you very much for this detailed guide. I will try this. But i want to add it is a NTFS hdd if it matters and is it still possible to reuse the hdd as a samba server as well?

**Comment by lachlan-00** [comment]
sure is. you can mount things wherever you want really.

Think of it this way. /media is for live add/remove drives like a usb or cd and /mnt is for things you want the server to use like a file-share or permanent storage.

**Comment by CrazyWolf13** [comment]
> sure is. you can mount things wherever you want really.
> 
> Think of it this way. /media is for live add/remove drives like a usb or cd and /mnt is for things you want the server to use like a file-share or permanent storage.

Thank you very much
