### ISSUE TITLE
[BUG] Creation of Admin Account issue

### ISSUE THREAD

**Issue by mariushosting** [ampache/ampache#3435]
I create an admin account in the first configuration, for example Mariusadmin
When I'm ready to log in, I can log in with Marius**A**dmin instead of Mariusadmin so I can log in with either an uppercase letter or a lowercase letter. Ampache 5.5.6 disregards this basic safety rule.

**Comment by lachlan-00** [comment]
i can't say i've used many applications/programs that cared about case for the username?

**Comment by kuzi-moto** [comment]
I don’t think this could be considered a bug. Case sensitive logins might offer a small amount of protection. I don’t think the trade-off is worth it when you could have many more cases of login failure when someone uses the wrong case.

For what it’s worth, Google allows for logging in with different cases.
