### ISSUE TITLE
Upgrade 4.1.1 > 5.5.6  - unable to produce config file - it also complains about checking the db.

### ISSUE THREAD

**Issue by AndKe** [ampache/ampache#3443]
### Discussed in https://github.com/ampache/ampache/discussions/3440

<div type='discussions-op-text'>

<sup>Originally posted by **AndKe** January  6, 2023</sup>
I rm'ed my /var/www/ampache (4.1.1)
installed new 5.5.6 to same directory.(php 8.1)

I skip creating the database step. and proceed to the "generate config file" step:

![Screenshot from 2023-01-05 19-46-23](https://user-images.githubusercontent.com/1468842/211036509-c14b7677-ce8e-4842-bc6a-c5e80f0c1f25.png)

then I get this:
![Screenshot from 2023-01-05 19-48-26](https://user-images.githubusercontent.com/1468842/211036657-1e2bbb8e-70f3-4f93-a864-cd982a2ceafb.png)

Downloading htaccess works fine, but the download button for ampache.cfg.php just produces a blank webpage(no download)
clicking "write" does not work - (even if the config dir is 777)
..and some of those actions produce a warning line that the SQL test failed. - which I do not trust - as I've verified the database name, user name, and reset password.
</div>

**Comment by CarrionAndOn** [comment]
Don't skip the database step. You can set "don't create database" in the database step so it uses an existing database.

**Comment by AndKe** [comment]
@CarrionAndOn  ok - it got further this time.
I got an error, but then could write the config file anyway(?)
then it tried to go to the wrong URL :  http://192.168.1.20ampache/update.php?action=update

I corrected it to http://192.168.1.20/update.php?action=update

and then I got to "Ampache debug" which told me  "You may have reached this page because a configuration error has occurred. Debug information is below."  and shows this end:
![Screenshot from 2023-01-07 21-51-28](https://user-images.githubusercontent.com/1468842/211169876-85de44d5-4689-44b1-b20f-c8582aae5c95.png)

I fixed the web_path variable in the configuration and correct database name and then it worked.

The first option to skip database-creation step is clearly confusing, I mean - if it is not smart to use it.
It would also be very nice if the setup could parse old config file - this way it would get all the names/username/addresses etc right.


Thank you.

**Comment by CarrionAndOn** [comment]
What'd you set the web_path to? I keep getting the database tables error.

**Comment by AndKe** [comment]
I set it to ""  - because I thought the path expected "ampache"  as if relative to webroot, in  /var/www/ampache
but the attaempt it did at "http://192.168.1.20ampache/update.php?action=update"  - told me I needed to remove it (http://192.168.1.20/update.php?action=update)  was right for me.

**Comment by CarrionAndOn** [comment]
I have it set to nothing too, I have no idea why I keep getting database tables errors then.

**Comment by AndKe** [comment]
in my case, it also tried to do database_name = "ampache"    while the correct name is database name is "ampache_database"
I can't be sure that it's not my bad - I tried this process too many times before succeeding.

**Comment by CarrionAndOn** [comment]
I got further, it got to the create admin account page, but now it's stuck on updating the database.
![image](https://user-images.githubusercontent.com/30084485/211172753-83f22c1b-bef1-4d75-95ff-c2cb1fd07a9e.png)
