### ISSUE TITLE
playlist_create with the existing name just returns existing playlist

### ISSUE THREAD

**Issue by AshotN** [ampache/ampache#3455]
### Describe the bug
Calling `playlist_create` with a name of a playlist that already exists, doesn't create a new playlist or throw an error. 

This is kind of a pain since the client thinks the request was successful, when in reality nothing happened.

### Expected behavior

I'm not sure what the expected behavior should be. Should the user be able to create two playlists with the same name? If not, return a bad request error.

**Comment by lachlan-00** [comment]
i forget my reasoning for it. i think it should match the other create methods and return an error
![image](https://user-images.githubusercontent.com/1305249/221729773-25da5f11-ecc6-4390-a76a-0f2eadc0bd93.png)

**Comment by lachlan-00** [comment]
70a041ce7 error in api6 (keeping the existing behaviour for the others.)
