### ISSUE TITLE
[Feature Request] Expose server type to Subsonic API

### ISSUE THREAD

**Issue by Tolriq** [ampache/ampache#3456]
## Describe what you don't like about Ampache, or what it is missing

Currently Ampache does not advertise that it's Ampache in Subsonic responses.
Most servers now support that to help clients adapt their code.
Next release of Symfonium will add more warnings to users when the server is not recognized to reduce support about servers not supporting Search3 endpoint with empty queries.
Since Ampache does support that, it would be nice to avoid showing a warning to users for no reasons.

## Describe how you would like the feature to work**

https://support.symfonium.app/t/explicit-server-name-and-version/1182

**Comment by lachlan-00** [comment]
i'll add type and version to responses

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/219261407-47ba739b-def6-4ef2-a896-d82519150920.png)
type as 'ampache'
version as the api version (e.g. 6.0.0)

**Comment by lachlan-00** [comment]
set with 9bff70fbe

**Comment by lachlan-00** [comment]
![image](https://user-images.githubusercontent.com/1305249/219263202-c4a75ebe-f1ad-45ca-a0ae-a197675e0d40.png)

![image](https://user-images.githubusercontent.com/1305249/219263224-158a453a-32cf-4471-8d2c-0cf227fbfa12.png)

**Comment by Tolriq** [comment]
@lachlan-00 Thanks, does this also covers JSON as that what I use?

**Comment by lachlan-00** [comment]
> @lachlan-00 Thanks, does this also covers JSON as that what I use?

that's the second picture ;)

Ampache converts the xml into json when your f=json

**Comment by Tolriq** [comment]
Perfect thanks.

**Comment by Tolriq** [comment]
So just tested and it works, but found a small Subsonic API issue : See https://github.com/ampache/ampache/issues/3462
