### ISSUE TITLE
[Bug] Differences in behaviour between XML api 6 and JSON api 6

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#3458]
### Describe the bug

This patch is not ported to xml, causing a difference in behaviour between XML and JSON:

https://github.com/ampache/ampache/commit/224ba1979405f5aeafd6d03dacb0143f5e68ef67

**Comment by lachlan-00** [comment]
This should be extracted out of the data classes into Album instead now.

I've pulled it back into `get_artist_fullname()` in the Album class with ef267e3171dc6ab28b8f39ecc8ba72c03dcf1785

I've tested it in the WebUi with a test album now have the responses not been fixed?

**Comment by lusum** [comment]
Not fixed, the results for an album without main artist is:

 <artist id="0">
  <name><![CDATA[]]></name>
  <prefix><![CDATA[]]></prefix>
  <basename><![CDATA[]]></basename>
</artist>

**Comment by lachlan-00** [comment]
what's the row for that album look like? 

song_artist_count and artist_count specifically

**Comment by lachlan-00** [comment]
the xml data classes need more checks for empty values, they assume it's always there still in most spots

**Comment by lachlan-00** [comment]
checks for the artist added with 00640d192. i'm just going back through the other ones to check that too

**Comment by lachlan-00** [comment]
and set some more stuff in a6f30c7ce as it seems to be an issue with the name array

**Comment by lusum** [comment]
Fixed with latest patches.
