### ISSUE TITLE
[Make ListenBrainz API Host user-configurable]

### ISSUE THREAD

**Issue by CustardFlan** [ampache/ampache#3459]
Hi!

First, thanks for creating such awesome music server software! I'm really happy with it!

So, here is my request:

In https://github.com/ampache/ampache/blob/develop/src/Plugin/Ampachelistenbrainz.php

The API domain it's defined here
 private $api_host = 'api.listenbrainz.org';

Can you make it configurable in the plugin preferences section?

Why? Because i'm using Maloja (https://github.com/krateng/maloja) for keeping track of my listen history, Maloja supports a ListenBrainz compatible endpoint (https://maloja.chocoflan.net/apis/listenbrainz for example) only this endpoint and the API key is needed

I have changed the code from api.listenbrainz.org to maloja.chocoflan.net/apis/listenbrainz and, indeed, it works

But, can be handy for the regular user to change to any compatible server if they wish

Best, regards, Custard

**Comment by lachlan-00** [comment]
yeah that's easy enough. just need to update the plugin with a new option

**Comment by lachlan-00** [comment]
will it work with the token setup as well just by configuring the host?

**Comment by CustardFlan** [comment]
Yes! if you put the Maloja token already in the plugin config, with the server address changed, it works

**Comment by lachlan-00** [comment]
k, this file should be good for you then

315dc0a8c try that out and let me know if it's missing anything and i'll put it in the next 5 release

**Comment by CustardFlan** [comment]
I been using the develop branch, so, after one click, it's updated!

Yes, it works!

Thank you!

Now, i have another issue, maybe it's my fault, a config error, but, i'm opening another issue fot that...

**Comment by lachlan-00** [comment]
cool, i'll keep it in dev as the translation won't be there anyways. let me know in your other issue how it goes
