### ISSUE TITLE
Subsonic auth error invalid json/xml message

### ISSUE THREAD

**Issue by Tolriq** [ampache/ampache#3462]
### Describe the bug

While testing the dev server, with invalid credential the answer is not a valid subsonic answer.

### To reproduce

For example:
https://develop.ampache.dev/rest/ping.view?u=REDACTED&t=REDACTED&s=REDACTED&v=1.13.0&c=Symfonium&f=json 

### Expected behavior

Should return something like:

```
{"subsonic-response":{"status":"failed","version":"1.16.1","type":"ampache","serverVersion":"6.0.0","error":{"code":40,"message":"Invalid authentication attempt to Subsonic API for user [REDACTED]"}}}
```

But it only returns:
```
{
    "error": {
        "code": 40,
        "message": "Invalid authentication attempt to Subsonic API for user [REDACTED]"
    }
}
```

So without the `subsonic-response` wrapper

## Environment

* Ampache version: develop.ampache.dev

### Client type

Subsonic

**Comment by lachlan-00** [comment]
only a 9month old bug.. set it develop and patch5 now
![image](https://user-images.githubusercontent.com/1305249/219549062-a69dbf8d-974d-458f-bb2c-27147854ffc7.png)

**Comment by lachlan-00** [comment]
the functions used to echo everything so it was an easy miss but fixed up on the demo's now
![image](https://user-images.githubusercontent.com/1305249/219563542-4d5cac03-9c14-455f-8c4b-c7c7dc3fe037.png)

**Comment by Tolriq** [comment]
Thanks I must admit I nearly never test with wrong data :(

But this got me a nice bad rating today because I can't display the error.
I love users :)

![image](https://user-images.githubusercontent.com/932609/219572747-e352ad55-a4d2-4a8d-848f-1bb3935f5976.png)
