### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Dreadlocke12** [ampache/ampache#3463]
I tried to freshly install ampache using the latest version (5.5.7). After configuring the apache server and copying the files to  /var/www/html/apache I can access the page

![image](https://user-images.githubusercontent.com/56894437/219333614-1e3b4bdc-db92-487a-a0ab-305f347fae37.png)

but as soon as I go to public or try to access the install.php the following page appears: 

![image](https://user-images.githubusercontent.com/56894437/219334327-fe485c0b-b085-4750-94e5-da0f72d5a9d0.png)

My PHP version is 

PHP 8.1.2-1ubuntu2.10 (cli) (built: Jan 16 2023 15:19:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.10, Copyright (c), by Zend Technologies

and i downloaded the 8.1 php  version of amapache

**Comment by lycurgus** [comment]
It sounds like you've got the documentroot set to the base Ampache folder (i.e. `/var/www/html/ampache`), not to the `public` subfolder (i.e. `/var/www/html/ampache/public`). Can you share your apache config to confirm?

Did you check the Ampache wiki link as mentioned on the error page? Most notably: https://github.com/ampache/ampache/wiki/Ampache-next-Changes#you-will-need-to-update-the-web-server-document-root

**Comment by lachlan-00** [comment]
the way to install now for apache to link the public folder to your webroot
```
DocumentRoot /var/www/ampache/public
```

This guide also explains how to link the folders.
https://github.com/ampache/ampache/wiki/install-ampache-on-ubuntu2204#here-choices-be

if you can't work that out there are also squashed releases that you can extract to your webroot (but they're not the ideal way to install)
![image](https://user-images.githubusercontent.com/1305249/219542008-9055e986-4161-4f79-ba1b-bed0a54607db.png)

**Comment by Dreadlocke12** [comment]
I think the issue was because PHP has not been correctly installed therefore I close the issue. Sorry for the inconveniences.
