### ISSUE TITLE
Ampache 5.5.7: New Catalog with double entries

### ISSUE THREAD

**Issue by Khymick** [ampache/ampache#3481]
### Discussed in https://github.com/ampache/ampache/discussions/3480

<div type='discussions-op-text'>

<sup>Originally posted by **Khymick** March 10, 2023</sup>
Hello there,

I am using Ampache 5.5.7 on an Ubuntu 22.04 server with Apache2.
I have the problem that when I create a new catalog, I get artists double listed in the frontend as well as on subsonic client.
I already deleted the whole catalog and added a new one. It just started collecting files from my mp3 dir, but already now, I have artists with double entries.

I don´t think it´s an issue of the files itself, because when I import the same mp3 dir on different services, I do not get any artist listed 2 times. So I guess there is something wrong in the Ampache collector.

Can someone please help me to solve the issue?</div>

**Comment by lachlan-00** [comment]
Artists are created based on tags. Might be differences between the tags for the dupe artists especially if one artist has an mbid and the other doesn't.

If you edit artist for each of them; what are the differences?
