### ISSUE TITLE
[Feature Request] Move tag delete to catalog garbage collection

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#3499]
## Describe what you don't like about Ampache, or what it is missing
This delete query shown below runs for a long time when doing a catalog verify, now over 1500 seconds. This seems to run often during the verify thus making the verify take several days. I also had to change the MySQL server inodb lock timeout to 1 day as a safety measure because some table locks would time out. I think moving this delete to the catalog garbage collection routine, thus only running once.

![image](https://user-images.githubusercontent.com/4076671/231146891-470a4dd6-0119-4f76-84d2-7e5d9be591b8.png)

**Comment by lachlan-00** [comment]
This probably doesn't need to be there. The migrate_artist function is probably doing too much too and running per-song

![image](https://user-images.githubusercontent.com/1305249/231346444-9f15005a-856d-4ce5-bcdb-a71830d448b6.png)

**Comment by lachlan-00** [comment]
@stebe i've sped up a few things but i think this still needs to be done. will be focusing on this issue next

**Comment by lachlan-00** [comment]
i think this should be okay / better now and that the query shouldn't lock up the table like that now
