### ISSUE TITLE
Cookie name should have __Secure- prefix when session_cookiesecure is true

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3501]
When we have `session_cookiesecure` enable, it mean we run an Ampache with https setup.

But the Cookie does not have the `__Secure-` prefix, wich allow it to be used over simple http.

We can fix it by manually setup the `session_name = "__Secure-ampache"`, but it require a manual action. I think it could be great to add it automatically so people will have a better security out-of-the-box.

Warning: it can generate error if the website can be accessed by http AND https, and not only https. Maybe we could prefix it only when `session_cookiesecure` is true and the actual protocol is https. People won't be able to swap between http and https session without having to authenticate again, but it should not happen.

**Comment by fufroma** [comment]
@usox some opinion about that?

**Comment by usox** [comment]
Hi @fufroma 

I don't see a fundamental problem with this. Browser support for cookie prefixes is also fine (who cares about IE11?). https://caniuse.com/mdn-http_headers_set-cookie_cookie_prefixes

The only advantage of the current state is that we don't have to do anything. If someone wants the secure prefix, they just add it. If we did this automatically, we would again have to provide an option to disable it if someone doesn't want it.
The question now is whether the effort is worth the benefit, or whether we should simply write a note about this in the documentation/config file...

**Comment by lachlan-00** [comment]
I prefer that people can hang themselves on these things if they want

notes in the config would be helpful to warn people about things they might not know about

**Comment by fufroma** [comment]
so we can close this issue ^^

**Comment by lachlan-00** [comment]
added with 9dcb9d6b3bd552ee6ef262d0c3703c58ea5eaba8
