### ISSUE TITLE
gather-messages.sh fails to gather some strings that need to be translated

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3508]
I have seen an untranslated string and figured out that it is not in messages.pot. Moreover, when running gather-messages.sh the string still does not appear there.
The string is in file public/templates/show_add_catalog.inc.php and starts with "In the form below enter..."

It would be great if  gather-messages.sh recognizes that string  in order to be able to localized.

**Comment by lachlan-00** [comment]
it's a bad string because the variable is inside the string and should be outside in a sprintf or something else.

i've taken it out with b2ede2dce

**Comment by cquike** [comment]
This has been fixed time ago. Hence closing.
