### ISSUE TITLE
[Feature Request] UI Improvements

### ISSUE THREAD

**Issue by LukasTheViking** [ampache/ampache#3511]
I found that most of the control icons in the UI to be extremely small and not very intuitive graphically. For instance, to minimize the player, I wouldn't have thought to look at the bottom left corner of the page. Perhaps it would be better to move it to the top right or top left corner of the player pop-up. Having larger icons will also make it easier to identify what they do. I found myself hovering my mouse over the icon and having to read the pop-up description of the action to get an idea of what I was about to do. Also moving to a more universal set of glyphs would make it a lot more user friendly for those of us new to using Ampache. I myself am not a coder but just an end-user looking at music repository options. It may also be helpful to have a tutorial guide when first launching that can be disables or skipped in the account settings. That way, brand new users can get guided through how to use the software, or choose to skip it if they wish.

These are just some of my initial impressions and I hope they are received as helpful feedback.

**Comment by mitchray** [comment]
Agree 100%, unfortunately its a massive task to overhaul the UI as the presentation layer is heavily intertwined with the logic. The strategy being implemented is to improve the API system so we can ultimately split the presentation from logic

In the mean time I would recommend using an [Ampache-specific or Subsonic-compatible client](https://github.com/ampache/ampache/wiki/client-api) if you need a more modern interface

So I'll close this as there isn't anything for us to action here really, the work is already underway
