### ISSUE TITLE
`bin/cli run:updateCatalog` command not performing default action

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3516]
## Description

The `bin/cli run:updateCatalog` command is supposed to perform the default actions -ceag when no argument is given. However after installing 5.6.0 this seems to be not the case. _Something_ is performed, but not those actions.

### To reproduce

1. Run  `bin/cli run:updateCatalog` 
2. Run  `bin/cli run:updateCatalog -ceag` 
3. Compare the output of both commands

### Expected behavior
Outputs should be the same

## Environment

* Ampache version: 5.6.0
* Web server + version: nginx
* Server operating system: Raspbian 11

**Comment by cquike** [comment]
This seems to be a regression introduced in 44b079174c, when the condition `&& !empty($values['safe'])` was added in line 62 of src/Module/Clie/UpdateCatalogCommand.php. Removing that is enough to make work again, but I am not sure what was the intention of adding that extra condition.

**Comment by lachlan-00** [comment]
safe mode maybe. i'll look back through the blame to see what it was

**Comment by lachlan-00** [comment]
no idea where i got that from seems like a longtime typo. reset with 14030c359

**Comment by lachlan-00** [comment]
i need to fix up that one first. the verify is too slow but i'll be working on speeding that up next week

**Comment by lachlan-00** [comment]
Added verify back again in d5f04c4cd

I've sped up the verify process a lot more so i'm happy to have it back again

**Comment by cquike** [comment]
I am running ampache 6.5.0 and just wanted to report that this has been fixed in the meantime. Hence closing.
Thanks!
