### ISSUE TITLE
ajax.server.php is being called periodically when a song page is displayed.

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3517]
## Description
 
 I have been seeing too much traffic in my ampache server and I have realized that ajax.server.php is being called in many cases in which it should not be performing anything in the background.

### Describe the bug
If I am in the front page of ampache then there are some widgets that need to be reloaded and I see that `/server/ajax.server.php?page=index&action=reloadnp` is being called (to refresh the now playing widget). That's all good an expected. However when I click on a song (for instance the last one played), I see in the server logs that there are periodic connections to the same `ajax.erver.php` URL.

Something I have notices is that when hovering the mouse over the song link (before clicking on it), the URL it points to is https://example.com/song.php?action=show_song&song_id=28753. However, once clicked, the URL in the browser is
https://example.com/#song.php?action=show_song&song_id=28753. Other times, if the front page has the URL https://example.com/index.php (which for whatever the reason is not always the case), then the song URL once clicked is https://example.com/index.php#song.php?action=show_song&song_id=28753, which is certainly strange.

 I am not sure whether this confusion with the URLs is related to the fact that the ajax.server.php triggering is wrong, but I can confirm that if I enter in the browser the URL https://example.com/song.php?action=show_song&song_id=28753 (without any #) then the ajax.server.php periodic triggering does not happen anymore.

In some situations this can have a significant impact on server performance. For instance, it is not unusual that I have several ampache tabs, one with the front page and others with the details of a song, an album or an artist. This causes the server to be contacted periodically as many times as tabs are open.

### To reproduce

1. Go to https://example.com/index.php
2. Click on a song.
3. Monitor web requests coming from the browser (either in the apache, nginx logs or in Firefox Developer Tools.
4. Check that there are requests to URLs of the type  `/server/ajax.server.php?page=index&action=reloadnp`.

## Environment

* Ampache version: 5.6.0
* Web server + version:  apache2   2.4.54-1~deb11u1
* Server operating system: Raspbian 11
* Client operating system: Debian 12

### Client type

* Web: Firefox 102

**Comment by mitchray** [comment]
That's easily fixed, the interval timer isn't being cleared but with that PR it will be cleared when navigating away from the home page

**Comment by cquike** [comment]
I have tried your patch and indeed it works! Thank you very much.

**Comment by lachlan-00** [comment]
i am wondering out loud here but when searching while playing music there is a pause when clicking search in the music

pressing update from tags pauses while the dialog box is open too

could that be why this was left in there?
