### ISSUE TITLE
[Feature Request] Web-server config: Clarify patterns, and why they are needed.

### ISSUE THREAD

**Issue by IngwiePhoenix** [ampache/ampache#3520]
## Describe what you don't like about Ampache, or what it is missing
I tried setting up Ampache on my home server after a long, long round-trip of trying various music management solutions - gonic, Navidrone, Jellyfin, beet, ... - and found myself stumped during the web-server config.

I use Caddy v2 for all my webserver stuff, mainly because it handles TLS/SSL for me in the background. It's quite an advanced setup too, it shares certificates with another server via a VPN to handle all forms of certs.

Now, in the setup instructions, a Caddyfile is presented, but [the config is a Caddy v1 config](https://caddy.community/t/managing-a-lot-of-rewrites/19755/2).

I already tried to convert some of the rewrites, but truthfuly, there's just so, so many of them and an awful lot of them. Therefore, I wanted to know exactly which ones I actually needed before I went and edited everything, only to realize that I did more work than needed.

My usecase is the Subsonic part; as a MusicBee plugin and Android app.

I already tried to use the Docker container instead, but after one restart, the internal `apache2` service refuses to start up, and I couldn't find any related error log too. Plus, my music lives on an NFS share, so it'd actually be beneficial to just run Ampache directly on the OS (PHP 8.2, though!) to avoid mount-stacking and possibly even more permission problems.

## Describe how you would like the feature to work**
Document - or rather, clafify - which parts of the webserver config are important for what, and possibly why. Right now, it's just an extremely long configuration with no explanation as to what is what exactly. It's mentioned that some of the URL rewrites are for Subsonic - but which ones do I actually need and which ones are just "nice URLs"? In the end, those will be abstracted away either way through the apps I use - which might apply to others as well.

Thank you and kind regards,
Ingwie

**Comment by lachlan-00** [comment]
i've never used caddy before but outside of the channels you might need most of them. you can also disable features to avoid others. for subsonic some are mandatory.

for subsonic this rewrite subsonic calls to match ampache ones.
```
    # Rewrite rules for Subsonic backend
    rewrite /rest {
        r ^/rest/(.*).view$
        to {path}/ /rest/index.php?action={1}
    }
    rewrite /rest/fake {
        r ^/rest/fake/(.+)$
        to {path}/ /play/{1}
    }
```

The section for these rewrite rules is disabled by default but is enabled with 'Enable URL Rewriting'. it's also used for upnp or something but i actually forget which.

If you could regex that into pairs it could be cut down

`http://localhost/play/ssid/5bbbce613a86c32eef32c81c0b523492/type/song/oid/3/uid/1/format/raw/action/download/cache/1/name/Synthetic+-+Black-BlueSmoke.mp3`

needs to be converted into 
`http://localhost/play/index.php?ssid=5bbbce613a86c32eef32c81c0b523492&type=song&oid=3&uid=1&format/raw&action/download&cache=1&name=Synthetic+-+Black-BlueSmoke.mp3`
```
    # Beautiful URL Rewriting
    rewrite /play/ssid {
        r ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$
        to /play/index.php?ssid={1}&type={2}&oid={3}&uid={4}&name={5}

        r ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$
        to /play/index.php?ssid={1}&type={2}&oid={3}&uid={4}&client={5}&noscrobble={6}&name={7}

        r ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/player/(.*)/name/(.*)$
        to /play/index.php?ssid={1}&type={2}&oid={3}&uid={4}&client={5}&noscrobble={6}&player={7}&name={8}

        r ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$
        to /play/index.php?ssid={1}&type={2}&oid={3}&uid={4}&client={5&}noscrobble={6}&transcode_to={7}&bitrate={8}&player={9}&name={10}

        r ^/play/ssid/(.*)/type/(.*)/oid/([0-9]+)/uid/([0-9]+)/action/(.*)/name/(.*)$
        to /play/index.php?ssid={1}&type={2}&oid={3}&uid={4}action={5}&name={6}
    }
```

The art line here is needed for images
```
    # the following line was needed for me to get downloads of single songs to work
    rewrite /play {
        r ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$
        to /image.php?object_type={2}&object_id={3}&auth={1}

```

These ones i have no idea about but they're probably related to the beautiful rules.
```
        r ^/([^/]+)/([^/]+)(/.*)?$
        to /play/{3}?{1}={2}

        r ^/(/[^/]+|[^/]+/|/?)$
        to /play/index.php
    }
```

**Comment by mitchray** [comment]
OK to close I think
