### ISSUE TITLE
Integer overflow in 32 bits raspbery systems

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#3524]
## Description

Running `cli run:updateCatalog -cea` causes an integer overflow exception

### Describe the bug

I have seen that running `cli run:updateCatalog -cea` produces an exception in the logs:

```
TypeError Argument 2 passed to Ampache\Repository\Model\Catalog::set_update_info() must be of the type int, float given, called in
/srv/ampache_musica/src/Repository/Model/Catalog.php on line 3020
(thrown in /srv/ampache_musica/src/Repository/Model/Catalog.php:954)

Stack Trace:

  0) Ampache\Repository\Model\Catalog::set_update_info()
     at /srv/ampache_musica/src/Repository/Model/Catalog.php:3020
  1) Ampache\Repository\Model\Catalog::update_counts()
     at /srv/ampache_musica/src/Module/Catalog/Update/UpdateCatalog.php:275
  2) Ampache\Module\Catalog\Update\UpdateCatalog->update()
     at /srv/ampache_musica/src/Module/Cli/UpdateCatalogCommand.php:70
  3) Ampache\Module\Cli\UpdateCatalogCommand->execute()
     at /srv/ampache_musica/vendor/adhocore/cli/src/Application.php:366
  4) Ahc\Cli\Application->doAction()
     at /srv/ampache_musica/vendor/adhocore/cli/src/Application.php:280
  5) Ahc\Cli\Application->handle()
     at /srv/ampache_musica/bin/cli:79
```

 Looking a bit more in detail it seems that the error happens when trying to update the `size` column of the `update_info`
 table. The `update_counts() `function in `Catalog.php` goes through the song, video and podcast_episode tables to compute the total size of the catalogue. I can see that the SQL query in line 3010 of that file correctly gives the total size of the song and podcast_episode tables (I have no videos) despite the mariaDB server also running in the same 32 bits system. However, when this is cast into an integer in line 3016 it already overflows with value  `2147483647`. When two such numbers are added the `size` variable ends up being  `4294967294`, which is then passed later on to the `self::update_info()` function where it fails with the above exception.

### To reproduce

1.  Install apache in a 32 bits system
2. Populate a catalogue with more than 2GB of files
3. Run `cli run:updateCatalog -cea`
4. Check the output of the above command in the console

## Environment

* Ampache version: 5.6.0
* Web server + version: apache 2.4.54
* Server operating system: Raspbian GNU/Linux 11 on a  32 bits Raspberry Pi 2 Model B

**Comment by lachlan-00** [comment]
i need to work out what this is used for as it's a cumulative size of what you've streamed as a user.

**Comment by lachlan-00** [comment]
I think it may just be in this place.

The size is the catalog size in bytes which is how all the files are stored so it adds up. not sure how i'd fix that for a smaller ints unless i could pre-cache it
![image](https://github.com/ampache/ampache/assets/1305249/98125916-32dd-4e3d-9c5d-11af2e83ebe1)

On the other end there is also user play size which would do the same thing after time
![image](https://github.com/ampache/ampache/assets/1305249/d8900fa5-9d72-437b-80df-4fa143c6f6a4)

are they super important? not really. i'll put catches in it for now.

**Comment by lachlan-00** [comment]
i also might be able to pre-format the total so it just stores the string

**Comment by lachlan-00** [comment]
I've converted these fields from bytes to megabytes and put in updated counts.

will be a 6 release though as it's got a lot of data changes in there

**Comment by cquike** [comment]
It makes sense indeed to convert the fields to megabytes.

**Comment by lachlan-00** [comment]
tested a few times okay, the data is really only used visually so the higher calculation is fine.
