### ISSUE TITLE
 problem with the installation

### ISSUE THREAD

**Issue by mirx72rus** [ampache/ampache#3527]
Hello, there was a problem with the installation, php 8.1, mariadb
![Снимок экрана 2023-05-16 174940](https://github.com/ampache/ampache/assets/110601333/5af0a6b3-53be-48d5-95ce-aafe16d6a918)

**Comment by lachlan-00** [comment]
You need 2 php extensions.

If you use Debian/ubuntu the package names should be
```
php8.1-mysql
php8.1-intl
```

**Comment by mirx72rus** [comment]
thanks, it helped! now another problem swears at amapche.cfg.php
gave permission to the file 777
![Снимок экрана 2023-05-18 095228](https://github.com/ampache/ampache/assets/110601333/ac235143-7d08-4ee2-bff6-c80d159398df)
