### ISSUE TITLE
New albums get added under the heading A, L, B, U, M

### ISSUE THREAD

**Issue by MarkTerMors** [ampache/ampache#3531]
## Description
When new albums get added to Ampache they don't appear under "Albums" instead they apper under a new heading "A,L,B,U,M,S"

### Describe the bug
This also happens to compilations as C,O,M,P,I,L,A,T,I,O,N,S

### To reproduce

Just import a new album or compilation

### Screenshots

![Screenshot from 2023-05-31 15-35-17](https://github.com/ampache/ampache/assets/120024197/aaddef58-adfc-4fcc-bc91-8cf609b7a3b0)
## Environment

* Ampache version:
* 5.6.1-release
* Apache 2.4.54-1~deb11u1
* Server operating system:Debian 11
* Client operating system: Debian 11

### Client type

* Web

**Comment by MarkTerMors** [comment]
Hi,
This music was all tagged with beets. I guess I should post a bug there rather.
I guess this one is closed.

Thanks!
![Screenshot from 2023-06-01 08-31-16](https://github.com/ampache/ampache/assets/120024197/e6537bbc-1fde-4884-b8cf-a443fadbedd5)


$ metaflac --list 01\ Magic\ Man.flac  | grep -i release
    comment[9]: RELEASESTATUS=Official
    comment[11]: RELEASETYPE=a
    comment[12]: RELEASETYPE=l
    comment[13]: RELEASETYPE=b
    comment[14]: RELEASETYPE=u
    comment[15]: RELEASETYPE=m
    comment[33]: RELEASECOUNTRY=CA
    comment[55]: MUSICBRAINZ_RELEASEGROUPID=65ebadae-3fcc-32c2-a161-a2cd53854c9b
    comment[56]: MUSICBRAINZ_RELEASETRACKID=388bee57-0db5-30ba-9f8d-1f261db67785

**Comment by lachlan-00** [comment]
haha oh wow now that's funny. glad its not me!

**Comment by mitchray** [comment]
Closing as problem with beets
