### ISSUE TITLE
Error playing the random selection with two of the 4 types

### ISSUE THREAD

**Issue by DJ-SteffEN** [ampache/ampache#3535]
Hello,

While the selection of items for songs and videos works, it goes wrong for albums and artist (see picture).
The problem can be reproduced even at 'https://ampache.org/demo.html'.
Can someone please patch this?

with kind regards
DJ SteffE.N.

![image](https://github.com/ampache/ampache/assets/111641714/8e59a177-bcaa-455c-923d-2cce4e9a81c0)

**Comment by lachlan-00** [comment]
will check.

**Comment by lachlan-00** [comment]
I think this has always been the behaviour.

you're playing random songs/videos so the output/returned items are always songs.

public/templates/show_random.inc.php is the template for this action and it's browse types are only song/video.
![image](https://github.com/ampache/ampache/assets/1305249/761ea851-0c62-4608-a3ac-a11f3d54d8b1)

So your search rules look for a full albun or full artist and will return those results as song objects in the browse

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

thanks for the quick reply ... and yes I misinterpreted the result.
To eliminate such confusion I would adjust the dropdown field label.

My changes:
Label Play Random Selection: from 'Items Count' to 'Results' and.
Label Search: from 'Results' to 'Items'.

Thanks, and keep up the good work ... you are great
