### ISSUE TITLE
Add Lyrist instance for searching lyrics

### ISSUE THREAD

**Issue by CustardFlan** [ampache/ampache#3539]
Hi!
Thanks, again, for you hard work! I'm very happy using you server software!

But, something is missing from the lyrics search function, ChartLyrics indeed have some lyrics missing, so, i have searched some server software for acomplish this, i found:
https://github.com/asrvd/lyrist
Can be self-hosted, works very, very well for findind lyrics, it's fast, and simply works, using musixmatch, genius and google

So, i copied and modified the chartlyrics plugin to make it work with Lyrist, that uses JSON
I cannot submit a pull request, because i solely works on ARM, and i cannot compile GCM from GitHub
Again, asking you if you can merge this code:

https://cloud.itzti.li/s/48eJPqBMdQMk7dK

Only the user-configurable instance field is missing, it's beyond my poor PHP skills

And, i offer my personal instance to work with, it's included in the modified code, or use the one offered by Lyrist creator: https://lyrist.now.sh/

Thanks in advance!

**Comment by mitchray** [comment]
Just putting those files into a gist https://gist.github.com/mitchray/3f7298251899ee4ada8a66fba76bf4b7

**Comment by lachlan-00** [comment]
hey @CustardFlan is the site active still? i'll look at importing this into ampache after i release 6 this week

**Comment by CustardFlan** [comment]
> hey @CustardFlan is the site active still? i'll look at importing this into ampache after i release 6 this week

Yes, it's still active!

Add the URL as you wish, it's my personal server for self hosting, was running this for 2 years in a row, and i want to still mantain as is

Thanks for taking your time to review the suggestion!

**Comment by lachlan-00** [comment]
okay that's functional now. and in develop d8aa9cf86

missing /api/ and the track and artist had swapped.

**Comment by CustardFlan** [comment]
> okay that's functional now. and in develop [d8aa9cf](https://github.com/ampache/ampache/commit/d8aa9cf866acf268bb8b064ef3149546abd173af)
> 
> missing /api/ and the track and artist had swapped.

Now, updated to the latest commit, and, everything works ok!

Thanks!

**Comment by lachlan-00** [comment]
No problem,
I've also updated the get_lyrics function to actually save the data when it's pulled from a plugin as well so that will help everyone out by not continually polling the api.

later i'll put a delete option on the lyrics page for admins to allow clearing bad lyrics. it's nice to see a lyrics client that doesn't suck so much
