### ISSUE TITLE
Beets catalog unable to run any CLI commands

### ISSUE THREAD

**Issue by megatwig** [ampache/ampache#3541]
## Description
The (local) `beets` catalog type is completely broken for me in the `6.0.0-preview2` release, unable to read/play any songs from the database. This is on a fresh install of Ampache.

### Describe the bug

From poking around in the code, the issue is at 

https://github.com/ampache/ampache/blob/67973f7d4a29b3d8885140eb82303329b76a7c90/src/Module/Beets/CliHandler.php#L137

`$this->handler->get_path()` is called but `$this->handler` is undefined. Because of this, no beets CLI commands can be run and the catalog type is completely broken.

I'm not sure how this field is supposed to be populated, if someone wants to provide guidance I'm happy to put together a fix. I've hacked one together for myself for now.

### To reproduce

1. Create new `beets` catalog with an existing Beets DB
2. Run add/import/verify/any other commands on the catalog

## Environment

Running from a modified version of the `ampache/ampache:preview` Docker image (the `beet` CLI seems to be missing in the base image).

Beets version: 1.6.1 (built from HEAD ~yesterday)

**Comment by lachlan-00** [comment]
I'm just looking at updating remote catalogs now as well so this is related. i'm not a beets person but i'll look at this now if i can set up a test beets file

**Comment by lachlan-00** [comment]
beets does have a get_path command at least so that's a start `src/Module/Catalog/Catalog_beets.php`
![image](https://github.com/ampache/ampache/assets/1305249/b84fb3e7-d51e-47af-b255-985fd171aa26)

**Comment by lachlan-00** [comment]
this is hideously confusing...

This looks like a complicated way of handling it but there is a beets module and then your beets catalog can be remote or local.

with 005ca3770 i've set the catalog handler on contrstuct but then get a while amount of file issues after running an add. need to investigate more
![image](https://github.com/ampache/ampache/assets/1305249/1ddd9d2f-7cf6-4f03-a1bf-3879b6d7f9a2)

**Comment by lachlan-00** [comment]
you're using docker? this might be fixed now with 0cf0dcb7d so i'm going to rebuild the preview container now

(I also included the beet comand in the container which i swear i did before but it's back now)

![image](https://github.com/ampache/ampache/assets/1305249/0b3a38c2-af0b-419c-b68c-9369e027913c)

**Comment by mitchray** [comment]
Seems to be resolved? Reopen if not
