### ISSUE TITLE
[Feature Request] API to add songs to Democratic Playlist

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#3546]
[Democratic](https://ampache.org/api/api-json-methods/#democratic) lacks a method for adding songs, it has a 'play' method but that returns the URL for playback 

Objective is to mimic the current behaviour, where being in Democratic mode and clicking any Play button adds the items to the predetermined Democratic Playlist as set up in /democratic.php?action=show_playlist

**Comment by lachlan-00** [comment]
the vote parameter will cover it but only for one song?

**Comment by mitchray** [comment]
Oh does it? I haven't tried it yet, just going by the docs. If thats the case then all good

**Comment by lachlan-00** [comment]
Vote and devote which are kind of confusing but when you add a vote to a demo list it goes into the playlist if it doesn't exist
