### ISSUE TITLE
6.0.0-preview2: filter bar 'starts_with' not working

### ISSUE THREAD

**Issue by Deathcow** [ampache/ampache#3549]
### Describe the bug
Filter bar starts_with filter non functional. on the other hand: catalogue filtering works ok.

### To reproduce

1. Go to 'Albums'
2. Click on "Starts With" text box in filter bar
3. Enter some text
4. Click out of the box (why? enter does nothing)
5. "loading..." appears
6. filter box is cleared, no filtering occurs

### Expected behavior
filtered results should appear

## Environment

* Ampache version: 6.0.0-preview2
* Web server + version: nginx 1.25, php 8.1.20
* Server operating system: gentoo
* Client operating system: gentoo, firefox

### Client type

* Web

## Logs

no relevant error logs found

**Comment by lachlan-00** [comment]
looks like the data isn't sent / read as it goes blank after checking
i'll compare to older sites and check for differences

**Comment by lachlan-00** [comment]
found it. that was an atrocious code there fixed with 7d200928b

**Comment by Deathcow** [comment]
@lachlan-00 patch https://github.com/ampache/ampache/commit/7d200928b8a8f23ab4f768440c5d49e07410bbd4.patch fixes this issue for me. thanks
