### ISSUE TITLE
ampache redirects to https when force_ssl = false

### ISSUE THREAD

**Issue by Deathcow** [ampache/ampache#3550]
### Describe the bug
ampache writes all urls with https when force_ssl is set as false in config

### To reproduce

1. set force_ssl = false in confg
2. go to http://ampache
3. nothing loads except the first request, because all generated urls point to https
### Expected behavior
stay in http scheme

Cutting to the chase, this is clearly wrong:

src/Config/Init/InitializationHandlerConfig.php:
```if (!empty($results['force_ssl']) || $this->environment->isSsl() === true) {```

makes zero sense to me. Just because it's non-empty doesn't mean it's true.

probably something like this is appropriate:
```
commit cfaa1c8d7d6e1f363648933e9f2508144a0917d0
Author: Deathcow
Date:   Tue Jul 11 22:07:26 2023 +0200
 
    fix force_ssl usage
 
diff --git a/src/Config/Init/InitializationHandlerConfig.php b/src/Config/Init/InitializationHandlerConfig.php
index 9e43de886..59b191855 100644
--- a/src/Config/Init/InitializationHandlerConfig.php
+++ b/src/Config/Init/InitializationHandlerConfig.php
@@ -63,7 +63,7 @@ final class InitializationHandlerConfig implements InitializationHandlerInterfac
         $results['version']            = static::VERSION;
         $results['int_config_version'] = static::CONFIG_VERSION;
 
-        if (!empty($results['force_ssl']) || $this->environment->isSsl() === true) {
+        if ($results['force_ssl'] == "true" || $this->environment->isSsl() === true) {
             $protocol = 'https';
         } else {
             $protocol = 'http';

```

**Comment by lachlan-00** [comment]
it doesn't that's expecting perfect config without user input

probably a make_bool
```
if (make_bool($results['force_ssl']) || $this->environment->isSsl() === true) {
```

**Comment by lachlan-00** [comment]
again , set in dev and patch5

**Comment by Deathcow** [comment]
@lachlan-00 one more thought: Isn't the comment in the config file also lying?

```
; If Ampache is behind an https reverse proxy, force use HTTPS protocol.
; DEFAULT: "false"
```
but that isn't true, is it? the default is undef/unset. Seems like config handling could use an overhaul. Defaults should actually be set and overwritten by custom values, imho. If the default is "false" setting the value in the user config to "false" should never cause a change in behavior.

**Comment by Deathcow** [comment]
@lachlan-00 fyi, both fixes cause warnings in ampache cli when force_ssl is unset:

```
sudo -u nobody php /var/www/localhost/nginx/ampache/bin/cli run:updateCatalog -a -v                                                                       
PHP Warning:  Undefined array key "force_ssl" in /var/www/localhost/nginx/ampache/src/Config/Init/InitializationHandlerConfig.php on line 66 
```

**Comment by lachlan-00** [comment]
yeah i added a ?? in to fix that after i posted this
```
        if (make_bool($results['force_ssl'] ?? false) || $this->environment->isSsl() === true) {
            $protocol = 'https';
        } else {
            $protocol = 'http';
        }
```

**Comment by mitchray** [comment]
Seems to be fixed
