### ISSUE TITLE
[BUG] Playlist items wrong in smart playlist api when results are zero

### ISSUE THREAD

**Issue by lusum** [ampache/ampache#3553]
### Describe the bug

When a smart playlist has zero items, the result items in api are 5000.

### To reproduce

Create a smart playlist with zero results.
Api returns :
<items>5000</items>

Tested only with smart playlist and xml api (6.0)

**Comment by lachlan-00** [comment]
the item count? that must be a 0/null fallback. good spot
![image](https://github.com/ampache/ampache/assets/1305249/aa5e0f0a-8db6-4fd9-bca9-ca81fc7ef0be)

**Comment by lachlan-00** [comment]
affects all api versions. it actually raises a further issue.

when a search is run it sets last_count which is the result size. BUT a search run per user and  possibly has different counts depending on the user who runs the search...

what we should do is save the last_count per-user for searches. something to go into the user_data table

**Comment by lachlan-00** [comment]
Question on how this should go @lusum 

should there be a null return on items if it's never been run?

e.g.

* If the search has never been run Items = null
* if it's empty allow 0
* else return limit/item total

For api3/4/5 i'll stick with a 0 int but for 6 that might be better to show it's fresh?

**Comment by lusum** [comment]
Yes, IHMO should be ok.
BTW, another bug: if you set a limit and the items are less than limit, smart playlist returns the  limit

**Comment by lachlan-00** [comment]
it's cast as an int so null values are 0 anyway. I've set it with c04fa0734 and i'll update the demos if you use those

**Comment by lachlan-00** [comment]
I think this was done originally as older api clients like power ampache didn't let you load a playlist if the item count was zero. now we save the count of items as a value so it's not needed to keep this workaround

**Comment by lusum** [comment]
It works now, thanks!
