### ISSUE TITLE
New catalog doesn't behave as expected.

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3555]
## Description
In an effort to work around #3554, I deleted the catalog via the GUI and re-created it so it would be empty.  I then put some content into the catalog directory and did an "add" to move the entries into the database.  The new content shows up in the "newest" section, but the artists never show up when doing any kind of search, however, the songs added by that artist do.

On the Subsonic interface (using the DSub Android Client), the new catalog appears in the Libraries drop down menu, but instead of showing content, it says "No Data".  The new content does show up in the Recently Added section, and the catalog is in the folders dropdown in the Library screen.  However, querying the server for the contents of that catalog show "No Data".

I'm perfectly willing to attribute this to some database error over time, but the query logs are not showing any errors.

### Describe the bug
The catalog isn't being built correctly, or maybe not completely.  The artists are not added to the search results and the subsonic API isn't returning any content for the catalog when queried.

### To reproduce
Create a new catalog on an empty directory.  Add some content.  Search for an artist that was just added in the top search bar and see the new artist isn't listed.  Using the Subsonic interface, see that the catalog query doesn't return any data,.

Note: all existing catalogs still work as expected.

### Expected behavior
I expected artists/album/songs to appear in the searches (especially the artist).  I expect all content in the catalog to be browsable via the Subsonic interface.

## Environment

Ampache Docker Develop (latest)

### Client type

* Ampache
* SubSonic

**Comment by troycarpenter** [comment]
I am going to try a fresh install and create the database from scratch to see if some database corruption may be causing this.

**Comment by troycarpenter** [comment]
When performing  a fresh install, I initially created two new catalogs with content.  The same behavior persisted:

- In Ampache web GUI, searches for the artist names didn't return any results.  Searches for albums and songs did return results.
- In DSub (Subsonic interface), all the albums showed up in Recently added.  Artists did not show up in search, but albums and songs did, similar to the web interface.
- In DSub, the library listing of all the catalogs returned "No data".

**Comment by lachlan-00** [comment]
most of that data is done with catalog mapping so that might be missing.

do a garbage collect action in the ui or -t in the cli

**Comment by troycarpenter** [comment]
I've decided to focus on one problem at a time, and to start I'm restoring an old image before all my problems and focus on #3554 .  However, I did do a garbage collection on this database and it did not change the issue presented in this ticket.  In fact, as mentioned above, a brand new install with only one catalog with music caused the same "no data" issue in DSub.

I want to go back to the other ticket and try to figure out why the clean isn't working.

**Comment by troycarpenter** [comment]
Also, when I restored an old backup, I noticed that the catalog I had been testing with was still messed up in DSub.  I then cleared the cache in DSub on Android and I was able to get the data for that specific catalog.  Mind you, this was from an older database, but it does force me to test again with a fresh install and new catalog to see if the "no data" problem still happens, or if the DSub cache was corrupted and not updating when going back to a known good database.

**Comment by troycarpenter** [comment]
I tried a hunch and looked at the table "deleted_song".  There were about 12k entries in it.  I deleted the entries thinking that maybe those entries already being there were preventing the clean/garbage collection from happening.  I was wrong.

**Comment by gwstorm** [comment]
It's not specific to you. I had the same thing happen to me with a docker image that I had been testing with. Updating it at first led to a database connection issue, noted [here](https://github.com/ampache/ampache-docker/issues/102). I got through that and still had no libraries in Dsub. Since it was a test instance, I just rebuilt it from scratch just now an also get No Data when trying to view the library. 

Something I've noticed though is that Dsub isn't picking up the Artist data. Maybe that is what populates the library page. I can search for artists and nothing comes up. If I search for a song or browse in alphabetical, everything populates and I can play music. So everything is still available, just not displayed on that one page. Maybe it's just a minor issue with that?

**Comment by gwstorm** [comment]
I'm past this now, but clearing cache and even completely resetting Dsub wasn't working for me, even on completely fresh installs of Ampache. Creating a small test library of just a few albums worked instantly though. Afterward, I was able to add the full libraries and everything is fine again.

**Comment by lachlan-00** [comment]
search results all come from the catalog_map table. i did take out the mapping part due to speed issues but it might need to go back in to at least get that going after changes.

![image](https://github.com/ampache/ampache/assets/1305249/bc6cd65a-6e2a-44db-aefa-6e71de1aedba)

**Comment by lachlan-00** [comment]
i've made some changes to do these slow actions when files are add or removed as well as with -t

**Comment by lachlan-00** [comment]
built for docker too. now this will always update mappings when files are added/cleaned

**Comment by troycarpenter** [comment]
I need to see if this is going to fix my next problem, and that's that new artists do not show up in searches nor are they in the artist lists in Subsonic for a catalog (or library as *sonic calls it).

**Comment by troycarpenter** [comment]
Fixed with recent update
