### ISSUE TITLE
Setting ACL user to ALL does not actually set to all. Web interface lockout risk.

### ISSUE THREAD

**Issue by gwstorm** [ampache/ampache#3556]
## Description
Setting ACL's in the web interface and selecting ALL for users actually results in no one, including admin.

### Describe the bug
The default database entry for ALL is `-1`. When setting ALL through the web interface, it sets `0` instead, which appears to be no one. From what I've gathered, each user is assigned a number in order. Admin, the account created during setup, is `1`, next user is `2` and so on.

It can also affect the default rules *if* a user chooses to edit the default ACL and clicks Update. Even if no changes were made, the ALL entry will be changed from `-1` to `0` and all users will be locked out.

The difference in settings are apparent in the web interface as ALL will be listed in the user column as `All` and when set by the web interface, it will be listed as an empty user in parenthesis like so - `()`

### To reproduce

When creating an ACL from scratch -
1. With admin privileges, go to Add ACL.
2. Fill in any info and set user to All.
3. Click on Create ACL.
4. Go back to Show ACL's. The newly created ACL user column should now show `()` while the other defaults will show `All`.

Lock out all users without making changes
1. With admin privileges, Show ACL(s).
2. Edit default web interface ACL.
3. Make no changes, just click update.
4. Go back to Show ACL's. The default web interface user column should now show `()` while the other defaults will show `All`.
5. Logout and you will immediately be met with the restricted access page and unable to login, requiring manually changing the `access_list` database entry from `0` to `-1` to restore access.
 
### Expected behavior

Setting User to All should set All, not an empty user.

## Environment

* Ampache version: 5.6.1
* Web server + version: Nginx Mainline 1.25 / PHP 8.2
* Server operating system: Arch Linux
* Client operating system: Arch Linux

I've verified this as well in a fresh docker image, so I don't think it's related to php config or ampache settings, so for the sake of keeping this somewhat short, I've opted out of pasting the configs. I can share them if needed.

**Comment by gwstorm** [comment]
5.6.2 doesn't seem to resolve it for me.

**Comment by lachlan-00** [comment]
okay so the table works until you change it then the UI will overwrite it to 0.

ui bug for sure so i'll do a db update and fixes just in case it's been set.

**Comment by lachlan-00** [comment]
i see it's 0 in the template cause it's null / empty there
![image](https://github.com/ampache/ampache/assets/1305249/b1f75248-7900-4d9c-8197-69b2e486ec08)

**Comment by gwstorm** [comment]
Oh I didn't even think to check there. I actually just edited that value and put in -1 and it applied correctly.

**Comment by lachlan-00** [comment]
fixed in develop / patch5 will needs a wait as i was working on release today and didn't see this but it's just a -1 for the all users
![image](https://github.com/ampache/ampache/assets/1305249/3a2db3b4-1111-4de0-8f28-459eedf9a4ff)

**Comment by lachlan-00** [comment]
i'll put some proper workarounds in cause that can really screw things up if we're not careful though

**Comment by gwstorm** [comment]
Awesome. Yeah, definitely want to make sure it's applied correctly for sure! Thanks for looking into it. No major rush.

**Comment by lachlan-00** [comment]
lots of expansion required, this is the first card on the cli project which i'll start right after 6 is out

https://github.com/ampache/ampache/projects/8

**Comment by gwstorm** [comment]
This is fixed now in 6.0.0

Thanks!
