### ISSUE TITLE
Version is now showing the git hash

### ISSUE THREAD

**Issue by brantlk** [ampache/ampache#3559]
## Description

I just upgraded to 5.6.2 using the git flow... I've got my local `release5` branch so do

```
git fetch
git merge --ff-only origin/release5
```

After the upgrade, the `Ampache Debug` page shows the version as the git hash rather than as `5.6.2`. Maybe this is the expected behavior but I think it changed.

```
Ampache Update
Installed Ampache version: 85309f356e2a005d57253e71de2de1d693177364.
Latest Ampache version: 85309f356e2a005d57253e71de2de1d693177364.
GitHub Branch: release5
```

### Expected behavior

The "Installed Ampache version" and "Latest Ampache version" should show `5.6.2`.

## Environment

* Ampache version: 5.6.2
* Web server + version: Apache
* Server operating system: Ubuntu on Raspberry Pi

**Comment by lachlan-00** [comment]
This is the conundrum. You're updating with Git so the version is checking for git versions.

This was done for a few reasons to fix up some errors with the update process in this commit 98d8990dd

Specifically here in the autoupdate class
![image](https://github.com/ampache/ampache/assets/1305249/e9475699-bf9c-4243-9c81-1d962478323a)

I do think the process can be better though.

I would like it to possibly provide more options to

* show/hide git version (e.g. force tag only)
* when force release tag only; allow zip OR git update if detected (like the config file update process)
* allow git updates but notify based on tag changes (e.g. when tag is > than your tag)

let me know what you think would be better ways of handling this. this is a classic ampache process of doing 2 separate things at the same time and pretending they're the same thing so i'd like to work on it more.

**Comment by brantlk** [comment]
If you're willing to exec the git CLI rather than read a file, the way that a version string is typically generated from a git repo is to use `git describe`. Here's what it shows on my system:

```
www-data@ubuntu:~/ampache$ git log --oneline -n1
85309f356 (HEAD -> release5, tag: 5.6.2, origin/release5) Merge pull request #3533 from ampache/patch5
www-data@ubuntu:~/ampache$ git describe
3.6-alpha6-7305-g85309f356
www-data@ubuntu:~/ampache$ git describe --tags
5.6.2
```

The `3.6-alpha6-7305-g85309f356` string is because `3.6-alpha6` was the last "annotated" tag and the current commit is 7305 commits since then.
Using `--tags` doesn't require annotated tags so works with the repo as it is now.

See https://git-scm.com/docs/git-describe

So that's how I would prefer the installed version to be displayed: the output of `git describe`.

I don't know how this works with checking what's the latest version available for download / update to.

**Comment by brantlk** [comment]
If I was using develop branch I'd be fine with showing commit hashes. It would be nice if the GitHub API had an option to get the `git describe` output for a branch then you could use that...

```
$ git describe --tag
6.0.0-preview2-52-g12112a42f
```

If GitHub had updates then the "version" string would be '-53-g...', etc.

**Comment by brantlk** [comment]
I don't see any way through the GitHub API to get the `git describe` output for a commit. "Get a commit" output (https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28) didn't include it.

**Comment by lachlan-00** [comment]
actually you just answered this.

release5/6 are release branches so i should keep them away from the git updates and then allow updating from get on new version if the release is new

**Comment by lachlan-00** [comment]
i've set that now in develop and patch5 to only report on release values when you are using a release git branch
![image](https://github.com/ampache/ampache/assets/1305249/9919cef3-b2e1-4f2a-9ff5-16f9f679810a)


I'll look at more options for this later to include git updates too

**Comment by lachlan-00** [comment]
much nicer way of doing it.

**Comment by mitchray** [comment]
Seems to be resolved? Reopen if not
