### ISSUE TITLE
API: `art` links to image.php are generated with unnecessary `auth` argument

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3564]
In the XML and JSON API, the `art` property on songs/albums/etc. is given like https://develop.ampache.dev/image.php?object_id=35&object_type=album&auth=0193b63a1593f5aa18e1d5deaf837dee&name=art.jpg. Yet, the image.php API does not require any authentication and the link https://develop.ampache.dev/image.php?object_id=35&object_type=album&name=art.jpg works just as well. Based on https://github.com/ampache/ampache/issues/1340#issuecomment-780241681, not requiring authentication seems to be a conscious decision.

This may not seem like a big problem but it lures the API clients to do silly things like the one shown here: https://github.com/mitchray/ample/blob/26b3e5bb67a32c24d7674228bfa9f5c6f73c8faa/src/logic/helper.js#L244-L255. It would be better to not include any unnecessary parts in URLs to not create a temptation for the clients to abuse the API.

**Comment by mitchray** [comment]
While on the topic I wonder if editing art also changes an items 'update' time then we can include that for cache busting, something like &lastUpdated=123456789

**Comment by lachlan-00** [comment]
it doesn't change the update time of the object right now or record changes in the image table.

**Comment by lachlan-00** [comment]
yeah i like it without requiring auth so i'll take it out now.

**Comment by lachlan-00** [comment]
removed with 8bed3788b
