### ISSUE TITLE
Upload link not present in uploads section

### ISSUE THREAD

**Issue by haelduksf** [ampache/ampache#3573]
### Describe the bug
The "upload" link in the upload section is missing. The upload page can still be reached by manually changing the URL to upload.php (which also causes the link to appear). This happens for multiple users with admin/catalog manager roles. 

### To reproduce

1. Go to the index page
2. Click on the preferences gear icon

### Expected behavior
Upload page should be linked under Uploads > Upload

### Screenshots
Sidebar for user with category manager role with url /index.php
![image](https://github.com/ampache/ampache/assets/1475264/7bd01777-5c98-43e0-b39b-53aabb6b2c82)
Sidebar for user with category manager role with url /upload.php
![image](https://github.com/ampache/ampache/assets/1475264/9dc2beea-85af-4118-9104-f55a177f2089)

## Environment
Docker compose
* Ampache version: 5.6.2
* Web server + version: Whatever is in the Docker container
* Server operating system: raspbian
* Client operating system: Windows, Android, iOS

### Client type

* Web

## Settings

Admin settings for uploads
![image](https://github.com/ampache/ampache/assets/1475264/6e99de31-6797-4a1b-bbac-17977cb33e63)

## Logs
No relevant logs

**Comment by mitchray** [comment]
Uploads show for my docker which is on the preview tag (6.0.0+)

![firefox_SuqoDar0q8](https://github.com/ampache/ampache/assets/5735900/3250e2df-0e2f-4087-9697-99ec55af5620)

Though if you toggle the Playlist header then the Uploads header is hidden, so there is something glitchy happening for sure

![firefox_QeBcXGgrYd](https://github.com/ampache/ampache/assets/5735900/c276b291-f95c-42e0-a2ff-509b00e3b173)

**Comment by lachlan-00** [comment]
Upload calculation is different between 5 and 6 but neither of them hide a single line in the section it's all or nothing. so your issue @haelduksf might be that it's erroring with a missing translation.

your log will probably have something like 
```
2023-08-17T05:29:47+00:00 [ampache] (log.lib) -> [Runtime Error] Undefined variable $t_upload in file /var/www/music/public/templates/sidebar_preferences.inc.php(83)
```

In ampache5 anyone user or higher should be able to see the upload section so i think we just need to work out why it's not loading the translation

@mitchray i can see that collapse, i'll see what i'm missing. maybe a closing UL or LI

**Comment by lachlan-00** [comment]
both of those should be fixed now. the translation was missing in patch5 so set with 3d6d9ae0c
closing UL set with a23ae23aa in develop

**Comment by haelduksf** [comment]
Looks good in 6.0.2!
