### ISSUE TITLE
API: Inconsistency in JSON/XML formats of `get_indexes`

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3580]
The results of the [`get_indexes`](https://ampache.org/api/api-xml-methods#get_indexes) method are quite different between the JSON and XML APIs: In the JSON API, the result objects seem to contain all the same fields as the entities returned by the methods like [`artists`](https://ampache.org/api/api-xml-methods#artists) or [`songs`](https://ampache.org/api/api-xml-methods#songs). Meanwhile, the result objects of `get_indexes` in the XML API contain only fraction of the fields.

Now, I know that the `get_indexes` method is already on its way out and you may not want to change it anymore at this point. But it should be noted that also the method [`get_similar`](https://ampache.org/api/api-xml-methods#get_similar) uses the same result formats. I would suggest that at least the `get_similar` method is modified to return all the fields also in the XML API. There shouldn't usually be so many results in this method that returning more fields would be an issue. And at least the Ample client already utilizes the `art` field of the results of the `get_similar` JSON API, so doing it the other way around and dropping fields from the JSON API would be bad.

**Comment by lachlan-00** [comment]
these are documented as song | artist in xml so they should return the object matching everywhere else.

Going to leave get_indexes as the xml for that function is a mess. but moved get_similar to use artists and songs functions in xml 4e380120a

**Comment by mitchray** [comment]
Seems to be resolved
