### ISSUE TITLE
JSON API: `user_preference` returns a 1-item array

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3581]
In the APIv5, most of the JSON API methods returning a single object were changed to return a plain JSON object instead of returning an anonymous array containing the said object. Apparently the `album` method was forgotten and it got the same treatment in APIv6.

But even in APIv6, the `user_preference` method still returns a 1-item anonymous array. I presume that `system_preference` method does the same although I couldn't test this on the demo server without the admin rights. Maybe these could be aligned with the others in APIv7?

**Comment by lachlan-00** [comment]
definitely the same for system_preference.

I think these are important enough to get out this week. I don't know if that's a good or bad idea but i'd like 6 to be complete without issues.

**Comment by lachlan-00** [comment]
i also haven't documented those responses so i'm leaning on bugfix this week

**Comment by paulijar** [comment]
Okay, I didn't realize that the v6.0.0 was only just released so changing the APIv6 can still be justified. Heads-up for @mitchray who is using the `user_preference` method.

**Comment by lachlan-00** [comment]
Just a genuine miss by me cause i haven't scripted it in my tests yet.

6 is meant to be clear about what you get and if data isn't returning what i've said it should it's a bug to fix it's just very lucky that we have people looking at these things so we can get it quick
