### ISSUE TITLE
API playback broken after 6.0.1 update

### ISSUE THREAD

**Issue by gwstorm** [ampache/ampache#3588]
## Description
This is a continuation of a [reddit post](https://www.reddit.com/r/ampache/comments/163eqqf/release_600_ampacheampache_its_here/jy71sft/). 6.0.0 broke local web playback (should I make a separate issue for that?) for me and the 6.0.1 update broke API playback. I was provided with a [gist](https://gist.github.com/lachlan-00/e672da6cf40a360f7640902ce7d723df) to use in place of the existing `src/Module/Playback/Stream.php`. Using that file, all playback remained broken and local web playback was unresponsive. Clicking play on a song doesn't bring up the control bar at the bottom of the browser with the controls for playback. 
### Describe the bug
6.0.0 broke local web playback. API and remote web is fine.
6.0.1 broke API playback and did not resolve local web playback. 
The provided gist seems to have damaged the web playback controls to the point where they don't show up

### To reproduce

1. update to 6.0.1
2. play a song via Dsub on Android or Web (firefox in this case)

## Environment

* Ampache version: 6.0.1
* Web server + version: nginx-mainline 1.25.2 and PHP 8.2
* Server operating system: Linux
* Client operating system: Web browser on linux, Dsub on Android

### Client type

* Web - Firefox 116.0.3
* SubSonic - Dsub 5.5.3

## Settings

[ampache-6.0.1-debug.txt](https://github.com/ampache/ampache/files/12470749/ampache-6.0.1-debug.txt)
[config.txt](https://github.com/ampache/ampache/files/12470750/config.txt)

**Comment by lachlan-00** [comment]
fixing that's would be a good start
`Call to undefined method Ampache\Module\Playback\Stream::get_stream_types_for_type()`

**Comment by lachlan-00** [comment]
There's no difference between ampache5 and ampache6 in that function/playaction.

Is there an error log in nginx that you can get? i can't see a problem with the code in the ide

The error is when the play action is tring to load the song and work out transcoding so maybe do it right in the class and lets see what errors are happening
```
$valid_types = Stream::get_stream_types_for_type($media->type, $player) ?? array('native');
```

![image](https://github.com/ampache/ampache/assets/1305249/ea359964-8190-4764-9ce3-8f87851e77a5)

**Comment by gwstorm** [comment]
Sorry for the delay. I have to wait for a time where I know its not going to be used and then re-update and reapply the changes. So, with that being said, this is 6.0.1 with the modified `Stream.php` and `PlayAction.php`. I cleared the log for each instance and then initiated a fresh start, so the web and dsub are independent of each other. The nginx-error is just generic between things.

`Call to undefined method Ampache\Module\Playback\Stream::get_stream_types_for_type()` still persists and as far as I can tell, there are no changes to report. Everything still seems to be broken all the same.

I noticed that my Dsub instance is hitting the server without the port number at all. I'm wondering if the regex changes you mentioned between 6.0.0 and 6.0.1 that were intended to fix duplicate port numbers for some is actually entirely removing my port altogether.

Should I consider a clean install of ampache, keeping my existing database and config file? If nothing related seemed to have been changed between versions, I don't want to waste a bunch of your time chasing potentially nothing. I'd imagine others would be running into the same issue by now.

[ampache-debug-Dsub-remotePlayback-6.0.1.txt](https://github.com/ampache/ampache/files/12482427/ampache-debug-Dsub-remotePlayback-6.0.1.txt)
[ampache-debug-web-localPlayback-6.0.1.txt](https://github.com/ampache/ampache/files/12482428/ampache-debug-web-localPlayback-6.0.1.txt)
[nginx-error.txt](https://github.com/ampache/ampache/files/12482429/nginx-error.txt)

**Comment by lachlan-00** [comment]
can you also change the play type to stream and then get the generated link form the m3u?
![image](https://github.com/ampache/ampache/assets/1305249/26fdab3d-4017-4d0d-948f-c323b7d7a034)

**Comment by gwstorm** [comment]
```
#EXTM3U
#EXTINF:173, Spiritbox - Holy Roller
http://server:9999/play/index.php?ssid=73b5d82155017d3dca6c2e367e29237f&type=song&oid=2695&uid=1&transcode_to=mp3&name=Spiritbox%20-%20Holy%20Roller.mp3
```

**Comment by lachlan-00** [comment]
ok so that looks like it's the correct stream url

does a download download?

`http://server:9999/play/index.php?ssid=73b5d82155017d3dca6c2e367e29237f&action=download&cache=1&type=song&oid=2695&uid=1&name=Spiritbox%20-%20Holy%20Roller.mp3

**Comment by lachlan-00** [comment]
I've reverted the function back to the 5.6.2 version. this might work so lets see?
[Stream.php.txt](https://github.com/ampache/ampache/files/12482623/Stream.php.txt)

![image](https://github.com/ampache/ampache/assets/1305249/8b24f42b-b0ad-4a5f-85cf-5a12c5f0e3bb)


I think it may be the playaction using the new function so i'll look at that too

**Comment by gwstorm** [comment]
Everything works now. Dsub and web, local and remote.

**Comment by gwstorm** [comment]
> ok so that looks like it's the correct stream url
> 
> does a download download?
> 
> `http://server:9999/play/index.php?ssid=73b5d82155017d3dca6c2e367e29237f&action=download&cache=1&type=song&oid=2695&uid=1&name=Spiritbox%20-%20Holy%20Roller.mp3`

Sorry. Missed this one. Yes. That was pulled from the downloaded file.

**Comment by lachlan-00** [comment]
weird. so the revert is fine. i'll make a hybrid revert that includes the fallback and streamtoken

**Comment by gwstorm** [comment]
I owe you beer/coffee or something. The only thing I know about php is managing its end use cases.

**Comment by lachlan-00** [comment]
OK, i think i know what's happening. there might be no matches array with local disabled
bb543e42d gets the preg going again

[Stream.php.txt](https://github.com/ampache/ampache/files/12483142/Stream.php.txt)

**Comment by gwstorm** [comment]
This Stream.php worked on all fronts as well.

**Comment by lachlan-00** [comment]
fuck yeah! i think that's the issue

**Comment by lachlan-00** [comment]
(that was an annoying one.)

**Comment by gwstorm** [comment]
Absolute legend. Once that hits release, I'll update, confirm and close.

**Comment by gwstorm** [comment]
Golden
