### ISSUE TITLE
Allow per-user timezone preference to allow various timestamps to be displayed in the user's timezone.

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3592]
Creating a feature request from this discussion.

### Discussed in https://github.com/ampache/ampache/discussions/3590

<div type='discussions-op-text'>

<sup>Originally posted by **troycarpenter** August 30, 2023</sup>
I've noticed that all my logs, notifications, and anything that generally uses a timestamp is all in UTC.  Has anyone figured out how to get the system to report the times appropriate for the local timezone?

I have tried using the TZ=America/Chicago variable in the docker-compose file, but even though the system responds with the correct timezone when I type "date" on the cli, it doesn't change the logs/notification timestamps.

While it would be nice if this were a per-user setting since I have some users in other timezones, I would at least want timestamps to be in the timezone local to the server.</div>

**Comment by lachlan-00** [comment]
Per user will require a bit of tweaking but should be okay. There is custom_datetime power just so I'll make custom_timezone

There are 419 different zones on my server so a reduced list or manual entry textbox list will be better

**Comment by lachlan-00** [comment]
Commit [904c163](https://github.com/ampache/ampache/commit/904c163209fde157fbe5bce9da9f820668273899) sets it on the server.

Then I will add to the DB for user overrides

**Comment by troycarpenter** [comment]
Yes, I was thinking a free-form entry as well instead of a drop-down from all the possible entries.  If the user gets it wrong, then it just defaults to UTC.

**Comment by troycarpenter** [comment]
So just to be sure I understand the logic...
Server timezone will be in the config file and used for displaying date/time stamps.
Server timezone will be UTC if the value is not formatted correctly (since it is a free-form field)
Server timezone should default to UTC if not set by admin.

User timezone will be a preference the user can set and will override the server timezone for GUI elements
User timezone will default to server setting at user creation
User timezone will be UTC for the same failure reasons as the server timezone.

Is that your thinking?

**Comment by lachlan-00** [comment]
that's it.

the idea is that you set it for your server and use the default php fallbacks.

then you can allow user overrides in the site as a user. if the user doesn't set a valid entry you fallback to server which falls back to UTC.

looking at hte DB pref now

**Comment by lachlan-00** [comment]
This is now set. the custom timezone is validated against the list otherwise it's not saved.

custom timezone '', server timezone Australia/Brisbane
![image](https://github.com/ampache/ampache/assets/1305249/2664b22a-ddb9-4e01-ba90-50db1bb5daf1)

custom_timezone UTC, server timezone Australia/Brisbane
![image](https://github.com/ampache/ampache/assets/1305249/19ce8d1f-5cbe-485a-be7c-627c7441a59c)


outside of this i also think i'm going to update the server logs to allow server time instead of UTC
