### ISSUE TITLE
API method `list` returns an empty result for `type=playlist`

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3594]
While testing the API on develop.ampache.dev, I noticed the following:

The new APIv6 method `list` seems to always return an empty result set when called with `type=playlist` and either `hide_search=0` or the `hide_search` argument is omitted. With `hide_search=1`, the result set contains 16 items which matches the result of `get_indexes` with `type=playlist&hide_search=1`, i.e. this works as expected. The `get_idexes` without `hide_search` or with `hide_search=0` returns 50 items.

**Comment by lachlan-00** [comment]
Catalog::get_name_array can't id the 'smart_' lists.

That needs a little jigging as it's still the hack around treating them as all as a single item.

**Comment by lachlan-00** [comment]
i have it written now just have to test when i get back from work.
