### ISSUE TITLE
API: Inconsistency in the JSON/XML formats of the action `browse`

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache#3595]
In the new APIv6 action `browse`, the keyword used for the array of children is different between the JSON and XML APIs. In the former it's `browse` and in the latter it's `list`. It would sure be nice to use the same keywords in both APIs. Here's some example results from develop.ampache.dev:
```
{
    "total_count": 2,
    "catalog_id": "",
    "parent_id": "26",
    "parent_type": "root",
    "child_type": "catalog",
    "browse": [
        {
            "id": "1",
            "name": "music",
            "prefix": null,
            "basename": "music"
        },
        {
            "id": "2",
            "name": "podcast",
            "prefix": null,
            "basename": "podcast"
        }
    ]
}
```
```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <total_count>2</total_count>
  <catalog_id/>
  <parent_id>26</parent_id>
  <parent_type>root</parent_type>
  <child_type>catalog</child_type>
  <list id="1">
    <name><![CDATA[music]]></name>
    <prefix><![CDATA[]]></prefix>
    <basename><![CDATA[music]]></basename>
  </list>
  <list id="2">
    <name><![CDATA[podcast]]></name>
    <prefix><![CDATA[]]></prefix>
    <basename><![CDATA[podcast]]></basename>
  </list>
</root>
```

**Comment by lycurgus** [comment]
Just to hopefully short-cut some debugging/investigation effort, it looks like the difference is between https://github.com/ampache/ampache/blob/develop/src/Module/Api/Xml_Data.php#L571 and https://github.com/ampache/ampache/blob/develop/src/Module/Api/Json_Data.php#L305.

**Comment by lachlan-00** [comment]
set with 1952af3ad. thanks @lycurgus that made it very obvious.

list returns list, browse should be returning browse

**Comment by mitchray** [comment]
Seems to be fixed
