### ISSUE TITLE
Combination of Smart Playlists ignores limits

### ISSUE THREAD

**Issue by brantlk** [ampache/ampache#3601]
### Describe the bug

I have a smart playlist that combines several other smart playlists.
My "RatingTime" playlist has match "any rule", then each of the rules is another smart playlist (there are 12 of them).
Currently when I look a this playlist it shows that there are 9354 items (my entire library).

When I add up the contents of the 12 combined smart playlists, there are only (14+48+40+30+20+10+5+3+1+15+1+0) = 187 items. (Most of these playlists are count limited.)

This was working correctly in Ampache 5.

### To reproduce

This should be pretty simple to recreate:

1. Create a smart playlist that takes any random song from the catalog and set a limit of 1 item, call it "zRandom". If you look at this playlist there's only ever 1 song.
2. Create a smart playlist with Match="any rule", and the rule is "Smart Playlist" is "zRandom".

The new smart playlist should only ever have 1 song, but instead it has all songs in the catalog.

### Expected behavior
The combination smart playlist should only include items that are in the sub-playlists.

## Environment

* Ampache version: 6.0.2
* Web server + version: Apache 2.4.55-1ubuntu2
* Server operating system: Ubuntu 23.04

**Comment by brantlk** [comment]
This started working again after a recent update.

**Comment by lachlan-00** [comment]
yup found it. we're hitting a lot of bugs this year :)
