### ISSUE TITLE
6.0.3 reports that it is 6.0.2

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3616]
My 6.0.2 instance reported there was an update to 6.0.3.   I just pulled both the latest and 6.0.3 docker images, but they both still report as 6.0.2 and the upgrade notification is still at the top of the screen.

Is there something I can look at in the code that will tell me that I really have a 6.0.3 image that just has the wrong version string somewhere?

**Comment by lachlan-00** [comment]
oh, that's odd. i checked the zips and they all seem okay

i must have built the images before something... i'm rebuilding again now

**Comment by troycarpenter** [comment]
I think this was my fault.  I have a few "patches" I pass into the docker container and I think one was the initialization routines where the database version is defined.
