### ISSUE TITLE
Ampache 6.0.3 with Nginx : Subsonic API not working with DSub

### ISSUE THREAD

**Issue by Johnson66666** [ampache/ampache#3631]
### Describe the bug
Fresh install. Everything works fine using web player.
Dsub grabs albums but nothing happend when hitting "play" button.
Looks like there is an issue with Nginx rewrite rules (I may be wrong)...
I don't want to transcode audio.

### To reproduce
1. Open DSub
2. Go to an album
3. Hit "Play" button
4. Nothing happen
5. Check ampache and nginx error logs

### Expected behavior
1. Open DSub
2. Go to an album
3. Hit "Play" button
4. Music plays
5. No ampache nor nginx error in logs

## Environment
* Ampache: 6.0.3
* Nginx: 1.25.3
* Php: 8.2-fpm
* Server operating system: Debian 12
* Client operating system: Android 13

### Client type
* SubSonic: DSub 5.5.3

### ampache.nginx.conf
Same as https://github.com/ampache/ampache/wiki/Installation#nginx

### ampache.cfg.php
```
;#<?php exit(); ?>##
;#########################################################
; General Config                                         #
;#########################################################

config_version = 68
date_timezone = "Europe/Paris"

;#########################################################
; Path Vars                                              #
;#########################################################

local_web_path = "https://ampache.mydomain.com"

;#########################################################
; Database                                               #
;#########################################################

database_hostname = "localhost"
database_port = "3306"
database_name = "myDb"
database_username = "myUser"
database_password = "myPass"

;#########################################################
; Session and Security                                   #
;#########################################################

secret_key = "mySecret"
session_length = "86400"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "86400"
session_cookiesecure = "0"
auth_methods = "mysql"
access_control = "true"
require_session = "true"
require_localnet_session = "true"

;#########################################################
; Metadata                                               #
;#########################################################

getid3_tag_order = "vorbiscomment,id3v2,id3v1,quicktime,matroska,ape,asf,avi,mpeg,riff"
metadata_order = "getID3,filename"
metadata_order_video = "filename,getID3"
deferred_ext_metadata = "true"
additional_genre_delimiters = "[/]{2}|[_/\|,;]"

;#########################################################
; Catalog                                                #
;#########################################################

catalog_file_pattern = "mp3|mpc|m4p|m4a|aac|ogg|oga|wav|aif|aiff|rm|wma|asf|flac|opus|spx|ra|ape|shn|wv"
catalog_video_pattern = "avi|mpg|mpeg|flv|m4v|mp4|webm|mkv|wmv|ogv|mov|divx|m2ts"
catalog_playlist_pattern = "m3u|m3u8|pls|asx|xspf"
catalog_prefix_pattern = ""

;#########################################################
; Program Settings                                       #
;#########################################################

allow_zip_download = "true"
allow_zip_types = "album, album_disk"
art_zip_add = "true"
use_auth = "true"
default_auth_level = "guest"
ratings = "false"
directplay = "true"
sociable = "false"
licensing = "true"
memory_cache = "true"
album_art_preferred_filename = "cover.jpg"
artist_art_preferred_filename = "cover.jpg"
artist_art_folder = "/var/www/metadata/artist"
album_art_store_disk = "true"
local_metadata_dir = "/var/www/metadata"
album_art_min_width = "30"
album_art_min_height = "30"
playlist_art = "true"
art_order = "db,tags,folder,musicbrainz,google"

;#########################################################
;      API keys                                          #
;#########################################################

lastfm_api_key = "xxxxxxxxxxxxxx"
lastfm_api_secret = ""
wanted = "false"
wanted_types = "album,official"
live_stream = "false"
podcast = "true"
refresh_limit = "60"
show_footer_statistics = "true"

;#########################################################
; Debugging                                              #
;#########################################################

debug = "true"
debug_level = "1"
log_path = "/var/log/ampache"
log_filename = "%name.%Y%m%d.log"

;#########################################################
; Encoding Settings                                      #
;#########################################################

site_charset = "UTF-8"

;#########################################################
; Public Registration settings, defaults to disabled     #
;#########################################################

allow_public_registration = "false"
cookie_disclaimer = "true"
registration_display_fields = "fullname,website"
registration_mandatory_fields = "fullname"

;#########################################################
; Transcode Settings                                     #
;#########################################################

transcode_player_customize = "false"
transcode_input = "-i %FILE%"
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_opus = "-vn -b:a %BITRATE%K -c:a libopus -compression_level 10 -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
encode_args_webm = "-b:a %BITRATE%K -f webm -c:v libvpx -preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_args_ogv = "-codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 -f ogg pipe:1"
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"
encode_srt = "-vf \"subtitles='%SRTFILE%'\""
encode_ss_frame = "-ss %TIME%"
encode_ss_duration = "-t %DURATION%"
send_full_stream = "webplayer"

;#########################################################
; Proxy Settings (optional)                              #
;#########################################################

force_ssl = "true"

;#########################################################
;   Abbreviation Filter                                  #
;#########################################################

common_abbr = "divx,xvid,dvdrip,hdtv,lol,axxo,repack,xor,pdtv,real,vtv,caph,2hd,proper,fqm,uncut,topaz,tvt,notv,fpn,fov,orenji,0tv,omicron,dsr,ws,sys,crimson,wat,hiqt,internal,brrip,boheme,vost,vostfr,fastsub,addiction,x264,LOL,720p,1080p,YIFY,evolve,fihtv,first,bokutox,bluray,tvboom,info"
```

### /var/log/ampache/ampache.20231031.log

> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:54+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:54+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:54+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:54+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:54+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:54+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:55+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:55+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:55+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400
> 
> 2023-10-31T12:12:55+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "action" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(125)
> 
> 2023-10-31T12:12:55+01:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "name" in file /var/www/ampache/src/Module/Application/Playback/PlayAction.php(126)
> 
> 2023-10-31T12:12:55+01:00 [MyUser] (Ampache\Module\Api\Subsonic_Api) -> Stream error: The requested URL returned error: 400

### /var/log/nginx/ampache.mydomain.com.access.log

> SERVER_IP - - [31/Oct/2023:12:12:54 +0100] "GET /play/ssid/72c40ecca142524859e7e40b999d1a04/type/song/oid/6541/uid/2/client/DSub/bitrate/258/player/api/name/Foo+Fighters+-+Stacked+Actors.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.006 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006541&maxBitRate=258 HTTP/1.1" status=400 bytes=5 cache=- time=0.053 referer="-" agent="DSub" forward="-"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /play/ssid/1bc8242906f18dc4205fd4d5b1961298/type/song/oid/6543/uid/2/client/DSub/bitrate/266/player/api/name/Foo+Fighters+-+Breakout.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.017 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006543&maxBitRate=266 HTTP/1.1" status=400 bytes=5 cache=- time=0.078 referer="-" agent="DSub" forward="-"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /play/ssid/b28dfb7b77fb2c369302f239789a7e58/type/song/oid/6541/uid/2/client/DSub/bitrate/258/player/api/name/Foo+Fighters+-+Stacked+Actors.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.017 referer="-" agent="DSub" forward="CLIENT_IP"       
> 
> CLIENT_IP- - [31/Oct/2023:12:12:54 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006541&maxBitRate=258 HTTP/1.1" status=400 bytes=5 cache=- time=0.073 referer="-" agent="DSub" forward="-"
> 
> SERVER_IP - - [31/Oct/2023:12:12:54 +0100] "GET /play/ssid/5117eff81c1fdbd575b044d7bda58a95/type/song/oid/6547/uid/2/client/DSub/bitrate/273/player/api/name/Foo+Fighters+-+Learn+To+Fly.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.009 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006547&maxBitRate=273 HTTP/1.1" status=400 bytes=5 cache=- time=0.061 referer="-" agent="DSub" forward="-"
> 
> SERVER_IP - - [31/Oct/2023:12:12:54 +0100] "GET /play/ssid/121224fcfdcc4aa5e3742ecc0a89ebc7/type/song/oid/6541/uid/2/client/DSub/bitrate/258/player/api/name/Foo+Fighters+-+Stacked+Actors.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.015 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:54 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006541&maxBitRate=258 HTTP/1.1" status=400 bytes=5 cache=- time=0.058 referer="-" agent="DSub" forward="-"
SERVER_IP - - [31/Oct/2023:12:12:55 +0100] "GET /play/ssid/d12cb9429dd575b85c57593dd3b072c8/type/song/oid/6542/uid/2/client/DSub/bitrate/280/player/api/name/Foo+Fighters+-+Gimme+Stitches.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.006 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:55 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006542&maxBitRate=280 HTTP/1.1" status=400 bytes=5 cache=- time=0.030 referer="-" agent="DSub" forward="-"
> 
> SERVER_IP - - [31/Oct/2023:12:12:55 +0100] "GET /play/ssid/08784ae522820a76d5b0e5b524ddc938/type/song/oid/6541/uid/2/client/DSub/bitrate/258/player/api/name/Foo+Fighters+-+Stacked+Actors.mp3 HTTP/2.0" status=400 bytes=0 cache=- time=0.017 referer="-" agent="DSub" forward="CLIENT_IP"
> 
> CLIENT_IP - - [31/Oct/2023:12:12:55 +0100] "GET /rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006541&maxBitRate=258 HTTP/1.1" status=400 bytes=5 cache=- time=0.067 referer="-" agent="DSub" forward="-"

### Manually downloading a song using web interface
* Original logged request : https://ampache.mydomain.com/rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006543&maxBitRate=266 = 400 error
* Remove &maxBitRate=266 : https://ampache.mydomain.com/rest/stream.view?u=MyUser&p=enc:xxxxxxx&v=1.2.0&c=DSub&id=300006543 = 200 OK

### ampache.cfg.php allow transcoding (I prefer to not transcode)
```
transcode_mp3 = "allowed"
encode_target = mp3
encode_player_api_target = api
```

### ampache.cfg.php allow full stream anywhere
```
send_full_stream = true
```

**Comment by SuperFola** [comment]
I think your local web path is wrong, it should be http://localhost iirc

I'll check my config once I get home, but I ran in the exact same problem when I made my install (though I use nginx proxy manager) and it was about a webpath.

**Comment by Johnson66666** [comment]
> I think your local web path is wrong, it should be http://localhost/ iirc

Thanks for your answer.
I just tried `local_web_path = "https://localhost"` and also `local_web_path = "localhost"` but it doesn't change anything.

**Comment by lachlan-00** [comment]
you need the http part of the local_webhost set for that to work.

it could be limited by the amount of parts to rewrite?

If you took off the maxbitrate and it worked that was a pair of parameters to change.

I put my current rewrite for apache into a converter and got this code. (i don't know a lot about nginx tso not sure if that change will help)

```
    location ~ "^/(.+)\.view$" {
        try_files $uri/ /rest/index.php?ssaction=$1;
    }
    location ~ "^/(.+)$" {
        try_files $uri/ /rest/index.php?ssaction=$1;
    }
    rewrite ^/fake/(.+)$ /play/$1;
```

**Comment by Johnson66666** [comment]
Hi there.

Thanks to all for your answers.

I finally found what was wrong, and that was an url rewriting issue in the Nginx config file sample [here](https://github.com/ampache/ampache/wiki/Installation#nginx).

I used `rewrite_log on` and `debug` log level on Nginx to find out what happen in terms of rewrite rules priority :

> 2023/11/10 00:24:09 [notice] 1155330#1155330: *10  "^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/name/(.*)$" matches "/play/ssid/bb81dbf11c5956ce52e9ae5868360f0a/type/song/oid/2797/uid/2/client/DSub/bitrate/240/player/api/name/Renaud+-+Marchand+De+Cailloux.mp3", client: SERVER_IP, server: ampache.mydomain.com, request: "GET /play/ssid/bb81dbf11c5956ce52e9ae5868360f0a/type/song/oid/2797/uid/2/client/DSub/bitrate/240/player/api/name/Renaud+-+Marchand+De+Cailloux.mp3 HTTP/2.0", host: "ampache.mydomain.com"
2023/11/10 00:24:09 [notice]

The 2nd rewrite rule matches the route and should not. The 4th should match to get a song play to work. This is because of the `/client/(.*)` that globally matches anything after `/client/`. So I replaced `/client/(.*)` by `/client/(\w+)` in every client rewrite rule to only match a string like `/client/Dsub/` and not every string after `/client/`.

There is also two mistakes in the config sample :
- Missing `&` in fourth rewrite rule, should be `bitrate=$6&player` instead of `bitrate=$6player`
- Missing `&` in 8th rewrite rule, should be `bitrate=$7&player` instead of `bitrate=$7player`

I won't close this ticket, as I'd like the admin to fix the Nginx sample inside documentation.
I think that reversing the order of rewrite rules could also work but would be less elegant.

```
# Current rewrite rules
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&name=$6 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&player=$6&name=$7 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&bitrate=$6player=$7&name=$8 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&transcode_to=$6&bitrate=$7&player=$8&name=$9 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&player=$7&name=$8 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&bitrate=$7player=$8&name=$9 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&transcode_to=$7&bitrate=$8&player=$9&name=$10 last;
```

```
# Fixed rewrite rules
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&name=$6 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&player=$6&name=$7 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&bitrate=$6&player=$7&name=$8 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&transcode_to=$6&bitrate=$7&player=$8&name=$9 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/noscrobble/([0-1])/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&player=$7&name=$8 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/noscrobble/([0-1])/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&bitrate=$7&player=$8&name=$9 last;
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(\w+)/noscrobble/([0-1])/transcode_to/(w+)/bitrate/([0-9]+)/player/(.*)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&transcode_to=$7&bitrate=$8&player=$9&name=$10 last;
```

**Comment by lachlan-00** [comment]
thanks for your efforts @Johnson66666 i'll update the wiki now

**Comment by lachlan-00** [comment]
updates in the wiki @ https://github.com/ampache/ampache/wiki/Installation#nginx

it might be good to make these files actual example files in the repo too so they're tracked a bit better.

**Comment by Johnson66666** [comment]
You're welcome @lachlan-00, thanks to you for maintaining this cool project.
I agree for the idea to add this wiki to the repo.
