### ISSUE TITLE
I cant upgrade, stuck with some database

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#3647]
I am using Debian testing and I am using Php 7.4, mysql  Ver 15.1 Distrib 10.6.11-MariaDB, Server version: Apache/2.4.52 (Debian)

I can't pass the database up[date screen. The list was quite long, after couple upgrade passes this is where I am and I am unable to pass this screen.

```

Ampache Update

This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is 6.1.0 with database version 6.0.0 Build: 034

The following updates need to be performed:

    Version: 6.0.0 Build: 035
    * Add `enabled` to `podcast_episode` table
    Version: 6.0.0 Build: 036
    * Update user `play_size` and catalog `size` fields to megabytes (Stop large catalogs overflowing 32bit ints)
    Version: 6.0.0 Build: 037
    * Update user server and user counts now that the scaling has changed
    Version: 6.0.0 Build: 038
    * Update `access_list` in case you have a bad `user` column
    Version: 6.0.0 Build: 039
    * Add user preference `custom_timezone`, Display dates using a different timezone to the server timezone
    Version: 6.0.0 Build: 040
    * Add `disksubtitle` to `song_data` and `album_disk` table
    Version: 6.0.0 Build: 041
    * Index `label` column on the `label_asso` table
    Version: 6.0.0 Build: 042
    * Add user preference `bookmark_latest`, Only keep the latest media bookmark


```

```
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Update) -> run_update: starting
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Update) -> run_update: checking versions
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Dba) -> Error_query MSG: ["42S21",1060,"Duplicate column name 'enabled'"]
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Dba) -> Error_query MSG: ["42S21",1060,"Duplicate column name 'enabled'"]
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Dba) -> Error_query MSG: ["42S21",1060,"Duplicate column name 'enabled'"]
2023-11-11T00:15:01-06:00 [ampache] (Ampache\Module\System\Dba) -> Error_query MSG: ["42S21",1060,"Duplicate column name 'enabled'"]


```

**Comment by choffm** [comment]
I had the same issue after the latest upgrade (running on docker with mariadb). I solved it with the following mysql commands:

```
ALTER TABLE podcast_episode DROP COLUMN enabled;
```
This solved 035, but I had to drop another few columns and rows, as 039 and 040 were also failing:
```
DELETE FROM preference WHERE name='custom_timezone';
ALTER TABLE song_data DROP COLUMN disksubtitle;
ALTER TABLE album_disk DROP COLUMN disksubtitle;
```

Not done any RCA yet.

**Comment by lachlan-00** [comment]
i'll do what you did @choffm and drop the column if it exists

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/commit/6c19cdb073bbc2dac93ef65bf6b9f4b1671b63f6

the updated file is `/src/Module/System/Update.php`

you can download the raw file here https://raw.githubusercontent.com/ampache/ampache/6c19cdb073bbc2dac93ef65bf6b9f4b1671b63f6/src/Module/System/Update.php

**Comment by gerroon** [comment]
@lachlan-00 

Thanks for the update but it is still stuck on some

![image](https://github.com/ampache/ampache/assets/8519469/487658d9-cbc3-461a-aabb-932f260efc84)

**Comment by lachlan-00** [comment]
No problem I'll hit it again in a few mins

**Comment by lachlan-00** [comment]
do you get a duplicate key on the label index? i've dropped it before creating with ab5348ec3

you can manually to that with 
```
ALTER TABLE `label` DROP KEY `label_asso_label_IDX`;
```

or the raw file here 
https://raw.githubusercontent.com/ampache/ampache/ab5348ec39dfe60fa365670ca29271afb0ae884d/src/Module/System/Update.php

**Comment by gerroon** [comment]
Thanks but I do not seem to get any change with the update issues?

![image](https://github.com/ampache/ampache/assets/8519469/debc10e5-7ffe-49a4-86c4-e171deb9be07)

**Comment by gerroon** [comment]
Thanks but I do not seem to get any change with the update issues?

![image](https://github.com/ampache/ampache/assets/8519469/4b66b4cd-fe19-4669-aac5-22e57f078916)

**Comment by gerroon** [comment]
No new update? 
![image](https://github.com/ampache/ampache/assets/8519469/e1ea23f6-593f-4066-bdeb-34c7a5ac9714)

**Comment by lachlan-00** [comment]
which update is is getting an error on?

**Comment by lachlan-00** [comment]
TYPO
 updating now

**Comment by gerroon** [comment]
I do not know much about mysql this is what I tried just

```

MariaDB [(none)]> use ampache
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [ampache]> ALTER TABLE `label` DROP KEY `label_asso_label_IDX`;
ERROR 1091 (42000): Can't DROP INDEX `label_asso_label_IDX`; check that it exists


```

**Comment by lachlan-00** [comment]
i put the column in instead of the table name, latest update is okay i think
![image](https://github.com/ampache/ampache/assets/1305249/4e7b13ee-db77-407d-9464-d1c74762cd7a)

**Comment by gerroon** [comment]
It looks like we now have couple left

![image](https://github.com/ampache/ampache/assets/8519469/7441a9ab-b39a-44e9-844d-455172430edc)

**Comment by lachlan-00** [comment]
delete before insert should fix that with 94075d865 (ignores if not existing)

**Comment by gerroon** [comment]
Thanks, I can test it if you can give me the actual link to the updated file

**Comment by lachlan-00** [comment]
here you go
https://raw.githubusercontent.com/ampache/ampache/94075d86574b7aad4215b7fe1035e6a1f718b9eb/src/Module/System/Update.php

**Comment by gerroon** [comment]
Awesome, that seemed to do the trick.

**Comment by lachlan-00** [comment]
great. i'm reworking how preferences are written in the DB and i'm going to test an upgrade myself from 3.9 before i commit but i think this will solve a lot of peoples problems.

thanks for helping me find and fix so fast

**Comment by lachlan-00** [comment]
9850592ea was tested with an Ampache 3.9.0 database and has updated all the way to 6.1.0!

Thanks again, the process is way easier for an admin to follow and much less likely to error out with less direct sql queries.
