### ISSUE TITLE
Upgrade fails at Version: 5.0.0 Build: 004 from 4.4.3 to 6.1.0

### ISSUE THREAD

**Issue by stonie08** [ampache/ampache#3653]
## Description
I'm trying to update my Ampache 4.4.3 to the latest version 6 but I'm hitting a database upgrade issue on the way. I tried with the latest 5.6.1 version and the latest 6.1.0. 

### Describe the bug
The issue occurs both via the web UI and the CLI version when upgrading the database to _update_500004.
With the 5.6.1 it will just take a long time and silently fail. With 6.1.0 I get the error via the CLI:

```
$ php -d max_execution_time=0  ./bin/cli admin:updateDatabase -e -v
Ampache version: 6.1.0
Config version: 69
Database version: 4.0.0 Build: 023

Update Now!

_update_400024
_update_500000
_update_500001
_update_500002
_update_500003
_update_500004
REPLACE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist`.`id` FROM `artist` LEFT JOIN `song` ON `song`.`artist` = `artist`.`id`;

Error
```

### To reproduce

- Use Ampache 4.4.3
- Donwnload and unzip ampache-5.6.1_all_php8.2.zip or ampache-6.1.0_all_php8.2.zip
- Run the update via the web UI or CLI `./bin/cli admin:updateDatabase -e -v`
- Wait until _update_500004 is reached

## Environment

* Ampache version: 4.4.3- release
* Web server + version: Apache/2.4.57, PHP 8.2.7 
* Server operating system: Debian Bookworm

### Client type

* Web
* Ampache

**Comment by lachlan-00** [comment]
What is the error you get when running the query manually?

```
REPLACE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist`.`id` FROM `artist` LEFT JOIN `song` ON `song`.`artist` = `artist`.`id`;
```

i would also try and `INSERT IGNORE` instead of replace

**Comment by stonie08** [comment]
Just tried it. If I run it before attempting the update (database version 4.0.0 Build: 023), or after the first partial update (database version 5.0.0 Build: 003):
```
MariaDB ampache@(none):ampache> REPLACE INTO `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist`.`id` FROM `artist` LEFT JOIN `song` ON `song`.`artist` = `artist`.`id`;
(1048, "Column 'catalog_id' cannot be null")
```

and alternatively if I run after the attempted update 
```
INSERT IGNORE `catalog_map` (`catalog_id`, `object_type`, `object_id`) SELECT `song`.`catalog`, 'artist', `artist`.`id` FROM `artist` LEFT JOIN `song` ON `song`.`artist` = `artist`.`id`;
Query OK, 0 rows affected
Time: 1.406s
```

In either case the admin:updateDatabase command continues to fail afterwards, though.

**Comment by lachlan-00** [comment]
ahhh you've got some songs without a catalog!

that's good to know, there must be a point in the versions that added catalog that you don't have yet. thanks for that i'll fix it up asap now!

**Comment by lachlan-00** [comment]
I've checked out V 4 and the catalog is in the SQL so it should be filled in the database, it might be that your files haven't been verified or updated since they were added but i can't confirm.

i'll work on a query to fill this data and add to the update

**Comment by lachlan-00** [comment]
i've updated the update file with 4aad4d92f and ebe887f82 (raw file https://raw.githubusercontent.com/ampache/ampache/ebe887f82d56011fea14845cd62ac19d45e83fce/src/Module/System/Update.php)

The query should be filling the data and checking before trying to load up. must not have noticed this before we made the update process stricter

**Comment by stonie08** [comment]
I used the 6.1.0 release as a base and replaced the Update.php file with the file you provided and the update ran past the _update_500004 step. I'd say it is fixed now.
Thank you very much!

**Comment by lachlan-00** [comment]
that's awesome. i want upgrades to work for anyone on any version so you've helped a lot.
