### ISSUE TITLE
Call to undefined method when changing shared album settings

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3676]
When trying to change the 'allow stream' or 'allow download' checkboxes in the edit box for shared albums in the web interface, the changes fail and the following error is shown in the logs:

`(/var/www/html/ampache/src/Module/Api/Edit/EditObjectAction.php:137) -> Call to undefined method Ampache\Repository\Model\Share::format()`

**Comment by lachlan-00** [comment]
a share isn't a library item so doesn't implement format. i've set checks for that now. format will eventually go away for the individual property calls but that will do for now

1f6850624 and ddd05fde8

**Comment by rsinfotech** [comment]
Thanks @lachlan-00, this has cleared the 'undefined method' error for me but the changes now fail with the following 'too few arguments' error:

`(/var/www/html/ampache/src/Repository/Model/Share.php:333) -> Too few arguments to function Ampache\Repository\Model\Share::update(), 1 passed in /var/www/html/ampache/src/Module/Api/Edit/EditObjectAction.php on line 140 and exactly 2 expected`

**Comment by usox** [comment]
I think my PR should cover the missing-argument issue

**Comment by rsinfotech** [comment]
Thanks both, this is now working as expected with no errors, great work, much appreciated.
