### ISSUE TITLE
Bug: webplayer can't play music on unauthenticated users

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3732]
## Description

When an user is not authenticated, the web player can't play music.

I think there may be a parameters I overlooked, but I didn't found it.

### Describe the bug
When not authenticated, we click on the play button, nothing happen.

Log say : 
` [-1] (Ampache\Module\Application\Playback\PlayAction) -> No user specified {Ampache\Repository\Model\User Object`

## Patch
To allow music to play, I made a patch. I won't submit a PR because I think you want a better patch or a parameters.
 
```diff
diff --git a/src/Module/Application/Playback/PlayAction.php b/src/Module/Application/Playback/PlayAction.php
index 1808580f4..d26a79caf 100644
--- a/src/Module/Application/Playback/PlayAction.php
+++ b/src/Module/Application/Playback/PlayAction.php
@@ -384,12 +384,14 @@ final class PlayAction implements ApplicationActionInterface
             $user = new User($share->user);
         }
 
+       # can't play music if not logged in
-        if ((!$user instanceof User || $user->id < 1) && (!$share_id && !$secret)) {
+        if ((!$user instanceof User ) && (!$share_id && !$secret)) {
             $this->logger->error(
                 'No user specified {' . print_r($user, true) . '}',
                 [LegacyLogger::CONTEXT_TYPE => __CLASS__]
             );


```

**Comment by lachlan-00** [comment]
i've added missing properties for the -1 user and then checking isNew status instead with a77c7dfe6 and 711951c93

**Comment by fufroma** [comment]
LGTM, thanks!
