### ISSUE TITLE
Please generate 6.2.0 Docker Images

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3745]
Looking forward to the new "Ampache Wrapped" feature, but I need a 6.2.0 docker image ;)

**Comment by troycarpenter** [comment]
Also created https://github.com/ampache/ampache-docker/issues/113 in the ampache-docker project.

**Comment by lachlan-00** [comment]
ha, sorry, i think i just built develop. i'm building that now and just testing 6.2.1 as we speak

**Comment by troycarpenter** [comment]
I'll take whatever you can give.

**Comment by lachlan-00** [comment]
built now!

**Comment by troycarpenter** [comment]
Thanks!  Already pulled and running.

**Comment by lachlan-00** [comment]
new release next week i think, i'll make sure my script does all the images instead of just develop again

**Comment by lachlan-00** [comment]
6.2.1 is out and built as well
