### ISSUE TITLE
Cannot upgrade from 5.6.0 to 6.2.0

### ISSUE THREAD

**Issue by Witos** [ampache/ampache#3748]
Steps to reproduce:
1. Download 6.2.0 (8.1 php)
2. Copy configuration file
3. Run `php bin/cli admin:updateDatabase -e`

and I get:
`
Ampache version: 6.2.0
Config version: 69
Database version: 6.0.0 Build: 004

Update Now!

_update_600005
Error Typed property Ampache\Repository\Model\Album::$version must not be accessed before initialization
(thrown in /mnt/disk/srv/http/ampache-6.2.0/src/Repository/Model/Album.php:526)

Stack Trace:

  0) Ampache\Repository\Model\Album->get_fullname()
     at /mnt/disk/srv/http/ampache-6.2.0/src/Repository/Model/Album.php:157
  1) Ampache\Repository\Model\Album->__construct()
     at /mnt/disk/srv/http/ampache-6.2.0/src/Module/System/Update.php:4509
  2) Ampache\Module\System\Update::_update_600005()  3) call_user_func()
     at /mnt/disk/srv/http/ampache-6.2.0/src/Module/System/Update.php:1002
  4) Ampache\Module\System\Update::run_update()
     at /mnt/disk/srv/http/ampache-6.2.0/src/Module/Cli/AdminUpdateDatabaseCommand.php:103
  5) Ampache\Module\Cli\AdminUpdateDatabaseCommand->execute()
     at /mnt/disk/srv/http/ampache-6.2.0/vendor/adhocore/cli/src/Application.php:366
  6) Ahc\Cli\Application->doAction()
     at /mnt/disk/srv/http/ampache-6.2.0/vendor/adhocore/cli/src/Application.php:280
  7) Ahc\Cli\Application->handle()
     at /mnt/disk/srv/http/ampache-6.2.0/bin/cli:82
`

### Expected behavior
Should update without problems

## Environment

* Ampache version: 6.2.0
* Web server + version: -
* Server operating system: arch
* Client operating system: -

### Client type

* Web
* Ampache
* SubSonic
* DAAP
* UPnP
* WebDAV

**Comment by elliotn** [comment]
I tried from 5.6.4 and gave up on the upgrade. I created a 2nd instance of ampache, db, etc. for 6.2 and getting much further. Although, I'm having a catalog issue that seems to be part of 6.2

**Comment by tofbouf** [comment]
Exactly same error while upgrading from 5.6.1 to 6.2.0 (php 8.2), on my server.

**Comment by lachlan-00** [comment]
that's from all the typing. i'll fix them up now. and we'll look at 6.2.1 this week to clean it all up

**Comment by lachlan-00** [comment]
i see that the _update_600027 will be affecting that as well as the album changed from subtitle to version. i'll have to put some mitigation in there for having either column

**Comment by lachlan-00** [comment]
51824aee1 will fix that. anyone on an older version with subtitle will load the full name correctly now and the property will be set.

these are the kind of bugs static typing helps me find.

**Comment by lachlan-00** [comment]
also just simplified it with 54e28aabc which will bypass this and allow updates. which is probably better way to do it so i'll revert 51824ae

**Comment by lachlan-00** [comment]
e3c6913a6 takes out the get_fullname on construct. that should fix it

**Comment by lachlan-00** [comment]
the update should work now with that, i didn't realise i'd left another on in the construct. that's an old workaround so not needed

**Comment by speeskeek** [comment]
thank you - I pulled the git (since the tarballs aren't nighlies) - but its giving other errors. maybe 'cuz of php8.3 vs 8.2 ?

**Comment by speeskeek** [comment]
not there yret ?



bart@Z800:/var/www/ampache/bin$ sudo -u www-data php cli admin:updateDatabase -e
Ampache version: 6.2.0
Config version: 69
Database version: 6.0.0 Build: 004

Nu bijwerken!                                                                                                                   

_update_600005
Error Typed property Ampache\Repository\Model\Album::$version must not be accessed before initialization
(thrown in /var/www/ampache/src/Repository/Model/Album.php:526)

Stack Trace:

  0) Ampache\Repository\Model\Album->get_fullname()
     at /var/www/ampache/src/Repository/Model/Album.php:157
  1) Ampache\Repository\Model\Album->__construct()
     at /var/www/ampache/src/Module/System/Update.php:4509
  2) Ampache\Module\System\Update::_update_600005()  3) call_user_func()
     at /var/www/ampache/src/Module/System/Update.php:1002
  4) Ampache\Module\System\Update::run_update()
     at /var/www/ampache/src/Module/Cli/AdminUpdateDatabaseCommand.php:103
  5) Ampache\Module\Cli\AdminUpdateDatabaseCommand->execute()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:366
  6) Ahc\Cli\Application->doAction()
     at /var/www/ampache/vendor/adhocore/cli/src/Application.php:280
  7) Ahc\Cli\Application->handle()
     at /var/www/ampache/bin/cli:82

**Comment by lachlan-00** [comment]
you might still have the older album code
```
Ampache\Repository\Model\Album->get_fullname()
at /var/www/ampache/src/Repository/Model/Album.php:157
```
that's been taken out now
![image](https://github.com/ampache/ampache/assets/1305249/34f529c7-83dc-429b-ad1b-a2235a9b6d0b)

**Comment by speeskeek** [comment]
works!

**Comment by lachlan-00** [comment]
awesome. i was waiting for this to resolve. 6.2.1 incoming after testing today then

**Comment by lachlan-00** [comment]
6.2.1 is out now with those fixes included
https://github.com/ampache/ampache/releases/tag/6.2.1

**Comment by fufroma** [comment]
@Witos can you close this issue?

**Comment by Witos** [comment]
Yes, thank you!
