### ISSUE TITLE
Type issues megathread

### ISSUE THREAD

**Issue by mitchray** [ampache/ampache#3765]
For any issues relating to the recent improvements to typing, squash those bugs!

"Creation of dynamic property"...

- [x] https://github.com/ampache/ampache/commit/22edc6a Creation of dynamic property Ampache\Repository\Model\Metadata\Model\Metadata::$object_id is deprecated in file C:\git-projects\ampache-preview\src\Module\System\Dba.php(290)

**Comment by fufroma** [comment]
There are many "dynamic property" error in the captcha section: 
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$prev is deprecated in file src/Module/Util/Captcha/easy_captcha.php(349)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha_graphic_image_waved::$img is deprecated in file src/Module/Util/Captcha/easy_captcha_graphic_image_waved.php(43)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha_dxy_wave::$dist_x is deprecated in file src/Module/Util/Captcha/easy_captcha_dxy_wave.php(43)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha_dxy_wave::$dist_y is deprecated in file src/Module/Util/Captcha/easy_captcha_dxy_wave.php(44)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha_dxy_wave::$slow_x is deprecated in file src/Module/Util/Captcha/easy_captcha_dxy_wave.php(45)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha_dxy_wave::$slow_y is deprecated in file src/Module/Util/Captcha/easy_captcha_dxy_wave.php(46)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(83)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(275)
- [ ]        (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(277)
- [ ]      (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(129)
- [ ]      (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(321)
- [ ]      (log.lib) -> [Error] Creation of dynamic property Ampache\Module\Util\Captcha\easy_captcha::$created$ is deprecated in file src/Module/Util/Captcha/easy_captcha.php(323)

And you can find other "must not be accessed before initialization" : 
- [ ]   (src/Repository/Model/playlist_object.php:75) -> Typed property Ampache\Repository\Model\playlist_object::$name must not be accessed before initialization
- [ ]   (src/Repository/Model/User.php:921) -> Typed property Ampache\Repository\Model\User::$last_seen must not be accessed before initialization
- [ ]   (public/templates/show_artist.inc.php:76) -> Typed property Ampache\Repository\Model\Artist::$mbid must not be accessed before initialization
- [ ]   (src/Module/Playback/Stream_Playlist.php:300) -> Typed property Ampache\Repository\Model\Song::$title must not be accessed before initialization

**Comment by lachlan-00** [comment]
305591454 will get Metadata::$object_id. the databse field isn't using objectId not sure how long that's been a problem

**Comment by lachlan-00** [comment]
@usox might be needed for the created$ property in `src/Module/Util/Captcha/easy_captcha.php` is that a typo?
![image](https://github.com/ampache/ampache/assets/1305249/b4f37a0b-4989-476b-8143-529504da0a68)

**Comment by lachlan-00** [comment]
added captcha properties with f832c2b53

**Comment by lachlan-00** [comment]
@fufroma for the must not be accessed before initialization items can you add the second line in the stack trace?, that will uaually tell me where the error is coming from.
These bugs are when the code thinks the object exists but fails because it doesn't exist.

I'll have a look for these now and see if i can find them but the error in https://github.com/ampache/ampache/issues/3766#issuecomment-1892974878 makes it very obvious.

```
Stack trace:
#0 /var/www/ampache/src/Repository/Model/Song.php(1712): Ampache\Repository\Model\Song->get_artist_fullname()
https://github.com/ampache/ampache/issues/1 /var/www/ampache/public/templates/show_recently_played.inc.php(129): Ampache\Repository\Model\Song->get_f_link()
```

**Comment by lachlan-00** [comment]
set playlist and user isnew checks with cb65c6fff and 7d2955794

**Comment by fufroma** [comment]
> @fufroma for the must not be accessed before initialization items can you add the second line in the stack trace?, that will uaually tell me where the error is coming from. These bugs are when the code thinks the object exists but fails because it doesn't exist.

Not a lot of informations: 
```
2024-01-17T00:31:47+00:00 [-1] (Ampache\Module\Util\ZipHandler) -> Ths file with the path REDACTED/ wasn't found.
2024-01-17T00:36:04+00:00 [-1] (src/Repository/Model/User.php:921) -> Typed property Ampache\Repository\Model\User::$last_seen must not be accessed before initialization
2024-01-17T00:36:51+00:00 [-1] (Ampache\Module\Util\ZipHandler) -> Ths file with the path edito REDACTED/ wasn't found.

2024-01-17T04:53:38+00:00 [-1] (Ampache\Module\Util\ZipHandler) -> Ths file with the path REDACTED/ wasn't found.
2024-01-17T04:53:39+00:00 [-1] (src/Module/Playback/Stream_Playlist.php:300) -> Typed property Ampache\Repository\Model\Song::$title must not be accessed before initialization
2024-01-17T04:53:46+00:00 [-1] (Ampache\Module\Util\ZipHandler) -> Ths file with the path abused REDACTED/ wasn't found.

```
Do you want for the others too? They have the same level of informations

**Comment by usox** [comment]
> @usox might be needed for the created$ property in `src/Module/Util/Captcha/easy_captcha.php` is that a typo?

I have no idea - this has been there since the initial commit 2008. It gets even worse as the catpcha class uses phps serialization features and creates properties on the fly (in theory, those properties should already be defined).

From my pov, 'created$' can be removed safely.

**Comment by usox** [comment]
> [3055914](https://github.com/ampache/ampache/commit/30559145431183e24f91129a6fa0e8af6af7f12e) will get Metadata::$object_id. the databse field isn't using objectId not sure how long that's been a problem

I've been planning to throw a stick of dynamite in there for a while... :bomb:

**Comment by lachlan-00** [comment]
that's good @fufroma  it tells me it's in the zip handler so i can find that reference

**Comment by fufroma** [comment]
> that's good @fufroma it tells me it's in the zip handler so i can find that reference

The timestamp look far apart

**Comment by lachlan-00** [comment]
created$ is removed with ac8fa45ca

**Comment by lachlan-00** [comment]
song title property with 6bfe8fe5d

**Comment by lachlan-00** [comment]
these three are a bit more vague but there are a few changes in for that

this one is the format function. so i've gone through usages and added isNew checks
` (src/Repository/Model/playlist_object.php:75) -> Typed property Ampache\Repository\Model\playlist_object::$name must not be accessed before initialization`

this error is also in the format and there aren't as many
`(src/Repository/Model/User.php:921) -> Typed property Ampache\Repository\Model\User::$last_seen must not be accessed before initialization`

for those two there are a few commits that should help cb65c6fff 7d2955794 29cadc844 29cadc844 but i don't know for sure if thats all of them.

for this one it seems like there's a valid artist but the db field hasn't loaded for them? i haven't really seen why but i did set empty with 6c2011093 to see if that covers it

`(public/templates/show_artist.inc.php:76) -> Typed property Ampache\Repository\Model\Artist::$mbid must not be accessed before initialization`

**Comment by lachlan-00** [comment]
one for you @usox

```
[Tue Mar 12 01:19:36.205713 2024] [php7:error] [pid 16] [client 192.168.1.9:42544] PHP Fatal error:  Cannot make static method Ampache\\Repository\\Model\\Catalog::getMetadataManager() non static in class Ampache\\Module\\Catalog\\Catalog_local in /var/www/html/src/Module/Catalog/Catalog_local.php on line 1391
```

that will blocks creating a new catalog for me with the api

![image](https://github.com/ampache/ampache/assets/1305249/fe88cf6d-f576-46d4-96ca-3fa6002cb48e)

**Comment by lachlan-00** [comment]
3a1c57ec8 probably okay with this

**Comment by usox** [comment]
> one for you @usox
> ...

Oh I hate this static methods...

**Comment by lachlan-00** [comment]
it's odd that it doesn't raise the error on any other version of php. i'll revert it from patch7 as well.

**Comment by fufroma** [comment]
No more error here, LGTM.

IMHO we can close this issue

**Comment by lachlan-00** [comment]
I do a grep on all my server logs most days and haven't had a type error for a long time now either.

One more step forward!
