### ISSUE TITLE
Ampache 6.2.1 can't play music with webplayer

### ISSUE THREAD

**Issue by SuperFola** [ampache/ampache#3766]
### Describe the bug
Can not play any song or playlist. No error in the console (nothing about audio context not being created either), all requests return 3xx or 2xx in the network tab.

However it works when using the subsonic API, I'm currently using FlSub as client for this.

I have tried logging out and back in, clearing caches, deleting the container and recreating it. I think it happened after Ampache told me my config was out of date and it updated it when I clicked on a link? Unsure about it because I still see the "ampche config outdated" message when pages are being refreshed.

Important to note that it worked right before I imported a new set of audio files (I had to rename the files and update their metadata with ffmpeg, then cleaned the catalog, updated it, updated file tags)

### To reproduce

I honestly don't know

### Expected behavior
Being able to play music in the browser

## Environment

* Ampache version: 6.2.1
* Web server + version: apache 2 (bundled in the official ampache docker image)
* Server operating system: debian 11
* Client operating system: macos 14

### Client type

* Web (through safari, chrome)

## Settings

```diff
diff ampache.cfg.php ampache.cfg.php.dist
64c64
< local_web_path = "http://localhost"
---
> ;local_web_path = "http://localhost/ampache"
73c73
< database_hostname = "mysql"
---
> database_hostname = localhost
77c77
< database_port = 3306
---
> ;database_port = 3306
81c81
< database_name = "ampache"
---
> database_name = ampache
85c85
< database_username = "root"
---
> database_username = username
91c91
< database_password = "***"
---
> database_password = password
116c116
< secret_key = "***"
---
> secret_key = "abcdefghijklmnoprqstuvwyz0123456"
139c139
< session_name = "ampache"
---
> session_name = ampache
264c264
< additional_genre_delimiters = "[/]{2}|[/\\|,;]"
---
> additional_genre_delimiters = "[/]{2}|[/\\\\|,;]"
514c514
< licensing = "false"
---
> ;licensing = "true"
719c719
< wanted = "false"
---
> ;wanted = "true"
746c746
< channel = "false"
---
> ;channel = "true"
996c996
< allow_public_registration = "false"
---
> ;allow_public_registration = "true"
1035c1035
< cookie_disclaimer = "false"
---
> ;cookie_disclaimer = "true"
1353d1352
<
```

## Logs

```
ampache          | 2024-01-14T13:59:06.030438593Z Please remember to change the above password as soon as possible!
ampache          | 2024-01-14T13:59:06.030448008Z MySQL user 'root' has no password but only allows local connections
ampache          | 2024-01-14T13:59:06.030457322Z ========================================================================
ampache          | 2024-01-14T13:59:07.321053793Z 2024-01-14 13:59:07,320 INFO Set uid to user 0 succeeded
ampache          | 2024-01-14T13:59:07.323832374Z 2024-01-14 13:59:07,323 INFO supervisord started with pid 1
ampache          | 2024-01-14T13:59:08.326736572Z 2024-01-14 13:59:08,326 INFO spawned: 'apache2' with pid 196
ampache          | 2024-01-14T13:59:08.328740652Z 2024-01-14 13:59:08,328 INFO spawned: 'cron' with pid 197
ampache          | 2024-01-14T13:59:08.330697116Z 2024-01-14 13:59:08,330 INFO spawned: 'inotifywait' with pid 198
ampache          | 2024-01-14T13:59:08.333030504Z 2024-01-14 13:59:08,332 INFO spawned: 'mysql' with pid 199
ampache          | 2024-01-14T13:59:09.416426712Z 2024-01-14 13:59:09,416 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T13:59:09.416537499Z 2024-01-14 13:59:09,416 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T13:59:09.416590014Z 2024-01-14 13:59:09,416 INFO success: inotifywait entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T13:59:09.416772842Z 2024-01-14 13:59:09,416 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by SuperFola** [comment]
I removed the local_web_path overload, restart ampache, set it again, restarted ampache, then apache (inside the ampache container) failed with the following logs:
```
ampache          | 2024-01-14T14:22:25.414992293Z => Using an existing volume of MySQL
ampache          | 2024-01-14T14:22:25.659195945Z 2024-01-14 14:22:25,658 INFO Set uid to user 0 succeeded
ampache          | 2024-01-14T14:22:25.662213663Z 2024-01-14 14:22:25,661 INFO supervisord started with pid 1
ampache          | 2024-01-14T14:22:26.665044478Z 2024-01-14 14:22:26,664 INFO spawned: 'apache2' with pid 7
ampache          | 2024-01-14T14:22:26.666973986Z 2024-01-14 14:22:26,666 INFO spawned: 'cron' with pid 8
ampache          | 2024-01-14T14:22:26.669076794Z 2024-01-14 14:22:26,668 INFO spawned: 'inotifywait' with pid 9
ampache          | 2024-01-14T14:22:26.671700886Z 2024-01-14 14:22:26,671 INFO spawned: 'mysql' with pid 10
ampache          | 2024-01-14T14:22:26.713630455Z 2024-01-14 14:22:26,713 WARN exited: apache2 (exit status 0; not expected)
ampache          | 2024-01-14T14:22:27.748165505Z 2024-01-14 14:22:27,747 INFO spawned: 'apache2' with pid 124
ampache          | 2024-01-14T14:22:27.748599999Z 2024-01-14 14:22:27,748 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T14:22:27.748694937Z 2024-01-14 14:22:27,748 INFO success: inotifywait entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T14:22:27.748825270Z 2024-01-14 14:22:27,748 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache          | 2024-01-14T14:22:27.802204240Z 2024-01-14 14:22:27,801 WARN exited: apache2 (exit status 0; not expected)
ampache          | 2024-01-14T14:22:29.807624558Z 2024-01-14 14:22:29,807 INFO spawned: 'apache2' with pid 127
ampache          | 2024-01-14T14:22:29.862378877Z 2024-01-14 14:22:29,862 WARN exited: apache2 (exit status 0; not expected)
ampache          | 2024-01-14T14:22:32.869276967Z 2024-01-14 14:22:32,868 INFO spawned: 'apache2' with pid 130
ampache          | 2024-01-14T14:22:32.925894175Z 2024-01-14 14:22:32,925 WARN exited: apache2 (exit status 0; not expected)
ampache          | 2024-01-14T14:22:33.927573534Z 2024-01-14 14:22:33,927 INFO gave up: apache2 entered FATAL state, too many start retries too quickly
```
so I stopped the container, waited a few seconds, and started it again. It now works again but I don't understand why nor what happened.

**Comment by Verbocutane** [comment]
I have the same problem (works with a subsonic client but not from the web browser).  No error seen in the console browser (all API calls show status 200).  This is the log error I get when it happens :

_2024/01/15 21:02:40 [error] 1176#1176: *774 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Typed property Ampache\Repository\Model\Song::$artist must not be accessed before initialization in /var/www/ampache/src/Repository/Model/Song.php:899
Stack trace:
#0 /var/www/ampache/src/Repository/Model/Song.php(1712): Ampache\Repository\Model\Song->get_artist_fullname()
#1 /var/www/ampache/public/templates/show_recently_played.inc.php(129): Ampache\Repository\Model\Song->get_f_link()
#2 /var/www/ampache/src/Application/Api/Ajax/Handler/IndexAjaxHandler.php(354): require('...')
#3 /var/www/ampache/src/Application/Api/Ajax/AjaxApplication.php(91): Ampache\Application\Api\Ajax\Handler\IndexAjaxHandler->handle()
#4 /var/www/ampache/public/server/ajax.server.php(35): Ampache\Application\Api\Ajax\AjaxApplication->run()
#5 {main}
  thrown in /var/www/ampache/src/Repository/Model/Song.php on line 899" while reading response header from upstream, client: 173.246.14.6, server: my_server, request: "POST /server/ajax.server.php?page=index&action=refresh_index HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "my_server"_

**Comment by lachlan-00** [comment]
okay that's in the template show_recently_played. easy to find

**Comment by lachlan-00** [comment]
a3fd71fd6 should fix that.

**Comment by Verbocutane** [comment]
After running a clean and garbage collect on my catalogs, the problem was fixed.
