### ISSUE TITLE
Trouble with getting Last.fm set up.

### ISSUE THREAD

**Issue by CatgirlMissRin** [ampache/ampache#3771]
I'm on 6.2.1 and am trying to enable Last.FM scrobbling and I just cant seem to connect them. I have created a last.fm API account, and have put the keys in the proper place in ampache.cfg.php, yet I'm still faced with this on the plugin screen where I go to enable last.fm which is where I just am completely unable to get last.fm to work.
![image](https://github.com/ampache/ampache/assets/27151280/866edcb5-a30d-4e00-a413-f3c4a3374d2b)

**Comment by lachlan-00** [comment]
there should be a button to open last.fm to generate a token. let me check my site

**Comment by lachlan-00** [comment]
this is what you should see. it's meant to open a new url and the generated request fills the challenge (which should be hidden).
![image](https://github.com/ampache/ampache/assets/1305249/23f52dd7-7917-443b-93c8-8a3e31e080e7)

It's possible you've got old preferences that haven't updated, is it an old site?

**Comment by lachlan-00** [comment]
you can disable and reanable the plugin to recreate the preferences. seems like it's missing something

**Comment by CatgirlMissRin** [comment]
So I did what you said and went and disabled and reenabled the plugin, I got that option and allowed it access to my account but it still isn't scrobbling anything.

**Comment by lachlan-00** [comment]
i don't think it's granting the generated code. i'm just checking that now

**Comment by lachlan-00** [comment]
found it. the grant action was not loading because the plugin hadn't granted itself

7a3d42fb4

This will fix it up for last and librefm plugins.

**Comment by lachlan-00** [comment]
you've helped me find 2 really annoying issues that not a lot of people would notice. thanks!

**Comment by CatgirlMissRin** [comment]
That worked! I didn't exactly know how to update so I just changed the code in my own GrantAction.php to what you changed the github hosted one too.
