### ISSUE TITLE
SQL Error - Search - "does not sound like"

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3775]
- Ampache 6.2.1
- Debian bookworm up-to-date
- MariaDB 10.11.4

In the search form, if I search for something with "sounds like", everything's fine.

If I search the same thing with "does not sounds like", no result and we have a SQL error:
```
(Ampache\Module\System\Dba) -> Error_query SQL: SELECT DISTINCT(`song`.`id`), `song`.`file` FROM `song`  WHERE `song`.`title` NOT SOUNDS LIKE ? ORDER BY `song`.`file` ["ani"]
(Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SOUNDS LIKE 'ani' ORDER BY `song`.`file`' at line 1
```

The two SQL query:
```
SELECT DISTINCT(`song`.`id`), `song`.`file` FROM `song`  WHERE `song`.`composer`  SOUNDS  LIKE 'ani' ORDER BY `song`.`file` ;
SELECT DISTINCT(`song`.`id`), `song`.`file` FROM `song`  WHERE `song`.`composer`  NOT SOUNDS  LIKE 'ani' ORDER BY `song`.`file` ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SOUNDS  LIKE 'ani' ORDER BY `song`.`file`' at line 1
```

Look like "NOT SOUNDS LIKE" is not a valid query with MariaDB, or if it need some plugins we miss to check them.

Look like the demo website got the same issue.

**Comment by lachlan-00** [comment]
i'll convert them to not in i can't see a not sounds like

**Comment by lachlan-00** [comment]
actually has that ever worked? i looked at 3.9.0 and it's just being used as an operator.

probably needs a larger change to fake create the option. there are 30 search terms where i'll need to make it

**Comment by fufroma** [comment]
I'm sure you like my new year present ;)

**Comment by fufroma** [comment]
Maybe we could "just" remove it until we make it work?

**Comment by lachlan-00** [comment]
i'm about to do some work in https://github.com/ampache/ampache/pull/3880 so i'll be able to do it there.

**Comment by fufroma** [comment]
I think #3880 didn't address the issue

**Comment by lachlan-00** [comment]
i've added the no into a wrapped NOT here b682542e0

**Comment by lachlan-00** [comment]
there are still more to go though. i've got to go through the docs to see which rules have the same operator

**Comment by fufroma** [comment]
\o/
are you planning a to release a 6.3.1? just to know if I need to backport all those patch to my production or if there will be a release in a quite soon

**Comment by lachlan-00** [comment]
i usually try and do one within the first two weeks. after a major like this.

**Comment by fufroma** [comment]
forgot to close it, it work fine
