### ISSUE TITLE
MyISAM may be deprecated

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3776]
Hi,

MyISAM look like it's deprecated : https://en.wikipedia.org/wiki/Comparison_of_MySQL_database_engines say it's no longer "Under active development"

Ampache 6.2.1 still have a few MyISAM table : 
```bash
# grep 'ENGINE=MyISAM' ./resources/sql/ampache.sql|wc -l
4
```

The list:
- [ ] album_disk
- [ ] album_map
- [ ] artist_map
- [ ] tmp_browse

Maybe we should migrate to something else?

BR,

**Comment by usox** [comment]
MyIsam is no longer actively developed by Mysql (Orcale), iirc MariaDb itself has an extended version of MyIsam (called Aria).

But I would also be in favor of switching all tables to InnoDb. Firstly, there should no longer be any performance disadvantages (compared to MyIsam) and secondly, we can finally use transactions.

**Comment by illuusio** [comment]
> But I would also be in favor of switching all tables to InnoDb. Firstly, there should no longer be any performance disadvantages (compared to MyIsam) and secondly, we can finally use transactions.

What kind of performance disadvantages there have been with InnoDB? Older InnoDB could have them but in current form it's robust and one can compare it to MyIsam or Aria performance.

**Comment by usox** [comment]
> What kind of performance disadvantages there have been with InnoDB? Older InnoDB could have them but in current form it's robust and one can compare it to MyIsam or Aria performance.

Yeah, I have been talking about older...way older...versions of InnoDb - about 15-20 years or so. I don't remember the exact details :laughing:

**Comment by illuusio** [comment]
Ok nowadays it very different beast and it would be nice to upgrade aging MyISAM to better alternative InnoDB. What would it require?

**Comment by usox** [comment]
> What would it require?

Well, I don't know whether @fufroma's list is complete or not - it may need to be expanded first.
Then it's probably best to first check whether the tables can be safely migrated to InnoDB (which I assume is the case).
Then one should simply migrate them piece by piece via an update script, ideally only one table per Ampache update (if there are really only 4) - just to be on the safe side.

But @lachlan-00 should also give his opinion on this.

Translated with DeepL.com (free version)

**Comment by illuusio** [comment]
If we are talking about `ampache.sql`. There is only 4 tables as @fufroma  noted.
 * tmp_browse
 * album_disk
 * album_map
 * artist_map

As far as I looked them they does not contain any special stuff why they should be MyISAM. With InnoDB they would be ACID and fault tolerant. I don't know if it's real problem but there is lots of mixed old `utf8mb3_unicode_ci` and  then `utf8mb4_unicode_ci` (which they should be now to get correct UTF-8 support).

**Comment by fufroma** [comment]
@lachlan-00 should it be a target for the 7.0 release?

**Comment by lachlan-00** [comment]
It is a big enough change, i'll just need to update migrations and test/dogfood myself for a while

There are a few hardcoded areas where it's set outside of the sql file as well so all those would need to be removed and all the ternary choices / choice workarounds.

on a new install there isn't a lot to convert but my home server has way more so all the tables will need checks and conversion (probably cli)

My server is probably a pretty common state so i'll update the CLI database commands to do these sanity checks

I'm assuming that for mysql and mariadb support the only option is InnoDB?

Does mysql support Aria?

If map tables and heavy read tables only option is innodb for mysql is the option of Aria for mariadb a good idea?

**Comment by illuusio** [comment]
Aria is only in MariaDB so migration to  InnoDB would be better choice.

**Comment by lachlan-00** [comment]
okay i don't want them to be incompatible with each other or deal with that as a code issue to workaround it

**Comment by illuusio** [comment]
InnoDB is robust beast nowadays in MariaDB and MySQL. Little bit more memory and but full ACID support also transactions.

**Comment by lachlan-00** [comment]
tmp_browse is the only one that didn't auto convert.

it has 2 primary keys for some reason so it probably requires a drop and recreate
```
SQL Error [1075] [42000]: (conn=87495) Incorrect table definition; there can be only one auto column and it must be defined as a key
```

That's probably the only issue to fix before anyone could convert

**Comment by illuusio** [comment]
Couldn't you just alter them before convert but as it's tmp table is it worth it?

**Comment by lachlan-00** [comment]
sessions get cleared on a db update so that table is useless soon as you update. it's the easiest way to work around any weirdness too.

Other than that i don't see much else stopping it. just have to do it to my own server first and break it where possible

**Comment by illuusio** [comment]
Is there something that can be tested?

**Comment by stebe** [comment]
I've been running with InnoDB except for tmp_browse which is still MyISAM for a couple of years without any issues or errors in the logs. I couldn't convert tmp_browse for the same reason @lachlan-00.

**Comment by lachlan-00** [comment]
Mentioned in the pull thread but I'm keeping this optional for 6.

any existing db can use the cli to force update the table collation now that tmp_browse is recreated. For v 7 I'll make it default
