### ISSUE TITLE
Videos of the moment all show unknown thumbnail but thumbnails show during browse

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#378]
As you can see from the screenshot, the videos of the moment are all showing the unknown thumbnail. 

![screenshot 2014-08-08 10 31 16](https://cloud.githubusercontent.com/assets/4076671/3857913/b59d174c-1f08-11e4-8c58-899296a50117.png)

But if I browse the videos, the thumbnails do show up. Is there something I'm not doing correctly for this inconsistency to happen?
![screenshot 2014-08-08 10 31 59](https://cloud.githubusercontent.com/assets/4076671/3857929/e1593884-1f08-11e4-8473-75dc3cbf8e41.png)

**Comment by Afterster** [comment]
There is a way to disable video support since few months now and the enhancement flag on this issue was for this point. Others things are just part of the discussion and will not involve changes.
