### ISSUE TITLE
Transcoding not finishing process

### ISSUE THREAD

**Issue by nan4k7** [ampache/ampache#381]
Hi, I'm experiencing some problems while using transcoding.

Everything works great and transcoding works but if I skip a track which has started transcode and didn't finish yet and skip track the transcode process is never killed (I can see it if I make a ps on the server)

Is this a bug or something not working correctly? If I wait till the song finishes transcoding everything goes well, If I skip it before the transcode ends the process stays there forever (I'm using lame to transcode).

**Comment by FoxBuru** [comment]
I'm having a similar trouble. 

In my case, i'm playing a DTS-WAV file. I've chosen to transcode all wav and flac to ogg (so i can use it on MPD-based systems). The first two minutes appears to work, then at 2:30 approx, PHP doesn't receives or sends stream anymore from ffmpeg. The ffmpeg process appears to still be running in background after that. 

I'll try to get a more detailed traceing, hoping that helps.

**Comment by FoxBuru** [comment]
After some trace-ing and some workarounds, i think i've managed to fix the hang on transconding. It seems related to the STDERR pipe blocking when calling proc_open on the stream class. The transcode side just misteriously "hangs", stopping the buffering on the audio player side. 

With a fclose($transcoder["stderr"]) would suffice. 

A more profound diff can be found here =>  http://pastebin.com/2KMRv83w

**Comment by SUTJael** [comment]
Thanks, we will investigate on that.

**Comment by Afterster** [comment]
Thank you for this investigation. There is already something similar line 648, but it is done after streaming. You mean stderr stream should be closed before streaming the media right? Do you have any explanation for this? Thanks.

**Comment by FoxBuru** [comment]
I did it based on this comment (http://php.net/manual/es/function.proc-open.php#89338). I think stderr is closing too late on the original code based on that notes. It's also subjectable to tests probing if using non-blocking before the proc_open starts the problem dissapears.

**Comment by Afterster** [comment]
Ok got it I will apply the fix. Thanks a lot this was an annoying issue.
Does your other changes improve anything (using `stream_select` and output buffer flush) or it was just for testing purpose?

**Comment by FoxBuru** [comment]
`stream_select` assures always to get the complete buffer, if not, just holds a 2 seconds timeout, and tries again (it could be useful to hold some transcoding errors possibly). 

The thing around the `ob_flush`, `flush`, and `ob_end_flush` is about precedence. Firstly, flush buffers on high-level to low-level buffering; secondly, flush low-level buffers to invocator (mod_php, uWSGI, fcgi, etc). Third one, just destroys the buffer. `ob_start` in this case, re-initializes all the buffering process to get a clean and controlled buffering.

**Comment by Afterster** [comment]
Ok thanks, I never used stream_select ^^.
I just commited your changes, @nan4k7 @stebe could you confirm this fix the issue on your side too? Thanks.

**Comment by nan4k7** [comment]
@Afterster I can confirm the process now finished and does not stay halted there forever but there is another problem now...

If I play a song and transcoding starts and then skip that song and play another one both processes stay there transcoding until it finishes. The correct behaviour should be that the first process ends and stops the transcoding because if you are playing a playlist and skip 3-4-5 tracks you'll then have a lot of transcoding processes consuming resources and making then very slow

**Comment by Afterster** [comment]
Ok there was a double loop. Could you test now?

**Comment by nan4k7** [comment]
No... Problem changed but still not working correctly... I'm sending you a screenr so you can see the problem occurring.

https://www.screenr.com/ObuN

**Comment by Afterster** [comment]
Ok thanks but I don't understand why this is still happening. Any chance you can add custom logs on your files to see where is the hang? (does it leave `while (!feof($fp) && (connection_status() == 0) && ($transcode || $bytes_streamed < $stream_size));` loop? ...)

**Comment by nan4k7** [comment]
What do you mean by custom logs? Do you want me to enable the debug and see the log? Make some prints in the file to see what happens? I'll make any test you need

**Comment by Afterster** [comment]
Yes it's what I mean. Enable ampache logs and add some additional `debug_event` temporary around the loop to know where it could hangs. Thanks.

**Comment by Afterster** [comment]
@nan4k7 can you identify the issue more precisely with additional logs? 3.8.0 is really close now and I don't want this milestone to be released with a known transcoding bug. Thanks for your help!

**Comment by nan4k7** [comment]
@Afterster Took some time but I think I solved it... Tested it in my linux enviroment and also in a win enviroment.

The problem is basically a bug with proc_open that uses a child so when you kill the proc the child stays there (lot of info in php.net manuals in proc_open and proc_close pages).

To solve this I changed 2 files:
stream.class.php
play/index.php


In stream.class I "rewrote" the start_process function (around line 250) so that is ends up like this:
```
    private static function start_process($command, $settings = array())
    {
        debug_event('stream', "Transcode command: " . $command, 3);

        $descriptors = array(1 => array('pipe', 'w'));
        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
            // Windows doesn't like to provide stderr as a pipe
            $descriptors[2] = array('pipe', 'w');
        }

		if (stripos(php_uname('s'), 'win') > -1)
			$cmdPrefix = "start /B ";
		else
			$cmdPrefix = "exec ";
        
        debug_event('stream', "Transcode command prefix: " . $cmdPrefix, 3);

		$process = proc_open($cmdPrefix.$command, $descriptors, $pipes);
        $parray = array(
            'process' => $process,
            'handle' => $pipes[1],
            'stderr' => $pipes[2]
        );

        if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
            stream_set_blocking($pipes[2], 0); // Be sure stderr is non-blocking
        }

        return array_merge($parray, $settings);
    }
```


and in play/index.php made some changes at the end around line 669:
```
if ($transcode && isset($transcoder)) {
    fclose($fp);

	function kill($pid){
		return stripos(php_uname('s'), 'win')>-1  ? exec("taskkill /F /T /PID $pid") : exec("kill -9 $pid");
	}
	
	$status = proc_get_status($transcoder['process']);
	if($status['running'] == true)
	{
		$pid = $status['pid'];
		debug_event('play', 'Stream process about to be killed. pid:'.$pid, 1);
	
		kill($pid);
       
		proc_close($transcoder['process']);
	}
} else {
    fclose($fp);
}
```



Check it out, test it and if you think it's okay publish it! (you'll then have to add my name somewhere in ampache! :P)


If this works I'm very glad to have helped you.

**Comment by nan4k7** [comment]
Found out my solution is working for FCGI but not por CGI. I'll try to fix it

**Comment by Afterster** [comment]
This looks good, I will test it thank you for your work ! I will wait for CGI fix before publish.
But wouldn't it better to suggest a pull request instead? If you never did it you will learn some skills here and at least your changes will be associated to you directly in git history. It is also better to review / test your changes ;)
Thanks anyway.

**Comment by nan4k7** [comment]
@Afterster never worked with github and don't want to mess things up... :/ If you can clear me up how to do it I have no problem in doing it...


I researched about the problem with CGI and it seems to be a bug with certain apache installations finishing the php process when user aborts and not taking into account the "ignore_user_abort" php command. So as far as I can, there's nothing else I can do.

**Comment by Afterster** [comment]
Ok, do you have a link referring to this php issue?
About github PR, you can take a look on this link: https://help.github.com/articles/using-pull-requests/
But if you don't want to learn or do it, don't worry and just say it ;)

**Comment by nan4k7** [comment]
https://github.com/ampache/ampache/pull/775
https://github.com/ampache/ampache/pull/776

is that ok?

I'll try to find the link, found it yesterday but I seem to have lost it now...

**Comment by Afterster** [comment]
Better to do a single PR when the change is related to the same issue. You can have several files / commit per PR.

**Comment by nan4k7** [comment]
Deleted those, sorry! 

What about this one?
https://github.com/ampache/ampache/pull/779

**Comment by Afterster** [comment]
Merged, thanks!
