### ISSUE TITLE
Extension of the user api result

### ISSUE THREAD

**Issue by usox** [ampache/ampache#3813]
TBD/TBC

As an API developer, I would like to see the result of the user retrieval API method expanded. The aim is to be able to better adapt third-party apps to the respective user and their settings.

Ensure:
- Add the user avatar url to the result
- Add the User AccessLevel to the result (as an enum, not as an integer value)

Requested by @mitchray , @icefields

**Comment by usox** [comment]
Regarding the access level: This is security-relevant - so we need to clarify whether we can/should simply output this at this point as, as far as I know, there is no restriction on access to this method.
It may be necessary to create a separate method that can be used to retrieve the data of the current user.

**Comment by lachlan-00** [comment]
i would usually only output levels if you're the user in question or an admin/100 (which is how most checks are done.)
![image](https://github.com/ampache/ampache/assets/1305249/0bea78b9-a499-4986-89e2-b1b7cb705d06)

so level can go in fullinfo and the avatar url can go in either

has_art doesn't exist for users but should and then the url can go in

**Comment by lachlan-00** [comment]
is there a reason for either int level or text. i'd probably include both so either could be used?

**Comment by usox** [comment]
> is there a reason for either int level or text. i'd probably include both so either could be used?

The aim is to avoid magic numbers. An enum is usually self-explanatory, a magic number always requires a separate explanation.

This is particularly important in Apis so that you can make it as binding as possible. As a developer, you don't really want to work with 50, 75, 100, 324322, but with names that immediately explain the meaning of the number (MANAGER, ADMIN, etc.).

**Comment by usox** [comment]
> i would usually only output levels if you're the user in question or an admin/100 (which is how most checks are done.) !
> so level can go in fullinfo and the avatar url can go in either

Depending on what ideas might come up here, I would tend to design a separate method to pick up the current user's information.
Otherwise, we're mixing up information again and inflating results, all depending on permissions - which unnecessarily increases complexity.

Apart from that, you can integrate the avatar url into the users result either way.

**Comment by lachlan-00** [comment]
added the art url's with 3243e2072

**Comment by lachlan-00** [comment]
i also see that access is already there in the full access, which would be there if you as a user were looking at yourself.

![image](https://github.com/ampache/ampache/assets/1305249/9e887f38-6d07-473f-a7e5-6aa98fa1c66c)

**Comment by mitchray** [comment]
> i also see that access is already there in the full access, which would be there if you as a user were looking at yourself.
> 
> ![image](https://private-user-images.githubusercontent.com/1305249/302963660-9e887f38-6d07-473f-a7e5-6aa98fa1c66c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDYwNDYsIm5iZiI6MTcwNzMwNTc0NiwicGF0aCI6Ii8xMzA1MjQ5LzMwMjk2MzY2MC05ZTg4N2YzOC02ZDA3LTQ3M2YtYTdlNS02YWE5OGZhMWM2NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMTEzNTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZiMjBkMTkzNWM3ZGI0NzRmNzk0MWUzZTU3OTVmNGI3YTMwMDVmODZkMjU4NDQ2YjU2MzFmNGI5OWRkM2MyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-KgbWSdT-yTEACyhIeH_mbTBceUU0DJ2txBes9H3z-k)

Oh nice, I somehow missed that

**Comment by usox** [comment]
Excellent. That's all there is to it.
