### ISSUE TITLE
Broken user update in 6.2.1

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3814]
The MR https://github.com/ampache/ampache/pull/3690 with the patch https://github.com/ampache/ampache/commit/48208f7ad951280230144e5c004bbfe5fca0e123 deleted the function `update` function from User.php

But the `update` function is still in use, for example https://github.com/ampache/ampache/blob/ab2161f1455c76634ab26bd11272ac896d33fcfe/src/Module/Application/Preferences/UpdateUserAction.php#L95

Right now, users can't update their profil anymore, there is no error in front, only an error in ampache.log 
` (src/Module/Application/Preferences/UpdateUserAction.php:NOTRELEVANT) -> Call to undefined method Ampache\Repository\Model\User::update()`

**Comment by fufroma** [comment]
Related to https://github.com/ampache/ampache/pull/3690

**Comment by lachlan-00** [comment]
restored it until it can be removed again. i'll put a @see in as well db500dbb6
