### ISSUE TITLE
Catalog dissapears from the list of catalogs after update to 6.2.1

### ISSUE THREAD

**Issue by openhs** [ampache/ampache#3830]
## Description

After update from 6.1.0 to 6.2.1 my catalog is no longer listed on "Show Catalogs" page (index.php#admin/catalog.php?action=show_catalogs).  Content (songs, albums, ...) is available but not playable.

It happens with my existing catalog.  It does not happen with newly created catalogs.

### Describe the bug

The bug happens on my production installation where I have tried to update from 5.6.2. to 6.2.1.  I have then re-tested with docker installations.  Below is the full list of the tested scenarios and results:

- Production system: update from 5.6.2 to 6.2.1 => catalog dissapears
- New installation from Docker image: update from 5.6.2 to 6.2.1 - no issue
- New installation from Docker image, DB from production system: update from 5.6.2 to 6.2.0 - catalog dissapears
- New installation from Docker image, DB from production system: update from **5.6.2 to 6.1.0 - no issue**
- New installation from Docker image, DB from production system: update from 5.6.2 to 6.2.1 - catalog dissapears
- New installation from Docker image, DB from production system: update from 5.6.2 to 6.1.0 => no issue; then updated from **6.1.0 to 6.2.0 => catalog dissapears**

So in summary, the bug started to appear in 6.2.0 and newly created catalogs are not affected.

### To reproduce

1. Update to 6.2.0 or 6.2.1
2. Click on Show Catalogs
3. See that there is no catalog listed
4. Browse albums
5. Try to play any song
6. See that song is not played

### Expected behavior
Old catalogs are listed on "Show Catalogs" page and songs can be played.

## Environment

* Ampache version: 6.2.1
* Web server + version: Apache
* Server operating system: Linux
* Client operating system: Linux

### Client type

* Web
* Ampache

## Settings

Same as in Docker image 5.6.2.

## Logs

When trying to play a song it writes following log:

2024-02-17T12:20:35+01:00 [admin] (/var/www/localhost/htdocs/ampache/src/Module/
Catalog/Catalog_local.php:162) -> Cannot assign null to property Ampache\Reposit
ory\Model\Catalog::$gather_types of type string

**Comment by usox** [comment]
I think I have found the problem. Seems like you have at least one catalog without media-type - this is currently triggering an error.
