### ISSUE TITLE
Ampache mixes up compilations and solo records

### ISSUE THREAD

**Issue by haelduksf** [ampache/ampache#3841]
### Describe the bug
I have one [split album by Kyuss / Queens of the Stone Age](https://musicbrainz.org/release/1a35b63f-a10e-420f-af2d-12d21632e5a1), and [one album by Kyuss](https://musicbrainz.org/release/78fa4b93-55ff-49b3-84ae-30018a81d0ed). Both are correctly tagged and in the correct folder. Both appear in the web client with Album Artist = "Kyuss / Queens of the Stone Age", album name = "Kyuss / Queens of the Stone Age", and song artist on all Kyuss songs = "Kyuss / Queens of the Stone Age". Queens of the Stone Age songs on the split album correctly show artist = "Queens of the Stone Age". The Ampache API client shows the correct album name but incorrect album artist and song artists. 

Running "update from tags" or manually editing album or song tags does nothing. 

This may be a duplicate of  #3833  but the details are different enough that I figured I'd open a new one. 

![image](https://github.com/ampache/ampache/assets/1475264/5467d98e-2a5b-4509-8f58-9bdd1aed1929)
![image](https://github.com/ampache/ampache/assets/1475264/bad3e654-fc69-4ad4-b487-902cd56efd2a)

I don't have any repro instructions beyond setting up a fresh Ampache 6.2.1 database and importing a music library as described above.  

## Environment

* Ampache version: 6.2.1 Docker image
* Web server + version: Apache Docker image
* Server operating system: PiOS
* Client operating system: Windows/DSub

### Client type

* Web
* Ampache

**Comment by mitchray** [comment]
I'm assuming its due to a known bug where a new artist being added to Ampache sometimes is named incorrectly if the first song it processed was a multi-artist track

You can see if it is or not by going to the Kyuss / Queens of the Stone Age artist in Ampache, if it has an MBID of ```ea0f2a37-7007-4217-a812-396227f5013a``` then its actually Kyuss

The quick fix is to just rename the artist in the Artist > Edit Artist

**Comment by haelduksf** [comment]
You were correct about renaming the artist. This also renamed the album "Kyuss (2006)". Renaming the album does nothing. 
![image](https://github.com/ampache/ampache/assets/1475264/ce307adc-b529-451d-ac1e-7b4aca8f8eeb)

**Comment by mitchray** [comment]
That is probably this bug, if you don't have an album artist set: https://github.com/ampache/ampache/issues/3761

**Comment by haelduksf** [comment]
There was an album artist set, so I don't think it's exactly the same bug. 
I did manage to fix it with "Update from tags"
I won't close this myself in case you want to pursue this further; otherwise it can be closed. Thanks for your help!
