### ISSUE TITLE
Can't download albums in 6.2.1?

### ISSUE THREAD

**Issue by jasminemoeller** [ampache/ampache#3851]
### Describe the bug
It is not possible to download single albums as a ZIP file, even though it is explicitly allowed in the config

### To reproduce

1. Set allow_zip_types = "artist, album, playlist, search, tmp_playlist" in config/ampache.config.php
2. Browse to any album
3. There is no option to download the album.

### Expected behavior
There should be an option to download the album, as it does for single titles and whole artists

### Screenshots
![ampache](https://github.com/ampache/ampache/assets/8457716/b0f02b68-f8b9-4fee-8a51-fe47bf1827bf)

## Environment

* Ampache version: 6.2.1
* Web server + version: official docker image official docker image (nosql)
* Server operating system: official docker image (nosql)
* Client operating system: Windows 10, Chrome

### Client type

* Web

## Settings

See above...

**Comment by fufroma** [comment]
Good catch!

You must add `album_disk` to `allow_zip_types` in `config/ampache.cfg.php`.

I had the same issue, and now I have 
`allow_zip_types = "artist,album,playlist,album_disk"`

And "Download" link is back.

**Comment by fufroma** [comment]
@jasminemoeller did it fix your problem?

**Comment by fufroma** [comment]
@lachlan-00 i think you can close this issue
