### ISSUE TITLE
Forward/backward multimedia controls do not work in web client

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#3862]
### Describe the bug
Unable to use the forward/backward multimedia controls. Have tested on PC with keyboard, as well as an iOS device with Bluetooth headset controls, and Bluetooth car head units. Pause/Play seems to work fine.

### To reproduce

1. Play song using web client
2. Attempt to use forward/backward action on a physical device.
3. No change

### Expected behavior
Should skip to the next or previous track in the playlist, just as using the physical forward/backward arrows do in the web interface.

## Environment

* Ampache version: 6.0.2
* Web server + version: 
* Server operating system: Archlinux
* Client operating system: any

### Client type

* Web

I don't have console access to the server at the moment, but if it helps I can get the logs later. I'm pretty sure this has been an issue for years.

**Comment by usox** [comment]
#3759

**Comment by kuzi-moto** [comment]
I’m fairly certain it’s been working this way for at least 3-4 years. It’s just finally bothered me enough.

**Comment by lachlan-00** [comment]
There were a lot of JS issues in the webplayer over the last year. it could either be the JS or the webplayer html (show_html5_player.inc.php)

i had a look in the comparison and you could probably drop in the latest JS and template without issue. https://github.com/ampache/ampache/compare/6.0.2...patch6 

The only issue i see is it might not catch the is checks
![image](https://github.com/ampache/ampache/assets/1305249/4e84efd8-ec62-4568-8cc1-d31bfc0beb5e)

as of develop/patch6 N and B are working right now for next/back though.

P - play/pause
N - next
B - previous
, - volume down
. - volume up

**Comment by usox** [comment]
> I’m fairly certain it’s been working this way for at least 3-4 years. It’s just finally bothered me enough.

Ah, nevermind.

**Comment by lachlan-00** [comment]
The mpris change works for me in Windows 11 using the notification tray area to change tracks so that would probably be needed to change outside of focus

**Comment by fufroma** [comment]
@kuzi-moto can you try with ampache 6.3.0?

**Comment by kuzi-moto** [comment]
@fufroma Huzzah! It appears that the controls are working now. Thank you!

**Comment by fufroma** [comment]
great :) ! so we can close this issue?

**Comment by kuzi-moto** [comment]
Yes, I think we can!
