### ISSUE TITLE
Video Transcode

### ISSUE THREAD

**Issue by Damgan** [ampache/ampache#3900]
# Issue Template
Video Transcode

## Description
Video enabled, I cannot play many formats.
Example with Acqua Alta Venise 2012 a.mp4 (see encoding below) it works, but not with 100_0057.avi
I'm trying to understand Transcode part (fairly poorly documentation on the net) of ampache.cfg.php, I don't see what's wrong.
The doc https://github.com/ampache/ampache/wiki/Transcoding seems dated to me, can you help me ?

## Log file
Log is not verbose after launching the video 100_0057.avi :
2024-03-24T18:59:36+01:00 [Admin] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\WebPlayer\ShowEmbeddedAction" for action "show"
2024-03-24T18:59:36+01:00 [Admin] (Ampache\Module\System\Session) -> Writing to nnbm6n0jjjotgjikvl0q47c688 with expiration 1711306776
While the launch of the video Acqua Alta Venise 2012 a.mp4 :
2024-03-24T19:09:23+01:00 [Admin] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Utility\ShowAction" for action "show"
2024-03-24T19:09:23+01:00 [Admin] (Ampache\Module\System\Session) -> Writing to nnbm6n0jjjotgjikvl0q47c688 with expiration 1711307363
2024-03-24T19:09:23+01:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2024-03-24T19:09:23+01:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2024-03-24T19:09:23+01:00 [Admin] (Ampache\Module\System\Session) -> nnbm6n0jjjotgjikvl0q47c688 has been extended to Sun, 24 Mar 2024 20:09:23 +0100 extension length 3600
2024-03-24T19:09:23+01:00 [Admin] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Stream\PlayItemAction" for action "play_item"
2024-03-24T19:09:23+01:00 [Admin] (Ampache\Module\Application\Stream\AbstractStreamAction) -> Stream Type: web_player Media IDs: [{"object_type":"video","object_id":260}]

## Video encoding
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/video/Voyage/Acqua Alta Venise 2012 a.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2012-10-28T14:49:29.000000Z
  Duration: 00:05:50.69, start: 0.000000, bitrate: 2662 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x544 [SAR 1:1 DAR 40:17], 2502 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2012-10-28T14:49:29.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 157 kb/s (default)
    Metadata:
      creation_time   : 2012-10-28T14:49:29.000000Z
      handler_name    : L-SMASH Audio Handler

Input #0, avi, from '/data/video/Famille/100_0057.avi':
  Metadata:
    creation_time   : 2003-06-29 10:32:10
    encoder         : CanonMVI01
  Duration: 00:01:27.60, start: 0.000000, bitrate: 2395 kb/s
    Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 320x240, 2305 kb/s, 15 fps, 15 tbr, 15 tbn, 15 tbc
    Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11024 Hz, mono, u8, 88 kb/s

## ampache.cfg.php Transcode part

;#########################################################
; These options control the dynamic downsampling based   #
; on current usage                                       #
; *Note* Transcoding must be enabled and working         #
;#########################################################

; Attempt to optimize bandwidth by dynamically lowering the bit rate of new
; streams. Since the bit rate is only adjusted at the beginning of a song, the
; actual cumulative bitrate for concurrent streams can be up to around
; double the configured value. It also only applies to streams that are
; transcoded.
; DEFAULT: none
;max_bit_rate = 576

; New dynamically downsampled streams will be denied if they are forced below
; this value.
; DEFAULT: 8
;min_bit_rate = 48

;#########################################################
; Transcode Settings                                     #
;#########################################################

; These are commands used to transcode non-streaming
; formats to the target file type for streaming.
; This can be useful in re-encoding file types that don't stream
; very well, or if your player doesn't support some file types.
;
; 'Downsampling' will also use these commands.
;
; To state the bleeding obvious, any programs referenced in the transcode
; commands must be installed, in the web server's search path (or referenced
; by their full path), and executable by the web server.

; Input type selection
; TYPE is the extension. 'allowed' certifies that transcoding works properly for
; this input format. 'required' further forbids the direct streaming of a format
; (e.g. if you store everything in FLAC, but don't want to ever stream that.)
; transcode_TYPE = {allowed|required|false}
; DEFAULT: "false"
;;; Audio
transcode_m4a = "required"
transcode_flac = "required"
transcode_mpc = "required"
transcode_ogg = "allowed"
;transcode_oga = "required"
;transcode_opus = "required"
transcode_wav = "required"
;transcode_wma = "required"
;transcode_aif = "required"
;transcode_aiff = "required"
;transcode_ape = "required"
;transcode_shn = "required"
transcode_mp3 = "allowed"
;;; Video
transcode_avi = "allowed"
;transcode_flv = "allowed"
transcode_mkv = "allowed"
transcode_mpg = "allowed"
;transcode_mpeg = "allowed"
;transcode_m4v = "allowed"
;transcode_mp4 = "allowed"
;transcode_mov = "allowed"
;transcode_wmv = "allowed"
;transcode_ogv = "allowed"
;transcode_divx = "allowed"
;transcode_m2ts = "allowed"
;transcode_webm = "allowed"

; Default audio output format
; DEFAULT: none
encode_target = "mp3"

; Default video output format
; DEFAULT: none
encode_video_target = "webm"

; Override the default output format on a per-type basis, for example,
; to stream lossless encoded files in lossy formats.
; encode_target_TYPE = TYPE
; DEFAULT: none
;encode_target_flac = opus

; Override the default TYPE transcoding behavior on a per-player basis, for example,
; to stream lossless using the api and lossy using the web interface.
; transcode_player_PLAYER_TYPE = TYPE
; Valid PLAYER is: webplayer, api
; DEFAULT: none
;transcode_player_webplayer_m4a = "required"
;transcode_player_webplayer_flac = "required"
;transcode_player_webplayer_mpc = "required"

; Override the default output format on a per-player basis
; encode_player_PLAYER_target = TYPE
; Valid PLAYER is: webplayer, api
; DEFAULT: none
;encode_player_webplayer_target = mp3
;encode_player_api_target = mp3

; Allow clients to override transcode settings (output type, bitrate, codec ...)
; DEFAULT: "true"
transcode_player_customize = "true"

; Command configuration. Substitutions will be made as follows:
; %FILE% => filename
; %BITRATE% => target bit rate (as chosen by the admin or users in the
; preferences, if transcode_player_customize = "true")
; You can do fancy things like VBR, but consider whether the consequences are
; acceptable in your environment.

; Master transcode command
; transcode_cmd should be a single command that supports multiple file types,
; such as ffmpeg or avconv. It's still possible to make a configuration that's
; equivalent to the old default, but if you find that necessary you should be
; clever enough to figure out how on your own.
; DEFAULT: none
transcode_cmd = "ffmpeg"
;transcode_cmd = "avconv"
;transcode_cmd = "/usr/bin/neatokeen"

; Transcode input file argument
transcode_input = "-i %FILE%"

; Specific transcode commands
; It shouldn't be necessary in most cases, but you can override the transcode
; command for specific source formats.  It still needs to accept the
; encoding arguments, so the easiest approach is to use your normal command as
; a clearing-house.
; transcode_cmd_TYPE = TRANSCODE_CMD
;transcode_cmd_mid = "timidity -Or -o \u2013 %FILE% | ffmpeg -f s16le -i pipe:0"

; Encoding arguments
; For each output format, you should provide the necessary arguments for
; your transcode_cmd.
; encode_args_TYPE = TRANSCODE_CMD_ARGS
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_opus = "-vn -b:a %BITRATE%K -c:a libopus -compression_level 10 -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
encode_args_webm = "-b:a %BITRATE%K -f webm -c:v libvpx -preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_args_ogv = "-codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 -f ogg pipe:1"

; Encoding arguments to retrieve an image from a single frame
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"

; Encoding argument to encrust subtitle
encode_srt = "-vf \"subtitles='%SRTFILE%'\""

; Encode segment frame argument
encode_ss_frame = "-ss %TIME%"

; Encode segment duration argument
encode_ss_duration = "-t %DURATION%"

; Use segments for transcoding or send it all in one go.
; Useful if you are having issues streaming the full track.
; You can set it for all streams or a specific player
; POSSIBLE VALUES: true webplayer api
; DEFAULT: "webplayer"
send_full_stream = "webplayer"

## Environment

* Ampache version: 6.2.1
* Web server + version: Nginx 1.18.0
* Server operating system: Debian 11
* Client operating system: Macos

**Comment by Damgan** [comment]
Hello,
I can't find any solutions to solve my problem.
Who can help me ?
I have just mounted ampache/ampache:latest via docker and am faced with the same observation.
Thanks

**Comment by mitchray** [comment]
What happens when you change ```transcode_avi = "required"```

**Comment by Damgan** [comment]
Alors, je dis merci beaucoup Monsieur Mitchray.
