### ISSUE TITLE
image\showaction for non library items (user)

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#3914]
LibraryItemEnum::from() can't ID a user image because it's not a library item.

```
2024-04-03T22:42:22+00:00 [user] (/var/www/music/src/Module/Application/Image/ShowAction.php:163) -> "user" is not a valid backing value for enum Ampache\Repository\Model\LibraryItemEnum
```

@usox i'm assuming we shouldn't be expanding the enum for a user but handling differently? i could add a match or something for users?

https://github.com/ampache/ampache/blob/3d70fc7970f64cd9d2524b497d466d44a720ec34/src/Module/Application/Image/ShowAction.php#L163

**Comment by lachlan-00** [comment]
btw i've switched my home server to patch7 now.

**Comment by lachlan-00** [comment]
7f4604b90658ab6c9e085c962884a150340bc199 sets the match unless you want to do it another way

**Comment by usox** [comment]
Thank you. The LibraryItemLoader should definitely only load library items - therefore the user does not fit in there. I think it would be a good solution to remove the loading of user avatar images from this action altogether. I'll do that now.

**Comment by lachlan-00** [comment]
mental not for me to not close till i've documented that links have to be updated if saved `https://music.com.au/image.php?action=show_user_avatar&object_id=1&thumb=4`

**Comment by usox** [comment]
Maybe add a documentation-label and a 7.0 milestone?

**Comment by lachlan-00** [comment]
starting the docs now. first draft in!

https://github.com/ampache/ampache/wiki/ampache7-for-admins
