### ISSUE TITLE
Adding a tvshow catalog gives error: PHP Fatal error:  Uncaught Error: Class "tvshow" not found

### ISSUE THREAD

**Issue by gibboni** [ampache/ampache#3921]
### Describe the bug

When I add a 'tvshow' catalog the web UI immediately displays _Server-Sent Events connection error. Re-connection..._

Apache error log has this message repeating: 
PHP Fatal error:  Uncaught Error: Class "tvshow" not found in /var/www/ampache/src/Repository/Model/Catalog.php:1939

The catalog is created and Ampache finds all the media files correctly but it keeps displaying the error message in a loop.

### To reproduce

1. Create 'tvshow' catalog

## Environment

* Ampache version: tested with 6.3.1 and develop branch (commit 65d72618f61d2010d87de041da07b3e07d79384d)
* Web server + version: Apache 2.4.57 with php 8.2
* Server operating system: Ubuntu 23.10.
* Client operating system: Windows with Firefox

Edit: added the missing line number in the error message

**Comment by lachlan-00** [comment]
you'll have to include the line number from the error line. its usually at the end in brackets e.g. (1039)

it's possibly in a few areas in that class where there are generic items created from variables

**Comment by gibboni** [comment]
Sorry! I don't know why I didn't notice that it was missing. I added the line number to my post.

**Comment by lachlan-00** [comment]
cool, that's what i thought, gathering art.

it's actually missing the class in the mapper. i'll send that now
![image](https://github.com/ampache/ampache/assets/1305249/dfd9ebeb-3375-4f5f-8ec2-2af9668c4a90)

**Comment by lachlan-00** [comment]
Class "tvshow" means we tried to find th eclass by tvshow didn't match anything in the mapper. this is all good now. i'll be doing a release next week probably
