### ISSUE TITLE
Array to string conversion getFromRequest()

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3934]
Ampache 6.3., php 8.2

I have this error in the logs : 
`[ampache] (log.lib) -> [Runtime Error] Array to string conversion in file src/Module/Util/RequestParser.php(49)`

After some debuging, error is on the line 
` $variable = (string) ($_REQUEST[$variable] ?? '');`
and match the apache log
`https://ampache/batch.php?action=album&id%5B0%5D=3611`
produced mainly by crawler

`%5B0%5D` means [0]

I don't know if we have an issue generating bad link, or if we should handle array in `getFromRequest()`

**Comment by lachlan-00** [comment]
it equals `album&id[0]=3611`

kind of weird. getfromrequest is massive so where is it coming from? do you have a page source/link?

**Comment by fufroma** [comment]
I wasn't able to find the source, there are no referer in the crawler request.

I'll try to add some debug to find the source.

**Comment by lachlan-00** [comment]
oh i missed the url there.

batch is downloading an album so it's possibly creating an array of id's which would have been from when albums were multiple disk items so it would create an array.

This shouldn't be needed now so i'll see if i can recreate it

**Comment by fufroma** [comment]
i don't remember any commit about this, do you want me to check if the bug is still in 6.6.3?

**Comment by lachlan-00** [comment]
i think i took the array off this as it's a single item download. 7 okay `/batch.php?action=album&id=194737`

checking 6 now

**Comment by lachlan-00** [comment]
yeah i think this is okay all the links should be single items
![image](https://github.com/user-attachments/assets/4e180b1d-a590-4f76-8f27-850cb9d558d4)

**Comment by fufroma** [comment]
```
# grep '%5B' play.dogmazic.net-access.log
REDACTED - - [04/Oct/2024:05:52:28 +0200] "GET /batch.php?action=album&id%5B0%5D=9695 HTTP/1.1" 200 870 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.89 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
REDACTED - - [04/Oct/2024:07:33:54 +0200] "GET /batch.php?action=album&id%5B0%5D=9877 HTTP/1.1" 200 3684 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.89 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

I still don't know how they find those url, or if it's some old url they try :s

**Comment by lachlan-00** [comment]
google bot? lol what are they doing there

the only []= i see is for catalogs so they must be using something historical
![image](https://github.com/user-attachments/assets/d68e3a7a-2ea8-4a02-8ce1-7dc1a3e3217f)

![image](https://github.com/user-attachments/assets/f7356447-1114-4049-8d0a-b5ee29d346c9)

**Comment by fufroma** [comment]
if they just try some old cached url, let's close this issue :)
