### ISSUE TITLE
OpenID Support

### ISSUE THREAD

**Issue by Dreadlocke12** [ampache/ampache#3938]
I saw that in the ampache config file the following is included:

;#########################################################
; OpenID login info (optional)                           #
;#########################################################

; Requires specific OpenID Provider Authentication Policy
; DEFAULT: none
; VALUES: PAPE_AUTH_MULTI_FACTOR_PHYSICAL,PAPE_AUTH_MULTI_FACTOR,PAPE_AUTH_PHISHING_RESISTANT
;openid_required_pape = ""

I am a bit confused on how to register this to an openid authentication as this usually reuqires the client id, the secret and as well a few urls. I did not find any documentation on this path. Can you tell me which values I would need to make OpenId work.

**Comment by mitchray** [comment]
We're looking for someone with the knowledge and willingness to tackle this https://github.com/ampache/ampache/issues/2207#issuecomment-1690719233
