### ISSUE TITLE
Remove / replace abandoned packages

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3943]
Two packages are abandoned.

[nabil1337/case-helper ](https://packagist.org/packages/nabil1337/case-helper) 
- last update 2022-02-18. Replaced by [marcusball/case-helper](https://packagist.org/packages/marcusball/case-helper)
- we don't ask for it, but we include [rsd/seafile-php-sdk](https://packagist.org/packages/rsd/seafile-php-sdk) 
- it was fix in 2020 https://github.com/Schmidt-DevOps/Seafile-PHP-SDK/commit/a9e3b95166cbfa321b055e2a6f2e678b99c4b71f
- we need to update our rsd/seafile-php-sdk requirements from ^1 to ^2

[robloach/component-installer](https://packagist.org/packages/robloach/component-installer) 
- last update 2020-08-10. 
- replaced by [oomphinc/composer-installers-extender](https://packagist.org/packages/oomphinc/composer-installers-extender), and look like it's already here : https://github.com/ampache/ampache/blob/ef173c07d7e2d06762eb17df8f84583ee85cb233/composer.json#L35 (added in 6737c6674c800878940516239d7f0d2ed0639952)
- maybe we can just trash it?

**Comment by mitchray** [comment]
Some of these are already fixed in v7 (patch7) 👍

robloach/component-installer is removed as no longer needed
seafile is ^2

**Comment by fufroma** [comment]
Thank you, I checked develop but forgot to check patch7 :)
