### ISSUE TITLE
Conflicting report on what version is installed 

### ISSUE THREAD

**Issue by cnic023** [ampache/ampache#3946]
### Describe the bug
I have attempted to upgrade from Ampache v 5.6.0 to v 6.4.0. I have upgraded from php8.0-fpm to php8.3-fpm
I downloaded: https://github.com/ampache/ampache/releases/download/6.4.0/ampache-6.4.0_all_php8.3.zip
Having updated the config file and adjusted .htaccess, I tried to run:
sudo -u www-data php cli admin:updateDatabase but got:
"Composer dependencies require a PHP version ">= 8.2.0" 

BUT PHP 8.3-fpm is running.

Ampache debug reports:
   Installed Ampache version: 6.4.0.
   Latest Ampache version: 6.4.0.
   [Force check...](https://media.nicoll.nz/admin/system.php?action=show_debug&autoupdate=force)
   Update available (6.4.0).
   [View changes](https://github.com/ampache/ampache/blob/master/docs/CHANGELOG.md) | [Download] 
   (https://github.com/ampache/ampache/releases/download/6.4.0/ampache-6.4.0_all_php8.3.zip)
Ampache debug also reports:
PHP 
Setting | Value
Version | 8.3.6

* Ampache version: ???????
* Web server + version: Apache 2.4.59 (Ubuntu)
* Server operating system: Ubuntu 22.04 Server
* Client operating system: Windows 11 Pro (Firefox up to date) and Chrome

### Client type

* Web

**Comment by cnic023** [comment]
Since my last post I played some music for a while. Then the installation crashed. No login page. Browser reports "504 Gateway Timeout. The gateway did not receive a timely response from the upstream server or application"

I suppose I revert to backup of database and old installation? But I want to upgrade to latest version. It looked pretty good for the short time I got to see it.

**Comment by cnic023** [comment]
I've noticed that my php cli is at 8.0. I guess I should update that to php cli 8.3

**Comment by lachlan-00** [comment]
For apache2 you need to make sure the module is enabled for the php version you want

check the apache conf folder
```
ls /etc/apache2/conf-enabled/
```

i have 8.2-fpm right now on my home server
![image](https://github.com/ampache/ampache/assets/1305249/9bbf6426-7cd9-4194-831f-368d728b9fad)

you can ls the available modules and pick the one you want
```
ls /etc/apache2/conf-available/
```
![image](https://github.com/ampache/ampache/assets/1305249/c140e37a-1374-4942-8d93-35b9d3f4f981)


so for me if i wanted to enable php8.3 i have to disable my active version and enable the new one

```
a2disconf php8.2-fpm
a2enconf php8.3-fpm
```

and then restart the apache service
```
systemctl restart apache2
```

Then for fpm i need to make sure the new php version is running.
```
systemctl stop php8.3-fpm
systemctl start php8.3-fpm
```

For cli you should be able to set it using update alternatives for the cli
```
update-alternatives --config php
```

![image](https://github.com/ampache/ampache/assets/1305249/fc48f48f-4867-4350-8779-b17b2e0bd4b6)


you want apache and the cli to be the same versions so composer will update the correct packages

depending on which versions you have running composer and the web server on different versions will break it all.

**Comment by cnic023** [comment]
I'm very grateful for your help on this. I've been a happy Ampache user for years. I've answered your comments below in green highlight

**Comment by cnic023** [comment]
Ah, I've at least managed to get the login up again (I don't know why it crashed last night). But the 'admin' 'ampache debug' screen still says:

"Ampache Update
Installed Ampache version: 6.4.0.
Latest Ampache version: 6.4.0.
Force check...
Update available (6.4.0).

PHP settings show: 8.3.6

I doubt it's very stable at the moment

**Comment by cnic023** [comment]
Just to say I think I’m on the right track now with tidying up my 6.4.0 upgrade. I can see you have provided a script at https://github.com/ampache/ampache/wiki/ampache6-details
Sorry if I have been wasting your valuable time. But … that’s not to say I definitely won’t bother you again 😊

**Comment by fufroma** [comment]
@cnic023  can we close this issue?

**Comment by cnic023** [comment]
yes please close issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
