### ISSUE TITLE
Symfonium: all cached data lost after update to Ampache 6.4.0

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#3950]
## Description
After updating to the latest Ampache version the access to songs cached for offline access by the app Symfonium is not working anymore.
After checking in with the developer of Symfonium: Has the naming convention for files delivered by Ampache via the Subsonic API changed? This would explain the problem.

## Environment

* Ampache version: 6.4.0
* Web server + version: Apache 2.4
* Server operating system: Fedora Linux 40
* Client operating system: Android 12

### Client type

* SubSonic

**Comment by lachlan-00** [comment]
the file path was sent as a relative file path that also sent the possible transcoded path.

https://github.com/ampache/ampache/commit/bd0f543ea7a43364855f8bae2b74a201e8c2b841

sets the original full file path as the file sent by ampache would never exist as a file

**Comment by lachlan-00** [comment]
You should be able to move your cached files if you cache one file and then move the cache files into the new sub folders.

So 'artist/album/song'

Might become 'music/artist/album/song'

**Comment by arno1979** [comment]
I think this won't work. If I remember correctly Symfonium stores all cached files in one folder, ignoring the original file paths and file names. My best guess is that it generates its own filenames based on a hash value and stores references in a database.

**Comment by lachlan-00** [comment]
For dsub and ultrasonic all i needed to do to refind my cached files was move them into hte sub paths

i'm syncing my library with symphonium now to see if it does anything differently

**Comment by lachlan-00** [comment]
I have no idea where the symphonium cache goes, must be in that closed /sdcard/Android/data folder. I haven't rooted this phone so i haven't checked the actual path.

The help said there was an option for changing the cache path but it may be paid as i can't see an option to change the path.

**Comment by arno1979** [comment]
I just took my SD card and put it into my MacBook to get access to the protected app folders.
The structure of the Symfonium folder is as follows:
"SD Card > Android > data > app.symfonik.music.player > files > OfflineMedias"
Below the last folder I can see subfolders with names from "0" to "9" and "A" to "F". The cached files can be found in these subfolders depending on which number or letter their filename starts with.
Tolriq says this in regards to how the filenames are generated:
"the cache is based on hash on the files names".

I guess this means: Symfonium takes the full filename from the API response (including the filepath which has now changed) and uses a generated hash value as the filename of the cached file.

**Comment by lachlan-00** [comment]
that is annoying, you'd think a hash of the id would be better than the files but that's the way it's been done.

**Comment by Tolriq** [comment]
> that is annoying, you'd think the id would be better than the files but that's the way it's been done.

Actually a file is more immutable than an ID as can be shared accros multiple providers and survive a full crash of Ampache and rescan that would generate new ids.

There's pro and cons for both, but in the context of Symfonium multi provider approach, the file based offline is a lot more efficient unless the server decide to not return the actual file names but generate them and then change the generation algo, that some could say is a breaking change.

**Comment by lachlan-00** [comment]
oh that's right you're multi source, that would be reason enough

**Comment by lachlan-00** [comment]
I'm going to close this because the old way of ampache setting the file path was very wrong.

If you changed your transcode config the file name would change which would break your symphonium cache as well because the path wasn't a real path.

The file name is the original source file path and then transcode format from the response could be used to generate those paths if needed in other areas
