### ISSUE TITLE
playlist_edit API call bug on 6.4

### ISSUE THREAD

**Issue by icefields** [ampache/ampache#3961]
### Describe the bug
There's a bug when adding songs to a playlist, with the new stable version (6.4). Check attached a video and a screenshot.
Version affected are 6.4 and above, everything works as expected in previous versions of Ampache.

### To reproduce
- go to album A, add album A to a newly created playlist P.
- go to album B, add album to P.

**Result:** 
Album A gets added again, this goes on exponentially while adding more albums (at some point I had a playlist with 513 songs, adding only 6 albums). 

### Expected behavior
when I add songs to a playlist using `action=playlist_edit`, the backend should respect the values passed in the call.
The same previously added album shouldn't be re-added every time I add something else to the playlist, unless explicitely specified in the call. 

### More notes

The call looks fine, I'm passing the right ids with the right positions:

```
https://myserver.org//server/json.server.php?
action=playlist_edit&
auth=aaa&
filter=58&
owner=franz&
items=16907,16905,16912,16906,16909,16911,16908,16913,16914,16910,8283,8282,8281,8285,8284&
tracks=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15&
type=private
```

### Power Ampache 2:

https://github.com/ampache/ampache/assets/149625124/15eda962-02b0-49f5-baf7-27da1b393c7e

### Check the web interface after adding to playlist

![photo_2024-05-14_20-19-27](https://github.com/ampache/ampache/assets/149625124/63a3e1b4-8cad-4769-935a-223c4a213ebe)

## Environment

* Ampache version: 6.4 Only
* Server operating system: Any
* Client operating system: Android, Power Ampache 2

### Client type
* Power Ampache

**Comment by lachlan-00** [comment]
1 issue i see is owner is the id of the user and not username. workaround with 90486f3b7518e59095be077250e5cee1f0ce1977
![image](https://github.com/ampache/ampache/assets/1305249/2e782f00-7e16-4cea-a904-0a9b3b188f95)

It looks like PlaylistEditMethod is trying to sort the list and failing massively. this will be in the playlist class, not something in the api.

**Comment by lachlan-00** [comment]
taking the constraint off the rows affects the replace so it's not seeing the existing rows as valid ones to replace so when recreating the list it's inserted after the results.

**Comment by lachlan-00** [comment]
i think this is fixed after d83e50b4aceb47d9805ba8ce004762fb784e6096

**Comment by lachlan-00** [comment]
I think this is all good now with 707a177ff395be2854973d04075e4eff117d755b

go over any issues you've had with it but i think it covers all the issues now

**Comment by icefields** [comment]
awesome! Thanks for the quick fix!

**Comment by lachlan-00** [comment]
ha, not as quick as it could have been
