### ISSUE TITLE
[Feature Request] Debug info in run:cronProcess

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3970]
Ampache 6.5.0 - Debian bookworm - PHP 8.2

Running  `$ /usr/bin/php bin/cli run:cronProcess` can take a long time and it's complicated to know which action is the slowest.

The verbosity level do not seem to improve the output about this.

Having a verbosity level showing time taken by the action and the SQL query launched would be useful to improve performance.

**Comment by fufroma** [comment]
Ampache 7.0 being a pretty big release, this feature could be pretty useful to have to allow quick debug on big instance.

**Comment by lachlan-00** [comment]
i put in more debug lines for it for the steps, i think the biggest ones will be the object cache and the first catalog garbage collect

**Comment by fufroma** [comment]
Fixed in https://github.com/ampache/ampache/commit/64f68035f4e3f7cc15bda75c075724d8e3912ead
