### ISSUE TITLE
Bug - Unvalided account kept forever

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#3979]
_Ampache 6.5.0_

If the instance is open to public registration and the email confirm registration is mandatory, we can have account that never enabled their account (mainly spam & bot).

Actually, those never enabled account are kept it the db forever.

I think it should be deleted after a few days.

**Comment by lachlan-00** [comment]
we clean catalogs but not users. probably need an age limit for guests and a cli command for garbage like that

**Comment by fufroma** [comment]
Do you think you could address this one in 7.0 ?

I made something for my instance, but it may be a persistent issue for others.

**Comment by lachlan-00** [comment]
i can do garbage collection off create date and not null validation
![image](https://github.com/user-attachments/assets/80114276-bf1a-4c93-aa38-38e95f272c54)

30 days after creation garbage

**Comment by fufroma** [comment]
my script use 
```sql
select id, username, FROM_UNIXTIME(last_seen), FROM_UNIXTIME(create_date), last_seen, create_date  from user where last_seen = 0 and create_date < UNIX_TIMESTAMP(DATE_ADD(NOW(), INTERVAL -1 MONTH));
```

**Comment by lachlan-00** [comment]
set with 2cb1900f4 checking validation OR last_seen

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/commit/2cb1900f4ce57c2cac92fd48e760c564dfd04de3#r147524997

that user probably didn't validate but was allowed on. might have to do a cleanup / warning

**Comment by lachlan-00** [comment]
i'll probably do a db update to clear missing validation completion on last seen.

but we need to block users without validation if it's set so i'll test that

**Comment by lachlan-00** [comment]
ee6f375cd that user is valid and should be cleared so lets clear on activate

i'll clear validation on garbage collection.

**Comment by lachlan-00** [comment]
e9a20371c912da5e74a945b31b1e5f242481ebfd checks and clears validation from users if logged in.

this will also catch manually enabled user accounts from the ui

**Comment by fufroma** [comment]
Look good to me :)
