### ISSUE TITLE
Invalid album/artist art when searching for new art

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3983]
Noticed that searching for replacement or new album or artist art has started returning 'invalid' results for all files:

![invallid](https://github.com/user-attachments/assets/06d81bac-ebc4-49d1-bf36-63c05c4e5864)

No errors are reported in the logs and all of the search methods seem to be delivering results from URL's correctly?

On the latest `patch7` git branch and this issue has only started happening very recently.

**Comment by mitchray** [comment]
Confirming, I was on 1d82f42 and it worked but broken on latest pull so somewhere in between, haven't dug further yet

**Comment by lachlan-00** [comment]
probably not sending the type enum. i'll check tomorrow

**Comment by lachlan-00** [comment]
it finds art urls but fails to display, that'll mean the template has something

**Comment by lachlan-00** [comment]
208fa6307 backwards logic for < || >

**Comment by rsinfotech** [comment]
Perfect, that fixes it.

Thanks @lachlan-00 and @mitchray for the rapid responses as always. :+1:
