### ISSUE TITLE
Web UI - right-click album context menu showing php code

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#3988]
Right clicking on an album cover in the web UI shows the context menu with some php code visible:

![image](https://github.com/user-attachments/assets/43cc80d4-bd1d-423a-81f4-ea6e0d38eaa3)

All links still seem to work fine.

On the latest git develop branch.

**Comment by lachlan-00** [comment]
base js doesn't have php to echo
![image](https://github.com/user-attachments/assets/7fb2dfab-4675-401f-b6e2-0dc2deb5e861)

**Comment by lachlan-00** [comment]
is there a way to pass translations through to the JS @mitchray ?

**Comment by mitchray** [comment]
Should be doable, I'll take a look Thursday

**Comment by rsinfotech** [comment]
Perfect, much appreciated all :+1:
