### ISSUE TITLE
[Feature Request] Simplify using avatar as custom logo

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3990]
## Describe what you don't like about Ampache, or what it is missing
It should be easier to make the user's avatar as the custom logo in the upper left corner and apply that setting for all users at the same time.  Right now each user needs to add a specific URL to their avatar.  It also appears this functionality does not work with Gravatar avatars.

## Describe how you would like the feature to work
Create a checkbox for interface customization that says "Use avatar as custom logo" which would allow admin/users/managers to set that value for everyone from one setting.  The existing custom logo functionality should be retained.

Also, if the user does not have an avatar, then the default Ampache logo should be use.

This feature should also work with Gravatar avatars.

**Comment by lachlan-00** [comment]
I do like it, glad to see someone else does that too

**Comment by lachlan-00** [comment]
should be as simple as using the user avatar value (medium for the header bar)
![image](https://github.com/user-attachments/assets/3db3bea2-c08d-42f2-9102-cfa3f1c7fd25)

**Comment by lachlan-00** [comment]
@troycarpenter this works for me in the interim
![image](https://github.com/user-attachments/assets/79702008-c9fb-46cc-81f7-a9210b9d61a9)

`<img src="<?php echo $current_user->get_avatar()['url_medium'] ?? Ui::get_logo_url(); ?>" title="<?php echo $site_title; ?>" alt="<?php echo $site_title; ?>">`

**Comment by lachlan-00** [comment]
added with 898f6087f fea1c3b1c c5198ba20
![image](https://github.com/user-attachments/assets/12fe85b8-b1b6-4298-b7df-f2c768a171b8)

this will use the avatar and ignore the other settings
![image](https://github.com/user-attachments/assets/d542880a-5e99-4aa8-81c6-18140d2af668)

**Comment by troycarpenter** [comment]
Perfect!

**Comment by troycarpenter** [comment]
Does this work with Gravatar avatars as well?  The show_user_avatar function didn't seem to work with Gravatar avatars, probably because they are not stored locally.

**Comment by lachlan-00** [comment]
if User->get_avatar doesn't get a gravatar url it's a bug to fix

the function calls the plugin get_avatar_url function which is what the plugins use
![image](https://github.com/user-attachments/assets/7e8b807a-d2bf-4ee0-abca-91a0d28e6e76)

**Comment by troycarpenter** [comment]
I can confirm it does work with Gravatars.  I deleted my local avatar which reverted then to my Gravatar avatar which showed up as expected.  I then changed my avatar in Gravatar and it also was reflected in Ampache.

But not right away.  To get it to work right away I had to enable the developer tools and do an empty cache and hard reload on Ampache.  Only then did the avatar/Gravatar change show up in the Ampache GUI.

**Comment by lachlan-00** [comment]
yeah the header is cached usually so i think the only way to force it is to reload or log out as the ajax doesn't update that part of the page.

**Comment by troycarpenter** [comment]
Closing as available in the latest 7.x pre-releases.  Not sure if was back ported to 6.5, though.

**Comment by lachlan-00** [comment]
Not yet. I might do it but I'm trying to stop feature creeping outside of api changes
