### ISSUE TITLE
[BUG]: Episodes for Newest Podcasts are not listed in sorted order

### ISSUE THREAD

**Issue by troycarpenter** [ampache/ampache#3997]
## Description
Using Ampache 7.0 Latest Docker Image, the Newest Podcast Episodes tab is not sorted correctly.

### Describe the bug
When selecting Home->Information->Newest->Podcast Episodes, the resulting list seems to not be sorted.  Episodes as far back as 2017 are listed first, but the sort is not in reverse order.  Refreshing the page gives a slightly different random list.

This is for the web interface.  In my Subsonic client (Dsub), the recently added podcast list appears in correct order.

### To reproduce

1. In a web browser, select Home->Information->Newest->Podcast Episodes
2. Observe podcast list is NOT sorted correctly.

### Expected behavior
I expect the list to be sorted by publication date in descending order (that is, newest first).

## Environment

* Ampache version:
* Web server 7.0.0 (Docker Develop Image)
* Server operating system: Linux Docker

### Client type

* Web
* SubSonic: As noted above, SubSonic API appears to be presenting recent podcast episodes in the correct order.

**Comment by troycarpenter** [comment]
It appears they may be at least grouped by podcast, but the episodes should be sorted by publication date, not by podcast (and the episodes are not sorted within each podcast group).

**Comment by lachlan-00** [comment]
Newest means addition time all the stat pages show things based on the time they were added to the database.

That's probably why the podcast episodes look like they're grouped as they're added by podcast.

publication date isn't what that stats class is sorting on.

e.g.
```
SELECT DISTINCT(`podcast_episode`.`id`) AS `id`, MIN(`podcast_episode`.`addition_time`) AS `real_atime` 
FROM `podcast_episode`
LEFT JOIN `catalog` ON `catalog`.`id` = `podcast_episode`.`catalog`
WHERE `catalog`.`id` IN (6,66,2,68,7,64,32)
GROUP BY `podcast_episode`.`id` 
ORDER BY `real_atime` DESC
```

**Comment by troycarpenter** [comment]
Let me think about how to get them to appear as expected.  But your explanation makes sense.  There must have been something that happened recently that caused the episodes to be rescanned (re-added?).  Here's the Newest Podcast Episodes list from this morning.  Notice that all the top new episodes publication dates are from yesterday and today.  Then at the first "skipped" entry, you can see 2017 as the date.
![image](https://github.com/user-attachments/assets/224df303-9b4d-403f-9a81-947a49bb0cfe)

**Comment by troycarpenter** [comment]
Just a follow-up.  The atime in most of my episodes is from Aug 29, 2023.  That day may as well be in the stone age for me because I'll never remember what happened that day to figure it out.

The quick fix will be to simply copy the pubdate into the addition_time field to get it back to a properly sorted order and not worry about it.
