### ISSUE TITLE
[Feature Request] - Sync last.fm playcount to Ampache

### ISSUE THREAD

**Issue by CustardFlan** [ampache/ampache#4004]
Hello!, again there, requesting a new feature

I wish to sync my last.fm playcount to Ampache

What i got is the query for getting that info:

http://ws.audioscrobbler.com/2.0/?method=track.getinfo&api_key=supersecretapikey&artist=Ottawan&track=D.I.S.C.O.&username=CustardSandS&lang=es

This GET request, return that info in the key:

< userplaycount>3< /userplaycount>

So, it works passing the last.fm username and using the track.getinfo method

In addition, that returns if the track is marked as "loved"

< userloved>0< /userloved>

maybe this can be used to mark / unmark the track as favorite too

I been thinking that this feature can be added as a option to sync all the playcounts to the logged user, and update the data in every track loading in the webUI or from an app that request the track use the Subsonic API, keeping the Ampache playcount in sync, the API key can be supplied as usual, and the username can be configured in the user setting too

I really wish that feature, my collection has grown dramatically last years, and, i wish to make smart playlists based on that data, and listen again those forgotten tracks

Thanks in advance!

**Comment by lachlan-00** [comment]
i did an export with lastscrape years ago using https://github.com/lachlan-00/ampache-scripts and this python export script https://github.com/lachlan-00/lastscrape-gui/blob/master/lastexport3.py

I'm not sure if it still works but i used it to export play history and loved tracks.

it's annoying that you have to add your username to get the metadata but the plugin can add that.

the only issue with importing the count is that the database will create that number based on the ampache object_count table so we need to import play history with dates. otherwise the server will recalculate the count using current history

**Comment by lachlan-00** [comment]
if i can still get my export using last scrape i can make a new python script to use the API instead of directly accessing the database.

**Comment by CustardFlan** [comment]
Ok, gonna check that scripts, and test on my server
So, it's not feasible integrating that logic inside Ampache, replacing directly the playcount from whats inside in the returned data from the API?

**Comment by lachlan-00** [comment]
if you export the userplaycount into the database you need to have the play history to back it up.

![image](https://github.com/user-attachments/assets/d830a306-b6b1-4723-9bff-0875de4bd67e)

Right now the database will update counts based on the play history that exists and will decrease counts for missing rows in the object_count table

**Comment by lachlan-00** [comment]
i'll work on my import script again cause it's all possible with the API now and would be less complicated to implement

**Comment by CustardFlan** [comment]
> i'll work on my import script again cause it's all possible with the API now and would be less complicated to implement

Ok, dumping the data right now...

Got page 172 of 4224..

He he

**Comment by lachlan-00** [comment]
give me a few days to make this updated file. i'll make a pretty basic one based on the existing one where you just put name /password in the file manually and test on my spare user.

I'm away for a few days but expect it next week if i don't finish today

**Comment by CustardFlan** [comment]
> give me a few days to make this updated file. i'll make a pretty basic one based on the existing one where you just put name /password in the file manually and test on my spare user.
> 
> I'm away for a few days but expect it next week if i don't finish today

Ok, i know that you told me to wait, but ihave tried the update_ampache_from_file.py with the last.fm exported data and...
nothing happened
It connects to the DB using the name user and pass, i configured  my user ID, but the playcounts remain the same

I suppose that in your side works as is

**Comment by lachlan-00** [comment]
that file is pretty old so i don't know how well that would work anymore but i'll be able to get it done pretty quickly in a new script when i get back to my desk

**Comment by lachlan-00** [comment]
i'm back but not working till prob thurs. will be doing it as my first job.

**Comment by lachlan-00** [comment]
There are 2 queries you'll want to run after this is done

When Ampache scrobbles a track it checks against the client agent that made the play. If the agent matches is will skip, if the agent doesn't match it will insert. This lets you play on the web while playing on your phone.
![image](https://github.com/user-attachments/assets/0acd0c57-2a1f-49e5-b666-ef0464f923c8)

When you import it will only reject a scrobble if the agent matches so you'll get dupes. We can find out which ones are duplicates manually. So if you ran this script on top of existing data you will get duplicates (same `object_id`, `object_type`, `date`, `user` but under a different `agent`)

This query will give you an idea of duplicate plays in your database. (I had 3 in my database)
```
SELECT *
FROM `object_count`
WHERE `count_type` = 'stream' AND
      `date` IN (
                 SELECT `date`
                 FROM `object_count`
                 WHERE `count_type` = 'stream' and
                       `object_type` IN ('song', 'podcast_episode')
                 GROUP BY `object_id`, `object_type`, `date`, `user`, `count_type`
                 HAVING COUNT(CONCAT(`object_id`, `object_type`, `date`, `user`, `count_type`)) > 1
      )
ORDER BY `date`, `object_type`;
```

This action is destructive and will the delete the highest object_id for these plays. (we get the dates from songs and podcasts because you can have multiple artist entries for object_count)
```
DELETE FROM `object_count` WHERE `id` IN (
	SELECT `id` FROM (
	    SELECT max(`id`) as `id`
	    FROM `object_count`
	    WHERE `count_type` = 'stream' AND
	          `date` IN (
	                     SELECT `date`
	                     FROM `object_count`
	                     WHERE `count_type` = 'stream' AND
	                           `object_type` IN ('song', 'podcast')
	                     GROUP BY `object_id`, `object_type`, `date`, `user`, `count_type`
	                     HAVING COUNT(CONCAT(`object_id`, `object_type`, `date`, `user`, `count_type`)) > 1
	    ) GROUP BY `object_id`, `object_type`, `date`, `user`, `count_type`
	) AS `duplicate`
);
```

The key word here is **destructive** so before you do anything, make sure you back up the database.

I have deleted my stuff so many times over the years and almost lost everything a few times.

Now onto python!

**Comment by lachlan-00** [comment]
@CustardFlan the new file is updated. https://github.com/lachlan-00/ampache-scripts/blob/master/update_ampache_from_file2.py for the play history dump.

You can hardcode the variables inside the file or use a csv config file in the same folder
![image](https://github.com/user-attachments/assets/8a1a3b8d-1a8b-4d38-9190-6f463c38162f)

make the file ampache.csv and put in your details
```
# Ampache variables
ampache_url,https://music..com.au
ampache_user,username
ampache_api,supersecretapikey

```

when you have your dump and loved files, copy them and call them dump.txt and loved.txt

I hadn't implemented the loved import but i'll do that now. i want to include the date as an optional field in the server as well as that way you can have the date of loved items in history.

you can use the cli switches or hardcode things as well
![image](https://github.com/user-attachments/assets/a35a1d74-7c3c-43c3-a9f2-e8461cca2c82)

**Comment by lachlan-00** [comment]
loved files don't include albums so i need to just shorten what we have for dump files but i'll test that out soon and update again

**Comment by CustardFlan** [comment]
Excelent!
I will try that right now, time to backup the database...

**Comment by lachlan-00** [comment]
loved is in now too
![image](https://github.com/user-attachments/assets/19bba8e8-7ca5-4266-8460-524eee18c85e)

that should process both files if found and connected

**Comment by lachlan-00** [comment]
all right, i'm done with it all i think.

if you're on develop make sure you get d1b073e54accdaec7986fd9fea692bdd4161e10f so your flag dates will update

If you're on 6.* releases you could copy this commit manually 3377992a778ec5a01791f56196cabf126cd237a7

You can also ignore that and wait if you don't care about the correct date for your heart.

if you update in future and run the script again it will force the correct date without any issue.

What these commits do is let api6 flag calls send a date which will be updated using the lastscrape export.

**Comment by fufroma** [comment]
@CustardFlan  do you still have this bug with the last ampache release? If you don't, can you close this issue?

**Comment by lachlan-00** [comment]
I might put this in the wiki somewhere too so i'll close it when i make that page

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache/wiki/import-lastfm-data

wiki page set, that should cover anyone wanting to import their data
