### ISSUE TITLE
Cannot make static method Ampache\Repository\Model\Catalog

### ISSUE THREAD

**Issue by CodehXodeh** [ampache/ampache#4009]
## Description
Fatal error: Cannot make static method Ampache\Repository\Model\Catalog::getMetadataManager() non static in class Ampache\Module\Beets\Catalog in /home/kaspnuez/radiovault.net/src/Module/Beets/Catalog.php on line 421

### Describe the bug
When trying to access Catalog Types I get a fatal error and am not able to create a type or add any new Catalogs
![ampache-error-1](https://github.com/user-attachments/assets/1b6712ed-e8c0-45b8-91ee-a65874fd8756)

![ampache-error-2](https://github.com/user-attachments/assets/067213a8-c4f3-476f-8076-48d94bb552e6)

![ampache-error-3](https://github.com/user-attachments/assets/ca79190b-689c-4705-b9cc-addc7a799dd0)

**Comment by CodehXodeh** [comment]
Solved it. Had to call the functions Static.

private **static** function getUtilityFactory(): UtilityFactoryInterface for instance

**Comment by lachlan-00** [comment]
i'll enable beets catalog and have a look, this usually means there is a static function that has a call to $this->

there is a mix of static / nonstatic methods with the same name so could be something simple like that
