### ISSUE TITLE
Test of the OpenSearch search (XML) fails for me

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache#4011]
### Discussed in https://github.com/ampache/ampache/discussions/4010

<div type='discussions-op-text'>

<sup>Originally posted by **DJ-SteffEN** August 27, 2024</sup>
Hello,

I would like to know if the OpenSearch search (XML) still works, or how I can test it. 

![image](https://github.com/user-attachments/assets/af36878e-7c6e-465e-be94-46e91a09d56a)

Kind regards 
icqtoni</div>

**Comment by lachlan-00** [comment]
I've created what i think is valid XML output but i still get an error adding as a search engine, not really sure where firefox will log or report these errors?

the file is public/templates/show_search_descriptor.inc.php
```
use Ampache\Config\AmpConfig;

$web_path = AmpConfig::get_web_path();
$char_set = AmpConfig::get('site_charset', 'UTF-8');

header(sprintf('Content-type: application/opensearchdescription+xml; charset=%s; filename=opensearch.xml', $char_set));

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" .
    "<OpenSearchDescription  xmlns=\"http://a9.com/-/spec/opensearch/1.1/\">" .
    "<ShortName>" . scrub_out(T_('Ampache')) . "</ShortName>" .
    "<Description>" . scrub_out(AmpConfig::get('site_title')) . "</Description>" .
    "<InputEncoding>" . $char_set . "></InputEncoding>" .
    "<OutputEncoding>" . $char_set . "></OutputEncoding>" .
    "<Image width=\"16\" height=\"16\">data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAABkZGRVLi4urywsLK8rKyuvKysrrywsLK9ERESQAAAABwAAAAcxMTGQLS0trysrK68rKyuvLS0tryMjI69KSkpVNDQ0uLS0tP+5ubn/uLi4/7i4uP+7u7v/VVVV/0hISBcQEBAXb29v/8HBwf+4uLj/uLi4/76+vv+UlJT/Q0NDuC4uLq+/v7//vr6+/729vf+9vb3/wMDA/1ZWVvg+Pj4WAAAAFnR0dPjIyMj/vb29/729vf/Dw8P/mZmZ/0BAQK8wMDCvv7+//7+/v/++vr7/vr6+/8HBwf9WVlb4Pz8/FgAAABZ1dXX4ycnJ/76+vv++vr7/xMTE/5mZmf9AQECvMDAwr8DAwP/BwcH/wMDA/8DAwP/ExMT/V1dX+D8/PxYAAAAWdXV1+MvLy//AwMD/wMDA/8bGxv+bm5v/Pz8/rzExMa/Dw8P/xMTE/8PDw//Dw8P/x8fH/1hYWPg/Pz8WAAAAFnd3d/jOzs7/w8PD/8PDw//Jycn/nZ2d/z8/P68xMTGvxsbG/8fHx//Gxsb/xsbG/8rKyv9YWFj4Pz8/FgAAABZ4eHj40dHR/8bGxv/Gxsb/zc3N/5+fn/8/Pz+vMjIyr8nJyf/Kysr/ycnJ/8nJyf/Nzc3/Wlpa+D8/PxYAAAAWenp6+NTU1P/Jycn/ycnJ/9DQ0P+ioqL/Pz8/rzIyMq/Ly8v/zc3N/8vLy//Ly8v/z8/P/1tbW/hCQkITAAAAE3x8fPjX19f/y8vL/8vLy//S0tL/pKSk/z8/P68zMzOvzs7O/9DQ0P/Ozs7/zs7O/9TU1P9TU1P4GBgYHwAAAB97e3v42tra/87Ozv/Ozs7/1dXV/6ampv9AQECvNDQ0r9HR0f/T09P/0dHR/9HR0f/X19f/WFhY/h4eHukhISHpjIyM/tra2v/R0dH/0dHR/9jY2P+pqan/QEBArzQ0NK/T09P/1dXV/9PT0//T09P/1NTU/9HR0f/Nzc3/zc3N/9PT0//U1NT/09PT/9PT0//a2tr/q6ur/0BAQK82Njaw1tbW/9jY2P/W1tb/1tbW/93d3f99fX39Pz8/ukVFRbqcnJz93t7e/9bW1v/W1tb/3d3d/62trf9AQECwKioqst7e3v/g4OD/3d3d/93d3f/j4+P/h4eH/kVFRd9ISEjfpqam/uXl5f/d3d3/3d3d/+Xl5f+3t7f/SEhItFJSUlR+fn7zu7u7/7y8vP+7u7v/u7u7/729vf+9vb3/vb29/729vf+7u7v/u7u7/729vf+9vb3/Wlpa1UlJSTuNjY0TR0dHgUZGRq9HR0evRkZGr0VFRa9JSUmvTU1Nr01NTa9ISEivRUVFr0ZGRq9HR0evTk5Orw8PD1UAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAA==</Image>" .
    "<Url type=\"text/html\" method=\"GET\" template=\"" . $web_path . "/search.php?type=song&amp;rule_1_input={searchTerms}&amp;action=search&amp;rule_1_operator=0&amp;object_type=song&amp;rule_1=anywhere\"/>" .
    "</OpenSearchDescription>";
```

**Comment by fufroma** [comment]
There was some PHP code in plain text after the generated XML on `https://[server]/search.php?action=descriptor`

I removed it, firefox allowed me to add the search engine. Maybe it's fixed...

**Comment by fufroma** [comment]
Ampache 6.6.1 and Firefox 115.14 ESR here. What about you?

Can you try adding the search engine of https://play.dogmazic.net/ ?

**Comment by lachlan-00** [comment]
Actually, i'll be that this has to do with authentication!

search.php requires auth and firefox hasn't got it

**Comment by lachlan-00** [comment]
so what we probably can't do is allow public search when the site requires auth OR work out how that even happens,

Firefox must be requiring access to the page and the site is sent to the login page instead

**Comment by lachlan-00** [comment]
confirmed working with public.ampache.dev so that's the answer for why it doesn't work.

s_all also doesn't exist as a parameter anywhere so the search is just all / public so i need to fix that too

**Comment by lachlan-00** [comment]
fix incoming. got it working with a separate output file

**Comment by lachlan-00** [comment]
all working now with be28dd5cf76f2cef303df0e6ec0ca8ef56236e1

* use a separate php file without auth to generate the xml (site/opensearch.php?action=descriptor)
* generate and actual xml file with correct headers (if you go to that address you get an opensearch.xml)
* use valid search parameters for the search url (s_all must have been really old)
* add an autoupdate link in case things change (haven't tested this but it should work)
* Use a Unique ShortName (Can't add duplicates) (use site_title for name and a generic 'Search Ampache description')
* use custom favicon if available and default to current favicon instead of the original one (the original A was the data icon)

Now with auth, i can add the url as it's always publicly accessible using opensearch.php
![image](https://github.com/user-attachments/assets/a55ad0ae-fc3d-45e3-8903-c68ced3d07c2)

then search
![image](https://github.com/user-attachments/assets/75977d12-24b9-4ddf-a860-940b093f83b4)

It also fixes up continually asking to add (the plus button in the search bar disappears)

**Comment by lachlan-00** [comment]
> Ampache 6.6.1 and Firefox 115.14 ESR here. What about you?
> 
> Can you try adding the search engine of https://play.dogmazic.net/ ?
> 
> And what the output of `view-source:https://[fqdn]/search.php?action=descriptor`

thanks for pointing me to the answer

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

great, thanks for your quick response.
I don't enforce authentication but have implemented #be28dd5 anyway.
Unfortunately, it then only returns an empty HTML framework.
So I only adjusted '[show_search_descriptor]( url)' and something comes back.
However, the line with the header causes a download of the XML file in search.osdx.
I assume that this is not correct for OpenSearch, or is it?

with kind regards
DJ-SteffEN

**Comment by lachlan-00** [comment]
osdx is what windows saves the file as for some reason, it seems to ignore the header to set filename.

I had a loot at your file and the data looks good, I can add inthemix as a search engine and search with it as my engine from the search bar no problem too

**Comment by lachlan-00** [comment]
splitting the file out into a different link gets around requiring auth.

your site without auth will work with search.php but sites with auth will need to use the extra opensearch.php file with doesn't require aith to return data.

**Comment by DJ-SteffEN** [comment]
super ... thanks

**Comment by lachlan-00** [comment]
it was a good one to fix, i didn't know anything about it as a feature and now i know

**Comment by fufroma** [comment]
@DJ-SteffEN  do you still have this bug with the last ampache release? If you don't, can you close this issue?

**Comment by DJ-SteffEN** [comment]
Hello fufroma

I tried, but I can't close #4011 or I don't know how (4010 is closed).

with kind regards
DJ-SteffEN
