### ISSUE TITLE
Change the example installation "chuck everything into var www" for Debian to a mv instead of a rm

### ISSUE THREAD

**Issue by Bracket-H** [ampache/ampache#4028]
I'm not on Debian but, I'd be PISSED if I blindly copy pasted this as a user who put something in his web directory before at some point, maybe forgot about it, and was so honeystrucked by this software that I'd somehow overlook the rm -rf you're putting there.

In a perfect world, noone would be surprised by this, but, perhaps just mv the old html folder and name it html_ampached_backup or something.

The page in question.
https://github.com/ampache/ampache/wiki/Installation#web-based-installer

I'm not learned enough to link the section directly.

**Comment by fufroma** [comment]
Fixed

@lachlan-00 you can close the issue
