### ISSUE TITLE
Additionnal UI text in the upload form intro to warn about irrevocable nature of most, if not any, free/open licenses

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#4039]
At Dogmazic we are currently thinking about adding on the upload page, at the bottom of the free form text/HTML explaining the upload process, the following sentences (in French) : 

"ATTENTION: la licence de musique que vous allez choisir abandonne de manière irrévocable certains droits au public. Lisez soigneusement le texte de la licence que vous allez choisir avec le lien 'voir la licence' disponible"

which translates roughly as (in English)

"WARNING: the music license you are going to choose gives away in a irrevocable manner some rights to the audience. Read carefully the text of license you are going to choose with the 'see license' link provided"

Since this warning applies to just any open publishing platform using licenses, it may be a good idea to have it as a text label for anyone, provided by Ampache as-is - also it would allow translations of it.

**Comment by lachlan-00** [comment]
which area do you think? probably at the top between the header and target folder?

![image](https://github.com/user-attachments/assets/e4f1acec-a170-48e7-a072-7dde5fda06a7)

**Comment by lachlan-00** [comment]
what about here, this is 3 separate translations
![image](https://github.com/user-attachments/assets/3309fa0c-4fba-4a1a-8125-929cf5834164)

**Comment by shangril** [comment]
That exactlyt the place I was thinking about as the most relevant ! Thank
you !Message ID: ***@***.***>

>

**Comment by lachlan-00** [comment]
set in develop with 7a0f43b96 ampache6 isn't getting translation updates so you can just copy the diff into your add_upload and translate directly
