### ISSUE TITLE
Catalog view shows no counter while updating

### ISSUE THREAD

**Issue by Razrael** [ampache/ampache#404]
The counter,  which was displayed while add/verify/clean actions,  is not displayed anymore. 
It will be shown after the action,  but this can be too late because the action may take a few minutes. Users should get a imediately response.

It only works,  if I disable the Ajax loading in the Settings. 

If this is no error on my installation/webserver,  I will try to fix this.

**Comment by Afterster** [comment]
@Razrael is this something still in progress on your side (you looked to have good ideas on how to handle it correctly) or should I work on it? Thanks.

**Comment by Razrael** [comment]
I could not yet begin with this. If you have time to do it then you can do it, there was no work on my side yet.

**Comment by Afterster** [comment]
Ok I added Server-Sent Events on catalog actions, this should fix this issue but I will wait for feedbacks before closing it. Thanks !
If SSE is not available ajax request is used (no progress view).

**Comment by 84Guzz** [comment]
Hey there, this is my first comment on ampache. I tested this and the update section is not visible if web player is enabled.

**Comment by Afterster** [comment]
Indeed @84Guzz, thanks for the report. I should have fixed that now.

**Comment by 84Guzz** [comment]
Tested, works :+1:

**Comment by Razrael** [comment]
Nice, this works fine, thanks!
