### ISSUE TITLE
Ampache does not work after Ubuntu upgrade from 22.04 to 24.04, php7.4-fpm.sock error  -- Resolved

### ISSUE THREAD

**Issue by rhauff1** [ampache/ampache#4046]
## Description
Get "503 Service Unavailable" when trying to load Ampache webpage

### Describe the bug
Webpage does not load

## Environment

* Ampache version:  6.6.1 (I THINK, cannot see version as page does not load)
* Web server + version:  Apache2
* Server operating system:  Ubuntu 24.04
* Client operating system:

### Client type

* Web
* Ampache
* SubSonic

## What I tried to fix
I found the php7.4-fpm.service was masked, was able to unmask it and start the service, but still getting the same error.

## Logs

Ampache error log in var/log/ampache no longer exists since I upgraded a few days ago

Here is the contents of var/log/apache2/ampache.error.log:
`[Sat Oct 19 18:36:50.979185 2024] [proxy:error] [pid 487553] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 18:36:50.979244 2024] [proxy_fcgi:error] [pid 487553] [client 192.168.2.110:55860] AH01079: failed to make connection to backend: httpd-UDS
[Sat Oct 19 18:46:01.556942 2024] [proxy:error] [pid 487554] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 18:46:01.556984 2024] [proxy_fcgi:error] [pid 487554] [client 192.168.2.110:42952] AH01079: failed to make connection to backend: httpd-UDS
[Sat Oct 19 18:46:40.858050 2024] [proxy:error] [pid 619822] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 18:46:40.858160 2024] [proxy_fcgi:error] [pid 619822] [client 192.168.2.110:34574] AH01079: failed to make connection to backend: httpd-UDS
[Sat Oct 19 18:49:30.394279 2024] [proxy:error] [pid 619821] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 18:49:30.394372 2024] [proxy_fcgi:error] [pid 619821] [client 192.168.2.110:47264] AH01079: failed to make connection to backend: httpd-UDS
[Sat Oct 19 18:58:11.653859 2024] [proxy:error] [pid 619823] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 18:58:11.655626 2024] [proxy_fcgi:error] [pid 619823] [client 192.168.2.110:43254] AH01079: failed to make connection to backend: httpd-UDS
[Sat Oct 19 19:00:56.275125 2024] [proxy:error] [pid 1382] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.sock (*:80) failed
[Sat Oct 19 19:00:56.275384 2024] [proxy_fcgi:error] [pid 1382] [client 192.168.2.110:42746] AH01079: failed to make connection to backend: httpd-UDS`

**Comment by rhauff1** [comment]
Checked the Ampache debug page again, and it suggested the PHP SimpleXML and PHP GD extensions.

Installed these and all errors cleared!

**Comment by rhauff1** [comment]
Resolved

**Comment by fufroma** [comment]
@rhauff1 could you close this issue?
