### ISSUE TITLE
export playlists

### ISSUE THREAD

**Issue by mrpurplenz** [ampache/ampache#405]
Is there any chance playlists could be exported - or more precisely - backed up?
I dont know how many times I (as an average user) have lost playlists due to reinstalling (usually a newer version) of ampache from clean. There are many reasons someone would reinstall ampache to a clean server and to have an importable backup of playlists (and settings) would be just super. 

I do realise some of the difficulties but perhaps this could be a place to start a discussion about potential solutions?

**Comment by Afterster** [comment]
Okay! Finally done as a tool inside /bin folder with commit https://github.com/ampache/ampache/commit/14dcce0cce3e2bb617d03b274de23ad43b318874.
To use it just call `php bin/write_playlists.inc <DIRNAME> <TYPE> [<EXT>]`.

For instance:
 * to export all playlists to xspf files: `php bin/write_playlists.inc /var/local/playlists playlists xspf`
 * to export all albums to m3u files: `php bin/write_playlists.inc /var/local/playlists albums m3u`
 * to export all artists to pls files: `php bin/write_playlists.inc /var/local/playlists artists pls`

**Comment by roba91** [comment]
Hint (could help the next one finding this): On calling `php bin/write_playlists.inc <PATH> playlist m3u` I got

    PHP Warning:  require_once(../lib/init.php): failed to open stream: No such file or directory in /var/www/ampache/bin/write_playlists.inc on line 24
    PHP Fatal error:  require_once(): Failed opening required '../lib/init.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/ampache/bin/write_playlists.inc on line 24

Fixed it by calling `php write_playlists.inc <PATH> playlist m3u` inside of `bin` instead.

**Comment by xeruf** [comment]
Now called via `cli export:playlist` in case anybody still stumbles upon this as I did ^^
