### ISSUE TITLE
7.0.1 - UI Issue for Album Art

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#4059]
Ampache 7.0.1

With JS : art is over the footer
https://play.dogmazic.net/#albums.php?action=show_disk&album_disk=7655
![image](https://github.com/user-attachments/assets/bae45b2d-4d40-48c3-bdfa-01c5bf170b11)

Without JS : footer missing, art overflow the div
https://play.dogmazic.net/albums.php?action=show_disk&album_disk=7655
![image](https://github.com/user-attachments/assets/50f8423b-c4d4-4b9e-a26d-3910eac0e999)

It seems fine when we are logged in, but just because we have some luck (there are a lot a link on the right, so the Art doesn't overflow the div)

**Comment by lachlan-00** [comment]
yeah there must be an expectation of lines/songs to pad it out

**Comment by lachlan-00** [comment]
![image](https://github.com/user-attachments/assets/65b40858-a9a9-4b04-aa10-e4f898219830)

the main container can be lower, that doesn't affect logged in look as well.
![image](https://github.com/user-attachments/assets/10e517de-41db-410a-bda0-5d0181eedeed)

the content link box i'll look at now

**Comment by lachlan-00** [comment]
is there a reason there are no songs in the album as well?

**Comment by lachlan-00** [comment]
your loading popup is in an odd spot too

![image](https://github.com/user-attachments/assets/1a84a8d4-d78d-4525-9821-d73bc2cc3ac6)

it doesn't seem to be in the header so this fits here. is this a different theme setting we need to account for?
![image](https://github.com/user-attachments/assets/5d9f9bce-ed1a-4e38-a424-2ec076c397b1)

**Comment by lachlan-00** [comment]
i set it to 100% now and that covers most cases of the content not fitting and then the footer is always at the footer now.

**Comment by lachlan-00** [comment]
lots of screwing around to come.... i hate css sometimes

**Comment by lachlan-00** [comment]
7ffced0f7 is what you want. there should be an empty row table on there

**Comment by lachlan-00** [comment]
The loading position is for the ui_fixed preference.  I'm going to load that directly on the header if that's enabled

**Comment by lachlan-00** [comment]
@fufroma fix your loading text location with these two commits

dda1d27a9 (assign to variable instead of multiple calls)
54f6094dd (put the loading text in the fixed header instead of the content page)

**Comment by fufroma** [comment]
Fixed with 7.1.0 !
