### ISSUE TITLE
7.0.1 - Issue for looking at an album

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#4060]
Maybe not an issue, but there is a problem for the user.

Let's try on https://play.dogmazic.net/ , I want to take a look at the album _Hysteresis_.

Two way of doing it :
- search bar, top right. I tape "Hysteresis", one result : a link to https://play.dogmazic.net/#albums.php?action=show_disk&album_disk=7281
- I go on the left, Albums, scroll down, I found it : a link to https://play.dogmazic.net/#albums.php?action=show&album=8824

Here the issue : search result point the the album **disk**, and you have no way of understanding that except looking at the URL

I think the search result not point to album disk but to album, I think it's too shady for an end-user to understand out of the box.

**Comment by fufroma** [comment]
I forgot : Issue to have a link to album disk : no way to play music or find the album

**Comment by shangril** [comment]
Also there's the same symptom (mostly empty page, no "download" link, no tracklist  - an album "disk" page) when browsing first an "artist" page and clicking  on an album in its list : it leads to a broken "disk" page.

**Comment by lachlan-00** [comment]
Downloads for album_disk need to be added as a valid download type.

The link issue means there is a spot where album_group isn't checking.

When album_group is disabled all links should point to album_disk links

**Comment by lachlan-00** [comment]
Albums and album_disks also have different id's so there may be a bug where the link is putting album but is using a disk id.

I'm not working again til Monday but if you have any spots or more info add in and I'll fix them up monday

**Comment by lachlan-00** [comment]
901d428ab sets album group for mashup

**Comment by lachlan-00** [comment]
i'm going to look for some more places but i think that's the biggest issue. sidebar didn't know it was ungrouped

**Comment by fufroma** [comment]
> Downloads for album_disk need to be added as a valid download type in the config.

Do you mean in` allow_zip_types = "artist,album,playlist,album_disk"` ? If you are, I already added it a few release ago.

Nevertheless, on a album_disk page like https://play.dogmazic.net/#albums.php?action=show_disk&album_disk=7281 even the song list is missing

**Comment by lachlan-00** [comment]
For this page i think the id is an album id

Remove the _disk and you will see songs. 

What i need to know is where this link comes from as it must id disk correctly but be applying the album id I correctly

What you should be sent is a different id's for the album_disk.

If you check the album_disk table that would confirm it. But I need to know what page that link comes from to confirm it is the correct id being sent

**Comment by fufroma** [comment]
Take a look at my first comment:
- there are explanation where I got the link
- in the example I gave, removing _disk does not show song as the id is not the good one

I think we should almost never give the album_disk page as a search result

**Comment by fufroma** [comment]
> search bar, top right. I tape "Hysteresis", one result : a link to https://play.dogmazic.net/#albums.php?action=show_disk&album_disk=7281

The search give answer https://play.dogmazic.net/server/ajax.server.php?page=search&action=search&target=anywhere&search=Hysteresis&xoutput=json

Answer got album_disk link
```json
[
  {
    "type": "Albums",
    "link": "https://play.dogmazic.net/albums.php?action=show_disk&album_disk=7281",
    "label": "Hysteresis",
    "value": "Hysteresis",
    "rels": "-SHNECK REAPER-",
    "image": "https://play.dogmazic.net/image.php?object_id=8824&object_type=album&thumb=10&name=art.jpg"
  }
]
```
The id 7281 is the good ID for the album_disk.

**Comment by lachlan-00** [comment]
with album_group disabled it should always be showing album_disk links.
![image](https://github.com/user-attachments/assets/c88bc4c3-943c-4e21-afa2-57cee58e7652)

the sidebar needs to be updated with https://github.com/ampache/ampache/commit/901d428ab5f843748aded9ef8f918bba1fe88718
![image](https://github.com/user-attachments/assets/9e77bd61-8ef2-4ced-86a6-7c513597e3cc)

all the other areas look correct. everywhere i'm looking shows up as album_disk

what i don't understand right now is why your album_disk's aren't showing songs. i set up https://public.ampache.dev to match your settings and things are all loading correctly

when i search the album Hysteresis all the songs show up correctly but not when loading the songs when using the disk
https://play.dogmazic.net/index.php#albums.php?action=show&album=8824

**Comment by fufroma** [comment]
> when i search the album Hysteresis

how do you search it? top right search bar return a album_disk link

**Comment by fufroma** [comment]
I applied https://github.com/ampache/ampache/commit/901d428ab5f843748aded9ef8f918bba1fe88718 (there is a typo, there is a " to remove)

If I get it, it should be `album_disk` everywhere, and never `album` ?

**Comment by lachlan-00** [comment]
interesting is that other albums are working fine so i think it's specific to older albums (new albums all lost album disks)

the mashup page link is still showing albums (fixed with 74e9b017b, get album art but use disk link)
![image](https://github.com/user-attachments/assets/ebb66cac-3786-4bce-803e-0221a3fe5acf)

**Comment by lachlan-00** [comment]
We need to see why browse for album disk isn't showing for you though.

![image](https://github.com/user-attachments/assets/946cd1e0-4f5f-49e4-8966-88e069d6e8aa)

query without catalog filter is:

```
SELECT `song`.`id` FROM `song` LEFT JOIN `album_disk` ON `album_disk`.`album_id` = `song`.`album` AND `album_disk`.`disk` = `song`.`disk` WHERE `album_disk`.`id` = '7281' ORDER BY `song`.`track` ASC LIMIT 0, 50
```

I think there is a disconnect between the album disk and the song disks. there also isn't an option to assign a disk number on a track

**Comment by fufroma** [comment]
```
MariaDB [ampache]> SELECT `song`.`id` FROM `song` LEFT JOIN `album_disk` ON `album_disk`.`album_id` = `song`.`album` AND `album_disk`.`disk` = `song`.`disk` WHERE `album_disk`.`id` = '7281' ORDER BY `song`.`track` ASC LIMIT 0, 50;
+-------+
| id    |
+-------+
| 53634 |
| 53633 |
| 53632 |
| 53631 |
| 53630 |
| 53629 |
| 53628 |
| 53627 |
+-------+
8 rows in set (0,000 sec)

```

**Comment by lachlan-00** [comment]
werid! wonder why i can't see any songs on the album_disk links?

the id's are all correct

can you check the site debug on the query class? `src/Repository/Model/Query.php`
![image](https://github.com/user-attachments/assets/3bc260f8-ad54-49f6-9236-a28e593d6e0d)

**Comment by fufroma** [comment]
got something : page stopped executing, there is a missing var :
```
2024-11-05T06:48:09+00:00 [ampache] (log.lib) -> [Runtime Error] Undefined variable $current_user in file /opt/play.dogmazic.net/public/templates/show_album_disk.inc.php(181)
2024-11-05T06:48:09+00:00 [ampache] (log.lib) -> [Runtime Error] Undefined variable $current_user in file /opt/play.dogmazic.net/public/templates/show_album_disk.inc.php(207)
2024-11-05T06:48:09+00:00 [-1] (/opt/play.dogmazic.net/public/templates/show_album_disk.inc.php:207) -> Call to a member function getId() on null
```

**Comment by fufroma** [comment]
Manually adding `$current_user` definition made the song appears

**Comment by lachlan-00** [comment]
ahha! i just put that in today as well with 9ae3bd48d

**Comment by lachlan-00** [comment]
i've put a lot of effort into editing and managing single disks today.

Disk and subtitle are allowed when editing an individual disk (not shown on album objects only album_disk)
![image](https://github.com/user-attachments/assets/f99120f0-52e8-4ef2-ba07-9c313762894e)

Disk added to song_edit
![image](https://github.com/user-attachments/assets/32f025f5-4987-4d33-9c3a-2e3064386249)

All album_disk edit links will now point to the disk edit page instead of the album.

If you edit a song disk with songs they will move their disk to the new number.

> EDIT : got this error by calling https://play.dogmazic.net/albums.php?action=show_disk&album_disk=7281 from shell with wget (so no logged in, no session)

97be002ea fixed the null user, there might be a few of those elsewhere

**Comment by fufroma** [comment]
I applied https://github.com/ampache/ampache/commit/9ae3bd48d1277082cdb7ca6758268b5c4343e7ad and look fine

I'll let my users do some more test but look good to me :) ( @shangril ?)

(I'm glad we found a bug and it wasn't an error on my config :D )

**Comment by lachlan-00** [comment]
yeah definite bugs. i've changed the public demo to be more like your server and that helped me find a lot of things.

the next version has kind of exploded now with all these fixes

**Comment by lachlan-00** [comment]
if you do a grep on your logs you might find some more

```
cat /var/log/ampache/*.log | grep "$(date +"%Y-%m-%d")" | grep "Error"
```

**Comment by shangril** [comment]
After basic tests, it's established that the patch broke the "album" (not album_disk) URLs, which now display a blank page instead of the wanted album. This is an issue and @fufroma has been informed. Most notably : 

RSS feeds of newest albums include "album" URL : then the landing homepage of Dogmazic which basically parses various RSSes from play.dogmazic.net which is our Ampache now have linking covers/titles that lead to nowhere. 

5 years of blogging over our non-profit blog for reviews and monthly bulletin have now "album" URLs that lead currently to nowhere. 

Fufroma should look at it a bit. Thx for reading.

**Comment by shangril** [comment]
Here's an example of broke "album" URL page : 

https://play.dogmazic.net/albums.php?action=show&album=11009

**Comment by fufroma** [comment]
@shangril  I made a typo when applying the fix, it works fine :)

**Comment by shangril** [comment]
testing… Tested. Working.

**Comment by fufroma** [comment]
@shangril do you think I can close this issue ?

**Comment by shangril** [comment]
If it's OK for you, I think you can.
