### ISSUE TITLE
Bootstrap 3 EOL

### ISSUE THREAD

**Issue by fufroma** [ampache/ampache#4070]
Ampache 7 still use Bootstrap 3

> Bootstrap 3 reached end of life July 24, 2019, followed by Bootstrap 4 on January 1, 2023. As such, neither version receives new features, updates, or security fixes. However, both are still available on all existing distribution channels (CDNs, package managers, GitHub, etc).

**Comment by lachlan-00** [comment]
i actually just updated the npm packages this morning https://github.com/ampache/ampache/commit/36027bfcf03e125676430b07118bdf6661e87e07
