### ISSUE TITLE
The filtering (alphabet) for the tags does not work

### ISSUE THREAD

**Issue by DJ-SteffEN** [ampache/ampache#4077]
Hello,

I have a problem with 'Browse Tags' with the list that is displayed below the tags when I use filtering.

0. go to the tags -> /browse.php?action=tag&type=song
1. select tag -> list OK -> the display of the pages and the item count are correct
2. switch on filtering -> list remains unchanged -> the display of the pages and the item count match the filter result
3. if I now select the same tag again, the matching list is also displayed

The problem can also be seen with 5.6.4 (https://5.ampache.dev/), with demo version 7.1.0 it also seems to be the same (is very slow)

Can someone take a look at this and fix it, attach a picture.

With kind regards
DJ-SteffEN

![issue](https://github.com/user-attachments/assets/f7d2cffb-3399-446a-adcc-c3d335fbc633)

**Comment by lachlan-00** [comment]
the query is not including the items in the browse. it's actually looking at everything. this seems to be replacing all the filters and not reloading the page correctly

```
SELECT `album`.`id` AS `id`
FROM `album`
WHERE `album`.`name` REGEXP '^Y' AND 
 `album`.`catalog` IN (SELECT `catalog_id` FROM `catalog_filter_group_map` INNER JOIN `user` ON `user`.`catalog_filter_group` = `catalog_filter_group_map`.`group_id` WHERE `user`.`id` = 2 AND `catalog_filter_group_map`.`enabled`=1)
GROUP BY `album`.`name`, `album`.`id`
ORDER BY IFNULL(`album`.`original_year`, `album`.`year`)
DESC, `album`.`addition_time` DESC
```
same for songs
```
SELECT `song`.`id` FROM `song`
WHERE `song`.`title` REGEXP '^Y' AND
  `song`.`catalog` IN (SELECT `catalog_id` FROM `catalog_filter_group_map` INNER JOIN `user` ON `user`.`catalog_filter_group` = `catalog_filter_group_map`.`group_id` WHERE `user`.`id` = 2 AND `catalog_filter_group_map`.`enabled`=1)
```

**Comment by lachlan-00** [comment]
I don't think these header filters have been applying to smaller browses. it looks like the intention is that thay;re applied to everything but they show up in a few places. i need to filter them in a second area and not overwrite the originals.

**Comment by lachlan-00** [comment]
I tried setting it on the output with 9d8b89ebe0334ba7085c68fe63573501599e7757 but it's only going to check items per page. (Reverted again with 8d086bf7a)

needs more work as i don't think this logically works right now

**Comment by lachlan-00** [comment]
seems a bit better after 23f74c86f, but there's also no way to reset so i'll add one.

this should also be something you can edit in the config file in case you want to filter on different languages

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

It looks to me as if only the refresh of the 'ajax area' is missing, since the display of the pages and the item counter work correctly.
The filtering of the cache seems to have been successful.

**Comment by lachlan-00** [comment]
there are some areas where i click on alphabet and it doesn't seem to do anything which is weird. i'll spend some more time on it but the actual function seems okay.

I've also added the string to the server config and added * to allow you to clear the current selection (regex ^.*)
![image](https://github.com/user-attachments/assets/0d61c72d-1d8a-403b-bd08-c3cae2a330a6)

**Comment by DJ-SteffEN** [comment]
yes exactly, when I click from one letter of the alphabet to the other only the page and count are updated but not the list.
This works everywhere except for the genres.

**Comment by DJ-SteffEN** [comment]
The comparison of the JSON in the 'tmp_browse' table also shows that the filtering works.
above: alphabet filtering of the song list
below: alphabet filtering of the song list under genres

`{
	"base":"SELECT %%SELECT%% FROM `song` ",
	"filter":{"catalog":null,"regex_match":"^A"},
	"select":["`song`.`id`"],
	"static":false,
	"simple":true,
	"start":0,
	"offset":50,
	"use_pages":true,
	"use_alpha":true,
	"grid_view":true,
	"type":"song",
	"update_session":true,
	"sort":{"title":"ASC"},
	"total":1410
}

{
	"base":"SELECT %%SELECT%% FROM `song` ",
	"filter":{"tag":["59"],"regex_match":"^A",
	"catalog":null},
	"select":["`song`.`id`"],
	"static":false,
	"simple":false,
	"start":0,
	"offset":50,
	"use_pages":true,
	"use_alpha":true,
	"grid_view":true,
	"type":"song",
	"sort":{"title":"ASC"},
	"total":59,
	"join":{"100":{"`tag_map`":"LEFT JOIN `tag_map` ON `tag_map`.`object_id` = `song`.`id`"}}
}`

**Comment by DJ-SteffEN** [comment]
or is only “update_session”:true missing?

**Comment by lachlan-00** [comment]
i'm back today so i'll check it but it must be in that area specifically now

**Comment by lachlan-00** [comment]
it's weird, album is slow/breaking but then song and artist are quick/instant

**Comment by lachlan-00** [comment]
this is from an album
![image](https://github.com/user-attachments/assets/bc1fc7bd-35a7-48a2-8fed-a709885c450c)

this is from the tag page
![image](https://github.com/user-attachments/assets/968e7558-d86f-4006-988d-9e59160a1dd1)

the browse isn't set (0/uncached for tag) then a different browse loads the content which happens after the initial load

i'll look more but that's why they're not  working together

**Comment by lachlan-00** [comment]
i "Think" it's not loading the new items and is using cached data.

When i load a browse is should  be filtering the objects and not changing them but it's loading the cached object list for the data instead.
![image](https://github.com/user-attachments/assets/9a1ca861-57e3-45fb-9d5a-004d79148b8e)

So it's not the ajax/site but the browse/query class.

should be able to ID that this week but working away tomorrow

**Comment by DJ-SteffEN** [comment]
> So it's not the ajax/site but the browse/query class.
Yes, exactly, 
see my feeling -> in my previous post

**Comment by lachlan-00** [comment]
I think i found it. It's not in the filter it's in the re-browse after the filter.

Fix incoming

**Comment by lachlan-00** [comment]
i think i've got it now after 81fc194f6ad0becefb62ff397055cbd2d274e847

if you set a filter you need to also get the new objects

**Comment by lachlan-00** [comment]
although now it overwrites the other areas. artist browse now gets every album so there's more to do

![image](https://github.com/user-attachments/assets/7ede0ba4-2afc-4944-8a1e-0124856081c2)

**Comment by lachlan-00** [comment]
those browses are not meant to be filtered so ther'ye now hidden from showing the alphabet button.

i'm checking cookies in the show_obkjects function which i think now will allways update things correctly

**Comment by DJ-SteffEN** [comment]
Great, it works now.
But there is still a difference between filtering with and without genres.

Without genres:
if I only activate the filtering (see 2nd in the picture above) the default filtering is ^A and the list of objects is updated accordingly.

With genres:
if I only switch on filtering (See 2. in the picture above) the default filtering is ^A, but the list of objects is not updated.

Can you please have another look at this.
Thanks in advance.

**Comment by lachlan-00** [comment]
it shouldn't filter to A now it will default to just showing the alpha list

**Comment by lachlan-00** [comment]
i didn't like that it was changing something without someone actually pressing the button to filter.

i'm going to make preferences for showing the filters and grid view with preferences that update cookies when creating the user (at login)

**Comment by lachlan-00** [comment]
Ok i see, what's happening there is similar to the other area where the objects need to be pulled again. i'll set that now

**Comment by lachlan-00** [comment]
that's set with a65b69b571a6b960b87be352cfa04947946386ef

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

Thank you, but unfortunately nothing has changed for me.
Have I done something wrong (version 5.4.1), is it working for you?
I'll attach the file 'BrowseAjaxHandler.txt
[BrowseAjaxHandler.txt](https://github.com/user-attachments/files/17972374/BrowseAjaxHandler.txt)
'.

**Comment by lachlan-00** [comment]
you only set it on the true value missing `regex_not_match`

set it after the if/else and it will work

![image](https://github.com/user-attachments/assets/455ab153-e84f-4560-b8dc-1777dbed4e8c)


if you set it only for removal that's probably better. (You only want to refresh the page when you remove the alpha list)

![image](https://github.com/user-attachments/assets/3496f0f1-4f61-4927-ac40-18886bb70130)

**Comment by DJ-SteffEN** [comment]
Yes, thank you, it works now.
I had made a mistake, probably because of the differences in the version.

**Comment by lachlan-00** [comment]
that was an amazingly long disaster to get through. but at least that's fixed up a lot of browse and ajax problems.

**Comment by DJ-SteffEN** [comment]
Hello lachlan-00,

sorry to be a pain again.
I have just discovered that the filtering of the user list in the admin area is not working.
The alphabet appears and the list is also refreshed, but the content remains unchanged.
How much effort does it take to fix this?

![issue2](https://github.com/user-attachments/assets/f5fbc9b8-0e1b-4f63-933b-ba4a9255082c)

Kind regards
DJ-SteffEN

**Comment by lachlan-00** [comment]
depends on how the browse is created but should be able to work it out

**Comment by lachlan-00** [comment]
the query filters had % at the end making them invalid filters. seems to be okay once i've fixed that

**Comment by DJ-SteffEN** [comment]
Hi lachlan-00,

hm, which query filters do you mean and/or where can they be found?

Kind regards
DJ-SteffEN
