### ISSUE TITLE
Icons excesive large in dark mode

### ISSUE THREAD

**Issue by cquike** [ampache/ampache#4080]
## Description

I have updated to ampache 7.0.1 and the icons look very large (looks like they are displayed in original size) when the theme color is dark.

### Describe the bug

After the update to 7.0.1 the icons looked very large. When I changed the theme color to light then the icons where shown correctly. And when I changed back to dark the icons continued to be correct. So something while changing the  theme color fixed the issue.

I guess this is difficult to reproduce, but just wanted to report it.

**Comment by lachlan-00** [comment]
you're probably on cached CSS. the icons didn't exist and it seems like for a few people the browser cache hasn't updated

Clear cookies and data for the site and you'll be back to normal

**Comment by cquike** [comment]
Thanks! Indeed now it works.

**Comment by lachlan-00** [comment]
i put a note in the release page to say that this might happen
https://github.com/ampache/ampache/wiki/ampache7-for-users#material-icons-have-replaced-a-lot-of-the-old-png-files
