### ISSUE TITLE
Multi-Disc Album Subtitles

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#4081]
Been uploading quite a few multi-disc albums lately and noticed that the disc subtitles weren't being shown anymore on the `albums.php?action=show&album` page.

I checked my file tags and all of the discs had subtitles but were using the tag `discsubtitle` as tagged by MusicBrainz Picard.

I added new subtitles using the tag `subtitle` and, after a quick 'update from tags' for each album, all the disc subtitles appeared again on the web page.

Can we add the ability for both `subtitle` and `discsubtitle` tags to be recognised in cases like this?

Thanks...

**Comment by lachlan-00** [comment]
i don't have subtitle set as a tag in VaInfo but some other people are having trouble with this this week

uncomment the `//$this->logger->debug` sections to get data on the output tags for your file. (src\Module\Util\VaInfo.php)

just skip the first one that prints the raw tags, it's massive
```
//$this->logger->debug('RAW TAGS ' . print_r($this->_raw, true), [LegacyLogger::CONTEXT_TYPE => self::class]);
```

**Comment by rsinfotech** [comment]
I uncommented the debug sections related to my files (id3v2) and did another 'update from tags' via the web interface on an existing multi-disc album with `discsubtitle` tags set but not showing.

For each track I get this database update in the logs:
```
(Ampache\Repository\Model\Song) -> media-diff {"disksubtitle":"OLD: --> Hunters \/ Prelude to 'The Teds'"}
(Ampache\Repository\Model\Catalog) -> /mnt/ampachemusic/MP3Albums/The Residents - Gingerbread Man/16 - The Residents - Struggle.mp3 : differences found, updating database
(Ampache\Repository\Model\Tag) -> update_tag_list album: {24987}
```
The disc subtitles are then shown in the web interface.

So it looks like the `discsubtitle` tags are being picked up when I do an 'update from tags' via the web interface but not when initially adding the files as I usually do using: `cli run:updateCatalog ampachemusic -ceag`

Next time I add another multi-disc album with subtitles, I'll check the logs again.

**Comment by lachlan-00** [comment]
so song insert is missing?

I've done some tweaking onthat might need to do more.

**Comment by lachlan-00** [comment]
add debug to the insert function. i've put in disk subtitle. src\Repository\Model\Song.php

put it in with f051efdba05c9b156dba754d88aa8f30da0fea71

**Comment by rsinfotech** [comment]
Apologies for the delayed response, not uploaded any multi-disc albums with disc subtitles for a while.

So to test this, I deleted an existing album and added it again, after a clean, using the cli.

The debug shows it being read but it's still not showing in the web interface album view?

`
[System] (Ampache\Repository\Model\Song) ->     [disksubtitle] => Live at the Boathouse Norfolk, VA (7/21/1991)
`

I'm also getting a duplicate entry database warning after each track:

``
[System] (Ampache\Module\System\Dba) -> Error_query SQL: INSERT INTO `album_disk` (`album_id`, `disk`, `catalog`) VALUES(?, ?, ?); [25021,2,4]
``
`
[System] (Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '25020-2-4' for key 'album_disk.unique_album_disk'
`

It still picks up the subtitles perfectly when doing an 'update from tags' via the web interface.

**Comment by lachlan-00** [comment]
ah okay, so there is a problem with my disk check function then by the looks. i should be able to find that

**Comment by lachlan-00** [comment]
it's also missing the insert for the subtitle column entirely

**Comment by lachlan-00** [comment]
3fb120ad21f9bc54671cdb9a1befee1d1257c7bd should do that. it'll `replace into` the table and includes all columns which is the actual reason you're getting the error.

**Comment by rsinfotech** [comment]
That's cured it! :+1: 

All disc subtitles are now correctly displayed after adding muti-disc albums via the cli. No need to 'update from tags' to catch them anymore.

Great work and much appreciation for your dedication as always...
