### ISSUE TITLE
It is possible on open-license public servers to post a song without indicating a license

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#4087]
Hello, we spotted this on Dogmazic. One of our musician users have been able to add a song for which the license field is kept blank. Maybe this, is related to the user not choosing anything in the license combobox when uploading. In sites like our, choosing a license is, obviously, mandatory. This is almost certainly a new bug, otherwise in the 9.5 years of existence of our server, it would have been spotted many times before now. Sorry for not having the will of investigating more and really, surely, indicate here that it's the lack of license selection at the upload step that led to the absence of license associated to the track.

**Comment by lachlan-00** [comment]
i didn't think so, if licensing is enabled it will be included / 'mandatory'

![image](https://github.com/user-attachments/assets/4a27d088-b316-450b-966e-54a151af0572)

But it only checks for the data in the upload process

![image](https://github.com/user-attachments/assets/5e4d29bf-0583-4c75-8a49-0ea62967de8d)

The box should always select something though i don't think you can select nothing without deleting it from the html

I can set a check on that though. if licensing is enabled it should error out on upload if not present

**Comment by lachlan-00** [comment]
added in a fail if not sent and licensing is enabled here
73fa26673eadf9db35381e8c0609e760e7ae799f

**Comment by lachlan-00** [comment]
made mistakes in that, the better commit is 40e17ff2180a3191cced9db9646a27fafacd4ca8

```
                // Require a license with the upload if it's enabled
                if (AmpConfig::get('licensing') && !isset($options['license'])) {
                    return self::rerror($targetfile);
                }
```

![image](https://github.com/user-attachments/assets/fe409918-2fef-452f-8398-da65c9283634)

**Comment by shangril** [comment]
That's wonderful. Now it will be impossible to re-behave this way. Thank you.
