### ISSUE TITLE
Large black icons after 6 to 7.1 update

### ISSUE THREAD

**Issue by nelgin** [ampache/ampache#4089]
### Describe the bug
After updating from Ampache 6 to 7.01 using the ampache-7.0.1_all_php8.3.zip file, my icons look horrible.

### To reproduce

Update ampache 6 to 7.01

### Expected behavior

I should have regular sized icons I can actually see.

### Screenshots
![image](https://github.com/user-attachments/assets/3a350bb7-6179-4b38-9c74-1bd424ded6af)

## Environment

* Ampache version: 7.01
* Web server + version: Brave Version 1.71.121 
* Server operating system: Ubuntu 24.04.1
* Client operating system: Windows 10

### Client type

* Web

**Comment by mitchray** [comment]
Try clearing your browser cache

**Comment by lachlan-00** [comment]
This is definitly CSS caching, the rules didn't exist before as we didn't have any svg icons in 6

**Comment by nelgin** [comment]
I tried it on another browser I thought I hadn't accessed ampache on but I got the same issue so I didn't consider it a browser cache issue. When I looked this morning it had resolved itself so maybe it was. Sorry for the false alarm.
