### ISSUE TITLE
SQL query error when viewing an album

### ISSUE THREAD

**Issue by rsinfotech** [ampache/ampache#4093]
Since the latest develop pull, I'm getting the following SQL error in the logs whenever I view an album page:
```
(Ampache\Module\System\Dba) -> Error_query SQL: SELECT `song`.`id` FROM `song` WHERE  ORDER BY `song`.`track` ASC LIMIT 0, 50 []
(Ampache\Module\System\Dba) -> Error_query MSG: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY `song`.`track` ASC LIMIT 0, 50' at line 1
```
Page still displays ok with all tracks listed correctly.

**Comment by lachlan-00** [comment]
hmm, might be that rtrim i changed yesterday, there is an empty where or it's a browse that's empty and shouldn't be doing anything.

what page link is this on and album or album_disk? i can't see it on album or disk links so far

**Comment by rsinfotech** [comment]
This was when viewing #albums.php?action=show&album=

But just noticed it's also happening for all browse pages except for #browse.php?action=album_artist and no resuts are being returned for these?

**Comment by rsinfotech** [comment]
Rolling back to previous pull 1b23ee0ff gets rid of the warnings and all the browse pages are working again

**Comment by lachlan-00** [comment]
54a48acba27e273658a39d0571f29a7dacd5bef0 i need to keep the  space

**Comment by lachlan-00** [comment]
ah i know what it will be for you, you won't have catalog_disable or catalog_filter.

i think this will be covered now i've returned the space. i'll test

**Comment by rsinfotech** [comment]
Yep, that's fixed it, no error messages and all browse pages working again.
