### ISSUE TITLE
Multiple artists in groups or personnal projects

### ISSUE THREAD

**Issue by Aisyk** [ampache/ampache#416]
For now, there is no link between, for example, Paul Mc Cartney as solo artist and Paul Mc Cartney as former member of the  group Bealtes. If Ampache could class Artists like Paul Mc Cartney as former of Beatles group, when you search him, you could have both informations for his solo projects and group projects.
Some artists aren't members of groups, or they participate to anothers... I think it's important to follow artists.

**Comment by Phyks** [comment]
@anettles Looks like it is available: https://www.discogs.com/developers/#page:database,header:database-artist (see `members` in the response).

Same for musicbrainz (see https://musicbrainz.org/artist/b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d/relationships and "members" field). I'd rather use musicbrainz over Discogs for this purpose by the way.

**Comment by mitchray** [comment]
Closing due to time since last discussion, also I think the 'related artists' addresses this
