### ISSUE TITLE
A framework for unrecognized artists from musicbrainz or else...

### ISSUE THREAD

**Issue by Aisyk** [ampache/ampache#421]
Many artists don't use musicbrainz or huge databases like lastfm. They make music. I think i'll be great to have a free framework to add informations about theses artists, videos, or links...

**Comment by minnesotags** [comment]
Musicbrainz has a lot more info than you would think. As more people add to it, it will be even better. I have tons of obscure music and have spent a lot of time adding it to the database. Sometimes my submits have been rejected, which is dissappointing when I am holding the source CD in my hand, but overall, it is good.

**Comment by mitchray** [comment]
Closing due to time since last discussion
