### ISSUE TITLE
Fatal error..

### ISSUE THREAD

**Issue by Jahak** [ampache/ampache#422]
Hello dear developers Ampache. When installing Ampache I have a Fatal error:

Call to a member function quote() on a non-object in D:\Server\domains\site.ru\lib\class\dba.class.php on line 130

Software:
Operating System - Windows 7
PHP - 5.4.16
MySQL - 5.1.69

Please help fix this error.

**Comment by deragon** [comment]
I have the same problem with ampache-3.8.0-beta.  Shouldn't the fix be part of that release?  Running on Ubuntu 14.04 LTS Trusty Thar.

**Comment by deragon** [comment]
BTW, as a side effect, when the error occurs, the web page remains blank.  It would be great if an error page, with the full details of the errors, would show up.  But maybe I should open another issue to track that request.

**Comment by Psy-Virus** [comment]
Hey @deragon,
did you also try the latest dev build? 
> But maybe I should open another issue to track that request.
Yep, you should, with a reference to this issue here^^ Because, if it is a bug, it's a new bug on another version :)
And also you should enable the debug option in you ampache cfg and set it to level 5

Thank you :)
