### ISSUE TITLE
Docker package

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#425]
This past month several people was creating his own ampache-docker package:
https://github.com/ericfrederich/docker-ampache
https://github.com/velocity303/ampache-docker
https://github.com/cmehay/ampache_docker

Ampache project should have an official Docker package, and we should define how it will work. I'm a bit a newbie with Docker, any suggestion is welcome :)

**Comment by thoroc** [comment]
sorry to comment on an old issue but It might be easier to add the docker file to the project and use docker-compose.
