### ISSUE TITLE
web technology idea

### ISSUE THREAD

**Issue by meandor** [ampache/ampache#449]
Yesterday night I worked a bit more on my branch on a new UI and I got a tiny bit frustrated about how static and limited php can be regarding client side stuff.

Of course you can expand it with Javascript/jQuery and stuff, but there is always to some extend a lot of fiddling you need to do.

That increased the wish for angular.js support in ampache. That would mean a major Tech switch and a lot of work but also an easier programming experience and an easier to use user experience.

There are a lot of benefits you would get from using angular.js. The most prominent one I am thinking about is keeping parts of the website like a part where the player is persistent and switch out the rest of the content or other nifty UI effects.

Here are some demos for angular.js and PHP

http://www.angularcode.com/angularjs-datagrid-paging-sorting-filter-using-php-and-mysql/
http://www.angularcode.com/simple-task-manager-application-using-angularjs-php-mysql/
http://www.keyboardninja.eu/webdevelopment/a-simple-search-with-angularjs-and-php

So are there any people who would endorse that or can we have a general discussion about this?

**Comment by wagnered** [comment]
Gotta put in my two-cents worth.
I'm wondering how well using the Angular.js as a framework, will allow php modules to be integrated into the framework.  For example, the existing PHP Tmdb/Tvdb modules I've been working on would require a lot of work to implement in js. 

i can see using Angular.js as a toolkit for use in a  PHP based framework, I'm just wondering how easy it is to incorporate php modules into an Angular.js Framework.

I don't see how an Angular.js framework would be all that advantageous over a php  based framework as both run on the server. As Angular.js contains the tools to embed dynamic content into a view It would compliment a php based framework quite well.  The existing javascript code mystifies me to a large degree.  I can't imagine what an application implemented entirely in javascript would be like to debug. ( ; ' >

**Comment by arnaudbey** [comment]
Just to clarify, for what I've understood, Angular would be use to handle front-end, and that doesnt exclude the use of a PHP framework for the back end

**Comment by meandor** [comment]
correct

**Comment by Afterster** [comment]
Dead end as long no one will do it without breaking any features :smile:. 
Discussion should continue on #359.
