### ISSUE TITLE
UPnP discovery (missing)

### ISSUE THREAD

**Issue by SeregaPru** [ampache/ampache#461]
Now only UPnP notification broadcast messages are implemented, which can be send from special page or  script with cron.
But for proper work should be also implemented UPnP discovery,
when player send broadcast packages to all network devices and they should answer.
Not all (my) players can see UPnP server with only notification messages.

Suggestion:
Why not to develop special script (in /bin folder) that will realize simply socket server, it will listen for incoming discovery messages and answer them.
Also It could periodically send notifications (instead of current script, to have all the broadcast logic in one place/script).

I think I could try to make it.

**Comment by Phyks** [comment]
Hmm, not sure to fully understand the issue here.

Isn't it what is already done in [this function](https://github.com/ampache/ampache/blob/develop/upnp/find.php#L73)?

It does send a SSDP discovery to multicast address and listening for answers.

**Comment by SeregaPru** [comment]
Hi.
This function sent discovery by initiative of Ampache. So the Ampache is crying - "Hey, I'm here. Please everyone know about me."
But there is another side - when the remote player begins to work, it also sends discovery package to network: "Is anybody here?". And UPNP server responses: "Yes, I'm here. I'm server!".
And for the second function work, there should be some process that continuously listen to the network for such incoming discovery package.

**Comment by Phyks** [comment]
Oh, you mean when someone else is doing a discovery, Ampache should send a server message.

But isn't it the pupose of [this script](https://github.com/ampache/ampache/blob/develop/bin/broadcast.inc) calling [this function](https://github.com/ampache/ampache/blob/develop/lib/class/upnp_api.class.php#L70) to advertise on the network?

**Comment by mitchray** [comment]
Closing due to time since last activity
