### ISSUE TITLE
Prevent 'Various Artists' albums without MusicBrainz Id

### ISSUE THREAD

**Issue by hypfvieh** [ampache/ampache#462]
I got the following problem:
I have multiple albums with the same name than other albums of different artists.
All albums have nothing in common but the album name (no album-artist or other tag).

Ampache show those albums as 'Various Artists' albums, even if you just look for albums of a certain artist. This feature is somehow annoying and I'm looking for ideas how to get rid of this without tagging everything with musicbrainz Ids.

One idea would be to tell ampache to honor the directory structure.
The best way would be something like a placeholder/regex-aware pattern which you can configure in the catalog (so you can have different patterns per catalog).

In my case I have a very strict naming in the directory structure:
- All artists are sorted alphabetically (folders A-Z and @ for everything not starting with a letter).
- In the artist folder there is a folder for each album of that artist
- in some cases (multi disc albums) there are subfolders like 'Disc 1' and 'Disc 2'

So I'm thinking of something like:
    /my/path/to/music/.*/%artist%/%album%/{%disc%}

Where .\* is my folder A-Z
%artist% is placeholder for artist name
%album% is placeholder for album name
{%disc%} means use subfolder as 'disc'-tag if there is any subfolder

I guess the most difficult part is to deal with folder which only exists on certain albums (like multi disc albums). This will require some sort of 'smart' pattern. In my example above I would use the brackets {} to define something like 'use as sth if existing'. 

What do you think?
Any other ideas are welcome!

**Comment by luckydonald** [comment]
How do I get a MusicBrainz Id added for all my music in my library (on debian linux)? Is there a command line tool for that? Anyone did that before, and show me the commands/point me in a direction?

**Comment by SUTJael** [comment]
Hi @luckydonald,

That kind of question should go on [google discussion](https://groups.google.com/forum/?hl=fr#!forum/ampache) and not on any (closed) issue. Have a look to [beets](http://beets.radbox.org/) ;)

**Comment by lachlan-00** [comment]
I'm happy with the current grouping situation now this isn't really going to be a common issue now.
