### ISSUE TITLE
Write down in log file IPs of failed connections in order to use fail2ban

### ISSUE THREAD

**Issue by popindavibe** [ampache/ampache#470]
Hi there,
I just did a tiny modification in the code that I'd be happy to see in the master branch. In login.php, I changed: 
//debug_event('Login', scrub_out($username) . ' attempted to login and failed', '1');
For :
debug_event('Login', scrub_out($username) . ' From ' .  $_SERVER['REMOTE_ADDR'] . ' attempted to login and failed', '1');

That way I can apply a fail2ban filter on failed attempts to connect to Ampache.

In case some people are interested, it looks like that in /etc/fail2ban/filter.d/apache-auth.conf:
failregex = ^%(_apache_error_client)s user .\* (authentication failure|not found|password mismatch)\s*$
            From <HOST> attempted to login and failed

And in /etc/fail2ban/jail.local:
[apache-access]
enabled = true
action = iptables46-multiport[name=apache, port="http,https", protocol=tcp]
         mail-whois[name=apache, dest=root, sender=root]
filter  = apache-auth
logpath = /var/log/apache_/_access.log
          /var/log/ampache/ampache.log

**Comment by dhsc19** [comment]
@popindavibe 

I'm not able to get this to work.  I'm getting the following errors when I try to implement these into fail2ban:

ERROR  Failed during configuration: File contains parsing errors: /etc/fail2ban/jail.local
        [line 24]: '/var/log/ampache/ampache.log\n'

If I remove the /var/log/ampache/ampache.log line, I get:

ERROR  Found no accessible config files for 'action.d/iptables46-multiport' under /etc/fail2ban
ERROR  Error in action definition iptables46-multiport[name=apache, port="http,https", protocol=tcp]
ERROR  Errors in jail 'apache-access'. Skipping...

Can you help me with what I am missing?  Thanks.

**Comment by popindavibe** [comment]
Which version of fail2ban are you using? The config I pasted is for a patched fail2ban to support IPv6 banning (http://www.crazyws.fr/dev/systeme/fail2ban-et-ipv6-sur-votre-serveur-debian-squeeze-MG970.html). Maybe the current version integrated the patch, I haven't followed last releases.
Anyway it seems you don't use the patched version and your version does not declare any file in action.d folder named 'iptables46-multiport.conf' so you have to adapt it to your version. 
As a start you can replace :  
action = iptables46-multiport[name=apache, port="http,https", protocol=tcp]
         mail-whois[name=apache, dest=root, sender=root]
with : 
action = iptables-multiport[name=apache, port="http,https", protocol=tcp]
         mail-whois[name=apache, dest=root, sender=root]
Restart and see what happens.

Also the logpath parameter has to point to the path of your log of ampache (and no "\n" should be quoted)

**Comment by xekon** [comment]
The file log not includes the date, you cannot even use wildcard format for the log because fail2ban seems to only generate the file log when fail2ban is started/restarted.

I am looking for how to change the file to just ampache.log
