### ISSUE TITLE
Composer error on add to catalog

### ISSUE THREAD

**Issue by jcwmoore** [ampache/ampache#471]
I have noticed recently that some songs are not importing into my catalog.  after reading the log files i was able to work around this problem by blanking out the composer field in the mp3 file itself.  In windows media player and in rhythmbox the composer was labeled as "Unknown"

below is the relevant log section...  any thoughts?

[john](read) -> Starting work on 20-immortal-avenger.mp3 inside C:\inetpub\wwwroot\owncloud\data\john\files\music\two-steps-from-hell\archangel 
2014-09-21 13:57:39 [john](Memory) -> 6.25 MB 
2014-09-21 13:57:39 [john](vainfo) -> encoding detection: {"ASCII":4} 
2014-09-21 13:57:39 [john](vainfo) -> /(.+?)\/(.+?)\(.+?)\s-\s([0-9]+?)\s-\s(.+?)..+$/ matched  on files\music\two-steps-from-hell\archangel\20-immortal-avenger.mp3 
2014-09-21 13:57:39 [john](vainfo) -> Cleaning id3v1 
2014-09-21 13:57:39 [john](vainfo) -> Cleaning id3v2 
2014-09-21 13:57:39 [john](Dba) -> Error: ["HY000",1366,"Incorrect string value: '\xFF\xFE' for column 'composer' at row 1"] 
2014-09-21 13:57:39 [john](Dba) -> Error: ["HY000",1366,"Incorrect string value: '\xFF\xFE' for column 'composer' at row 1"] 
2014-09-21 13:57:39 [john](Dba) -> Error: ["HY000",1366,"Incorrect string value: '\xFF\xFE' for column 'composer' at row 1"] 
2014-09-21 13:57:39 [john](Dba) -> Error: ["HY000",1366,"Incorrect string value: '\xFF\xFE' for column 'composer' at row 1"] 
2014-09-21 13:57:39 [john](song) -> Unable to insert C:\inetpub\wwwroot\owncloud\data\john\files\music\two-steps-from-hell\archangel\20-immortal-avenger.mp3

**Comment by Afterster** [comment]
Any chance to send me this test file to me too? afterster@gmail.com
Thanks.

**Comment by Afterster** [comment]
Thanks for the file but same for me, no issue on catalog update. What is your ampache.cfg.php settings?

**Comment by jcwmoore** [comment]
Just updated to the latest development, still experiencing the issue.  links below are good for one week.

cfg
http://cloud.johnclaytonmoore.com/public.php?service=files&t=ab142419752b983c8c8bc0af35d59f2b

log file
http://cloud.johnclaytonmoore.com/public.php?service=files&t=5f3c8b359c0ddd0a3268e566a32afd42

**Comment by Afterster** [comment]
Thanks but still working on my side. Could be related to your php configuration. Could you copy/past your *Ampache Debug* page somewhere? Thanks.

**Comment by jcwmoore** [comment]
here's a saved snapshot of the Debug page.
https://cloud.johnclaytonmoore.com/public.php?service=files&t=e137b7f800b13cff187e2008cbae78b6

**Comment by Afterster** [comment]
Thank you for the debug page export but I'm sorry I cannot identify your issue.
Any other Windows user willing to test your files would be appreciated to at least reproduce your issue. Thanks guys.

**Comment by Afterster** [comment]
I will remove this from 3.8.0 milestone as it cannot be reproduced right now. I'm really sorry @jcwmoore but you will have to wait that a maintainer can reproduce your issue or found a fix by yourself :\

**Comment by jcwmoore** [comment]
Thanks for looking into it, if i can find the time i'll look into it but i
do appreciate your efforts on this.

**Comment by Phyks** [comment]
@jcwmoore Are you still experiencing the issue on latest `develop` branch?

**Comment by jcwmoore** [comment]
A few months ago I started self hosting my ampache on a Raspberry PI.  That meant changing from the Windows to Linux OS.  I am no longer experience this.  I don't think the behavior ever change but, with no one else reporting this, it isn't worth keeping open or around at this point.

**Comment by Phyks** [comment]
Ok. Anyone feel free to reopen with extra comments if experiencing this :)

**Comment by AshotN** [comment]
I have repeated the issue, but it wasn't on the latest version. Was on my fork, not sure if thats the issue. I'd be willing to 'share' the song if anyone cares to try.

**Comment by Phyks** [comment]
Maybe linked to https://github.com/ampache/ampache/issues/1271. I will try to have a look at it when handling this.

A song and an easy way to reliably reproduce it would help a lot :)

**Comment by mitchray** [comment]
Closing again due to inactivity, if anyone is experiencing this on current version please open a new issue
