### ISSUE TITLE
Cue sheet file support

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#483]
Cue sheet file (https://en.wikipedia.org/wiki/Cue_sheet_%28computing%29) support is interesting to improve catalog file type flexibility and better audio stream management (this kind of improvement will be also required for mkv files), even if not really requested by users right now.
Useful information on CherryMusic project which is almost ready to add this support: https://github.com/devsnd/cherrymusic/pull/457

**Comment by rubenhak** [comment]
Hi, are CUE files already supported in ampache?

**Comment by Afterster** [comment]
No it is not, neither the development started ^^.

**Comment by lachlan-00** [comment]
This one is something that i don't think will get implemented easily/soon unless someone wants to do it and make a pull.
