### ISSUE TITLE
Integration Questions

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#488]
Hey, 

Thanks again for awesome piece of software! 
Is it planned to have integration for:

- Discogs
- NoSQL DB (Mongo) :: *There is no plan for that and I believe there will never have*
- PostgreSQL :: *Dup #118*
- Google Drive
- s3 Amazon
- OpenStack (Swift)

Best,
-SR

**Comment by Afterster** [comment]
Discogs plugin just added.
Remaining points on the list is out of this repository scope (should be done as external plugin) or will not be done (changing the db to nosql... is just impossible without all refactoring).

**Comment by votacom** [comment]
ad PostgreSQL integration: this issue seems to have been ignored (#118 closed, #488 closed). Is there a way to reopen it?
MySQL, PostgreSQL, sqlite and others are just variants of relational databases, all speaking the same language (SQL99). Restricting ampache to MySQL is like restricting it to a certain distribution of GNU/Linux.

**Comment by danielcotton** [comment]
@votacom 

> MySQL, PostgreSQL, sqlite and others are just variants of relational databases, all speaking the same language (SQL99). Restricting ampache to MySQL is like restricting it to a certain distribution of GNU/Linux.

That's not true at all. If that were the case, you could just run Ampache on postgres without a problem.

Most modern RDBMSes extend SQL99 with extra functions/statements/language features/etc.

So it's nothing like restricting it to a certain distro; it's more like restricting it to glibc systems over the less-common libc implementations.

**Comment by Phyks** [comment]
There is a (somewhat long term) plan to rewrite Ampache using Laravel. Supporting Postgres will not be very difficult at this time and will most likely be part of the required features. 

With the current Ampache code, SQL queries are generated at hand and tightly bound to MySQL, this would just be way too much work to support Postgres, especially when we have other blocking bugs to fix. 

Of course, if anyone comes up with a PR to support Postgtres, I would be happy to review for merge :)
