### ISSUE TITLE
Download transcoded files

### ISSUE THREAD

**Issue by Kernald** [ampache/ampache#497]
Hi,
Sometimes I'm not on my computer, and I don't have a reliable internet access. I'd like to download an album for offline listening, but I don't have the required bandwith to download a full flac album. I couldn't find any way to achieve this currently. Does it sounds like a valid feature to you?

**Comment by mrpurplenz** [comment]
I also thought this would be useful but was knocked back by an earlier mod :(. Good to see positive ideas supported moving forward. :)

**Comment by lachlan-00** [comment]
i know this is many years too late but this is possible now in develop with the api and in the ui
