### ISSUE TITLE
Track data editing permissions questions

### ISSUE THREAD

**Issue by erikYX** [ampache/ampache#512]
Hi, I've been using Ampache to create an online service for our local music scene, primarily using the Upload functionality now to allow artists to submit their music. The issue that I'm finding is that if a user role is allowed to edit uploaded songs in System settings, they can edit all uploaded songs, not restricted to their own.This opens up data security problems if users can edit each other's tracks. I have /uploads in their own catalog with separate folders for each user. Are there some settings or permissions that would enable this? 

Also, have noticed that the cover art editor icon is showing up for all user groups, not just those with  editing permissions. and I'd like to restrict that either to only the album owner or specific roles. I know the upload module is fairly new, so I'm also willing to fork and hack the core for if anyone can point me in the right direction. Thanks!

**Comment by Afterster** [comment]
Looks fixed. Other upload user rights improvement will be handled on #388.
