### ISSUE TITLE
How to Improve Search Responce Time?

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#514]
Hello,

Search responce on large datasets seems to be slow. My collection consist of 1,000,000 tracks and 200,000 artist roughly. I'm the only one so far who is hitting database. And search time by any keyword (let's say Flashbulb) taking a bit longer then expected for single query via browser:

```
Anywhere: Queries:116 Cache Hits:0 | Load time:7.8917 
Title: Queries:84 Cache Hits:0 | Load time:0.6172
Artist: Queries:76 Cache Hits:0 | Load time:4.4393
Album: Queries:32 Cache Hits:0 | Load time:0.5123
```

Tables itself not seems to be too large:

```
+-------------------------------------+-------+-------+-------+------------+---------+
| concat(table_schema,'.',table_name) | rows  | DATA  | idx   | total_size | idxfrac |
+-------------------------------------+-------+-------+-------+------------+---------+
| amm.song                            | 0.90M | 0.16G | 0.32G | 0.48G      |    2.04 |
| amm.song_data                       | 0.90M | 0.02G | 0.01G | 0.03G      |    0.51 |
| amm.artist                          | 0.16M | 0.00G | 0.01G | 0.02G      |    2.57 |
| mysql.help_topic                    | 0.00M | 0.00G | 0.00G | 0.00G      |    0.04 |
| mysql.help_keyword                  | 0.00M | 0.00G | 0.00G | 0.00G      |    0.18 |
| amm.album                           | 0.00M | 0.00G | 0.00G | 0.00G      |    4.11 |
| amm.session                         | 0.00M | 0.00G | 0.00G | 0.00G      |    0.80 |
| mysql.help_relation                 | 0.00M | 0.00G | 0.00G | 0.00G      |    2.19 |
| amm.tmp_browse                      | 0.00M | 0.00G | 0.00G | 0.00G      |    0.31 |
| mysql.slave_worker_info             | 0.00M | 0.00G | 0.00G | 0.00G      |    0.00 |
| mysql.innodb_table_stats            | 0.00M | 0.00G | 0.00G | 0.00G      |    0.00 |
| mysql.innodb_index_stats            | 0.00M | 0.00G | 0.00G | 0.00G      |    0.00 |
| mysql.slave_relay_log_info          | 0.00M | 0.00G | 0.00G | 0.00G      |    0.00 |
| mysql.slave_master_info             | 0.00M | 0.00G | 0.00G | 0.00G      |    0.00 |
| amm.preference                      | 0.00M | 0.00G | 0.00G | 0.00G      |    1.57 |
| amm.tmp_playlist                    | 0.00M | 0.00G | 0.00G | 0.00G      |   49.23 |
| amm.user_preference                 | 0.00M | 0.00G | 0.00G | 0.00G      |    2.93 |
| amm.access_list                     | 0.00M | 0.00G | 0.00G | 0.00G      |   39.72 |
| mysql.proxies_priv                  | 0.00M | 0.00G | 0.00G | 0.00G      |    3.69 |
| mysql.db                            | 0.00M | 0.00G | 0.00G | 0.00G      |    5.82 |
+-------------------------------------+-------+-------+-------+------------+---------+
20 rows in set (0.01 sec)


```

I'm using 
`Ampache 3.7.0, mysql  Ver 14.14 Distrib 5.6.17, PHP 5.4` on 
`2 GHz 4 cores Intel Core i7, 8 GB 1600 MHz DDR, SSD drive`

How may I improve search response? Out-of-the-box db indexes on the critical fields of above tables seems to be in place. Should I try table partitioning? Suggestions are more then welcome!

Thanks

**Comment by ricksorensen** [comment]
I to have seen the longer search times on the database.  I have about 9000 songs, 800 albums, and badly mangled tags on many of the songs.  I use the random playlist generator using a base smart playlist and it takes 15-30 seconds to generate a random playlist of 20 songs.  Prior to the 2014 versions this used to be very fast- measured by the display time for the generated playlist.

**Comment by Afterster** [comment]
I cannot reproduce your issue. Do you have more information about your smart playlist creation (parameters)?
You tried with develop branch right?

**Comment by ricksorensen** [comment]
Yes- I am using the development version pulled from git.  The numbers below
are from a "git pull" version done Feb 11 in the morning (TZ = CST = GMT-6)

I just tried an advanced random generation with:

Count=20, no conditions:
... ~1s for generated list to appear

Count=20
Condition 1: Tag does not contain holiday
... ~1s for generated list to appear

Count = 20
(Match all rules)
Condition 1: Tag does not contain holiday
Condition 2: Tag does not contain christmas
... ~10s for the generated list to appear

Count = 20
(Match all rules)
Condition 1: Tag does not contain holiday
Condition 2: Tag does not contain christmas
Condition 3: Tag does not contain child
... ~23s for the generated list to appear

The smart playlist I used matches the last (3 condition) sample- The 3
conditions should eliminate about 15% of the song titles.

I am not very skilled with databases- but  releases around 2013 vintage did
not show this slow results.

Rick Sorensen

On Wed, Feb 11, 2015 at 11:44 PM, Afterster <notifications@github.com>
wrote:

> I cannot reproduce your issue. Do you have more information about your
> smart playlist creation (parameters)?
> You tried with develop branch right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/514#issuecomment-74020960>.
>



-- 
Rick Sorensen
rick.sorensen@gmail.com
651-470-5511

**Comment by CountMurphy** [comment]
Overall the search is speedy, except when searching by song title. Searching by title takes about a minute to show me any results. Hitting the database directly using "select title, album from song where title like '%SearchTerm%';" brings me the results instantly.

**Comment by mitchray** [comment]
Closing due to time since last discussion
