### ISSUE TITLE
Message of the day on home page. enhancement!

### ISSUE THREAD

**Issue by jlz13fr** [ampache/ampache#526]
I know it's possible to let a message at the login form. But  it could be fine to let this message (if wanted) on the home page. And the ability to create, modify or validate or not this message in tools menu. see my pictures files.
your opinion?
regards,

![capture0](https://cloud.githubusercontent.com/assets/7567861/4748455/b6bc5810-5a70-11e4-9c4a-e3a10b564667.PNG)
![capture1](https://cloud.githubusercontent.com/assets/7567861/4748458/bddd4780-5a70-11e4-9e19-06a9f7d5c2bb.PNG)

**Comment by Afterster** [comment]
Message of the Day was added as an optional homepage plugin.
