### ISSUE TITLE
Musicbrainz button

### ISSUE THREAD

**Issue by anettles** [ampache/ampache#536]
I love having the buttons for Google, Wikipedia, and LastFM.  It would be a really nice feature if there were also a Musicbrainz lookup button.  One for Discogs and Amazon would be cool too.  Discogs has a lot of liner notes not found elsewhere and this would be easier to implement than any kind of metadata integration.

**Comment by Aisyk** [comment]
Hi ! Some libre services must be present on this area :
librefm
duckduckgo instead of google.

Or an interface to configure theses buttons to place every thing we want to search for in relation of this area ?
