### ISSUE TITLE
A switch for maintenance mode with custom message

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#545]
I think the title says what is meant but for the form^^

I think it would be nice if a maintenance mode could be added where only admin stuff have access and other users where redirected or otherwise informed about for example how log it takes or why the site isn't accessible.
In options it could be done with a bigger text field where the admin have the possibility to also use html for linking a sad-face-smiley-picture or something what also is displayed on that message page. :-)

But maybe it should be done after #535. That means, if you have the intention to do it :-))

**Comment by Afterster** [comment]
A short maintenance mode support was added.
To go to maintenance mode, just create a *.maintenance* file in your Ampache root directory. A sample *.maintenance.example* is provided.

This maintenance mode avoid **all** access including admin (like Workpress do) but scripts likes those located in bin/* will still work.

**Comment by Afterster** [comment]
Ok I'm closing this. Current .maintenance file should be enough for Ampache.
Feel free to comment if you don't agree.
