### ISSUE TITLE
Multi title editing

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#547]
Since Tagging is a very complicated issue and music is actually being imported from so many sources i found difficult to update large libraries by editing songs one by one. 
A multi title editing will be very useful in cases where all album data is missing, for example.
![screen shot 2014-10-31 at 08 27 50](https://cloud.githubusercontent.com/assets/7412863/4859958/60f6de96-60f1-11e4-838d-267652af6794.png)

**Comment by lachlan-00** [comment]
I don't want to support large editing operations in Ampache, it's better to use a proper tagging application like picard.
