### ISSUE TITLE
User Upload Improvements

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#549]
Hey there,

Few improvement requests for closed **User Uploads** feature  [ #132 ]

[ **1** ] It would be good not to allow users to upload the tracks, which are already in the database, unless bitrate is higher. 

Straight bitrate comparison will not be workaround here, since track length playing 2nd key role in the track fulltiming. Sort by size may be quick workaround here, since `size` consists of `bitrate` and `length` variables. Or sort by bitrate 1st and by length after.

[ **2** ] UI giving back to the user successful upload for the files which actually were not uploaded (non-music file types) and for the tracks which were uploaded already by the user earlier and thus were not reuploaded.  This is something easy to tackle, i believe.

Thanks!

**Comment by Afterster** [comment]
First implementation with be816474f64ac047ff5d49a71c82020767c748f3.
It's a simple one, based on song mbid, or song title + track + album + artist.
This assume song metadata are not malicious from users.
