### ISSUE TITLE
Stream to broadcast address

### ISSUE THREAD

**Issue by powerpaul17** [ampache/ampache#550]
Hello! Firstly I would like to congratulate on this wonderful piece of software, thank you very much.

There is one thing I am really missing: I am looking for a way to simply play the current song in the web interface to a simple broadcast address. I would try to help implementing this functionality but I have no idea where to start.

**Comment by poshwosh** [comment]
A bit of a late reply, but what is the alternative you found that satisfied your needs? I'm struggling to get the broadcast function to my liking.

**Comment by powerpaul17** [comment]
Actually I was not able to achieve exactly what I wanted. One possibility I'm exploring right now is a solution combining "jackd" and "jacktrip". But it requires the start of the "jackd" daemon on both sides and uses a lot of bandwidth. I originally was looking at something like Apple's "Airplay", just an open source equivalent.
