### ISSUE TITLE
Update search.php to search rule_1 types when no type is specified

### ISSUE THREAD

**Issue by eephyne** [ampache/ampache#551]
I don't know if this wanted,forgotten things or anything else but when I search for album terms It return me a list of tracks (with the good matching album). (I'm talking of the basic search at the top, next I can of course select album and determine my album search in the search page (damn that's a lot of search))

It surely can be a result expected in some cases but I think it's more human understandable than when we search tracks it show tracks and when we search album, it show albums (and same for artists)

**Comment by lachlan-00** [comment]
I see the rule_1 type should be used to direct those specific searches

anywhere/titles = song, the rest are specific types

```
<form name="search" method="post" action="https://music.com.au/search.php?type=song" enctype="multipart/form-data" style="Display:inline">
        <input type="text" name="rule_1_input" id="searchString" placeholder="Search" class="ui-autocomplete-input" autocomplete="off">
        <input type="hidden" name="action" value="search">
        <input type="hidden" name="rule_1_operator" value="0">
        <input type="hidden" name="object_type" value="song">
        <select name="rule_1" id="searchStringRule">
            <option value="anywhere">Anywhere</option>
            <option value="title">Titles</option>
            <option value="album">Albums</option>
            <option value="artist">Artists</option>
            <option value="playlist_name">Playlists</option>
            <option value="tag">Genres</option>
                            <option value="label">Labels</option>
                                        <option value="missing_artist">Missing Artists</option>
                    </select>
        <input class="button" type="submit" value="Search" id="searchBtn">    </form>
```

**Comment by lachlan-00** [comment]
this is now part of a2a5d10b4

i didn't realise how much this annoyed me until i read this issue.
