### ISSUE TITLE
Can't load songs via Android

### ISSUE THREAD

**Issue by MissingNoIOI** [ampache/ampache#565]
Hi, 

I just encountered the strangest error. I've been using Ampache happily for around a year now, mainly with the Subsonic Backend and an Android Client. I haven't been using it lately and wanted to use it again now, but for some reason the songs don't load. No matter what I use: Subsonic Client, Ampache Client, Website, it connects fine with the server, I can see Albums, Coverart, etc., but when I actually try to play a song it gets added to the playlist but it won't download the song.
The strange thing is that it works fine from my laptop, with the website as well as a client. The error has been reproducible with 2 Android devices and to be frank I'm all out of ideas by now, since it worked fine just a few months ago.

Btw my ACL are all set to allow everything from everywhere

**Comment by Afterster** [comment]
Client side issue. Closing this.

**Comment by rene98c** [comment]
i had problem playing with subsonic android app, changed output encoding from mp3 to ogg and voila

**Comment by Cqoicebordel** [comment]
Got the same issue when upgrading from Ampache 3.6-alpha6+FUTURE to Ampache 3.8.3-develop, so I'll share my findings, in case it might help somebody : 
In 3.6 I had the "not enough data" issue, so I upgraded. And everything worked nicely with 3.8 and the Android clients (Amdroid, Lullaby...) *except* the playing.

Turn out that the 3.8 instance sent in the XML_Data::song the _local_ domain name of the instance, domain name that wasn't advertised/discovered at all (it wasn't "localhost", but could have been). So, indeed, Android couldn't find the songs, as the domain name used was unknown to the device.
I could have fixed it by changing the hosts file on my device, but I choose to change the config of Ampache to set the 'http_host'.

But shouldn't the host be determined automatically from the client request ?
