### ISSUE TITLE
Google drive remote catalog

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#580]
Hello,

It would be great to have Google drive as remote catalog. 

Thanks!

**Comment by RoelofNutbeij** [comment]
I agree. Something like http://www.drivetunes.org

**Comment by Afterster** [comment]
If not mounted as a file system, this should be done as an external catalog plugin on Ampache and will not be available in base.
Anyone willing to develop it, please use https://github.com/ampache/ampache/blob/develop/modules/catalog/remote/remote.catalog.php as example.
