### ISSUE TITLE
Song Details - Split file path/name and add catalog

### ISSUE THREAD

**Issue by minnesotags** [ampache/ampache#597]
On 3.8.0-Develop, the text from long file names gets overlapped in the song details because it includes the entire directory path of the catalog. This made me think what is shown in that field should get changed and another field should be added. The filename field should only have the actual file name in it. There should be another field for "Catalog" which shows the catalog name, so that you know what catalog the song is stored in. If you want details on the path to the catalog, that is already available in the "Show Catalog" page.

**Comment by Afterster** [comment]
Wordwrap on filename was recently added on current UI.
