### ISSUE TITLE
Subsonic Client /Dsub Bookmark Issue

### ISSUE THREAD

**Issue by cloudcoder2** [ampache/ampache#601]
Hi 
I tried with subsonic official client & Dsub to bookmark.
But its not working .

Thankyou

**Comment by daneren2005** [comment]
I hate that Github doesn't seem to have any nice way to see tickets you talked in without explicitly going to look for them.  I don't see much value in chat, but bookmarks can definitely be nice.  If anyone listens to Audio Books or anything else long, being able to mark your place is nice.  I also use it to mark my place in a album or artist.  For example I will start all of Metallica, set a bookmark, then go back and press play on Metallica and DSub will ask if I want to resume where I had last left off.

**Comment by Afterster** [comment]
Ok, I will set it to enhancement then. Thanks for giving your inputs.

**Comment by Afterster** [comment]
Just added :).
