### ISSUE TITLE
Webplayer does not appear with SSL proxy

### ISSUE THREAD

**Issue by Dual-Boot** [ampache/ampache#613]
Hi,

 I found this bug with FireFox 33/34 .
- My Ampache is setting without force_ssl, my server is behind an Apache Proxy with SSL enabled (self signed certificate)
- go to https://myampache.tld => FireFox warned about mixed-mode content
-  disable the protection (little shield icon) => the web page refreshes
- log into with credential => home page with  FireFox warned about mixed-mode content
- disable the protection (little shield icon) => the web page refreshes

At this moment I am still navigating with SSL.
- Try to play something, nothing happens

 If I enable force_ssl I do not get this problem.

 Regards,

**Comment by Afterster** [comment]
Any new @Dual-Boot? I really believe it is fixed in develop.

**Comment by Afterster** [comment]
Any update @Dual-Boot?
If this is not valid anymore, you should close it. Thanks.

**Comment by Afterster** [comment]
Without the appropriate test I assume this is fixed in develop branch. Feel free to comment for reopen if you still have an issue.

**Comment by Dual-Boot** [comment]
Hi,

 Sorry to be late. I have upgrade to the stable release.
I have checked and it is OK. When you set ssl to true and with http and https and with no redirect directive, the webplayer runs well.
 Is it possible to have http and https working separately ?
With ssl enable, it is impossible to run http, it automaticaly redirects to https.

 Regards,

**Comment by Dual-Boot** [comment]
I understand a little more.
For the login url, it is forced into https but after, when you change in the url https to http, nothing works.
The redirect is only for the login URL.
When I use FireBug with HTTP (after login), the problem seems to be linked to Cross-Origin Request which does not allow https request to https://myampache/index.php#browse.php?action=album from http://ampache/index.php#browse.php?action=album
