### ISSUE TITLE
Feature request: Democratic play with more rules, for example cooldown on artist

### ISSUE THREAD

**Issue by fre-ber** [ampache/ampache#617]
I would love to see a more flexible system for track selection in Democratic play. I am talking about when there are no votes and it selects songs from the base playlist. 

Today it has a cooldown period that has to run out before that exact track is played again. I would like to be able to add more constraints such as a cooldown period for the artist and possibly other parameters such as "containing the same tags", "containing tag x", "not containing tag x", "year y", et.c.

If the generic, multi-rule system is too complex, a single cooldown for same artist would go a long way.

With some assistance I might be interested in actually helping to code this myself, but I would probably need a bit of encouragement to try.

**Comment by Afterster** [comment]
This looks complicated. Shouldn't reuse the 'search' engine for that instead?

**Comment by fre-ber** [comment]
Maybe, I haven't really looked into the capabilities of the search engine. The key here is that it needs to be able to access the history log and allow multiple rules for matching.

The idea is to more or less make up a "format" of a jukebox radio station. For this you need the capability of setting up rules that make it play, say three songs of category A, then a jingle of category B, then a "podcast" of category C, a station ID of category D, a jingle of category E, five songs of category F and so on. Each of these categories would, in my example be defined by a TrackSelectionRule object and the complete "format" would be defined by a TrackSelectorRuleSet object.

Utilising the search engine changes the TrackSelectionRule to a search string and the relational logic becomes an evaluable expression. I like this idea. It might make it a little bit more difficult for some people to configure, but it makes the storage and evaluation much, much simpler.

In addition, it might be possible to re-use the playlist construct - if an entry in a playlist could be a search expression, or better yet, a named search expression (stored in a separate list), you have the radio station "format" in a playlist.

Thoughts?

**Comment by Afterster** [comment]
I'm not a big fan of this request which will add too much complicate stuff on Ampache and I still believe Search is enough here. @SUTJael @fre-ber?

**Comment by SUTJael** [comment]
Well I like the idea of adding more rules for democratic playlists without votes but, like you, I'm not sure of the implementation. Today adding too complicate process just for that feature would be useless as democratic is not the top most feature used in ampache. I would let it opened but wait for more "+1" votes on that request.So no plan for future milestones and we may create a new tag "Submission to votes" :)

**Comment by Afterster** [comment]
Waited enough :).
