### ISSUE TITLE
Genre being separated into multiple tags for mp3s

### ISSUE THREAD

**Issue by bliptec** [ampache/ampache#628]
I just recently set up ampache, and it seems like every mp3 file that I import has its genre separated into different tags for each character (for example, Electronic became the tags c, E, i, l, n ,o, r, t). As far as I can tell, the problem is that the data is being read in as 8 bit values, but all of the mp3 tags are storing the genre as 16 bit values. When ParseID3v2GenreString gets the genre info, it reads in the first 8 bits of each character, which almost always is NUL, and treats that as a delimiting character.

**Comment by SUTJael** [comment]
That was I was thinking by adding the array parameter ;) With that list we can provide (by default) standard delimiters and let users adding their owns. The parameters should also be checked in the defined order.

**Comment by lotan** [comment]
@SUTJael: I've looked into the getID3 code and I think that this is the crucial point:
https://github.com/ampache/ampache/blob/develop/modules/getid3/module.tag.id3v2.php#L678
I suggest following that advice by implementing additional separator splitting using the separator array you've suggested. But we should do that on top of getid3s processing and not on the raw strings.

**Comment by SUTJael** [comment]
What do you think when you say "on top of getid3s"? From my point of view we should do the following:
- Parse with getid3
  - If result array contains 2 or more items, we're good, a null separator has been found.
  - If array contains only 1 item (should be the raw string like "my tag//my 2nd tag", we loop in parameters until we find more than 1 item or until nothing has been found.
Parameters may have by default values ["//", "\\", "/", "\"]. With the "AC/DC" example, of course it would be splitted into "AC" and "DC" but there's no magic :) (and I never had any tags with that kind of syntax until now).

**Comment by lotan** [comment]
I meant that we should do any additional delimiter processing on ```$tags['genre']``` (which is parsed by getid3) instead of ```$_raw['id3v2']['TCON']```.
Other than that, your plan sounds good.

**Comment by SUTJael** [comment]
Do you want to take care of that?

**Comment by lotan** [comment]
Well, as I said, I don't know phps really, so what I could come up with might be less than stellar, but I'm certainly willing to give it a try, provided that you have a look at it afterwards.
Should we consider the additional delimiters only for genres or should we consider them for all ID3v2 tags (AC/DC is obviously an artist)?

**Comment by webpeon** [comment]
I would only do it for Genres.   Doing it for all fields may cause a lot of other issues.

**Comment by SUTJael** [comment]
@lotan Yes only for genres

**Comment by Afterster** [comment]
Done thanks to all contribution few days ago. Closing this.
