### ISSUE TITLE
Feature request: Play Next

### ISSUE THREAD

**Issue by tan-ce** [ampache/ampache#635]
I have been searching for it, but I've not been able to figure out how to "play this song next". It should work exactly like "play last", but it would insert the song immediately after the currently playing song.

If this is something that isn't implemented yet, I can code and am willing to try implementing this myself. I just wanted to get opinions, especially from the project maintainer, as to how this would best be implemented. 

Currently I'm thinking of adding another icon beside "Play Last".

**Comment by Afterster** [comment]
Your PR is merged thanks. @SUTJael you can improve icons if you want :)
