### ISSUE TITLE
Web player keyboard controls dysfunctional

### ISSUE THREAD

**Issue by mcladyz** [ampache/ampache#636]
Web player keyboard controls for previous, next, play/pause) don't work anymore. This is a [bug]( https://github.com/happyworm/jPlayer/issues/283) in jPlayer.

**Comment by SUTJael** [comment]
@mcladyz Any chance to revive your question in jPlayer? (at least to have a first response)

**Comment by mcladyz** [comment]
Done

**Comment by SUTJael** [comment]
@mcladyz, it seems that default binding keys have changed:
``p play/pause toggle``
``f full/restore screen toggle``
``m mute/unmute toggle``
``, decrease volume``
``. increase volume``
``[ previous item (playlist)``
``] next item (playlist)``
Have a look and close this when confirmed ;)

**Comment by mcladyz** [comment]
Yeah, I misunderstood how ARIA shortcuts should work. This issue can be closed.
