### ISSUE TITLE
Update downloads only the next commit

### ISSUE THREAD

**Issue by mcladyz** [ampache/ampache#637]
Pressing the "Update" button (To update Ampache) updates Ampache to the next commit version. Is this the intended behaviour? Shouldn't the update download the **latest** commit version instead?

**Comment by mcladyz** [comment]
This is what git pull return when I'm on commit 22c6ea6b60cf3c16ed86cb67eb55d79c5aee9291

`$ git pull`
`Updating 22c6ea6..cb9062c`
`error: Your local changes to the following files would be overwritten by merge:`
`        lib/class/plex_api.class.php`
`        lib/class/vainfo.class.php`
`        modules/getid3/getid3.lib.php`
`        modules/getid3/module.audio-video.quicktime.php`
`        modules/getid3/module.tag.apetag.php`
`        modules/getid3/module.tag.id3v2.php`
`        modules/getid3/write.id3v2.php`
`        plex/web/init.php`
`        server/search.ajax.php`
`        templates/show_searches.inc.php`
`        templates/show_shares.inc.php`
`Please, commit your changes or stash them before you can merge.`
`Aborting`
`$`

**Comment by SUTJael** [comment]
Well like it's written: you have modified some files so git is asking to commit first your changes before updating the repo. To reset your repo just execute the following commands:
``git fetch --all``
``git reset --hard origin/develop``

**Comment by Psy-Virus** [comment]
`<git reset --hard HEAD>` is also possible, from within the repo. Then it also resets to the last pulled commit. :-)

**Comment by mcladyz** [comment]
Hmmhhh....I reseted my copy to HEAD and ran the update in the UI again. It fetched only the next commit. 

However, executing `git pull` fetched all the remaining commits.
