### ISSUE TITLE
Limit Access to artists by user or group.

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#639]
I would like a way to exclude or include certain artists from certain accounts?  My kids asked me to put Ariana Grande on the ampache server.  Given my choice, I would prefer to set them up with their own userIDs and have Ariana Grande only available for their accounts and not mine.

This would also allow music with explicit content to filtered out from child's accounts.

**Comment by eyeke04** [comment]
Hello please I'm new to ampache. I just installed ampache 3.7.0 on my web server but I can't find how to add music to it or setup other accounts. Please can you walk me through it!

**Comment by mcladyz** [comment]
Does this relate to #308 techinally? Could they be added to 3.9.0 milestone?

**Comment by Afterster** [comment]
Yes, thank you for noticing the duplicate. Closing this, please continue the discussion on #308.
