### ISSUE TITLE
Add ability to sort by original release date

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#640]
I recently got a bunch of remastered older albums. When they get tagged from Musicbrainz, the date tag show the year the remaster was released, with another tag, Original Release Date, indicating when the album first came out.  I'd love to have the option to sort by original release date.  I like the idea of having some indicator of when an album was released, so I know which remaster I am dealing with, since some albums have been remastered more than once.  But I would prefer to sort by the original release date.

**Comment by usox** [comment]
Duplication of #2712, will be discussed in there.
