### ISSUE TITLE
Version 3.8-development Menu not working with Firefox browser (Win and Linux) 

### ISSUE THREAD

**Issue by essagl** [ampache/ampache#642]
When i try to select any of the menu entries in Ampache 3.8-develop version using Firefox Browser, nothing happens. The JavaScript console displays following error: 

TypeError: Event.stopObserving is not a function
Event.stopObserving(source, 'click', function(){ ajaxPut(url, source); });

The menue works as expected in Chrome Browser.

**Comment by Afterster** [comment]
Did you try to clean your cache?

**Comment by essagl** [comment]
No

**Comment by essagl** [comment]
OK you're right - CTRL-F5 fixes the problem for now.

**Comment by essagl** [comment]
Thanks for your quick response :-)
