### ISSUE TITLE
order of languages dropdown

### ISSUE THREAD

**Issue by brownl** [ampache/ampache#644]
It doesn't seem like there's any order to this menu. I was thinking of ordering them alphabetically - would that be OK?
![Dropdown menu](http://i.imgur.com/giSnaex.png)

**Comment by Afterster** [comment]
Yes :)
You should do it on get_languages() function in /lib/general.lib.php file I believe. Thanks.

**Comment by brownl** [comment]
Thanks, I'll have a look tomorrow. ---- On Fri, 02 Jan 2015 22:02:10 +0000  Afterster<notifications@github.com> wrote ----Yes :)You should do it on get_languages() function in /lib/general.lib.php file I believe. Thanks.—Reply to this email directly or view it on GitHub.

**Comment by brownl** [comment]
Created PR #650
