### ISSUE TITLE
Subsonic clients don't work with rewrite rules described on docs.

### ISSUE THREAD

**Issue by FoxBuru** [ampache/ampache#648]
When using the suggested config on Nginx for "play" songs, subsonic clients doesn't work properly. Adding a rewrite rule could help them:

```nginx
rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
```

**Comment by Afterster** [comment]
Indeed this is related to latest enhancement on Subsonic API. I updated the wiki with this new rewrite rule for Nginx.
Thank you!
