### ISSUE TITLE
Waveform not working due to " in_array('transcode', $valid_types)" test.

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#653]
Hi there,

maybe I have something misconfigured, but I can't get the waveforms to show up.

However, if I comment out the test below in lib/class/waveform.php it works.

 if ($transcode_cfg != 'never') { // && in_array('transcode', $valid_types)) {

...

The $valid_types variable contains "Array" in my case all the time.  If I remove it as part of the check the waveform renders fine.

Is this a code issue or config issue?

**Comment by Afterster** [comment]
I believe it's a config issue. You should setup transcode settings for your file format (ex: `transcode_mp3 = allowed`) as 'allowed' at least and it should work.
Could you confirm?

**Comment by florihupf** [comment]
Indeed, I had transcode_mp3 disabled (I thought transcode_wav would be the
right thing), d'oh.

However, it still doesn't work.  It still says "transcode settings to wav
required" in the debug log.

Attaching my config, surely this must be a noob mistake. :(

Thanks btw for all your support!

**Comment by Afterster** [comment]
You should copy/past your setting on pastbin instead attached to your email.
Anyway, check that `transcode_cmd` and `encode_args_wav` are configured

**Comment by florihupf** [comment]
They are  both configured like this:

transcode_cmd = "ffmpeg"
transcode_input = "-i %FILE%"
encode_args_wav = "-vn -b:a %SAMPLE%K -c:a pcm_s16le -f wav pipe:1"

So I think it should work.  What made me suspicious is the fact that the
$valid_types comes back as "Array".

Also, will use pastebin next time. Sorry for that.

**Comment by Afterster** [comment]
Ok. Please copy/past your config to gist or pastbin so I can take a look.

**Comment by florihupf** [comment]
Here you go: http://pastebin.com/KCK7VuvF

**Comment by Afterster** [comment]
Looks fine to me, are you sure your files are mp3?
Also, could you check on web interface your `Transcoding` setting on Admin (or user preference) => Server Config => Streaming?

**Comment by florihupf** [comment]
Ah, dang it.  Of course it was the ServerConfig setting. *embarrassed"*
