### ISSUE TITLE
Social feature broken in recent development tree

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#656]
Hi there,

I am using latest and greatest of the development tree.  I love the "social feature".  However, as of recently when I click the comment bubble the text entry field has gone missing and I can't post any comments on a song anymore.

**Comment by brownl** [comment]
could you give a rough estimation of when this became an issue?

**Comment by florihupf** [comment]
It was working in the last officially released version (I think 3.7.0).
When I updated to the dev version about a month ago it wasn't anymore.

Thank you for taking a peek!

~ Florian

**Comment by brownl** [comment]
okay, the issue is in /modules/jquery-mediaTable/jquery.mediaTable.css, line 69:

    (68) .activeMediaTable th, .activeMediaTable td {
	(69)    display: none;
    (70) }

With that rule disabled, the input box renders fine. does anyone know why it is here?

**Comment by brownl** [comment]
Created Pull Request #659

**Comment by florihupf** [comment]
Thank you!
