### ISSUE TITLE
Automatically populating $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by GieltjE** [ampache/ampache#660]
The use of $HTTP_RAW_POST_DATA is deprecated in php 5.6+, without always_populate_raw_post_data set to -1 in the php.ini file the sidebar fails to work properly (because a deprecation warning is echoed into the ajax response).

**Comment by SUTJael** [comment]
Thanks, I just found an interesting [article](https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/) talking about that. It seems that setting ``always_populate_raw_post_data`` to ``-1`` is the only fix right now...

**Comment by GieltjE** [comment]
I guess at least a warning message should be shown if it isn't fixed in the next release, as php 5.6 is getting rolled out with default updates a lot of people will have their installation fail.

If I understand the post correctly setting a mime type with the requests should fix the whole issue (our server runs a lot of other json/ajax requests without problems).

**Comment by Afterster** [comment]
Thanks for pointing this out, interesting indeed.
But if I understand correctly we should only get this data in our case when sending ajax request with custom content type ($HTTP_RAW_POST_DATA is already replaced by php://input here).
Sidebar loading and other ajax stuff post requests are using default content type which should be "application/x-www-form-urlencoded; charset=UTF-8". Do you see any other reason why you get this warning?

**Comment by GieltjE** [comment]
The response content type from my server is: "text/html; charset=UTF-8" for some reason, tried reproducing it on a debian server with the same php version (5.6.4) and it just worked.

**Comment by Afterster** [comment]
I'm not sure we can do anything here, what do you think @GieltjE?

**Comment by GieltjE** [comment]
Afterster, I also agree, my server is refusing to give me any reasonable debug info and I cannot reproduce it on other servers.
