### ISSUE TITLE
equalizer not showing

### ISSUE THREAD

**Issue by brownl** [ampache/ampache#661]
I'm using the lastest development version.

When I click on the the button for the equalizer, nothing happens. Trying to run `showEqualizer();` in the console produces an error saying that `showEqualizer()` is not defined.

Does anyone else have this issue?

**Update:** now, the console runs `ShowEqualizer();` ok, but nothing happens. Weird..

**Comment by SUTJael** [comment]
It seems that you can only show the equalizer when the vizualizer is displayed.

**Comment by brownl** [comment]
thanks for investigating!

**Comment by Afterster** [comment]
Indeed but this is not really a bug, equalizer is working closely to visualizer. I will commit a fix to disable equalizer if visualizer is not enabled.
