### ISSUE TITLE
Zip file download doesn't remove temporary files

### ISSUE THREAD

**Issue by wolkenschieber** [ampache/ampache#665]
I just set up an Ampache 3.7.0. It is configured to allow zip downloads of albums by following configuration entires:

allow_zip_download = "true"
file_zip_download = "true" 
tmp_dir_path = "/tmp"

So if I click on the download icon of an album, the zip file is generated in the temp directory.
After sucessful generation the download window is shown in the browser. If the download is canceled here, the temporary file will persist.

So its only a matter of time until /tmp will run out of space.

**Comment by Afterster** [comment]
Yes this is already fixed in current development branch (in fact temp file is not mandatory anymore for large archive). But thanks for the report ;)
