### ISSUE TITLE
Clicking cancel on select new art page throws error

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#667]
I went to select new album art but found nothing better so clicked on cancel. I was given this error:

Not Found

The requested URL /ampache/prettyPhoto was not found on this server.

**Comment by Afterster** [comment]
I committed a fix to avoid 404 error. This happened if you clicked on a photo to enlarge it and then go to search art, because we use location hash text to know the current page. In this scenario and with this fix, you go back to the main page.

**Comment by stebe** [comment]
I haven't been able to reproduce since the last pull.
