### ISSUE TITLE
Plex Backend

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#668]
No sure if filing an issue is the right way to ask a question, please advise if there is a better way.

Just trying to enable the Plex backend: 

Is the Plex Backend supposed to be "auto discovered" by Plex clients?  I kind of getting it working to some extend when I manually add my server IP to the Plex iOS app, but it won't be auto discovered.

I changed the port to 32500 because I have a "real" (no offense :)) server running on port 32400.

Again, thanks for all the great work.

**Comment by Afterster** [comment]
First and just to be sure, did you successfully 'published' the server to myPlex after logging into http://localhost:32400/web?

**Comment by florihupf** [comment]
I could login and only saw an empty page after the successful log in.  Is
there something else supposed to show up after the log in?

**Comment by Afterster** [comment]
The page shouldn't be empty after log-on. I believe you have an error in Ampache/Apache logs somewhere, could you look?

**Comment by florihupf** [comment]
Ok, will dig around and post back.  Thanks for your patience.

**Comment by florihupf** [comment]
Here is the apache2 log while logging in (successfully) and then seeing the
white screen after log in:

vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /web HTTP/1.1" 301 556 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:33.0)
Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /web/ HTTP/1.1" 200 408 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:33.0)
Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /favicon.ico HTTP/1.1" 200 1456 "-" "Mozilla/5.0 (X11; Linux x86_64;
rv:33.0) Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /web/index.php HTTP/1.1" 302 342 "-" "Mozilla/5.0 (X11; Linux x86_64;
rv:33.0) Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /web/login.php HTTP/1.1" 200 847 "-" "Mozilla/5.0 (X11; Linux x86_64;
rv:33.0) Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /web/style.css HTTP/1.1" 200 1131 "http://localhost:32500/web/login.php"
"Mozilla/5.0 (X11; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:02 -0800]
"GET /images/plex-icon-256.png HTTP/1.1" 200 28416 "
http://localhost:32500/web/login.php" "Mozilla/5.0 (X11; Linux x86_64;
rv:33.0) Gecko/20100101 Firefox/33.0"
www.nid-nad-nud.org:80 77.234.40.150 - - [12/Jan/2015:13:22:03 -0800] "GET
/wp-login.php HTTP/1.0" 404 531 "-" "Mozilla/4.0 (compatible; Synapse)"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:14 -0800]
"POST /web/login.php HTTP/1.1" 302 553 "http://localhost:32500/web/login.php"
"Mozilla/5.0 (X11; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0"
vm-01-seafile.local:32500 192.168.13.52 - - [12/Jan/2015:13:22:14 -0800]
"GET /web/index.php HTTP/1.1" 200 442 "http://localhost:32500/web/login.php"
"Mozilla/5.0 (X11; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0"


Here is the ampache log at the same time:

2015-01-12 13:22:14 [flo] (session) -> Session created:
vaharnouqegb4elhcdhnbg1163
2015-01-12 13:22:14 [flo] (User Ip) -> Login from ip adress: 192.168.13.52
2015-01-12 13:22:14 [flo] (session) -> vaharnouqegb4elhcdhnbg1163 has been
extended to Mon, 12 Jan 2015 14:22:14 -0800 extension length 3600

**Comment by florihupf** [comment]
Additionally info:

When I just ignore the white log in screen and manually add the server on
the iOS app I see a list of songs, but can't play and no images for songs,
very similar to here:
https://github.com/ampache-doped/ampache-doped/issues/150

I read through the issue and inspected logs and one thing I saw is that
access is made to "/Library/..." which end up being 404s.

**Comment by Afterster** [comment]
Is **http_host** setting configured in ampache.cfg.php? Could you try to also configure **local_web_path** setting?
Could you comment line 31 of /lib/init-tiny.php and see if you still have a blank page?

**Comment by florihupf** [comment]
*local_web_path* wasn't configured -> set to 'http://localhost/ampache'
*http_host *was configured to -> 'www.mydomain.org'
commented out the line:
   error_reporting(E_ERROR); // Only show fatal errors in production
in init_tiny.php.

No luck with any of these.

**Comment by Afterster** [comment]
Ok then it should be a php settings. Could you take a look on your php.ini and see what are the settings about debug/error logging? (display_errors, error_log, ...).
You probably have a blank page because an error is throwing up somewhere and it is not logged / displayed.

**Comment by florihupf** [comment]
After switching everything on that remotely is concerned with php and
debugging I see this notice:

*Warning*: session_set_save_handler(): Argument 1 is not a valid callback
in */var/www/ampache/lib/class/session.class.php* on line *402*

*Notice*: Undefined index: max_upload_size in
*/var/www/ampache/lib/init.php* on line *92*

I still can login just fine and the white screen is replaced with a white
screen with these two messages.

Somehow, I don't think those are related.

**Comment by Afterster** [comment]
Oh got it, I was able to reproduce the error.
This is admin zone for Plex features, you have to login with an administrator user. I updated the page to display the "Unauthorized" error message in case the user is not an administrator.

**Comment by florihupf** [comment]
That went further! ~ I should have thought about this myself.

I attempted to publish the server, but it gave me: Cannot register server
on myPlex.

The log sayed:

2015-01-12 15:25:56 [root] (User Ip) -> Login from ip adress: 192.168.13.52
2015-01-12 15:27:16 [root] (plex) -> Calling
https://my.plexapp.com/users/sign_in.xml
2015-01-12 15:27:16 [root] (plex) -> Calling https://my.plexapp.com/pms/:/ip

2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected,
'&lt;' not found in file /var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): xx.xx.xx.xx in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): ^ in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [root] (plex) -> Calling
https://my.plexapp.com/servers.xml?auth_token=X6WoNsL5SpyzB7sPrcFN
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected,
'&lt;' not found in file /var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string():   in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string():  ^ in file
/var/www/ampache/lib/class/plex_api.class.php(505)

**Comment by florihupf** [comment]
Update:

After tinkering some more with my apache2 config I can get the server
published.  The plex.tv web page sees the server and so does my iphone
client.

I can play music fine but there are no images / artwork on plex.tv.

I saw artwork briefly on the iphone client but it is gone now.

I see the following things in my access log which looks suspicious:

vm-01-seafile.nid-nad-nud.org:80 127.0.0.1 - - [12/Jan/2015:21:42:57 -0800]
"GET /library/metadata/20000147/thumb/20000147 HTTP/1.1" 404 460 "
http://127.0.0.1:32500/library/metadata/20000147/thumb/20000147"
"php-requests/1.6"

Note that the server listens on port 32500.  Looks like something gets
redirected from port 32500 to 80 ?

Anyways, getting closer!

**Comment by Afterster** [comment]
As noticed in the Plex admin zone:
`Plex servers should locally listen on port 32400. Current local listing port for your Plex backend is 32402. Ampache applies a small URI `hack` to work with custom port as Plex server, but be aware that this will not work with all clients.`
Plex port is hardcoded in most plex clients (sick). If you're not listening locally on port 32400 (another port externally is ok) could you give a try on that port? Thanks.

**Comment by Afterster** [comment]
Btw, why and how did you manage to resolve the publish error? This could be useful for other people.

**Comment by florihupf** [comment]
I tried port 32400 but no change, it is the same behavior.  For registering
the server it sometimes works and sometimes bails with the error message
stated.

So I am still stuck somehow.  Sometimes it works partically on the iOS
client, but it never works on plex.tv...

Hmm, my hunch is that my apache2 config must be bogus.  How could I verify
that it indeed picks up the .htaccess with the rewrite rules in the /plex
subfolder?

**Comment by florihupf** [comment]
Just wanted to give an update on my current status:

1) I use port 32500 for the plex backend, but using port 32400 doesn't change it.
2) When publishing the server for the first time or after unregistering it, I get: "An error occured when registering the server". I get the following log when this happens:

2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected,
'&lt;' not found in file /var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): xx.xx.xx.xx in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): ^ in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:16 [root] (plex) -> Calling
https://my.plexapp.com/servers.xml?auth_token=X6WoNsL5SpyzB7sPrcFN
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected,
'&lt;' not found in file /var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string():   in file
/var/www/ampache/lib/class/plex_api.class.php(505)
2015-01-12 15:27:21 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string():  ^ in file
/var/www/ampache/lib/class/plex_api.class.php(505)

3) After the failed registration (maybe it partially succeeded), I can "plex.tv" and my local iphone client do see the server.
4) "plex.tv" more often than not says: "can't connect to server", but sometimes indeed can connect.  It can browse and play music, but no images (ie. album artwork) is visible.  
5) The iOS client (on the same local net as the server) sometimes sees images and can play music. Sometimes it doesn't see images.
6) When the iOS clients sees images it locks up quickly as if there is only one concurrent request possible to the ampache/plex server.

When connecting to the ampache server, I often see these error messages in the apache.log:

server.my-domain.org:80 127.0.0.1 - - [12/Jan/2015:21:42:57 -0800]
"GET /library/metadata/20000147/thumb/20000147 HTTP/1.1" 404 460 "
http://127.0.0.1:32500/library/metadata/20000147/thumb/20000147"
"php-requests/1.6"

I am kind of a bit stuck as I don't know a way to better debug the situation.  My hunch is that there may be interference with my other apache2 config, although that may be just a red herring.

If there is anything I can upload/help you guys with, please let me know.

**Comment by florihupf** [comment]
Ok, one more update: After disabling CTF in my Linksys Router, I was finally able to successfully register my server with "plex.tv".  I saw a white message saying "registering successful".  

Now it works but the images and album artwork won't show up.  Looks like this is the remaining issue.

**Comment by florihupf** [comment]
Ok, long story shot: I was using NamedVirtualHost xxx.xxx.xxx.xxx:32500 instead of a plain Listen on port 32500 (as in the example).

Using NamedVirtualHost turned on the name matching with the given http headers.  And that was the reason that it didn't work.

All fine now.  Great work!  It's awesome to have a Plex Backend for Ampache! Cheers!

**Comment by Afterster** [comment]
Ok good to know this was a misconfiguration and thank you for posting the solution here :)
