### ISSUE TITLE
Transcoding regression? 

### ISSUE THREAD

**Issue by SUTJael** [ampache/ampache#669]
Did anyone noticed a regression about transcoding m4a/ogg files (into mp3) in the webplayer? It's not working anymore on my side after latest commits.

@Afterster, I saw you merged/worked recently on the streaming process, any chance something failed after that?

**Comment by Afterster** [comment]
Yes I believe it is related to #381; please continue the discussion on this thread.
I'm stuck at work with a customer for the evening :\ and as you have the issue on your server, could you try to debug this according to my changes? Thanks.

**Comment by SUTJael** [comment]
Yes will do that asap ;)
