### ISSUE TITLE
HTML Problem in install_footer.inc

### ISSUE THREAD

**Issue by essagl** [ampache/ampache#671]
eclipse ide detected the following error in ampache/templates/
  <script src="<?php echo $web_path; ?>/modules/jquery/jquery.min.js"</script>
should be
<script src="<?php echo $web_path; ?>/modules/jquery/jquery.min.js"></script>

**Comment by brownl** [comment]
could you provide the details of the error? Thanks.

**Comment by essagl** [comment]
It's just a typo. The html <script ... tag should be closed.

2015-01-16 20:01 GMT+01:00 Lawrence Brown <notifications@github.com>:

**Comment by brownl** [comment]
Thanks for spotting this. Opened PR #673
