### ISSUE TITLE
Bug and usability in "Edit Song" form 

### ISSUE THREAD

**Issue by essagl** [ampache/ampache#672]
1) The form to edit the song information has the ability to add and remove Tags by selecting one from a dropdownlist which appears when you type in the appropiate field. Added tags get store with the song, however it is not possible to remove tags. After submitting the form, the deleted tags ar not deleted.
2) Interpreter and album values can only be selected from a dropdown list of already existing values. It is not possible to directly write new values 
![song edit form vom 2015-01-16 12 43 35](https://cloud.githubusercontent.com/assets/7497666/5775696/a7b864d0-9d7d-11e4-9880-eb677d8a3b5c.png)
in the field. The dropdown selection should only be an optional proposal.

**Comment by SUTJael** [comment]
Thanks, 1 should be fixed.
2 is something planned for 3.9 ;)
