### ISSUE TITLE
Delayed transcoding when Last.FM credentials are invalid

### ISSUE THREAD

**Issue by benklop** [ampache/ampache#677]
My ampache installation has been behaving badly for the past few weeks, and I decided tonight to determine why. After a few hours of troubleshooting, I determined if Last.FM scrobbling does not work (due to invalid / incomplete login credentials for instance) sending of a transcoded file is blocked until some timeout is reached.

0. Have ampache configured to transcode certain file types (flac)
1. add a last.fm password but no username
2. Try to play a file though an API client or through the webplayer.
3. notice the file does not play, though the log indicates the transcode command has run.
4. wait about 5 minutes
5. the transcoded audio will play eventually.
6. Try to repeat with a non-transcoded file
7. notice the file plays immediately

This probably explains all the trouble I have had recently with subsonic clients as well.

**Comment by Afterster** [comment]
Unfortunately this is a known issue even if I don't really understand why it's taking so much time (it shouldn't exceed 2 seconds according to the code in /lib/class/scrobbler.class.php). All lastfm issues are referenced on #349, but you should also have the issue with non-transcoded files (are you on master or develop branch?)

**Comment by Afterster** [comment]
Closing this, please continue on #349.
