### ISSUE TITLE
Ampache reports wrong time of tracks

### ISSUE THREAD

**Issue by henryford** [ampache/ampache#678]
Hi,

I'm currently facing a strange issue with ampache: 
A big, big part of my library (or catalog, as you might put it) is reporting wrong track durations when added to ampache. I tried several different approaches to resolve this issue, but even removing the entire catalog and readding it does not yield any results.

A lot of my songs are reporting track lengths way over 40 minutes, despite them being only a few minutes long. When I check the database, the track duration is indeed wrong there. 

For example:
```
MariaDB [ampache]> select file,time from song where file LIKE '%Rap God%';
+------------------------------------------------------------+------+
| file                                                       | time |
+------------------------------------------------------------+------+
| /var/Music/Eminem/The Marshall Mathers LP 2/09 Rap God.mp3 | 3635 |
+------------------------------------------------------------+------+
1 row in set (0.01 sec)
```

While mediainfo (and literally every other program I use for playback) reports the correct duration:
```
$> mediainfo /var/Music/Eminem/The\ Marshall\ Mathers\ LP\ 2/09\ Rap\ God.mp3 
General
Complete name                            : /var/Music/Eminem/The Marshall Mathers LP 2/09 Rap God.mp3
Format                                   : MPEG Audio
File size                                : 13.9 MiB
Duration                                 : 6mn 3s
(...)
```

What's going on here? Why does ampache scrape those wrong times?

Thanks in advance for your help.

**Comment by Afterster** [comment]
Weird. Could you send me a sample file to afterster@gmail.com. Thanks.

**Comment by henryford** [comment]
On it's way - thanks for looking into it!

**Comment by Afterster** [comment]
After several tests, this is a GetID3 bug.
Could you report it on https://github.com/JamesHeinrich/getID3 and attach the test file you sent to me (dropbox, ...)? Thanks !

**Comment by Afterster** [comment]
Ok reported as https://github.com/JamesHeinrich/getID3/issues/41, I'm closing the issue here.

**Comment by henryford** [comment]
Thanks for reporting it! Great Support here :+1:
