### ISSUE TITLE
Plex Backend sometimes doesn't deliver album art / images.

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#679]
Hi there,

thanks again for the great Plex Backend.

I am running into some minor issues, which maybe just corner cases that aren't implemented.

a) Sometimes album art isn't delivered and the apache2 server gives a 404 on the image.  I verified it by copy-pasting the request URL in a browser.  I think it has to do with image resizing 'transcoding'.

For example, iOS Plex App shows images just fine during browsing, but in the play windows it is missing.  On the Apple TV (via plexConnect) I miss all images.  The access via "plex.tv" has most images.

I am willing to code it up.  Are there any recommendations or starting points?  Thank you!

b) Another minor issue is that the "Artist" artwork seems only available if I manually clicked on a specific artist via the ampache web interface.  This seems to pull the information for the single artist.  However, when looking at "Artists" via the Plex Backend, I can't see artist artwork for any other artist.  I am guessing because nothing gets pulled in that case.   Would it be possible to add a script or other method to gather artwork for all artists when updating the catalog?

Again, I am willing to code it up.

Thank you again!
 ~ Florian

**Comment by Afterster** [comment]
Great :)
About a), it could be a good way to start Ampache development indeed. You should take a look at /lib/class/plex_api.class.php (`photo` function) and /lib/class/plex_xml_data.class.php which handle basically the complete Plex backend.
And for b), I believe this will be fix with #288 which is almost developed but not enabled for performance reason for now (need to found a better way to process).

**Comment by Afterster** [comment]
@florihupf, did you worked on it? Cannot be reproduce on my side.

**Comment by florihupf** [comment]
It is working for me now.  It doesn't work when using plexConnect, but I think this is a plexConnect issue.
