### ISSUE TITLE
Letter GLITCH

### ISSUE THREAD

**Issue by abhiklodh** [ampache/ampache#680]
when installing ampache from the latest branch of New-UI ,a small 'q' is visible at the bottom left corner of the site.
![image](https://cloud.githubusercontent.com/assets/8018018/5835215/e6f5595c-a18b-11e4-96eb-973d8634ba49.png)

**Comment by Psy-Virus** [comment]
Created PR #681

**Comment by abhiklodh** [comment]
ty psy (virus ver) .i will check it out
