### ISSUE TITLE
Radio station just silent

### ISSUE THREAD

**Issue by florihupf** [ampache/ampache#683]
Hi there,

I added a radio station using this link:

http://www.ndr.de/resources/metadaten/audio/m3u/ndrkultur.m3u

However, when I click on it, nothing happens and I hear only silence.

Here is the log for pressing "play" on the radio station:

http://pastebin.com/7fKZ5f4L

TIA,
 ~ flo

**Comment by Afterster** [comment]
For web player, you have to set the direct stream, here it is http://ndr-ndrkultur-mp3.akacast.akamaistream.net/7/527/273758/v1/gnl.akacast.akamaistream.net/ndr_ndrkultur_mp3
This is a jPlayer related limitation, some work is in progress but it will not be before next major jPlayer version or a move to something similar.

**Comment by ainola** [comment]
This isn't really an Ampache issue and should be closed, I would imagine. Though I guess Ampache could parse the .m3u.... that seems like the wrong way to do things, it should be fixed upstream.
