### ISSUE TITLE
Album split between mp3 and m4a

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#684]
I'm on the 3.8.0 develop branch.  Albums that have a mix of mp3s and m4as are split up in Ampache.    I have one entry containing all mp3s for the album, and another entry containing all mp4s for the same album.  I've tried using MusicBrainz for metadata, as well as the ID3 tags.  Haven't figured out a way to get around this.

**Comment by Afterster** [comment]
Could you please send test file (both mp3 and m4a) to afterster@gmail.com? Thanks.

**Comment by JoeDat** [comment]
I've had to walk away from Ampache for a while, but coming back to it.  I've noticed this issue appears to have returned.  On single disk albums, all M4As show as Disk 1, while all MP3s show as Disk 0.  This splits up the view of the album, and when viewing via Artist, only Disk 0 tracks appear.  

I'm running 3.8.3-develop.

**Comment by lachlan-00** [comment]
Groupings have changed and tags are read differently (m4a uses vorbis?)

this should be okay
