### ISSUE TITLE
Disc number ignored on M4A files

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#685]
I'm on 3.8.0 develop.  Ampache is not reading in the disc number tag on MP4 (M4A) files.  It defaults to 0, regardless of whether the tag doesn't exist, or does and contains a non-zero value.  I don't experience this same problem with MP3s, Ogg/Vorbis, or FLAC files.

**Comment by Afterster** [comment]
Could you please send test file to afterster@gmail.com? Thanks.
