### ISSUE TITLE
Unable to display avi movie in ampache, while playing directly with apache is ok

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#686]
There seems to be something wrong with ampache web player. I can play some avi encoded videos directly from within apache folders, but cannot play those same ones on ampache. Got "Unsupported
This media is not supported by the player. Is your browser up to date?" message.
![screen shot 2015-01-23 at 12 50 07](https://cloud.githubusercontent.com/assets/7412863/5877557/24c473ac-a2ff-11e4-976e-10d83ecbc67f.png)

**Comment by Afterster** [comment]
Avi streaming is not supported (cannot be streamed in flash/html5).
I believe you're using a vlc plugin or something like that. I contributed to video.js project few weeks ago and added vlc backend support to the project. So this will be supported as soon I integrated this backend in jPlayer project or Ampache move to video.js (not mature enough for audio only right now).

**Comment by mitchray** [comment]
Closed due to time since last discussion
