### ISSUE TITLE
Display <DISCSUBTITLE> information when showing multi-disc albums

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#687]
So, now that I have The Beatles in Mono in Ampache, and it's all tagged properly in Musicbrainz, I see 13 discs and each one is called "The Beatles in Mono, Disc xxx."

Each of the individual Beatles albums had their names added in the <DISCSUBTITLE> field.  If would be nice if Ampache could read this information and display it.

**Comment by Afterster** [comment]
Just a reminder for later to see DISCSUBTITLE tag http://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

**Comment by Rouzax** [comment]
That would be a nice feature.

**Comment by Phyks** [comment]
I don't get what is happening here (did not check it in details though).

What is different between https://musicbrainz.org/release/5cd103c6-07e3-32b1-8cea-7e53eb994829 and https://musicbrainz.org/release/84b998b5-d3a2-4bdb-a932-4642b0e4cc3a?

The latter is handled just fine by Ampache (see [this screenshot](https://cloud.githubusercontent.com/assets/3856586/17366674/b5cd6328-598c-11e6-9f91-6f1b30198295.png)).

cc @Niols who handled the import of this album, I think, and might have more infos on this

**Comment by apastuszak** [comment]
Here is a screen shot of The Beatles in Mono on my PC, tagged with MusicBrainz Picard:

![2016-08-03 13_17_44-ampache __ for the love of music - home](https://cloud.githubusercontent.com/assets/3401054/17375043/5a3b5d6c-597d-11e6-8301-9a356c26f5ed.png)

**Comment by apastuszak** [comment]
@Phyks I think this is because I have it set to group multi disc albums together in my Ampache preferences.

**Comment by Phyks** [comment]
Ok. I will need @Niols input on this, as he is the one managing our instance and knowing exactly why it may differ here. Anyway, it is tightly linked to #1015 previously mentionned.

**Comment by mitchray** [comment]
I've made a start on this in #3599

**Comment by lachlan-00** [comment]
merged now
