### ISSUE TITLE
Update from Tags not available for albums of FLAC files

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#691]
The list of available options is much shorter for albums made of FLAC files vs MP3, Ogg or AAC albums.

A FLAC album shows the following options:

Play
Play last
Add to temporary playlist
Random to temporary playlist
Download

A MP3/Ogg/AAC album shows:

Play
Play last
Add to temporary playlist
Random to temporary playlist
Post Shout
Save Tracks Order
Update from tags
Edit Album
Download

**Comment by Afterster** [comment]
There is no such condition as far as I know.
Are you sure your FLAC album is not a two-disk album and you're browsing the 'grouped view'?

**Comment by apastuszak** [comment]
Here is a screen shot:

![bse](https://cloud.githubusercontent.com/assets/3401054/5922729/efd80bfc-a61b-11e4-877f-d28519229323.png)

**Comment by Afterster** [comment]
Yep, multi disk. You have the options per disk if you take a better look ;)

**Comment by apastuszak** [comment]
I don't see an option for Update From Tags, next to the disc when I look at that row of icons.

**Comment by Afterster** [comment]
Mhh not this one you're right, but you should have all this other. A mark this thread as Enhancement then.

**Comment by apastuszak** [comment]
Thank you
