### ISSUE TITLE
currently listening on lists

### ISSUE THREAD

**Issue by eephyne** [ampache/ampache#692]
I was thinking of that today.

It could be a good idea to show whats currently listened (with a small icon ) in lists (either when showing the album or any other list who contains the title).

I don't know if this is currently possible but I personally think that would add a nice touch on the interface.

**Comment by eephyne** [comment]
and if this is doable and wanted by other peoples (I don't use multiaccount), I could be fun to mark whats listened by others too.

**Comment by SUTJael** [comment]
Hum but what would be the benefit of seeing that into the list? (I'm thinking of UI and SQL queries). I would prefer to not mix library browsing and currently listening information which is something completely different. Maybe we could think about something like a listening "breadcrump" which would always be displayed whatever the page you navigate (like the static menu)?

**Comment by eephyne** [comment]
For example you watch a list of popular songs and you can see you already listen to one. Or  you listen to Xx - yy and go to an album of Xx,  you see yy but it's not marked as currently listened, meaning it's an other version of this song. Again it's not a feature killer but something nice to have (IMHO) .

**Comment by SUTJael** [comment]
Well I think there's a misunterstood: the title says "currently listening" and you're talking about "already listened" songs. Which one is good ?! Because it's really really different :)
About your point "already listened", I think it's related to the "# played" number no?
![nb_played](https://cloud.githubusercontent.com/assets/5746257/5978758/66ec418a-a8a2-11e4-9c47-d31d74d45bd1.png)

**Comment by eephyne** [comment]
No I said "you already listen to one" I mean you currently listen to a song present in this list (sorry for my poor english level :(  )

**Comment by mitchray** [comment]
Closing due to time since last discussion
