### ISSUE TITLE
enabling get voters

### ISSUE THREAD

**Issue by M4DM4NZ** [ampache/ampache#694]
Hey Guys,

I'm trying to get the democratic playlist to display the voters id's on my ampache setup.

to implement this im using get_voters() in the class file democratic.class.php, I've tried passing the function or the likely object_id, but i dont seem to get any output at all.

I've tried adding the following lines to call the function from /templates/show_democratic_playlist.inc.php, but nothings working....

<?php $voters_array = $democratic->get_voters($media->id); ?>
      <?php $voters_array = $democratic->get_voters($item['object_id']); ?>
      <?php $voters_array = $democratic->get_voters($item['id']); ?>
      <?php $voters_array = $democratic->get_voters($item); ?>

I also canot find anywhere else on the site where this function is called or refered to.

Can someone please point me in the right direction?

**Comment by Afterster** [comment]
Mhh I believe this function shouldn't even exists anymore, it gets from cache something that was never set ; there is also several unused local variables... Old code Yeah!
get_voters need to be implemented with a sql request.

**Comment by M4DM4NZ** [comment]
Thanks Afterster, 

Could you please add this as a feature request, I would really love to get this going to keep track of what users are voting on various songs.

Cheers :)
