### ISSUE TITLE
Problems with iampache 

### ISSUE THREAD

**Issue by spassat** [ampache/ampache#697]
I have a working ampache 3.8.0 server running on Centos which I can access on a local network from a desktop, but am having problems with access from an iPhone with iOS 8.1.3 via iampache.

From the ampache logs, I can log in successfully, but then the app on the iPhone becomes completely unresponsive. The login result is here:

2015-01-29 09:50:58 [ampache] (API) -> Handshake Attempt, IP:192.168.1.xxx User:DCiPhone Version:350001
2015-01-29 09:50:58 [ampache] (API) -> Login Attempt, IP:192.168.1.xxx Time: 1422525058 User:DCiPhone (3) Auth:9d7f854eac1957f9a9292fc42e444df9a92f2b4c732baeb0eee0316bb1875952
2015-01-29 09:50:58 [ampache] (session) -> Session created: 38be28bc2c7573f8120d25975b641d28
2015-01-29 09:50:58 [ampache] (API) -> Login Success, passphrase matched

After this, nothing. As I said, the iPhone app become completely unresponsive and the only thing you can do is close it down. There are no further entries in the log.

I have set up ACL for API/RPC for IP range 0.0.0.0 - 255.255.255.255 (overkill) and can access the ampache server fine from a wired desktop client through a browser. Music is displayed and can be played wither via playlist (with MediaMonkey) or via Web by changing the ampache settings.

The iampache URL settings for the ampache server are URL=192.168..2/ampache.

Any ideas?

**Comment by SUTJael** [comment]
Could you give a try with iSub? Seems like the client is working great (see [here](https://groups.google.com/forum/?hl=fr#!topic/ampache/gHO9kb-FdUI))

**Comment by SUTJael** [comment]
@spassat I will close this thread as it's not related to ampache but Iampache. Don't hesitate to ask to iampache developers directly to get some news, otherwise reopen this thread if needed.
