### ISSUE TITLE
Web player UI gets messed up when removing the footer statistics

### ISSUE THREAD

**Issue by gregoo** [ampache/ampache#705]
When you set the option below to false in the configuration, the web player buttons display text, the song title moves at the top of the player and gets cut.
```
; Footer Statistics
; This defines whether statistics (Queries, Cache Hits, Load Time)
; are shown in the page footer.
; DEFAULT: true
; Possible values: true, false
show_footer_statistics = false
```

Option set to `true`
![2015-02-01-ampache-player-stats](https://cloud.githubusercontent.com/assets/1266495/5994241/b16cd786-aa6b-11e4-9d95-b8beb911ae8f.png)

Option set to `false`
![2015-02-01-ampache-player-no-stats](https://cloud.githubusercontent.com/assets/1266495/5994242/c1e58284-aa6b-11e4-9efc-5ce00449d6e7.png)

Same song is played on both screenshots. I am using a freshly pulled `develop` branch

**Comment by Afterster** [comment]
Yep, thanks.
