### ISSUE TITLE
lighttpd rewrite rule for Subsonic API

### ISSUE THREAD

**Issue by jaquer** [ampache/ampache#709]
Took me a bit to figure out the rewrite rule for the Subsonic API when using lighttpd. Here it is, in case you'd like to add it to the wiki:

for an installation on the root:

    url.rewrite-once = (
      "^/rest/(([^\?]+)\.view)(\?(.*))?" => "/rest/index.php?ssaction=$2&$4"
    )

Modify as needed for subdir installs.

    url.rewrite-once = (
      "^/ampache/rest/(([^\?]+)\.view)(\?(.*))?" => "/ampache/rest/index.php?ssaction=$2&$4"
    )

mod_rewrite must be enabled in order for the rule to work.

**Comment by Afterster** [comment]
Thanks for sharing your config, I added these lines in the wiki Subsonic section.
I'm not a lighttpd user ; when you have some times could you write the wiki general configuration section for lighttpd as we did for nginx in https://github.com/ampache/ampache/wiki/Installation#web-server-configuration? That would be awesome, thanks!

**Comment by jaquer** [comment]
I'm far from a lighttpd expert, but I'll give it a shot.

**Comment by Afterster** [comment]
Ok :)
Just copy / past here when you have something, I will update the wiki by myself. Thanks.

**Comment by smvueno** [comment]
Hello!!

I have been fiddling with my server for some days now but i really cant get it to work.
When i added this script it worked like a charm!!

Would you also be able to convert the rest of the nginx code for lighttpd?

server {
   listen   80;
   server_name FQDN;
   charset utf-8;

   root PATH;
   index index.php;

   # Rewrite rule for Subsonic backend
   if ( !-d $request_filename ) {
      rewrite ^/rest/(.*).view$ /rest/index.php?action=$1 last;
      rewrite ^/rest/fake/(.+)$ /play/$1 last;
   }

   # Rewrite rule for Plex backend
   if ( !-d $request_filename ) {
      rewrite ^/plex/(.*)$ /plex/index.php?action=$1 last;
   }

   # Rewrite rule for Channels
   if (!-d $request_filename){
      rewrite ^/channel/([0-9]+)/(.*)$ /channel/index.php?channel=$1&target=$2 last;
   }

   # Beautiful URL Rewriting
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&name=$5 last;
   rewrite ^/play/ssid/(\w+)/type/(\w+)/oid/([0-9]+)/uid/([0-9]+)/client/(.*)/noscrobble/([0-1])/name/(.*)$ /play/index.php?ssid=$1&type=$2&oid=$3&uid=$4&client=$5&noscrobble=$6&name=$7 last;
   location /play {
      if (!-e $request_filename) {
         rewrite ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1;
         break;
      }

      rewrite ^/([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2;
      rewrite ^/(/[^/]+|[^/]+/|/?)$ /play/index.php last;
      break;
   }

   location /rest {
      limit_except GET POST {
         deny all;
      }
   }

   location /plex {
      limit_except GET POST {
         deny all;
      }
   }

   location ^~ /bin/ {
      deny all;
      return 403;
   }

   location ^~ /config/ {
      deny all;
      return 403;
   }

   location / {
      limit_except GET POST HEAD{
         deny all;
      }
   }

   location ~ ^/.*.php {
    # PHP config...
   }

   # Rewrite rule for WebSocket
   location /ws {
    rewrite ^/ws/(.*) /$1 break;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:8100/;
   }
}


I have been staring myself blind on this for hours, i just dont get the thing with regex and how to make it work in lighttpd.
The nginx code looks soo much simpler than the lighttpd.
I will keep tinkering in case i have some success i will post it here. 
Anyone else who is good at this?

**Comment by Afterster** [comment]
Any new on this @jaquer  @smvueno ? I would be glad to add lighttpd rules in the wiki. Thanks.

**Comment by smvueno** [comment]
Hey Afterster! I have been experimenting a lot with it but i ended up giving up. Im running it on my computer again now.
My router that was running lighttpd, could not access the stream page somehow. So it's still missing something to make me being able to access it.

**Comment by Afterster** [comment]
Ok thanks for the feedback smvueno.
It's unfortunate you had to do a workaround because Ampache installation on lighttpd server is not documented.
@jaquer, any chance you can help us on this? Thank you.

**Comment by Afterster** [comment]
I'm going to close this in attempt to clean issue list. A new [lighttpd section](https://github.com/ampache/ampache/wiki/Installation#lighttpd) was added to the wiki. Please feel free to improve it.
