### ISSUE TITLE
Cleared text in an episode row edit dialog isn't saved to database. 

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#710]
For examle, I accidently entered text into the "original_name" text field and saved it.
When I cleared the text  in the edit box, to remove the information from the database, it failed to update the original_name column in the table..

I think the reason is that $data['original_name'] is of 0 length (empty?) so will not be selected in:
  $original_name = $data['original_name'] ?: $this->original_name;
when trying to update the db column wiith null data. $this->original_name will always be set.

This is in the update function of tvshow_episode.class.php.

**Comment by Afterster** [comment]
Fixed, thanks for the good report!
