### ISSUE TITLE
Music - Year defaults to 1969 when Year tag contains more than year

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#711]
Running dev branch on latest commit.  Noticed that the Year info will default to 1969 if the Year tag contains something other than just the year.  I use MusicBrainz Picard to tag my files, and in many instances, it will tag the Year in a yyyy-mm-dd format.  I don't know whether to consider this a bug in Ampache, or Picard, considering that the tag is called 'Year', and they're including additional info.

**Comment by Afterster** [comment]
Mhh works on my side. Could you send me a test file to afterster@gmail.com? Thanks.

**Comment by Afterster** [comment]
Thanks for your test file. It still works on my side with your file then I believe it is related to server configuration (it shouldn't).
Maybe it is related to `date.timezone` php.ini setting? What is your value for it?

**Comment by JoeDat** [comment]
Strange.  My data.timezone setting is "America/New_York". v PHP v 5.4.36.  What do you see on your side?  Full date, or does it rip out non-year data, and display the year only?

**Comment by Afterster** [comment]
It display the year only, and it is the good one (1970 in your case).

**Comment by JoeDat** [comment]
Even weirder.  The Year tag file in the example I sent you is "1993- 2-22"

**Comment by Afterster** [comment]
Ok I believe I identified your issue, your test file release_date has space in the date.
Could you try with latest commit?

**Comment by JoeDat** [comment]
Hm, no difference with doing a catalog update.  I'll try a file removal, clean and re-add, and report back.

**Comment by JoeDat** [comment]
Ok, I removed the files from the album with these problem tags, cleaned the catalog, re-added the files, and ran an Add on the catalog, and they are reporting correctly now (year shows 1993, which is perfect).  Easiest way now to clean up the rest for me is to just completely delete and re-add my whole catalog.  Not really a big problem for me.  I consider this resolved.  Thanks!!

**Comment by Afterster** [comment]
Ok great, I'm closing this then.
