### ISSUE TITLE
Rational for requiring getID3 along with Tmdb/tvdb?

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#712]
Without getID3 included in metadata_order_video, the tags array isn't created and tvdb.plugin.php can't determine what information to collect.

If getID3 is included and a clean mp4 without any metadata is used, there will be little tag data anyway an only general data will fill the array. 

If I understand the process, The required metadata should be pre-defined and Tmdb/Tvdb class  should be able to parse the filename correctly to look up the series name to grab the requested metadata. 

I compare it to MetaX which I use as my "Standard".  It searches for the series name based only on the filename and does a very good job if the filename uses the customary format. If it can't quite guess correctly, it will allow you to choose.

At any rate, I just tested it with and without the getID3 included  on a fresh mp4 (free of any metadata) and the Tvdb search failed miserably, giving me "unkown" metadata.

If you agree with my explanation, I'll look into the required changes.

**Comment by Afterster** [comment]
Normally `getID3` should be optional but `filename` mandatory to at least query external services like Tmdb/Tvdb with a name determined from the path/filename. So I agree, maybe you just have to look to improve the `filename` parsing?

**Comment by wagnered** [comment]
OK, as for rational, why are both "metadata_order_video" and "metadata_order" both checked when grabbing only movies and tv shows?  Unless there is a need for heirarchy with "metadata_order" having priority over "metadata_order_video" why isn't "metadata_order"  referred to as "metadata_order_music" and ignored when grabbing video metadata? 

It has caused me confusiion/misdirection whiile working on grabbing metadata for movies and tv shows.  I accidently entered "Tvdb" in "metadata_order"  and  "getID3" in "metadata_order_video" and was wondering why it was  wasn't grabbing the correct information.

Thanks,

Ernie D

**Comment by wagnered** [comment]
Discovered that the title returned by   AmpacheTmdb-get_metadata() is overwritten because  vainfo->get_tag_type always returns "general" as the last item and the vainfo->_parse_general() doesn't parse the filename for a prettty title.  The file names for movies can get pretty ugly.

I could move the preg_* statements that I use to extract the pure title in AmpacheTmdb-get_metadata() to the vainfo class so that vainfo->_parse_general() creates   the prettyfied title to be written to the database.

That would probably be the easiest way to prevent titles like "Dying.of.the.Light.2014.720p.BluRay.x264.YIFY" from showing up on the Movies page.

**Comment by Afterster** [comment]
Catalog media type (music / video) is only checked before library insertion ; file type identification is always performed independently of the catalog media type. This could be changed to avoid unnecessary checks but it wouldn't change much.

Mhh ok for  AmpacheTmdb-get_metadata(), what does looks like your preg statements?
Thanks for working on the video part,

**Comment by wagnered** [comment]
This is what I wrote based on kodi(xbmc) naming conventions:

examples from their wiki:

    Reservoir Dogs (1992).avi  // The date is optional.

for tv shows:

   anything_s01e02.ext 


   public function parseFileName($file, $gather_types)
    {
    	$title = pathinfo($file,  PATHINFO_FILENAME);
    	$replaceWith = array(".","_");
    	if (in_array('tvshow', $gather_types)) {
    		if (preg_match("~[Ss]\d+[Ee]\d+~", $title, $seasonEpisode)) {
    			$SE = $seasonEpisode[0];
    			preg_match_all("/\d+/",$SE,$tmp);
    			//Get the title and clean it up
    			$temp = preg_split("/[Ss]\d+[Ee]\d+/",$title,2);
    			$matches[] = trim(str_replace($replaceWith," ", $temp[0]), " \t\n
\r\0\x0B\."); //trim($temp[0], " \t\n\r\0\x0B\.");
    			// Add the season and episode. The tmdb search engine doesn't
like leading zeroes.
    			$matches[] = ltrim($tmp[0][0], "0");
    			$matches[] = ltrim($tmp[0][1], "0");
    		
    			return $matches;
    		}
    	else {
    		$matches[] =str_replace(replaceWith," ", $title);
    		return $match;
    	}
    	
    	}
    	
        if (in_array('movie', $gather_types)) {
             
            //search for a date.
            if (preg_match("~(\d{4})~", $title, $temp))
            {
                if (($temp[0] > 1919) & ($temp[0] < 2030)) {
                    $matches  = preg_split("/" . $temp[0] . "/", $title,
2);
                    $tmp[] = trim(str_replace("."," ", $matches[0]), "
\t\n\r\0\x0B\.");
                     
                    return $tmp;
                }
            }
            else {
                $tmp []= $title;
                return $tmp;
            }
        }
    }
    
I will be doing a survey in the Google forum to get an idea of what
naming conventions might be popular.

Also, I can envision a user menu selecting their preferred scanning
convention much like what Easytag provides for scanning music file
names.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wagnered** [comment]
@Afterster , in another issue you stated that you are reluctant to modify external code.
I agree and this is concerning the Moinax/Tvdb module.  After modifying the code to download a zip file from Tvdb, I realized that the module is a third-party source.  So I checked the Moinax/tvdb repository and the latest version includes the function I needed, pretty much exactly as I had written it..

My question is  how to deal with the new version:  Should I just download/install iit in my local branch so it will be included with the changes I'm making to the tvdb featues or is there some other proccedure for including updated modules?

**Comment by Afterster** [comment]
The current way to update external modules is to override the files yes. This should change with Composer support but I didn't had the time to work on it yet.

**Comment by wagnered** [comment]
My mistake, upon a close look at the new function , it won't serve my
purpose: It's purpose is to provide a way to download an entire series
with all episodes in a zipped file.


I think I found the function I can use in client.php that I can call
from get_metadata().  I just wonder why get_metadata() doesn't use it to
get all the metadata: It misses genre and content_ratings.


Thanks



-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wagnered** [comment]
I thought I had already closed this....
