### ISSUE TITLE
FB / TW sharing not working

### ISSUE THREAD

**Issue by robertocarlo** [ampache/ampache#714]
Unable to share files/albums/playlists with index.php#share.php?action=external_share&plugin=Facebook&type=song&id=
maybe some permissions issue?

**Comment by Afterster** [comment]
Ok there was an issue in redirection when the share is ajax loaded. Now external share are open in new window with latest commit, is it working for you?

**Comment by robertocarlo** [comment]
Attempted to update to latest develop branch, but install is requesting php 5.4, which cannot be updated on server side right now.
Can i try to replace modified files only, e.g. share.php?

**Comment by Afterster** [comment]
Not recommended.
PHP 5.3 drop is quite new and can still be reverted for any good reason. It was dropped for further code development simplicity. When we discussed about it we believed all distrib and major hosting provider was on PHP >= 5.4. Any reason your server cannot be updated?

**Comment by robertocarlo** [comment]
Will attempt to update it later. After doing so, will test it and get back to this.

**Comment by robertocarlo** [comment]
After updating Server to PHP 5.6 and Ampache to latest commit there's no new popup window or changes in FB/TW share behaviour.
![screen shot 2015-02-06 at 16 13 32](https://cloud.githubusercontent.com/assets/7412863/6085797/9895c7aa-ae1b-11e4-9e42-03c7617b3c9d.png)

**Comment by Afterster** [comment]
It should. Did you try to clear your browser cache?
Any javascript error in your browser console?

**Comment by robertocarlo** [comment]
Cache cleared, in different machines. Same -no popup- result. Will post a Firefox javascript browser console log today.

**Comment by robertocarlo** [comment]
On Firefox error console says "Not well formed".
Details:
<ul><li><a onclick="handleShareAction('http://souly.us.to/share.php?action=show_create&type=album&id=3010')"><img src="http://souly.us.to/images/icon_share.png" alt="Advanced Share" title="Advanced Share" /> &nbsp;Advanced Share</a></li><li style='padding-top: 8px; text-align: right;'><a onclick="handleShareAction('http://souly.us.to/share.php?action=external_share&plugin=Facebook&type=album&id=3010')" target="_blank"><img src="http://souly.us.to/images/icon_share_facebook.png" alt="Facebook" title="Facebook" /></a>&nbsp;<a onclick="handleShareAction('http://souly.us.to/share.php?action=external_share&plugin=Twitter&type=album&id=3010')" target="_blank"><img src="http://souly.us.to/images/icon_share_twitter.png" alt="Twitter" title="Twitter" /></a>&nbsp;</li></ul>

**Comment by Afterster** [comment]
Ok, any error lines in the console log? More information is required to be able to determinate the problem as I cannot reproduce it.

**Comment by robertocarlo** [comment]
Cannot tell about more error lines, but i can confirm it is working now. 
The only change is that i have restarted my working macbook.
Maybe just clearing browser cache wasn't enough.
Tested in Safari and Firefox.
