### ISSUE TITLE
auto update, proxies and slow downs

### ISSUE THREAD

**Issue by brendankearney** [ampache/ampache#716]
i have an ampache instance running on my nas device, which does not have direct outbound access to the internet.  i configured the proxy in the config file, but the auto update function still attempted to access api.github.com (and possibly other URLs) directly.  the result was tcp timeouts, since i drop (not reject) the connection attempts at the firewall.  because of this, i think, the user experience slows a lot.  when i turned off the auto update feature, the user experience greatly improved.

can the auto update process be made proxy-aware, like the album art gathering and other functions?
can the auto update process be made more of a "background" process that does not affect the user experience?

**Comment by Afterster** [comment]
The proxy setting should be applied to auto update indeed. I will mark this as an improvement.
I also believe we should check in *background*, using an ajax request. Another improvement ;)

**Comment by lachlan-00** [comment]
I think that i fixed this a while ago after another report.
