### ISSUE TITLE
QR Code is not readable with black/dark background

### ISSUE THREAD

**Issue by RyanCopley** [ampache/ampache#724]
I did some research and it only picks up the QR code when you have our cursor over the QR code-- activating the hover state of the parent container turning it to orange. It picks up the QR code almost instantly while in the hover state. http://www.qrcode.com/en/howto/trouble.html shows some examples / reasoning

**Comment by Afterster** [comment]
Should be fixed with the white border I just added, could you confirm?

**Comment by ainola** [comment]
immediately picked it up for me.

**Comment by RyanCopley** [comment]
Picks up immediately for me as well.
