### ISSUE TITLE
Upload Function // UTF-8 question

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#726]
Hello,

When I'm trying to use upload function with invoking `script.sh`  after it I have the issue, when tagger not working correctly and can't assign tags at all if they contain UTF8 chars. In the same time - script, invoking from CLI, from the same user `httpd` and `php` running from (uname: `nobody`), works just fine. I'm using `mid3v2` from python `mutagen` as tagging tool, which dealing pretty well with UTF8 

Here is the flow: 

CLI: bash > python  `working OK`
WEB INTERFACE: httpd > php > bash > ~~python~~ 
```
- bash script completing without errors and echo-ing with UTF-8 chars nicely, before mid3v2 invoked 
- mid3v2  goes to fatal screaming that it unable to decode UTF8 chars and quits
```
Also I've already tried to migrate to python3 for this tool, which has UTF-8 support pre-built, but had same issue. Error below:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`

I can't really understand what's happening here, because upper layers (`httpd` and `php`) shouldn't care about `python` invoking, by `bash`.  I've localised env to UTF-8 on system and php side, but still having same issue. Right now I'm on the way to update ampache to latest dev to see if it helps and make ampache logs very verbose with debbugging info. 

Thanks for any guideline!

**Comment by systems-rebooter** [comment]
Can this be related somehow?
https://github.com/ampache/ampache/wiki/Catalog#invalid-characters-in-filenames

**Comment by systems-rebooter** [comment]
Upgrading to latest dev didn't solve the issue. Found no valuable info in logs.
Reproduced same behaviour with other python tagger: eyeD3

**Comment by systems-rebooter** [comment]
Have tried to omit ampache from the chain and reproduced the issue with simple `php` script via web-interface:

nginx* > php > bash > ~~python~~

```
<?php
echo "Hello world";
echo exec('/xyz/script.sh');
?>
```

So, something weird going on in the env, but not ampache itself. I think the issue may be marked as `won't solve` or put `discussion` tag on in case someone will help to solve this out.

* Actually I'm using nginx, not apa~~m~~che :]

**Comment by Afterster** [comment]
Ok I will close this here then. If you want to start a discussion you can use Google Groups.
Thanks for the update on this thread.

**Comment by systems-rebooter** [comment]
Below is the fix, in case someone face with the same problem. 

It turned to be an issue on PHP-script side. Everything started work correctly, after adding following lines  to test `php` script, mentioned above: 

```
$locale='en_US.UTF-8';
setlocale(LC_ALL,$locale);
putenv('LC_ALL='.$locale);
```



```
$ php -r "echo exec('locale charmap');"
UTF-8
```
```
$ php /xyz/locale.php
UTF-8 < OLD CHARSET
UTF-8 < NEW CHARSET

```
$ curl 127.1/locale.php
US-ASCII < OLD CHARSET
UTF-8 < NEW CHARSET
```
```
```
$ cat /xyz/locale.php
<?php
#header('Content-type: text/plain; charset=utf-8');
#error_reporting(E_ALL);
#ini_set('display_errors', True);

echo exec('locale charmap');
echo " < OLD CHARSET\n";
$locale='en_US.UTF-8';
setlocale(LC_ALL,$locale);
putenv('LC_ALL='.$locale);
echo exec('locale charmap');
echo " < NEW CHARSET\n";

echo exec('/xyz/script.sh > out 2> err.txt &');

?>
```

```
$ cat /xyz/script.sh
#!/bin/bash

#MYDIR="$(dirname "$0")"
#bash "$MYDIR/config.sh"

echo `date`
SONG="/xyz/song.mp3"
ID3='а б в г ґ д е є ж з и і ї й к л м н о п р с т у ф х ц ч ш щ ь ю я'-`date`
MID3V2=/usr/bin/mid3v2
PYTHON=/usr/bin/python3

#export PYTHONIOENCODING=utf-8

$PYTHON $MID3V2 -v -a "$ID3" "$SONG"
```

I know @Afterster is very busy now to get 3.8 out as soon as possible, but it would be super cool to get this fixed on Ampache side. Meanwhile I'm using following dirty recursive workaround for the option

```
Upload: run the following script after upload (current directory = upload target directory)
```

```change-php-locale.sh > php-locale.php > script.sh```
instead of 
```script.sh```

Thanks!
