### ISSUE TITLE
"Ajax is not defined" in chrome 

### ISSUE THREAD

**Issue by rene98c** [ampache/ampache#727]
Latest development branch, same problem as #646 . 
Default installation writes to ampache.cfg.php (followed wiki installation guide)
web_path = "/ampache" .
changed it to => web_path = "/ampache/" and javascript loaded correctly.

**Comment by Afterster** [comment]
Ok but I do not have the issue, I believe it is also related to another setting.
Any other error in browser console? Any 404/403 error on network resources? Other error in Ampache / Apache logs?

**Comment by rene98c** [comment]
screenshot : https://lh3.googleusercontent.com/vWXmwD-wyqyhNeG-JpmZ87R4kl0eX3pzSUQ8MWajTB7RM-SiA-EvVTmiGbIj6oJZeZa7W8tj598=w1896-h859.
i'll check logs

**Comment by rene98c** [comment]
changed back to /ampache , i did few times ctrl+f5 , browser cached something maybe?

**Comment by Afterster** [comment]
I'm not sure to understand your last sentences.
Do you believe it was a cache issue because it is now fixed on your side? Otherwise please send more logs.

**Comment by rene98c** [comment]
yes currently working with default configure path "/ampache" , no more client side errors. I reinstalled my ubuntu box and fresh installation of ampache. I am browsing ampache on a windows pc with same browser and i suspect something was cached clientside that caused the issue.

on a ampache log there seem to be no errors, except "(autoload) -> 'OAuthException' not found!", which probably is not an exception and in apache error.log:
[Tue Feb 10 19:47:06.852381 2015] [mpm_event:notice] [pid 5079:tid 139848783673216] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Tue Feb 10 19:47:06.852692 2015] [core:notice] [pid 5079:tid 139848783673216] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 19:47:16.690144 2015] [mpm_event:notice] [pid 5079:tid 139848783673216] AH00491: caught SIGTERM, shutting down
[Tue Feb 10 19:47:17.828140 2015] [mpm_prefork:notice] [pid 6893] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Tue Feb 10 19:47:17.828394 2015] [core:notice] [pid 6893] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 19:47:19.334804 2015] [mpm_prefork:notice] [pid 6893] AH00169: caught SIGTERM, shutting down
[Tue Feb 10 19:47:20.529079 2015] [mpm_prefork:notice] [pid 6979] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Tue Feb 10 19:47:20.529173 2015] [core:notice] [pid 6979] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 19:55:33.753520 2015] [mpm_prefork:notice] [pid 6979] AH00169: caught SIGTERM, shutting down
[Tue Feb 10 19:55:34.959138 2015] [mpm_prefork:notice] [pid 7635] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Tue Feb 10 19:55:34.959247 2015] [core:notice] [pid 7635] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 20:22:15.241076 2015] [mpm_prefork:notice] [pid 7635] AH00169: caught SIGTERM, shutting down
[Tue Feb 10 20:22:16.394770 2015] [mpm_prefork:notice] [pid 31294] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Tue Feb 10 20:22:16.394871 2015] [core:notice] [pid 31294] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 20:57:42.674831 2015] [mpm_prefork:notice] [pid 31294] AH00169: caught SIGTERM, shutting down
[Tue Feb 10 20:57:43.830178 2015] [mpm_prefork:notice] [pid 31897] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Tue Feb 10 20:57:43.830277 2015] [core:notice] [pid 31897] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 10 21:02:18.359957 2015] [mpm_prefork:notice] [pid 31897] AH00169: caught SIGTERM, shutting down
[Tue Feb 10 21:02:19.520096 2015] [mpm_prefork:notice] [pid 31964] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Tue Feb 10 21:02:19.520188 2015] [core:notice] [pid 31964] AH00094: Command line: '/usr/sbin/apache2'


these messages probably related to restarting apache2 service

**Comment by rene98c** [comment]
I don't know if a fact that i also had to download and extract bootstap to /var/www/html/bootstrap  - ampache had a references pointing there.

**Comment by Afterster** [comment]
Ok then it should be cache issue indeed, please close this thread then in that case.
