### ISSUE TITLE
Amarok skipping selected track (not an ampache bug, but the solution)

### ISSUE THREAD

**Issue by lotherk** [ampache/ampache#729]
I've got an ampache instance running with a self signed certificate. Even though amarok asks for accepting the self signed certificate forever, it can not make a handshake for every track you select but loads the one that comes after. Doesn't matter if on windows or on unix.

The solution is adding your root CA to your system (see the first answer on http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate for ubuntu/debian for example).

This is not an ampache bug but may be worth adding to the FAQ or something.

**Comment by Afterster** [comment]
Okay I will follow your advice ;)
Updated in https://github.com/ampache/ampache/wiki/API#note-about-ssl
