### ISSUE TITLE
Season's show divided based on year of first-aired date.

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#730]
Even though the show name and season are identical, Ampache is splitting the twenty one episodes of a series into two different shows based on  "first aired" date.  

Most networks show a single season spread out from about August through March of the next year as the same season.  At least that's the way they are displayed on Tvdb and Tmdb.  I think the year should be ignored when sorting out the TV shows

**Comment by Afterster** [comment]
I believe it is important to distinguish tvshow based on first aired date. For instance, there is several shows with the name Doctor Who and most software are using first aired date for distinction.
Depending the metadata, you should have a tvshow first aired date, and a season first aired date (not impacting the tvshow distinction normally).

**Comment by wagnered** [comment]
That is interesting that you admit there are only "several" shows.
Shouldn't they be the exception, especially when one of the largest
commercial producers of serial/seasonal entertainment is the USA.

You mention "Doctor Who" as the example, could your opinion be because
you are British and biased? ;'>

You also wrote:

"Depending the metadata, you should have a tvshow first aired date, and
a season first aired date"

Ampache doesn't hav a date column in the season table, although, I think
both Tvdb and Tmdb modules provide functions/statements to capture the
season's "first aired" date.  Does Ampache provide the logic to
categorize/sort seasons based on the season's "first aired" date? If so,
I can add the column to the tv_season table and the logic to store it.

The problem will be with mp4 tagging software.  There is no tag for the
season's first aired date and would have to be added manually as a text
object, or possibly an id3 tag (if getID3 will detect it).  


For my own use, I'll look into adding a config setting to allow either
way. Actually, I'm not sure a  setting would be necessary.

Regards,

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wagnered** [comment]
ABC Family seems to be the only network that has seasons overlap years.. So I'm closing this.

**Comment by Afterster** [comment]
Ok, thank you for the investigation anyway ;).
