### ISSUE TITLE
Error in small album/artist images

### ISSUE THREAD

**Issue by robertocarlo** [ampache/ampache#731]
![screen shot 2015-02-13 at 11 52 09](https://cloud.githubusercontent.com/assets/7412863/6189191/7ed83152-b377-11e4-870c-62b3b62f4949.png)
In latest release small album/artist images do not show. Can confirm that in previous release it doesn't happened.

**Comment by Afterster** [comment]
Any Ampache / Apache logs as usual? Thanks.

**Comment by robertocarlo** [comment]
[Fri Feb 13 07:28:59 2015] [error] [client xxx.xxx.xxx.xxx] File does not exist: /webserver/souly.us.to/play/art,

**Comment by Afterster** [comment]
Ok, it looks like you enabled beautiful url but didn't setup .htaccess files correctly. You can disabled beautiful url setting if not required, or correct the .htaccess files (/play/.htaccess in this case).

**Comment by robertocarlo** [comment]
Done!

**Comment by Afterster** [comment]
Done => as it works?
If so then you should close this.

**Comment by robertocarlo** [comment]
Added .htaccess to /rest /play folders and enabled/disabled beautiful url option in streaming.
Inspecting with Firefox still got same:
"Unknown property '-moz-border-radius-topleft'.  Declaration dropped. jquery.mediaTable.css:139
Unknown property 'user-select'.  Declaration dropped. jquery.datetimepicker.css:41
Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. jquery.datetimepicker.css:43
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. index.php:1
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-corner'.  Ruleset ignored due to bad selector. index.php:1
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. index.php:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:6
Firefox can't establish a connection to the server at ws://localhost:8090/broadcast."

**Comment by Afterster** [comment]
OK but this is not related to your issue (broadcast feature setup and not-standardized css properties handled by chrome only).
Is the album art issue on web player you encountered fixed?

**Comment by robertocarlo** [comment]
No.
![screen shot 2015-02-14 at 17 46 08](https://cloud.githubusercontent.com/assets/7412863/6200998/6f8f3240-b471-11e4-9374-ed63ca266478.png)

**Comment by Afterster** [comment]
What looks like the missing image url? What in apache/ampache logs if you try to access it directly through your browser?

**Comment by robertocarlo** [comment]
Address http://souly.us.to/play/art/69b0d86140371fb6e99105d7c9f0bf1c/album/5130/thumb3.jpg
Apache log [Sat Feb 14 17:50:00 2015] [error] [client 186.136.187.128] File does not exist: /webserver/souly.us.to/play/art

**Comment by Afterster** [comment]
Ok. Then back to my first post, your .htaccess is misconfigured.

**Comment by robertocarlo** [comment]
play .htaccess is 
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>

**Comment by Afterster** [comment]
It is not up to date. It should be
```
`<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1 [L]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>
```

**Comment by robertocarlo** [comment]
Now it's fixed.
![screen shot 2015-02-14 at 17 58 22](https://cloud.githubusercontent.com/assets/7412863/6201043/236310e2-b473-11e4-85ac-fbde5b456a9c.png)

**Comment by Afterster** [comment]
Ok great, I had no other idea otherwise :)

**Comment by eephyne** [comment]
I got the same issue here, except that direct access to thumb.jpg give me an file but a corrupted one (4.7kb but no render in any software) 
php-fpm is'nt giving any errors (except for not founding mp3.min.js at the root but I don't think its related) but it say this (meaning the rewrite rules are working):

2015/02/19 09:00:11 [notice] 21755#0: *2127 "^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$" **matches** "/play/art/1d00b19b0112e2b76b29aee28ede7574/album/9892/thumb3.jpg", client: 192.168.0.254, server: XXX, request: "GET /play/art/1d00b19b0112e2b76b29aee28ede7574/album/9892/thumb3.jpg HTTP/1.1", host: "XXX", referrer: "https://XXX/index.php"

2015/02/19 09:00:11 [notice] 21755#0: *2127 rewritten data: __"/image.php"__, args: __"object_type=album&object_id=9892&auth=1d00b19b0112e2b76b29aee28ede7574"__, client: 192.168.0.254, server: XXX request: "GET /play/art/1d00b19b0112e2b76b29aee28ede7574/album/9892/thumb3.jpg HTTP/1.1", host: "XXX", referrer: "https://XXX/index.php"


if I deactivate beautiful url it work and the url is 

XXX/image.php?object_id=9892&object_type=album&auth=9afdc924c15c163b1f171d7f78cf675e&thumb=3&name=art.jpg

The difference are obvious, rewrited url miss thumb and name parameter

my rewrite rule was rewrite ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1;          

If I change it to : rewrite ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)    $ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=thumb$4.jpg; 

or rewrite ^/play/art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)    $ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg; 

it works if directly in the url but doesn't show up in the ampache page.

Sooo, I'm kind of stuck

**Comment by Afterster** [comment]
Indeed the thumb and name parameter was missing, thanks!
Are you sure it didn't work in ampache page, maybe it was a cache issue? What the http code  you get in your browser console?

**Comment by eephyne** [comment]
I'm not on my computer right now but from what I remember I didn't got any error http (I know that's weird)
By the way I discovered that thumb are missing in search box too (I simply assume that's the same URL but why other thumbs are working? )
