### ISSUE TITLE
Unable to visualize controls on movie player

### ISSUE THREAD

**Issue by robertocarlo** [ampache/ampache#732]
Latest commit will not show controls (volume/full screen) on Ampache player due to bigger tittle fonts, previous did.
This is an issue in e.g. PS3/4 because its not possible to stream movies in full screen, it can be bypassed in any laptop/pc by right clicking player and selecting "show controls" option. But it shows controls from within player, not ampache one.
![screen shot 2015-02-14 at 08 10 47](https://cloud.githubusercontent.com/assets/7412863/6199421/7cce909a-b421-11e4-96fc-593cb466d302.png)

**Comment by Afterster** [comment]
Could you try to clear your cache and try again? This should have been fixed last week with #719.

**Comment by robertocarlo** [comment]
Fixed.
