### ISSUE TITLE
Democratic playlist time column display

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#733]
When first looking at the democratic playlist there is no time column, but if a vote is remove or an entry deleted the time column appears.

**Comment by Afterster** [comment]
Mhh I'm not sure to understand. Are you sure this is not related to your screen resolution (maybe the song removed had a long title, ...?)?
Could you detail a little more otherwise? Thanks.

**Comment by stebe** [comment]
I'll give a couple of screenshots.

First I added two entries, names are not long.
![screenshot from 2015-02-15 09 07 53](https://cloud.githubusercontent.com/assets/4076671/6203475/52135d96-b4f2-11e4-9db9-74bbd478db2c.png)

Now after removing the first entry. The time column shows.

![screenshot from 2015-02-15 09 08 25](https://cloud.githubusercontent.com/assets/4076671/6203476/608843e6-b4f2-11e4-8621-2080508793fc.png)

**Comment by Afterster** [comment]
Ok I believe it is fixed with latest commit. The columns choice is applied even when media are removed from the democratic playlist.
Now I just believe "Time" column is unchecked in your columns list.

**Comment by stebe** [comment]
It was unchecked in my case. Now time is not displayed at all.
Thanks
