### ISSUE TITLE
When editing and item and after saving the save edited item is not displayed correctly

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#734]
When I edit (the gear icon), the saved item is bunched on the left side. Seen in playlists, album editing artist editing and other lists. I've cleared my cache CTRL-F5 in Firefox.

![screenshot from 2015-02-14 09 02 13](https://cloud.githubusercontent.com/assets/4076671/6199814/73587cd6-b428-11e4-91f8-32af3c8443eb.png)

**Comment by Afterster** [comment]
Mhh I cannot reproduce it. This should be related to your settings. Could you copy/past the html code (ajax loaded included), your settings and maybe try to enable/disable some feature for test purpose? Thanks.

**Comment by stebe** [comment]
screenshot of my settings
![screenshot from 2015-02-15 09 24 03](https://cloud.githubusercontent.com/assets/4076671/6203571/df276670-b4f5-11e4-9146-0c094e26663b.png)

And this is a link to the saved pages before and after editing:
https://ca.animeshare.com/owncloud/index.php/s/8vnaBLVqXtXbGou

I'll play with some of the settings and set up a new user with defaults.

**Comment by SUTJael** [comment]
Any chance to disable extensions like "pagespeed" and give a new try?

**Comment by stebe** [comment]
This is definately caused by pagespeed. As soon as I disabled this module the problem disappears. Since I don't really need this module I'll leave it disabled.

**Comment by SUTJael** [comment]
Good to know thanks.
