### ISSUE TITLE
Upload Function // Multiple Invokes of Shell Script

### ISSUE THREAD

**Issue by systems-rebooter** [ampache/ampache#736]
Hello,

When using upload function with multiple files, following not working correctly:
_Upload: run the following script after upload (current directory = upload target directory)_

Shell script invokes multiple times. For each of uploaded files. But since multiple files are uploading to the same destination, this result in running multiple script instances for the same uploaded files few times. This leads to duplicates in the mysql.

Can we limit invoking shell script only once, when upload finished, nevertheless of number of uploaded files?

Also, processing in batch mode is more preferable then 1 by 1 in case of large number of uploaded files.

Thanks!

Somehow refs #726

**Comment by systems-rebooter** [comment]
Lockfile-ing shell script right now...

**Comment by Afterster** [comment]
Unfortunately (for you at least :)) this is the excepted behavior.
But I understand your requirement, I will mark this as an enhancement.

**Comment by Afterster** [comment]
This can now be done on another way with commit a5a3e5dad015cdf7a7eb4eaedb14b1b7c004c14e. You can add the variable %FILE% to your script parameter to specify the uploaded file path.
