### ISSUE TITLE
Add same download folder for multiple file types

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#744]
Would be nice to be able to add different content (audio, video clips, movies) from a single folder automatically or in a period of time (cron job).
In my case i use transmission-daemon for downloading to a single folder and have to move files in order to add different content types from same folder.

**Comment by Afterster** [comment]
This is unfortunately not possible. Some file types require logic incompatible with others. We cannot neither distinguish with certainty the file type (how should be handled undetected video type? movie, tv shows, clip or personal video?). No solution from my point of view.

**Comment by RobertoCarlo** [comment]
Got it, but wouldn't be useful to add different content types to same folder?
Right now is not possible, e.g. if you add a folder /xxx/xxx for personal video you can't add same folder on another server.

**Comment by Afterster** [comment]
Yes, but as I explained I don't see how it could technically be done. For me it is not possible to do that in a clean way.

**Comment by RobertoCarlo** [comment]
Ampache will not allow you to repeat same folder address (/Volumes/XXX) for different content Catalogs?
If it does you can add different file types from same folder...

**Comment by Afterster** [comment]
Yes I see what you mean now, the problematic is the same.
There is technically no solution for this to identify media type accurately from my point of view.

**Comment by SUTJael** [comment]
@RobertoCarlo wouldn't be possible to write a script that move automatically media depending on your needs and then update ampache whith a cron?

**Comment by RobertoCarlo** [comment]
Thanks for your reply. Got it @SUTJael, and that would be a "non clean" solution in @Afterster words...

**Comment by Afterster** [comment]
Moving your media to subfolders and importing all different subfolders to different ampache catalog is clean. But that wasn't what you asked for ;)

**Comment by RobertoCarlo** [comment]
Yes indeed. As i´ve mentioned a long time ago i use Transmission-bt daemon along with Ampache for downloading media content, then from there i need to manually select and update to different folders.
Which is how i do it. As i didn´t knew it was not possible to implement, requested it as an enhancement.

**Comment by SUTJael** [comment]
I don't know transmission but, with my experience of sabnzbd, I was able to define a media type to each downloads. Then, for each different types, I had a specific scrypt ("post-processing") which was executed after a successful download. You may want to look to that ;)

**Comment by RobertoCarlo** [comment]
Shure. After installing sabnzbd will ask you for that post-processing script...Thanks

**Comment by Afterster** [comment]
Ok, closing then. Thank you for all your suggestion / discussion.
