### ISSUE TITLE
Can't audio seek transcoded streaming ogg format over webplayer

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#746]
Transcoding to ogg format and streaming though webplayer is working, but there doesn't seem to be the ability to seek through audio during playback.  I tried in both Firefox and Chrome [edit: Firefox works].  Audio seek with mp3 streaming, both direct and transcoded, works.  Using version 3.8.0-beta1.

**Comment by Afterster** [comment]
Could you try to disable some streaming technology in Stream settings and test one by one to identify correctly the one you're using (html5, flash, aurora.js). If aurora.js this is a known issue on Aurora.js project side.
Thanks.

**Comment by dhsc19** [comment]
It looks like the only technology setting that will stream ogg is HTML5.
When I enable Flash only, I get "unsupported" shown in the player.  When I
enable Javascript only, it won't play at all (it looks like it's about to
start, but stops shortly).  This is true for both Firefox and Chrome.

I double checked with Firefox and it looks like Firefox does allow me to
seek.  Chrome does not.



www.carlovirtucio.com

**Comment by Afterster** [comment]
I cannot reproduce your issue with ogg + chrome. I will leave it open for now in case someone else or yourself can give more information.

**Comment by dhsc19** [comment]
Thanks.  Just to be clear (for all that may be reading), I'm not talking about not being able to advance from one song to another.  I'm talking about not being able to click on the progress bar to skip to a specific time spot.  I've attached an image to help focus on the problems I'm reporting:

![webplayer_chome](https://cloud.githubusercontent.com/assets/10291198/6422498/38da2a4e-be8e-11e4-8b48-7bf7840b15ac.png)

1)  Clicking on the progress bar does not advance time position of playback.
2)  The progress bar does not show advancing time position.  It will play though a whole song and not indicate time position.  Subsequently, the "wave image" position indicator does not move.
3)  Total time shows 0:00

**Comment by Afterster** [comment]
Just reading your post again ; you're using transcoding. I believe it is the excepted behavior with chrome and it cannot be fixed Ampache side.

**Comment by dhsc19** [comment]
Ok.  Thanks for looking into it.  Hopefully Chrome will get fixed.
