### ISSUE TITLE
Statistical Graphs stay empy

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#748]
Not sure if it is a config error or something else but my Statistical Graphs always stay empty.
![image](https://cloud.githubusercontent.com/assets/4103090/6393503/f11e9d3e-bdca-11e4-8a69-4f566e983b8d.png)

Using https://github.com/ampache/ampache/commit/cfc45a83b6b402566e2309b4a54dd6d26e6a2fbf
Config:
Windows 2012 R2 with IIS 8.5
PHP: 5.6.0
MySQL: 5.6.21

**Comment by Afterster** [comment]
This graph should show you the new file addition (in size). If no addition during this time or too small, you will not show anything.

**Comment by Rouzax** [comment]
This was just an example, all my graphs are empty. 
The catalogue has grown in size in that time frame.

**Comment by Afterster** [comment]
Hits and bandwith are also empty? If so then please copy/past Ampache logs :)

**Comment by Rouzax** [comment]
Yeah they stay empty, do you want a debug level 5 and then open a page with statistics on it?

**Comment by Rouzax** [comment]
Just loaded the latest git version to start the debugging but somehow the graphs are filled now :confounded: 
![image](https://cloud.githubusercontent.com/assets/4103090/6425402/59db7416-bf27-11e4-975d-9ed86441d1fb.png)

**Comment by Afterster** [comment]
Ok weird.
Don't hesitate to reopen if you can reproduce / identify an issue ;)

**Comment by Rouzax** [comment]
Will do.
