### ISSUE TITLE
login.php redirection may be broken

### ISSUE THREAD

**Issue by Mr3ase** [ampache/ampache#752]
Hi,

At first I thought about a bad redirection in my .htaccess, but issue seems to reproduce without any .htaccess in the root ampache folder.
Example : 

Typed URL : https://xxx.domain.tld/~userdirectory/ampache/
Expected redirect from Ampache : https://xxx.domain.tld/~userdirectory/ampache/login.php
Actual redirection : https://xxx.domain.tld/ampache/login.php <= 404.

As you can see, it seems like the ~userdirectory/ path wasn't included in the path.
I'm investigating lib/init.php that might just be some broken $path variable not taking all URL types into account and I've never officially learned PHP, so you should be better at this than I am. 
Also keep in mind I haven't tried to reproduce this bug onto another server with the same kind of URL.

**Comment by Afterster** [comment]
What is your `web_path` setting in ampache.cfg.php?

**Comment by Mr3ase** [comment]
Shows like this : 

web_path = "/ampache"

Works like a charm when using my domain directly as https://domain.tld/ampache/

Is there a way to include both URL types ?

**Comment by Afterster** [comment]
You cannot have both public url at the same time. In your case `web_path` should be set to "/~userdirectory/ampache".

**Comment by Mr3ase** [comment]
Mmmh changing to web_path = "/~userdirectory/ampache/" correctly redirects both URL types actually, probably server side things.

Just using the other URL for SSL as my cert is for the entire shared server cluster. Well, I failed during config then. Thank you sir!

No user, no problems. :)
