### ISSUE TITLE
Download Artist

### ISSUE THREAD

**Issue by sphildreth** [ampache/ampache#755]
Feature Request: the ability to download all albums found for an Artist from the "Actions" list on the Artist detail page.

**Comment by SUTJael** [comment]
You can already download all albums from Artist's list and Artist details. Is this what you're looking for?

**Comment by sphildreth** [comment]
Oh I see there is a "Batch Download" for each album for an Artist. I was thinking something more along the lines of a singe "Download All Albums" button up by the "Actions" for the Artist. 

I suppose that what is there definitely works and is a valid work around. Thanks!
