### ISSUE TITLE
Single Play All for Top Rated

### ISSUE THREAD

**Issue by sphildreth** [ampache/ampache#757]
Feature request: A button to play all the songs listed in the "Top Rated" list.

**Comment by Jucgshu** [comment]
I second this one : adding action buttons would be great.

**Comment by RobertoCarlo** [comment]
Also favourited ones will be great. Or any random albums selection, e.g. "Slow Music".

**Comment by Phyks** [comment]
Kind of related to https://github.com/ampache/ampache/issues/359. Just posting to get a link to all UI issues in the "new UI" issue.

**Comment by mitchray** [comment]
If/when smartlist sorting (#293) is implemented then it would fulfill this
