### ISSUE TITLE
[Enhancement] Web player links

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#761]
Would like to see the links in the web player updated to the following

Song Title click -> Opens song details (goes to album details today)
Album Art click -> Opens album details (does nothing today)

I think it'll make more sense logically to have it operate in this way.

**Comment by Phyks** [comment]
Kind of related to https://github.com/ampache/ampache/issues/359. Just posting to get a link to all UI issues in the "new UI" issue.

**Comment by mitchray** [comment]
Currently the song title opens the song details, and an album link (see icon below) was added in 2020 so I would consider this implemented for all intents and purposes

![firefox_2YkmkhzdwW](https://user-images.githubusercontent.com/5735900/106457699-764c5580-64e3-11eb-8713-7825802b82fc.png)
