### ISSUE TITLE
DAAP not working

### ISSUE THREAD

**Issue by thegeekrv** [ampache/ampache#762]
Hey guys !

I m trying to make working ampache DAAP, but it s not working, i m using develop version.
I see the daap in itunes, but it won t dl the music list...

**Comment by Afterster** [comment]
Indeed there is an issue opened for that, see https://github.com/ampache/ampache/issues/718.
I will close the discussion here, please continue on the other thread.
Could you also try the stuff I explained in the last comment? Thank you!
