### ISSUE TITLE
Add a title to an existing playlist: no list.

### ISSUE THREAD

**Issue by davicool** [ampache/ampache#764]
Hello,
I use the Develop version of today, but the problem persists for several weeks:
- When I want to add a title to an existing playlist,
  As part of adding opens but yet none of the existing playlists appears.
It is not possible to add new titles to an existing playlist.
Thank you in advance if anyone can fix this bug.

Ampache Devel: March 10, 2015.
Internet Explorer 11: 11.0.9600.1731 - 11.0.16
Mozilla Firefox: 36.0.1
Windows 8.1 Professional

**Comment by davicool** [comment]
This produce only on users accounts, no problem for admin.

**Comment by SUTJael** [comment]
When you try to edit the title, are you logged-in with the same owner than the playlist?

**Comment by Afterster** [comment]
If the playlist doesn't belong to the user and the user doesn't have the right (admin / catalog manager) he will not be allowed to add song to the playlist. This is the normal behavior.
