### ISSUE TITLE
Right panel overlay menu displaced when window is scrolled

### ISSUE THREAD

**Issue by jpbaril** [ampache/ampache#768]
With 3.8-beta1, on Firefox 37 beta3 on Mac OS X 10.9.5, when the browser window is scrolled, in the right panel, the overlay menu is displaced far below. This makes it impossible to select options in that menu.
![capture d ecran 2015-03-12 a 20 40 44](https://cloud.githubusercontent.com/assets/5779633/6631274/9533e65c-c8f9-11e4-8a2e-8266e160e81a.png)

**Comment by SUTJael** [comment]
The class "fixedrightbarsubmenu" which is applied to the rightbar menu, when fixed options are disabled, should already handle that. Could you try to clear your cache, refresh and then see if the submenu has the ".fixedrightbarsubmenu" class? Working great on my side.

**Comment by SUTJael** [comment]
@thegeekrv, @jpbaril  BTW, I reverted the commit to the initial value, you should update before trying again :)

**Comment by jpbaril** [comment]
You are right, it seems cache was not properly emptied because after a few more click on "clear cache" and refreshes, the bug eventually disappeared.

I can only speak for what's in 3.8 beta-1, but that issue still sometimes happens when after scrolling the window down, the window is scrolled back to the top. The rightbar menu is then sometimes not positioned correctly and the submenu is again too far below.

![capture d ecran 2015-03-23 a 13 03 17](https://cloud.githubusercontent.com/assets/5779633/6785858/cdda5f64-d15e-11e4-91d4-c07f5f324375.png)

The quick fix is to simply slightly scroll down again and the menu will get positioned right again. Yet, that happens sometimes.

Hopefully this time it will not be a waste of your time.

**Comment by SUTJael** [comment]
Ok closing this as that was a cache issue. Thanks.
