### ISSUE TITLE
Complete documentation about channels and streaming

### ISSUE THREAD

**Issue by romanromeo** [ampache/ampache#771]
The documentation needs to be improved so simple users will learn to use this fantastic tool. Searching google about how to stream music with ampache you get minor help. If this function was easier for the users it would really boost ampache :)

**Comment by SUTJael** [comment]
Any chance to start writing something? Community can provide any kind of help :)

**Comment by romanromeo** [comment]
Yes, of course! I have basic knowledge, so please give me instructions, how can i help :)

**Comment by SUTJael** [comment]
Thank you ! :) You can start writing a documentation about channels and streaming with words and details a simple user will undertand easily. Then give us the content (mail, copy/paste, external resources, ...) and we will update the wiki ;)

**Comment by romanromeo** [comment]
I'm one simple user that can't make a channel work or stream music, because there is not enough documentation. :/

**Comment by SUTJael** [comment]
I thought you finally got it :) Ok so let's mark this thread as enhancement for documentation.

**Comment by dhsc19** [comment]
Yes, Ampache community, please help!  I, too, am curious about this feature, but have no clue how it works :+1:

**Comment by Afterster** [comment]
I just updated the wiki yesterday with some information about channel. You can take a look here https://github.com/ampache/ampache/wiki/Channels
