### ISSUE TITLE
load balanced web servers

### ISSUE THREAD

**Issue by brendankearney** [ampache/ampache#772]
i was running ampache on load balanced web servers, and i ran into issues.  it does not seem that the session is being shared by the two web servers.  take the below examples.  i load the page, which leverages calls to each of the web servers in my load balanced pool (balanced using "least connections").  the page paints.  i click the "Song Titles" link, and bring up the list of songs in my catalog.  so far no issue.  both web servers are giving me the content because there is nothing session specific yet.  additionally, both web servers are able to access the backend database so all calls to it are working as expected.

i pick a song from my catalog and select the "Play" blue arrow that shows to the left of the song name.  using the html5 Web Player, and iframes, the bottom iframe rises, but is blank.  the POST went to web server one, and the attempt to play the song seems to have gone to web server two, which lacks the session info and cannot play the song it does not know i picked.

if i pick a song, and click the "Add to temporary playlist" blue note with plus sign that shows to the right of the song name, the POST goes to one of the web servers, and the playlist iframe slides in from the right side of the window.  when i click the "Play" blue arrow in the playlist iframe, the iframe disappears and nothing plays.  the POST seems to go to the other web server, which does not know about the temporary playlist and which songs were added to it.

i dont have the setup currently configured, and the above scenarios are from memory, but i believe to them to be accurate.

the theory i have is that each web server maintains the session info, and i do not have them sharing the session data.  i am not sure if i am able to setup the php environment on each of the servers to share the data.  does anyone know if the session data can be sync'd between web servers?  if the session cannot be shared between web servers, can an intermediary (such as the database) be used to share the session data between web servers?

**Comment by Afterster** [comment]
Interesting subject. I personally never tried load balancing for Ampache but most data are stored into the database. I believe the issue here is php session. You should try to google for `php session load balancing` and try a workaround like https://www.digitalocean.com/community/tutorials/how-to-share-php-sessions-on-multiple-memcached-servers-on-ubuntu-14-04
But I have no knowledge of it.

**Comment by arnaudbey** [comment]
An alternative, if you can't share session correctky, would be to make your load balancer use *sticky session*, where a session/client is still assigned to a same server of your LB. 
Anyway, I've no idea how to configure that. Good luck
