### ISSUE TITLE
Content ratings function has been merged

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#773]
I had been working on a PR to merge the TV content ratings function into Michael Roterman's Tmdb php api.  The Tmdb api is now at revison 2.03. and the version in Ampache is 0.0.1.

Also,  the Moinax TvDb api has no revision history and no version number, but I noticed that The latest version contains  a  folder with the label 'http' which is required to get the api to actually retrieve the information from  the Tvdb repository.

The changes to get both Tmdb and Tvdb metadata capture functional are pretty much complete, I'm just having a little difficulty  in getting the TV content rating/Movie certifications to display and sort properly on the web page.  Now I can give more time to understanding those processes.

**Comment by Afterster** [comment]
That's great, many thanks for your work !
Don't hesitate to suggest a PR that updates dependencies if I miss to update them. I'm looking forward to see your changes ;)

**Comment by wagnered** [comment]
@Afterster, will you be updating those dependencies, or should I just include those updates when I am ready to submit the PR which requires them ?

The changes/additions are somewhat extensive.  I would like to discuss them, perhaps in the Google forum before I submit the PR.  Also, I discovered a need to create an on-the-fly modal dialog, because the Tmdb/Tvdb repositories may produce multiple results, but I'm not sure of the best way to do this.  I do have some ideas, though.

**Comment by Afterster** [comment]
It would be better that you include updates in your PR as it is related.
Current modal dialogs are in javascript file /lib/javascript/tools.js ; I believe this could be more generic.

**Comment by wagnered** [comment]
OK on including the updates with my PR.

I saw the functions in tools.js   but they are triggered from HTML input tags and mouse/keyboard events.  The (for example) onlick event triggers the showEditdDalog() which  then displays the data to be edited. 

As I understand it, PHP would have to redisplay the existing page with appended content that includes an onload() event which triggers a jQuery dialog function to produce a modal dialog.

I am also investigating the PHP-V8Js extension which provides PHP interaction with javascript/jQuery.

Then again, I might not fully understand the relationship between the server and the client.

**Comment by Afterster** [comment]
Closing this, the discussion should continue on the now existing PR #846.
Thanks ;)
