### ISSUE TITLE
Keeping disabled songs from appearing in non-admin accounts

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#774]
Is there a way to keep disabled songs from appearing in non-admin accounts?  While having a disabled track showing in the album list doesn't seem to affect playing an entire album through the web interface (it just ends up not getting entered in the playlist), it seems to have a negative affect on mobile players when choosing to play entire album that contains a disabled track.  The disabled track still appears in the list and the mobile player attempts to play it and fails.  When it fails, the player just stops instead of skipping to the next song.  I think it would be better if disabled songs are not shown at all in non-admin accounts, since they are no good anyway.  Therefore it never gets included in the playlist in the first place.

**Comment by Afterster** [comment]
This was fixed few weeks ago with commit a3c2a4336fb395f901e95bf88f97c2c11610427b.
