### ISSUE TITLE
Small UI design optimization for "add catalog" and whats the context of "Make it ready ..."?

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#777]
![radio](https://cloud.githubusercontent.com/assets/6222200/6767229/5201daf0-d025-11e4-940c-7b07675440f1.PNG)

Or

![dropdown kills the radio star](https://cloud.githubusercontent.com/assets/6222200/6767230/52049a6a-d025-11e4-971c-fec0385d101f.PNG)

?

I prefer the second. I think, it fits better the site style and reduces drastically the page width.

@SUTJael do you also plan a min-width for the new-ui? And would my mod make problems on your side?

And one question translation related... when does `show_catalog_row.inc.php:35` come into play? When is it shown on UI? I don't get it. gg
But I need a context for what it stands for...

EDIT: sh*t! Issue 777 ...  :beers: for all! :D

**Comment by Afterster** [comment]
I think the same as you do, I prefer the second too. Thanks ;)

**Comment by Psy-Virus** [comment]
I bet you answered to the e-mail, hm?
Would you do me a favour and view the whole comment? :D
Because I was to fast again with sending the comment and had to edit it. ^^

Thank you :)

**Comment by Afterster** [comment]
Sure but I'm not sure to understand your question. `show_catalog_row.inc.php` describe a catalog row, so basically it is included for each row listed in catalogs (through browse class).

**Comment by Psy-Virus** [comment]
Hmmm, I thought that ":35" after the file name gives the hint for the meant line...
Well I meant line 35, especially that "Make it ready ..." on it. Because I can't see it on the UI and don't get it by reading the code.. So I've no context for translation. If I only translate it word by word, it maybe makes no sense^^

**Comment by Afterster** [comment]
Ahh, indeed :)
This is only for catalogs that are two-step setups. For instance, Dropbox catalogs requires a manual application approval to work correctly. This will not show up on local and Ampache remote catalogs.

**Comment by Psy-Virus** [comment]
Ahhhh well okay, thx. 
Now I got it.
I'll create a PR with this and some other small changes I've made.

**Comment by SUTJael** [comment]
@Psy-Virus No problem on my side ;)

**Comment by SUTJael** [comment]
Thanks for the PR, merged ;)
