### ISSUE TITLE
[Enhancement] External music URL without ampache installation

### ISSUE THREAD

**Issue by SoTotallyXray** [ampache/ampache#783]
Would love to see a way to add External music without an ampache installation on an external webserver. this would be a neat idea.

**Comment by Afterster** [comment]
I'm not sure what you mean, could you give some details? Thanks.

**Comment by SoTotallyXray** [comment]
You can have music on another vm and you add add that via Ampache using some sort of a url, instead if having ammpache installed on that vm

**Comment by SUTJael** [comment]
+1 @Afterster would be great... ^^

**Comment by mcladyz** [comment]
WebDAV catalog plugin would be great. Owncloud, for example, has WebDAV file access.

**Comment by Afterster** [comment]
I see about WebDAV but I believe @SUTJael and @SoTotallyXray was talking about something else. Index of support or something like that?

**Comment by SUTJael** [comment]
From my side I understood the request of @SoTotallyXray with something like default Apache directory listing or FTP directory. My "^^" comment means "Ouch! Good luck with that!" :) @SoTotallyXray we need more details about your request ;)

**Comment by Afterster** [comment]
This request is invalid sorry, I'm closing it.
If you have a more specific feature request, that is technically possible, don't hesitate to open a new one.
