### ISSUE TITLE
What about live TV stations?

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#784]
Having managed to have a functional set of radio stations broadcasting live from the internet, this question arouse since in a very near future they'll all be doing this.

**Comment by SUTJael** [comment]
Well if users are requesting that why not! But of course there's already so many work to do on music part (which should be the priority) so it will not be a priority at all.

**Comment by AshotN** [comment]
I don't think this falls into the scope of Ampache. The constant barrage of new features is what made this project so hard to maintain.

@lachlan-00 if we are in agreeement we can close the issue.

**Comment by lachlan-00** [comment]
Yeah, this is a big one that I don't think would ever get done. It's really too large for any of us to do.
