### ISSUE TITLE
Albums with the same title are merged to one album

### ISSUE THREAD

**Issue by T-Rock** [ampache/ampache#788]
I have installed 3.8.0-beta1.
The configuration is nearly like default, but albums with the same name are merged to one album including all song titles from all the different albums.
This merged album also is visible for all artists from all the different albums.
The cover is the one from the latest imported album.

Is there a certain setting necessary?
And when why is it not the default?

Thanks in advance.

**Comment by Afterster** [comment]
Yes, it is related to missing Musicbrainz tags.
This is already an highly discussed subject, you should take a look on https://github.com/ampache/ampache/wiki/FAQ#albums-with-the-same-title-are-being-displayed-as-a-single-album and #462 (which also has references to other similar discussion).
