### ISSUE TITLE
Unnable to see Artist list via Subsonic API

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#791]
One the recent updates seems to have broken the Subsonic API.  When I try to browse artists using either iSub or AVsub on my iPhone or iPad, the list of artists is blank.

If I go into AVSub and choose Recently Added, Recently Played or Frequently Played, it shows me albums to pick.  But Artist browsing does not work.

I know it last worked for me on Wednesday night, so I'm thinking some committ yesterday broke it.

**Comment by Afterster** [comment]
Yep, just fixed few hours ago but thanks for the report :)
