### ISSUE TITLE
ID3 (v1 or v2?) genre tag is displayed as numerical ID under Tags column

### ISSUE THREAD

**Issue by AsavarTzeth** [ampache/ampache#792]
I have discovered a weird issue. I have some mp3 files, originally from Google Music. Metadata is stored either using ID3v1 or ID3v2 (not sure which). Since initial download I have edited the genre tags of my files, using EasyTAG.

When I add files to my catalog the Tags column display their numerical IDs instead of strings, like this:
![screendump](https://cloud.githubusercontent.com/assets/6402411/6994569/72144fae-db1e-11e4-9448-0647f3c40cb4.png)

It is also worth noting that I did not seem to have an issue with this before I edited them, so it may well be that I (or EasyTAG) have done something wrong. I have worked around this by manually correcting the tags after upload.

**Comment by wagnered** [comment]
You can try removing id3v1 from the getid3_tag_order property in the
ampache.cfg.php script.

If that doesn't work this is what I did on 3.6 or early 3.7:

I had the same problem awhile back.  I think I cured it in Easytag by
clearing the checkbox in Preferences->ID3 Tag settings->ID3v1
Tags->Write ID3v1.x tag. Then removed all the ID3v1 tags. I used a
script to scan my music folders.  Fedora has a python-eyeD3 package that
will copy the id3v1 tag information to ID3V2 then removes the ID3v1
tags.

Or you might be able to use PHP's id3_remove_tag.

This question should be asked in the Ampache Google groups first.

Ernie D

**Comment by AsavarTzeth** [comment]
I see, thank's a lot for the information.

I tried setting the `getid3_tag_order` property to exclude `id3v1`, which did nothing, then the same with `id3v2` which resulted in "Other" showing instead.

I found a _python2-eyed3_ package in the  Arch _community_ repo and I used it to identify my files (I really should have found this myself...). I have confirmed that all my mp3 files, even the ones I modified, uses id3v2.4.

Next I checked the EasyTAG preferences. There I actually found another interesting setting "Write Genre in text only", tool tip: "Don't use ID3v1 number references in genre tag. Enable this if you see numbers in your music player."

Next I tried things like this:

1. Checking "Write Genre in text only", leaving "Write ID3v1.x tag" checked.  
__Result: Genre Tag is shown properly in Ampache, as promised.__
2. Unchecking "Write Genre in text only" & unchecking "Write ID3v1.x tag".  
__Result: Genre Tag is once more showing as numerical reference.__
3. Leaving "Write ID3v1.x tag" unchecked (optional), again checking "Write Genre in text only".
__Result: For obvious reasons, same as number 1.__

So to summarize: It would seem ID3v1 was never an issue. The issue is when the tag is written as a numerical reference (ID) instead of as plain text. For some reason (I assume legacy player support), this is the default setting in EasyTAG and since I knew nothing about how this worked, just a few days ago, issues occurred.

So the real question then would be if there is any good reason for Ampache to support translating these IDs, when you import them to a catalog? Personally I don't know if this behavior is common enough with tag editors to consider this. Maybe, simply adding this information to the FAQ would be a better solution? I would be happy to write it if that is deemed a proper solution.

Regarding Google groups. Unfortunately I had no idea whatsoever that they were used by the project & have zero experience using them. Is there anything special I have to know if I am to use them? Where do I go?

**Comment by wagnered** [comment]
@AsavarTzeth The Google group is located at:

https://groups.google.com/forum/#!forum/ampache

The Ampache Google group, usage is explained on the home page, It also gives the IRC and chat addresses.

Interesting that if one searches for "Ampache" on Google, the groups do not come up within the first 3 pages, but if one searches for "Ampache group" it is the first entry. ; ' >

What I did find out is that set up of the config file is not very intuitive at all.

As for "the real question", I'll leave it up to @Afterster or one of the primary developers to respond.

**Comment by AsavarTzeth** [comment]
I just want to say I am not one of those people that don't search before I ask. In fact, I almost never dare to ask. Normally I would do way more research before I report anything, since I am uncomfortable doing do.

I think these last days have been difficult for me. Ampache does everything I want, but the learning curve have been quite high. That might have caused me to comment a bit to quickly.

In any case, I am glad we both we learned from this. Oh, and I don't use Google as my main search engine, so I don't get those Google biased results :P
