### ISSUE TITLE
Streaming doesn't work on iPhone5s with IOS 8.1.3

### ISSUE THREAD

**Issue by jeffkennedy5** [ampache/ampache#793]
I may not have something configured correctly with my phone or the server settings, so, please let me know if I just need to change some settings on my Ampache server and/or my phone.

I can't seem to get Ampache to actually play on my iPhone 5s in streaming mode or even with trying to download the song. I know that the server works correctly because I can listen to the stream on my laptop with Firefox. I can also download the file on my Firefox browser and play the downloaded file, so, it doesn't seem that the issue is with the Ampache server not working correctly.

Things I have tried on my iPhone 5s:
1. iAmpache: I still have this app on my phone, but it freezes on the page before I can even navigate to any songs to attempt to play.
2. AmpacheX: I bought this application, but it freezes on a screen right after I added the IP address of my local LAN instance of Ampache, which was, in my case http://192.168.1.4/Ampache.
3. Safari web browser on my iPhone: everything looks okay in terms of navigation, but after I click the 'play' icon, I hear the hard drive on my server spin up like it is serving a stream, but no sound comes out of my iPhone.... I've tried to ensure that the phone's volume settings are not muted in any way, but nothing....

Are there some settings I can try that are known to work with iPhone 5s IOS 8 and Ampache that others have had success with? I really want to use my primary phone with Ampache if there is any way possible. If not, what mobile devices might I consider that work well with Ampache?

**Comment by SUTJael** [comment]
Hi @jeffkennedy5, there's some talks about IOS clients on [google groups](https://groups.google.com/forum/?hl=fr#!topic/ampache/V3OvHDbUsC0). You should ask there for any kind of help with IOS clients (Andy seems to have all working by the way, I think he can guide you)

**Comment by jeffkennedy5** [comment]
Thanks! 
Just as a follow-up on my findings, for the benefit of anyone else that finds this thread. I've found that Ampache's SubSonic Backend feature works well with iPhone 5 and IOS 8 using the AVSub app from the Apple App Store on the iPhone. I don't yet have FLAC streaming working, but I think that is a configuration issue I need to work through on my specific environment.
