### ISSUE TITLE
[Enhancement] Ignore List for Random

### ISSUE THREAD

**Issue by sphildreth** [ampache/ampache#794]
A request to have the ability to create a comma seperated list of artists to ignore, like "Kiss, The Beach Boys" in User preferences/settings.

I love the random feature (both random song and random album) but there are some artists that I *really* dislike. It would be great if this feature would skip these artists from the random feature. My ampache is used by my entire family and some of them love these artists - which I can't stand.

Thanks!

**Comment by SUTJael** [comment]
We already need to work on being able to split/hide artists per users. I think that functionnality will handle your request ;)

**Comment by Afterster** [comment]
I agree, this should be handled as describe in https://github.com/ampache/ampache/issues/308 (otherwise it will take too much resources and will be duplicate).
If this solution is ok for you (in theory, not available now), please close this issue ;)
