### ISSUE TITLE
Share link via Subsonic API discrepancies

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#795]
Hi!  Just wanted to pass along this info.  DSub dev has recently made a workaround, but maybe there's something that can also be done on the Ampache side to make it more compliant.

https://github.com/daneren2005/Subsonic/issues/482

**Comment by Afterster** [comment]
This is not part of SubSonic API specification, I believe we shouldn't add unnecessary additional stuff. I will close it as it will not be done, but please comment here again if someone found a similar issue with another SubSonic player.
