### ISSUE TITLE
Unable to sort album by year from Subsonic API because of missing parameter

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#796]
DSub mobile app cannot sort album by year instead of by name because Ampache is missing the year information in the proper field.

Please see:

https://github.com/daneren2005/Subsonic/issues/485

**Comment by daneren2005** [comment]
Example child record from Subsonic:

    <child id="41058" parent="147" isDir="true" title="Behind Silence and Solitude" album="Behind Silence and Solitude" artist="All That Remains" year="2002" genre="Metal" coverArt="41058" userRating="3" averageRating="3.0" created="2015-03-21T03:13:20.000Z"/>

**Comment by SUTJael** [comment]
@daneren2005 do you see any other field we are missing and which would be supported by your app? (to add them at the same time)

**Comment by daneren2005** [comment]
Genre also appears to be missing, though DSub doesn't really use that anywhere but in the Details dialog so it's not such a big deal.  Other than that everything looks good.

**Comment by Afterster** [comment]
Year and Genre on albums fixed. Thanks for the report guys ;)
