### ISSUE TITLE
Subsonic API returning same value for album and artist (name)

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#798]
Retrieving "Show Album" and "Show Artist" in mobile app is directed to the same screen (Album screen) because "album" and "name" fields are both returning album name.  Whereas "name" should be the artist name.  At least, that's how I understood it (I may be completely wrong).

Please see:

https://github.com/daneren2005/Subsonic/issues/487

**Comment by Afterster** [comment]
Hum, wrong commit ref sorry.

**Comment by daneren2005** [comment]
I added more information to the DSub issue ticket.  The name of this issue is incorrect upon further inspection.  Sorry for giving the wrong initial assumption.

**Comment by Afterster** [comment]
Fixed now. Thanks for the report @dhsc19 and thanks for the really helpful details @daneren2005.

**Comment by dhsc19** [comment]
Just tried it.  Had to clear the mobile app cache, but it is now working perfectly.  Thanks again, @Afterster and @daneren2005 for the great work.

**Comment by gerroon** [comment]
I am trying to use Dsub with Ampache and I am getting "The requested data was not found". COuld it be related to this one?

**Comment by dhsc19** [comment]
What sequence of steps are you doing to produce this error?
