### ISSUE TITLE
Pdf epub mobi reader?

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#804]
Will also allow to have a full multimedia experience with ampache, and might be easy to implement from freeware.

**Comment by SUTJael** [comment]
Hum could you explain your pov?

**Comment by apastuszak** [comment]
I think what he's getting at is that some albums purchased digitally contain the "booklet" that came in the CD case as a PDF.

It would be kind of cool to have something like the iTunes LP format for Ampache, where you can add "extras," such as photos, video clips, liner notes, etc.

**Comment by RobertoCarlo** [comment]
Right there, but also you own private book collection.

**Comment by apastuszak** [comment]
You want to catalog books, use Calibre.  You can then use Calibre2ODPS to
export to a web page.

**Comment by Jucgshu** [comment]
Also COPS is a great project which works with Calibre librairies : https://github.com/seblucas/cops

**Comment by Afterster** [comment]
I don't know about that. Video support was already a big discussion on the 'should Ampache do that?' subject. Adding book and even image gallery support could match Ampache scope in a way it is multimedia. But that would make Ampache bigger and outside its current scope for now. If one day this is done anyway, it should be in a flexible way so media types could become optional modules (this is not the case today, you can disable some features but they are not modules).

**Comment by joshp23** [comment]
I realize that this is old thread, but Calibre works well on it's own for this. All you need is  to set up a headless Calibre server, and run it via a proxy in apache. Perhaps a plugin could nest calibre into ampache in a way?

**Comment by Afterster** [comment]
My opinion is that Calibre and Ampache should be installed side by side.

Closing feature requests that looks too specific / outside Ampache scope to refocus the effort. That's one, sorry for you!
Feel free to reopen this issue once the tracker become empty ;).
