### ISSUE TITLE
Artists mixed up if same album name?

### ISSUE THREAD

**Issue by sphildreth** [ampache/ampache#807]
I have song from "Zeds Dead" with the album "Somewhere Else" and the "Somewhere Else" album by Marillion.

So I click on "Random" -> "Song" and "Marillion" starts playing. I click on the song title and it shows me the album it thinks the song belongs to along with songs from the other artist? 
![Mixed Up Artists](http://s27.postimg.org/uannwxwsj/mixed_up_artists.png)
Thoughts?

**Comment by Afterster** [comment]
This is not an issue :)
There was already several interesting discussion about this subject. You should first read https://github.com/ampache/ampache/wiki/FAQ#albums-with-the-same-title-are-being-displayed-as-a-single-album

**Comment by sphildreth** [comment]
Humm. That seems weird. But Ok.
