### ISSUE TITLE
Cannot login: Unable to read session from key

### ISSUE THREAD

**Issue by odergut** [ampache/ampache#809]
Since this morning, I cannot log in to my Ampache installation. The log says:

```
2015-04-20 08:27:35 [ampache] (session) -> Unable to read session from key kl7a65u5ikt21bjvgfa7stesra no data found 
2015-04-20 08:27:35 [ampache] (UI::access_denied) -> Access Denied:x.x.x.x is not in the Interface Access list 
````

I have tried to use the latest development version, but the problem persists. What can I do?

**Comment by Afterster** [comment]
Looks like you removed web access from ACL.
You should try to add manually the required ACL in database, like
```sql
INSERT INTO `access_list` (`name`, `start`, `end`, `level`, `type`, `user`, `enabled`) VALUES
('DEFAULTv4', '\0\0\0\0', 'ÿÿÿÿ', 75, 'interface', -1, 1),
('DEFAULTv4', '\0\0\0\0', 'ÿÿÿÿ', 75, 'stream', -1, 1),
('DEFAULTv4', '\0\0\0\0', 'ÿÿÿÿ', 75, 'rpc', -1, 1),
('DEFAULTv6', '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0', 'ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ', 75, 'interface', -1, 1),
('DEFAULTv6', '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0', 'ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ', 75, 'stream', -1, 1),
('DEFAULTv6', '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0', 'ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ', 75, 'rpc', -1, 1);
```

**Comment by odergut** [comment]
Thanks for the hint, but unfortunately, this did not solve the problem. I found out, that the problem occurs only with some machines (i.e. those my workplace).

**Comment by Afterster** [comment]
Yep, I fixed it 3 days ago. This was a major issue on fresh installation, sorry it got me so much time to find it. Thanks ;)
