### ISSUE TITLE
Can't seem to stream channel using ogg

### ISSUE THREAD

**Issue by dhsc19** [ampache/ampache#810]
I was able to successfully set up and stream a channel using mp3 stream type, but it doesn't seem to work if I try with ogg.  Ampache seems be initiating transcoding, my media player seems to be connecting, but no music coming though.

2015-04-20 17:11:35 [ampache] (channel) -> Now listening to /Music/Rush/Caress of Steel/01 Bastille Day.mp3.
2015-04-20 17:11:35 [ampache] (stream.class.php) -> Starting transcode for {/media/serverhdd/backup_source/netstore/Music/Rush/Caress of Steel/01 Bastille Day.mp3}. Type {ogg}. Options: Array
2015-04-20 17:11:35 [ampache] (stream.class.php) -> (
2015-04-20 17:11:35 [ampache] (stream.class.php) ->     [bitrate] => 64
2015-04-20 17:11:35 [ampache] (stream.class.php) -> )
2015-04-20 17:11:35 [ampache] (stream.class.php) -> }...
2015-04-20 17:11:35 [ampache] (media) -> Explicit format request {ogg}
2015-04-20 17:11:35 [ampache] (media) -> Transcode settings: from mp3 to ogg
2015-04-20 17:11:35 [ampache] (media) -> Command: ffmpeg Arguments: -i %FILE% -vn -b:a %SAMPLE%K -c:a libvorbis -f ogg pipe:1
2015-04-20 17:11:35 [ampache] (stream) -> Final transcode bitrate is 64
2015-04-20 17:11:35 [ampache] (stream) -> %MAXBITRATE% not in transcode command
2015-04-20 17:11:35 [ampache] (stream) -> %RESOLUTION% not in transcode command
2015-04-20 17:11:35 [ampache] (stream) -> %QUALITY% not in transcode command
2015-04-20 17:11:35 [ampache] (stream) -> Transcode command: ffmpeg -i '/Music/Rush/Caress of Steel/01 Bastille Day.mp3' -vn -b:a 64K -c:a libvorbis -f ogg pipe:1

**Comment by mrpurplenz** [comment]
In my freshly installed system (3.7.0) libvorbis tries (and fails) to transcode to ogg.  For me the solution was to go to the config file and edit  the encode_args_ogg line.
I replaced "%SAMPLE%K" with  "max\(%SAMPLE%K\,45K\)"
For some reason sample rates less than 45K (such as the default 32K) crash libvorbis. This hack limits the low end to 45K which doesnt crash libvorbis. I dont know if it wil fix your problem but it will fix this bug in a default ubuntu install.

**Comment by mrpurplenz** [comment]
Oh wait... I see your bit rate was already 64K... Sorry mane. I'll repost my comment as a seperate bug.

**Comment by Afterster** [comment]
Could you try the generated ffmpeg command line in the shell to see if it is working outside Ampache?

**Comment by dhsc19** [comment]
The command works in shell and I am able to stream ogg without a problem for normal playback.

**Comment by Afterster** [comment]
Works on my side. Could you try with VLC on add the VLC debug interface to see what is happening client side? Thanks.

**Comment by dhsc19** [comment]
Here is my log for VLC.  When creating the channel, I put "ogg" as stream type.  But it looks like VLC is trying to use MP3 demux?

core debug: adding item `http://127.0.0.1:8201/stream.ogg' ( http://127.0.0.1:8201/stream.ogg )
core debug: processing request item: http://127.0.0.1:8201/stream.ogg, node: null, skip: 0
core debug: rebuilding array of current - root Playlist
core debug: rebuild done - 1 items, index 0
core debug: starting playback of the new playlist item
core debug: resyncing on http://127.0.0.1:8201/stream.ogg
core debug: http://127.0.0.1:8201/stream.ogg is at 0
core debug: creating new input thread
core debug: Creating an input for 'http://127.0.0.1:8201/stream.ogg'
core debug: requesting art for http://127.0.0.1:8201/stream.ogg
core debug: using timeshift granularity of 50 MiB, in path 'C:\Users\Carlo\AppData\Local\Temp'
core debug: `http://127.0.0.1:8201/stream.ogg' gives access `http' demux `' path `127.0.0.1:8201/stream.ogg'
core debug: specified demux `any'
core debug: creating demux: access='http' demux='any' location='127.0.0.1:8201/stream.ogg' file='\\127.0.0.1:8201\stream.ogg'
core debug: looking for access_demux module matching "http": 12 candidates
core debug: no access_demux modules matched
core debug: creating access 'http' location='127.0.0.1:8201/stream.ogg', path='\\127.0.0.1:8201\stream.ogg'
core debug: looking for access module matching "http": 21 candidates
http debug: querying proxy for http://127.0.0.1:8201/stream.ogg
http debug: no proxy
http debug: http: server='127.0.0.1' port=8201 file='/stream.ogg'
core debug: net: connecting to 127.0.0.1 port 8201
core debug: connection succeeded (socket = 1612)
core debug: meta ok for (null), need to fetch art
core debug: looking for meta fetcher module matching "any": 1 candidates
lua debug: Trying Lua scripts in C:\Users\Carlo\AppData\Roaming\vlc\lua\meta\fetcher
lua debug: Trying Lua scripts in C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher\tvrage.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher\tvrage.luac
core debug: no meta fetcher modules matched
core debug: searching art for http://127.0.0.1:8201/stream.ogg
core debug: looking for art finder module matching "any": 2 candidates
lua debug: Trying Lua scripts in C:\Users\Carlo\AppData\Roaming\vlc\lua\meta\art
lua debug: Trying Lua scripts in C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
qt4 debug: IM: Setting an input
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
core debug: no art finder modules matched
core debug: art not found for http://127.0.0.1:8201/stream.ogg
core debug: looking for meta fetcher module matching "any": 1 candidates
lua debug: Trying Lua scripts in C:\Users\Carlo\AppData\Roaming\vlc\lua\meta\fetcher
lua debug: Trying Lua scripts in C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher\tvrage.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\fetcher\tvrage.luac
core debug: no meta fetcher modules matched
core debug: searching art for http://127.0.0.1:8201/stream.ogg
core debug: looking for art finder module matching "any": 2 candidates
lua debug: Trying Lua scripts in C:\Users\Carlo\AppData\Roaming\vlc\lua\meta\art
lua debug: Trying Lua scripts in C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
lua debug: skipping script (unmatched scope) C:\Program Files (x86)\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
core debug: no art finder modules matched
core debug: art not found for http://127.0.0.1:8201/stream.ogg
http debug: protocol 'HTTP' answer code 200
http debug: Content-Type: audio/mpeg
http debug: Icy-Notice: 
http debug: Icy-Name: Dramarama
http debug: Meta-Info: icy-url: https://xxx.xxxxxxx.xxx/ampache
http debug: Icy-MetaInt: 16000
http warning: ICY metaint=16000
http debug: Meta-Info: x-audiocast-server-url: https://xxx.xxxxxxx.xxx/ampache
http debug: Meta-Info: x-audiocast-name: Dramarama
http debug: Meta-Info: x-audiocast-description: Vinyl
http debug: Meta-Info: x-audiocast-url: https://xxx.xxxxxxx.xxx/ampache
http debug: Meta-Info: x-audiocast-bitrate: 128
http debug: Meta-Info: x-audiocast-public: 1
http info: Raw-audio server found, mp3 demuxer selected
http debug: auto re-connect enabled
core debug: using access module "http"
core debug: Using stream method for AStream*
core debug: starting pre-buffering
core debug: received first data after 1009 ms
core debug: pre-buffering done 512 bytes in 1s - 0 KiB/s
core debug: looking for stream_filter module matching "any": 6 candidates
core debug: no stream_filter modules matched
core debug: looking for stream_filter module matching "record": 6 candidates
core debug: using stream_filter module "record"
core debug: creating demux: access='http' demux='mp3' location='127.0.0.1:8201/stream.ogg' file='\\127.0.0.1:8201\stream.ogg'
core debug: looking for demux module matching "mp3": 66 candidates
es debug: detected format mpga
core debug: looking for packetizer module matching "any": 23 candidates
core debug: using packetizer module "mpeg_audio"
mpeg_audio debug: emulated startcode (no startcode on following frame)
es debug: did not sync on first block
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 1033 > 1032 (emulated startcode ?)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
http debug: New Icy-Title=Dramarama-Classic Rot
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 5763 > 5762 (emulated startcode ?)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 2057 > 2056 (emulated startcode ?)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 1545 > 1544 (emulated startcode ?)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 2091 > 2090 (emulated startcode ?)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 1923 > 1922 (emulated startcode ?)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: free bitrate mode
mpeg_audio debug: frame too big 2091 > 2090 (emulated startcode ?)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode (no startcode on following frame)
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
mpeg_audio debug: emulated startcode
core debug: incoming request - stopping current input
core debug: socket 1612 polling interrupted
core debug: using demux module "es"
core debug: looking for meta reader module matching "any": 2 candidates
lua debug: Trying Lua scripts in C:\Users\Carlo\AppData\Roaming\vlc\lua\meta\reader
lua debug: Trying Lua scripts in C:\Program Files (x86)\VideoLAN\VLC\lua\meta\reader
lua debug: Trying Lua playlist script C:\Program Files (x86)\VideoLAN\VLC\lua\meta\reader\filename.luac
core debug: no meta reader modules matched
core debug: `http://127.0.0.1:8201/stream.ogg' successfully opened
core debug: object waitpipe triggered
audioscrobbler debug: No artist..
core debug: removing module "es"
core debug: removing module "mpeg_audio"
core debug: removing module "record"
core debug: removing module "http"
core debug: incoming request - stopping current input
core debug: dead input
qt4 debug: IM: Deleting the input

**Comment by Deathcow** [comment]
I have the same problem: Ogg works for normal streaming, but not for broadcast/channel. Only with Mp3 the channel plays music.

**Comment by Afterster** [comment]
Mhh @Deathcow, I will give a try about this chunks change. This is more related to #827 btw.
Thanks for vlc log @dhsc19, I believe I found the issue. This is coming from undeclared variable use on https://github.com/ampache/ampache/blob/develop/bin/channel_run.inc#L184

I will fix it later in the day/week, thanks.

**Comment by Deathcow** [comment]
@Afterstar Thanks for looking into this. Yeah `$transcode_to` should probably be replaced with `$channel->stream_format` there. Even when setting the correct mime-type manually though (I tried application/ogg, audio/ogg, audio/vorbis) music will not play for me.

**Comment by Afterster** [comment]
Yeah it looks like current channel stream implementation is too simple. Ogg indeed needs an header as describe here http://xiph.org/ogg/doc/oggstream.html
Thanks for your tests, now we should:
 * determinate the real header chunk length and keep it in memory as in your test
 * Adapt the chunk length to the excepted size according to transcode settings

The IDs thing is related to how we generally manage data into the database in ampache, we never allow to override the sql identifier at any place.

**Comment by Deathcow** [comment]
Hello! I finally got Ogg to work. It was a lot of work but also lots of fun.

See the pull request for further info: https://github.com/ampache/ampache/pull/872

Sorry for the large amount of changes. If I had used Git from the beginning this should have been multiple commits.

**Comment by Afterster** [comment]
I merged @Deathcow pull request which is working fine on my side.
@dhsc19 could you confirm it fix this issue?

**Comment by dhsc19** [comment]
Confirming.  It is working for me.  Thank you, both!
