### ISSUE TITLE
Default install from source in ubuntu cant transcode to ogg untill i force sample rate >44K

### ISSUE THREAD

**Issue by mrpurplenz** [ampache/ampache#811]
Hi, I just downloaded and install 3.7.0 in ubuntu. I'm still loving it - and I cant believe the improvements since I was here last - supa! Just wow.
Unfortunately:
In my freshly installed system (ampache 3.7.0/ubuntu server 14.04 LTS) libvorbis tries (and fails) to transcode to ogg. For me the solution was to go to the config file and edit the encode_args_ogg line.
I replaced "%SAMPLE%K" with "max(%SAMPLE%K\,45K)"
For some reason sample rates less than 45K (such as the default 32K) crash libvorbis. This hack limits the low end to 45K which doesnt crash libvorbis. I'm not sure  where the fix should go or whether "ubuntu/libvorbis" is considered too unique to solve the problem in a general way. I dont think the best solution is for ubuntu users to have a broken ogg transcode and have to hack the solution into the ogg encode args though. Perhaps upping the default 32K to 45K %SAMPLE% value? with a note about oggs not working below 45?

**Comment by Afterster** [comment]
I understand your issue but I don't see any generic way to fix it. Maybe the default bitrate is already too low by the way (should we set 64K instead 32K by default in Ampache?)

**Comment by dhsc19** [comment]
I think official Xiph.org Foundation vorbis can only go as low as 45k anyway.

**Comment by Afterster** [comment]
Changed to 64k by default which makes more sense and should fix this. Thanks for the report.
