### ISSUE TITLE
social integration

### ISSUE THREAD

**Issue by a7medo778** [ampache/ampache#813]
hello there
ampache is very much more than a personal media streamer now, most servers has multiple users now sharing the same library, liking rating and listening to different tracks, so why not make them connect together

for starters, sign in using your twitter/facebook getting simple profile for eachuser (his name, avatar), users should be able to friend/unfriend other users, enabling them to follow what are those users listening and liking, enhancing the discovery within ampache 

and from that integrate other ampache feature into the user feed/friends system, channels and democratic would make whole lot more sense with ampache serving multiple users...etc etc

would love to get some feedback to even improve this idea further

regards
ahmad

**Comment by Afterster** [comment]
I just added few features in that way. You have now a better user page, private messages and user follow/unfollow.
That's the first step, it still needs improvement. If you are not in a hurry you will see it one day ;)

**Comment by a7medo778** [comment]
AWESOME :dancer: 
thats really really good news, i will integrate it into the planned app immediately :dash: 
any api's to support the functions ? 
social auth for login/registration, activity timeline should be next :D

**Comment by a7medo778** [comment]
any idea which api's can be used to access the new features ?

**Comment by Afterster** [comment]
By API you means Ampache API, Subsonic API, ... I believe. Well for now no API can be used to access this information. If you need it I can extend Ampache API with it but that's all as we don't want to fork other existing API. Please let me know.

**Comment by a7medo778** [comment]
yes please, the features are almost useless sitting on the web only

completely agree on the no forking policy, all efforts should be concetrated in 1 place

**Comment by a7medo778** [comment]
any updates m8's :P

**Comment by Afterster** [comment]
Not yet.
There is hundred of requests before this one, and even creation date doesn't mean anything, bug fix are always handled in priority. Be patient :).

**Comment by Afterster** [comment]
I just added user, followers, following and last_shouts XML API functions. Is that what you excepted about the API improvement?

**Comment by a7medo778** [comment]
AWESOME !! 
i am going to try to integrate it into the apps, (gonna start with these to be honest) and give you the feedback
are they added to the wiki yet ? what does last shouts return ? the feed of the user will include his likes, listens (including playlists) and ratings
ofcourse i am mashing them up in a timeline style with all other people your following

**Comment by Afterster** [comment]
Yes I added it to the wiki ; btw API documentation should be improved in a more modern API style one day.
Last shouts will return last shouts posted (globally or per user ; date, text and username). There is no way to filter per catalog in the api.

**Comment by a7medo778** [comment]
Mmmmm, I guess I have to do it through tags maybe
Or set up them up as remote catalogs (since I am using networked storage anyway) and target the remote catalog directly, but will the main server render the statistics then ?

**Comment by a7medo778** [comment]
afterster, i think we need a "follow" and "unfollow" api aswell, currenly we are only retreiving those
and an avatar (display picture) update api (missing from subsonics)

**Comment by Afterster** [comment]
Timeline / friends timeline was added and also available on XML API with ca2028256a93cb8d8de05f280942a4a52beb1821 (toggle_follow added to the api too).

**Comment by a7medo778** [comment]
you just made my day m8 :D

**Comment by kumardippu** [comment]
Hi , I have successfully integrated the Hybrid Social Auth api.
Problem is that when some one want to create the <iframe></iframe> of my website to their own website then it creates problem during login.
Is there any solution ?

**Comment by Afterster** [comment]
@kumardippu this has nothing related to this issue, you're missing accurate information and I'm not sure to understand you correctly. If your issue is related to Ampache project development, feel free to open a new thread.

**Comment by Afterster** [comment]
I will consider this done. Any improvement request should have a specific thread.
