### ISSUE TITLE
Float over text for options/settings

### ISSUE THREAD

**Issue by mrpurplenz** [ampache/ampache#814]
I think a useful feature would be for settings to have a float over text. or a clickable popup detailed description.
For example when floating over the "Use beautiful stream url" setting in the preferences/options spacde a little float over text could appear and say what that settting actually means.

**Comment by Psy-Virus** [comment]
Hey @mrpurplenz,
That's already planed ad discussed in #535 :-)
So You're not alone :+1:

**Comment by Afterster** [comment]
Indeed, it will be done one day :)
