### ISSUE TITLE
Use beautiful stream url is borked

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#815]
Hi

When I enable Use beautiful stream url I cant play anything off my server using streaming. I am on https server maybe that is the issue?

Web player works but streaming to apps do not.

I am using apache on Linux, Ampache 3.8.0-develop

**Comment by Afterster** [comment]
Again here, this is related to url rewriting ;)

**Comment by Afterster** [comment]
Is this still an issue on your side? If so please check .htacess files and your url rewriting settings, otherwise you can close it. Thanks.

**Comment by Afterster** [comment]
Definitelly an url rewriting issue, closing it as it is already discussed several time.
