### ISSUE TITLE
Smart Playlist - Unrated Songs 

### ISSUE THREAD

**Issue by buck2825** [ampache/ampache#819]
it would be nice to have smart playlists show songs that are not rated.  no rating is less than 3 stars, for example.  also be able to build a list of songs that have no rating.  

Ampache 3.8.0-develop

**Comment by Combustible** [comment]
Agreed, I'd really like to be able to search for unrated songs. I was hoping that @Afterster's recent commit df0c09e would fix this, but as far as I can tell it is still impossible to search for unrated entities.
