### ISSUE TITLE
confusing LDAP documentation

### ISSUE THREAD

**Issue by T-Rock** [ampache/ampache#820]
the LDAP docu starts with:

> Ampache can have multiple authentication methods at the same time. It will try them in the order they are listed until a match is found. If you would like it to try ldap first, and then fall back on mysql simply set auth_methods as follows.

> auth_methods = "ldap,mysql"

but then in "Tips and Gotchas with LDAP" it says:

> To allow multiple authentication sources, use multiple 'auth_methods' statements--the variable name is somewhat misleading, it is NOT an array or comma-separated list of values. To authenticate with both ldap and mysql, use both 'auth_methods = "ldap"' and 'auth_mthods = "mysql"' in your config file. This is recommended, as it will allow authentication against a MySQL database in the event the LDAP server cannot be reached, or vice versa

The first example works fine, so what is going on with the second recommendation?

**Comment by Afterster** [comment]
The first method is the good one, I don't know who wrote that wrong tip...
Fixed now, thanks for the report!
