### ISSUE TITLE
LDAP: more than one ldap_filter

### ISSUE THREAD

**Issue by T-Rock** [ampache/ampache#821]
Is it possible to use more than one ldap_filter?
How would the configuration look like?

**Comment by Afterster** [comment]
It is not possible due to the line
`$sr = ldap_search($ldap_link, $ldap_dn, "(&(objectclass=$ldap_class)($ldap_filter=$username))");` which except only one filter. Any suggestion are welcomed :)

**Comment by T-Rock** [comment]
Other applications require to define the complete filter, not just the attribute used in the filter.
For example instead of `ldap_filter = "mail"` it should be `ldap_filter = "(mail=$username)"`.
Therefore the filter can be flexible extended like `ldap_filter = "(|(mail=$username)(alias=$username))"`.
Maybe the line in auth.class.php is then:
`$sr = ldap_search($ldap_link, $ldap_dn, "(&(objectclass=$ldap_class)$ldap_filter)");`

As another example in the configuration of proftpd this looks like `"(|(mail=%v)(alias=%v))"`.

My workaround right now is as follows:
- I added a new parameter `ldap_filter1 = "alias"` in ampache.config.php
- I added this line in the ldap configuration in auth.class.php: `$ldap_filter1    = AmpConfig::get('ldap_filter1');`
- I changed the line from above to: `$sr = ldap_search($ldap_link, $ldap_dn, "(&(objectclass=$ldap_class)(|($ldap_filter=$username)($ldap_filter1=$username)))");`

**Comment by Afterster** [comment]
Ok thanks for the details, I will do the change as suggested.
