### ISSUE TITLE
LDAP documentation

### ISSUE THREAD

**Issue by T-Rock** [ampache/ampache#822]
In "Tips and Gotchas with LDAP" the following is mentioned:
> Valid values for auto_user are "0" for guest, "25" for user, and "100" for admin.

Is this correct?

In ampache.cfg.php is written:
> ; POSSIBLE VALUES: guest, user, admin
> ; DEFAULT: guest
> auto_user = "user"

**Comment by Afterster** [comment]
Yep, wiki fixed. Thanks again ;)

**Comment by T-Rock** [comment]
Thank you for your fast reply and anyway thank you for overtaking the project as it was nearly dead. :-)

I think you should also delete the half sentence in between, because it could be misleading:
"... , but the possible values are incorrectly specified ..."

That's it, now I am done with this part of the docu.  ;-)
