### ISSUE TITLE
SUBSONIC/DSUB client Playlist error in Ampache

### ISSUE THREAD

**Issue by cloudcoder2** [ampache/ampache#823]
Hi 
i am sory if i am a late comer to this platform or too ate to ask this .
I cannot save any playlist with subsonic or dsub with ampache .

Fatal error: Call to undefined function boolean() in /var/www/html/ampache/lib/class/subsonic_api.class.php on line 853

ca you please help me to solve this problem.
Thankyou

**Comment by Afterster** [comment]
I believe you're using 3.7.0? This is fixed in current develop branch normally.

**Comment by cloudcoder2** [comment]
Hi, I tested in latest version (3.80). But i am finding problem.I can only create playlist from same album.
When i tried to add song from another album i am only finding "create playlist". So i have to create different playlist for different albums each time tried to add songs .Even from same album if i tried to add songs to play list , i have to create separate playlists. Thankyou

**Comment by Afterster** [comment]
I think this is related to recent (and another) issue. See https://github.com/ampache/ampache/issues/880.
