### ISSUE TITLE
Synchronous channel play

### ISSUE THREAD

**Issue by Peajee** [ampache/ampache#827]
While using both the Broadcast and the Channels features, I realized that the ting I was looking for was a mixture of both: Have multiple Channels with fixed Playlists, and have all devices listening in on one channel play the exact same song at the exact same time without any shift (or at least minimal). 

As far as I have experienced, that is not the case with the normal Channels feature. One device Plays Song A while the other one, newly connected already plays Song E even when setting the caching time to 0 ms. 

Is there a way to do this synchronous play with Ampache?

I am sorry, should I have missed some settings while looking through the wiki!

**Comment by Afterster** [comment]
That is what Channel feature should normally do.
But current implementation is bugged, all clients are treated equally (the last connected client will start listening from the end of transfered buffer to previous clients, which is not equals to what is currently played on client side) whereas we should manage a buffer status per client.

**Comment by Peajee** [comment]
Thank you for answering so fast and for officially marking as a bug!
Glad to see, I didnt do something horribly wrong with my configuration :-)

May I ask how complicated and timeconsuming it will be to fix this?

**Comment by Afterster** [comment]
PHP is not well suited for this task. There was some review with #810 and I don't think we will go further for now.
If you really want a solid webradio stream, you should link Ampache to Icecast or similar software. See (Ampache on Icecast)[https://github.com/ampache/ampache/wiki/Ampache-on-Icecast]for instance.
