### ISSUE TITLE
[3.8.0] adding to catalog status indication

### ISSUE THREAD

**Issue by stonie08** [ampache/ampache#828]
When using the "Add" action in the "Show Catalogs" menue, one gets the 
"Catalog Update started...
Continue" 
Message and some kind of progress as a notification at the bottom of the screen.

But I'm missing some kind of indication that the adding is done. Also the continue button is available all the time and one is tempted to press it (maybe canceling the process?).

**Comment by Afterster** [comment]
Catalog update on web ui changed a lot in 3.8.0 as you noticed. You can click on "continue" and it will not stop.
At the end of the update you should receive a "done" notification which only appears during few seconds.
