### ISSUE TITLE
Reason for using original_name to store movie title trimmed for prefix?

### ISSUE THREAD

**Issue by wagnered** [ampache/ampache#832]
Sorry I've been taking so long on the Video/Tmdb/Tvdb enhancement, but I've had a number of set-backs including Linux Eclipse/xdebug stopped working and I lost some of the work.  I did get Eclipse debug to work in Windows, so that's how I am working on the enhancements now.

Anyway, I started rethinking the whole movie/TV show aspect and was wondering why the original_name column is used to store a trimmed version of the title.

The original name can be very different from the title when a version is released in a different country.

As the trimmed movie title is not used for searching, it is not necessary to store.

The original_name could also be used as a switch for searching for a movie.

For those reasons I would like to do the work to store and possible display the original name, if provided.

BTW:  The rework on the Tmdb/Tvdb/content_ratings/certifications, should not be delayed too long as I have the original backed up.

**Comment by Afterster** [comment]
Don't worry about the time it's taking. Sometimes we have, sometimes we don't, and sometimes we want to do something else ;).
I think you're right here, both the title and the real original name should be used for the search. Today the original name is only useful depending on the metadata plugin you're using.

Thanks for taking care about the improvement on the video feature.

**Comment by wagnered** [comment]
OK, will implement actual original_name.
