### ISSUE TITLE
Strange filenames when downloading via webDAV

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#837]
Hello, 

I'm currently testing the webDAV interface, all the downloaded files are named according to this patern : 

meme - (track number) - (track title)

I don't know why all the songs are called "meme", it would make more sense to add artist name here. 

Bye

**Comment by Afterster** [comment]
The pattern should be (artist name) - (track number) - (track title). Did you try with another set of files just to be sure it is not the artist name by any way? Thanks.

**Comment by shangril** [comment]
I'm downloading a whole catalog ; and any artist is called "Meme".
Nevertheless, the Artist/Album directory tree shows the correct artist
name.

--------
Retrouvez ma musique sur Clewn.org

2015-05-03 19:25 GMT+02:00 Afterster <notifications@github.com>:

**Comment by Afterster** [comment]
I cannot reproduce your issue with the same test server.
Could you try again using a different client?

**Comment by shangril** [comment]
Corrected just now, fixed
