### ISSUE TITLE
Error playing albums

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#839]
Hello,

I did a git pull this weekend, and I can't play albums no more. Nginx sends this error :

`*7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function quote() on null in ampache-dir/lib/class/dba.class.php on line 131" while reading response header from upstream, client: xx.xx.xx.xx, server: myserver.com, request: "GET /music/stream.php?action=play_item&object_type=album&object_id=45&append=true HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "myserver.com", referrer: "https://myserver.com/ampache/index.php"`

When I try to play songs (not whole albums), it works well though.

* Ngnix 1.8.0
* php 5.6.8

Thank you !

**Comment by Jucgshu** [comment]
Mmh, some albums are playing, with no errors thown. Dunno why though.

**Comment by Jucgshu** [comment]
Ok, I tried to activate logs and I have lots of lines like this one :
`(Dba) -> Error: ["HY000",144,"Table '.\/ampache\/tag' is marked as crashed and last (automatic?) repair failed"]`

**Comment by Psy-Virus** [comment]
Hi @Jucgshu,

that means, that you database server has marked the `tag` table in your ampache database as corrupt. you could try to repair it manually or maybe truncate that tag table, repair it and after that rebuild it via catalog update action. Should work very easy over PHPMyAdmin for example.

:-)

**Comment by Jucgshu** [comment]
Ok, that was indeed pretty easy to fix.

Just did a `REPAIR TABLE tag;` on ampache table and voila !

Thanx for the pointer :)

**Comment by Psy-Virus** [comment]
You're welcome,

and thx for the reply. :-)
