### ISSUE TITLE
Album "Unknown (Orphaned)" has thousands of songs II

### ISSUE THREAD

**Issue by styla01** [ampache/ampache#84]
i will close this issues, but somehow in my last req, my post was deleted or lost:
when i have 90.000 songs and 40.000 no albums tag. now u tell me: "you should fix the root problem and make sure Ampache can find the album info for your songs."
are u serious? for 40.000 songs? need just a condition like: IF Album Orphaned  > 100 songs THEN split it.

guys, i know is a free project and no time, but this a real problem for some users ..

**Comment by rikmendes** [comment]
solution : use musicbrainz to mass tag thousands of files properly putting all your ID3 tag as they should be for you and then reupload your library, rescan your entire collection, let it populate the now fixed ID3 mp3 files and you're good to go !

**Comment by xeruf** [comment]
not all songs are part of an album, though...

**Comment by rmdes** [comment]
Yeah I know, well I fixed that by creating arbitrary albums for such cases
