### ISSUE TITLE
No players work anymore

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#842]
Hi

I upgraded to the latest git version, and none of the players work. Neither web player nor stream does  anything ;( I tried it on multiple browsers with no luck. I do not even know how to debug.

I am on Debian Wheezy using MySQL and Apache

thanks

**Comment by gerroon** [comment]
Ok, Just Player on Android stopped working too ;( This was working fine before. It is able to get the song and artists, however it does not stream anything anymore ;(

**Comment by minnesotags** [comment]
Try transcoding a file just from command line. there is an example in the faq.

**Comment by Psy-Virus** [comment]
Hey @gerroon,
the debug information can be written if you enable the debug option in you ampache cfg and set the debug level on a higher value. The most infos are given with value 5.

Related to your problem:
It seems to me that you may have an ACL issue. You should check your ACL settings and set them for testing purposes to default. For more information pls see [the wiki entry for ACL](https://github.com/ampache/ampache/wiki/ACL)

Hope this helps :-)

**Comment by gerroon** [comment]
Hi
Thanks for the info. The ACLS were all fine, since I have been using it for 2 years without much issue. I checked them they looked good. I could not figure out the issue so I deleted the user as admin and recreated it whcih solved the issue. Bizarre

**Comment by Afterster** [comment]
Ok weird... As it is fixed even if we don't know why, I'm closing this then.
