### ISSUE TITLE
No Artists w/ Subsonic API

### ISSUE THREAD

**Issue by psjbeisler** [ampache/ampache#845]
After an update (3.80+) and using the subsonic API (via an android app), I am not able to get a list of Artists. Everything else works except that specific query with no server errors i could find. I can a list of albums, songs, favs, albums by artist, but just not the list of Artists themselves.

**Comment by s4astliv** [comment]
Did you upgrade to the latest commit? Sounds like issue that was fixed with this commit df6dc76f570f62b20acba569f6061ee644e6488a (https://github.com/ampache/ampache/commit/df6dc76f570f62b20acba569f6061ee644e6488a). Fixed 4 days ago.

**Comment by psjbeisler** [comment]
i did see that and i wanted to test more before i said anything but i just tried with another device and it worked fine. I cleared everything and re-added my server on the first device and it was good again.
