### ISSUE TITLE
Return "favorited" (aka user_flag) status in XML API

### ISSUE THREAD

**Issue by RyanCopley** [ampache/ampache#848]
I'd like to add an option to list only favorited songs, but the API doesn't support that. I'm digging into the code, but I'm not a PHP wiz and it seems like you need the user object to do that query, which I don't think the `api.class.php` receives...

**Comment by RyanCopley** [comment]
does `$GLOBALS['user']` pass through to api.class.php?

**Comment by Afterster** [comment]
Yes `$GLOBALS['user']` also exists when using the api. I believe you can use it for what you want to achieve.

**Comment by RyanCopley** [comment]
@Afterster For the sake of speed... what would you think of a NEW api call to just return that users favorited tracks, rather than mash it in with the song data? I don't know how I would efficiently intermingle that table in in the current implementation

**Comment by RyanCopley** [comment]
If you're game for that, I can probably knock it out sometime this week

**Comment by a7medo778** [comment]
@RyanCopley it would be awesome if you could add a couple of api's for the new social features (user feed, following, followers, follow, unfollow) as they were not available in subsonics

**Comment by Afterster** [comment]
Any progress on this @RyanCopley?

**Comment by Phyks** [comment]
Any news on this? Anyone requiring it (and then willing to leave it open)?

**Comment by lachlan-00** [comment]
This is in the stats call in develop. It will currently pick up your flags but can get others by name/id

type     = (string) 'song'|'album'|'artist'
filter   = (string) 'flagged'
user_id  = (integer) //optional
username = (string) //optional
