### ISSUE TITLE
Add radiostation to playlist, not overwrite

### ISSUE THREAD

**Issue by sam-san91** [ampache/ampache#853]
Hi, in an earlier release (3.7.) it's been possible to add radio stations to the playlist just like songs.
It seems like in the develop branch this isn't possible anymore, or am I just missing a setting?
I'm using localplay to send it to a mpd instance
3.7.0
![image](https://cloud.githubusercontent.com/assets/12391623/7561281/225c8d40-f7cb-11e4-97d5-a3ea35e9f434.png)
Now:
![image](https://cloud.githubusercontent.com/assets/12391623/7561287/2c36cf92-f7cb-11e4-8705-a6394f18dc6b.png)
Also I can't add items to the playlist at all, if I try to add a song via the temporary playlist (send & clear on add) it overwrites the old playlist instead of adding it. I already compared all settings, but I can't find a difference

**Comment by Afterster** [comment]
The radio station was indeed removed from a playlist. It doesn't make sense to have it in a playlist as a station will never end.
About your second issue I don't get it, are you talking about playlist objects or the temporary playlist. Both work correctly on my side, could you details?

**Comment by sam-san91** [comment]
If I add a song to the temporary playlist it should add it to the main playlist. But in my case, it simply overrides the current playlist. So I'm not able to build a bigger playlist like this.

**Comment by SUTJael** [comment]
You have maybe the "Playlist Method" (into the "Playlist" settings) set to "Clear on Send". You may want to use the "Default" one.
