### ISSUE TITLE
Updating Catalog does not preserve modified tags

### ISSUE THREAD

**Issue by Dual-Boot** [ampache/ampache#857]
Hello,

When I first add my catalog, I have some troubles with album.
For a part of the album MusicBrainz ID is set and Tags fields too, but some other song from
the same album in the same folder are not set with MusicBrainz ID and Tags fields.
So I see my album split into 2 albums.
I manualy put the right MusicBrainz ID and Tags fields which solved the problem and record with : 
 Overwrite tags of sub songs
or
 Add tags to sub songs
But when I update the catalog, the fields are reinitilized .

 Any idea ?

  Regards

PS : 
OS Linux Ubuntu 14.04 64 bit
Mariadb 5.5
Apache2.4
Ampache 3.8 beta
(Latest Ampache version: 8edf18896afb98cafa01786517a335bb9dc06ca3)

**Comment by SUTJael** [comment]
Hi @Dual-Boot, you should use our [group discussion](https://groups.google.com/forum/?hl=fr#!forum/ampache) to ask that kind of question ;)
You can activate the write metadata setting ("write_id3") or, if you are using the update command line, don't use the verify (-v) attribute.

**Comment by Dual-Boot** [comment]
Hello,

 Thank you for the tip, but allowing write_id3 by adding write_id3="true" in the php configuration file does not change anything.

 For the second command, can you explain me how to use it ? Is-it this one : 
```php5 bin/catalog_update.inc```
Regards,

**Comment by Dual-Boot** [comment]
More information : 
Seems to be link to the type file.
Modifying id3 tag on ogg format file => KO
Modifying id3 tag on mp3 format file => OK

 Any idea how to fix it ?
Regards,

**Comment by Afterster** [comment]
Indeed this is the normal behavior.
If you attempt to only add new files on your catalog, you should use "add" instead of "update" action to keep your manually edited information.
Or you can write back the information to the file with write_id3 as suggested by SUTJael. But this currently only work with mp3 files, other files format is not yet supported (#564)

**Comment by Dual-Boot** [comment]
OK, thank you for these precisions.
I think I can close this question.
 Regards,
