### ISSUE TITLE
Add to playlist

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#859]
Adding full albums to playlists will ease its creation. Specially in large selections.
![screen shot 05-15-15 at 10 53 am](https://cloud.githubusercontent.com/assets/7412863/7654192/95793674-faf1-11e4-9687-1f38a18db582.PNG)

**Comment by Afterster** [comment]
This can already be done if you go the artist, on mouse hover the artist albums. I'm not a big fan to add another new link into the album page, there is already enough actions here.

**Comment by RobertoCarlo** [comment]
I've found myself wondering why not, since it's a feature i use a lot. The procedure of adding albums to playlists through artist search is kind a workaround, and i already use it. Still thinking its an useful add, even on top of "Add to temporary playlist".

**Comment by RyanCopley** [comment]
@Afterster I'm with RobertoCarlo here... Add to a regular playlist totally makes sense-- please consider it.

**Comment by RyanCopley** [comment]
If it helps, I'm going to put in a PR for this in about ~15 minutes...

**Comment by Afterster** [comment]
Merged, you can thanks @RyanCopley ;)

**Comment by RobertoCarlo** [comment]
Thanks @Afterster.
