### ISSUE TITLE
typo in French translation

### ISSUE THREAD

**Issue by shangril** [ampache/ampache#863]
on preferences.php?action=update_user#preferences.php?tab=account ; "mette" on the button should be "mettre" ("update" ; "mettre à jour") (reported by ardoisebleue from Dogmazic.net)

**Comment by Psy-Virus** [comment]
Hey @shangril,

you could do it by yourself extremely easy if you register at [Transifex](https://www.transifex.com/projects/p/ampache/) and contribute to Ampaches localization.
It's quite easy, so maybe you'll try it?

:-)

**Comment by shangril** [comment]
OK I requested to join the fr team. Thanks Manuel !

--------
Retrouvez ma musique sur Clewn.org

2015-05-20 18:22 GMT+02:00 Manuel <notifications@github.com>:

**Comment by Psy-Virus** [comment]
Perfect!

How is your French? Do you think you also could act as reviewer?
You need at least very good knowledge about grammar and so on.

If you have interest, pls look at the discussion I've started at Transifex team French. :-)

**Comment by Psy-Virus** [comment]
Hmmm, okay O.o
It's three times there... I think I had an cache accident. :(

**Comment by Afterster** [comment]
Translation issue and discussion should be done on transifex for now. This to give a full try on its benefits!
Closing it here then, thanks.
