### ISSUE TITLE
feature request:  now playing plugin for IRC

### ISSUE THREAD

**Issue by robled** [ampache/ampache#865]
In music channels it's nice to be able to automatically notify a channel of what you're currently listening to.  Perhaps Ampache could notify a channel of what you're currently playing on request via the web interface or API or both.

**Comment by Afterster** [comment]
No progress on this, but as a remember it can quickly be done as a new scrobbling plugin and using https://github.com/WildPHP/Wild-IRC-Bot library. It's a good way/feature to learn about Ampache development easily for anyone interested btw ;)

**Comment by Afterster** [comment]
Should be done as an external scrobbling plugin and will not be available in base.
Anyone willing to develop it, please use https://github.com/ampache/ampache/blob/develop/modules/plugins/Growl/Growl.plugin.php as example.

**Comment by Phyks** [comment]
@Afterster Link is dead in your last post. (And I cannot find `Growl` in current `develop` branch).

Should this be a scrobbler in Ampache or should the IRC bot fetch the currently played music from the API? Second option sounds a bit better to me, although it does not seem to be the one you privileged.

**Comment by Afterster** [comment]
Indeed, growl plugin was move to https://github.com/ampache/ampache-growl in attempt to have more independent plugin architecture based on composer. But command line and composer.lock committed file update was a problem.
Anyway, I was thinking about a new scrobbler but an IRC bot fetching currently played music could also do the trick.

**Comment by stebe** [comment]
Ampache also has an RSS feeds of currently played song <http://example.com/ampache/rss.php?type=now_playing>  and recently played songs <http://example.com/ampache/rss.php?type=recently_played> which could be used for this purpose. There are probably already good IRC bots that support RSS.

**Comment by Phyks** [comment]
Ok, I'll have a look at it :)

**Comment by Phyks** [comment]
[This](https://github.com/Phyks/Ampache2IRC) is what I am using for now and that should mostly do the trick :)
