### ISSUE TITLE
Subsonic API not working

### ISSUE THREAD

**Issue by joelstitch** [ampache/ampache#866]
I have been trying to get the Subsonic API working on my server, I follow all the directions and I think I have all the settings as they should be but whenever I try to use a Android app to access my music I get connection errors even when I try to access it from inside my network. I follow these directions:
----------------------------------------------------------------------------------------------------------------
SubSonic API

Your Ampache server can be accessed through SubSonic API but there is some prerequisite for that:

    You must enable SubSonic Backend in System settings.
    Default configuration is for Apache web server, you have to adapt /rest/.htaccess script for your web server if you're not using Apache
    Url rewriting Apache mod must be enabled and your Apache configuration must allow configuration override (AllowOverride all).

If you use Nginx, htaccess files are not read. You must add this lines in your VHost file:

if ( !-d $request_filename ) {
    rewrite ^/rest/(.*)\.view$ /rest/index.php?action=$1 last;
}

location /rest/ {
    limit_except GET POST {
        deny all;
    }
}

The same for lighttpd:

url.rewrite-once = (
  "^/rest/(([^\?]+)\.view)(\?(.*))?" => "/rest/index.php?ssaction=$2&$4"
)

    Access control and XML-API must be enabled
    PHP cUrl mod is highly recommended
    To not break few clients, Authorization header should be passed (some Apache module can remove this header for security reason). To be sure, please add the following directive in your Apache configuration : SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    Most SubSonic client will request cover thumbnail. To return real thumbnail on the fly, PHP-GD module is recommended.

Once these prerequisites matched, the best test is to open http://localhost/ampache/rest/ping.view page with your browser and see the output. You should get the following XML response:

<subsonic-response version="1.10.1" status="failed">
    <error code="10" message="Required parameter is missing."/>
</subsonic-response>

If you get successfully this XML message, you can now add your server on a Subsonic client, adding http://localhost/ampache as web server url.
----------------------------------------------------------------------------------------------------------------

I have SubSonic Backend enabled, mod rewrite is on and I have AllowOverride ALL on all of apache configration. When I access http://mywebsite/ampache/rest I get this message:
----------------------------------------------------------------------------------------------------------------
subsonic-response type="ampache" version="1.11.0" status="failed" error code="10" message="Required parameter is missing."/ /subsonic-response
----------------------------------------------------------------------------------------------------------------
And when I try to access my ampache server from DSub I get a connection error.

What am I doing wrong?

**Comment by Afterster** [comment]
http://mywebsite/ampache/rest is not http://mywebsite/ampache/rest/ping.view

 * Which Ampache version are you using? If 3.7.0, please try with latest commit on develop branch in case it is really an issue and it is fixed.
 * Do you have the same xml message on ping.view?
 * Could you copy/past here your Ampache ACL list?

PS: text formating as you did on your message looks random and it make it really hard to read :)

**Comment by joelstitch** [comment]
There is no ping.view file. The Apache version I have is 2.4.7 the latest one in Ubuntu Server 14.04. Here is the  ACL list

DEFAULTv4 	0.0.0.0 	255.255.255.255 	All 	All 	Web Interface
DEFAULTv6 	:: 		All 	All 	Web Interface 	
API 	0.0.0.0 	255.255.255.255 	All 	All 	API/RPC
API 	0.0.0.0 	255.255.255.255 	All 	All 	Stream Access

**Comment by Afterster** [comment]
Yeah it's what url rewriting is made for...
I reiterate my question, what happening if you try to access http://mywebsite/ampache/rest/ping.view?
If 404, then url rewriting is not setup properly. Thanks.

**Comment by joelstitch** [comment]
I edited the .htacess file to have /ampache/rest/ping.view instead of just /rest/ping.view and now it seems like is working fine. Thanks for the help,

**Comment by tomgould** [comment]
I had this issue when I was port forwarding from 8088 to 80, I just changed the routing so I could access Ampache from port 80 externally and it worked :)
