### ISSUE TITLE
Web Player not working with remote catalog

### ISSUE THREAD

**Issue by Thalhammer** [ampache/ampache#867]
Let's assume I have two ampache instances.
Instance 1 provides musik and is added as a remote catalog to instance 2.
I log in to instance 2 via the web interface and press play on a song placed in instance 1.
If i select stream or use rhythmbox (ampache-plugin) everything works just fine.
If i select webplayer, nothing happens. The webplayer is shown but does not play anything, also the title inside the webplayer is empty. Looking at the apache log in instance 1 i see that the file is never requested.

Tested With Firefox 38 and Latest Chrome.

[EDIT:] Ampache version 3.8.0-develop
[EDIT2] I just tested with version Ampache 3.6-alpha6+FUTURE and it works fine there.
[EDIT3] I tested version 3.7.0 to make sure its not a bug of the development release and it didn't work there too. It look's like this functionality is broken in every version later than 3.6

[EDIT4] I have done some further investigation and it looks like the problem is because of ampache not providing the right media type.
During the initialisation of jplayer an associative array is provided which contains a media url for each type. The type is the key. Normaly it is detected by the ending of the local file, but when used with remote catalog there are request paramters at the end of the file. This results in jplayer being unable to detect the correct file type and fail.
I "fixed" this problem by replacing line 103( ampache version 3.7.0) in /lib/class/webplayer.class.php from
$ftype = $song->type;
to
$ftype = substr($song->type,0,strpos($song->type,"?"));

I'm sure this is not a perfect solution, but it works for me.

// In version 3.8.0 it is the same except the variable is called $media instead of $song.

**Comment by Afterster** [comment]
Thank you for the report and the bug localisation. This is indeed the root of your issue.
3.7.0 included several changes on streaming and indeed it broke this feature depending your installation enabled settings.
I will fix it properly, thanks again.

**Comment by Afterster** [comment]
I just commited a change to avoid additional parameters at the end after the filename.
Could you give a try and let me know? Thanks.

**Comment by Thalhammer** [comment]
Sorry for the late answer, but I had a lot of work to do.
I have tried it out and it now works as expected.
