### ISSUE TITLE
Playlist improvements...? (please)

### ISSUE THREAD

**Issue by PeterBehrend** [ampache/ampache#869]
-hi, Been using Ampache for years streaming to web client and Android (Justplayer). It worked ok but was not great. I really like that someone now have given Ampache an overhaul. Much better now. The Subsonic API via rewrite rulesets give the benefit of using many more clients. Thanks for all that. One thing I REALLY miss is better handling of playlists and tags (mostly id3v2). A prioritized tag sort order in config file PRETTY PLEASE. For instance "disc no," is ignored. So if you play any double album all tracks gets "intermixed" (track 1 from disc 1 -> track 1 from disc 2 -> track 2 from disc 1 -> track 2 from disc 2 ....). If you create a playlist placing the tracks correctly it will still be played wrong since "disc no." from tag is still ignored. So could you include all fields from tag (id3v2) and possibly a way to prioritize sort order. And for playlists don't sort them in any way?
Is this understandable ? :-)
kind regards
/peter

**Comment by Afterster** [comment]
Mh I'm not sure to get it.
Disc number is read from your mp3 metadata normally, and according to the disc number we will create new albums entry, that you can regroup on the user interface with a dedicated ampache settings.
If disc number is not read from your files then I believe it is a getid3 issue. Please be aware that we fixed few metadata issues on 3.8.0-develop, you should test with development branch first and if it is still not working please send me a test file. Thanks.
