### ISSUE TITLE
Fresh install can't write in installation folder

### ISSUE THREAD

**Issue by sanzi** [ampache/ampache#873]
Hello,
First of all thank you for this project it is amazing.
I am trying to install ampache on a frech debian install (through git clone), with apache2, php5, mysql configured...
As soon as ampache tries to write into /var/www/html/ampache it fails because of permission.
If in between step i do a chmod a+rwx to ampache folder it works only for 1 writing step.
I wonder what I am doing wrong, html folder owner is the www user and group...
Sorry for the english... And any help welcomed!

**Comment by sanzi** [comment]
Alright, I have made some progress :
I have set the default permission of /html file and folder to rwx for all (To be modified after install) using
setfacl -d -m o::rwx your/directory/path
I did the same command with u::rwx and g::rwx
Now the install goes smoethly, but after the install I am unable to login.
I identify myself and automaticly redirected to the homepage without been logged in.
I am not pronted with a "wrong password" messsage.

**Comment by Afterster** [comment]
Nothing wrong in your log. You cloned 3.7.0 or develop version? You can try with develop version otherwise.
Check your debug messages on your browser, I don't see any reason why it would silently failed without an error on Ampache logs.

**Comment by sanzi** [comment]
Alright, indeed my setup was right.
I have restarted from the beginning (reinstalled vm...) and I got the exact same error.
Using internet explorer I have no error and I can log in.
After clearing my cookies I was also able to log in in firefox.
So all in all it works, and I advise to clear your cache I you had a previous ampcache install!
Thanks
