### ISSUE TITLE
Translation issue during Installation

### ISSUE THREAD

**Issue by Thalhammer** [ampache/ampache#877]
There is a typo in the german translation used during installation.
See patch below.

diff -rupN ampache/locale/de_DE/LC_MESSAGES/messages.po dev/locale/de_DE/LC_MESSAGES/messages.po
--- ampache/locale/de_DE/LC_MESSAGES/messages.po	2015-06-04 10:12:32.082025250 +0200
+++ dev/locale/de_DE/LC_MESSAGES/messages.po	2015-06-04 10:14:01.866024210 +0200
@@ -5169,7 +5169,7 @@ msgstr "Minimal"
 
 #: ../../templates/show_install_config.inc.php:116
 msgid "only essential features are enabled to stream simply your music from a web interface."
-msgstr "Nur die wihtigsten Features, zum streamen deiner Musik über das Web Interface, wurden eingerichtet."
+msgstr "Nur die wichtigsten Features, zum streamen deiner Musik über das Web Interface, wurden eingerichtet."
 
 #: ../../templates/show_install_config.inc.php:119
 msgid "Community"

**Comment by Afterster** [comment]
Thanks I will let @Psy-Virus review this.
But maybe you can directly do the change using the web interface:
https://www.transifex.com/projects/p/ampache/

Thanks.

**Comment by Psy-Virus** [comment]
I was trying to fix it but I can't login at Transifex at the moment...

**Comment by Thalhammer** [comment]
I just submited a request to join the german translation team.

**Comment by Psy-Virus** [comment]
Yey, after several hours of trial and error, the project page showed up. - strange

I already fixed the typo and thanks @Afterster for adding @Thalhammer as translator.
And also a big THX @Thalhammer for joining. :-)
