### ISSUE TITLE
Add to existing playlist not working anymore

### ISSUE THREAD

**Issue by Niols** [ampache/ampache#880]
Hi,

On the develop branch, it's not possible any more to “Add to existing playlist” because the box that opens when we click is empty.

I don't know why, but I noticed the box was not empty in *Browse Music > Playlists* section, even if it seems to be the case everywhere else.

I'll try to find out which commit broke that, and how this can be fixed, and I'll send a PR. Except if you find it before me of course.

**Comment by Afterster** [comment]
It's not the case on my side for information. Looks like an environment or data related bug.

**Comment by Niols** [comment]
I think this might come from the use of a 3.7.0 config file in a 3.8.0-beta instance. Don't know why though, but I reinstalled not using my old file and everything is fine.

**Comment by stonie08** [comment]
I encountered the same problem. For me it only happens for members of the group 'user' and not for admins.

**Comment by Niols** [comment]
Yep, it rehappened to me too. So I guess that's not the reinstallation that solved my problem…

**Comment by Afterster** [comment]
Yeah first bug (already) after 3.8.0... thanks, fixed now ;)
