### ISSUE TITLE
Random song is not a continuous random ?

### ISSUE THREAD

**Issue by Phyks** [ampache/ampache#881]
Hi,

It seems that when using "Random song" function, it is loading a bunch of randomly selected songs in the playlist (right panel) but when reaching the end of the playlist, it seems to not load more songs, while it could be a continuous random play mode (at least, that was what I understood at first).

Moreover right panel and web player playlists are kind of decoupled, which is also some misleading UX I think. I mean, clicking on a title in this right panel show it in the central panel, but to read it, one must click on the title in the web player playlist.

**Comment by SUTJael** [comment]
Yes that's what we call the "temporary" playlist which let you browse and add some songs to a "basket" and then save them to a real playlist.
About the random songs, we don't have that kind of functionnality for continuous play in the web player but additional clients can already do that with the API. I'm flagging your request as enhancement.

**Comment by Phyks** [comment]
Thanks :)

**Comment by Phyks** [comment]
Closing as it is a duplicate of https://github.com/ampache/ampache/issues/834.
