### ISSUE TITLE
Invalid example URL in XML API page

### ISSUE THREAD

**Issue by nicklan** [ampache/ampache#890]
On the XML API page there is an example url of:

```
http://localhost/ampache/server/xml.server.php?action=genres&auth=1234567890123456789012345678901&filter=Rock
```

Requesting this url (with a correct auth token) will give:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<root>
	<error code="405"><![CDATA[Invalid Request]]></error>
</root>
```

Not a huge deal, but should probably be fixed.

**Comment by Afterster** [comment]
Yes indead it is *tags* instead of *genres*.
Fixed, thanks for the report!
