### ISSUE TITLE
XML API doesn't support proper searching

### ISSUE THREAD

**Issue by nicklan** [ampache/ampache#891]
The XML API seems to have no way of specifying more advanced queries.  The search_songs function hard codes "rule_1" to search "anywhere", and there is no other call that allows flexibly specifying rules.

This means, for example, there is no way to search for songs by year, or only by genre, etc...

I'd suggest a call something like:

```
http://localhost/ampache/server/xml.server.php?action=search&auth=[auth]&rule_1=year&rule_1_input=2012&rule_2=genre&rule_2_input=Rock
```

**Comment by nicklan** [comment]
so, a simple way to support this would be to add the following function to api.class.php:

```php
    /**
     * advanced_search
     * Perform an advanced search given passed rules
     * @param array $input
     */
    public static function advanced_search($input)
    {
        ob_end_clean();

        XML_Data::set_offset($input['offset']);
        XML_Data::set_limit($input['limit']);

        $results = Search::run($input);

        echo XML_Data::songs($results);
    } // advanced_search
```

The problem here is that the input needs to look something like 

```
[url]?action=advanced_searchrule_1=anywhere&rule_1_input=foo&rule_1_operator=0
```

which is all fine except the rule_1_operator part, which basically requires one to look into the source to figure out the correct index.  solutions are: document the operator indexes in the api doc, or make the function a bit more complex to support transforming something like rule_1_operator=contain into the correct index.

If you think this work, let me know which you would prefer and I can submit a pull request.

**Comment by Afterster** [comment]
PR #949 was merged. Thanks.
