### ISSUE TITLE
Possible bug in compare_song_information

### ISSUE THREAD

**Issue by nan4k7** [ampache/ampache#892]
I found that catalog update was reporting changes in a lot of files that didn't change.

So I researched what could be going wrong and while doing this I found out that the catalog update was reporting the difference was on key "object_cnt" that I don't know what it is but it is not a id3 tag definitely.

So I suggest changing line 815 of song.class.php to add object_cnt and avoid the comparison of this "tag"
```        $skip_array = array('id','tag_id','mime','artist_mbid','album_mbid','albumartist_mbid','albumartist','mbid','mb_albumid_group','waveform','object_cnt');```

Also it would be great to add a implode in the value of the data shown in debug because some tags can be arrays (such as genres)
```
$songData = is_array($song->$key) ? implode(" ", $song->$key) : $song->$key;

$newSongData = is_array($new_song->$key) ? implode(" ", $new_song->$key) : $new_song->$key;

$array['element'][$key] = 'OLD:' . $songData . ' -> NEW: ' . $newSongData;
```

**Comment by Afterster** [comment]
For object_cnt, indeed this would happen if *show_played_times* setting is enabled. I also applied your suggestion for debug output. Fixed, thanks again ;).
