### ISSUE TITLE
[Info] New ampache kodi addon

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#897]
Hey guys,

In case it hasn't been notity elsewhere, there's a new kodi/xbmc addon available, which is a fork of another previous addon which looks abandonned.
 
It has been developped by lusum and there's a discussion on kodi forums qbout it : http://forum.kodi.tv/showthread.php?tid=230736&pid=2047977

Also a Github repo : 
https://github.com/lusum/ampache-xbmc-plugin/tree/0.5.0

Cheers !

**Comment by Afterster** [comment]
I'm closing this has it is not a real issue related to development (there is enough open issue to scare me every morning lol).
Better to use the group for this kind of discussion/information, but this is great ;)

**Comment by Jucgshu** [comment]
Yeah, sure. I should have done it myself, sorry about that. Also, open issues show the interest the users have in the project :-)
