### ISSUE TITLE
Impossible to add temporary playing playlist to new playlist

### ISSUE THREAD

**Issue by RobertoCarlo** [ampache/ampache#901]
While pop-up windows opens only when pointer is in top of "Add to playlist" it is impossible to do it since is no continuity between this two items. So, when you try to click over "Add to new playlist" or any other option pop-up window disappear since pointer is no longer on top of it.
![screen shot 2015-07-15 at 14 48 35](https://cloud.githubusercontent.com/assets/7412863/8705593/028f5060-2b01-11e5-86d1-adb6d3377fea.png)
There's a workarund: double click over "Add to playlist" and while it's with secondary options click over "Add to new playlist". Too messy.

**Comment by Afterster** [comment]
Pointer is on the top on my side, so I don't have the issue.
Which version are you using? Which browser (and version)? Which screen resolution?

**Comment by JoeDat** [comment]
I can confirm I have the same problem, but only in Chrome.  As soon as you try to move the pointer to 'Add to Playlist' from the temporary playlist, the window disappears.  

Testing in MS EDGE, it works fine

**Comment by RobertoCarlo** [comment]
Firefox, Safari mostly latest versions on Mac OS X 10.9 and Windows 7
Also development branch. Latest commits.
