### ISSUE TITLE
I have problem in "config/ampache.cfg.php"

### ISSUE THREAD

**Issue by lovijoshi5** [ampache/ampache#904]
Hello,

I'm tiring to configure the ampache but i'm on "Step 2 - Create configuration files (ampache.cfg.php ...)"

but i'm facing the problem in "config/ampache.cfg.php" below is the error with screenshot:

 config/ampache.cfg.php action
config/ampache.cfg.php exists?
config/ampache.cfg.php configured?  
Screen Shot : http://prntscr.com/7twtvf

Please help me to resolve it and if possible please provide me the screen shot of video also.

humbly requesting you 

Thanks and Regards

Lovi Joshi

**Comment by Afterster** [comment]
The means Ampache wasn't able to create the config file automatically. It is probably related to file permissions. You can either change the file permissions to give write access to your web server user (probably www-data), or download and copy the file manually as suggested.

**Comment by lovijoshi5** [comment]
Hello Afterster,

Thank you for your bug report, could you please provide the steps.

Thanks
Lovi

**Comment by dcrobertson01** [comment]
Same problem - permissions seem okay - apache user and group have rwx to config folder. Do not get anything when I click download or write.

Pretty confusing to have both Error and Ok buttons presented - which is it? and why buttons? Also - as this is probably as far as I am going to bother going with this - the install failed on the data base step while installing over https. I enabled http and started to install over that - got past the database step ... but now stuck here.

**Comment by RazorApple** [comment]
Same problems but using windows and xampp

**Comment by RazorApple** [comment]
Please help.

**Comment by wagnered** [comment]
@RazorApple 

What version of Ampache are you trying to install?

What happens when you press "Create Config"? What error message , if any, is displayed when it is pressed?
