### ISSUE TITLE
Channels Won't Start

### ISSUE THREAD

**Issue by istariong** [ampache/ampache#905]
Using 3.8.0, I am unable to start any Channels either through the web interface or at the command line using  "php bin/channel_run.inc -c 1 > /dev/null &" (for Channel 1). Channel is set to "true" in ampache.cfg. Transcoding using avconv is working. After trying to start a Channel in either the web interface or command line, the log at debug_level 5 only shows this change:
2015-07-18 16:00:40 [*****] (session) -> ad4cbbcd2e2a58b1fa36c6534e2e2e25 has been extended to Sat, 18 Jul 2015 17:00:40 +0000 extension length 3600 
2015-07-18 16:00:40 [*****] (ajax.server.php) -> Called for page: {index}

**Comment by Afterster** [comment]
If using command line without `> /dev/null &`, what's the output? Nothing in PHP/Apache error logs neither?

**Comment by istariong** [comment]
When running the command:
 php bin/channel_run.inc -c 1

it returns:
Parse error: syntax error, unexpected ':' in /home/*****/*****/*****/lib/init.php on line 90

This is line 90:
$results['site_charset'] = $results['site_charset'] ?: 'UTF-8';

When removing the only colon there and running the command, I get an unexpected semi-colon error. Removing the only semi-colon just continues to produce more syntax errors. I'm guessing the problem starts somewhere before line 90. Here's a larger block of code starting at line 81:

$results['raw_web_path'] = $results['web_path'];
if (empty($results['http_host'])) {
    $results['http_host'] = $_SERVER['HTTP_HOST'];
}
if (empty($results['local_web_path'])) {
    $results['local_web_path'] = $http_type . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . $results['raw_web_path'];
}
$results['web_path'] = $http_type . $results['http_host'] . $results['web_path'];
$results['http_port'] = (!empty($results['http_port'])) ? $results['http_port'] : $http_port;
$results['site_charset'] = $results['site_charset'] ?: 'UTF-8';
$results['raw_web_path'] = $results['raw_web_path'] ?: '/';
$results['max_upload_size'] = $results['max_upload_size'] ?: 1048576;
$_SERVER['SERVER_NAME'] = $_SERVER['SERVER_NAME'] ?: '';

if (isset($results['user_ip_cardinality']) && !$results['user_ip_cardinality']) {
    $results['user_ip_cardinality'] = 42;
}

My PHP/Apache Error log is blank, but the Access log shows:
2600:100e:b00b:377b:7488:59fc:e668:7ee1 - - [19/Jul/2015:17:48:01 +0000] "POST /server/ajax.server.php?page=index&action=reloadnp HTTP/1.0" 200 164 "http://*****.*****.*****/index.php#browse.php?action=channel" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"

**Comment by istariong** [comment]
New information. After changing my cfg variable "transcode_ogg" from "allowed" to "required", I attempted to start the channel again with:

[... bin]$ php bin/channel_run.inc -c 1

and got a new error:

Could not open input file: bin/channel_run.inc

Permissions on channel_run.inc are currently 664. The file is owned and a member of same group as all the other files in bin.

**Comment by Afterster** [comment]
Definitely seems to be a file permission issue. You should check again your environment. Maybe you are using SELinux?

**Comment by istariong** [comment]
I am running Ampache in a CentOS 6.6 hosted environment. What permissions should channel_run.inc have?

**Comment by Afterster** [comment]
CentOS has SELinux installed by default, this looks definitely like an SELinux misconfiguration for me. Please take a look on this side.

**Comment by istariong** [comment]
Thanks, I'll check into the SELinux thing. I'm in a hosted environment, so not sure what, if anything, I may be able to do about that configuration. I did, however, try using my full path in command line statement and got a new error:

Parse error: syntax error, unexpected ':' in /home/*****/*****/*****/lib/init.php on line 90

My line init.php line 90 reads:

$results['site_charset'] = $results['site_charset'] ?: 'UTF-8';

**Comment by Afterster** [comment]
Ok. But again, this error seems also related to SELinux.

**Comment by istariong** [comment]
New info. I just ran the command sestatus in my environment and it is returning:

SELinux status:                 disabled

**Comment by Bacon8tor** [comment]
Hello, All, first of thanks for the documentation you have contributed it helped me to figure out how to add a playlist to a channel.  I am currently using ampache on my paid web hosting service. I am unable to get the channel to start. I only found an error log in the main directory of ampache, it had no relevant information. I have tried also changing the ch on channel_run.inc, although I am unsure as I can not use command line, I am honestly not sure if selinux is enabled on the hosted server. everything else works great I would really love to have a channel streaming (I am new to have a hosting site, I usually host myself of a linux server, but that machine is down, so im forced to host. )

**Comment by Bacon8tor** [comment]
I am still having this issue, I am currently waiting on a power supply for my personal server . Still unable to get channels to start thru web alone. I have gone thru the documentation , nothing has seemed to help, other then that this software is amazing.

**Comment by Afterster** [comment]
@Bacon8tor, if you cannot run something through command line, chances are that you will not have permissions to run channels on your hosted server unfortunately. I believe you are not able to enable transcoding neither btw.

**Comment by Bacon8tor** [comment]
Ok , guess I'll just have to get a VPS , so that I am use the cli, I really
like the ampache so far, everything besides channels works great.

**Comment by Afterster** [comment]
@istariong there is no reason for failing at this line, please take some time to check your environment as probability is high to be related to it.
Otherwise according to your latest error I would say you're using php version < 5.3 when using command line which is not supported, minimum PHP version is 5.3.
You can check with `php -v`. Otherwise I don't have a clue.

**Comment by Afterster** [comment]
Environment related issue, closing this (I hope you found the right configuration on your side!).
