### ISSUE TITLE
Wrong mimetype for m4v files (video/quicktime)

### ISSUE THREAD

**Issue by tpinky** [ampache/ampache#909]
During the scan of the catalog the wrong mime-type is assigned to m4v files.
In the database table "video" it is "video/quicktime" which is not correct.
Should be "video/mp4".

During the scan following method is called:
GetFileFormat in getId3.php(Line 1307)

The method iterates over a set of fileformat objects, that have a defined pattern field, which are checked with the header of the file(if it matches). Unfortunately it also matches with m4v files.

For quick time the entry is the following:
// QT - audio/video - Quicktime
'quicktime' => array(
'pattern' => '^.{4}(cmov|free|ftyp|mdat|moov|pnot|skip|wide)',
'group' => 'audio-video',
'module' => 'quicktime',
'mime_type' => 'video/quicktime',
)

**Comment by tpinky** [comment]
Running Ampache 3.8.0

**Comment by tpinky** [comment]
What is a problem if I don't have a quicktime plugin.

**Comment by Afterster** [comment]
Mhh looks like a little getid3 bug (or more a missing case support), could you post the issue on getid3 issue tracker https://github.com/JamesHeinrich/getID3 (maybe you can directly suggest a PR on getid3 project btw)? Thank you!

**Comment by wagnered** [comment]
Actually from the "iTunes Metadata Format Specification" dated 4/16/2008:

quote:

The iTunes audio and video files covered by this specification normally
have the extension .m4a (unprotected audio), .m4p (protected audio),
.m4v (unprotected or unprotected video), or .mp4 (unprotected audio or
video). The format and use of metadata is identical for files of audio
and video, protected and unprotected formats. These file formats are all
based on the ISO Base Media File Format specification (defined by the
ISO/IEC 14496-12:2005 and 15444-12 standards) and the MPEG-4 File
Format specification (defined by the ISO/IEC 14496-14 standard).

unquote

The ISO/IEC 14496-12:2008 specs reference
http://www.apple.com/quicktime/resources/qtfileformat.pdf in it's
bibliography. And the web page states

"This is the document on which the original MP4 File Format
Specification was based".

and from "Final Cut Pro 7" documentation:

quote:

The QuickTime movie file format, often abbreviated to QuickTime file, is
a special file format that contains multiple tracks for storing
different kinds of media. Don’t confuse this special movie file format
with other files that are simply QuickTime-compatible formats.

unquote

Please understand, that the .mp4/m4v etc indicate a container that holds
the actual video information which may be h264/xvid/DV or other  encoded
video.

Regards,

Ernie Wagner

**Comment by tpinky** [comment]
@Afterster 
ok . I will do that.

@wagnered 
I understand that. But my point is that not every browser supports quicktime as a container.

e.g. Firefox for Windows
https://bugzilla.mozilla.org/show_bug.cgi?id=924555

**Comment by tpinky** [comment]
Opened new issue in
https://github.com/JamesHeinrich/getID3/issues/48
