### ISSUE TITLE
Ampache stops playing on certain songs

### ISSUE THREAD

**Issue by hypfvieh** [ampache/ampache#912]
Hi,

I have problems playing some songs with ampache.

Ampache stops playing those songs before they are finished.
Example: Ampache shows song length of 3:33 minutes, but song stops right after 3:20.

Other players, like foobar2000 or Audacious are playing these songs correctly.

All songs which behave like this, are regular MP3 VBR (Joint Stereo) files with id3Tag 1.1 and 2.3.

I tried to find out what is happening using the ampache debug log, but there is no usable information:
```
2015-07-28 10:49:50 [ampuser] (play) -> Playing file (/music/Artist/Album/01. Artist - Song.mp3}... 
2015-07-28 10:49:50 [ampuser] (play) -> Media type {mp3} 
2015-07-28 10:49:50 [ampuser] (play) -> Custom play action {} 
2015-07-28 10:49:50 [ampuser] (play) -> Transcode to {} 
2015-07-28 10:49:50 [ampuser] (play) -> Decided not to transcode 
2015-07-28 10:49:50 [ampuser] (play) -> Starting stream of /music/Artist/Album/01. Artist - Song.mp3 with size 6590694 
2015-07-28 10:49:50 [ampuser] (play) -> Registering stream stats for {Artist - Song}... 
2015-07-28 10:49:50 [ampuser] (user.class.php) -> Updating stats for {song/4711} {Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0}... 
```
Other MP3s with the same encoding options (VBR, joint stereo) are working as expected.

I don't think it is a PHP memory problem, because the song is short, other tracks play well and my PHP memory limit is already set to 512MB.

Is there any way to debug this issue?

**Comment by Afterster** [comment]
Are you using html5 as the audio back end ? If so, this could be related to the browser. Could you try to create a simple html5 test page with the audio tag playing the same mp3 file? Thank you.

**Comment by hypfvieh** [comment]
Yes I'm using the HTML 5 player.

I've tested what you suggested, and created a small page using HTML 5 audio-tag to play the "broken" song (using same firefox version). 

Works like a charm, song is playing like it should (including the last 10 seconds).

Tried it again with ampache, still no luck. It stops playing before the end. I have this problem on the whole album, but with different "gaps". Some songs play. Some songs misses 5 seconds to the end, and one song misses 10 seconds.
I know that I have some more albums with that issue, but I can't remember which ...

**Comment by SUTJael** [comment]
Any chance to try on another browser than firefox?

**Comment by hypfvieh** [comment]
Just tried it with the latest chrome browser (44.0.2403.130-1).
Still no luck :(

The gap to the end differs (firefox: 2 - 10 seconds; chrome: 2 - 5 seconds), but it is still not playing the song until it really ends.

**Comment by stebe** [comment]
Inside the MPD configuration file is this information which may be related to your problem. The headers are not corrected on your MP3 files which needs to be corrected. This is the correct link to the program mentioned below: https://gna.org/projects/vbrfix

"gapless_mp3_playback <yes or no>
    This specifies whether to support gapless playback of MP3s which have the necessary headers. Useful if your MP3s have headers with incorrect information. If you have such MP3s, it is highly recommended that you fix them using vbrfix (available from <http://www.willwap.co.uk/Programs/vbrfix.php>) instead of disabling gapless MP3 playback. "

**Comment by hypfvieh** [comment]
I just tried your suggestion and "fixed" a broken file - same result :-(

**Comment by hypfvieh** [comment]
I got an update to this problem.
It doesn't have to do with streaming. The problem is, that the file size of the "broken" songs is wrong in ampache.

I have tested that with 3 different songs of different artists and albums.
While Ampache says my song has 6590694 bytes, 'du -b' says the file has 6712822 bytes.

When checking the database, I see that Ampache has set the songs size to 6590694.
I have changed the entry in the database to the size which 'du -b' reports, and now the song plays like it should.

I copied the song to a new catalog for testing, and did "add" as well as "update",  but Ampache still measures the wrong size.

I'm now trying to figure out what ampache does and why the size it determines is wrong.

**Comment by hypfvieh** [comment]
Ok I made some progress here.

In the MP3 file, getID3 returns two sizes. The raw file size which is the same as "du -b" reports and a size which is read from id3v2 comment->size.

I don't know for which purpose this field exists, as eyeD3 doesn't show it. 

As far as I can see, ampache likes the size information of the comment field more than the real file size. I guess that this is not really smart, if the size stored in database is used for streaming...

**Comment by hypfvieh** [comment]
Alright, I got it... vainfo.class.php takes the wrong size parameter (the one from id3v2) instead of the real file size.
I'm not sure if this is really a bug or by design.

In my opinion there are 2 ways to fix it:
1) write the REAL filesize to database, which will also be more accurate for displaying file size on the UI.
2) Determine the real filesize for streaming only.

I don't know how you would fix it, so I won't be issuing a pull request... 
This would be my patch for variant 1):

```diff
diff --git a/lib/class/vainfo.class.php b/lib/class/vainfo.class.php
index d49b34b..1b3e8bb 100644
--- a/lib/class/vainfo.class.php
+++ b/lib/class/vainfo.class.php
@@ -349,7 +349,7 @@ class vainfo
             $info['bitrate'] = $info['bitrate'] ?: intval($tags['bitrate']);
             $info['rate'] = $info['rate'] ?: intval($tags['rate']);
             $info['mode'] = $info['mode'] ?: $tags['mode'];
-            $info['size'] = $info['size'] ?: $tags['size'];
+            // size will be added later, because of conflicts between real file size and getID3 reported filesize
             $info['mime'] = $info['mime'] ?: $tags['mime'];
             $info['encoding'] = $info['encoding'] ?: $tags['encoding'];
             $info['rating'] = $info['rating'] ?: $tags['rating'];
@@ -422,6 +422,17 @@ class vainfo
             unset($info['totaldisks']);
         }
 
+       // Determine the correct file size, do not get fooled by the size which may be returned by id3v2!
+       $size = -1;
+        if (isset($results['general']['size'])) {
+                $size = $results['general']['size'];
+        } else {
+                $size = Core::get_filesize($filename);
+        }
+
+        $info['size'] = $info['size'] ?: $size;
+
         return $info;
     }
```

If you want me to issue a pull request, let me know.

**Comment by SUTJael** [comment]
Yes of course don't hesitate to suggest a PR ;)

**Comment by Afterster** [comment]
PR Merged.
