### ISSUE TITLE
Wiki contribution

### ISSUE THREAD

**Issue by arnaudbey** [ampache/ampache#914]
Hey there.
I dunno how to contribute to a github wiki (no pull request system ?) but I was playing with VLC localplay today and I get 2 little things to add / correct :

* The path of authorized hosts file :  ``` /usr/share/vlc/lua/http/.hosts ```
* The interface can also be started from the command line if you only have a remote access to this machine : ```cvlc -I http --http-port 8080```

Thanks for your work :+1:

**Comment by SUTJael** [comment]
Thanks, added to wiki, any more comments?

**Comment by arnaudbey** [comment]
Nope. 

Except that cVLC crashes systematically at the end of a track. (so I couldnt listen to a complete playlist without manually relaunching (c)vlc for each track.) Cant' remember exactly the error (seg. fault)

Anyway, no problem with MPD, working like a charm :)
