### ISSUE TITLE
User Permission issues

### ISSUE THREAD

**Issue by joelstitch** [ampache/ampache#921]
I installed Ampache on my server running Ubuntu Server 15.04, set all the settings right, enabled mod_rewrite and is working fine but whenever I try to access my Ampache from a Android app either Dsub or Subsonic I keep getting a message saying "Connection failure. Not authorized. Check user permissions in Subsonic server." I have all the setting to Allow Sharing enabled and my user is an Administrator.

**Comment by nioc** [comment]
Hello, may be you should add both apache and ampache logs (you have to activate debug in level 5 before).
I installed it last week and works fine with the subsonic app for Android.
Do you add ACL for API?

**Comment by joelstitch** [comment]
That was the issue. I cant believe I missed that. Thanks so much.

**Comment by joelstitch** [comment]
I git it to access my music list and it connects to my server fine now but whenever I try playing something on the Android apps it caches the music but wont play it.

**Comment by nioc** [comment]
I got this problem too. For me, it was a misconfuration on apache redirect (I use severals virtuals hosts on apache and the subsonic playing function called the bad host).
Check your apache logs and set the correct host in the configuration file.

**Comment by joelstitch** [comment]
I'm pretty sure the apache redirect is fine. When I access /rest/ I get the right results.

**Comment by nioc** [comment]
The setting I changed was in the **ampache configuration** (config/ampache.cfg.php) not the Apache configuration nor .htaccess.
Check (and post) the apache access and errors logs to be sure.

**Comment by joelstitch** [comment]
I got it working now. I added /ampache/ before the link on the /play/ host file

**Comment by nioc** [comment]
Yes, it was my second idea, it the first was not the good one ;)

**Comment by joelstitch** [comment]
Thanks for the help!

**Comment by joelstitch** [comment]
So I am running into the same issue again with a completely different system. I have the latest Ampache running on a Raspberry Pi,port forwarding is setup fine. I can access the ampache page and play music locally and online but cannot get it to work with the Android app Dsub. I add the server and it says the connection is OK but when I try to load the artist list it gives me a connection error.

**Comment by joelstitch** [comment]
Figured it out. I had to go to Preferences > Account > and add an API for my user. That was all. Thanks!

**Comment by joelstitch** [comment]
Well now all of a sudden its not working again. Same issue. Settings are still the same and I generated the API. It works on the browser but not on my Android Dsub app.

**Comment by Phyks** [comment]
Are you using a different network when it does not work?
