### ISSUE TITLE
Last.fm API are deprecated, upgrade planned?

### ISSUE THREAD

**Issue by nioc** [ampache/ampache#922]
Hello, Ampache uses the old API for handhsake and submission of now-playing to Last.fm user profiles in [/lib/class/scrobbler.class.php] (https://github.com/ampache/ampache/blob/47a6585c88f3fb93b1e9516467efbcd5a6cc921a/lib/class/scrobbler.class.php).
As we can see in the [Last.fm API page] (http://www.lastfm.fr/api/submissions) :
>This protocol is now deprecated! Please use the Scrobbling API.
Note: There is now a new way for sending scrobbles called the Scrobbling API which is integrated into the rest of the Last.fm Web Services as opposed to being a separate service like 1.2.1. New clients should all use the Scrobbling API and not this protocol as we will not be issuing new client ids for this protocol and are likely to disable the "tst" client id at some point.

Are there any plans to migrate to theses new services? I just take a look, and the main problem  will be how (and where) to add the button to link user's Lasf.fm account and Ampache (it opens a lasf.fm GUI where the user have to login with his Last.fm account for granting the Ampache access to his profile) and return a token by callback.
I will try to add some functions to call authentication and scrobbling services in a new branch.

Any suggestions will be welcome :smiley:

**Comment by SUTJael** [comment]
Any kind of help is appreciate ;)
If you can take care about upgrading the API, that would be awesome ;)

**Comment by nioc** [comment]
Ok, I'll start tonight :smile:
Do I have to create a new branch or working on "develop"?
I will need to add an hyperlink which opens last.fm website for the granting process, on which ampache GUI can I add it?

**Comment by SUTJael** [comment]
You could maybe add the complete enrollment process into the Last.fm settings? (Settings->Plugins)
You can create a new branch on your local repository and then you will be able to create a pull request when everything works.

**Comment by nioc** [comment]
Hello, here are a few news :
-due to the Last.fm website upgrade, the API documentation was not accessible... (thanks Google cache),
-Libre.fm and Last.fm exposed the sames API,
-here is the sequence :
![diag-libre fm](https://cloud.githubusercontent.com/assets/5225411/9410925/5ac793b6-4823-11e5-95ba-d0fdaffab34b.png)
-I use the preference screen (plugin tab) for the GUI with a new link for each plugin :white_check_mark:,
-it opens the authentication url for the plugin and catch the returned token (by passing callback parameter) :white_check_mark:,
-receiving the token triggers the call of the getSession API [TODO :construction:],
-the session key is stored and the plugin is ready to use [TODO :construction:],
-rewrite the 2 plugins and Scrobbler class for simplification [TODO :construction:]
-replacing the call method `fsockopen` by `fopen` (with `stream_context_create`, `http_build_query` and `ob_get_contents`)

**Comment by nioc** [comment]
Hello, the last.fm API need to set the API key and the secret (seems to be a md5 hash, shown in the API account), do you know it?
Otherwise, I'll create a new Ampache API account and set it by default (and give you the ownership).

**Comment by Afterster** [comment]
Discussion continue on PR #935.
