### ISSUE TITLE
Premium streaming service ie Spotify and Ampache Question/Request

### ISSUE THREAD

**Issue by Gunrunner101** [ampache/ampache#923]
Team,

I have Ampache 3.8.0 up and running and loving it. I have changed Internet radio from false to true and this got me thinking. Has anyone had any luck taking a premium streaming service like spotify or Google listen 
(paid for) and converting it and streaming it in a format where Ampache can add it as a radio stream?

Am I out to lunch here or is there some wrapper that can do this.

Thanks in advance

Andrew.

**Comment by Gunrunner101** [comment]
Pyxis is a Command Line Player for SIRIUS and XM Sattelite Radio, if one could covert it to a format where we could add it as a stream to Ampache, it would make for a great feature.

**Comment by Gunrunner101** [comment]
I have been able to get spotify to stream using DSbrdige to Ampache

**Comment by Afterster** [comment]
Thanks for the discussion but duplicate with your post on Google Groups, I'm closing this here, please continue the discussion on the group.
