### ISSUE TITLE
Support of Aurora.js (flac.js and friends) for radio stations

### ISSUE THREAD

**Issue by sideeffffect** [ampache/ampache#933]
Aurora.js decoders doesn't seem to work on radio stations
http://amp1.cesnet.cz:8000/cro-d-dur.flac
http://amp.cesnet.cz:8000/cro-d-dur-256.ogg
http://icecast2.play.cz/crojazz128aac
it would be nice if I could listen to radio stations that use any of the aurora.js supported format

**Comment by Afterster** [comment]
I think this could be related to Icecast according to this recent issue on aurora.js project: https://github.com/audiocogs/aurora.js/issues/135

Did you try with another stream not based on an Icecast server (and which provides HEAD request method support)?

**Comment by sideeffffect** [comment]
I haven't tried it with non-icecast based streams.
Do you know of any that I can try?

**Comment by Afterster** [comment]
Funny thing is that I don't, all stream I know are using Icecast...
You can create a similar stream using *Channel* on Ampache but I think we have the same issue and doesn't support HEAD requests...

Handling HEAD request on channels is not that easy in fact, I can understand why Icecast doesn't support it :grin:

**Comment by Afterster** [comment]
Closing this here as it is on Icecast / Aurora.js project side.

**Comment by sideeffffect** [comment]
@ph3-der-loewe over at [#2223](https://gitlab.xiph.org/xiph/icecast-server/issues/2223#note_46469) suggests that this is a problem on ampache/aurora.js side
