### ISSUE TITLE
new theme css

### ISSUE THREAD

**Issue by jamiroconca** [ampache/ampache#934]
hi
I'm trying to write a theme for Ampache, but it seems that neither "base" or "colors" configuration are are considered... in fact css are loaded in this order:
templates/base.css
newtheme/templates/default.css
newtheme/templates/dark.css

several files (templates/show_login_form.inc.php, templates/show_lostpassword_form.inc.php,  templates/stylesheets.inc.php, templates/show_user_activate.inc.php, templates/show_user_registration.inc.php, templates/show_registration_confirmation.inc.php, ... )
load default.css and dark.css, with only 
```
$theme_path = AmpConfig::get('theme_path') . '/templates';
```
as configuration

**Comment by Afterster** [comment]
Indeed, this is a work I wasn't involved. @SUTJael, could you give your review as you developed this part: Is the theme css bases and colors not working but hard coded (looks like...)?

**Comment by Afterster** [comment]
Ok I reviewed the code and it wasn't implemented except in NewUI branch... This was wrong as we started to ship Ampache with theme configuration/color support, it has to be implemented. Should be ok now with latest commits.
