### ISSUE TITLE
Problem with 'featuring' and Musicbrainz ID

### ISSUE THREAD

**Issue by dengste** [ampache/ampache#941]
My library is completely tagged with musicbrainz ids. The problem I have is that sometimes Ampache associates an artist-id from musicbrainz with something like 'X feat. Y'. The problem is this: if you have a file with artist 'X feat. Y', then in the musicbrainz-db this will have the artist-id from 'X'. If Ampache sees such a file *first*, it will associate the artist-id not with 'X' but with 'X feat. Y'.

To give an example, say Ampache first sees a file with tags

Artist: X feat. Y
Musicbrainz artist-id: 123

and then later a file

Artist: X
Musicbrainz artist-id: 123

Ampache will put both with Artist 'X feat. Y' in its database.

**Comment by Afterster** [comment]
Yes this was already discussed but unfortunately there is no fix. Problem is that featuring artist doesn't have a different musicbrainz id that the real artist. First imported win.
Suggestion are welcome but we didn't find a solution last time...

**Comment by dengste** [comment]
How about an option to simply ignore the artist-id? I was actually surprised that Ampache used it in the first place. My library is tagged with proper 'artist' tags, so I would be happy if Ampache would simply stick to what's in there.
Another possibility might be to detect 'featuring' in the artist tag and strip it off. I think there's already code for that, as the FtInTitle plugin does this kind of detection already. Another possibility might be to look up the artist-id on Musicbrainz the first time you see a new one.

**Comment by Afterster** [comment]
Artist id became an important part of Ampache for most of new features and to correctly distinguish artists with similar names. This shouldn't be ignored.

Requesting Musicbrainz would be undesirable by default but it could be an improvement of Musicbrainz plugin (used only today to get track metadata from musicbrainz track-id).

Parsing artist name to remove 'featuring' could be the best option here but subject to modification to add new string parsing. Only artists with strange name like 'feat.' would failed which is an acceptable amount of error.

**Comment by Afterster** [comment]
In fact this case shouldn't happen if you have metadata Album Artist because it will treated first and album artist doesn't have featuring. But I will have featuring trimming for cases songs doesn't have album artist setted.

**Comment by Afterster** [comment]
Done with https://github.com/ampache/ampache/commit/4d3949cf5aa0a4e1f6a75aef4df9384b82dee076.
