### ISSUE TITLE
Error: Unable to open xxx/ampache/play when gathering album art/updating catalog 

### ISSUE THREAD

**Issue by AuToFiRE-xx** [ampache/ampache#946]
Pretty self explanatory title. I believe I have the ACLs set up properly as I did in previous versions of Ampache that worked. IPTables has been completely removed while diagnosing this and still continues to spit out this error.

**Comment by Afterster** [comment]
This could come from : web server simultaneous connection configuration, browser limitation on simultaneous connections per server, or php session lock.
Here you will have session lock first anyway, it is handled at song playback but not at catalog update. I believe we can unlock the session before processing the catalog process as catalog update is not really related to an user. I will take a look, thanks for the report.

**Comment by Afterster** [comment]
Ok session lock is freed before processing catalog update now with commit 7fa6e5c31af28c2d8c45ddfe615bfb68ed9cfa62.
Could you try again? Otherwise I didn't understand your issue correctly and in that case please details.
