### ISSUE TITLE
Catalog add / update does not work

### ISSUE THREAD

**Issue by Razrael** [ampache/ampache#947]
Hi there

Finally I found time to update my dev to work on the still pending PR.

After I've updated the Ampache instance, the importer does not work anymore on latest develop branch.
I get the following JS error in the add / update screen: `ReferenceError: sse_worker is not defined`. I get this in Firefox and Chrome.

`git bisect` got me to the commit "Add Server-Sent Events on catalog actions" (c763103beee3ca608f8b395383be787af094fd7a)

But I couldn't trace it down yet. Maybe you have an idea.

**Comment by Afterster** [comment]
sse_worker javascript function is declared on /lib/javascript/dynamicpage.js
Are you sure this is not only a cache issue on your browser side?

**Comment by Razrael** [comment]
Yes I am sure. I tested it also in which Ampache was never opened. 

The file is accessible trough the browser. There is just no script tag loading this script.

**Comment by Razrael** [comment]
I just discovered that the whole thing seems to work on my production environment with the same commit checked out. So it may be an issue within the Database. I'll let you know when I found something.

**Comment by Razrael** [comment]
Okay I could trace it down and resolve the issue for me. I could find it in the configuration.
But the bug is still there and I now know how to reproduce it.

To reproduce the error:
Go to your preferences -> interface and deactivate the AJAX page load. Reload the whole page and go to the add / update screen and reproduce my error.

I still had this deactivated because it was easier to develop when the catalog was done with Ajax and not SSE.

**Comment by Afterster** [comment]
Mhh indeed. We should probably add a logic to process the catalog update the old way if `ajax_load` is disabled.
