### ISSUE TITLE
Webplayer not playing in Chrome

### ISSUE THREAD

**Issue by darookee** [ampache/ampache#952]
When trying to play a song in the webplayer, the player pops up and the play-icon turns into the pause-icon, but the time will stay at ```00:00```.
This happens on Windows 7 Google Chrome 45.0.2454.85 and Android Chrome (latest stable).

Streaming to 'Subsonic' on Android works, so I don't think it is a general problem with the ampache installation.

I have disabled the Flash player and just enabled the HTML5 player.

[Here](http://pastebin.com/eqNsnB1Q) is the relevant debug log.

**Comment by Afterster** [comment]
Nothing wrong on your log file.
I believe HTML5 mp3 audio test is working here http://hpr.dogphilosophy.net/test/ ?

**Comment by darookee** [comment]
Yes, everything but flac is working.

At first I thought it had something to do with file permissions, but the fact that it works just fine using the Subsonic Android Client seems to rule that out...

**Comment by Afterster** [comment]
Any error on your browser console?

**Comment by darookee** [comment]
Just this warning:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

But the request with ```&type=song``` I don't get a status, just ```(pending)```, looks like it just isn't loading the song...?

**Comment by lachlan-00** [comment]
i'm getting a pretty similar experience.
[log: https://owncloud.lachlandewaard.org/index.php/s/McrIpJDObfQWQxn]

I have a JS error in the firefox console
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

 * all web playback fails stuck at 00:00
 * subsonic on android always plays
 * I've tried native as well as transcoding mp3->ogg and mp3->mp3
 * I've tried firefox, epiphany, chromium and midori

I was using 3.8-dev but the recent commits with composer broke updates so i went back to 3.6 on a new database (which worked) then i upgraded to 3.8 to use the subsonic client on android and that immediately broke web streaming.

**Comment by lachlan-00** [comment]
sorry for the double post, i actually have a heap of conversions that are stuck in my process list. It looks like every song i've tried to play in the web interface has gotten stuck.

root@debian# service apache2 status
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: active (running) since Sat 2015-09-26 20:11:24 AEST; 1 day 19h ago
  Process: 2475 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/apache2.service
           ├─ 1109 /usr/sbin/apache2 -k start
           ├─ 1303 /usr/sbin/apache2 -k start
           ├─ 1304 /usr/sbin/apache2 -k start
           ├─ 1408 /usr/sbin/apache2 -k start
           ├─ 1769 avconv -i /mnt/music/Weezer/(2005) Make Believe/101 - Beverly Hills.ogg -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 1784 /usr/sbin/apache2 -k start
           ├─ 1798 /usr/sbin/apache2 -k start
           ├─ 1800 /usr/sbin/apache2 -k start
           ├─ 1801 /usr/sbin/apache2 -k start
           ├─ 1976 /usr/sbin/apache2 -k start
           ├─ 2495 /usr/sbin/apache2 -k start
           ├─ 2497 /usr/sbin/apache2 -k start
           ├─ 2498 /usr/sbin/apache2 -k start
           ├─ 2502 /usr/sbin/apache2 -k start
           ├─ 2566 /usr/sbin/apache2 -k start
           ├─ 2599 /usr/sbin/apache2 -k start
           ├─ 2675 avconv -i /mnt/music/David Bowie/(1983) Ziggy Stardust The Motion Picture - The Album/110 - Time.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2681 avconv -i /mnt/music/Marilyn Manson/(1999) The Last Tour on Earth/201 - Coma White.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2698 /usr/sbin/apache2 -k start
           ├─ 2703 /usr/sbin/apache2 -k start
           ├─ 2711 avconv -i /mnt/music/Monty Python/(2005) Monty Python's SPAMALOT/101 - Tuning.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2798 /usr/sbin/apache2 -k start
           ├─ 2803 avconv -i /mnt/music/Die Perlen/(2013) Mein rechter Platz ist leer/101 - Mein rechter Platz ist leer.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2878 avconv -i /mnt/music/Die Perlen/(2013) Mein rechter Platz ist leer/102 - Morgen (Diesmal in Hah-Moll).mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2888 avconv -i /mnt/music/Die Perlen/(2013) Mein rechter Platz ist leer/103 - Run for Your Lives.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 2898 /usr/sbin/apache2 -k start
           ├─ 2990 /usr/sbin/apache2 -k start
           ├─ 2994 /usr/sbin/apache2 -k start
           ├─ 2995 /usr/sbin/apache2 -k start
           ├─ 3011 /usr/sbin/apache2 -k start
           ├─ 3013 avconv -i /mnt/music/Monolith/(2014) Near Crash/101 - Near Crash.mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 3104 avconv -i /mnt/music/!Bang Elektronika/(2011) Aktivierung/101 - aktivierung (nacht mix).mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─ 3143 /usr/sbin/apache2 -k start
           ├─ 3144 /usr/sbin/apache2 -k start
           ├─ 3145 /usr/sbin/apache2 -k start
           ├─ 3146 /usr/sbin/apache2 -k start
           ├─ 3151 /usr/sbin/apache2 -k start
           ├─22193 /usr/sbin/apache2 -k start
           ├─22483 /usr/sbin/apache2 -k start
           ├─22611 /usr/sbin/apache2 -k start
           ├─22642 /usr/sbin/apache2 -k start
           ├─22792 /usr/sbin/apache2 -k start
           ├─22793 /usr/sbin/apache2 -k start
           ├─22797 /usr/sbin/apache2 -k start
           ├─22812 /usr/sbin/apache2 -k start
           ├─22930 /usr/sbin/apache2 -k start
           ├─22932 /usr/sbin/apache2 -k start
           ├─22940 /usr/sbin/apache2 -k start
           ├─22941 /usr/sbin/apache2 -k start
           ├─23026 /usr/sbin/apache2 -k start
           ├─23061 /usr/sbin/apache2 -k start
           ├─23066 /usr/sbin/apache2 -k start
           ├─23124 /usr/sbin/apache2 -k start
           ├─23241 /usr/sbin/apache2 -k start
           ├─23374 /usr/sbin/apache2 -k start
           ├─23375 /usr/sbin/apache2 -k start
           ├─23382 avconv -i /mnt/music/The Prodigy/(1996) Firestarter/101 - Firestarter (Edit).mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─23386 /usr/sbin/apache2 -k start
           ├─23388 /usr/sbin/apache2 -k start
           ├─23435 /usr/sbin/apache2 -k start
           ├─23442 avconv -i /mnt/music/!Bang Elektronika/(2011) Aktivierung/101 - aktivierung (nacht mix).mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─23479 /usr/sbin/apache2 -k start
           ├─23480 /usr/sbin/apache2 -k start
           ├─23482 /usr/sbin/apache2 -k start
           ├─23483 /usr/sbin/apache2 -k start
           ├─23485 /usr/sbin/apache2 -k start
           ├─23491 /usr/sbin/apache2 -k start
           ├─23495 avconv -i /mnt/music/The Prodigy/(1996) Firestarter/102 - Firestarter (Empirion Mix).mp3 -vn -b:a 160K -c:a libvorbis -f ogg pipe:1
           ├─23503 /usr/sbin/apache2 -k start
           ├─23504 /usr/sbin/apache2 -k start
           ├─23506 /usr/sbin/apache2 -k start
           ├─23507 /usr/sbin/apache2 -k start
           ├─23508 /usr/sbin/apache2 -k start
           ├─23522 /usr/sbin/apache2 -k start
           ├─23526 /usr/sbin/apache2 -k start
           ├─23527 /usr/sbin/apache2 -k start
           ├─23528 /usr/sbin/apache2 -k start
           ├─23529 /usr/sbin/apache2 -k start
           ├─23532 /usr/sbin/apache2 -k start
           ├─23611 /usr/sbin/apache2 -k start
           ├─23616 /usr/sbin/apache2 -k start
           ├─23620 /usr/sbin/apache2 -k start
           ├─23621 /usr/sbin/apache2 -k start
           ├─23632 /usr/sbin/apache2 -k start
           ├─23682 /usr/sbin/apache2 -k start
           ├─23687 /usr/sbin/apache2 -k start
           ├─23706 /usr/sbin/apache2 -k start
           ├─23709 /usr/sbin/apache2 -k start
           ├─23710 /usr/sbin/apache2 -k start
           ├─23711 /usr/sbin/apache2 -k start
           ├─23817 /usr/sbin/apache2 -k start
           ├─23819 /usr/sbin/apache2 -k start
           ├─23820 /usr/sbin/apache2 -k start
           ├─23832 /usr/sbin/apache2 -k start
           ├─23860 /usr/sbin/apache2 -k start
           ├─23877 /usr/sbin/apache2 -k start
           ├─23879 /usr/sbin/apache2 -k start
           ├─23881 /usr/sbin/apache2 -k start
           ├─23884 /usr/sbin/apache2 -k start
           ├─23935 /usr/sbin/apache2 -k start
           ├─24334 /usr/sbin/apache2 -k start
           ├─26187 /usr/sbin/apache2 -k start
           ├─28903 /usr/sbin/apache2 -k start
           ├─29257 /usr/sbin/apache2 -k start
           ├─29259 /usr/sbin/apache2 -k start
           ├─29279 /usr/sbin/apache2 -k start
           ├─29797 /usr/sbin/apache2 -k start
           └─32197 /usr/sbin/apache2 -k start

Sep 26 20:11:24 mail apache2[22178]: Starting web server: apache2.
Sep 27 07:35:08 mail apache2[831]: Reloading web server: apache2.
Sep 28 07:35:08 mail apache2[21959]: Reloading web server: apache2.
Sep 28 15:41:07 mail apache2[2475]: Reloading web server: apache2.

**Comment by darookee** [comment]
I just noticed that the request that has the ```(pending)``` status does not get logged in the apache access or error logs. It just keeps loading in Chrome and Firefox...

**Comment by ufp32633** [comment]
I experienced this problem too, see: https://github.com/ampache/ampache/issues/961#issuecomment-142794212 and in my case the solution is a bit weird.
The solution is in the transcoding section of the config file.
If I set transcode_flac = "required" then it gets stuck. If I omit the quotes like this: transcode_flac = required then it is working.

**Comment by darookee** [comment]
I found my solution. The script stopped without any error after trying to access last.fm. I disabled the last.fm-Plugin and now it's working. I'm closing this, as the other problems don't seem related to this but more to issue #961.

**Comment by lachlan-00** [comment]
Works for me too as soon as I disable the last.fm plugin.

**Comment by nioc** [comment]
Hi guys. The way apache sends scrobbles to last.fm and libre.fm has changed recently.
In order to make it works, you have to process the authentication sequence from this url /index.php#preferences.php?tab=plugins.
Sorry for the inconvenience.

**Comment by Afterster** [comment]
After investigation I'm not sure playing issue is related to your changes as I cannot reproduce it. Guys, are you using 3.8.0 or latest changes on develop branch?

**Comment by lachlan-00** [comment]
I don't get any issues using last.fm plugin v5 enabled on 3.8.0 or 3.8.1-develop.

I think it was caused by the last.fm api change on the older plugin version (3/4) which is why it worked after it was disabled.

**Comment by darookee** [comment]
I just updated to the current development branch, activated the last.fm plugin and it worked just fine. The issues were with the last.fm plugin that required username and password, this new one seems to connects through another method (oauth?).

So no issue here... :-)

**Comment by Afterster** [comment]
Ok thanks for the feedbacks. Then I believe @nioc changes was opportune, nice timing :)

**Comment by nioc** [comment]
Glad to read this :)
As the old method will be deprecated, perhaps lastfm servers handling it should have been downsized and make the calls fails.
