### ISSUE TITLE
AGPL v3 relicensing

### ISSUE THREAD

**Issue by Afterster** [ampache/ampache#954]
Ampache is currently licensed under GPL v2 which is far from perfect for a web application today.
I would like to move it to [**AGPL v3**](http://www.gnu.org/licenses/agpl-3.0.en.html).

For that I would need all contributors listed bellow to answer to this thread with acceptation/refusal of this license change for all their contributions to Ampache.
If no answer or disagreement from one contributor, this could result to license change failure (if main contributor like vollmerk or flowerysong), code removal of author contributions, or project split between GPL v2 and AGPL v3 code (if possible...). GitHub account will be used as identification proof.
Some of you may have contribute only 1 or 2 commits, and probably left the projects years ago but this still matter. Please takes some minutes to answer :wink:.

 * ~~Afterster~~
 * ~~vollmerk~~
 * ~~flowerysong~~
 * ~~SUTJael~~ 
 * ~~Psy-Virus~~
 * ~~momo-i~~
 * ~~jcwmoore~~
 * ~~Razrael~~
 * ~~brownl~~
 * ~~changi67~~
 * ~~Deathcow~~
 * ~~arnaudbey~~
 * ~~wagnered~~
 * ~~martindiphoorn~~
 * ~~purdyk~~
 * ~~RyanCopley~~
 * ~~nan4k7~~
 * ~~eliasp~~
 * ~~hypfvieh~~
 * ~~SeregaPru~~
 * ~~KaivoAnastetiks~~
 * ~~thinca~~
 * ~~Fondor1~~
 * ~~ss23~~
 * ~~Niols~~
 * ~~thegeekrv~~
 * ~~tsquare66~~
 * ~~fredthomsen~~
 * ~~Combustible~~
 * ~~nicklan~~
 * ~~a9k~~
 * ~~anonymous2ch~~
 * ~~ainola~~
 * ~~eigan~~
 * ~~nioc~~
 * ~~stebe~~
 * ~~bliptec~~
 * ~~Toilal~~
 * ~~randomessence~~
 * ~~sarbuckle~~
 * ~~trogdor1138~~
 * ~~meandor~~
 * ~~thejk~~
 * ~~axelsimon~~
 * ~~thezerobit~~
 * ~~victorhaggqvist~~
 * ~~mat-mo~~
 * ~~mrpi~~
 * ~~Swissbite~~
 * ~~Natureshadow~~
 * ~~hyperactivated~~
 * ~~tan-ce~~
 * ~~Bidules079~~
 * ~~e3betht~~
 * ~~uberbrady~~
 * ~~oppai~~
 * ~~new3kinnnn~~
 * ~~cslamar~~
 * ~~hbrunn~~
 * ~~hopson~~
 * ~~protag~~
 * ~~bikkuri10~~
 * ~~spocky~~
 * ~~grissoma~~
 * ~~pb1dft~~
 * ~~flashk~~
 * ~~slienard~~

There is also list of *old* contributors retrieved from git history but unavailable on GitHub. Contact will be initiated outside GitHub once properly identified. Related list bellow so you can follow the overall progress, which will certainly takes more time.
 * ~~Florent Fourcot~~
 * ~~jack~~
 * ~~mywindow~~

Thanks!

**Comment by fredthomsen** [comment]
No issue with this. I accept.

On Mon, Sep 14, 2015 at 6:20 PM, Afterster <notifications@github.com> wrote:

> Ampache is currently licensed under GPL v2 which is far from perfect for a
> web application today.
> I would like to move it to *AGPL v3*
> <http://www.gnu.org/licenses/agpl-3.0.en.html>.
>
> For that I would need all contributors listed bellow to answer to this
> thread with acceptation/refusal of this license change for all their
> contributions to Ampache.
> If no answer or disagreement from one contributor, this could result to
> license change failure (if main contributor like vollmerk or flowerysong),
> code removal of author contributions, or project split between GPL v2 and
> AGPL v3 code (if possible...). GitHub account will be used as
> identification proof.
> Some of you may have contribute only 1 or 2 commits, and probably left the
> projects years ago but this still matter. Please takes some minutes to
> answer [image: :wink:].
>
>    - @vollmerk <https://github.com/vollmerk>
>    - @flowerysong <https://github.com/flowerysong>
>    - @SUTJael <https://github.com/SUTJael>
>    - @Psy-Virus <https://github.com/Psy-Virus>
>    - @momo-i <https://github.com/momo-i>
>    - @jcwmoore <https://github.com/jcwmoore>
>    - @Razrael <https://github.com/Razrael>
>    - @brownl <https://github.com/brownl>
>    - @changi67 <https://github.com/changi67>
>    - @Deathcow <https://github.com/Deathcow>
>    - @arnaudbey <https://github.com/arnaudbey>
>    - @wagnered <https://github.com/wagnered>
>    - @martindiphoorn <https://github.com/martindiphoorn>
>    - @purdyk <https://github.com/purdyk>
>    - @RyanCopley <https://github.com/RyanCopley>
>    - @nan4k7 <https://github.com/nan4k7>
>    - @eliasp <https://github.com/eliasp>
>    - @hypfvieh <https://github.com/hypfvieh>
>    - @SeregaPru <https://github.com/SeregaPru>
>    - @KaivoAnastetiks <https://github.com/KaivoAnastetiks>
>    - @thinca <https://github.com/thinca>
>    - @Fondor1 <https://github.com/Fondor1>
>    - @ss23 <https://github.com/ss23>
>    - @Niols <https://github.com/Niols>
>    - @thegeekrv <https://github.com/thegeekrv>
>    - @tsquare66 <https://github.com/tsquare66>
>    - @fredthomsen <https://github.com/fredthomsen>
>    - @Combustible <https://github.com/Combustible>
>    - @nicklan <https://github.com/nicklan>
>    - @a9k <https://github.com/a9k>
>    - @anonymous2ch <https://github.com/anonymous2ch>
>    - @ainola <https://github.com/ainola>
>    - @eigan <https://github.com/eigan>
>    - @nioc <https://github.com/nioc>
>    - @stebe <https://github.com/stebe>
>    - @bliptec <https://github.com/bliptec>
>    - @Toilal <https://github.com/Toilal>
>    - @randomessence <https://github.com/randomessence>
>    - @sarbuckle <https://github.com/sarbuckle>
>    - @trogdor1138 <https://github.com/trogdor1138>
>    - @meandor <https://github.com/meandor>
>    - @thejk <https://github.com/thejk>
>    - @axelsimon <https://github.com/axelsimon>
>    - @thezerobit <https://github.com/thezerobit>
>    - @victorhaggqvist <https://github.com/victorhaggqvist>
>    - @mat-mo <https://github.com/mat-mo>
>    - @mrpi <https://github.com/mrpi>
>    - @Swissbite <https://github.com/Swissbite>
>    - @Natureshadow <https://github.com/Natureshadow>
>    - @hyperactivated <https://github.com/hyperactivated>
>    - @tan-ce
>    - @Bidules079
>    - @e3betht
>    - @uberbrady
>    - @oppai
>    - @new3kinnnn
>
> There is also list of *old* contributors retrieved from git history but
> unavailable on GitHub. Contact will be initiated outside GitHub and I will
> post the list here later so you can follow the overall progress, which will
> certainly takes a lot of time.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/954>.
>



-- 
-Fred Thomsen

**Comment by thegeekrv** [comment]
I accept ;)

**Comment by purdyk** [comment]
I accept

**Comment by bliptec** [comment]
I have no problem with this

**Comment by brownl** [comment]
This seems like a positive change. I accept.

**Comment by Fondor1** [comment]
Fondor1: I accept.

**Comment by nan4k7** [comment]
No problem! I accept.

**Comment by RyanCopley** [comment]
Not only do I accept, but those who reject, I will assist in removing their code and rewriting under AGPL

**Comment by trogdor1138** [comment]
Accept

**Comment by nicklan** [comment]
Fine by me

**Comment by hyperactivated** [comment]
I accept.

**Comment by ainola** [comment]
I accept. Thanks for all your work, Afterster! You should be proud of what you've made.

**Comment by victorhaggqvist** [comment]
I accept

--
Victor

**Comment by wagnered** [comment]
I also accept....

On 09/14/2015 03:20 PM, Afterster wrote:
> Ampache is currently licensed under GPL v2 which is far from perfect for
> a web application today.
> I would like to move it to *AGPL v3*
> <http://www.gnu.org/licenses/agpl-3.0.en.html>.
> 
> For that I would need all contributors listed bellow to answer to this
> thread with acceptation/refusal of this license change for all their
> contributions to Ampache.
> If no answer or disagreement from one contributor, this could result to
> license change failure (if main contributor like vollmerk or
> flowerysong), code removal of author contributions, or project split
> between GPL v2 and AGPL v3 code (if possible...). GitHub account will be
> used as identification proof.
> Some of you may have contribute only 1 or 2 commits, and probably left
> the projects years ago but this still matter. Please takes some minutes
> to answer :wink:.
> 
>   * @vollmerk <https://github.com/vollmerk>
>   * @flowerysong <https://github.com/flowerysong>
>   * @SUTJael <https://github.com/SUTJael>
>   * @Psy-Virus <https://github.com/Psy-Virus>
>   * @momo-i <https://github.com/momo-i>
>   * @jcwmoore <https://github.com/jcwmoore>
>   * @Razrael <https://github.com/Razrael>
>   * @brownl <https://github.com/brownl>
>   * @changi67 <https://github.com/changi67>
>   * @Deathcow <https://github.com/Deathcow>
>   * @arnaudbey <https://github.com/arnaudbey>
>   * @wagnered <https://github.com/wagnered>
>   * @martindiphoorn <https://github.com/martindiphoorn>
>   * @purdyk <https://github.com/purdyk>
>   * @RyanCopley <https://github.com/RyanCopley>
>   * @nan4k7 <https://github.com/nan4k7>
>   * @eliasp <https://github.com/eliasp>
>   * @hypfvieh <https://github.com/hypfvieh>
>   * @SeregaPru <https://github.com/SeregaPru>
>   * @KaivoAnastetiks <https://github.com/KaivoAnastetiks>
>   * @thinca <https://github.com/thinca>
>   * @Fondor1 <https://github.com/Fondor1>
>   * @ss23 <https://github.com/ss23>
>   * @Niols <https://github.com/Niols>
>   * @thegeekrv <https://github.com/thegeekrv>
>   * @tsquare66 <https://github.com/tsquare66>
>   * @fredthomsen <https://github.com/fredthomsen>
>   * @Combustible <https://github.com/Combustible>
>   * @nicklan <https://github.com/nicklan>
>   * @a9k <https://github.com/a9k>
>   * @anonymous2ch <https://github.com/anonymous2ch>
>   * @ainola <https://github.com/ainola>
>   * @eigan <https://github.com/eigan>
>   * @nioc <https://github.com/nioc>
>   * @stebe <https://github.com/stebe>
>   * @bliptec <https://github.com/bliptec>
>   * @Toilal <https://github.com/Toilal>
>   * @randomessence <https://github.com/randomessence>
>   * @sarbuckle <https://github.com/sarbuckle>
>   * @trogdor1138 <https://github.com/trogdor1138>
>   * @meandor <https://github.com/meandor>
>   * @thejk <https://github.com/thejk>
>   * @axelsimon <https://github.com/axelsimon>
>   * @thezerobit <https://github.com/thezerobit>
>   * @victorhaggqvist <https://github.com/victorhaggqvist>
>   * @mat-mo <https://github.com/mat-mo>
>   * @mrpi <https://github.com/mrpi>
>   * @Swissbite <https://github.com/Swissbite>
>   * @Natureshadow <https://github.com/Natureshadow>
>   * @hyperactivated <https://github.com/hyperactivated>
>   * @tan-ce
>   * @Bidules079
>   * @e3betht
>   * @uberbrady
>   * @oppai
>   * @new3kinnnn
> 
> There is also list of /old/ contributors retrieved from git history but
> unavailable on GitHub. Contact will be initiated outside GitHub and I
> will post the list here later so you can follow the overall progress,
> which will certainly takes a lot of time.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/954>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by KaivoAnastetiks** [comment]
I also accept.

**Comment by thinca** [comment]
I accept.

**Comment by nioc** [comment]
Fine, I accept :smile:

**Comment by momo-i** [comment]
Accept.

**Comment by SeregaPru** [comment]
Accept.


________________________________
От: momo-i <notifications@github.com>
Отправлено: 15 сентября 2015 г. 6:49
Кому: ampache/ampache
Копия: SeregaPru
Тема: Re: [ampache] AGPL v3 relicensing (#954)


Accept.

-

**Comment by ss23** [comment]
Accept

**Comment by hypfvieh** [comment]
I accept too

**Comment by Toilal** [comment]
Accept.

**Comment by changi67** [comment]
I accept too

**Comment by oppai** [comment]
Accept

**Comment by Deathcow** [comment]
Accept

**Comment by new3kinnnn** [comment]
No problem. I accept

**Comment by thejk** [comment]
Sure, I accept

**Comment by hbrunn** [comment]
:+1:

**Comment by arnaudbey** [comment]
No problemo ! :rabbit:

**Comment by eigan** [comment]
I accept.

**Comment by eliasp** [comment]
Accepted

**Comment by Bidules079** [comment]
I accept.​

2015-09-15 7:51 GMT+02:00 Afterster <notifications@github.com>:

**Comment by mrpi** [comment]
I accept.

**Comment by tan-ce** [comment]
I accept.

**Comment by Razrael** [comment]
I accept

**Comment by axelsimon** [comment]
Good to see things moving forward, including in this way. Aye, I accept! :)

**Comment by Niols** [comment]
I accept, thanks for keeping this project alive!

**Comment by vollmerk** [comment]
Accept! :)

**Comment by e3betht** [comment]
I accept. :)

**Comment by hopson** [comment]
I accept.  Good luck!  -Robert Hopson

**Comment by anonymous2ch** [comment]
I accept

**Comment by martindiphoorn** [comment]
I accept! :)

**Comment by stebe** [comment]
I accept!

**Comment by protag** [comment]
I accept

**Comment by flowerysong** [comment]
Okay by me.

**Comment by thezerobit** [comment]
I accept! (@thezerobit)

**Comment by Swissbite** [comment]
I accept.

**Comment by uberbrady** [comment]
I accept the proposed licensing change.

-B.

**Comment by Psy-Virus** [comment]
I agree. :-)

**Comment by bikkuri10** [comment]
I accept the licensing change.

**Comment by jcwmoore** [comment]
accept.

**Comment by grissoma** [comment]
Accept.

**Comment by pb1dft** [comment]
I accept, Github account pb1dft

**Comment by flashk** [comment]
I accept

**Comment by mat-mo** [comment]
I accept

**Comment by spocky** [comment]
I accept

**Comment by Combustible** [comment]
I accept

**Comment by a9k** [comment]
Good idea. I accept.

**Comment by SUTJael** [comment]
Sure (sorry for the delay, vacation first!) ;)

**Comment by randomessence** [comment]
I accept.

**Comment by Natureshadow** [comment]
I'm fine with re-licensing.

In fact, for future reference, feel free to pick any OSI-approved license for my contributions.

**Comment by meandor** [comment]
I accept

**Comment by cslamar** [comment]
I Accept

**Comment by slienard** [comment]
I accept.

**Comment by sarbuckle** [comment]
I @sarbuckle Accept! Thanks for your patience Afterster.

**Comment by Afterster** [comment]
Thanks all, almost here :)
After commits review of remaining people who didn't agreed yet, I removed bhasselbeck, cjsmo, nf, rosensama, sigger and xgizzmo from the list. They don't have any code anymore on current code base.
People with remaining code who didn't agreed and are not answering for now are: @tsquare66 (commits 6cf030675291a1f680cd80d1e83834b03535e9bb and 5ca3053bc8b745590c13d8ebc360669de1eaa282) and mywindow (commit c3b6ef7ad2e888fd228f62ed3cef6f7d55070a84).

**Comment by tsquare66** [comment]
I accept.
Sorry for the delay
I haven't noticed that I'll had to do this

**Comment by Afterster** [comment]
All contributors with active changes accepted the license change.
Ampache is now under AGPL v3 license :smile: :smile: :smile:.

Thanks a lot everybody, really!

**Comment by pb1dft** [comment]
Time for a celebration.

;)

Gr pb1dft

-----Original message-----
