### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by nakinigit** [ampache/ampache#956]
Did a git -pull on my install directory. Now I get a message that my dependancies are not met, and I need to "download and install Composer from http://getcomposer.org then run `composer install` on Ampache directory" I do that, then get:
<code>  Problem 1
    - Installation request for openid/php-openid 2.3.0 -> satisfiable by openid/php-openid[2.3.0].
    - openid/php-openid 2.3.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
</code>
I'm using ubuntu 14.04, the newest available php-openid is 2.2.2-1.2. will that work? Would try it, but don't even know what it is or why all of a sudden I need it.

**Comment by apastuszak** [comment]
Composer configuration needs to be added to the wiki.

**Comment by wagnered** [comment]
Your system is missing php-gmp which is an extension of PHP You should
find it in your distribution's repository.  Once that is installed and
enabled,composer should install openid/php-openid[2.3.0].

On 09/16/2015 09:03 PM, nakinigit wrote:
> Did a git -pull on my install directory. Now I get a message that my
> dependancies are not met, and I need to "download and install Composer
> from http://getcomposer.org then run |composer install| on Ampache
> directory" I do that, then get:
> |Problem 1
> - Installation request for openid/php-openid 2.3.0 -> satisfiable by
> openid/php-openid[2.3.0].
> - openid/php-openid 2.3.0 requires ext-gmp * -> the requested PHP
> extension gmp is missing from your system.
> |
> I'm using ubuntu 14.04, the newest available php-openid is 2.2.2-1.2.
> will that work? Would try it, but don't even know what it is or why all
> of a sudden I need it.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/956>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by axelsimon** [comment]
On Debian jessie, I had to install php5-gmp :
`aptitude install php5-gmp`

**Comment by Afterster** [comment]
Mhh ok. That should be changed because openid is generally not used, it shouldn't be mandatory.

**Comment by ufp32633** [comment]
It gives me this error:

Fatal error: Class 'Requests_Hooks' not found in /usr/share/ampache/ampache-develop/modules/requests/Requests.php on line 484

I assume this is related to composer.

**Comment by ufp32633** [comment]
For anyone stuck with a defunctional version of Ampache. It is possible to recover:
Go into the folder of ampache and on the command line execute: sudo git reset --hard fa8084d
This will revert Ampache to a working version of a few days ago.
You might want to go to another commit but this worked for me.
And as always: be careful trying this.

**Comment by apastuszak** [comment]
The big thing I need to know how to run composer as the web server user when I do an ampache update.  I can run it manually from the command line using sudo, and it pulled down a bunch of stuff and installed it.  But running through sudo, it's using the API key stored in my home directory.  I assume when the ampache update process kicks off, it is not going to have access to my home drive to read my config.  The www-data user doesn't have a home drive, so not sure where to store the composer config.

Also, the version of composer that is created by the install was had the filename composer.shah, I believe.  Do I need to rename that to just "composer" to get to work with the Ampache auto-update process?

**Comment by Afterster** [comment]
Yes the wiki should be updated but I'm not sure the process will not change soon. I'm not used to Composer yet and I'm trying to find the best way to process for Ampache.
@apastuszak, to install Composer globally you should run `curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin`
I believe you're talking about GitHub API Key here? This one is really annoying and it was a bad discovery about Composer/GitHub combo. I really don't want people to have a GitHub account to install Ampache... I'm looking for a workaround here.

**Comment by Afterster** [comment]
About openid/php5-gmp dependency issue.
There is no such thing like optional dependency on Composer based on conditions and there approach are quite simple: you have to create a separate package.
Then Ampache openid code should become a plugin with its own dependencies. We don't necessary need another Git repository for every plugin but at least a folder per plugin with its own composer.json file in case the dependency is too much intrusive.
That's how I'm gonna fix it but I'm open to other suggestions.

**Comment by apastuszak** [comment]
What about Ampache having a universal API key, or will that violate some TOS?

Will Composer be used in the master branch at some point, or only in the development branch?  If you're going to hard-code the modules into the master branch, then the API key is only an issue for us bleeding edge guys.

**Comment by Afterster** [comment]
Hehe :)
Ampache universal API key would violate GitHub TOS yes unfortunately.
The plan is to use Composer on master yes, but to provide a download package with all dependencies at each release (need to found a way to automate this).

**Comment by wagnered** [comment]
@Afterster,

Perhaps you already read this, but I'm wondering if the docs at:
https://getcomposer.org/doc/05-repositories.md#packagist might provide
an answer.  Especially the section on VCS and "Hosting Your Own".



On 09/17/2015 01:25 PM, Afterster wrote:
> Hehe :)
> Ampache universal API key would violate GitHub TOS yes unfortunately.
> The plan is to use Composer on master yes, but to provide a download
> package with all dependencies at each release (need to found a way to
> automate this).
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/956#issuecomment-141217453>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
This is interesting but not really usable for public use I think. I don't want to setup a custom server to host Sati or similar tool. We're doing fine without any server in charge right now. But thanks for the pointer!
For what I'm reading, we could be able to avoid this API rate limit by using `composer install --prefer-source --no-interaction` and because composer.lock is committed (as it should be for an app).

**Comment by psjbeisler** [comment]
got it to work right (i think), but definitely tricky  w/o a wiki

**Comment by Afterster** [comment]
About the original dependency issue, I did some change on Composer.json with db131af442453c719581830c35a8336bf9914658 to always detect system dependencies used by optional modules to not break the installation. This should be fixed now.
I'm not sure it is the best way to do but other solutions that I'm aware of are requiring a lot of code changes and would make the installation process more difficult for end users.

**Comment by nakinigit** [comment]
so I ran:
<pre>curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin</pre>
My Ampache installation is /usr/share/ampache, so I assume that is where it should be installed. I get the following error:
<pre>#!/usr/bin/env php
All settings correct for using Composer
Downloading...
Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
Downloading...
Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
Downloading...
Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
The download failed repeatedly, aborting.
</pre>

**Comment by wagnered** [comment]
I tried the command with both sudo and su.  It only worked with su.

I guess because it's a compound statement and only the first part gets
the permissions.

You can also download the latest snapshot from
https://getcomposer.org/download/ and just do  sudo cp composer.phar
/usr/local/bin/composer.


On 09/19/2015 03:21 PM, nakinigit wrote:
> so I ran:
> 
> curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin
> 
> My Ampache installation is /usr/share/ampache, so I assume that is where
> it should be installed. I get the following error:
> 
> #!/usr/bin/env php
> All settings correct for using Composer
> Downloading...
> Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> fwrite() expects parameter 1 to be resource, boolean given
> Downloading...
> Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> fwrite() expects parameter 1 to be resource, boolean given
> Downloading...
> Could not create file /usr/share/ampache/composer: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> Download failed: fopen(/usr/share/ampache/composer): failed to open stream: Permission denied
> fwrite() expects parameter 1 to be resource, boolean given
> The download failed repeatedly, aborting.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/956#issuecomment-141711134>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by nakinigit** [comment]
Wow, what a mess. Downloaded & ran the snapshot. Got the messages regarding guzzle/common, but it seemed to install. Ampache now opens, but only partially. Library is not present, along all the settings links. So then I do a git reset in an attempt to revert to a pull prior to composer, and now the library is there, but many fields such as song title, artist, album are missing. I suspect it might have something to do with the database update from the most recent pull.

I have backups of the database, and would like to revert all to a point in time, say beginning of September. How do I make sure Ampache version is in sync with the database?  Also, when I do a git reflog to see the pulls, there is no reference date. So it seems to be guesswork as to how far back in time I may be going.

Lastly, anyway to uninstall composer?

**Comment by wagnered** [comment]
Just throwing some ideas out:

Are you actually using the latest commit?  The one that was modified for
use with Composer?

If you ran "composer install" in the /usr/share/ampache folder, does the
installed files have the correct ownership/permissions?

if you do a git-log you can see the commits with dates. Just checkout
the commit for the date of your choice. then restore the database backup
from nearest that date. Your ampache.cfg.php shouldn't be touched and
should be ready to go.

It's not really necessary, but to delete composer(.phar), just do a sudo
rm /usr/local/bin/composer or from where ever you copied it to.

There should be a .composer folder in the home folder of what ever you
ran composer as (probably root).

I don't believe that the database structure has been changed since
before 3.8.0 was released.

On 09/19/2015 05:25 PM, nakinigit wrote:
> Wow, what a mess. Downloaded & ran the snapshot. Got the messages
> regarding guzzle/common, but it seemed to install. Ampache now opens,
> but only partially. Library is not present, along all the settings
> links. So then I do a git reset in an attempt to revert to a pull prior
> to composer, and now the library is there, but many fields such as song
> title, artist, album are missing. I suspect it might have something to
> do with the database update from the most recent pull.
> 
> I have backups of the database, and would like to revert all to a point
> in time, say beginning of September. How do I make sure Ampache version
> is in sync with the database? Also, when I do a git reflog to see the
> pulls, there is no reference date. So it seems to be guesswork as to how
> far back in time I may be going.
> 
> Lastly, anyway to uninstall composer?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/956#issuecomment-141721905>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by psjbeisler** [comment]
So how do i do a manual update like a Git pull for composer. I have a module failing and Ampache doesnt want to load. Ive seen it flash by when i upgrade normally but cant remember what the command is

**Comment by nakinigit** [comment]
@psjbeisler Once composer was installed, I ran /usr/local/bin/composer/composer.phar selfupdate.

**Comment by psjbeisler** [comment]
i just wiped the whole directory and started over, i must still be doing it wrong. I have the xbmc module loaded and because of that, ampache doesnt load correctly.

**Comment by nakinigit** [comment]
@psjbeisler I did a git reset --hard to a commit just prior to the implementation of composer. That got things going again. I also tried a new clone (but with the same database) and couldn't get ampache's page to appear correctly, same as my prior attempts with composer. I also have the xbmc module, I use it a lot. When I get the time, I will re-enable logging and try to figure out what's happening. But how do you know xbmc is the culprit?

**Comment by psjbeisler** [comment]
@nakinigit [Runtime Error] require_once(ampache/modules/localplay/xbmc/xbmc.controller.php): failed to open stream: No such file or directory in file ampache/lib/class/localplay.class.php(103)
 I tried editing the database directly to disable Localplay but that didnt work.

**Comment by Afterster** [comment]
Thanks for all your tests guys, it's getting some times to have something smooth with Composer but we are going to have it.
About xbmc plugin issue since Composer move, this should have been fixed now.

**Comment by psjbeisler** [comment]
editing the database directly did end up working for me, i did have to set some other options over again, but it was setter than starting from scratch

**Comment by florihupf** [comment]
Just found this thread because my ampache isn't working anymore since it complains about me needing to download composer.

Reading this thread, I decided to not going to do it.  Scared that it ruins my install ;-)

Just curious, apart from tons of problems I don't see the benefit.  What problem does it try to solve?  Is it worth all that hassle?

**Comment by florihupf** [comment]
Just FYI: git reset --hard fa8084d fixed it for me too.

**Comment by Afterster** [comment]
Sure composer *complexify* Ampache installation as it had an additional tool and step. But:
 * This will only impact people using develop branch (ok, it's a lot of people). Releases will be provided with and without embedded dependencies (and ok, there is no much releases it's why people are using develop branch).
 * Yes it is important to use it. It's not a pain to update dependencies anymore, it ensures that we don't hack fix the dependencies, and trust me it also cleaned a bit the code

Sure, the transition is not that smooth for now but it's working.

**Comment by florihupf** [comment]
Thanks for the info.  I give it another try.

**Comment by pluser** [comment]
About gmp dependency problem,
Maybe add
```
"provide": {
 "ext-gmp": "*"
},
```
into composer.json will help you?

**Comment by Afterster** [comment]
I edited composer.json few days ago with `platform` directive which is for what I know similar to `provide` but for platform dependencies (ext-gmp is more a platform dependency than a package dependency).

**Comment by pluser** [comment]
I see. So gmp module is not depended yet, right?
Thanks for the info!

**Comment by Afterster** [comment]
It is only if using openid.
The alternative would have been to do code refactoring the complete Ampache project to make everything a plugin on different git repositories. Which is just too heavy for now :smile:.

**Comment by nakinigit** [comment]
OK, did a new clone, but transferred my ampache.cfg.php to the new clone & maintained the existing database. For starters, this is what the ampache page looks like:
![screenshot from 2015-10-11 15 52 56](https://cloud.githubusercontent.com/assets/6116858/10419560/43b5ad04-7030-11e5-99a4-7b94ea01aed8.png)
So there is no library, settings, or anything else resembling my setup. I enabled logging, this is all that has shown up:
<pre>-> cat ampache.20151011.log
2015-10-11 15:41:59 [admin] (session) -> 78g3isuvom4h98dnrbrb1lt5r1 has been extended to Sun, 11 Oct 2015 16:41:59 -0700 extension length 3600 
2015-10-11 15:41:59 [admin] (session) -> Session created: 14d52731df42da8f542628bef020240a 
2015-10-11 15:41:59 [ampache] (PHP) -> [Runtime Error] require_once(/usr/share/ampache/modules/localplay/xbmc/xbmc.controller.php): failed to open stream: No such file or directory in file /usr/share/ampache/lib/class/localplay.class.php(103)
</pre>
Prior to this, I did run composer.phar. Got the messages regarding guzzle. I'm thinking the current philosophy is to ignore the guzzle warnings. Am I mistaken? Composer returned the following suggestions:
<pre>kriswallsmith/assetic suggests installing twig/twig (Assetic provides the integration with the Twig templating engine)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler)
kriswallsmith/assetic suggests installing leafo/scssphp (Assetic provides the integration with the scssphp SCSS compiler)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed data uris)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass plugin)
kriswallsmith/assetic suggests installing patchwork/jsqueeze (Assetic provides the integration with the JSqueeze JavaScript compressor)
mikealmond/musicbrainz suggests installing guzzle/guzzle (Allows you to use the GuzzleHttpAdapter. You must install one of the supported adapters.)
phpmailer/phpmailer suggests installing league/oauth2-client (Needed for Gmail's XOAUTH2 authentication system)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
react/react suggests installing ext-libevent (Allows for use of a more performant event-loop implementation.)
react/react suggests installing ext-libev (Allows for use of a more performant event-loop implementation.)
react/react suggests installing ext-event (Allows for use of a more performant event-loop implementation.)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
needim/noty suggests installing twbs/bootstrap (~3.0.0)
components/bootstrap suggests installing components/bootstrap-default (Provide a theme for Bootstrap as components/bootstrap only provides the CSS as file assets)
</pre>
Are these suggestions actually requirements?

**Comment by DarylOliver** [comment]
err sorry if this not related but I'm having difficulty with using composer it's says there's no json file then I make one nut I'm unsure how to install the dependences into ampache with composer. Could anyone lend assistance?

**Comment by Afterster** [comment]
@nakinigit composer execution looks fine. There was a mistype on xbmc localplay, should be fixed now.
@DarylOliver you shouldn't have to create a json file, there is one. Be sure you're using develop branch and you are on the correct working directory.

**Comment by Afterster** [comment]
Move to composer added instability for few weeks but the current way shouldn't change anymore now, I will close this. New composer problems should be created on a separate issue now :).
