### ISSUE TITLE
Request exceeded the limit of %d internal redirects due to probable configuration error

### ISSUE THREAD

**Issue by pateretou** [ampache/ampache#960]
I was unable to connect through SUBSonic API.

I had this error in my apache error.log : 

> [Fri Sep 18 15:23:22.022462 2015] [core:error] [pid 3847] [client 198.45.26.30:39657] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

I changed the /rest/.htaccess on my setup to have this working : 

>     RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]

to

>    RewriteRule ^(.+)\.view$ /ampache/rest/index.php?ssaction=$1 [PT,L,QSA]

**Comment by SUTJael** [comment]
Thanks for the tip. There's other discussions in google groups including the same result. Good to know it's working now ;)
