### ISSUE TITLE
UUID for upnp is fixed

### ISSUE THREAD

**Issue by dengste** [ampache/ampache#962]
It is currently not possible to have two Ampache upnp servers in the same network because the UUID is fixed (see UUIDSTR in file upnp_api.class.php). I currently worked around that problem by simply changing it by hand, but the proper way would be that Ampache generates an UUID for each installation.
While it is then possible to have two servers in the same subnet, both will announce themselves with the name 'Ampache', so it would be nice if one could override the 'friendlyName' somewhere in the configuration (again, I worked around that problem by setting it by hand in MediaServerServiceDesc.php).

**Comment by Afterster** [comment]
Indeed it is hard coded. That should have been temporary and remained as usual :smile: .
Fixed on 1446bd22c6432cfae04c71af83d3d60fa0be999a, thanks.

UUID is not derived from host and friendlyName equals your Ampache site title.
