### ISSUE TITLE
Update code

### ISSUE THREAD

**Issue by joshp23** [ampache/ampache#964]
I hope this isn't seen as horrible, I don't know where else to put this request. I am not a strong coder, but I would like to be able to isolate the section of your code that is responsible for handling the updates over git. I want to offer it up to another project, or at least fork it into a personal branch, and I need some help. Please feel free to delete this if it is inappropriately placed.

**Comment by Afterster** [comment]
You will found everything related to auto update here https://github.com/ampache/ampache/blob/develop/lib/class/autoupdate.class.php
See references usage on the project code to know how it is used.
