### ISSUE TITLE
Catalog updates finding differences where there are none

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#969]
I've recently noticed that on catalog updates, Ampache is finding tag differences in files that haven't had changes. In particular, I'm noticing this in the lyric and genre tags.  

For genre tags, it seems to have a problem with mutliple genres (separated by comma).  Single genre tagged files are unaffected.

2015-09-23 04:49:20 [ampache] (tag-read) -> Reading tags from .......\Tonic\Lemon Parade\04 Soldier's Daughter.m4a 
2015-09-23 04:49:22 [ampache] (song-diff) -> {"tags":"OLD:Alternative Rock  Rock  Post-Grunge --> Alternative Rock, Rock, Post-Grunge"} 

For lyrics, not sure what it could be.  I have a lot of lyrics that contain inline hypertext.  Not sure if it's having a problem with some of those characters as a result.  

If a file will help, happy to supply one.

**Comment by Afterster** [comment]
Fixed for genres. Could you send me a test file to afterster@gmail.com for the lyrics issue? Thanks.

**Comment by JoeDat** [comment]
This issue may actually be fixed as well.  Not sure if getid3() was 
updated or not, but when re-writing my tags (using beets, same exact tag 
info), the issue is consistently clearing up on previously broken 
examples.  I'm going to keep testing and will let you know with a final 
answer soon.
