### ISSUE TITLE
Multiple genres on a song are treated as one tag

### ISSUE THREAD

**Issue by JoeDat** [ampache/ampache#970]
Noticed that if songs are tagged with multiple genres, separated by a comma, the Tag Cloud treats the entry as one tag, rather than separating it out.  The genre links on the titles are also treated a single genre / link.

![image](https://cloud.githubusercontent.com/assets/8648894/10057097/8662873a-620c-11e5-8996-68791dafd201.png)

**Comment by Afterster** [comment]
Is `additional_genre_delimiters` setting configured on your ampache.cfg.php config file?

**Comment by JoeDat** [comment]
Yes it is.

; Some taggers use delimiters other than \0 for fields
; This list specifies possible delimiters additional to \0
; This setting takes a regex pattern.
; DEFAULT: // / \ | , ;
additional_genre_delimiters = "[/]{2}|[/|\|\|,|;]"

Default settings.

**Comment by JoeDat** [comment]
I've figured out the true difference.  It's not recognizing multiple genres for AAC files.  MP3s are fine. So, it has nothing to do with the delimiter at all.  It's the file format.

**Comment by Afterster** [comment]
Mhh ok thanks for the investigation. Could you make the test with [getid3](https://github.com/JamesHeinrich/getID3) directly and  related demo.browse.php? Looks like another getid3 bug. Thanks.

**Comment by JoeDat** [comment]
On a test with demo.browse.php, I do get warnings for every AAC file against an artist where I have both mp3 and AAC files.  I can't decipher, so unsure if it's related, but they are all similar to the following:
![image](https://cloud.githubusercontent.com/assets/8648894/10085185/aac49428-62d5-11e5-9dc3-d7b6f1312d69.png)

As for the file details, the fields themselves look similar.  Granted, I've never run this before, so I'm not quite sure what I'm seeing.  If you want to see the output, I can export and provide it privately.

**Comment by JoeDat** [comment]
I'm in the middle of rebuilding my server, but will test out as soon as I get it back up and running.

**Comment by apastuszak** [comment]
Sounds like you're reading MPs Atoms instead of ID3 tags.

**Comment by Afterster** [comment]
Should be fixed now.
