### ISSUE TITLE
Search results can't be added to the current playlist and other.

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#972]
Hey guys,

if I search for something and want to add the results as a playlist, via the button under 'options', nothing happens, no loading, nothing.
The same, if I try to add any of the results to the current playlist (play next, play last) or play them directly.

The right buttons (download, post shout and so on) are working.

:-)

**Comment by Afterster** [comment]
Variant of #903.

**Comment by mitchray** [comment]
Appears to be working as of 4.4.1, closing due to time since last discussion
