### ISSUE TITLE
unable to play some album/song when other work fine on the web player

### ISSUE THREAD

**Issue by Pirokio** [ampache/ampache#973]
Hello,

I've faced to a problem on my ampache after uptdate him last night. The update work fine, git pull ok composer ok ect... but when I try to play song from the webplayer the icon instantly passed on pause, no song is played.

When i digg on my apache error.log I can see this message:

PHP Fatal error:  Call to a member function prepare_media() on a non-object in /var/www/ampache/play/index.php on line 328

In other album/song, the player just work fine, no error on apache error.log, i don't know why this is happen, the song on my directory have all the same rights, i've try to make apt-get upgrade off all my package, including php but that didn't solve the probleme.

I'm stuck with this error, force me to listen only a few songs...

I'm sorry for my bad english, i'm not a native english and i hope my issue was clear for you! Don't hesitate to ask for precision if needed.

Best regards,

Pirokio

**Comment by Afterster** [comment]
Please enable Ampache logs too and sent it here. Thanks.

**Comment by Pirokio** [comment]
Hi! thanks for reply

when debug on 1 (error logging) nothing apear to be logged

when i hit play with debug at 5:

2015-09-27 12:19:07 [ampache] (play) -> Asked for type {song}
2015-09-27 12:19:07 [pirokio] (session) -> ea7303c0f22a21684c7486bf34e83b53 has been extended to Sun, 27 Sep 2015 14:19:07 +0200 extension length 7200
2015-09-27 12:19:07 [pirokio] (session) -> tr2cru6rpndu30mp7t2si4psg2 has been extended to Sun, 27 Sep 2015 13:19:07 +0200 extension length 3600
2015-09-27 12:19:07 [pirokio] (ajax.server.php) -> Called for page: {song}
2015-09-27 12:19:07 [pirokio] (session) -> tr2cru6rpndu30mp7t2si4psg2 has been extended to Sun, 27 Sep 2015 13:19:07 +0200 extension length 3600
2015-09-27 12:19:07 [pirokio] (ajax.server.php) -> Called for page: {}

**Comment by Pirokio** [comment]
Hello,

Today, I've tested to switch ampache on a 3.7.0 and the songs who don't want to play, works fine...

I've reinstalled 3.8.0 with git and composer, but the situation is the same, certain song refuse to play... it's definitly not a files problem and the problem come with recent update (3 or 4 days ago)...

Hope i'm not the only one with this probleme and hope you will find the cause and help me to resolve it!

Best regards,

Pirokio

**Comment by Afterster** [comment]
Few people reported an issue when using latest changes on lastfm plugins, see #952. Do you have lastfm plug-in enabled?

**Comment by Afterster** [comment]
I believe this is fixed now. Feel free to comment otherwise.
