### ISSUE TITLE
Add Support for Disc Subtitle in Web UI

### ISSUE THREAD

**Issue by apastuszak** [ampache/ampache#976]
MusicBrainz writes a tag for Disc Subtitle, which is extremely useful for boxed sets that are compilations of albums by an artists.

In the Web UI right now you will see (using Rush as an Example):

```Studio Albums 1989-2007 , Disk 1```
It would ne nice if it said ```Studio Albums 1989-2007 , Disk 1 - Presto``` or

```Studio Albums 1989-2007 , Disk 1``` on one line and ```Presto``` on the line underneath it.

**Comment by Afterster** [comment]
Duplicate with #687, also created by you btw...
