### ISSUE TITLE
how to hide localplay icon the left menu

### ISSUE THREAD

**Issue by tristan-k** [ampache/ampache#977]
I completely disabled the localplay features and now the localplay button on the left menu is useless. In fact it is irrtating for some users. Is there a way to hide that icon?

**Comment by Afterster** [comment]
If *allow_localplay_playback* (Allow Localplay Play) setting is disabled, the localplay button should disappears.

**Comment by tristan-k** [comment]
It is disabled. Still the icon is there.

![selection_027](https://cloud.githubusercontent.com/assets/732025/10233129/01f87da6-688d-11e5-9cf5-a81b38b595c7.png)

**Comment by Afterster** [comment]
Well this should be available this 3.8.0, and you can see the line here https://github.com/ampache/ampache/blob/develop/templates/sidebar.inc.php#L34

**Comment by tristan-k** [comment]
Oh, I see. Then it is my fault. I'm using version 3.7 because of a [subsonic api issue](https://github.com/ampache/ampache/issues/974#issuecomment-143572322). I will close this one.
