### ISSUE TITLE
Add rule in advanced search not doing anything

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#980]
I'm trying to do an advanced search of songs and I cannot add any rules as the Add Another Rule button doesn't do anything.
![image](https://cloud.githubusercontent.com/assets/4076671/10243140/81ee8924-68c4-11e5-9b7d-e0e92476b817.png)

Using build c86327176eeeb713e0c1369bf257d654bfdf16be

**Comment by Psy-Virus** [comment]
:+1:
