### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by daeavelwyn** [ampache/ampache#982]
Hi,
I'd like to suggest to add this line : mv composer.phar /usr/local/bin/composer
while the error message " This tests whether Ampache dependencies are installed.
Please download and install Composer from http://getcomposer.org then run `composer install --prefer-source --no-interaction` on Ampache directory." is displayed.
I could be : 
" This tests whether Ampache dependencies are installed.
Please download Composer from http://getcomposer.org and install it (e.g: mv composer.phar /usr/local/bin/composer) then run `composer install --prefer-source --no-interaction` on Ampache directory."

**Comment by Afterster** [comment]
Indeed, better if installed globally if you're using auto-update ^^. Changed, thanks (don't hesitate to PR even for small changes btw).

**Comment by daeavelwyn** [comment]
:)
