### ISSUE TITLE
Question(s) about the Ampache code (formatting) itself

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache#984]
Hey @Afterster,

I know Googlegroups is for discussions and questions but here I've a preview button, inline code and better syntax highlighting. I hope you can forgive me. ^^

My question(s):
Is there a reason why there are sometimes so many php open and close tags? For example the `templates/show_song_row.inc.php`; everything between the `<div class="cel_play_hover">...</div>` (lines 27-48)

(Example 1 (copied and pasted as is))
```php
    <?php if (AmpConfig::get('directplay')) {
    ?>
        <?php echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id, 'play', T_('Play'), 'play_song_' . $libitem->id);
    ?>
        <?php if (Stream_Playlist::check_autoplay_append()) {
    ?>
            <?php echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id . '&append=true', 'play_add', T_('Play last'), 'addplay_song_' . $libitem->id);
    ?>
        <?php 
}
    ?>
        <?php if (Stream_Playlist::check_autoplay_next()) {
    ?>
            <?php echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id . '&playnext=true', 'play_next', T_('Play next'), 'nextplay_song_' . $libitem->id);
    ?>
        <?php 
}
    ?>
    <?php 
} ?>
```
it looks really ugly and at least for me it's irritating, not only the huge amount of php tags, also the formatting.
I think the formatting came through the new php-cs script version, right?
Is it possible to change it a little bit (the options), so that it is more like:

```php
<?php
    if bla bla bla
?>
<?php
    echo bla bla bla
?>
```
contrary to
```php
<?php if bla bla bla
?>
<?php echo bla bla bla
?>
```
Sure, the first way has more lines, but it looks cleaner and less chaotic in general.

Second, the php tags:

As you can see in "Example 1", there are many php tags at least in this lines. Maybe I am wrong because of less knowledge, but on my side it works the same way, if I rewrite it that way:

```php
<?php 
    if (AmpConfig::get('directplay')) {
        echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id, 'play', T_('Play'), 'play_song_' . $libitem->id);
    if (Stream_Playlist::check_autoplay_next()) {
        echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id . '&playnext=true', 'play_next', T_('Play next'), 'nextplay_song_' . $libitem->id);
    if (Stream_Playlist::check_autoplay_append()) {
        echo Ajax::button('?page=stream&action=directplay&object_type=song&object_id=' . $libitem->id . '&append=true', 'play_add', T_('Play last'), 'addplay_song_' . $libitem->id);
            }
        }
    }
?>
```
Less lines and muuuuuch cleaner code, isn't it?

I stumbled over it, because I do not like the order of the play(list) actions on song/abum/artist/video rows (now: play | play last | play next) - it's simply wrong :laughing: It's like reading the first page of a book, then the last and then the second^^ (I'll create a PR for it after you've answered)

So, what do you think?

:-)

**Comment by Afterster** [comment]
You're right here. I agree with your recommended changes. For unique lines we could also put everything on one line like
```php
<?php if bla bla bla ?>
```
but php-cs-fixer tool argument lines should be corrected (I don't know the excepted one here).
I think the reason is historical and because of several copy/past between templates... better to avoid consecutive php open/close tags of course :).

**Comment by Psy-Virus** [comment]
Great :-)

I did some searching and found also other Code Style fixers like [>this "CodeSniffer" here<](https://github.com/squizlabs/PHP_CodeSniffer). It also seems to be quite popular. Maybe you want to take a look.

I also read the options for sensiolabs cs-fixer. But honestly I don't get it completely and for me it looks like it is not that much customizable. Also, every preset I've used, like this PSR-1/2, it leaves the code as ugly as it is.^^ Maybe a bug on the script or not, but I can't determine that.

Well, as I had written before, I'll create a PR, If you see that something on the formatting have to be done manually, don't hesitate to ask me for help; if I can, I'll do it. :-)

**Comment by Afterster** [comment]
I think we can keep the current fixer, we just need to code differently.
 * When doing a condition, we shouldn't write it
```php
<?php if ($var === 'test') { ?>
```
but
```php
<?php
if ($var === 'test') {
?>
```
 * When doing an one line echo we should not add trailing semi-colon to avoid new line break by the fixer
```php
<?php echo "test"; ?>
```
but
```php
<?php echo "test" ?>
```
The other solution would be to use `<?=` shortcut for `<?php echo` but even if it was enabled by default since php5.4, I'm not sure about his long term use.
