### ISSUE TITLE
Doing a video catalog update error

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#985]
I'm doing an update of my video catalog, I'm seeing the following error in the debug logs. 

2015-10-09 06:57:51 [ampache] (tag-read) -> Reading tags from /home/steve/Media/anime/Viewed/Naruto OVA 7/[Hatsuyuki]_Naruto_OVA_-_07_-_Naruto_Soyokazeden_[DVD_1024x554_x264_AC3_5.1][2B5DCFCA].mkv 
2015-10-09 06:57:51 [ampache] (vainfo) -> Unable to determine file type from h264 on file /home/steve/Media/anime/Viewed/Naruto OVA 7/[Hatsuyuki]_Naruto_OVA_-_07_-_Naruto_Soyokazeden_[DVD_1024x554_x264_AC3_5.1][2B5DCFCA].mkv 
2015-10-09 06:57:51 [ampache] (vainfo) -> Cleaning matroska 
2015-10-09 06:57:51 [ampache] (PHP) -> [Strict Error] call_user_func() expects parameter 1 to be a valid callback, non-static method Catalog::update_video_from_tags() should not be called statically in file /usr/share/ampache/stebe-git/ampache/lib/class/catalog.class.php(1452)

**Comment by wagnered** [comment]
I'm working with 3.8.1-develop and it looks like the function,
update_video_from_tags hasn't been implemented yet. But there still
seems to be a problem with the code.

I an curious though, as you are updating the video files from tags, I
was wondering what type of video files you are updating (mp4's?) and
what you are using to edit the tags?  The reason I asked is that I'm
trying to learn what mp4 editors are available and how they compare.

Thanks,

Ernie D

On 10/09/2015 03:55 AM, stebe wrote:
> I'm doing an update of my video catalog, I'm seeing the following error
> in the debug logs.
> 
> 2015-10-09 06:52:07 ampache <PHP> -> [Strict Error] call_user_func()
> expects parameter 1 to be a valid callback, non-static method
> Catalog::update_video_from_tags() should not be called statically in
> file /usr/share/ampache/stebe-git/ampache/lib/class/catalog.class.php(1452)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/985>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by stebe** [comment]
Actually I wasn't updating any tags.  I just ran the update of all catalogs and one of the video catalogs was included. These are all files I've downloaded over the years. I was getting the error with all formats mkv, avi, mpg etc. Any tags they had was already there.

**Comment by wagnered** [comment]
@stebe,

Thanks for the info and reporting the issue.

@Afterster,  is it OK to change "update_video_from_tags" to a static
function, and add it to my PR?

On 10/09/2015 04:49 PM, stebe wrote:
> Actually I wasn't updating any tags. I just ran the update of all
> catalogs and one of the video catalogs was included. These are all files
> I've downloaded over the years. I was getting the error with all formats
> mkv, avi, mpg etc. Any tags they had was already there.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/985#issuecomment-147012712>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Yes indeed, this method should be static. You can handle it @wagnered if you want. Thanks.

**Comment by Afterster** [comment]
Fixed.
