### ISSUE TITLE
Tags on FLAC & OGG files

### ISSUE THREAD

**Issue by ciroiriarte** [ampache/ampache#986]
Hi!, found that MP3 comments are included in the song attributes, but OGG file comments are not. At first I thought it was because I generate the files with multiple comment tags (oggenc file.wav --comment foo --comment bar ...) , but generating a new file with just one comment tag I get the same result.

Also, FLAC files don't show additional/custom tags.

**Comment by Afterster** [comment]
Custom tags will not be supported as long #664 is not merged.
About the comment issue on flac/ogg, could you try directly with getid3 (https://github.com/JamesHeinrich/getID3) examples and see if it is read correctly as a comment tag? If it is then please send me a test file to afterster@gmail.com. Thanks.

**Comment by ciroiriarte** [comment]
Ok, in the case of FLAC they're all custom tags,so I thing I should wait for the merge. For the OGG file the tag is "vorbiscomment", which is an array. I'll send you demo files..

**Comment by Afterster** [comment]
It is merged now. Feel free to test it :)
