### ISSUE TITLE
Move cover art out of database

### ISSUE THREAD

**Issue by ajmas** [ampache/ampache#992]
It may be better to store the cover art outside of the database, on the file system? This approach is typical in CMS systems, to avoid complications around BLOBs.

As part of this work the album art could exist in both original form and scaled form. This would help reduce network overhead, when the full resolution is not needed. Something like:

   * cache/album-art/original/album/
   * cache/album-art/256x256/album/...
   * cache/album-art/original/track/...
   * cache/album-art/256x256/track/...

Note, that the size issue, regarding the database, is listed as a limitation in the FAQ: https://github.com/ampache/ampache/wiki/FAQ

**Comment by Afterster** [comment]
This in fact was added this year (I updated the wiki, thanks). See `album_art_store_disk` setting.
