### ISSUE TITLE
Zero length image files

### ISSUE THREAD

**Issue by ajmas** [ampache/ampache#993]
The album covers coming back as zero length responses:

http://ampache.local/ampache/image.php?thumb=1&object_id=14&object_type=album

This is running on Raspbian, with Apache2 and HEAD from Git repo

    album_art_store_disk = "true"
    local_metadata_dir = "/var/tmp/ampache/metadata"

**Comment by Afterster** [comment]
After changing the setting to album_art_store_disk, you should run album art gathering on your catalog again.

**Comment by Afterster** [comment]
Closing this as the setting should be the solution. Please comment if it is not.

**Comment by ajmas** [comment]
It did solve the issue, but though I do notice images aren't there for all albums. Are the images extracted in a separate phase to MP4 file metadata?
