### ISSUE TITLE
Updating album art does not work

### ISSUE THREAD

**Issue by gnujeremie** [ampache/ampache#996]
Selecting a new album art does not change the said album art.

No error message, it just comes back to the previous screen, with the old (default) album art.

**Comment by gnujeremie** [comment]
Ok so it seems it works, but, you have to refresh the page to see the change.

**Comment by Afterster** [comment]
Since the move to ajax page loading, this is the excepted behavior related to how the browser cache is handled with ajax.

**Comment by EvilLivesHere** [comment]
Is there an expected improvement in the future to invalidate the browser's cache for an old album cover after an update?  I would certainly vote in favor of that improvement, if possible.  I always feel the need to navigate to and manually refresh the page after updating an album cover to make sure the image was processed correctly.

**Comment by Afterster** [comment]
As it is the excepted browser behavior, any suggestion is welcomed :)
